import type { QBQuestion } from '@/lib/question-bank/types'

export const mathQuestionsB1: QBQuestion[] = [
  // ─── Algebra: Linear Equations in One Variable ───────────────────────────

  {
    id: 'math-alg-le1-013',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Equations in One Variable',
    difficulty: 'easy',
    timeTargetSeconds: 75,
    mistakeType: 'careless',
    questionType: 'multiple_choice',
    question: 'If 5x − 3 = 22, what is the value of x?',
    choices: [
      { label: 'A', text: '3' },
      { label: 'B', text: '4' },
      { label: 'C', text: '5' },
      { label: 'D', text: '6' },
    ],
    correctAnswer: 'C',
    explanation: 'Add 3 to both sides: 5x = 25. Divide by 5: x = 5.',
    wrongAnswerExplanations: {
      A: 'x = 3 gives 5(3) − 3 = 12 ≠ 22. Incorrect — check arithmetic.',
      B: 'x = 4 gives 5(4) − 3 = 17 ≠ 22. Incorrect — you may have added 3 then divided by 4 instead of 5.',
      D: 'x = 6 gives 5(6) − 3 = 27 ≠ 22. Incorrect — you may have added 3 incorrectly or divided wrong.',
    },
    teachingPoint: 'Isolate the variable by undoing each operation in reverse: first add or subtract the constant, then divide by the coefficient.',
    relatedSkills: ['Linear Functions'],
    isWordProblem: false,
  },

  {
    id: 'math-alg-le1-014',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Equations in One Variable',
    difficulty: 'easy',
    timeTargetSeconds: 75,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'A bookstore sells notebooks for $3 each. Maria buys only notebooks and spends exactly $18. How many notebooks did she buy?',
    choices: [
      { label: 'A', text: '4' },
      { label: 'B', text: '5' },
      { label: 'C', text: '6' },
      { label: 'D', text: '9' },
    ],
    correctAnswer: 'C',
    explanation: 'Let n = number of notebooks. 3n = 18, so n = 6.',
    wrongAnswerExplanations: {
      A: '4 notebooks cost $12, not $18.',
      B: '5 notebooks cost $15, not $18.',
      D: '$18 ÷ $2 = 9; this uses the wrong price per notebook.',
    },
    teachingPoint: 'Write a simple equation from the context, then divide the total by the per-unit cost.',
    relatedSkills: ['Linear Functions'],
    isWordProblem: true,
  },

  {
    id: 'math-alg-le1-015',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Equations in One Variable',
    difficulty: 'medium',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'If (3/4)x + 5 = (1/2)x + 11, what is the value of x?',
    choices: [
      { label: 'A', text: '16' },
      { label: 'B', text: '20' },
      { label: 'C', text: '24' },
      { label: 'D', text: '32' },
    ],
    correctAnswer: 'C',
    explanation: 'Multiply every term by 4 to clear fractions: 3x + 20 = 2x + 44. Subtract 2x from both sides: x + 20 = 44. Subtract 20: x = 24.',
    wrongAnswerExplanations: {
      A: 'x = 16 gives (3/4)(16) + 5 = 17 and (1/2)(16) + 11 = 19. Not equal.',
      B: 'x = 20 gives (3/4)(20) + 5 = 20 and (1/2)(20) + 11 = 21. Not equal.',
      D: 'x = 32 gives (3/4)(32) + 5 = 29 and (1/2)(32) + 11 = 27. Not equal — likely from a fraction subtraction error.',
    },
    teachingPoint: 'Clear fractions by multiplying all terms by the LCD before solving. Then use standard inverse operations.',
    relatedSkills: ['Linear Functions'],
    isWordProblem: false,
  },

  {
    id: 'math-alg-le1-016',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Equations in One Variable',
    difficulty: 'medium',
    timeTargetSeconds: 90,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    question: 'A gym charges a $40 enrollment fee plus $25 per month. A competing gym charges no enrollment fee but $35 per month. After how many months will the total cost at both gyms be equal?',
    choices: [
      { label: 'A', text: '2' },
      { label: 'B', text: '4' },
      { label: 'C', text: '5' },
      { label: 'D', text: '8' },
    ],
    correctAnswer: 'B',
    explanation: 'Set the costs equal: 40 + 25m = 35m. Subtract 25m from both sides: 40 = 10m. Divide by 10: m = 4.',
    wrongAnswerExplanations: {
      A: '2 months: 40 + 25(2) = 90 vs. 35(2) = 70. Not equal.',
      C: '5 months: 40 + 25(5) = 165 vs. 35(5) = 175. Not equal.',
      D: '8 months: 40 + 25(8) = 240 vs. 35(8) = 280. Not equal. A common trap is dividing $40 by $25 (the monthly rate) instead of the rate difference of $10.',
    },
    teachingPoint: 'Set the two cost expressions equal and solve. The enrollment fee shifts one expression up by a constant amount.',
    relatedSkills: ['Systems of Two Linear Equations in Two Variables'],
    isWordProblem: true,
  },

  {
    id: 'math-alg-le1-017',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Equations in One Variable',
    difficulty: 'medium',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'grid_in',
    question: 'If 2(3x − 4) = 5x + 6, what is the value of x?',
    correctAnswer: '14',
    acceptableAnswers: ['14'],
    explanation: 'Distribute: 6x − 8 = 5x + 6. Subtract 5x from both sides: x − 8 = 6. Add 8: x = 14.',
    teachingPoint: 'Distribute first to remove parentheses, then collect like terms on each side before isolating the variable.',
    relatedSkills: ['Linear Functions'],
    isWordProblem: false,
  },

  {
    id: 'math-alg-le1-018',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Equations in One Variable',
    difficulty: 'hard',
    timeTargetSeconds: 120,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'For what value of k does the equation 3(x − 2) + kx = 5x − 6 have infinitely many solutions?',
    choices: [
      { label: 'A', text: '0' },
      { label: 'B', text: '2' },
      { label: 'C', text: '3' },
      { label: 'D', text: '5' },
    ],
    correctAnswer: 'B',
    explanation: 'Expand the left side: 3x − 6 + kx = 5x − 6. Combine like terms: (3 + k)x − 6 = 5x − 6. For infinitely many solutions, both sides must be identical: 3 + k = 5, so k = 2. The constants already match (−6 = −6).',
    wrongAnswerExplanations: {
      A: 'k = 0 gives 3x − 6 = 5x − 6, so −2x = 0, meaning x = 0 — one solution, not infinitely many.',
      C: 'k = 3 gives 6x − 6 = 5x − 6, so x = 0 — one solution.',
      D: 'k = 5 gives 8x − 6 = 5x − 6, so 3x = 0, meaning x = 0 — one solution.',
    },
    teachingPoint: 'For infinitely many solutions, both the coefficients of x and the constants must be identical on both sides after simplification.',
    relatedSkills: ['Linear Functions'],
    isWordProblem: false,
  },

  // ─── Algebra: Linear Equations in Two Variables ──────────────────────────

  {
    id: 'math-alg-le2-010',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Equations in Two Variables',
    difficulty: 'easy',
    timeTargetSeconds: 75,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'A line passes through the points (0, 4) and (2, 10). Which of the following is the equation of this line?',
    choices: [
      { label: 'A', text: 'y = 2x + 4' },
      { label: 'B', text: 'y = 3x + 4' },
      { label: 'C', text: 'y = 4x + 2' },
      { label: 'D', text: 'y = 6x + 4' },
    ],
    correctAnswer: 'B',
    explanation: 'The y-intercept is 4 (from the point (0, 4)). Slope = (10 − 4)/(2 − 0) = 6/2 = 3. Equation: y = 3x + 4.',
    wrongAnswerExplanations: {
      A: 'Slope of 2 is incorrect. Rise = 6, run = 2, so slope = 3, not 2.',
      C: 'Slope 4 and y-intercept 2 are both wrong. The y-intercept is 4 since the line crosses (0, 4).',
      D: 'Slope 6 is the rise, not the slope (rise divided by run = 6/2 = 3).',
    },
    teachingPoint: 'Use slope = (y2 − y1)/(x2 − x1). The y-intercept can be read directly from the point where x = 0.',
    relatedSkills: ['Linear Functions'],
    isWordProblem: false,
  },

  {
    id: 'math-alg-le2-011',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Equations in Two Variables',
    difficulty: 'medium',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'Line l has a slope of −2 and passes through the point (3, 1). What is the y-intercept of line l?',
    choices: [
      { label: 'A', text: '5' },
      { label: 'B', text: '7' },
      { label: 'C', text: '−5' },
      { label: 'D', text: '−7' },
    ],
    correctAnswer: 'B',
    explanation: 'Using point-slope form: y − 1 = −2(x − 3). Expand: y − 1 = −2x + 6. Add 1 to both sides: y = −2x + 7. The y-intercept is 7.',
    wrongAnswerExplanations: {
      A: 'y-intercept of 5 comes from computing 1 + 4 = 5 (substituting incorrectly).',
      C: 'A sign error: computing 1 + (−2)(3) = 1 − 6 = −5 instead of correctly rearranging point-slope form.',
      D: 'Computing −2(3) − 1 = −7 is a sign error in rearranging the point-slope equation.',
    },
    teachingPoint: 'Use point-slope form y − y1 = m(x − x1), then solve for y to get slope-intercept form.',
    relatedSkills: ['Linear Functions'],
    isWordProblem: false,
  },

  {
    id: 'math-alg-le2-012',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Equations in Two Variables',
    difficulty: 'medium',
    timeTargetSeconds: 90,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    question: 'A car rental company charges $50 per day plus $0.20 per mile driven. A customer rents a car for 3 days and drives m miles. Which equation represents the total cost C, in dollars?',
    choices: [
      { label: 'A', text: 'C = 0.20m + 50' },
      { label: 'B', text: 'C = 0.20m + 150' },
      { label: 'C', text: 'C = 3m + 50' },
      { label: 'D', text: 'C = 0.60m + 150' },
    ],
    correctAnswer: 'B',
    explanation: 'The daily fee for 3 days is 3 × $50 = $150. The per-mile charge is $0.20 per mile. Total: C = 0.20m + 150.',
    wrongAnswerExplanations: {
      A: 'This uses only 1 day of the flat fee ($50), not 3 days ($150).',
      C: 'This uses $3 per mile instead of $0.20, and only $50 for the fixed fee rather than $150.',
      D: 'Multiplying the per-mile rate by the number of days ($0.20 × 3 = $0.60) is incorrect — the per-mile rate does not change with the number of days.',
    },
    teachingPoint: 'Multiply the per-day rate by the number of days for the fixed portion. The per-mile rate stays constant regardless of days.',
    relatedSkills: ['Linear Functions'],
    isWordProblem: true,
  },

  {
    id: 'math-alg-le2-013',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Equations in Two Variables',
    difficulty: 'medium',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'grid_in',
    question: 'A line in the xy-plane has x-intercept 6 and y-intercept −4. What is the slope of this line?',
    correctAnswer: '2/3',
    acceptableAnswers: ['2/3', '.667', '0.667', '.6667', '0.6667'],
    explanation: 'The line passes through (6, 0) and (0, −4). Slope = (0 − (−4))/(6 − 0) = 4/6 = 2/3.',
    teachingPoint: 'The x-intercept gives the point (a, 0) and the y-intercept gives (0, b). Use these two points to compute the slope.',
    relatedSkills: ['Linear Functions'],
    isWordProblem: false,
  },

  {
    id: 'math-alg-le2-014',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Equations in Two Variables',
    difficulty: 'hard',
    timeTargetSeconds: 120,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'In the xy-plane, line p is perpendicular to the line 4x − 3y = 12 and passes through (−3, 2). Which of the following is the equation of line p?',
    choices: [
      { label: 'A', text: 'y = (4/3)x + 6' },
      { label: 'B', text: 'y = −(3/4)x − (1/4)' },
      { label: 'C', text: 'y = (3/4)x + (17/4)' },
      { label: 'D', text: 'y = −(4/3)x + (14/3)' },
    ],
    correctAnswer: 'B',
    explanation: 'Rewrite 4x − 3y = 12 as y = (4/3)x − 4; slope = 4/3. The perpendicular slope is the negative reciprocal: −3/4. Using point-slope form with (−3, 2): y − 2 = −(3/4)(x + 3). Expand: y − 2 = −(3/4)x − 9/4. Add 2 (= 8/4): y = −(3/4)x − 9/4 + 8/4 = −(3/4)x − 1/4.',
    wrongAnswerExplanations: {
      A: 'This line has slope 4/3, the same as the original line — it is parallel, not perpendicular.',
      C: 'This uses slope 3/4 instead of −3/4 (missing the negative sign in the negative reciprocal).',
      D: 'This uses the negative of the original slope (−4/3) instead of the correct negative reciprocal (−3/4).',
    },
    teachingPoint: 'Perpendicular lines have slopes that are negative reciprocals. If the original slope is m, the perpendicular slope is −1/m.',
    relatedSkills: ['Linear Functions'],
    isWordProblem: false,
  },

  // ─── Algebra: Systems of Two Linear Equations in Two Variables ───────────

  {
    id: 'math-alg-sys-009',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Systems of Two Linear Equations in Two Variables',
    difficulty: 'easy',
    timeTargetSeconds: 75,
    mistakeType: 'careless',
    questionType: 'multiple_choice',
    question: 'What is the value of x in the solution to the following system?\n2x + y = 10\nx − y = 2',
    choices: [
      { label: 'A', text: '2' },
      { label: 'B', text: '3' },
      { label: 'C', text: '4' },
      { label: 'D', text: '6' },
    ],
    correctAnswer: 'C',
    explanation: 'Add the two equations: (2x + y) + (x − y) = 10 + 2, giving 3x = 12, so x = 4.',
    wrongAnswerExplanations: {
      A: 'x = 2: check 2(2) + y = 10 gives y = 6; x − y = 2 − 6 = −4 ≠ 2. Incorrect.',
      B: 'x = 3 gives 3x = 9 from addition, not 12. Arithmetic error.',
      D: 'x = 6 gives 3x = 18, but adding the equations gives 3x = 12.',
    },
    teachingPoint: 'When y-terms cancel by addition (y + (−y) = 0), add the equations directly to eliminate y and solve for x.',
    relatedSkills: ['Linear Equations in Two Variables'],
    isWordProblem: false,
  },

  {
    id: 'math-alg-sys-010',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Systems of Two Linear Equations in Two Variables',
    difficulty: 'medium',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'A store sells small and large candles. Small candles cost $4 each and large candles cost $9 each. A customer buys a total of 8 candles and spends $52. How many large candles did the customer buy?',
    choices: [
      { label: 'A', text: '2' },
      { label: 'B', text: '3' },
      { label: 'C', text: '4' },
      { label: 'D', text: '5' },
    ],
    correctAnswer: 'C',
    explanation: 'Let s = small candles, L = large candles. System: s + L = 8 and 4s + 9L = 52. From the first equation, s = 8 − L. Substitute: 4(8 − L) + 9L = 52 → 32 − 4L + 9L = 52 → 5L = 20 → L = 4.',
    wrongAnswerExplanations: {
      A: '2 large candles: 4(6) + 9(2) = 24 + 18 = 42 ≠ 52.',
      B: '3 large candles: 4(5) + 9(3) = 20 + 27 = 47 ≠ 52.',
      D: '5 large candles: 4(3) + 9(5) = 12 + 45 = 57 ≠ 52.',
    },
    teachingPoint: 'Write two equations from the problem (one for count, one for cost). Use substitution to reduce to one equation in one variable.',
    relatedSkills: ['Linear Equations in One Variable'],
    isWordProblem: true,
  },

  {
    id: 'math-alg-sys-011',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Systems of Two Linear Equations in Two Variables',
    difficulty: 'medium',
    timeTargetSeconds: 90,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    question: 'What is the value of y in the solution to the system?\n3x − 2y = 22\nx + 2y = 2',
    choices: [
      { label: 'A', text: '−2' },
      { label: 'B', text: '1' },
      { label: 'C', text: '2' },
      { label: 'D', text: '4' },
    ],
    correctAnswer: 'A',
    explanation: 'Add the equations to eliminate y: (3x − 2y) + (x + 2y) = 22 + 2 → 4x = 24 → x = 6. Substitute into x + 2y = 2: 6 + 2y = 2 → 2y = −4 → y = −2. Trap: students who stop after finding x = 6 may choose a distractor. The question asks for y.',
    wrongAnswerExplanations: {
      B: 'y = 1: check x + 2(1) = 2, so x = 0; then 3(0) − 2(1) = −2 ≠ 22.',
      C: 'y = 2: check x + 4 = 2, so x = −2; then 3(−2) − 2(2) = −10 ≠ 22.',
      D: 'y = 4: check x + 8 = 2, so x = −6; then 3(−6) − 2(4) = −26 ≠ 22.',
    },
    teachingPoint: 'When y-coefficients are opposites (+2y and −2y), add the equations to eliminate y immediately. Then back-substitute to find y — do not stop after finding x.',
    relatedSkills: ['Linear Equations in Two Variables'],
    isWordProblem: false,
  },

  {
    id: 'math-alg-sys-012',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Systems of Two Linear Equations in Two Variables',
    difficulty: 'medium',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'grid_in',
    question: 'A system of two linear equations has solution (p, q). If 2p + q = 13 and p − q = 2, what is the value of p + q?',
    correctAnswer: '8',
    acceptableAnswers: ['8'],
    explanation: 'Add the equations: 3p = 15, so p = 5. Substitute into p − q = 2: 5 − q = 2, so q = 3. Verify: 2(5) + 3 = 13 and 5 − 3 = 2. Both check out. Therefore p + q = 5 + 3 = 8.',
    teachingPoint: 'After finding p and q individually, compute the requested expression p + q directly. Do not assume p + q can be found without solving the system first.',
    relatedSkills: ['Linear Equations in Two Variables'],
    isWordProblem: false,
  },

  {
    id: 'math-alg-sys-013',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Systems of Two Linear Equations in Two Variables',
    difficulty: 'hard',
    timeTargetSeconds: 120,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'For what value of k does the system below have no solution?\n2x − 4y = 6\nkx − 6y = 12',
    choices: [
      { label: 'A', text: '2' },
      { label: 'B', text: '3' },
      { label: 'C', text: '4' },
      { label: 'D', text: '6' },
    ],
    correctAnswer: 'B',
    explanation: 'A system has no solution when the lines are parallel: same slopes, different y-intercepts. Rewrite the first equation: 2x − 4y = 6 → y = (1/2)x − (3/2); slope = 1/2. Rewrite the second: kx − 6y = 12 → y = (k/6)x − 2; slope = k/6. For parallel lines: k/6 = 1/2 → k = 3. Check that the y-intercepts differ: first has −3/2, second has −2. Since −3/2 ≠ −2, the lines are parallel (not identical) when k = 3. No solution.',
    wrongAnswerExplanations: {
      A: 'k = 2: slope of second line is 2/6 = 1/3 ≠ 1/2. Lines intersect at one point.',
      C: 'k = 4: slope of second line is 4/6 = 2/3 ≠ 1/2. Lines intersect at one point.',
      D: 'k = 6: slope of second line is 6/6 = 1 ≠ 1/2. Lines intersect at one point.',
    },
    teachingPoint: 'A system has no solution when lines are parallel: slope ratios are equal but the lines are not identical. Verify that the constant ratio differs from the coefficient ratio.',
    relatedSkills: ['Linear Equations in Two Variables'],
    isWordProblem: false,
  },

  // ─── Algebra: Linear Inequalities in One or Two Variables ────────────────

  {
    id: 'math-alg-ineq-007',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Inequalities in One or Two Variables',
    difficulty: 'easy',
    timeTargetSeconds: 75,
    mistakeType: 'careless',
    questionType: 'multiple_choice',
    question: 'Which of the following values of x satisfies 3x − 7 > 8?',
    choices: [
      { label: 'A', text: '3' },
      { label: 'B', text: '4' },
      { label: 'C', text: '5' },
      { label: 'D', text: '6' },
    ],
    correctAnswer: 'D',
    explanation: 'Solve: 3x − 7 > 8 → 3x > 15 → x > 5. The only choice strictly greater than 5 is 6.',
    wrongAnswerExplanations: {
      A: 'x = 3: 3(3) − 7 = 2, which is not greater than 8.',
      B: 'x = 4: 3(4) − 7 = 5, which is not greater than 8.',
      C: 'x = 5: 3(5) − 7 = 8, which equals 8 but does NOT satisfy the strict inequality > 8.',
    },
    teachingPoint: 'Solve the inequality like an equation; x = 5 satisfies 3x − 7 = 8 but NOT the strict inequality 3x − 7 > 8.',
    relatedSkills: ['Linear Equations in One Variable'],
    isWordProblem: false,
  },

  {
    id: 'math-alg-ineq-008',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Inequalities in One or Two Variables',
    difficulty: 'medium',
    timeTargetSeconds: 90,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    question: 'Solving the inequality −4x + 3 ≥ 15 gives which of the following?',
    choices: [
      { label: 'A', text: 'x ≥ −3' },
      { label: 'B', text: 'x ≤ −3' },
      { label: 'C', text: 'x ≥ 3' },
      { label: 'D', text: 'x ≤ 3' },
    ],
    correctAnswer: 'B',
    explanation: 'Subtract 3 from both sides: −4x ≥ 12. Divide by −4 and flip the inequality: x ≤ −3.',
    wrongAnswerExplanations: {
      A: 'x ≥ −3 forgets to flip the inequality sign when dividing by a negative number.',
      C: 'x ≥ 3 both forgets the sign flip and uses a positive result for −12 ÷ −4.',
      D: 'x ≤ 3 correctly flips the sign but loses the negative on the result (−12 ÷ −4 = 3, not −3).',
    },
    teachingPoint: 'When dividing or multiplying both sides of an inequality by a negative number, you must reverse the inequality direction.',
    relatedSkills: ['Linear Equations in One Variable'],
    isWordProblem: false,
  },

  {
    id: 'math-alg-ineq-009',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Inequalities in One or Two Variables',
    difficulty: 'medium',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'A taxi charges $2.50 per mile plus a $3 base fare. Anya wants to spend no more than $18. Which inequality represents the maximum number of miles m she can travel?',
    choices: [
      { label: 'A', text: '2.50m ≤ 18' },
      { label: 'B', text: '2.50m + 3 ≤ 18' },
      { label: 'C', text: '2.50m + 3 ≥ 18' },
      { label: 'D', text: '3m + 2.50 ≤ 18' },
    ],
    correctAnswer: 'B',
    explanation: 'Total cost = 2.50m + 3. To spend no more than $18: 2.50m + 3 ≤ 18. Solving: 2.50m ≤ 15, so m ≤ 6.',
    wrongAnswerExplanations: {
      A: 'This omits the $3 base fare entirely.',
      C: '"No more than" means ≤, not ≥. This inequality would require spending at least $18.',
      D: 'This swaps the per-mile rate ($2.50) and the base fare ($3).',
    },
    teachingPoint: '"No more than" translates to ≤. Write the full cost expression and set it ≤ the budget.',
    relatedSkills: ['Linear Equations in One Variable'],
    isWordProblem: true,
  },

  {
    id: 'math-alg-ineq-010',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Inequalities in One or Two Variables',
    difficulty: 'medium',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'In the xy-plane, which of the following points is NOT in the solution set of 2x + 3y ≤ 12?',
    choices: [
      { label: 'A', text: '(0, 0)' },
      { label: 'B', text: '(1, 2)' },
      { label: 'C', text: '(3, 2)' },
      { label: 'D', text: '(2, 4)' },
    ],
    correctAnswer: 'D',
    explanation: 'Test each point in 2x + 3y ≤ 12. (0,0): 0 ≤ 12 ✓. (1,2): 2 + 6 = 8 ≤ 12 ✓. (3,2): 6 + 6 = 12 ≤ 12 ✓ (on the boundary). (2,4): 4 + 12 = 16, and 16 > 12. This point does NOT satisfy the inequality.',
    wrongAnswerExplanations: {
      A: '2(0) + 3(0) = 0 ≤ 12. This point satisfies the inequality.',
      B: '2(1) + 3(2) = 8 ≤ 12. This point satisfies the inequality.',
      C: '2(3) + 3(2) = 12 ≤ 12. This point is on the boundary and satisfies the inequality (≤ includes equality).',
    },
    teachingPoint: 'To test whether a point is in the solution set, substitute its coordinates and check whether the inequality holds. The boundary (equality) is included for ≤.',
    relatedSkills: ['Linear Equations in Two Variables'],
    isWordProblem: false,
  },

  {
    id: 'math-alg-ineq-011',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Inequalities in One or Two Variables',
    difficulty: 'hard',
    timeTargetSeconds: 120,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'A company produces two products, X and Y. Each unit of X requires 3 hours of labor and each unit of Y requires 5 hours. The company has at most 60 hours of labor available per day. If x and y represent the number of units produced, which of the following represents all constraints, including that production must be non-negative?',
    choices: [
      { label: 'A', text: '3x + 5y ≤ 60, x ≥ 0, y ≥ 0' },
      { label: 'B', text: '3x + 5y ≥ 60, x ≥ 0, y ≥ 0' },
      { label: 'C', text: '5x + 3y ≤ 60, x ≥ 0, y ≥ 0' },
      { label: 'D', text: '3x + 5y ≤ 60, x > 0, y > 0' },
    ],
    correctAnswer: 'A',
    explanation: 'Total labor = 3x + 5y must be at most 60: 3x + 5y ≤ 60. Production quantities cannot be negative: x ≥ 0 and y ≥ 0 (non-negative, which includes zero).',
    wrongAnswerExplanations: {
      B: '"At most 60" means ≤ 60, not ≥ 60.',
      C: 'The coefficients are reversed: X requires 3 hours and Y requires 5 hours, so the correct expression is 3x + 5y, not 5x + 3y.',
      D: 'Non-negative includes zero production (x ≥ 0, y ≥ 0). Using strict inequalities (x > 0) would forbid producing zero units of a product.',
    },
    teachingPoint: '"At most" means ≤. Non-negative means ≥ 0, which allows zero. These are the standard constraints in linear programming problems.',
    relatedSkills: ['Linear Equations in Two Variables'],
    isWordProblem: true,
  },

  // ─── Algebra: Linear Functions ───────────────────────────────────────────

  {
    id: 'math-alg-lf-009',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Functions',
    difficulty: 'easy',
    timeTargetSeconds: 75,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'A linear function f has the property that f(2) = 9 and f(5) = 18. What is f(0)?',
    choices: [
      { label: 'A', text: '1' },
      { label: 'B', text: '3' },
      { label: 'C', text: '5' },
      { label: 'D', text: '6' },
    ],
    correctAnswer: 'B',
    explanation: 'Slope = (18 − 9)/(5 − 2) = 9/3 = 3. Using f(x) = 3x + b: 9 = 3(2) + b → b = 3. So f(0) = 3.',
    wrongAnswerExplanations: {
      A: 'f(0) = 1 would require b = 1, but f(2) = 3(2) + 1 = 7 ≠ 9.',
      C: 'f(0) = 5 would require b = 5, but f(2) = 3(2) + 5 = 11 ≠ 9.',
      D: 'f(0) = 6 would require b = 6, but f(2) = 3(2) + 6 = 12 ≠ 9.',
    },
    teachingPoint: 'Find the slope from two points, then substitute one point into f(x) = mx + b to find the y-intercept b = f(0).',
    relatedSkills: ['Linear Equations in Two Variables'],
    isWordProblem: false,
  },

  {
    id: 'math-alg-lf-010',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Functions',
    difficulty: 'medium',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'The function f(x) = −3x + 12 represents the amount of water (in gallons) remaining in a tank x hours after it begins draining. What does the value 12 represent in this context?',
    choices: [
      { label: 'A', text: 'The rate at which water drains per hour' },
      { label: 'B', text: 'The number of hours until the tank is empty' },
      { label: 'C', text: 'The initial amount of water in the tank' },
      { label: 'D', text: 'The amount of water remaining after 12 hours' },
    ],
    correctAnswer: 'C',
    explanation: 'In f(x) = −3x + 12, setting x = 0 gives f(0) = 12. Since x represents hours after draining begins, f(0) = 12 gallons is the initial amount of water.',
    wrongAnswerExplanations: {
      A: 'The rate of draining is the slope, which is −3 (3 gallons per hour draining).',
      B: 'The tank is empty when f(x) = 0: −3x + 12 = 0 → x = 4 hours, not 12.',
      D: 'After 12 hours: f(12) = −3(12) + 12 = −24, which is negative and physically impossible.',
    },
    teachingPoint: 'In f(x) = mx + b, the constant b is the value of the function when x = 0. In context, this is the starting (initial) value.',
    relatedSkills: ['Linear Equations in Two Variables'],
    isWordProblem: true,
  },

  {
    id: 'math-alg-lf-011',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Functions',
    difficulty: 'medium',
    timeTargetSeconds: 90,
    mistakeType: 'trap answer',
    questionType: 'grid_in',
    question: 'A linear function g satisfies g(1) = 7 and g(4) = 19. What is g(7)?',
    correctAnswer: '31',
    acceptableAnswers: ['31'],
    explanation: 'Slope = (19 − 7)/(4 − 1) = 12/3 = 4. Each unit increase in x increases g(x) by 4. g(7) = g(4) + 4 × (7 − 4) = 19 + 12 = 31.',
    teachingPoint: 'Once you know the slope, step forward: g(7) = g(4) + slope × (7 − 4). No need to find the full equation.',
    relatedSkills: ['Linear Equations in Two Variables'],
    isWordProblem: false,
  },

  {
    id: 'math-alg-lf-012',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Functions',
    difficulty: 'hard',
    timeTargetSeconds: 120,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'A company\'s profit (in thousands of dollars) is modeled by P(n) = 2n − 12, where n is units sold. A rival company\'s profit is modeled by Q(n) = 0.5n + 8. For how many units sold does the company earn exactly twice the rival\'s profit?',
    choices: [
      { label: 'A', text: '20' },
      { label: 'B', text: '24' },
      { label: 'C', text: '28' },
      { label: 'D', text: '36' },
    ],
    correctAnswer: 'C',
    explanation: 'Set P(n) = 2 × Q(n): 2n − 12 = 2(0.5n + 8) = n + 16. Subtract n from both sides: n − 12 = 16. Add 12: n = 28. Verify: P(28) = 2(28) − 12 = 44 and Q(28) = 0.5(28) + 8 = 22. Indeed 44 = 2 × 22.',
    wrongAnswerExplanations: {
      A: 'P(20) = 28, Q(20) = 18. 2Q = 36 ≠ 28.',
      B: 'P(24) = 36, Q(24) = 20. 2Q = 40 ≠ 36.',
      D: 'P(36) = 60, Q(36) = 26. 2Q = 52 ≠ 60.',
    },
    teachingPoint: 'Translate "twice the rival\'s profit" into P(n) = 2Q(n), then solve the resulting linear equation for n.',
    relatedSkills: ['Linear Equations in One Variable'],
    isWordProblem: true,
  },

  // ─── Advanced Math: Quadratic Equations ──────────────────────────────────

  {
    id: 'math-adv-quad-010',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Quadratic Equations',
    difficulty: 'easy',
    timeTargetSeconds: 75,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'Which of the following are the solutions to x² − 5x + 6 = 0?',
    choices: [
      { label: 'A', text: 'x = 1 and x = 6' },
      { label: 'B', text: 'x = 2 and x = 3' },
      { label: 'C', text: 'x = −2 and x = −3' },
      { label: 'D', text: 'x = −1 and x = 6' },
    ],
    correctAnswer: 'B',
    explanation: 'Factor: x² − 5x + 6 = (x − 2)(x − 3) = 0. Setting each factor to zero: x = 2 or x = 3.',
    wrongAnswerExplanations: {
      A: 'x = 1 and x = 6: product = 6 ✓ but sum = 7 ≠ 5. Incorrect factors.',
      C: 'x = −2 and x = −3 come from factoring x² + 5x + 6 = 0, not x² − 5x + 6 = 0.',
      D: 'x = −1 and x = 6: product = −6 ≠ 6. Does not satisfy the equation.',
    },
    teachingPoint: 'To factor x² + bx + c, find two numbers that multiply to c and add to b. Then set each factor equal to zero.',
    relatedSkills: ['Polynomials'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-quad-011',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Quadratic Equations',
    difficulty: 'medium',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'What is the sum of the solutions to 2x² + 3x − 9 = 0?',
    choices: [
      { label: 'A', text: '−3/2' },
      { label: 'B', text: '3/2' },
      { label: 'C', text: '9/2' },
      { label: 'D', text: '−9/2' },
    ],
    correctAnswer: 'A',
    explanation: 'By Vieta\'s formula, sum of roots = −b/a = −3/2. Verify by factoring: 2x² + 3x − 9 = (2x − 3)(x + 3) = 0, giving x = 3/2 and x = −3. Sum = 3/2 + (−3) = 3/2 − 6/2 = −3/2.',
    wrongAnswerExplanations: {
      B: '3/2 is one root alone, not the sum of both roots.',
      C: '9/2 comes from confusing the sum formula with the product formula or arithmetic error.',
      D: '−9/2 is the product of roots (c/a = −9/2), not the sum.',
    },
    teachingPoint: 'Vieta\'s formula: sum of roots = −b/a. For 2x² + 3x − 9, sum = −3/2. No need to find individual roots first.',
    relatedSkills: ['Polynomials'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-quad-012',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Quadratic Equations',
    difficulty: 'medium',
    timeTargetSeconds: 90,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    question: 'A ball is thrown upward and its height h (in feet) after t seconds is given by h(t) = −16t² + 64t + 5. What is the maximum height reached by the ball?',
    choices: [
      { label: 'A', text: '64 feet' },
      { label: 'B', text: '69 feet' },
      { label: 'C', text: '74 feet' },
      { label: 'D', text: '133 feet' },
    ],
    correctAnswer: 'B',
    explanation: 'The vertex occurs at t = −b/(2a) = −64/(2 × (−16)) = 64/32 = 2 seconds. Maximum height = h(2) = −16(4) + 64(2) + 5 = −64 + 128 + 5 = 69 feet.',
    wrongAnswerExplanations: {
      A: '64 feet ignores the constant term 5 (the initial height above ground).',
      C: '74 feet results from an arithmetic error in evaluating h(2).',
      D: '133 feet results from evaluating at the wrong time or summing all coefficients incorrectly.',
    },
    teachingPoint: 'The maximum of a downward parabola occurs at t = −b/(2a). Substitute this t-value back into the function to find the maximum height.',
    relatedSkills: ['Nonlinear Functions'],
    isWordProblem: true,
  },

  {
    id: 'math-adv-quad-013',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Quadratic Equations',
    difficulty: 'medium',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'grid_in',
    question: 'If x² − 10x + c = 0 can be written in the form (x − 5)² = k, what is the value of c when k = 7?',
    correctAnswer: '18',
    acceptableAnswers: ['18'],
    explanation: 'Completing the square: x² − 10x + 25 = (x − 5)². Rewrite the equation: x² − 10x + c = 0 → (x − 5)² − 25 + c = 0 → (x − 5)² = 25 − c. We need 25 − c = k = 7, so c = 25 − 7 = 18.',
    teachingPoint: 'To complete the square for x² − bx, add and subtract (b/2)² = 25. Track the constant carefully: (x−5)² = k means 25 − c = k, so c = 25 − k.',
    relatedSkills: ['Polynomials'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-quad-014',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Quadratic Equations',
    difficulty: 'hard',
    timeTargetSeconds: 120,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'For which of the following values of k does the equation x² + (k − 2)x + 1 = 0 have two distinct real solutions?',
    choices: [
      { label: 'A', text: 'k = 0' },
      { label: 'B', text: 'k = 2' },
      { label: 'C', text: 'k = 4' },
      { label: 'D', text: 'k = 6' },
    ],
    correctAnswer: 'D',
    explanation: 'Two distinct real solutions require discriminant > 0. Discriminant = (k − 2)² − 4(1)(1) = (k − 2)² − 4. Set > 0: (k − 2)² > 4. This means |k − 2| > 2, so k − 2 > 2 (giving k > 4) or k − 2 < −2 (giving k < 0). Only k = 6 satisfies k > 4.',
    wrongAnswerExplanations: {
      A: 'k = 0: (0 − 2)² − 4 = 4 − 4 = 0. Discriminant = 0 means exactly one real solution, not two.',
      B: 'k = 2: (2 − 2)² − 4 = −4 < 0. No real solutions.',
      C: 'k = 4: (4 − 2)² − 4 = 4 − 4 = 0. Discriminant = 0 means exactly one real solution.',
    },
    teachingPoint: 'Two distinct real solutions require discriminant b² − 4ac > 0. Solve the resulting inequality for the parameter k.',
    relatedSkills: ['Polynomials'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-quad-015',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Quadratic Equations',
    difficulty: 'hard',
    timeTargetSeconds: 120,
    mistakeType: 'concept error',
    questionType: 'grid_in',
    question: 'The quadratic equation x² − kx + 16 = 0 has exactly one real solution. What is the positive value of k?',
    correctAnswer: '8',
    acceptableAnswers: ['8'],
    explanation: 'A quadratic has exactly one real solution when its discriminant equals zero. Discriminant = b² − 4ac = (−k)² − 4(1)(16) = k² − 64. Setting k² − 64 = 0 gives k² = 64, so k = ±8. The positive value is k = 8.',
    teachingPoint: 'When a quadratic has exactly one solution, the discriminant b² − 4ac = 0. Solve for the unknown parameter by setting the discriminant equal to zero.',
    relatedSkills: ['Polynomials'],
    isWordProblem: false,
  },

  // ─── Advanced Math: Nonlinear Functions ──────────────────────────────────

  {
    id: 'math-adv-nf-009',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Nonlinear Functions',
    difficulty: 'easy',
    timeTargetSeconds: 75,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'The function f(x) = x² − 4 is defined for all real x. What is f(−3)?',
    choices: [
      { label: 'A', text: '−13' },
      { label: 'B', text: '5' },
      { label: 'C', text: '13' },
      { label: 'D', text: '−5' },
    ],
    correctAnswer: 'B',
    explanation: 'f(−3) = (−3)² − 4 = 9 − 4 = 5.',
    wrongAnswerExplanations: {
      A: '−13 comes from computing −(3²) − 4 = −9 − 4, incorrectly treating (−3)² as −9.',
      C: '13 comes from computing (−3)² + 4 = 9 + 4, adding 4 instead of subtracting.',
      D: '−5 comes from computing −(3²) + 4 = −9 + 4, again treating (−3)² as −9.',
    },
    teachingPoint: '(−3)² = 9, not −9. A negative number squared is always positive.',
    relatedSkills: ['Quadratic Equations'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-nf-010',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Nonlinear Functions',
    difficulty: 'medium',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'The function g(x) = −(x + 2)² + 9 has a vertex at (−2, 9). How many x-intercepts does g have?',
    choices: [
      { label: 'A', text: '0' },
      { label: 'B', text: '1' },
      { label: 'C', text: '2' },
      { label: 'D', text: '3' },
    ],
    correctAnswer: 'C',
    explanation: 'The parabola opens downward (coefficient −1 < 0) with vertex at (−2, 9). Since the vertex is above the x-axis and the parabola opens downward, it crosses the x-axis twice. Solve: −(x+2)² + 9 = 0 → (x+2)² = 9 → x + 2 = ±3 → x = 1 or x = −5.',
    wrongAnswerExplanations: {
      A: '0 x-intercepts would apply if the vertex were below the x-axis for a downward parabola.',
      B: '1 x-intercept occurs when the vertex is exactly on the x-axis (discriminant = 0).',
      D: 'A quadratic can have at most 2 x-intercepts.',
    },
    teachingPoint: 'For a downward-opening parabola with vertex above the x-axis, there are exactly 2 x-intercepts. Set the function equal to zero and solve.',
    relatedSkills: ['Quadratic Equations'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-nf-011',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Nonlinear Functions',
    difficulty: 'medium',
    timeTargetSeconds: 90,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    question: 'If h(x) = x² + 2x − 8 and h(a) = 0, which of the following could be the value of a?',
    choices: [
      { label: 'A', text: '−4' },
      { label: 'B', text: '−2' },
      { label: 'C', text: '4' },
      { label: 'D', text: '8' },
    ],
    correctAnswer: 'A',
    explanation: 'Factor: x² + 2x − 8 = (x + 4)(x − 2) = 0. Solutions: x = −4 or x = 2. Choice A (−4) is one valid answer.',
    wrongAnswerExplanations: {
      B: 'h(−2) = 4 − 4 − 8 = −8 ≠ 0.',
      C: 'h(4) = 16 + 8 − 8 = 16 ≠ 0.',
      D: 'h(8) = 64 + 16 − 8 = 72 ≠ 0.',
    },
    teachingPoint: 'Find zeros of h(x) by factoring. The roots of (x + 4)(x − 2) = 0 are x = −4 and x = 2.',
    relatedSkills: ['Quadratic Equations'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-nf-012',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Nonlinear Functions',
    difficulty: 'medium',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'The graph of y = f(x) is a parabola with vertex at (3, −4) that passes through (1, 0). Which of the following is the equation of f(x)?',
    choices: [
      { label: 'A', text: 'f(x) = (x − 3)² − 4' },
      { label: 'B', text: 'f(x) = (x + 3)² − 4' },
      { label: 'C', text: 'f(x) = −(x − 3)² − 4' },
      { label: 'D', text: 'f(x) = 2(x − 3)² − 4' },
    ],
    correctAnswer: 'A',
    explanation: 'Vertex form: f(x) = a(x − 3)² − 4. Substitute (1, 0): 0 = a(1 − 3)² − 4 = 4a − 4, so a = 1. The equation is f(x) = (x − 3)² − 4.',
    wrongAnswerExplanations: {
      B: 'f(x) = (x + 3)² − 4 has vertex at (−3, −4), not (3, −4).',
      C: 'f(x) = −(x − 3)² − 4: at (1, 0): −(4) − 4 = −8 ≠ 0. This parabola does not pass through (1, 0).',
      D: 'f(x) = 2(x − 3)² − 4: at (1, 0): 2(4) − 4 = 4 ≠ 0.',
    },
    teachingPoint: 'Use vertex form f(x) = a(x − h)² + k with the given vertex (h, k). Substitute the known point to solve for a.',
    relatedSkills: ['Quadratic Equations'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-nf-013',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Nonlinear Functions',
    difficulty: 'hard',
    timeTargetSeconds: 120,
    mistakeType: 'concept error',
    questionType: 'grid_in',
    question: 'The function p(x) = x² − 6x + 5 is defined for x ≥ 3. If p(a) = 12, what is the value of a?',
    correctAnswer: '7',
    acceptableAnswers: ['7'],
    explanation: 'Solve x² − 6x + 5 = 12: x² − 6x − 7 = 0. Factor: (x − 7)(x + 1) = 0, so x = 7 or x = −1. Since the domain is x ≥ 3, only x = 7 is valid. Verify: 49 − 42 + 5 = 12.',
    teachingPoint: 'After solving the quadratic, check both solutions against the domain restriction and discard any that fall outside it.',
    relatedSkills: ['Quadratic Equations'],
    isWordProblem: false,
  },

  // ─── Advanced Math: Equivalent Expressions (Exponential) ─────────────────

  {
    id: 'math-adv-exp-007',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Equivalent Expressions',
    difficulty: 'easy',
    timeTargetSeconds: 75,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'Which expression is equivalent to x³ · x⁵?',
    choices: [
      { label: 'A', text: 'x¹⁵' },
      { label: 'B', text: 'x⁸' },
      { label: 'C', text: '2x⁸' },
      { label: 'D', text: 'x²' },
    ],
    correctAnswer: 'B',
    explanation: 'When multiplying powers with the same base, add the exponents: x³ · x⁵ = x^(3+5) = x⁸.',
    wrongAnswerExplanations: {
      A: 'x¹⁵ comes from multiplying the exponents (3 × 5), which is the rule for (x³)⁵, not x³ · x⁵.',
      C: '2x⁸ incorrectly doubles the coefficient. No coefficient exists to add here.',
      D: 'x² comes from subtracting exponents (5 − 3), which applies to x⁵ ÷ x³, not multiplication.',
    },
    teachingPoint: 'Product rule: x^a · x^b = x^(a+b). Power rule: (x^a)^b = x^(ab). These are different — do not confuse them.',
    relatedSkills: ['Polynomials'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-exp-008',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Equivalent Expressions',
    difficulty: 'medium',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'Which of the following is equivalent to (2x²y³)³?',
    choices: [
      { label: 'A', text: '6x⁶y⁹' },
      { label: 'B', text: '8x⁶y⁹' },
      { label: 'C', text: '8x⁵y⁶' },
      { label: 'D', text: '2x⁶y⁹' },
    ],
    correctAnswer: 'B',
    explanation: '(2x²y³)³ = 2³ · (x²)³ · (y³)³ = 8 · x⁶ · y⁹ = 8x⁶y⁹.',
    wrongAnswerExplanations: {
      A: '6x⁶y⁹: the coefficient 2 was multiplied by 3 instead of raised to the power 3. 2³ = 8, not 6.',
      C: '8x⁵y⁶: the exponents were added (2+3=5, 3+3=6) instead of multiplied by 3.',
      D: '2x⁶y⁹: the coefficient 2 was left unchanged. The exponent 3 applies to all factors inside the parentheses.',
    },
    teachingPoint: 'When raising a product to a power, apply the exponent to every factor: (abc)^n = a^n · b^n · c^n. The coefficient must also be raised to the power.',
    relatedSkills: ['Polynomials'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-exp-009',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Equivalent Expressions',
    difficulty: 'medium',
    timeTargetSeconds: 90,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    question: 'Which expression is equivalent to (x⁴ · y²)^(1/2)?',
    choices: [
      { label: 'A', text: 'x²y' },
      { label: 'B', text: 'x²y²' },
      { label: 'C', text: 'xy' },
      { label: 'D', text: 'x⁴y' },
    ],
    correctAnswer: 'A',
    explanation: '(x⁴ · y²)^(1/2) = x^(4/2) · y^(2/2) = x² · y¹ = x²y.',
    wrongAnswerExplanations: {
      B: 'x²y²: divides x\'s exponent correctly but leaves y\'s exponent at 2 instead of halving it to 1.',
      C: 'xy: y\'s exponent is correct (2/2=1), but x\'s exponent should be 4/2 = 2, not 1.',
      D: 'x⁴y: the exponent 1/2 was applied to y (2/2=1) but not to x (4 unchanged).',
    },
    teachingPoint: '(x^a)^(1/2) = x^(a/2). A fractional exponent of 1/2 means square root. Apply it to each variable\'s exponent independently.',
    relatedSkills: ['Polynomials'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-exp-010',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Equivalent Expressions',
    difficulty: 'medium',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'A population of bacteria doubles every 3 hours. If the initial population is P₀, which expression gives the population after t hours?',
    choices: [
      { label: 'A', text: 'P₀ · 2^t' },
      { label: 'B', text: 'P₀ · 2^(t/3)' },
      { label: 'C', text: 'P₀ · 3^t' },
      { label: 'D', text: 'P₀ · (t/3)²' },
    ],
    correctAnswer: 'B',
    explanation: 'The bacteria double every 3 hours, so in t hours there are t/3 doubling periods. Population = P₀ · 2^(t/3).',
    wrongAnswerExplanations: {
      A: 'P₀ · 2^t would mean the population doubles every 1 hour, not every 3 hours.',
      C: 'P₀ · 3^t would mean tripling every hour, which contradicts the problem.',
      D: 'P₀ · (t/3)² is a polynomial growth model, not exponential. Bacterial doubling follows exponential growth.',
    },
    teachingPoint: 'Exponential growth: if a quantity doubles every d units of time, the formula is P₀ · 2^(t/d). The number of doubling periods is t/d.',
    relatedSkills: ['Nonlinear Functions'],
    isWordProblem: true,
  },

  {
    id: 'math-adv-exp-011',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Equivalent Expressions',
    difficulty: 'hard',
    timeTargetSeconds: 120,
    mistakeType: 'concept error',
    questionType: 'grid_in',
    question: 'If 4^(2x) = 32, what is the value of x?',
    correctAnswer: '5/4',
    acceptableAnswers: ['5/4', '1.25'],
    explanation: 'Write everything as powers of 2: 4^(2x) = (2²)^(2x) = 2^(4x). And 32 = 2⁵. So 2^(4x) = 2⁵, giving 4x = 5, so x = 5/4.',
    teachingPoint: 'Convert all bases to the same prime base, then equate the exponents. Here 4 = 2² and 32 = 2⁵.',
    relatedSkills: ['Polynomials'],
    isWordProblem: false,
  },

  // ─── Advanced Math: Polynomials ──────────────────────────────────────────

  {
    id: 'math-adv-poly-007',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Polynomials',
    difficulty: 'easy',
    timeTargetSeconds: 75,
    mistakeType: 'careless',
    questionType: 'multiple_choice',
    question: 'Which of the following is equivalent to (x + 3)(x − 5)?',
    choices: [
      { label: 'A', text: 'x² − 2x − 15' },
      { label: 'B', text: 'x² + 2x − 15' },
      { label: 'C', text: 'x² − 2x + 15' },
      { label: 'D', text: 'x² − 15' },
    ],
    correctAnswer: 'A',
    explanation: 'FOIL: (x + 3)(x − 5) = x² − 5x + 3x − 15 = x² − 2x − 15.',
    wrongAnswerExplanations: {
      B: 'x² + 2x − 15 results from computing −5x + 3x = +2x instead of −2x (sign error on the outer term).',
      C: 'x² − 2x + 15 uses the correct middle term but wrong sign on the constant: (3)(−5) = −15, not +15.',
      D: 'x² − 15 omits the middle term entirely, forgetting the outer and inner cross-products.',
    },
    teachingPoint: 'FOIL: First, Outer, Inner, Last. Carefully track the sign of each product, especially the inner and outer terms.',
    relatedSkills: ['Quadratic Equations'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-poly-008',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Polynomials',
    difficulty: 'medium',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'The polynomial p(x) = x³ − 2x² − 5x + 6 has x = 1 as a root. Which of the following is the complete factorization of p(x)?',
    choices: [
      { label: 'A', text: '(x − 1)(x² − x − 6)' },
      { label: 'B', text: '(x − 1)(x + 2)(x − 3)' },
      { label: 'C', text: '(x − 1)(x − 2)(x + 3)' },
      { label: 'D', text: '(x + 1)(x − 2)(x − 3)' },
    ],
    correctAnswer: 'B',
    explanation: 'Since x = 1 is a root, (x − 1) is a factor. Synthetic division by 1: coefficients 1, −2, −5, 6 give quotient x² − x − 6. Factor further: x² − x − 6 = (x + 2)(x − 3). Complete factorization: (x − 1)(x + 2)(x − 3).',
    wrongAnswerExplanations: {
      A: 'Only partially factored — x² − x − 6 can be factored further as (x + 2)(x − 3).',
      C: '(x − 1)(x − 2)(x + 3): expanding gives x³ − 5x + 6, which does not match p(x).',
      D: '(x + 1)(x − 2)(x − 3): expanding gives x³ − 4x² + x + 6 ≠ p(x). Also, x = 1 is not a root of this product.',
    },
    teachingPoint: 'If r is a root, (x − r) is a factor. Use synthetic division to find the quotient, then factor the quotient further.',
    relatedSkills: ['Quadratic Equations'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-poly-009',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Polynomials',
    difficulty: 'medium',
    timeTargetSeconds: 90,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    question: 'Which of the following is equivalent to (2x − 3)²?',
    choices: [
      { label: 'A', text: '4x² − 9' },
      { label: 'B', text: '4x² + 9' },
      { label: 'C', text: '4x² − 12x + 9' },
      { label: 'D', text: '2x² − 12x + 9' },
    ],
    correctAnswer: 'C',
    explanation: '(2x − 3)² = (2x)² − 2(2x)(3) + 3² = 4x² − 12x + 9.',
    wrongAnswerExplanations: {
      A: '4x² − 9 is the difference of squares (2x + 3)(2x − 3), not (2x − 3)².',
      B: '4x² + 9 only squares the first and last terms, omitting the middle term −2(2x)(3) = −12x.',
      D: '2x² − 12x + 9: the coefficient of x² should be (2x)² = 4x², not 2x².',
    },
    teachingPoint: '(a − b)² = a² − 2ab + b². The middle term −2ab is often forgotten. Do not confuse with (a+b)(a−b) = a² − b².',
    relatedSkills: ['Quadratic Equations'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-poly-010',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Polynomials',
    difficulty: 'medium',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'grid_in',
    question: 'If x − 2 is a factor of x³ + ax² − 4x + 4, what is the value of a?',
    correctAnswer: '-1',
    acceptableAnswers: ['-1'],
    explanation: 'If x − 2 is a factor, then x = 2 is a root. Substitute x = 2: 2³ + a(2²) − 4(2) + 4 = 0 → 8 + 4a − 8 + 4 = 0 → 4a + 4 = 0 → a = −1.',
    teachingPoint: 'By the Factor Theorem, if (x − r) is a factor, then p(r) = 0. Substitute r into the polynomial and solve for the unknown coefficient.',
    relatedSkills: ['Quadratic Equations'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-poly-011',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Polynomials',
    difficulty: 'hard',
    timeTargetSeconds: 120,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'The polynomial q(x) = x⁴ − 5x² + 4 can be written in completely factored form as:',
    choices: [
      { label: 'A', text: '(x² − 1)(x² − 4)' },
      { label: 'B', text: '(x − 1)(x + 1)(x − 4)(x + 4)' },
      { label: 'C', text: '(x − 1)(x + 1)(x − 2)(x + 2)' },
      { label: 'D', text: '(x² + 1)(x² − 4)' },
    ],
    correctAnswer: 'C',
    explanation: 'Let u = x². Then x⁴ − 5x² + 4 = u² − 5u + 4 = (u − 1)(u − 4) = (x² − 1)(x² − 4). Factor each further: x² − 1 = (x − 1)(x + 1) and x² − 4 = (x − 2)(x + 2). Fully factored: (x − 1)(x + 1)(x − 2)(x + 2).',
    wrongAnswerExplanations: {
      A: 'Correct but only partially factored. Both x² − 1 and x² − 4 can be factored further.',
      B: '(x − 1)(x + 1)(x − 4)(x + 4): this has roots ±1 and ±4. But x = 4 gives q(4) = 256 − 80 + 4 = 180 ≠ 0.',
      D: '(x² + 1)(x² − 4) = x⁴ − 3x² − 4 ≠ x⁴ − 5x² + 4.',
    },
    teachingPoint: 'For a biquadratic polynomial (only even-degree terms), substitute u = x² to get a quadratic in u. Factor that, then factor each resulting difference of squares.',
    relatedSkills: ['Quadratic Equations'],
    isWordProblem: false,
  },

  // ─── Advanced Math: Rational Expressions ─────────────────────────────────

  {
    id: 'math-adv-rat-004',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Rational Expressions',
    difficulty: 'easy',
    timeTargetSeconds: 75,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'Which of the following is equivalent to (x² − 9)/(x − 3) for x ≠ 3?',
    choices: [
      { label: 'A', text: 'x − 3' },
      { label: 'B', text: 'x + 3' },
      { label: 'C', text: 'x² + 3' },
      { label: 'D', text: '(x + 3)(x − 3)' },
    ],
    correctAnswer: 'B',
    explanation: 'Factor the numerator: x² − 9 = (x + 3)(x − 3). Cancel (x − 3): (x + 3)(x − 3)/(x − 3) = x + 3, for x ≠ 3.',
    wrongAnswerExplanations: {
      A: 'x − 3 would be correct if the numerator were (x − 3)², not x² − 9.',
      C: 'x² + 3 results from not factoring x² − 9 correctly or simplifying incorrectly.',
      D: '(x + 3)(x − 3) = x² − 9 is just the original numerator — not simplified.',
    },
    teachingPoint: 'Factor the numerator first. If a factor in the numerator matches the denominator, cancel it (with a restriction on the excluded value).',
    relatedSkills: ['Polynomials'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-rat-005',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Rational Expressions',
    difficulty: 'medium',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'What is the solution to (3/x) + (1/4) = (5/x) for x ≠ 0?',
    choices: [
      { label: 'A', text: '8' },
      { label: 'B', text: '4' },
      { label: 'C', text: '2' },
      { label: 'D', text: '−8' },
    ],
    correctAnswer: 'A',
    explanation: 'Multiply all terms by 4x (the LCD): 12 + x = 20. Solving: x = 8.',
    wrongAnswerExplanations: {
      B: 'x = 4: (3/4) + (1/4) = 1, and (5/4) = 1.25. Not equal.',
      C: 'x = 2: (3/2) + (1/4) = 7/4, and (5/2) = 10/4. Not equal.',
      D: 'x = −8: a sign error from subtracting instead of adding when solving 12 + x = 20.',
    },
    teachingPoint: 'Clear fractions by multiplying all terms by the LCD. Identify the LCD as the product of all distinct denominators.',
    relatedSkills: ['Linear Equations in One Variable'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-rat-006',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Rational Expressions',
    difficulty: 'medium',
    timeTargetSeconds: 90,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    question: 'Which of the following is equivalent to (2x² + x − 6)/(x + 2) for x ≠ −2?',
    choices: [
      { label: 'A', text: '2x − 3' },
      { label: 'B', text: '2x + 3' },
      { label: 'C', text: 'x − 3' },
      { label: 'D', text: 'x + 3' },
    ],
    correctAnswer: 'A',
    explanation: 'Factor the numerator: 2x² + x − 6. Find two numbers multiplying to 2 × (−6) = −12 and adding to 1: that is 4 and −3. Rewrite: 2x² + 4x − 3x − 6 = 2x(x + 2) − 3(x + 2) = (2x − 3)(x + 2). Cancel (x + 2): result is 2x − 3.',
    wrongAnswerExplanations: {
      B: '2x + 3: sign error — the factor is (2x − 3), not (2x + 3). Verify: (2x + 3)(x + 2) = 2x² + 7x + 6 ≠ 2x² + x − 6.',
      C: 'x − 3: missing the coefficient of 2 on x. The leading coefficient of the numerator is 2.',
      D: 'x + 3: wrong sign and missing the factor of 2 on x.',
    },
    teachingPoint: 'To factor a trinomial ax² + bx + c with a ≠ 1, find two numbers multiplying to ac and adding to b, then factor by grouping.',
    relatedSkills: ['Polynomials'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-rat-007',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Rational Expressions',
    difficulty: 'hard',
    timeTargetSeconds: 120,
    mistakeType: 'concept error',
    questionType: 'grid_in',
    question: 'If x/(x − 1) − 2/(x + 1) = 1 has the solution x = k, what is the value of k?',
    correctAnswer: '3',
    acceptableAnswers: ['3'],
    explanation: 'Multiply all terms by (x − 1)(x + 1): x(x + 1) − 2(x − 1) = (x − 1)(x + 1). Expand: x² + x − 2x + 2 = x² − 1. Simplify: x² − x + 2 = x² − 1. Subtract x² from both sides: −x + 2 = −1. So x = 3. Verify: x = 3 is not 1 or −1. Check: (3/2) − (2/4) = (3/2) − (1/2) = 1 ✓.',
    teachingPoint: 'Multiply both sides by the LCD to clear denominators. Always verify your solution does not make any denominator zero (no extraneous solutions).',
    relatedSkills: ['Polynomials', 'Linear Equations in One Variable'],
    isWordProblem: false,
  },
]
