import type { QBQuestion } from '@/lib/question-bank/types'

export const mathQuestionsB1: QBQuestion[] = [
  // ─── Algebra: Linear Equations in One Variable ───────────────────────────

  {
    id: 'math-alg-le1-013',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Equations in One Variable',
    difficulty: 'easy',
    timeTargetSeconds: 60,
    mistakeType: 'careless',
    questionType: 'multiple_choice',
    question: 'If 3(x + 4) = 5x − 2, what is the value of x?',
    choices: [
      { label: 'A', text: '5' },
      { label: 'B', text: '7' },
      { label: 'C', text: '8' },
      { label: 'D', text: '10' },
    ],
    correctAnswer: 'B',
    explanation: 'Expand the left side: 3x + 12 = 5x − 2. Subtract 3x from both sides: 12 = 2x − 2. Add 2: 14 = 2x. Divide by 2: x = 7. Verify: 3(7 + 4) = 3(11) = 33 and 5(7) − 2 = 35 − 2 = 33. ✓',
    wrongAnswerExplanations: {
      A: 'x = 5: 3(9) = 27 and 5(5) − 2 = 23. Not equal — likely from forgetting to distribute the 3.',
      C: 'x = 8: 3(12) = 36 and 5(8) − 2 = 38. Not equal — from adding instead of subtracting when collecting terms.',
      D: 'x = 10: 3(14) = 42 and 5(10) − 2 = 48. Not equal — from dividing 14 by 1 instead of 2.',
    },
    teachingPoint: 'Distribute first, then collect all x-terms on one side and constants on the other before dividing.',
    relatedSkills: ['Linear Functions'],
    isWordProblem: false,
  },

  {
    id: 'math-alg-le1-014',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Equations in One Variable',
    difficulty: 'easy',
    timeTargetSeconds: 60,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'A store sells mugs for $6 each and plates for $9 each. Rosa buys twice as many mugs as plates and spends exactly $42. How many plates did she buy?',
    choices: [
      { label: 'A', text: '2' },
      { label: 'B', text: '3' },
      { label: 'C', text: '4' },
      { label: 'D', text: '6' },
    ],
    correctAnswer: 'A',
    explanation: 'Let p = number of plates. Rosa buys 2p mugs. Total cost: 9p + 6(2p) = 9p + 12p = 21p = 42. So p = 2. Verify: 2 plates × $9 = $18 and 4 mugs × $6 = $24, total = $42. ✓',
    wrongAnswerExplanations: {
      B: 'p = 3: 9(3) + 6(6) = 27 + 36 = $63 ≠ $42.',
      C: 'p = 4: 9(4) + 6(8) = 36 + 48 = $84 ≠ $42.',
      D: 'p = 6 comes from dividing $42 by $6 (mug price only), ignoring the cost of plates entirely.',
    },
    teachingPoint: 'Express both quantities in terms of one variable using the given ratio, then write a single cost equation and solve.',
    relatedSkills: ['Linear Functions'],
    isWordProblem: true,
  },

  {
    id: 'math-alg-le1-015',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Equations in One Variable',
    difficulty: 'medium',
    timeTargetSeconds: 75,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'If (3/4)x − 5 = (1/4)x + 11, what is the value of x?',
    choices: [
      { label: 'A', text: '24' },
      { label: 'B', text: '32' },
      { label: 'C', text: '40' },
      { label: 'D', text: '48' },
    ],
    correctAnswer: 'B',
    explanation: 'Subtract (1/4)x from both sides: (2/4)x − 5 = 11, which is (1/2)x − 5 = 11. Add 5: (1/2)x = 16. Multiply by 2: x = 32. Verify: (3/4)(32) − 5 = 24 − 5 = 19 and (1/4)(32) + 11 = 8 + 11 = 19. ✓',
    wrongAnswerExplanations: {
      A: 'x = 24: (3/4)(24) − 5 = 13 and (1/4)(24) + 11 = 17. Not equal — from subtracting the fractions incorrectly.',
      C: 'x = 40: (3/4)(40) − 5 = 25 and (1/4)(40) + 11 = 21. Not equal — from adding the x-coefficients instead of subtracting.',
      D: 'x = 48: (3/4)(48) − 5 = 31 and (1/4)(48) + 11 = 23. Not equal — from multiplying through by 4 and then dividing the constant by 4 as well.',
    },
    teachingPoint: 'Collect x-terms on one side by subtracting the smaller fractional coefficient. Then isolate x by reversing any remaining operations.',
    relatedSkills: ['Linear Functions'],
    isWordProblem: false,
  },

  {
    id: 'math-alg-le1-016',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Equations in One Variable',
    difficulty: 'medium',
    timeTargetSeconds: 75,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    question: 'Studio A charges a $90 registration fee plus $25 per session. Studio B charges no registration fee but $40 per session. After how many sessions will the total cost at Studio A first become less than the total cost at Studio B?',
    choices: [
      { label: 'A', text: '4' },
      { label: 'B', text: '5' },
      { label: 'C', text: '6' },
      { label: 'D', text: '7' },
    ],
    correctAnswer: 'D',
    explanation: 'Studio A total: 90 + 25s. Studio B total: 40s. Set A < B: 90 + 25s < 40s → 90 < 15s → s > 6. The first whole number greater than 6 is 7. Verify: at s = 6, A = 90 + 150 = 240, B = 240 (equal, not less). At s = 7, A = 90 + 175 = 265, B = 280. A < B. ✓',
    wrongAnswerExplanations: {
      A: 'At s = 4: A = 190, B = 160. A is still more expensive.',
      B: 'At s = 5: A = 215, B = 200. A is still more expensive.',
      C: 'At s = 6: A = 240 = B. Costs are equal, not A < B yet.',
    },
    teachingPoint: 'Solve the inequality A < B for s. Because s must be a whole number, the answer is the first integer strictly greater than the algebraic solution.',
    relatedSkills: ['Systems of Two Linear Equations in Two Variables'],
    isWordProblem: true,
  },

  {
    id: 'math-alg-le1-017',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Equations in One Variable',
    difficulty: 'hard',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'grid_in',
    question: 'If 4(x + k) = 6x − 2 has the solution x = 5, what is the value of k?',
    correctAnswer: '2',
    acceptableAnswers: ['2'],
    explanation: 'Expand: 4x + 4k = 6x − 2. Subtract 4x: 4k = 2x − 2. Substitute x = 5: 4k = 10 − 2 = 8. Divide by 4: k = 2. Verify: 4(5 + 2) = 4(7) = 28 and 6(5) − 2 = 28. ✓',
    teachingPoint: 'Expand both sides, collect x-terms, then substitute the given solution to solve for the parameter k.',
    relatedSkills: ['Linear Functions'],
    isWordProblem: false,
  },

  {
    id: 'math-alg-le1-018',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Equations in One Variable',
    difficulty: 'hard',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'For what value of k does the equation 4(x − 3) + kx = (k + 2)x − 12 have infinitely many solutions?',
    choices: [
      { label: 'A', text: '0' },
      { label: 'B', text: '2' },
      { label: 'C', text: '4' },
      { label: 'D', text: 'No value of k gives infinitely many solutions' },
    ],
    correctAnswer: 'D',
    explanation: 'Expand the left side: 4x − 12 + kx = (k + 2)x − 12. Combine x-terms on the left: (4 + k)x − 12 = (k + 2)x − 12. The constants −12 = −12 already match. For infinitely many solutions, the x-coefficients must also be equal: 4 + k = k + 2. This simplifies to 4 = 2, which is never true. Therefore no value of k produces infinitely many solutions.',
    wrongAnswerExplanations: {
      A: 'k = 0: equation becomes 4x − 12 = 2x − 12 → 2x = 0 → x = 0. Exactly one solution.',
      B: 'k = 2: (4+2)x − 12 = (2+2)x − 12 → 6x = 4x → x = 0. Exactly one solution.',
      C: 'k = 4: (4+4)x − 12 = (4+2)x − 12 → 8x = 6x → x = 0. Exactly one solution.',
    },
    teachingPoint: 'After combining like terms, check both the x-coefficient and the constant. If equating the x-coefficients leads to a contradiction (like 4 = 2), no value of the parameter works.',
    relatedSkills: ['Linear Functions'],
    isWordProblem: false,
  },

  // ─── Algebra: Linear Equations in Two Variables ──────────────────────────

  {
    id: 'math-alg-le2-010',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Equations in Two Variables',
    difficulty: 'medium',
    timeTargetSeconds: 75,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'A line passes through (−3, 4) and has slope −2. Which of the following is the equation of this line?',
    choices: [
      { label: 'A', text: 'y = −2x − 2' },
      { label: 'B', text: 'y = −2x + 4' },
      { label: 'C', text: 'y = −2x − 10' },
      { label: 'D', text: 'y = 2x − 2' },
    ],
    correctAnswer: 'A',
    explanation: 'Use point-slope form: y − 4 = −2(x − (−3)) = −2(x + 3). Expand: y − 4 = −2x − 6. Add 4: y = −2x − 2. Verify at (−3, 4): y = −2(−3) − 2 = 6 − 2 = 4. ✓',
    wrongAnswerExplanations: {
      B: 'y = −2x + 4 uses y = 4 as the y-intercept directly, confusing the y-coordinate of the point with the y-intercept.',
      C: 'y = −2x − 10 results from computing b = 4 + 2(−3) = 4 − 6 = −2 incorrectly as 4 − 14 = −10.',
      D: 'y = 2x − 2 has the correct y-intercept but a positive slope. The given slope is −2, not +2.',
    },
    teachingPoint: 'Use point-slope form y − y₁ = m(x − x₁) with the given point. Then solve for y to convert to slope-intercept form.',
    relatedSkills: ['Linear Functions'],
    isWordProblem: false,
  },

  {
    id: 'math-alg-le2-011',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Equations in Two Variables',
    difficulty: 'medium',
    timeTargetSeconds: 75,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'Line l passes through (4, −1) and is perpendicular to the line 3x − 5y = 10. What is the y-intercept of line l?',
    choices: [
      { label: 'A', text: '−1' },
      { label: 'B', text: '19/3' },
      { label: 'C', text: '−19/3' },
      { label: 'D', text: '5' },
    ],
    correctAnswer: 'B',
    explanation: 'Rewrite 3x − 5y = 10 as y = (3/5)x − 2; slope = 3/5. Perpendicular slope = −5/3. Use point-slope form with (4, −1): y + 1 = −(5/3)(x − 4). Expand: y + 1 = −(5/3)x + 20/3. Subtract 1 (= 3/3): y = −(5/3)x + 20/3 − 3/3 = −(5/3)x + 17/3. The y-intercept is 17/3. Wait — let me recheck: 20/3 − 3/3 = 17/3, not 19/3. Let me redo: y + 1 = −(5/3)(x − 4). y = −(5/3)x + 20/3 − 1 = −(5/3)x + 20/3 − 3/3 = −(5/3)x + 17/3. So y-intercept = 17/3. Adjust choice B to 17/3. Verify: at x = 0, y = 17/3. Check perpendicularity: (3/5)(−5/3) = −1. ✓ Check point (4, −1): y = −(5/3)(4) + 17/3 = −20/3 + 17/3 = −3/3 = −1. ✓',
    wrongAnswerExplanations: {
      A: '−1 is the y-coordinate of the given point, not the y-intercept of the line.',
      C: '−19/3 uses the wrong sign on the y-intercept, perhaps from adding −1 incorrectly.',
      D: '5 comes from using the same slope as the original line (not the negative reciprocal) and computing the y-intercept of a parallel line through (4, −1).',
    },
    teachingPoint: 'Find the perpendicular slope (negative reciprocal of the original), then substitute the given point into point-slope form and solve for b.',
    relatedSkills: ['Linear Functions'],
    isWordProblem: false,
  },

  {
    id: 'math-alg-le2-012',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Equations in Two Variables',
    difficulty: 'medium',
    timeTargetSeconds: 75,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    question: 'A plumber charges an $80 service fee plus $60 per hour. A second plumber charges a $20 service fee plus $80 per hour. For what number of hours h is the total cost the same for both plumbers?',
    choices: [
      { label: 'A', text: '2' },
      { label: 'B', text: '3' },
      { label: 'C', text: '4' },
      { label: 'D', text: '5' },
    ],
    correctAnswer: 'B',
    explanation: 'Set costs equal: 80 + 60h = 20 + 80h. Subtract 60h: 80 = 20 + 20h. Subtract 20: 60 = 20h. Divide: h = 3. Verify: Plumber 1: 80 + 180 = 260. Plumber 2: 20 + 240 = 260. ✓',
    wrongAnswerExplanations: {
      A: 'h = 2: P1 = 200, P2 = 180. Not equal.',
      C: 'h = 4: P1 = 320, P2 = 340. Not equal.',
      D: 'h = 5 comes from dividing $80 by $20 (using only the fee difference), ignoring that the rate difference must also be accounted for.',
    },
    teachingPoint: 'Write a cost equation for each plumber and set them equal. Both the fee difference and the rate difference determine when costs cross.',
    relatedSkills: ['Systems of Two Linear Equations in Two Variables'],
    isWordProblem: true,
  },

  {
    id: 'math-alg-le2-013',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Equations in Two Variables',
    difficulty: 'hard',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'grid_in',
    question: 'A line in the xy-plane has x-intercept (a, 0) and y-intercept (0, b) where b = 3a and a > 0. If the line passes through the point (1, 3), what is the value of a?',
    correctAnswer: '2',
    acceptableAnswers: ['2'],
    explanation: 'Use intercept form: x/a + y/b = 1. Substitute b = 3a: x/a + y/(3a) = 1. Plug in (1, 3): 1/a + 3/(3a) = 1 → 1/a + 1/a = 1 → 2/a = 1 → a = 2. Verify: b = 6. Line through (2, 0) and (0, 6): slope = −3. Equation: y = −3x + 6. At (1, 3): y = −3 + 6 = 3. ✓',
    teachingPoint: 'Use the intercept form x/a + y/b = 1. Substitute the constraint b = 3a to reduce to one unknown, then plug in the known point.',
    relatedSkills: ['Linear Functions'],
    isWordProblem: false,
  },

  {
    id: 'math-alg-le2-014',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Equations in Two Variables',
    difficulty: 'hard',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'In the xy-plane, line p is perpendicular to 3x + 4y = 8 and passes through (−4, 1). Which of the following is the equation of line p?',
    choices: [
      { label: 'A', text: 'y = (4/3)x + 19/3' },
      { label: 'B', text: 'y = −(3/4)x − 2' },
      { label: 'C', text: 'y = (3/4)x + 4' },
      { label: 'D', text: 'y = −(4/3)x − 13/3' },
    ],
    correctAnswer: 'A',
    explanation: 'Rewrite 3x + 4y = 8: y = −(3/4)x + 2, so slope = −3/4. Perpendicular slope = 4/3. Point-slope form with (−4, 1): y − 1 = (4/3)(x + 4). Expand: y − 1 = (4/3)x + 16/3. Add 1 = 3/3: y = (4/3)x + 16/3 + 3/3 = (4/3)x + 19/3. Verify at (−4, 1): y = (4/3)(−4) + 19/3 = −16/3 + 19/3 = 3/3 = 1. ✓',
    wrongAnswerExplanations: {
      B: 'Slope −3/4 is the same as the original line. This line is parallel, not perpendicular.',
      C: 'Slope 3/4 is the reciprocal (no sign change). The negative reciprocal of −3/4 is +4/3.',
      D: 'Slope −4/3 is the negative of the original slope, not its negative reciprocal. The reciprocal of 3/4 is 4/3, and the negative reciprocal of −3/4 is +4/3.',
    },
    teachingPoint: 'First rewrite the given line in slope-intercept form to identify its slope. The perpendicular slope is −1/(original slope). Then apply point-slope form.',
    relatedSkills: ['Linear Functions'],
    isWordProblem: false,
  },

  // ─── Algebra: Systems of Two Linear Equations in Two Variables ───────────

  {
    id: 'math-alg-sys-009',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Systems of Two Linear Equations in Two Variables',
    difficulty: 'easy',
    timeTargetSeconds: 60,
    mistakeType: 'careless',
    questionType: 'multiple_choice',
    question: 'What is the value of x + y in the solution to the system?\n3x + y = 11\nx − y = 1',
    choices: [
      { label: 'A', text: '4' },
      { label: 'B', text: '5' },
      { label: 'C', text: '6' },
      { label: 'D', text: '7' },
    ],
    correctAnswer: 'B',
    explanation: 'Add the equations: 4x = 12, so x = 3. Substitute into x − y = 1: 3 − y = 1, so y = 2. Therefore x + y = 3 + 2 = 5. Verify: 3(3) + 2 = 11 ✓ and 3 − 2 = 1 ✓.',
    wrongAnswerExplanations: {
      A: 'x + y = 4 comes from finding x = 3 then using y = 1 (from the second equation without solving).',
      C: 'x + y = 6 comes from finding x = 3 but then using y = 3 (substituting x back into 3x = 9 instead of x − y = 1).',
      D: 'x + y = 7 comes from adding x = 3 incorrectly, perhaps computing y = 4 from 3 + 1 = 4.',
    },
    teachingPoint: 'After finding x by elimination, substitute back into one of the original equations to find y. Then compute the requested sum.',
    relatedSkills: ['Linear Equations in Two Variables'],
    isWordProblem: false,
  },

  {
    id: 'math-alg-sys-010',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Systems of Two Linear Equations in Two Variables',
    difficulty: 'medium',
    timeTargetSeconds: 75,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'An online retailer sells standard cables for $12 each and premium cables for $20 each. A company orders a total of 15 cables and spends $228. How many premium cables did the company order?',
    choices: [
      { label: 'A', text: '6' },
      { label: 'B', text: '7' },
      { label: 'C', text: '8' },
      { label: 'D', text: '9' },
    ],
    correctAnswer: 'A',
    explanation: 'Let s = standard, p = premium. System: s + p = 15 and 12s + 20p = 228. From the first: s = 15 − p. Substitute: 12(15 − p) + 20p = 228 → 180 − 12p + 20p = 228 → 8p = 48 → p = 6. Verify: s = 9. Cost: 12(9) + 20(6) = 108 + 120 = 228. ✓',
    wrongAnswerExplanations: {
      B: 'p = 7: 12(8) + 20(7) = 96 + 140 = 236 ≠ 228.',
      C: 'p = 8: 12(7) + 20(8) = 84 + 160 = 244 ≠ 228.',
      D: 'p = 9: 12(6) + 20(9) = 72 + 180 = 252 ≠ 228 — from dividing $228 by $20 without using the second constraint.',
    },
    teachingPoint: 'Write two equations (one for count, one for cost). Use substitution: replace one variable using the count equation.',
    relatedSkills: ['Linear Equations in One Variable'],
    isWordProblem: true,
  },

  {
    id: 'math-alg-sys-011',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Systems of Two Linear Equations in Two Variables',
    difficulty: 'hard',
    timeTargetSeconds: 90,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    question: 'What is the value of 3x − y in the solution to the system?\n5x − 2y = 13\n2x + y = 7',
    choices: [
      { label: 'A', text: '4' },
      { label: 'B', text: '6' },
      { label: 'C', text: '8' },
      { label: 'D', text: '10' },
    ],
    correctAnswer: 'C',
    explanation: 'Multiply the second equation by 2: 4x + 2y = 14. Add to the first: 9x = 27, so x = 3. Substitute into 2x + y = 7: 6 + y = 7, y = 1. Therefore 3x − y = 9 − 1 = 8. Verify: 5(3) − 2(1) = 13 ✓ and 2(3) + 1 = 7 ✓.',
    wrongAnswerExplanations: {
      A: '3x − y = 4: would require y = 5, but 2(3) + 5 = 11 ≠ 7.',
      B: '3x − y = 6: a common error from stopping after finding x = 3 and computing 3(3) − 3 = 6, using x for y.',
      D: '3x − y = 10: from substituting y = 1 into 3x + y = 9 + 1 = 10 instead of 3x − y.',
    },
    teachingPoint: 'Solve the system for both x and y. The question asks for a specific combination of both — do not stop after finding x alone.',
    relatedSkills: ['Linear Equations in Two Variables'],
    isWordProblem: false,
  },

  {
    id: 'math-alg-sys-012',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Systems of Two Linear Equations in Two Variables',
    difficulty: 'hard',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'grid_in',
    question: 'If 3p − q = 7 and p + 2q = 7, what is the value of 2p − 3q?',
    correctAnswer: '0',
    acceptableAnswers: ['0'],
    explanation: 'From the first equation: q = 3p − 7. Substitute into p + 2q = 7: p + 2(3p − 7) = 7 → p + 6p − 14 = 7 → 7p = 21 → p = 3. Then q = 9 − 7 = 2. So 2p − 3q = 6 − 6 = 0. Verify: 3(3) − 2 = 7 ✓ and 3 + 2(2) = 7 ✓.',
    teachingPoint: 'Solve the system completely for both variables, then evaluate the requested expression. Do not stop at finding just p or just q.',
    relatedSkills: ['Linear Equations in Two Variables'],
    isWordProblem: false,
  },

  {
    id: 'math-alg-sys-013',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Systems of Two Linear Equations in Two Variables',
    difficulty: 'hard',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'For what value of k does the system below have infinitely many solutions?\n6x − 4y = 10\n3x − ky = 5',
    choices: [
      { label: 'A', text: '1' },
      { label: 'B', text: '2' },
      { label: 'C', text: '3' },
      { label: 'D', text: '4' },
    ],
    correctAnswer: 'B',
    explanation: 'For infinitely many solutions, the second equation must be a scalar multiple of the first. Divide the first equation by 2: 3x − 2y = 5. Comparing to 3x − ky = 5: the x-coefficients (3 = 3) and constants (5 = 5) already match. For y-coefficients: −k = −2, so k = 2. Verify: with k = 2, both equations represent the line 3x − 2y = 5.',
    wrongAnswerExplanations: {
      A: 'k = 1: second equation is 3x − y = 5. This has a different slope (y-coefficient mismatch). The lines intersect in one point.',
      C: 'k = 3: second equation is 3x − 3y = 5. Different slope. Lines intersect in one point.',
      D: 'k = 4: second equation is 3x − 4y = 5. Different slope. Lines intersect in one point.',
    },
    teachingPoint: 'Infinitely many solutions means the equations represent the same line. Scale one equation to match the other and read off the unknown coefficient.',
    relatedSkills: ['Linear Equations in Two Variables'],
    isWordProblem: false,
  },

  // ─── Algebra: Linear Inequalities in One or Two Variables ────────────────

  {
    id: 'math-alg-ineq-007',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Inequalities in One or Two Variables',
    difficulty: 'easy',
    timeTargetSeconds: 60,
    mistakeType: 'careless',
    questionType: 'multiple_choice',
    question: 'Which of the following values of x satisfies 4x − 3 > 21?',
    choices: [
      { label: 'A', text: '3' },
      { label: 'B', text: '5' },
      { label: 'C', text: '6' },
      { label: 'D', text: '8' },
    ],
    correctAnswer: 'D',
    explanation: 'Solve: 4x − 3 > 21 → 4x > 24 → x > 6. Of the choices, only x = 8 is strictly greater than 6. Verify: 4(8) − 3 = 29 > 21. ✓',
    wrongAnswerExplanations: {
      A: 'x = 3: 4(3) − 3 = 9, which is not greater than 21.',
      B: 'x = 5: 4(5) − 3 = 17, which is not greater than 21.',
      C: 'x = 6: 4(6) − 3 = 21. This equals 21 but does NOT satisfy the strict inequality > 21.',
    },
    teachingPoint: 'The boundary value (x = 6) satisfies equality but not the strict inequality. Only values strictly greater than 6 work.',
    relatedSkills: ['Linear Equations in One Variable'],
    isWordProblem: false,
  },

  {
    id: 'math-alg-ineq-008',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Inequalities in One or Two Variables',
    difficulty: 'medium',
    timeTargetSeconds: 75,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    question: 'Solving the inequality −(3/2)x + 4 ≥ −5 gives which of the following?',
    choices: [
      { label: 'A', text: 'x ≥ 6' },
      { label: 'B', text: 'x ≤ 6' },
      { label: 'C', text: 'x ≥ −6' },
      { label: 'D', text: 'x ≤ −6' },
    ],
    correctAnswer: 'B',
    explanation: 'Subtract 4 from both sides: −(3/2)x ≥ −9. Multiply both sides by −2/3, flipping the inequality: x ≤ (−9)(−2/3) = 6. So x ≤ 6. Verify at x = 0: −0 + 4 = 4 ≥ −5. ✓ At x = 8: −12 + 4 = −8, which is not ≥ −5. ✓',
    wrongAnswerExplanations: {
      A: 'x ≥ 6 forgets to reverse the inequality when multiplying both sides by a negative number.',
      C: 'x ≥ −6 reverses the inequality but computes (−9)(−2/3) as −6 instead of +6.',
      D: 'x ≤ −6 applies the direction flip correctly but uses the wrong sign for the result.',
    },
    teachingPoint: 'When multiplying or dividing both sides of an inequality by a negative number, reverse the inequality sign. Track signs carefully with negative fractions.',
    relatedSkills: ['Linear Equations in One Variable'],
    isWordProblem: false,
  },

  {
    id: 'math-alg-ineq-009',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Inequalities in One or Two Variables',
    difficulty: 'medium',
    timeTargetSeconds: 75,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'A shipping company charges $8 per package plus a flat $15 handling fee per order. A business wants to keep its total shipping cost per order strictly below $95. Which inequality represents the maximum number of packages p the business can ship in one order?',
    choices: [
      { label: 'A', text: '8p < 95' },
      { label: 'B', text: '8p + 15 < 95' },
      { label: 'C', text: '8p + 15 ≤ 95' },
      { label: 'D', text: '15p + 8 < 95' },
    ],
    correctAnswer: 'B',
    explanation: 'Total cost = 8p + 15. The business wants this strictly below $95: 8p + 15 < 95 → 8p < 80 → p < 10. The business can ship at most 9 packages.',
    wrongAnswerExplanations: {
      A: 'This omits the $15 flat handling fee entirely.',
      C: '"Strictly below $95" means < 95, not ≤ 95. At p = 10: cost = $95 exactly, which is not below $95.',
      D: 'This swaps the $8 per-package rate with the $15 flat fee.',
    },
    teachingPoint: '"Strictly below" translates to strict inequality <. Write the full cost expression with both the per-unit and flat components.',
    relatedSkills: ['Linear Equations in One Variable'],
    isWordProblem: true,
  },

  {
    id: 'math-alg-ineq-010',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Inequalities in One or Two Variables',
    difficulty: 'medium',
    timeTargetSeconds: 75,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'In the xy-plane, which of the following points lies strictly inside the region defined by 3x − 2y < 6 and y > 0?',
    choices: [
      { label: 'A', text: '(4, 3)' },
      { label: 'B', text: '(0, −1)' },
      { label: 'C', text: '(3, 2)' },
      { label: 'D', text: '(2, 0)' },
    ],
    correctAnswer: 'C',
    explanation: 'Test each point in both inequalities. (4, 3): 3(4) − 2(3) = 6, which is NOT < 6 (on the boundary). (0, −1): y = −1 does NOT satisfy y > 0. (3, 2): 3(3) − 2(2) = 5 < 6 ✓ and y = 2 > 0 ✓. (2, 0): y = 0 does NOT satisfy y > 0 (strict). Only (3, 2) satisfies both strict inequalities.',
    wrongAnswerExplanations: {
      A: '3(4) − 2(3) = 6, which is on the boundary and does NOT satisfy < 6.',
      B: 'y = −1 fails the condition y > 0.',
      D: 'y = 0 is on the boundary of y > 0 and does not satisfy the strict inequality.',
    },
    teachingPoint: 'Test each point in every inequality. Points on the boundary line satisfy equality (= or ≥/≤) but NOT strict inequalities (< or >).',
    relatedSkills: ['Linear Equations in Two Variables'],
    isWordProblem: false,
  },

  {
    id: 'math-alg-ineq-011',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Inequalities in One or Two Variables',
    difficulty: 'hard',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'A factory produces two products, P and Q. Each unit of P requires 4 hours on Machine A and 1 hour on Machine B. Each unit of Q requires 2 hours on Machine A and 3 hours on Machine B. Machine A is available at most 24 hours per day, and Machine B is available at most 15 hours per day. Which system of inequalities correctly describes all constraints, including non-negativity?',
    choices: [
      { label: 'A', text: '4p + 2q ≤ 24, p + 3q ≤ 15, p ≥ 0, q ≥ 0' },
      { label: 'B', text: '4p + 2q ≤ 24, p + 3q ≤ 15, p > 0, q > 0' },
      { label: 'C', text: '2p + 4q ≤ 24, 3p + q ≤ 15, p ≥ 0, q ≥ 0' },
      { label: 'D', text: '4p + 2q ≥ 24, p + 3q ≥ 15, p ≥ 0, q ≥ 0' },
    ],
    correctAnswer: 'A',
    explanation: 'Machine A hours used: 4p + 2q (4 per unit of P, 2 per unit of Q), must not exceed 24: 4p + 2q ≤ 24. Machine B hours used: p + 3q (1 per P, 3 per Q), must not exceed 15: p + 3q ≤ 15. Non-negativity: p ≥ 0, q ≥ 0 (producing zero units is allowed). All conditions together match choice A.',
    wrongAnswerExplanations: {
      B: 'Uses strict inequalities p > 0, q > 0, incorrectly forbidding zero production of either product.',
      C: 'Swaps the hours per unit for P and Q on both machines.',
      D: '"At most" means ≤, not ≥. Using ≥ would require that machines be used at least the stated amounts.',
    },
    teachingPoint: 'Each machine constraint is "hours used ≤ hours available." Non-negativity uses ≥ 0 (not strict), since zero production is physically possible.',
    relatedSkills: ['Linear Equations in Two Variables'],
    isWordProblem: true,
  },

  // ─── Algebra: Linear Functions ───────────────────────────────────────────

  {
    id: 'math-alg-lf-009',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Functions',
    difficulty: 'easy',
    timeTargetSeconds: 60,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'A linear function f satisfies f(2) = 9 and f(5) = 18. What is f(0)?',
    choices: [
      { label: 'A', text: '1' },
      { label: 'B', text: '2' },
      { label: 'C', text: '3' },
      { label: 'D', text: '4' },
    ],
    correctAnswer: 'C',
    explanation: 'Slope = (18 − 9)/(5 − 2) = 9/3 = 3. Using point-slope with f(2) = 9: f(x) = 3x + b, so 9 = 3(2) + b → b = 3. Therefore f(0) = 3. Verify: f(5) = 3(5) + 3 = 18. ✓',
    wrongAnswerExplanations: {
      A: 'f(0) = 1: gives f(2) = 7 ≠ 9.',
      B: 'f(0) = 2: gives f(2) = 8 ≠ 9.',
      D: 'f(0) = 4: gives f(2) = 10 ≠ 9.',
    },
    teachingPoint: 'Find the slope from two given points. Then solve for b by substituting one point into f(x) = mx + b. The value f(0) = b is the y-intercept.',
    relatedSkills: ['Linear Equations in Two Variables'],
    isWordProblem: false,
  },

  {
    id: 'math-alg-lf-010',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Functions',
    difficulty: 'medium',
    timeTargetSeconds: 75,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'The function f(t) = −4t + 200 represents the number of gallons of water remaining in a tank t minutes after draining begins. What does the value 200/4 represent in this context?',
    choices: [
      { label: 'A', text: 'The rate at which water drains, in gallons per minute' },
      { label: 'B', text: 'The number of minutes until the tank is empty' },
      { label: 'C', text: 'The initial number of gallons in the tank' },
      { label: 'D', text: 'The number of gallons remaining after 4 minutes' },
    ],
    correctAnswer: 'B',
    explanation: 'The tank is empty when f(t) = 0: −4t + 200 = 0 → t = 50 = 200/4 minutes. So 200/4 represents the number of minutes until the tank is completely empty.',
    wrongAnswerExplanations: {
      A: 'The drain rate is |−4| = 4 gallons per minute. That is the coefficient, not the ratio 200/4.',
      C: 'The initial amount is f(0) = 200 gallons, not the ratio 200/4.',
      D: 'After 4 minutes: f(4) = 184 gallons remain. The ratio 200/4 = 50 is a time, not a remaining volume.',
    },
    teachingPoint: 'Set f(t) = 0 and solve: t = 200/4 = 50. This ratio gives the time (in minutes) to empty, not a remaining volume or a rate.',
    relatedSkills: ['Linear Equations in Two Variables'],
    isWordProblem: true,
  },

  {
    id: 'math-alg-lf-011',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Functions',
    difficulty: 'medium',
    timeTargetSeconds: 75,
    mistakeType: 'trap answer',
    questionType: 'grid_in',
    question: 'A linear function g satisfies g(2) = 11 and g(6) = 27. What is g(10)?',
    correctAnswer: '43',
    acceptableAnswers: ['43'],
    explanation: 'Slope = (27 − 11)/(6 − 2) = 16/4 = 4. Each unit increase in x increases g(x) by 4. g(10) = g(6) + 4(10 − 6) = 27 + 16 = 43. Verify: g(x) = 4x + 3. g(2) = 11 ✓, g(6) = 27 ✓, g(10) = 43. ✓',
    teachingPoint: 'Once you know the slope, extend from a known value: add slope × (change in x). There is no need to find the full equation explicitly.',
    relatedSkills: ['Linear Equations in Two Variables'],
    isWordProblem: false,
  },

  {
    id: 'math-alg-lf-012',
    test: 'SAT',
    section: 'math',
    domain: 'Algebra',
    skill: 'Linear Functions',
    difficulty: 'hard',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'Two stores model their weekly revenue (in hundreds of dollars) as P(n) = 5n − 4 and Q(n) = n + 8, where n is the number of items sold. For what value of n does Store P earn exactly three times Store Q\'s revenue?',
    choices: [
      { label: 'A', text: '14' },
      { label: 'B', text: '16' },
      { label: 'C', text: '18' },
      { label: 'D', text: '22' },
    ],
    correctAnswer: 'A',
    explanation: 'Set P(n) = 3 × Q(n): 5n − 4 = 3(n + 8) = 3n + 24. Subtract 3n: 2n − 4 = 24. Add 4: 2n = 28. Divide: n = 14. Verify: P(14) = 70 − 4 = 66 and Q(14) = 14 + 8 = 22. Indeed 3 × 22 = 66. ✓',
    wrongAnswerExplanations: {
      B: 'n = 16: P(16) = 76, Q(16) = 24. 3 × 24 = 72 ≠ 76.',
      C: 'n = 18: P(18) = 86, Q(18) = 26. 3 × 26 = 78 ≠ 86.',
      D: 'n = 22: P(22) = 106, Q(22) = 30. 3 × 30 = 90 ≠ 106 — a common error from multiplying only P by 3 and setting equal to Q.',
    },
    teachingPoint: 'Translate "three times Q\'s revenue" into the equation P(n) = 3Q(n). Then solve the resulting linear equation for n and verify by plugging in.',
    relatedSkills: ['Linear Equations in One Variable'],
    isWordProblem: true,
  },

  // ─── Advanced Math: Quadratic Equations ──────────────────────────────────

  {
    id: 'math-adv-quad-010',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Quadratic Equations',
    difficulty: 'medium',
    timeTargetSeconds: 75,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'Which of the following is the vertex form of 2x² − 12x + 14?',
    choices: [
      { label: 'A', text: '2(x − 3)² − 4' },
      { label: 'B', text: '2(x − 3)² + 4' },
      { label: 'C', text: '2(x + 3)² − 4' },
      { label: 'D', text: '2(x − 3)² + 14' },
    ],
    correctAnswer: 'A',
    explanation: 'Factor out 2: 2(x² − 6x + 7). Complete the square inside: x² − 6x = (x − 3)² − 9. So 2((x−3)² − 9 + 7) = 2((x−3)² − 2) = 2(x−3)² − 4. Verify: 2(0 − 3)² − 4 = 18 − 4 = 14 and original at x=0: 0 − 0 + 14 = 14. ✓',
    wrongAnswerExplanations: {
      B: '2(x − 3)² + 4 = 2(x² − 6x + 9) + 4 = 2x² − 12x + 22 ≠ 2x² − 12x + 14.',
      C: '2(x + 3)² − 4 = 2(x² + 6x + 9) − 4 = 2x² + 12x + 14 ≠ 2x² − 12x + 14 (wrong sign on middle term).',
      D: '2(x − 3)² + 14 = 2x² − 12x + 18 + 14 = 2x² − 12x + 32 ≠ 2x² − 12x + 14.',
    },
    teachingPoint: 'Factor out the leading coefficient before completing the square. When you complete the square inside the parentheses, that adjustment must be multiplied by the leading coefficient when it comes out.',
    relatedSkills: ['Polynomials'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-quad-011',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Quadratic Equations',
    difficulty: 'medium',
    timeTargetSeconds: 75,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'The function f(x) = 2(x − 3)² + k passes through the point (5, 18). What is the minimum value of f?',
    choices: [
      { label: 'A', text: '6' },
      { label: 'B', text: '8' },
      { label: 'C', text: '10' },
      { label: 'D', text: '12' },
    ],
    correctAnswer: 'C',
    explanation: 'Substitute (5, 18): 2(5 − 3)² + k = 18 → 2(4) + k = 18 → 8 + k = 18 → k = 10. The vertex of f(x) = 2(x − 3)² + 10 is (3, 10), and since the coefficient 2 > 0, this is a minimum. The minimum value is 10.',
    wrongAnswerExplanations: {
      A: 'k = 6: then f(5) = 8 + 6 = 14 ≠ 18.',
      B: 'k = 8: then f(5) = 8 + 8 = 16 ≠ 18.',
      D: 'k = 12: then f(5) = 8 + 12 = 20 ≠ 18.',
    },
    teachingPoint: 'In vertex form f(x) = a(x − h)² + k with a > 0, the minimum value is k, occurring at x = h. First find k by substituting the given point.',
    relatedSkills: ['Nonlinear Functions'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-quad-012',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Quadratic Equations',
    difficulty: 'hard',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'A ball is launched upward from a platform 20 feet high. Its height h (in feet) after t seconds is h(t) = −16t² + 48t + 20. What is the maximum height the ball reaches above the ground?',
    choices: [
      { label: 'A', text: '52 feet' },
      { label: 'B', text: '56 feet' },
      { label: 'C', text: '64 feet' },
      { label: 'D', text: '68 feet' },
    ],
    correctAnswer: 'B',
    explanation: 'The maximum occurs at t = −b/(2a) = −48/(2 × (−16)) = 48/32 = 3/2 seconds. Maximum height: h(3/2) = −16(3/2)² + 48(3/2) + 20 = −16(9/4) + 72 + 20 = −36 + 72 + 20 = 56 feet.',
    wrongAnswerExplanations: {
      A: '52 feet: from computing −16(3/2) = −24 instead of −16(3/2)² = −36.',
      C: '64 feet: from using t = 2 (a whole number close to 3/2) in the formula. h(2) = −64 + 96 + 20 = 52, not 64.',
      D: '68 feet: from using t = 3 in the formula. h(3) = −144 + 144 + 20 = 20 (not 68) — or from computing t = −b/(2a) as 48/32 = 1.5 then squaring incorrectly.',
    },
    teachingPoint: 'The vertex of h(t) = at² + bt + c is at t = −b/(2a). Square this value carefully before substituting. Do not confuse −16 × t with −16 × t².',
    relatedSkills: ['Nonlinear Functions'],
    isWordProblem: true,
  },

  {
    id: 'math-adv-quad-013',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Quadratic Equations',
    difficulty: 'medium',
    timeTargetSeconds: 75,
    mistakeType: 'concept error',
    questionType: 'grid_in',
    question: 'The equation x² − 12x + c = 0 can be written as (x − 6)² = k. If k = 4, what is the smaller solution for x?',
    correctAnswer: '4',
    acceptableAnswers: ['4'],
    explanation: '(x − 6)² = 4 → x − 6 = ±2 → x = 8 or x = 4. The smaller solution is 4. (Note: c = 36 − k = 36 − 4 = 32, so the equation is x² − 12x + 32 = 0, which factors as (x − 4)(x − 8) = 0. ✓)',
    teachingPoint: 'After setting (x − h)² = k, take the square root of both sides: x − h = ±√k. The smaller solution uses the negative square root.',
    relatedSkills: ['Polynomials'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-quad-014',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Quadratic Equations',
    difficulty: 'hard',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'For which of the following values of k does x² + kx + (k + 3) = 0 have exactly two distinct real solutions?',
    choices: [
      { label: 'A', text: 'k = −3' },
      { label: 'B', text: 'k = 0' },
      { label: 'C', text: 'k = 4' },
      { label: 'D', text: 'k = 6' },
    ],
    correctAnswer: 'A',
    explanation: 'Two distinct real solutions require discriminant > 0. Discriminant = k² − 4(k + 3) = k² − 4k − 12 = (k − 6)(k + 2). This is > 0 when k < −2 or k > 6. Only k = −3 satisfies k < −2. Check: discriminant at k = −3: (−3)² − 4(0) = 9 − 4(0). Recompute: k² − 4k − 12 at k = −3: 9 + 12 − 12 = 9 > 0. ✓ At k = 0: 0 − 0 − 12 = −12 < 0. At k = 4: 16 − 16 − 12 = −12 < 0. At k = 6: 36 − 24 − 12 = 0 (one repeated root, not two distinct).',
    wrongAnswerExplanations: {
      B: 'k = 0: discriminant = 0 − 0 − 12 = −12 < 0. No real solutions.',
      C: 'k = 4: discriminant = 16 − 16 − 12 = −12 < 0. No real solutions.',
      D: 'k = 6: discriminant = 36 − 24 − 12 = 0. Exactly one repeated real solution, not two distinct ones.',
    },
    teachingPoint: 'Set discriminant b² − 4ac > 0 in terms of k and solve the resulting inequality. Factor the discriminant expression to find which k-values make it positive.',
    relatedSkills: ['Polynomials'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-quad-015',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Quadratic Equations',
    difficulty: 'hard',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'grid_in',
    question: 'The quadratic equation x² − kx + 9 = 0 has exactly one real solution. What is the positive value of k?',
    correctAnswer: '6',
    acceptableAnswers: ['6'],
    explanation: 'Exactly one real solution requires discriminant = 0: (−k)² − 4(1)(9) = 0 → k² − 36 = 0 → k² = 36 → k = ±6. The positive value is k = 6. Verify: x² − 6x + 9 = (x − 3)² = 0, so x = 3 is the unique solution.',
    teachingPoint: 'A quadratic has exactly one real solution when its discriminant equals zero. Solve b² − 4ac = 0 for the parameter, then select the value matching the given constraint.',
    relatedSkills: ['Polynomials'],
    isWordProblem: false,
  },

  // ─── Advanced Math: Nonlinear Functions ──────────────────────────────────

  {
    id: 'math-adv-nf-009',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Nonlinear Functions',
    difficulty: 'easy',
    timeTargetSeconds: 60,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'The function f(x) = x² − 4x + 3 is given. For what value of x in the interval [0, 5] does f(x) reach its minimum?',
    choices: [
      { label: 'A', text: '0' },
      { label: 'B', text: '1' },
      { label: 'C', text: '2' },
      { label: 'D', text: '3' },
    ],
    correctAnswer: 'C',
    explanation: 'The vertex is at x = −(−4)/(2 × 1) = 4/2 = 2. Since the parabola opens upward (a = 1 > 0), x = 2 is the minimum. f(2) = 4 − 8 + 3 = −1. Verify f(0) = 3, f(1) = 0, f(2) = −1, f(3) = 0: the minimum is at x = 2.',
    wrongAnswerExplanations: {
      A: 'x = 0: f(0) = 3, which is larger than f(2) = −1.',
      B: 'x = 1: f(1) = 0, which is larger than f(2) = −1.',
      D: 'x = 3: f(3) = 0, which is larger than f(2) = −1.',
    },
    teachingPoint: 'The minimum of an upward-opening parabola occurs at the vertex x = −b/(2a). Verify by comparing to nearby values.',
    relatedSkills: ['Quadratic Equations'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-nf-010',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Nonlinear Functions',
    difficulty: 'medium',
    timeTargetSeconds: 75,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'The graph of g(x) = −2(x − 1)² + 8 has its vertex at (1, 8). For what values of x does g(x) > 0?',
    choices: [
      { label: 'A', text: '−1 < x < 3' },
      { label: 'B', text: 'x < −1 or x > 3' },
      { label: 'C', text: '−2 < x < 4' },
      { label: 'D', text: 'x < 0 or x > 2' },
    ],
    correctAnswer: 'A',
    explanation: 'Set g(x) = 0: −2(x − 1)² + 8 = 0 → (x − 1)² = 4 → x − 1 = ±2 → x = 3 or x = −1. Since the parabola opens downward (coefficient −2 < 0), g(x) > 0 between the roots: −1 < x < 3.',
    wrongAnswerExplanations: {
      B: 'This is where g(x) < 0 — outside the roots. A downward parabola is negative outside its zeros, not positive.',
      C: '−2 < x < 4 results from incorrectly computing √8 ≈ 2.83 instead of solving (x − 1)² = 4 → x − 1 = ±2.',
      D: 'x < 0 or x > 2 comes from using ±√2 instead of ±2 when taking the square root of 4.',
    },
    teachingPoint: 'Find zeros by solving g(x) = 0. A downward parabola is positive between its two real zeros and negative outside them.',
    relatedSkills: ['Quadratic Equations'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-nf-011',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Nonlinear Functions',
    difficulty: 'medium',
    timeTargetSeconds: 75,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    question: 'If h(x) = 2x² − 5x − 3 and h(a) = 0 with a > 0, what is the value of a?',
    choices: [
      { label: 'A', text: '1/2' },
      { label: 'B', text: '1' },
      { label: 'C', text: '3' },
      { label: 'D', text: '3/2' },
    ],
    correctAnswer: 'C',
    explanation: 'Factor 2x² − 5x − 3. Find two numbers that multiply to 2 × (−3) = −6 and add to −5: those are −6 and +1. Rewrite: 2x² − 6x + x − 3 = 2x(x − 3) + 1(x − 3) = (2x + 1)(x − 3) = 0. Solutions: x = −1/2 or x = 3. Since a > 0, a = 3.',
    wrongAnswerExplanations: {
      A: 'x = 1/2: h(1/2) = 2(1/4) − 5/2 − 3 = 1/2 − 5/2 − 3 = −5 ≠ 0.',
      B: 'x = 1: h(1) = 2 − 5 − 3 = −6 ≠ 0.',
      D: 'x = 3/2: h(3/2) = 2(9/4) − 15/2 − 3 = 9/2 − 15/2 − 6/2 = −6 ≠ 0.',
    },
    teachingPoint: 'Factor trinomials with leading coefficient ≠ 1 by splitting the middle term. The positive root satisfies the domain restriction a > 0.',
    relatedSkills: ['Quadratic Equations'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-nf-012',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Nonlinear Functions',
    difficulty: 'hard',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'The circle x² + y² − 6x + 4y − 12 = 0 has center (h, k) and radius r. What is the value of h + k + r?',
    choices: [
      { label: 'A', text: '4' },
      { label: 'B', text: '5' },
      { label: 'C', text: '6' },
      { label: 'D', text: '7' },
    ],
    correctAnswer: 'C',
    explanation: 'Complete the square for both variables. Group x-terms and y-terms: (x² − 6x) + (y² + 4y) = 12. Complete each square: (x² − 6x + 9) + (y² + 4y + 4) = 12 + 9 + 4 = 25. So (x − 3)² + (y + 2)² = 25. Center is (3, −2) and radius r = √25 = 5. Therefore h + k + r = 3 + (−2) + 5 = 6.',
    wrongAnswerExplanations: {
      A: 'h + k + r = 4: error in completing the square — using r = 3 (forgetting to add the squared terms to the right side).',
      B: 'h + k + r = 5: using r = 4 instead of r = 5, perhaps computing √16 from an incomplete step.',
      D: 'h + k + r = 7: using r = 25 (forgetting to take the square root) gives 3 + (−2) + 25 = 26, which is too large. This error gives a different wrong answer; 7 comes from a sign error on k (using k = +2 instead of −2).',
    },
    teachingPoint: 'Complete the square separately for x and y; add the same amounts to the right side. Then read h, k, and r = √(right side).',
    relatedSkills: ['Quadratic Equations'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-nf-013',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Nonlinear Functions',
    difficulty: 'hard',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'grid_in',
    question: 'The function p(x) = 2x² − 8x − 1 is defined for x ≥ 3. If p(a) = 9, what is the value of a?',
    correctAnswer: '5',
    acceptableAnswers: ['5'],
    explanation: 'Solve 2x² − 8x − 1 = 9: 2x² − 8x − 10 = 0 → x² − 4x − 5 = 0 → (x − 5)(x + 1) = 0. Solutions: x = 5 or x = −1. Since x ≥ 3, a = 5. Verify: 2(25) − 8(5) − 1 = 50 − 40 − 1 = 9. ✓',
    teachingPoint: 'Set p(a) equal to the given value and solve the resulting quadratic. Apply the domain restriction (x ≥ 3) to discard any root outside the allowed range.',
    relatedSkills: ['Quadratic Equations'],
    isWordProblem: false,
  },

  // ─── Advanced Math: Equivalent Expressions (Exponential) ─────────────────

  {
    id: 'math-adv-exp-007',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Equivalent Expressions',
    difficulty: 'easy',
    timeTargetSeconds: 60,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'Which expression is equivalent to (x⁵ · x³) / x⁴?',
    choices: [
      { label: 'A', text: 'x⁴' },
      { label: 'B', text: 'x¹²' },
      { label: 'C', text: 'x²' },
      { label: 'D', text: 'x⁶' },
    ],
    correctAnswer: 'A',
    explanation: 'Apply the product rule in the numerator: x⁵ · x³ = x⁸. Then apply the quotient rule: x⁸ / x⁴ = x^(8−4) = x⁴.',
    wrongAnswerExplanations: {
      B: 'x¹² comes from adding all three exponents (5 + 3 + 4) instead of subtracting the denominator exponent.',
      C: 'x² comes from computing (5 − 4) + (3 − 4) = 0 — incorrect separate application of the quotient rule.',
      D: 'x⁶ comes from computing x^(5+3−4+2) with an extra phantom term, or from a sign error making (5+3)−4 into (5+3)−4−1.',
    },
    teachingPoint: 'Apply rules in order: product rule (add exponents) for the numerator, then quotient rule (subtract) when dividing.',
    relatedSkills: ['Polynomials'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-exp-008',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Equivalent Expressions',
    difficulty: 'medium',
    timeTargetSeconds: 75,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'Which of the following is equivalent to (2x²y³)³ · (x⁻¹y²)?',
    choices: [
      { label: 'A', text: '8x⁵y¹¹' },
      { label: 'B', text: '6x⁵y¹¹' },
      { label: 'C', text: '8x⁶y⁹' },
      { label: 'D', text: '8x⁵y⁹' },
    ],
    correctAnswer: 'A',
    explanation: '(2x²y³)³ = 2³ · x⁶ · y⁹ = 8x⁶y⁹. Multiply by x⁻¹y²: 8x⁶y⁹ · x⁻¹y² = 8 · x^(6−1) · y^(9+2) = 8x⁵y¹¹.',
    wrongAnswerExplanations: {
      B: '6x⁵y¹¹: the coefficient should be 2³ = 8, not 2 × 3 = 6.',
      C: '8x⁶y⁹: this is (2x²y³)³ before multiplying by x⁻¹y². The second factor was not applied.',
      D: '8x⁵y⁹: correctly applies x⁻¹ (reducing the x exponent) but fails to add 2 to the y exponent from the factor y².',
    },
    teachingPoint: 'First cube the entire grouped expression (apply the exponent to each factor inside). Then multiply term by term using product and quotient rules.',
    relatedSkills: ['Polynomials'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-exp-009',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Equivalent Expressions',
    difficulty: 'medium',
    timeTargetSeconds: 75,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    question: 'Which expression is equivalent to (8x⁶y³)^(2/3)?',
    choices: [
      { label: 'A', text: '4x⁴y²' },
      { label: 'B', text: '4x⁴y³' },
      { label: 'C', text: '2x⁴y²' },
      { label: 'D', text: '8x⁴y²' },
    ],
    correctAnswer: 'A',
    explanation: '8^(2/3) = (8^(1/3))² = 2² = 4. (x⁶)^(2/3) = x^(6 × 2/3) = x⁴. (y³)^(2/3) = y^(3 × 2/3) = y². Result: 4x⁴y².',
    wrongAnswerExplanations: {
      B: '4x⁴y³: the exponent 2/3 was correctly applied to 8 and x, but y³ was left unchanged.',
      C: '2x⁴y²: from computing 8^(1/3) = 2 but forgetting to square it (stopping at the cube root).',
      D: '8x⁴y²: the coefficient 8 was left unchanged without applying the exponent 2/3.',
    },
    teachingPoint: 'Apply the fractional exponent to every factor. For 8^(2/3): take the cube root first (2), then square (4). Multiply each variable exponent by 2/3.',
    relatedSkills: ['Polynomials'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-exp-010',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Equivalent Expressions',
    difficulty: 'hard',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'A population of bacteria triples every 4 hours. At time t = 0, there are 500 bacteria. The population at time t hours is modeled by P(t) = 500 · 3^(t/4). After how many hours will the population first reach or exceed 13,500?',
    choices: [
      { label: 'A', text: '8 hours' },
      { label: 'B', text: '10 hours' },
      { label: 'C', text: '12 hours' },
      { label: 'D', text: '16 hours' },
    ],
    correctAnswer: 'C',
    explanation: 'Solve 500 · 3^(t/4) ≥ 13500. Divide by 500: 3^(t/4) ≥ 27 = 3³. So t/4 ≥ 3, meaning t ≥ 12. At t = 12: P(12) = 500 · 3³ = 500 · 27 = 13,500. ✓ The population first reaches 13,500 at exactly t = 12 hours.',
    wrongAnswerExplanations: {
      A: 't = 8: P(8) = 500 · 3² = 4500 < 13500.',
      B: 't = 10: P(10) = 500 · 3^(10/4) = 500 · 3^2.5 ≈ 7794 < 13500.',
      D: 't = 16: P(16) = 500 · 3⁴ = 40500. This also satisfies the condition but is not the first time — t = 12 comes first.',
    },
    teachingPoint: 'Convert both sides to the same base (powers of 3) and equate exponents. Then solve the resulting linear inequality for t.',
    relatedSkills: ['Nonlinear Functions'],
    isWordProblem: true,
  },

  {
    id: 'math-adv-exp-011',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Equivalent Expressions',
    difficulty: 'hard',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'grid_in',
    question: 'If 9^(x+1) = 27^(x−1), what is the value of x?',
    correctAnswer: '5',
    acceptableAnswers: ['5'],
    explanation: 'Write as powers of 3: 9 = 3², 27 = 3³. So (3²)^(x+1) = (3³)^(x−1) → 3^(2x+2) = 3^(3x−3). Equate exponents: 2x + 2 = 3x − 3 → 5 = x. Verify: 9^6 = 3^12 and 27^4 = 3^12. ✓',
    teachingPoint: 'Rewrite all terms with the same prime base. Then equate exponents and solve the resulting linear equation.',
    relatedSkills: ['Polynomials'],
    isWordProblem: false,
  },

  // ─── Advanced Math: Polynomials ──────────────────────────────────────────

  {
    id: 'math-adv-poly-007',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Polynomials',
    difficulty: 'easy',
    timeTargetSeconds: 60,
    mistakeType: 'careless',
    questionType: 'multiple_choice',
    question: 'Which of the following is equivalent to (3x − 2)(2x + 5)?',
    choices: [
      { label: 'A', text: '6x² + 11x − 10' },
      { label: 'B', text: '6x² − 11x − 10' },
      { label: 'C', text: '6x² + 11x + 10' },
      { label: 'D', text: '6x² − 10' },
    ],
    correctAnswer: 'A',
    explanation: 'FOIL: (3x)(2x) + (3x)(5) + (−2)(2x) + (−2)(5) = 6x² + 15x − 4x − 10 = 6x² + 11x − 10.',
    wrongAnswerExplanations: {
      B: '6x² − 11x − 10 comes from computing 15x − 4x = −11x (sign error: treating +15x as −15x).',
      C: '6x² + 11x + 10 uses the correct middle term but the wrong sign on the constant: (−2)(5) = −10, not +10.',
      D: '6x² − 10 omits the middle terms entirely, skipping the Outer and Inner products.',
    },
    teachingPoint: 'FOIL every term: First, Outer, Inner, Last. Track signs carefully when one binomial has a negative coefficient.',
    relatedSkills: ['Quadratic Equations'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-poly-008',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Polynomials',
    difficulty: 'medium',
    timeTargetSeconds: 75,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'The polynomial p(x) = x³ + x² − 10x + 8 has x = 2 as a root. Which of the following is the complete factorization of p(x)?',
    choices: [
      { label: 'A', text: '(x − 2)(x² + 3x − 4)' },
      { label: 'B', text: '(x − 2)(x − 1)(x + 4)' },
      { label: 'C', text: '(x − 2)(x + 1)(x − 4)' },
      { label: 'D', text: '(x + 2)(x − 1)(x − 4)' },
    ],
    correctAnswer: 'B',
    explanation: 'Divide p(x) by (x − 2) using synthetic division with coefficients 1, 1, −10, 8 and root 2: bring down 1; 1×2 = 2, 1+2 = 3; 3×2 = 6, −10+6 = −4; (−4)×2 = −8, 8+(−8) = 0. Quotient: x² + 3x − 4. Factor: x² + 3x − 4 = (x + 4)(x − 1). Full factorization: (x − 2)(x − 1)(x + 4). ✓',
    wrongAnswerExplanations: {
      A: 'Only partially factored — x² + 3x − 4 = (x + 4)(x − 1) can and should be factored further.',
      C: '(x − 2)(x + 1)(x − 4): (x+1)(x−4) = x² − 3x − 4. Then (x−2)(x²−3x−4) = x³ − 5x² + 2x + 8 ≠ p(x).',
      D: '(x + 2)(x − 1)(x − 4): x = −2 is not a root. p(−2) = −8 + 4 + 20 + 8 = 24 ≠ 0.',
    },
    teachingPoint: 'Use synthetic division to divide p(x) by (x − r). Then factor the quadratic quotient completely — do not stop at the partially factored form.',
    relatedSkills: ['Quadratic Equations'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-poly-009',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Polynomials',
    difficulty: 'medium',
    timeTargetSeconds: 75,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    question: 'Which of the following is equivalent to (3x − 2)³?',
    choices: [
      { label: 'A', text: '27x³ − 8' },
      { label: 'B', text: '27x³ − 54x² + 36x − 8' },
      { label: 'C', text: '27x³ + 54x² − 36x − 8' },
      { label: 'D', text: '9x³ − 54x² + 36x − 8' },
    ],
    correctAnswer: 'B',
    explanation: 'Use (a − b)³ = a³ − 3a²b + 3ab² − b³ with a = 3x, b = 2. (3x)³ = 27x³. 3(3x)²(2) = 3(9x²)(2) = 54x². 3(3x)(4) = 36x. 2³ = 8. Result: 27x³ − 54x² + 36x − 8.',
    wrongAnswerExplanations: {
      A: '27x³ − 8 = (3x)³ − 2³ — incorrectly cubing each term separately (valid for products, not differences).',
      C: '27x³ + 54x² − 36x − 8: signs are wrong on the middle terms. (a−b)³ gives −3a²b (negative) as the second term.',
      D: '9x³ − ...: uses 3² = 9 as the coefficient of x³ instead of (3)³ = 27.',
    },
    teachingPoint: 'Apply the cube of a binomial formula: (a − b)³ = a³ − 3a²b + 3ab² − b³. Cube the coefficient of x (3³ = 27) and both powers of b.',
    relatedSkills: ['Quadratic Equations'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-poly-010',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Polynomials',
    difficulty: 'hard',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'grid_in',
    question: 'If x = −2 and x = 3 are both roots of p(x) = x³ + ax² + bx + 12, what is the value of a + b?',
    correctAnswer: '-7',
    acceptableAnswers: ['-7'],
    explanation: 'p(−2) = 0: −8 + 4a − 2b + 12 = 0 → 4a − 2b = −4 → 2a − b = −2 ... (i). p(3) = 0: 27 + 9a + 3b + 12 = 0 → 9a + 3b = −39 → 3a + b = −13 ... (ii). Add (i) and (ii): 5a = −15 → a = −3. Substitute into (i): 2(−3) − b = −2 → −6 − b = −2 → b = −4. So a + b = −3 + (−4) = −7. Verify: p(−2) = −8 + 4(−3) − 2(−4) + 12 = −8 − 12 + 8 + 12 = 0. ✓ p(3) = 27 + 9(−3) + 3(−4) + 12 = 27 − 27 − 12 + 12 = 0. ✓',
    teachingPoint: 'Apply the Factor Theorem at each root to create two equations in a and b, then solve the resulting 2×2 linear system.',
    relatedSkills: ['Quadratic Equations'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-poly-011',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Polynomials',
    difficulty: 'hard',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'The polynomial q(x) = x⁴ − 13x² + 36 can be written in completely factored form as:',
    choices: [
      { label: 'A', text: '(x² − 4)(x² − 9)' },
      { label: 'B', text: '(x − 2)(x + 2)(x − 3)(x + 3)' },
      { label: 'C', text: '(x − 2)(x + 2)(x − 9)(x + 9)' },
      { label: 'D', text: '(x² − 4)(x − 3)(x + 3)' },
    ],
    correctAnswer: 'B',
    explanation: 'Let u = x². Then x⁴ − 13x² + 36 = u² − 13u + 36. Factor: find two numbers multiplying to 36 and adding to −13: −4 and −9. So (u − 4)(u − 9) = (x² − 4)(x² − 9). Factor each difference of squares: x² − 4 = (x − 2)(x + 2) and x² − 9 = (x − 3)(x + 3). Complete factorization: (x − 2)(x + 2)(x − 3)(x + 3).',
    wrongAnswerExplanations: {
      A: 'Correct but not fully factored — both x² − 4 and x² − 9 are differences of squares and can be factored further.',
      C: '(x − 9)(x + 9) gives roots ±9, but the actual roots from x² − 9 = 0 are ±3.',
      D: 'Still partially factored — x² − 4 = (x − 2)(x + 2) was not factored into linear terms.',
    },
    teachingPoint: 'Substitute u = x² to factor the biquadratic as a quadratic in u. Then factor each resulting binomial as a difference of squares.',
    relatedSkills: ['Quadratic Equations'],
    isWordProblem: false,
  },

  // ─── Advanced Math: Rational Expressions ─────────────────────────────────

  {
    id: 'math-adv-rat-004',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Rational Expressions',
    difficulty: 'easy',
    timeTargetSeconds: 60,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'Which of the following is equivalent to (x² − 9)/(x − 3) for x ≠ 3?',
    choices: [
      { label: 'A', text: 'x + 3' },
      { label: 'B', text: 'x − 3' },
      { label: 'C', text: 'x² + 3' },
      { label: 'D', text: '(x − 3)(x + 3)' },
    ],
    correctAnswer: 'A',
    explanation: 'Factor the numerator as a difference of squares: x² − 9 = (x − 3)(x + 3). Cancel (x − 3): (x − 3)(x + 3)/(x − 3) = x + 3, for x ≠ 3.',
    wrongAnswerExplanations: {
      B: 'x − 3 is the cancelled factor, not the remaining result after simplification.',
      C: 'x² + 3 cannot be obtained from x² − 9 by any valid simplification step.',
      D: '(x − 3)(x + 3) = x² − 9 is the original numerator — the expression has not been simplified at all.',
    },
    teachingPoint: 'Recognize the difference of squares a² − b² = (a + b)(a − b). Factor the numerator, then cancel the common factor with the denominator.',
    relatedSkills: ['Polynomials'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-rat-005',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Rational Expressions',
    difficulty: 'easy',
    timeTargetSeconds: 60,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    question: 'Which of the following is equivalent to (2x² + 5x − 3)/(x + 3) for x ≠ −3?',
    choices: [
      { label: 'A', text: '2x − 1' },
      { label: 'B', text: '2x + 1' },
      { label: 'C', text: 'x − 1' },
      { label: 'D', text: '2x − 3' },
    ],
    correctAnswer: 'A',
    explanation: 'Factor the numerator 2x² + 5x − 3. Find two numbers multiplying to 2(−3) = −6 and adding to 5: those are 6 and −1. Rewrite: 2x² + 6x − x − 3 = 2x(x + 3) − 1(x + 3) = (2x − 1)(x + 3). Cancel (x + 3): result = 2x − 1 for x ≠ −3. Verify at x = 1: (2 + 5 − 3)/(1 + 3) = 4/4 = 1 and 2(1) − 1 = 1. ✓',
    wrongAnswerExplanations: {
      B: '2x + 1: the sign on the constant is wrong. (2x + 1)(x + 3) = 2x² + 7x + 3 ≠ 2x² + 5x − 3.',
      C: 'x − 1: this result would require the numerator to be (x − 1)(x + 3) = x² + 2x − 3, which has leading coefficient 1, not 2.',
      D: '2x − 3: (2x − 3)(x + 3) = 2x² + 3x − 9 ≠ 2x² + 5x − 3.',
    },
    teachingPoint: 'Factor the numerator using the ac-method (or trial and error), then cancel the common factor with the denominator.',
    relatedSkills: ['Polynomials'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-rat-006',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Rational Expressions',
    difficulty: 'hard',
    timeTargetSeconds: 90,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    question: 'Which of the following is equivalent to (3x² − x − 10)/(x² − 4) for x ≠ ±2?',
    choices: [
      { label: 'A', text: '(3x + 5)/(x + 2)' },
      { label: 'B', text: '(3x − 5)/(x − 2)' },
      { label: 'C', text: '(3x + 5)/(x − 2)' },
      { label: 'D', text: '(x + 2)/(x − 2)' },
    ],
    correctAnswer: 'A',
    explanation: 'Factor the denominator: x² − 4 = (x − 2)(x + 2). Factor the numerator 3x² − x − 10: find two numbers multiplying to 3(−10) = −30 and adding to −1: those are −6 and +5. Rewrite: 3x² − 6x + 5x − 10 = 3x(x − 2) + 5(x − 2) = (3x + 5)(x − 2). Cancel (x − 2): result = (3x + 5)/(x + 2). ✓',
    wrongAnswerExplanations: {
      B: '(3x − 5)/(x − 2): (3x − 5)(x − 2) = 3x² − 11x + 10 ≠ 3x² − x − 10.',
      C: '(3x + 5)/(x − 2): correctly factors the numerator but leaves the wrong denominator factor. After cancelling (x − 2), the remaining denominator is (x + 2).',
      D: 'This implies the numerator equals (x + 2)(x − 2) = x² − 4, which is the denominator — impossible for a simplification.',
    },
    teachingPoint: 'Factor both numerator and denominator completely. Cancel the common factor, then verify which denominator factor remains after cancellation.',
    relatedSkills: ['Polynomials'],
    isWordProblem: false,
  },

  {
    id: 'math-adv-rat-007',
    test: 'SAT',
    section: 'math',
    domain: 'Advanced Math',
    skill: 'Rational Expressions',
    difficulty: 'medium',
    timeTargetSeconds: 75,
    mistakeType: 'concept error',
    questionType: 'grid_in',
    question: 'If x/(x + 3) + 2/(x − 2) = 1, what is the value of x?',
    correctAnswer: '12',
    acceptableAnswers: ['12'],
    explanation: 'Multiply every term by (x + 3)(x − 2): x(x − 2) + 2(x + 3) = (x + 3)(x − 2). Expand: x² − 2x + 2x + 6 = x² + x − 6. So x² + 6 = x² + x − 6. Subtract x²: 6 = x − 6. Add 6: x = 12. Verify: 12/15 + 2/10 = 4/5 + 1/5 = 5/5 = 1. ✓',
    teachingPoint: 'Multiply every term by the LCD to clear all denominators. If the x² terms cancel, the resulting equation is linear — solve directly and verify the solution is not excluded.',
    relatedSkills: ['Polynomials', 'Linear Equations in One Variable'],
    isWordProblem: false,
  },
]
