import type { QBQuestion } from '@/lib/question-bank/types'

export const rwQuestionsB5c: QBQuestion[] = [
  // ─── Expression of Ideas: Transitions (001–007) ──────────────────────────────

  {
    id: 'rw-b5c-001',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Expression of Ideas',
    skill: 'Transitions',
    difficulty: 'hard',
    timeTargetSeconds: 70,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    stimulus: `Nineteenth-century photographers believed their medium would make painting obsolete, since the camera could capture reality with unprecedented fidelity. ______ the displacement never occurred: rather than dying out, painting reinvented itself, embracing abstraction and expressionism precisely because it was freed from the obligation to represent the world as it literally appeared.`,
    question: `Which choice completes the text with the most logical transition?`,
    choices: [
      { label: 'A', text: 'Therefore,' },
      { label: 'B', text: 'Likewise,' },
      { label: 'C', text: 'For instance,' },
      { label: 'D', text: 'Yet' },
    ],
    correctAnswer: 'D',
    explanation: `The first sentence asserts that photographers predicted painting's obsolescence. The second reveals that this prediction was wrong — painting reinvented itself. The relationship is contrast: an expected outcome did not occur. "Yet" correctly signals this reversal. "Therefore" and "Likewise" imply the second sentence follows from or parallels the first, which is wrong. "For instance" would make painting's survival an example of photography displacing it, which is illogical.`,
    teachingPoint: `When the second sentence shows a predicted outcome did NOT occur, the transition is concessive: "Yet," "However," "Nevertheless."`,
    relatedSkills: ['Text Structure and Purpose'],
  },

  {
    id: 'rw-b5c-002',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Expression of Ideas',
    skill: 'Transitions',
    difficulty: 'hard',
    timeTargetSeconds: 70,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    stimulus: `Tropical deforestation releases stored carbon dioxide into the atmosphere and eliminates tree cover that would otherwise absorb future emissions. ______ tropical forests are among the most cost-effective targets for climate mitigation investment, offering large carbon gains per dollar spent compared to most alternative strategies.`,
    question: `Which choice completes the text with the most logical transition?`,
    choices: [
      { label: 'A', text: 'As a result,' },
      { label: 'B', text: 'Even so,' },
      { label: 'C', text: 'By contrast,' },
      { label: 'D', text: 'For example,' },
    ],
    correctAnswer: 'A',
    explanation: `The first sentence establishes that tropical forests have high carbon value (releasing CO₂ when destroyed, absorbing future emissions when preserved). The second concludes from that value that preserving them is cost-effective — a direct consequence. "As a result" correctly signals this causal relationship. "Even so" signals concession, "By contrast" signals opposition, and "For example" signals illustration — none fits a cause-and-effect relationship here.`,
    teachingPoint: `When the second sentence is a practical conclusion that follows from the facts in the first, use a causal transition: "As a result," "Therefore," "Consequently."`,
    relatedSkills: ['Central Ideas and Details'],
  },

  {
    id: 'rw-b5c-003',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Expression of Ideas',
    skill: 'Transitions',
    difficulty: 'hard',
    timeTargetSeconds: 70,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    stimulus: `Neuroscientists studying brain plasticity have found that the brain continues reorganizing in response to experience well into adulthood — a property once thought to be restricted to childhood development. ______ musicians who begin intensive practice in adulthood show measurable thickening in the cortical regions governing fine motor control, comparable in some cases to that seen in lifelong players.`,
    question: `Which choice completes the text with the most logical transition?`,
    choices: [
      { label: 'A', text: 'However,' },
      { label: 'B', text: 'In contrast,' },
      { label: 'C', text: 'For instance,' },
      { label: 'D', text: 'As a result,' },
    ],
    correctAnswer: 'C',
    explanation: `The first sentence makes a general claim: adult brains reorganize in response to experience. The second gives a specific case — adult musicians developing measurably thicker motor cortex — that illustrates that claim. "For instance" correctly signals that what follows is an example of the preceding generalization. "However" and "In contrast" signal opposition where there is none. "As a result" would miscast the musicians' brain changes as a consequence of the research finding, which is a category error.`,
    teachingPoint: `When the second sentence is a concrete case that illustrates the general claim in the first, use "For instance," "For example," or "To illustrate."`,
    relatedSkills: ['Text Structure and Purpose'],
  },

  {
    id: 'rw-b5c-004',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Expression of Ideas',
    skill: 'Transitions',
    difficulty: 'hard',
    timeTargetSeconds: 70,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    stimulus: `Whole-genome sequencing has transformed diagnostic medicine by enabling clinicians to identify rare genetic variants responsible for conditions that previously went undiagnosed for years. ______ the technology has opened new possibilities for pharmacogenomics — the practice of tailoring drug regimens to individual genetic profiles, reducing adverse reactions and improving therapeutic efficacy.`,
    question: `Which choice completes the text with the most logical transition?`,
    choices: [
      { label: 'A', text: 'Consequently,' },
      { label: 'B', text: 'On the other hand,' },
      { label: 'C', text: 'For example,' },
      { label: 'D', text: 'Moreover,' },
    ],
    correctAnswer: 'D',
    explanation: `The first sentence describes one benefit of whole-genome sequencing (diagnosing rare conditions). The second describes a separate, additional benefit (pharmacogenomics). Both sentences contribute to a picture of the technology's value — the relationship is additive, not causal or illustrative. "Moreover" signals that the second sentence adds a related but distinct point. "Consequently" implies the pharmacogenomics application is caused by the diagnostic use. "For example" would make pharmacogenomics an instance of the diagnostic point rather than an independent benefit.`,
    teachingPoint: `When the second sentence adds a parallel benefit or feature rather than explaining, causing, or exemplifying the first, use "Moreover," "Furthermore," or "Additionally."`,
    relatedSkills: ['Central Ideas and Details'],
  },

  {
    id: 'rw-b5c-005',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Expression of Ideas',
    skill: 'Transitions',
    difficulty: 'hard',
    timeTargetSeconds: 70,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    stimulus: `Romanesque architecture, which flourished in Europe from roughly the tenth to twelfth centuries, is characterized by thick stone walls, rounded arches, and small windows that kept interiors dim and fortress-like. ______ Gothic architecture, which supplanted it beginning in the twelfth century, employed pointed arches, ribbed vaults, and flying buttresses to achieve soaring heights and flood interiors with colored light.`,
    question: `Which choice completes the text with the most logical transition?`,
    choices: [
      { label: 'A', text: 'By contrast,' },
      { label: 'B', text: 'As a result,' },
      { label: 'C', text: 'For example,' },
      { label: 'D', text: 'Similarly,' },
    ],
    correctAnswer: 'A',
    explanation: `The first sentence describes Romanesque features (thick walls, small windows, dim interiors). The second describes Gothic features that are structurally and aesthetically opposed (pointed arches, flying buttresses, flooded with light). The relationship is direct contrast. "By contrast" correctly signals this opposition. "As a result" would wrongly make Gothic architecture a consequence of Romanesque. "For example" would wrongly make Gothic an instance of Romanesque. "Similarly" would make them alike, which contradicts the passage.`,
    teachingPoint: `When two architectural, historical, or conceptual categories are described with opposite properties, the transition is contrastive: "By contrast," "In contrast," "Conversely."`,
    relatedSkills: ['Text Structure and Purpose'],
  },

  {
    id: 'rw-b5c-006',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Expression of Ideas',
    skill: 'Transitions',
    difficulty: 'hard',
    timeTargetSeconds: 70,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    stimulus: `When central banks raise interest rates, borrowing becomes more expensive for businesses and consumers alike, reducing spending and investment across the economy. ______ inflationary pressures typically diminish as demand contracts and producers find themselves with less pricing power.`,
    question: `Which choice completes the text with the most logical transition?`,
    choices: [
      { label: 'A', text: 'Nevertheless,' },
      { label: 'B', text: 'For instance,' },
      { label: 'C', text: 'However,' },
      { label: 'D', text: 'Consequently,' },
    ],
    correctAnswer: 'D',
    explanation: `The first sentence explains that rate hikes reduce spending and investment (the cause). The second explains what follows from that: demand contracts, pricing power weakens, inflation falls (the effect). The connector is explicitly causal. "Consequently" correctly marks this cause-and-effect relationship. "Nevertheless" and "However" signal contrast or concession, but the second sentence follows logically from the first. "For instance" would make falling inflation an example of reduced spending, misrepresenting the relationship.`,
    teachingPoint: `Identify whether the second sentence restates, contrasts, follows from, or illustrates the first. Here the chain is "rate hike → less spending → less pricing power → less inflation," so a causal transition is required.`,
    relatedSkills: ['Central Ideas and Details'],
  },

  {
    id: 'rw-b5c-007',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Expression of Ideas',
    skill: 'Transitions',
    difficulty: 'hard',
    timeTargetSeconds: 70,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    stimulus: `Colony collapse disorder has been attributed by various researchers to pesticide exposure, parasitic mite infestations, pathogen loads, habitat loss, and nutritional deficits. Controlled studies have found that when multiple stressors are present simultaneously, colony mortality rates far exceed what any single stressor predicts in isolation. ______ colony collapse is best understood not as a single-cause disease but as a syndrome driven by the cumulative interaction of many threats.`,
    question: `Which choice completes the text with the most logical transition?`,
    choices: [
      { label: 'A', text: 'For example,' },
      { label: 'B', text: 'In sum,' },
      { label: 'C', text: 'Nevertheless,' },
      { label: 'D', text: 'Moreover,' },
    ],
    correctAnswer: 'B',
    explanation: `The passage presents evidence — multiple proposed causes and the finding that combined stressors cause disproportionate mortality. The final sentence draws the overall conclusion from this body of evidence: CCD is a syndrome, not a single-cause disease. "In sum" correctly signals a synthesizing conclusion drawn from preceding evidence. "For example" would make the conclusion an illustration. "Nevertheless" implies the conclusion contradicts the evidence. "Moreover" adds another point rather than summarizing.`,
    teachingPoint: `"In sum," "In short," and "Taken together" signal that a sentence synthesizes or concludes from preceding evidence — they appear at the end of an argument, not in the middle.`,
    relatedSkills: ['Text Structure and Purpose'],
  },

  // ─── Expression of Ideas: Rhetorical Synthesis (008–016) ─────────────────────

  {
    id: 'rw-b5c-008',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Expression of Ideas',
    skill: 'Rhetorical Synthesis',
    difficulty: 'hard',
    timeTargetSeconds: 90,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    stimulus: `A student is writing a blog post about food insecurity in the United States. She wants to open with a statistic that conveys the scale of the problem among children specifically, without discussing causes. She has found the following information:

• In 2023, approximately 18 million U.S. households experienced food insecurity — about 13.5% of all households.
• Children are disproportionately affected: about 1 in 5 children in the United States lives in a food-insecure household.
• Food insecurity rates are highest in rural areas and among single-parent households.
• Research links childhood food insecurity to lower academic achievement, increased rates of chronic disease, and reduced lifetime earnings.`,
    question: `Which choice most effectively uses the relevant information to accomplish the student's goal?`,
    choices: [
      { label: 'A', text: 'Food insecurity affects 13.5% of all U.S. households, a rate that reflects inadequate access to nutritious food for millions of families across the country.' },
      { label: 'B', text: 'Because rural areas and single-parent households face the highest food insecurity rates, targeted policy interventions in those communities could most efficiently reduce childhood hunger.' },
      { label: 'C', text: 'Childhood food insecurity has serious long-term consequences, including lower academic achievement, higher rates of chronic disease, and reduced lifetime earnings.' },
      { label: 'D', text: 'Roughly one in five children in the United States lives in a food-insecure household, meaning millions of American children lack reliable access to adequate nutrition.' },
    ],
    correctAnswer: 'D',
    explanation: `The goal is a statistic about children specifically, without discussing causes. (D) uses the child-specific statistic ("1 in 5 children") and simply states what it means — no causal language anywhere. (A) uses the general household statistic, not the child-specific one. (B) mentions causes (rural areas, single-parent households) and makes a policy argument, violating both constraints. (C) describes consequences rather than conveying scale.`,
    teachingPoint: `Match both the audience and the constraints. "Children specifically" requires the child-focused data point; "without discussing causes" eliminates any answer mentioning demographics, drivers, or policy causes.`,
    relatedSkills: ['Information and Ideas'],
  },

  {
    id: 'rw-b5c-009',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Expression of Ideas',
    skill: 'Rhetorical Synthesis',
    difficulty: 'hard',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    stimulus: `A student is writing a paper on the economics of sports stadiums. He wants to include a sentence that presents both the proponents' and critics' economic arguments about public stadium funding, making clear both sides have economic rationales. He has gathered the following notes:

• Proponents argue that publicly funded stadiums generate economic activity through tourism, jobs, and business for local vendors.
• Several independent economic studies have found that new stadiums generate little to no net economic benefit for host cities.
• Critics contend that tax dollars used for stadium construction represent an opportunity cost — the same funds could build schools, repair infrastructure, or reduce public debt.
• Team owners typically capture most of the financial gains from publicly subsidized stadiums through increased franchise values and revenue.`,
    question: `Which choice most effectively uses the relevant information to accomplish the student's goal?`,
    choices: [
      { label: 'A', text: 'Independent economic studies consistently find that publicly funded stadiums generate little net benefit for host cities, suggesting that public investment in stadiums is rarely justified.' },
      { label: 'B', text: 'Team owners benefit disproportionately from publicly funded stadiums, capturing most of the financial gains while taxpayers bear the construction costs.' },
      { label: 'C', text: 'While proponents argue that public stadiums generate tourism, jobs, and local business activity, critics counter that the same funds could more productively be invested in schools, infrastructure, or debt reduction.' },
      { label: 'D', text: 'The debate over public stadium funding involves complex questions of economic benefit, opportunity cost, and the appropriate use of public resources.' },
    ],
    correctAnswer: 'C',
    explanation: `The goal is to present both sides' economic arguments. (C) uses "while...counter" to contrast proponents (economic activity argument) with critics (opportunity cost argument) — exactly what the task requires. (A) presents only the critics' side and endorses it. (B) presents only the critics' argument about team owners without mentioning proponents. (D) describes what the debate involves without actually voicing either economic argument.`,
    teachingPoint: `"Present both sides with economic arguments" requires the answer to explicitly voice BOTH positions using contrastive structure: "while proponents argue...critics counter."`,
    relatedSkills: ['Information and Ideas'],
  },

  {
    id: 'rw-b5c-010',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Expression of Ideas',
    skill: 'Rhetorical Synthesis',
    difficulty: 'hard',
    timeTargetSeconds: 90,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    stimulus: `A student is writing an essay about women in the history of computing. She wants to emphasize that Ada Lovelace's contributions to the Analytical Engine went beyond translation to include original analytical work developed in collaboration with Babbage. She has found the following:

• Ada Lovelace (1815–1852) worked with Charles Babbage on his Analytical Engine from approximately 1842 to 1843.
• She translated Luigi Menabrea's Italian article on the Analytical Engine, adding her own extended notes.
• Her notes contain what is now considered the first machine-executable algorithm — a method for computing Bernoulli numbers.
• Lovelace and Babbage exchanged dozens of letters discussing the Analytical Engine's potential for music composition, algebraic computation, and other applications.`,
    question: `Which choice most effectively uses the relevant information to accomplish the student's goal?`,
    choices: [
      { label: 'A', text: 'Lovelace translated Luigi Menabrea\'s article on the Analytical Engine, adding notes that were substantially longer than the original article.' },
      { label: 'B', text: 'Lovelace and Babbage corresponded extensively, with their letters revealing Lovelace\'s vision of the Analytical Engine as a machine capable of far more than numerical calculation.' },
      { label: 'C', text: 'Lovelace\'s notes on the Analytical Engine contain what is now recognized as the first machine-executable algorithm, making her a foundational figure in the history of programming.' },
      { label: 'D', text: 'Working alongside Babbage over two years of close collaboration, Lovelace developed original analytical insights into the Analytical Engine\'s design and potential, contributions that were inseparable from her role as translator.' },
    ],
    correctAnswer: 'D',
    explanation: `The goal is to emphasize that Lovelace's contributions went beyond translation to original analytical work developed in collaboration with Babbage. (D) explicitly frames her work as going "beyond translation" and as collaborative, describing "original analytical insights" developed "alongside Babbage." (A) describes the translation and its length but doesn't emphasize original analysis or collaboration. (B) focuses on the correspondence and vision but doesn't address the translation-versus-original-work distinction. (C) highlights the algorithm but frames it as her individual achievement, not as collaborative work beyond translation.`,
    teachingPoint: `When the goal has two specific components ("went beyond translation" AND "in collaboration with Babbage"), the correct answer must address both — not just one or a related but different fact.`,
    relatedSkills: ['Information and Ideas'],
  },

  {
    id: 'rw-b5c-011',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Expression of Ideas',
    skill: 'Rhetorical Synthesis',
    difficulty: 'hard',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    stimulus: `A student is writing a report on animal cognition. She wants to include a sentence that uses data to compare bottlenose dolphins and chimpanzees on the mirror self-recognition test, without drawing any conclusion about which species is more cognitively advanced. She has gathered the following information:

• Bottlenose dolphins typically pass the mirror self-recognition (MSR) test at around 7 years of age.
• Chimpanzees typically pass the MSR test between ages 4 and 4.5.
• The MSR test is considered a marker of self-awareness and is passed by very few non-human species.
• Dolphins have demonstrated problem-solving abilities comparable to great apes in certain experimental contexts.`,
    question: `Which choice most effectively uses the relevant information to accomplish the student's goal?`,
    choices: [
      { label: 'A', text: 'Bottlenose dolphins typically pass the mirror self-recognition test at around age 7, while chimpanzees generally do so between ages 4 and 4.5.' },
      { label: 'B', text: 'Because chimpanzees pass the mirror self-recognition test earlier than dolphins, chimpanzees likely develop self-awareness at a younger age than dolphins do.' },
      { label: 'C', text: 'Dolphins and chimpanzees are remarkable animals whose cognitive abilities place them among the most intelligent non-human species on Earth.' },
      { label: 'D', text: 'The mirror self-recognition test demonstrates that both dolphins and chimpanzees possess self-awareness, a cognitive capacity rare in the animal kingdom.' },
    ],
    correctAnswer: 'A',
    explanation: `The goal is to compare the performance data without drawing a conclusion about cognitive advancement. (A) presents only the data points — the ages at which each species passes — using neutral "while" to juxtapose them, with no evaluative conclusion. (B) explicitly draws a conclusion ("chimpanzees likely develop self-awareness at a younger age"), violating the constraint. (C) is too vague to be a data comparison and makes an evaluative claim. (D) draws a conclusion about self-awareness rather than simply presenting the comparative data.`,
    teachingPoint: `"Without drawing any conclusion" means the answer must present data only, using neutral comparison language ("while," "whereas") with no interpretive or evaluative language following the data.`,
    relatedSkills: ['Information and Ideas'],
  },

  {
    id: 'rw-b5c-012',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Expression of Ideas',
    skill: 'Rhetorical Synthesis',
    difficulty: 'hard',
    timeTargetSeconds: 90,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    stimulus: `A student is preparing a presentation on consumer behavior. He wants to include a sentence presenting the counterintuitive finding that adding a high-priced option to a menu can increase sales of a mid-tier option even when no one orders the expensive item. He has found the following:

• Behavioral economists call this the "decoy effect" or "asymmetric dominance."
• When restaurants add a $95 prix fixe to a menu alongside a $45 entrée and a $28 pasta, orders of the $45 entrée typically increase substantially.
• Consumers use the expensive option as a price anchor, making the mid-tier option seem like reasonable value by comparison.
• The expensive item itself rarely sells; its role is to reframe the other options.`,
    question: `Which choice most effectively uses the relevant information to accomplish the student's goal?`,
    choices: [
      { label: 'A', text: 'Restaurants often use the "decoy effect" to steer consumers toward higher-priced options, raising ethical questions about the use of behavioral economics in pricing.' },
      { label: 'B', text: 'Behavioral economists have identified a phenomenon called "asymmetric dominance" that affects consumer decision-making in retail and restaurant settings.' },
      { label: 'C', text: 'When a $95 prix fixe is added to a menu, sales of the $45 entrée often increase substantially — not because anyone orders the expensive dish, but because its presence makes the $45 option feel like reasonable value.' },
      { label: 'D', text: 'The decoy effect shows that consumers do not always choose the cheapest option, complicating standard economic models that assume rational price-minimizing behavior.' },
    ],
    correctAnswer: 'C',
    explanation: `The goal is to present the counterintuitive finding itself: adding an expensive item boosts mid-tier sales without the expensive item being ordered. (C) does this directly — it states the outcome (more $45 orders) and explains the mechanism (the $95 price makes $45 feel reasonable), capturing the counterintuitive logic precisely. (A) pivots to ethical concerns, not the finding. (B) provides the technical name but doesn't describe the counterintuitive outcome. (D) draws a broad conclusion about rationality models rather than presenting the specific phenomenon.`,
    teachingPoint: `"Present a counterintuitive finding" means the answer must state what is surprising — the outcome — AND why it happens. Neither just naming the phenomenon nor drawing broader conclusions is sufficient.`,
    relatedSkills: ['Information and Ideas'],
  },

  {
    id: 'rw-b5c-013',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Expression of Ideas',
    skill: 'Rhetorical Synthesis',
    difficulty: 'hard',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    stimulus: `A student is writing a history paper on the Apollo program. He wants to describe NASA's design philosophy, specifically that it prioritized redundancy over perfection as the primary strategy for ensuring crew safety. He has gathered the following notes:

• NASA engineers designed Apollo systems so that most critical functions had at least two or three independent backups.
• The core principle: any single component failure should not be mission- or life-threatening.
• Perfect manufacturing was considered unachievable; building in redundancy was considered achievable.
• The Apollo 13 oxygen tank failure demonstrated this philosophy: one system failed, but redundant systems enabled crew survival.`,
    question: `Which choice most effectively uses the relevant information to accomplish the student's goal?`,
    choices: [
      { label: 'A', text: 'Rather than pursuing flawless manufacturing — deemed unachievable — NASA designed Apollo systems around redundancy, ensuring that most critical functions had at least two or three independent backups so that no single failure would endanger the mission or crew.' },
      { label: 'B', text: 'The Apollo 13 mission illustrated NASA\'s engineering philosophy: when an oxygen tank failed catastrophically, redundant systems allowed the crew to survive and return safely to Earth.' },
      { label: 'C', text: 'NASA engineers acknowledged that perfect manufacturing was unachievable, which led them to recognize the limits of engineering and the inherent risks of human spaceflight.' },
      { label: 'D', text: 'Apollo spacecraft were among the most complex machines ever built, comprising millions of components that had to function reliably in the extreme environment of space.' },
    ],
    correctAnswer: 'A',
    explanation: `The goal is to describe NASA's design philosophy — specifically redundancy over perfection. (A) directly contrasts perfection (deemed unachievable) with redundancy (the actual strategy) and specifies what redundancy meant in practice (two or three backups, no single-failure threat). (B) uses Apollo 13 as an example of the philosophy in action, not a description of the philosophy itself. (C) says perfection was unachievable but wrongly implies this revealed limitations rather than drove a specific design choice. (D) describes complexity without addressing the design philosophy at all.`,
    teachingPoint: `"Describe the design philosophy" means explain what the philosophy WAS and how it worked — not an example of it in action (B) or a vague acknowledgment of its premise (C).`,
    relatedSkills: ['Information and Ideas'],
  },

  {
    id: 'rw-b5c-014',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Expression of Ideas',
    skill: 'Rhetorical Synthesis',
    difficulty: 'hard',
    timeTargetSeconds: 90,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    stimulus: `A student is writing an essay arguing that urban tree canopy programs are a cost-effective climate adaptation strategy. She wants to include a sentence using specific cost and benefit data to support her argument directly. She has gathered the following:

• Urban tree programs cost between $15 and $65 per tree to plant and establish.
• A single mature urban tree provides cooling services worth an estimated $90–$270 per year in reduced energy costs.
• Trees in urban areas can reduce building cooling energy use by 10–15%.
• Urban tree canopies also reduce stormwater runoff, improve air quality, and increase property values.`,
    question: `Which choice most effectively uses relevant information to support the student's argument?`,
    choices: [
      { label: 'A', text: 'Urban trees provide multiple benefits beyond cooling, including stormwater management, air quality improvement, and property value increases, making them a versatile urban planning tool.' },
      { label: 'B', text: 'Urban tree planting costs $15–$65 per tree, while each mature tree can yield $90–$270 in annual cooling-related energy savings, suggesting a strong long-term return on investment.' },
      { label: 'C', text: 'Urban trees can reduce building cooling energy use by 10–15%, which over time would lower energy demand citywide and reduce the urban heat island effect.' },
      { label: 'D', text: 'Because urban trees provide energy savings, stormwater management, and air quality benefits, cities should prioritize tree canopy expansion over other climate investments.' },
    ],
    correctAnswer: 'B',
    explanation: `The student's goal is to support the cost-effectiveness argument with specific cost and benefit data. (B) does this most directly: it compares the specific upfront cost ($15–$65 per tree) against the specific annual return ($90–$270 in energy savings), making the cost-effectiveness case numerically explicit. (A) lists multiple benefits without cost data — no cost comparison, so it doesn't establish cost-effectiveness. (C) gives one benefit statistic without any cost figure to compare it against. (D) lists benefits and makes a policy recommendation but provides no cost-benefit data at all.`,
    teachingPoint: `A cost-effectiveness argument requires comparing costs to returns. An answer that lists benefits without a cost figure, or states a cost without a benefit figure, is incomplete as an economic argument.`,
    relatedSkills: ['Information and Ideas'],
  },

  {
    id: 'rw-b5c-015',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Expression of Ideas',
    skill: 'Rhetorical Synthesis',
    difficulty: 'hard',
    timeTargetSeconds: 90,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    stimulus: `A student is writing a paper on language endangerment. She wants to make the case that language loss has consequences beyond the communities directly affected, appealing specifically to readers interested in scientific knowledge. She has gathered the following notes:

• Approximately 40% of the world's estimated 7,000 languages are at risk of extinction.
• Many endangered languages contain vocabulary for local plants, animals, and ecological relationships not documented in scientific literature.
• When a language dies, the ethnobotanical and ecological knowledge encoded in it often disappears permanently.
• Language loss also erodes cultural identity and community cohesion among affected populations.`,
    question: `Which choice most effectively uses the relevant information to accomplish the student's goal?`,
    choices: [
      { label: 'A', text: 'With 40% of the world\'s 7,000 languages at risk, the pace of language loss has become an urgent crisis requiring immediate intervention by governments and international organizations.' },
      { label: 'B', text: 'Language loss devastates affected communities, eroding the cultural identity and social cohesion that sustained those communities for generations.' },
      { label: 'C', text: 'Because many endangered languages encode ecological and ethnobotanical knowledge not yet documented in scientific literature, their extinction represents an irreversible loss for scientific understanding of the natural world.' },
      { label: 'D', text: 'Language researchers must act quickly to document endangered languages before the communities that speak them disappear entirely.' },
    ],
    correctAnswer: 'C',
    explanation: `The goal is to appeal to readers interested in scientific knowledge by showing consequences beyond affected communities. (C) directly addresses scientific readers: endangered languages encode scientifically valuable ecological and ethnobotanical knowledge, and their loss is irreversible for science — not just for affected communities. (A) presents the scale of crisis and makes a policy argument rather than making a scientific consequences case. (B) focuses on community impact, which is the consequence within affected communities, not beyond them. (D) is a call to action for researchers, not an argument about scientific consequences.`,
    teachingPoint: `When the target audience is "readers interested in scientific knowledge," the correct answer must frame the consequence in terms of knowledge loss, not community impact or policy urgency.`,
    relatedSkills: ['Information and Ideas'],
  },

  {
    id: 'rw-b5c-016',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Expression of Ideas',
    skill: 'Rhetorical Synthesis',
    difficulty: 'hard',
    timeTargetSeconds: 90,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    stimulus: `A student is writing a report on renewable energy transitions. He wants to conclude with a sentence that uses trend data to project continued solar growth while explicitly acknowledging that projections involve uncertainty. He has found the following:

• Global solar photovoltaic capacity grew from 40 GW in 2010 to over 1,600 GW in 2023 — a fortyfold increase.
• Annual solar capacity additions broke records each year from 2020 to 2023.
• The International Energy Agency projects solar will be the world's largest electricity source by 2035 under current policy scenarios.
• Solar costs have fallen more than 90% since 2010.`,
    question: `Which choice most effectively uses the relevant information to accomplish the student's goal?`,
    choices: [
      { label: 'A', text: 'Solar costs have fallen more than 90% since 2010, making photovoltaics the cheapest source of new electricity in most of the world and virtually guaranteeing their continued dominance of global energy markets.' },
      { label: 'B', text: 'Global solar capacity has grown more than fortyfold since 2010, and the IEA projects solar will become the world\'s largest electricity source by 2035.' },
      { label: 'C', text: 'The record-breaking pace of annual solar additions from 2020 to 2023 demonstrates the renewable energy sector\'s capacity to drive rapid decarbonization of the global economy.' },
      { label: 'D', text: 'With solar capacity having grown fortyfold since 2010 and record annual additions in recent years, the IEA projects solar could become the world\'s largest electricity source by 2035 — though that projection depends on current policy conditions continuing.' },
    ],
    correctAnswer: 'D',
    explanation: `The goal requires three elements: (1) trend data, (2) a projection of continued growth, and (3) explicit acknowledgment of uncertainty. (D) satisfies all three: it cites the fortyfold capacity growth and record additions (trend data), includes the IEA's 2035 projection (growth projection), and adds a caveat ("though that projection depends on current policy conditions continuing") that explicitly signals uncertainty. (A) provides trend data but says "virtually guaranteeing dominance" — the opposite of acknowledging uncertainty. (B) provides trend data and projection but lacks any uncertainty acknowledgment. (C) mentions trend data but makes a broad interpretive claim without any projection or uncertainty caveat.`,
    teachingPoint: `When the goal requires "explicitly acknowledging uncertainty," the correct answer must include a qualifying phrase. An answer saying "virtually guaranteeing" or making no caveat fails this criterion regardless of how much other information it includes.`,
    relatedSkills: ['Information and Ideas'],
  },

  // ─── Standard English Conventions: Boundaries (017–033) ─────────────────────

  {
    id: 'rw-b5c-017',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'hard',
    timeTargetSeconds: 65,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    stimulus: `Although the discovery of penicillin in 1928 transformed the treatment of infectious diseases ______ it also created selective pressure that would eventually produce antibiotic-resistant bacterial strains.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'diseases,' },
      { label: 'B', text: 'diseases;' },
      { label: 'C', text: 'diseases—' },
      { label: 'D', text: 'diseases' },
    ],
    correctAnswer: 'A',
    explanation: `The sentence opens with a subordinate clause introduced by "although": "Although the discovery of penicillin in 1928 transformed the treatment of infectious diseases." When a subordinate (dependent) clause precedes the main clause, standard convention requires a comma at the end of the subordinate clause. "Diseases," (A) correctly places that comma. "Diseases;" (B) is wrong — a semicolon joins two independent clauses, not a dependent and independent clause. "Diseases—" (C) is stylistically inappropriate for a standard subordinate-clause-to-main-clause transition. "Diseases" (D) omits the required comma.`,
    teachingPoint: `A subordinate clause beginning with "although," "because," "when," "if," "since," etc. that precedes the main clause must be followed by a comma. A semicolon cannot follow a dependent clause.`,
    relatedSkills: ['Standard English Conventions'],
  },

  {
    id: 'rw-b5c-018',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'hard',
    timeTargetSeconds: 65,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    stimulus: `The human eye can distinguish approximately ten million different colors ______ most languages have far fewer basic color terms, with some having as few as two.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'colors,' },
      { label: 'B', text: 'colors however' },
      { label: 'C', text: 'colors;' },
      { label: 'D', text: 'colors' },
    ],
    correctAnswer: 'C',
    explanation: `The sentence contains two independent clauses: "The human eye can distinguish approximately ten million different colors" and "most languages have far fewer basic color terms, with some having as few as two." (A) "colors," creates a comma splice — two independent clauses joined only by a comma. (B) "colors however" places a conjunctive adverb ("however") without a semicolon before it: the correct form would be "colors; however, most languages..." (D) "colors" with no punctuation creates a run-on. (C) "colors;" correctly joins two independent clauses with a semicolon.`,
    teachingPoint: `Conjunctive adverbs ("however," "therefore," "moreover") cannot join two independent clauses with only a comma before them. They require a semicolon: "[IC]; however, [IC]."`,
    relatedSkills: ['Standard English Conventions'],
  },

  {
    id: 'rw-b5c-019',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'hard',
    timeTargetSeconds: 65,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    stimulus: `The Great Wall of China — a series of fortifications built across northern China rather than a single continuous structure ______ stretches for thousands of kilometers and represents one of the most ambitious construction projects in human history.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'structure,' },
      { label: 'B', text: 'structure;' },
      { label: 'C', text: 'structure' },
      { label: 'D', text: 'structure—' },
    ],
    correctAnswer: 'D',
    explanation: `The sentence opens with "The Great Wall of China —" — an em-dash introduces the non-restrictive appositive phrase "a series of fortifications built across northern China rather than a single continuous structure." An appositive phrase opened with an em-dash must be closed with a matching em-dash before the sentence continues: "...structure— stretches for thousands of kilometers." (A) closes the em-dash phrase with a comma — mismatched punctuation. (B) uses a semicolon, which cannot close an em-dash phrase. (C) provides no closing punctuation, blending the appositive into the main clause.`,
    teachingPoint: `When a parenthetical phrase is introduced with an em-dash, it must be closed with another em-dash. You cannot mix an opening em-dash with a closing comma or semicolon.`,
    relatedSkills: ['Standard English Conventions'],
  },

  {
    id: 'rw-b5c-020',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'hard',
    timeTargetSeconds: 65,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    stimulus: `During the three decades following the end of World War II ______ many European nations rebuilt their industrial infrastructure with financial support from the United States through the Marshall Plan.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'II,' },
      { label: 'B', text: 'II;' },
      { label: 'C', text: 'II—' },
      { label: 'D', text: 'II' },
    ],
    correctAnswer: 'A',
    explanation: `"During the three decades following the end of World War II" is a long introductory prepositional phrase (ten words). Standard convention calls for a comma after a long introductory phrase before the main clause. (A) correctly provides this comma. (B) uses a semicolon, which joins two independent clauses — incorrect here because the introductory phrase is not an independent clause. (C) uses an em-dash, which is stylistically inappropriate for a standard introductory phrase. (D) omits the comma, which is required for clarity given the phrase's length.`,
    teachingPoint: `Long introductory prepositional or participial phrases (generally more than four words) require a comma before the main clause. A semicolon is never correct after an introductory phrase.`,
    relatedSkills: ['Standard English Conventions'],
  },

  {
    id: 'rw-b5c-021',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'hard',
    timeTargetSeconds: 65,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    stimulus: `Deforestation reduces a forest's capacity to absorb rainfall ______ consequently, flooding becomes more frequent and more severe in surrounding lowland areas.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'rainfall,' },
      { label: 'B', text: 'rainfall' },
      { label: 'C', text: 'rainfall and' },
      { label: 'D', text: 'rainfall;' },
    ],
    correctAnswer: 'D',
    explanation: `The sentence has two independent clauses: "Deforestation reduces a forest's capacity to absorb rainfall" and "consequently, flooding becomes more frequent and more severe in surrounding lowland areas." "Consequently" is a conjunctive adverb. When two independent clauses are connected by a conjunctive adverb, the correct punctuation is a semicolon before it: "[IC]; consequently, [IC]." (A) "rainfall," creates a comma splice. (B) "rainfall" with no punctuation creates a run-on. (C) "rainfall and consequently" incorrectly adds a coordinating conjunction before a conjunctive adverb.`,
    teachingPoint: `"Consequently," "therefore," "however," "moreover," and similar conjunctive adverbs connecting two independent clauses require a semicolon before them: "[IC]; consequently, [IC]."`,
    relatedSkills: ['Standard English Conventions'],
  },

  {
    id: 'rw-b5c-022',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'hard',
    timeTargetSeconds: 65,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    stimulus: `The economist Adam Smith ______ author of The Wealth of Nations, argued that free markets, guided by the invisible hand of competition, produce efficient outcomes without deliberate planning.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'Smith—' },
      { label: 'B', text: 'Smith' },
      { label: 'C', text: 'Smith,' },
      { label: 'D', text: 'Smith;' },
    ],
    correctAnswer: 'C',
    explanation: `"Author of The Wealth of Nations" is a non-restrictive appositive phrase renaming "Adam Smith." Since the appositive ends with a comma already in the text ("Nations,"), the phrase is closed by that existing comma — what's needed is a comma to open it after "Smith." "Smith," (C) correctly provides the opening comma for the non-restrictive appositive: "The economist Adam Smith, author of The Wealth of Nations, argued..." (A) "Smith—" opens with an em-dash but the phrase is closed with a comma, creating mismatched punctuation. (B) "Smith" provides no punctuation to set off the appositive. (D) "Smith;" uses a semicolon, which cannot introduce an appositive.`,
    teachingPoint: `Non-restrictive appositive phrases must be set off with matching punctuation on both sides. If the closing punctuation is a comma (already in the text), the opening punctuation must also be a comma.`,
    relatedSkills: ['Standard English Conventions'],
  },

  {
    id: 'rw-b5c-023',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'hard',
    timeTargetSeconds: 65,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    stimulus: `The unprecedented speed of technological change in the twenty-first century ______ has created both new opportunities and new challenges for workers across every sector of the economy.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'century,' },
      { label: 'B', text: 'century;' },
      { label: 'C', text: 'century—' },
      { label: 'D', text: 'century' },
    ],
    correctAnswer: 'D',
    explanation: `The subject of this sentence is "The unprecedented speed of technological change in the twenty-first century," and the predicate is "has created both new opportunities and new challenges for workers across every sector of the economy." No punctuation should separate a subject from its verb. (A) "century," inserts an incorrect comma between subject and verb. (B) "century;" inserts an incorrect semicolon between subject and verb. (C) "century—" inserts an incorrect em-dash between subject and verb. (D) "century" correctly provides no punctuation, allowing the sentence to flow from subject to verb without interruption.`,
    teachingPoint: `Never place a comma, semicolon, or em-dash between a simple subject and its verb, regardless of how long the subject phrase is.`,
    relatedSkills: ['Standard English Conventions'],
  },

  {
    id: 'rw-b5c-024',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'hard',
    timeTargetSeconds: 65,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    stimulus: `Exploring the deep ocean using remotely operated vehicles ______ scientists have discovered thousands of previously unknown species living in complete darkness near hydrothermal vents.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'vehicles,' },
      { label: 'B', text: 'vehicles;' },
      { label: 'C', text: 'vehicles—' },
      { label: 'D', text: 'vehicles' },
    ],
    correctAnswer: 'A',
    explanation: `"Exploring the deep ocean using remotely operated vehicles" is an introductory participial phrase that modifies "scientists." Standard convention requires a comma after an introductory participial phrase: "Exploring...vehicles, scientists have discovered..." This correctly links the phrase to the subject it modifies. (B) "vehicles;" is wrong — a semicolon cannot follow an introductory participial phrase. (C) "vehicles—" uses an em-dash, which is not the conventional punctuation for this construction. (D) "vehicles" omits the required comma, creating an unclear sentence that runs the participial phrase directly into the main clause.`,
    teachingPoint: `An introductory participial phrase ("Exploring...," "Having completed...," "Determined to...") must be followed by a comma, then the noun it modifies.`,
    relatedSkills: ['Standard English Conventions'],
  },

  {
    id: 'rw-b5c-025',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'hard',
    timeTargetSeconds: 65,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    stimulus: `The scientific method ______ requires hypotheses to be testable and falsifiable, has proven remarkably effective at generating reliable knowledge about the natural world.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'method that' },
      { label: 'B', text: 'method which' },
      { label: 'C', text: 'method, which' },
      { label: 'D', text: 'method—which' },
    ],
    correctAnswer: 'C',
    explanation: `"Requires hypotheses to be testable and falsifiable" is a non-restrictive relative clause — it provides extra information about the scientific method but is not essential to identifying which method is meant (there is only one scientific method). Non-restrictive clauses introduced by "which" must be set off by commas: "The scientific method, which requires hypotheses to be testable and falsifiable, has proven..." (C) correctly provides "method, which." (A) "method that" uses "that" — "that" introduces restrictive clauses and takes no comma; using it here is wrong. (B) "method which" omits the required preceding comma. (D) "method—which" uses an em-dash but the clause ends with a comma, creating a mismatch.`,
    teachingPoint: `"Which" introduces non-restrictive clauses and always requires commas on both sides. "That" introduces restrictive clauses and takes no commas. When the information is non-essential, use ", which."`,
    relatedSkills: ['Standard English Conventions'],
  },

  {
    id: 'rw-b5c-026',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'hard',
    timeTargetSeconds: 65,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    stimulus: `The first synthetic dye was discovered accidentally in 1856 by chemist William Perkin ______ his discovery transformed the textile industry and spurred the growth of the modern chemical industry.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'Perkin,' },
      { label: 'B', text: 'Perkin but' },
      { label: 'C', text: 'Perkin and' },
      { label: 'D', text: 'Perkin;' },
    ],
    correctAnswer: 'D',
    explanation: `The sentence has two independent clauses: "The first synthetic dye was discovered accidentally in 1856 by chemist William Perkin" and "his discovery transformed the textile industry and spurred the growth of the modern chemical industry." (A) "Perkin," creates a comma splice — a comma alone cannot join two independent clauses. (B) "Perkin but" adds a coordinating conjunction but lacks the required comma before it: the correct form would be "Perkin, but his discovery..." (C) "Perkin and" similarly lacks the required comma: "Perkin, and his discovery..." (D) "Perkin;" correctly joins the two independent clauses with a semicolon.`,
    teachingPoint: `A coordinating conjunction (FANBOYS) joining two independent clauses requires a comma immediately before it: "IC, and IC." A semicolon works without any conjunction: "IC; IC."`,
    relatedSkills: ['Standard English Conventions'],
  },

  {
    id: 'rw-b5c-027',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'hard',
    timeTargetSeconds: 65,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    stimulus: `If researchers can successfully develop a vaccine against malaria ______ millions of lives could be saved annually, particularly in sub-Saharan Africa where the disease causes the most deaths.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'malaria,' },
      { label: 'B', text: 'malaria;' },
      { label: 'C', text: 'malaria—' },
      { label: 'D', text: 'malaria' },
    ],
    correctAnswer: 'A',
    explanation: `"If researchers can successfully develop a vaccine against malaria" is a conditional subordinate clause preceding the main clause. When a subordinate clause comes before the main clause, a comma is required between them. (A) "malaria," correctly places this comma. (B) "malaria;" uses a semicolon — incorrect, because a semicolon joins two independent clauses, and a conditional "if" clause is dependent. (C) "malaria—" uses an em-dash, which is not the standard punctuation for this subordinate-to-main-clause transition. (D) "malaria" omits the required comma.`,
    teachingPoint: `Conditional "if" clauses that precede the main clause are subordinate (dependent) and must be followed by a comma. A semicolon after a dependent clause is always wrong.`,
    relatedSkills: ['Standard English Conventions'],
  },

  {
    id: 'rw-b5c-028',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'hard',
    timeTargetSeconds: 65,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    stimulus: `The human brain consumes approximately 20% of the body's energy despite representing only 2% of total body weight ______ therefore, the evolutionary pressures that expanded human cognitive capacity must have provided substantial survival advantages.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'weight,' },
      { label: 'B', text: 'weight' },
      { label: 'C', text: 'weight and' },
      { label: 'D', text: 'weight;' },
    ],
    correctAnswer: 'D',
    explanation: `The sentence has two independent clauses joined by the conjunctive adverb "therefore": "The human brain consumes approximately 20% of the body's energy despite representing only 2% of total body weight" and "the evolutionary pressures that expanded human cognitive capacity must have provided substantial survival advantages." When a conjunctive adverb connects two independent clauses, a semicolon must precede it: "[IC]; therefore, [IC]." (A) "weight," creates a comma splice before "therefore." (B) "weight" with no punctuation creates a run-on. (C) "weight and" adds a coordinating conjunction but still lacks a comma ("weight, and therefore" would be odd but "weight; therefore" is the standard form).`,
    teachingPoint: `The rule for conjunctive adverbs ("therefore," "however," "consequently," "moreover") is consistent: semicolon before, comma after — never just a comma before.`,
    relatedSkills: ['Standard English Conventions'],
  },

  {
    id: 'rw-b5c-029',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'hard',
    timeTargetSeconds: 65,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    stimulus: `Watson and Crick's 1953 paper ______ published in the journal Nature, described the double-helix structure of DNA and launched the era of molecular biology.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'paper—' },
      { label: 'B', text: 'paper' },
      { label: 'C', text: 'paper,' },
      { label: 'D', text: 'paper;' },
    ],
    correctAnswer: 'C',
    explanation: `"Published in the journal Nature" is a non-restrictive participial phrase providing additional information about the paper. Since this phrase ends with a comma already in the text ("Nature,"), the phrase must be opened with a matching comma after "paper": "Watson and Crick's 1953 paper, published in the journal Nature, described..." (C) correctly provides the opening comma. (A) "paper—" opens with an em-dash but the phrase closes with a comma — mismatched punctuation. (B) "paper" provides no opening punctuation to set off the participial phrase. (D) "paper;" uses a semicolon, which cannot introduce a participial phrase.`,
    teachingPoint: `Non-restrictive participial phrases must be set off with matching punctuation on both sides. If the closing punctuation visible in the text is a comma, the opening punctuation must also be a comma.`,
    relatedSkills: ['Standard English Conventions'],
  },

  {
    id: 'rw-b5c-030',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'hard',
    timeTargetSeconds: 65,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    stimulus: `Calcium carbonate ______ which forms the shells of marine organisms such as oysters, clams, and certain plankton, dissolves more rapidly in acidic water, threatening the survival of these species as ocean acidification accelerates.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'carbonate that' },
      { label: 'B', text: 'carbonate,' },
      { label: 'C', text: 'carbonate' },
      { label: 'D', text: 'carbonate—' },
    ],
    correctAnswer: 'B',
    explanation: `"Which forms the shells of marine organisms" is a non-restrictive relative clause — it provides extra information about calcium carbonate but is not essential to identifying the substance. Non-restrictive clauses introduced by "which" must be preceded by a comma: "Calcium carbonate, which forms the shells of marine organisms..." (B) correctly provides "carbonate," so the full phrase reads "Calcium carbonate, which forms the shells...accelerates." (A) "carbonate that" uses "that," which introduces restrictive clauses and takes no comma; this would wrongly imply there are multiple types of calcium carbonate being distinguished. (C) "carbonate" omits the required comma. (D) "carbonate—" uses an em-dash but the clause closes with a comma, creating mismatched punctuation.`,
    teachingPoint: `"Which" introduces non-restrictive (extra information) clauses and always requires a comma before it. "That" introduces restrictive (essential identification) clauses and never takes a comma before it.`,
    relatedSkills: ['Standard English Conventions'],
  },

  {
    id: 'rw-b5c-031',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'hard',
    timeTargetSeconds: 65,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    stimulus: `Because the sun provides energy for nearly all life on Earth ______ disruptions to solar output can have cascading effects on ecosystems, weather patterns, and human agriculture.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'Earth,' },
      { label: 'B', text: 'Earth;' },
      { label: 'C', text: 'Earth—' },
      { label: 'D', text: 'Earth' },
    ],
    correctAnswer: 'A',
    explanation: `"Because the sun provides energy for nearly all life on Earth" is a subordinate clause introduced by "because." When a subordinate clause precedes the main clause, a comma must follow the subordinate clause before the main clause begins. (A) "Earth," correctly provides this comma. (B) "Earth;" is wrong — a semicolon joins two independent clauses, and "Because...Earth" is a dependent clause, not independent. (C) "Earth—" uses an em-dash, which is not standard punctuation for this construction. (D) "Earth" omits the required comma.`,
    teachingPoint: `Subordinate clauses beginning with "because," "although," "when," "since," or "if" that come before the main clause must end with a comma. A semicolon after a dependent clause is always an error.`,
    relatedSkills: ['Standard English Conventions'],
  },

  {
    id: 'rw-b5c-032',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'hard',
    timeTargetSeconds: 65,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    stimulus: `The rate at which polar ice sheets are melting ______ has accelerated dramatically over the past three decades due to rising global temperatures.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'melting,' },
      { label: 'B', text: 'melting;' },
      { label: 'C', text: 'melting—' },
      { label: 'D', text: 'melting' },
    ],
    correctAnswer: 'D',
    explanation: `The subject of this sentence is "The rate at which polar ice sheets are melting" — a noun phrase with an embedded relative clause. The predicate is "has accelerated dramatically over the past three decades." No punctuation should separate a subject from its predicate. (A) "melting," places an incorrect comma between subject and verb. (B) "melting;" places an incorrect semicolon between subject and verb. (C) "melting—" places an incorrect em-dash between subject and verb. (D) "melting" correctly provides no punctuation, allowing the subject to flow naturally into its predicate.`,
    teachingPoint: `Even when the subject phrase is long or complex (as with embedded relative clauses), no punctuation should be inserted between the subject and its verb.`,
    relatedSkills: ['Standard English Conventions'],
  },

  {
    id: 'rw-b5c-033',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'hard',
    timeTargetSeconds: 65,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    stimulus: `The philosopher Immanuel Kant ______ whose Critique of Pure Reason remains one of the most demanding works in Western philosophy, argued that the structure of human cognition shapes our experience of reality.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'Kant—' },
      { label: 'B', text: 'Kant' },
      { label: 'C', text: 'Kant,' },
      { label: 'D', text: 'Kant;' },
    ],
    correctAnswer: 'C',
    explanation: `"Whose Critique of Pure Reason remains one of the most demanding works in Western philosophy" is a non-restrictive relative clause modifying "Immanuel Kant." The clause must be set off with commas on both sides, and since it ends with a comma already in the text ("philosophy,"), the opening punctuation must also be a comma: "Immanuel Kant, whose Critique of Pure Reason...philosophy, argued..." (C) correctly provides the opening comma. (A) "Kant—" uses an em-dash as the opening but the phrase closes with a comma — mismatched. (B) "Kant" provides no punctuation to open the non-restrictive clause. (D) "Kant;" uses a semicolon, which cannot introduce a relative clause.`,
    teachingPoint: `Non-restrictive "whose" clauses must be set off with commas on both sides. Match the opening punctuation to the closing punctuation: if the clause ends with a comma, it must open with a comma.`,
    relatedSkills: ['Standard English Conventions'],
  },

  // ─── Standard English Conventions: Form, Structure, and Sense (034–050) ──────

  {
    id: 'rw-b5c-034',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'hard',
    timeTargetSeconds: 65,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    stimulus: `The number of wild tiger subspecies recognized by conservationists ______ from nine in the twentieth century to six today due to extinction, habitat loss, and taxonomic reclassification.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'have declined' },
      { label: 'B', text: 'are declining' },
      { label: 'C', text: 'has declined' },
      { label: 'D', text: 'were declining' },
    ],
    correctAnswer: 'C',
    explanation: `The subject is "The number" — a singular noun phrase. "Of wild tiger subspecies" is a prepositional phrase modifying "number," not the subject itself. The verb must agree with the singular "number": "has declined." (A) "have declined" is plural — incorrect for singular "number." (B) "are declining" is present progressive and plural. (D) "were declining" is past progressive — both the tense and number are wrong. (C) "has declined" correctly uses the singular present perfect to describe a change that began in the past and persists to the present.`,
    teachingPoint: `"The number of [plural noun]" is singular — it takes a singular verb. "A number of [plural noun]" is plural. Don't be distracted by the plural noun in the prepositional phrase.`,
    relatedSkills: ['Standard English Conventions'],
  },

  {
    id: 'rw-b5c-035',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'hard',
    timeTargetSeconds: 65,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    stimulus: `Neither the project director nor the senior engineers ______ consulted before the decision to restructure the department was announced to staff.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'were' },
      { label: 'B', text: 'was' },
      { label: 'C', text: 'have been' },
      { label: 'D', text: 'are' },
    ],
    correctAnswer: 'A',
    explanation: `With "neither...nor" constructions, the verb agrees with the subject closest to the verb — the proximity rule. The subject nearest the verb is "the senior engineers," which is plural. Therefore, the verb must be plural: "were consulted." (B) "was" agrees with the singular "project director," but proximity requires agreement with the nearest subject ("engineers"). (C) "have been" is plural present perfect — wrong tense for this past-tense context. (D) "are" is present tense — wrong tense.`,
    teachingPoint: `With "neither...nor" and "either...or," the verb agrees with the subject CLOSEST to it. Here, "senior engineers" (plural) is closest, so use "were."`,
    relatedSkills: ['Standard English Conventions'],
  },

  {
    id: 'rw-b5c-036',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'hard',
    timeTargetSeconds: 65,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    stimulus: `The architect designed the new community center to be energy efficient, architecturally distinctive, and ______ by the surrounding neighborhood.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'embracing' },
      { label: 'B', text: 'to be embraced' },
      { label: 'C', text: 'that is embraced' },
      { label: 'D', text: 'embraced' },
    ],
    correctAnswer: 'D',
    explanation: `The sentence lists three adjectives describing the community center: "energy efficient," "architecturally distinctive," and the third item. All three follow "to be" and must be in parallel form — adjectives or participial adjectives. "Embraced" (D) is a past participle functioning as an adjective, parallel with "efficient" and "distinctive": "to be energy efficient, architecturally distinctive, and embraced by the surrounding neighborhood." (A) "embracing" is a present participle — it would mean the center is doing the embracing, not being embraced. (B) "to be embraced" redundantly repeats "to be," breaking parallel structure. (C) "that is embraced" introduces a relative clause, not an adjective.`,
    teachingPoint: `In a parallel list after "to be X, Y, and Z," all items must be the same grammatical form. Adjectives and past-participial adjectives are parallel; gerunds and relative clauses are not.`,
    relatedSkills: ['Standard English Conventions'],
  },

  {
    id: 'rw-b5c-037',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'hard',
    timeTargetSeconds: 65,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    stimulus: `Everyone who attended the international climate summit ______ asked to commit to a specific emissions reduction target before the conclusion of the conference.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'was' },
      { label: 'B', text: 'were' },
      { label: 'C', text: 'have been' },
      { label: 'D', text: 'are' },
    ],
    correctAnswer: 'A',
    explanation: `The subject is "Everyone" — an indefinite pronoun that is always singular in standard formal usage. The relative clause "who attended the international climate summit" modifies "Everyone" but does not change its number. The verb must be singular: "was asked." (B) "were" is plural — incorrect for singular "everyone." (C) "have been" is plural present perfect — wrong number and tense for this past context. (D) "are" is present tense plural — doubly incorrect.`,
    teachingPoint: `Indefinite pronouns — "everyone," "everyone," "anyone," "someone," "nobody," "each," "every" — are singular and require singular verbs, regardless of any plural nouns in modifying phrases.`,
    relatedSkills: ['Standard English Conventions'],
  },

  {
    id: 'rw-b5c-038',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'hard',
    timeTargetSeconds: 65,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    stimulus: `By the time the archaeologists excavated the site, previous looters ______ most of the artifacts of greatest historical value.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'have already removed' },
      { label: 'B', text: 'are already removing' },
      { label: 'C', text: 'had already removed' },
      { label: 'D', text: 'were already removing' },
    ],
    correctAnswer: 'C',
    explanation: `The phrase "By the time the archaeologists excavated the site" establishes a past reference point. The looting occurred before that excavation — one past action completed before another past action. The past perfect tense ("had + past participle") is required to indicate that the looting was completed before the reference point. (C) "had already removed" correctly uses the past perfect. (A) "have already removed" is present perfect — wrong for a past sequence. (B) "are already removing" is present progressive — wrong tense entirely. (D) "were already removing" is past progressive, which implies the looting was still ongoing at the moment of excavation, contradicting the context.`,
    teachingPoint: `"By the time [past event]" signals a sequence: use past perfect (had + past participle) for the action that was completed first.`,
    relatedSkills: ['Standard English Conventions'],
  },

  {
    id: 'rw-b5c-039',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'hard',
    timeTargetSeconds: 65,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    stimulus: `Having reviewed the experimental data carefully, ______ three anomalous data points that did not conform to the predicted model.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'the researchers identified' },
      { label: 'B', text: 'three anomalous data points were identified' },
      { label: 'C', text: 'the identification was made of' },
      { label: 'D', text: 'the experimental results showed' },
    ],
    correctAnswer: 'A',
    explanation: `The introductory participial phrase "Having reviewed the experimental data carefully" must modify the grammatical subject of the main clause — the subject must be the entity that reviewed the data. Only "the researchers" (A) can logically review data. (B) makes "three anomalous data points" the subject — data points cannot review data, creating a dangling modifier. (C) "the identification was made of" is passive and vague, and an identification cannot review data. (D) "the experimental results showed" makes results the subject — results do not review data.`,
    teachingPoint: `An introductory participial phrase modifies the subject of the main clause. The subject immediately after the comma must be the logical doer of the action described in the phrase. If not, it's a dangling modifier.`,
    relatedSkills: ['Standard English Conventions'],
  },

  {
    id: 'rw-b5c-040',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'hard',
    timeTargetSeconds: 65,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    stimulus: `When a student encounters an unfamiliar word while reading, ______ should use context clues to infer the meaning before consulting a dictionary.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'you' },
      { label: 'B', text: 'they' },
      { label: 'C', text: 'we' },
      { label: 'D', text: 'he or she' },
    ],
    correctAnswer: 'D',
    explanation: `The antecedent is "a student" — a singular third-person noun. In formal Standard English, the pronoun must agree in number and person with its antecedent. "He or she" (D) is singular and third-person, correctly matching "a student." (A) "you" is second-person — a shift in person from "a student." (B) "they" is plural in formal Standard English, and "a student" is singular. (C) "we" is first-person plural — wrong in both person and number for "a student."`,
    teachingPoint: `In formal Standard English writing, a singular antecedent like "a student" or "a person" requires a singular pronoun ("he or she"). Pronoun-antecedent agreement errors most often involve number (singular vs. plural) or person (first, second, third).`,
    relatedSkills: ['Standard English Conventions'],
  },

  {
    id: 'rw-b5c-041',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'hard',
    timeTargetSeconds: 65,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    stimulus: `The committee spent six months ______ the most effective approach to reducing urban air pollution without imposing undue burdens on local businesses.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'to evaluate' },
      { label: 'B', text: 'evaluating' },
      { label: 'C', text: 'for evaluating' },
      { label: 'D', text: 'evaluate' },
    ],
    correctAnswer: 'B',
    explanation: `The idiom "spend [time] doing something" requires a gerund (an -ing verb form) after the time expression. "Spent six months evaluating" is the correct idiomatic construction. (A) "to evaluate" is an infinitive — the idiom does not accept "spent time to do something." (C) "for evaluating" adds an unnecessary preposition — the idiom is "spend time [gerund]," not "spend time for [gerund]." (D) "evaluate" is a bare infinitive — also not correct in this idiom.`,
    teachingPoint: `"Spend time [doing something]" requires a gerund (-ing form), not an infinitive or bare verb: "spent six months evaluating," not "spent six months to evaluate."`,
    relatedSkills: ['Standard English Conventions'],
  },

  {
    id: 'rw-b5c-042',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'hard',
    timeTargetSeconds: 65,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    stimulus: `The jury ______ deliberating for three days before the judge dismissed the members for the weekend, instructing them to return Monday morning.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'was' },
      { label: 'B', text: 'were' },
      { label: 'C', text: 'have been' },
      { label: 'D', text: 'are' },
    ],
    correctAnswer: 'A',
    explanation: `"The jury" is a collective noun. In American English, collective nouns (jury, team, committee, faculty) are treated as singular entities and take singular verbs. The correct past progressive form is "was deliberating." (B) "were deliberating" uses a plural verb — this would be correct in British English but not American Standard English. (C) "have been deliberating" is present perfect plural — wrong tense and number. (D) "are deliberating" is present tense plural — both tense and number are wrong.`,
    teachingPoint: `In American English, collective nouns ("jury," "team," "committee," "government") take singular verbs: "The jury was deliberating," not "were deliberating."`,
    relatedSkills: ['Standard English Conventions'],
  },

  {
    id: 'rw-b5c-043',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'hard',
    timeTargetSeconds: 65,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    stimulus: `The new environmental regulations require manufacturers to reduce emissions, improve energy efficiency, and ______ comprehensive sustainability reports to regulators each quarter.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'submitting' },
      { label: 'B', text: 'for submitting' },
      { label: 'C', text: 'have submitted' },
      { label: 'D', text: 'submit' },
    ],
    correctAnswer: 'D',
    explanation: `The sentence lists three things manufacturers are required to do: "to reduce emissions," "improve energy efficiency," and the third item. All three follow from "require manufacturers to" and must be parallel bare infinitives: "to reduce," "improve," and "submit." (D) "submit" correctly maintains this parallel structure. (A) "submitting" is a gerund — not parallel with "reduce" and "improve." (B) "for submitting" adds an unnecessary preposition. (C) "have submitted" is present perfect — not parallel with the infinitives.`,
    teachingPoint: `In a list after "require [someone] to X, Y, and Z," all items must be bare infinitives (no "to" repeated). "To reduce, improve, and submit" — not "reduce, improve, and submitting."`,
    relatedSkills: ['Standard English Conventions'],
  },

  {
    id: 'rw-b5c-044',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'hard',
    timeTargetSeconds: 65,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    stimulus: `The research grant was awarded to the scientist ______ the committee selected after a rigorous six-month peer review process.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'which' },
      { label: 'B', text: 'whoever' },
      { label: 'C', text: 'whom' },
      { label: 'D', text: 'who' },
    ],
    correctAnswer: 'C',
    explanation: `The relative pronoun refers to "the scientist" and serves as the object of "selected" in the relative clause: "the committee selected [him/her]." Because the pronoun is in the object position, the object form "whom" is required. (C) is correct: "the scientist whom the committee selected." (A) "which" refers to things, not people. (B) "whoever" is a pronoun meaning "any person who" — it cannot function as the object of a relative clause modifying "scientist." (D) "who" is the subject form — correct when the pronoun is a subject ("the scientist who won"), but here it is the object of "selected."`,
    teachingPoint: `"Who" is subject case (the scientist who won); "whom" is object case (the scientist whom the committee selected). Test by substituting he/him: "the committee selected him" → use "whom."`,
    relatedSkills: ['Standard English Conventions'],
  },

  {
    id: 'rw-b5c-045',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'hard',
    timeTargetSeconds: 65,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    stimulus: `One of the most significant challenges facing marine ecosystems ______ the rapid acidification of ocean water caused by increased absorption of atmospheric carbon dioxide.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'is' },
      { label: 'B', text: 'are' },
      { label: 'C', text: 'have been' },
      { label: 'D', text: 'were' },
    ],
    correctAnswer: 'A',
    explanation: `The subject of the sentence is "One" — a singular indefinite pronoun. "Of the most significant challenges facing marine ecosystems" is a prepositional phrase modifying "One" but not serving as the subject. The verb must agree with the singular "One": "is." (B) "are" is plural, incorrectly agreeing with "challenges" in the prepositional phrase. (C) "have been" is plural present perfect — wrong in number and unnecessarily complex in tense. (D) "were" is plural past — doubly incorrect.`,
    teachingPoint: `"One of the [plural noun]" — the subject is "one" (singular), not the plural noun in the prepositional phrase. Always use a singular verb: "one of the challenges is," not "are."`,
    relatedSkills: ['Standard English Conventions'],
  },

  {
    id: 'rw-b5c-046',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'hard',
    timeTargetSeconds: 65,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    stimulus: `If the researchers ______ a larger sample size, they might have detected the subtle correlation that smaller studies consistently missed.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'used' },
      { label: 'B', text: 'use' },
      { label: 'C', text: 'have used' },
      { label: 'D', text: 'had used' },
    ],
    correctAnswer: 'D',
    explanation: `The sentence is a past counterfactual conditional: it describes a hypothetical scenario in the past that did not actually happen. The construction for past counterfactuals is "If [subject] had + past participle, [subject] would have + past participle." "Had used" (D) correctly completes the past counterfactual: "If the researchers had used a larger sample size, they might have detected..." (A) "used" simple past — this would form a mixed conditional where "if they used" doesn't clearly signal a past counterfactual. (B) "use" is present tense — wrong for a past scenario. (C) "have used" is present perfect — wrong for this past counterfactual structure.`,
    teachingPoint: `Past counterfactual conditionals require past perfect in the "if" clause: "If [subject] had [past participle]...would/might have [past participle]."`,
    relatedSkills: ['Standard English Conventions'],
  },

  {
    id: 'rw-b5c-047',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'hard',
    timeTargetSeconds: 65,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    stimulus: `The university announced that ______ new interdisciplinary research center would house faculty from the departments of physics, biology, computer science, and environmental studies.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'their' },
      { label: 'B', text: 'a' },
      { label: 'C', text: 'its' },
      { label: 'D', text: 'our' },
    ],
    correctAnswer: 'C',
    explanation: `The antecedent of the possessive pronoun is "the university" — a singular institutional noun. In American English, institutions are treated as singular entities and take the singular pronoun "its." (C) "its new interdisciplinary research center" correctly uses the singular possessive. (A) "their" is plural — in American English, a university takes "its," not "their." (B) "a" is an indefinite article — it could be grammatically acceptable but fails to establish the possessive relationship showing the center belongs to the university. (D) "our" is first-person plural — a shift in person from the third-person "the university."`,
    teachingPoint: `Institutional nouns (university, company, government, committee) take singular pronouns in American English: "its" not "their." "Their" is used for groups of people, not institutions treated as single entities.`,
    relatedSkills: ['Standard English Conventions'],
  },

  {
    id: 'rw-b5c-048',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'hard',
    timeTargetSeconds: 65,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    stimulus: `During the presentation, the lead scientist explained the methodology, presented the key findings, and ______ several potential applications for the research in clinical settings.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'is identifying' },
      { label: 'B', text: 'identifies' },
      { label: 'C', text: 'had identified' },
      { label: 'D', text: 'identified' },
    ],
    correctAnswer: 'D',
    explanation: `The sentence lists three things the scientist did during the presentation: "explained the methodology," "presented the key findings," and the third action. All three must be in the same tense — simple past — to maintain parallel structure and tense consistency. (D) "identified" is simple past, matching "explained" and "presented." (A) "is identifying" shifts to present progressive, breaking both tense consistency and parallel structure. (B) "identifies" shifts to present tense. (C) "had identified" is past perfect — inconsistent with the simple past verbs that precede it.`,
    teachingPoint: `In a list of parallel verbs describing the same past event ("explained...presented...and ___"), all verbs must use the same tense. Mixing tenses breaks parallel structure.`,
    relatedSkills: ['Standard English Conventions'],
  },

  {
    id: 'rw-b5c-049',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'hard',
    timeTargetSeconds: 65,
    mistakeType: 'concept error',
    questionType: 'multiple_choice',
    stimulus: `The ancient Romans were remarkable ______ their ability to absorb and adapt the cultural practices of the peoples they conquered throughout the Mediterranean world.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'about' },
      { label: 'B', text: 'by' },
      { label: 'C', text: 'for' },
      { label: 'D', text: 'in' },
    ],
    correctAnswer: 'C',
    explanation: `The correct idiomatic expression is "remarkable for [something]," meaning notable or distinguished by that quality. "The Romans were remarkable for their ability to adapt" is standard English idiom. (A) "remarkable about" is not standard English — "about" introduces a topic, not a distinguishing quality. (B) "remarkable by" is nonstandard — "by" indicates means or agent, not a distinguishing attribute. (D) "remarkable in their ability" is a plausible but less standard alternative; "for" is the established preposition in this idiom.`,
    teachingPoint: `"Remarkable for [quality]" is the standard English idiom meaning "notable or distinguished by." Other prepositions (about, by, in) are either wrong or nonstandard in this construction.`,
    relatedSkills: ['Standard English Conventions'],
  },

  {
    id: 'rw-b5c-050',
    test: 'SAT',
    section: 'reading-writing',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'hard',
    timeTargetSeconds: 65,
    mistakeType: 'trap answer',
    questionType: 'multiple_choice',
    stimulus: `The use of renewable energy sources and the development of more efficient battery storage technology ______ expected to play a central role in reducing global greenhouse gas emissions over the coming decade.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'is' },
      { label: 'B', text: 'has been' },
      { label: 'C', text: 'was' },
      { label: 'D', text: 'are' },
    ],
    correctAnswer: 'D',
    explanation: `The subject of this sentence is a compound subject joined by "and": "The use of renewable energy sources" AND "the development of more efficient battery storage technology." Two subjects joined by "and" form a plural compound subject, requiring a plural verb: "are expected." (A) "is" is singular — incorrect for a compound subject. (B) "has been" is singular present perfect — wrong in both number and tense. (C) "was" is singular past — wrong in number, and past tense is inappropriate for a forward-looking projection.`,
    teachingPoint: `Two subjects joined by "and" form a compound subject that requires a plural verb. "The use...and the development...are" — not "is."`,
    relatedSkills: ['Standard English Conventions'],
  },
]
