import type { MCATQBQuestion } from './types'

// C/P QB Shard 3 — questions mcat-qb-cp-151 through mcat-qb-cp-180 (30 questions)

const WAVES_PASSAGE = `A researcher studies wave phenomena using a string under tension and a sound source. A standing wave is produced on a string of length L = 1.2 m fixed at both ends. The wave speed on the string is v = 120 m/s.

Key wave relationships:
- λₙ = 2L/n for a string fixed at both ends (n = 1, 2, 3…)
- fₙ = nv/(2L) (harmonic frequencies)
- Intensity: I = P/(4πr²) for a point source
- Decibels: β = 10 log(I/I₀) where I₀ = 10⁻¹² W/m²`

const CIRCUIT_PASSAGE = `A student builds a series RC circuit with R = 1000 Ω and C = 100 μF (100 × 10⁻⁶ F). The circuit is driven by a 12 V DC battery.

Key relationships:
- Series circuit: same current through all elements
- Capacitor charge: Q = CV; energy stored: U = ½CV² = Q²/(2C)
- RC time constant: τ = RC (time to reach 63% of final charge)
- Resistors in series: R_total = R₁ + R₂ + …
- Capacitors in parallel: C_total = C₁ + C₂ + …`

const AMINO_ACIDS_PASSAGE = `A biochemist studies amino acid properties and peptide chemistry. The 20 standard amino acids differ in their side chain (R group) properties, which determine protein structure and function.

Key concepts:
- Peptide bond: formed between α-carboxyl of one amino acid and α-amino of the next; releases water (dehydration condensation)
- pKa values: α-COOH ≈ 2, α-NH₃⁺ ≈ 9, side chains vary
- At physiological pH (7.4), most proteins carry net negative charge (above the pI of most amino acids)
- Primary structure → secondary (α-helix, β-sheet) → tertiary (overall folding) → quaternary (subunit assembly)`

const OXIDATION_PASSAGE = `A chemistry student investigates oxidation states and redox reactions. The following half-reactions are observed:

MnO₄⁻ + 8H⁺ + 5e⁻ → Mn²⁺ + 4H₂O    E° = +1.51 V
Fe³⁺ + e⁻ → Fe²⁺                           E° = +0.77 V
Cr₂O₇²⁻ + 14H⁺ + 6e⁻ → 2Cr³⁺ + 7H₂O  E° = +1.33 V

The student is performing a titration and uses KMnO₄ to oxidize Fe²⁺ in acidic solution.`

const PERIODIC_TRENDS_PASSAGE = `Periodic trends describe systematic changes in atomic properties as one moves across or down the periodic table.

Key trends:
- Atomic radius: increases down a group (more electron shells); decreases across a period (increasing nuclear charge pulls electrons closer)
- Ionization energy (IE): increases across a period, decreases down a group; first IE < second IE
- Electronegativity: increases across a period, decreases down (Pauling scale: F = 4.0, highest)
- Electron affinity: generally increases across a period (exceptions: noble gases, half-filled subshells)
- Ionic radius: cations smaller than parent atoms; anions larger than parent atoms`

export const chemPhysQuestions3: MCATQBQuestion[] = [
  // ── Waves & Sound (Q151–Q154) ─────────────────────────────────────────────
  {
    id: 'mcat-qb-cp-151',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'Physics',
    contentCategory: '4C: Waves',
    foundationalConcept: '4: Physical processes',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    questionType: 'passage',
    passageText: WAVES_PASSAGE,
    question: 'What is the fundamental frequency (first harmonic) of the 1.2 m string?',
    choices: [
      { label: 'A', text: '25 Hz' },
      { label: 'B', text: '50 Hz' },
      { label: 'C', text: '100 Hz' },
      { label: 'D', text: '200 Hz' },
    ],
    correctAnswer: 'B',
    explanation: 'Fundamental (n=1): f₁ = v/(2L) = 120 m/s / (2 × 1.2 m) = 120/2.4 = 50 Hz. Equivalently: λ₁ = 2L = 2.4 m, f = v/λ = 120/2.4 = 50 Hz.',
    wrongAnswerExplanations: {
      A: '25 Hz = v/(2L) only if L = 2.4 m or v = 60 m/s. Check: 120/(2×1.2) = 50 Hz, not 25.',
      C: '100 Hz would be the second harmonic (n=2): f₂ = 2f₁ = 2 × 50 = 100 Hz.',
      D: '200 Hz would be the fourth harmonic (n=4).',
    },
    teachingPoint: 'Standing wave on string fixed at both ends: λₙ = 2L/n, fₙ = nv/(2L). Fundamental (n=1): f₁ = v/(2L). Harmonics: f₂ = 2f₁, f₃ = 3f₁. Open pipe (open both ends): same as string. Closed pipe (closed one end): fₙ = nv/(4L), n = odd only.',
    relatedTopics: ['standing wave fundamental frequency', 'harmonic string', 'wave speed frequency wavelength'],
  },
  {
    id: 'mcat-qb-cp-152',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'Physics',
    contentCategory: '4C: Waves',
    foundationalConcept: '4: Physical processes',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    questionType: 'passage',
    passageText: WAVES_PASSAGE,
    question: 'A 1.0 W point source of sound is heard at 4 m away. What is the intensity at 4 m?',
    choices: [
      { label: 'A', text: '0.05 W/m²' },
      { label: 'B', text: '0.02 W/m²' },
      { label: 'C', text: '5.0 × 10⁻³ W/m²' },
      { label: 'D', text: '1.25 × 10⁻² W/m²' },
    ],
    correctAnswer: 'C',
    explanation: 'I = P/(4πr²) = 1.0 / (4π × 4²) = 1.0 / (4π × 16) = 1.0 / (64π) ≈ 1.0 / 201 ≈ 5 × 10⁻³ W/m².',
    wrongAnswerExplanations: {
      A: '0.05 W/m²: P/(4πr²) with r=2 gives ~0.02 W/m². With r=4: ~0.005. Check: 1/(4π×16) = 1/201 ≈ 0.005.',
      B: '0.02 W/m²: 1/(4π×r²) = 0.02 → r² = 1/(0.02 × 4π) = 1/0.251 ≈ 4 → r ≈ 2 m, not 4 m.',
      D: '0.0125 W/m² = 1/(4×4×π/something) — arithmetic error. Correct: 1/(64π) ≈ 0.005.',
    },
    teachingPoint: 'Intensity of point source: I = P/(4πr²). Inverse square law: doubling distance → intensity/4. Decibel scale: β = 10 log(I/I₀). Threshold of hearing I₀ = 10⁻¹² W/m². Pain threshold ≈ 1 W/m² = 120 dB.',
    relatedTopics: ['sound intensity inverse square', 'point source intensity', 'I = P/4πr²'],
  },
  {
    id: 'mcat-qb-cp-153',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'Physics',
    contentCategory: '4C: Waves',
    foundationalConcept: '4: Physical processes',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    questionType: 'passage',
    passageText: WAVES_PASSAGE,
    question: 'A stethoscope amplifies sounds with an intensity of 10⁻⁸ W/m² to the physician. What is this intensity in decibels?',
    choices: [
      { label: 'A', text: '40 dB' },
      { label: 'B', text: '80 dB' },
      { label: 'C', text: '60 dB' },
      { label: 'D', text: '20 dB' },
    ],
    correctAnswer: 'A',
    explanation: 'β = 10 log(I/I₀) = 10 log(10⁻⁸/10⁻¹²) = 10 log(10⁴) = 10 × 4 = 40 dB.',
    wrongAnswerExplanations: {
      B: '80 dB would correspond to I = 10⁻⁴ W/m² (10 log(10⁻⁴/10⁻¹²) = 10 × 8 = 80 dB).',
      C: '60 dB corresponds to I = 10⁻⁶ W/m².',
      D: '20 dB corresponds to I = 10⁻¹⁰ W/m².',
    },
    teachingPoint: 'Decibel shortcut: I = 10^(−12+n) W/m² → β = 10n dB. I = 10⁻⁸: 10⁻¹²⁺⁴ → 40 dB. Each 10 dB = 10× intensity. Each 3 dB ≈ 2× intensity. 0 dB = threshold of hearing. 120 dB = threshold of pain.',
    relatedTopics: ['decibel calculation', 'sound intensity dB', 'β = 10 log I/I₀'],
  },
  {
    id: 'mcat-qb-cp-154',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'Physics',
    contentCategory: '4C: Waves',
    foundationalConcept: '4: Physical processes',
    scientificSkill: 'Skill 1',
    difficulty: 'medium',
    questionType: 'passage',
    passageText: WAVES_PASSAGE,
    question: 'An ambulance siren moves toward a stationary observer. Compared to when the ambulance was stationary, the observed frequency is:',
    choices: [
      { label: 'A', text: 'Lower — the sound waves are stretched out' },
      { label: 'B', text: 'Higher — the sound waves are compressed, increasing frequency' },
      { label: 'C', text: 'Unchanged — Doppler effect only affects wavelength, not frequency' },
      { label: 'D', text: 'Lower — the amplitude decreases as the source moves' },
    ],
    correctAnswer: 'B',
    explanation: 'Doppler effect: when a sound source approaches a stationary observer, each successive wave crest is emitted from a position closer to the observer → waves are compressed → shorter wavelength → higher frequency. f_observed = f_source × (v/(v − v_source)). When source approaches: denominator < v → f_observed > f_source.',
    wrongAnswerExplanations: {
      A: 'Waves are stretched (longer λ, lower f) when the source MOVES AWAY from the observer. Approaching source → compressed waves → higher frequency.',
      C: 'Doppler effect changes BOTH wavelength AND frequency (they are related by f = v/λ). Wavelength change directly produces frequency change.',
      D: 'Amplitude (loudness) changes with distance but is not the Doppler effect. Approaching source does increase amplitude (closer = louder), but the Doppler effect specifically refers to frequency change.',
    },
    teachingPoint: 'Doppler effect: source approaches → f increases (compressed waves). Source recedes → f decreases (stretched waves). Medical Doppler ultrasound: measures blood flow velocity by detecting frequency shift of reflected ultrasound (red cells move toward/away from transducer).',
    relatedTopics: ['Doppler effect', 'ambulance siren frequency', 'sound source approaching observer'],
  },

  // ── RC Circuits (Q155–Q158) ───────────────────────────────────────────────
  {
    id: 'mcat-qb-cp-155',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'Physics',
    contentCategory: '4E: Electricity and circuits',
    foundationalConcept: '4: Physical processes',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    questionType: 'passage',
    passageText: CIRCUIT_PASSAGE,
    question: 'What is the RC time constant for this circuit?',
    choices: [
      { label: 'A', text: '0.1 seconds' },
      { label: 'B', text: '10 seconds' },
      { label: 'C', text: '0.01 seconds' },
      { label: 'D', text: '1000 seconds' },
    ],
    correctAnswer: 'A',
    explanation: 'τ = RC = (1000 Ω)(100 × 10⁻⁶ F) = (10³)(10⁻⁴) = 10⁻¹ = 0.1 seconds.',
    wrongAnswerExplanations: {
      B: '10 seconds would require τ = 10 → R × C = 10 → R = 10/(100 × 10⁻⁶) = 10⁵ Ω. Not correct for R = 1000 Ω.',
      C: '0.01 s = 10⁻² = RC if R = 100 Ω or C = 10 μF. With R = 1000 Ω and C = 100 μF: RC = 0.1 s.',
      D: '1000 s would require a much larger RC product than (10³)(10⁻⁴) = 0.1.',
    },
    teachingPoint: 'RC time constant τ = RC (units: seconds). At t = τ: capacitor reaches ~63% of final charge. At t = 5τ: ~99% charged (fully charged for practical purposes). τ = 0.1 s means the capacitor is 63% charged after 0.1 s and 99% charged after 0.5 s.',
    relatedTopics: ['RC time constant', 'capacitor charging time', 'τ = RC'],
  },
  {
    id: 'mcat-qb-cp-156',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'Physics',
    contentCategory: '4E: Electricity and circuits',
    foundationalConcept: '4: Physical processes',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    questionType: 'passage',
    passageText: CIRCUIT_PASSAGE,
    question: 'Once fully charged, what is the energy stored in the capacitor?',
    choices: [
      { label: 'A', text: '7.2 × 10⁻³ J' },
      { label: 'B', text: '1.44 × 10⁻² J' },
      { label: 'C', text: '7.2 × 10⁻² J' },
      { label: 'D', text: '1.2 × 10⁻³ J' },
    ],
    correctAnswer: 'A',
    explanation: 'When fully charged, V_C = V_battery = 12 V. U = ½CV² = ½ × (100 × 10⁻⁶ F) × (12 V)² = ½ × 10⁻⁴ × 144 = ½ × 1.44 × 10⁻² = 7.2 × 10⁻³ J.',
    wrongAnswerExplanations: {
      B: '1.44 × 10⁻² J = CV² (without the ½ factor). Energy stored = ½CV², not CV².',
      C: '7.2 × 10⁻² J = 10× too large — likely used C = 1000 μF or made a decimal error.',
      D: '1.2 × 10⁻³ J = ½ × 10⁻⁴ × (144/12) — error using V = 12 without squaring it.',
    },
    teachingPoint: 'Capacitor energy: U = ½CV² = Q²/(2C) = QV/2. V when fully charged = source voltage (no current through fully charged capacitor means no voltage drop across resistor → all voltage across capacitor). Units: ½ × F × V² = ½ × (C/V) × V² = ½ C·V = J.',
    relatedTopics: ['capacitor energy stored', 'U = ½CV²', 'fully charged capacitor voltage'],
  },
  {
    id: 'mcat-qb-cp-157',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'Physics',
    contentCategory: '4E: Electricity and circuits',
    foundationalConcept: '4: Physical processes',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    questionType: 'passage',
    passageText: CIRCUIT_PASSAGE,
    question: 'Two identical resistors (each 1000 Ω) are connected in parallel. What is the total resistance?',
    choices: [
      { label: 'A', text: '2000 Ω' },
      { label: 'B', text: '1000 Ω' },
      { label: 'C', text: '500 Ω' },
      { label: 'D', text: '250 Ω' },
    ],
    correctAnswer: 'C',
    explanation: 'Parallel resistors: 1/R_total = 1/R₁ + 1/R₂ = 1/1000 + 1/1000 = 2/1000. R_total = 1000/2 = 500 Ω. Two equal resistors in parallel = half the individual resistance.',
    wrongAnswerExplanations: {
      A: '2000 Ω would be two resistors in SERIES (R_total = R₁ + R₂ = 1000 + 1000).',
      B: '1000 Ω would be just one resistor — not the parallel combination.',
      D: '250 Ω = 1000/4 — would be four identical resistors in parallel, or two pairs each already halved.',
    },
    teachingPoint: 'Resistors in parallel: 1/R_total = 1/R₁ + 1/R₂ + … → R_total < smallest individual R. Two equal R in parallel = R/2. Shortcut for 2 resistors: R_total = (R₁ × R₂)/(R₁ + R₂). Parallel gives MORE paths for current → LESS total resistance.',
    relatedTopics: ['parallel resistors', 'total resistance parallel', 'circuit resistance calculation'],
  },
  {
    id: 'mcat-qb-cp-158',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'Physics',
    contentCategory: '4E: Electricity and circuits',
    foundationalConcept: '4: Physical processes',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    questionType: 'passage',
    passageText: CIRCUIT_PASSAGE,
    question: 'A 12 V battery drives 2 mA of current through a resistor. What is the power dissipated in the resistor?',
    choices: [
      { label: 'A', text: '6 mW' },
      { label: 'B', text: '24 mW' },
      { label: 'C', text: '0.006 W' },
      { label: 'D', text: 'Both A and C are correct' },
    ],
    correctAnswer: 'B',
    explanation: 'P = IV = (2 × 10⁻³ A)(12 V) = 24 × 10⁻³ W = 24 mW. Choices A and C both give 6 mW (in different units: 6 mW = 0.006 W), which would require I = 0.5 mA at 12 V — not the stated 2 mA. Choice D ("Both A and C are correct") is wrong because A and C give the incorrect value. Choice B (24 mW) is correct.',
    wrongAnswerExplanations: {
      A: '6 mW = 6 × 10⁻³ W. This would require I × V = 0.006 → with V = 12 V, I = 0.5 mA. The problem states I = 2 mA, so P = 0.002 × 12 = 0.024 W = 24 mW.',
      C: '0.006 W = 6 mW — the same incorrect value as Choice A in different units. P = IV = 0.002 × 12 = 0.024 W, not 0.006 W.',
      D: 'Both A and C give 6 mW (the same wrong answer in different units). Since neither A nor C is correct, D is also incorrect.',
    },
    teachingPoint: 'Power: P = IV = I²R = V²/R. With I = 2 mA = 0.002 A and V = 12 V: P = 0.002 × 12 = 0.024 W = 24 mW. Ohm\'s Law: V = IR → R = V/I = 12/0.002 = 6000 Ω. Check: P = I²R = (0.002)² × 6000 = 4 × 10⁻⁶ × 6000 = 0.024 W ✓.',
    relatedTopics: ['electrical power P=IV', 'power dissipation resistor', 'Ohm law power'],
  },

  // ── Amino Acids & Peptides (Q159–Q162) ────────────────────────────────────
  {
    id: 'mcat-qb-cp-159',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'Biochemistry',
    contentCategory: '1C: Proteins',
    foundationalConcept: '1: Biomolecules have unique properties',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    questionType: 'passage',
    passageText: AMINO_ACIDS_PASSAGE,
    question: 'A peptide bond is formed by a condensation reaction between which two groups?',
    choices: [
      { label: 'A', text: 'The α-carboxyl of one amino acid and the α-amino of the next' },
      { label: 'B', text: 'The α-amino of one amino acid and the R-group of the next' },
      { label: 'C', text: 'Two R-groups of adjacent amino acids' },
      { label: 'D', text: 'The α-carboxyl and the α-amino of the SAME amino acid' },
    ],
    correctAnswer: 'A',
    explanation: 'Peptide bond: the α-carboxyl group (–COOH) of one amino acid reacts with the α-amino group (–NH₂) of the next amino acid in a dehydration condensation reaction, releasing one water molecule (H₂O) and forming the amide bond (–CO–NH–).',
    wrongAnswerExplanations: {
      B: 'R-groups (side chains) are not involved in peptide bond formation. Peptide bonds form between backbone groups (α-COOH and α-NH₂), not between backbone and side chain.',
      C: 'R-groups form disulfide bonds (Cys-Cys), hydrophobic interactions, ionic bonds, and hydrogen bonds, but not peptide bonds.',
      D: 'Within the same amino acid, the α-COOH and α-NH₂ form a zwitterion — they are not condensed with each other. Peptide bond requires INTERMOLECULAR reaction between two different amino acids.',
    },
    teachingPoint: 'Peptide bond: α-COOH + α-NH₂ → amide bond + H₂O. Peptide bond has partial double bond character (resonance with carbonyl) → planar, trans configuration. N-terminus (free NH₂) to C-terminus (free COOH): direction of convention and ribosomal synthesis.',
    relatedTopics: ['peptide bond formation', 'condensation reaction amino acid', 'amide bond protein'],
  },
  {
    id: 'mcat-qb-cp-160',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'Biochemistry',
    contentCategory: '1C: Proteins',
    foundationalConcept: '1: Biomolecules have unique properties',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    questionType: 'passage',
    passageText: AMINO_ACIDS_PASSAGE,
    question: 'A tripeptide Ala-Lys-Glu is placed in a solution at pH 7.4. Which amino acid side chain contributes a POSITIVE charge?',
    choices: [
      { label: 'A', text: 'Alanine — its methyl side chain is positively polarized' },
      { label: 'B', text: 'Lysine — its ε-amino group (pKa ≈ 10.5) is protonated at pH 7.4' },
      { label: 'C', text: 'Glutamate — its carboxyl side chain donates a proton to become positive' },
      { label: 'D', text: 'All three side chains are neutral at pH 7.4' },
    ],
    correctAnswer: 'B',
    explanation: 'Lysine has an ε-amino group with pKa ≈ 10.5. At pH 7.4, which is below pKa 10.5, the ε-amino group is protonated (–NH₃⁺) → positive charge. Glutamate has a γ-carboxyl with pKa ≈ 4.1. At pH 7.4 > 4.1, the carboxyl is deprotonated (–COO⁻) → negative charge. Alanine has a nonpolar methyl side chain → neutral at all physiological pH values.',
    wrongAnswerExplanations: {
      A: 'Alanine\'s methyl group (–CH₃) is nonpolar and uncharged at all physiological pH values. It has no ionizable proton.',
      C: 'Glutamate\'s carboxyl side chain (pKa ≈ 4.1) is DEPROTONATED at pH 7.4 (pH > pKa → loses proton → negative charge –COO⁻). A carboxyl group losing a proton becomes negatively charged, not positive.',
      D: 'Lysine (positive) and Glutamate (negative) both carry charges at pH 7.4. Not all three are neutral.',
    },
    teachingPoint: 'Charged amino acids at pH 7.4: Positive: Lys (pKa 10.5), Arg (pKa 12.5), His (pKa 6.0 — mostly neutral, ~10% positive at 7.4). Negative: Asp (pKa 3.9), Glu (pKa 4.1). Neutral: Ala, Gly, Val, Leu, Ile, Pro, Phe, Trp, Met, Ser, Thr, Cys, Tyr, Asn, Gln.',
    relatedTopics: ['amino acid charge pH 7.4', 'lysine positive charge', 'ionizable side chains'],
  },
  {
    id: 'mcat-qb-cp-161',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'Biochemistry',
    contentCategory: '1C: Proteins structure',
    foundationalConcept: '1: Biomolecules have unique properties',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    questionType: 'passage',
    passageText: AMINO_ACIDS_PASSAGE,
    question: 'Which level of protein structure is PRIMARILY stabilized by hydrogen bonds between backbone carbonyl (C=O) and amino (N-H) groups?',
    choices: [
      { label: 'A', text: 'Primary structure — sequence of amino acids' },
      { label: 'B', text: 'Secondary structure — α-helices and β-sheets' },
      { label: 'C', text: 'Tertiary structure — overall 3D folding of a single chain' },
      { label: 'D', text: 'Quaternary structure — assembly of multiple subunits' },
    ],
    correctAnswer: 'B',
    explanation: 'Secondary structure (α-helix and β-sheets) is stabilized by hydrogen bonds between backbone C=O and N-H groups. In an α-helix: C=O of residue n H-bonds to N-H of residue n+4. In a β-sheet: H-bonds form between extended strands (parallel or antiparallel). These are backbone H-bonds — the R-groups do not participate in secondary structure H-bonds.',
    wrongAnswerExplanations: {
      A: 'Primary structure = amino acid sequence, held together by covalent peptide bonds — not H-bonds.',
      C: 'Tertiary structure is stabilized by hydrophobic interactions (dominant), disulfide bonds, H-bonds between R-groups, ionic interactions, and van der Waals forces. Secondary structure backbone H-bonds contribute but tertiary involves more side-chain interactions.',
      D: 'Quaternary structure involves interactions between separate polypeptide chains: hydrophobic effects, H-bonds between side chains, ionic bonds, and disulfide bonds between subunits.',
    },
    teachingPoint: 'Protein structural levels: Primary = peptide bonds (covalent). Secondary = backbone H-bonds (C=O···H-N). Tertiary = hydrophobic effect, disulfide, ionic, H-bonds (R-groups). Quaternary = non-covalent interactions between subunits (+ disulfide in some). Denaturation disrupts secondary, tertiary, quaternary (not primary).',
    relatedTopics: ['protein secondary structure', 'alpha helix beta sheet H-bonds', 'protein structure levels'],
  },
  {
    id: 'mcat-qb-cp-162',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'Biochemistry',
    contentCategory: '1C: Proteins',
    foundationalConcept: '1: Biomolecules have unique properties',
    scientificSkill: 'Skill 3',
    difficulty: 'hard',
    questionType: 'passage',
    passageText: AMINO_ACIDS_PASSAGE,
    question: 'A researcher adds urea (denaturant that disrupts H-bonds and hydrophobic interactions) to a monomeric enzyme. Which observation is MOST expected?',
    choices: [
      { label: 'A', text: 'Loss of primary structure — peptide bonds are cleaved by urea' },
      { label: 'B', text: 'Loss of secondary and tertiary structure → loss of enzymatic activity, but primary structure preserved' },
      { label: 'C', text: 'Disruption of quaternary structure only — no effect on individual chain folding' },
      { label: 'D', text: 'No change — monomeric enzymes do not denature in urea' },
    ],
    correctAnswer: 'B',
    explanation: 'Urea (and guanidinium chloride) are chemical denaturants that disrupt non-covalent interactions (H-bonds, hydrophobic interactions) that maintain secondary and tertiary structure. Primary structure (covalent peptide bonds) is NOT disrupted by urea — only harsh conditions (acid hydrolysis) cleave peptide bonds. A monomeric enzyme loses its 3D fold (secondary + tertiary) → active site disrupted → loss of enzymatic activity. Primary structure is preserved.',
    wrongAnswerExplanations: {
      A: 'Urea cannot cleave peptide bonds (covalent bonds). Denaturation by urea is reversible (in some proteins) — if it cleaved peptide bonds, renaturation would be impossible.',
      C: 'A monomeric enzyme (single polypeptide chain) has no quaternary structure. Urea disrupts secondary and tertiary structure. Quaternary structure disruption occurs in multimeric proteins.',
      D: 'Monomeric proteins do denature in urea — they unfold from their native secondary and tertiary structure. Urea is a potent protein denaturant for both monomeric and multimeric proteins.',
    },
    teachingPoint: 'Protein denaturation: disrupts non-covalent interactions (H-bonds, hydrophobic, ionic, van der Waals) → loss of secondary, tertiary, quaternary. PRIMARY STRUCTURE (covalent peptide bonds) PRESERVED. Denaturants: urea, guanidinium (chemical, disrupt H-bonds/hydrophobic); heat (disrupts all non-covalent); SDS (detergent, disrupts hydrophobic); acid/base (disrupts ionic). Some proteins refold on denaturant removal (Anfinsen — primary determines tertiary).',
    relatedTopics: ['protein denaturation urea', 'primary structure preserved denaturation', 'non-covalent denaturation'],
  },

  // ── Redox Reactions (Q163–Q166) ───────────────────────────────────────────
  {
    id: 'mcat-qb-cp-163',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'General Chemistry',
    contentCategory: '5D: Electrochemistry',
    foundationalConcept: '5: The principles that govern chemical interactions',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    questionType: 'passage',
    passageText: OXIDATION_PASSAGE,
    question: 'In the reaction MnO₄⁻ + Fe²⁺ → Mn²⁺ + Fe³⁺ (acidic solution), what is the standard cell potential E°cell?',
    choices: [
      { label: 'A', text: '+0.74 V' },
      { label: 'B', text: '+2.28 V' },
      { label: 'C', text: '+0.77 V' },
      { label: 'D', text: '+1.51 V' },
    ],
    correctAnswer: 'A',
    explanation: 'MnO₄⁻ is the oxidizing agent (cathode, reduction): E° = +1.51 V. Fe²⁺ is oxidized (anode): Fe²⁺ → Fe³⁺ + e⁻. The reverse of the Fe³⁺/Fe²⁺ reduction (E° = +0.77 V). E°cell = E°cathode − E°anode = +1.51 − (+0.77) = +0.74 V.',
    wrongAnswerExplanations: {
      B: '+2.28 V = +1.51 + 0.77 — this incorrectly adds both reduction potentials. The cell potential = E°cathode − E°anode.',
      C: '+0.77 V is just the E° for Fe³⁺/Fe²⁺ reduction. This is the anode half-reaction potential, not the full cell potential.',
      D: '+1.51 V is the E° for MnO₄⁻/Mn²⁺ reduction alone. The cell potential requires subtracting the anode E°.',
    },
    teachingPoint: 'E°cell = E°cathode − E°anode. The stronger oxidizing agent (higher E°) is reduced at the cathode. The weaker oxidizing agent (lower E°) is oxidized at the anode. KMnO₄ (E° = +1.51 V) oxidizes Fe²⁺ (E° = +0.77 V) spontaneously because E°cell = +0.74 V > 0.',
    relatedTopics: ['redox cell potential calculation', 'permanganate iron oxidation', 'E° cathode minus anode'],
  },
  {
    id: 'mcat-qb-cp-164',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'General Chemistry',
    contentCategory: '5D: Electrochemistry',
    foundationalConcept: '5: The principles that govern chemical interactions',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    questionType: 'passage',
    passageText: OXIDATION_PASSAGE,
    question: 'What is the oxidation state of Mn in MnO₄⁻?',
    choices: [
      { label: 'A', text: '+4' },
      { label: 'B', text: '+7' },
      { label: 'C', text: '+2' },
      { label: 'D', text: '−1' },
    ],
    correctAnswer: 'B',
    explanation: 'In MnO₄⁻: oxygen = −2 each (4 oxygens = −8 total). Ion charge = −1. So Mn + (−8) = −1 → Mn = +7. Permanganate has Mn in its highest common oxidation state (+7). After reduction: Mn²⁺ (oxidation state +2). Change: +7 → +2 = gain of 5 electrons (reduction).',
    wrongAnswerExplanations: {
      A: '+4 is the oxidation state of Mn in MnO₂ (manganese dioxide). In MnO₄⁻: 4(−2) + Mn = −1 → Mn = +7.',
      C: '+2 is the product (Mn²⁺) after reduction — not the starting oxidation state in MnO₄⁻.',
      D: '−1 is the charge of the permanganate ion, not the oxidation state of manganese within it.',
    },
    teachingPoint: 'Oxidation state rules: O = −2 (usually); H = +1 (with nonmetals); sum of oxidation states = overall charge. Mn oxidation states: MnO₄⁻ = +7, MnO₂ = +4, Mn₂O₃ = +3, MnO = +2, Mn = 0. In KMnO₄ titrations: MnO₄⁻ (+7) → Mn²⁺ (+2) in acid (5 electrons); Mn²⁺ is nearly colorless vs. deep purple MnO₄⁻.',
    relatedTopics: ['oxidation state MnO4', 'permanganate oxidation state', 'oxidation state rules'],
  },
  {
    id: 'mcat-qb-cp-165',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'General Chemistry',
    contentCategory: '5D: Electrochemistry',
    foundationalConcept: '5: The principles that govern chemical interactions',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    questionType: 'passage',
    passageText: OXIDATION_PASSAGE,
    question: 'In the balanced redox reaction: MnO₄⁻ + 5Fe²⁺ + 8H⁺ → Mn²⁺ + 5Fe³⁺ + 4H₂O, the role of H⁺ is to:',
    choices: [
      { label: 'A', text: 'Act as an oxidizing agent alongside MnO₄⁻' },
      { label: 'B', text: 'Balance the oxygen atoms by providing hydrogen for water formation' },
      { label: 'C', text: 'Reduce Fe³⁺ back to Fe²⁺' },
      { label: 'D', text: 'Donate electrons to MnO₄⁻' },
    ],
    correctAnswer: 'B',
    explanation: 'In acidic permanganate reduction: MnO₄⁻ + 8H⁺ + 5e⁻ → Mn²⁺ + 4H₂O. The 8H⁺ ions combine with the 4 oxygen atoms from MnO₄⁻ to form 4 H₂O molecules, balancing the oxygen. H⁺ is consumed but not reduced (it keeps its +1 oxidation state in H₂O). Without H⁺, oxygen from MnO₄⁻ cannot be balanced in the products.',
    wrongAnswerExplanations: {
      A: 'H⁺ is not an oxidizing agent in this reaction. Its oxidation state in both H⁺ (reactant) and H₂O (product) is +1 — no change in oxidation state, so no redox activity.',
      C: 'H⁺ does not reduce Fe³⁺ to Fe²⁺. The reaction goes Fe²⁺ → Fe³⁺ (oxidation). H⁺ balances oxygen via water formation.',
      D: 'H⁺ (oxidation state +1) does not donate electrons — only reducing agents donate electrons. H⁺ is balanced as part of water in this reaction.',
    },
    teachingPoint: 'Balancing redox in acid: (1) Balance all atoms except H and O. (2) Balance O by adding H₂O. (3) Balance H by adding H⁺. (4) Balance charge with electrons. (5) Multiply half-reactions so electrons cancel. In basic solution: after balancing in acid, add equal OH⁻ to both sides to neutralize H⁺ → H₂O.',
    relatedTopics: ['balancing redox in acid', 'H+ role acidic redox', 'permanganate half reaction'],
  },
  {
    id: 'mcat-qb-cp-166',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'General Chemistry',
    contentCategory: '5D: Electrochemistry',
    foundationalConcept: '5: The principles that govern chemical interactions',
    scientificSkill: 'Skill 3',
    difficulty: 'hard',
    questionType: 'passage',
    passageText: OXIDATION_PASSAGE,
    question: 'A student uses Cr₂O₇²⁻ instead of MnO₄⁻ to oxidize Fe²⁺. Compared to permanganate, which statement is correct?',
    choices: [
      { label: 'A', text: 'Cr₂O₇²⁻ is a stronger oxidizing agent than MnO₄⁻ (E° = +1.33 > +1.51 is false — wait, 1.33 < 1.51)' },
      { label: 'B', text: 'Cr₂O₇²⁻ is a weaker oxidizing agent than MnO₄⁻; the titration with Fe²⁺ still works but with a lower cell potential' },
      { label: 'C', text: 'Cr₂O₇²⁻ cannot oxidize Fe²⁺ because its E° (+1.33 V) is below a minimum threshold' },
      { label: 'D', text: 'Both oxidizing agents produce the same cell potential when reacted with Fe²⁺' },
    ],
    correctAnswer: 'B',
    explanation: 'E°cell for Cr₂O₇²⁻/Fe²⁺: E°cell = +1.33 − +0.77 = +0.56 V. This is positive → reaction is spontaneous → Cr₂O₇²⁻ CAN oxidize Fe²⁺. But E°cell (+0.56 V) < permanganate cell E° (+0.74 V) → Cr₂O₇²⁻ is a weaker oxidizing agent. B is correct. The reaction works (positive E°cell) but with lower driving force.',
    wrongAnswerExplanations: {
      A: 'E°(MnO₄⁻) = +1.51 V > E°(Cr₂O₇²⁻) = +1.33 V. MnO₄⁻ is the STRONGER oxidizing agent. Higher E° = stronger tendency to be reduced = stronger oxidizing agent.',
      C: 'A positive E°cell (+0.56 V) for the Cr₂O₇²⁻/Fe²⁺ reaction means the reaction IS spontaneous. There is no "minimum threshold" for spontaneity other than E°cell > 0.',
      D: 'The cell potentials are different: 0.74 V (MnO₄⁻/Fe²⁺) vs. 0.56 V (Cr₂O₇²⁻/Fe²⁺). They are not the same.',
    },
    teachingPoint: 'Oxidizing agent strength = reduction potential E°. Higher E° = stronger oxidizing agent = more easily reduced. MnO₄⁻ (E° = +1.51) > Cr₂O₇²⁻ (E° = +1.33) > Fe³⁺ (E° = +0.77). Both Cr₂O₇²⁻ and MnO₄⁻ oxidize Fe²⁺ (both have E°cell > 0 with Fe²⁺). KMnO₄ is used for self-indicating titration (purple → colorless at endpoint).',
    relatedTopics: ['oxidizing agent strength E°', 'dichromate permanganate comparison', 'Fe2+ oxidation titration'],
  },

  // ── Periodic Trends (Q167–Q169) ───────────────────────────────────────────
  {
    id: 'mcat-qb-cp-167',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'General Chemistry',
    contentCategory: '5A: Periodic table and properties',
    foundationalConcept: '5: The principles that govern chemical interactions',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    questionType: 'passage',
    passageText: PERIODIC_TRENDS_PASSAGE,
    question: 'Which has the LARGEST atomic radius?',
    choices: [
      { label: 'A', text: 'Na (Period 3, Group 1)' },
      { label: 'B', text: 'Cl (Period 3, Group 17)' },
      { label: 'C', text: 'K (Period 4, Group 1)' },
      { label: 'D', text: 'F (Period 2, Group 17)' },
    ],
    correctAnswer: 'C',
    explanation: 'Atomic radius trends: decreases across a period (left to right), increases down a group. K (Period 4, Group 1) is lower in its group than Na and further left than Cl and F. Going down Group 1: Li < Na < K → K is larger. Across Period 3: Na (Group 1) > Cl (Group 17) — Na is much larger. K > Na (more shells). K is the largest among these options.',
    wrongAnswerExplanations: {
      A: 'Na is in Period 3, Group 1. Larger than Cl and F, but K (Period 4, Group 1) is larger than Na (same group, one period lower).',
      B: 'Cl is in Period 3, Group 17 — it has a high nuclear charge pulling electrons close. Much smaller than Na in the same period and much smaller than K.',
      D: 'F is in Period 2, Group 17 — it is the smallest atom among these four (highest period and far right group, meaning smallest radius despite being the most electronegative).',
    },
    teachingPoint: 'Atomic radius: decreases → across a period (more protons pull electrons closer). Increases ↓ down a group (more electron shells). Largest radius = bottom left of periodic table (Cs, Fr). Smallest = top right (He, F). Cations: smaller than atom (lost electron shells or electrons reduced). Anions: larger (added electrons → repulsion increases size).',
    relatedTopics: ['atomic radius periodic trends', 'largest atom radius', 'periodic table trends'],
  },
  {
    id: 'mcat-qb-cp-168',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'General Chemistry',
    contentCategory: '5A: Periodic table and properties',
    foundationalConcept: '5: The principles that govern chemical interactions',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    questionType: 'passage',
    passageText: PERIODIC_TRENDS_PASSAGE,
    question: 'Which of the following has the HIGHEST first ionization energy?',
    choices: [
      { label: 'A', text: 'Na' },
      { label: 'B', text: 'Mg' },
      { label: 'C', text: 'Ne' },
      { label: 'D', text: 'Al' },
    ],
    correctAnswer: 'C',
    explanation: 'First ionization energy (IE₁) increases across a period and decreases down a group. Ne is a noble gas (Period 2, Group 18) — it has a completely filled outer shell (very stable configuration), making it extremely difficult to remove an electron. IE₁ order in Period 3: Na < Al < Mg < P < Si < S < Cl < Ar. But Ne (Period 2) has higher IE₁ than all of these Period 3 elements (different period). Ne IE₁ = 2080 kJ/mol, far higher than Na (496), Mg (738), Al (578).',
    wrongAnswerExplanations: {
      A: 'Na (Group 1) has the lowest IE₁ in Period 3 — it easily loses one electron to achieve a noble gas configuration.',
      B: 'Mg (Group 2) has higher IE₁ than Na but lower than many others in the same period. Ne (noble gas) has a much higher IE₁.',
      D: 'Al (Group 13) has a slightly LOWER IE₁ than Mg (anomaly: Al removes one electron from 3p¹, while Mg removes from 3s²; 3p is higher energy and easier to remove). Neither is close to Ne.',
    },
    teachingPoint: 'IE trends: increases → across a period; decreases ↓ down a group. Anomalies: IE₁(Mg) > IE₁(Al) (Al loses 3p¹, easier than 3s²); IE₁(P) > IE₁(S) (S loses one electron from half-filled 3p, breaking stable configuration). Noble gases have highest IE in their period.',
    relatedTopics: ['first ionization energy trends', 'noble gas ionization energy', 'IE anomalies Mg Al'],
  },
  {
    id: 'mcat-qb-cp-169',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'General Chemistry',
    contentCategory: '5A: Periodic table and properties',
    foundationalConcept: '5: The principles that govern chemical interactions',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    questionType: 'passage',
    passageText: PERIODIC_TRENDS_PASSAGE,
    question: 'Which correctly ranks these ions from SMALLEST to LARGEST radius: Na⁺, Mg²⁺, F⁻?',
    choices: [
      { label: 'A', text: 'F⁻ < Na⁺ < Mg²⁺' },
      { label: 'B', text: 'Na⁺ < F⁻ < Mg²⁺' },
      { label: 'C', text: 'Mg²⁺ < Na⁺ < F⁻' },
      { label: 'D', text: 'Mg²⁺ < F⁻ < Na⁺' },
    ],
    correctAnswer: 'C',
    explanation: 'These are isoelectronic species (all have 10 electrons: 1s² 2s² 2p⁶). With the same number of electrons, higher nuclear charge → smaller radius (more protons pull the same electrons closer). Proton counts: Mg = 12, Na = 11, F = 9. Larger nuclear charge → smaller radius. Smallest to largest: Mg²⁺ (Z=12) < Na⁺ (Z=11) < F⁻ (Z=9).',
    wrongAnswerExplanations: {
      A: 'Inverts the order. F⁻ has the FEWEST protons (Z=9) → largest radius among isoelectronic ions. Mg²⁺ has most protons → smallest.',
      B: 'Wrong — Na⁺ < F⁻ means Na⁺ is smaller, which is correct (11 > 9 protons). But Mg²⁺ (12 protons) must be smallest, not largest.',
      D: 'Mg²⁺ < F⁻ is correct in direction but Na⁺ should be between them (Z=11, intermediate).',
    },
    teachingPoint: 'Isoelectronic series: same number of electrons, different nuclear charges. Size determined by Z (nuclear charge): higher Z → more protons pull electrons → smaller radius. O²⁻ > F⁻ > Ne > Na⁺ > Mg²⁺ > Al³⁺ (all have 10 electrons). Opposite intuition from neutral atoms: cation of large element can be smaller than anion of small element.',
    relatedTopics: ['isoelectronic ions radius', 'ionic radius nuclear charge', 'Mg2+ Na+ F- size'],
  },

  // ── Discrete questions (Q170–Q180) ────────────────────────────────────────
  {
    id: 'mcat-qb-cp-170',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'Organic Chemistry',
    contentCategory: '6B: Alkenes and alkynes',
    foundationalConcept: '5: The principles that govern chemical interactions',
    scientificSkill: 'Skill 1',
    difficulty: 'medium',
    questionType: 'discrete',
    question: 'HBr is added to 2-methylpropene (CH₂=C(CH₃)₂). According to Markovnikov\'s rule, what is the MAJOR product?',
    choices: [
      { label: 'A', text: '1-bromo-2-methylpropane (Br on the terminal carbon)' },
      { label: 'B', text: '2-bromo-2-methylpropane (Br on the central, tertiary carbon)' },
      { label: 'C', text: 'The reaction produces equal amounts of both products' },
      { label: 'D', text: 'No reaction occurs — HBr does not add to alkenes' },
    ],
    correctAnswer: 'B',
    explanation: 'Markovnikov\'s rule: H adds to the carbon with more H\'s (or less substituted), and the nucleophile (Br⁻) adds to the more substituted (more stable) carbocation. Protonation of CH₂=C(CH₃)₂: H⁺ adds to CH₂ (less substituted end) → tertiary carbocation at C(CH₃)₂⁺ (more stable) → Br⁻ attacks → 2-bromo-2-methylpropane. The anti-Markovnikov product (1-bromo) would require a less stable primary carbocation.',
    wrongAnswerExplanations: {
      A: 'Anti-Markovnikov addition (requires radical conditions with peroxides, not ionic HBr addition). Ionic HBr follows Markovnikov → more stable carbocation → Br adds to tertiary carbon.',
      C: 'Not equal amounts — Markovnikov regiochemistry strongly favors the tertiary carbocation intermediate → tertiary bromide predominates greatly.',
      D: 'HBr readily adds to alkenes (electrophilic addition). The π bond is nucleophilic and attacks H⁺ from HBr.',
    },
    teachingPoint: 'Markovnikov addition of HX to alkenes: H adds to less substituted carbon; X adds to more substituted carbon (via most stable carbocation intermediate). Anti-Markovnikov: radical addition with HBr + peroxides (ROOR) → Br adds to less substituted carbon. No anti-Markovnikov with HCl or HI.',
    relatedTopics: ['Markovnikov rule', 'HBr alkene addition', 'electrophilic addition alkene'],
  },
  {
    id: 'mcat-qb-cp-171',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'Biochemistry',
    contentCategory: '1D: Enzyme kinetics',
    foundationalConcept: '1: Biomolecules have unique properties',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    questionType: 'discrete',
    question: 'Which statement about enzyme catalysis is correct?',
    choices: [
      { label: 'A', text: 'Enzymes lower the activation energy but do not change ΔG° of the reaction' },
      { label: 'B', text: 'Enzymes shift the equilibrium of a reaction toward products' },
      { label: 'C', text: 'Enzymes are consumed in the reaction and must be continually replenished' },
      { label: 'D', text: 'Enzymes lower the activation energy by raising the energy of the transition state' },
    ],
    correctAnswer: 'A',
    explanation: 'Enzymes are catalysts: they lower the activation energy (Ea) by stabilizing the transition state (bringing reactants together, providing acidic/basic groups, etc.). They do NOT change the thermodynamics of the reaction — ΔG°, ΔH°, and the equilibrium constant Keq are unchanged. The enzyme is NOT consumed (regenerated after each reaction cycle). The reaction reaches equilibrium faster, but the equilibrium position (Keq) is the same.',
    wrongAnswerExplanations: {
      B: 'Enzymes do not shift equilibrium. Keq = e^(−ΔG°/RT) — determined by ΔG°, which enzymes do not change. The reaction reaches equilibrium faster, but the final ratio of products to reactants at equilibrium is unchanged.',
      C: 'Enzymes are NOT consumed. They are regenerated after catalysis (that\'s what makes them catalysts). Covalent intermediates form transiently but the enzyme is restored.',
      D: 'Enzymes LOWER the energy of the transition state (stabilize it), NOT raise it. Lower transition state energy → lower activation energy → faster reaction.',
    },
    teachingPoint: 'Enzyme catalysis: lowers Ea (not ΔG°). Mechanism: (1) Transition state stabilization. (2) Proximity/orientation effects. (3) Acid-base catalysis. (4) Covalent catalysis. Keq unchanged — enzyme accelerates both forward and reverse reactions equally. kcat/Km = catalytic efficiency (measures how efficiently enzyme uses substrate at low [S]).',
    relatedTopics: ['enzyme catalysis activation energy', 'Keq enzyme unchanged', 'enzyme not consumed catalyst'],
  },
  {
    id: 'mcat-qb-cp-172',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'Physics',
    contentCategory: '4A: Mechanics',
    foundationalConcept: '4: Physical processes',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    questionType: 'discrete',
    question: 'A 2 kg object on a frictionless surface is pushed by a constant 10 N horizontal force for 3 seconds. What is the final speed if it starts from rest?',
    choices: [
      { label: 'A', text: '5 m/s' },
      { label: 'B', text: '15 m/s' },
      { label: 'C', text: '30 m/s' },
      { label: 'D', text: '60 m/s' },
    ],
    correctAnswer: 'B',
    explanation: 'Newton\'s 2nd law: a = F/m = 10 N / 2 kg = 5 m/s². Starting from rest (v₀ = 0): v = v₀ + at = 0 + (5 m/s²)(3 s) = 15 m/s.',
    wrongAnswerExplanations: {
      A: '5 m/s = a × 1 s, or v = F/m (missing time). Speed = at = 5 × 3 = 15, not just acceleration alone.',
      C: '30 m/s = F × t / m with an extra factor of 2 somewhere, or a × t² instead of a × t.',
      D: '60 m/s = F × t² / m or 2 × F × t / m — incorrect kinematics formula.',
    },
    teachingPoint: 'Newton\'s 2nd law: F = ma → a = F/m. Kinematics: v = v₀ + at (for constant acceleration). From rest: v = at. Displacement: x = ½at². Work-energy: W = Fd = ΔKE = ½mv². Check: KE = ½(2)(15²) = 225 J; W = Fd = 10 × ½(5)(9) = 10 × 22.5 = 225 J ✓.',
    relatedTopics: ['Newton second law', 'constant force acceleration', 'kinematics from rest'],
  },
  {
    id: 'mcat-qb-cp-173',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'General Chemistry',
    contentCategory: '5B: Solubility equilibria',
    foundationalConcept: '5: The principles that govern chemical interactions',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    questionType: 'discrete',
    question: 'AgCl has Ksp = 1.8 × 10⁻¹⁰. What is its molar solubility in pure water?',
    choices: [
      { label: 'A', text: '1.3 × 10⁻⁵ M' },
      { label: 'B', text: '1.8 × 10⁻¹⁰ M' },
      { label: 'C', text: '3.6 × 10⁻¹⁰ M' },
      { label: 'D', text: '9 × 10⁻⁶ M' },
    ],
    correctAnswer: 'A',
    explanation: 'AgCl(s) ⇌ Ag⁺ + Cl⁻. Let molar solubility = s. [Ag⁺] = s, [Cl⁻] = s. Ksp = s × s = s² = 1.8 × 10⁻¹⁰. s = √(1.8 × 10⁻¹⁰) = √1.8 × 10⁻⁵ ≈ 1.34 × 10⁻⁵ M ≈ 1.3 × 10⁻⁵ M.',
    wrongAnswerExplanations: {
      B: '1.8 × 10⁻¹⁰ is Ksp itself — not the molar solubility. s = √Ksp ≠ Ksp.',
      C: '3.6 × 10⁻¹⁰ = 2 × Ksp — algebraic error, not the square root.',
      D: '9 × 10⁻⁶: close to the correct order of magnitude but incorrect. √(1.8 × 10⁻¹⁰) = √1.8 × √10⁻¹⁰ = 1.34 × 10⁻⁵.',
    },
    teachingPoint: 'Molar solubility from Ksp: write dissolution equation → express Ksp in terms of s → solve for s. For AB type: Ksp = s². For AB₂ type (CaF₂): Ksp = (s)(2s)² = 4s³. Common ion effect: adding Ag⁺ or Cl⁻ to the solution decreases s (LeChâtelier).',
    relatedTopics: ['Ksp molar solubility', 'AgCl dissolution', 'solubility product calculation'],
  },
  {
    id: 'mcat-qb-cp-174',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'Organic Chemistry',
    contentCategory: '6D: Nitrogen-containing compounds',
    foundationalConcept: '5: The principles that govern chemical interactions',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    questionType: 'discrete',
    question: 'Which of the following is the weakest base?',
    choices: [
      { label: 'A', text: 'Methylamine (CH₃NH₂)' },
      { label: 'B', text: 'Aniline (C₆H₅NH₂)' },
      { label: 'C', text: 'Ammonia (NH₃)' },
      { label: 'D', text: 'Dimethylamine ((CH₃)₂NH)' },
    ],
    correctAnswer: 'B',
    explanation: 'Aniline (C₆H₅NH₂) is the weakest base. The nitrogen lone pair is delocalized into the aromatic ring (resonance) → reduced availability for protonation → weaker base. pKb: aniline ~9.4 (very weak), NH₃ ~4.7, methylamine ~3.4, dimethylamine ~3.3. Alkyl amines are stronger bases than ammonia (alkyl groups donate electron density); aniline is much weaker (resonance delocalization).',
    wrongAnswerExplanations: {
      A: 'Methylamine is a stronger base than both ammonia and aniline. The methyl group donates electron density inductively → increased basicity relative to NH₃.',
      C: 'Ammonia is a moderate base but stronger than aniline. NH₃ lone pair is more available than aniline\'s resonance-delocalized lone pair.',
      D: 'Dimethylamine is stronger than methylamine (two electron-donating methyl groups). It is a stronger base than all the others listed except for steric effects at higher substitution.',
    },
    teachingPoint: 'Amine basicity: dimethylamine > methylamine > NH₃ >> aniline. Resonance decreases basicity (aniline: lone pair delocalized). Electron-donating groups (alkyl) increase basicity. Electron-withdrawing groups (NO₂, halogens on ring) further decrease aniline\'s basicity. Amide nitrogen (RC(=O)NH₂) is even weaker base than aniline (resonance with carbonyl).',
    relatedTopics: ['amine basicity', 'aniline weak base resonance', 'amine pKa comparison'],
  },
  {
    id: 'mcat-qb-cp-175',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'Physics',
    contentCategory: '4D: Light and optics',
    foundationalConcept: '4: Physical processes',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    questionType: 'discrete',
    question: 'Light travels from glass (n = 1.5) into air (n = 1.0) at an angle of incidence of 20°. What happens?',
    choices: [
      { label: 'A', text: 'The refracted ray bends toward the normal in air' },
      { label: 'B', text: 'The refracted ray bends away from the normal in air (larger angle of refraction)' },
      { label: 'C', text: 'Total internal reflection occurs because the light enters a denser medium' },
      { label: 'D', text: 'The wavelength of light increases but the frequency decreases in air' },
    ],
    correctAnswer: 'B',
    explanation: 'Snell\'s law: n₁ sin θ₁ = n₂ sin θ₂. Going from glass (n=1.5) to air (n=1.0): sin θ₂ = (n₁/n₂) sin θ₁ = (1.5/1.0) sin 20° = 1.5 × 0.342 = 0.513. θ₂ = arcsin(0.513) ≈ 31°. Since θ₂ (31°) > θ₁ (20°), the refracted ray bends AWAY from the normal. Going from denser to less dense medium → angle increases → ray bends away from normal.',
    wrongAnswerExplanations: {
      A: 'Bending toward the normal occurs when light enters a DENSER medium (lower to higher n). Here light goes from denser glass (n=1.5) to less dense air (n=1.0) → bends AWAY from normal.',
      C: 'Total internal reflection occurs when light goes from denser to less dense medium AND the angle of incidence exceeds the critical angle (θc = arcsin(n₂/n₁) = arcsin(1/1.5) = 41.8°). At θ₁ = 20° < 41.8°, refraction occurs (not TIR).',
      D: 'Frequency does NOT change when light passes between media (frequency is determined by source). Wavelength increases (λ = v/f; speed increases in air, f unchanged → λ increases). Speed increases in air (less optically dense).',
    },
    teachingPoint: 'Snell\'s law: n₁sinθ₁ = n₂sinθ₂. Denser → less dense (n₁ > n₂): angle increases, ray bends away from normal. Less → denser: angle decreases, ray bends toward normal. TIR: only when going denser → less dense, AND θ₁ > θc = arcsin(n₂/n₁). Fiber optics uses TIR.',
    relatedTopics: ['Snell law refraction', 'glass to air bending', 'total internal reflection critical angle'],
  },
  {
    id: 'mcat-qb-cp-176',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'Biochemistry',
    contentCategory: '1E: Carbohydrates',
    foundationalConcept: '1: Biomolecules have unique properties',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    questionType: 'discrete',
    question: 'Glycogen and starch are both glucose polymers but differ in that glycogen:',
    choices: [
      { label: 'A', text: 'Uses β-1,4 glycosidic bonds while starch uses α-1,4 bonds' },
      { label: 'B', text: 'Is more highly branched than starch, with α-1,6 branches approximately every 8-12 residues' },
      { label: 'C', text: 'Is found only in plants while starch is found in animals' },
      { label: 'D', text: 'Is a lipid, not a polysaccharide' },
    ],
    correctAnswer: 'B',
    explanation: 'Glycogen (animal storage) and starch (plant storage) are both α-glucose polymers with α-1,4 glycosidic linkages in the main chain and α-1,6 linkages at branch points. Key difference: glycogen is MORE highly branched (~every 8-12 glucose units) vs. amylopectin (plant starch branching every 24-30 units) and amylose (unbranched). High branching of glycogen enables rapid glucose mobilization (many non-reducing ends accessible to glycogen phosphorylase simultaneously).',
    wrongAnswerExplanations: {
      A: 'Both glycogen and starch use α-1,4 glycosidic bonds in the linear chain. β-1,4 bonds are found in cellulose (a structural polysaccharide, not digestible by humans).',
      C: 'Glycogen is the storage form in ANIMALS (liver and muscle). Starch is the storage form in PLANTS. C inverts the correct association.',
      D: 'Glycogen is a polysaccharide (carbohydrate polymer), not a lipid. It is hydrophilic and stored in the cytosol of liver and muscle cells.',
    },
    teachingPoint: 'Polysaccharides: Glycogen (animals): highly branched, α-1,4 + α-1,6 every 8-12. Starch = amylose (α-1,4, unbranched) + amylopectin (α-1,4 + α-1,6 every 24-30). Cellulose (plant structural): β-1,4 (cannot be hydrolyzed by human amylase). Glycogen branching → rapid release of glucose for energy (many free ends).',
    relatedTopics: ['glycogen vs starch', 'polysaccharide glycosidic bonds', 'glycogen branching'],
  },
  {
    id: 'mcat-qb-cp-177',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'General Chemistry',
    contentCategory: '5A: Solutions',
    foundationalConcept: '5: The principles that govern chemical interactions',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    questionType: 'discrete',
    question: 'A 1.0 m NaCl aqueous solution has a boiling point elevation of 1.04°C. The Kb for water is 0.512°C/m. Which value does this experimental result yield for the van\'t Hoff factor i?',
    choices: [
      { label: 'A', text: 'i = 1.0 (no dissociation)' },
      { label: 'B', text: 'i = 1.5' },
      { label: 'C', text: 'i ≈ 2.0 (full dissociation into Na⁺ and Cl⁻)' },
      { label: 'D', text: 'i = 3.0' },
    ],
    correctAnswer: 'C',
    explanation: 'ΔTb = i × Kb × m. 1.04 = i × 0.512 × 1.0. i = 1.04/0.512 ≈ 2.03 ≈ 2.0. This is consistent with NaCl fully dissociating into 2 ions (Na⁺ + Cl⁻) → i = 2 (theoretical). The experimental value ≈ 2.0 confirms near-complete dissociation of NaCl in dilute solution.',
    wrongAnswerExplanations: {
      A: 'i = 1 would mean ΔTb = 1 × 0.512 × 1 = 0.512°C. The measured ΔTb = 1.04°C > 0.512°C → i > 1. NaCl dissociates.',
      B: 'i = 1.5 would give ΔTb = 1.5 × 0.512 = 0.768°C, not 1.04°C. 1.5 would suggest partial dissociation (e.g., 50% dissociation).',
      D: 'i = 3 would give ΔTb = 3 × 0.512 = 1.536°C, not 1.04°C. i = 3 applies to electrolytes yielding 3 ions (e.g., MgCl₂ → Mg²⁺ + 2Cl⁻).',
    },
    teachingPoint: 'Colligative properties: ΔTb = iKbm; ΔTf = iKfm; Π = iMRT. van\'t Hoff factor i: non-electrolyte = 1; NaCl = 2; MgCl₂ = 3; Na₂SO₄ = 3. Real solutions: i is slightly less than theoretical due to ion pairing (activity < ideal). Osmotic pressure clinical: IV saline (0.9% NaCl) is isotonic (~285 mOsm/L) matching blood osmolarity.',
    relatedTopics: ['boiling point elevation colligative', 'van t Hoff factor NaCl', 'electrolyte colligative properties'],
  },
  {
    id: 'mcat-qb-cp-178',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'Organic Chemistry',
    contentCategory: '6A: Stereochemistry',
    foundationalConcept: '5: The principles that govern chemical interactions',
    scientificSkill: 'Skill 1',
    difficulty: 'medium',
    questionType: 'discrete',
    question: 'A molecule has 3 stereocenters. What is the MAXIMUM number of stereoisomers it can have?',
    choices: [
      { label: 'A', text: '3' },
      { label: 'B', text: '6' },
      { label: 'C', text: '8' },
      { label: 'D', text: '16' },
    ],
    correctAnswer: 'C',
    explanation: 'Maximum stereoisomers = 2ⁿ, where n = number of stereocenters. With 3 stereocenters: 2³ = 8. The actual number may be less if the molecule has internal symmetry (meso compounds). The 8 includes all combinations of R and S at each center, which form enantiomeric and diastereomeric pairs.',
    wrongAnswerExplanations: {
      A: '3 is just the number of stereocenters — not the number of stereoisomers. Stereoisomers = 2ⁿ.',
      B: '6 = 2 × n = 2 × 3 — wrong formula. It should be 2ⁿ (exponential), not 2n (linear).',
      D: '16 = 2⁴ — that would be 4 stereocenters. With 3 stereocenters: 2³ = 8.',
    },
    teachingPoint: 'Stereoisomers: maximum = 2ⁿ (n = stereocenters). Fewer if: meso compound (internal mirror plane eliminates one stereoisomer pair). Types: enantiomers (non-superimposable mirror images), diastereomers (stereoisomers that are NOT enantiomers). With 3 stereocenters: 4 enantiomeric pairs = 8 possible; meso forms reduce this.',
    relatedTopics: ['stereoisomers stereocenters 2n', 'maximum stereoisomers', 'chirality centers'],
  },
  {
    id: 'mcat-qb-cp-179',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'Biochemistry',
    contentCategory: '2C: Respiration and ATP',
    foundationalConcept: '2: Highly organized structures are necessary for health',
    scientificSkill: 'Skill 1',
    difficulty: 'medium',
    questionType: 'discrete',
    question: 'Complete oxidation of one acetyl-CoA in the TCA cycle produces which set of electron carriers?',
    choices: [
      { label: 'A', text: '2 NADH, 1 FADH₂, 1 GTP' },
      { label: 'B', text: '3 NADH, 1 FADH₂, 1 GTP' },
      { label: 'C', text: '3 NADH, 2 FADH₂, 1 GTP' },
      { label: 'D', text: '4 NADH, 1 FADH₂, 2 GTP' },
    ],
    correctAnswer: 'B',
    explanation: 'One turn of the TCA cycle (one acetyl-CoA): isocitrate dehydrogenase → 1 NADH; α-ketoglutarate dehydrogenase → 1 NADH; succinyl-CoA synthetase → 1 GTP; succinate dehydrogenase → 1 FADH₂; malate dehydrogenase → 1 NADH. Total: 3 NADH + 1 FADH₂ + 1 GTP per acetyl-CoA.',
    wrongAnswerExplanations: {
      A: '2 NADH is one short — three NADH-producing steps (isocitrate DH, α-KG DH, malate DH).',
      C: '2 FADH₂ is wrong — only succinate dehydrogenase produces FADH₂ (1 per turn). Only one step uses FAD in the TCA cycle.',
      D: '4 NADH and 2 GTP are both wrong. 3 NADH and 1 GTP per acetyl-CoA turn.',
    },
    teachingPoint: 'TCA cycle per acetyl-CoA: 3 NADH + 1 FADH₂ + 1 GTP + 2 CO₂ released. ATP yield from electron carriers: NADH → ~2.5 ATP; FADH₂ → ~1.5 ATP. Per acetyl-CoA: 3(2.5) + 1(1.5) + 1 = 7.5 + 1.5 + 1 = 10 ATP. Per glucose (2 acetyl-CoA): 20 ATP from TCA (plus glycolysis and pyruvate dehydrogenase).',
    relatedTopics: ['TCA cycle products NADH FADH2', 'acetyl-CoA electron carriers', 'citric acid cycle ATP'],
  },
  {
    id: 'mcat-qb-cp-180',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'Physics',
    contentCategory: '4A: Mechanics torque',
    foundationalConcept: '4: Physical processes',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    questionType: 'discrete',
    question: 'A 60 kg person stands at the end of a uniform 4 m beam of mass 20 kg. The beam is supported at its center. What is the torque created by the person about the support point?',
    choices: [
      { label: 'A', text: '120 N·m' },
      { label: 'B', text: '600 N·m' },
      { label: 'C', text: '1200 N·m' },
      { label: 'D', text: '240 N·m' },
    ],
    correctAnswer: 'C',
    explanation: 'Torque = F × d (perpendicular distance from pivot). The person stands at the END of the 4 m beam, supported at the CENTER. Distance from center to end = 4/2 = 2 m. Force = weight = mg = 60 × 10 = 600 N. Torque = 600 N × 2 m = 1200 N·m.',
    wrongAnswerExplanations: {
      A: '120 N·m = 60 kg × 2 m — forgot to multiply by g (10 m/s²). Torque = mg × d = 600 × 2 = 1200 N·m.',
      B: '600 N·m = F × 1 m — used distance = 1 m instead of 2 m. Distance from CENTER to END = L/2 = 2 m.',
      D: '240 N·m = 20 kg × 12 m² — confused with beam torque or used wrong formula.',
    },
    teachingPoint: 'Torque τ = F × d (d = perpendicular distance from pivot to force line). Rotational equilibrium: Σtorques = 0. In this problem: beam (20 kg) acts at center of beam (0 m from pivot — no torque). Person (60 kg) at end: d = L/2 = 2 m from center pivot. τ = (60 × 10) × 2 = 1200 N·m.',
    relatedTopics: ['torque calculation pivot', 'lever arm torque', 'rotational equilibrium torque'],
  },
]
