import type { MCATQBQuestion } from './types'

export const chemPhysQuestions: MCATQBQuestion[] = [
  // ── Passage 1: Enzyme Kinetics (Q001–Q003) ──────────────────────────────────
  {
    id: 'mcat-qb-cp-001',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'Biochemistry',
    contentCategory: '1D: How enzymes work',
    foundationalConcept: '1: Biomolecules have unique properties',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    questionType: 'passage',
    passageText: `A researcher studied the kinetics of a purified protease under four conditions. Reaction velocity was measured at varying substrate concentrations. A Lineweaver-Burk (double-reciprocal) plot was constructed from the data. Two inhibitors, compound X and compound Y, were then tested at fixed inhibitor concentrations. The results are summarized in the table below.

Key observations: In the presence of compound X, the x-intercept of the Lineweaver-Burk plot shifted to a less negative value while the y-intercept remained unchanged. In the presence of compound Y, the y-intercept increased while the x-intercept remained unchanged.`,
    tableData: {
      headers: ['Condition', 'Vmax (nmol/min)', 'Km (mM)', 'x-intercept change', 'y-intercept change'],
      rows: [
        ['No inhibitor', '120', '2.0', 'baseline', 'baseline'],
        ['+ Compound X', '120', '6.0', 'shifts right', 'unchanged'],
        ['+ Compound Y', '60', '2.0', 'unchanged', 'increases'],
        ['+ Both X and Y', '60', '6.0', 'shifts right', 'increases'],
      ],
      caption: 'Table 1. Enzyme kinetics under inhibitory conditions',
    },
    question: 'Based on the data in Table 1, what type of inhibition does Compound X exhibit?',
    choices: [
      { label: 'A', text: 'Uncompetitive inhibition, because both Km and Vmax are altered' },
      { label: 'B', text: 'Competitive inhibition, because Km increases but Vmax is unchanged' },
      { label: 'C', text: 'Noncompetitive inhibition, because Vmax decreases but Km is unchanged' },
      { label: 'D', text: 'Mixed inhibition, because both Km and Vmax are altered but in opposite directions' },
    ],
    correctAnswer: 'B',
    explanation: 'Choice B is correct. Compound X increases Km (from 2.0 to 6.0 mM) while leaving Vmax unchanged (120 nmol/min). This is the hallmark of competitive inhibition: the inhibitor competes with substrate for the active site, raising the apparent Km (decreasing apparent affinity), but at sufficiently high substrate concentrations Vmax can still be reached. On the Lineweaver-Burk plot, competitive inhibition shifts the x-intercept (−1/Km) to a less negative value (right shift) while the y-intercept (1/Vmax) is unchanged, exactly matching the data.',
    wrongAnswerExplanations: {
      A: 'Uncompetitive inhibition decreases BOTH Km and Vmax proportionally and causes parallel line shifts on the Lineweaver-Burk plot. Here Km increases and Vmax is unchanged — inconsistent with uncompetitive inhibition.',
      C: 'Noncompetitive inhibition decreases Vmax while leaving Km unchanged. Here Vmax is unchanged and Km increases, which is opposite to noncompetitive inhibition and matches competitive inhibition instead.',
      D: 'Mixed inhibition changes both Km and Vmax. Here Vmax is unchanged (120 nmol/min in both no-inhibitor and compound X conditions), so mixed inhibition is not supported by the data.',
    },
    teachingPoint: 'On a Lineweaver-Burk plot: competitive inhibitors pivot the line around the y-intercept (same Vmax, higher apparent Km); noncompetitive inhibitors pivot around the x-intercept (same Km, lower Vmax); uncompetitive inhibitors shift the line parallel (both Km and Vmax decrease proportionally).',
    relatedTopics: ['Enzyme kinetics', 'Michaelis-Menten kinetics', 'Lineweaver-Burk plot', 'Inhibitor types'],
  },
  {
    id: 'mcat-qb-cp-002',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'Biochemistry',
    contentCategory: '1D: How enzymes work',
    foundationalConcept: '1: Biomolecules have unique properties',
    scientificSkill: 'Skill 3',
    difficulty: 'hard',
    questionType: 'passage',
    passageText: `A researcher studied the kinetics of a purified protease under four conditions. Reaction velocity was measured at varying substrate concentrations. A Lineweaver-Burk (double-reciprocal) plot was constructed from the data. Two inhibitors, compound X and compound Y, were then tested at fixed inhibitor concentrations. The results are summarized in the table below.

Key observations: In the presence of compound X, the x-intercept of the Lineweaver-Burk plot shifted to a less negative value while the y-intercept remained unchanged. In the presence of compound Y, the y-intercept increased while the x-intercept remained unchanged.`,
    tableData: {
      headers: ['Condition', 'Vmax (nmol/min)', 'Km (mM)', 'x-intercept change', 'y-intercept change'],
      rows: [
        ['No inhibitor', '120', '2.0', 'baseline', 'baseline'],
        ['+ Compound X', '120', '6.0', 'shifts right', 'unchanged'],
        ['+ Compound Y', '60', '2.0', 'unchanged', 'increases'],
        ['+ Both X and Y', '60', '6.0', 'shifts right', 'increases'],
      ],
      caption: 'Table 1. Enzyme kinetics under inhibitory conditions',
    },
    question: 'A follow-up experiment tests whether Compound X is reversible by adding excess substrate after inhibition. If Compound X is a reversible competitive inhibitor, which result would be expected?',
    choices: [
      { label: 'A', text: 'Enzyme activity returns to near-baseline Vmax at saturating substrate concentrations' },
      { label: 'B', text: 'Km decreases to below the uninhibited baseline' },
      { label: 'C', text: 'Enzyme activity remains permanently suppressed regardless of substrate concentration' },
      { label: 'D', text: 'Vmax decreases proportionally to the increase in Km' },
    ],
    correctAnswer: 'A',
    explanation: 'Choice A is correct. A reversible competitive inhibitor binds the active site non-covalently and can be displaced by substrate. Adding excess substrate shifts the equilibrium toward enzyme-substrate complex formation, outcompeting the inhibitor. At saturating substrate, activity approaches the uninhibited Vmax because the apparent Km increases but maximum velocity is unaffected. This is the defining feature of reversible competitive inhibition: "competable out" by excess substrate.',
    wrongAnswerExplanations: {
      B: 'Km cannot decrease below baseline by adding more substrate; excess substrate displaces the competitive inhibitor, restoring normal Km, but does not lower it further. A sub-baseline Km would imply an activator or allosteric effect, not substrate displacement of a competitive inhibitor.',
      C: 'Permanent suppression regardless of substrate concentration describes irreversible inhibition (covalent), not reversible competitive inhibition. Reversible inhibitors are definitionally displaced by competition.',
      D: 'Vmax and Km do not change proportionally for competitive inhibitors — Vmax stays constant while apparent Km increases. Proportional changes in both would describe uncompetitive inhibition.',
    },
    teachingPoint: 'Reversible competitive inhibitors can always be overcome by adding enough substrate, which restores full Vmax. This distinguishes them from irreversible inhibitors (permanent, covalent) and noncompetitive inhibitors (Vmax cannot be restored regardless of substrate).',
    relatedTopics: ['Reversible vs irreversible inhibition', 'Enzyme kinetics', 'Competitive inhibition', 'Substrate competition'],
  },
  {
    id: 'mcat-qb-cp-003',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'General Chemistry',
    contentCategory: '5A: Acid/base equilibria',
    foundationalConcept: '5: The principles that govern chemical interactions',
    scientificSkill: 'Skill 4',
    difficulty: 'hard',
    questionType: 'passage',
    passageText: `A researcher studied the kinetics of a purified protease under four conditions. Reaction velocity was measured at varying substrate concentrations. A Lineweaver-Burk (double-reciprocal) plot was constructed from the data. Two inhibitors, compound X and compound Y, were then tested at fixed inhibitor concentrations. The results are summarized in the table below.

Key observations: In the presence of compound X, the x-intercept of the Lineweaver-Burk plot shifted to a less negative value while the y-intercept remained unchanged. In the presence of compound Y, the y-intercept increased while the x-intercept remained unchanged.`,
    tableData: {
      headers: ['Condition', 'Vmax (nmol/min)', 'Km (mM)', 'x-intercept change', 'y-intercept change'],
      rows: [
        ['No inhibitor', '120', '2.0', 'baseline', 'baseline'],
        ['+ Compound X', '120', '6.0', 'shifts right', 'unchanged'],
        ['+ Compound Y', '60', '2.0', 'unchanged', 'increases'],
        ['+ Both X and Y', '60', '6.0', 'shifts right', 'increases'],
      ],
      caption: 'Table 1. Enzyme kinetics under inhibitory conditions',
    },
    question: 'The protease is most active at pH 7.4. The researcher buffers the reaction at pH 7.4 using a phosphate buffer (pKa2 = 7.2). What is the approximate ratio of [HPO₄²⁻] to [H₂PO₄⁻] in this buffer?',
    choices: [
      { label: 'A', text: '1:1.6' },
      { label: 'B', text: '1.2:1' },
      { label: 'C', text: '1.6:1' },
      { label: 'D', text: '2.4:1' },
    ],
    correctAnswer: 'C',
    explanation: 'Choice C is correct. Using the Henderson-Hasselbalch equation: pH = pKa + log([A⁻]/[HA]). Here pH = 7.4 and pKa = 7.2. So 7.4 = 7.2 + log([HPO₄²⁻]/[H₂PO₄⁻]). This gives log([HPO₄²⁻]/[H₂PO₄⁻]) = 0.2, so [HPO₄²⁻]/[H₂PO₄⁻] = 10^0.2 ≈ 1.58. The ratio HPO₄²⁻ : H₂PO₄⁻ ≈ 1.6 : 1.',
    wrongAnswerExplanations: {
      A: 'A ratio of 1:1.6 would mean H₂PO₄⁻ exceeds HPO₄²⁻, implying the pH is below the pKa (below 7.2). At pH 7.4 (above pKa 7.2), the conjugate base (HPO₄²⁻) must predominate.',
      B: 'A ratio of 1.2:1 is too small. 10^0.2 ≈ 1.58, not 1.2. This would correspond to a pH difference of about +0.08 above pKa, not +0.2.',
      D: 'A ratio of 2.4:1 would correspond to log(2.4) ≈ 0.38, meaning the pH would be pKa + 0.38 = 7.58, not 7.4. The calculation gives 10^0.2 ≈ 1.58.',
    },
    teachingPoint: 'Henderson-Hasselbalch: pH = pKa + log([base]/[acid]). When pH > pKa, the conjugate base predominates. The ratio equals 10^(pH−pKa). At pH 7.4 and pKa 7.2, ratio = 10^0.2 ≈ 1.6 (base:acid).',
    relatedTopics: ['Henderson-Hasselbalch equation', 'Buffer systems', 'Phosphate buffer', 'Acid-base equilibria'],
  },

  // ── Discrete questions ────────────────────────────────────────────────────────
  {
    id: 'mcat-qb-cp-004',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'Physics',
    contentCategory: '4B: Fluids',
    foundationalConcept: '4: Physical and chemical principles govern living systems',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    questionType: 'discrete',
    question: 'Blood flows from a wide artery (radius 4 mm) into a narrower arteriole (radius 1 mm). Assuming ideal laminar flow and incompressible fluid, by what factor does the flow velocity increase in the arteriole?',
    choices: [
      { label: 'A', text: '4-fold' },
      { label: 'B', text: '8-fold' },
      { label: 'C', text: '16-fold' },
      { label: 'D', text: '64-fold' },
    ],
    correctAnswer: 'C',
    explanation: 'Choice C is correct. By the continuity equation for incompressible flow, A₁v₁ = A₂v₂. Cross-sectional area A = πr². The ratio of areas is (r₁/r₂)² = (4/1)² = 16. Since A₁v₁ = A₂v₂, the velocity ratio v₂/v₁ = A₁/A₂ = πr₁²/πr₂² = (4mm)²/(1mm)² = 16. Velocity increases 16-fold in the narrower vessel.',
    wrongAnswerExplanations: {
      A: 'A 4-fold increase would apply if velocity scaled with the radius ratio directly (4:1). But velocity scales with area, which is proportional to r², so the factor is 4² = 16, not 4.',
      B: 'An 8-fold increase has no physical basis here. The correct relationship uses area (πr²), giving a factor of 16.',
      D: '64-fold would correspond to r³ scaling, which would apply to a volume calculation, not velocity. Velocity scales with r² (area ratio) per the continuity equation.',
    },
    teachingPoint: 'The continuity equation (A₁v₁ = A₂v₂) governs ideal fluid flow. Velocity is inversely proportional to cross-sectional area. Since area scales as r², halving the radius quadruples the velocity. In MCAT cardiovascular physiology, narrow vessels have much higher blood velocity than wide ones.',
    relatedTopics: ['Continuity equation', 'Bernoulli principle', 'Cardiovascular physiology', 'Fluid dynamics'],
  },
  {
    id: 'mcat-qb-cp-005',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'General Chemistry',
    contentCategory: '5E: Electrochemistry',
    foundationalConcept: '5: Chemical interactions and thermodynamics',
    scientificSkill: 'Skill 4',
    difficulty: 'hard',
    questionType: 'discrete',
    question: 'For the electrochemical cell Zn(s) | Zn²⁺(aq) || Cu²⁺(aq) | Cu(s), E°cell = +1.10 V. At 25°C, [Zn²⁺] = 0.1 M and [Cu²⁺] = 0.001 M. Using the Nernst equation (RT/F ≈ 0.0257 V at 25°C), what is the approximate cell potential?',
    choices: [
      { label: 'A', text: '+1.04 V' },
      { label: 'B', text: '+1.07 V' },
      { label: 'C', text: '+1.10 V' },
      { label: 'D', text: '+1.16 V' },
    ],
    correctAnswer: 'A',
    explanation: 'Choice A is correct. The overall reaction is Zn + Cu²⁺ → Zn²⁺ + Cu, with n = 2 electrons. The reaction quotient Q = [Zn²⁺]/[Cu²⁺] = 0.1/0.001 = 100. Using the Nernst equation: E = E° − (RT/nF) × ln Q = 1.10 − (0.0257/2) × ln(100) = 1.10 − 0.01285 × 4.605 ≈ 1.10 − 0.059 ≈ 1.04 V.',
    wrongAnswerExplanations: {
      B: '+1.07 V would result from an error in the calculation, possibly using log₁₀ without converting or using n=1 instead of n=2. The correct application gives approximately 1.04 V.',
      C: '+1.10 V is the standard cell potential (E°), which only applies when all concentrations are 1 M. Since [Cu²⁺] < 1 M and [Zn²⁺] > 1 M (relative to the standard), Q > 1 and E < E°.',
      D: '+1.16 V would imply E > E°, which requires Q < 1 (i.e., [Zn²⁺] < [Cu²⁺]). Here [Zn²⁺] = 0.1 M > [Cu²⁺] = 0.001 M, so Q > 1 and E must be less than E°, not greater.',
    },
    teachingPoint: 'The Nernst equation: E = E° − (0.0592/n) × log Q at 25°C. When Q > 1 (products favored over reactants relative to standard), E < E°. When Q < 1, E > E°. Remember n is the number of electrons transferred in the balanced cell reaction.',
    relatedTopics: ['Nernst equation', 'Electrochemical cells', 'Galvanic cells', 'Reduction potentials'],
  },
  {
    id: 'mcat-qb-cp-006',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'General Chemistry',
    contentCategory: '5C: Thermodynamics',
    foundationalConcept: '5: Thermodynamics and chemical equilibrium',
    scientificSkill: 'Skill 4',
    difficulty: 'hard',
    questionType: 'discrete',
    question: 'A reaction has ΔH = −80 kJ/mol and ΔS = −200 J/(mol·K). At what temperature (in Kelvin) does this reaction transition from spontaneous to non-spontaneous?',
    choices: [
      { label: 'A', text: '200 K' },
      { label: 'B', text: '250 K' },
      { label: 'C', text: '400 K' },
      { label: 'D', text: '800 K' },
    ],
    correctAnswer: 'C',
    explanation: 'Choice C is correct. Spontaneity is determined by ΔG = ΔH − TΔS. The reaction is spontaneous (ΔG < 0) when ΔH < TΔS. Setting ΔG = 0 gives the crossover temperature: T = ΔH/ΔS = −80,000 J/mol ÷ (−200 J/mol·K) = 400 K. Below 400 K, ΔG < 0 (spontaneous). Above 400 K, the −TΔS term (positive since ΔS < 0) dominates and ΔG > 0 (non-spontaneous).',
    wrongAnswerExplanations: {
      A: '200 K results from a calculation error, possibly dividing 80 kJ/mol by 400 J/(mol·K) instead of 200 J/(mol·K), or by a factor-of-2 mistake. The correct answer is 80,000/200 = 400 K.',
      B: '250 K would require ΔH/ΔS = 250, meaning either ΔH = −50 kJ or ΔS = −320 J/(mol·K). Neither matches the given values.',
      D: '800 K results from an error such as using ΔH = −160 kJ or ΔS = −100 J/(mol·K), or a factor-of-2 mistake. The correct division is 80,000 J / 200 J/K = 400 K.',
    },
    teachingPoint: 'When ΔH < 0 and ΔS < 0: spontaneous only at low T. The crossover temperature is T = ΔH/ΔS (both in same units). Above this T, the entropy penalty (−TΔS > 0 since ΔS < 0) outweighs the enthalpy benefit, and the reaction becomes non-spontaneous.',
    relatedTopics: ['Gibbs free energy', 'Thermodynamic spontaneity', 'Entropy and enthalpy', 'Thermodynamic crossover temperature'],
  },
  {
    id: 'mcat-qb-cp-007',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'Organic Chemistry',
    contentCategory: '1C: Separation and purification',
    foundationalConcept: '1: Structure and function of biomolecules',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    questionType: 'discrete',
    question: 'An amino acid with a side chain pKa of 10.5 is dissolved in a buffer at pH 7.4. What is the predominant ionization state of its side chain?',
    choices: [
      { label: 'A', text: 'Fully protonated (positively charged) because pH < pKa' },
      { label: 'B', text: 'Fully deprotonated (negatively charged) because pH > pKa' },
      { label: 'C', text: 'Approximately 50% protonated because pH is near the pKa' },
      { label: 'D', text: 'Uncharged because it is a neutral amino acid side chain' },
    ],
    correctAnswer: 'A',
    explanation: 'Choice A is correct. When pH < pKa, the protonated form predominates. Here pH 7.4 < pKa 10.5 by 3.1 units, meaning the ratio of protonated to deprotonated form = 10^(pKa − pH) = 10^3.1 ≈ 1259:1. The side chain is overwhelmingly in the protonated (positively charged) state. This is characteristic of lysine (pKa ~10.5), which carries a positive charge at physiological pH.',
    wrongAnswerExplanations: {
      B: 'Deprotonation predominates when pH > pKa. At pH 7.4 with pKa 10.5, pH is well below pKa, so the protonated (charged) form predominates, not the deprotonated form.',
      C: '50% protonation occurs only when pH ≈ pKa (within about ±0.3 units). Here the difference is 3.1 pH units, yielding a >1000:1 ratio — far from 50/50.',
      D: 'A pKa of 10.5 belongs to a basic side chain like lysine (−NH₃⁺/−NH₂), not a neutral side chain. Neutral side chains include those of glycine, alanine, and valine.',
    },
    teachingPoint: 'A rule of thumb: when pH is more than 2 units below pKa, >99% of the group is protonated. For amino acid side chains, knowing whether pH is above or below the side chain pKa tells you the charge state. Lysine, arginine, and histidine carry positive charges at pH 7.4; aspartate and glutamate carry negative charges.',
    relatedTopics: ['Amino acid ionization', 'pKa and pH', 'Henderson-Hasselbalch', 'Protein charge'],
  },
  {
    id: 'mcat-qb-cp-008',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'Physics',
    contentCategory: '4C: Circuits',
    foundationalConcept: '4: Physical principles',
    scientificSkill: 'Skill 4',
    difficulty: 'hard',
    questionType: 'discrete',
    question: 'Three resistors of 2 Ω, 4 Ω, and 6 Ω are connected in parallel across a 12 V battery. What is the total current drawn from the battery?',
    choices: [
      { label: 'A', text: '1.0 A' },
      { label: 'B', text: '4.0 A' },
      { label: 'C', text: '6.0 A' },
      { label: 'D', text: '11 A' },
    ],
    correctAnswer: 'D',
    explanation: 'Choice D is correct. In a parallel circuit, the total current is the sum of branch currents. Each branch has the full 12 V applied. I₁ = 12/2 = 6 A; I₂ = 12/4 = 3 A; I₃ = 12/6 = 2 A. Total current = 6 + 3 + 2 = 11 A. Alternatively, 1/R_total = 1/2 + 1/4 + 1/6 = 6/12 + 3/12 + 2/12 = 11/12, so R_total = 12/11 Ω and I = V/R = 12/(12/11) = 11 A.',
    wrongAnswerExplanations: {
      A: '1.0 A would be the current through a single 12 Ω resistor, not three parallel resistors. Parallel circuits always draw more total current than any single branch.',
      B: '4.0 A appears to use I = V/R_avg where R_avg = 3 Ω — but average resistance is not the correct formula for parallel resistors. The reciprocal rule must be used: 1/R_p = sum of 1/R_i.',
      C: '6.0 A is the current through only the 2 Ω branch (I = 12/2 = 6 A). The total current must include contributions from all three parallel branches.',
    },
    teachingPoint: 'In a parallel circuit: (1) voltage is the same across all branches; (2) total current = sum of branch currents; (3) equivalent resistance is found via 1/R_eq = 1/R₁ + 1/R₂ + 1/R₃. Adding parallel branches always decreases total resistance and increases total current.',
    relatedTopics: ['Parallel circuits', 'Ohm\'s law', 'Kirchhoff\'s laws', 'Electrical resistance'],
  },
  {
    id: 'mcat-qb-cp-009',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'Organic Chemistry',
    contentCategory: '1I: Spectroscopy',
    foundationalConcept: '1: Structure and function',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    questionType: 'discrete',
    question: 'An unknown organic compound shows a broad IR absorption around 3300 cm⁻¹ and a sharp absorption at 1715 cm⁻¹. The ¹H NMR shows a singlet at ~11 ppm (1H) and a quartet-triplet pattern in the alkyl region. Which compound is most consistent with these data?',
    choices: [
      { label: 'A', text: 'Ethanol' },
      { label: 'B', text: 'Propanal' },
      { label: 'C', text: 'Propanoic acid' },
      { label: 'D', text: 'Acetone' },
    ],
    correctAnswer: 'C',
    explanation: 'Choice C is correct. The broad 3300 cm⁻¹ absorption is characteristic of O−H stretch (carboxylic acid O−H is broad due to hydrogen bonding). The 1715 cm⁻¹ absorption is a C=O stretch typical of a carboxylic acid (aldehydes absorb ~1720–1740, ketones ~1715–1720, carboxylic acids ~1700–1725). The NMR singlet around 11 ppm is the highly deshielded carboxylic acid proton. Propanoic acid (CH₃CH₂COOH) would show a quartet (CH₂, n+1 = 3 adjacent H) and a triplet (CH₃, n+1 = 2 adjacent H) in the alkyl region, consistent with the data.',
    wrongAnswerExplanations: {
      A: 'Ethanol would show a broad O−H stretch at ~3300 cm⁻¹ but lacks the C=O stretch at 1715 cm⁻¹. Ethanol has no carbonyl group, and its O−H proton appears around 2–5 ppm in NMR, not 11 ppm.',
      B: 'Propanal would show a C=O stretch (aldehyde) at ~1720–1740 cm⁻¹, which overlaps, but the NMR would show an aldehyde C−H at ~9–10 ppm (not 11 ppm), not the very downfield carboxylic acid proton. Propanal also lacks a broad O−H stretch.',
      D: 'Acetone has no O−H group, so it would not show a broad 3300 cm⁻¹ stretch. Its C=O absorbs around 1710–1720 cm⁻¹, but the absence of O−H and alkyl quartet-triplet pattern (acetone is a symmetric methyl ketone) rules it out.',
    },
    teachingPoint: 'IR fingerprints: O−H carboxylic acid ≈ 2500–3300 cm⁻¹ (very broad); O−H alcohol ≈ 3200–3550 cm⁻¹ (broad); carboxylic acid C=O ≈ 1700–1725 cm⁻¹. The NMR carboxylic acid proton is the most downfield proton in organic molecules (~10–12 ppm). Quartet-triplet coupling patterns identify adjacent CH₂−CH₃ groups.',
    relatedTopics: ['IR spectroscopy', 'NMR spectroscopy', 'Carboxylic acids', 'Functional group identification'],
  },
  {
    id: 'mcat-qb-cp-010',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'Physics',
    contentCategory: '4A: Translational motion',
    scientificSkill: 'Skill 3',
    foundationalConcept: '4: Physical principles',
    difficulty: 'medium',
    questionType: 'discrete',
    question: 'A researcher wants to determine whether the viscosity of a biological fluid affects ultrasound propagation speed. Which experimental design best isolates the effect of viscosity while controlling for other variables?',
    choices: [
      { label: 'A', text: 'Measure sound speed in fluids with identical density but varying viscosity by adding a viscosity-modifying polymer at different concentrations' },
      { label: 'B', text: 'Compare sound speed in water at different temperatures, since viscosity changes with temperature' },
      { label: 'C', text: 'Use fluids with different molecular compositions to achieve different viscosity values' },
      { label: 'D', text: 'Measure sound speed in a single fluid before and after heating to reduce viscosity' },
    ],
    correctAnswer: 'A',
    explanation: 'Choice A is correct. To isolate the effect of viscosity, the ideal design holds all other variables constant (density, temperature, molecular composition) while varying only viscosity. Adding a polymer at different concentrations to an identical base fluid controls density (approximately constant at low polymer concentrations) and temperature while modulating viscosity. This is the most controlled approach to test viscosity as the independent variable.',
    wrongAnswerExplanations: {
      B: 'Changing temperature to alter viscosity is a poor design because temperature also changes density, thermal expansion, and molecular kinetic energy — all of which independently affect sound propagation. This confounds the independent variable (viscosity) with multiple other changes.',
      C: 'Using fluids with different molecular compositions introduces confounds: different molecules have different compressibility, density, and intermolecular forces, making it impossible to attribute differences in sound speed to viscosity alone.',
      D: 'Heating a single fluid changes both viscosity and temperature simultaneously. Since sound speed depends on temperature (and density), this design cannot isolate the viscosity effect from the thermal effect.',
    },
    teachingPoint: 'Good experimental design requires controlling all variables except the independent variable. On the MCAT, look for designs that isolate the variable of interest — changing multiple factors simultaneously creates confounds that prevent valid causal inference. The best designs use a single-variable manipulation in a matched system.',
    relatedTopics: ['Experimental design', 'Scientific controls', 'Sound propagation', 'Variables and confounds'],
  },
  {
    id: 'mcat-qb-cp-011',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'Physics',
    contentCategory: '4D: Light and optics',
    foundationalConcept: '4: Physical principles',
    scientificSkill: 'Skill 4',
    difficulty: 'easy',
    questionType: 'discrete',
    question: 'A converging lens has a focal length of 20 cm. An object is placed 30 cm from the lens. Where does the image form, and what is its nature?',
    choices: [
      { label: 'A', text: '12 cm on the same side as the object; virtual and upright' },
      { label: 'B', text: '60 cm on the same side as the object; virtual and upright' },
      { label: 'C', text: '60 cm on the opposite side; real and inverted' },
      { label: 'D', text: '12 cm on the opposite side; real and inverted' },
    ],
    correctAnswer: 'C',
    explanation: 'Choice C is correct. Using the thin lens equation: 1/f = 1/do + 1/di. With f = 20 cm and do = 30 cm: 1/20 = 1/30 + 1/di → 1/di = 1/20 − 1/30 = 3/60 − 2/60 = 1/60 → di = 60 cm. A positive image distance means the image forms on the opposite side of the lens from the object (real image). Real images formed by converging lenses are inverted.',
    wrongAnswerExplanations: {
      A: 'A virtual image (same side as object) from a converging lens only forms when the object is inside the focal length (do < f). Here do = 30 cm > f = 20 cm, so a real image forms. 12 cm results from incorrectly using 1/di = 1/f − 1/do with wrong signs or formula.',
      B: '60 cm is the correct image distance, but a virtual image would require the image to be on the same side as the object. Since di is positive (from correct application of the formula), it is real and on the opposite side.',
      D: '12 cm results from an algebraic error (e.g., subtracting fractions in reverse: 1/30 − 1/20 = −1/60, taking the magnitude). The correct application gives di = +60 cm, not 12 cm.',
    },
    teachingPoint: 'Thin lens equation: 1/f = 1/do + 1/di. For a converging lens (f > 0) with object beyond the focal point (do > f): image is real (di > 0, opposite side) and inverted. Magnification m = −di/do. The negative sign means inversion. Virtual images form only when do < f for converging lenses.',
    relatedTopics: ['Thin lens equation', 'Converging lenses', 'Ray optics', 'Real vs virtual images'],
  },
  {
    id: 'mcat-qb-cp-012',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'Organic Chemistry',
    contentCategory: '1H: Stereochemistry and reaction mechanisms',
    foundationalConcept: '1: Biomolecule structure',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    questionType: 'discrete',
    question: 'A secondary alkyl bromide is treated with sodium ethoxide (NaOEt) in ethanol. Which statement best predicts the major product and mechanism?',
    choices: [
      { label: 'A', text: 'SN2 substitution predominates because ethoxide is a strong nucleophile and the substrate is secondary' },
      { label: 'B', text: 'SN1 substitution predominates because secondary carbocations are stable in a polar protic solvent' },
      { label: 'C', text: 'E2 elimination predominates because ethoxide is a strong, bulky base in polar protic conditions' },
      { label: 'D', text: 'E2 elimination predominates because ethoxide is a strong base and secondary substrates favor elimination over SN2' },
    ],
    correctAnswer: 'D',
    explanation: 'Choice D is correct. Sodium ethoxide (NaOEt) is a strong, relatively non-bulky base. For secondary alkyl halides with a strong base, E2 elimination is favored over SN2 because the secondary carbon has significant steric hindrance that slows SN2, while the strong base can abstract a β-hydrogen to drive E2. In a polar protic solvent (ethanol), SN1 is possible but NaOEt is too strong a base to allow SN1 to dominate. E2 is the major pathway for secondary substrates with strong bases.',
    wrongAnswerExplanations: {
      A: 'SN2 is favored for primary substrates with strong nucleophiles/bases. Secondary substrates have enough steric hindrance at the reaction center to disfavor SN2 relative to E2 when a strong base is present. The ethoxide acts primarily as a base here, not a nucleophile.',
      B: 'SN1 requires a stable carbocation. Secondary carbocations are marginally stable, but NaOEt is a strong base that promotes E2 more efficiently than SN1. SN1 is favored by weak nucleophiles and polar protic solvents without strong bases.',
      C: 'The statement correctly says E2 predominates, but calls ethoxide "bulky" — ethoxide (CH₃CH₂O⁻) is not a bulky base. Bulky bases like tert-butoxide (t-BuO⁻) favor Hofmann (less substituted) elimination products. Ethoxide gives Zaitsev (more substituted) product via E2, but the mechanism description is otherwise correct.',
    },
    teachingPoint: 'Decision tree for secondary alkyl halides: strong base → E2 predominates over SN2; weak nucleophile/polar protic → SN1 possible. For primary: SN2 preferred. Key: SN2 rate decreases 1° > 2° >> 3° due to steric effects, while E2 rate follows 3° > 2° > 1°.',
    relatedTopics: ['SN1 vs SN2 vs E1 vs E2', 'Nucleophilic substitution', 'Elimination reactions', 'Substrate and base effects'],
  },
  {
    id: 'mcat-qb-cp-013',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'Physics',
    contentCategory: '4A: Waves and sound',
    foundationalConcept: '4: Physical principles',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    questionType: 'discrete',
    question: 'A string fixed at both ends vibrates at its fundamental frequency. If the length of the string is doubled while tension and linear density remain constant, what happens to the fundamental frequency?',
    choices: [
      { label: 'A', text: 'It increases by a factor of 2' },
      { label: 'B', text: 'It decreases by a factor of 2' },
      { label: 'C', text: 'It decreases by a factor of 4' },
      { label: 'D', text: 'It remains the same because tension is unchanged' },
    ],
    correctAnswer: 'B',
    explanation: 'Choice B is correct. The fundamental frequency of a string fixed at both ends is f = v/(2L), where v = √(T/μ) is the wave speed (T = tension, μ = linear mass density). Since T and μ are unchanged, v is unchanged. Doubling L gives f_new = v/(2 × 2L) = f_original/2. The fundamental frequency decreases by a factor of 2.',
    wrongAnswerExplanations: {
      A: 'Frequency increasing by a factor of 2 would require halving the length, not doubling it. f = v/(2L), so f ∝ 1/L — frequency and length are inversely proportional.',
      C: 'A factor of 4 decrease would occur if L were squared in the denominator, but the relationship is f ∝ 1/L (linear inverse), not 1/L². Doubling L halves the frequency.',
      D: 'Tension determines wave speed but frequency also depends on string length. f = v/(2L), so even at constant v (constant T and μ), changing L directly changes f. Tension unchanged does not mean frequency unchanged.',
    },
    teachingPoint: 'Fundamental frequency of a fixed string: f₁ = v/(2L) where v = √(T/μ). Frequency is inversely proportional to length and directly proportional to √(tension/linear density). This has analogues in MCAT biology: longer vocal cords produce lower pitch.',
    relatedTopics: ['Standing waves', 'String harmonics', 'Wave speed formula', 'Acoustics'],
  },

  // ── 10 additional discrete questions ─────────────────────────────────────────
  {
    id: 'mcat-qb-cp-014',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'General Chemistry',
    contentCategory: '5D: Nuclear chemistry',
    foundationalConcept: '5: Physical and chemical principles',
    scientificSkill: 'Skill 4',
    difficulty: 'medium',
    questionType: 'discrete',
    question: 'A radioactive isotope has a half-life of 8 days. A hospital receives a 400 mg sample. How many milligrams remain after 24 days?',
    choices: [
      { label: 'A', text: '50 mg' },
      { label: 'B', text: '100 mg' },
      { label: 'C', text: '200 mg' },
      { label: 'D', text: '25 mg' },
    ],
    correctAnswer: 'A',
    explanation: 'Choice A is correct. The number of half-lives elapsed = 24 days ÷ 8 days/half-life = 3 half-lives. After each half-life the amount halves: 400 → 200 → 100 → 50 mg. After 3 half-lives, 400 × (1/2)³ = 400/8 = 50 mg remain.',
    wrongAnswerExplanations: {
      B: '100 mg corresponds to 2 half-lives (400 → 200 → 100). Three half-lives have elapsed (24 ÷ 8 = 3), so one additional halving is required: 100 → 50 mg.',
      C: '200 mg corresponds to only 1 half-life. After 24 days (3 half-lives), the amount is one-eighth of the original, not one-half.',
      D: '25 mg would correspond to 4 half-lives (32 days). Only 3 half-lives have elapsed in 24 days, leaving 50 mg.',
    },
    teachingPoint: 'Half-life formula: N = N₀ × (1/2)^n, where n = t/t½. Count the number of half-lives first (t ÷ t½), then apply repeated halving. Iodine-131 (t½ = 8 days) is a real radioisotope used in thyroid imaging and therapy — making this calculation clinically relevant.',
    relatedTopics: ['Radioactive decay', 'Half-life', 'Nuclear medicine', 'Exponential decay'],
  },
  {
    id: 'mcat-qb-cp-015',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'General Chemistry',
    contentCategory: '5A: Acid-base equilibria',
    foundationalConcept: '5: Chemical interactions',
    scientificSkill: 'Skill 2',
    difficulty: 'hard',
    questionType: 'discrete',
    question: 'A 50.0 mL solution of 0.100 M acetic acid (pKa = 4.74) is titrated with 0.100 M NaOH. At the half-equivalence point, what is the approximate pH?',
    choices: [
      { label: 'A', text: '3.74' },
      { label: 'B', text: '5.00' },
      { label: 'C', text: '4.74' },
      { label: 'D', text: '7.00' },
    ],
    correctAnswer: 'C',
    explanation: 'Choice C is correct. At the half-equivalence point, exactly half the acid has been neutralized. This means [CH₃COOH] = [CH₃COO⁻]. Applying Henderson-Hasselbalch: pH = pKa + log([A⁻]/[HA]) = 4.74 + log(1) = 4.74 + 0 = 4.74. The pH equals the pKa at the half-equivalence point — a fundamental relationship useful for identifying unknown acids from titration curves.',
    wrongAnswerExplanations: {
      A: '3.74 = pKa − 1.00, which would correspond to [HA]/[A⁻] = 10 (90% protonated). At the half-equivalence point the ratio is 1:1, so pH = pKa exactly, not pKa − 1.',
      B: '5.00 would imply pH = pKa + 0.26, which would require [A⁻]/[HA] = 10^0.26 ≈ 1.8. At the half-equivalence point the ratio is exactly 1:1, giving pH = pKa = 4.74.',
      D: '7.00 is the pH at the equivalence point of a strong acid-strong base titration, not an acetic acid-NaOH titration. The equivalence point for a weak acid-strong base titration is basic (>7), not 7.00.',
    },
    teachingPoint: 'Key titration landmarks: (1) Half-equivalence point: pH = pKa (buffer region maximum capacity). (2) Equivalence point: weak acid/strong base → basic pH (conjugate base in solution). (3) Past equivalence: excess NaOH drives pH toward 13–14. Reading pKa from a titration curve is done at the half-equivalence volume.',
    relatedTopics: ['Titration curves', 'Half-equivalence point', 'pKa identification', 'Buffer region', 'Weak acid titration'],
  },
  {
    id: 'mcat-qb-cp-016',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'General Chemistry',
    contentCategory: '5B: Gas phase',
    foundationalConcept: '5: Chemical principles',
    scientificSkill: 'Skill 4',
    difficulty: 'medium',
    questionType: 'discrete',
    question: 'A gas occupies 4.0 L at 300 K and 2.0 atm. If the pressure is increased to 4.0 atm and the temperature raised to 600 K, what is the new volume?',
    choices: [
      { label: 'A', text: '1.0 L' },
      { label: 'B', text: '2.0 L' },
      { label: 'C', text: '4.0 L' },
      { label: 'D', text: '8.0 L' },
    ],
    correctAnswer: 'C',
    explanation: 'Choice C is correct. Using the combined gas law: P₁V₁/T₁ = P₂V₂/T₂. Solving for V₂: V₂ = V₁ × (P₁/P₂) × (T₂/T₁) = 4.0 L × (2.0/4.0) × (600/300) = 4.0 × 0.5 × 2.0 = 4.0 L. Doubling the pressure halves the volume, but doubling the temperature doubles the volume — the effects cancel and volume is unchanged.',
    wrongAnswerExplanations: {
      A: '1.0 L would result from applying only the pressure change (4.0 × 0.5 = 2.0) then halving again, or from incorrectly applying temperature in the denominator instead of numerator. Both T and P changes must be applied together.',
      B: '2.0 L results from applying only the pressure change (4.0 × (2/4) = 2.0 L) without accounting for the temperature increase. Both the pressure and temperature effects must be applied simultaneously.',
      D: '8.0 L would result from doubling the volume for pressure and doubling again for temperature, which incorrectly treats both changes as volume-increasing. Pressure increase decreases volume; only temperature increase increases volume.',
    },
    teachingPoint: 'Combined gas law: P₁V₁/T₁ = P₂V₂/T₂ (for fixed amount of ideal gas). Temperature must be in Kelvin. Check each variable\'s effect on volume: increasing P decreases V (inverse); increasing T increases V (direct). When both change, evaluate the net effect by applying both ratios.',
    relatedTopics: ['Combined gas law', 'Boyle\'s law', 'Charles\'s law', 'Ideal gas', 'PV = nRT'],
  },
  {
    id: 'mcat-qb-cp-017',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'General Chemistry',
    contentCategory: '5C: Chemical equilibrium',
    foundationalConcept: '5: Thermodynamics and equilibrium',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    questionType: 'discrete',
    question: 'For the reaction N₂(g) + 3H₂(g) ⇌ 2NH₃(g), the system is at equilibrium. If the total pressure is suddenly doubled (by compressing the container), in which direction will the equilibrium shift according to Le Chatelier\'s principle?',
    choices: [
      { label: 'A', text: 'Toward the products (right), because the product side has fewer moles of gas' },
      { label: 'B', text: 'Toward the reactants (left), because the reactant side has more moles of gas' },
      { label: 'C', text: 'No shift occurs because the temperature is unchanged' },
      { label: 'D', text: 'No shift occurs because pressure does not affect equilibria involving gases' },
    ],
    correctAnswer: 'A',
    explanation: 'Choice A is correct. The reactant side has 1 + 3 = 4 moles of gas; the product side has 2 moles. When pressure is increased, Le Chatelier\'s principle states the system will shift toward the side that reduces pressure — the side with fewer moles of gas. Since the product side (2 mol gas) has fewer moles than the reactant side (4 mol gas), equilibrium shifts right, producing more NH₃.',
    wrongAnswerExplanations: {
      B: 'Shifting left would increase the number of gas moles (4 mol reactants > 2 mol products), which would increase pressure further — the opposite of relieving the perturbation. Le Chatelier\'s principle predicts relief, not amplification.',
      C: 'Temperature affects Keq (changing it). Pressure changes do not change Keq, but they do shift the position of equilibrium (Qc vs Kc changes upon compression). Temperature unchanged does not mean no shift — pressure effects independently shift equilibrium for reactions with unequal moles of gas.',
      D: 'Pressure effects on equilibrium are real for reactions with different numbers of moles of gas on each side. The shift magnitude depends on the difference in moles. For reactions with equal moles of gas on both sides (e.g., H₂ + I₂ ⇌ 2HI), pressure has no net effect.',
    },
    teachingPoint: 'Le Chatelier for pressure changes: compress → shift toward fewer moles of gas; expand → shift toward more moles of gas. Count moles of GAS only (ignore solids and liquids). The Haber process uses high pressure to shift N₂ + 3H₂ → 2NH₃ toward ammonia production.',
    relatedTopics: ['Le Chatelier\'s principle', 'Chemical equilibrium', 'Pressure effects', 'Haber process', 'Moles of gas'],
  },
  {
    id: 'mcat-qb-cp-018',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'General Chemistry',
    contentCategory: '5D: Nuclear reactions',
    foundationalConcept: '5: Physical chemistry',
    scientificSkill: 'Skill 1',
    difficulty: 'medium',
    questionType: 'discrete',
    question: 'Carbon-14 undergoes beta-minus (β⁻) decay. Which daughter nucleus is produced?',
    choices: [
      { label: 'A', text: 'Boron-14 (decrease in atomic number by 1)' },
      { label: 'B', text: 'Nitrogen-14 (increase in atomic number by 1, mass number unchanged)' },
      { label: 'C', text: 'Carbon-13 (decrease in mass number by 1)' },
      { label: 'D', text: 'Oxygen-14 (increase in atomic number by 2)' },
    ],
    correctAnswer: 'B',
    explanation: 'Choice B is correct. In beta-minus decay, a neutron in the nucleus is converted to a proton, emitting an electron (β⁻ particle) and an antineutrino. The atomic number (Z) increases by 1 (one more proton), but the mass number (A) remains the same (total nucleons unchanged). Carbon (Z=6) gains a proton → Nitrogen (Z=7). Mass number stays 14. The daughter is Nitrogen-14 (¹⁴N), the stable end product of C-14 radiocarbon decay.',
    wrongAnswerExplanations: {
      A: 'Atomic number decreasing by 1 (Z: 6→5, boron) would result from beta-plus (β⁺) decay or electron capture — not beta-minus decay. In β⁻, a proton is created, increasing Z.',
      C: 'Mass number decreasing by 1 would result from an alpha particle emission (which loses 4 mass units and 2 protons). Beta decay does not change the mass number — it only changes one neutron to a proton (or vice versa).',
      D: 'Atomic number increasing by 2 (Z: 6→8, oxygen) would require emission of two positrons or alpha decay of a different starting nucleus. Beta-minus decay changes Z by exactly +1.',
    },
    teachingPoint: 'Radioactive decay rules: α decay: Z−2, A−4. β⁻ decay: Z+1, A unchanged (neutron→proton + e⁻ + antineutrino). β⁺ decay: Z−1, A unchanged (proton→neutron + positron + neutrino). γ decay: neither Z nor A changes. Radiocarbon dating relies on ¹⁴C → ¹⁴N via β⁻.',
    relatedTopics: ['Radioactive decay types', 'Beta decay', 'Nuclear equations', 'Carbon-14 dating'],
  },
  {
    id: 'mcat-qb-cp-019',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'General Chemistry',
    contentCategory: '5F: Colligative properties',
    foundationalConcept: '5: Chemical principles',
    scientificSkill: 'Skill 2',
    difficulty: 'hard',
    questionType: 'discrete',
    question: 'A 1.0 molal aqueous solution of CaCl₂ (assumed to fully dissociate) has a boiling point elevation compared to pure water. The boiling point elevation constant (Kb) for water is 0.512 °C/m. What is the expected boiling point elevation?',
    choices: [
      { label: 'A', text: '0.512 °C' },
      { label: 'B', text: '1.024 °C' },
      { label: 'C', text: '1.536 °C' },
      { label: 'D', text: '2.048 °C' },
    ],
    correctAnswer: 'C',
    explanation: 'Choice C is correct. ΔTb = i × Kb × m, where i is the van\'t Hoff factor (number of particles per formula unit upon dissociation). CaCl₂ → Ca²⁺ + 2 Cl⁻, yielding i = 3 particles. ΔTb = 3 × 0.512 °C/m × 1.0 m = 1.536 °C.',
    wrongAnswerExplanations: {
      A: '0.512 °C would result from i = 1 (treating CaCl₂ as a non-electrolyte with no dissociation). CaCl₂ is a strong electrolyte that fully dissociates into 3 ions, giving i = 3.',
      B: '1.024 °C corresponds to i = 2, which would be correct for a 1:1 electrolyte like NaCl (Na⁺ + Cl⁻). CaCl₂ dissociates into 3 ions (1 Ca²⁺ + 2 Cl⁻), so i = 3.',
      D: '2.048 °C would require i = 4, which would correspond to a formula unit producing 4 ions (e.g., AlCl₃ → Al³⁺ + 3 Cl⁻). CaCl₂ produces only 3 ions per formula unit.',
    },
    teachingPoint: 'Colligative property formula: ΔTb = i × Kb × m; ΔTf = i × Kf × m; π = iMRT. The van\'t Hoff factor i accounts for dissociation: non-electrolytes i=1; NaCl i=2; CaCl₂ i=3; AlCl₃ i=4. Colligative properties depend only on the number of solute particles, not their identity.',
    relatedTopics: ['Colligative properties', 'Boiling point elevation', 'van\'t Hoff factor', 'Electrolyte dissociation'],
  },
  {
    id: 'mcat-qb-cp-020',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'Physics',
    contentCategory: '4A: Kinematics',
    foundationalConcept: '4: Physical principles',
    scientificSkill: 'Skill 4',
    difficulty: 'medium',
    questionType: 'discrete',
    question: 'A ball is launched horizontally from a cliff 80 m high with an initial horizontal velocity of 20 m/s. Assuming g = 10 m/s², how far from the base of the cliff does the ball land?',
    choices: [
      { label: 'A', text: '40 m' },
      { label: 'B', text: '60 m' },
      { label: 'C', text: '100 m' },
      { label: 'D', text: '80 m' },
    ],
    correctAnswer: 'D',
    explanation: 'Choice D is correct. For projectile motion, horizontal and vertical components are independent. Vertical: h = ½gt² → 80 = ½(10)t² → t² = 16 → t = 4 s. Horizontal: x = v₀ₓ × t = 20 m/s × 4 s = 80 m. The ball lands 80 m from the base.',
    wrongAnswerExplanations: {
      A: '40 m would result from t = 2 s, which corresponds to a fall height of h = ½(10)(4) = 20 m, not 80 m. The time of flight must be calculated from the 80 m drop: t = √(2h/g) = 4 s.',
      B: '60 m has no clear physical basis — it might result from using t = 3 s (corresponding to a 45 m fall) or another calculation error. Systematic application of kinematics gives t = 4 s and x = 80 m.',
      C: '100 m would require a time of flight of 5 s, which corresponds to h = ½(10)(25) = 125 m. The cliff height is 80 m, giving t = 4 s, not 5 s.',
    },
    teachingPoint: 'Projectile motion strategy: (1) Find time of flight from vertical equation (h = ½gt² for horizontal launch with v₀y = 0). (2) Use t in horizontal equation (x = v₀x × t, since there is no horizontal acceleration in ideal projectile motion). Horizontal and vertical motion are always independent.',
    relatedTopics: ['Projectile motion', 'Kinematics', 'Free fall', 'Horizontal launch'],
  },
  {
    id: 'mcat-qb-cp-021',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'Physics',
    contentCategory: '4D: Electromagnetic spectrum',
    foundationalConcept: '4: Physical principles',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    questionType: 'discrete',
    question: 'Light of wavelength 400 nm (violet) and 700 nm (red) are both visible. Which statement correctly compares their energies and frequencies?',
    choices: [
      { label: 'A', text: 'Violet light has higher frequency and higher energy than red light' },
      { label: 'B', text: 'Red light has higher frequency because it has a longer wavelength' },
      { label: 'C', text: 'Both have the same energy because both are visible light' },
      { label: 'D', text: 'Violet light has lower energy than red light because it has a shorter wavelength' },
    ],
    correctAnswer: 'A',
    explanation: 'Choice A is correct. For electromagnetic radiation: c = λν (speed = wavelength × frequency) and E = hν = hc/λ (energy). Shorter wavelength → higher frequency; higher frequency → higher energy. Violet (400 nm) has shorter wavelength than red (700 nm), therefore violet has higher frequency and higher photon energy. UV radiation causing sunburn and cancer is an extension of this principle: even higher frequency (shorter wavelength) carries enough energy to damage DNA.',
    wrongAnswerExplanations: {
      B: 'Longer wavelength corresponds to LOWER frequency (c = λν, so ν = c/λ — frequency and wavelength are inversely related). Red light has a longer wavelength (700 nm) and therefore a lower frequency than violet light.',
      C: 'All visible light photons do not have the same energy. Within the visible spectrum, energy increases from red to violet. The visible spectrum is defined by wavelength range (approximately 380–700 nm), not by a fixed energy.',
      D: 'This reverses the energy-wavelength relationship. E = hc/λ — shorter wavelength means higher energy (larger denominator means smaller energy is wrong: smaller λ → larger E). Violet (shorter λ) has more energy per photon than red (longer λ).',
    },
    teachingPoint: 'EM spectrum: γ rays > X-rays > UV > Visible (violet→red) > IR > Microwave > Radio. As wavelength decreases: frequency increases, energy increases. E = hν = hc/λ. Remember: "ROYGBIV" goes from lower energy (red) to higher energy (violet). This determines which radiation can ionize atoms and damage biological molecules.',
    relatedTopics: ['Electromagnetic spectrum', 'Photon energy', 'E = hν', 'Wavelength and frequency'],
  },
  {
    id: 'mcat-qb-cp-022',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'General Chemistry',
    contentCategory: '5E: Oxidation-reduction reactions',
    foundationalConcept: '5: Chemical interactions',
    scientificSkill: 'Skill 2',
    difficulty: 'hard',
    questionType: 'discrete',
    question: 'In the reaction: MnO₄⁻ + Fe²⁺ → Mn²⁺ + Fe³⁺ (acidic solution), which statement correctly identifies the oxidizing and reducing agents?',
    choices: [
      { label: 'A', text: 'Fe²⁺ is the oxidizing agent because it loses electrons to become Fe³⁺' },
      { label: 'B', text: 'MnO₄⁻ is the oxidizing agent because it gains electrons (Mn goes from +7 to +2)' },
      { label: 'C', text: 'Mn²⁺ is the reducing agent because it is produced when MnO₄⁻ is reduced' },
      { label: 'D', text: 'Both Fe²⁺ and MnO₄⁻ are oxidizing agents' },
    ],
    correctAnswer: 'B',
    explanation: 'Choice B is correct. In permanganate (MnO₄⁻), manganese has oxidation state +7. In Mn²⁺, manganese is +2. Manganese goes from +7 to +2 — a gain of 5 electrons (reduction). The species that is reduced is the oxidizing agent. Therefore MnO₄⁻ is the oxidizing agent. Iron goes from +2 to +3 (loss of 1 electron — oxidation). The species that is oxidized is the reducing agent. Fe²⁺ is the reducing agent.',
    wrongAnswerExplanations: {
      A: 'A species that loses electrons is oxidized (not reduced), making it the REDUCING agent, not the oxidizing agent. Fe²⁺ loses an electron to become Fe³⁺, so Fe²⁺ is the reducing agent.',
      C: 'Mn²⁺ is a product, not an agent. The reducing agent is the reactant that gets oxidized. The agent that causes reduction is the oxidizing agent (MnO₄⁻). Products are not themselves "agents."',
      D: 'In a redox reaction, oxidizing and reducing agents are distinct: one species is reduced (gains electrons = oxidizing agent) and another is oxidized (loses electrons = reducing agent). A single reaction cannot have two oxidizing agents without a different reducing agent.',
    },
    teachingPoint: 'Redox mnemonics: OIL RIG (Oxidation Is Loss of electrons; Reduction Is Gain of electrons). LEO GER (Lose Electrons = Oxidation; Gain Electrons = Reduction). The oxidizing agent causes oxidation of another species by accepting electrons (and is itself reduced). The reducing agent causes reduction by donating electrons (and is itself oxidized). Assign oxidation states to identify which species changes.',
    relatedTopics: ['Oxidation-reduction reactions', 'Oxidation states', 'Oxidizing and reducing agents', 'Permanganate reactions'],
  },
  {
    id: 'mcat-qb-cp-023',
    test: 'MCAT',
    section: 'chem-phys',
    discipline: 'Organic Chemistry',
    contentCategory: '1G: Alcohols and carbonyl chemistry',
    foundationalConcept: '1: Biomolecule structure',
    scientificSkill: 'Skill 1',
    difficulty: 'medium',
    questionType: 'discrete',
    question: 'Which of the following correctly ranks the carbonyl compounds in order of increasing electrophilicity (least to most reactive toward nucleophilic addition)?',
    choices: [
      { label: 'A', text: 'Amide < Ester < Aldehyde < Ketone' },
      { label: 'B', text: 'Aldehyde < Ketone < Ester < Amide' },
      { label: 'C', text: 'Amide < Ester < Ketone < Aldehyde' },
      { label: 'D', text: 'Ketone < Aldehyde < Ester < Amide' },
    ],
    correctAnswer: 'C',
    explanation: 'Choice C is correct. Electrophilicity of the carbonyl carbon toward nucleophilic attack depends on how much the adjacent groups donate electron density into the C=O through resonance and induction. Amides: the nitrogen lone pair strongly donates into the C=O, greatly reducing electrophilicity (least reactive). Esters: oxygen lone pair also donates, moderately reducing electrophilicity. Ketones: two alkyl groups donate electrons inductively, slightly reducing electrophilicity. Aldehydes: one hydrogen (no donation) and one alkyl group — least donation, most electrophilic (most reactive). Order of increasing electrophilicity: Amide < Ester < Ketone < Aldehyde.',
    wrongAnswerExplanations: {
      A: 'This order incorrectly places aldehyde before ketone. Aldehydes are more reactive than ketones toward nucleophilic addition because ketones have two alkyl groups donating electron density to the carbonyl, while aldehydes have only one alkyl group and a hydrogen.',
      B: 'This order is exactly reversed from the correct order. Amides are the least reactive (not most reactive) because nitrogen lone pair donation strongly stabilizes the C=O against nucleophilic attack.',
      D: 'This order incorrectly places ketone before aldehyde, and both before ester and amide. Esters and amides are less reactive than ketones and aldehydes because the heteroatom lone pairs stabilize the carbonyl through resonance donation.',
    },
    teachingPoint: 'Nucleophilic addition reactivity at C=O (most to least reactive): Acid chloride > Anhydride > Aldehyde > Ketone > Ester > Amide. Amides are the most stable (N lone pair donation); acid chlorides are the most reactive (Cl is a poor electron donor). On the MCAT, knowing that aldehydes > ketones and esters > amides is often sufficient.',
    relatedTopics: ['Nucleophilic addition', 'Carbonyl reactivity', 'Amide resonance', 'Ester vs aldehyde reactivity'],
  },
]
