import type { MCATQuestion } from '../types'

// Form 4 B/B — 9 discrete questions (IDs mcat4-bb-051 through mcat4-bb-059)

export const bbDiscretes4: MCATQuestion[] = [
  {
    id: 'mcat4-bb-051',
    sectionId: 'bio-biochem',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Biology',
    contentCategory: 'Endocrinology',
    foundationalConcept: 'FC 3',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    question: 'Insulin and glucagon have opposing effects on blood glucose. Which combination correctly describes their actions on liver metabolism?',
    choices: [
      { label: 'A', text: 'Insulin promotes glycolysis and glycogenesis; glucagon promotes glycogenolysis and gluconeogenesis' },
      { label: 'B', text: 'Insulin promotes glycogenolysis; glucagon promotes glycogenesis' },
      { label: 'C', text: 'Both insulin and glucagon promote glycolysis in the liver' },
      { label: 'D', text: 'Insulin and glucagon have identical effects in the liver but opposite effects in muscle' },
    ],
    correctAnswer: 'A',
    explanation: 'Insulin (fed state): promotes glucose uptake, glycolysis (glucose → pyruvate → energy/building blocks), glycogenesis (glucose → glycogen storage), and fatty acid synthesis. Glucagon (fasted state): promotes glycogenolysis (glycogen → glucose-1-P → blood glucose) and gluconeogenesis (amino acids, glycerol, lactate → glucose) to raise blood glucose. A correctly describes both. B reverses their roles. C is wrong — glucagon inhibits glycolysis (phosphorylates/inactivates PFK-2). D is wrong — they have opposite effects on liver.',
    wrongAnswerExplanations: {
      B: 'These are exactly reversed. Insulin promotes glycogen synthesis (glycogenesis); glucagon promotes glycogen breakdown (glycogenolysis).',
      C: 'Glucagon actively inhibits hepatic glycolysis (via PKA → phosphorylation of PFK-2 → decreased fructose-2,6-bisphosphate → PFK-1 inhibited). Insulin promotes glycolysis.',
      D: 'Insulin and glucagon have opposing effects in the liver. Glucagon does not have significant effects on muscle (muscle lacks glucagon receptors).',
    },
    teachingPoint: 'Insulin (fed): GLUT4 translocation in muscle/fat; hepatic glycolysis ↑, glycogenesis ↑, lipogenesis ↑, gluconeogenesis ↓. Glucagon (fasted): hepatic glycogenolysis ↑, gluconeogenesis ↑, ketogenesis ↑. AMPK: activated by glucagon (via PKA-mediated phosphorylation) → fatty acid oxidation ↑. Key regulatory enzymes: glycogen phosphorylase (glycogenolysis, activated by glucagon/PKA); glycogen synthase (glycogenesis, activated by insulin/PP1). Phosphofructokinase-2 (PFK-2): glucagon → PKA → PFK-2 inactive → low F-2,6-BP → PFK-1 inactive → reduced glycolysis.',
    relatedTopics: ['insulin glucagon liver', 'glycogenolysis gluconeogenesis', 'glycolysis glycogenesis', 'fed vs fasted state', 'hepatic glucose metabolism'],
  },
  {
    id: 'mcat4-bb-052',
    sectionId: 'bio-biochem',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Biology',
    contentCategory: 'Cell biology',
    foundationalConcept: 'FC 2',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    question: 'The sodium-potassium ATPase (Na⁺/K⁺-ATPase) maintains the resting membrane potential. Which statement best describes its transport stoichiometry?',
    choices: [
      { label: 'A', text: '3 Na⁺ out, 2 K⁺ in per ATP hydrolyzed; creates net outward movement of positive charge' },
      { label: 'B', text: '2 Na⁺ out, 3 K⁺ in per ATP; creates net inward movement of positive charge' },
      { label: 'C', text: '3 Na⁺ out, 3 K⁺ in per ATP; electrically neutral transport' },
      { label: 'D', text: '1 Na⁺ out, 1 K⁺ in per ATP; not electrogenic' },
    ],
    correctAnswer: 'A',
    explanation: 'Na⁺/K⁺-ATPase: moves 3 Na⁺ out and 2 K⁺ in per cycle (per ATP hydrolyzed). Net charge movement: 3 positive charges out, 2 positive charges in → net 1 positive charge out per cycle → electrogenic (contributes small hyperpolarizing effect). A is correct. B reverses the stoichiometry. C would be electrically neutral. D is wrong — the pump is electrogenic (unequal charge exchange).',
    wrongAnswerExplanations: {
      B: 'The correct stoichiometry is 3 Na⁺ OUT, 2 K⁺ IN. B states 2 Na⁺ out, 3 K⁺ in — which would be inward net charge movement (incorrect direction and wrong stoichiometry).',
      C: '3 out and 3 in would be electrically neutral — but the actual stoichiometry is 3 Na⁺ out and 2 K⁺ in, which is electrogenic.',
      D: '1:1 transport would not be electrogenic (or would be minimally electrogenic if ions have different charges). The Na⁺/K⁺-ATPase is definitely electrogenic.',
    },
    teachingPoint: 'Na⁺/K⁺-ATPase: P-type ATPase (forms phosphorylated intermediate). Stoichiometry: 3 Na⁺ out, 2 K⁺ in per ATP. Functions: (1) maintains Na⁺/K⁺ gradients (low intracellular Na⁺, high intracellular K⁺); (2) drives secondary active transport (SGLT, Na-glucose symport); (3) maintains cell volume (Na⁺ gradient prevents osmotic swelling); (4) contributes to resting membrane potential (electrogenic, ~−70 mV in neurons). Inhibited by: cardiac glycosides (ouabain, digoxin) → increased intracellular Na⁺ → NCX (Na-Ca exchanger) reverses → increased intracellular Ca²⁺ → positive inotropic effect.',
    relatedTopics: ['Na-K-ATPase stoichiometry', '3 sodium 2 potassium', 'electrogenic pump', 'resting membrane potential', 'primary active transport'],
  },
  {
    id: 'mcat4-bb-053',
    sectionId: 'bio-biochem',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Biology',
    contentCategory: 'Molecular biology',
    foundationalConcept: 'FC 1',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    question: 'Translation terminates when a stop codon enters the ribosomal A site. Which molecules facilitate termination?',
    choices: [
      { label: 'A', text: 'Elongation factors and GTP' },
      { label: 'B', text: 'Release factors that recognize stop codons and stimulate peptidyl transferase to hydrolyze the peptide from the tRNA' },
      { label: 'C', text: 'Ribozymes that cleave the mRNA at the stop codon' },
      { label: 'D', text: 'The ribosome dissociates spontaneously when it encounters a stop codon' },
    ],
    correctAnswer: 'B',
    explanation: 'In eukaryotes: eRF1 (recognizes all three stop codons: UAA, UAG, UGA) and eRF3 (GTP-binding factor) enter the A site. eRF1 stimulates peptidyl transferase activity of the ribosome to hydrolyze the ester bond between the peptide and the tRNA → peptide released. eRF3 facilitates release of eRF1 and mRNA. B is correct. A describes elongation (aminoacyl-tRNA delivery = EF-Tu/GTP; translocation = EF-G/GTP). C is incorrect — ribozymes don\'t cleave mRNA at stop codons. D is incorrect — spontaneous dissociation does not describe termination.',
    wrongAnswerExplanations: {
      A: 'Elongation factors (EF-Tu in prokaryotes, eEF1A in eukaryotes) deliver aminoacyl-tRNAs to the A site during elongation. They are not involved in termination.',
      C: 'Ribozymes are catalytic RNAs. While the ribosome itself has ribozyme activity (23S/28S rRNA catalyzes peptide bond formation), stop codon recognition uses protein release factors, not ribozymes cleaving mRNA.',
      D: 'The ribosome does not dissociate spontaneously. Specific release factors (eRF1, eRF3 in eukaryotes; RF1/RF2/RF3 in prokaryotes) must recognize the stop codon and catalyze peptide release.',
    },
    teachingPoint: 'Prokaryotic vs. eukaryotic release factors: Prokaryotes: RF1 (recognizes UAA, UAG), RF2 (recognizes UAA, UGA), RF3 (GTP-binding, assists release). Eukaryotes: eRF1 (recognizes all three stop codons), eRF3 (GTP-binding). After termination: ribosome recycling factor (RRF) + EF-G (prokaryotes) or ABCE1 (eukaryotes) split ribosomes into subunits. Nonsense-mediated mRNA decay (NMD): if stop codon is premature → mRNA degraded (surveillance pathway).',
    relatedTopics: ['translation termination', 'release factors eRF1', 'stop codon recognition', 'peptide hydrolysis', 'ribosome dissociation'],
  },
  {
    id: 'mcat4-bb-054',
    sectionId: 'bio-biochem',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Biology',
    contentCategory: 'Physiology',
    foundationalConcept: 'FC 3',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    question: 'The Frank-Starling mechanism in the heart states that:',
    choices: [
      { label: 'A', text: 'Heart rate increases as venous return decreases' },
      { label: 'B', text: 'Stroke volume increases as end-diastolic volume (EDV) increases, up to a limit' },
      { label: 'C', text: 'Cardiac output remains constant regardless of venous return' },
      { label: 'D', text: 'Increased afterload increases stroke volume by stretching cardiac muscle' },
    ],
    correctAnswer: 'B',
    explanation: 'Frank-Starling mechanism: increased venous return → increased EDV (preload) → cardiac muscle fibers are stretched → increased cross-bridge formation (more actin-myosin overlap and Ca²⁺ sensitivity) → more forceful contraction → increased stroke volume. The heart pumps what it receives. B is correct. A is reversed — increased venous return increases heart output. C is wrong — cardiac output adjusts to match venous return (Frank-Starling). D confuses afterload with preload — increased afterload (arterial resistance) actually decreases stroke volume; preload (EDV) increases stroke volume.',
    wrongAnswerExplanations: {
      A: 'Frank-Starling: increased venous return → increased EDV → increased stroke volume. A states decreased venous return increases HR — this is not Frank-Starling (though baroreceptor reflexes may increase HR in response to low venous return to compensate).',
      C: 'Cardiac output does NOT remain constant — it adjusts based on venous return. Frank-Starling is specifically about this auto-regulation.',
      D: 'Afterload (arterial pressure against which the heart must eject) and preload (filling volume) are different. Increased afterload → decreased stroke volume (heart pumps against higher resistance). Increased preload (EDV) → increased stroke volume (Frank-Starling).',
    },
    teachingPoint: 'Frank-Starling mechanism: intrinsic (myocardium-level) regulation of cardiac output. Cellular basis: increased sarcomere stretch → increased Ca²⁺ sensitivity of troponin C + better actin-myosin overlap → stronger contraction. Clinical relevance: heart failure — Frank-Starling curve is shifted down (less stroke volume for any given EDV). Starling\'s law allows both ventricles to remain balanced (equal output prevents pulmonary or systemic congestion). Preload (venous return/EDV) vs. afterload (systolic wall stress/TPR/aortic pressure) vs. contractility (sympathetic/positive inotropes).',
    relatedTopics: ['Frank-Starling mechanism', 'stroke volume EDV', 'preload cardiac output', 'cardiac muscle stretch', 'heart physiology'],
  },
  {
    id: 'mcat4-bb-055',
    sectionId: 'bio-biochem',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Biology',
    contentCategory: 'Physiology',
    foundationalConcept: 'FC 3',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    question: 'A patient with chronic obstructive pulmonary disease (COPD) has elevated pCO₂ (hypercapnia) and reduced pH. The kidneys compensate by:',
    choices: [
      { label: 'A', text: 'Increasing bicarbonate excretion to lower plasma pH further' },
      { label: 'B', text: 'Retaining bicarbonate and excreting more H⁺ to raise plasma pH toward normal' },
      { label: 'C', text: 'Excreting CO₂ directly in the urine' },
      { label: 'D', text: 'Increasing ventilation to blow off excess CO₂' },
    ],
    correctAnswer: 'B',
    explanation: 'COPD → respiratory acidosis (high pCO₂, low pH). Renal compensation for respiratory acidosis: kidneys retain HCO₃⁻ (by increasing bicarbonate reabsorption in the proximal tubule and generating new HCO₃⁻ via α-intercalated cells of the collecting duct) and excrete H⁺ (as NH₄⁺ and titratable acid). This raises plasma pH toward normal. B is correct. A would worsen the acidosis. C is incorrect — CO₂ is not excreted in urine directly. D describes respiratory compensation (increasing ventilation), not renal compensation — in COPD the lungs cannot blow off CO₂.',
    wrongAnswerExplanations: {
      A: 'Excreting HCO₃⁻ would LOWER plasma pH further (removing base). The kidneys RETAIN HCO₃⁻ to raise pH in respiratory acidosis.',
      C: 'CO₂ in blood is converted to HCO₃⁻ and H⁺ by carbonic anhydrase. The kidney handles acid-base balance through H⁺ excretion and HCO₃⁻ regulation — not direct CO₂ excretion in urine.',
      D: 'Increasing ventilation would be RESPIRATORY compensation. In COPD, the lungs are the problem — they cannot increase effective ventilation. Renal compensation is the kidney\'s response.',
    },
    teachingPoint: 'Acid-base disturbances and compensation: Respiratory acidosis (↑pCO₂, ↓pH): renal compensation → ↑HCO₃⁻ retention, ↑H⁺ excretion → ↑plasma HCO₃⁻. Respiratory alkalosis (↓pCO₂, ↑pH): renal compensation → ↓HCO₃⁻ retention, ↓H⁺ excretion. Metabolic acidosis (↓HCO₃⁻, ↓pH): respiratory compensation → hyperventilation → ↓pCO₂ (Kussmaul breathing in DKA). Metabolic alkalosis (↑HCO₃⁻, ↑pH): respiratory compensation → hypoventilation → ↑pCO₂. Compensation is always in the same direction as the primary disturbance (never fully corrects pH).',
    relatedTopics: ['COPD respiratory acidosis', 'renal compensation', 'bicarbonate retention', 'H+ excretion', 'acid-base compensation'],
  },
  {
    id: 'mcat4-bb-056',
    sectionId: 'bio-biochem',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Biochemistry',
    contentCategory: 'Biochemistry',
    foundationalConcept: 'FC 1',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    question: 'Glycolysis produces a net gain of 2 ATP per glucose. Why is the net only 2 ATP despite both substrate-level phosphorylation steps in the pay-off phase?',
    choices: [
      { label: 'A', text: 'Two ATP molecules are consumed in the investment phase (steps 1 and 3) to phosphorylate glucose' },
      { label: 'B', text: 'Two ATP molecules are consumed by the electron transport chain' },
      { label: 'C', text: 'NADH produced in glycolysis does not contribute any ATP' },
      { label: 'D', text: 'Pyruvate formation requires additional ATP expenditure' },
    ],
    correctAnswer: 'A',
    explanation: 'Glycolysis: investment phase (steps 1-5) uses 2 ATP (hexokinase phosphorylates glucose: 1 ATP; phosphofructokinase-1 phosphorylates fructose-6-P: 1 ATP). Pay-off phase (steps 6-10): produces 4 ATP (phosphoglycerate kinase: 2 ATP; pyruvate kinase: 2 ATP). Net: 4 ATP − 2 ATP (invested) = 2 ATP per glucose. A is correct. B is wrong — the ETC uses NADH to make more ATP, not consume glycolysis ATP. C is wrong — NADH from glycolysis does contribute ATP via the ETC (in aerobic conditions). D is wrong — pyruvate kinase produces ATP, not consumes it.',
    wrongAnswerExplanations: {
      B: 'The ETC PRODUCES ATP (from NADH and FADH₂) — it does not consume glycolysis ATP. The 2 ATP investment occurs in glycolysis itself.',
      C: 'NADH produced in glycolysis (at glyceraldehyde-3-phosphate dehydrogenase) is used to produce additional ATP via the ETC in aerobic conditions (~2.5 ATP per NADH × 2 = ~5 more ATP). It does contribute to total cellular ATP.',
      D: 'Pyruvate kinase is the last step of glycolysis and PRODUCES ATP (substrate-level phosphorylation: PEP → pyruvate + ATP). It does not consume ATP.',
    },
    teachingPoint: 'Glycolysis net ATP: 2 invested (hexokinase step 1, PFK-1 step 3) − 4 produced (phosphoglycerate kinase ×2 and pyruvate kinase ×2) = net +2 ATP. Per glucose, both halves of glycolysis run (after aldolase splits F-1,6-BP into 2 triose phosphates), so all pay-off steps occur twice: 2×2 = 4 ATP gross, 4 − 2 = 2 ATP net. Also produced: 2 NADH (→ ~5 ATP in aerobic conditions via ETC). Total aerobic yield of glycolysis: 2 ATP (substrate level) + ~5 ATP (from 2 NADH via ETC).',
    relatedTopics: ['glycolysis net ATP', 'investment phase', 'ATP investment 2', 'substrate level phosphorylation', 'glycolysis steps'],
  },
  {
    id: 'mcat4-bb-057',
    sectionId: 'bio-biochem',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Biology',
    contentCategory: 'Evolution',
    foundationalConcept: 'FC 1',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    question: 'Natural selection acts on phenotype but evolution occurs at the level of genotype frequencies. Which statement best captures the relationship?',
    choices: [
      { label: 'A', text: 'Natural selection directly alters gene sequences (DNA) to produce better-adapted organisms' },
      { label: 'B', text: 'Natural selection acts on phenotypic variation; by differentially affecting survival and reproduction, it changes allele frequencies in the next generation' },
      { label: 'C', text: 'Evolution requires natural selection; no other mechanism can change allele frequencies' },
      { label: 'D', text: 'Phenotype and genotype are always perfectly correlated' },
    ],
    correctAnswer: 'B',
    explanation: 'Natural selection: differential survival and reproduction based on phenotype. Because phenotype is (partly) determined by genotype, individuals with favorable phenotypes leave more offspring → their alleles become more common in the next generation → allele frequencies change → evolution. B captures this correctly. A is wrong — selection doesn\'t directly alter DNA sequences; it filters existing variation. C is wrong — other mechanisms also change allele frequencies: genetic drift, mutation, gene flow, non-random mating. D is wrong — phenotype is influenced by environment, epistasis, and pleiotropy; genotype-phenotype correlation is not perfect.',
    wrongAnswerExplanations: {
      A: 'Natural selection does not alter DNA sequences. It acts on existing phenotypic variation caused by existing genetic variation. Mutation generates new variation; selection filters it.',
      C: 'Multiple mechanisms change allele frequencies: mutation (introduces new alleles), genetic drift (random changes, especially in small populations), gene flow (migration), non-random mating (changes genotype frequencies). Natural selection is one of several mechanisms.',
      D: 'Genotype-phenotype relationship is complex: penetrance (not all carriers show phenotype), expressivity (variable severity), environment × gene interactions, polygenic traits, epistasis. Perfect correlation is not assumed.',
    },
    teachingPoint: 'Mechanisms of evolution: (1) Natural selection: differential reproduction based on heritable phenotypic variation; (2) Genetic drift: random allele frequency changes (more pronounced in small populations — founder effect, bottleneck); (3) Mutation: source of new variation; (4) Gene flow: allele movement between populations; (5) Non-random mating: changes genotype but not allele frequencies directly. Hardy-Weinberg equilibrium: no evolution when all 5 are absent. Fitness: relative reproductive success (not strength/survival alone).',
    relatedTopics: ['natural selection evolution', 'allele frequency change', 'mechanisms of evolution', 'genotype phenotype', 'genetic drift'],
  },
  {
    id: 'mcat4-bb-058',
    sectionId: 'bio-biochem',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Biology',
    contentCategory: 'Physiology',
    foundationalConcept: 'FC 3',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    question: 'Antidiuretic hormone (ADH/vasopressin) is released from the posterior pituitary in response to increased plasma osmolality. Its primary mechanism of action in the kidney is:',
    choices: [
      { label: 'A', text: 'Increasing Na⁺ reabsorption in the proximal tubule' },
      { label: 'B', text: 'Inserting aquaporin-2 (AQP2) water channels into the apical membrane of collecting duct cells, increasing water reabsorption' },
      { label: 'C', text: 'Stimulating the Na⁺/K⁺-ATPase to pump more Na⁺ into the urine' },
      { label: 'D', text: 'Inhibiting aldosterone secretion from the adrenal cortex' },
    ],
    correctAnswer: 'B',
    explanation: 'ADH/vasopressin acts on V2 receptors in the collecting duct → Gαs → adenylyl cyclase → cAMP → PKA → phosphorylates aquaporin-2 (AQP2) vesicles → AQP2 inserted into apical membrane → increased water permeability → water reabsorption from collecting duct lumen into hyperosmolar medullary interstitium → concentrated urine. B is correct. A — Na⁺ reabsorption in the proximal tubule is driven by Na⁺/K⁺-ATPase and not ADH. C — Na⁺/K⁺-ATPase pumps Na⁺ OUT of the cell (into blood), not into urine. D — ADH does not directly inhibit aldosterone (that is ANP\'s role).',
    wrongAnswerExplanations: {
      A: 'Na⁺ reabsorption in the proximal tubule occurs via Na⁺/H⁺ exchanger and SGLT — it is constitutive and not directly regulated by ADH. ADH acts on the collecting duct.',
      C: 'Na⁺/K⁺-ATPase pumps Na⁺ out of the cell (basolateral) into the blood — not into the urine lumen. ADH does not increase urinary Na⁺ loss.',
      D: 'ANP (atrial natriuretic peptide) inhibits aldosterone and ADH release. ADH itself does not directly inhibit aldosterone secretion.',
    },
    teachingPoint: 'ADH (vasopressin): made in hypothalamus (supraoptic/paraventricular nuclei), stored/released from posterior pituitary. Stimuli for release: increased osmolality (detected by hypothalamic osmoreceptors), decreased blood volume/pressure (detected by baroreceptors). Mechanism: V2 receptor in collecting duct → Gs → cAMP → PKA → AQP2 phosphorylation → membrane insertion → water reabsorption → concentrated urine. SIADH: excess ADH → water retention → dilutional hyponatremia. Diabetes insipidus: central (ADH deficiency) or nephrogenic (V2/AQP2 defect) → dilute polyuria.',
    relatedTopics: ['ADH vasopressin mechanism', 'aquaporin-2 AQP2', 'collecting duct water reabsorption', 'SIADH', 'diabetes insipidus'],
  },
  {
    id: 'mcat4-bb-059',
    sectionId: 'bio-biochem',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Biology',
    contentCategory: 'Physiology',
    foundationalConcept: 'FC 3',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    question: 'An action potential in a neuron is initiated when the membrane is depolarized to threshold potential. Which event BEST describes what occurs at threshold?',
    choices: [
      { label: 'A', text: 'Voltage-gated K⁺ channels open, causing rapid depolarization to +30 mV' },
      { label: 'B', text: 'Voltage-gated Na⁺ channels open, causing a rapid influx of Na⁺ and depolarization' },
      { label: 'C', text: 'Na⁺/K⁺-ATPase stops pumping, causing Na⁺ to accumulate intracellularly' },
      { label: 'D', text: 'Ligand-gated Cl⁻ channels open, hyperpolarizing the membrane' },
    ],
    correctAnswer: 'B',
    explanation: 'At threshold (~−55 mV in neurons): voltage-gated Na⁺ channels (NaV channels) undergo a conformational change → open → Na⁺ rushes into the cell (down electrochemical gradient: extracellular Na⁺ concentration is ~145 mM; intracellular ~12 mM; and inside is negative) → rapid depolarization to ~+30 mV (approaching Na⁺ equilibrium potential ≈ +60 mV). B is correct. A — voltage-gated K⁺ channels open later (during repolarization). C — Na⁺/K⁺-ATPase is slow and not responsible for the rapid depolarization. D — Cl⁻ influx would hyperpolarize (inhibitory), not depolarize.',
    wrongAnswerExplanations: {
      A: 'Voltage-gated K⁺ channels open DURING repolarization (after the peak of the action potential). Their opening brings the membrane back toward the K⁺ equilibrium potential (~−90 mV), repolarizing it.',
      C: 'Na⁺/K⁺-ATPase operates on a slow timescale (milliseconds to seconds) — it maintains baseline gradients. The rapid depolarization of the action potential is due to fast voltage-gated Na⁺ channels (opening in < 1 ms).',
      D: 'Cl⁻ influx (through inhibitory GABA receptors or glycine receptors) HYPERPOLARIZES the membrane (Cl⁻ equilibrium potential ≈ −70 mV in most neurons). This is an inhibitory event, not what initiates an action potential.',
    },
    teachingPoint: 'Action potential phases: Resting (−70 mV): K⁺ leak channels open, Na⁺/K⁺-ATPase maintains gradients. Depolarization (threshold → +30 mV): voltage-gated Na⁺ channels open → Na⁺ influx. Peak: Na⁺ channels inactivate (fast inactivation gate closes). Repolarization: voltage-gated K⁺ channels open → K⁺ efflux → membrane toward −90 mV. Hyperpolarization (undershoot): K⁺ channels slowly close. Refractory period: absolute (Na⁺ channels inactivated, cannot re-open until repolarized) and relative (some K⁺ channels still open, harder to reach threshold).',
    relatedTopics: ['action potential threshold', 'voltage-gated sodium channels', 'depolarization Na+ influx', 'action potential phases', 'Na/K ATPase vs action potential'],
  },
]
