import type { MCATPassage } from '../types'

// Form 4 B/B — Passages 1–5 (IDs mcat4-bb-001 through mcat4-bb-025)

export const bbPassages4_01to05: MCATPassage[] = [
  {
    id: 'f4-bb-p1',
    sectionId: 'bio-biochem',
    passageNumber: 1,
    title: 'Enzyme Kinetics and Inhibition',
    text: `Enzymes are biological catalysts that increase the rate of chemical reactions by lowering the activation energy. Enzyme activity is commonly described by the Michaelis-Menten model, which relates reaction velocity (v) to substrate concentration ([S]): v = Vmax[S] / (Km + [S]). At low [S], the reaction is approximately first-order in substrate; at high [S], the reaction approaches Vmax and becomes zero-order. The Michaelis constant (Km) is the substrate concentration at which v = Vmax/2 and is an approximate measure of enzyme-substrate affinity (lower Km = higher affinity).

Enzyme inhibitors reduce catalytic activity through several mechanisms. Competitive inhibitors bind to the active site, directly competing with substrate; their effect can be overcome by increasing [S]. In competitive inhibition, Vmax remains unchanged (can still be reached at high [S]) but the apparent Km increases (enzyme appears to have lower affinity for substrate). Non-competitive inhibitors bind to an allosteric site (not the active site) and reduce enzyme activity regardless of [S]; Vmax decreases but Km is unchanged. Uncompetitive inhibitors bind only to the enzyme-substrate complex; both Vmax and Km decrease.

Allosteric regulation provides a more nuanced control mechanism. Allosteric enzymes have multiple subunits and exhibit cooperative binding: binding of one substrate molecule increases the affinity of remaining binding sites (positive cooperativity). This produces a sigmoidal v-[S] curve rather than the hyperbolic curve of Michaelis-Menten kinetics. Allosteric effectors can be activators (increase activity) or inhibitors (decrease activity), binding at regulatory sites distinct from the active site. Many allosteric enzymes are subject to feedback inhibition: the end product of a metabolic pathway inhibits an enzyme early in the pathway, providing a self-regulatory mechanism.

Researchers studying an enzyme involved in nucleotide biosynthesis found that at Km conditions, the enzyme velocity was reduced by 60% in the presence of compound X. When [S] was increased tenfold above Km, the velocity was reduced by 45% relative to uninhibited enzyme at the same [S]. A Lineweaver-Burk analysis revealed that both Vmax and Km changed in the presence of compound X.`,
    questions: [
      {
        id: 'mcat4-bb-001',
        sectionId: 'bio-biochem',
        passageId: 'f4-bb-p1',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'Enzymes',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'Based on the experimental results described in the final paragraph, compound X is MOST consistent with which type of inhibitor?',
        choices: [
          { label: 'A', text: 'Competitive inhibitor' },
          { label: 'B', text: 'Non-competitive inhibitor' },
          { label: 'C', text: 'Uncompetitive inhibitor' },
          { label: 'D', text: 'Irreversible inhibitor' },
        ],
        correctAnswer: 'C',
        explanation: 'Key evidence: (1) at Km, velocity reduced 60%; (2) at [S] = 10Km, velocity reduced 45% — as [S] increases, the inhibition decreases slightly but does not vanish; (3) Lineweaver-Burk shows BOTH Vmax and Km decrease. Uncompetitive inhibition: binds only ES complex (more common at high [S]) → as [S] increases, more ES complex → more inhibitor binding → inhibition increases... but wait, both Vmax and Km decrease in uncompetitive inhibition, and the inhibition effect is present and does not disappear with high [S]. Non-competitive: Km unchanged, Vmax decreases. Competitive: Km increases, Vmax unchanged. The Lineweaver-Burk change in BOTH Km and Vmax = uncompetitive (both decrease). C is correct.',
        wrongAnswerExplanations: {
          A: 'Competitive inhibition: Km increases, Vmax unchanged. The passage states both change → not competitive.',
          B: 'Non-competitive inhibition: Km unchanged, Vmax decreases. The passage states both change → not non-competitive.',
          D: 'Irreversible inhibition is not described by these kinetic parameters in the context of reversible inhibitor types. Uncompetitive binding to ES complex gives both Km and Vmax changing.',
        },
        teachingPoint: 'Inhibitor identification by Lineweaver-Burk: competitive = Km increases, Vmax same (lines intersect y-axis, same 1/Vmax); non-competitive = Vmax decreases, Km same (lines intersect x-axis, same −1/Km); uncompetitive = both Vmax and Km decrease by same factor (parallel lines on Lineweaver-Burk). Uncompetitive inhibitors bind ES, not free enzyme.',
        relatedTopics: ['enzyme inhibition', 'Lineweaver-Burk', 'uncompetitive inhibition', 'Km Vmax changes'],
      },
      {
        id: 'mcat4-bb-002',
        sectionId: 'bio-biochem',
        passageId: 'f4-bb-p1',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'Enzymes',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'An enzyme has Km = 2 mM. At what substrate concentration will the reaction velocity equal half of Vmax?',
        choices: [
          { label: 'A', text: '1 mM' },
          { label: 'B', text: '2 mM' },
          { label: 'C', text: '4 mM' },
          { label: 'D', text: 'Vmax/2 cannot be determined from Km alone' },
        ],
        correctAnswer: 'B',
        explanation: 'By definition, Km is the substrate concentration at which v = Vmax/2. The passage states: "Km is the substrate concentration at which v = Vmax/2." Therefore, [S] = Km = 2 mM. B is correct. This is a direct application of the Michaelis-Menten definition.',
        wrongAnswerExplanations: {
          A: '1 mM = Km/2; at this [S], v = Vmax × (1)/(2+1) = Vmax/3, not Vmax/2.',
          C: '4 mM = 2Km; at this [S], v = Vmax × (4)/(2+4) = 4Vmax/6 = 2Vmax/3, not Vmax/2.',
          D: 'Km is by definition the [S] at which v = Vmax/2 — so Vmax/2 is directly determined by Km.',
        },
        teachingPoint: 'Michaelis-Menten: v = Vmax[S]/(Km + [S]). When [S] = Km: v = Vmax × Km/(Km + Km) = Vmax × Km/2Km = Vmax/2. This is the definition of Km. Km is a kinetic constant, not directly the dissociation constant (Kd) of E+S → ES, though it approximates affinity.',
        relatedTopics: ['Michaelis-Menten', 'Km definition', 'Vmax/2', 'enzyme kinetics'],
      },
      {
        id: 'mcat4-bb-003',
        sectionId: 'bio-biochem',
        passageId: 'f4-bb-p1',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'Enzymes',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'Which feature of allosteric enzymes distinguishes their kinetics from classical Michaelis-Menten kinetics?',
        choices: [
          { label: 'A', text: 'Allosteric enzymes have no Vmax' },
          { label: 'B', text: 'Allosteric enzymes show a sigmoidal v-[S] curve due to cooperative binding' },
          { label: 'C', text: 'Allosteric enzymes are not subject to inhibition' },
          { label: 'D', text: 'Allosteric enzymes only function at very high substrate concentrations' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 3: allosteric enzymes "exhibit cooperative binding...This produces a sigmoidal v-[S] curve rather than the hyperbolic curve of Michaelis-Menten kinetics." B matches. A is incorrect — allosteric enzymes still have a maximum velocity. C is incorrect — allosteric inhibitors exist. D is not stated.',
        wrongAnswerExplanations: {
          A: 'Allosteric enzymes still have a maximum rate (Vmax); they just reach it with sigmoidal rather than hyperbolic kinetics.',
          C: 'Allosteric enzymes are specifically subject to allosteric inhibitors (effectors that decrease activity) — inhibition is a key feature.',
          D: 'Cooperative binding means lower concentrations are needed to reach near-maximum activity once cooperativity kicks in — not that only high [S] is functional.',
        },
        teachingPoint: 'Sigmoidal kinetics: result of cooperative binding (Hill coefficient > 1). Michaelis-Menten: hyperbolic (Hill coefficient = 1). Hemoglobin is the classic example of sigmoidal O₂ binding (cooperative, with Hill coefficient ≈ 2.8). The sigmoidal curve allows for more sensitive regulation — small changes in [S] around the inflection point cause large changes in activity.',
        relatedTopics: ['allosteric enzymes', 'sigmoidal kinetics', 'cooperative binding', 'Hill coefficient'],
      },
      {
        id: 'mcat4-bb-004',
        sectionId: 'bio-biochem',
        passageId: 'f4-bb-p1',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'Enzymes',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'Feedback inhibition in a biosynthetic pathway would be MOST important under which condition?',
        choices: [
          { label: 'A', text: 'When the end product of the pathway is depleted' },
          { label: 'B', text: 'When the end product of the pathway accumulates to high levels' },
          { label: 'C', text: 'When the initial substrate of the pathway is limiting' },
          { label: 'D', text: 'When a competitive inhibitor is present' },
        ],
        correctAnswer: 'B',
        explanation: 'Feedback inhibition: the end product of a metabolic pathway inhibits an early enzyme → prevents overproduction. This is most important when the end product accumulates (signals "enough has been made → slow down production"). B is correct. A is the opposite: when product is depleted, feedback inhibition is released → more production. C and D are unrelated mechanisms.',
        wrongAnswerExplanations: {
          A: 'When end product is depleted, the enzyme early in the pathway should be ACTIVATED (or at least uninhibited) to increase production. Feedback inhibition operates when end product is in excess.',
          C: 'Limiting initial substrate would slow the pathway regardless of feedback inhibition. Feedback inhibition responds to end product levels, not substrate levels.',
          D: 'Competitive inhibitors are a separate regulatory mechanism — not the condition under which feedback inhibition operates.',
        },
        teachingPoint: 'Feedback (end-product) inhibition: end product acts as allosteric inhibitor of the committed step of the pathway (usually an early, irreversible reaction). Classic examples: ATP inhibits phosphofructokinase-1; CTP inhibits ATCase in pyrimidine synthesis. The feedback signal is high [end product], not low [substrate].',
        relatedTopics: ['feedback inhibition', 'allosteric regulation', 'metabolic pathway control', 'end product inhibition'],
      },
      {
        id: 'mcat4-bb-005',
        sectionId: 'bio-biochem',
        passageId: 'f4-bb-p1',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'Enzymes',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 2',
        difficulty: 'hard',
        question: 'An enzyme with a very low Km and high Vmax would be most accurately described as:',
        choices: [
          { label: 'A', text: 'A low-affinity, low-efficiency enzyme' },
          { label: 'B', text: 'A high-affinity, high-efficiency enzyme' },
          { label: 'C', text: 'An enzyme that operates only at saturating substrate concentrations' },
          { label: 'D', text: 'An enzyme that would be maximally inhibited by competitive inhibitors' },
        ],
        correctAnswer: 'B',
        explanation: 'Low Km = high affinity (reaches half-maximum velocity at very low [S]); high Vmax = high maximum rate/efficiency. B is correct. A reverses both. C is wrong — low Km means the enzyme reaches near-maximum velocity at low [S], not that it requires saturating [S]. D is unrelated to Km and Vmax values per se.',
        wrongAnswerExplanations: {
          A: 'Low Km = HIGH affinity (enzyme binds substrate well at low concentrations). High Vmax = HIGH efficiency. A reverses both characteristics.',
          C: 'Low Km means the enzyme is near-saturated at LOW substrate concentrations. An enzyme that requires saturating [S] would have a high Km.',
          D: 'Sensitivity to competitive inhibitors depends on Ki of the inhibitor and Km, not simply on the enzyme having high or low Km and Vmax.',
        },
        teachingPoint: 'Km and Vmax are independent parameters. Km ≈ affinity (lower = tighter binding). Vmax = maximum velocity = kcat × [Etotal]; kcat = turnover number (catalytic efficiency). Catalytic efficiency = kcat/Km (measure of how well enzyme converts substrate at low concentrations). Enzymes approaching diffusion limit: kcat/Km ≈ 10⁸–10⁹ M⁻¹s⁻¹ (e.g., carbonic anhydrase, catalase = "perfect enzymes").',
        relatedTopics: ['Km affinity', 'Vmax efficiency', 'kcat turnover number', 'catalytic efficiency'],
      },
    ],
  },
  {
    id: 'f4-bb-p2',
    sectionId: 'bio-biochem',
    passageNumber: 2,
    title: 'DNA Replication and Repair',
    text: `DNA replication is a semi-conservative process: each parental strand serves as a template for a new complementary strand, resulting in two daughter duplexes each containing one old and one new strand. The process is catalyzed by DNA polymerase, which can only synthesize DNA in the 5'→3' direction and requires a free 3'-OH primer to initiate synthesis. At each replication fork, the leading strand is synthesized continuously in the 5'→3' direction, while the lagging strand is synthesized discontinuously as Okazaki fragments, each initiated by a short RNA primer placed by primase. DNA polymerase I (in prokaryotes) removes RNA primers and fills in the gaps; DNA ligase seals the nicks between Okazaki fragments.

Replication fidelity is ensured by multiple mechanisms. DNA polymerase has intrinsic 3'→5' exonuclease (proofreading) activity that removes mismatched bases immediately after incorporation. The mismatch repair (MMR) system corrects errors that escape proofreading by recognizing distortions in the DNA helix and excising the mismatched segment. Nucleotide excision repair (NER) removes bulky adducts (e.g., thymine dimers from UV light) by cutting on both sides of the lesion and synthesizing a new patch. Base excision repair (BER) removes damaged individual bases. Double-strand breaks (DSBs) are the most dangerous lesions, repaired by either homologous recombination (high-fidelity, uses sister chromatid as template) or non-homologous end joining (NHEJ, error-prone, joins broken ends directly).

Telomeres — repetitive sequences (TTAGGG in humans) at the ends of linear chromosomes — address the "end replication problem": because DNA polymerase requires a primer and synthesizes 5'→3', the very end of the lagging strand template cannot be fully replicated, leading to progressive shortening with each cell division. Telomerase, a reverse transcriptase that uses an internal RNA template, adds telomeric repeats to chromosome ends in germ cells and stem cells, maintaining length. Somatic cells have low telomerase activity; most cancer cells reactivate telomerase, conferring replicative immortality.`,
    questions: [
      {
        id: 'mcat4-bb-006',
        sectionId: 'bio-biochem',
        passageId: 'f4-bb-p2',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Molecular biology',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'Why must the lagging strand be synthesized discontinuously as Okazaki fragments?',
        choices: [
          { label: 'A', text: 'DNA polymerase can only synthesize DNA in the 3\'→5\' direction' },
          { label: 'B', text: 'DNA polymerase can only synthesize in the 5\'→3\' direction, but the lagging strand template runs 5\'→3\' away from the fork' },
          { label: 'C', text: 'Primase can only function at the origin of replication' },
          { label: 'D', text: 'RNA primers are too large to allow continuous synthesis' },
        ],
        correctAnswer: 'B',
        explanation: 'DNA polymerase synthesizes 5\'→3\' (adding to the 3\'-OH). At the replication fork: the leading strand template runs 3\'→5\', allowing continuous synthesis in the 5\'→3\' direction moving toward the fork. The lagging strand template runs 5\'→3\' (away from the fork), so synthesis must occur in the opposite direction from fork movement — requiring multiple primers and Okazaki fragments. B is correct. A states the wrong direction (polymerase is 5\'→3\', not 3\'→5\'). C and D are incorrect mechanistic claims.',
        wrongAnswerExplanations: {
          A: 'DNA polymerase synthesizes 5\'→3\' (not 3\'→5\'). The 3\'→5\' exonuclease activity is for PROOFREADING, not synthesis direction.',
          C: 'Primase does not function only at the origin — it places multiple primers throughout the lagging strand (one per Okazaki fragment).',
          D: 'RNA primer size does not cause discontinuous synthesis. The cause is the directionality of DNA polymerase vs. template orientation.',
        },
        teachingPoint: 'Replication directionality: DNA polymerase adds nucleotides to 3\'-OH → synthesis is 5\'→3\'. Leading strand: template is 3\'→5\' → continuous synthesis toward fork. Lagging strand: template is 5\'→3\' → must synthesize away from fork → multiple Okazaki fragments (100-200 nt in eukaryotes; 1000-2000 nt in prokaryotes). Each requires its own RNA primer.',
        relatedTopics: ['Okazaki fragments', 'lagging strand', 'DNA polymerase direction', 'replication fork'],
      },
      {
        id: 'mcat4-bb-007',
        sectionId: 'bio-biochem',
        passageId: 'f4-bb-p2',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Molecular biology',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'A patient with xeroderma pigmentosum has a defect in which DNA repair pathway, resulting in extreme UV sensitivity and high risk of skin cancer?',
        choices: [
          { label: 'A', text: 'Mismatch repair (MMR)' },
          { label: 'B', text: 'Base excision repair (BER)' },
          { label: 'C', text: 'Nucleotide excision repair (NER)' },
          { label: 'D', text: 'Non-homologous end joining (NHEJ)' },
        ],
        correctAnswer: 'C',
        explanation: 'Paragraph 2: NER "removes bulky adducts (e.g., thymine dimers from UV light) by cutting on both sides of the lesion." Xeroderma pigmentosum (XP) is caused by defects in NER genes → inability to remove UV-induced thymine dimers → accumulation of mutations → skin cancer. C is correct. MMR fixes replication errors (mismatches). BER fixes individual damaged bases (e.g., oxidized bases). NHEJ repairs double-strand breaks.',
        wrongAnswerExplanations: {
          A: 'MMR repairs replication errors (mismatched base pairs). Hereditary non-polyposis colorectal cancer (Lynch syndrome) is associated with MMR defects, not UV sensitivity.',
          B: 'BER repairs individual damaged bases (oxidized guanine = 8-oxoG, deaminated cytosine = uracil). Not UV/thymine dimer repair.',
          D: 'NHEJ repairs double-strand breaks. Defects are associated with radiation sensitivity and immune deficiency (V(D)J recombination), not UV-induced thymine dimers.',
        },
        teachingPoint: 'Repair pathway summary: NER = bulky lesions (thymine dimers, carcinogen adducts) → cuts ~25-30 nt around lesion; BER = single damaged bases → glycosylase removes base, AP endonuclease cuts; MMR = replication mismatches → recognizes helix distortion; NHEJ = DSBs → error-prone ligation. Disease associations: XP = NER defect; Lynch syndrome = MMR defect; BRCA1/2 mutations affect homologous recombination (DSB repair).',
        relatedTopics: ['xeroderma pigmentosum', 'NER', 'thymine dimers', 'DNA repair pathways'],
      },
      {
        id: 'mcat4-bb-008',
        sectionId: 'bio-biochem',
        passageId: 'f4-bb-p2',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Molecular biology',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'Cancer cells reactivate telomerase, conferring replicative immortality. This is best understood as:',
        choices: [
          { label: 'A', text: 'Telomerase shortens telomeres, allowing cancer cells to divide indefinitely' },
          { label: 'B', text: 'Telomerase prevents telomere shortening, allowing cancer cells to bypass the normal replicative limit' },
          { label: 'C', text: 'Cancer cells activate NER to repair telomeric DNA' },
          { label: 'D', text: 'Telomerase converts RNA to DNA throughout the cancer cell genome' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 3: somatic cells lose telomere length with each division (end replication problem). When telomeres become critically short, cells undergo senescence or apoptosis (Hayflick limit). Cancer cells reactivate telomerase, which adds telomeric repeats → prevents shortening → cells can divide indefinitely (replicative immortality). B is correct. A reverses the effect. C introduces NER incorrectly. D overstates — telomerase acts only on chromosome ends (telomeres), not throughout the genome.',
        wrongAnswerExplanations: {
          A: 'Telomerase ADDS telomeric repeats, preventing shortening — it does not shorten telomeres.',
          C: 'NER repairs bulky DNA lesions, not telomeric sequences specifically. Telomere maintenance uses telomerase (a specialized reverse transcriptase).',
          D: 'Telomerase is a specialized reverse transcriptase that acts specifically at chromosome ends (telomeres) — it does not convert RNA to DNA throughout the genome.',
        },
        teachingPoint: 'Telomerase mechanism: RNA component (TERC) serves as template for telomeric repeat synthesis; TERT is the reverse transcriptase catalytic subunit. Active in: germ cells, stem cells, most cancer cells. Hayflick limit: normal somatic cells divide ~50-70 times before senescence (controlled by telomere shortening). p53 and Rb pathways respond to critically short telomeres. Anti-telomerase therapy: cancer treatment strategy (prevent replication).',
        relatedTopics: ['telomerase', 'telomere shortening', 'replicative immortality', 'Hayflick limit', 'cancer'],
      },
      {
        id: 'mcat4-bb-009',
        sectionId: 'bio-biochem',
        passageId: 'f4-bb-p2',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Molecular biology',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 2',
        difficulty: 'hard',
        question: 'Which of the following would be the most likely consequence of a mutation eliminating the 3\'→5\' exonuclease activity of DNA polymerase?',
        choices: [
          { label: 'A', text: 'DNA synthesis would proceed in the 3\'→5\' direction instead of 5\'→3\'' },
          { label: 'B', text: 'DNA synthesis would stop completely' },
          { label: 'C', text: 'The mutation rate would increase substantially due to failure to proofread mismatched bases' },
          { label: 'D', text: 'Okazaki fragments would not be joined properly' },
        ],
        correctAnswer: 'C',
        explanation: 'Paragraph 2: "DNA polymerase has intrinsic 3\'→5\' exonuclease (proofreading) activity that removes mismatched bases immediately after incorporation." Eliminating this activity would prevent proofreading → mismatched bases would remain incorporated → increased mutation rate. C is correct. A confuses proofreading with synthesis direction — the 3\'→5\' exonuclease is for proofreading, not for synthesis direction. B is wrong — DNA polymerase would still synthesize; just without proofreading. D is wrong — Okazaki fragment joining is performed by DNA ligase, not by the proofreading exonuclease.',
        wrongAnswerExplanations: {
          A: 'The 3\'→5\' exonuclease is for PROOFREADING (removes mismatched nucleotides), not for determining synthesis direction. Synthesis always proceeds 5\'→3\'.',
          B: 'The 5\'→3\' polymerase activity is separate from the 3\'→5\' exonuclease activity. Eliminating proofreading would not stop synthesis.',
          D: 'Okazaki fragment joining requires DNA ligase (seals nicks) and DNA polymerase I (fills gaps after primer removal). The 3\'→5\' proofreading exonuclease is not specifically required for this step.',
        },
        teachingPoint: 'DNA polymerase activities: (1) 5\'→3\' polymerase activity = synthesis; (2) 3\'→5\' exonuclease = proofreading (removes mismatched 3\' terminal nucleotide); (3) 5\'→3\' exonuclease (pol I only) = primer removal. Proofreading reduces error rate ~100-fold (from 10⁻⁵ to 10⁻⁷). MMR adds another 100-fold correction (overall replication error rate ≈ 10⁻⁹–10⁻¹⁰). Mutator phenotype: cancer cells often have DNA repair or proofreading defects → high mutation rate → accelerated evolution.',
        relatedTopics: ['proofreading exonuclease', 'DNA polymerase fidelity', 'mutation rate', 'mutator phenotype'],
      },
      {
        id: 'mcat4-bb-010',
        sectionId: 'bio-biochem',
        passageId: 'f4-bb-p2',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Molecular biology',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'Homologous recombination (HR) is described as "high-fidelity" repair compared to NHEJ. What makes HR more accurate?',
        choices: [
          { label: 'A', text: 'HR uses the broken ends directly without a template' },
          { label: 'B', text: 'HR uses the intact sister chromatid as a template for accurate repair' },
          { label: 'C', text: 'HR does not require any enzymatic activity' },
          { label: 'D', text: 'HR is faster than NHEJ, reducing the time for errors to accumulate' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 2: HR uses "sister chromatid as template" — having an identical template allows for accurate copying of the correct sequence across the break site. B is correct. A describes NHEJ (joins broken ends directly = no template = error-prone). C is incorrect — HR requires multiple enzymes (Rad51 recombinase, etc.). D is incorrect — HR is actually slower than NHEJ; it is available only in S/G2 phase when sister chromatid is present.',
        wrongAnswerExplanations: {
          A: 'Joining ends without a template = NHEJ, which is error-prone. HR\'s accuracy comes from using a template.',
          C: 'HR requires extensive enzymatic machinery: exonuclease processing, Rad51 strand invasion, DNA synthesis, Holliday junction resolution.',
          D: 'HR is slower and more complex than NHEJ. Its accuracy comes from using a template, not from speed.',
        },
        teachingPoint: 'HR vs. NHEJ: HR = high fidelity, requires sister chromatid (available in S/G2 phase after DNA replication), used in germ cells and rapidly dividing cells; NHEJ = error-prone (may lose or alter nucleotides at join site), available throughout cell cycle, predominates in G1. Therapeutic relevance: BRCA1/2 mutations impair HR → more reliance on error-prone NHEJ → genomic instability → cancer. PARP inhibitors exploit BRCA-deficient cancers (synthetic lethality).',
        relatedTopics: ['homologous recombination', 'NHEJ', 'DSB repair', 'sister chromatid template', 'BRCA'],
      },
    ],
  },
  {
    id: 'f4-bb-p3',
    sectionId: 'bio-biochem',
    passageNumber: 3,
    title: 'Gene Expression and RNA Processing',
    text: `Gene expression in eukaryotes involves multiple tightly regulated steps between the DNA template and the functional protein. Transcription produces a pre-mRNA transcript that undergoes extensive processing in the nucleus before export to the cytoplasm. The three major processing events are: 5\' capping (addition of a 7-methylguanosine cap), polyadenylation (addition of a poly-A tail of ~200 adenine residues at the 3\' end), and splicing (removal of introns by the spliceosome, retaining exons). The 5\' cap and 3\' poly-A tail protect the mRNA from exonucleolytic degradation and facilitate ribosome recognition during translation initiation.

Splicing is carried out by the spliceosome, a large complex of small nuclear ribonucleoproteins (snRNPs). Intron sequences are recognized by conserved sequences at the 5\' splice site (GU), branch point (adenosine), and 3\' splice site (AG). The spliceosome catalyzes two transesterification reactions: the branch point adenosine attacks the 5\' splice site, forming a lariat intermediate; then the free 3\'-OH of the upstream exon attacks the 3\' splice site, joining the exons and releasing the lariat intron.

Alternative splicing allows a single gene to produce multiple protein isoforms by differentially including or excluding exons. It is estimated that over 90% of human multi-exon genes undergo alternative splicing, greatly amplifying the protein-coding capacity of the genome. Regulatory proteins called SR proteins (splicing activators, bind exonic splicing enhancers) and hnRNPs (splicing repressors, bind silencers) modulate spliceosome assembly at specific exons in a tissue-specific and developmental-stage-specific manner.

Researchers found that a point mutation at position +5 of intron 7 of a gene encoding a plasma membrane receptor causes exon 8 skipping in 85% of transcripts. The resulting protein isoform lacks 45 amino acids encoded by exon 8, rendering the receptor non-functional.`,
    questions: [
      {
        id: 'mcat4-bb-011',
        sectionId: 'bio-biochem',
        passageId: 'f4-bb-p3',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Molecular biology',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'The mutation at position +5 of intron 7 most likely disrupts which component of the splicing machinery?',
        choices: [
          { label: 'A', text: 'The poly-A signal sequence at the 3\' end of the mRNA' },
          { label: 'B', text: 'The 5\' splice site (GU) of intron 7, disrupting spliceosome recognition' },
          { label: 'C', text: 'The branch point adenosine within intron 7' },
          { label: 'D', text: 'The 3\' splice site (AG) of intron 7' },
        ],
        correctAnswer: 'B',
        explanation: 'Position +5 of an intron refers to the 5th nucleotide after the exon-intron boundary (the 5\' splice site, which begins GU). Mutations at the 5\' splice site disrupt spliceosome recognition of the intron\'s 5\' end → the spliceosome fails to recognize intron 7\'s 5\' end → the preceding exon (exon 8) is skipped (the spliceosome may instead join exon 7 to exon 9). B is correct. A is unrelated to splicing at this position. C — the branch point is within the intron but further from the 5\' end (typically ~20-50 nt upstream of the 3\' splice site). D — the 3\' splice site is at the 3\' end of the intron (AG), not at position +5.',
        wrongAnswerExplanations: {
          A: 'The poly-A signal (AAUAAA) is at the 3\' end of the pre-mRNA. Position +5 of intron 7 is a splice site, not a polyadenylation signal.',
          C: 'The branch point adenosine is inside the intron, typically 20-50 nt upstream of the 3\' splice site — not at position +5 of the 5\' splice site.',
          D: 'The 3\' splice site (AG) is at the 3\' end of the intron. Position +5 is near the 5\' end of the intron (5\' splice site), not the 3\' end.',
        },
        teachingPoint: 'Splice site notation: position +1 is the first nucleotide of the intron; position −1 is the last nucleotide of the exon. The 5\' splice site consensus is: exon/GU...intron. Mutations at +1 or +2 (GU) are most damaging; +5 is in the conserved 5\' splice site region (consensus: GURAGU). Mutations → exon skipping, intron retention, or cryptic splice site activation. Bernstein Exon 8 skipping: alternative interpretation is that mutation at intron 7 5\' splice site causes the spliceosome to skip from exon 7 directly to exon 9.',
        relatedTopics: ['splice site mutation', 'exon skipping', '5\' splice site', 'spliceosome', 'GU splice site'],
      },
      {
        id: 'mcat4-bb-012',
        sectionId: 'bio-biochem',
        passageId: 'f4-bb-p3',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Molecular biology',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'What is the primary function of the 5\' cap and 3\' poly-A tail added to eukaryotic mRNA?',
        choices: [
          { label: 'A', text: 'They encode additional amino acids at the protein\'s N- and C-termini' },
          { label: 'B', text: 'They protect mRNA from exonucleolytic degradation and facilitate ribosome recognition' },
          { label: 'C', text: 'They signal the mRNA for nuclear export to mitochondria' },
          { label: 'D', text: 'They serve as the primer for DNA replication' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 1: "The 5\' cap and 3\' poly-A tail protect the mRNA from exonucleolytic degradation and facilitate ribosome recognition during translation initiation." B matches directly. A is incorrect — these are non-coding modifications, not codons. C is partially correct (cap does aid nuclear export) but the passage emphasizes protection and ribosome recognition. D confuses mRNA cap with RNA primers (primers are short RNA sequences used in DNA replication; mRNA cap is a distinct structure).',
        wrongAnswerExplanations: {
          A: 'The 5\' cap (7-methylguanosine) and poly-A tail are non-coding modifications. They are not translated into amino acids.',
          C: 'While the cap contributes to nuclear export, this is not stated as its primary function in the passage. The passage states protection from degradation and ribosome recognition.',
          D: 'RNA primers for DNA replication are short RNA sequences placed by primase at replication origins. The mRNA 5\' cap is a completely different structure with a different function.',
        },
        teachingPoint: 'mRNA processing functions: 5\' cap (7mG): protection from 5\' exonucleases + ribosome (eIF4E) binding (translation initiation) + nuclear export; poly-A tail: protection from 3\' exonucleases + mRNA stability + nuclear export + PABP binding (translation). Degradation pathway: decapping (removal of 5\' cap) → 5\'→3\' exonuclease degradation. mRNA half-life varies from minutes to hours depending on stability elements.',
        relatedTopics: ['5\' cap function', 'poly-A tail', 'mRNA stability', 'mRNA processing', 'ribosome recognition'],
      },
      {
        id: 'mcat4-bb-013',
        sectionId: 'bio-biochem',
        passageId: 'f4-bb-p3',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Molecular biology',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'Alternative splicing of a single gene can produce protein isoforms with different functions. Which of the following best explains why this increases protein diversity without requiring more genes?',
        choices: [
          { label: 'A', text: 'Alternative splicing adds new exons to the genome' },
          { label: 'B', text: 'Different combinations of exons produce structurally distinct proteins from the same pre-mRNA' },
          { label: 'C', text: 'Alternative splicing allows ribosomes to translate different reading frames of the same mRNA' },
          { label: 'D', text: 'SR proteins create new coding sequences not present in the original gene' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 3: alternative splicing "allows a single gene to produce multiple protein isoforms by differentially including or excluding exons." Different exon combinations encode structurally different proteins (different functional domains) → different functions. B is correct. A is incorrect — alternative splicing combines existing exons, does not create new ones. C is a different mechanism (ribosomal frameshifting) not described in the passage. D misrepresents SR protein function (they modulate spliceosome assembly, not create new sequences).',
        wrongAnswerExplanations: {
          A: 'Alternative splicing does not add new exons. It selectively includes or excludes existing exons from the final mRNA.',
          C: 'Ribosomal frameshifting is a separate phenomenon. The passage describes alternative splicing as producing different exon combinations, not reading different frames.',
          D: 'SR proteins modulate which exons are included by facilitating spliceosome assembly at specific locations — they do not create new coding sequences.',
        },
        teachingPoint: 'Alternative splicing: >90% of human multi-exon genes undergo alternative splicing → ~100,000 distinct protein isoforms from ~20,000 genes. Types: exon skipping (most common), alternative 5\' or 3\' splice sites, mutually exclusive exons, intron retention. Example: troponin T has 18 exons → 64 possible isoforms; DSCAM (Drosophila) can produce >38,000 isoforms (critical for neural wiring). Tissue specificity: different organs express different splicing factors → different isoforms.',
        relatedTopics: ['alternative splicing', 'exon inclusion exclusion', 'protein diversity', 'SR proteins', 'splicing isoforms'],
      },
      {
        id: 'mcat4-bb-014',
        sectionId: 'bio-biochem',
        passageId: 'f4-bb-p3',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Molecular biology',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'During splicing, what is the "lariat intermediate"?',
        choices: [
          { label: 'A', text: 'A circular RNA formed by exon-exon ligation' },
          { label: 'B', text: 'A looped intron structure formed when the branch point adenosine attacks the 5\' splice site' },
          { label: 'C', text: 'A protein complex that holds the spliceosome together' },
          { label: 'D', text: 'The released poly-A tail after mRNA degradation' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 2: "the branch point adenosine attacks the 5\' splice site, forming a lariat intermediate." The lariat is a lasso-shaped intron with a 2\'-5\' phosphodiester bond at the branch point, creating a closed loop with a 3\' tail. B is correct. A describes circularization of RNA (circular RNA is different). C incorrectly describes the lariat as a protein complex. D is unrelated.',
        wrongAnswerExplanations: {
          A: 'Circular RNAs (circRNAs) are formed by back-splicing (exon-exon or exon-intron joining); lariat intermediates are intron-specific structures with a 2\'-5\' branch.',
          C: 'The lariat is an RNA structure (branched intron), not a protein complex.',
          D: 'The poly-A tail is a different RNA modification; it is not produced during splicing.',
        },
        teachingPoint: 'Splicing mechanism: (1) Branch point adenosine 2\'-OH attacks 5\' splice site → lariat + exon 1 with free 3\'-OH; (2) Exon 1 3\'-OH attacks 3\' splice site → exons joined + lariat released. Lariat: intron folded back on itself, 2\'-5\' phosphodiester bond at branch point. Eventually debranched by lariat debranching enzyme → linear intron → degraded. Splice sites: 5\' GU (almost invariant) / branch point A / 3\' AG (almost invariant) — "GU-AG rule."',
        relatedTopics: ['lariat intermediate', 'splicing mechanism', 'branch point', 'transesterification', 'intron removal'],
      },
      {
        id: 'mcat4-bb-015',
        sectionId: 'bio-biochem',
        passageId: 'f4-bb-p3',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Molecular biology',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 2',
        difficulty: 'hard',
        question: 'In the context of the described mutation (exon 8 skipping in 85% of transcripts), which approach would most directly restore normal receptor function?',
        choices: [
          { label: 'A', text: 'Increasing the transcription rate of the gene' },
          { label: 'B', text: 'Adding exogenous poly-A tail sequences' },
          { label: 'C', text: 'Antisense oligonucleotide therapy that blocks the aberrant splice site or promotes correct splicing' },
          { label: 'D', text: 'Treating with a competitive inhibitor of the mutant receptor isoform' },
        ],
        correctAnswer: 'C',
        explanation: 'The mutation causes exon 8 skipping due to disrupted 5\' splice site of intron 7. Antisense oligonucleotides (ASOs) can be designed to block aberrant splice sites, force inclusion of exon 8, or redirect splicing to the correct site. This is the mechanism of FDA-approved splice-correcting therapies (e.g., nusinersen for SMA, eteplirsen for Duchenne muscular dystrophy). C is the most targeted approach. A would increase total mRNA but not fix the aberrant splicing. B is irrelevant — poly-A tail is separate from splicing. D doesn\'t address the cause.',
        wrongAnswerExplanations: {
          A: 'Increasing transcription rate would produce more mRNA — but 85% would still undergo exon 8 skipping. The problem is splicing, not transcription rate.',
          B: 'The poly-A tail has no role in exon splicing. Adding exogenous poly-A sequences would not correct the splice site mutation.',
          D: 'The mutant isoform is non-functional (lacks 45 amino acids). A competitive inhibitor of the mutant isoform would not restore function of the receptor; it would further inhibit whatever activity the mutant might have.',
        },
        teachingPoint: 'Splice-correcting therapies: ASOs (antisense oligonucleotides) hybridize to pre-mRNA to block or redirect splicing. Examples: nusinersen (Spinraza) — blocks ISS-N1 silencer in SMN2 intron 7 → exon 7 inclusion → SMN protein restoration (SMA treatment); eteplirsen — promotes exon 51 skipping in dystrophin to restore reading frame (DMD). This is precision medicine targeting RNA processing rather than protein function.',
        relatedTopics: ['antisense oligonucleotide', 'splice correction therapy', 'exon skipping treatment', 'SMA DMD', 'splice site mutation treatment'],
      },
    ],
  },
  {
    id: 'f4-bb-p4',
    sectionId: 'bio-biochem',
    passageNumber: 4,
    title: 'Cellular Respiration: The TCA Cycle and Oxidative Phosphorylation',
    text: `The citric acid cycle (TCA cycle, Krebs cycle) is the central metabolic hub of aerobic respiration. In the mitochondrial matrix, acetyl-CoA (2 carbons) condenses with oxaloacetate (4 carbons) to form citrate (6 carbons). Through a series of oxidation and decarboxylation reactions, the 2 carbons introduced as acetyl-CoA are released as CO₂, generating 3 NADH, 1 FADH₂, and 1 GTP per turn. The four-carbon oxaloacetate is regenerated, allowing the cycle to continue. Per glucose molecule, the cycle turns twice (two acetyl-CoA from pyruvate decarboxylation), producing 6 NADH, 2 FADH₂, and 2 GTP from the TCA cycle alone.

The electrons carried by NADH and FADH₂ are transferred to the electron transport chain (ETC) embedded in the inner mitochondrial membrane. The ETC consists of four complexes (I–IV) plus ATP synthase (Complex V). Complex I (NADH dehydrogenase) accepts electrons from NADH and pumps 4H⁺ into the intermembrane space (IMS). Complex II (succinate dehydrogenase) accepts electrons from FADH₂ but does not pump protons. Complexes III and IV pump additional protons. The proton gradient (higher [H⁺] in IMS) drives ATP synthesis by ATP synthase (chemiosmosis), which uses the proton motive force to phosphorylate ADP. The final electron acceptor is O₂ (reduced to H₂O at Complex IV). ATP yield per glucose: approximately 30-32 ATP (theoretical maximum is ~38 but losses due to proton leak and ATP/ADP translocase cost reduce actual yield).

Uncoupling agents disrupt the proton gradient without passing through ATP synthase, dissipating the gradient as heat. Dinitrophenol (DNP) is a protonophore that carries H⁺ across the inner mitochondrial membrane, uncoupling electron transport from ATP synthesis — electron transport continues (O₂ consumption increases) but ATP production falls. In physiological contexts, uncoupling protein 1 (UCP1) in brown adipose tissue performs a similar function, generating heat rather than ATP (thermogenesis in neonates and hibernating animals).`,
    questions: [
      {
        id: 'mcat4-bb-016',
        sectionId: 'bio-biochem',
        passageId: 'f4-bb-p4',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'Metabolism',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'How many NADH and FADH₂ molecules are produced from one complete turn of the TCA cycle (from one acetyl-CoA)?',
        choices: [
          { label: 'A', text: '2 NADH and 2 FADH₂' },
          { label: 'B', text: '3 NADH and 1 FADH₂' },
          { label: 'C', text: '1 NADH and 3 FADH₂' },
          { label: 'D', text: '4 NADH and 1 FADH₂' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 1: "generating 3 NADH, 1 FADH₂, and 1 GTP per turn." B is correct. The three NADH come from isocitrate dehydrogenase, α-ketoglutarate dehydrogenase, and malate dehydrogenase. The single FADH₂ comes from succinate dehydrogenase (Complex II).',
        wrongAnswerExplanations: {
          A: 'The passage states 3 NADH, 1 FADH₂ per turn — not 2 NADH, 2 FADH₂.',
          C: 'The ratio is reversed: 3 NADH (not 1) and 1 FADH₂ (not 3) per turn.',
          D: '4 NADH and 1 FADH₂ would overcount NADH. Only 3 oxidation steps yield NADH in the TCA cycle.',
        },
        teachingPoint: 'TCA cycle per turn (per acetyl-CoA): 3 NADH + 1 FADH₂ + 1 GTP (substrate-level phosphorylation) + 2 CO₂ released. Per glucose (2 pyruvates → 2 acetyl-CoA): 6 NADH + 2 FADH₂ + 2 GTP from TCA. Plus: 2 NADH from glycolysis, 2 NADH from pyruvate decarboxylation. Total NADH for ETC: ~10 NADH per glucose.',
        relatedTopics: ['TCA cycle yield', 'NADH FADH2', 'citric acid cycle', 'acetyl-CoA'],
      },
      {
        id: 'mcat4-bb-017',
        sectionId: 'bio-biochem',
        passageId: 'f4-bb-p4',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'Metabolism',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'Why does FADH₂ produce fewer ATP molecules than NADH when fed into the electron transport chain?',
        choices: [
          { label: 'A', text: 'FADH₂ is oxidized at Complex I, which pumps fewer protons' },
          { label: 'B', text: 'FADH₂ is oxidized at Complex II, which does not pump protons into the intermembrane space' },
          { label: 'C', text: 'FADH₂ carries more electrons than NADH' },
          { label: 'D', text: 'FAD cannot be oxidized by the ETC' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 2: "Complex II (succinate dehydrogenase) accepts electrons from FADH₂ but does not pump protons." Because FADH₂ feeds electrons into the ETC at Complex II (bypassing Complex I which pumps 4H⁺), fewer protons are pumped per FADH₂ molecule → smaller proton gradient → less ATP synthesis. FADH₂ ≈ 1.5 ATP; NADH ≈ 2.5 ATP (at ~P/O ratios). B is correct. A is wrong — FADH₂ is oxidized at Complex II, not Complex I. C and D are incorrect.',
        wrongAnswerExplanations: {
          A: 'NADH (not FADH₂) is oxidized at Complex I. FADH₂ is oxidized at Complex II (succinate dehydrogenase).',
          C: 'FADH₂ and NADH both carry 2 electrons per molecule. The difference is WHERE they enter the ETC (proton pumping difference).',
          D: 'FADH₂ is readily oxidized by the ETC at Complex II (succinate dehydrogenase).',
        },
        teachingPoint: 'ETC entry points: NADH → Complex I (4H⁺ pumped) → Complex III (4H⁺) → Complex IV (2H⁺) = 10H⁺ pumped → ~2.5 ATP. FADH₂ → Complex II (0H⁺) → Complex III (4H⁺) → Complex IV (2H⁺) = 6H⁺ pumped → ~1.5 ATP. ATP/O ratio (P/O): NADH ≈ 2.5; FADH₂ ≈ 1.5. The bypass of Complex I by FADH₂ is the key.',
        relatedTopics: ['FADH2 fewer ATP', 'Complex II no proton pump', 'ETC entry points', 'P/O ratio', 'NADH vs FADH2'],
      },
      {
        id: 'mcat4-bb-018',
        sectionId: 'bio-biochem',
        passageId: 'f4-bb-p4',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'Metabolism',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'Treatment with dinitrophenol (DNP) would most likely result in which of the following?',
        choices: [
          { label: 'A', text: 'Decreased O₂ consumption and increased ATP production' },
          { label: 'B', text: 'Increased O₂ consumption and decreased ATP production, with heat generation' },
          { label: 'C', text: 'Inhibition of the TCA cycle, reducing NADH production' },
          { label: 'D', text: 'Increased O₂ consumption and increased ATP production' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 3: "electron transport continues (O₂ consumption increases) but ATP production falls" and DNP "dissipating the gradient as heat." Because DNP uncouples proton gradient from ATP synthesis, the ETC continues to consume O₂ (to maintain electron flow) but the proton motive force is wasted as heat rather than driving ATP synthesis. B matches. A incorrectly predicts decreased O₂ (O₂ consumption actually increases because ETC accelerates to try to maintain gradient). C is wrong — TCA cycle is not directly inhibited. D is wrong — ATP production decreases.',
        wrongAnswerExplanations: {
          A: 'O₂ consumption INCREASES with uncouplers (ETC works harder) and ATP DECREASES. A states the opposite on both counts.',
          C: 'DNP acts on the inner mitochondrial membrane as a protonophore. The TCA cycle is in the matrix and is not directly inhibited by DNP.',
          D: 'Increased O₂ is correct, but ATP production DECREASES (proton gradient is dissipated as heat, not used for ATP synthesis).',
        },
        teachingPoint: 'Uncouplers: disrupt the proton gradient without going through ATP synthase. Results: (1) ETC accelerates (no "back pressure" from high proton gradient) → increased O₂ consumption; (2) No ATP synthesis from proton gradient → decreased ATP; (3) Energy released as heat. DNP historical use: "diet pill" (dangerous — caused deaths by hyperthermia). Physiological uncoupling: UCP1 in brown adipose tissue (BAT) → thermogenesis. UCP2/3 in other tissues (less efficient). Brown fat activation: cold exposure → NE → β3 receptor → cAMP → lipolysis → free fatty acids activate UCP1.',
        relatedTopics: ['DNP uncoupler', 'uncoupling proton gradient', 'O2 consumption increase', 'heat generation', 'UCP1'],
      },
      {
        id: 'mcat4-bb-019',
        sectionId: 'bio-biochem',
        passageId: 'f4-bb-p4',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'Metabolism',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'The final electron acceptor in the electron transport chain is:',
        choices: [
          { label: 'A', text: 'NAD⁺' },
          { label: 'B', text: 'FAD' },
          { label: 'C', text: 'Oxygen (O₂)' },
          { label: 'D', text: 'ATP' },
        ],
        correctAnswer: 'C',
        explanation: 'Paragraph 2: "The final electron acceptor is O₂ (reduced to H₂O at Complex IV)." C is correct. O₂ accepts electrons at cytochrome c oxidase (Complex IV): O₂ + 4H⁺ + 4e⁻ → 2H₂O. This is why aerobic respiration requires oxygen. NAD⁺ and FAD are electron carriers (accept electrons in metabolic reactions), not the final ETC acceptor. ATP is not an electron acceptor.',
        wrongAnswerExplanations: {
          A: 'NAD⁺ is an electron ACCEPTOR in metabolic reactions (oxidation steps in glycolysis, TCA cycle), becoming NADH. But it is not the final ETC acceptor — it DONATES electrons to Complex I.',
          B: 'FAD accepts electrons in the TCA cycle (succinate dehydrogenase) becoming FADH₂, which then donates electrons to Complex II. FAD is not the final ETC acceptor.',
          D: 'ATP is a phosphorylated energy carrier — not an electron acceptor. ATP synthase uses the proton gradient to produce ATP, but ATP itself does not accept electrons.',
        },
        teachingPoint: 'Why aerobic respiration requires O₂: O₂ is the terminal electron acceptor at Complex IV. Without O₂, electrons cannot be passed along the ETC → no proton gradient → no ATP synthesis → cells must rely on anaerobic fermentation. O₂ has a very high reduction potential (E°\' = +0.82 V), making it an ideal terminal acceptor. 2.5% of O₂ is reduced to superoxide (O₂•⁻) rather than H₂O — this is the source of most cellular reactive oxygen species (ROS).',
        relatedTopics: ['final electron acceptor', 'oxygen ETC', 'Complex IV', 'aerobic respiration', 'H2O formation'],
      },
      {
        id: 'mcat4-bb-020',
        sectionId: 'bio-biochem',
        passageId: 'f4-bb-p4',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'Metabolism',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 2',
        difficulty: 'hard',
        question: 'A researcher treats cells with oligomycin, which blocks the proton channel of ATP synthase. Which of the following best predicts the immediate consequence?',
        choices: [
          { label: 'A', text: 'Increased ETC activity and increased ATP production' },
          { label: 'B', text: 'Decreased ETC activity and decreased ATP production' },
          { label: 'C', text: 'The proton gradient dissipates immediately due to proton leak' },
          { label: 'D', text: 'Uncoupling of electron transport from O₂ consumption' },
        ],
        correctAnswer: 'B',
        explanation: 'Oligomycin blocks ATP synthase\'s proton channel → protons cannot flow back through ATP synthase → proton gradient builds up → "back pressure" on the ETC (pumping more protons into an already-saturated IMS becomes thermodynamically difficult) → ETC slows → O₂ consumption decreases → NADH and FADH₂ accumulate → ATP production falls (no proton flux through ATP synthase). B is correct. This is the opposite of uncouplers: oligomycin increases the gradient (inhibits its use), uncouplers decrease the gradient (bypass ATP synthase).',
        wrongAnswerExplanations: {
          A: 'Blocking ATP synthase causes the proton gradient to BUILD UP → thermodynamic "back pressure" → ETC SLOWS (decreased activity). ATP production also decreases.',
          C: 'Proton leak is a passive process that increases when the gradient builds — but it is slow and incomplete. The immediate consequence is ETC slowing, not complete dissipation.',
          D: 'Oligomycin does NOT uncouple — it inhibits ATP synthase. Uncouplers bypass ATP synthase, allowing proton leak without ATP synthesis. Oligomycin prevents proton flow through ATP synthase but does NOT provide an alternative proton path.',
        },
        teachingPoint: 'Oligomycin vs. uncouplers (compare and contrast): Oligomycin (Complex V inhibitor): blocks proton channel → gradient builds → ETC slows → O₂ consumption decreases → ATP falls. Uncouplers (DNP, FCCP): provide alternative proton path → gradient dissipates → ETC speeds up → O₂ consumption increases → ATP falls. Both decrease ATP; opposite effects on ETC activity and O₂ consumption.',
        relatedTopics: ['oligomycin ATP synthase', 'proton gradient back pressure', 'ETC inhibition', 'oligomycin vs uncoupler', 'chemiosmosis'],
      },
    ],
  },
  {
    id: 'f4-bb-p5',
    sectionId: 'bio-biochem',
    passageNumber: 5,
    title: 'Protein Structure and Function',
    text: `Proteins are polymers of amino acids linked by peptide bonds. Their function depends on their three-dimensional structure, which is organized into four hierarchical levels. Primary structure is the linear sequence of amino acids, determined by the gene sequence. Secondary structure consists of local regular folding patterns stabilized by hydrogen bonds between backbone amide and carbonyl groups: the α-helix (H-bond between i and i+4 residues) and β-sheet (H-bonds between extended strands). Tertiary structure is the overall 3D fold of a single polypeptide, stabilized by hydrophobic interactions (major driving force), hydrogen bonds, ionic interactions, and disulfide bonds. Quaternary structure describes the arrangement of multiple polypeptide subunits.

Protein folding is thermodynamically driven by the hydrophobic effect: the burial of nonpolar residues in the protein interior reduces the ordered water structure around them (favorable entropy increase in water). The process is guided by molecular chaperones that prevent aggregation of partially folded intermediates. Misfolding and aggregation underlie diseases like Alzheimer's (amyloid-β plaques), Parkinson's (α-synuclein Lewy bodies), and prion diseases (PrPᶜ → PrPˢᶜ conformational change).

Denaturation disrupts tertiary and secondary structure without breaking peptide bonds. Denaturing agents include heat (disrupts hydrophobic interactions and H-bonds), urea (disrupts H-bonds and hydrophobic interactions), detergents (SDS disrupts hydrophobic core), and extremes of pH (disrupts ionic interactions and hydrogen bonds). Denaturation is often reversible for small proteins (renaturation) but is typically irreversible for large, multi-domain proteins.

Researchers studied a small cytoplasmic protein of 120 amino acids. Under physiological conditions (pH 7.4, 37°C), the protein exists as a homodimer. When treated with 8M urea and β-mercaptoethanol (BME), the protein unfolds completely and the subunits separate. Upon removal of urea and BME by dialysis, ~80% of protein activity is restored.`,
    questions: [
      {
        id: 'mcat4-bb-021',
        sectionId: 'bio-biochem',
        passageId: 'f4-bb-p5',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'Protein structure',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'Treatment with β-mercaptoethanol (BME) in the experiment described would most directly disrupt which type of protein interaction?',
        choices: [
          { label: 'A', text: 'Hydrogen bonds within α-helices' },
          { label: 'B', text: 'Hydrophobic interactions in the protein core' },
          { label: 'C', text: 'Disulfide bonds between cysteine residues' },
          { label: 'D', text: 'Ionic interactions between charged amino acid side chains' },
        ],
        correctAnswer: 'C',
        explanation: 'BME (β-mercaptoethanol) is a reducing agent that reduces disulfide bonds (S-S → 2 SH) by providing free thiol groups. The passage mentions BME alongside 8M urea as denaturants, and the context (homodimer that separates) suggests disulfide bonds may link subunits. BME specifically targets disulfide bonds; urea disrupts H-bonds and hydrophobic interactions. C is correct. A — α-helix H-bonds are disrupted by urea/heat, not BME. B — hydrophobic interactions are disrupted by urea and SDS, not BME. D — ionic interactions are disrupted by pH changes, not BME.',
        wrongAnswerExplanations: {
          A: 'BME does not disrupt hydrogen bonds. H-bonds in α-helices are disrupted by denaturants like urea, guanidinium chloride, or heat.',
          B: 'Hydrophobic interactions are disrupted by urea and detergents (SDS). BME has no effect on hydrophobic interactions.',
          D: 'Ionic interactions between charged residues are disrupted by pH extremes (changing protonation state) or high salt. BME is a thiol-specific reducing agent.',
        },
        teachingPoint: 'BME and DTT: reducing agents that cleave disulfide bonds (cysteine-cysteine). Used to: (1) denature proteins by breaking S-S bonds; (2) reduce proteins for SDS-PAGE (fully denatured + SDS = separation by size only). Disulfide bonds are important in extracellular proteins (stable in oxidizing environment). Inside cells: reducing environment (GSH) keeps thiols reduced. BME + urea = complete denaturation (breaks all non-covalent interactions + disulfide bonds); BME alone = breaks disulfide bonds only.',
        relatedTopics: ['beta-mercaptoethanol', 'disulfide bonds', 'reducing agent', 'protein denaturation', 'DTT'],
      },
      {
        id: 'mcat4-bb-022',
        sectionId: 'bio-biochem',
        passageId: 'f4-bb-p5',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'Protein structure',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'The observation that ~80% of protein activity is restored after dialysis most directly demonstrates:',
        choices: [
          { label: 'A', text: 'The protein\'s primary structure alone determines its three-dimensional fold' },
          { label: 'B', text: 'The protein is irreversibly denatured by urea and BME' },
          { label: 'C', text: 'At least some of the protein can refold correctly without external chaperones under these conditions' },
          { label: 'D', text: 'Quaternary structure is not important for protein function' },
        ],
        correctAnswer: 'C',
        explanation: '80% activity recovery after removal of denaturants indicates substantial correct refolding and dimer reassembly — i.e., the protein can refold (at least partially) spontaneously under the experimental conditions, consistent with the information encoded in the primary sequence guiding folding. C is correct. A may be implied but "primary structure alone" is too strong — chaperones often assist in vivo; the result shows refolding occurred, not that primary structure is sufficient. B is incorrect (80% recovery = largely reversible). D is wrong — the protein is a homodimer, so quaternary structure is important; recovery of dimer activity shows quaternary structure reassembles.',
        wrongAnswerExplanations: {
          A: '"Primary structure alone determines fold" may be largely true (Anfinsen\'s experiment) but the experimental result (80% recovery) directly demonstrates refolding capability — not a mechanistic claim about what determines the fold.',
          B: 'Irreversible denaturation would show 0% activity recovery. 80% recovery = substantially reversible denaturation.',
          D: 'The protein is a homodimer (quaternary structure). The fact that 80% activity recovers shows the dimer reassembles — confirming quaternary structure IS important and CAN reassemble.',
        },
        teachingPoint: 'Anfinsen\'s experiment (1972): RNase A denatured with urea + BME → completely unfolded. Removal of denaturants → 95-100% activity recovered → conclusion: primary sequence encodes 3D structure (thermodynamic information in the sequence). The MCAT often references Anfinsen to support the idea that primary structure determines tertiary structure. Chaperones assist with kinetics (preventing aggregation) but do not provide information — the final fold is determined by primary structure.',
        relatedTopics: ['Anfinsen experiment', 'protein refolding', 'primary structure determines fold', 'renaturation', 'chaperones'],
      },
      {
        id: 'mcat4-bb-023',
        sectionId: 'bio-biochem',
        passageId: 'f4-bb-p5',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'Protein structure',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'The hydrophobic effect, described as the "major driving force" for protein folding, primarily involves:',
        choices: [
          { label: 'A', text: 'Formation of hydrogen bonds between nonpolar side chains' },
          { label: 'B', text: 'Favorable entropy increase as ordered water molecules are released when nonpolar residues cluster' },
          { label: 'C', text: 'Electrostatic attraction between positively and negatively charged residues' },
          { label: 'D', text: 'Covalent bond formation between hydrophobic amino acids' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 2: "the burial of nonpolar residues in the protein interior reduces the ordered water structure around them (favorable entropy increase in water)." B matches. The hydrophobic effect is primarily entropy-driven: when nonpolar residues are exposed to water, water molecules form ordered clathrate-like structures around them (low entropy). Burying nonpolar residues releases these ordered waters → large increase in water entropy → thermodynamically favorable. A is incorrect — hydrophobic interactions are not H-bonds (nonpolar groups don\'t form H-bonds). C describes ionic interactions. D involves covalent bonds (not the hydrophobic effect).',
        wrongAnswerExplanations: {
          A: 'Hydrophobic residues are nonpolar — they do not form hydrogen bonds. H-bonds involve δ+ and δ- partial charges (polar or charged groups).',
          C: 'Electrostatic attraction between oppositely charged residues is ionic interaction (salt bridges), not the hydrophobic effect.',
          D: 'The hydrophobic effect involves van der Waals interactions between nonpolar groups and/or entropy of water — not covalent bond formation.',
        },
        teachingPoint: 'Hydrophobic effect: thermodynamic basis. ΔG = ΔH − TΔS. Hydrophobic folding: ΔH ≈ 0 or slightly unfavorable (weak van der Waals). ΔS(water) is strongly favorable (releasing ordered water shells → entropy gain). Overall ΔG < 0 → folding is spontaneous. This is why proteins fold with hydrophobic core — burying nonpolar residues releases constrained water molecules → large entropy increase. Temperature dependence: hydrophobic effect increases with temperature (unlike H-bonds which weaken).',
        relatedTopics: ['hydrophobic effect', 'protein folding driving force', 'entropy water', 'nonpolar residue burial'],
      },
      {
        id: 'mcat4-bb-024',
        sectionId: 'bio-biochem',
        passageId: 'f4-bb-p5',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'Protein structure',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 2',
        difficulty: 'hard',
        question: 'Prion diseases involve conversion of PrPᶜ to PrPˢᶜ with no change in primary structure. Which principle of protein structure does this MOST directly challenge?',
        choices: [
          { label: 'A', text: 'That secondary structure is stabilized by hydrogen bonds' },
          { label: 'B', text: 'That the primary structure uniquely determines the three-dimensional fold' },
          { label: 'C', text: 'That the hydrophobic effect drives folding' },
          { label: 'D', text: 'That quaternary structure requires disulfide bonds' },
        ],
        correctAnswer: 'B',
        explanation: 'In prion diseases, PrPˢᶜ has the same amino acid sequence (primary structure) as normal PrPᶜ but adopts a different β-sheet-rich conformation → different (pathological) function. If primary structure uniquely determined 3D fold, the same sequence could not adopt two distinct conformations. This is a direct challenge to the Anfinsen principle that primary sequence uniquely encodes structure. B is correct. A, C, D are not directly challenged by prion conformational polymorphism.',
        wrongAnswerExplanations: {
          A: 'Prion conformational change involves α-helix → β-sheet conversion, which affects the types of H-bonds — but the challenge is not specifically to H-bond stabilization theory.',
          C: 'The hydrophobic effect drives folding regardless; prions show that the same sequence can reach different stable conformational minima — the challenge is to uniqueness of folding, not to the driving force.',
          D: 'Quaternary structure and disulfide bonds are not specifically implicated in the prion conformational challenge.',
        },
        teachingPoint: 'Prion challenge to Anfinsen principle: same primary sequence → two distinct stable conformations (PrPᶜ = α-helical; PrPˢᶜ = β-sheet rich). PrPˢᶜ acts as a template to convert PrPᶜ → PrPˢᶜ (conformational templating). This shows the folding energy landscape can have multiple minima for the same sequence. Prion diseases: CJD, kuru, scrapie, BSE. Transmission: ingestion of prion protein converts host PrPᶜ. No nucleic acid required (challenged Central Dogma).',
        relatedTopics: ['prion conformational change', 'Anfinsen principle challenge', 'same sequence different fold', 'PrPsc', 'protein conformational polymorphism'],
      },
      {
        id: 'mcat4-bb-025',
        sectionId: 'bio-biochem',
        passageId: 'f4-bb-p5',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'Protein structure',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'Which level of protein structure is disrupted by denaturation but NOT by hydrolysis of peptide bonds?',
        choices: [
          { label: 'A', text: 'Primary structure' },
          { label: 'B', text: 'Secondary, tertiary, and quaternary structure' },
          { label: 'C', text: 'Only quaternary structure' },
          { label: 'D', text: 'All four levels of protein structure equally' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 3: "Denaturation disrupts tertiary and secondary structure without breaking peptide bonds." Since primary structure = sequence of amino acids linked by peptide bonds, denaturation does NOT disrupt primary structure. Hydrolysis (e.g., by proteases or acid/base) DOES break peptide bonds → disrupts primary structure. Therefore, denaturation disrupts secondary, tertiary, and quaternary structure — but not primary. B is correct. A is incorrect. C is too restrictive. D is incorrect — primary structure is preserved during denaturation.',
        wrongAnswerExplanations: {
          A: 'Primary structure is the peptide-bond-linked sequence. Denaturation does NOT break peptide bonds → primary structure is preserved during denaturation.',
          C: 'Denaturation disrupts secondary AND tertiary AND quaternary structure (all non-covalent interactions, and disulfide bonds with reducing agents). Only primary structure is preserved.',
          D: 'Primary structure is NOT disrupted by denaturation — only secondary, tertiary, and quaternary are.',
        },
        teachingPoint: 'Denaturation = disruption of non-covalent interactions (and disulfide bonds with reducing agents) → loss of secondary/tertiary/quaternary structure. Primary structure (peptide bonds) = covalent bonds → require acid/base/protease hydrolysis or peptide bond cleavage. Irreversible denaturation: large proteins aggregate (hydrophobic patches exposed) → cannot refold. SDS-PAGE: SDS denatures proteins + coats them with negative charge → separation by molecular weight (primary structure determines size).',
        relatedTopics: ['denaturation vs hydrolysis', 'protein structure levels', 'peptide bond preservation', 'SDS-PAGE denaturation'],
      },
    ],
  },
]
