import type { MCATQuestion } from '../types'

// Form 4 C/P — 15 discrete questions (IDs mcat4-cp-045 through mcat4-cp-059)

export const cpDiscretes4: MCATQuestion[] = [
  {
    id: 'mcat4-cp-045',
    sectionId: 'chem-phys',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Physics',
    contentCategory: 'Physics',
    foundationalConcept: 'FC 4',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    question: 'A 2 kg object falls from rest. What is its kinetic energy after falling 10 m? (g = 10 m/s²; ignore air resistance)',
    choices: [
      { label: 'A', text: '10 J' },
      { label: 'B', text: '100 J' },
      { label: 'C', text: '200 J' },
      { label: 'D', text: '400 J' },
    ],
    correctAnswer: 'C',
    explanation: 'By conservation of energy: KE gained = PE lost = mgh = (2 kg)(10 m/s²)(10 m) = 200 J. C is correct. Alternatively: v² = 2gh = 200 m²/s² → KE = ½mv² = ½(2)(200) = 200 J. A — 10 J would require mgh = 10 → h = 0.5 m. B — 100 J = (1)(10)(10) — incorrect mass. D — 400 J = (2)(10)(20) — incorrect height.',
    wrongAnswerExplanations: {
      A: 'KE = mgh = 2 × 10 × 10 = 200 J. 10 J is far too small for this height and mass.',
      B: '100 J = (1 kg)(10)(10): incorrect mass. The correct mass is 2 kg → KE = 200 J.',
      D: '400 J = (2)(10)(20): uses height of 20 m instead of 10 m.',
    },
    teachingPoint: 'Conservation of energy: KE gained = PE lost (in absence of friction). PE = mgh; KE = ½mv². At bottom of fall (h=0): all PE converted to KE. mgh = ½mv² → v = √(2gh). Energy is a scalar — no direction needed. Work-energy theorem: net work = ΔKE. Gravity does positive work when object falls (force parallel to displacement).',
    relatedTopics: ['conservation of energy', 'kinetic energy', 'potential energy', 'mgh', 'free fall'],
  },
  {
    id: 'mcat4-cp-046',
    sectionId: 'chem-phys',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Chemistry',
    contentCategory: 'General chemistry',
    foundationalConcept: 'FC 5',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    question: 'Le Chatelier\'s Principle predicts that increasing pressure in an equilibrium system favors:',
    choices: [
      { label: 'A', text: 'The side with fewer moles of gas' },
      { label: 'B', text: 'The side with more moles of gas' },
      { label: 'C', text: 'The endothermic direction' },
      { label: 'D', text: 'No change, because pressure does not affect equilibrium involving gases' },
    ],
    correctAnswer: 'A',
    explanation: 'Le Chatelier\'s Principle: when a system at equilibrium is disturbed, it shifts to oppose the disturbance. Increasing pressure on a gas-phase system: the system reduces pressure by shifting toward the side with fewer moles of gas (fewer gas molecules = lower pressure). Example: N₂ + 3H₂ ⇌ 2NH₃ — increasing pressure favors the right (4 mol gas → 2 mol gas). A is correct. A — fewer moles reduces pressure; more moles would increase it (opposing the perturbation means shifting to fewer moles). C — endothermic/exothermic direction is affected by temperature, not pressure. D — pressure does affect equilibrium involving gases (and not solids/liquids).',
    wrongAnswerExplanations: {
          C: 'Temperature changes affect the endothermic/exothermic direction of equilibrium. Pressure changes affect the gas mole balance. These are independent perturbations.',
      D: 'Pressure changes affect equilibria involving gases (when the number of gas moles differs between reactants and products). If moles of gas are equal on both sides (e.g., H₂ + I₂ ⇌ 2HI: 2 mol gas each side), pressure has no effect.',
          B: 'The side with MORE moles of gas would INCREASE pressure — which opposes the direction the system needs to shift to reduce pressure. Le Chatelier\'s Principle predicts the system shifts to OPPOSE the change → fewer moles (lower pressure).',
    },
    teachingPoint: 'Le Chatelier\'s perturbations: (1) Concentration: add reactant → shift right; remove product → shift right; (2) Pressure: increase → shift toward fewer gas moles; decrease → shift toward more gas moles; (3) Temperature: increase → shift toward endothermic (absorbs heat); decrease → shift toward exothermic; (4) Catalyst: no effect on equilibrium position — only on rate of reaching equilibrium. Inert gas added at constant volume: no effect (partial pressures unchanged). Inert gas added at constant pressure: volume increases → partial pressures decrease → shifts toward more gas moles.',
    relatedTopics: ['Le Chatelier Principle', 'pressure effect equilibrium', 'fewer moles gas', 'equilibrium shift', 'Haber process'],
  },
  {
    id: 'mcat4-cp-047',
    sectionId: 'chem-phys',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Chemistry',
    contentCategory: 'Organic chemistry',
    foundationalConcept: 'FC 5',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    question: 'Which amino acid contains a sulfur atom in its side chain and can form disulfide bonds?',
    choices: [
      { label: 'A', text: 'Serine' },
      { label: 'B', text: 'Methionine' },
      { label: 'C', text: 'Cysteine' },
      { label: 'D', text: 'Threonine' },
    ],
    correctAnswer: 'C',
    explanation: 'Cysteine (Cys, C) contains a thiol (−SH) side chain. Two cysteine residues can be oxidized to form a disulfide bond (−S−S−): Cys−SH + HS−Cys → Cys−S−S−Cys + 2H⁺ + 2e⁻. Disulfide bonds stabilize tertiary and quaternary protein structure. C is correct. B — methionine also contains sulfur (as a thioether, −S−CH₃) but does NOT form disulfide bonds (thioether is not easily oxidized to a bond). A — serine has a hydroxyl (−OH) side chain (no sulfur). D — threonine also has a hydroxyl group (no sulfur).',
    wrongAnswerExplanations: {
      A: 'Serine has a hydroxymethyl side chain (−CH₂OH). It contains oxygen, not sulfur. Serine participates in phosphorylation and ester bond formation, not disulfide bonds.',
      B: 'Methionine contains sulfur (thioether: −CH₂CH₂SCH₃) but the thioether sulfur is not in the −SH (thiol) form — it cannot readily form disulfide bonds. Methionine is often the initiator methionine (start codon AUG).',
      D: 'Threonine has a hydroxyl side chain (−CHOH−CH₃). Contains oxygen, not sulfur. Threonine can be phosphorylated at the hydroxyl group.',
    },
    teachingPoint: 'Sulfur-containing amino acids: Cysteine (−SH thiol) → disulfide bonds (oxidation); Methionine (−SCH₃ thioether) → start codon, methylation reactions. Disulfide bonds: covalent cross-links in tertiary/quaternary structure. Reduction of disulfide bonds: β-mercaptoethanol (BME) or DTT (dithiothreitol) + heat → disrupts disulfide bonds → denatures protein. Disulfide bonds are important in extracellular proteins (antibodies, collagen, insulin) — reducing environment inside cells keeps −SH groups reduced.',
    relatedTopics: ['cysteine disulfide bond', 'thiol SH', 'protein structure stabilization', 'sulfur amino acids', 'methionine vs cysteine'],
  },
  {
    id: 'mcat4-cp-048',
    sectionId: 'chem-phys',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Chemistry',
    contentCategory: 'General chemistry',
    foundationalConcept: 'FC 5',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    question: 'A weak acid HA has pKa = 5. What fraction of HA is in its deprotonated (A⁻) form at pH 7?',
    choices: [
      { label: 'A', text: 'About 1% deprotonated' },
      { label: 'B', text: 'About 50% deprotonated' },
      { label: 'C', text: 'About 99% deprotonated' },
      { label: 'D', text: 'About 10% deprotonated' },
    ],
    correctAnswer: 'C',
    explanation: 'Henderson-Hasselbalch: pH = pKa + log([A⁻]/[HA]) → 7 = 5 + log([A⁻]/[HA]) → log([A⁻]/[HA]) = 2 → [A⁻]/[HA] = 100. So [A⁻] is 100× [HA]. Fraction deprotonated = [A⁻]/([A⁻] + [HA]) = 100/(100+1) ≈ 99%. C is correct. When pH is 2 units above pKa, ~99% of the acid is in the conjugate base (deprotonated) form. B — 50% occurs when pH = pKa = 5. A — 1% occurs when pH = pKa − 2 = 3 (90% protonated). D — 10% deprotonated occurs when pH = pKa − 1 = 4.',
    wrongAnswerExplanations: {
      A: '~1% deprotonated (99% protonated) occurs when pH = pKa − 2 = 3, not pH 7. At pH 7 (2 units ABOVE pKa = 5), the acid is mostly deprotonated.',
      B: '50% deprotonated occurs when pH = pKa = 5. At pH 7 (above pKa), more than half is deprotonated.',
      D: '~10% deprotonated occurs when pH = pKa − 1 = 4. At pH 7 = pKa + 2, [A⁻]/[HA] = 100 → ~99% deprotonated.',
    },
    teachingPoint: 'Henderson-Hasselbalch and ionization: at pH = pKa: 50% ionized. At pH = pKa + 1: 91% ionized (90:10 ratio). At pH = pKa + 2: 99% ionized (100:1 ratio). Rule: each 1 unit above pKa = 10× more deprotonated. Clinical: drug ionization determines absorption. Weak acids (aspirin, pKa = 3.5) are mostly un-ionized in stomach (pH 2) → lipid-soluble → absorbed. In blood (pH 7.4): mostly ionized → cannot re-enter cells easily (ion trapping).',
    relatedTopics: ['Henderson-Hasselbalch ionization', 'fraction deprotonated', 'pH vs pKa', '99% deprotonated', 'acid-base equilibrium'],
  },
  {
    id: 'mcat4-cp-049',
    sectionId: 'chem-phys',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Physics',
    contentCategory: 'Physics',
    foundationalConcept: 'FC 4',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    question: 'A magnetic force on a moving charged particle is maximized when the velocity of the particle is:',
    choices: [
      { label: 'A', text: 'Parallel to the magnetic field' },
      { label: 'B', text: 'Anti-parallel (opposite) to the magnetic field' },
      { label: 'C', text: 'Perpendicular to the magnetic field' },
      { label: 'D', text: 'The magnetic force does not depend on direction' },
    ],
    correctAnswer: 'C',
    explanation: 'The magnetic force on a charged particle: F = qv × B (cross product). F = qvB sinθ, where θ is the angle between v and B. Force is maximized when sinθ = 1 → θ = 90° (perpendicular). C is correct. When v is parallel or anti-parallel to B (θ = 0° or 180°): sinθ = 0 → F = 0 (no force). This is why particles moving parallel to a magnetic field are not deflected.',
    wrongAnswerExplanations: {
      A: 'Parallel (θ = 0°): sin(0°) = 0 → F = qvB(0) = 0. No magnetic force on particles moving parallel to B.',
      B: 'Anti-parallel (θ = 180°): sin(180°) = 0 → F = 0. No force on particles moving anti-parallel to B.',
      D: 'The magnetic force depends critically on the angle between velocity and field (F = qvB sinθ). It varies from 0 (parallel) to maximum (perpendicular).',
    },
    teachingPoint: 'Magnetic force: F = qvB sinθ. Direction: perpendicular to both v and B (right-hand rule). Perpendicular force → circular motion (centripetal force): qvB = mv²/r → r = mv/(qB) (cyclotron radius). No work done by magnetic force (always perpendicular to motion → F·v = 0 → no change in KE → speed unchanged). Applications: mass spectrometry (r = mv/(qB) → separates ions by mass/charge ratio); cyclotron (accelerates particles); MRI (uses magnetic fields and RF pulses).',
    relatedTopics: ['magnetic force', 'F = qvB sinθ', 'perpendicular maximum force', 'cross product', 'Lorentz force'],
  },
  {
    id: 'mcat4-cp-050',
    sectionId: 'chem-phys',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Chemistry',
    contentCategory: 'General chemistry',
    foundationalConcept: 'FC 4',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    question: 'According to VSEPR theory, which molecule has a bent (V-shaped) molecular geometry?',
    choices: [
      { label: 'A', text: 'CO₂' },
      { label: 'B', text: 'BF₃' },
      { label: 'C', text: 'H₂O' },
      { label: 'D', text: 'CH₄' },
    ],
    correctAnswer: 'C',
    explanation: 'VSEPR: molecular geometry depends on electron domains around the central atom. H₂O: 2 bonding pairs + 2 lone pairs on O → 4 electron domains (tetrahedral electron geometry) → bent molecular geometry (two lone pairs occupy more space, compressing H-O-H bond angle to ~104.5°). CO₂: 2 double bonds (2 electron domains) → linear. BF₃: 3 bonding pairs (3 domains, no lone pairs) → trigonal planar. CH₄: 4 bonding pairs → tetrahedral. C is correct.',
    wrongAnswerExplanations: {
      A: 'CO₂ is linear. Carbon has 2 double bonds (treated as 2 electron domains in VSEPR), giving 180° bond angle. No lone pairs on C → no distortion.',
      B: 'BF₃ is trigonal planar. Boron has 3 bonding pairs, no lone pairs → 120° bond angles, flat geometry. BF₃ is an exception to the octet rule (6 electrons on B).',
      D: 'CH₄ is tetrahedral. Carbon has 4 bonding pairs, no lone pairs → 109.5° bond angles, 3D tetrahedral geometry.',
    },
    teachingPoint: 'VSEPR molecular geometries: 2 domains = linear; 3 = trigonal planar (no LP) or bent (1 LP); 4 = tetrahedral (no LP), trigonal pyramidal (1 LP), or bent (2 LP); 5 = trigonal bipyramidal (no LP) → various with LP; 6 = octahedral (no LP). Lone pairs occupy more space than bonding pairs → compress bond angles: H₂O has 4 electron domains (tetrahedral electron geometry) but 2 LP → bent molecular geometry, ~104.5°. NH₃: 4 domains, 1 LP → trigonal pyramidal, ~107°.',
    relatedTopics: ['VSEPR', 'bent molecular geometry', 'water geometry', 'lone pair effect', 'molecular shape'],
  },
  {
    id: 'mcat4-cp-051',
    sectionId: 'chem-phys',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Chemistry',
    contentCategory: 'Organic chemistry',
    foundationalConcept: 'FC 5',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    question: 'Which reaction converts a primary alcohol to an aldehyde (and NOT over-oxidizes to a carboxylic acid)?',
    choices: [
      { label: 'A', text: 'PCC (pyridinium chlorochromate) in CH₂Cl₂' },
      { label: 'B', text: 'KMnO₄ (acidic)' },
      { label: 'C', text: 'K₂Cr₂O₇ in H₂SO₄' },
      { label: 'D', text: 'CrO₃ in aqueous H₂SO₄ (Jones reagent)' },
    ],
    correctAnswer: 'A',
    explanation: 'PCC (pyridinium chlorochromate) is a mild oxidizing agent in anhydrous conditions (CH₂Cl₂). It oxidizes: primary alcohol → aldehyde (stops here — anhydrous conditions prevent further oxidation to carboxylic acid); secondary alcohol → ketone. A is correct. A, C, D — KMnO₄ (acidic), K₂Cr₂O₇/H₂SO₄, and Jones reagent (CrO₃/H₂SO₄) are strong oxidants in aqueous media → oxidize primary alcohols all the way to carboxylic acids; secondary alcohols → ketones.',
    wrongAnswerExplanations: {
          C: 'K₂Cr₂O₇/H₂SO₄ (dichromate in acidic aqueous solution) oxidizes primary alcohols to carboxylic acids. Over-oxidizes past aldehyde.',
      D: 'Jones reagent (CrO₃/H₂SO₄/acetone) oxidizes primary alcohols to carboxylic acids and secondary alcohols to ketones. It is too strong for selective aldehyde formation.',
          B: 'KMnO₄ (acidic conditions) is a powerful oxidant that oxidizes primary alcohols to carboxylic acids (and cleaves alkenes). It over-oxidizes past aldehyde.',
    },
    teachingPoint: 'Oxidation selectivity: PCC (Corey\'s reagent) = mild, anhydrous → primary alcohol → aldehyde; secondary alcohol → ketone; tertiary alcohol = no reaction. Strong oxidants (KMnO₄, Jones, Cr₂O₇²⁻/H⁺) = primary alcohol → carboxylic acid; secondary → ketone. Key: anhydrous conditions prevent hydration of aldehyde to geminal diol, which would then be oxidized further. Alternative mild oxidants: Swern oxidation, Dess-Martin periodinane (DMP).',
    relatedTopics: ['PCC oxidation', 'primary alcohol to aldehyde', 'selective oxidation', 'chromium oxidants', 'mild oxidation'],
  },
  {
    id: 'mcat4-cp-052',
    sectionId: 'chem-phys',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Physics',
    contentCategory: 'Physics',
    foundationalConcept: 'FC 4',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    question: 'An object on a frictionless inclined plane at 30° to the horizontal has mass 4 kg. What is the component of gravitational force acting along the incline? (g = 10 m/s²)',
    choices: [
      { label: 'A', text: '20 N (parallel to incline, down the slope)' },
      { label: 'B', text: '34.6 N (perpendicular to incline)' },
      { label: 'C', text: '40 N (total weight)' },
      { label: 'D', text: '34.6 N (parallel to incline, down the slope)' },
    ],
    correctAnswer: 'A',
    explanation: 'Weight W = mg = 4 × 10 = 40 N (straight down). Component along incline (parallel, down the slope) = W sin θ = 40 × sin 30° = 40 × 0.5 = 20 N. Component perpendicular to incline (normal to surface) = W cos θ = 40 × cos 30° = 40 × 0.866 = 34.6 N. A is correct — 20 N along the incline. B — 34.6 N is the normal force component (perpendicular). C — 40 N is the total weight. D — 34.6 N is perpendicular, not parallel.',
    wrongAnswerExplanations: {
      B: '34.6 N = W cos 30° — this is the component PERPENDICULAR to the incline (normal force magnitude), not parallel to it.',
      C: '40 N is the total weight (vertical). The component along the incline is W sinθ = 40 × 0.5 = 20 N.',
      D: 'W sin 30° = 20 N (along incline), not 34.6 N. 34.6 N = W cos 30° (perpendicular to incline).',
    },
    teachingPoint: 'Inclined plane force decomposition: along incline = mg sinθ (causes acceleration down the slope). Perpendicular to incline = mg cosθ (balanced by normal force N). Acceleration along frictionless incline: a = g sinθ. With friction: a = g(sinθ − μcosθ). At 30°: sin30° = 0.5, cos30° = √3/2 ≈ 0.866. Memory: sinθ is the smaller component for θ < 45°; cosθ is larger for θ < 45°.',
    relatedTopics: ['inclined plane', 'force components', 'mg sinθ', 'normal force', 'frictionless incline'],
  },
  {
    id: 'mcat4-cp-053',
    sectionId: 'chem-phys',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Chemistry',
    contentCategory: 'General chemistry',
    foundationalConcept: 'FC 5',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    question: 'The intermolecular force responsible for the unusually high boiling point of water compared to other small molecules (e.g., H₂S) is:',
    choices: [
      { label: 'A', text: 'London dispersion forces' },
      { label: 'B', text: 'Dipole-dipole interactions' },
      { label: 'C', text: 'Hydrogen bonding' },
      { label: 'D', text: 'Ionic interactions' },
    ],
    correctAnswer: 'C',
    explanation: 'Water has an anomalously high boiling point (100°C) compared to other molecules of similar mass (H₂S bp = −60°C; NH₃ bp = −33°C). The key difference is hydrogen bonding: water\'s two O−H groups form hydrogen bonds with neighboring water molecules (O is highly electronegative; H is partially positive; the lone pairs on O accept H-bonds). Hydrogen bonding requires H bonded to N, O, or F (high electronegativity + lone pairs) and is the strongest intermolecular force in water. C is correct. A — London forces exist in all molecules but are weak (dominant in non-polar molecules). B — dipole-dipole exists in polar molecules, but hydrogen bonding (a special case of dipole-dipole with H bonded to N/O/F) is much stronger. D — ionic interactions are between ions (not present in molecular water).',
    wrongAnswerExplanations: {
      A: 'London dispersion forces are present in all molecules (due to instantaneous dipoles) but are relatively weak for small molecules. They do not explain why water has a higher boiling point than H₂S (which has only London forces + dipole-dipole).',
      B: 'Water is polar and has dipole-dipole interactions. But hydrogen bonding is a special case of dipole-dipole that is much stronger (H directly bonded to electronegative N, O, or F allows partial proton transfer). The distinguishing feature is H-bonding.',
      D: 'Ionic interactions are electrostatic attractions between full positive and negative charges (ions). Water is a molecular compound — it has no free ions in pure form. NaCl, MgO are ionic.',
    },
    teachingPoint: 'Intermolecular force strength (weakest to strongest): London dispersion < dipole-dipole < hydrogen bonding < ion-dipole < ionic/covalent. H-bond criteria: H bonded to N, O, or F (donor); lone pair on N, O, or F of another molecule (acceptor). Water: 2 donors (O−H groups) + 2 acceptors (lone pairs on O) → 4 H-bonds per molecule → network → high bp, surface tension, capillary action. DNA base pairing uses H-bonds (A-T: 2 H-bonds; G-C: 3 H-bonds).',
    relatedTopics: ['hydrogen bonding', 'water boiling point', 'intermolecular forces', 'H-bond criteria N O F', 'anomalous water properties'],
  },
  {
    id: 'mcat4-cp-054',
    sectionId: 'chem-phys',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Chemistry',
    contentCategory: 'Organic chemistry',
    foundationalConcept: 'FC 5',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    question: 'The E/Z (cis/trans) isomerism in alkenes arises because of:',
    choices: [
      { label: 'A', text: 'Free rotation around the C=C double bond' },
      { label: 'B', text: 'Restricted rotation around the C=C double bond due to the pi bond' },
      { label: 'C', text: 'The presence of a chiral center on the double bond carbons' },
      { label: 'D', text: 'Electronegativity differences between substituents' },
    ],
    correctAnswer: 'B',
    explanation: 'The C=C double bond consists of a sigma bond (free rotation would be possible) plus a pi bond (formed by lateral overlap of p orbitals). Rotation around the C=C axis would break the pi bond (very high energy barrier ~65 kcal/mol). This restricted rotation locks substituents in fixed spatial positions — cis (Z: same groups on same side) and trans (E: higher priority groups on opposite sides) isomers are distinct compounds that cannot interconvert at room temperature. B is correct. A — free rotation exists around single bonds (C−C), producing conformational isomers that interconvert rapidly. C — chirality is a different type of stereoisomerism (requires 4 different groups on sp3 carbon). D — electronegativity differences determine polarity, not geometric isomerism.',
    wrongAnswerExplanations: {
      A: 'Free rotation occurs around SINGLE bonds (C−C), producing conformational isomers (e.g., staggered vs. eclipsed) that rapidly interconvert. C=C double bonds have RESTRICTED rotation due to the pi bond.',
      C: 'Chirality (R/S configuration) arises at sp3 carbons bearing four different substituents. E/Z isomerism arises at sp2 carbons (double bond carbons) due to restricted rotation — different concept.',
      D: 'Electronegativity differences create polarity (bond dipoles) but do not cause geometric isomerism. E/Z isomerism exists even between carbon-only substituents (e.g., 2-butene: Z = cis, both CH₃ same side).',
    },
    teachingPoint: 'Geometric isomerism requirements: (1) restricted rotation (C=C or ring); (2) each sp2 carbon must have two DIFFERENT substituents. E/Z designation uses CIP priorities (unlike cis/trans which uses similar groups): Z = zusammen (together, higher priority groups same side); E = entgegen (opposite, higher priority groups opposite sides). Examples: (Z)-2-butene = cis; (E)-2-butene = trans. Rings: cis/trans also applies (substituents same or opposite face of ring).',
    relatedTopics: ['E/Z isomerism', 'geometric isomers', 'restricted rotation pi bond', 'cis trans alkenes', 'sp2 carbon'],
  },
  {
    id: 'mcat4-cp-055',
    sectionId: 'chem-phys',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Physics',
    contentCategory: 'Physics',
    foundationalConcept: 'FC 4',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    question: 'A simple pendulum has a period T = 2π√(L/g). If the length is quadrupled, how does the period change?',
    choices: [
      { label: 'A', text: 'Period doubles (T → 2T)' },
      { label: 'B', text: 'Period quadruples (T → 4T)' },
      { label: 'C', text: 'Period halves (T → T/2)' },
      { label: 'D', text: 'Period is unchanged' },
    ],
    correctAnswer: 'A',
    explanation: 'T = 2π√(L/g). If L → 4L: T_new = 2π√(4L/g) = 2π × 2 × √(L/g) = 2T. Period doubles when length quadruples (because T ∝ √L). A is correct. B — period would quadruple only if T ∝ L (linear), not √L. C — period halves when length is reduced by a factor of 4. D — period changes when length changes (T ∝ √L).',
    wrongAnswerExplanations: {
      B: 'T ∝ √L, not T ∝ L. Quadrupling L gives T ∝ √(4L) = 2√L = 2T (doubles, not quadruples).',
      C: 'Halving the period would require reducing length to L/4 (inverse: T_new = 2π√(L/4/g) = T/2). Quadrupling L gives T_new = 2T (doubles, not halves).',
      D: 'Period depends on length L (and g). Changes in L change T. Only pendulum mass does NOT affect T (period is mass-independent).',
    },
    teachingPoint: 'Pendulum period: T = 2π√(L/g). T is independent of mass and amplitude (for small angles). T ∝ √L: to double T, need L × 4. T ∝ 1/√g: higher gravity → shorter period (faster pendulum). On the Moon (g_moon = g/6): T_moon = 2π√(L/g_moon) = 2π√(6L/g) = √6 × T_earth ≈ 2.45 × T_earth. Applications: grandfather clock (adjusting rod length tunes period); seismometer (pendulum detects ground motion).',
    relatedTopics: ['pendulum period', 'T = 2π√(L/g)', 'period vs length', 'simple pendulum', 'quadruple length double period'],
  },
  {
    id: 'mcat4-cp-056',
    sectionId: 'chem-phys',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Chemistry',
    contentCategory: 'General chemistry',
    foundationalConcept: 'FC 4',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    question: 'An element has atomic number 17 and mass number 35. How many protons, neutrons, and electrons does a neutral atom have?',
    choices: [
      { label: 'A', text: '17 protons, 18 neutrons, 17 electrons' },
      { label: 'B', text: '18 protons, 17 neutrons, 18 electrons' },
      { label: 'C', text: '17 protons, 35 neutrons, 17 electrons' },
      { label: 'D', text: '35 protons, 17 neutrons, 35 electrons' },
    ],
    correctAnswer: 'A',
    explanation: 'Atomic number (Z) = number of protons = 17 (chlorine). Mass number (A) = protons + neutrons = 35. Neutrons = A − Z = 35 − 17 = 18. Neutral atom: electrons = protons = 17. A is correct. B — atomic number 17, not 18. C — neutrons = A − Z = 35 − 17 = 18, not 35. D — protons = Z = 17, not 35 (mass number).',
    wrongAnswerExplanations: {
      B: 'Atomic number defines number of protons (17 for chlorine, not 18). 18 protons = argon. Protons = atomic number = 17.',
      C: 'Neutrons = A − Z = 35 − 17 = 18, not 35. The mass number (35) equals protons (17) PLUS neutrons (18).',
      D: 'Protons = atomic number = 17. The mass number (35) is NOT the number of protons — it is the sum of protons and neutrons.',
    },
    teachingPoint: 'Atomic composition: Z (atomic number) = protons = determines the element. A (mass number) = protons + neutrons. Neutrons = A − Z. Neutral atom: electrons = protons = Z. Ions: cation (lost electrons): e⁻ < protons. Anion (gained electrons): e⁻ > protons. Isotopes: same Z, different A (same element, different neutron count). ³⁵Cl (18 neutrons) and ³⁷Cl (20 neutrons) are chlorine isotopes.',
    relatedTopics: ['atomic number protons', 'mass number', 'neutrons A-Z', 'neutral atom electrons', 'isotopes'],
  },
  {
    id: 'mcat4-cp-057',
    sectionId: 'chem-phys',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Chemistry',
    contentCategory: 'Organic chemistry',
    foundationalConcept: 'FC 5',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    question: 'The IR absorption for a carbonyl (C=O) stretch appears near 1700 cm⁻¹. An amide C=O stretch appears at a lower wavenumber (~1650 cm⁻¹) than an acid chloride C=O stretch (~1800 cm⁻¹). Which best explains this trend?',
    choices: [
      { label: 'A', text: 'Amides are more electronegative than acid chlorides, weakening the C=O bond' },
      { label: 'B', text: 'Amides absorb at lower wavenumber because amides have higher molecular weight' },
      { label: 'C', text: 'Acid chlorides absorb at higher wavenumber because Cl is larger and increases the reduced mass' },
      { label: 'D', text: 'The nitrogen lone pair in amides donates electron density into the C=O (resonance), reducing C=O bond order and lowering the stretching frequency; the electron-withdrawing Cl in acid chlorides increases C=O bond order and raises the frequency' },
    ],
    correctAnswer: 'D',
    explanation: 'IR stretching frequency relates to bond strength (force constant k) and reduced mass μ: ν ∝ √(k/μ). For the C=O stretch, changes in bond order (k) dominate for the same pair of atoms. Amide: nitrogen lone pair resonates into C=O (N donates → C=O has partial single bond character → lower bond order → lower k → lower ν). Acid chloride: Cl is electron-withdrawing by induction (withdraws from C) → C becomes more electrophilic → C=O is strengthened slightly → higher k → higher ν. D correctly explains both trends via electronic effects on bond order. A — electronegativity is not the correct mechanism here. C — reduced mass for C=O stretch involves only C and O (not Cl, which is on the adjacent carbon). D — molecular weight is irrelevant to the specific C=O stretching frequency.',
    wrongAnswerExplanations: {
      A: 'Electronegativity of N vs. Cl alone doesn\'t directly explain the trend. The mechanism is resonance donation by N lone pair INTO the C=O (reduces C=O bond order) vs. inductive withdrawal by Cl (slightly strengthens C=O through electron withdrawal from C).',
      C: 'The reduced mass in the C=O stretching vibration involves only C and O (diatomic approximation for the stretch). The substituents affect bond order (k), not the reduced mass of the C=O unit.',
          B: 'IR stretching frequency depends on bond strength (k) and reduced mass of the two bonded atoms, not molecular weight of the whole molecule. Molecular weight affects only the number of atoms, not the specific bond vibration frequency.',
          
    },
    teachingPoint: 'IR carbonyl stretch trends: higher ν (stronger C=O) → acid chloride > anhydride > ester > ketone > aldehyde > amide. Rule: electron donation into C=O (N lone pair in amide, O lone pair in ester but less than N) → lowers C=O bond order → lower ν. Electron withdrawal from C (Cl induction → C more positive → C=O stronger) → higher ν. Ring strain (cyclic ketones) → higher ν. Conjugation (α,β-unsaturated ketone) → lower ν (extends resonance to include C=O). Hydrogen bonding → lower ν (broad peak).',
    relatedTopics: ['IR carbonyl stretch', 'C=O frequency', 'amide vs acid chloride', 'resonance effect IR', 'bond order and wavenumber'],
  },
  {
    id: 'mcat4-cp-058',
    sectionId: 'chem-phys',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Physics',
    contentCategory: 'Physics',
    foundationalConcept: 'FC 4',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    question: 'A projectile is launched horizontally at 20 m/s from a height of 45 m. How long does it take to reach the ground? (g = 10 m/s²)',
    choices: [
      { label: 'A', text: '2.25 s' },
      { label: 'B', text: '3.0 s' },
      { label: 'C', text: '4.5 s' },
      { label: 'D', text: '9.0 s' },
    ],
    correctAnswer: 'B',
    explanation: 'Horizontal launch: vertical initial velocity = 0. Vertical motion: h = ½gt² → 45 = ½(10)t² = 5t² → t² = 9 → t = 3 s. B is correct. The horizontal velocity (20 m/s) does not affect the time to fall — horizontal and vertical motions are independent. A — 2.25 s would require 5(2.25)² = 25.3 m, not 45 m. C — 4.5 s would require 5(4.5)² = 101 m. D — 9 s would require 5(81) = 405 m.',
    wrongAnswerExplanations: {
      A: 't = 2.25 s: h = ½(10)(2.25)² = 5(5.06) ≈ 25.3 m ≠ 45 m.',
      C: 't = 4.5 s: h = 5(4.5)² = 5(20.25) ≈ 101 m ≠ 45 m.',
      D: 't = 9.0 s: h = 5(81) = 405 m ≠ 45 m. Also, the horizontal initial velocity of 20 m/s is irrelevant to vertical fall time.',
    },
    teachingPoint: 'Projectile motion: horizontal and vertical components are independent. Horizontal: x = v₀ₓt (constant velocity, no acceleration). Vertical: y = v₀ᵧt + ½gt² (free fall). For horizontal launch: v₀ᵧ = 0 → h = ½gt² → t = √(2h/g). Range = v₀ₓ × t. The 20 m/s horizontal speed determines range (20 × 3 = 60 m) but NOT time of flight.',
    relatedTopics: ['projectile motion', 'horizontal launch', 'time of flight', 'free fall time', 'independent components'],
  },
  {
    id: 'mcat4-cp-059',
    sectionId: 'chem-phys',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Chemistry',
    contentCategory: 'General chemistry',
    foundationalConcept: 'FC 5',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    question: 'Colligative properties depend on the number of solute particles, not their identity. Which of the following does NOT contribute to colligative property effects?',
    choices: [
      { label: 'A', text: 'Boiling point elevation' },
      { label: 'B', text: 'Freezing point depression' },
      { label: 'C', text: 'The color of the solution' },
      { label: 'D', text: 'Osmotic pressure' },
    ],
    correctAnswer: 'C',
    explanation: 'Colligative properties: boiling point elevation (ΔTb = Kb × m × i), freezing point depression (ΔTf = Kf × m × i), osmotic pressure (π = iMRT), and vapor pressure lowering (Raoult\'s Law). All depend on solute concentration and the van\'t Hoff factor i (number of particles), but NOT on the identity or chemical nature of the solute. The color of the solution depends on which wavelengths of light the solute absorbs — this is a property of the solute\'s molecular structure (identity), not a colligative property. C is correct.',
    wrongAnswerExplanations: {
      A: 'Boiling point elevation IS a colligative property (ΔTb = Kb × m × i). It depends on solute concentration and i — not on the specific nature of the solute.',
      B: 'Freezing point depression IS a colligative property (ΔTf = Kf × m × i). It is why salt is put on icy roads (NaCl → 2 particles → greater FPD than non-electrolyte) and why antifreeze (ethylene glycol) works.',
      D: 'Osmotic pressure IS a colligative property (π = iMRT). It is why red blood cells shrink in hypertonic solution (water leaves cell by osmosis) and swell in hypotonic solution.',
    },
    teachingPoint: 'Colligative properties: the "big 4" — VP lowering, BP elevation, FP depression, osmotic pressure. All depend on solute mole fraction or molality × i (van\'t Hoff factor). i = 1 for non-electrolytes; i = 2 for NaCl, KBr, MgSO₄; i = 3 for CaCl₂, MgCl₂; (with full dissociation). Color, odor, reactivity, and spectroscopic properties are identity-dependent — not colligative. Clinical: hypertonic saline draws fluid out of edematous tissue (osmotic effect).',
    relatedTopics: ['colligative properties', 'non-colligative', 'boiling point elevation', 'freezing point depression', 'osmotic pressure'],
  },
]
