import type { MCATQuestion } from '../types'

// Form 4 P/S — Discrete questions (IDs mcat4-ps-052 through mcat4-ps-059)

export const psDiscretes4: MCATQuestion[] = [
  {
    id: 'mcat4-ps-052',
    sectionId: 'psych-soc',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Psychology',
    contentCategory: 'Sensation and perception',
    foundationalConcept: 'FC 6',
    scientificSkill: 'Skill 1',
    difficulty: 'medium',
    question: 'Signal detection theory distinguishes between sensitivity (d\') and response criterion (β). A radiologist who increases β (raises their criterion) will experience:',
    choices: [
      { label: 'A', text: 'More hits and more false alarms' },
      { label: 'B', text: 'Fewer false alarms but also fewer hits (more misses)' },
      { label: 'C', text: 'Improved sensitivity (d\') with no change in hit rate' },
      { label: 'D', text: 'More correct rejections and more hits simultaneously' },
    ],
    correctAnswer: 'B',
    explanation: 'Raising the criterion (β) means requiring stronger signal evidence before saying "yes." This simultaneously reduces false alarms (saying yes to noise) AND reduces hits (saying yes to real signals) — more misses. The sensitivity (d\') is unchanged; only the decision strategy shifts. B is correct. A = lowering criterion. C — d\' changes with signal/noise overlap, not criterion shift. D — hits and correct rejections move in opposite directions when criterion shifts.',
    wrongAnswerExplanations: {
      A: 'More hits AND more false alarms would result from LOWERING the criterion (less stringent standard — say yes more often). Raising criterion has the opposite effect.',
      C: 'Changing β (criterion) does not change d\' (sensitivity). Sensitivity is a property of the signal-noise overlap, not of the decision threshold.',
      D: 'Hits (correct signal detection) and correct rejections (correctly rejecting noise) trade off against each other. More correct rejections = more conservative criterion = fewer hits.',
    },
    teachingPoint: 'Signal Detection Theory (SDT): Separates sensitivity (d\' = how well signal can be discriminated from noise) from criterion (β = decision threshold for responding "yes"). Outcomes: Hit (signal present, said yes), Miss (signal present, said no), False alarm (noise, said yes), Correct rejection (noise, said no). Conservative criterion (high β): few false alarms, many misses. Liberal criterion (low β): many hits, many false alarms. d\' is invariant across criterion shifts. Clinical applications: mammography (liberal → more biopsies; conservative → miss cancers). Setting criterion involves trade-off between consequences of misses vs. false alarms.',
    relatedTopics: ['signal detection theory', 'response criterion', 'hit rate false alarm', 'd prime sensitivity', 'SDT radiology'],
  },
  {
    id: 'mcat4-ps-053',
    sectionId: 'psych-soc',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Psychology',
    contentCategory: 'Memory',
    foundationalConcept: 'FC 7',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    question: 'The "tip of the tongue" (TOT) phenomenon — knowing a word exists and feeling certain you know it but being unable to retrieve it — is BEST explained by which memory concept?',
    choices: [
      { label: 'A', text: 'Retrieval failure with intact storage — the information is in memory but temporarily inaccessible' },
      { label: 'B', text: 'Encoding failure — the word was never stored in long-term memory' },
      { label: 'C', text: 'Source monitoring error — confusion about where the memory came from' },
      { label: 'D', text: 'Proactive interference — older memories block retrieval of the target word' },
    ],
    correctAnswer: 'A',
    explanation: 'The TOT state involves certainty that the word is stored (often accompanied by partial information — first letter, syllable count) combined with inability to retrieve it. This is classic retrieval failure with intact storage. A is correct. A is ruled out because the person knows the word exists and often knows partial details. C — source monitoring errors involve uncertainty about where something was learned, not inability to produce a known word. D — proactive interference involves older learning blocking newer — not the phenomenon described.',
    wrongAnswerExplanations: {
          C: 'Source monitoring errors: confusing who said something, or whether an event was imagined or real. Not the same as knowing a word exists but being unable to produce it.',
      D: 'Proactive interference: old learning interferes with new learning. TOT is not about interference from other memories — it is retrieval failure for a specific item that is known to be stored.',
          B: 'If encoding had failed, the person would not know the word exists at all — they would have no memory of it. TOT involves knowing a word IS in memory but being temporarily unable to access it.',
    },
    teachingPoint: 'Memory failures types: Encoding failure: information never entered long-term memory (e.g., forgetting what you read while mind-wandering). Storage decay: trace fades over time (less supported by evidence — most forgetting is retrieval failure, not decay). Retrieval failure: cue-dependent forgetting — information is stored but current cues do not activate it. TOT: retrieval failure with partial access (know first letter, syllable count, sounds similar to something). Interference: Proactive: old learning → impairs new retrieval. Retroactive: new learning → impairs old retrieval. TOT resolves when an appropriate cue activates the target (environmental cue, related word).',
    relatedTopics: ['tip of tongue', 'retrieval failure storage', 'memory access', 'cue-dependent forgetting', 'TOT phenomenon'],
  },
  {
    id: 'mcat4-ps-054',
    sectionId: 'psych-soc',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Sociology',
    contentCategory: 'Social stratification',
    foundationalConcept: 'FC 9',
    scientificSkill: 'Skill 1',
    difficulty: 'medium',
    question: 'Max Weber distinguished between class (economic position), status (social honor/prestige), and party (political power). Which scenario BEST illustrates "status inconsistency"?',
    choices: [
      { label: 'A', text: 'A wealthy CEO who also holds political office and is highly respected socially' },
      { label: 'B', text: 'A physician with high income, high occupational prestige, and membership in influential professional organizations' },
      { label: 'C', text: 'A lottery winner who has high income but low occupational prestige and limited social honor' },
      { label: 'D', text: 'A factory worker with low income, low prestige, and minimal political power' },
    ],
    correctAnswer: 'C',
    explanation: 'Status inconsistency occurs when an individual has high standing on one or more dimensions of stratification (class, status, party) but low standing on others. A lottery winner has high economic capital (class) but has not earned occupational prestige (status) and lacks social honor — the dimensions are inconsistent. C is correct. A and B — both have consistent high standing across dimensions (consistent high status). D — consistently low across all dimensions (no inconsistency).',
    wrongAnswerExplanations: {
      A: 'The wealthy CEO with political office and high social respect has high standing across all three dimensions (class, party, status) — this is status consistency, not inconsistency.',
      B: 'High income + high prestige + influential networks = consistently high across Weberian dimensions. No inconsistency.',
      D: 'Low income + low prestige + little power = consistently low across all dimensions. Inconsistency requires high on some, low on others.',
    },
    teachingPoint: 'Weber\'s three dimensions of stratification: Class: economic position (market situation — wages, wealth, assets). Status: social honor, prestige, lifestyle (doctors, clergy, professors may have high status disproportionate to income). Party: organized pursuit of power, influence over political decisions. Status inconsistency: discrepancy between dimensions (nouveau riche — high income, low prestige; black professionals in segregated era — high education/occupation, low racial status). Consequences: stress, frustration, political radicalism (those with inconsistent status seek to reform the system). Contrast with Marx: one-dimensional (class) stratification.',
    relatedTopics: ['Weber stratification', 'class status party', 'status inconsistency', 'multidimensional inequality', 'social honor prestige'],
  },
  {
    id: 'mcat4-ps-055',
    sectionId: 'psych-soc',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Psychology',
    contentCategory: 'Learning',
    foundationalConcept: 'FC 7',
    scientificSkill: 'Skill 1',
    difficulty: 'medium',
    question: 'A rat is trained to press a lever for food every 5th press (fixed ratio schedule). After extinction (no food delivery) begins, which extinction pattern is expected?',
    choices: [
      { label: 'A', text: 'Immediate and complete cessation of lever pressing' },
      { label: 'B', text: 'Gradual, slow reduction in responding over many sessions' },
      { label: 'C', text: 'A brief extinction burst followed by relatively rapid extinction' },
      { label: 'D', text: 'High resistance to extinction — rate of lever pressing remains high for many sessions' },
    ],
    correctAnswer: 'C',
    explanation: 'Fixed ratio (FR) schedules produce high rates of responding with post-reinforcement pauses. Upon extinction, FR-trained animals typically show an extinction burst (temporarily increased responding) followed by relatively rapid cessation — FR schedules are associated with low-to-moderate resistance to extinction. The animal knows that reinforcement comes reliably after a set number of responses, so when reinforcement stops, the animal quickly detects the change and extinction is relatively rapid compared to variable schedules. C is correct. D — high resistance to extinction is characteristic of variable ratio (VR) schedules, not fixed ratio.',
    wrongAnswerExplanations: {
      A: 'Immediate cessation would occur if the rat had never been reinforced. Extinction follows a process — there is typically an extinction burst before cessation.',
      B: 'Slow reduction over many sessions describes variable ratio or variable interval extinction patterns. FR schedules extinguish more rapidly.',
      D: 'High resistance to extinction is the hallmark of VARIABLE RATIO schedules (slot machines). FR schedules have lower resistance to extinction because the predictable ratio makes the absence of reinforcement more easily detectable.',
    },
    teachingPoint: 'Schedules of reinforcement and extinction resistance: Fixed Ratio (FR): high response rate, post-reinforcement pause, relatively rapid extinction. Variable Ratio (VR): highest response rate, no post-reinforcement pause, highest resistance to extinction (cannot predict when next reinforcement will occur). Fixed Interval (FI): scallop pattern (slow → fast near end of interval), moderate resistance. Variable Interval (VI): moderate, steady rate, high resistance to extinction. Extinction burst: initial increase in responding when reinforcement stops → then cessation. VR = gambling (slot machines → high resistance explains why gambling is hard to extinguish). Fixed schedules extinguish faster because predictability allows the animal to detect reinforcement removal.',
    relatedTopics: ['fixed ratio schedule', 'extinction pattern', 'resistance to extinction', 'variable ratio comparison', 'operant conditioning schedules'],
  },
  {
    id: 'mcat4-ps-056',
    sectionId: 'psych-soc',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Psychology',
    contentCategory: 'Language and cognition',
    foundationalConcept: 'FC 7',
    scientificSkill: 'Skill 1',
    difficulty: 'medium',
    question: 'Wernicke\'s aphasia is characterized by:',
    choices: [
      { label: 'A', text: 'Fluent speech with poor comprehension and frequent paraphasias (word substitution errors)' },
      { label: 'B', text: 'Non-fluent speech with good comprehension and word-finding difficulty' },
      { label: 'C', text: 'Inability to produce speech with intact comprehension and reading' },
      { label: 'D', text: 'Difficulty repeating words with intact spontaneous speech and comprehension' },
    ],
    correctAnswer: 'A',
    explanation: 'Wernicke\'s aphasia (receptive aphasia) results from damage to Wernicke\'s area (posterior superior temporal gyrus, BA 22). Hallmarks: fluent speech output (production is intact structurally), severely impaired comprehension, and paraphasias (literal substitutions — "dog" for "cat"; neologisms). A is correct. A = Broca\'s aphasia (non-fluent, good comprehension). C = global aphasia or mutism. D = conduction aphasia (repetition impaired, production and comprehension relatively intact).',
    wrongAnswerExplanations: {
          C: 'Inability to produce speech at all suggests global aphasia, mutism, or severe Broca\'s. Wernicke\'s patients produce fluent (but meaningless) speech.',
      D: 'Difficulty repeating with intact spontaneous speech and comprehension = conduction aphasia (damage to arcuate fasciculus connecting Broca\'s and Wernicke\'s areas). Not Wernicke\'s.',
          B: 'Non-fluent speech + good comprehension + word-finding difficulty = Broca\'s aphasia (anterior, frontal lobe, BA 44/45). Wernicke\'s is in the posterior temporal lobe → fluent speech but impaired comprehension.',
    },
    teachingPoint: 'Language areas: Broca\'s area (BA 44/45, inferior frontal gyrus, left hemisphere): speech production, grammar processing. Lesion → Broca\'s aphasia: non-fluent, telegraphic speech; comprehension relatively intact; "know what they want to say but can\'t say it." Wernicke\'s area (BA 22, posterior superior temporal gyrus): speech comprehension, word selection. Lesion → Wernicke\'s aphasia: fluent, paraphasia-filled speech; severely impaired comprehension; "word salad"; patient unaware of errors. Arcuate fasciculus: connects Broca\'s to Wernicke\'s; lesion → conduction aphasia. Global aphasia: entire perisylvian region damaged → severe production AND comprehension.',
    relatedTopics: ['Wernicke aphasia', 'Broca vs Wernicke', 'fluent aphasia', 'paraphasias', 'language areas brain'],
  },
  {
    id: 'mcat4-ps-057',
    sectionId: 'psych-soc',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Sociology',
    contentCategory: 'Health and illness',
    foundationalConcept: 'FC 9',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    question: 'The sick role (Parsons) includes which of the following obligations and exemptions?',
    choices: [
      { label: 'A', text: 'Exemption from normal social duties AND obligation to seek medical help and work toward recovery' },
      { label: 'B', text: 'Exemption from all social duties permanently, with no obligation to recover' },
      { label: 'C', text: 'Obligation to perform normal duties while seeking care, without exemption from work' },
      { label: 'D', text: 'Obligation to disclose illness publicly and exemption from seeking professional care' },
    ],
    correctAnswer: 'A',
    explanation: 'Parsons\' sick role has four components: (1) Exemption from normal social roles (not expected to go to work, fulfill family duties); (2) Not held responsible for being ill; (3) Obligation to want to get well (sickness is not a desirable state); (4) Obligation to seek competent medical help and cooperate with treatment. A correctly captures exemption from duties + obligation to seek care/recover. B — exemption is temporary, not permanent; obligation to recover is required. C — no exemption contradicts the sick role. D — public disclosure and exemption from care are not components of the sick role.',
    wrongAnswerExplanations: {
      B: 'The sick role exemption is CONDITIONAL and TEMPORARY — contingent on working toward recovery. There is an explicit obligation to recover and cooperate with treatment. Permanent, unconditional exemption would be a violation of the sick role.',
      C: 'The sick role specifically EXEMPTS individuals from normal social obligations (work, family duties). No exemption from work is the opposite of what Parsons describes.',
      D: 'Public disclosure is not a component of the sick role. Obligation to seek professional care is a component — exemption from care contradicts the sick role framework.',
    },
    teachingPoint: 'Parsons\' sick role (functionalist perspective): Four components: (1) Exempt from normal social roles (cannot work); (2) Not blamed for illness; (3) Must want to recover; (4) Must seek medical help and cooperate. Social function: provides a structured way for illness to disrupt society minimally — temporary exemption plus recovery mandate maintains social order. Critiques: applies primarily to acute illness (chronic illness doesn\'t fit — permanent exemption, no "recovery"); ignores power dynamics between doctor and patient; ignores social determinants of health. Alternative: Freidson\'s illness legitimacy theory (some illnesses are more socially legitimate than others).',
    relatedTopics: ['sick role Parsons', 'functionalist health', 'illness exemptions obligations', 'medical sociology', 'temporary exemption recovery'],
  },
  {
    id: 'mcat4-ps-058',
    sectionId: 'psych-soc',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Psychology',
    contentCategory: 'Psychological disorders',
    foundationalConcept: 'FC 7',
    scientificSkill: 'Skill 1',
    difficulty: 'medium',
    question: 'In classical conditioning, "extinction" refers to:',
    choices: [
      { label: 'A', text: 'The permanent destruction of a conditioned response through punishment' },
      { label: 'B', text: 'The elimination of a conditioned response by repeatedly presenting the CS without the UCS' },
      { label: 'C', text: 'The replacement of one conditioned stimulus with another via higher-order conditioning' },
      { label: 'D', text: 'The return of a conditioned response after a rest period — also called spontaneous recovery' },
    ],
    correctAnswer: 'B',
    explanation: 'In classical conditioning, extinction is the process of repeatedly presenting the conditioned stimulus (CS) without the unconditioned stimulus (UCS), leading to progressive weakening and eventual elimination of the conditioned response (CR). B is correct. A — punishment is an operant procedure; extinction in classical conditioning does not involve punishment. C — higher-order conditioning is a separate process (CS1 becomes UCS for CS2). D — spontaneous recovery is the return of an extinguished CR after a rest period — the result of extinction, not extinction itself.',
    wrongAnswerExplanations: {
      A: 'Punishment is an operant conditioning procedure (applies an aversive consequence after a behavior). Classical conditioning extinction involves repeated CS presentation without UCS — no punishment.',
      C: 'Higher-order (second-order) conditioning: an established CS1 is used as an unconditioned stimulus to condition a new CS2. This is a separate process from extinction.',
      D: 'Spontaneous recovery is what HAPPENS AFTER extinction — the extinguished CR reappears after a rest period (demonstrating that extinction doesn\'t permanently erase the association). D describes the phenomenon that extinction produces, not extinction itself.',
    },
    teachingPoint: 'Classical conditioning key processes: Acquisition: CS repeatedly paired with UCS → CR develops. Extinction: CS presented alone (without UCS) → CR weakens and disappears. Spontaneous recovery: after extinction + rest, CR returns at reduced strength. Re-acquisition: after spontaneous recovery, conditioning is faster than original learning (original trace not fully erased). Stimulus generalization: similar stimuli elicit CR (gradient). Stimulus discrimination: only the specific CS elicits CR (not similar stimuli). Theoretical implications: extinction ≠ erasure (CS-UCS association persists; extinction creates new inhibitory learning that competes with original excitatory association).',
    relatedTopics: ['classical conditioning extinction', 'CS without UCS', 'conditioned response elimination', 'spontaneous recovery distinction'],
  },
  {
    id: 'mcat4-ps-059',
    sectionId: 'psych-soc',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Sociology',
    contentCategory: 'Deviance',
    foundationalConcept: 'FC 9',
    scientificSkill: 'Skill 1',
    difficulty: 'medium',
    question: 'Labeling theory (Becker) proposes that deviance is:',
    choices: [
      { label: 'A', text: 'A fixed property of certain acts that are inherently wrong regardless of social context' },
      { label: 'B', text: 'Not a quality of the act itself, but a consequence of the application of rules and labels by those in power' },
      { label: 'C', text: 'Determined solely by the biological predispositions of individuals who commit deviant acts' },
      { label: 'D', text: 'The result of anomie — the breakdown of social norms during rapid social change' },
    ],
    correctAnswer: 'B',
    explanation: 'Howard Becker\'s labeling theory: "Deviance is not a quality of the act a person commits, but rather a consequence of the application of rules and sanctions to an \'offender\' by others." Deviance is created through social labeling by those with power to define norms and apply labels. B is correct. A — essentialism/moral absolutism — labeling theory explicitly rejects this. C — biological determinism is the opposite of labeling theory\'s social constructionist perspective. D — anomie theory (Durkheim, Merton) sees deviance as a breakdown of social norms — different from labeling theory.',
    wrongAnswerExplanations: {
      A: 'Labeling theory is explicitly a social constructionist critique of moral essentialism. The same act (e.g., marijuana use) may be deviant in one social context and not in another — deviance is context-dependent, not a fixed property of the act.',
      C: 'Biological determinism of deviance — favored by some earlier theories (Lombroso) — is precisely what labeling theory opposes. Labeling theory focuses on the social RESPONSE to behavior, not the biological cause of behavior.',
      D: 'Anomie theory (Durkheim: social breakdown; Merton: strain between cultural goals and legitimate means) explains deviance as a response to social strain — not the labeling process. Labeling theory focuses on how labels are applied and their consequences.',
    },
    teachingPoint: 'Labeling theory (Becker, Lemert): Primary deviance: initial deviant act (minor, situational). Secondary deviance: internalization of the deviant label → career of deviance. Deviant career: once labeled, individual is treated as deviant → limits legitimate opportunities → more deviance. "Master status": deviant label overrides all other identities. Moral entrepreneurs (Becker): those who define and enforce norms (police, moral reformers). Critique: overemphasizes labeling, underemphasizes individual agency and initial deviant motivations. Relatedly: Goffman\'s stigma theory — management of "spoiled identity" from deviant labels. Application: mental illness labeling, criminal justice recidivism.',
    relatedTopics: ['labeling theory Becker', 'social construction deviance', 'deviant label secondary deviance', 'master status', 'anomie theory contrast'],
  },
]
