import type { RWQuestion } from './types'

export const f4RwModule2EasyQuestions: RWQuestion[] = [
  // ── Words in Context (4) ─────────────────────────────────────────────────
  {
    id: 'sat-f4-rw-m2e-q01',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-easy',
    domain: 'Craft and Structure',
    skill: 'Words in Context',
    difficulty: 'easy',
    stimulus: 'Because sea turtles travel thousands of miles across open ocean, scientists once assumed their movements were random. New tracking data has shown the opposite: the turtles follow _______ routes, returning to the same nesting beaches year after year.',
    question: 'Which choice completes the text with the most logical and precise word or phrase?',
    choices: [
      { label: 'A', text: 'dangerous' },
      { label: 'B', text: 'brief' },
      { label: 'C', text: 'predictable' },
      { label: 'D', text: 'crowded' },
    ],
    correctAnswer: 'C',
    explanation: '"Predictable" fits the contrast with "random": the turtles return to the same beaches yearly, so their routes can be foreseen.',
    wrongAnswerExplanations: {
      A: '"Dangerous" describes risk, not the regularity the passage emphasizes.',
      B: '"Brief" contradicts the fact that the turtles travel thousands of miles.',
      D: '"Crowded" describes how many turtles share a route, not whether the route is regular.',
    },
  },
  {
    id: 'sat-f4-rw-m2e-q02',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-easy',
    domain: 'Craft and Structure',
    skill: 'Words in Context',
    difficulty: 'easy',
    stimulus: 'The young violinist practiced for hours every day. Her dedication was _______ : even during holidays, she rarely let a day pass without picking up her instrument.',
    question: 'Which choice completes the text with the most logical and precise word or phrase?',
    choices: [
      { label: 'A', text: 'unwavering' },
      { label: 'B', text: 'unusual' },
      { label: 'C', text: 'occasional' },
      { label: 'D', text: 'hesitant' },
    ],
    correctAnswer: 'A',
    explanation: '"Unwavering" means steady and firm, which fits a dedication so consistent that she practiced even on holidays.',
    wrongAnswerExplanations: {
      B: '"Unusual" describes rarity, not the steadiness the example illustrates.',
      C: '"Occasional" means now and then, contradicting daily practice.',
      D: '"Hesitant" means uncertain, the opposite of committed daily practice.',
    },
  },
  {
    id: 'sat-f4-rw-m2e-q03',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-easy',
    domain: 'Craft and Structure',
    skill: 'Words in Context',
    difficulty: 'medium',
    stimulus: 'The city\'s new recycling program was met with _______ from residents: within the first month, participation exceeded every target the planners had set.',
    question: 'Which choice completes the text with the most logical and precise word or phrase?',
    choices: [
      { label: 'A', text: 'indifference' },
      { label: 'B', text: 'confusion' },
      { label: 'C', text: 'suspicion' },
      { label: 'D', text: 'enthusiasm' },
    ],
    correctAnswer: 'D',
    explanation: 'Participation exceeding every target signals a positive, eager response, which "enthusiasm" captures.',
    wrongAnswerExplanations: {
      A: '"Indifference" means a lack of interest, contradicting the high participation.',
      B: '"Confusion" would not explain participation that surpassed targets.',
      C: '"Suspicion" implies distrust, inconsistent with residents eagerly joining.',
    },
  },
  {
    id: 'sat-f4-rw-m2e-q04',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-easy',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'easy',
    stimulus: 'The library stays open late during exam week _______ students often study there until midnight.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choices: [
      { label: 'A', text: ', many' },
      { label: 'B', text: '. Many' },
      { label: 'C', text: ' many' },
      { label: 'D', text: 'many' },
    ],
    correctAnswer: 'B',
    explanation: 'Choice B is correct. The sentence contains two independent clauses, and a period correctly separates them into two complete sentences, avoiding a comma splice or run-on.',
    wrongAnswerExplanations: {
      A: 'Choice A is incorrect. Joining two independent clauses with only a comma creates a comma splice.',
      C: 'Choice C is incorrect. Placing two independent clauses side by side with no punctuation creates a run-on sentence.',
      D: 'Choice D is incorrect. Running the two independent clauses together with no punctuation creates a run-on sentence.',
    },
  },

  // ── Text Structure and Purpose (4) ────────────────────────────────────────
  {
    id: 'sat-f4-rw-m2e-q05',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-easy',
    domain: 'Craft and Structure',
    skill: 'Text Structure and Purpose',
    difficulty: 'easy',
    stimulus: 'Honey never spoils. Archaeologists have found pots of honey in ancient tombs that, after thousands of years, remain perfectly edible. Its low moisture content and natural acidity create conditions in which bacteria cannot grow, allowing honey to last almost indefinitely.',
    question: 'What is the main purpose of the passage?',
    choices: [
      { label: 'A', text: 'To describe how bees produce honey' },
      { label: 'B', text: 'To compare honey with other sweeteners' },
      { label: 'C', text: 'To explain why honey does not spoil' },
      { label: 'D', text: 'To argue that ancient tombs should be preserved' },
    ],
    correctAnswer: 'C',
    explanation: 'The passage states honey never spoils and explains the reasons: low moisture and acidity prevent bacterial growth. Its purpose is to explain this.',
    wrongAnswerExplanations: {
      A: 'The passage does not describe how bees make honey.',
      B: 'No comparison with other sweeteners appears.',
      D: 'The tomb example illustrates honey\'s longevity; the passage is not about preserving tombs.',
    },
  },
  {
    id: 'sat-f4-rw-m2e-q06',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-easy',
    domain: 'Craft and Structure',
    skill: 'Text Structure and Purpose',
    difficulty: 'easy',
    stimulus: 'Public libraries have changed a great deal in recent decades. Once quiet halls devoted mainly to books, many now offer free internet access, meeting rooms, tool-lending programs, and classes for job seekers. For many communities, the library has become a center for far more than reading.',
    question: 'What is the main idea of the passage?',
    choices: [
      { label: 'A', text: 'Modern libraries offer many services beyond lending books' },
      { label: 'B', text: 'Libraries should return to focusing only on books' },
      { label: 'C', text: 'Internet access is the most important service libraries provide' },
      { label: 'D', text: 'Fewer people visit libraries than in the past' },
    ],
    correctAnswer: 'A',
    explanation: 'The passage lists new services — internet, meeting rooms, tool lending, classes — to show that libraries now do much more than lend books.',
    wrongAnswerExplanations: {
      B: 'The passage describes expansion, not a call to return to books alone.',
      C: 'Internet access is one of several services listed, not singled out as most important.',
      D: 'The passage does not discuss visitor numbers.',
    },
  },
  {
    id: 'sat-f4-rw-m2e-q07',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-easy',
    domain: 'Craft and Structure',
    skill: 'Text Structure and Purpose',
    difficulty: 'medium',
    stimulus: 'At first, the gardener assumed the wilting tomato plants needed more water. But adding water only made things worse. It turned out that the soil was already saturated, and the roots were drowning; the plants recovered only once she let the soil dry out.',
    question: 'Which choice best describes the structure of the passage?',
    choices: [
      { label: 'A', text: 'It lists several methods for growing tomatoes in order of importance' },
      { label: 'B', text: 'It compares two gardeners with different watering habits' },
      { label: 'C', text: 'It presents an initial assumption, shows it was mistaken, and reveals the actual cause of the problem' },
      { label: 'D', text: 'It describes the life cycle of a tomato plant from seed to harvest' },
    ],
    correctAnswer: 'C',
    explanation: 'The gardener first assumes the plants need water, discovers that assumption was wrong, and learns the real cause was overwatering — matching option C.',
    wrongAnswerExplanations: {
      A: 'The passage does not list multiple growing methods ranked by importance.',
      B: 'Only one gardener appears; no comparison is made.',
      D: 'The passage addresses a single problem, not the plant\'s full life cycle.',
    },
  },
  {
    id: 'sat-f4-rw-m2e-q08',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-easy',
    domain: 'Craft and Structure',
    skill: 'Text Structure and Purpose',
    difficulty: 'medium',
    stimulus: 'The following is adapted from a short story. The clerk kept the shop exactly as his late father had: the same faded sign, the same jars in the same order, the same brass bell above the door. Customers who had known the father sometimes paused, half expecting to see him behind the counter.',
    question: 'What is the main function of the details about the shop in the text?',
    choices: [
      { label: 'A', text: 'To explain how the shop\'s sales have increased' },
      { label: 'B', text: 'To criticize the clerk for refusing to modernize' },
      { label: 'C', text: 'To describe the products the shop sells' },
      { label: 'D', text: 'To show that the clerk preserves the shop as a tribute to his father' },
    ],
    correctAnswer: 'D',
    explanation: 'The clerk keeps everything "exactly as his late father had," and customers half expect to see the father — details that show the shop is maintained as a tribute to him.',
    wrongAnswerExplanations: {
      A: 'The passage says nothing about sales.',
      B: 'The details are affectionate, not critical of the clerk.',
      C: 'The jars are mentioned, but the point is continuity with the father, not the merchandise.',
    },
  },

  // ── Cross-Text Connections (2) ────────────────────────────────────────────
  {
    id: 'sat-f4-rw-m2e-q09',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-easy',
    domain: 'Craft and Structure',
    skill: 'Cross-Text Connections',
    difficulty: 'medium',
    stimulus: 'Text 1\nHomework helps students learn. By practicing at home, students reinforce what they studied in class and develop habits of independent work. Teachers can also use homework to see which topics students have mastered and which need review.\n\nText 2\nSome educators worry that too much homework does more harm than good. Long assignments can crowd out sleep, family time, and play, especially for younger children. These educators argue that the amount of homework should be limited so that its benefits are not outweighed by its costs.',
    question: 'Based on the texts, both authors would most likely agree that homework',
    choices: [
      { label: 'A', text: 'should be eliminated for all students' },
      { label: 'B', text: 'can affect students, though they weigh its effects differently' },
      { label: 'C', text: 'is equally beneficial for students of all ages' },
      { label: 'D', text: 'has no measurable effect on learning' },
    ],
    correctAnswer: 'B',
    explanation: 'Text 1 stresses homework\'s benefits and Text 2 stresses its potential costs, but both treat homework as something that affects students; they simply weigh those effects differently.',
    wrongAnswerExplanations: {
      A: 'Text 1 supports homework, and Text 2 wants it limited, not eliminated.',
      C: 'Text 2 notes special concerns for younger children, so it does not treat homework as equally beneficial for all ages.',
      D: 'Text 1 says homework helps students learn, so neither author claims it has no effect.',
    },
  },
  {
    id: 'sat-f4-rw-m2e-q10',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-easy',
    domain: 'Craft and Structure',
    skill: 'Cross-Text Connections',
    difficulty: 'medium',
    stimulus: 'Text 1\nElectric cars are better for the environment than gasoline cars because they produce no tailpipe emissions. As more drivers switch to electric vehicles, the air in crowded cities should become noticeably cleaner.\n\nText 2\nElectric cars produce no emissions while driving, but the electricity that charges them must come from somewhere. In regions where power plants burn coal, the pollution is simply moved from the road to the plant. The environmental benefit depends heavily on how the electricity is generated.',
    question: 'How would the author of Text 2 most likely respond to the claim in Text 1 that electric cars are better for the environment?',
    choices: [
      { label: 'A', text: 'By agreeing fully and adding that gasoline cars should be banned' },
      { label: 'B', text: 'By noting that the benefit depends on how the electricity used to charge them is produced' },
      { label: 'C', text: 'By arguing that electric cars produce more tailpipe emissions than gasoline cars' },
      { label: 'D', text: 'By claiming that city air quality cannot be measured' },
    ],
    correctAnswer: 'B',
    explanation: 'Text 2 accepts that electric cars have no tailpipe emissions but stresses that pollution may shift to power plants, so the benefit "depends heavily on how the electricity is generated."',
    wrongAnswerExplanations: {
      A: 'Text 2 qualifies rather than fully endorses Text 1 and does not call for banning gasoline cars.',
      C: 'Text 2 agrees electric cars have no tailpipe emissions, so it would not claim they produce more.',
      D: 'Text 2 does not claim air quality is unmeasurable.',
    },
  },

  // ── Central Ideas and Details (3) ─────────────────────────────────────────
  {
    id: 'sat-f4-rw-m2e-q11',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-easy',
    domain: 'Information and Ideas',
    skill: 'Central Ideas and Details',
    difficulty: 'easy',
    stimulus: 'The Sahara Desert was not always dry. Between roughly 11,000 and 5,000 years ago, a wetter climate covered the region with grasslands, lakes, and abundant wildlife. Rock paintings from this period show people hunting animals such as hippos and crocodiles that could not survive in today\'s desert.',
    question: 'Which choice best states the main idea of the text?',
    choices: [
      { label: 'A', text: 'The Sahara has always been a dry desert' },
      { label: 'B', text: 'Thousands of years ago, the Sahara was a much wetter, greener region' },
      { label: 'C', text: 'Rock paintings are the only record of ancient climates' },
      { label: 'D', text: 'Hippos and crocodiles live in the Sahara today' },
    ],
    correctAnswer: 'B',
    explanation: 'The passage explains that the Sahara was once wet, with grasslands, lakes, and wildlife, supported by rock paintings of animals that need water.',
    wrongAnswerExplanations: {
      A: 'The passage says the opposite: the Sahara "was not always dry."',
      C: 'Rock paintings are mentioned as evidence, not claimed to be the only record of climates.',
      D: 'The passage says those animals "could not survive in today\'s desert."',
    },
  },
  {
    id: 'sat-f4-rw-m2e-q12',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-easy',
    domain: 'Information and Ideas',
    skill: 'Central Ideas and Details',
    difficulty: 'easy',
    stimulus: 'The inventor Garrett Morgan patented an early traffic signal in 1923. Unlike earlier signals, which showed only "stop" and "go," his design added a third position that halted traffic in all directions at once, giving vehicles time to clear the intersection safely before the next direction proceeded.',
    question: 'According to the text, what was distinctive about Morgan\'s traffic signal?',
    choices: [
      { label: 'A', text: 'It was the first signal ever used' },
      { label: 'B', text: 'It added a position that stopped traffic in all directions at once' },
      { label: 'C', text: 'It showed only "stop" and "go"' },
      { label: 'D', text: 'It was designed for use only at night' },
    ],
    correctAnswer: 'B',
    explanation: 'The passage says his design added a third position that halted traffic in all directions to let the intersection clear — the distinctive feature.',
    wrongAnswerExplanations: {
      A: 'The passage refers to "earlier signals," so his was not the first.',
      C: 'Earlier signals showed only "stop" and "go"; Morgan\'s added a third position.',
      D: 'The passage does not say the signal was for nighttime use only.',
    },
  },
  {
    id: 'sat-f4-rw-m2e-q13',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-easy',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'easy',
    stimulus: 'A honeybee communicates the location of food to the rest of the hive by performing a "waggle dance." Through the direction and length of _______ movements, the bee tells the others where to fly.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choices: [
      { label: 'A', text: 'their' },
      { label: 'B', text: 'its' },
      { label: 'C', text: 'our' },
      { label: 'D', text: 'they\'re' },
    ],
    correctAnswer: 'B',
    explanation: 'Choice B is correct. A pronoun must agree with its antecedent in number. The antecedent, "A honeybee," is singular, so the singular possessive pronoun "its" is correct.',
    wrongAnswerExplanations: {
      A: 'Choice A is incorrect. "Their" is plural, but the antecedent "A honeybee" is singular.',
      C: 'Choice C is incorrect. "Our" is a first-person pronoun and does not refer back to "A honeybee."',
      D: 'Choice D is incorrect. "They\'re" is a contraction of "they are," not a possessive pronoun, so it cannot show possession of the movements.',
    },
  },

  // ── Command of Evidence (4) ───────────────────────────────────────────────
  {
    id: 'sat-f4-rw-m2e-q14',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-easy',
    domain: 'Information and Ideas',
    skill: 'Command of Evidence',
    difficulty: 'easy',
    stimulus: 'A student claimed that people remember information better when they write it by hand than when they type it. She wants to support this claim with evidence from a study.',
    question: 'Which finding, if true, would most directly support the student\'s claim?',
    choices: [
      { label: 'A', text: 'Typing notes is faster than writing them by hand' },
      { label: 'B', text: 'Most students prefer to type their notes on a laptop' },
      { label: 'C', text: 'Students who took notes by hand scored higher on a later memory test than students who typed their notes' },
      { label: 'D', text: 'Handwriting and typing require different muscles' },
    ],
    correctAnswer: 'C',
    explanation: 'The claim is that handwriting improves memory. A finding that handwritten note-takers scored higher on a memory test directly supports it.',
    wrongAnswerExplanations: {
      A: 'Typing being faster does not show that handwriting improves memory.',
      B: 'A preference for typing says nothing about which method aids memory.',
      D: 'Using different muscles does not address memory performance.',
    },
  },
  {
    id: 'sat-f4-rw-m2e-q15',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-easy',
    domain: 'Information and Ideas',
    skill: 'Command of Evidence',
    difficulty: 'easy',
    stimulus: 'A gardener wanted to know whether a certain plant grows taller in full sunlight than in shade. She grew seedlings in each condition and measured their average height after eight weeks.',
    graphData: {
      type: 'table',
      title: 'Average Plant Height After 8 Weeks',
      headers: ['Light Condition', 'Average Height (cm)'],
      rows: [
        ['Full sunlight', '34'],
        ['Partial shade', '25'],
        ['Full shade', '16'],
      ],
    },
    question: 'Which choice best uses data from the table to support the idea that more light leads to taller plants?',
    choices: [
      { label: 'A', text: 'Plants in full shade averaged 16 cm, the tallest of the three groups.' },
      { label: 'B', text: 'All three groups reached the same average height.' },
      { label: 'C', text: 'Plants in partial shade averaged taller than those in full sunlight.' },
      { label: 'D', text: 'Plants in full sunlight averaged 34 cm, taller than those in partial shade (25 cm) and full shade (16 cm).' },
    ],
    correctAnswer: 'D',
    explanation: 'The table shows height rising with light: 16 cm in full shade, 25 cm in partial shade, and 34 cm in full sunlight, supporting the idea that more light produces taller plants.',
    wrongAnswerExplanations: {
      A: 'Full shade plants (16 cm) were the shortest, not the tallest.',
      B: 'The three groups had clearly different heights.',
      C: 'Partial-shade plants (25 cm) were shorter than full-sunlight plants (34 cm).',
    },
  },
  {
    id: 'sat-f4-rw-m2e-q16',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-easy',
    domain: 'Information and Ideas',
    skill: 'Command of Evidence',
    difficulty: 'medium',
    stimulus: 'A café owner believed that offering free samples of a new pastry would increase its sales. To test this, she tracked pastry sales during weeks with and without a sample table near the entrance.',
    graphData: {
      type: 'table',
      title: 'Weekly Pastry Sales',
      headers: ['Condition', 'Average Pastries Sold per Day'],
      rows: [
        ['No samples offered', '42'],
        ['Free samples offered', '68'],
      ],
    },
    question: 'Which choice best uses data from the table to support the café owner\'s belief?',
    choices: [
      { label: 'A', text: 'The café sold fewer pastries on days when samples were offered.' },
      { label: 'B', text: 'Pastry sales were the same whether or not samples were offered.' },
      { label: 'C', text: 'On days when free samples were offered, the café sold an average of 68 pastries, compared with 42 on days without samples.' },
      { label: 'D', text: 'The café sold an average of 42 pastries on days when samples were offered.' },
    ],
    correctAnswer: 'C',
    explanation: 'The table shows daily sales rose from 42 without samples to 68 with samples, supporting the belief that free samples increased sales.',
    wrongAnswerExplanations: {
      A: 'Sales rose with samples (68 versus 42), so they did not fall.',
      B: 'The two conditions produced clearly different sales figures.',
      D: 'The 42-pastry average was for days without samples, not with them.',
    },
  },
  {
    id: 'sat-f4-rw-m2e-q17',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-easy',
    domain: 'Information and Ideas',
    skill: 'Command of Evidence',
    difficulty: 'medium',
    stimulus: 'A biologist studying frogs claimed that a nearby pond\'s water quality had improved over the past decade. She based this claim on surveys of the frog population, since frogs are sensitive to pollution and tend to disappear from contaminated water.',
    question: 'Which finding, if true, would most directly support the biologist\'s claim?',
    choices: [
      { label: 'A', text: 'The pond is larger than most others in the region' },
      { label: 'B', text: 'Frogs are found on every continent except Antarctica' },
      { label: 'C', text: 'The biologist has studied frogs for over twenty years' },
      { label: 'D', text: 'The number of frogs living in the pond increased steadily over the past ten years' },
    ],
    correctAnswer: 'D',
    explanation: 'Because frogs disappear from polluted water, a steady rise in the frog population over ten years supports the claim that the water quality improved.',
    wrongAnswerExplanations: {
      A: 'The pond\'s size does not indicate whether its water quality improved.',
      B: 'The global range of frogs says nothing about this pond\'s water quality.',
      C: 'The biologist\'s experience does not by itself show the water improved.',
    },
  },

  // ── Inferences (2) ────────────────────────────────────────────────────────
  {
    id: 'sat-f4-rw-m2e-q18',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-easy',
    domain: 'Information and Ideas',
    skill: 'Inferences',
    difficulty: 'easy',
    stimulus: 'Penguins have a layer of dense, overlapping feathers coated with a waterproof oil, as well as a thick layer of fat beneath the skin. Together, these features trap heat and keep cold water away from the body, which is why penguins _______',
    question: 'Which choice most logically completes the text?',
    choices: [
      { label: 'A', text: 'are unable to swim in the ocean.' },
      { label: 'B', text: 'must avoid the water entirely.' },
      { label: 'C', text: 'can survive in extremely cold environments.' },
      { label: 'D', text: 'lose heat faster than most other birds.' },
    ],
    correctAnswer: 'C',
    explanation: 'The passage explains that penguins\' feathers and fat trap heat and block cold water, which supports the conclusion that they can survive in very cold environments.',
    wrongAnswerExplanations: {
      A: 'Waterproof feathers suit swimming; nothing suggests penguins cannot swim.',
      B: 'The waterproofing helps them handle water, so they need not avoid it entirely.',
      D: 'The features trap heat, so penguins lose heat slowly, not faster than other birds.',
    },
  },
  {
    id: 'sat-f4-rw-m2e-q19',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-easy',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'easy',
    stimulus: 'The park\'s new trail was designed with visitors of all ages in mind. Along the route, hikers can rest on shaded benches, read informative signs about local wildlife, and _______ the wide views of the valley below.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choices: [
      { label: 'A', text: 'enjoying' },
      { label: 'B', text: 'they enjoy' },
      { label: 'C', text: 'enjoy' },
      { label: 'D', text: 'to enjoy' },
    ],
    correctAnswer: 'C',
    explanation: 'Choice C is correct. Items in a list must be parallel in form. The list uses the base verbs "rest" and "read," so the base verb "enjoy" keeps the series parallel.',
    wrongAnswerExplanations: {
      A: 'Choice A is incorrect. The "-ing" form "enjoying" is not parallel with the base verbs "rest" and "read."',
      B: 'Choice B is incorrect. Adding the subject "they" breaks the parallel structure of the verb list.',
      D: 'Choice D is incorrect. The infinitive "to enjoy" is not parallel with the base verbs "rest" and "read."',
    },
  },

  // ── Boundaries (3) ────────────────────────────────────────────────────────
  {
    id: 'sat-f4-rw-m2e-q20',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-easy',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'easy',
    stimulus: 'After finishing her shift at the hospital _______ the nurse drove home and slept for nearly ten hours.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choices: [
      { label: 'A', text: ';' },
      { label: 'B', text: ':' },
      { label: 'C', text: '.' },
      { label: 'D', text: ',' },
    ],
    correctAnswer: 'D',
    explanation: 'The introductory phrase "After finishing her shift at the hospital" should be followed by a comma before the main clause.',
    wrongAnswerExplanations: {
      A: 'A semicolon joins two independent clauses, but the opening phrase is not independent.',
      B: 'A colon introduces a list or explanation, which is not the case here.',
      C: 'A period would leave the opening phrase as a sentence fragment.',
    },
  },
  {
    id: 'sat-f4-rw-m2e-q21',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-easy',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'easy',
    stimulus: 'The recipe calls for three simple _______ flour, water, and salt.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choices: [
      { label: 'A', text: 'ingredients:' },
      { label: 'B', text: 'ingredients' },
      { label: 'C', text: 'ingredients,' },
      { label: 'D', text: 'ingredients;' },
    ],
    correctAnswer: 'A',
    explanation: 'A colon follows the complete clause "The recipe calls for three simple ingredients" to introduce the list that names them.',
    wrongAnswerExplanations: {
      B: 'With no punctuation, the list runs into the clause without a clear break.',
      C: 'A comma is too weak to introduce this list clearly.',
      D: 'A semicolon joins independent clauses; the list is not an independent clause.',
    },
  },
  {
    id: 'sat-f4-rw-m2e-q22',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-easy',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'medium',
    stimulus: 'The bridge, which was completed in _______ still carries thousands of vehicles across the river each day.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choices: [
      { label: 'A', text: '1932,' },
      { label: 'B', text: '1932' },
      { label: 'C', text: '1932;' },
      { label: 'D', text: '1932:' },
    ],
    correctAnswer: 'A',
    explanation: 'The nonessential clause "which was completed in 1932" must be closed with a comma before the sentence continues with "still carries."',
    wrongAnswerExplanations: {
      B: 'Without a closing comma, the nonessential clause is not properly set off.',
      C: 'A semicolon would break the sentence in the middle of a single clause.',
      D: 'A colon does not belong in the middle of this nonessential clause.',
    },
  },

  // ── Form, Structure, and Sense (2) ────────────────────────────────────────
  {
    id: 'sat-f4-rw-m2e-q23',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-easy',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'easy',
    stimulus: 'The team of researchers _______ their results at the conference next week.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choices: [
      { label: 'A', text: 'presents' },
      { label: 'B', text: 'will present' },
      { label: 'C', text: 'presented' },
      { label: 'D', text: 'has presented' },
    ],
    correctAnswer: 'B',
    explanation: 'The phrase "next week" signals the future, so the future tense "will present" is correct.',
    wrongAnswerExplanations: {
      A: '"Presents" is present tense and does not match the future time marker "next week."',
      C: '"Presented" is past tense, contradicting the future "next week."',
      D: '"Has presented" describes a completed past action, not a future one.',
    },
  },
  {
    id: 'sat-f4-rw-m2e-q24',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-easy',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'medium',
    stimulus: 'Neither the coach nor the players _______ satisfied with the outcome of the match.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choices: [
      { label: 'A', text: 'was' },
      { label: 'B', text: 'is' },
      { label: 'C', text: 'were' },
      { label: 'D', text: 'has been' },
    ],
    correctAnswer: 'C',
    explanation: 'In a "neither...nor" construction, the verb agrees with the nearer subject. Here that subject is "players" (plural), so the plural "were" is correct.',
    wrongAnswerExplanations: {
      A: '"Was" is singular, but the nearer subject "players" is plural.',
      B: '"Is" is singular and does not agree with the plural "players."',
      D: '"Has been" is singular and mismatches the plural nearer subject.',
    },
  },

  // ── Rhetorical Synthesis (2) ──────────────────────────────────────────────
  {
    id: 'sat-f4-rw-m2e-q25',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-easy',
    domain: 'Expression of Ideas',
    skill: 'Rhetorical Synthesis',
    difficulty: 'easy',
    stimulus: 'While researching a topic, a student has taken the following notes:\n• The lighthouse was built in 1854 on a rocky point along the coast.\n• Its light could be seen from up to 20 miles away.\n• For over a century, keepers lived on-site and tended the light by hand.\n• In 1998, the light was automated, and the last keeper left.',
    question: 'The student wants to emphasize a change in how the lighthouse was operated. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
    choices: [
      { label: 'A', text: 'For over a century, keepers tended the light by hand, but in 1998 the lighthouse was automated and the last keeper left.' },
      { label: 'B', text: 'The lighthouse was built in 1854 on a rocky point along the coast.' },
      { label: 'C', text: 'The lighthouse\'s light could be seen from up to 20 miles away.' },
      { label: 'D', text: 'The lighthouse was built on a rocky point and stands along the coast.' },
    ],
    correctAnswer: 'A',
    explanation: 'The goal is to emphasize a change in operation. Choice A contrasts the era of hand-tending keepers with the 1998 automation, capturing the change directly.',
    wrongAnswerExplanations: {
      B: 'This gives the construction date, not a change in how the lighthouse was operated.',
      C: 'The range of the light is a feature, not a change in operation.',
      D: 'This describes the location, not a change in operation.',
    },
  },

  // ── Transitions (3) ───────────────────────────────────────────────────────
  {
    id: 'sat-f4-rw-m2e-q26',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-easy',
    domain: 'Expression of Ideas',
    skill: 'Transitions',
    difficulty: 'easy',
    stimulus: 'The hikers set out early to reach the summit before noon. _______ a sudden storm forced them to turn back only halfway up the trail.',
    question: 'Which choice completes the text with the most logical transition?',
    choices: [
      { label: 'A', text: 'Therefore,' },
      { label: 'B', text: 'For example,' },
      { label: 'C', text: 'However,' },
      { label: 'D', text: 'In addition,' },
    ],
    correctAnswer: 'C',
    explanation: 'The hikers planned to reach the summit but a storm forced them back — a contrast. "However" correctly signals this.',
    wrongAnswerExplanations: {
      A: '"Therefore" signals a result, but the storm is not caused by their early start.',
      B: '"For example" would introduce an illustration, which the storm is not.',
      D: '"In addition" signals another similar point, but the storm contrasts with their plan.',
    },
  },
  {
    id: 'sat-f4-rw-m2e-q27',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-easy',
    domain: 'Expression of Ideas',
    skill: 'Transitions',
    difficulty: 'medium',
    stimulus: 'Bees play a vital role in pollinating many crops. _______ a decline in bee populations could threaten the production of fruits and vegetables that depend on them.',
    question: 'Which choice completes the text with the most logical transition?',
    choices: [
      { label: 'A', text: 'Nevertheless,' },
      { label: 'B', text: 'As a result,' },
      { label: 'C', text: 'In contrast,' },
      { label: 'D', text: 'Meanwhile,' },
    ],
    correctAnswer: 'B',
    explanation: 'Because bees pollinate crops, a decline in bees could threaten crop production — a cause-and-effect relationship that "As a result" signals.',
    wrongAnswerExplanations: {
      A: '"Nevertheless" signals contrast, but the second sentence follows logically from the first.',
      C: '"In contrast" signals opposition, but the sentences are consistent, not opposed.',
      D: '"Meanwhile" signals simultaneous events, not a consequence.',
    },
  },
]
