import type { RWQuestion } from './types'

export const f3RwModule1Questions: RWQuestion[] = [
  {
    id: 'sat-f3-rw-m1-q01',
    section: 'reading-writing',
    moduleId: 'f3-rw-module-1',
    domain: 'Craft and Structure',
    skill: 'Words in Context',
    difficulty: 'easy',
    stimulus: 'Coral reefs worldwide have suffered repeated bleaching events as ocean temperatures rise. Scientists describe the reefs\' response as _______ : individual colonies recover temporarily between thermal stress episodes, only to face increasingly frequent and severe events that prevent full recuperation.',
    question: 'Which choice completes the text with the most logical and precise word or phrase?',
    choices: [
      { label: 'A', text: 'cyclical' },
      { label: 'B', text: 'spontaneous' },
      { label: 'C', text: 'permanent' },
      { label: 'D', text: 'unprecedented' },
    ],
    correctAnswer: 'A',
    explanation: '"Cyclical" means recurring in cycles, which fits the pattern of temporary recovery followed by repeated bleaching events described in the passage.',
    wrongAnswerExplanations: {
      B: '"Spontaneous" means occurring without apparent cause, which does not describe the predictable pattern of thermal stress and partial recovery.',
      C: '"Permanent" contradicts the description of temporary recovery between events.',
      D: '"Unprecedented" means without prior example; the passage describes repeated events, not something novel.',
    },
  },

  {
    id: 'sat-f3-rw-m1-q02',
    section: 'reading-writing',
    moduleId: 'f3-rw-module-1',
    domain: 'Craft and Structure',
    skill: 'Words in Context',
    difficulty: 'easy',
    stimulus: 'Archival historians working with eighteenth-century merchant ledgers must contend with _______ records: pages degraded by moisture, ink faded beyond legibility, and binding glue that crumbles when a volume is opened, making each consultation a test of patience.',
    question: 'Which choice completes the text with the most logical and precise word or phrase?',
    choices: [
      { label: 'A', text: 'fragile' },
      { label: 'B', text: 'abundant' },
      { label: 'C', text: 'meticulous' },
      { label: 'D', text: 'coherent' },
    ],
    correctAnswer: 'A',
    explanation: '"Fragile" means easily damaged or broken, which precisely describes records with degraded pages, faded ink, and crumbling binding.',
    wrongAnswerExplanations: {
      B: '"Abundant" means plentiful; the passage says nothing about quantity, only about the physical condition of the documents.',
      C: '"Meticulous" means very careful, a quality of the historian rather than the records themselves.',
      D: '"Coherent" means logically consistent or clear, which contradicts the description of degraded, illegible pages.',
    },
  },

  {
    id: 'sat-f3-rw-m1-q03',
    section: 'reading-writing',
    moduleId: 'f3-rw-module-1',
    domain: 'Craft and Structure',
    skill: 'Words in Context',
    difficulty: 'medium',
    stimulus: 'Early autonomous vehicle researchers assumed that teaching a machine to drive required _______ a complete set of traffic rules into the system. Experience proved otherwise: environments too complex for exhaustive codification required vehicles that could learn from exposure to real-world driving rather than from handcrafted rule libraries.',
    question: 'Which choice completes the text with the most logical and precise word or phrase?',
    choices: [
      { label: 'A', text: 'encoding' },
      { label: 'B', text: 'simulating' },
      { label: 'C', text: 'negotiating' },
      { label: 'D', text: 'discarding' },
    ],
    correctAnswer: 'A',
    explanation: '"Encoding" means converting rules into a form a system can process, which fits the idea of programming traffic rules directly into a vehicle\'s software.',
    wrongAnswerExplanations: {
      B: '"Simulating" means imitating or modeling, which relates to testing rather than to the programming approach being described.',
      C: '"Negotiating" means reaching agreement through discussion, which does not apply to programming a machine.',
      D: '"Discarding" means throwing away, which is opposite to the act of loading rules into a system.',
    },
  },

  {
    id: 'sat-f3-rw-m1-q04',
    section: 'reading-writing',
    moduleId: 'f3-rw-module-1',
    domain: 'Craft and Structure',
    skill: 'Words in Context',
    difficulty: 'medium',
    stimulus: 'Economists who study the effects of trade sanctions note that their impact is rarely _______ : while sanctions are intended to penalize the targeted government, the costs are often distributed unevenly, with ordinary citizens and vulnerable populations bearing the greatest economic hardship.',
    question: 'Which choice completes the text with the most logical and precise word or phrase?',
    choices: [
      { label: 'A', text: 'temporary' },
      { label: 'B', text: 'intentional' },
      { label: 'C', text: 'targeted' },
      { label: 'D', text: 'visible' },
    ],
    correctAnswer: 'C',
    explanation: '"Targeted" means directed precisely at a specific group. The passage explains that while sanctions aim at the government, the harm spreads to the general population — meaning the impact is not as precisely targeted as intended.',
    wrongAnswerExplanations: {
      B: '"Intentional" means deliberate; the passage is not questioning whether sanctions are deliberate but whether their effects are precise.',
      A: '"Temporary" relates to duration, but the passage focuses on distribution of harm, not its length.',
      D: '"Visible" relates to observability, which is not the contrast the passage draws.',
    },
  },

  {
    id: 'sat-f3-rw-m1-q11',
    section: 'reading-writing',
    moduleId: 'f3-rw-module-1',
    domain: 'Information and Ideas',
    skill: 'Central Ideas and Details',
    difficulty: 'easy',
    stimulus: 'The human gut contains trillions of microorganisms — bacteria, viruses, and fungi — collectively called the microbiome. Far from passive residents, these microbes actively participate in digestion, synthesizing vitamins and breaking down fiber into compounds the gut cannot process alone. Disruptions to the microbiome, whether through antibiotic use or dietary changes, are increasingly linked to conditions ranging from inflammatory bowel disease to anxiety disorders, suggesting that these microorganisms influence far more than digestion.',
    question: 'What is the central idea of this passage?',
    choices: [
      { label: 'A', text: 'Antibiotic use is the leading cause of microbiome disruption and should be avoided when possible' },
      { label: 'B', text: 'Anxiety disorders are primarily caused by imbalances in the gut microbiome' },
      { label: 'C', text: 'Bacteria in the gut produce every vitamin the human body requires' },
      { label: 'D', text: 'The gut microbiome is an active community of microorganisms with wide-ranging effects on human health' },
    ],
    correctAnswer: 'D',
    explanation: 'The passage introduces the microbiome, explains its active role in digestion and vitamin synthesis, and notes its links to various health conditions — all supporting the idea that it has wide-ranging effects on human health.',
    wrongAnswerExplanations: {
      A: 'The passage mentions antibiotics as one source of disruption but does not argue they are the leading cause or advocate avoiding them.',
      C: 'The passage says microbes synthesize vitamins, not that they produce every vitamin the body requires.',
      B: 'The passage mentions a link between microbiome disruption and anxiety but does not claim the microbiome is the primary cause of anxiety disorders.',
    },
  },

  {
    id: 'sat-f3-rw-m1-q06',
    section: 'reading-writing',
    moduleId: 'f3-rw-module-1',
    domain: 'Craft and Structure',
    skill: 'Text Structure and Purpose',
    difficulty: 'medium',
    stimulus: 'When photography emerged in the 1840s, portrait painters initially dismissed it as a mechanical craft with no claim to artistic status. Within a generation, however, many painters had quietly incorporated photographic reference material into their own practice — using photographs to study light, document poses, and capture expressions their sitters could not hold for the hours required by traditional portraiture. The very medium they had dismissed became an indispensable tool.',
    question: 'Which choice best describes the overall structure of the passage?',
    choices: [
      { label: 'A', text: 'It presents a problem, identifies its cause, and proposes a solution' },
      { label: 'B', text: 'It introduces an initial attitude, describes how practice changed it, and notes the irony of the outcome' },
      { label: 'C', text: 'It makes a claim and then provides statistical evidence to support it' },
      { label: 'D', text: 'It describes a historical event and evaluates its long-term consequences' },
    ],
    correctAnswer: 'B',
    explanation: 'The passage opens with painters\' dismissal of photography, explains how they came to use it, and ends by noting the irony: the rejected medium became essential. This matches option B.',
    wrongAnswerExplanations: {
      A: 'The passage identifies no problem to be solved; it traces a shift in attitude.',
      C: 'No statistical evidence is presented; the passage relies on historical narrative.',
      D: 'The passage does not evaluate long-term consequences; it ends with an observation about irony.',
    },
  },

  {
    id: 'sat-f3-rw-m1-q07',
    section: 'reading-writing',
    moduleId: 'f3-rw-module-1',
    domain: 'Craft and Structure',
    skill: 'Text Structure and Purpose',
    difficulty: 'medium',
    stimulus: 'Public health campaigns often rely on fear-based messaging — graphic images of diseased lungs on cigarette packaging, or stark warnings about the consequences of drunk driving. Research on behavior change, however, suggests that excessive fear can lead to defensive avoidance rather than action: when a threat feels overwhelming and uncontrollable, audiences disengage rather than adopt the recommended behavior. Effective campaigns must therefore pair warnings with clear, achievable protective actions.',
    question: 'What is the main purpose of the second sentence ("Research on behavior change . . . recommended behavior")?',
    choices: [
      { label: 'A', text: 'To introduce evidence that complicates the assumption implied by the first sentence' },
      { label: 'B', text: 'To provide an example that illustrates the effectiveness of fear-based campaigns' },
      { label: 'C', text: 'To argue that public health campaigns should be eliminated' },
      { label: 'D', text: 'To summarize the findings of a specific research study about smoking' },
    ],
    correctAnswer: 'A',
    explanation: 'The first sentence describes the common use of fear-based messaging. The second sentence introduces research showing that excessive fear can backfire — complicating the assumption that fear-based approaches are effective.',
    wrongAnswerExplanations: {
      B: 'The sentence describes a limitation of fear-based campaigns, not an example of their effectiveness.',
      C: 'The passage does not advocate eliminating campaigns; it advocates improving them.',
      D: 'The sentence generalizes across behavior change research; it does not summarize a specific study about smoking.',
    },
  },

  {
    id: 'sat-f3-rw-m1-q12',
    section: 'reading-writing',
    moduleId: 'f3-rw-module-1',
    domain: 'Information and Ideas',
    skill: 'Central Ideas and Details',
    difficulty: 'medium',
    stimulus: 'The Great Wall of China was not built as a single unified project but was assembled over more than a thousand years by successive dynasties with different goals. The earliest sections, built during the Warring States period, were earthen ramparts designed to protect individual kingdoms from one another. Later dynasties linked and extended these walls primarily to deter northern nomadic peoples. The famous stone and brick sections that tourists visit today date largely from the Ming dynasty, built between the fourteenth and seventeenth centuries — the most recent major phase of construction.',
    question: 'According to the passage, which of the following best describes the Great Wall?',
    choices: [
      { label: 'A', text: 'A single engineering project completed during the Ming dynasty' },
      { label: 'B', text: 'A series of structures built across centuries, serving evolving defensive purposes' },
      { label: 'C', text: 'An earthen rampart originally built to repel northern nomadic peoples' },
      { label: 'D', text: 'A monument constructed primarily for cultural and symbolic rather than military purposes' },
    ],
    correctAnswer: 'B',
    explanation: 'The passage explicitly states the wall was built over more than a thousand years by different dynasties with different goals — from protecting kingdoms against each other to deterring nomadic peoples.',
    wrongAnswerExplanations: {
      A: 'The Ming dynasty built the most famous sections, but the Wall was built across many centuries and dynasties.',
      C: 'The earliest sections protected individual kingdoms from each other; later sections targeted northern nomadic peoples.',
      D: 'The passage describes the Wall\'s defensive military purposes, not cultural or symbolic ones.',
    },
  },

  {
    id: 'sat-f3-rw-m1-q08',
    section: 'reading-writing',
    moduleId: 'f3-rw-module-1',
    domain: 'Craft and Structure',
    skill: 'Text Structure and Purpose',
    difficulty: 'hard',
    stimulus: 'Zora Neale Hurston trained as an anthropologist under Franz Boas at Columbia University, and her fieldwork collecting African American folklore in the 1930s south reflected rigorous ethnographic methodology. Yet literary critics have often placed her in the tradition of creative writers, focusing on her novel Their Eyes Were Watching God at the expense of works like Mules and Men. Hurston herself resisted this bifurcation, arguing that her fiction and her anthropology were unified by a single project: preserving and celebrating a culture that dominant society had long devalued.',
    underlineTargets: ['this bifurcation'],
    question: 'As used in the passage, what does the underlined phrase "this bifurcation" refer to?',
    choices: [
      { label: 'A', text: 'The separation of African American folklore from mainstream American literary traditions' },
      { label: 'B', text: 'The gap between the critical reception of Hurston\'s work during her lifetime and after her death' },
      { label: 'C', text: 'The methodological difference between Boas\'s anthropology and Hurston\'s fieldwork approach' },
      { label: 'D', text: 'The division between Hurston\'s identity as an anthropologist and her identity as a creative writer' },
    ],
    correctAnswer: 'D',
    explanation: '"This bifurcation" refers to the split just described: literary critics categorizing Hurston as a creative writer while her anthropological work goes underappreciated — the division between her two roles that she herself rejected.',
    wrongAnswerExplanations: {
      A: 'The passage discusses the separation of Hurston\'s own roles, not the separation of African American folklore from American literature broadly.',
      C: 'No methodological difference between Boas and Hurston is described.',
      B: 'The passage does not discuss Hurston\'s reception during versus after her lifetime.',
    },
  },

  {
    id: 'sat-f3-rw-m1-q14',
    section: 'reading-writing',
    moduleId: 'f3-rw-module-1',
    domain: 'Information and Ideas',
    skill: 'Command of Evidence',
    difficulty: 'medium',
    stimulus: 'A researcher studying urban green spaces and mental health surveyed 1,200 residents across three cities. Participants reported their weekly time in parks or gardens and completed a validated stress inventory. The researcher found that residents who spent at least two hours per week in green spaces scored significantly lower on the stress inventory than those who spent no time in natural settings, even after controlling for income and employment status.',
    question: 'Which finding, if true, would most directly support the researcher\'s claim that green space exposure reduces stress independently of socioeconomic factors?',
    choices: [
      { label: 'A', text: 'Wealthier residents in the study visited parks more frequently than lower-income residents' },
      { label: 'B', text: 'Residents who exercised regularly reported lower stress than those who did not, regardless of green space use' },
      { label: 'C', text: 'The stress reduction associated with green space was consistent across all income brackets in the study' },
      { label: 'D', text: 'Some parks in the study cities were located in wealthier neighborhoods' },
    ],
    correctAnswer: 'C',
    explanation: 'If the stress-reduction benefit appeared consistently across all income levels, this would confirm that the effect holds independently of socioeconomic status, directly supporting the researcher\'s claim.',
    wrongAnswerExplanations: {
      A: 'If wealthier residents visited parks more, this would raise concerns about confounding rather than support independence from socioeconomic factors.',
      B: 'Regular exercise as an alternative explanation would undermine rather than support the green space hypothesis.',
      D: 'Park locations in wealthier neighborhoods would suggest a socioeconomic confound, weakening rather than supporting the claim.',
    },
  },

  {
    id: 'sat-f3-rw-m1-q15',
    section: 'reading-writing',
    moduleId: 'f3-rw-module-1',
    domain: 'Information and Ideas',
    skill: 'Command of Evidence',
    difficulty: 'medium',
    stimulus: 'Reading researchers debate whether comprehension is primarily driven by decoding skill or vocabulary breadth. One study tracked 800 third-graders over four years. Among students with strong decoding skills, those with large vocabularies showed significantly higher reading comprehension by seventh grade than those with limited vocabularies, suggesting vocabulary plays a critical independent role even when decoding is controlled.',
    question: 'Which choice best states the main finding reported in the passage?',
    choices: [
      { label: 'A', text: 'Decoding skill is more important than vocabulary for reading comprehension in early grades' },
      { label: 'B', text: 'Among students with comparable decoding ability, vocabulary size predicted later reading comprehension' },
      { label: 'C', text: 'Reading comprehension does not improve significantly between third and seventh grade' },
      { label: 'D', text: 'Students who receive vocabulary instruction consistently outperform students who do not' },
    ],
    correctAnswer: 'B',
    explanation: 'Among students with strong decoding, those with large vocabularies outperformed those with limited vocabularies in comprehension by seventh grade — showing vocabulary\'s independent predictive role when decoding is held constant.',
    wrongAnswerExplanations: {
      A: 'The study held decoding constant and found vocabulary mattered, not that decoding was more important.',
      C: 'The passage discusses growth in comprehension across that period, not stagnation.',
      D: 'The passage describes a correlational study tracking students, not an instructional intervention study.',
    },
  },

  {
    id: 'sat-f3-rw-m1-q16',
    section: 'reading-writing',
    moduleId: 'f3-rw-module-1',
    domain: 'Information and Ideas',
    skill: 'Command of Evidence',
    difficulty: 'hard',
    stimulus: 'An environmental scientist studying urban tree canopy coverage collected the following data:\n\nDistrict | Tree Canopy Coverage | Average Summer Temperature\nNorth | 42% | 27°C\nEast | 18% | 31°C\nWest | 35% | 28°C\nSouth | 9% | 34°C\n\nThe scientist concluded that districts with greater tree canopy coverage experience lower average summer temperatures.',
    question: 'Which choice best evaluates the strength of the scientist\'s conclusion?',
    choices: [
      { label: 'A', text: 'The conclusion is strongly supported: every district with higher canopy coverage shows a lower average temperature than every district with lower canopy coverage' },
      { label: 'B', text: 'The conclusion is weakened by the fact that the East district has both lower canopy coverage and lower temperatures than the South district' },
      { label: 'C', text: 'The conclusion is unsupported because the scientist did not measure precipitation levels in each district' },
      { label: 'D', text: 'The conclusion is weakened because the South district has both the lowest canopy coverage and the highest temperature, making it an outlier' },
    ],
    correctAnswer: 'A',
    explanation: 'Examining the data: North (42%, 27°C), West (35%, 28°C), East (18%, 31°C), South (9%, 34°C). Each district with higher canopy coverage shows a lower temperature, with no exceptions — this consistently supports the conclusion.',
    wrongAnswerExplanations: {
      B: 'The East (18%, 31°C) has higher temperatures than the South (9%, 34°C) — the claim is false, which means this choice misreads the data.',
      C: 'While precipitation could be a confounding factor, the question asks about the strength of the conclusion given the data provided, not about alternative explanations.',
      D: 'The South having the lowest canopy and highest temperature actually confirms the trend rather than being an outlier.',
    },
  },

  {
    id: 'sat-f3-rw-m1-q17',
    section: 'reading-writing',
    moduleId: 'f3-rw-module-1',
    domain: 'Information and Ideas',
    skill: 'Command of Evidence',
    difficulty: 'hard',
    stimulus: 'A sociologist examining internal migration in a country collected data from five regions over twenty years. She observed that regions with the fastest-growing technology sectors saw the largest net population inflows, while regions with declining manufacturing employment saw consistent net outflows. She concluded that economic opportunity, specifically in high-growth industries, is the primary driver of internal migration patterns.',
    question: 'Which of the following, if true, would most weaken the sociologist\'s conclusion?',
    choices: [
      { label: 'A', text: 'Migrants who moved to technology hubs reported that lower housing costs were their primary motivation' },
      { label: 'B', text: 'Regions with the largest population inflows also had the most universities and colleges' },
      { label: 'C', text: 'The technology sector grew fastest in regions that were already the most densely populated' },
      { label: 'D', text: 'Both of the above choices would individually weaken the conclusion' },
    ],
    correctAnswer: 'B',
    explanation: 'If regions with technology growth also had the most universities, the migration could be driven by educational access rather than industry employment, undermining the conclusion that technology-sector growth is the primary driver.',
    wrongAnswerExplanations: {
      A: 'Lower housing costs would be a competing explanation for migration to technology hubs — this also weakens the conclusion, but option B is more directly relevant to testing a causal alternative.',
      C: 'Existing population density is correlated with the finding but does not present an alternative explanation for what drives migration.',
      D: 'Option A does weaken the conclusion, but the question asks which single choice most effectively weakens it — option B provides a more direct causal alternative.',
    },
  },

  {
    id: 'sat-f3-rw-m1-q18',
    section: 'reading-writing',
    moduleId: 'f3-rw-module-1',
    domain: 'Information and Ideas',
    skill: 'Inferences',
    difficulty: 'hard',
    stimulus: 'Genetic genealogy databases now contain DNA profiles from tens of millions of people. Law enforcement agencies have used these databases to identify suspects by uploading crime scene DNA and searching for partial matches with distant relatives. Several high-profile cold cases have been solved through this method. Privacy advocates, however, note that individuals who contribute their DNA to recreational genealogy services effectively enroll their biological relatives — who may never have consented — into a searchable database accessible to law enforcement.',
    question: 'Based on the passage, which of the following can most reasonably be inferred?',
    choices: [
      { label: 'A', text: 'All genetic genealogy companies voluntarily share their databases with law enforcement agencies' },
      { label: 'B', text: 'Genetic genealogy databases are less accurate than traditional forensic DNA testing methods' },
      { label: 'C', text: 'Privacy advocates oppose all forensic uses of DNA evidence in criminal investigations' },
      { label: 'D', text: 'A person who has never used a genetic genealogy service may still be identifiable through a relative\'s DNA submission' },
    ],
    correctAnswer: 'D',
    explanation: 'The passage states that submitting DNA enrolls biological relatives who may not have consented. This directly implies that non-users can become identifiable through a relative\'s submission.',
    wrongAnswerExplanations: {
      A: 'The passage says databases are "accessible to law enforcement" via searching, but does not state all companies voluntarily share.',
      C: 'Privacy advocates\' objection is about consent and enrollment of non-participants, not a blanket opposition to DNA evidence.',
      B: 'Accuracy is never compared between genetic genealogy and traditional forensic methods.',
    },
  },

  {
    id: 'sat-f3-rw-m1-q21',
    section: 'reading-writing',
    moduleId: 'f3-rw-module-1',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'easy',
    stimulus: 'The festival attracted visitors from eleven countries _______ organizers had not expected such an international turnout in only its second year.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choices: [
      { label: 'A', text: ',' },
      { label: 'B', text: '; however,' },
      { label: 'C', text: ': however,' },
      { label: 'D', text: 'and' },
    ],
    correctAnswer: 'B',
    explanation: 'A semicolon correctly joins two independent clauses. "However" signals contrast and is a conjunctive adverb, correctly placed after the semicolon and followed by a comma.',
    wrongAnswerExplanations: {
      A: 'A comma alone between two independent clauses is a comma splice.',
      C: 'A colon introduces explanatory content; it does not connect two clauses showing contrast with "however."',
      D: '"And" as a conjunction without a comma before it does not correctly signal the contrast between the clauses.',
    },
  },

  {
    id: 'sat-f3-rw-m1-q13',
    section: 'reading-writing',
    moduleId: 'f3-rw-module-1',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'medium',
    stimulus: `In 1846, the astronomer Urbain Le Verrier predicted the location of an unknown planet by studying irregularities in the orbit of Uranus. He mailed his calculations to an observatory in Berlin, where a young astronomer pointed a telescope at the exact region Le Verrier had specified. Within an hour, the astronomer ______ Neptune, almost precisely where the mathematics said it would be.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'spots' },
      { label: 'B', text: 'spotted' },
      { label: 'C', text: 'will spot' },
      { label: 'D', text: 'is spotting' },
    ],
    correctAnswer: 'B',
    explanation: `Choice B is correct. This item tests verb tense consistency within a narrative. The surrounding sentences establish a past-tense account of events in 1846 ("predicted," "mailed," "pointed"). The verb in the blank describes another completed action in that same sequence, so the simple past "spotted" keeps the narrative consistent.`,
    wrongAnswerExplanations: {
      A: `Choice A is incorrect. The present-tense "spots" breaks the past-tense narrative established by "predicted," "mailed," and "pointed," producing an inconsistent shift in time.`,
      C: `Choice C is incorrect. The future-tense "will spot" is illogical, since the discovery being described occurred in 1846 and is narrated entirely in the past.`,
      D: `Choice D is incorrect. The present progressive "is spotting" both shifts to the present and implies an ongoing action, neither of which fits the completed past event in this narrative.`,
    },
  },

  {
    id: 'sat-f3-rw-m1-q19',
    section: 'reading-writing',
    moduleId: 'f3-rw-module-1',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'medium',
    stimulus: `Tidal marshes are among the most productive ecosystems on Earth. The dense network of grasses and channels that lines these coastal wetlands ______ habitat for fish, shellfish, and migratory birds while also buffering shorelines against storm surges. Ecologists warn that rising sea levels threaten to submerge many of these marshes faster than they can migrate inland.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'provide' },
      { label: 'B', text: 'provides' },
      { label: 'C', text: 'have provided' },
      { label: 'D', text: 'were providing' },
    ],
    correctAnswer: 'B',
    explanation: `Choice B is correct. This item tests subject-verb agreement. The grammatical subject of the sentence is the singular noun "network," not the nearby plural nouns "grasses and channels" inside the modifying phrase "that lines these coastal wetlands." A singular subject requires the singular present-tense verb "provides."`,
    wrongAnswerExplanations: {
      A: `Choice A is incorrect. "Provide" is the plural form; it mistakenly agrees with the intervening plural nouns "grasses and channels" rather than with the true singular subject "network."`,
      C: `Choice C is incorrect. The plural "have provided" fails to agree with the singular subject "network" and also shifts the sentence out of the present tense used to describe an ongoing function.`,
      D: `Choice D is incorrect. The past progressive "were providing" is both plural and past tense, disagreeing in number with "network" and clashing with the present-tense description of what marshes do.`,
    },
  },

  {
    id: 'sat-f3-rw-m1-q24',
    section: 'reading-writing',
    moduleId: 'f3-rw-module-1',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'medium',
    stimulus: 'The committee of regional directors _______ meeting quarterly to review infrastructure priorities, a schedule that participants say allows enough time to analyze data between sessions without losing momentum on ongoing projects.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choices: [
      { label: 'A', text: 'have been' },
      { label: 'B', text: 'has been' },
      { label: 'C', text: 'were' },
      { label: 'D', text: 'are' },
    ],
    correctAnswer: 'B',
    explanation: 'The subject is "committee," a singular collective noun, so it takes a singular verb. "Has been" is the correct singular present perfect form, consistent with the ongoing nature described.',
    wrongAnswerExplanations: {
      A: '"Have been" is plural, but the head noun "committee" is singular.',
      C: '"Were" is past tense, but the passage describes a continuing practice.',
      D: '"Are" is present tense but lacks the continuity implied by the context and does not pair correctly with "meeting" in this construction.',
    },
  },

  {
    id: 'sat-f3-rw-m1-q22',
    section: 'reading-writing',
    moduleId: 'f3-rw-module-1',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'medium',
    stimulus: 'The chef described her philosophy of cooking _______ simplicity above novelty, seasonal ingredients above imported ones, and technique above technology.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choices: [
      { label: 'A', text: '; she valued' },
      { label: 'B', text: ', she valued' },
      { label: 'C', text: ': she valued' },
      { label: 'D', text: '— and she valued' },
    ],
    correctAnswer: 'C',
    explanation: 'A colon is used after an independent clause to introduce a list or explanation. The first clause ("The chef described her philosophy of cooking") is complete, and the colon correctly introduces the enumerated values that follow.',
    wrongAnswerExplanations: {
      B: 'A comma alone between two independent clauses creates a comma splice.',
      A: 'A semicolon joins two independent clauses of roughly equal weight; here, the second clause functions as an explanation of the first, making a colon more appropriate.',
      D: 'Adding "and" implies a simple addition rather than an explanatory elaboration; the colon more precisely signals that what follows defines the philosophy.',
    },
  },

  {
    id: 'sat-f3-rw-m1-q23',
    section: 'reading-writing',
    moduleId: 'f3-rw-module-1',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'medium',
    stimulus: 'The observatory\'s new telescope can detect light from stars more than twelve billion light-years away _______ it is sensitive enough to distinguish objects separated by less than one arc-second in the sky.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choices: [
      { label: 'A', text: ',' },
      { label: 'B', text: '. Furthermore,' },
      { label: 'C', text: ': furthermore,' },
      { label: 'D', text: '; furthermore,' },
    ],
    correctAnswer: 'D',
    explanation: 'A semicolon joins two independent clauses; "furthermore" is a conjunctive adverb that adds related information and is followed by a comma. This is the standard construction for linking two closely related independent clauses.',
    wrongAnswerExplanations: {
      A: 'A comma alone between two independent clauses creates a comma splice.',
      C: 'A colon before "furthermore" is nonstandard; colons introduce explanations or lists, not additive transitions.',
      B: 'Starting a new sentence with "Furthermore" is grammatically acceptable but unnecessarily separates two closely related ideas; the semicolon construction is the preferred standard form.',
    },
  },

  {
    id: 'sat-f3-rw-m1-q25',
    section: 'reading-writing',
    moduleId: 'f3-rw-module-1',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'hard',
    stimulus: 'Winning three consecutive research grants, _______ enabled the laboratory to expand its facilities and hire six additional postdoctoral researchers.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choices: [
      { label: 'A', text: 'the laboratory\'s success' },
      { label: 'B', text: 'they' },
      { label: 'C', text: 'it was the laboratory' },
      { label: 'D', text: 'the grants had' },
    ],
    correctAnswer: 'A',
    explanation: 'The participial phrase "Winning three consecutive research grants" modifies the subject of the main clause. The subject must be the entity that won the grants. "The laboratory\'s success" correctly identifies the laboratory as that entity, and the structure avoids a dangling modifier.',
    wrongAnswerExplanations: {
      B: '"They" refers to the grants rather than to the laboratory, creating a dangling modifier — the grants did not "win" themselves.',
      C: '"It was the laboratory" creates an awkward construction and still leaves the participial phrase dangling.',
      D: '"The grants had" would mean the grants won themselves, which is logically incoherent.',
    },
  },

  {
    id: 'sat-f3-rw-m1-q09',
    section: 'reading-writing',
    moduleId: 'f3-rw-module-1',
    domain: 'Expression of Ideas',
    skill: 'Transitions',
    difficulty: 'medium',
    stimulus: 'The city\'s new composting program diverts thousands of tons of organic waste from landfills each month. _______, it has created an unexpected logistical challenge: collection trucks must now follow separate routes on alternating days, doubling the number of early-morning passes through residential streets.',
    question: 'Which choice completes the text with the most logical transition?',
    choices: [
      { label: 'A', text: 'Therefore' },
      { label: 'B', text: 'That said' },
      { label: 'C', text: 'In addition' },
      { label: 'D', text: 'Similarly' },
    ],
    correctAnswer: 'B',
    explanation: '"That said" acknowledges the prior positive point (waste diversion) while signaling a qualification or complication — which is precisely what the second sentence introduces: an unexpected drawback of the program.',
    wrongAnswerExplanations: {
      A: '"Therefore" would imply the logistical challenge is a logical result or conclusion drawn from the waste diversion, but the challenge is an unexpected side effect, not a deduction.',
      C: '"In addition" signals that the second sentence adds a further benefit or parallel point, but the second sentence describes a drawback rather than an additional advantage.',
      D: '"Similarly" signals that the second sentence presents a parallel or analogous situation, but a logistical challenge is not parallel to waste diversion success.',
    },
  },

  {
    id: 'sat-f3-rw-m1-q20',
    section: 'reading-writing',
    moduleId: 'f3-rw-module-1',
    domain: 'Expression of Ideas',
    skill: 'Transitions',
    difficulty: 'medium',
    stimulus: 'The renovation project finished two months ahead of schedule. _______, the final budget came in under the contractor\'s original estimate, sparing the city council a difficult vote on supplemental funding.',
    question: 'Which choice completes the text with the most logical transition?',
    choices: [
      { label: 'A', text: 'However' },
      { label: 'B', text: 'In other words' },
      { label: 'C', text: 'As a result' },
      { label: 'D', text: 'In addition' },
    ],
    correctAnswer: 'D',
    explanation: '"In addition" signals that the second sentence adds another positive development alongside the first — both the early completion and the lower-than-expected cost are separate but parallel good outcomes.',
    wrongAnswerExplanations: {
      A: '"However" signals contrast or qualification, but the second sentence presents another positive result rather than a complication or contradiction.',
      B: '"In other words" signals a restatement or clarification of the preceding sentence, but the budget news is a distinct new fact, not a restatement of the schedule news.',
      C: '"As a result" implies the under-budget outcome was caused by finishing early, but the passage does not establish that causal link; both outcomes may be independent successes.',
    },
  },

  {
    id: 'sat-f3-rw-m1-q27',
    section: 'reading-writing',
    moduleId: 'f3-rw-module-1',
    domain: 'Expression of Ideas',
    skill: 'Transitions',
    difficulty: 'medium',
    stimulus: 'Early astronomers explained the motion of planets by placing Earth at the center of the universe and charting elaborate cycles within cycles to account for planetary movement. These models made reasonable predictions. _______, they required increasingly complex adjustments as observations improved, and the underlying geometry grew so unwieldy that astronomers searched for a simpler alternative.',
    question: 'Which choice completes the text with the most logical transition?',
    choices: [
      { label: 'A', text: 'Therefore' },
      { label: 'B', text: 'Similarly' },
      { label: 'C', text: 'However' },
      { label: 'D', text: 'Consequently' },
    ],
    correctAnswer: 'C',
    explanation: '"However" signals a contrast: the models made reasonable predictions (positive), but they required increasingly complex adjustments (negative). This contrast is the logical relationship between the sentences.',
    wrongAnswerExplanations: {
      A: '"Therefore" signals a conclusion or result, but the complexity of the models is not a result of their predictive success.',
      B: '"Similarly" signals that the same relationship applies; there is no parallel being drawn here.',
      D: '"Consequently" signals that what follows results from what preceded; the need for adjustments is not a consequence of making reasonable predictions.',
    },
  },

  {
    id: 'sat-f3-rw-m1-q10',
    section: 'reading-writing',
    moduleId: 'f3-rw-module-1',
    domain: 'Expression of Ideas',
    skill: 'Transitions',
    difficulty: 'hard',
    stimulus: 'Historians have documented that the printing press dramatically accelerated the spread of both religious reform and scientific thought in sixteenth-century Europe. _______, many of the ideas that circulated most widely through print were sensationalist pamphlets and astrological almanacs rather than scholarly treatises.',
    question: 'Which choice completes the text with the most logical transition?',
    choices: [
      { label: 'A', text: 'As a result' },
      { label: 'B', text: 'By contrast' },
      { label: 'C', text: 'Furthermore' },
      { label: 'D', text: 'Nevertheless' },
    ],
    correctAnswer: 'D',
    explanation: '"Nevertheless" acknowledges the validity of the prior point (the press accelerated serious intellectual movements) while introducing a complication: the most widely circulated content was actually popular, non-scholarly material. This concessive relationship is precisely what "nevertheless" captures.',
    wrongAnswerExplanations: {
      A: '"As a result" signals that the second sentence follows as a consequence of the first, but pamphlets and almanacs circulating widely is not a consequence of the press accelerating scholarly ideas — it is a qualifying observation.',
      B: '"By contrast" sets up a direct opposition between two different subjects or situations, but the sentence is not contrasting a different subject — it is qualifying the first sentence by noting what else happened alongside the intellectual acceleration.',
      C: '"Furthermore" signals that the second sentence adds a point consistent with and reinforcing the first, but the prevalence of sensationalist content complicates rather than supports the prior claim.',
    },
  },

  {
    id: 'sat-f3-rw-m1-q05',
    section: 'reading-writing',
    moduleId: 'f3-rw-module-1',
    domain: 'Expression of Ideas',
    skill: 'Rhetorical Synthesis',
    difficulty: 'easy',
    stimulus: 'A student is writing a paragraph about wetland conservation for an environmental science class. The student has gathered the following notes:\n• Wetlands cover roughly 6% of Earth\'s land surface but store an estimated 20–30% of global soil carbon.\n• Wetland drainage for agriculture has accelerated in the past century, with more than half of the world\'s wetlands lost since 1900.\n• Wetlands filter pollutants from water, reducing the nitrogen and phosphorus that cause algal blooms in rivers and lakes.\n• Coastal wetlands such as mangroves buffer inland areas from storm surges and hurricane-force winds.\n• Wetlands support roughly 40% of the world\'s plant and animal species despite their small total area.',
    question: 'The student wants to argue that wetlands provide benefits that extend well beyond their small geographic footprint. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
    choices: [
      { label: 'A', text: 'Wetlands have been significantly reduced since 1900 due to agricultural drainage, raising concerns about their long-term survival.' },
      { label: 'B', text: 'Although wetlands occupy only a small fraction of Earth\'s surface, they store a disproportionate share of global soil carbon, host roughly 40% of the world\'s species, and provide water filtration and coastal storm protection.' },
      { label: 'C', text: 'Wetlands store carbon and filter pollutants, making them important for climate and water quality, and they have been threatened by agricultural drainage for more than a century.' },
      { label: 'D', text: 'Coastal mangroves protect communities from storm surges, while inland wetlands filter nitrogen and phosphorus from waterways, preventing algal blooms.' },
    ],
    correctAnswer: 'B',
    explanation: 'Choice B directly addresses the goal by contrasting wetlands\' small geographic area with their disproportionately large contributions across multiple categories — carbon storage, biodiversity, water filtration, and storm protection — making the "beyond their footprint" argument explicitly.',
    wrongAnswerExplanations: {
      A: 'Choice A focuses on the loss of wetlands rather than on the benefits they provide, so it does not accomplish the stated goal of arguing for their outsized value.',
      C: 'Choice C includes some benefits but also shifts focus to the threat of drainage, muddying the argument; it does not emphasize the disproportion between small area and large benefit as clearly as Choice B.',
      D: 'Choice D describes only two specific benefits (storm protection and water filtration) and does not make the broader argument about benefits exceeding the geographic footprint.',
    },
  },

  {
    id: 'sat-f3-rw-m1-q26',
    section: 'reading-writing',
    moduleId: 'f3-rw-module-1',
    domain: 'Expression of Ideas',
    skill: 'Rhetorical Synthesis',
    difficulty: 'medium',
    stimulus: 'A student is writing a report on the relationship between sleep duration and academic performance. She has compiled the following notes:\n• A study of 1,500 high school students found that students who slept fewer than six hours per night scored an average of 12 points lower on standardized tests than students who slept eight or more hours.\n• Researchers found that sleep-deprived students showed impaired working memory and slower reaction times on cognitive tasks.\n• Students who maintained consistent sleep schedules — even if total hours varied — performed better than students with irregular sleep patterns.\n• School districts that shifted start times later to allow more sleep reported higher attendance rates and fewer disciplinary incidents.',
    question: 'The student wants to emphasize that inadequate sleep affects both cognitive performance and school-level outcomes. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
    choices: [
      { label: 'A', text: 'Sleep deprivation reduces scores by 12 points, impairs working memory, and slows reaction times, making it the primary cause of academic underperformance in high schools.' },
      { label: 'B', text: 'Students who sleep fewer than six hours score lower on standardized tests and show impaired working memory, suggesting that sleep duration is the most important factor in academic success.' },
      { label: 'C', text: 'Consistent sleep schedules are associated with better performance, and school districts that shifted start times later saw improvements in attendance.' },
      { label: 'D', text: 'Insufficient sleep impairs working memory and reduces standardized test scores, while later school start times — which allow more sleep — have been linked to higher attendance and fewer disciplinary problems.' },
    ],
    correctAnswer: 'D',
    explanation: 'Choice A draws on two categories of evidence: cognitive effects (working memory, standardized test scores) and school-level outcomes (attendance, discipline). This directly fulfills the goal of addressing both types of impact.',
    wrongAnswerExplanations: {
      B: 'This choice focuses only on cognitive/test performance and makes an unsupported claim that sleep is "the most important factor in academic success."',
      C: 'This choice focuses on schedule consistency and attendance — omitting the cognitive performance dimension the goal requires.',
      A: 'This choice focuses only on cognitive and test impacts while asserting sleep is "the primary cause" of underperformance, an overstatement not in the notes.',
    },
  },
]
