import type { MathQuestion } from './types'

export const f4MathModule2HardQuestions: MathQuestion[] = [
  {
    id: 'sat-f4-math-m2h-q06',
    section: 'math',
    moduleId: 'f4-math-module-2-hard',
    domain: 'Algebra',
    skill: 'Linear functions',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'A linear function g satisfies g(−4) = 14 and g(2) = 2. For what value of x does g(x) = 0?',
    choices: [
      { label: 'A', text: '1' },
      { label: 'B', text: '2' },
      { label: 'C', text: '3' },
      { label: 'D', text: '4' },
    ],
    correctAnswer: 'C',
    explanation: 'Find the slope: m = (2 − 14)/(2 − (−4)) = −12/6 = −2. Use the point (2, 2) to find b: 2 = −2(2) + b → b = 6. So g(x) = −2x + 6. Setting g(x) = 0: −2x + 6 = 0 → x = 3.',
    wrongAnswerExplanations: {
      A: 'x = 1 gives g(1) = −2 + 6 = 4, not 0. This error comes from stopping at the slope step and guessing a nearby integer.',
      B: 'x = 2 is one of the given input values (where g(2) = 2), not where g(x) = 0.',
      D: 'x = 4 gives g(4) = −8 + 6 = −2, not 0. This error typically comes from computing the x-intercept formula incorrectly as b/m instead of −b/m.',
    },
  },

  {
    id: 'sat-f4-math-m2h-q22',
    section: 'math',
    moduleId: 'f4-math-module-2-hard',
    domain: 'Algebra',
    skill: 'Systems of two linear equations in two variables',
    difficulty: 'hard',
    type: 'grid_in',
    question: 'In the system of equations below, k is a constant. If the system has no solution, what is the value of k?\n\n4x − 6y = 10\n2x + ky = 8',
    correctAnswer: '-3',
    acceptableAnswers: ['-3'],
    explanation: 'A system of two linear equations has no solution when the lines are parallel — same slope but different y-intercepts. Rewrite the first equation by dividing by 2: 2x − 3y = 5. For the lines to be parallel, the second equation must have the same ratio of x-coefficient to y-coefficient as the first, but a different constant. The first equation in the form 2x − 3y = 5 has coefficient ratio 2 : −3. The second equation 2x + ky = 8 must have the same ratio: k must equal −3. Check that the constants differ: 5 ≠ 8 ✓, so with k = −3 the lines are indeed parallel and the system has no solution.',
  },

  {
    id: 'sat-f4-math-m2h-q01',
    section: 'math',
    moduleId: 'f4-math-module-2-hard',
    domain: 'Algebra',
    skill: 'Systems of two linear equations in two variables',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'The system 6x + 4y = 14 and 3x + 2y = k has infinitely many solutions. What is the value of k?',
    choices: [
      { label: 'A', text: '5' },
      { label: 'B', text: '7' },
      { label: 'C', text: '14' },
      { label: 'D', text: '28' },
    ],
    correctAnswer: 'B',
    explanation: 'Infinitely many solutions means the equations are equivalent. Dividing the first by 2 gives 3x + 2y = 7, which must match 3x + 2y = k, so k = 7.',
    wrongAnswerExplanations: {
      A: 'k = 5 gives a parallel, non-identical line (no solution).',
      C: 'k = 14 keeps the original constant without halving it.',
      D: 'k = 28 doubles the constant instead of matching the reduced equation.',
    },
  },

  {
    id: 'sat-f4-math-m2h-q02',
    section: 'math',
    moduleId: 'f4-math-module-2-hard',
    domain: 'Algebra',
    skill: 'Linear equations in two variables',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Line ℓ passes through (−2, 5) and is perpendicular to the line 3x − y = 7. What is the y-intercept of line ℓ?',
    choices: [
      { label: 'A', text: '11/3' },
      { label: 'B', text: '13/3' },
      { label: 'C', text: '5' },
      { label: 'D', text: '17/3' },
    ],
    correctAnswer: 'B',
    explanation: '3x − y = 7 has slope 3, so the perpendicular slope is −1/3. Line ℓ: y = −(1/3)x + b. Using (−2, 5): 5 = −(1/3)(−2) + b = 2/3 + b → b = 5 − 2/3 = 13/3.',
    wrongAnswerExplanations: {
      A: '11/3 comes from subtracting 2/3 with the wrong sign in the substitution.',
      C: '5 ignores the shift caused by the x = −2 term.',
      D: '17/3 adds 2/3 instead of subtracting it.',
    },
  },

  {
    id: 'sat-f4-math-m2h-q03',
    section: 'math',
    moduleId: 'f4-math-module-2-hard',
    domain: 'Algebra',
    skill: 'Linear equations in one variable',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'If |2x − 7| = 9, what is the sum of all possible values of x?',
    choices: [
      { label: 'A', text: '1' },
      { label: 'B', text: '7' },
      { label: 'C', text: '8' },
      { label: 'D', text: '16' },
    ],
    correctAnswer: 'B',
    explanation: '2x − 7 = 9 → x = 8, or 2x − 7 = −9 → x = −1. The sum is 8 + (−1) = 7.',
    wrongAnswerExplanations: {
      A: '1 is the difference-related value, not the sum of 8 and −1.',
      C: '8 is only one of the two solutions.',
      D: '16 uses only the positive case doubled or ignores x = −1.',
    },
  },

  {
    id: 'sat-f4-math-m2h-q04',
    section: 'math',
    moduleId: 'f4-math-module-2-hard',
    domain: 'Algebra',
    skill: 'Linear inequalities in one or two variables',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'A store sells notebooks for $3 and pens for $2. A customer buys at least 4 notebooks and spends no more than $40 total. If n is the number of notebooks and p is the number of pens, which system represents these constraints?',
    choices: [
      { label: 'A', text: 'n ≥ 4 and 3n + 2p ≤ 40' },
      { label: 'B', text: 'n ≤ 4 and 3n + 2p ≥ 40' },
      { label: 'C', text: 'n ≥ 4 and 2n + 3p ≤ 40' },
      { label: 'D', text: 'n ≥ 4 and 3n + 2p ≥ 40' },
    ],
    correctAnswer: 'A',
    explanation: '"At least 4 notebooks" is n ≥ 4. Notebooks cost $3 each (3n) and pens $2 each (2p); spending "no more than $40" is 3n + 2p ≤ 40.',
    wrongAnswerExplanations: {
      B: '"At least 4" is n ≥ 4, not n ≤ 4, and the cost should be ≤ 40.',
      C: 'This swaps the prices: notebooks are $3 (3n), not $2.',
      D: '"No more than $40" is ≤ 40, not ≥ 40.',
    },
  },

  {
    id: 'sat-f4-math-m2h-q05',
    section: 'math',
    moduleId: 'f4-math-module-2-hard',
    domain: 'Algebra',
    skill: 'Systems of two linear equations in two variables',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'A chemist mixes a 20% acid solution with a 50% acid solution to make 30 liters of a 30% acid solution. How many liters of the 20% solution are used?',
    choices: [
      { label: 'A', text: '10' },
      { label: 'B', text: '15' },
      { label: 'C', text: '20' },
      { label: 'D', text: '25' },
    ],
    correctAnswer: 'C',
    explanation: 'Let x = liters of 20% solution and (30 − x) = liters of 50%. Acid: 0.20x + 0.50(30 − x) = 0.30(30) → 0.20x + 15 − 0.50x = 9 → −0.30x = −6 → x = 20.',
    wrongAnswerExplanations: {
      A: '10 liters of 20% solution gives 0.20(10) + 0.50(20) = 12 L acid = 40%, not 30%.',
      B: '15 liters gives 0.20(15) + 0.50(15) = 10.5 L acid = 35%, not 30%.',
      D: '25 liters gives 0.20(25) + 0.50(5) = 7.5 L acid = 25%, not 30%.',
    },
  },

  {
    id: 'sat-f4-math-m2h-q16',
    section: 'math',
    moduleId: 'f4-math-module-2-hard',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'Percentages',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'A survey of 400 registered voters found that 55% supported a ballot measure. The survey has a margin of error of ±4 percentage points at the 95% confidence level. A political analyst claims that the true level of support among all registered voters is below 50%. Which of the following best evaluates the analyst\'s claim based on the survey results?',
    choices: [
      { label: 'A', text: 'The claim is supported because the margin of error is 4%, which is less than 5%.' },
      { label: 'B', text: 'The claim cannot be supported because the entire confidence interval (51% to 59%) is above 50%.' },
      { label: 'C', text: 'The claim is supported because the sample size of 400 is too small to draw any conclusions.' },
      { label: 'D', text: 'The claim is plausible because the margin of error means the true support could be as low as 51%, which is close to 50%.' },
    ],
    correctAnswer: 'B',
    explanation: 'The survey found 55% support with a margin of error of ±4 points. The 95% confidence interval is therefore 55% − 4% = 51% to 55% + 4% = 59%. Because the entire interval lies above 50%, the data do not support the claim that true support is below 50%; in fact, the results suggest with 95% confidence that a majority of registered voters support the measure.',
    wrongAnswerExplanations: {
      A: 'The size of the margin of error relative to 5% is irrelevant to whether support is below 50%. The interval must be examined, not the margin of error in isolation.',
      C: 'A sample of 400 is a commonly used survey size and is sufficient to produce a meaningful confidence interval; dismissing it as too small is not statistically justified and does not address the analyst\'s specific claim.',
      D: 'The lower bound of the confidence interval is 51%, not below 50%. The claim requires the interval to include values below 50%, but 51% is still above 50%, so the results do not support the claim.',
    },
  },

  {
    id: 'sat-f4-math-m2h-q13',
    section: 'math',
    moduleId: 'f4-math-module-2-hard',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'Two-variable data: models and scatterplots',
    difficulty: 'hard',
    type: 'multiple_choice',
    graphData: {
      type: 'scatter',
      xLabel: 'Temperature (°C)',
      yLabel: 'Sales',
      xMin: 0, xMax: 40, yMin: 0, yMax: 200,
      points: [[5, 40], [10, 70], [15, 95], [20, 120], [25, 150], [30, 170]],
      trendLine: { slope: 5.4, intercept: 12, color: '#4f46e5' },
    },
    question: 'The line of best fit is y = 5.4x + 12. At x = 20°C, the actual sales value is 120. What is the residual (actual − predicted) at this point?',
    choices: [
      { label: 'A', text: '−20' },
      { label: 'B', text: '0' },
      { label: 'C', text: '12' },
      { label: 'D', text: '20' },
    ],
    correctAnswer: 'B',
    explanation: 'Predicted y = 5.4(20) + 12 = 108 + 12 = 120. Residual = actual − predicted = 120 − 120 = 0.',
    wrongAnswerExplanations: {
      A: '−20 would require a predicted value of 140, but the prediction is 120.',
      C: '12 is the intercept, not the residual.',
      D: '20 reverses or mis-scales the difference; the residual is 0.',
    },
  },

  {
    id: 'sat-f4-math-m2h-q14',
    section: 'math',
    moduleId: 'f4-math-module-2-hard',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'Probability and conditional probability',
    difficulty: 'hard',
    type: 'multiple_choice',
    graphData: {
      type: 'table',
      title: 'Test Results by Group',
      headers: ['', 'Pass', 'Fail', 'Total'],
      rows: [
        ['Group A', '36', '14', '50'],
        ['Group B', '48', '2', '50'],
        ['Total', '84', '16', '100'],
      ],
    },
    question: 'A student is selected at random from those who passed. What is the probability that the student is from Group A?',
    choices: [
      { label: 'A', text: '36/50' },
      { label: 'B', text: '36/84' },
      { label: 'C', text: '36/100' },
      { label: 'D', text: '84/100' },
    ],
    correctAnswer: 'B',
    explanation: 'Total who passed = 84. Those from Group A who passed = 36. P(Group A | passed) = 36/84.',
    wrongAnswerExplanations: {
      A: '36/50 conditions on Group A membership, not on passing.',
      C: '36/100 is the fraction of all students who are Group A passers.',
      D: '84/100 is the overall pass rate, not conditioned on Group A.',
    },
  },

  {
    id: 'sat-f4-math-m2h-q15',
    section: 'math',
    moduleId: 'f4-math-module-2-hard',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'One-variable data: distributions and measures of center and spread',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'A set of five numbers has a mean of 20. Four of the numbers are 15, 18, 22, and 24. What is the fifth number?',
    choices: [
      { label: 'A', text: '19' },
      { label: 'B', text: '20' },
      { label: 'C', text: '21' },
      { label: 'D', text: '23' },
    ],
    correctAnswer: 'C',
    explanation: 'The five numbers sum to 5 × 20 = 100. The four known values sum to 15 + 18 + 22 + 24 = 79. The fifth number = 100 − 79 = 21.',
    wrongAnswerExplanations: {
      A: '19 would make the sum 98, giving a mean of 19.6.',
      B: '20 assumes the fifth equals the mean, but the known values do not sum to 80.',
      D: '23 would make the sum 102, giving a mean of 20.4.',
    },
  },

  {
    id: 'sat-f4-math-m2h-q17',
    section: 'math',
    moduleId: 'f4-math-module-2-hard',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'Ratios, rates, proportional relationships, and units',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Two pipes fill a tank. Pipe A alone fills it in 6 hours and Pipe B alone fills it in 3 hours. Working together, how many hours does it take to fill the tank?',
    choices: [
      { label: 'A', text: '1.5' },
      { label: 'B', text: '2' },
      { label: 'C', text: '4.5' },
      { label: 'D', text: '9' },
    ],
    correctAnswer: 'B',
    explanation: 'Combined rate = 1/6 + 1/3 = 1/6 + 2/6 = 3/6 = 1/2 tank per hour. Time = 1 ÷ (1/2) = 2 hours.',
    wrongAnswerExplanations: {
      A: '1.5 would require a combined rate of 2/3 per hour, which is too fast.',
      C: '4.5 averages the two times, which does not model combined work.',
      D: '9 adds the two times, which is incorrect for simultaneous work.',
    },
  },

  {
    id: 'sat-f4-math-m2h-q08',
    section: 'math',
    moduleId: 'f4-math-module-2-hard',
    domain: 'Advanced Math',
    skill: 'Nonlinear functions',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'The function h is defined by h(x) = ax² + b, where a and b are constants. If h(2) = 13 and h(−1) = 4, what is the value of h(3)?',
    choices: [
      { label: 'A', text: '22' },
      { label: 'B', text: '25' },
      { label: 'C', text: '28' },
      { label: 'D', text: '31' },
    ],
    correctAnswer: 'C',
    explanation: 'Set up two equations: h(2) = 4a + b = 13 and h(−1) = a + b = 4. Subtract the second from the first: 3a = 9, so a = 3. Then b = 4 − 3 = 1. Therefore h(x) = 3x² + 1, and h(3) = 3(9) + 1 = 27 + 1 = 28.',
    wrongAnswerExplanations: {
      A: '22 results from finding a = 3 correctly but using b = 4 (forgetting to subtract a): h(3) = 27 − 5 = 22 is a sign error in computing b.',
      B: '25 results from computing h(3) = 3(9) − 2 = 25, which uses b = −2, a common arithmetic mistake when solving the system.',
      D: '31 results from using b = 4 unchanged without solving for it: 3(9) + 4 = 31.',
    },
  },

  {
    id: 'sat-f4-math-m2h-q07',
    section: 'math',
    moduleId: 'f4-math-module-2-hard',
    domain: 'Advanced Math',
    skill: 'Quadratic functions',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'The quadratic equation x² + bx + 25 = 0 has exactly one real solution, and b is negative. What is the value of b?',
    choices: [
      { label: 'A', text: '−25' },
      { label: 'B', text: '−10' },
      { label: 'C', text: '−5' },
      { label: 'D', text: '10' },
    ],
    correctAnswer: 'B',
    explanation: 'One real solution means the discriminant is zero: b² − 4(1)(25) = 0 → b² = 100 → b = ±10. Since b is negative, b = −10.',
    wrongAnswerExplanations: {
      A: '−25 gives a discriminant of 625 − 100 = 525 > 0 (two solutions).',
      C: '−5 gives 25 − 100 = −75 < 0 (no real solutions).',
      D: '10 is positive; the problem requires b negative.',
    },
  },

  {
    id: 'sat-f4-math-m2h-q09',
    section: 'math',
    moduleId: 'f4-math-module-2-hard',
    domain: 'Advanced Math',
    skill: 'Rational and radical expressions',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Which expression is equivalent to (x² − 9)/(x² + 5x + 6) for x ≠ −2, −3, 3?',
    choices: [
      { label: 'A', text: '(x − 3)/(x + 2)' },
      { label: 'B', text: '(x + 3)/(x + 2)' },
      { label: 'C', text: '(x − 3)/(x + 3)' },
      { label: 'D', text: '(x − 9)/(x + 6)' },
    ],
    correctAnswer: 'A',
    explanation: 'Factor: x² − 9 = (x − 3)(x + 3) and x² + 5x + 6 = (x + 2)(x + 3). Cancel (x + 3): (x − 3)/(x + 2).',
    wrongAnswerExplanations: {
      B: 'This cancels the wrong factor; (x − 3) remains in the numerator, not (x + 3).',
      C: 'This cancels (x + 2) instead of (x + 3).',
      D: 'This incorrectly cancels terms rather than factors.',
    },
  },

  {
    id: 'sat-f4-math-m2h-q11',
    section: 'math',
    moduleId: 'f4-math-module-2-hard',
    domain: 'Advanced Math',
    skill: 'Quadratic functions',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'The parabola y = −x² + 6x − 5 has its maximum at the point (h, k). What is the value of k?',
    choices: [
      { label: 'A', text: '3' },
      { label: 'B', text: '4' },
      { label: 'C', text: '5' },
      { label: 'D', text: '9' },
    ],
    correctAnswer: 'B',
    explanation: 'Vertex x-coordinate: h = −6/(2·(−1)) = 3. k = −(3²) + 6(3) − 5 = −9 + 18 − 5 = 4.',
    wrongAnswerExplanations: {
      A: '3 is h (the x-coordinate of the vertex), not k.',
      C: '5 is the constant term, not the maximum value.',
      D: '9 = 6(3) − 9 miscomputes the vertex height.',
    },
  },

  {
    id: 'sat-f4-math-m2h-q12',
    section: 'math',
    moduleId: 'f4-math-module-2-hard',
    domain: 'Advanced Math',
    skill: 'Nonlinear equations in one variable and systems of equations',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'The graphs of y = x² − 2 and y = x intersect at two points. What is the product of the x-coordinates of these points?',
    choices: [
      { label: 'A', text: '−2' },
      { label: 'B', text: '−1' },
      { label: 'C', text: '1' },
      { label: 'D', text: '2' },
    ],
    correctAnswer: 'A',
    explanation: 'Set equal: x² − 2 = x → x² − x − 2 = 0. The product of the roots equals c/a = −2/1 = −2. (The roots are x = 2 and x = −1, product −2.)',
    wrongAnswerExplanations: {
      B: '−1 is one of the roots, not the product.',
      C: '1 is the sum of the roots (2 + (−1)), not the product.',
      D: '2 is one of the roots, not the product.',
    },
  },

  {
    id: 'sat-f4-math-m2h-q21',
    section: 'math',
    moduleId: 'f4-math-module-2-hard',
    domain: 'Advanced Math',
    skill: 'Quadratic functions',
    difficulty: 'hard',
    type: 'grid_in',
    question: 'The quadratic function f(x) = x² + px + 12 has two x-intercepts whose product is 12 and whose sum is 7. What is the value of p?',
    correctAnswer: '-7',
    acceptableAnswers: ['-7'],
    explanation: 'For x² + px + 12, the sum of the roots equals −p and the product equals 12. Since the sum is 7, −p = 7, so p = −7. (The roots are 3 and 4.)',
  },

  {
    id: 'sat-f4-math-m2h-q10',
    section: 'math',
    moduleId: 'f4-math-module-2-hard',
    domain: 'Geometry and Trigonometry',
    skill: 'Right triangles and trigonometry',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'In right triangle ABC, angle C is the right angle. If cos A = 4/5, what is the value of sin A?',
    choices: [
      { label: 'A', text: '3/5' },
      { label: 'B', text: '4/5' },
      { label: 'C', text: '5/4' },
      { label: 'D', text: '5/3' },
    ],
    correctAnswer: 'A',
    explanation: 'By the Pythagorean identity sin²A + cos²A = 1: sin²A = 1 − (4/5)² = 1 − 16/25 = 9/25, so sin A = 3/5 (positive for an acute angle).',
    wrongAnswerExplanations: {
      B: '4/5 is cos A, not sin A.',
      C: '5/4 is the reciprocal of cos A (sec A), not sin A.',
      D: '5/3 is the reciprocal of sin A (csc A), not sin A.',
    },
  },

  {
    id: 'sat-f4-math-m2h-q18',
    section: 'math',
    moduleId: 'f4-math-module-2-hard',
    domain: 'Geometry and Trigonometry',
    skill: 'Circles',
    difficulty: 'hard',
    type: 'grid_in',
    question: 'A circle is defined by the equation x² + y² − 6x + 8y = 0. What is the radius of the circle?',
    correctAnswer: '5',
    acceptableAnswers: ['5'],
    explanation: 'Complete the square: (x² − 6x + 9) + (y² + 8y + 16) = 9 + 16 → (x − 3)² + (y + 4)² = 25. The radius is √25 = 5.',
  },

  {
    id: 'sat-f4-math-m2h-q19',
    section: 'math',
    moduleId: 'f4-math-module-2-hard',
    domain: 'Geometry and Trigonometry',
    skill: 'Right triangles and trigonometry',
    difficulty: 'hard',
    type: 'grid_in',
    graphData: {
      type: 'geometry',
      viewBox: { xMin: -1.5, xMax: 14, yMin: -6, yMax: 6 },
      elements: [
        { kind: 'poly', pts: [[0, 5], [12, 0], [0, 0]] as [number, number][] },
        { kind: 'right_angle', v: [0, 0] as [number, number], a: [12, 0] as [number, number], b: [0, 5] as [number, number] },
        { kind: 'seg', p1: [0, 0] as [number, number], p2: [4.26, -1.78] as [number, number], dashed: true },
        { kind: 'label', x: 6, y: -0.9, text: '12' },
        { kind: 'label', x: -0.9, y: 2.5, text: '5' },
        { kind: 'label', x: 6.5, y: 3, text: '13' },
        { kind: 'label', x: 3, y: -2.6, text: 'h' },
      ],
    },
    question: 'In a right triangle, the two legs have lengths 5 and 12 and the hypotenuse has length 13. What is the length of the altitude drawn from the right angle to the hypotenuse? Round to the nearest hundredth.',
    correctAnswer: '4.62',
    acceptableAnswers: ['4.62'],
    explanation: 'The altitude to the hypotenuse equals (product of the legs)/(hypotenuse) = (5 × 12)/13 = 60/13 ≈ 4.615, which rounds to 4.62. (This follows because both expressions equal twice the triangle\'s area divided by the hypotenuse.)',
    scoringNotes: 'Exact value is 60/13 ≈ 4.6154, rounded to 4.62.',
  },

  {
    id: 'sat-f4-math-m2h-q20',
    section: 'math',
    moduleId: 'f4-math-module-2-hard',
    domain: 'Geometry and Trigonometry',
    skill: 'Area and volume',
    difficulty: 'hard',
    type: 'grid_in',
    question: 'A right circular cylinder has a volume of 96π cubic centimeters and a height of 6 centimeters. What is the radius of the cylinder, in centimeters?',
    correctAnswer: '4',
    acceptableAnswers: ['4'],
    explanation: 'Volume = πr²h → 96π = πr²(6) → r² = 96/6 = 16 → r = 4.',
  },
]
