import type { RWQuestion } from './types'

export const f2RwModule2HardQuestions: RWQuestion[] = [
  {
    id: 'sat2-rw-m2h-004',
    section: 'reading-writing',
    moduleId: 'f2-rw-module-2-hard',
    domain: 'Craft and Structure',
    skill: 'Words in Context',
    difficulty: 'hard',
    stimulus: 'In his 1974 lectures on the philosophy of science, Paul Feyerabend argued that scientific methodology as standardly conceived was not merely insufficient but actively _______ to the advancement of knowledge: the rigid insistence on falsifiability, reproducibility, and controlled experimentation had historically suppressed the very anomalies and theoretical innovations that later proved to be the field\'s most generative contributions.',
    question: 'Which choice completes the text with the most logical and precise word or phrase?',
    choices: [
      { label: 'A', text: 'inimical' },
      { label: 'B', text: 'ancillary' },
      { label: 'C', text: 'indifferent' },
      { label: 'D', text: 'tendentious' },
    ],
    correctAnswer: 'A',
    explanation: '"Inimical" means actively harmful or hostile to something. Feyerabend\'s argument as described is that standard scientific methodology does not merely fail to advance knowledge — it actively works against such advancement by suppressing productive anomalies. "Inimical to the advancement of knowledge" captures this hostility precisely, and is the standard philosophical idiom for this kind of argument.',
    wrongAnswerExplanations: {
      B: '"Ancillary" means subordinate or supplementary, implying a supportive role — the opposite of the harmful relationship Feyerabend describes.',
      C: '"Indifferent to" would mean the methodology neither helps nor harms knowledge advancement — too weak for Feyerabend\'s active opposition claim.',
      D: '"Tendentious" means biased toward a particular point of view, which describes a quality of argumentation, not the relationship between a methodology and an outcome.',
    },
  },

  {
    id: 'sat2-rw-m2h-002',
    section: 'reading-writing',
    moduleId: 'f2-rw-module-2-hard',
    domain: 'Craft and Structure',
    skill: 'Words in Context',
    difficulty: 'hard',
    stimulus: 'In ecology, the concept of a "keystone species" describes an organism whose influence on its ecosystem is _______ to its biomass: the removal of such a species triggers cascading disruptions entirely disproportionate to the animal\'s or plant\'s physical presence in the habitat.',
    question: 'Which choice completes the text with the most logical and precise word or phrase?',
    choices: [
      { label: 'A', text: 'proportional' },
      { label: 'B', text: 'analogous' },
      { label: 'C', text: 'disproportionate' },
      { label: 'D', text: 'subordinate' },
    ],
    correctAnswer: 'C',
    explanation: 'The passage defines keystone species by contrasting their large ecosystem impact with their small physical presence. The influence is "disproportionate to" — far larger than what the biomass would suggest.',
    wrongAnswerExplanations: {
      A: '"Proportional to" would mean the influence scales with size, which contradicts the passage\'s emphasis on impact being larger than expected given the organism\'s biomass.',
      B: '"Analogous to" means similar or comparable, which doesn\'t capture the mismatch between size and impact.',
      D: '"Subordinate to" means lesser than or dependent on, which contradicts the idea of outsized influence.',
    },
  },

  {
    id: 'sat2-rw-m2h-003',
    section: 'reading-writing',
    moduleId: 'f2-rw-module-2-hard',
    domain: 'Craft and Structure',
    skill: 'Words in Context',
    difficulty: 'hard',
    stimulus: 'Despite decades of effort, linguists have found it surprisingly difficult to establish definitive _______ between Proto-Indo-European and any other ancient language family: the proposed connections between PIE and the Kartvelian or Uralic language families remain speculative, supported by only a handful of structural parallels that many specialists consider coincidental.',
    question: 'Which choice completes the text with the most logical and precise word or phrase?',
    choices: [
      { label: 'A', text: 'rivalries' },
      { label: 'B', text: 'cognates' },
      { label: 'C', text: 'genealogical links' },
      { label: 'D', text: 'phonetic distinctions' },
    ],
    correctAnswer: 'C',
    explanation: '"Genealogical links" means ancestral or family-tree relationships between languages — exactly what linguists attempt to establish when connecting language families. The passage describes failed attempts to prove that PIE and other families share a common ancestor.',
    wrongAnswerExplanations: {
      A: '"Rivalries" would describe competitive relationships, not linguistic family connections.',
      B: '"Cognates" are words in different languages with shared ancestry — a narrower concept than the family-level relationships the passage discusses.',
      D: '"Phonetic distinctions" describe differences in sound systems, not ancestral relationships.',
    },
  },

  {
    id: 'sat2-rw-m2h-001',
    section: 'reading-writing',
    moduleId: 'f2-rw-module-2-hard',
    domain: 'Craft and Structure',
    skill: 'Words in Context',
    difficulty: 'hard',
    stimulus: 'The philosopher argued that most political discourse suffers from a kind of conceptual _______ : citizens and politicians alike routinely deploy terms such as "freedom," "equality," and "justice" as though their meanings were self-evident, without acknowledging that these concepts are deeply contested and have been defined differently across centuries and cultures.',
    question: 'Which choice completes the text with the most logical and precise word or phrase?',
    choices: [
      { label: 'A', text: 'incoherence' },
      { label: 'B', text: 'ambiguity' },
      { label: 'C', text: 'parsimony' },
      { label: 'D', text: 'equivocation' },
    ],
    correctAnswer: 'D',
    explanation: '"Equivocation" refers to the use of ambiguous language to conceal the truth or avoid commitment — particularly the use of a word with multiple meanings in a way that misleads. The passage describes political actors using contested terms as though they were fixed, which is precisely equivocation.',
    wrongAnswerExplanations: {
      A: '"Incoherence" suggests logical inconsistency or nonsense, but the passage implies the terms are used coherently — just without acknowledging their contested nature.',
      B: '"Ambiguity" describes having multiple meanings, but the issue the philosopher identifies is not that the terms are ambiguous per se, but that speakers pretend they are not.',
      C: '"Parsimony" means extreme frugality or economy, unrelated to language or conceptual issues.',
    },
  },

  {
    id: 'sat2-rw-m2h-005',
    section: 'reading-writing',
    moduleId: 'f2-rw-module-2-hard',
    domain: 'Craft and Structure',
    skill: 'Text Structure and Purpose',
    difficulty: 'hard',
    stimulus: 'Scholars of medieval music have long debated whether plainchant — the unaccompanied liturgical singing developed in early Christian monasteries — was performed with strict rhythmic regularity or with a more fluid, speech-like delivery. For centuries, performers and editors imposed regular meter on chant, assuming that notation implied rhythm. Recent paleographic analysis of original manuscripts, however, suggests that early notation indicated pitch relationships but made no systematic provision for duration. This finding has prompted renewed interest in performance practices that treat each syllable as metrically free, resulting in a sound substantially different from the chant familiar to modern audiences.',
    question: 'Which choice best describes the overall structure of the passage?',
    choices: [
      { label: 'A', text: 'It introduces a historical debate, describes a long-held assumption, presents new evidence that challenges that assumption, and identifies a resulting shift in practice' },
      { label: 'B', text: 'It defines plainchant, argues that modern performers misunderstand it, and calls for immediate reform in performance practice' },
      { label: 'C', text: 'It presents two equally supported theories about plainchant rhythm and concludes that neither can be proven correct' },
      { label: 'D', text: 'It traces the invention of plainchant notation and explains how it spread through medieval Europe' },
    ],
    correctAnswer: 'A',
    explanation: 'The passage follows this exact structure: (1) states the historical debate about rhythm; (2) notes that performers imposed regular meter; (3) presents new paleographic evidence suggesting notation didn\'t encode duration; (4) describes the resulting renewed interest in freer performance.',
    wrongAnswerExplanations: {
      B: 'The passage does not call for reform — it describes what has happened as a result of new findings.',
      C: 'The passage does not present two equally supported theories; it describes a long-held assumption challenged by new evidence that tips in one direction.',
      D: 'The passage does not trace the invention or geographical spread of chant notation.',
    },
  },

  {
    id: 'sat2-rw-m2h-006',
    section: 'reading-writing',
    moduleId: 'f2-rw-module-2-hard',
    domain: 'Craft and Structure',
    skill: 'Text Structure and Purpose',
    difficulty: 'hard',
    stimulus: 'The philosopher Iris Murdoch insisted that the primary moral task is not the making of dramatic choices but the cultivation of attention — the slow, disciplined effort to see other people clearly and accurately, without the distortions introduced by self-interest or fantasy. Moral failure, on this view, is less often the result of bad choices made at moments of crisis than the consequence of years of habitual misperception: of seeing the world through the lens of one\'s own anxieties, desires, and illusions rather than as it actually is.',
    underlineTargets: ['habitual misperception'],
    question: 'Which choice best describes the function of the underlined phrase in the context of the passage?',
    choices: [
      { label: 'A', text: 'It identifies the specific perceptual errors that Murdoch believes most people make' },
      { label: 'B', text: 'It introduces a concept that the final clause of the passage goes on to explain and exemplify' },
      { label: 'C', text: 'It presents a concession that Murdoch acknowledges before defending her main argument' },
      { label: 'D', text: 'It summarizes Murdoch\'s definition of moral failure as something requiring sudden dramatic correction' },
    ],
    correctAnswer: 'B',
    explanation: '"Habitual misperception" is introduced as the source of moral failure, and the final clause immediately explains what this looks like: "seeing the world through the lens of one\'s own anxieties, desires, and illusions." The phrase is set up and then exemplified.',
    wrongAnswerExplanations: {
      A: 'The phrase names the category; it is the final clause that specifies what the perceptual errors look like.',
      C: 'There is no concession here — the phrase is part of Murdoch\'s positive argument, not a qualification of it.',
      D: 'Murdoch\'s view is that moral failure results from gradual habitual misperception, explicitly contrasted with dramatic crisis moments — not corrected by sudden action.',
    },
  },

  {
    id: 'sat2-rw-m2h-008',
    section: 'reading-writing',
    moduleId: 'f2-rw-module-2-hard',
    domain: 'Craft and Structure',
    skill: 'Cross-Text Connections',
    difficulty: 'hard',
    stimulus: 'Text 1: Proponents of "degrowth" economics argue that the pursuit of endless GDP growth on a finite planet is ecologically unsustainable. They advocate for reducing overall economic output in wealthy nations while improving distribution, arguing that well-being does not require perpetual expansion and that the ecological costs of growth — emissions, habitat loss, resource depletion — far outweigh the benefits.\n\nText 2: Critics of degrowth contend that reducing economic output in wealthy nations would cause significant unemployment and fiscal strain, making social programs that protect the poor harder to fund. They argue that "green growth" — decoupling GDP expansion from carbon emissions through renewable energy and efficiency gains — is a more realistic path that does not require sacrificing material living standards.',
    question: 'A degrowth advocate (Text 1) would most likely respond to the green growth argument in Text 2 by arguing that',
    choices: [
      { label: 'A', text: 'renewable energy is too expensive to replace fossil fuels at scale' },
      { label: 'B', text: 'green growth still relies on the assumption that GDP expansion is compatible with ecological health, an assumption degrowth theory rejects' },
      { label: 'C', text: 'social programs should be funded through degrowth policies that reduce inequality' },
      { label: 'D', text: 'wealthy nations do not actually have higher carbon emissions than developing nations' },
    ],
    correctAnswer: 'B',
    explanation: 'Degrowth advocates challenge the premise of green growth at its root: that GDP can expand sustainably. A degrowth proponent would reject the idea that decoupling growth from emissions is sufficient, since growth itself — regardless of its energy source — drives resource depletion and ecological pressure.',
    wrongAnswerExplanations: {
      A: 'Text 1 does not discuss the cost of renewable energy; making this argument would go beyond what degrowth theory as described would claim.',
      C: 'This is consistent with degrowth theory but does not directly respond to the green growth argument about decoupling.',
      D: 'Text 1 makes no claims about relative emissions between wealthy and developing nations.',
    },
  },

  {
    id: 'sat2-rw-m2h-010',
    section: 'reading-writing',
    moduleId: 'f2-rw-module-2-hard',
    domain: 'Information and Ideas',
    skill: 'Central Ideas and Details',
    difficulty: 'hard',
    stimulus: 'The history of coral reef decline is often narrated as a story of direct anthropogenic harm: dynamite fishing, bleaching from rising sea temperatures, runoff from agricultural fertilizers. But reef ecologists have increasingly argued that this framing, while accurate, obscures a more insidious dynamic. Reefs can tolerate significant individual stressors, but they become catastrophically fragile when multiple stressors interact simultaneously. A reef weakened by thermal bleaching will recover if given adequate time and water quality; a bleached reef additionally subjected to nutrient pollution will recruit far fewer juvenile corals, because the algae that flourish under nutrient enrichment outcompete coral larvae for settlement space. The implication is that targeting any single threat in isolation may prove insufficient if the others remain unaddressed.',
    question: 'Which choice most accurately captures the central claim of the passage?',
    choices: [
      { label: 'A', text: 'Reef ecologists have identified thermal bleaching as the single most damaging threat to coral reef survival.' },
      { label: 'B', text: 'The conventional focus on individual stressors fails to account for how the simultaneous interaction of multiple threats makes coral reefs disproportionately vulnerable.' },
      { label: 'C', text: 'Nutrient pollution from agricultural runoff is a more damaging threat to coral reefs than thermal bleaching or dynamite fishing.' },
      { label: 'D', text: 'Coral reefs have demonstrated remarkable resilience to anthropogenic threats when given adequate recovery time between bleaching events.' },
    ],
    correctAnswer: 'B',
    explanation: 'The passage\'s central claim is not that any single threat is worst, but that the prevailing single-stressor narrative misses the way simultaneous, interacting threats produce a fragility far beyond what each stressor alone would cause. The bleaching-plus-nutrient-pollution example is a supporting detail that illustrates this main point, not the point itself.',
    wrongAnswerExplanations: {
      A: 'The passage explicitly argues against privileging any single stressor; the point is that thermal bleaching alone does not capture the full picture.',
      C: 'The passage names nutrient pollution as one interacting factor in an example; it does not rank threats against each other.',
      D: 'The passage states reefs can recover from bleaching only if given adequate time AND water quality — the conditional clause is critical, and the passage ultimately warns against relying on resilience alone.',
    },
  },

  {
    id: 'sat2-rw-m2h-009',
    section: 'reading-writing',
    moduleId: 'f2-rw-module-2-hard',
    domain: 'Information and Ideas',
    skill: 'Central Ideas and Details',
    difficulty: 'hard',
    stimulus: 'The Younger Dryas was a brief but intense cold period that occurred approximately 12,900 to 11,700 years ago, interrupting the warming trend at the end of the last Ice Age. During this interval, average temperatures in parts of the Northern Hemisphere dropped by as much as 15°C over just a few decades — a rate of cooling far exceeding anything recorded in modern climate data. Paleoecologists have linked the Younger Dryas to the sudden collapse of several early human civilizations and the extinction of megafauna including woolly mammoths, giant ground sloths, and saber-toothed cats. The most widely accepted explanation attributes the cooling to a massive influx of glacial meltwater into the North Atlantic, which disrupted thermohaline circulation and effectively shut down the oceanic heat pump that keeps the Northern Hemisphere warm.',
    question: 'What is the most accurate summary of the passage?',
    choices: [
      { label: 'A', text: 'The Younger Dryas was a prehistoric warming event that caused the extinction of large mammals' },
      { label: 'B', text: 'Scientists are uncertain about the cause of the Younger Dryas and have proposed many competing theories without reaching consensus' },
      { label: 'C', text: 'Modern climate change is occurring at a faster rate than the Younger Dryas and poses greater risks to human civilization' },
      { label: 'D', text: 'The Younger Dryas was a rapid cooling period roughly 12,000 years ago, linked to oceanic circulation disruption, whose effects included societal collapse and megafaunal extinction' },
    ],
    correctAnswer: 'D',
    explanation: 'The passage describes the Younger Dryas as a rapid cooling period (not warming), identifies its cause as disrupted thermohaline circulation, and links it to civilizational collapse and megafaunal extinction. Choice D accurately synthesizes all these elements.',
    wrongAnswerExplanations: {
      A: 'The passage describes a cooling event, not a warming event.',
      C: 'The passage makes no comparison between the Younger Dryas and modern climate change.',
      B: 'The passage explicitly states the "most widely accepted explanation," indicating scientific consensus, not uncertainty.',
    },
  },

  {
    id: 'sat2-rw-m2h-011',
    section: 'reading-writing',
    moduleId: 'f2-rw-module-2-hard',
    domain: 'Information and Ideas',
    skill: 'Command of Evidence',
    difficulty: 'hard',
    stimulus: 'Sociologist Arlie Hochschild introduced the term "emotional labor" to describe the effort required to manage one\'s feelings to fulfill the emotional requirements of a job — smiling at difficult customers, projecting calm during crises, expressing enthusiasm about routine tasks. Hochschild argued that this form of labor is systematically undervalued, particularly in service industries, and falls disproportionately on women and workers in lower-wage jobs.',
    question: 'Which finding would most directly challenge Hochschild\'s claim that emotional labor is systematically undervalued?',
    choices: [
      { label: 'A', text: 'A study finding that jobs requiring high emotional labor are rated as more stressful by workers than jobs requiring low emotional labor' },
      { label: 'B', text: 'Survey data showing that 70% of service workers report performing emotional labor daily' },
      { label: 'C', text: 'Wage data showing that jobs formally classified as requiring high emotional labor consistently pay above-average salaries in the same industry' },
      { label: 'D', text: 'Research showing that emotional labor is more common in female-dominated industries than in male-dominated ones' },
    ],
    correctAnswer: 'C',
    explanation: 'Hochschild\'s claim is that emotional labor is systematically undervalued. If jobs requiring high emotional labor consistently pay above-average salaries, it would suggest that the market does compensate for this form of work — directly challenging the "undervalued" thesis.',
    wrongAnswerExplanations: {
      A: 'Finding that emotional labor causes stress confirms it is burdensome, but doesn\'t address whether it is financially undervalued.',
      B: 'Demonstrating how common emotional labor is says nothing about how it is valued financially.',
      D: 'Confirming the gender skew in emotional labor aligns with Hochschild\'s argument rather than challenging it.',
    },
  },

  {
    id: 'sat2-rw-m2h-012',
    section: 'reading-writing',
    moduleId: 'f2-rw-module-2-hard',
    domain: 'Information and Ideas',
    skill: 'Command of Evidence',
    difficulty: 'hard',
    stimulus: 'A team of public health researchers studied the relationship between neighborhood walkability scores and rates of Type 2 diabetes across 60 urban neighborhoods. Their results are summarized below. The researchers concluded: "Higher neighborhood walkability is associated with lower rates of Type 2 diabetes."',
    graphData: {
      type: 'table',
      title: 'Walkability, Diabetes Prevalence, and Income by Quartile',
      headers: ['Walkability Quartile', 'Average Walkability Score', 'Diabetes Prevalence (%)', 'Median Household Income ($)'],
      rows: [
        ['Q1 (Lowest)', '22', '18.4', '38,200'],
        ['Q2', '48', '14.9', '47,500'],
        ['Q3', '71', '11.2', '59,800'],
        ['Q4 (Highest)', '89', '7.6', '74,100'],
      ],
    },
    question: 'A peer reviewer argues that the data do not necessarily support a causal relationship between walkability and diabetes. Which observation from the data best supports the peer reviewer\'s concern?',
    choices: [
      { label: 'A', text: 'Diabetes prevalence is highest in the lowest-walkability quartile' },
      { label: 'B', text: 'Walkability scores and median household income both increase together across quartiles, making it impossible to isolate walkability as the cause of lower diabetes rates' },
      { label: 'C', text: 'The difference in diabetes prevalence between Q1 and Q4 is approximately 11 percentage points' },
      { label: 'D', text: 'There are only 60 neighborhoods in the study, which may be an insufficient sample' },
    ],
    correctAnswer: 'B',
    explanation: 'The peer reviewer challenges causality. The table shows that income rises in lockstep with walkability across all quartiles. Since income is a known determinant of diabetes risk (via diet, healthcare access, stress), the correlation between walkability and diabetes may actually reflect income differences — a confounding variable that makes causal claims about walkability alone unjustified.',
    wrongAnswerExplanations: {
      A: 'This confirms the correlation but doesn\'t address the causal concern — it supports the researchers\' conclusion, not the peer reviewer\'s critique.',
      C: 'The magnitude of the difference is relevant to the strength of the correlation, not to whether it is causal.',
      D: 'Sample size concerns are valid but are not directly supported by the data in the table.',
    },
  },

  {
    id: 'sat2-rw-m2h-013',
    section: 'reading-writing',
    moduleId: 'f2-rw-module-2-hard',
    domain: 'Information and Ideas',
    skill: 'Command of Evidence',
    difficulty: 'medium',
    stimulus: 'Researchers studying language acquisition claim that children exposed to a richer vocabulary in early childhood develop stronger reading comprehension skills in adolescence. They cite a longitudinal study that followed 800 children from age 3 to age 15.',
    question: 'A student wants to use this research to argue: "Early childhood vocabulary programs should be mandatory in all preschools." Which quotation from the study, if genuine, would most strongly support this policy argument?',
    choices: [
      { label: 'A', text: '"Children in the highest vocabulary-exposure quintile at age 3 scored an average of 28 percentile points higher on reading comprehension tests at age 15 than children in the lowest quintile."' },
      { label: 'B', text: '"Vocabulary acquisition rates vary considerably across individuals and are influenced by numerous genetic and environmental factors."' },
      { label: 'C', text: '"The study controlled for parental education level, household income, and home language environment."' },
      { label: 'D', text: '"Children who attended preschool programs emphasizing oral language and vocabulary scored 31 percentile points higher on adolescent reading assessments than comparable children who did not attend such programs."' },
    ],
    correctAnswer: 'D',
    explanation: 'The policy argument advocates for mandatory preschool vocabulary programs. Choice D provides direct evidence that preschool programs emphasizing vocabulary produced measurable gains in comparable children — the most direct support for this specific institutional intervention.',
    wrongAnswerExplanations: {
      A: 'This shows a correlation between early vocabulary exposure and later outcomes, but doesn\'t specifically demonstrate that preschool programs produce this exposure — it could reflect home environment differences.',
      B: 'Noting that vocabulary acquisition varies complicates rather than supports the case for universal mandates.',
      C: 'Controlling for confounders strengthens the study\'s internal validity but does not directly support the policy claim.',
    },
  },

  {
    id: 'sat2-rw-m2h-014',
    section: 'reading-writing',
    moduleId: 'f2-rw-module-2-hard',
    domain: 'Information and Ideas',
    skill: 'Command of Evidence',
    difficulty: 'medium',
    stimulus: 'An economist studying consumer spending patterns across five income brackets collected data on the percentage of income spent on housing, food, and discretionary purchases. The economist claims: "As income rises, households spend a smaller share of their income on necessities and a larger share on discretionary purchases."',
    graphData: {
      type: 'table',
      title: 'Consumer Spending Shares by Income Bracket',
      headers: ['Income Bracket', '% Spent on Housing', '% Spent on Food', '% Discretionary'],
      rows: [
        ['Under $30K', '42', '24', '8'],
        ['$30K–$60K', '33', '19', '16'],
        ['$60K–$100K', '28', '15', '23'],
        ['$100K–$200K', '22', '12', '31'],
        ['Over $200K', '14', '8', '45'],
      ],
    },
    question: 'Which choice most accurately characterizes the support the data provides for the economist\'s claim?',
    choices: [
      { label: 'A', text: 'The data fully supports the claim; both housing and food percentages decline at every income level while discretionary spending rises' },
      { label: 'B', text: 'The data partially supports the claim; food spending decreases but housing spending remains constant' },
      { label: 'C', text: 'The data does not support the claim; discretionary spending percentages remain roughly equal across all income brackets' },
      { label: 'D', text: 'The data supports the claim about housing but contradicts it for food, which increases with income' },
    ],
    correctAnswer: 'A',
    explanation: 'Looking at the table: housing percentages fall from 42% to 14%; food percentages fall from 24% to 8%; and discretionary spending rises from 8% to 45% — all at every income step. The data fully supports the claim.',
    wrongAnswerExplanations: {
      B: 'Housing does decrease at every income level (42, 33, 28, 22, 14), not remain constant.',
      C: 'Discretionary spending clearly rises from 8% to 45% across brackets.',
      D: 'Food spending decreases with income (24% down to 8%), not increases.',
    },
  },

  {
    id: 'sat2-rw-m2h-015',
    section: 'reading-writing',
    moduleId: 'f2-rw-module-2-hard',
    domain: 'Information and Ideas',
    skill: 'Inferences',
    difficulty: 'medium',
    stimulus: 'Anthropologists studying gift exchange in non-market societies have observed that gifts rarely function as simple transfers of goodwill. Among the Kwakwaka\'wakw peoples of the Pacific Northwest, potlatch ceremonies involve elaborate gift-giving in which chiefs distribute or even destroy vast quantities of goods. The generosity displayed is not purely altruistic: it asserts social rank, creates obligations of reciprocity in recipients, and converts material wealth into social capital. A chief who gives more than his rivals gains prestige precisely because his rivals cannot easily match the gesture.',
    question: 'What can be most reasonably inferred from the passage about the relationship between generosity and power in potlatch ceremonies?',
    choices: [
      { label: 'A', text: 'Chiefs who participate in potlatches are motivated purely by a desire to improve the material conditions of community members' },
      { label: 'B', text: 'Generosity in potlatch ceremonies functions as a competitive strategy that converts material wealth into social and political status' },
      { label: 'C', text: 'The destruction of goods during potlatches indicates that Kwakwaka\'wakw chiefs have no interest in material wealth' },
      { label: 'D', text: 'Potlatch ceremonies are a form of trade in which goods are exchanged for equivalent goods of equal value' },
    ],
    correctAnswer: 'B',
    explanation: 'The passage describes potlatch generosity as assigning social rank, creating obligations, and converting material wealth into social capital — with competitive advantage going to whoever gives most. The inference is that generosity is a competitive tool for gaining status.',
    wrongAnswerExplanations: {
      A: 'The passage explicitly states generosity "is not purely altruistic" — it serves the chief\'s social position.',
      C: 'Destroying goods demonstrates excess wealth, thereby enhancing prestige — it does not indicate indifference to wealth.',
      D: 'Potlatches involve one-directional giving and status assertion, not equivalent exchange.',
    },
  },

  {
    id: 'sat2-rw-m2h-016',
    section: 'reading-writing',
    moduleId: 'f2-rw-module-2-hard',
    domain: 'Information and Ideas',
    skill: 'Inferences',
    difficulty: 'hard',
    stimulus: 'A central challenge in the history of science is explaining why some accurate scientific ideas are rejected by contemporaries while obviously wrong ideas are widely accepted for centuries. Historian of science Naomi Oreskes notes that scientific consensus is not simply the aggregate of individual expert opinions but a social phenomenon shaped by institutional structures, funding priorities, and ideological commitments. Ideas that challenge dominant paradigms often require not just new evidence but new institutional support — champions with prestige, journals willing to publish, and funders willing to pay for the next generation of experiments.',
    question: 'What can be most reasonably inferred from Oreskes\' analysis about why paradigm-challenging ideas are sometimes delayed in gaining acceptance?',
    choices: [
      { label: 'A', text: 'Scientists who propose new ideas often lack the intellectual capacity to defend them against criticism' },
      { label: 'B', text: 'Accurate scientific ideas always eventually gain acceptance once sufficient evidence accumulates, regardless of institutional context' },
      { label: 'C', text: 'Scientific journals are primarily responsible for preventing new ideas from gaining acceptance' },
      { label: 'D', text: 'The acceptance of scientific ideas depends not only on the quality of evidence but also on social and institutional factors that can slow or accelerate recognition' },
    ],
    correctAnswer: 'D',
    explanation: 'Oreskes\' argument is that scientific consensus is a social phenomenon shaped by institutions, funding, and ideology — not just evidence. The inference is that social and institutional factors, beyond evidence quality, determine whether ideas gain acceptance and how quickly.',
    wrongAnswerExplanations: {
      A: 'Oreskes attributes delays to institutional barriers, not to scientists\' intellectual limitations.',
      C: 'Oreskes mentions journals as one factor among several — prestige, funding, and institutional support are equally cited.',
      B: 'Oreskes\' analysis implies that institutional support is necessary, suggesting that evidence alone is insufficient — contradicting this claim.',
    },
  },

  {
    id: 'sat2-rw-m2h-025',
    section: 'reading-writing',
    moduleId: 'f2-rw-module-2-hard',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'medium',
    stimulus: 'Neither the lead investigator nor the three graduate students who conducted the fieldwork _______ able to explain why the sediment cores from the western transect produced readings so dramatically inconsistent with those from the eastern sites.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choices: [
      { label: 'A', text: 'were' },
      { label: 'B', text: 'was' },
      { label: 'C', text: 'are being' },
      { label: 'D', text: 'have been' },
    ],
    correctAnswer: 'A',
    explanation: 'With "neither...nor" constructions, the verb agrees with the subject closest to it — here, "the three graduate students," which is plural. Therefore the plural verb "were" is correct. The intervening relative clause "who conducted the fieldwork" modifies "students" but does not change the subject of the main clause.',
    wrongAnswerExplanations: {
      B: '"Was" would agree with the lead investigator (singular), but in "neither...nor" constructions the verb agrees with the nearer subject — "the three graduate students" — which requires a plural verb.',
      C: '"Are being" is present progressive and inconsistent with the past-tense context established by "conducted."',
      D: '"Have been" is present perfect, which would imply the inability to explain is an ongoing state into the present; the context describes a specific past situation.',
    },
  },

  {
    id: 'sat2-rw-m2h-027',
    section: 'reading-writing',
    moduleId: 'f2-rw-module-2-hard',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'medium',
    stimulus: 'The selection committee had narrowed the candidates to three finalists; _______ of whom had the technical expertise the position required, but only one had both the experience and the interpersonal skills the team considered essential.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choices: [
      { label: 'A', text: 'all' },
      { label: 'B', text: 'every' },
      { label: 'C', text: 'each' },
      { label: 'D', text: 'either' },
    ],
    correctAnswer: 'A',
    explanation: '"All of whom" correctly refers to the entirety of a group of three — establishing that all three had the technical expertise before the contrast ("but only one") is introduced. "All" is the only choice that works with "of whom" for a group of three.',
    wrongAnswerExplanations: {
      B: '"Every" is not used with "of whom" in standard construction; "every one of whom" would be grammatically possible but nonstandard here.',
      C: '"Each of whom" would work grammatically, but "all of whom" is the more natural choice when establishing a universal quality across a group before introducing a distinction.',
      D: '"Either of whom" is used for a group of exactly two, but the sentence specifies three finalists.',
    },
  },

  {
    id: 'sat2-rw-m2h-026',
    section: 'reading-writing',
    moduleId: 'f2-rw-module-2-hard',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'medium',
    stimulus: 'When the research team first _______ the anomalous readings in the dataset, they assumed a calibration error; only after repeating the experiment under controlled conditions did they conclude that the results were genuine.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choices: [
      { label: 'A', text: 'encounter' },
      { label: 'B', text: 'had encountered' },
      { label: 'C', text: 'encountered' },
      { label: 'D', text: 'were encountering' },
    ],
    correctAnswer: 'C',
    explanation: 'The sentence describes a sequence of past events: first the team encountered readings, then assumed a calibration error, then later concluded the results were genuine. The simple past "encountered" correctly describes the initial action in this past-event sequence.',
    wrongAnswerExplanations: {
      A: '"Encounter" is present tense, inconsistent with the past-tense narrative.',
      B: '"Had encountered" (past perfect) would be appropriate only if this action preceded another past event that is the narrative focus — but the sentence\'s temporal markers ("when...first") already establish the sequence without requiring past perfect.',
      D: '"Were encountering" (past progressive) implies the action was ongoing when interrupted, but the sentence implies a discrete initial discovery.',
    },
  },

  {
    id: 'sat2-rw-m2h-022',
    section: 'reading-writing',
    moduleId: 'f2-rw-module-2-hard',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'medium',
    stimulus: 'The expedition\'s lead geologist, having spent fourteen months mapping the canyon system and identifying the stratigraphic anomalies that suggested ancient volcanic activity, presented her findings to the review panel, however, several panel members questioned whether the thin ash layers she had identified were of volcanic origin or merely the result of windblown mineral deposits from adjacent desert formations.',
    question: 'Which choice best corrects the punctuation error in the sentence?',
    choices: [
      { label: 'A', text: '...presented her findings to the review panel; however, several panel members questioned...' },
      { label: 'B', text: '...presented her findings to the review panel, however several panel members questioned...' },
      { label: 'C', text: '...presented her findings to the review panel. However several panel members questioned...' },
      { label: 'D', text: '...presented her findings to the review panel — however, several panel members questioned...' },
    ],
    correctAnswer: 'A',
    explanation: '"However" is a conjunctive adverb joining two independent clauses: (1) the geologist presented her findings; (2) panel members questioned her interpretation. A conjunctive adverb joining two independent clauses must be preceded by a semicolon and followed by a comma. Choice A provides exactly this punctuation: semicolon before "however," comma after.',
    wrongAnswerExplanations: {
      B: 'A comma before "however" when it joins two independent clauses creates a comma splice, which is a sentence boundary error.',
      C: 'A period before "However" correctly ends the first sentence, but "however" as a conjunctive adverb at the start of a sentence must be followed by a comma — omitting it is a punctuation error.',
      D: 'An em dash can introduce a sharp break or elaboration, but it cannot substitute for the semicolon required when a conjunctive adverb joins two independent clauses; this choice also retains the comma after "however," which would be correct placement if the semicolon were used instead of the dash.',
    },
  },

  {
    id: 'sat2-rw-m2h-023',
    section: 'reading-writing',
    moduleId: 'f2-rw-module-2-hard',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'medium',
    stimulus: 'The architect\'s design was groundbreaking, incorporating sustainable materials and passive cooling techniques that had never before been used in a commercial building of this scale, nevertheless, the city planning board rejected it on the grounds that it did not conform to the neighborhood\'s historical aesthetic guidelines.',
    question: 'Which choice best corrects the punctuation in the sentence?',
    choices: [
      { label: 'A', text: '...building of this scale; nevertheless, the city planning board rejected it...' },
      { label: 'B', text: '...building of this scale, nevertheless the city planning board rejected it...' },
      { label: 'C', text: '...building of this scale, nevertheless; the city planning board rejected it...' },
      { label: 'D', text: '...building of this scale. Nevertheless the city planning board rejected it...' },
    ],
    correctAnswer: 'A',
    explanation: '"Nevertheless" is a conjunctive adverb. It must be preceded by a semicolon (or period) when it joins two independent clauses, and followed by a comma. The correct form is: "...scale; nevertheless, the city planning board rejected it..."',
    wrongAnswerExplanations: {
      B: 'A comma before a conjunctive adverb joining two independent clauses creates a comma splice.',
      C: 'A comma before and a semicolon after "nevertheless" inverts the required punctuation pattern.',
      D: 'A period before "Nevertheless" is grammatically correct, but the absence of a comma after "Nevertheless" is nonstandard for this conjunctive adverb usage.',
    },
  },

  {
    id: 'sat2-rw-m2h-024',
    section: 'reading-writing',
    moduleId: 'f2-rw-module-2-hard',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'hard',
    stimulus: 'The discovery of the Rosetta Stone in 1799, which bore the same decree in Ancient Egyptian hieroglyphics, Demotic script, and Ancient Greek — languages that allowed scholars for the first time to decode a writing system that had been unreadable for more than 1,400 years.',
    question: 'Which choice best corrects the sentence?',
    choices: [
      { label: 'A', text: 'The discovery of the Rosetta Stone in 1799, which bore the same decree in three scripts, allowed scholars to decode hieroglyphics for the first time in over 1,400 years.' },
      { label: 'B', text: 'The discovery of the Rosetta Stone in 1799 bore the same decree in Ancient Egyptian hieroglyphics, Demotic script, and Ancient Greek.' },
      { label: 'C', text: 'The Rosetta Stone was discovered in 1799, it bore the same decree in three scripts, which allowed scholars to decode hieroglyphics.' },
      { label: 'D', text: 'Discovered in 1799, the Rosetta Stone bore the same decree in Ancient Egyptian hieroglyphics, Demotic script, and Ancient Greek, allowing scholars to decode a writing system unreadable for 1,400 years.' },
    ],
    correctAnswer: 'D',
    explanation: 'The original is a sentence fragment — the subject "The discovery of the Rosetta Stone" and the relative clause "which bore..." never receive a main verb. Choice D restructures cleanly: subject (the Rosetta Stone) + past tense verb (bore) + participial phrase for the result (allowing scholars...).',
    wrongAnswerExplanations: {
      A: 'Also corrects the fragment adequately, but Choice D preserves more of the original\'s detail about the three scripts.',
      B: 'This corrects the fragment but omits the crucial information about what the discovery enabled (decoding hieroglyphics).',
      C: 'This creates a comma splice between the first two clauses.',
    },
  },

  {
    id: 'sat2-rw-m2h-007',
    section: 'reading-writing',
    moduleId: 'f2-rw-module-2-hard',
    domain: 'Expression of Ideas',
    skill: 'Transitions',
    difficulty: 'hard',
    stimulus: 'Historians of technology have shown that the social conditions surrounding an invention often determine its form as much as technical constraints do. The telephone, for instance, was initially promoted as a tool for broadcasting music and news to subscribers before its potential as a two-way communication device was recognized. _______ the uses to which technologies are ultimately put reflect the priorities and assumptions of the institutions that commercialize them rather than any inherent logic of the technology itself.',
    question: 'Which choice completes the text with the most logical transition?',
    choices: [
      { label: 'A', text: 'In other words,' },
      { label: 'B', text: 'Still,' },
      { label: 'C', text: 'Subsequently,' },
      { label: 'D', text: 'Likewise,' },
    ],
    correctAnswer: 'A',
    explanation: 'The third sentence restates the passage\'s opening claim — that social conditions shape technology — now rephrased as a general principle after the telephone example has illustrated it. "In other words" correctly signals that the final sentence is a reformulation or clarification of the argument already made, drawing together the opening claim and the illustrative example.',
    wrongAnswerExplanations: {
      B: 'Choice B is incorrect. "Still" introduces a concession or qualification, implying that something unexpected follows despite what was just said; the final sentence is not a concession but a logical synthesis of the preceding material.',
      C: 'Choice C is incorrect. "Subsequently" signals temporal sequence, indicating that one event followed another in time; the final sentence is a conceptual conclusion, not a later event in a chronology.',
      D: 'Choice D is incorrect. "Likewise" introduces a parallel example comparable to the telephone case, but the final sentence does not present a new example — it draws a general conclusion from the example already given.',
    },
  },

  {
    id: 'sat2-rw-m2h-020',
    section: 'reading-writing',
    moduleId: 'f2-rw-module-2-hard',
    domain: 'Expression of Ideas',
    skill: 'Transitions',
    difficulty: 'hard',
    stimulus: 'Proponents of strict constructionism argue that judges should interpret the Constitution solely according to the text\'s original public meaning at the time of ratification, insulating legal interpretation from the political preferences of the judiciary. Critics counter that many constitutional provisions — "equal protection," "cruel and unusual punishment," "due process" — are deliberately general, requiring judges to exercise interpretive judgment regardless of their preferred methodology. _______ originalists do not avoid discretion so much as relocate it: from disputes about contemporary values to disputes about historical evidence, a domain that is itself deeply contested among historians.',
    question: 'Which choice completes the text with the most logical transition?',
    choices: [
      { label: 'A', text: 'Furthermore,' },
      { label: 'B', text: 'By contrast,' },
      { label: 'C', text: 'As a result,' },
      { label: 'D', text: 'In this light,' },
    ],
    correctAnswer: 'D',
    explanation: '"In this light" signals that what follows is a reinterpretation or reassessment of the preceding argument given the perspective just established. The critics\' observation (that constitutional provisions require judgment anyway) reframes the originalist claim — and "in this light" correctly marks that the third sentence draws an interpretive conclusion from the critics\' point. It is neither a simple contrast, a causal consequence, nor an addition.',
    wrongAnswerExplanations: {
      A: '"Furthermore" would add another supporting point in the same direction, but the third sentence does not extend the critics\' objection — it draws a specific conclusion from it, requiring a transition that marks inference rather than accumulation.',
      B: '"By contrast" would introduce an opposing view, but the third sentence does not contradict the critics\' point — it develops and sharpens it.',
      C: '"As a result" implies strict causation, but the third sentence is an interpretive inference (a reassessment of what originalism accomplishes) rather than a direct consequence of the critics\' argument.',
    },
  },

  {
    id: 'sat2-rw-m2h-021',
    section: 'reading-writing',
    moduleId: 'f2-rw-module-2-hard',
    domain: 'Expression of Ideas',
    skill: 'Transitions',
    difficulty: 'hard',
    stimulus: 'Archaeological evidence suggests that the first cultivated crops appeared in the Fertile Crescent of the Middle East approximately 10,000 years ago. _______ the transition from hunter-gatherer subsistence to settled agriculture was not a rapid or deliberate revolution but a gradual, uneven process that unfolded over millennia and proceeded at different rates in different regions.',
    question: 'Which choice completes the text with the most logical transition?',
    choices: [
      { label: 'A', text: 'Therefore,' },
      { label: 'B', text: 'Subsequently,' },
      { label: 'C', text: 'However,' },
      { label: 'D', text: 'Consequently,' },
    ],
    correctAnswer: 'C',
    explanation: '"However" signals a qualification or complication of what was just stated. The first sentence locates the origin of cultivation; the second complicates the implied picture of a clean, dateable "agricultural revolution" by describing gradualness and unevenness.',
    wrongAnswerExplanations: {
      A: '"Therefore" would imply the second sentence is a logical conclusion of the first, but the second sentence complicates rather than follows from the first.',
      B: '"Subsequently" signals temporal sequence — that the second event came after the first — but the second sentence describes the nature of the transition, not an event that followed it.',
      D: '"Consequently" implies the second statement is a consequence or result of the first, which does not capture the qualifying relationship.',
    },
  },

  {
    id: 'sat2-rw-m2h-019',
    section: 'reading-writing',
    moduleId: 'f2-rw-module-2-hard',
    domain: 'Expression of Ideas',
    skill: 'Rhetorical Synthesis',
    difficulty: 'hard',
    stimulus: 'A student is writing an essay arguing that the historical narrative surrounding the Green Revolution needs to be revised. The student has gathered the following notes:\n\n• Between 1960 and 1990, the Green Revolution introduced high-yield crop varieties and synthetic fertilizers in South and Southeast Asia, and grain production roughly tripled in the region.\n• Economists Amartya Sen and Jean Drèze found that aggregate food production increases did not consistently reduce hunger in the poorest populations, because access to food depends on purchasing power and distribution networks, not only supply.\n• The intensified use of irrigation during the Green Revolution contributed to severe groundwater depletion in Punjab (India) and parts of Pakistan, with some aquifers now projected to run dry within decades.\n• A 2019 meta-analysis of Green Revolution outcomes found that while caloric availability increased broadly, diet diversity declined as smallholder farmers shifted entirely to monoculture cash crops, increasing micronutrient deficiency rates in several countries.',
    question: 'The student wants to argue that the Green Revolution\'s legacy is more complicated than the traditional "success story" narrative suggests, using specific evidence from the notes to illustrate both its achievements and its unintended consequences. Which choice best accomplishes this goal?',
    choices: [
      { label: 'A', text: 'The Green Revolution tripled grain production in Asia between 1960 and 1990, but this achievement did not benefit the poorest populations, who lacked the purchasing power to access increased food supplies.' },
      { label: 'B', text: 'While the Green Revolution dramatically expanded caloric availability and averted famine at scale, it simultaneously produced groundwater depletion, declining diet diversity, and persistent hunger among the poorest populations — consequences that complicate any straightforward account of it as an unqualified success.' },
      { label: 'C', text: 'The Green Revolution caused more harm than good: by promoting monoculture and depleting aquifers, it sacrificed long-term food security for short-term production gains.' },
      { label: 'D', text: 'Economists Sen and Drèze showed that the Green Revolution failed to reduce hunger, which suggests that food security requires distribution reform, not production increases.' },
    ],
    correctAnswer: 'B',
    explanation: 'The task requires acknowledging the Green Revolution\'s achievements while using specific evidence to show unintended consequences. Choice B is the only option that (1) credits the production gains, (2) cites multiple specific negative consequences drawn from at least three of the four notes (hunger persistence, groundwater depletion, diet diversity), and (3) frames these together as complicating — not simply negating — the traditional narrative.',
    wrongAnswerExplanations: {
      A: 'Choice A draws on only two of the notes and omits the environmental and nutritional consequences entirely, giving an incomplete account of the complications the student wants to illustrate.',
      C: 'Choice C overstates the negative case by claiming the Green Revolution caused "more harm than good," a claim the notes do not support — they show genuine production gains alongside serious drawbacks.',
      D: 'Choice D presents a single-source conclusion (Sen and Drèze) and pivots to a policy prescription about distribution reform, which goes beyond what the notes establish and ignores the environmental and nutritional data.',
    },
  },

  {
    id: 'sat2-rw-m2h-017',
    section: 'reading-writing',
    moduleId: 'f2-rw-module-2-hard',
    domain: 'Expression of Ideas',
    skill: 'Rhetorical Synthesis',
    difficulty: 'hard',
    stimulus: 'A student is writing an essay examining the debate over nuclear energy\'s role in addressing climate change. The student has gathered the following notes:\n\n• Nuclear power plants produce no direct carbon emissions during operation and currently supply about 10% of global electricity.\n• The Intergovernmental Panel on Climate Change (IPCC) lists nuclear energy as one of several low-carbon technologies that could help limit warming to 1.5°C.\n• The levelized cost of new nuclear plants has increased significantly in recent decades, with recent projects in Western countries running billions of dollars over budget.\n• Solar and wind power costs have fallen by more than 90% since 2010 and are now cheaper per kilowatt-hour than new nuclear in most markets.\n• Nuclear waste disposal remains an unresolved problem in most countries, with no permanent storage solution in operation.',
    question: 'The student wants to present a balanced assessment of nuclear energy\'s climate potential that acknowledges both its advantages and its limitations. Which choice best accomplishes this?',
    choices: [
      { label: 'A', text: 'Nuclear energy is a clean, proven technology that should be rapidly expanded to address climate change.' },
      { label: 'B', text: 'Although nuclear energy produces no direct carbon emissions and is endorsed by the IPCC as a climate solution, its high and rising costs, competition from cheaper renewables, and unresolved waste storage issues raise serious questions about its scalability.' },
      { label: 'C', text: 'Nuclear energy is too expensive and dangerous to play any meaningful role in addressing climate change.' },
      { label: 'D', text: 'The IPCC\'s endorsement of nuclear energy means that it should be prioritized over solar and wind in climate policy.' },
    ],
    correctAnswer: 'B',
    explanation: 'Choice B presents genuine balance: it acknowledges nuclear\'s zero-carbon operation and IPCC endorsement (advantages) while accurately citing rising costs, cheaper renewables, and waste storage as significant limitations. This is a direct and fair synthesis of the notes.',
    wrongAnswerExplanations: {
      A: 'This is one-sided — it presents only advantages without engaging with the cost, competition, or waste concerns.',
      C: 'This is one-sided in the opposite direction and overstates the case against nuclear by calling it "too dangerous," which the notes don\'t support.',
      D: 'This misrepresents the IPCC position (it lists nuclear as one of several options, not as a priority) and ignores the cost disadvantage relative to renewables.',
    },
  },

  {
    id: 'sat2-rw-m2h-018',
    section: 'reading-writing',
    moduleId: 'f2-rw-module-2-hard',
    domain: 'Expression of Ideas',
    skill: 'Rhetorical Synthesis',
    difficulty: 'hard',
    stimulus: 'A student is writing a research paper examining whether urban farming can meaningfully contribute to food security in large cities. The student has gathered the following notes:\n\n• A 2022 global analysis found that urban farms in 100 cities collectively produced enough food to meet less than 2% of those cities\' caloric needs, even under optimistic land-use assumptions.\n• Urban farms have significant co-benefits: they reduce stormwater runoff, lower urban heat, provide community green space, and improve mental health outcomes for participants.\n• In cities like Singapore and Shenzhen, vertical farming using artificial lighting is being scaled to produce leafy greens year-round at commercially competitive prices.\n• Critics of urban farming note that the energy costs of indoor farming under artificial lighting can exceed the carbon savings achieved by reducing food transport distances.',
    question: 'The student wants to argue that urban farming has value despite its limited direct contribution to caloric food security. Which choice most effectively supports this claim?',
    choices: [
      { label: 'A', text: 'Urban farming is unlikely to solve food security challenges given that it currently meets less than 2% of caloric needs even in the most optimistic scenarios.' },
      { label: 'B', text: 'Although urban farming cannot realistically replace conventional food systems as a primary caloric source, its documented environmental and community health benefits justify investment and expansion as a complementary strategy.' },
      { label: 'C', text: 'Singapore and Shenzhen demonstrate that with enough investment, urban farming can eventually meet the full caloric needs of large cities.' },
      { label: 'D', text: 'The carbon costs of indoor farming lighting make it an ineffective climate strategy, undermining the case for urban farming expansion.' },
    ],
    correctAnswer: 'B',
    explanation: 'The task is to argue that urban farming has value despite limited caloric contribution. Choice B acknowledges the 2% limitation honestly while making the affirmative case using the documented co-benefits (environmental, community health) — exactly the synthesis the task requires.',
    wrongAnswerExplanations: {
      A: 'This concedes the limitation but makes no affirmative case for value, failing the task of arguing for urban farming despite the limitation.',
      C: 'The notes don\'t support this claim; Singapore/Shenzhen examples involve leafy greens at competitive prices, not meeting full caloric needs.',
      D: 'This argues against urban farming and undermines rather than supports the student\'s intended claim.',
    },
  },
]
