import type { MathQuestion } from './types'

export const f3MathModule2HardQuestions: MathQuestion[] = [
  // ── Algebra (7) ───────────────────────────────────────────────────────────
  {
    id: 'sat-f3-math-m2h-q01',
    section: 'math',
    moduleId: 'f3-math-module-2-hard',
    domain: 'Geometry and Trigonometry',
    skill: 'Circles',
    difficulty: 'hard',
    type: 'multiple_choice',
    graphData: {
      type: 'geometry',
      viewBox: { xMin: -5.5, xMax: 11.5, yMin: -7.5, yMax: 3.5 },
      elements: [
        { kind: 'seg', p1: [-5, 0] as [number, number], p2: [11, 0] as [number, number] },
        { kind: 'seg', p1: [0, -7] as [number, number], p2: [0, 3.3] as [number, number] },
        { kind: 'label', x: 10.5, y: 0, text: 'x', dy: -9, anchor: 'start', size: 10, weight: '600' },
        { kind: 'label', x: 0, y: 3.2, text: 'y', dx: 8, size: 10, weight: '600' },
        { kind: 'label', x: 5, y: 0, text: '5', dy: 13, size: 9 },
        { kind: 'label', x: -5, y: 0, text: '−5', dy: 13, size: 9 },
        { kind: 'label', x: 0, y: -5, text: '−5', dx: -6, anchor: 'end', size: 9 },
        { kind: 'label', x: 0, y: 3, text: '3', dx: -6, anchor: 'end', size: 9 },
        { kind: 'circle', cx: 3, cy: -2, r: 5 },
        { kind: 'point', x: 3, y: -2, label: '(3, −2)', dx: 8, dy: -10 },
      ],
    },
    question: 'The equation x² + y² − 6x + 4y = 12 represents a circle in the xy-plane. What is the radius of the circle?',
    choices: [
      { label: 'A', text: '3' },
      { label: 'B', text: '4' },
      { label: 'C', text: '5' },
      { label: 'D', text: '√21' },
    ],
    correctAnswer: 'C',
    explanation: 'Complete the square for both variables. Group and add: (x² − 6x + 9) + (y² + 4y + 4) = 12 + 9 + 4, giving (x − 3)² + (y + 2)² = 25. The radius is √25 = 5.',
    wrongAnswerExplanations: {
      A: '3 is the x-coordinate of the center (x − 3)², not the radius.',
      B: '4 is related to the y-coefficient; the right side is 25, giving radius √25 = 5, not 4.',
      D: '√21 = √(12 + 9) omits the +4 that comes from completing the square on the y terms.',
    },
  },
  {
    id: 'sat-f3-math-m2h-q02',
    section: 'math',
    moduleId: 'f3-math-module-2-hard',
    domain: 'Algebra',
    skill: 'Systems of two linear equations in two variables',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'In the system below, what is the value of x − y?\n\n5x + 2y = 19\n3x − 2y = 5',
    choices: [
      { label: 'A', text: '1' },
      { label: 'B', text: '2' },
      { label: 'C', text: '3' },
      { label: 'D', text: '4' },
    ],
    correctAnswer: 'A',
    explanation: 'Add the two equations: (5x + 2y) + (3x − 2y) = 19 + 5 → 8x = 24 → x = 3. Substitute into 3x − 2y = 5: 9 − 2y = 5 → y = 2. Therefore x − y = 3 − 2 = 1.',
    wrongAnswerExplanations: {
      B: 'x − y = 2 would require y = 1, but substituting back: 5(3) + 2(1) = 17 ≠ 19.',
      C: 'x − y = 3 would require y = 0, but 5(3) + 2(0) = 15 ≠ 19.',
      D: 'x − y = 4 would require y = −1, but 5(3) + 2(−1) = 13 ≠ 19.',
    },
  },
  {
    id: 'sat-f3-math-m2h-q03',
    section: 'math',
    moduleId: 'f3-math-module-2-hard',
    domain: 'Algebra',
    skill: 'Linear functions',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Line p is perpendicular to the line y = (2/5)x − 3 and passes through the point (4, 1). What is the equation of line p?',
    choices: [
      { label: 'A', text: 'y = (−5/2)x + 11' },
      { label: 'B', text: 'y = (−5/2)x − 11' },
      { label: 'C', text: 'y = (2/5)x + 1' },
      { label: 'D', text: 'y = (5/2)x − 9' },
    ],
    correctAnswer: 'A',
    explanation: 'The slope of y = (2/5)x − 3 is 2/5. The perpendicular slope is the negative reciprocal: −5/2. Line p: y − 1 = (−5/2)(x − 4) → y = (−5/2)x + 10 + 1 → y = (−5/2)x + 11.',
    wrongAnswerExplanations: {
      B: 'y-intercept −11 is incorrect; 1 = (−5/2)(4) + b gives b = 1 + 10 = 11.',
      C: 'This has the same slope as the given line (2/5), not the perpendicular slope.',
      D: 'Slope 5/2 is the reciprocal but not the negative reciprocal; perpendicular lines have slopes that multiply to −1.',
    },
  },
  {
    id: 'sat-f3-math-m2h-q04',
    section: 'math',
    moduleId: 'f3-math-module-2-hard',
    domain: 'Algebra',
    skill: 'Linear inequalities in one or two variables',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'A company produces widgets (w) and gadgets (g). Each widget takes 3 hours to produce and each gadget takes 5 hours. The company has at most 120 production hours per week. If the company makes at least 10 widgets per week, which system of inequalities represents these constraints?',
    choices: [
      { label: 'A', text: '3w + 5g ≤ 120 and w ≥ 10' },
      { label: 'B', text: '3w + 5g ≥ 120 and w ≤ 10' },
      { label: 'C', text: '3w + 5g ≤ 120 and w ≤ 10' },
      { label: 'D', text: 'w + g ≤ 120 and w ≥ 10' },
    ],
    correctAnswer: 'A',
    explanation: 'Total production hours = 3w + 5g ≤ 120 (at most 120 hours). The company makes at least 10 widgets: w ≥ 10.',
    wrongAnswerExplanations: {
      B: '"At most 120 hours" means ≤ 120, not ≥ 120, and "at least 10 widgets" means w ≥ 10, not w ≤ 10.',
      C: '"At least 10 widgets" means w ≥ 10, not w ≤ 10.',
      D: 'The hours constraint must account for different rates per item; it is 3w + 5g ≤ 120, not w + g ≤ 120.',
    },
  },
  {
    id: 'sat-f3-math-m2h-q05',
    section: 'math',
    moduleId: 'f3-math-module-2-hard',
    domain: 'Algebra',
    skill: 'Linear equations in two variables',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'A line ℓ has the equation 4x − 3y = 12. Which of the following lines is parallel to ℓ?',
    choices: [
      { label: 'A', text: '3x − 4y = 12' },
      { label: 'B', text: '4x − 3y = −8' },
      { label: 'C', text: '6x − 4y = 12' },
      { label: 'D', text: '4x + 3y = 12' },
    ],
    correctAnswer: 'B',
    explanation: 'Line ℓ has slope 4/3 (from 4x − 3y = 12 → y = (4/3)x − 4). Parallel lines have the same slope but different y-intercepts. 4x − 3y = −8 → y = (4/3)x + 8/3, which has slope 4/3 and a different intercept.',
    wrongAnswerExplanations: {
      A: '3x − 4y = 12 → y = (3/4)x − 3; slope 3/4 ≠ 4/3.',
      C: '6x − 4y = 12 → y = (3/2)x − 3; slope 3/2 ≠ 4/3.',
      D: '4x + 3y = 12 → y = −(4/3)x + 4; slope −4/3 ≠ 4/3.',
    },
  },
  {
    id: 'sat-f3-math-m2h-q06',
    section: 'math',
    moduleId: 'f3-math-module-2-hard',
    domain: 'Algebra',
    skill: 'Systems of two linear equations in two variables',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'If the system 2x + ay = 6 and 4x + 6y = 12 has infinitely many solutions, what is the value of a?',
    choices: [
      { label: 'A', text: '2' },
      { label: 'B', text: '3' },
      { label: 'C', text: '4' },
      { label: 'D', text: '6' },
    ],
    correctAnswer: 'B',
    explanation: 'A system has infinitely many solutions when the equations are equivalent (one is a multiple of the other). Multiplying the first equation by 2: 4x + 2ay = 12. For this to equal 4x + 6y = 12, we need 2a = 6, so a = 3.',
    wrongAnswerExplanations: {
      A: 'a = 2: first equation ×2 gives 4x + 4y = 12; this differs from 4x + 6y = 12.',
      C: 'a = 4: first equation ×2 gives 4x + 8y = 12; this differs from 4x + 6y = 12.',
      D: 'a = 6: first equation ×2 gives 4x + 12y = 12; this differs from 4x + 6y = 12.',
    },
  },
  {
    id: 'sat-f3-math-m2h-q07',
    section: 'math',
    moduleId: 'f3-math-module-2-hard',
    domain: 'Algebra',
    skill: 'Linear equations in one variable',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'The equation |2x − 6| = 10 has two solutions. What is the sum of these solutions?',
    choices: [
      { label: 'A', text: '2' },
      { label: 'B', text: '4' },
      { label: 'C', text: '6' },
      { label: 'D', text: '12' },
    ],
    correctAnswer: 'C',
    explanation: 'Case 1: 2x − 6 = 10 → 2x = 16 → x = 8. Case 2: 2x − 6 = −10 → 2x = −4 → x = −2. Sum = 8 + (−2) = 6.',
    wrongAnswerExplanations: {
      A: '2 = 8 − 6; this is the difference, not the sum.',
      B: '4 would be the average of the two solutions, not their sum.',
      D: '12 is twice the sum, not the sum itself.',
    },
  },

  // ── Advanced Math (7) ─────────────────────────────────────────────────────
  {
    id: 'sat-f3-math-m2h-q08',
    section: 'math',
    moduleId: 'f3-math-module-2-hard',
    domain: 'Advanced Math',
    skill: 'Quadratic functions',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'The function f(x) = 2x² − 12x + k has a minimum value of 5. What is the value of k?',
    choices: [
      { label: 'A', text: '13' },
      { label: 'B', text: '19' },
      { label: 'C', text: '23' },
      { label: 'D', text: '27' },
    ],
    correctAnswer: 'C',
    explanation: 'Complete the square: f(x) = 2(x² − 6x) + k = 2(x² − 6x + 9 − 9) + k = 2(x − 3)² − 18 + k. The minimum value is −18 + k. Setting −18 + k = 5: k = 23.',
    wrongAnswerExplanations: {
      A: 'k = 13 gives minimum −18 + 13 = −5, not 5.',
      B: 'k = 19 gives minimum −18 + 19 = 1, not 5.',
      D: 'k = 27 gives minimum −18 + 27 = 9, not 5.',
    },
  },
  {
    id: 'sat-f3-math-m2h-q09',
    section: 'math',
    moduleId: 'f3-math-module-2-hard',
    domain: 'Advanced Math',
    skill: 'Nonlinear equations in one variable and systems of equations',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'If x > 0 and x² + (1/x²) = 7, what is the value of x − (1/x)?',
    choices: [
      { label: 'A', text: '√5' },
      { label: 'B', text: '√3' },
      { label: 'C', text: '√7 − 2' },
      { label: 'D', text: '3' },
    ],
    correctAnswer: 'A',
    explanation: 'Let p = x − 1/x. Then p² = x² − 2 + 1/x² = (x² + 1/x²) − 2 = 7 − 2 = 5. Since x > 0 and we need x − 1/x: if x > 1 then p > 0, so p = √5.',
    wrongAnswerExplanations: {
      B: 'p² = 3 would require x² + 1/x² = 5, not 7.',
      C: '√7 − 2 ≈ 0.65; squaring gives 7 − 4√7 + 4 = 11 − 4√7 ≈ 0.42 ≠ 5.',
      D: 'p = 3 → p² = 9 ≠ 5.',
    },
  },
  {
    id: 'sat-f3-math-m2h-q10',
    section: 'math',
    moduleId: 'f3-math-module-2-hard',
    domain: 'Advanced Math',
    skill: 'Equivalent expressions',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Which of the following is equivalent to (x³ − 8) / (x − 2) for x ≠ 2?',
    choices: [
      { label: 'A', text: 'x² − 4' },
      { label: 'B', text: 'x² + 2x + 4' },
      { label: 'C', text: 'x² − 2x + 4' },
      { label: 'D', text: 'x² + 4' },
    ],
    correctAnswer: 'B',
    explanation: 'x³ − 8 is a difference of cubes: x³ − 2³ = (x − 2)(x² + 2x + 4). So (x³ − 8)/(x − 2) = x² + 2x + 4.',
    wrongAnswerExplanations: {
      A: 'x² − 4 = (x−2)(x+2); this would require x³ − 8 = (x−2)(x²−4), which is false.',
      C: 'x² − 2x + 4 is the factoring pattern for sum of cubes denominator (x+2), not difference.',
      D: 'x² + 4 omits the middle term; verify: (x−2)(x²+4) = x³ + 4x − 2x² − 8 ≠ x³ − 8.',
    },
  },
  {
    id: 'sat-f3-math-m2h-q11',
    section: 'math',
    moduleId: 'f3-math-module-2-hard',
    domain: 'Advanced Math',
    skill: 'Quadratic functions',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'The quadratic y = ax² + bx + c passes through (0, 3), has its vertex at (2, −1), and the parabola opens upward. What is the value of a?',
    choices: [
      { label: 'A', text: '1/2' },
      { label: 'B', text: '1' },
      { label: 'C', text: '2' },
      { label: 'D', text: '4' },
    ],
    correctAnswer: 'B',
    explanation: 'In vertex form: y = a(x − 2)² − 1. At (0, 3): 3 = a(0 − 2)² − 1 = 4a − 1 → 4a = 4 → a = 1.',
    wrongAnswerExplanations: {
      A: 'a = 1/2: y = (1/2)(0−2)² − 1 = 2 − 1 = 1 ≠ 3.',
      C: 'a = 2: y = 2(0−2)² − 1 = 8 − 1 = 7 ≠ 3.',
      D: 'a = 4: y = 4(0−2)² − 1 = 16 − 1 = 15 ≠ 3.',
    },
  },
  {
    id: 'sat-f3-math-m2h-q12',
    section: 'math',
    moduleId: 'f3-math-module-2-hard',
    domain: 'Advanced Math',
    skill: 'Exponential functions',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'A population of bacteria doubles every 3 hours. If there are initially 500 bacteria, which function gives the number of bacteria N after t hours?',
    choices: [
      { label: 'A', text: 'N = 500 + 2t/3' },
      { label: 'B', text: 'N = 500 · 2^(3t)' },
      { label: 'C', text: 'N = 500 · 3^(t/2)' },
      { label: 'D', text: 'N = 500 · 2^(t/3)' },
    ],
    correctAnswer: 'D',
    explanation: 'After every 3 hours, the count doubles. After t hours, there are t/3 doubling periods. So N = 500 · 2^(t/3). Check: at t = 3, N = 500 · 2¹ = 1000 ✓.',
    wrongAnswerExplanations: {
      B: 'N = 500 · 2^(3t) would double 3 times per hour, not once per 3 hours.',
      C: 'Using base 3 instead of 2 contradicts "doubles."',
      A: 'This is a linear model, not exponential; populations multiplying cannot be modeled linearly.',
    },
  },
  {
    id: 'sat-f3-math-m2h-q13',
    section: 'math',
    moduleId: 'f3-math-module-2-hard',
    domain: 'Advanced Math',
    skill: 'Nonlinear equations in one variable and systems of equations',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'If x² + y = 10 and y = 2x + 1, how many solutions does the system have where x is real?',
    choices: [
      { label: 'A', text: 'Zero' },
      { label: 'B', text: 'One' },
      { label: 'C', text: 'Three' },
      { label: 'D', text: 'Two' },
    ],
    correctAnswer: 'D',
    explanation: 'Substitute y = 2x + 1 into x² + y = 10: x² + 2x + 1 = 10 → x² + 2x − 9 = 0. Discriminant = 4 + 36 = 40 > 0, so there are two real solutions.',
    wrongAnswerExplanations: {
      A: 'Zero solutions would require a negative discriminant; here Δ = 40 > 0.',
      B: 'One solution would require Δ = 0; here Δ = 40.',
      C: 'A quadratic can have at most two real solutions.',
    },
  },
  {
    id: 'sat-f3-math-m2h-q14',
    section: 'math',
    moduleId: 'f3-math-module-2-hard',
    domain: 'Advanced Math',
    skill: 'Equivalent expressions',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'Which expression is equivalent to (4x³y²) / (2x⁻¹y⁴)?',
    choices: [
      { label: 'A', text: '2x²/y²' },
      { label: 'B', text: '2x²y⁻²' },
      { label: 'C', text: '8x⁴/y²' },
      { label: 'D', text: '2x⁴/y²' },
    ],
    correctAnswer: 'D',
    explanation: '(4x³y²)/(2x⁻¹y⁴) = (4/2) · x^(3−(−1)) · y^(2−4) = 2 · x⁴ · y⁻² = 2x⁴/y².',
    wrongAnswerExplanations: {
      A: 'x exponent: 3 − (−1) = 4, not 2.',
      B: '2x²y⁻² = 2x²/y²; the x exponent is wrong (should be 4, not 2).',
      C: '4/2 = 2, not 8.',
    },
  },

  // ── Problem-Solving and Data Analysis (4) ─────────────────────────────────
  {
    id: 'sat-f3-math-m2h-q15',
    section: 'math',
    moduleId: 'f3-math-module-2-hard',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'Two-variable data: models and scatterplots',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'A researcher finds that a linear model fits data about advertising spending (in thousands of dollars) and monthly sales (in thousands of units): Sales = 3.2 × Spend + 12. If actual monthly sales were 45,000 units when spending was $8,000, what is the residual?',
    choices: [
      { label: 'A', text: '−3.6' },
      { label: 'B', text: '3.6' },
      { label: 'C', text: '7.4' },
      { label: 'D', text: '−7.4' },
    ],
    correctAnswer: 'C',
    explanation: 'Predicted sales at Spend = 8: 3.2(8) + 12 = 25.6 + 12 = 37.6 thousand units. Actual = 45 thousand units. Residual = actual − predicted = 45 − 37.6 = 7.4 thousand units.',
    wrongAnswerExplanations: {
      A: 'A negative residual would mean predicted > actual; here actual (45) > predicted (37.6).',
      B: '3.6 is not the correct calculation; 45 − 37.6 = 7.4, not 3.6.',
      D: 'The residual is positive (actual exceeds predicted), not negative.',
    },
  },
  {
    id: 'sat-f3-math-m2h-q16',
    section: 'math',
    moduleId: 'f3-math-module-2-hard',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'Probability and conditional probability',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'A survey of 200 students found that 120 play a sport, 80 play a musical instrument, and 40 do both. What is the probability that a randomly selected student plays a sport given that they play a musical instrument?',
    choices: [
      { label: 'A', text: '1/5' },
      { label: 'B', text: '1/3' },
      { label: 'C', text: '2/3' },
      { label: 'D', text: '1/2' },
    ],
    correctAnswer: 'D',
    explanation: 'P(sport | instrument) = P(sport AND instrument) / P(instrument) = (40/200) / (80/200) = 40/80 = 1/2.',
    wrongAnswerExplanations: {
      A: '40/200 = 1/5 is P(both), not the conditional probability.',
      B: '1/3 is not derived from correct conditional probability formula here.',
      C: '2/3 would be obtained by dividing incorrectly: 40/60 — but 60 is not a relevant quantity.',
    },
  },
  {
    id: 'sat-f3-math-m2h-q17',
    section: 'math',
    moduleId: 'f3-math-module-2-hard',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'Inference from sample statistics and margin of error',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'A poll of 500 registered voters finds that 58% support a ballot measure, with a margin of error of ±4 percentage points at 95% confidence. Which conclusion is best supported?',
    choices: [
      { label: 'A', text: 'It is certain that the majority of all registered voters support the measure' },
      { label: 'B', text: 'The true population support is definitely between 54% and 62%' },
      { label: 'C', text: 'Exactly 58% of all registered voters support the measure' },
      { label: 'D', text: 'There is 95% confidence that the true population support is between 54% and 62%' },
    ],
    correctAnswer: 'D',
    explanation: 'A 95% confidence interval means that if many samples were drawn, 95% of the resulting confidence intervals would contain the true population value. The interval 54%–62% represents this range, not a certainty.',
    wrongAnswerExplanations: {
      A: '"Certain" overstates the conclusion; statistics provide confidence levels, not certainties.',
      B: '"Definitely" overstates statistical inference; confidence intervals provide probabilistic, not guaranteed, ranges.',
      C: 'The sample result is 58%; the true population parameter is unknown and is being estimated, not confirmed.',
    },
  },
  {
    id: 'sat-f3-math-m2h-q18',
    section: 'math',
    moduleId: 'f3-math-module-2-hard',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'Ratios, rates, proportional relationships, and units',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'A chemical solution is 15% salt by volume. How many liters of pure salt must be added to 40 liters of the solution to make a 25% salt solution?',
    choices: [
      { label: 'A', text: '4' },
      { label: 'B', text: '5' },
      { label: 'C', text: '16/3' },
      { label: 'D', text: '6' },
    ],
    correctAnswer: 'C',
    explanation: 'Initial salt = 0.15 × 40 = 6 liters. Let x = liters of pure salt added. New total solution = 40 + x. New salt = 6 + x. (6 + x)/(40 + x) = 0.25 → 6 + x = 10 + 0.25x → 0.75x = 4 → x = 4/0.75 = 16/3 ≈ 5.33 liters.',
    wrongAnswerExplanations: {
      A: '(6+4)/(44) = 10/44 ≈ 22.7%, not 25%.',
      B: '(6+5)/(45) = 11/45 ≈ 24.4%, not 25%.',
      D: '(6+6)/(46) = 12/46 ≈ 26.1%, not 25%.',
    },
  },

  // ── Geometry and Trigonometry (4) ─────────────────────────────────────────
  {
    id: 'sat-f3-math-m2h-q19',
    section: 'math',
    moduleId: 'f3-math-module-2-hard',
    domain: 'Geometry and Trigonometry',
    skill: 'Area and volume',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'A cone has a height of 12 cm and a base radius of 5 cm. What is the volume of the cone in cubic centimeters? (Use π ≈ 3.14 and round to the nearest cubic centimeter.)',
    choices: [
      { label: 'A', text: '314' },
      { label: 'B', text: '565' },
      { label: 'C', text: '942' },
      { label: 'D', text: '1130' },
    ],
    correctAnswer: 'A',
    explanation: 'Volume of cone = (1/3)πr²h = (1/3)(3.14)(25)(12) = (1/3)(942) = 314 cm³.',
    wrongAnswerExplanations: {
      B: '565 ≈ πr²h/2; this uses (1/2) instead of (1/3) as the coefficient.',
      C: '942 = πr²h without the 1/3 factor.',
      D: '1130 ≈ πr²h × (12/10); no standard formula yields this.',
    },
  },
  {
    id: 'sat-f3-math-m2h-q20',
    section: 'math',
    moduleId: 'f3-math-module-2-hard',
    domain: 'Geometry and Trigonometry',
    skill: 'Right triangles and trigonometry',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'In right triangle PQR, angle Q = 90°. If sin(P) = 5/13, what is cos(P)?',
    choices: [
      { label: 'A', text: '5/12' },
      { label: 'B', text: '12/13' },
      { label: 'C', text: '13/12' },
      { label: 'D', text: '5/13' },
    ],
    correctAnswer: 'B',
    explanation: 'If sin(P) = 5/13, then the opposite side = 5 and hypotenuse = 13. By the Pythagorean theorem, adjacent = √(169 − 25) = √144 = 12. cos(P) = adjacent/hypotenuse = 12/13.',
    wrongAnswerExplanations: {
      A: '5/12 = tan(P), not cos(P).',
      C: '13/12 > 1, which is impossible for a cosine value.',
      D: '5/13 = sin(P), not cos(P).',
    },
  },

  // ── Grid-in questions (Q21–Q22) ───────────────────────────────────────────
  {
    id: 'sat-f3-math-m2h-q21',
    section: 'math',
    moduleId: 'f3-math-module-2-hard',
    domain: 'Advanced Math',
    skill: 'Quadratic functions',
    difficulty: 'hard',
    type: 'grid_in',
    question: 'If the sum of the roots of 3x² − 15x + k = 0 is 5 and the product of the roots is 4, what is the value of k?',
    correctAnswer: '12',
    acceptableAnswers: ['12'],
    explanation: 'For ax² + bx + c = 0, the product of roots = c/a. Product = k/3 = 4, so k = 12. (Verify sum: −(−15)/3 = 5 ✓)',
  },
  {
    id: 'sat-f3-math-m2h-q22',
    section: 'math',
    moduleId: 'f3-math-module-2-hard',
    domain: 'Geometry and Trigonometry',
    skill: 'Circles',
    difficulty: 'hard',
    type: 'grid_in',
    question: 'A circle has its center at (3, −2) and passes through the point (7, 1). What is the radius of the circle?',
    correctAnswer: '5',
    acceptableAnswers: ['5'],
    explanation: 'Radius = distance from center to point = √((7−3)² + (1−(−2))²) = √(16 + 9) = √25 = 5.',
  },
]
