import type { RWQuestion } from './types'

export const f4RwModule2HardQuestions: RWQuestion[] = [
  {
    id: 'sat-f4-rw-m2h-q01',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-hard',
    domain: 'Craft and Structure',
    skill: 'Words in Context',
    difficulty: 'hard',
    stimulus: 'The philosopher\'s late writings are notoriously _______ : sentences double back on themselves, key terms are defined and then quietly redefined, and a claim asserted in one paragraph is hedged in the next, leaving even sympathetic readers uncertain of what, finally, is being maintained.',
    question: 'Which choice completes the text with the most logical and precise word or phrase?',
    choices: [
      { label: 'A', text: 'elusive' },
      { label: 'B', text: 'derivative' },
      { label: 'C', text: 'conventional' },
      { label: 'D', text: 'concise' },
    ],
    correctAnswer: 'A',
    explanation: '"Elusive" means hard to grasp or pin down, which fits writing whose shifting definitions and hedged claims leave readers uncertain of the author\'s meaning.',
    wrongAnswerExplanations: {
      B: '"Derivative" means unoriginal; the passage concerns difficulty of interpretation, not originality.',
      C: '"Conventional" means ordinary, contradicting the unusual, self-undermining style described.',
      D: '"Concise" means brief and clear, the opposite of prose that leaves readers uncertain.',
    },
  },

  {
    id: 'sat-f4-rw-m2h-q02',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-hard',
    domain: 'Craft and Structure',
    skill: 'Words in Context',
    difficulty: 'hard',
    stimulus: 'Far from being a passive record of the past, memory is _______ : each time a recollection is retrieved, it is subtly reshaped by present circumstances and then re-stored in its altered form, so that a vivid memory may be, paradoxically, one that has been revised the most.',
    question: 'Which choice completes the text with the most logical and precise word or phrase?',
    choices: [
      { label: 'A', text: 'reconstructive' },
      { label: 'B', text: 'permanent' },
      { label: 'C', text: 'inherited' },
      { label: 'D', text: 'selective' },
    ],
    correctAnswer: 'A',
    explanation: '"Reconstructive" describes something built anew each time; it fits the account of memories being reshaped and re-stored on every retrieval.',
    wrongAnswerExplanations: {
      B: '"Permanent" contradicts the description of memories being altered with each recall.',
      C: '"Inherited" implies passed down genetically, which the passage does not discuss.',
      D: '"Selective" means choosing some things over others; the point is that memories are actively rebuilt, not merely filtered.',
    },
  },

  {
    id: 'sat-f4-rw-m2h-q03',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-hard',
    domain: 'Craft and Structure',
    skill: 'Words in Context',
    difficulty: 'hard',
    stimulus: 'The committee praised the proposal in public while working quietly to ensure it never reached a vote. Such _______ support — endorsement in word paired with obstruction in deed — is difficult for reformers to counter precisely because it is so hard to name.',
    question: 'Which choice completes the text with the most logical and precise word or phrase?',
    choices: [
      { label: 'A', text: 'wholehearted' },
      { label: 'B', text: 'ostensible' },
      { label: 'C', text: 'unanimous' },
      { label: 'D', text: 'belated' },
    ],
    correctAnswer: 'B',
    explanation: '"Ostensible" means apparent but not genuine. It fits support that is stated in public but undermined in private — endorsement in word paired with obstruction in deed.',
    wrongAnswerExplanations: {
      A: '"Wholehearted" means sincere and complete, contradicting the secret obstruction described.',
      C: '"Unanimous" concerns whether all agree, not the gap between words and actions.',
      D: '"Belated" means late, which the passage does not indicate.',
    },
  },

  {
    id: 'sat-f4-rw-m2h-q09',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-hard',
    domain: 'Craft and Structure',
    skill: 'Words in Context',
    difficulty: 'hard',
    stimulus: 'The editorial board\'s praise for the candidate was, on closer inspection, _______ : it conceded his administrative record while delicately avoiding his most contested policy positions, and its carefully hedged language left readers unable to determine whether the board actually supported his candidacy or merely declined to oppose it.',
    question: 'Which choice completes the text with the most logical and precise word or phrase?',
    choices: [
      { label: 'A', text: 'pellucid' },
      { label: 'B', text: 'equivocal' },
      { label: 'C', text: 'unqualified' },
      { label: 'D', text: 'trenchant' },
    ],
    correctAnswer: 'B',
    explanation: '"Equivocal" means deliberately ambiguous or open to more than one interpretation — exactly what praise that avoids contested positions and leaves readers uncertain of the board\'s actual stance would be.',
    wrongAnswerExplanations: {
      A: '"Pellucid" means perfectly clear and transparent, the opposite of hedged language that leaves readers uncertain.',
      C: '"Unqualified" means unconditional and wholehearted; the passage describes praise that is anything but unqualified.',
      D: '"Trenchant" means vigorously effective and sharply expressed, which contradicts the carefully hedged and evasive quality the passage describes.',
    },
  },

  {
    id: 'sat-f4-rw-m2h-q05',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-hard',
    domain: 'Craft and Structure',
    skill: 'Text Structure and Purpose',
    difficulty: 'hard',
    stimulus: 'Economists have long treated gross domestic product as a proxy for national well-being, and for describing certain kinds of growth it serves that purpose adequately. Yet GDP counts a hurricane\'s reconstruction as a gain while ignoring the destruction that preceded it, and it registers no loss when unpaid caregiving is withdrawn from the home and, in effect, disappears from the ledger. The measure, in short, tracks what is transacted, not necessarily what is valuable.',
    question: 'What is the main purpose of the text?',
    choices: [
      { label: 'A', text: 'To argue that GDP should be abolished as an economic measure' },
      { label: 'B', text: 'To illustrate the limitations of GDP as a measure of well-being' },
      { label: 'C', text: 'To explain the mathematical formula used to calculate GDP' },
      { label: 'D', text: 'To praise GDP for accurately capturing all economic activity' },
    ],
    correctAnswer: 'B',
    explanation: 'The passage grants GDP some usefulness but offers examples (disaster reconstruction, withdrawn caregiving) showing it tracks transactions rather than value — illustrating its limitations as a well-being measure.',
    wrongAnswerExplanations: {
      A: 'The passage critiques GDP but does not call for abolishing it; it even grants that it serves some purposes adequately.',
      C: 'No formula or method of calculation is explained.',
      D: 'The passage highlights what GDP misses, so it does not praise it as fully accurate.',
    },
  },

  {
    id: 'sat-f4-rw-m2h-q06',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-hard',
    domain: 'Craft and Structure',
    skill: 'Text Structure and Purpose',
    difficulty: 'hard',
    stimulus: 'The following is an original short passage. She had rehearsed the refusal for days, arranging her reasons in a tidy row like place settings. But when the moment came and he looked at her with that mild, expectant patience, the row dissolved; she heard herself agreeing, in a bright voice she scarcely recognized, to precisely the thing she had resolved to decline.',
    question: 'What is the main function of the phrase "arranging her reasons in a tidy row like place settings" in the text?',
    choices: [
      { label: 'A', text: 'To emphasize how carefully she had prepared to refuse, heightening the reversal that follows' },
      { label: 'B', text: 'To describe the physical setting of a dinner party' },
      { label: 'C', text: 'To suggest that she was indifferent to the outcome of the conversation' },
      { label: 'D', text: 'To explain why the other character was reluctant to speak' },
    ],
    correctAnswer: 'A',
    explanation: 'The image of neatly arranged reasons stresses her thorough preparation, which makes the subsequent collapse of that preparation — her agreeing instead of refusing — more striking.',
    wrongAnswerExplanations: {
      B: 'The "place settings" are a simile for her reasons, not a literal dinner-party setting.',
      C: 'Her careful rehearsal shows she cared deeply, not that she was indifferent.',
      D: 'The phrase concerns her own preparation, not the other character\'s reluctance.',
    },
  },

  {
    id: 'sat-f4-rw-m2h-q07',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-hard',
    domain: 'Craft and Structure',
    skill: 'Text Structure and Purpose',
    difficulty: 'hard',
    stimulus: 'Critics of standardized testing often assume that the tests fail because they measure the wrong things. A more unsettling possibility is that they measure something real but narrow — a capacity for a particular kind of timed problem-solving — and that schools, in optimizing for it, gradually redefine education as the cultivation of that single capacity. The danger, on this view, is not inaccuracy but influence: the test does not merely record what schools do; it reshapes it.',
    question: 'Which choice best describes the overall structure of the text?',
    choices: [
      { label: 'A', text: 'It states a common criticism, proposes a more troubling alternative, and clarifies what makes the alternative troubling' },
      { label: 'B', text: 'It defends standardized testing against all criticism and recommends expanding its use' },
      { label: 'C', text: 'It presents statistical data about test scores and interprets the trends' },
      { label: 'D', text: 'It compares two testing systems and endorses the older one' },
    ],
    correctAnswer: 'A',
    explanation: 'The passage opens with the common criticism (tests measure the wrong things), advances a more unsettling alternative (they measure something narrow and reshape schooling), and clarifies why that is worse: the danger is influence, not inaccuracy.',
    wrongAnswerExplanations: {
      B: 'The passage raises a serious concern about testing rather than defending it and recommending more of it.',
      C: 'No statistical data or trends are presented.',
      D: 'No two testing systems are compared.',
    },
  },

  {
    id: 'sat-f4-rw-m2h-q12',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-hard',
    domain: 'Information and Ideas',
    skill: 'Central Ideas and Details',
    difficulty: 'hard',
    stimulus: 'Fermentation was practiced for millennia before anyone understood the organisms responsible for it. Ancient brewers and bread-makers observed that certain conditions reliably produced desired results and learned to perpetuate those conditions without any knowledge of microbiology. When scientists in the nineteenth century finally demonstrated that living microorganisms drove the process, this explanation was resisted by chemists who preferred a purely mechanical account. The conflict was not simply about fermentation: it was an early skirmish in a longer debate over whether living processes could be fully explained by the same laws that governed non-living matter.',
    question: 'Which choice best states the main idea of the text?',
    choices: [
      { label: 'A', text: 'Ancient brewers were more skilled than modern scientists at managing fermentation' },
      { label: 'B', text: 'The history of fermentation research illustrates a broader dispute about whether life requires explanations beyond physical chemistry' },
      { label: 'C', text: 'Nineteenth-century chemists eventually accepted the microbial explanation of fermentation without controversy' },
      { label: 'D', text: 'Fermentation was not fully understood until the development of modern molecular biology' },
    ],
    correctAnswer: 'B',
    explanation: 'The passage moves from millennia of practical fermentation to a nineteenth-century dispute between microbiologists and chemists, concluding that the conflict was really about whether living processes obey the same laws as non-living matter — a broader philosophical question that fermentation research brought into focus.',
    wrongAnswerExplanations: {
      A: 'The passage says ancient practitioners lacked knowledge of microbiology, not that they were more skilled than scientists.',
      C: 'The passage says chemists resisted the microbial explanation, not that they accepted it without controversy.',
      D: 'Molecular biology is never mentioned; the passage does not claim fermentation remained ununderstood until that field emerged.',
    },
  },

  {
    id: 'sat-f4-rw-m2h-q11',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-hard',
    domain: 'Information and Ideas',
    skill: 'Central Ideas and Details',
    difficulty: 'hard',
    stimulus: 'Conventional accounts credit the printing press with spreading literacy, but the causation may run partly the other way. In regions where merchants and administrators had already created a demand for written records, presses found a ready market and multiplied; where such demand was absent, the technology diffused slowly regardless of its availability. The press, on this account, did not simply create readers so much as answer a hunger that was already present.',
    question: 'Which choice best states the main idea of the text?',
    choices: [
      { label: 'A', text: 'The printing press had no effect on the spread of literacy' },
      { label: 'B', text: 'Existing demand for written records may have shaped where the printing press spread, not only the reverse' },
      { label: 'C', text: 'Merchants and administrators opposed the adoption of the printing press' },
      { label: 'D', text: 'The printing press spread most quickly in regions with no prior use of writing' },
    ],
    correctAnswer: 'B',
    explanation: 'The passage argues the press flourished where demand for written records already existed and diffused slowly where it did not, suggesting prior demand shaped the press\'s spread rather than the press alone creating readers.',
    wrongAnswerExplanations: {
      A: 'The passage revises the causal story but does not claim the press had no effect on literacy.',
      C: 'Merchants and administrators created demand for records; they did not oppose the press.',
      D: 'The passage says the press spread fastest where demand for writing already existed, not where writing was absent.',
    },
  },

  {
    id: 'sat-f4-rw-m2h-q17',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-hard',
    domain: 'Information and Ideas',
    skill: 'Command of Evidence',
    difficulty: 'hard',
    stimulus: 'An ecologist proposed a specific mechanism for why invasive shrubs outcompete native grasses in disturbed meadows: the shrubs release allelopathic compounds — chemicals toxic to neighboring plants — into the soil, suppressing germination of native seeds rather than simply shading them out. She designed a controlled greenhouse experiment to test this mechanism directly, using soil taken from invaded and uninvaded plots.',
    question: 'Which result, if true, would most directly support the ecologist\'s proposed mechanism?',
    choices: [
      { label: 'A', text: 'Native grass seeds germinated at significantly lower rates when grown in soil from invaded plots than when grown in soil from uninvaded plots, even under identical light conditions' },
      { label: 'B', text: 'The invasive shrubs grew taller and produced more biomass in invaded plots than in uninvaded plots' },
      { label: 'C', text: 'Native grasses survived at lower rates in plots where invasive shrubs cast the most shade' },
      { label: 'D', text: 'The allelopathic compounds were detected in soil samples taken from both invaded and uninvaded plots' },
    ],
    correctAnswer: 'A',
    explanation: 'The ecologist\'s proposed mechanism is that soil chemicals from the shrubs suppress native seed germination independently of shading. A result showing reduced germination in invaded-plot soil under identical light conditions isolates the chemical mechanism from the shading explanation, directly supporting the proposed mechanism.',
    wrongAnswerExplanations: {
      B: 'Greater shrub biomass shows competitive success, but does not distinguish chemical suppression from shading as the mechanism responsible for native grass decline.',
      C: 'Lower native grass survival in heavily shaded plots actually supports the competing shading explanation, not the allelopathic chemical mechanism the ecologist proposed.',
      D: 'Detecting compounds in both plot types does not show that those compounds suppress germination; it would actually weaken the argument if uninvaded plots also contain the compounds.',
    },
  },

  {
    id: 'sat-f4-rw-m2h-q14',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-hard',
    domain: 'Information and Ideas',
    skill: 'Command of Evidence',
    difficulty: 'hard',
    stimulus: 'A psychologist proposed that people are more willing to help a single identifiable victim than a large group of anonymous victims, even when the group\'s need is greater — a tendency she called the identifiable-victim effect. She designed an experiment to test whether presenting aid appeals in terms of one named individual would elicit more donations than statistics about many.',
    question: 'Which result, if true, would most directly support the psychologist\'s proposal?',
    choices: [
      { label: 'A', text: 'Participants shown a story about one named child donated more, on average, than participants shown statistics about thousands of children in need' },
      { label: 'B', text: 'Participants who donated reported feeling more informed after reading statistics than after reading individual stories' },
      { label: 'C', text: 'Wealthier participants donated more than poorer participants regardless of the appeal they saw' },
      { label: 'D', text: 'Participants spent more time reading the statistical appeal than the individual story' },
    ],
    correctAnswer: 'A',
    explanation: 'The proposal is that a single identifiable victim draws more help than anonymous numbers. Higher donations from the named-child appeal than the statistical appeal directly supports it.',
    wrongAnswerExplanations: {
      B: 'Feeling informed is not the same as donating more; the proposal is about willingness to help.',
      C: 'Donation differences tied to wealth rather than appeal type do not test the identifiable-victim effect.',
      D: 'Time spent reading does not show which appeal produced more giving.',
    },
  },

  {
    id: 'sat-f4-rw-m2h-q15',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-hard',
    domain: 'Information and Ideas',
    skill: 'Command of Evidence',
    difficulty: 'hard',
    stimulus: 'A researcher hypothesized that a plant species native to nutrient-poor soils would grow poorly when given abundant fertilizer, because it is adapted to conserve resources rather than exploit surpluses. She measured the survival rate of seedlings grown at four fertilizer levels.',
    graphData: {
      type: 'table',
      title: 'Seedling Survival by Fertilizer Level',
      headers: ['Fertilizer Level', 'Seedling Survival Rate (%)'],
      rows: [
        ['None', '88'],
        ['Low', '84'],
        ['Moderate', '61'],
        ['High', '33'],
      ],
    },
    question: 'Which choice best uses data from the table to support the researcher\'s hypothesis?',
    choices: [
      { label: 'A', text: 'Survival fell as fertilizer increased, from 88% with no fertilizer to 33% at the high level.' },
      { label: 'B', text: 'Survival was highest at the high fertilizer level (33%).' },
      { label: 'C', text: 'Survival remained constant across all four fertilizer levels.' },
      { label: 'D', text: 'Survival was higher at the moderate level (61%) than with no fertilizer (88%).' },
    ],
    correctAnswer: 'A',
    explanation: 'The hypothesis predicts poor growth with abundant fertilizer. Survival dropping from 88% (none) to 33% (high) as fertilizer rises directly supports it.',
    wrongAnswerExplanations: {
      B: 'The high level had the lowest survival (33%), not the highest.',
      C: 'Survival varied widely, from 88% down to 33%.',
      D: 'Moderate survival (61%) was lower, not higher, than survival with no fertilizer (88%).',
    },
  },

  {
    id: 'sat-f4-rw-m2h-q16',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-hard',
    domain: 'Information and Ideas',
    skill: 'Command of Evidence',
    difficulty: 'hard',
    stimulus: 'A linguist studying how quickly new words enter everyday use tracked four coined terms, recording the percentage of surveyed speakers who reported using each term one year and five years after it first appeared in print.',
    graphData: {
      type: 'table',
      title: 'Reported Use of Coined Terms',
      headers: ['Term', 'Use at 1 Year (%)', 'Use at 5 Years (%)'],
      rows: [
        ['Term W', '8', '41'],
        ['Term X', '35', '38'],
        ['Term Y', '3', '6'],
        ['Term Z', '22', '55'],
      ],
    },
    question: 'The linguist concluded that a term\'s popularity in its first year does not reliably predict its popularity after five years. Which choice best uses data from the table to support this conclusion?',
    choices: [
      { label: 'A', text: 'Term X had higher one-year use (35%) than Term W (8%), yet Term W ended with higher five-year use (41% versus 38%).' },
      { label: 'B', text: 'Term Y had the lowest use at both one year and five years.' },
      { label: 'C', text: 'Every term increased in use between one year and five years.' },
      { label: 'D', text: 'Term Z had the highest five-year use at 55%.' },
    ],
    correctAnswer: 'A',
    explanation: 'The conclusion is that early popularity does not reliably predict later popularity. Term X led at one year but was overtaken by Term W at five years, showing the ranking can reverse — direct support.',
    wrongAnswerExplanations: {
      B: 'Term Y being consistently low shows a stable case, which does not demonstrate that early rank fails to predict later rank.',
      C: 'That all terms rose does not address whether early popularity predicts later popularity.',
      D: 'Term Z\'s high five-year figure alone says nothing about the relationship between one-year and five-year use.',
    },
  },

  {
    id: 'sat-f4-rw-m2h-q18',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-hard',
    domain: 'Information and Ideas',
    skill: 'Inferences',
    difficulty: 'hard',
    stimulus: 'Some desert plants open the pores in their leaves only at night, taking in carbon dioxide when the air is cool and storing it as an acid until daylight, when it can be used for photosynthesis. Plants in wetter climates, by contrast, open their pores during the day and lose far more water to evaporation. This difference suggests that the nighttime strategy _______',
    question: 'Which choice most logically completes the text?',
    choices: [
      { label: 'A', text: 'evolved as a way to conserve water in environments where it is scarce.' },
      { label: 'B', text: 'allows desert plants to photosynthesize faster than plants in wet climates.' },
      { label: 'C', text: 'prevents desert plants from carrying out photosynthesis at all.' },
      { label: 'D', text: 'requires more water than the daytime strategy used in wetter climates.' },
    ],
    correctAnswer: 'A',
    explanation: 'By opening pores at night, when cool air reduces evaporation, desert plants lose less water than daytime openers. This supports the inference that the strategy conserves water where it is scarce.',
    wrongAnswerExplanations: {
      B: 'The passage emphasizes water conservation, not faster photosynthesis, and provides no basis for a speed comparison.',
      C: 'The plants store carbon for daytime photosynthesis, so they do photosynthesize.',
      D: 'The nighttime strategy loses less water, so it does not require more than the daytime one.',
    },
  },

  {
    id: 'sat-f4-rw-m2h-q13',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-hard',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'hard',
    stimulus: 'Buried under layers of volcanic ash for nearly two thousand years, _______ preserving details of daily Roman life that written records rarely captured.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choices: [
      { label: 'A', text: 'archaeologists uncovered the city of Pompeii in remarkable condition,' },
      { label: 'B', text: 'the excavation of the city of Pompeii revealed remarkable conditions,' },
      { label: 'C', text: 'the city of Pompeii was uncovered in remarkable condition,' },
      { label: 'D', text: 'it was the city of Pompeii that was uncovered in remarkable condition,' },
    ],
    correctAnswer: 'C',
    explanation: 'Choice C is correct. The introductory modifier "Buried under layers of volcanic ash for nearly two thousand years" must describe the noun that immediately follows it. The thing buried was the city of Pompeii, so "the city of Pompeii" correctly follows the modifier and avoids a dangling construction.',
    wrongAnswerExplanations: {
      A: 'Choice A is incorrect. This makes "archaeologists" the thing buried under ash for two thousand years, which is illogical and creates a dangling modifier.',
      B: 'Choice B is incorrect. This makes "the excavation" the thing buried under ash, which is illogical, since the excavation is a recent activity, not something buried for millennia.',
      D: 'Choice D is incorrect. The wordy "it was...that" construction leaves the modifier attached to no clear noun and does not directly name what was buried.',
    },
  },

  {
    id: 'sat-f4-rw-m2h-q19',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-hard',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'hard',
    stimulus: 'High on the museum wall, above the crowded galleries and beyond the reach of casual visitors, _______ a series of tapestries whose faded threads still hint at the brilliant colors they once displayed.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choices: [
      { label: 'A', text: 'hang' },
      { label: 'B', text: 'hangs' },
      { label: 'C', text: 'to hang' },
      { label: 'D', text: 'hanging' },
    ],
    correctAnswer: 'A',
    explanation: 'Choice A is correct. In this sentence the normal order is inverted, so the verb comes before its subject. The true subject is the plural "a series of tapestries" — here "series" heads a phrase whose plural sense governs the verb, and, more decisively, the verb must agree with the plural noun it precedes rather than with the introductory location phrases. The plural "hang" agrees with the plural subject that follows.',
    wrongAnswerExplanations: {
      B: 'Choice B is incorrect. The singular "hangs" fails to agree with the plural subject "tapestries" that follows the inverted verb; the introductory phrases are not the subject.',
      C: 'Choice C is incorrect. The infinitive "to hang" is not a finite verb and cannot serve as the main verb of the sentence, leaving it without a complete predicate.',
      D: 'Choice D is incorrect. The participle "hanging" is not a finite verb and cannot function as the sentence\'s main verb, producing a fragment.',
    },
  },

  {
    id: 'sat-f4-rw-m2h-q23',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-hard',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'hard',
    stimulus: 'The collection of manuscripts that the scholar spent decades assembling, along with the annotations she added to nearly every page, _______ now housed in the university\'s rare-book library.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choices: [
      { label: 'A', text: 'are' },
      { label: 'B', text: 'is' },
      { label: 'C', text: 'were' },
      { label: 'D', text: 'have been' },
    ],
    correctAnswer: 'B',
    explanation: 'The subject is "The collection," a singular noun. The intervening phrases ("of manuscripts," "along with the annotations") do not change the number, so the singular verb "is" is correct.',
    wrongAnswerExplanations: {
      A: '"Are" is plural, but the head noun "collection" is singular.',
      C: '"Were" is plural and mismatches the singular subject "collection."',
      D: '"Have been" is plural and does not agree with the singular subject.',
    },
  },

  {
    id: 'sat-f4-rw-m2h-q24',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-hard',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'hard',
    stimulus: 'Long dismissed by critics as a minor regional writer, _______ has, in recent years, been reassessed as one of the century\'s most inventive stylists.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choices: [
      { label: 'A', text: 'the reputation of the author' },
      { label: 'B', text: 'the author' },
      { label: 'C', text: 'critics have decided that the author' },
      { label: 'D', text: 'it is the author who' },
    ],
    correctAnswer: 'B',
    explanation: 'The opening modifier "Long dismissed by critics as a minor regional writer" must describe the person dismissed. "The author" is that person, so it correctly follows the modifier and avoids a dangling construction.',
    wrongAnswerExplanations: {
      A: 'This makes "the reputation" the thing dismissed as a "regional writer," which is illogical.',
      C: 'This makes "critics" the ones dismissed as a regional writer, misattaching the modifier.',
      D: '"It is the author who" is wordy and leaves the modifier awkwardly attached.',
    },
  },

  {
    id: 'sat-f4-rw-m2h-q04',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-hard',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'hard',
    stimulus: 'After years of study, the metallurgist concluded that the ancient sword owed its remarkable strength to a single overlooked factor _______ the trace impurities in the ore, which formed microscopic structures that reinforced the blade in ways early smiths could not have understood.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choices: [
      { label: 'A', text: 'factor;' },
      { label: 'B', text: 'factor:' },
      { label: 'C', text: 'factor,' },
      { label: 'D', text: 'factor' },
    ],
    correctAnswer: 'B',
    explanation: 'Choice B is correct. A colon follows a complete independent clause to introduce an element that explains or specifies what came before. The clause before the colon is complete, and what follows names the "single overlooked factor," so the colon is correct.',
    wrongAnswerExplanations: {
      A: 'Choice A is incorrect. A semicolon must join two independent clauses, but the material after it ("the trace impurities in the ore...") is not an independent clause.',
      C: 'Choice C is incorrect. A comma is too weak to introduce the explanatory element that identifies the factor and blurs the boundary before it.',
      D: 'Choice D is incorrect. With no punctuation, the specifying phrase runs into the clause without the clear break the structure requires.',
    },
  },

  {
    id: 'sat-f4-rw-m2h-q20',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-hard',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'hard',
    stimulus: 'The expedition faced one obstacle after _______ a washed-out bridge, a mislabeled map, and a guide who abandoned them on the second day left the team badly behind schedule.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choices: [
      { label: 'A', text: 'another:' },
      { label: 'B', text: 'another,' },
      { label: 'C', text: 'another' },
      { label: 'D', text: 'another; that is' },
    ],
    correctAnswer: 'A',
    explanation: 'The clause "The expedition faced one obstacle after another" is complete, and a colon correctly introduces the list of obstacles that elaborates on it.',
    wrongAnswerExplanations: {
      B: 'A comma is too weak to introduce the elaborating list and blurs the boundary before it.',
      C: 'With no punctuation, the list runs into the clause without a break.',
      D: '"That is" after a semicolon awkwardly introduces a list and produces a clumsy, nonstandard construction here.',
    },
  },

  {
    id: 'sat-f4-rw-m2h-q21',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-hard',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'hard',
    stimulus: 'The novelist\'s early works, praised for their spare _______ gave little hint of the sprawling, ornate style she would adopt in later decades.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choices: [
      { label: 'A', text: 'prose,' },
      { label: 'B', text: 'prose' },
      { label: 'C', text: 'prose;' },
      { label: 'D', text: 'prose:' },
    ],
    correctAnswer: 'A',
    explanation: 'The nonessential phrase "praised for their spare prose" is set off by commas — one before "praised" and one after "prose." A comma after "prose" correctly closes that phrase before the verb "gave."',
    wrongAnswerExplanations: {
      B: 'Omitting the comma leaves the nonessential phrase unclosed, so it is not properly set off from the main clause.',
      C: 'A semicolon must separate two independent clauses; the material before it is not a complete clause on its own here.',
      D: 'A colon introduces a list or explanation, which does not fit between the interrupting phrase and the verb.',
    },
  },

  {
    id: 'sat-f4-rw-m2h-q10',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-hard',
    domain: 'Expression of Ideas',
    skill: 'Transitions',
    difficulty: 'hard',
    stimulus: 'Scholars of nineteenth-century American literature have long read the narrator of Herman Melville\'s story "Bartleby, the Scrivener" as an unreliable guide to the title character\'s inner life: his attempts to explain Bartleby\'s behavior consistently reveal more about his own anxieties than about Bartleby himself. This interpretive consensus held largely unchallenged for decades. _______ a body of archival work published in the last fifteen years, drawing on newly digitized records of Manhattan\'s commercial culture, has begun to shift the conversation from psychology toward the material conditions — low pay, dim offices, numbing repetitive work — that the story\'s setting encodes.',
    question: 'Which choice completes the text with the most logical transition?',
    choices: [
      { label: 'A', text: 'In other words,' },
      { label: 'B', text: 'More recently, however,' },
      { label: 'C', text: 'For this reason,' },
      { label: 'D', text: 'In addition,' },
    ],
    correctAnswer: 'B',
    explanation: 'The first two sentences describe a long-standing consensus; the third introduces a challenge from recent archival work. "More recently, however" signals both the temporal contrast (recent vs. decades-long) and the adversative shift away from the established view.',
    wrongAnswerExplanations: {
      A: '"In other words" signals a restatement of what came before, but the third sentence introduces a new approach rather than restating the earlier consensus.',
      C: '"For this reason" signals that the new archival work follows as a consequence of the unchallenged consensus, which misrepresents the relationship — the new work challenges the consensus rather than arising from it.',
      D: '"In addition" signals that the third sentence supplements the preceding information, but the archival work shifts the conversation away from the consensus rather than adding to it.',
    },
  },

  {
    id: 'sat-f4-rw-m2h-q22',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-hard',
    domain: 'Expression of Ideas',
    skill: 'Transitions',
    difficulty: 'hard',
    stimulus: 'Early advocates of carbon pricing argued that setting a sufficiently high price on emissions would, on its own, drive the innovation and behavioral change needed to meet climate targets — the assumption being that rational actors would respond predictably to price signals. The empirical record has been less tidy. Firms in carbon-priced markets have frequently lobbied for exemptions, passed costs to consumers, and shifted production to unregulated jurisdictions rather than investing in cleaner technologies. _______ economists who once treated carbon pricing as close to a technocratic solution now emphasize that its effectiveness depends on complementary policies, enforcement capacity, and political durability that the price signal alone cannot guarantee.',
    question: 'Which choice completes the text with the most logical transition?',
    choices: [
      { label: 'A', text: 'Chastened by this evidence,' },
      { label: 'B', text: 'Nevertheless,' },
      { label: 'C', text: 'For instance,' },
      { label: 'D', text: 'Similarly,' },
    ],
    correctAnswer: 'A',
    explanation: 'The preceding sentences document that real-world behavior has not matched the rational-actor assumptions behind carbon pricing; the final sentence shows that economists have revised their position in response to this record. "Chastened by this evidence" captures the causal link — the empirical disappointments have humbled advocates — and the shift from confidence to qualification.',
    wrongAnswerExplanations: {
      B: '"Nevertheless" signals that the final sentence happens despite the preceding evidence, but the economists\' revised view is a direct response to that evidence, not a concession made in spite of it.',
      C: '"For instance" signals that the final sentence exemplifies a point just made, but it draws a broader conclusion about carbon pricing rather than illustrating the firms\' behavior already described.',
      D: '"Similarly" signals a parallel case, but the economists\' revised view is not another instance of the same phenomenon described in the preceding sentences; it is a conclusion drawn from those phenomena.',
    },
  },

  {
    id: 'sat-f4-rw-m2h-q27',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-hard',
    domain: 'Expression of Ideas',
    skill: 'Transitions',
    difficulty: 'hard',
    stimulus: 'The earliest maps of the ocean floor were assembled from isolated depth soundings taken by ships lowering weighted lines over the side — a technique so slow that centuries of measurement had charted only a fraction of the seafloor. Echo-sounding technology, developed in the early twentieth century, made it possible to record continuous depth profiles along a ship\'s path. _______ the broad outlines of mid-ocean ridges and deep trenches could be mapped within decades rather than millennia.',
    question: 'Which choice completes the text with the most logical transition?',
    choices: [
      { label: 'A', text: 'As a result,' },
      { label: 'B', text: 'Nevertheless,' },
      { label: 'C', text: 'In other words,' },
      { label: 'D', text: 'By contrast,' },
    ],
    correctAnswer: 'A',
    explanation: 'The third sentence describes a consequence of the echo-sounding technology introduced in the second sentence: because continuous depth profiles could now be recorded, broad features of the seafloor could be mapped quickly. "As a result" correctly signals this causal consequence.',
    wrongAnswerExplanations: {
      B: '"Nevertheless" signals that something happens despite an obstacle; the third sentence is not a concession but an outcome of the new technology.',
      C: '"In other words" signals a restatement or clarification, but the third sentence introduces a new consequence rather than restating what was just said.',
      D: '"By contrast" signals an opposition or difference, but the third sentence extends and follows from the preceding point rather than opposing it.',
    },
  },

  {
    id: 'sat-f4-rw-m2h-q26',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-hard',
    domain: 'Expression of Ideas',
    skill: 'Transitions',
    difficulty: 'hard',
    stimulus: 'The survey found that most respondents said they valued long-form journalism and wished more of it were produced. Their actual reading habits told a different story: the same respondents spent the bulk of their time on short, quickly consumed articles. _______ what people say they want and what they choose to read can diverge sharply.',
    question: 'Which choice completes the text with the most logical transition?',
    choices: [
      { label: 'A', text: 'In short,' },
      { label: 'B', text: 'By contrast,' },
      { label: 'C', text: 'For instance,' },
      { label: 'D', text: 'Similarly,' },
    ],
    correctAnswer: 'A',
    explanation: 'The final sentence sums up the preceding point — that stated preferences and actual reading habits diverge. "In short" correctly signals a concluding summary of the gap just described.',
    wrongAnswerExplanations: {
      B: '"By contrast" would introduce an opposing idea, but the last sentence summarizes rather than contrasts.',
      C: '"For instance" introduces an example, but the sentence generalizes from the survey rather than giving an example.',
      D: '"Similarly" signals a parallel case, but the sentence draws a conclusion, not a comparison.',
    },
  },

  {
    id: 'sat-f4-rw-m2h-q08',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-hard',
    domain: 'Expression of Ideas',
    skill: 'Rhetorical Synthesis',
    difficulty: 'hard',
    stimulus: 'While researching a topic, a student has taken the following notes:\n• The philosopher Simone Weil argued that attention — the capacity to wait, without seeking, for truth to reveal itself — is the foundation of genuine ethical and intellectual life.\n• For Weil, attention differs from willpower: willpower effortfully imposes itself, while attention empties the self and allows reality to enter.\n• She contended that modern education, by prizing speed and the quick production of correct answers, systematically undermines the capacity for attention.\n• Weil saw the cultivation of attention as having both moral and epistemological stakes: it was necessary for perceiving the reality of other people\'s suffering as well as for rigorous thought.',
    question: 'The student wants to explain why Weil regarded modern education as deficient, while also conveying what she believed was lost as a result. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
    choices: [
      { label: 'A', text: 'Weil distinguished attention from willpower, arguing that genuine attention requires emptying the self rather than effortfully imposing it.' },
      { label: 'B', text: 'Because modern education prizes speed and quick answers, Weil argued, it undermines attention — the very capacity she held necessary for both rigorous thought and perceiving others\' suffering.' },
      { label: 'C', text: 'Weil believed that attention, not willpower, was the foundation of ethical and intellectual life, and she distinguished the two carefully.' },
      { label: 'D', text: 'Weil saw attention as having both moral and epistemological stakes, making it central to her philosophy.' },
    ],
    correctAnswer: 'B',
    explanation: 'The goal requires both explaining the deficiency (education prizes speed and quick answers, undermining attention) and conveying what is lost (attention, which is necessary for rigorous thought and perceiving others\' suffering). Choice B synthesizes two separate notes to meet both parts of the goal.',
    wrongAnswerExplanations: {
      A: 'This explains the distinction between attention and willpower but says nothing about education\'s deficiency or what is lost.',
      C: 'This characterizes attention generally but does not address education\'s deficiency or what is lost when attention is undermined.',
      D: 'This states the stakes of attention but does not explain what is wrong with modern education or how education undermines those stakes.',
    },
  },

  {
    id: 'sat-f4-rw-m2h-q25',
    section: 'reading-writing',
    moduleId: 'f4-rw-module-2-hard',
    domain: 'Expression of Ideas',
    skill: 'Rhetorical Synthesis',
    difficulty: 'hard',
    stimulus: 'While researching a topic, a student has taken the following notes:\n• Lichens are composite organisms made of a fungus and an alga (or cyanobacterium) living together.\n• The fungus provides structure and protection; the photosynthetic partner produces food.\n• Lichens can grow on bare rock, breaking it down over time into soil.\n• Because they absorb substances directly from the air, lichens are sensitive to pollution and are used to monitor air quality.',
    question: 'The student wants to explain how lichens contribute to the formation of soil. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
    choices: [
      { label: 'A', text: 'Lichens can grow on bare rock, and over time they break it down, helping to form soil.' },
      { label: 'B', text: 'Lichens are composite organisms made of a fungus and a photosynthetic partner living together.' },
      { label: 'C', text: 'Because they absorb substances from the air, lichens are used to monitor air quality.' },
      { label: 'D', text: 'In a lichen, the fungus provides structure while the photosynthetic partner produces food.' },
    ],
    correctAnswer: 'A',
    explanation: 'The goal is to explain lichens\' role in soil formation. Choice A states that lichens grow on bare rock and break it down over time, helping form soil — directly on point.',
    wrongAnswerExplanations: {
      B: 'This defines what a lichen is but says nothing about soil formation.',
      C: 'This concerns pollution monitoring, not soil formation.',
      D: 'This describes the partnership within a lichen, not how lichens form soil.',
    },
  },
]
