import type { MathQuestion } from './types'

export const f4MathModule1Questions: MathQuestion[] = [
  {
    id: 'sat-f4-math-m1-q01',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Algebra',
    skill: 'Linear equations in one variable',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'A phone plan charges a flat monthly fee plus $0.05 per minute of calls. In a month with 200 minutes of calls, the bill was $35. What is the flat monthly fee?',
    choices: [
      { label: 'A', text: '$10' },
      { label: 'B', text: '$15' },
      { label: 'C', text: '$25' },
      { label: 'D', text: '$30' },
    ],
    correctAnswer: 'C',
    explanation: 'The call charge is 200 × $0.05 = $10. The bill is fee + $10 = $35, so the fee = $35 − $10 = $25.',
    wrongAnswerExplanations: {
      A: '$10 is the cost of the call minutes, not the flat fee.',
      B: '$15 would make the total 15 + 10 = $25, not $35.',
      D: '$30 would make the total 30 + 10 = $40, not $35.',
    },
  },

  {
    id: 'sat-f4-math-m1-q07',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Geometry and Trigonometry',
    skill: 'Lines, angles, and triangles',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'In a triangle, the measures of the three angles are x°, (2x)°, and (3x)°. What is the measure of the largest angle?',
    choices: [
      { label: 'A', text: '30°' },
      { label: 'B', text: '60°' },
      { label: 'C', text: '90°' },
      { label: 'D', text: '120°' },
    ],
    correctAnswer: 'C',
    explanation: 'The angles sum to 180°: x + 2x + 3x = 180 → 6x = 180 → x = 30. The largest angle is 3x = 90°.',
    wrongAnswerExplanations: {
      A: '30° = x is the smallest angle, not the largest.',
      B: '60° = 2x is the middle angle, not the largest.',
      D: '120° exceeds 3x = 90°; the three angles are 30°, 60°, and 90°.',
    },
  },

  {
    id: 'sat-f4-math-m1-q08',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Advanced Math',
    skill: 'Quadratic functions',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'The function f(x) = 2x² − 8x + 5 has a minimum value. What is that minimum value?',
    choices: [
      { label: 'A', text: '−5' },
      { label: 'B', text: '−3' },
      { label: 'C', text: '3' },
      { label: 'D', text: '5' },
    ],
    correctAnswer: 'B',
    explanation: 'The vertex is at x = −(−8)/(2·2) = 8/4 = 2. f(2) = 2(4) − 8(2) + 5 = 8 − 16 + 5 = −3.',
    wrongAnswerExplanations: {
      A: '−5 is not the minimum; f(2) = −3.',
      C: '3 has the correct magnitude but the wrong sign.',
      D: '5 is the y-intercept f(0), not the minimum value.',
    },
  },

  {
    id: 'sat-f4-math-m1-q02',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Algebra',
    skill: 'Linear equations in two variables',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'The line y = mx + 4 passes through the point (3, 13). What is the value of m?',
    choices: [
      { label: 'A', text: '2' },
      { label: 'B', text: '3' },
      { label: 'C', text: '4' },
      { label: 'D', text: '5' },
    ],
    correctAnswer: 'B',
    explanation: 'Substitute the point: 13 = m(3) + 4 → 3m = 9 → m = 3.',
    wrongAnswerExplanations: {
      A: 'm = 2 gives y = 2(3) + 4 = 10, not 13.',
      C: 'm = 4 gives y = 4(3) + 4 = 16, not 13.',
      D: 'm = 5 gives y = 5(3) + 4 = 19, not 13.',
    },
  },

  {
    id: 'sat-f4-math-m1-q13',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Geometry and Trigonometry',
    skill: 'Circles',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'A circle has a circumference of 16π. What is the area of the circle?',
    choices: [
      { label: 'A', text: '16π' },
      { label: 'B', text: '32π' },
      { label: 'C', text: '64π' },
      { label: 'D', text: '256π' },
    ],
    correctAnswer: 'C',
    explanation: 'Circumference = 2πr = 16π → r = 8. Area = πr² = π(8²) = 64π.',
    wrongAnswerExplanations: {
      A: '16π equals the circumference, not the area.',
      B: '32π = 4πr uses the diameter incorrectly instead of r².',
      D: '256π uses r = 16 (the diameter) instead of the radius r = 8.',
    },
  },

  {
    id: 'sat-f4-math-m1-q09',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Advanced Math',
    skill: 'Equivalent expressions',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'Which expression is equivalent to (2x + 3)(x − 4) − (x² − 5x)?',
    choices: [
      { label: 'A', text: 'x² − 12' },
      { label: 'B', text: 'x² − 10x − 12' },
      { label: 'C', text: 'x² − 12x + 12' },
      { label: 'D', text: '3x² − 10x − 12' },
    ],
    correctAnswer: 'A',
    explanation: '(2x + 3)(x − 4) = 2x² − 8x + 3x − 12 = 2x² − 5x − 12. Subtracting (x² − 5x): 2x² − 5x − 12 − x² + 5x = x² − 12.',
    wrongAnswerExplanations: {
      B: 'This keeps the −5x term instead of canceling it with +5x.',
      C: 'This mishandles signs when distributing the subtraction.',
      D: 'This fails to subtract the x² term, leaving 3x² instead of x².',
    },
  },

  {
    id: 'sat-f4-math-m1-q03',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Algebra',
    skill: 'Linear functions',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'A tank contains 500 liters of water and drains at a constant rate. After 8 minutes, 340 liters remain. Which function gives the number of liters L remaining after t minutes?',
    choices: [
      { label: 'A', text: 'L = 500 − 8t' },
      { label: 'B', text: 'L = 500 − 20t' },
      { label: 'C', text: 'L = 500 − 40t' },
      { label: 'D', text: 'L = 340 − 20t' },
    ],
    correctAnswer: 'B',
    explanation: 'The tank loses 500 − 340 = 160 liters in 8 minutes, a rate of 160/8 = 20 liters per minute. Starting from 500: L = 500 − 20t.',
    wrongAnswerExplanations: {
      A: 'A rate of 8 liters/min would leave 500 − 64 = 436 after 8 minutes, not 340.',
      C: 'A rate of 40 liters/min would drain 320 in 8 minutes, leaving 180, not 340.',
      D: 'The starting amount is 500 liters, not 340.',
    },
  },

  {
    id: 'sat-f4-math-m1-q14',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'Ratios, rates, proportional relationships, and units',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'A machine fills 45 bottles in 3 minutes at a constant rate. At this rate, how many bottles will it fill in 20 minutes?',
    choices: [
      { label: 'A', text: '150' },
      { label: 'B', text: '225' },
      { label: 'C', text: '300' },
      { label: 'D', text: '900' },
    ],
    correctAnswer: 'C',
    explanation: 'Rate = 45/3 = 15 bottles per minute. In 20 minutes: 15 × 20 = 300 bottles.',
    wrongAnswerExplanations: {
      A: '150 uses a rate of 7.5 bottles/min, which is half the correct rate.',
      B: '225 corresponds to 15 minutes, not 20.',
      D: '900 multiplies 45 by 20, treating 45 as a per-minute rate.',
    },
  },

  {
    id: 'sat-f4-math-m1-q10',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Advanced Math',
    skill: 'Exponential functions',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'The value of a car is $24,000 and decreases by 15% each year. Which function models the value V of the car after t years?',
    choices: [
      { label: 'A', text: 'V = 24000(1.15)^t' },
      { label: 'B', text: 'V = 24000(0.85)^t' },
      { label: 'C', text: 'V = 24000(0.15)^t' },
      { label: 'D', text: 'V = 24000 − 0.15t' },
    ],
    correctAnswer: 'B',
    explanation: 'A 15% decrease each year multiplies the value by (1 − 0.15) = 0.85 per year, so V = 24000(0.85)^t.',
    wrongAnswerExplanations: {
      A: '(1.15)^t models 15% growth, not decay.',
      C: '(0.15)^t means retaining only 15% each year, an 85% decrease.',
      D: 'This is linear decay, not the exponential 15% yearly decrease.',
    },
  },

  {
    id: 'sat-f4-math-m1-q04',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Algebra',
    skill: 'Systems of two linear equations in two variables',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'At a concession stand, 3 hot dogs and 2 drinks cost $16, while 1 hot dog and 4 drinks cost $12. What is the price of one hot dog?',
    choices: [
      { label: 'A', text: '$2.00' },
      { label: 'B', text: '$3.00' },
      { label: 'C', text: '$4.00' },
      { label: 'D', text: '$5.00' },
    ],
    correctAnswer: 'C',
    explanation: 'Let h = hot dog price, d = drink price. 3h + 2d = 16 and h + 4d = 12. Multiply the first by 2: 6h + 4d = 32. Subtract the second: 5h = 20 → h = 4.',
    wrongAnswerExplanations: {
      A: '$2.00 gives 3(2) + 2d = 16 → d = 5, but then 2 + 4(5) = 22 ≠ 12.',
      B: '$3.00 gives 3(3) + 2d = 16 → d = 3.5, but then 3 + 4(3.5) = 17 ≠ 12.',
      D: '$5.00 gives 3(5) + 2d = 16 → d = 0.5, but then 5 + 4(0.5) = 7 ≠ 12.',
    },
  },

  {
    id: 'sat-f4-math-m1-q15',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'Percentages',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'A jacket is on sale for $68 after a 15% discount off its original price. What was the original price?',
    choices: [
      { label: 'A', text: '$78.20' },
      { label: 'B', text: '$80.00' },
      { label: 'C', text: '$83.00' },
      { label: 'D', text: '$85.00' },
    ],
    correctAnswer: 'B',
    explanation: 'The sale price is 85% of the original: 0.85 × original = 68 → original = 68/0.85 = 80.',
    wrongAnswerExplanations: {
      A: '$78.20 adds 15% of 68 back onto 68, which is not the correct reverse of a discount.',
      C: '$83.00 does not satisfy 0.85 × price = 68.',
      D: '$85.00 gives a sale price of 0.85 × 85 = $72.25, not $68.',
    },
  },

  {
    id: 'sat-f4-math-m1-q11',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Advanced Math',
    skill: 'Nonlinear equations in one variable and systems of equations',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'What is the sum of the solutions to the equation x² − 7x + 10 = 0?',
    choices: [
      { label: 'A', text: '3' },
      { label: 'B', text: '5' },
      { label: 'C', text: '7' },
      { label: 'D', text: '10' },
    ],
    correctAnswer: 'C',
    explanation: 'Factoring: (x − 2)(x − 5) = 0, so x = 2 or x = 5. Their sum is 2 + 5 = 7. (Equivalently, the sum of roots equals −b/a = 7.)',
    wrongAnswerExplanations: {
      A: '3 is the difference of the roots (5 − 2), not the sum.',
      B: '5 is one of the roots, not the sum of both.',
      D: '10 is the product of the roots (2 × 5), not the sum.',
    },
  },

  {
    id: 'sat-f4-math-m1-q05',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Algebra',
    skill: 'Linear inequalities in one or two variables',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'A delivery van can carry at most 1,200 kilograms. It is already loaded with 450 kilograms of equipment. Each box weighs 25 kilograms. What is the maximum number of boxes b the van can additionally carry?',
    choices: [
      { label: 'A', text: '18' },
      { label: 'B', text: '24' },
      { label: 'C', text: '30' },
      { label: 'D', text: '48' },
    ],
    correctAnswer: 'C',
    explanation: '450 + 25b ≤ 1200 → 25b ≤ 750 → b ≤ 30. The maximum is 30 boxes.',
    wrongAnswerExplanations: {
      A: '18 uses only part of the remaining capacity and is not the maximum.',
      B: '24 boxes weigh 600 kg; there is room for more.',
      D: '48 ignores the 450 kg already loaded: 48 × 25 = 1200 alone exceeds the remaining capacity.',
    },
  },

  {
    id: 'sat-f4-math-m1-q16',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'Two-variable data: models and scatterplots',
    difficulty: 'medium',
    type: 'multiple_choice',
    graphData: {
      type: 'scatter',
      xLabel: 'Advertising ($1000s)',
      yLabel: 'Sales ($1000s)',
      xMin: 0, xMax: 10, yMin: 0, yMax: 60,
      points: [[1, 14], [2, 20], [3, 23], [4, 30], [5, 34], [6, 41], [7, 44], [8, 52]],
      trendLine: { slope: 5, intercept: 9, color: '#4f46e5' },
    },
    question: 'The scatterplot shows sales versus advertising spending for 8 months, along with the line of best fit y = 5x + 9. Based on the model, what is the predicted sales value (in $1000s) when advertising is $6,000 (x = 6)?',
    choices: [
      { label: 'A', text: '30' },
      { label: 'B', text: '36' },
      { label: 'C', text: '39' },
      { label: 'D', text: '41' },
    ],
    correctAnswer: 'C',
    explanation: 'Substitute x = 6 into the model: y = 5(6) + 9 = 30 + 9 = 39.',
    wrongAnswerExplanations: {
      A: '30 = 5 × 6 forgets to add the intercept of 9.',
      B: '36 uses an intercept of 6 rather than 9.',
      D: '41 is the observed data value at x = 6, not the model prediction.',
    },
  },

  {
    id: 'sat-f4-math-m1-q12',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Advanced Math',
    skill: 'Nonlinear functions',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'The function f is defined by f(x) = x² + 1. If g(x) = f(x − 3), what is g(5)?',
    choices: [
      { label: 'A', text: '5' },
      { label: 'B', text: '11' },
      { label: 'C', text: '17' },
      { label: 'D', text: '26' },
    ],
    correctAnswer: 'A',
    explanation: 'g(5) = f(5 − 3) = f(2) = 2² + 1 = 5.',
    wrongAnswerExplanations: {
      B: '11 does not follow from g(5) = f(2) = 5.',
      C: '17 = f(4) uses x = 4 (from 5 − 1) instead of 5 − 3 = 2.',
      D: '26 = f(5) forgets the −3 horizontal shift.',
    },
  },

  {
    id: 'sat-f4-math-m1-q06',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Algebra',
    skill: 'Linear equations in two variables',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'The system 4x + 6y = 10 and 2x + ky = 7 has no solution. What is the value of k?',
    choices: [
      { label: 'A', text: '3' },
      { label: 'B', text: '4' },
      { label: 'C', text: '6' },
      { label: 'D', text: '12' },
    ],
    correctAnswer: 'A',
    explanation: 'No solution means the lines are parallel: the x- and y-coefficient ratios match but the constants differ. 4/2 = 6/k → k = 6/2 = 3. Check: with k = 3, the second equation ×2 gives 4x + 6y = 14 ≠ 10, so the lines are parallel with no solution.',
    wrongAnswerExplanations: {
      B: 'k = 4 gives non-proportional coefficients (4/2 ≠ 6/4), so the lines intersect.',
      C: 'k = 6 does not make the x- and y-coefficient ratios equal.',
      D: 'k = 12 gives 4/2 ≠ 6/12, so the lines are not parallel.',
    },
  },

  {
    id: 'sat-f4-math-m1-q17',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'One-variable data: distributions and measures of center and spread',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'A data set consists of the values 4, 7, 7, 10, 12. Let m be the mean and M be the median. What is the value of m − M?',
    choices: [
      { label: 'A', text: '−1' },
      { label: 'B', text: '0' },
      { label: 'C', text: '1' },
      { label: 'D', text: '2' },
    ],
    correctAnswer: 'C',
    explanation: 'Mean = (4 + 7 + 7 + 10 + 12)/5 = 40/5 = 8. The ordered list is 4, 7, 7, 10, 12, so the median (middle value) is 7. Therefore m − M = 8 − 7 = 1.',
    wrongAnswerExplanations: {
      A: '−1 reverses the sign; the mean (8) exceeds the median (7).',
      B: '0 would require equal mean and median, but they are 8 and 7.',
      D: '2 overstates the difference between the mean (8) and median (7).',
    },
  },

  {
    id: 'sat-f4-math-m1-q20',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Geometry and Trigonometry',
    skill: 'Right triangles and trigonometry',
    difficulty: 'medium',
    type: 'grid_in',
    graphData: {
      type: 'geometry',
      viewBox: { xMin: -1.5, xMax: 10, yMin: -1.5, yMax: 6.5 },
      elements: [
        { kind: 'poly', pts: [[0, 0], [8, 0], [0, 6]] as [number, number][] },
        { kind: 'right_angle', v: [0, 0] as [number, number], a: [8, 0] as [number, number], b: [0, 6] as [number, number] },
        { kind: 'label', x: 4, y: -0.8, text: '8' },
        { kind: 'label', x: -0.8, y: 3, text: '6' },
        { kind: 'label', x: 4.5, y: 3.5, text: '?' },
      ],
    },
    question: 'A right triangle has legs of length 6 and 8. What is the length of the hypotenuse?',
    correctAnswer: '10',
    acceptableAnswers: ['10'],
    explanation: 'By the Pythagorean theorem: hypotenuse = √(6² + 8²) = √(36 + 64) = √100 = 10.',
  },

  {
    id: 'sat-f4-math-m1-q19',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Algebra',
    skill: 'Linear equations in one variable',
    difficulty: 'medium',
    type: 'grid_in',
    question: 'If 5(x − 3) = 2x + 9, what is the value of x?',
    correctAnswer: '8',
    acceptableAnswers: ['8'],
    explanation: '5x − 15 = 2x + 9 → 3x = 24 → x = 8.',
  },

  {
    id: 'sat-f4-math-m1-q18',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'Probability and conditional probability',
    difficulty: 'hard',
    type: 'grid_in',
    graphData: {
      type: 'table',
      title: 'Beverage Preferences',
      headers: ['', 'Coffee', 'Tea', 'Total'],
      rows: [
        ['Students', '48', '32', '80'],
        ['Teachers', '12', '8', '20'],
        ['Total', '60', '40', '100'],
      ],
    },
    question: 'The table shows the beverage preferences of 100 people. If one person who prefers tea is selected at random, what is the probability that the person is a teacher? Enter your answer as a decimal.',
    correctAnswer: '0.2',
    acceptableAnswers: ['0.2', '.2', '1/5'],
    explanation: 'Among the 40 tea drinkers, 8 are teachers. P(teacher | tea) = 8/40 = 0.2.',
  },

  {
    id: 'sat-f4-math-m1-q21',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Advanced Math',
    skill: 'Quadratic functions',
    difficulty: 'hard',
    type: 'grid_in',
    question: 'The parabola y = x² − 10x + 21 crosses the x-axis at two points. What is the x-coordinate of its vertex?',
    correctAnswer: '5',
    acceptableAnswers: ['5'],
    explanation: 'The x-coordinate of the vertex is −b/(2a) = −(−10)/(2·1) = 10/2 = 5. (Equivalently, the roots are x = 3 and x = 7, whose midpoint is 5.)',
  },

  {
    id: 'sat-f4-math-m1-q22',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Geometry and Trigonometry',
    skill: 'Right triangles and trigonometry',
    difficulty: 'hard',
    type: 'grid_in',
    question: 'In right triangle ABC, the right angle is at C. If sin A = 3/5 and the hypotenuse AB has length 20, what is the length of side BC (the side opposite angle A)?',
    correctAnswer: '12',
    acceptableAnswers: ['12'],
    explanation: 'sin A = opposite/hypotenuse = BC/AB = BC/20 = 3/5, so BC = 20 × 3/5 = 12.',
  },
]
