import type { RWQuestion } from './types'

export const f5RwModule2HardQuestions: RWQuestion[] = [
  {
    id: 'sat-f5-rw-m2h-q27',
    section: 'reading-writing',
    moduleId: 'f5-rw-module-2-hard',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'hard',
    stimulus: 'The lead researcher, along with the three postdoctoral fellows who had contributed the bulk of the laboratory work and the statistician who _______ the final dataset for inconsistencies over the preceding six weeks, was listed as a co-author on the published paper.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choices: [
      { label: 'A', text: 'had been auditing' },
      { label: 'B', text: 'has been auditing' },
      { label: 'C', text: 'audits' },
      { label: 'D', text: 'is auditing' },
    ],
    correctAnswer: 'A',
    explanation: 'Choice A is correct. The action of auditing occurred over the six weeks preceding the publication of the paper — a past action completed before another past event. The past perfect progressive ("had been auditing") correctly conveys ongoing activity in the past that concluded before the reference point.',
    wrongAnswerExplanations: {
      B: 'Choice B is incorrect. The present perfect progressive ("has been auditing") implies the action extends to the present, but the auditing is described as occurring over the preceding six weeks before a past publication — it is complete.',
      C: 'Choice C is incorrect. The simple present ("audits") does not fit the past-time frame of the entire sentence, which describes events leading to a past publication.',
      D: 'Choice D is incorrect. The present progressive ("is auditing") implies the auditing is happening now, which contradicts the past-time context and the phrase "over the preceding six weeks."',
    },
  },

  {
    id: 'sat-f5-rw-m2h-q09',
    section: 'reading-writing',
    moduleId: 'f5-rw-module-2-hard',
    domain: 'Information and Ideas',
    skill: 'Central Ideas and Details',
    difficulty: 'medium',
    stimulus: 'Astronomers studying exoplanet atmospheres have begun distinguishing between two classes of sub-Neptune worlds: "water worlds," which appear to have thick envelopes of steam or water, and "rocky super-Earths," which have thin or negligible atmospheres. Early transit spectroscopy lacked the resolution to tell them apart. The James Webb Space Telescope has now provided spectra detailed enough to identify the water-vapor signatures characteristic of the former class, offering the first systematic means of separating the two populations and helping constrain models of how planets at this mass range form and evolve.',
    question: 'Which choice best states the main idea of the text?',
    choices: [
      { label: 'A', text: 'The James Webb Space Telescope has confirmed that all sub-Neptune planets have water in their atmospheres' },
      { label: 'B', text: 'New spectroscopic data from the James Webb Space Telescope allows astronomers to distinguish between two previously hard-to-separate classes of sub-Neptune worlds' },
      { label: 'C', text: 'Rocky super-Earths are more common than water worlds among sub-Neptune exoplanets' },
      { label: 'D', text: 'Transit spectroscopy was abandoned in favor of direct imaging after the James Webb Space Telescope launched' },
    ],
    correctAnswer: 'B',
    explanation: 'The passage\'s main point is that JWST\'s high-resolution spectra can now identify water-vapor signatures, enabling astronomers to separate two sub-Neptune populations they previously could not distinguish.',
    wrongAnswerExplanations: {
      A: 'The passage describes a means of distinguishing water worlds from rocky super-Earths; it does not claim all sub-Neptunes have water.',
      C: 'The passage does not compare the frequency of the two populations.',
      D: 'The passage says transit spectroscopy lacked resolution before JWST, not that it was abandoned.',
    },
  },

  {
    id: 'sat-f5-rw-m2h-q17',
    section: 'reading-writing',
    moduleId: 'f5-rw-module-2-hard',
    domain: 'Expression of Ideas',
    skill: 'Transitions',
    difficulty: 'medium',
    stimulus: 'The initial trial of the new drug produced striking results, with patients in the treatment group showing significantly faster recovery times than those receiving the placebo. _______ the sample size was small and the follow-up period lasted only eight weeks, leaving open questions about long-term efficacy and whether the effect would persist in a larger, more diverse population.',
    question: 'Which choice completes the text with the most logical transition?',
    choices: [
      { label: 'A', text: 'Therefore,' },
      { label: 'B', text: 'Furthermore,' },
      { label: 'C', text: 'However,' },
      { label: 'D', text: 'Similarly,' },
    ],
    correctAnswer: 'C',
    explanation: '"However" signals a contrast or qualification. The first sentence reports a positive finding; the second introduces limitations (small sample, brief follow-up) that qualify the optimism, making "However" the correct logical connector.',
    wrongAnswerExplanations: {
      A: '"Therefore" introduces a conclusion that follows logically; the second sentence does not conclude from the first but qualifies it.',
      B: '"Furthermore" adds to or extends a point in the same direction; the second sentence introduces a contrary qualification.',
      D: '"Similarly" signals that two things are alike; the second sentence contrasts with the first by raising concerns.',
    },
  },

  {
    id: 'sat-f5-rw-m2h-q02',
    section: 'reading-writing',
    moduleId: 'f5-rw-module-2-hard',
    domain: 'Craft and Structure',
    skill: 'Words in Context',
    difficulty: 'hard',
    stimulus: 'The council\'s decision to reclassify the wetlands was _______ at best: the legal authority it cited had never been applied to ecosystems, the scientific review it commissioned ran counter to its conclusion, and three of its own members filed written dissents — yet the ruling stood.',
    question: 'Which choice completes the text with the most logical and precise word or phrase?',
    choices: [
      { label: 'A', text: 'contentious' },
      { label: 'B', text: 'tenuous' },
      { label: 'C', text: 'innovative' },
      { label: 'D', text: 'cautious' },
    ],
    correctAnswer: 'B',
    explanation: '"Tenuous" means weakly supported or lacking a solid foundation. The council\'s authority, the contradictory scientific review, and the internal dissents all suggest the ruling rested on extremely weak grounds — a tenuous basis at best.',
    wrongAnswerExplanations: {
      A: '"Contentious" means causing disagreement or dispute; while the ruling was disputed, the passage is specifically cataloguing the weakness of the council\'s grounds, not merely the existence of opposition.',
      C: '"Innovative" means introducing something new; the passage criticizes the reasoning, not praises its novelty.',
      D: '"Cautious" means careful to avoid risk; the ruling proceeded despite its many problems, which is the opposite of caution.',
    },
  },

  {
    id: 'sat-f5-rw-m2h-q10',
    section: 'reading-writing',
    moduleId: 'f5-rw-module-2-hard',
    domain: 'Information and Ideas',
    skill: 'Central Ideas and Details',
    difficulty: 'hard',
    stimulus: 'Scholars of ancient trade have long assumed that luxury goods moved along well-defined overland routes and that changes in route use reflected political disruptions: a new empire, a blocked pass, a shift in tariff regimes. Isotopic analysis of glass beads recovered from burial sites across Eurasia and sub-Saharan Africa is beginning to complicate that picture. Because the chemical signature of glass encodes the geological origin of its raw materials, researchers can now identify production centers with precision unavailable to documentary historians. Beads are appearing in combinations — productions of the Levant paired with those of South Asia, alongside goods of East African origin — that suggest far more fluid, multipolar networks than the route-based model implies.',
    question: 'Which choice best states the main idea of the text?',
    choices: [
      { label: 'A', text: 'Isotopic analysis has confirmed that ancient trade was organized around a small number of fixed overland routes' },
      { label: 'B', text: 'Chemical analysis of ancient glass beads suggests that trade networks were more fluid and multipolar than the established route-based model assumed' },
      { label: 'C', text: 'The Levant was the dominant center of glass bead production in the ancient world' },
      { label: 'D', text: 'Documentary historians have long had the tools to identify the precise origins of ancient luxury goods' },
    ],
    correctAnswer: 'B',
    explanation: 'The passage presents isotopic analysis as "complicating" the route-based model, with bead combinations suggesting fluid, multipolar networks — which is the main idea.',
    wrongAnswerExplanations: {
      A: 'The passage says the new evidence challenges, not confirms, the fixed-route model.',
      C: 'The passage mentions the Levant as one production center among several; it does not claim Levantine dominance.',
      D: 'The passage notes that documentary historians lacked the precision that isotopic analysis now provides.',
    },
  },

  {
    id: 'sat-f5-rw-m2h-q18',
    section: 'reading-writing',
    moduleId: 'f5-rw-module-2-hard',
    domain: 'Expression of Ideas',
    skill: 'Transitions',
    difficulty: 'hard',
    stimulus: 'Proponents of universal basic income frequently cite the potential to reduce poverty without the stigma or administrative burden of means-tested programs. Critics counter that unconditional cash transfers could reduce labor market participation and strain government budgets. _______ economists studying pilot programs in Finland, Kenya, and Stockton, California found that recipients did not significantly reduce working hours and reported improvements in mental health and job-seeking behavior.',
    question: 'Which choice completes the text with the most logical transition?',
    choices: [
      { label: 'A', text: 'In other words,' },
      { label: 'B', text: 'Accordingly,' },
      { label: 'C', text: 'In fact,' },
      { label: 'D', text: 'By the same token,' },
    ],
    correctAnswer: 'C',
    explanation: '"In fact" introduces evidence that contradicts or strengthens a prior claim — here it pushes back on the critics\' concern by presenting real-world data showing that recipients did not reduce work and improved in other ways.',
    wrongAnswerExplanations: {
      A: '"In other words" signals a restatement or clarification; the final sentence does not rephrase what came before but introduces new empirical evidence.',
      B: '"Accordingly" signals a logical consequence; the pilot program findings follow from the debate as evidence, not as a consequence of either side\'s position.',
      D: '"By the same token" signals that the same reasoning applies; the pilot findings introduce new evidence rather than extending a prior line of reasoning.',
    },
  },

  {
    id: 'sat-f5-rw-m2h-q03',
    section: 'reading-writing',
    moduleId: 'f5-rw-module-2-hard',
    domain: 'Craft and Structure',
    skill: 'Words in Context',
    difficulty: 'hard',
    stimulus: 'The biographer spent four years _______ her subject\'s correspondence, reading hundreds of letters in a dozen archives across two continents, tracking the writer\'s shifting attitudes toward religion through decades of private disclosure.',
    question: 'Which choice completes the text with the most logical and precise word or phrase?',
    choices: [
      { label: 'A', text: 'cataloguing' },
      { label: 'B', text: 'excavating' },
      { label: 'C', text: 'combing' },
      { label: 'D', text: 'publishing' },
    ],
    correctAnswer: 'C',
    explanation: '"Combing" means searching through thoroughly and carefully, which precisely fits spending four years reading hundreds of letters across many archives to track subtle shifts in attitude.',
    wrongAnswerExplanations: {
      A: '"Cataloguing" means organizing and listing items systematically; the passage emphasizes thorough reading and interpretation, not organizational indexing.',
      B: '"Excavating" typically refers to digging and is used metaphorically to mean uncovering buried material; while partially plausible, it implies finding hidden things rather than the sustained, attentive reading the passage describes.',
      D: '"Publishing" means making public, the opposite of what a researcher does in archives.',
    },
  },

  {
    id: 'sat-f5-rw-m2h-q11',
    section: 'reading-writing',
    moduleId: 'f5-rw-module-2-hard',
    domain: 'Information and Ideas',
    skill: 'Command of Evidence',
    difficulty: 'medium',
    stimulus: 'A team of behavioral ecologists hypothesized that in highly social bird species, individuals that engage in more affiliative behaviors — such as allopreening and food-sharing — would have lower baseline corticosteroid levels than more solitary individuals of the same species. They measured corticosteroid concentrations in blood samples taken from 120 individually tracked zebra finches and cross-referenced these with behavioral observation logs collected over six months.',
    question: 'Which finding, if true, would most directly support the researchers\' hypothesis?',
    choices: [
      { label: 'A', text: 'Zebra finches observed allopreening or sharing food frequently had significantly lower corticosteroid levels than those observed engaging in such behaviors rarely' },
      { label: 'B', text: 'Corticosteroid levels varied more between breeding seasons than between individual birds' },
      { label: 'C', text: 'Zebra finches housed alone developed higher corticosteroid levels than those housed in large groups, regardless of individual behavioral variation' },
      { label: 'D', text: 'Researchers found no significant correlation between individual affiliation rates and corticosteroid levels in the sample' },
    ],
    correctAnswer: 'A',
    explanation: 'The hypothesis links individual affiliative behavior to lower corticosteroid levels. Choice A directly shows that individuals who engaged in affiliative behaviors more frequently had lower corticosteroid levels than those who did so rarely — a direct match.',
    wrongAnswerExplanations: {
      B: 'Seasonal variation in corticosteroid levels does not speak to individual behavioral differences within the sample.',
      C: 'This tests group size versus solitude rather than individual variation in affiliative behavior, which is what the hypothesis concerns.',
      D: 'No correlation would directly contradict, not support, the hypothesis.',
    },
  },

  {
    id: 'sat-f5-rw-m2h-q19',
    section: 'reading-writing',
    moduleId: 'f5-rw-module-2-hard',
    domain: 'Expression of Ideas',
    skill: 'Rhetorical Synthesis',
    difficulty: 'hard',
    stimulus: 'While researching a topic, a student has taken the following notes:\n• Mangrove forests grow along tropical and subtropical coastlines and can store carbon at rates three to five times higher per unit area than terrestrial forests.\n• Mangroves provide coastal protection by absorbing wave energy and reducing erosion during storms.\n• Deforestation has eliminated roughly 35% of global mangrove coverage since the 1980s, primarily due to shrimp aquaculture and coastal development.\n• Restoration projects in Vietnam and Sri Lanka have successfully re-established mangrove stands, with measurable improvements in fish nursery habitat within three years.\n• Each hectare of mangrove stores an estimated 1,000 metric tons of carbon in soil, roots, and above-ground biomass.',
    question: 'The student wants to argue that mangrove restoration is an economically and ecologically justified climate strategy. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
    choices: [
      { label: 'A', text: 'Mangroves have been eliminated from 35% of their historical range since the 1980s due to aquaculture and development.' },
      { label: 'B', text: 'Restoration projects have already succeeded in Vietnam and Sri Lanka, suggesting that re-establishing mangroves is feasible and that the carbon storage and coastal protection they provide make the investment ecologically and economically worthwhile.' },
      { label: 'C', text: 'Mangrove forests grow along tropical and subtropical coastlines and absorb wave energy during storms.' },
      { label: 'D', text: 'Each hectare of mangrove stores approximately 1,000 metric tons of carbon, more than terrestrial forests store per hectare.' },
    ],
    correctAnswer: 'B',
    explanation: 'The goal is to argue that mangrove restoration is economically and ecologically justified as a climate strategy. Choice B draws on restoration feasibility (proven in Vietnam and Sri Lanka), the ecological benefit (coastal protection), and the carbon-storage rationale — combining multiple notes to make the complete argument.',
    wrongAnswerExplanations: {
      A: 'This reports a problem (deforestation) but makes no argument for restoration as a climate strategy.',
      C: 'This describes where mangroves grow and one protective function but does not address climate justification or the case for restoration.',
      D: 'This cites only one ecological benefit (carbon storage) and omits the restoration feasibility and economic argument that the goal requires.',
    },
  },

  {
    id: 'sat-f5-rw-m2h-q04',
    section: 'reading-writing',
    moduleId: 'f5-rw-module-2-hard',
    domain: 'Craft and Structure',
    skill: 'Text Structure and Purpose',
    difficulty: 'medium',
    stimulus: 'For generations, popular accounts of the Roman Empire\'s fall blamed the barbarian invasions of the fifth century. Historians now increasingly regard the invasions not as a cause but as a symptom: they followed the collapse of frontier defense systems that themselves reflected deeper administrative, fiscal, and demographic pressures. The barbarians did not destroy a healthy empire; they moved into one that was already hollowing out.',
    question: 'What is the main purpose of the text?',
    choices: [
      { label: 'A', text: 'To show that the barbarian invasions had no historical significance' },
      { label: 'B', text: 'To challenge the popular explanation for Rome\'s fall by placing the invasions within broader systemic causes' },
      { label: 'C', text: 'To describe the military tactics the barbarians used to breach Roman defenses' },
      { label: 'D', text: 'To argue that demographic pressures were the only cause of Rome\'s fall' },
    ],
    correctAnswer: 'B',
    explanation: 'The passage reframes the invasions as a symptom rather than a cause, pointing instead to administrative, fiscal, and demographic pressures — challenging the popular account by embedding the invasions in a broader causal picture.',
    wrongAnswerExplanations: {
      A: 'The passage recontextualizes the invasions rather than dismissing their significance.',
      C: 'No military tactics are discussed.',
      D: 'The passage lists multiple pressures (administrative, fiscal, demographic); it does not single out demographics as the sole cause.',
    },
  },

  {
    id: 'sat-f5-rw-m2h-q12',
    section: 'reading-writing',
    moduleId: 'f5-rw-module-2-hard',
    domain: 'Information and Ideas',
    skill: 'Command of Evidence',
    difficulty: 'hard',
    stimulus: 'A historian argued that the relative stability of the Byzantine Empire during the seventh and eighth centuries — despite the Islamic conquests that stripped away its wealthiest provinces — was paradoxically enabled by those losses. Shedding Egypt, Syria, and Palestine removed the most deeply contested regions from imperial administration, reduced the fiscal burden of defending dispersed frontiers, and allowed Constantinople to consolidate authority over a more compact and ethnically coherent core. The historian concluded: the empire survived not in spite of contraction but through it.',
    question: 'Which finding, if true, would most directly support the historian\'s argument?',
    choices: [
      { label: 'A', text: 'Administrative records show that per-capita tax revenues in the remaining Byzantine territories increased in the decades following the loss of Egypt and Syria' },
      { label: 'B', text: 'The Islamic caliphate faced its own internal revolts during the same period, reducing pressure on Byzantine borders' },
      { label: 'C', text: 'Population decline in Egypt due to plague had already reduced its tax yield before the Islamic conquests' },
      { label: 'D', text: 'Byzantine military commanders stationed in the lost provinces frequently defected to Islamic forces' },
    ],
    correctAnswer: 'A',
    explanation: 'The historian\'s argument is that losing the contested outer provinces made the remaining empire more governable and fiscally sustainable. Rising per-capita revenues in remaining territories would directly support the claim that contraction improved the empire\'s core strength.',
    wrongAnswerExplanations: {
      B: 'External pressure from the caliphate is one factor, but this explains survival through an enemy\'s weakness, not through the Byzantine consolidation the historian emphasizes.',
      C: 'If Egypt was already yielding less due to plague, this would suggest the loss mattered less — but it does not support the positive argument that contraction itself enabled stability.',
      D: 'Defections would complicate rather than support the historian\'s claim, suggesting the lost provinces were difficult to hold rather than that losing them was beneficial.',
    },
  },

  {
    id: 'sat-f5-rw-m2h-q20',
    section: 'reading-writing',
    moduleId: 'f5-rw-module-2-hard',
    domain: 'Expression of Ideas',
    skill: 'Rhetorical Synthesis',
    difficulty: 'hard',
    stimulus: 'While researching a topic, a student has taken the following notes:\n• The Voynich manuscript is an illustrated codex written in an undeciphered script, carbon-dated to the early fifteenth century.\n• Attempts to decode the manuscript using frequency analysis, cryptographic techniques, and machine learning have all failed to produce a coherent translation.\n• Computational analysis by researchers at the University of Alberta found that the text obeys statistical patterns, including Zipf\'s Law, consistent with natural language rather than random symbol generation.\n• Some scholars argue the manuscript is an elaborate hoax; others maintain it encodes a genuine but unknown language or cipher.\n• A 2019 study proposed a phonetic theory linking the script to a constructed language derived from Latin, but the proposal has not gained wide acceptance.',
    question: 'The student wants to emphasize the central unresolved tension in Voynich manuscript scholarship. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
    choices: [
      { label: 'A', text: 'The Voynich manuscript was carbon-dated to the early fifteenth century and contains illustrations alongside its undeciphered text.' },
      { label: 'B', text: 'Although computational analysis shows the text behaves statistically like a natural language, no decipherment attempt has succeeded, leaving scholars divided between those who believe it encodes genuine meaning and those who consider it a hoax.' },
      { label: 'C', text: 'A 2019 phonetic theory proposed that the script derives from a Latin-based constructed language, offering a potential path to decipherment.' },
      { label: 'D', text: 'Researchers have applied frequency analysis, cryptographic methods, and machine learning to the manuscript without producing a coherent translation.' },
    ],
    correctAnswer: 'B',
    explanation: 'The central unresolved tension is between evidence suggesting genuine linguistic structure (Zipf\'s Law, natural-language statistics) and the complete failure to decode it, which feeds the debate between hoax and genuine-language camps. Choice B captures both sides of that tension precisely.',
    wrongAnswerExplanations: {
      A: 'This provides background facts (dating, illustrations) but does not convey any scholarly tension.',
      C: 'This presents one specific theory rather than the broader tension between the two scholarly camps.',
      D: 'This describes only the failure of decipherment attempts without capturing the countervailing statistical evidence that makes the puzzle intractable.',
    },
  },

  {
    id: 'sat-f5-rw-m2h-q05',
    section: 'reading-writing',
    moduleId: 'f5-rw-module-2-hard',
    domain: 'Craft and Structure',
    skill: 'Text Structure and Purpose',
    difficulty: 'hard',
    stimulus: 'The following is from a work of original literary fiction. He had spent thirty years building the firm into something he was proud of, something with a name that stood for a certain kind of honesty in a business not known for it. And now the partners were asking him to vote for a merger that would erase that name within six months. He kept his voice level during the meeting, said he would need time to consider it. He considered it for approximately eleven seconds on the drive home, and then he called his lawyer.',
    question: 'What is the main function of the sentence "He considered it for approximately eleven seconds on the drive home" in the text?',
    choices: [
      { label: 'A', text: 'To show that the character had already decided before the meeting and used the meeting to deceive the partners' },
      { label: 'B', text: 'To deflate the character\'s stated need for time, revealing that his mind was effectively already made up' },
      { label: 'C', text: 'To suggest that the character was driving carelessly' },
      { label: 'D', text: 'To explain why the character called his lawyer rather than his partners' },
    ],
    correctAnswer: 'B',
    explanation: 'The character says he needs time to consider the decision, but the next sentence undercuts that immediately — eleven seconds is not deliberation. The sentence deflates his stated need for time, revealing he was never genuinely undecided, and heightens the irony.',
    wrongAnswerExplanations: {
      A: 'The passage does not suggest he had decided before the meeting or intended to mislead; the eleven-second consideration happens after, not before, the meeting.',
      C: 'Driving is merely the setting; the sentence makes no comment on his attentiveness behind the wheel.',
      D: 'The sentence tells us how long he thought, not the reasoning behind calling a lawyer over partners.',
    },
  },

  {
    id: 'sat-f5-rw-m2h-q13',
    section: 'reading-writing',
    moduleId: 'f5-rw-module-2-hard',
    domain: 'Information and Ideas',
    skill: 'Command of Evidence',
    difficulty: 'hard',
    stimulus: 'An ecologist studying forest succession tracked tree species composition at twelve sites over forty years, recording dominant species at each site every five years. The ecologist concluded: "Early-successional species do not simply give way to late-successional species over time; the rate and direction of succession depend on initial site conditions, particularly soil nitrogen availability."',
    graphData: {
      type: 'table',
      title: 'Dominant Species After 40 Years by Initial Soil Nitrogen',
      headers: ['Site Group', 'Initial Nitrogen (mg/kg)', 'Dominant Species at Year 40', 'Succession Rate'],
      rows: [
        ['Low-N sites (n=4)', '12–18', 'Pioneer shrubs still dominant', 'Stalled'],
        ['Mid-N sites (n=4)', '28–34', 'Mixed pioneer and oak canopy', 'Moderate'],
        ['High-N sites (n=4)', '48–56', 'Closed-canopy beech-maple', 'Rapid'],
      ],
    },
    question: 'Which choice best uses data from the table to support the ecologist\'s conclusion?',
    choices: [
      { label: 'A', text: 'After forty years, all twelve sites were dominated by pioneer shrubs, showing that succession had stalled everywhere.' },
      { label: 'B', text: 'High-nitrogen sites reached closed-canopy beech-maple forest while low-nitrogen sites remained pioneer-shrub dominated, showing that nitrogen availability shaped the rate and direction of succession.' },
      { label: 'C', text: 'Mid-nitrogen sites had a higher nitrogen range than low-nitrogen sites, confirming that nitrogen levels differ across sites.' },
      { label: 'D', text: 'All sites showed some change in dominant species over forty years, confirming that succession always proceeds at the same rate.' },
    ],
    correctAnswer: 'B',
    explanation: 'The ecologist\'s conclusion is that nitrogen availability shapes both the rate and direction of succession. Choice B cites the contrast between high-N sites (rapid, reaching closed canopy) and low-N sites (stalled at pioneer shrubs) to directly demonstrate both aspects of that claim.',
    wrongAnswerExplanations: {
      A: 'This contradicts the table, which shows varied outcomes — high-N sites reached closed canopy.',
      C: 'This merely notes that nitrogen levels vary across site groups, which is a given, not evidence about succession outcomes.',
      D: 'The table shows different rates (stalled vs. moderate vs. rapid), contradicting the claim of a uniform rate.',
    },
  },

  {
    id: 'sat-f5-rw-m2h-q21',
    section: 'reading-writing',
    moduleId: 'f5-rw-module-2-hard',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'medium',
    stimulus: 'The geologist\'s report identified three distinct sediment layers _______ the deepest, composed of fine-grained silt deposited during a period of glacial meltwater flooding, predated the two upper layers by nearly six thousand years.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choices: [
      { label: 'A', text: 'layers;' },
      { label: 'B', text: 'layers,' },
      { label: 'C', text: 'layers:' },
      { label: 'D', text: 'layers' },
    ],
    correctAnswer: 'A',
    explanation: 'Choice A is correct. "The geologist\'s report identified three distinct sediment layers" is a complete independent clause, and "the deepest . . . predated the two upper layers by nearly six thousand years" is also a complete independent clause. A semicolon correctly joins two independent clauses without a coordinating conjunction.',
    wrongAnswerExplanations: {
      B: 'Choice B is incorrect. A comma alone between two independent clauses creates a comma splice.',
      C: 'Choice C is incorrect. A colon introduces what follows as an explanation or list, but the clause that follows is itself a full independent clause that does not function as a simple enumeration of what the first clause establishes.',
      D: 'Choice D is incorrect. With no punctuation, two independent clauses run together as a fused sentence.',
    },
  },

  {
    id: 'sat-f5-rw-m2h-q06',
    section: 'reading-writing',
    moduleId: 'f5-rw-module-2-hard',
    domain: 'Craft and Structure',
    skill: 'Text Structure and Purpose',
    difficulty: 'hard',
    stimulus: 'Critics of social media regulation often warn that content moderation risks becoming censorship. This concern has genuine weight when it refers to government-mandated removal of political speech. But when applied to private platforms deciding which posts violate their own terms of service, the censorship framing obscures more than it reveals. The word "censorship" has rhetorical force precisely because it evokes state repression; deploying it in a commercial context borrows that force without the corresponding conditions.',
    question: 'Which choice best describes the overall structure of the text?',
    choices: [
      { label: 'A', text: 'It concedes the partial validity of an argument, then narrows the conditions under which that argument applies, and concludes by explaining how misapplying it distorts the debate' },
      { label: 'B', text: 'It introduces a position, provides evidence that the position is entirely false, and urges readers to reject it' },
      { label: 'C', text: 'It compares two types of censorship and argues that both are equally harmful' },
      { label: 'D', text: 'It defends social media companies from all criticism and argues that their content decisions are always appropriate' },
    ],
    correctAnswer: 'A',
    explanation: 'The passage grants the censorship concern some validity in the government context, limits that validity to that specific context (not private platforms), and then explains how misusing the word "censorship" commercially borrows rhetorical force without justification.',
    wrongAnswerExplanations: {
      B: 'The passage does not call the concern entirely false — it grants it genuine weight in the government context.',
      C: 'The passage distinguishes between the two contexts rather than comparing them as equally harmful.',
      D: 'The passage does not evaluate whether platforms\' content decisions are appropriate; it critiques how the word "censorship" is applied.',
    },
  },

  {
    id: 'sat-f5-rw-m2h-q14',
    section: 'reading-writing',
    moduleId: 'f5-rw-module-2-hard',
    domain: 'Information and Ideas',
    skill: 'Inferences',
    difficulty: 'hard',
    stimulus: 'Languages with highly regular morphology — where a small number of rules produce virtually all word forms without exception — have historically been associated with socially isolated communities with low levels of adult language contact. Languages that attract many adult second-language learners, by contrast, tend to develop in the direction of reduced morphological complexity over generations, as adults transferring patterns from their native tongues and seeking efficient communication exert pressure on the system.',
    question: 'Which inference is most directly supported by the text?',
    choices: [
      { label: 'A', text: 'Languages spoken in geographically isolated communities are more likely to preserve complex morphology than those exposed to high rates of adult second-language learning' },
      { label: 'B', text: 'Languages with irregular morphology are inherently more efficient than regular ones' },
      { label: 'C', text: 'Adult second-language learners acquire morphologically complex languages more quickly than morphologically simple ones' },
      { label: 'D', text: 'Grammatical regularity is always the result of deliberate language planning by communities' },
    ],
    correctAnswer: 'A',
    explanation: 'The passage links high morphological regularity to isolated communities with low adult language contact and reduced complexity to high adult-learner contact. Combining both pieces, isolated communities should better preserve morphological complexity than those with heavy adult second-language learning.',
    wrongAnswerExplanations: {
      B: 'The passage describes a directional pressure toward simplicity under contact conditions; it does not claim irregular morphology is inherently more efficient.',
      C: 'The passage describes how adult learners affect a language\'s development over generations, not how quickly adults acquire complex systems.',
      D: 'The passage describes an organic social process; it makes no mention of deliberate language planning.',
    },
  },

  {
    id: 'sat-f5-rw-m2h-q22',
    section: 'reading-writing',
    moduleId: 'f5-rw-module-2-hard',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'hard',
    stimulus: 'The commission\'s final report, released after three years of testimony and more than two hundred hours of recorded interviews _______ made findings that challenged both the agency\'s official account and the version that had circulated in the press.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choices: [
      { label: 'A', text: 'interviews,' },
      { label: 'B', text: 'interviews;' },
      { label: 'C', text: 'interviews:' },
      { label: 'D', text: 'interviews and' },
    ],
    correctAnswer: 'A',
    explanation: 'Choice A is correct. The phrase "released after three years of testimony and more than two hundred hours of recorded interviews" is a nonessential participial phrase modifying "report." It opens with a comma after "report," so it must close with a comma before the main verb "made" — this comma after "interviews" correctly closes the parenthetical phrase.',
    wrongAnswerExplanations: {
      B: 'Choice B is incorrect. A semicolon must separate two independent clauses; what precedes "made" is not an independent clause — it is the subject plus a long modifying phrase.',
      C: 'Choice C is incorrect. A colon introduces a list or explanation but cannot appear here between the subject phrase and the verb.',
      D: 'Choice D is incorrect. Inserting "and" connects the phrase as though it were a coordinate element, but there is no parallel structure that "and" could be joining here, and the result is not grammatically standard.',
    },
  },

  {
    id: 'sat-f5-rw-m2h-q07',
    section: 'reading-writing',
    moduleId: 'f5-rw-module-2-hard',
    domain: 'Craft and Structure',
    skill: 'Cross-Text Connections',
    difficulty: 'hard',
    stimulus: 'Text 1\n\nThe migration of manufacturing from high-wage countries to lower-wage ones over the past four decades has been driven primarily by labor cost differentials. As wages in countries like China have risen, manufacturers have simply shifted operations further down the cost curve, to Vietnam, Bangladesh, or Cambodia. This constant repositioning suggests that globalized production will continue chasing cheap labor indefinitely, with no stable endpoint in sight.\n\nText 2\n\nThe labor-cost explanation for manufacturing migration, while accurate in the short term, misses a longer trend: automation is progressively eliminating the wage advantage that draws production to low-cost countries. As robotic systems replace assembly-line workers, the calculus shifts toward proximity to consumers, reliability of infrastructure, and control over intellectual property — factors that favor domestic or near-shore production. The endgame of global manufacturing may not be a further shift to cheaper labor markets but a partial return of production to higher-income countries.',
    question: 'Which choice best describes how Text 2 relates to Text 1\'s claim about the future of globalized production?',
    choices: [
      { label: 'A', text: 'Text 2 agrees that production will continue chasing cheap labor but adds that wages in low-cost countries will eventually equalize with those in high-wage countries' },
      { label: 'B', text: 'Text 2 accepts Text 1\'s short-term account but argues that automation changes the competitive dynamics, making a labor-cost-driven future less certain' },
      { label: 'C', text: 'Text 2 disputes both Text 1\'s historical account and its prediction, arguing that labor costs have never driven manufacturing location decisions' },
      { label: 'D', text: 'Text 2 confirms Text 1\'s prediction and provides data about specific low-cost countries that will attract production next' },
    ],
    correctAnswer: 'B',
    explanation: 'Text 2 explicitly says the labor-cost explanation is "accurate in the short term" — accepting Text 1\'s historical account — but then argues that automation changes the equation, making continued labor-cost migration less certain and a partial reshoring more plausible.',
    wrongAnswerExplanations: {
      A: 'Text 2 does not say wages will equalize; it argues that automation makes the wage advantage itself irrelevant.',
      C: 'Text 2 grants Text 1\'s historical account is accurate in the short term, so it does not dispute the history.',
      D: 'Text 2 challenges Text 1\'s prediction rather than confirming it, and names no specific future low-cost countries.',
    },
  },

  {
    id: 'sat-f5-rw-m2h-q15',
    section: 'reading-writing',
    moduleId: 'f5-rw-module-2-hard',
    domain: 'Information and Ideas',
    skill: 'Inferences',
    difficulty: 'hard',
    stimulus: 'Studies of wildfire behavior have found that fires burning in forests with heavy accumulations of dead wood and undergrowth — fuels that build up when fire is suppressed over decades — burn far more intensely and are far more difficult to control than fires in forests where fire has occurred more frequently and consumed those fuels periodically. Firefighters working in long-suppressed forests report that even water-bombing aircraft cannot reliably slow such fires once wind speeds exceed certain thresholds.',
    question: 'Which inference is most directly supported by the text?',
    choices: [
      { label: 'A', text: 'Frequent, lower-intensity fires in a forest may reduce the risk of an uncontrollable catastrophic fire in that same forest' },
      { label: 'B', text: 'Water-bombing aircraft are effective at controlling wildfires in all forest conditions' },
      { label: 'C', text: 'Wind speed has no effect on wildfire intensity in forests with heavy fuel accumulation' },
      { label: 'D', text: 'Long periods of fire suppression always improve a forest\'s ecological health' },
    ],
    correctAnswer: 'A',
    explanation: 'The passage states that forests with periodic fires have fewer accumulated fuels and burn less intensely. Combining that with the finding that heavy-fuel forests are hardest to control, frequent lower-intensity fires logically reduce the risk of catastrophic uncontrollable fire.',
    wrongAnswerExplanations: {
      B: 'The passage explicitly states water-bombing aircraft cannot reliably slow fires in long-suppressed forests at high wind speeds, refuting universal effectiveness.',
      C: 'The passage mentions wind speed thresholds above which aircraft cannot slow fires — the opposite of wind having no effect.',
      D: 'The passage describes ecological consequences of suppression (fuel buildup, catastrophic fire risk) that are negative, not improvements in forest health.',
    },
  },

  {
    id: 'sat-f5-rw-m2h-q23',
    section: 'reading-writing',
    moduleId: 'f5-rw-module-2-hard',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'hard',
    stimulus: 'By the time the auditors completed their review, the discrepancy had grown from a rounding error of a few hundred dollars into a shortfall measured in the millions _______ a detail the board of directors had apparently been informed of months earlier but had chosen not to disclose.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choices: [
      { label: 'A', text: 'millions —' },
      { label: 'B', text: 'millions,' },
      { label: 'C', text: 'millions;' },
      { label: 'D', text: 'millions:' },
    ],
    correctAnswer: 'A',
    explanation: 'Choice A is correct. The material after the blank — "a detail the board of directors had apparently been informed of months earlier but had chosen not to disclose" — is an appositive that adds a dramatic, parenthetical clarification. A dash correctly introduces this kind of emphatic appositive after a complete clause.',
    wrongAnswerExplanations: {
      B: 'Choice B is incorrect. A comma can introduce a short appositive, but here the appositive is long and contains its own internal commas, making a comma boundary unclear and potentially confusing.',
      C: 'Choice C is incorrect. A semicolon must be followed by an independent clause; "a detail the board..." is not an independent clause.',
      D: 'Choice D is incorrect. A colon introduces what follows as an explanation or enumeration that the preceding clause sets up, but "a detail" is an appositive renaming the shortfall, not an elaboration of a category introduced by the main clause.',
    },
  },

  {
    id: 'sat-f5-rw-m2h-q08',
    section: 'reading-writing',
    moduleId: 'f5-rw-module-2-hard',
    domain: 'Craft and Structure',
    skill: 'Cross-Text Connections',
    difficulty: 'hard',
    stimulus: 'Text 1\n\nSocial trust — the generalized confidence that strangers will behave honestly and cooperate — is among the most important drivers of economic development. Economists have found strong correlations between trust scores in cross-national surveys and long-run GDP growth, institutional quality, and investment rates. High-trust societies can sustain more complex transactions, longer supply chains, and more sophisticated contracts, because parties need not invest as heavily in monitoring and enforcement.\n\nText 2\n\nThe causal direction in trust-and-development research is far from settled. A society that develops effective legal institutions, reliable courts, and enforceable property rights may generate trust as a byproduct, rather than the reverse. What survey measures capture as "trust" may partly reflect prior institutional quality rather than a culturally rooted predisposition that independently drives growth. Treating trust as a cause rather than an effect risks misidentifying what policymakers should actually target.',
    question: 'Based on the texts, the author of Text 2 would most likely respond to Text 1\'s economic argument by claiming that Text 1',
    choices: [
      { label: 'A', text: 'understates how strongly trust scores correlate with GDP growth' },
      { label: 'B', text: 'mistakes a correlation for a settled causal relationship, potentially reversing cause and effect' },
      { label: 'C', text: 'relies on institutional data rather than cross-national surveys to measure trust' },
      { label: 'D', text: 'correctly identifies trust as the primary driver of development and should be used as the basis for policy' },
    ],
    correctAnswer: 'B',
    explanation: 'Text 2 argues that the causal direction is unsettled and that institutions may produce trust rather than the other way around. It directly challenges Text 1\'s implicit assumption that trust drives development, warning against treating correlation as settled causation.',
    wrongAnswerExplanations: {
      A: 'Text 2 does not dispute the strength of the correlation; it disputes the causal interpretation.',
      C: 'Text 1 uses cross-national surveys; Text 2 does not criticize the method, only the causal inference drawn from it.',
      D: 'Text 2 warns against using trust as a policy target precisely because its causal role is uncertain.',
    },
  },

  {
    id: 'sat-f5-rw-m2h-q16',
    section: 'reading-writing',
    moduleId: 'f5-rw-module-2-hard',
    domain: 'Information and Ideas',
    skill: 'Inferences',
    difficulty: 'hard',
    stimulus: 'Historians of early modern banking have observed that the extension of credit in sixteenth-century merchant networks depended not on formal legal enforcement but on reputation: because merchants conducted business repeatedly with the same counterparts across multiple cities, defection from a debt obligation in one city would become known throughout the network and permanently exclude the offender from future transactions. This information-transmission capacity was not a formal institution but an emergent property of how the networks were structured.',
    question: 'Based on the text, which statement about early modern credit would the historians most likely support?',
    choices: [
      { label: 'A', text: 'Early modern merchants would have been more willing to extend credit to an established network participant than to an unknown outsider' },
      { label: 'B', text: 'Legal courts were the primary mechanism ensuring that merchants repaid debts in the sixteenth century' },
      { label: 'C', text: 'Credit networks collapsed whenever a single merchant defaulted on a debt' },
      { label: 'D', text: 'Reputation-based credit systems were exclusive to Mediterranean trading cities' },
    ],
    correctAnswer: 'A',
    explanation: 'The passage explains that credit rested on reputation and the threat of network exclusion for defectors. An established participant has a reputation to protect and is embedded in the enforcement mechanism; an unknown outsider offers no such assurance, so merchants would logically favor the former.',
    wrongAnswerExplanations: {
      B: 'The passage explicitly says credit depended not on formal legal enforcement but on reputation.',
      C: 'The passage describes a default as destroying the defaulter\'s reputation and excluding them, not as collapsing the entire network.',
      D: 'The passage makes no geographic restriction; it discusses sixteenth-century merchant networks broadly.',
    },
  },

  {
    id: 'sat-f5-rw-m2h-q24',
    section: 'reading-writing',
    moduleId: 'f5-rw-module-2-hard',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'hard',
    stimulus: 'The director argued that the budget shortfall was manageable _______ her deputy, however, had already reviewed the revised projections and reached the opposite conclusion.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choices: [
      { label: 'A', text: 'manageable;' },
      { label: 'B', text: 'manageable,' },
      { label: 'C', text: 'manageable and' },
      { label: 'D', text: 'manageable:' },
    ],
    correctAnswer: 'A',
    explanation: 'Choice A is correct. Two independent clauses are connected here, with "however" beginning the second clause as a conjunctive adverb. A semicolon before the second clause (followed by "however" with a comma) is the standard way to join independent clauses with a conjunctive adverb.',
    wrongAnswerExplanations: {
      B: 'Choice B is incorrect. A comma before "however" between two independent clauses creates a comma splice.',
      C: 'Choice C is incorrect. "And" is a coordinating conjunction that can join independent clauses with only a comma before it, but the resulting sentence then needs no additional "however" — the "however" signals contrast, which "and" does not convey; additionally, the resulting construction is non-standard with the adversative "however" following "and."',
      D: 'Choice D is incorrect. A colon introduces an explanation or list, but what follows is a contrasting independent clause, not an elaboration of the first clause.',
    },
  },

  {
    id: 'sat-f5-rw-m2h-q25',
    section: 'reading-writing',
    moduleId: 'f5-rw-module-2-hard',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'medium',
    stimulus: 'The committee has spent three months deliberating over the proposal, and by the time the vote _______ the members will have reviewed more than four hundred pages of testimony and consulted with dozens of independent experts.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choices: [
      { label: 'A', text: 'occurs,' },
      { label: 'B', text: 'will occur,' },
      { label: 'C', text: 'has occurred,' },
      { label: 'D', text: 'occurred,' },
    ],
    correctAnswer: 'A',
    explanation: 'Choice A is correct. In a future-time clause introduced by "by the time," Standard English uses the simple present tense ("occurs"), even though the event is in the future. The main clause correctly uses the future perfect ("will have reviewed").',
    wrongAnswerExplanations: {
      B: 'Choice B is incorrect. Using the future tense ("will occur") in a "by the time" clause is non-standard; such temporal clauses use simple present to refer to future events.',
      C: 'Choice C is incorrect. The present perfect ("has occurred") implies the vote has already happened, which contradicts the future-perfect main clause.',
      D: 'Choice D is incorrect. The simple past ("occurred") implies a completed past action, inconsistent with the future frame established by the main clause.',
    },
  },

  {
    id: 'sat-f5-rw-m2h-q26',
    section: 'reading-writing',
    moduleId: 'f5-rw-module-2-hard',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'hard',
    stimulus: 'The committee\'s decision to renovate the historic theater, which had been closed for structural repairs for more than a decade and _______ the subject of contentious debates among preservationists, developers, and city officials, was ultimately approved by a narrow margin.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choices: [
      { label: 'A', text: 'had become' },
      { label: 'B', text: 'has become' },
      { label: 'C', text: 'became' },
      { label: 'D', text: 'would become' },
    ],
    correctAnswer: 'A',
    explanation: 'Choice A is correct. The relative clause is in the past-perfect frame ("had been closed"), describing a state that preceded the committee\'s decision (also past). The parallel verb in the same clause must also be past perfect: "had become" maintains consistency with the earlier verb and the temporal sequence.',
    wrongAnswerExplanations: {
      B: 'Choice B is incorrect. The present perfect ("has become") implies a connection to the present moment, but the entire clause describes a past state of the theater before the decision; it does not fit the past-perfect context established by "had been closed."',
      C: 'Choice C is incorrect. The simple past ("became") does not align with the past-perfect frame of "had been closed," obscuring the sequence of past events.',
      D: 'Choice D is incorrect. "Would become" implies a future-from-past or conditional meaning, neither of which fits the description of a completed state ("contentious debates") that had already occurred before the decision.',
    },
  },

  {
    id: 'sat-f5-rw-m2h-q01',
    section: 'reading-writing',
    moduleId: 'f5-rw-module-2-hard',
    domain: 'Craft and Structure',
    skill: 'Words in Context',
    difficulty: 'medium',
    stimulus: 'The diplomat\'s handling of the border dispute was widely praised for its _______ : rather than issuing ultimatums or escalating rhetoric, she identified the underlying economic grievances on both sides and proposed incremental concessions that preserved each government\'s ability to claim a degree of success.',
    question: 'Which choice completes the text with the most logical and precise word or phrase?',
    choices: [
      { label: 'A', text: 'pragmatism' },
      { label: 'B', text: 'stubbornness' },
      { label: 'C', text: 'impartiality' },
      { label: 'D', text: 'transparency' },
    ],
    correctAnswer: 'A',
    explanation: '"Pragmatism" means a focus on practical outcomes rather than rigid principles. The diplomat addressed underlying grievances and offered face-saving compromises, which is precisely pragmatic problem-solving.',
    wrongAnswerExplanations: {
      B: '"Stubbornness" implies unwillingness to change position, which contradicts her flexible, concession-based approach.',
      C: '"Impartiality" concerns equal treatment of all parties without favoritism; the passage emphasizes her practical problem-solving, not her neutrality.',
      D: '"Transparency" means openness about intentions or processes; the passage describes her strategy, not her level of openness.',
    },
  },
]
