import type { MathQuestion } from './types'

export const f4MathModule1Questions: MathQuestion[] = [
  {
    id: 'sat-f4-math-m1-q01',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Algebra',
    skill: 'Linear equations in one variable',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'A gym charges a one-time enrollment fee of $45 plus a monthly membership fee. After 8 months, a member has paid a total of $237. What is the monthly membership fee?',
    choices: [
      { label: 'A', text: '$21' },
      { label: 'B', text: '$24' },
      { label: 'C', text: '$27' },
      { label: 'D', text: '$30' },
    ],
    correctAnswer: 'B',
    explanation: 'Let m be the monthly fee. Total cost: 45 + 8m = 237 → 8m = 192 → m = 24. The monthly fee is $24.',
    wrongAnswerExplanations: {
      A: '$21 gives 45 + 8(21) = 45 + 168 = 213, not 237.',
      C: '$27 gives 45 + 8(27) = 45 + 216 = 261, not 237.',
      D: '$30 gives 45 + 8(30) = 45 + 240 = 285, not 237.',
    },
  },

  {
    id: 'sat-f4-math-m1-q02',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Algebra',
    skill: 'Linear equations in two variables',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'In the xy-plane, line ℓ passes through the points (1, 5) and (3, 11). Line m is parallel to line ℓ and passes through the point (0, −9). At what value of x does line m cross the x-axis?',
    choices: [
      { label: 'A', text: '1' },
      { label: 'B', text: '2' },
      { label: 'C', text: '3' },
      { label: 'D', text: '4' },
    ],
    correctAnswer: 'C',
    explanation: 'Step 1 — find the slope of ℓ: slope = (11 − 5)/(3 − 1) = 6/2 = 3. Step 2 — line m has the same slope (parallel) and passes through (0, −9), so its equation is y = 3x − 9. Step 3 — set y = 0: 3x − 9 = 0 → x = 3.',
    wrongAnswerExplanations: {
      A: 'x = 1 gives y = 3(1) − 9 = −6, not 0.',
      B: 'x = 2 gives y = 3(2) − 9 = −3, not 0. This error comes from dividing the y-intercept by the slope incorrectly.',
      D: 'x = 4 gives y = 3(4) − 9 = 3, not 0. This error comes from using only the y-intercept magnitude without the correct slope.',
    },
  },

  {
    id: 'sat-f4-math-m1-q03',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Algebra',
    skill: 'Linear functions',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'The function f is defined by f(x) = 3x + 2. What is f(5)?',
    choices: [
      { label: 'A', text: '13' },
      { label: 'B', text: '15' },
      { label: 'C', text: '17' },
      { label: 'D', text: '19' },
    ],
    correctAnswer: 'C',
    explanation: 'Substitute x = 5 into the function: f(5) = 3(5) + 2 = 15 + 2 = 17.',
    wrongAnswerExplanations: {
      A: '13 = 3(5) − 2 subtracts 2 instead of adding 2.',
      B: '15 = 3(5) forgets to add the constant +2.',
      D: '19 uses 3(5) + 4 with the wrong constant.',
    },
  },

  {
    id: 'sat-f4-math-m1-q04',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Algebra',
    skill: 'Systems of two linear equations in two variables',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'If x + y = 12 and y = 5, what is the value of x?',
    choices: [
      { label: 'A', text: '5' },
      { label: 'B', text: '7' },
      { label: 'C', text: '12' },
      { label: 'D', text: '17' },
    ],
    correctAnswer: 'B',
    explanation: 'Substitute y = 5 into x + y = 12: x + 5 = 12 → x = 7.',
    wrongAnswerExplanations: {
      A: '5 is the value of y, not x.',
      C: '12 is the sum x + y, not the value of x alone.',
      D: '17 = 12 + 5 adds instead of subtracts.',
    },
  },

  {
    id: 'sat-f4-math-m1-q05',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Algebra',
    skill: 'Linear inequalities in one or two variables',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'A delivery van can carry at most 1,200 kilograms. It is already loaded with 450 kilograms of equipment. Each box weighs 25 kilograms. What is the maximum number of boxes b the van can additionally carry?',
    choices: [
      { label: 'A', text: '18' },
      { label: 'B', text: '24' },
      { label: 'C', text: '30' },
      { label: 'D', text: '48' },
    ],
    correctAnswer: 'C',
    explanation: '450 + 25b ≤ 1200 → 25b ≤ 750 → b ≤ 30. The maximum is 30 boxes.',
    wrongAnswerExplanations: {
      A: '18 uses only part of the remaining capacity and is not the maximum.',
      B: '24 boxes weigh 600 kg; there is room for more.',
      D: '48 ignores the 450 kg already loaded: 48 × 25 = 1200 alone exceeds the remaining capacity.',
    },
  },

  {
    id: 'sat-f4-math-m1-q19',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Algebra',
    skill: 'Linear equations in one variable',
    difficulty: 'medium',
    type: 'grid_in',
    question: 'If 5(x − 3) = 2x + 9, what is the value of x?',
    correctAnswer: '8',
    acceptableAnswers: ['8'],
    explanation: '5x − 15 = 2x + 9 → 3x = 24 → x = 8.',
  },

  {
    id: 'sat-f4-math-m1-q14',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'Ratios, rates, proportional relationships, and units',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'A machine fills 45 bottles in 3 minutes at a constant rate. At this rate, how many bottles will it fill in 20 minutes?',
    choices: [
      { label: 'A', text: '150' },
      { label: 'B', text: '225' },
      { label: 'C', text: '300' },
      { label: 'D', text: '900' },
    ],
    correctAnswer: 'C',
    explanation: 'Rate = 45/3 = 15 bottles per minute. In 20 minutes: 15 × 20 = 300 bottles.',
    wrongAnswerExplanations: {
      A: '150 uses a rate of 7.5 bottles/min, which is half the correct rate.',
      B: '225 corresponds to 15 minutes, not 20.',
      D: '900 multiplies 45 by 20, treating 45 as a per-minute rate.',
    },
  },

  {
    id: 'sat-f4-math-m1-q15',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'Percentages',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'A jacket is on sale for $68 after a 15% discount off its original price. What was the original price?',
    choices: [
      { label: 'A', text: '$78.20' },
      { label: 'B', text: '$80.00' },
      { label: 'C', text: '$83.00' },
      { label: 'D', text: '$85.00' },
    ],
    correctAnswer: 'B',
    explanation: 'The sale price is 85% of the original: 0.85 × original = 68 → original = 68/0.85 = 80.',
    wrongAnswerExplanations: {
      A: '$78.20 adds 15% of 68 back onto 68, which is not the correct reverse of a discount.',
      C: '$83.00 does not satisfy 0.85 × price = 68.',
      D: '$85.00 gives a sale price of 0.85 × 85 = $72.25, not $68.',
    },
  },

  {
    id: 'sat-f4-math-m1-q16',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'Two-variable data: models and scatterplots',
    difficulty: 'medium',
    type: 'multiple_choice',
    graphData: {
      type: 'scatter',
      xLabel: 'Advertising ($1000s)',
      yLabel: 'Sales ($1000s)',
      xMin: 0, xMax: 10, yMin: 0, yMax: 60,
      points: [[1, 14], [2, 20], [3, 23], [4, 30], [5, 34], [6, 41], [7, 44], [8, 52]],
      trendLine: { slope: 5, intercept: 9, color: '#4f46e5' },
    },
    question: 'The scatterplot shows sales versus advertising spending for 8 months, along with the line of best fit y = 5x + 9. Based on the model, what is the predicted sales value (in $1000s) when advertising is $6,000 (x = 6)?',
    choices: [
      { label: 'A', text: '30' },
      { label: 'B', text: '36' },
      { label: 'C', text: '39' },
      { label: 'D', text: '41' },
    ],
    correctAnswer: 'C',
    explanation: 'Substitute x = 6 into the model: y = 5(6) + 9 = 30 + 9 = 39.',
    wrongAnswerExplanations: {
      A: '30 = 5 × 6 forgets to add the intercept of 9.',
      B: '36 uses an intercept of 6 rather than 9.',
      D: '41 is the observed data value at x = 6, not the model prediction.',
    },
  },

  {
    id: 'sat-f4-math-m1-q17',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'One-variable data: distributions and measures of center and spread',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'A data set consists of the values 4, 7, 7, 10, 12. Let m be the mean and M be the median. What is the value of m − M?',
    choices: [
      { label: 'A', text: '−1' },
      { label: 'B', text: '0' },
      { label: 'C', text: '1' },
      { label: 'D', text: '2' },
    ],
    correctAnswer: 'C',
    explanation: 'Mean = (4 + 7 + 7 + 10 + 12)/5 = 40/5 = 8. The ordered list is 4, 7, 7, 10, 12, so the median (middle value) is 7. Therefore m − M = 8 − 7 = 1.',
    wrongAnswerExplanations: {
      A: '−1 reverses the sign; the mean (8) exceeds the median (7).',
      B: '0 would require equal mean and median, but they are 8 and 7.',
      D: '2 overstates the difference between the mean (8) and median (7).',
    },
  },

  {
    id: 'sat-f4-math-m1-q08',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Advanced Math',
    skill: 'Quadratic functions',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'The function f(x) = 2x² − 8x + 5 has a minimum value. What is that minimum value?',
    choices: [
      { label: 'A', text: '−5' },
      { label: 'B', text: '−3' },
      { label: 'C', text: '3' },
      { label: 'D', text: '5' },
    ],
    correctAnswer: 'B',
    explanation: 'The vertex is at x = −(−8)/(2·2) = 8/4 = 2. f(2) = 2(4) − 8(2) + 5 = 8 − 16 + 5 = −3.',
    wrongAnswerExplanations: {
      A: '−5 is not the minimum; f(2) = −3.',
      C: '3 has the correct magnitude but the wrong sign.',
      D: '5 is the y-intercept f(0), not the minimum value.',
    },
  },

  {
    id: 'sat-f4-math-m1-q09',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Advanced Math',
    skill: 'Equivalent expressions',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'Which expression is equivalent to (2x + 3)(x − 4) − (x² − 5x)?',
    choices: [
      { label: 'A', text: 'x² − 12' },
      { label: 'B', text: 'x² − 10x − 12' },
      { label: 'C', text: 'x² − 12x + 12' },
      { label: 'D', text: '3x² − 10x − 12' },
    ],
    correctAnswer: 'A',
    explanation: '(2x + 3)(x − 4) = 2x² − 8x + 3x − 12 = 2x² − 5x − 12. Subtracting (x² − 5x): 2x² − 5x − 12 − x² + 5x = x² − 12.',
    wrongAnswerExplanations: {
      B: 'This keeps the −5x term instead of canceling it with +5x.',
      C: 'This mishandles signs when distributing the subtraction.',
      D: 'This fails to subtract the x² term, leaving 3x² instead of x².',
    },
  },

  {
    id: 'sat-f4-math-m1-q10',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Advanced Math',
    skill: 'Exponential functions',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'The value of a car is $24,000 and decreases by 15% each year. Which function models the value V of the car after t years?',
    choices: [
      { label: 'A', text: 'V = 24000(1.15)^t' },
      { label: 'B', text: 'V = 24000(0.85)^t' },
      { label: 'C', text: 'V = 24000(0.15)^t' },
      { label: 'D', text: 'V = 24000 − 0.15t' },
    ],
    correctAnswer: 'B',
    explanation: 'A 15% decrease each year multiplies the value by (1 − 0.15) = 0.85 per year, so V = 24000(0.85)^t.',
    wrongAnswerExplanations: {
      A: '(1.15)^t models 15% growth, not decay.',
      C: '(0.15)^t means retaining only 15% each year, an 85% decrease.',
      D: 'This is linear decay, not the exponential 15% yearly decrease.',
    },
  },

  {
    id: 'sat-f4-math-m1-q07',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Geometry and Trigonometry',
    skill: 'Lines, angles, and triangles',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'In a triangle, the measures of the three angles are x°, (2x)°, and (3x)°. What is the measure of the largest angle?',
    choices: [
      { label: 'A', text: '30°' },
      { label: 'B', text: '60°' },
      { label: 'C', text: '90°' },
      { label: 'D', text: '120°' },
    ],
    correctAnswer: 'C',
    explanation: 'The angles sum to 180°: x + 2x + 3x = 180 → 6x = 180 → x = 30. The largest angle is 3x = 90°.',
    wrongAnswerExplanations: {
      A: '30° = x is the smallest angle, not the largest.',
      B: '60° = 2x is the middle angle, not the largest.',
      D: '120° exceeds 3x = 90°; the three angles are 30°, 60°, and 90°.',
    },
  },

  {
    id: 'sat-f4-math-m1-q13',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Geometry and Trigonometry',
    skill: 'Circles',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'A circle has a circumference of 16π. What is the area of the circle?',
    choices: [
      { label: 'A', text: '16π' },
      { label: 'B', text: '32π' },
      { label: 'C', text: '64π' },
      { label: 'D', text: '256π' },
    ],
    correctAnswer: 'C',
    explanation: 'Circumference = 2πr = 16π → r = 8. Area = πr² = π(8²) = 64π.',
    wrongAnswerExplanations: {
      A: '16π equals the circumference, not the area.',
      B: '32π = 4πr uses the diameter incorrectly instead of r².',
      D: '256π uses r = 16 (the diameter) instead of the radius r = 8.',
    },
  },

  {
    id: 'sat-f4-math-m1-q20',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Geometry and Trigonometry',
    skill: 'Right triangles and trigonometry',
    difficulty: 'medium',
    type: 'grid_in',
    graphData: {
      type: 'geometry',
      viewBox: { xMin: -1.5, xMax: 10, yMin: -1.5, yMax: 6.5 },
      elements: [
        { kind: 'poly', pts: [[0, 0], [8, 0], [0, 6]] as [number, number][] },
        { kind: 'right_angle', v: [0, 0] as [number, number], a: [8, 0] as [number, number], b: [0, 6] as [number, number] },
        { kind: 'label', x: 4, y: -0.8, text: '8' },
        { kind: 'label', x: -0.8, y: 3, text: '6' },
        { kind: 'label', x: 4.5, y: 3.5, text: '?' },
      ],
    },
    question: 'A right triangle has legs of length 6 and 8. What is the length of the hypotenuse?',
    correctAnswer: '10',
    acceptableAnswers: ['10'],
    explanation: 'By the Pythagorean theorem: hypotenuse = √(6² + 8²) = √(36 + 64) = √100 = 10.',
  },

  {
    id: 'sat-f4-math-m1-q06',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Algebra',
    skill: 'Linear equations in two variables',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'The system 4x + 6y = 10 and 2x + ky = 7 has no solution. What is the value of k?',
    choices: [
      { label: 'A', text: '3' },
      { label: 'B', text: '4' },
      { label: 'C', text: '6' },
      { label: 'D', text: '12' },
    ],
    correctAnswer: 'A',
    explanation: 'No solution means the lines are parallel: the x- and y-coefficient ratios match but the constants differ. 4/2 = 6/k → k = 6/2 = 3. Check: with k = 3, the second equation ×2 gives 4x + 6y = 14 ≠ 10, so the lines are parallel with no solution.',
    wrongAnswerExplanations: {
      B: 'k = 4 gives non-proportional coefficients (4/2 ≠ 6/4), so the lines intersect.',
      C: 'k = 6 does not make the x- and y-coefficient ratios equal.',
      D: 'k = 12 gives 4/2 ≠ 6/12, so the lines are not parallel.',
    },
  },

  {
    id: 'sat-f4-math-m1-q18',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'Probability and conditional probability',
    difficulty: 'hard',
    type: 'grid_in',
    graphData: {
      type: 'table',
      title: 'Beverage Preferences',
      headers: ['', 'Coffee', 'Tea', 'Total'],
      rows: [
        ['Students', '48', '32', '80'],
        ['Teachers', '12', '8', '20'],
        ['Total', '60', '40', '100'],
      ],
    },
    question: 'The table shows the beverage preferences of 100 people. If one person who prefers tea is selected at random, what is the probability that the person is a teacher? Enter your answer as a decimal.',
    correctAnswer: '0.2',
    acceptableAnswers: ['0.2', '.2', '1/5'],
    explanation: 'Among the 40 tea drinkers, 8 are teachers. P(teacher | tea) = 8/40 = 0.2.',
  },

  {
    id: 'sat-f4-math-m1-q11',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Advanced Math',
    skill: 'Nonlinear equations in one variable and systems of equations',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'What is the sum of the solutions to the equation x² − 7x + 10 = 0?',
    choices: [
      { label: 'A', text: '3' },
      { label: 'B', text: '5' },
      { label: 'C', text: '7' },
      { label: 'D', text: '10' },
    ],
    correctAnswer: 'C',
    explanation: 'Factoring: (x − 2)(x − 5) = 0, so x = 2 or x = 5. Their sum is 2 + 5 = 7. (Equivalently, the sum of roots equals −b/a = 7.)',
    wrongAnswerExplanations: {
      A: '3 is the difference of the roots (5 − 2), not the sum.',
      B: '5 is one of the roots, not the sum of both.',
      D: '10 is the product of the roots (2 × 5), not the sum.',
    },
  },

  {
    id: 'sat-f4-math-m1-q12',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Advanced Math',
    skill: 'Nonlinear functions',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'The function f is defined by f(x) = 2x + 6 for x ≥ 0. Let f⁻¹ be the inverse function of f. Which of the following is the value of f⁻¹(f⁻¹(10))?',
    choices: [
      { label: 'A', text: '−1' },
      { label: 'B', text: '1' },
      { label: 'C', text: '2' },
      { label: 'D', text: '8' },
    ],
    correctAnswer: 'A',
    explanation: 'Step 1 — find f⁻¹: set y = 2x + 6, solve for x: x = (y − 6)/2, so f⁻¹(x) = (x − 6)/2. Step 2 — evaluate f⁻¹(10): f⁻¹(10) = (10 − 6)/2 = 4/2 = 2. Step 3 — evaluate f⁻¹(2): f⁻¹(2) = (2 − 6)/2 = −4/2 = −1. The answer is −1.',
    wrongAnswerExplanations: {
      B: '1 results from computing f⁻¹(10) = 2 correctly but then using f(2) = 10 (the original function) instead of f⁻¹(2) = −1.',
      C: '2 is the intermediate result f⁻¹(10), but the problem asks for f⁻¹ applied a second time.',
      D: '8 comes from applying f (not f⁻¹) twice: f(f(10)) would not be meaningful here, and mixing f and f⁻¹ gives this error.',
    },
  },

  {
    id: 'sat-f4-math-m1-q21',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Advanced Math',
    skill: 'Quadratic functions',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'A ball is launched upward from a platform. Its height in meters above the ground after t seconds is given by h(t) = −4t² + 24t + 7. What is the maximum height, in meters, that the ball reaches?',
    choices: [
      { label: 'A', text: '31' },
      { label: 'B', text: '36' },
      { label: 'C', text: '43' },
      { label: 'D', text: '79' },
    ],
    correctAnswer: 'C',
    explanation: 'The maximum occurs at the vertex. Complete the square: h(t) = −4t² + 24t + 7 = −4(t² − 6t) + 7 = −4(t² − 6t + 9 − 9) + 7 = −4(t − 3)² + 36 + 7 = −4(t − 3)² + 43. The vertex is at (3, 43), so the maximum height is 43 meters. (Alternatively, the vertex t-coordinate is −b/(2a) = −24/(2·(−4)) = 3, then h(3) = −4(9) + 24(3) + 7 = −36 + 72 + 7 = 43.)',
    wrongAnswerExplanations: {
      A: '31 = 24 + 7 uses only the linear and constant terms and ignores the quadratic term at t = 3.',
      B: '36 = −4(t − 3)² + 36 forgets to add back the +7 constant after completing the square.',
      D: '79 results from evaluating h(0) + h(6) or another combination; it is not the vertex value.',
    },
  },

  {
    id: 'sat-f4-math-m1-q22',
    section: 'math',
    moduleId: 'f4-math-module-1',
    domain: 'Geometry and Trigonometry',
    skill: 'Right triangles and trigonometry',
    difficulty: 'hard',
    type: 'grid_in',
    question: 'In right triangle ABC, the right angle is at C. If sin A = 3/5 and the hypotenuse AB has length 20, what is the length of side BC (the side opposite angle A)?',
    correctAnswer: '12',
    acceptableAnswers: ['12'],
    explanation: 'sin A = opposite/hypotenuse = BC/AB = BC/20 = 3/5, so BC = 20 × 3/5 = 12.',
  },
]
