import type { MathQuestion } from './types'

// Math Module 2 Hard — 22 questions (0 easy, ~10 medium, ~12 hard)
// 17 multiple choice (q01–q17) + 5 grid-in (q18–q22)

export const mathModule2HardQuestions: MathQuestion[] = [
  {
    id: 'm2h-01',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Algebra',
    skill: 'Systems of two linear equations in two variables',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'The system below has no solution. What is the value of k?\n3x − ky = 8\n9x − 12y = 18',
    choices: [
      { label: 'A', text: '3' },
      { label: 'B', text: '4' },
      { label: 'C', text: '6' },
      { label: 'D', text: '9' },
    ],
    correctAnswer: 'B',
    explanation: 'Divide the second equation by 3: 3x − 4y = 6. For no solution, the lines must be parallel (same slope, different constants). The first line 3x − ky = 8 has slope 3/k; the second has slope 3/4. Setting 3/k = 3/4 gives k = 4. With k = 4: the equations are 3x − 4y = 8 and 3x − 4y = 6 — parallel with different constants, confirming no solution.\n\nDesmos method: Enter y = (3x − 8)/k and y = (9x − 18)/12 using a slider for k. Increase k from 1. At k = 4 both lines become parallel — you can see them side by side with no intersection point.',
    wrongAnswerExplanations: {
      A: 'If k = 3, slope of first line = 1 ≠ 3/4 — the lines intersect (one solution).',
      C: 'If k = 6, slope of first line = 1/2 ≠ 3/4 — the lines intersect.',
      D: 'If k = 9, slope = 3/9 = 1/3 ≠ 3/4 — the lines intersect.',
    },
  },

  {
    id: 'm2h-02',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Algebra',
    skill: 'Linear functions',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Line p passes through the point (−2, 7) and is perpendicular to the line y = (1/3)x + 4. What is the equation of line p?',
    choices: [
      { label: 'A', text: 'y = 3x + 13' },
      { label: 'B', text: 'y = −3x − 1' },
      { label: 'C', text: 'y = (1/3)x + 23/3' },
      { label: 'D', text: 'y = −3x + 1' },
    ],
    correctAnswer: 'D',
    explanation: 'The slope of y = (1/3)x + 4 is 1/3. A perpendicular slope is −1/(1/3) = −3. Using point (−2, 7): y − 7 = −3(x + 2) → y = −3x − 6 + 7 → y = −3x + 1.',
    wrongAnswerExplanations: {
      A: 'Slope +3 is the reciprocal without flipping the sign — this line is not perpendicular.',
      C: 'Same slope as the original — this is the parallel line through (−2, 7), not perpendicular.',
      B: 'Correct slope −3, but wrong y-intercept: at x = −2, y = −3(−2) − 1 = 5 ≠ 7.',
    },
  },

  {
    id: 'm2h-04',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Algebra',
    skill: 'Systems of two linear equations in two variables',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'The total cost of 5 adult tickets and 3 child tickets is $88. The total cost of 2 adult tickets and 6 child tickets is $64. What is the cost, in dollars, of one adult ticket?',
    choices: [
      { label: 'A', text: '$10' },
      { label: 'B', text: '$12' },
      { label: 'C', text: '$14' },
      { label: 'D', text: '$16' },
    ],
    correctAnswer: 'C',
    explanation: 'Let a = adult price, c = child price. Equations: 5a + 3c = 88 and 2a + 6c = 64. Divide the second by 2: a + 3c = 32. Subtract from the first: 4a = 56 → a = 14. Verify: c = (32 − 14)/3 = 6; check: 5(14) + 3(6) = 88 ✓ and 2(14) + 6(6) = 64 ✓.',
    wrongAnswerExplanations: {
      A: 'If a = 10, then 3c = 22 — not an integer child price.',
      B: 'If a = 12, then 3c = 20 — not an integer child price.',
      D: 'If a = 16, then 3c = 16 — not an integer child price.',
    },
  },

  {
    id: 'm2h-05',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Algebra',
    skill: 'Linear inequalities in one or two variables',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Which of the following represents all values of x satisfying |2x − 1| ≤ 7?',
    choices: [
      { label: 'A', text: 'x ≤ 4' },
      { label: 'B', text: '−3 ≤ x ≤ 4' },
      { label: 'C', text: 'x ≥ −3' },
      { label: 'D', text: '−4 ≤ x ≤ 3' },
    ],
    correctAnswer: 'B',
    explanation: '|2x − 1| ≤ 7 means −7 ≤ 2x − 1 ≤ 7. Add 1: −6 ≤ 2x ≤ 8. Divide by 2: −3 ≤ x ≤ 4.',
    wrongAnswerExplanations: {
      A: 'This gives only the right boundary, missing the left constraint x ≥ −3.',
      C: 'This gives only the left boundary, missing the right constraint x ≤ 4.',
      D: 'This results from applying a sign error to the inner expression (treating it as −2x + 1 instead of 2x − 1).',
    },
  },

  {
    id: 'm2h-15',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'Ratios, rates, proportional relationships, and units',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Tank A contains 30 gallons of water and is being drained at a constant rate of 2 gallons per minute. At the same time, empty Tank B is being filled at a constant rate of 3 gallons per minute. After how many minutes will both tanks contain the same amount of water?',
    choices: [
      { label: 'A', text: '6' },
      { label: 'B', text: '10' },
      { label: 'C', text: '5' },
      { label: 'D', text: '8' },
    ],
    correctAnswer: 'A',
    explanation: 'Water in Tank A after t minutes: 30 − 2t. Water in Tank B after t minutes: 3t. Set equal: 30 − 2t = 3t → 30 = 5t → t = 6.',
    wrongAnswerExplanations: {
      B: 't = 10: Tank A has 10 gallons, Tank B has 30 — not equal.',
      C: 't = 5: Tank A has 20 gallons, Tank B has 15 — not equal.',
      D: 't = 8: Tank A has 14 gallons, Tank B has 24 — not equal.',
    },
  },

  {
    id: 'm2h-16',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'One-variable data: distributions and measures of center and spread',
    difficulty: 'hard',
    type: 'multiple_choice',
    stimulus: 'A class of 20 students took a test with a mean score of 78. The teacher then discovered that one student\'s score of 58 had been incorrectly recorded as 85.',
    question: 'What is the correct mean score after fixing the error?',
    choices: [
      { label: 'A', text: '75.65' },
      { label: 'B', text: '78.35' },
      { label: 'C', text: '77.65' },
      { label: 'D', text: '76.65' },
    ],
    correctAnswer: 'D',
    explanation: 'Original total = 78 × 20 = 1,560. The recorded score (85) should be 58, so the sum decreases by 85 − 58 = 27. Correct total = 1,560 − 27 = 1,533. Correct mean = 1,533 ÷ 20 = 76.65.',
    wrongAnswerExplanations: {
      A: 'Incorrectly reduces the mean by (85 + 58)/2 ÷ 20 rather than 27/20.',
      C: 'Uses the wrong difference — perhaps subtracting only part of the error.',
      B: 'Adds the error rather than subtracting it from the total.',
    },
  },

  {
    id: 'm2h-17',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'Probability',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'A bag contains 6 red marbles, 5 blue marbles, and 4 green marbles. Two marbles are drawn without replacement. What is the probability that both marbles are red?',
    choices: [
      { label: 'A', text: '1/7' },
      { label: 'B', text: '4/25' },
      { label: 'C', text: '2/5' },
      { label: 'D', text: '6/15' },
    ],
    correctAnswer: 'A',
    explanation: 'Total marbles = 15. P(1st red) = 6/15. P(2nd red | 1st red) = 5/14. P(both red) = (6/15)(5/14) = 30/210 = 1/7.',
    wrongAnswerExplanations: {
      B: '4/25 = (6/15)² — this incorrectly assumes replacement.',
      C: '2/5 = 6/15 — the probability the first marble is red, not both.',
      D: '6/15 is the unreduced probability of the first draw only.',
    },
  },

  {
    id: 'm2h-18',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'Probability',
    difficulty: 'hard',
    type: 'multiple_choice',
    stimulus: 'In a survey of 120 students, 50 said they play basketball, 40 said they play soccer, and 20 said they play both sports.',
    question: 'A student from the survey is selected at random. What is the probability that the selected student plays exactly one of the two sports?',
    choices: [
      { label: 'A', text: '5/12' },
      { label: 'B', text: '7/12' },
      { label: 'C', text: '1/6' },
      { label: 'D', text: '3/8' },
    ],
    correctAnswer: 'A',
    explanation: 'Basketball only: 50 − 20 = 30 students. Soccer only: 40 − 20 = 20 students. Exactly one sport: 30 + 20 = 50 students. Probability = 50/120 = 5/12.',
    wrongAnswerExplanations: {
      B: '7/12 = 70/120 is the probability of playing at least one sport (30 + 20 + 20 = 70), including those who play both.',
      C: '1/6 = 20/120 is the probability of playing both sports.',
      D: '3/8 = 45/120 does not correspond to any standard calculation from the given data.',
    },
  },

  {
    id: 'm2h-06',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Advanced Math',
    skill: 'Nonlinear functions',
    difficulty: 'hard',
    type: 'grid_in',
    question: 'If 2^(x + 3) = 64, what is the value of 3^x?',
    correctAnswer: '27',
    acceptableAnswers: ['27'],
    explanation: '64 = 2⁶, so 2^(x + 3) = 2⁶ → x + 3 = 6 → x = 3. Therefore 3^x = 3³ = 27.',
    scoringNotes: 'Only 27 is acceptable.',
  },

  {
    id: 'm2h-08',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Advanced Math',
    skill: 'Nonlinear equations in one variable',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'What are the solutions to 2x² + 5x − 3 = 0?',
    choices: [
      { label: 'A', text: 'x = 1/2 and x = −3' },
      { label: 'B', text: 'x = −1/2 and x = 3' },
      { label: 'C', text: 'x = 1 and x = −3/2' },
      { label: 'D', text: 'x = 3 and x = −1/2' },
    ],
    correctAnswer: 'A',
    explanation: 'Factor: (2x − 1)(x + 3) = 0 → x = 1/2 or x = −3. Alternatively, quadratic formula: x = (−5 ± √(25 + 24))/4 = (−5 ± 7)/4, giving x = 2/4 = 1/2 or x = −12/4 = −3.',
    wrongAnswerExplanations: {
      B: 'These are the negatives of the correct roots; check: 2(−1/2)² + 5(−1/2) − 3 = 1/2 − 5/2 − 3 = −5 ≠ 0.',
      C: '2(1)² + 5(1) − 3 = 4 ≠ 0.',
      D: 'Same roots as B reordered — neither satisfies the equation.',
    },
  },

  {
    id: 'm2h-09',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Advanced Math',
    skill: 'Nonlinear functions',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'The function f(x) = −2(x − 3)² + 8 has a maximum value. What is the maximum value?',
    choices: [
      { label: 'A', text: '−2' },
      { label: 'B', text: '3' },
      { label: 'C', text: '8' },
      { label: 'D', text: '14' },
    ],
    correctAnswer: 'C',
    explanation: 'In vertex form f(x) = a(x − h)² + k, the vertex is (h, k) = (3, 8). Since a = −2 < 0, the parabola opens downward and the vertex is the maximum. Maximum value = 8.',
    wrongAnswerExplanations: {
      A: '−2 is the coefficient a, which tells the direction of opening, not the maximum value.',
      B: '3 is the x-coordinate of the vertex, not the maximum y-value.',
      D: 'A common error: evaluating f(3) incorrectly or confusing the formula gives 14.',
    },
  },

  {
    id: 'm2h-10',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Advanced Math',
    skill: 'Equivalent expressions',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'For x ≠ 1, which expression is equivalent to (x² + 3x − 4)/(x − 1)?',
    choices: [
      { label: 'A', text: 'x − 4' },
      { label: 'B', text: 'x + 4' },
      { label: 'C', text: 'x + 3' },
      { label: 'D', text: 'x² + 4' },
    ],
    correctAnswer: 'B',
    explanation: 'Factor the numerator: x² + 3x − 4 = (x + 4)(x − 1). Cancel the common factor (x − 1): result is x + 4 for x ≠ 1.',
    wrongAnswerExplanations: {
      A: '(x − 4)(x − 1) = x² − 5x + 4 ≠ x² + 3x − 4.',
      C: '(x + 3)(x − 1) = x² + 2x − 3 ≠ x² + 3x − 4.',
      D: 'Dividing a degree-2 polynomial by a degree-1 polynomial yields a degree-1 result, not degree-2.',
    },
  },

  {
    id: 'm2h-11',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Advanced Math',
    skill: 'Nonlinear functions',
    difficulty: 'hard',
    type: 'grid_in',
    question: 'The function g(x) = −x² + kx + m has a maximum value of 11, and this maximum occurs at x = 3. What is the value of g(0)?',
    correctAnswer: '2',
    acceptableAnswers: ['2'],
    explanation: 'The vertex of g(x) = −x² + kx + m is at x = k/2 = 3, so k = 6. The maximum value is g(3): g(3) = −9 + 6(3) + m = 9 + m = 11, so m = 2. Therefore g(0) = −0 + 0 + 2 = 2.\n\nDesmos method: Enter y = −x² + kx + m and add sliders for k and m. Drag the sliders until the peak of the parabola lands exactly at (3, 11). Read the y-intercept of the graph directly — it equals g(0) = 2. You can also evaluate y at x = 0 using the Desmos table feature.',
    scoringNotes: 'Answer must be 2.',
  },

  {
    id: 'm2h-12',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Advanced Math',
    skill: 'Equivalent expressions',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'The polynomial 2x³ − 5x² + kx − 6 is divisible by (x − 3) with no remainder. What is the value of k?',
    choices: [
      { label: 'A', text: '−1' },
      { label: 'B', text: '1' },
      { label: 'C', text: '3' },
      { label: 'D', text: '−3' },
    ],
    correctAnswer: 'A',
    explanation: 'By the Remainder Theorem, if (x − 3) divides the polynomial with no remainder, then f(3) = 0. Substituting: 2(27) − 5(9) + 3k − 6 = 0 → 54 − 45 + 3k − 6 = 0 → 3 + 3k = 0 → k = −1.',
    wrongAnswerExplanations: {
      B: 'k = 1 gives f(3) = 3 + 3(1) = 6 ≠ 0; the polynomial is not divisible.',
      C: 'k = 3 gives f(3) = 3 + 9 = 12 ≠ 0.',
      D: 'k = −3 gives f(3) = 3 + 3(−3) = 3 − 9 = −6 ≠ 0.',
    },
  },

  {
    id: 'm2h-13',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Advanced Math',
    skill: 'Nonlinear equations in one variable and systems of equations',
    difficulty: 'hard',
    type: 'grid_in',
    question: 'The line y = 2x − k is tangent to the parabola y = x² − 4x + 5 (intersects it at exactly one point). What is the value of k?',
    correctAnswer: '4',
    acceptableAnswers: ['4'],
    explanation: 'Set the equations equal: x² − 4x + 5 = 2x − k → x² − 6x + (5 + k) = 0. For exactly one intersection, the discriminant equals zero: (−6)² − 4(1)(5 + k) = 0 → 36 − 20 − 4k = 0 → 16 = 4k → k = 4.\n\nDesmos method: Enter y = x² − 4x + 5 and y = 2x − k, then add a slider for k. Adjust k until the straight line is tangent to the parabola — exactly one intersection point appears. At k = 4 the line y = 2x − 4 touches the parabola at the single point (3, 2).',
    scoringNotes: 'Only 4 is acceptable.',
  },

  {
    id: 'm2h-14',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Advanced Math',
    skill: 'Nonlinear functions',
    difficulty: 'hard',
    type: 'grid_in',
    question: 'If 4^x = 8, what is the value of x? Enter your answer as a fraction.',
    correctAnswer: '3/2',
    acceptableAnswers: ['3/2', '1.5'],
    explanation: 'Express both sides as powers of 2: (2²)^x = 2³ → 2^(2x) = 2³ → 2x = 3 → x = 3/2.',
    scoringNotes: '3/2 or 1.5 are both acceptable.',
  },

  {
    id: 'm2h-03',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Geometry and Trigonometry',
    skill: 'Circles',
    difficulty: 'hard',
    type: 'multiple_choice',
    graphData: {
      type: 'geometry',
      viewBox: { xMin: -1.5, xMax: 12.5, yMin: -1.5, yMax: 11.5 },
      elements: [
        { kind: 'poly', pts: [[0,0],[10,0],[9.51,3.09],[8.09,5.88],[5.88,8.09],[3.09,9.51]] as [number, number][], fill: '#e0e7ff', stroke: '#4f46e5' },
        { kind: 'seg', p1: [0,0] as [number, number], p2: [10,0] as [number, number] },
        { kind: 'seg', p1: [0,0] as [number, number], p2: [3.09,9.51] as [number, number] },
        { kind: 'arc', center: [0,0] as [number, number], from: [1,0] as [number, number], to: [0.309,0.951] as [number, number], r: 1.5, label: '72°' },
        { kind: 'label', x: 5, y: -0.9, text: '10' },
        { kind: 'point', x: 0, y: 0 },
      ],
    },
    question: 'A circle has a radius of 10. A central angle of 72° intercepts an arc. What is the area of the sector formed by this central angle, in terms of π?',
    choices: [
      { label: 'A', text: '4π' },
      { label: 'B', text: '20π' },
      { label: 'C', text: '40π' },
      { label: 'D', text: '100π' },
    ],
    correctAnswer: 'B',
    explanation: 'Area of a sector = (central angle / 360°) × πr² = (72°/360°) × π(10²) = (1/5) × 100π = 20π.',
    wrongAnswerExplanations: {
      A: '4π is the arc length of this sector: (72°/360°) × 2π(10) = 4π — but the question asks for area, not arc length.',
      C: '40π results from incorrectly dividing the angle by 180° instead of 360°: (72/180) × 100π = 40π.',
      D: '100π = π(10²) is the total area of the full circle; the sector is only 72°/360° = 1/5 of the circle.',
    },
  },

  {
    id: 'm2h-07',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Geometry and Trigonometry',
    skill: 'Right triangles and trigonometry',
    difficulty: 'hard',
    type: 'grid_in',
    graphData: {
      type: 'geometry',
      viewBox: { xMin: -2, xMax: 16, yMin: -2, yMax: 7.5 },
      elements: [
        { kind: 'poly', pts: [[0,0],[12,0],[12,5]] as [number, number][] },
        { kind: 'right_angle', v: [12,0] as [number, number], a: [0,0] as [number, number], b: [12,5] as [number, number] },
        { kind: 'label', x: -0.4, y: -0.7, text: 'P', weight: 'bold', size: 11 },
        { kind: 'label', x: 12.6, y: -0.7, text: 'Q', weight: 'bold', size: 11 },
        { kind: 'label', x: 12.6, y: 5.5, text: 'R', weight: 'bold', size: 11 },
        { kind: 'label', x: 5.5, y: 3.1, text: '26', size: 11 },
        { kind: 'label', x: 13.2, y: 2.5, text: '?', size: 11 },
      ],
    },
    question: 'Right triangle PQR has a right angle at Q. If sin P = 5/13 and PR = 26, what is the length of QR?',
    correctAnswer: '10',
    acceptableAnswers: ['10'],
    explanation: 'sin P = QR/PR (opposite over hypotenuse). Setting up: 5/13 = QR/26, so QR = 26 × (5/13) = 10.',
    scoringNotes: 'Only 10 is acceptable.',
  },

  {
    id: 'm2h-19',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Geometry and Trigonometry',
    skill: 'Circles',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'The equation x² + y² − 6x + 8y = 0 represents a circle in the xy-plane. What is the radius of this circle?',
    choices: [
      { label: 'A', text: '5' },
      { label: 'B', text: '25' },
      { label: 'C', text: '√7' },
      { label: 'D', text: '7' },
    ],
    correctAnswer: 'A',
    explanation: 'Complete the square for x and y. Group: (x² − 6x) + (y² + 8y) = 0. Complete: (x − 3)² − 9 + (y + 4)² − 16 = 0 → (x − 3)² + (y + 4)² = 25. This is a circle centered at (3, −4) with r² = 25, so r = 5.',
    wrongAnswerExplanations: {
      B: '25 is r², not r — the square root step was omitted.',
      C: '√7 confuses this with completing the square incorrectly: √(9 − 16/2) or similar error.',
      D: '7 may result from computing 9 − 2 = 7 or another arithmetic error during the square completion.',
    },
  },

  {
    id: 'm2h-20',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Geometry and Trigonometry',
    skill: 'Lines, angles, and triangles',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'In triangle PQR, angle Q = 90°, PQ = 7, and QR = 24. Point S is the foot of the perpendicular from Q to hypotenuse PR. What is the length of PS?',
    choices: [
      { label: 'A', text: '7/5' },
      { label: 'B', text: '49/25' },
      { label: 'C', text: '168/25' },
      { label: 'D', text: '576/25' },
    ],
    correctAnswer: 'B',
    explanation: 'First find the hypotenuse: PR = √(PQ² + QR²) = √(49 + 576) = √625 = 25. When the altitude from the right angle meets the hypotenuse, two smaller triangles form that are each similar to triangle PQR. Triangle PQS ~ triangle PRQ (both share angle P and have a right angle), giving the proportion PS/PQ = PQ/PR. Therefore PS = PQ²/PR = 49/25.',
    wrongAnswerExplanations: {
      A: '7/5 mistakes the ratio PQ/QR (7/24) or confuses corresponding sides in the similarity.',
      C: '168/25 is the length of QS (the altitude itself): QS = PQ × QR / PR = 7 × 24 / 25.',
      D: '576/25 is the length of SR, the other segment of the hypotenuse: SR = QR²/PR = 576/25.',
    },
  },

  {
    id: 'm2h-21',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Geometry and Trigonometry',
    skill: 'Trigonometric ratios and equations',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'In the interval 0 ≤ x < 2π, how many distinct solutions does the equation 2sin²x + sin x − 1 = 0 have?',
    choices: [
      { label: 'A', text: '2' },
      { label: 'B', text: '3' },
      { label: 'C', text: '4' },
      { label: 'D', text: '6' },
    ],
    correctAnswer: 'B',
    explanation: 'Factor the left side as a quadratic in sin x: (2sin x − 1)(sin x + 1) = 0. This gives sin x = 1/2 or sin x = −1. For sin x = 1/2 in [0, 2π): x = π/6 and x = 5π/6 — two solutions. For sin x = −1 in [0, 2π): x = 3π/2 — one solution. The total is 3 solutions.',
    wrongAnswerExplanations: {
      A: '2 only counts the solutions to sin x = 1/2 and misses the solution sin x = −1 at x = 3π/2.',
      C: '4 incorrectly assumes each factor equation has exactly two solutions; sin x = −1 has only one solution in [0, 2π).',
      D: '6 overcounts by treating each quadrant as producing a solution for each factor, ignoring the range restriction of the sine function.',
    },
  },

  {
    id: 'm2h-22',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Geometry and Trigonometry',
    skill: 'Lines, angles, and triangles',
    difficulty: 'hard',
    type: 'grid_in',
    question: 'The two legs of a right triangle have lengths a and b where a + b = 17. The hypotenuse of the triangle has length 13. What is the value of ab?',
    correctAnswer: '60',
    acceptableAnswers: ['60'],
    explanation: 'By the Pythagorean theorem: a² + b² = 13² = 169. Expand (a + b)²: a² + 2ab + b² = 17² = 289. Substitute: 169 + 2ab = 289 → 2ab = 120 → ab = 60.',
    scoringNotes: 'Only 60 is acceptable.',
  },
]
