import type { MathQuestion } from './types'

// Math Module 2 Hard — 22 questions (0 easy, ~10 medium, ~12 hard)
// 17 multiple choice (q01–q17) + 5 grid-in (q18–q22)

export const mathModule2HardQuestions: MathQuestion[] = [

  // ── Algebra (5 MC + 2 grid-in) ───────────────────────────────────────────────

  {
    id: 'm2h-01',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Algebra',
    skill: 'Systems of two linear equations in two variables',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'The system below has no solution. What is the value of k?\n3x − ky = 8\n9x − 12y = 18',
    choices: [
      { label: 'A', text: '3' },
      { label: 'B', text: '4' },
      { label: 'C', text: '6' },
      { label: 'D', text: '9' },
    ],
    correctAnswer: 'B',
    explanation: 'Divide the second equation by 3: 3x − 4y = 6. For no solution, the lines must be parallel (same slope, different constants). The first line 3x − ky = 8 has slope 3/k; the second has slope 3/4. Setting 3/k = 3/4 gives k = 4. With k = 4: the equations are 3x − 4y = 8 and 3x − 4y = 6 — parallel with different constants, confirming no solution.',
    wrongAnswerExplanations: {
      A: 'If k = 3, slope of first line = 1 ≠ 3/4 — the lines intersect (one solution).',
      C: 'If k = 6, slope of first line = 1/2 ≠ 3/4 — the lines intersect.',
      D: 'If k = 9, slope = 3/9 = 1/3 ≠ 3/4 — the lines intersect.',
    },
  },

  {
    id: 'm2h-02',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Algebra',
    skill: 'Linear functions',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Line p passes through the point (−2, 7) and is perpendicular to the line y = (1/3)x + 4. What is the equation of line p?',
    choices: [
      { label: 'A', text: 'y = 3x + 13' },
      { label: 'B', text: 'y = −3x − 1' },
      { label: 'C', text: 'y = (1/3)x + 23/3' },
      { label: 'D', text: 'y = −3x + 1' },
    ],
    correctAnswer: 'D',
    explanation: 'The slope of y = (1/3)x + 4 is 1/3. A perpendicular slope is −1/(1/3) = −3. Using point (−2, 7): y − 7 = −3(x + 2) → y = −3x − 6 + 7 → y = −3x + 1.',
    wrongAnswerExplanations: {
      A: 'Slope +3 is the reciprocal without flipping the sign — this line is not perpendicular.',
      C: 'Same slope as the original — this is the parallel line through (−2, 7), not perpendicular.',
      B: 'Correct slope −3, but wrong y-intercept: at x = −2, y = −3(−2) − 1 = 5 ≠ 7.',
    },
  },

  {
    id: 'm2h-03',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Algebra',
    skill: 'Linear equations in one variable',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'A company produces and sells widgets. The cost to produce n widgets is C = 0.08n + 12 (in dollars) and the revenue from selling n widgets is R = 0.12n. How many widgets must be sold to break even?',
    choices: [
      { label: 'A', text: '150' },
      { label: 'B', text: '200' },
      { label: 'C', text: '400' },
      { label: 'D', text: '300' },
    ],
    correctAnswer: 'D',
    explanation: 'Set R = C: 0.12n = 0.08n + 12 → 0.04n = 12 → n = 300.',
    wrongAnswerExplanations: {
      A: 'At n = 150: R = 18, C = 12 + 12 = 24. Revenue < Cost — still losing money.',
      B: 'At n = 200: R = 24, C = 16 + 12 = 28. Still not break-even.',
      C: 'At n = 400: R = 48, C = 32 + 12 = 44. Already profitable — break-even passed.',
    },
  },

  {
    id: 'm2h-04',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Algebra',
    skill: 'Systems of two linear equations in two variables',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'The total cost of 5 adult tickets and 3 child tickets is $88. The total cost of 2 adult tickets and 6 child tickets is $64. What is the cost, in dollars, of one adult ticket?',
    choices: [
      { label: 'A', text: '$10' },
      { label: 'B', text: '$12' },
      { label: 'C', text: '$14' },
      { label: 'D', text: '$16' },
    ],
    correctAnswer: 'C',
    explanation: 'Let a = adult price, c = child price. Equations: 5a + 3c = 88 and 2a + 6c = 64. Divide the second by 2: a + 3c = 32. Subtract from the first: 4a = 56 → a = 14. Verify: c = (32 − 14)/3 = 6; check: 5(14) + 3(6) = 88 ✓ and 2(14) + 6(6) = 64 ✓.',
    wrongAnswerExplanations: {
      A: 'If a = 10, then 3c = 22 — not an integer child price.',
      B: 'If a = 12, then 3c = 20 — not an integer child price.',
      D: 'If a = 16, then 3c = 16 — not an integer child price.',
    },
  },

  {
    id: 'm2h-05',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Algebra',
    skill: 'Linear inequalities in one or two variables',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Which of the following represents all values of x satisfying |2x − 1| ≤ 7?',
    choices: [
      { label: 'A', text: 'x ≤ 4' },
      { label: 'B', text: '−3 ≤ x ≤ 4' },
      { label: 'C', text: 'x ≥ −3' },
      { label: 'D', text: '−4 ≤ x ≤ 3' },
    ],
    correctAnswer: 'B',
    explanation: '|2x − 1| ≤ 7 means −7 ≤ 2x − 1 ≤ 7. Add 1: −6 ≤ 2x ≤ 8. Divide by 2: −3 ≤ x ≤ 4.',
    wrongAnswerExplanations: {
      A: 'This gives only the right boundary, missing the left constraint x ≥ −3.',
      C: 'This gives only the left boundary, missing the right constraint x ≤ 4.',
      D: 'This results from applying a sign error to the inner expression (treating it as −2x + 1 instead of 2x − 1).',
    },
  },

  {
    id: 'm2h-06',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Algebra',
    skill: 'Linear functions',
    difficulty: 'medium',
    type: 'grid_in',
    question: 'A linear function f satisfies f(1) = 5 and f(4) = 14. What is the value of f(7)?',
    correctAnswer: '23',
    acceptableAnswers: ['23'],
    explanation: 'Slope = (14 − 5)/(4 − 1) = 9/3 = 3. Using f(1) = 5: b = 5 − 3(1) = 2. So f(x) = 3x + 2. Then f(7) = 3(7) + 2 = 23.',
  },

  {
    id: 'm2h-07',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Algebra',
    skill: 'Linear equations in one variable',
    difficulty: 'medium',
    type: 'grid_in',
    question: 'If (3a + 2)/4 − (a − 1)/2 = 3, what is the value of a?',
    correctAnswer: '8',
    acceptableAnswers: ['8'],
    explanation: 'Multiply every term by 4: (3a + 2) − 2(a − 1) = 12. Distribute: 3a + 2 − 2a + 2 = 12. Combine: a + 4 = 12 → a = 8.',
    scoringNotes: 'Only 8 is acceptable.',
  },

  // ── Advanced Math (5 MC + 2 grid-in) ─────────────────────────────────────────

  {
    id: 'm2h-08',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Advanced Math',
    skill: 'Nonlinear equations in one variable',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'What are the solutions to 2x² + 5x − 3 = 0?',
    choices: [
      { label: 'A', text: 'x = 1/2 and x = −3' },
      { label: 'B', text: 'x = −1/2 and x = 3' },
      { label: 'C', text: 'x = 1 and x = −3/2' },
      { label: 'D', text: 'x = 3 and x = −1/2' },
    ],
    correctAnswer: 'A',
    explanation: 'Factor: (2x − 1)(x + 3) = 0 → x = 1/2 or x = −3. Alternatively, quadratic formula: x = (−5 ± √(25 + 24))/4 = (−5 ± 7)/4, giving x = 2/4 = 1/2 or x = −12/4 = −3.',
    wrongAnswerExplanations: {
      B: 'These are the negatives of the correct roots; check: 2(−1/2)² + 5(−1/2) − 3 = 1/2 − 5/2 − 3 = −5 ≠ 0.',
      C: '2(1)² + 5(1) − 3 = 4 ≠ 0.',
      D: 'Same roots as B reordered — neither satisfies the equation.',
    },
  },

  {
    id: 'm2h-09',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Advanced Math',
    skill: 'Nonlinear functions',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'The function f(x) = −2(x − 3)² + 8 has a maximum value. What is the maximum value?',
    choices: [
      { label: 'A', text: '−2' },
      { label: 'B', text: '3' },
      { label: 'C', text: '8' },
      { label: 'D', text: '14' },
    ],
    correctAnswer: 'C',
    explanation: 'In vertex form f(x) = a(x − h)² + k, the vertex is (h, k) = (3, 8). Since a = −2 < 0, the parabola opens downward and the vertex is the maximum. Maximum value = 8.',
    wrongAnswerExplanations: {
      A: '−2 is the coefficient a, which tells the direction of opening, not the maximum value.',
      B: '3 is the x-coordinate of the vertex, not the maximum y-value.',
      D: 'A common error: evaluating f(3) incorrectly or confusing the formula gives 14.',
    },
  },

  {
    id: 'm2h-10',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Advanced Math',
    skill: 'Equivalent expressions',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'For x ≠ 1, which expression is equivalent to (x² + 3x − 4)/(x − 1)?',
    choices: [
      { label: 'A', text: 'x − 4' },
      { label: 'B', text: 'x + 4' },
      { label: 'C', text: 'x + 3' },
      { label: 'D', text: 'x² + 4' },
    ],
    correctAnswer: 'B',
    explanation: 'Factor the numerator: x² + 3x − 4 = (x + 4)(x − 1). Cancel the common factor (x − 1): result is x + 4 for x ≠ 1.',
    wrongAnswerExplanations: {
      A: '(x − 4)(x − 1) = x² − 5x + 4 ≠ x² + 3x − 4.',
      C: '(x + 3)(x − 1) = x² + 2x − 3 ≠ x² + 3x − 4.',
      D: 'Dividing a degree-2 polynomial by a degree-1 polynomial yields a degree-1 result, not degree-2.',
    },
  },

  {
    id: 'm2h-11',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Advanced Math',
    skill: 'Equivalent expressions',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'Which of the following is equivalent to (2x³y²)(3x²y)?',
    choices: [
      { label: 'A', text: '5x⁵y³' },
      { label: 'B', text: '6x⁵y²' },
      { label: 'C', text: '6x⁶y²' },
      { label: 'D', text: '6x⁵y³' },
    ],
    correctAnswer: 'D',
    explanation: 'Multiply coefficients: 2 × 3 = 6. Add exponents: x³ · x² = x⁵; y² · y¹ = y³. Result: 6x⁵y³.',
    wrongAnswerExplanations: {
      A: 'This adds the coefficients (2 + 3 = 5) instead of multiplying.',
      C: 'This multiplies the x-exponents (3 × 2 = 6) instead of adding.',
      B: 'Correct x-exponent but wrong y-exponent: y² · y = y³, not y².',
    },
  },

  {
    id: 'm2h-12',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Advanced Math',
    skill: 'Equivalent expressions',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'Which expression is equivalent to √(x − 2) when x = 27?',
    choices: [
      { label: 'A', text: '√7' },
      { label: 'B', text: '5' },
      { label: 'C', text: '√23' },
      { label: 'D', text: '√29' },
    ],
    correctAnswer: 'B',
    explanation: '√(27 − 2) = √25 = 5.',
    wrongAnswerExplanations: {
      A: '√7 results from computing √(x) − √2 = √27 − √2, incorrectly distributing the radical.',
      C: '√23 results from computing √27 − 2 (subtracting inside is correct, but √25 = 5, not √23).',
      D: '√29 results from computing √(27 + 2) = √29, adding instead of subtracting.',
    },
  },

  {
    id: 'm2h-13',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Advanced Math',
    skill: 'Nonlinear equations in one variable',
    difficulty: 'medium',
    type: 'grid_in',
    question: 'The equation x² − 6x + k = 0 has exactly one real solution. What is the value of k?',
    correctAnswer: '9',
    acceptableAnswers: ['9'],
    explanation: 'For exactly one real solution, the discriminant = 0: b² − 4ac = (−6)² − 4(1)(k) = 36 − 4k = 0 → k = 9.',
    scoringNotes: 'Only 9 is acceptable.',
  },

  {
    id: 'm2h-14',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Advanced Math',
    skill: 'Nonlinear functions',
    difficulty: 'hard',
    type: 'grid_in',
    question: 'If 4^x = 8, what is the value of x? Enter your answer as a fraction.',
    correctAnswer: '3/2',
    acceptableAnswers: ['3/2', '1.5'],
    explanation: 'Express both sides as powers of 2: (2²)^x = 2³ → 2^(2x) = 2³ → 2x = 3 → x = 3/2.',
    scoringNotes: '3/2 or 1.5 are both acceptable.',
  },

  // ── Problem-Solving and Data Analysis (4 MC) ─────────────────────────────────

  {
    id: 'm2h-15',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'Ratios, rates, proportional relationships, and units',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'A train travels at a constant speed of 60 miles per hour. How many miles does it travel in 100 minutes?',
    choices: [
      { label: 'A', text: '80' },
      { label: 'B', text: '90' },
      { label: 'C', text: '100' },
      { label: 'D', text: '120' },
    ],
    correctAnswer: 'C',
    explanation: 'Convert: 100 minutes = 100/60 = 5/3 hours. Distance = 60 × 5/3 = 100 miles.',
    wrongAnswerExplanations: {
      A: '80 does not follow from 60 mph × 100 minutes with proper unit conversion.',
      B: '90 = 60 × 1.5 hours — using 90 minutes rather than 100.',
      D: '120 = 60 × 2 hours — using 2 hours (120 min) instead of 100 minutes.',
    },
  },

  {
    id: 'm2h-16',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'One-variable data: distributions and measures of center and spread',
    difficulty: 'hard',
    type: 'multiple_choice',
    stimulus: 'A class of 20 students took a test with a mean score of 78. The teacher then discovered that one student\'s score of 58 had been incorrectly recorded as 85.',
    question: 'What is the correct mean score after fixing the error?',
    choices: [
      { label: 'A', text: '75.65' },
      { label: 'B', text: '78.35' },
      { label: 'C', text: '77.65' },
      { label: 'D', text: '76.65' },
    ],
    correctAnswer: 'D',
    explanation: 'Original total = 78 × 20 = 1,560. The recorded score (85) should be 58, so the sum decreases by 85 − 58 = 27. Correct total = 1,560 − 27 = 1,533. Correct mean = 1,533 ÷ 20 = 76.65.',
    wrongAnswerExplanations: {
      A: 'Incorrectly reduces the mean by (85 + 58)/2 ÷ 20 rather than 27/20.',
      C: 'Uses the wrong difference — perhaps subtracting only part of the error.',
      B: 'Adds the error rather than subtracting it from the total.',
    },
  },

  {
    id: 'm2h-17',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'Probability',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'A bag contains 6 red marbles, 5 blue marbles, and 4 green marbles. Two marbles are drawn without replacement. What is the probability that both marbles are red?',
    choices: [
      { label: 'A', text: '1/7' },
      { label: 'B', text: '4/25' },
      { label: 'C', text: '2/5' },
      { label: 'D', text: '6/15' },
    ],
    correctAnswer: 'A',
    explanation: 'Total marbles = 15. P(1st red) = 6/15. P(2nd red | 1st red) = 5/14. P(both red) = (6/15)(5/14) = 30/210 = 1/7.',
    wrongAnswerExplanations: {
      B: '4/25 = (6/15)² — this incorrectly assumes replacement.',
      C: '2/5 = 6/15 — the probability the first marble is red, not both.',
      D: '6/15 is the unreduced probability of the first draw only.',
    },
  },

  {
    id: 'm2h-18',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'Two-variable data: models and scatterplots',
    difficulty: 'medium',
    type: 'multiple_choice',
    stimulus: 'A study models the relationship between hours of sunlight (x) and plant height in cm (y) using the equation y = 2.4x + 3.',
    question: 'According to this model, what does the value 3 represent?',
    choices: [
      { label: 'A', text: 'The predicted height of the plant when it receives no sunlight' },
      { label: 'B', text: 'The number of hours of sunlight needed for the plant to start growing' },
      { label: 'C', text: 'The rate at which the plant grows per hour of sunlight' },
      { label: 'D', text: 'The maximum height the plant can reach' },
    ],
    correctAnswer: 'A',
    explanation: 'In y = 2.4x + 3, the value 3 is the y-intercept — the predicted height when x = 0 (no sunlight). The slope 2.4 is the rate of height increase per hour of sunlight.',
    wrongAnswerExplanations: {
      B: 'The y-intercept does not represent a required condition — it is the value of y when x = 0.',
      C: 'The rate of growth is the slope, 2.4, not the y-intercept 3.',
      D: 'A linear model has no maximum; a horizontal asymptote would indicate a maximum.',
    },
  },

  // ── Geometry and Trigonometry (3 MC + 1 grid-in) ─────────────────────────────

  {
    id: 'm2h-19',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Geometry and Trigonometry',
    skill: 'Area and volume',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'A cylinder has a radius of 3 cm and a height of 8 cm. What is the volume of the cylinder, in terms of π?',
    choices: [
      { label: 'A', text: '24π cm³' },
      { label: 'B', text: '48π cm³' },
      { label: 'C', text: '72π cm³' },
      { label: 'D', text: '144π cm³' },
    ],
    correctAnswer: 'C',
    explanation: 'Volume = πr²h = π(3)²(8) = 9π(8) = 72π cm³.',
    wrongAnswerExplanations: {
      A: '24π = π(3)(8) uses r instead of r².',
      B: '48π results from using diameter (6) as if it were the radius, then halving: π(6)²(8)/6 — or other errors.',
      D: '144π = 2 × 72π — doubling the correct answer.',
    },
  },

  {
    id: 'm2h-20',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Geometry and Trigonometry',
    skill: 'Lines, angles, and triangles',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'In a 30-60-90 triangle, the shorter leg has length 5. What is the length of the hypotenuse?',
    choices: [
      { label: 'A', text: '5√2' },
      { label: 'B', text: '5√3' },
      { label: 'C', text: '10' },
      { label: 'D', text: '10√3' },
    ],
    correctAnswer: 'C',
    explanation: 'In a 30-60-90 triangle, sides are in ratio 1 : √3 : 2. The shorter leg (opposite 30°) = 5, so the hypotenuse = 2 × 5 = 10.',
    wrongAnswerExplanations: {
      A: '5√2 applies the 45-45-90 ratio (1:1:√2), not 30-60-90.',
      B: '5√3 is the length of the longer leg, not the hypotenuse.',
      D: '10√3 doubles the longer leg instead of the shorter leg.',
    },
  },

  {
    id: 'm2h-21',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Geometry and Trigonometry',
    skill: 'Trigonometric ratios and equations',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'In right triangle ABC with the right angle at C, sin A = 3/5. What is the value of tan A?',
    choices: [
      { label: 'A', text: '3/4' },
      { label: 'B', text: '4/3' },
      { label: 'C', text: '4/5' },
      { label: 'D', text: '5/3' },
    ],
    correctAnswer: 'A',
    explanation: 'sin A = opposite/hypotenuse = 3/5. The adjacent side = √(5² − 3²) = √16 = 4. tan A = opposite/adjacent = 3/4.',
    wrongAnswerExplanations: {
      B: '4/3 = adjacent/opposite — this is cot A, not tan A.',
      C: '4/5 = adjacent/hypotenuse — this is cos A.',
      D: '5/3 = hypotenuse/opposite — this is csc A.',
    },
  },

  {
    id: 'm2h-22',
    section: 'math',
    moduleId: 'math-module-2-hard',
    domain: 'Geometry and Trigonometry',
    skill: 'Lines, angles, and triangles',
    difficulty: 'hard',
    type: 'grid_in',
    question: 'A ladder 25 feet long leans against a vertical wall. The base of the ladder is 7 feet from the base of the wall. How high up the wall does the top of the ladder reach, in feet?',
    correctAnswer: '24',
    acceptableAnswers: ['24'],
    explanation: 'The ladder, wall, and ground form a right triangle with hypotenuse 25 and one leg 7. By the Pythagorean theorem: h² + 7² = 25² → h² = 625 − 49 = 576 → h = 24. (7-24-25 is a Pythagorean triple.)',
    scoringNotes: 'Answer must be 24.',
  },
]
