import type { RWQuestion } from './types'

// Reading and Writing Module 2 Hard — 27 questions (harder second module, all hard)

export const rwModule2HardQuestions: RWQuestion[] = [
  {
    id: 'rw2h-01',
    section: 'reading-writing',
    moduleId: 'rw-module-2-hard',
    domain: 'Craft and Structure',
    skill: 'Words in Context',
    difficulty: 'hard',
    stimulus: `In epistemology, the problem of induction concerns whether repeated observations can ever logically justify a universal claim. David Hume argued that our habit of inferring future regularities from past experience is psychologically compelled but rationally unwarranted — a conclusion that has proven remarkably intractable to philosophers seeking a complete logical foundation for empirical science. No matter how many white swans one observes, strict deductive logic cannot preclude a black swan; the generalization remains, in principle, perpetually provisional.`,
    question: `As used in the passage, "intractable" most nearly means`,
    choices: [
      { label: 'A', text: 'resistant and impervious to solution' },
      { label: 'B', text: 'capable of being managed or readily analyzed' },
      { label: 'C', text: 'logically sound and well-supported' },
      { label: 'D', text: 'peripheral and of little concern' },
    ],
    correctAnswer: 'A',
    explanation: `Choice A is correct. The passage describes Hume's conclusion — that inductive reasoning is rationally unwarranted — as "remarkably intractable to philosophers seeking a complete logical foundation for empirical science." This means the conclusion has stubbornly resisted philosophers' efforts to overcome it. The final sentence reinforces this: the generalization "remains, in principle, perpetually provisional," confirming that the problem cannot be resolved by accumulating observations. "Resistant and impervious to solution" captures this meaning precisely.`,
    wrongAnswerExplanations: {
      B: `Choice B is incorrect. "Capable of being managed or readily analyzed" describes a tractable problem, which is the opposite of intractable. The passage emphasizes that the problem has not yielded to resolution.`,
      C: `Choice C is incorrect. The passage does not describe Hume's conclusion as logically sound; it describes a conclusion that undermines the logical foundations of empirical science by showing that inductive reasoning cannot be rationally justified.`,
      D: `Choice D is incorrect. Hume's problem of induction is treated by the passage as central and consequential to epistemology, not as peripheral or of little concern.`,
    },
  },

  {
    id: 'rw2h-02',
    section: 'reading-writing',
    moduleId: 'rw-module-2-hard',
    domain: 'Craft and Structure',
    skill: 'Words in Context',
    difficulty: 'hard',
    stimulus: `In literary criticism, "precipitate" can function as a verb meaning to cause something to happen abruptly, or as an adjective meaning arriving with undue haste before adequate preparation. A reviewer of a recent experimental novel writes: "The novel's final revelation is precipitate in the worst sense, arriving not as the culmination of carefully layered tension but as a blunt intrusion that forecloses the ambiguity the novel had so skillfully cultivated."`,
    question: `As used in the review, "precipitate" most nearly means`,
    choices: [
      { label: 'A', text: 'causing or triggering a sudden outcome' },
      { label: 'B', text: 'occurring with undue haste and insufficient preparation' },
      { label: 'C', text: 'condensed or compressed in expression' },
      { label: 'D', text: 'falling steeply or descending from a height' },
    ],
    correctAnswer: 'B',
    explanation: `Choice B is correct. The review specifies that the revelation is "precipitate in the worst sense" because it arrives as "a blunt intrusion" before the narrative's emotional logic is ready — it is not adequately prepared by what came before. This matches the meaning of precipitate as arriving with undue haste or premature abruptness. The passage even contrasts this with what should have been "the culmination of carefully layered tension," confirming that the fault is insufficient buildup.`,
    wrongAnswerExplanations: {
      A: `Choice A is incorrect. While "precipitate" can mean to cause or trigger something (as in "precipitate a crisis"), the review is describing the quality of the revelation itself — how it arrives — not its causal effect on another event. The reviewer criticizes its premature arrival, not its triggering of a collapse.`,
      C: `Choice C is incorrect. The passage does not describe the revelation's style of expression as condensed or compressed; the criticism is about its timing relative to the novel's emotional preparation.`,
      D: `Choice D is incorrect. The literal physical sense of "precipitate" (falling steeply) is not applicable to a narrative revelation in a novel.`,
    },
  },

  {
    id: 'rw2h-03',
    section: 'reading-writing',
    moduleId: 'rw-module-2-hard',
    domain: 'Craft and Structure',
    skill: 'Words in Context',
    difficulty: 'hard',
    stimulus: `Political theorists have long grappled with the tension between procedural and substantive conceptions of justice. Procedural accounts hold that an outcome is just if it results from a fair process, regardless of what that outcome happens to be. Substantive accounts, by contrast, evaluate outcomes directly against independent criteria of fairness or welfare. A persistent challenge for procedural theorists is the possibility that an ostensibly fair procedure can yield outcomes that are, by almost any independent reckoning, deeply unjust.`,
    question: `As used in the passage, "ostensibly" most nearly means`,
    choices: [
      { label: 'A', text: 'secretly' },
      { label: 'B', text: 'rigorously and transparently' },
      { label: 'C', text: 'apparently but perhaps not genuinely' },
      { label: 'D', text: 'historically established' },
    ],
    correctAnswer: 'C',
    explanation: `Choice C is correct. The passage describes a procedure that appears fair by procedural standards but may still yield unjust outcomes. "Ostensibly" signals that something appears to be one way but may not actually be so — the appearance of fairness that does not guarantee substantive justice.`,
    wrongAnswerExplanations: {
      A: `Choice A is incorrect. "Secretly" implies hidden deception, but "ostensibly" describes surface appearance without implying deliberate concealment.`,
      B: `Choice B is incorrect. "Rigorously and transparently" would suggest the procedure is genuinely fair, which is what the passage is questioning.`,
      D: `Choice D is incorrect. Historical establishment is unrelated to the meaning of "ostensibly" in this context.`,
    },
  },

  {
    id: 'rw2h-09',
    section: 'reading-writing',
    moduleId: 'rw-module-2-hard',
    domain: 'Craft and Structure',
    skill: 'Words in Context',
    difficulty: 'hard',
    stimulus: `The anthropologist's account of the ritual was not so much a description as a refraction: she had passed the community's practices through the lens of her own theoretical commitments until what emerged bore the structure of her argument more than the texture of what she had witnessed. Her colleagues in the field admired the elegance of her analysis while privately doubting that any informant, had they read it, would have recognized themselves in its pages. The gap between the observed and the represented had been, as it so often is in ethnographic work, tendentious.`,
    question: `As used in the passage, "tendentious" most nearly means`,
    choices: [
      { label: 'A', text: 'shaped by a particular interpretive bias rather than straightforwardly objective' },
      { label: 'B', text: 'excessively long and difficult to read' },
      { label: 'C', text: 'deliberately falsified to mislead readers' },
      { label: 'D', text: 'attentive to minor details at the expense of broader patterns' },
    ],
    correctAnswer: 'A',
    explanation: `Choice A is correct. The passage describes how the anthropologist passed the community's practices through "her own theoretical commitments" until the analysis reflected her argument more than observable reality — and her colleagues doubted informants would recognize themselves in the account. This is the portrait of analysis bent by prior interpretive commitments rather than straightforwardly objective. "Tendentious" in this context means shaped by a particular bias, exactly fitting the passage's portrait of scholarship distorted by theoretical precommitments.`,
    wrongAnswerExplanations: {
      B: `Choice B is incorrect. The passage does not describe the account as long or difficult; the colleagues admired its "elegance," suggesting it was well-crafted rather than unwieldy.`,
      C: `Choice C is incorrect. "Deliberately falsified" implies intentional deception, but the passage suggests the distortion arose from theoretical lens-shaping rather than conscious dishonesty.`,
      D: `Choice D is incorrect. Nothing in the passage suggests excessive attention to detail at the expense of broader patterns; the criticism is that the analysis over-imposed an argument, not that it got lost in minutiae.`,
    },
  },

  {
    id: 'rw2h-06',
    section: 'reading-writing',
    moduleId: 'rw-module-2-hard',
    domain: 'Craft and Structure',
    skill: 'Text Structure and Purpose',
    difficulty: 'hard',
    stimulus: `For centuries, the dominant view in philosophy held that perception gives us direct and unmediated access to an external world that exists independently of the mind. This "naive realism" was severely shaken — though not entirely abandoned — by Descartes' argument from illusion, which noted that perceptual experience can be qualitatively identical in cases of veridical perception and in cases of illusion or hallucination. If the mind's-eye view is the same in both cases, how can perception alone guarantee contact with reality? Subsequent thinkers proposed a range of mediating entities — sense-data, representations, or phenomenal images — standing between the perceiver and the world. Critics of this "indirect realism" have argued, however, that positing such intermediaries merely relocates the problem rather than solving it, since the question of how mental representations correspond to external reality is at least as difficult as the original puzzle.`,
    question: `The author's mention of "indirect realism" in the final sentence primarily serves to`,
    choices: [
      { label: 'A', text: 'provide an example of naive realism that has withstood philosophical criticism' },
      { label: 'B', text: 'introduce a proposed solution to the problem raised by Descartes and then immediately qualify its adequacy' },
      { label: 'C', text: 'argue that Descartes\' argument from illusion is logically flawed' },
      { label: 'D', text: 'explain why mediating entities such as sense-data cannot exist' },
    ],
    correctAnswer: 'B',
    explanation: `Choice B is correct. The passage describes indirect realism — the view that mediating entities stand between perceiver and world — as the solution subsequent thinkers offered to the problem Descartes raised. The author then immediately introduces critics who argue that positing intermediaries only displaces the problem, not eliminating it. This is a classic introduce-then-qualify rhetorical move: the proposed solution is presented and its adequacy is simultaneously challenged.`,
    wrongAnswerExplanations: {
      A: `Choice A is incorrect. Indirect realism is a response to naive realism, not an example of it; moreover, the passage presents it as contested, not as something that has withstood criticism.`,
      C: `Choice C is incorrect. The passage presents Descartes' argument as the source of the problem that later theories tried to solve; the author does not claim the argument is logically flawed.`,
      D: `Choice D is incorrect. The critics' argument is that mediating entities create a new problem of correspondence, not that such entities cannot exist at all.`,
    },
  },

  {
    id: 'rw2h-07',
    section: 'reading-writing',
    moduleId: 'rw-module-2-hard',
    domain: 'Craft and Structure',
    skill: 'Text Structure and Purpose',
    difficulty: 'hard',
    stimulus: `The philosopher Charles Taylor distinguishes between "weak" and "strong" evaluations of desire. A weak evaluation simply ranks preferences by how much one wants them. A strong evaluation assesses desires according to qualitative distinctions about worth — ranking some desires as higher, nobler, or more authentically expressive of who one wants to be than others. Taylor argues that the capacity for strong evaluation is constitutive of what it means to be a moral agent: it is what allows human beings to reflect on and potentially transform their motivational structures rather than simply acting on whichever desire happens to be strongest at a given moment.`,
    underlineTargets: ['whichever desire happens to be strongest at a given moment'],
    question: `The underlined phrase "whichever desire happens to be strongest at a given moment" primarily serves to`,
    choices: [
      { label: 'A', text: 'describe the behavior of agents capable of strong evaluation' },
      { label: 'B', text: 'characterize the motivational behavior that strong evaluation allows agents to transcend' },
      { label: 'C', text: 'provide an example of the qualitative distinctions involved in strong evaluation' },
      { label: 'D', text: 'suggest that weak evaluations are always selfish and irrational' },
    ],
    correctAnswer: 'B',
    explanation: `Choice B is correct. The phrase contrasts with strong evaluation: instead of reflecting on which desires are worthiest, an agent without this capacity merely acts on "whichever desire happens to be strongest." This phrase characterizes the unreflective motivational behavior that strong evaluation enables agents to move beyond.`,
    wrongAnswerExplanations: {
      A: `Choice A is incorrect. The phrase describes agents incapable of or not engaged in strong evaluation, not those who exercise it.`,
      C: `Choice C is incorrect. The phrase is a contrast to strong evaluation, not an example of it.`,
      D: `Choice D is incorrect. The passage does not describe weak evaluations as selfish or irrational; it simply says they rank preferences by intensity rather than by qualitative worth.`,
    },
  },

  {
    id: 'rw2h-08',
    section: 'reading-writing',
    moduleId: 'rw-module-2-hard',
    domain: 'Craft and Structure',
    skill: 'Text Structure and Purpose',
    difficulty: 'hard',
    stimulus: `Recent studies in epigenetics have challenged the once-firm boundary between nature and nurture by demonstrating that environmental experiences can alter gene expression without changing the underlying DNA sequence. Exposure to stress, malnutrition, or trauma can add chemical tags to DNA or to the histone proteins around which DNA is wound, toggling genes on or off in ways that affect physiology, behavior, and vulnerability to disease. In some organisms, these epigenetic modifications have been shown to persist across generations — though the extent to which this occurs in humans remains an active area of research and debate.`,
    question: `The final clause — "though the extent to which this occurs in humans remains an active area of research and debate" — primarily functions to`,
    choices: [
      { label: 'A', text: 'refute the claim that environmental experiences can alter gene expression in humans' },
      { label: 'B', text: 'argue that human epigenetics requires more government funding for research' },
      { label: 'C', text: 'suggest that epigenetics is a less credible field than classical genetics' },
      { label: 'D', text: 'introduce a caveat limiting how broadly the multigenerational finding applies' },
    ],
    correctAnswer: 'D',
    explanation: `Choice D is correct. The clause comes after the claim that epigenetic modifications can persist across generations "in some organisms." The final clause limits this finding by noting that the human case is uncertain and contested, making it a qualifying caveat that restricts how far the preceding claim can be extended.`,
    wrongAnswerExplanations: {
      A: `Choice A is incorrect. The clause limits the generational persistence claim, not the broader claim that environments can alter gene expression in humans, which was established earlier in the passage.`,
      C: `Choice C is incorrect. The passage presents epigenetics positively throughout; the caveat is about one specific question, not about the field's credibility.`,
      B: `Choice B is incorrect. The clause describes the research status of a question, not a funding argument.`,
    },
  },

  {
    id: 'rw2h-11',
    section: 'reading-writing',
    moduleId: 'rw-module-2-hard',
    domain: 'Information and Ideas',
    skill: 'Central Ideas and Details',
    difficulty: 'hard',
    stimulus: `The field of behavioral economics emerged from a striking observation: human beings systematically deviate from classical rational-choice theory in ways that are consistent across populations and settings. Researchers documented predictable patterns such as loss aversion — the tendency to weight losses more heavily than equivalent gains — and preferences that shift inconsistently depending on when a reward is anticipated. These anomalies were initially framed as cognitive failures, implying that corrective "nudges" could steer people toward better choices. Critics have since argued, however, that labeling departures from rational-choice theory as "failures" presupposes that the theory correctly describes what rationality requires — a premise that itself needs defense. Some departures, critics suggest, may reflect adaptive heuristics that perform well in realistic environments even if they appear irrational by the narrow standard of classical theory.`,
    question: `Which of the following best states the central claim of the passage?`,
    choices: [
      { label: 'A', text: 'Behavioral economics has proven that human beings are fundamentally irrational and require institutional correction.' },
      { label: 'B', text: 'The consistent deviations from rational-choice theory documented by behavioral economists may reflect adaptive heuristics rather than simple cognitive failures, and the "failure" framing itself rests on a contestable theoretical assumption.' },
      { label: 'C', text: 'Loss aversion and hyperbolic discounting are the most important discoveries of twentieth-century economics.' },
      { label: 'D', text: 'Nudge theory offers the most effective policy solution to the cognitive limitations identified by behavioral economists.' },
    ],
    correctAnswer: 'B',
    explanation: `Choice B is correct. The passage describes behavioral economics' empirical findings (systematic deviations), then explains how these were initially framed as failures calling for nudges, and then introduces critics who question whether the failure framing is warranted — since rational-choice theory's description of rationality is itself debatable and the deviations may be adaptive. Choice B synthesizes both the finding and the meta-critique, which is the passage's full argument.`,
    wrongAnswerExplanations: {
      A: `Choice A is incorrect. The passage explicitly challenges the "fundamental irrationality" framing in its final sentences, presenting critics who argue that apparent deviations may reflect adaptive heuristics rather than failures, so the passage does not endorse this conclusion.`,
      C: `Choice C is incorrect. Loss aversion and hyperbolic discounting are cited as examples of the broader pattern the field studies, not asserted as the passage's most important claims. The passage's concern is with how these findings should be interpreted.`,
      D: `Choice D is incorrect. The passage mentions nudge theory as one implication drawn from the initial "failure" framing, but the passage does not evaluate or endorse nudge theory as the most effective policy solution.`,
    },
  },

  {
    id: 'rw2h-12',
    section: 'reading-writing',
    moduleId: 'rw-module-2-hard',
    domain: 'Information and Ideas',
    skill: 'Central Ideas and Details',
    difficulty: 'hard',
    stimulus: `The concept of "satisficing," introduced by the economist Herbert Simon, describes a decision-making strategy in which agents seek outcomes that are good enough rather than optimal. Simon argued that fully rational optimization — surveying all possible options and selecting the one that maximizes a given utility function — is computationally impossible for real human beings operating under conditions of incomplete information and cognitive limitations. Satisficing, by contrast, sets an aspiration level and adopts the first option that meets or exceeds it, a strategy that is both cognitively feasible and often nearly as effective as optimization in practical terms.`,
    question: `According to the passage, which of the following best explains why Simon considers satisficing more realistic than optimization?`,
    choices: [
      { label: 'A', text: 'Satisficing always produces better outcomes than optimization in competitive markets.' },
      { label: 'B', text: 'Optimization strategies have been shown to produce outcomes that most people find morally objectionable.' },
      { label: 'C', text: 'Setting an aspiration level eliminates the need for any rational deliberation.' },
      { label: 'D', text: 'Human cognitive limitations and incomplete information make exhaustive optimization impractical.' },
    ],
    correctAnswer: 'D',
    explanation: `Choice D is correct. The passage states that "fully rational optimization...is computationally impossible for real human beings operating under conditions of incomplete information and cognitive limitations." This is the explicit reason Simon considers optimization unrealistic and satisficing a more practical alternative.`,
    wrongAnswerExplanations: {
      A: `Choice A is incorrect. The passage does not claim satisficing produces better outcomes than optimization; it says it is "often nearly as effective," implying optimization might still be superior if achievable.`,
      C: `Choice C is incorrect. Satisficing still involves rational deliberation — setting aspiration levels and evaluating options — it just does not require exhaustive comparison.`,
      B: `Choice B is incorrect. The passage makes no ethical argument about the moral acceptability of optimization outcomes.`,
    },
  },

  {
    id: 'rw2h-10',
    section: 'reading-writing',
    moduleId: 'rw-module-2-hard',
    domain: 'Information and Ideas',
    skill: 'Command of Evidence',
    difficulty: 'hard',
    stimulus: `A philosopher of science argues that scientific consensus can persist long after the preponderance of new evidence has shifted against it, because established paradigms shape which anomalies researchers notice and which they dismiss as noise. She draws on the following passages from a historical study of contested scientific transitions.`,
    question: `Which quotation from the study most directly supports the philosopher's argument?`,
    choices: [
      { label: 'A', text: '"In the decades before the acceptance of plate tectonics, geologists repeatedly catalogued the same puzzling distribution of fossil species across non-contiguous continents but classified these findings as curiosities rather than as evidence demanding a new theoretical framework."' },
      { label: 'B', text: '"The eventual acceptance of germ theory was hastened by technological improvements in microscopy that allowed researchers to visualize individual microorganisms with unprecedented clarity."' },
      { label: 'C', text: '"Paradigm shifts in science are typically preceded by periods of intense disagreement among specialists, during which rival camps compete for institutional funding and journal space."' },
      { label: 'D', text: '"The history of astronomy suggests that anomalous observations are often incorporated into existing models through small adjustments — such as the addition of epicycles — before a fundamentally new model is accepted."' },
    ],
    correctAnswer: 'A',
    explanation: `Choice A is correct. The philosopher's specific claim is that consensus persists because established paradigms determine which anomalies are noticed and which are dismissed as noise. Choice A directly supports this: geologists repeatedly catalogued anomalous fossil distributions but classified them as curiosities rather than paradigm-threatening evidence — the existing geological paradigm shaped how they interpreted the data, suppressing recognition of its significance. This is precisely the mechanism the philosopher describes.`,
    wrongAnswerExplanations: {
      B: `Choice B is incorrect. It attributes the shift to a technological improvement (better microscopes) rather than to paradigm-driven perception of evidence. It does not address how established consensus shapes the interpretation of anomalies.`,
      C: `Choice C is incorrect. It describes institutional competition during transitions but says nothing about how paradigms filter which evidence is taken seriously — the philosopher's specific claim about why consensus persists.`,
      D: `Choice D is incorrect. It describes how anomalies are accommodated within existing models through adjustments, which is related but focuses on model revision rather than on the paradigm's role in causing researchers to dismiss rather than notice evidence.`,
    },
  },

  {
    id: 'rw2h-14',
    section: 'reading-writing',
    moduleId: 'rw-module-2-hard',
    domain: 'Information and Ideas',
    skill: 'Command of Evidence',
    difficulty: 'hard',
    stimulus: `A historian is arguing that the construction of transcontinental railroads in the United States during the 1860s and 1870s did not primarily benefit the regions through which they passed but rather transferred wealth from those regions to the financial interests that controlled the railroad corporations. The historian wants to find a quotation from a secondary source that most directly supports this specific claim.`,
    question: `Which quotation from a historical study would most directly support the historian's argument?`,
    choices: [
      { label: 'A', text: '"The transcontinental railroads dramatically reduced freight costs and travel times, opening previously inaccessible markets to farmers and merchants across the interior West."' },
      { label: 'B', text: '"By manipulating construction contracts through affiliated holding companies, railroad promoters extracted inflated payments from their own corporations, concentrating profits at the top while leaving the railroads themselves — and the federal land grants that subsidized them — largely stripped of value for local communities."' },
      { label: 'C', text: '"The federal government granted railroad corporations approximately 170 million acres of public land between 1850 and 1872 as an incentive to extend lines into unsettled territory."' },
      { label: 'D', text: '"Labor on transcontinental construction projects was grueling and dangerous, with Chinese workers on the Central Pacific and Irish immigrants on the Union Pacific working under harsh conditions for low wages."' },
    ],
    correctAnswer: 'B',
    explanation: `Choice B is correct. The historian's specific claim is that railroad construction transferred wealth away from the regions through which lines passed and toward financial interests controlling the corporations. Choice B describes exactly this mechanism — promoters extracting inflated profits through holding companies, leaving the railroads stripped of value for local communities — making it the most direct support for the specific argument about wealth transfer toward financial controllers.`,
    wrongAnswerExplanations: {
      A: `Choice A is incorrect. This quotation argues that railroads benefited the regions they passed through by reducing freight costs and opening markets — the opposite of the historian's claim that regions were not primarily benefited.`,
      C: `Choice C is incorrect. This documents the scale of land grants but does not address whether the economic benefits of those grants ended up with the regions or with financial interests. It is relevant context but does not directly support the specific claim about wealth transfer.`,
      D: `Choice D is incorrect. This describes the exploitation of construction laborers, which is related to the broader critique of railroads but does not address the claim about wealth flowing from regions to financial controllers of the corporations.`,
    },
  },

  {
    id: 'rw2h-15',
    section: 'reading-writing',
    moduleId: 'rw-module-2-hard',
    domain: 'Information and Ideas',
    skill: 'Command of Evidence',
    difficulty: 'hard',
    stimulus: `A political scientist is arguing that voter turnout in national elections is positively correlated with the perceived closeness of the race. The table shows turnout rates for five national elections.`,
    graphData: {
      type: 'table',
      title: 'Margin of Victory and Voter Turnout',
      headers: ['Election', 'Margin of Victory (% points)', 'Voter Turnout (%)'],
      rows: [
        ['Election 1', '2', '74'],
        ['Election 2', '8', '64'],
        ['Election 3', '15', '55'],
        ['Election 4', '3', '72'],
        ['Election 5', '18', '51'],
      ],
    },
    question: `Which statement best uses the data in the table to support the political scientist's argument?`,
    choices: [
      { label: 'A', text: 'Elections with small margins of victory had the highest voter turnout, while elections with large margins had the lowest.' },
      { label: 'B', text: 'Election 1 had the smallest margin of victory of the five elections studied.' },
      { label: 'C', text: 'Voter turnout was above 70% in two of the five elections.' },
      { label: 'D', text: 'The largest margin of victory in the dataset was 18 percentage points.' },
    ],
    correctAnswer: 'A',
    explanation: `Choice A is correct. The table shows a clear inverse relationship between margin of victory and turnout: Elections 1 and 4, with margins of 2 and 3 points, had turnouts of 74% and 72%; Elections 3 and 5, with margins of 15 and 18 points, had turnouts of 55% and 51%. Stating this pattern directly supports the claim that closer races drive higher turnout.`,
    wrongAnswerExplanations: {
      B: `Choice B is incorrect. This is a true but isolated fact that does not describe the relationship between closeness and turnout.`,
      C: `Choice C is incorrect. This notes a threshold without connecting it to the margin of victory.`,
      D: `Choice D is incorrect. Reporting the maximum margin of victory as an isolated fact does not support a claim about a correlation between closeness and turnout.`,
    },
  },

  {
    id: 'rw2h-16',
    section: 'reading-writing',
    moduleId: 'rw-module-2-hard',
    domain: 'Information and Ideas',
    skill: 'Command of Evidence',
    difficulty: 'hard',
    stimulus: `A sociologist wants to challenge the claim that social mobility in the United States has declined significantly over the past fifty years. Which quotation would most directly support the sociologist's challenge?`,
    question: `Which quotation would most directly support a challenge to the claim that U.S. social mobility has declined significantly over the past fifty years?`,
    choices: [
      { label: 'A', text: '"The share of children who earn more than their parents has fallen from approximately 90% for children born in 1940 to around 50% for those born in 1980."' },
      { label: 'B', text: '"Income inequality in the United States, as measured by the Gini coefficient, has increased substantially since the 1970s."' },
      { label: 'C', text: '"When absolute mobility is adjusted for changes in cost of living and consumption patterns, children born in the 1980s appear to have maintained living standards comparable to or exceeding those of their parents."' },
      { label: 'D', text: '"Intergenerational earnings correlations in the United States are higher than in most other developed nations, suggesting less relative mobility."' },
    ],
    correctAnswer: 'C',
    explanation: `Choice C is correct. The sociologist wants to challenge the "significant decline" claim. This quotation provides an alternative measurement approach — adjusting for cost of living and consumption — that shows comparable or higher living standards, directly undermining the claim of a significant mobility decline.`,
    wrongAnswerExplanations: {
      A: `Choice A is incorrect. This quotation actually supports the claim that social mobility has declined, showing a drop from 90% to 50% in absolute mobility.`,
      B: `Choice B is incorrect. Rising income inequality is often cited as evidence that mobility has declined, not as a challenge to that claim.`,
      D: `Choice D is incorrect. This supports the idea that U.S. relative mobility is low compared to other countries, reinforcing rather than challenging the decline narrative.`,
    },
  },

  {
    id: 'rw2h-18',
    section: 'reading-writing',
    moduleId: 'rw-module-2-hard',
    domain: 'Information and Ideas',
    skill: 'Inferences',
    difficulty: 'hard',
    stimulus: `Ecological research on island biogeography has established two robust patterns. First, larger islands support more species than smaller ones of equivalent habitat type — a relationship described by the species-area curve. Second, islands closer to a continental source of colonizers maintain higher species diversity than more remote islands of the same size, because immigration rates are higher when the journey is shorter. These patterns suggest that species richness on any given island reflects a dynamic equilibrium between immigration and local extinction rather than a fixed carrying capacity. On very remote islands, however, researchers have observed that many resident species are found nowhere else on Earth, a phenomenon called endemism. The level of endemism tends to be highest precisely where overall species richness is lowest.`,
    question: `Based on the passage, what can most reasonably be inferred about why endemism tends to be highest on the most remote islands?`,
    choices: [
      { label: 'A', text: 'Remote islands have larger surface areas, providing more habitat niches for species to differentiate.' },
      { label: 'B', text: 'Because immigration is infrequent on remote islands, the species that do establish themselves face less competition from new arrivals and have more time to evolve distinctly in isolation.' },
      { label: 'C', text: 'Remote islands receive more rainfall, creating conditions favorable to unique evolutionary adaptations.' },
      { label: 'D', text: 'Endemism is highest on remote islands because those islands were once connected to the mainland and retain ancient lineages.' },
    ],
    correctAnswer: 'B',
    explanation: `Choice B is correct. The passage establishes that remote islands have lower immigration rates (because the journey from a continental source is longer) and lower overall species richness. If immigration is infrequent, the species that do reach and establish themselves are rarely joined by new colonizers of the same lineage. This prolonged isolation from genetic exchange and competitive immigration allows resident populations to evolve distinctly over time, producing endemic species. Combining the low-immigration point with the observation that endemism peaks where richness is lowest supports this inference.`,
    wrongAnswerExplanations: {
      A: `Choice A is incorrect. The passage states that larger islands have more species overall (the species-area curve), but it does not describe remote islands as particularly large. Endemism is highest where richness is lowest, which argues against an area-based explanation.`,
      C: `Choice C is incorrect. The passage makes no mention of rainfall or precipitation patterns as a factor in either species richness or endemism.`,
      D: `Choice D is incorrect. The passage does not describe remote islands as formerly connected to mainlands. The continental-connection hypothesis (vicariance) is a distinct explanation that is not introduced or supported by any information in the passage.`,
    },
  },

  {
    id: 'rw2h-19',
    section: 'reading-writing',
    moduleId: 'rw-module-2-hard',
    domain: 'Information and Ideas',
    skill: 'Inferences',
    difficulty: 'hard',
    stimulus: `In 1973, the psychologists David Rosenhan and his colleagues published a study in which mentally healthy individuals were admitted to psychiatric hospitals after feigning a single symptom. Once admitted, they behaved entirely normally, yet staff continued to interpret ordinary behaviors as signs of mental illness. A pseudopatient who took notes was recorded in clinical charts as displaying "writing behavior." The study found that genuine psychiatric patients, who recognized the pseudopatients as healthy outsiders, were far more accurate in their assessments than the professionals who diagnosed the pseudopatients.`,
    question: `Based on the passage, what can most reasonably be inferred about the professionals described in the Rosenhan study?`,
    choices: [
      { label: 'A', text: 'They were motivated primarily by financial incentives to keep patients hospitalized.' },
      { label: 'B', text: 'Their initial diagnostic labels shaped how they subsequently interpreted the pseudopatients\' behaviors.' },
      { label: 'C', text: 'They were more skilled than actual patients at recognizing who was genuinely ill.' },
      { label: 'D', text: 'Their errors resulted from insufficient training in psychiatric diagnostic criteria.' },
    ],
    correctAnswer: 'B',
    explanation: `Choice B is correct. The passage shows that after admitting the pseudopatients, professionals interpreted perfectly normal behaviors as symptoms of illness. This pattern — where the initial diagnosis ("this person is ill") colored all subsequent observation — strongly supports the inference that diagnostic labels biased how professionals interpreted what they saw.`,
    wrongAnswerExplanations: {
      A: `Choice A is incorrect. The passage does not mention financial incentives or economic motivations for the professionals' errors.`,
      C: `Choice C is incorrect. The passage explicitly states that actual patients outperformed professionals in recognizing the pseudopatients as healthy.`,
      D: `Choice D is incorrect. The passage does not attribute the errors to insufficient training; the explanation is more likely systematic perceptual bias from existing diagnoses.`,
    },
  },

  {
    id: 'rw2h-04',
    section: 'reading-writing',
    moduleId: 'rw-module-2-hard',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'hard',
    stimulus: `Restoring the faded frescoes required extraordinary patience and technical skill. Working with tiny brushes and magnifying lenses for months on end, ______. The results, unveiled to the public last spring, revealed colors that had been hidden for centuries.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'the damaged plaster gradually regained its original hues under the conservators\' care' },
      { label: 'B', text: 'the conservators gradually coaxed the original hues back from the damaged plaster' },
      { label: 'C', text: 'it was the damaged plaster that gradually regained its original hues' },
      { label: 'D', text: 'there were original hues that the damaged plaster gradually regained' },
    ],
    correctAnswer: 'B',
    explanation: `Choice B is correct. The introductory participial phrase "Working with tiny brushes and magnifying lenses for months on end" must be followed immediately by the noun it modifies — the people doing the working. Only "the conservators" can logically perform this action, so choice B places the correct subject right after the modifier and avoids a dangling modifier.`,
    wrongAnswerExplanations: {
      A: `Choice A is incorrect. It places "the damaged plaster" directly after the modifier, illogically implying that the plaster was working with brushes and lenses — a dangling modifier.`,
      C: `Choice C is incorrect. The construction "it was the damaged plaster" makes the plaster the apparent doer of the modifying action, so the modifier still dangles.`,
      D: `Choice D is incorrect. The "there were" construction leaves no logical subject to perform the action described in the introductory phrase, so the modifier remains dangling.`,
    },
  },

  {
    id: 'rw2h-05',
    section: 'reading-writing',
    moduleId: 'rw-module-2-hard',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'hard',
    stimulus: `Beneath the museum's grand staircase ______ the forgotten storerooms in which curators recently uncovered dozens of uncatalogued artifacts. The discovery has prompted a comprehensive review of the institution's entire holdings.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'lies' },
      { label: 'B', text: 'lie' },
      { label: 'C', text: 'has been' },
      { label: 'D', text: 'was' },
    ],
    correctAnswer: 'B',
    explanation: `Choice B is correct. The sentence uses inverted syntax, placing the verb before its subject. The true subject is the plural noun "the forgotten storerooms," not the singular "staircase" in the introductory prepositional phrase. Because the subject is plural, the plural verb "lie" is required.`,
    wrongAnswerExplanations: {
      A: `Choice A is incorrect. "Lies" is singular; it may seem to agree with the nearby "staircase," but that noun is part of a prepositional phrase and cannot be the subject.`,
      C: `Choice C is incorrect. "Has been" is singular and does not agree with the plural subject "storerooms."`,
      D: `Choice D is incorrect. "Was" is singular and fails to agree with the plural subject; the inverted word order makes the plural subject easy to overlook.`,
    },
  },

  {
    id: 'rw2h-27',
    section: 'reading-writing',
    moduleId: 'rw-module-2-hard',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'hard',
    stimulus: `The research team's findings, _______ initially met with considerable skepticism by peer reviewers, have since been replicated in six independent laboratories across three continents.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: 'which were' },
      { label: 'B', text: 'which was' },
      { label: 'C', text: 'that were' },
      { label: 'D', text: 'having been' },
    ],
    correctAnswer: 'A',
    explanation: `Choice A is correct. The relative clause modifies "findings," which is the plural noun. The relative pronoun "which" correctly introduces a nonrestrictive clause (set off by commas), and "were" agrees in number with the plural antecedent "findings."`,
    wrongAnswerExplanations: {
      B: `Choice B is incorrect. "Which was" uses a singular verb that does not agree with the plural noun "findings."`,
      C: `Choice C is incorrect. "That were" uses a restrictive relative pronoun, which requires no surrounding commas. Since the clause is set off by commas in the sentence, "which" (nonrestrictive) is required.`,
      D: `Choice D is incorrect. "Having been met with skepticism" is a participial phrase that could be grammatically placed here, but it changes the structure significantly and creates an awkward, run-on participial chain when the full sentence is read.`,
    },
  },

  {
    id: 'rw2h-25',
    section: 'reading-writing',
    moduleId: 'rw-module-2-hard',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'hard',
    stimulus: `The historian's argument rested on a single unpublished manuscript, a document that several archivists had examined but none had authenticated _______ the authentication process, which typically involves spectroscopic analysis of ink composition and paper fiber dating, had been bypassed entirely in the rush to publish.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: '; since' },
      { label: 'B', text: ', since' },
      { label: 'C', text: ': since' },
      { label: 'D', text: ' since' },
    ],
    correctAnswer: 'B',
    explanation: `Choice B is correct. The clause beginning with "since" is a subordinate adverbial clause explaining the reason none of the archivists had authenticated the document. Because "since" is a subordinating conjunction, it creates a dependent clause — not an independent clause — so a semicolon would be incorrect. A comma before a subordinate "since" clause is the conventional punctuation when the dependent clause follows and explains the main clause, especially when the dependent clause is long and the writer wants to signal the explanatory relationship clearly.`,
    wrongAnswerExplanations: {
      A: `Choice A is incorrect. A semicolon must join two independent clauses. The phrase beginning with "since" is a dependent subordinate clause, not an independent clause; placing a semicolon before it creates a grammatical error.`,
      C: `Choice C is incorrect. A colon introduces a list, explanation, or elaboration in the form of a noun phrase or independent clause. A dependent clause introduced by "since" is not the right grammatical unit to follow a colon.`,
      D: `Choice D is incorrect. Omitting the comma before the long dependent "since" clause, while not always incorrect in short sentences, creates an ambiguous and difficult-to-parse construction here, since the reader must navigate a long nonrestrictive appositive phrase before reaching the "since" clause. The comma clarifies where the main clause ends.`,
    },
  },

  {
    id: 'rw2h-13',
    section: 'reading-writing',
    moduleId: 'rw-module-2-hard',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'hard',
    stimulus: `Although astronomers had long theorized about planets orbiting distant stars, direct confirmation remained elusive until the 1990s, when improved instruments finally made detection possible. The breakthrough hinged on a single measurable clue ______ the tiny wobble that a planet's gravity induces in the motion of its host star.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: '; the' },
      { label: 'B', text: ': the' },
      { label: 'C', text: ', the tiny wobble; which is' },
      { label: 'D', text: ' the' },
    ],
    correctAnswer: 'B',
    explanation: `Choice B is correct. The words before the blank form a complete independent clause ending in "a single measurable clue," and what follows is a noun phrase that names and specifies that clue. A colon is the correct mark to introduce an explanatory or defining element after a complete clause.`,
    wrongAnswerExplanations: {
      A: `Choice A is incorrect. A semicolon must join two independent clauses, but "the tiny wobble that a planet's gravity induces in the motion of its host star" is a noun phrase, not an independent clause.`,
      C: `Choice C is incorrect. Inserting a semicolon before "which is" splits the sentence incorrectly and creates a fragment; a semicolon cannot precede the dependent relative clause "which is."`,
      D: `Choice D is incorrect. Omitting punctuation entirely runs the independent clause directly into the noun phrase, producing an unpunctuated, ungrammatical construction.`,
    },
  },

  {
    id: 'rw2h-17',
    section: 'reading-writing',
    moduleId: 'rw-module-2-hard',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'hard',
    stimulus: `The mathematician Emmy Noether developed a theorem linking symmetries in physical systems to conservation laws, a result that remains foundational to modern physics. Her most celebrated contribution ______ profoundly influenced the development of theoretical physics, is still taught in graduate courses nearly a century later.`,
    question: `Which choice completes the text so that it conforms to the conventions of Standard English?`,
    choices: [
      { label: 'A', text: ', which' },
      { label: 'B', text: ' which' },
      { label: 'C', text: ', that' },
      { label: 'D', text: ' that' },
    ],
    correctAnswer: 'A',
    explanation: `Choice A is correct. The clause "which profoundly influenced the development of theoretical physics" is a nonrestrictive relative clause: it adds extra information about "Her most celebrated contribution" without narrowing which contribution is meant. Nonrestrictive clauses are set off with a comma and introduced by "which." The matching comma after "physics" already closes the clause, so an opening comma before "which" is required.`,
    wrongAnswerExplanations: {
      B: `Choice B is incorrect. Omitting the comma before "which" leaves the nonrestrictive clause without its required opening comma, mismatching the comma that already closes the clause after "physics."`,
      C: `Choice C is incorrect. "That" introduces restrictive clauses and is not preceded by a comma; using "that" here conflicts with the nonrestrictive, comma-enclosed structure of the clause.`,
      D: `Choice D is incorrect. "That" cannot introduce a comma-set-off nonrestrictive clause, and without an opening comma the construction is inconsistent with the closing comma after "physics."`,
    },
  },

  {
    id: 'rw2h-20',
    section: 'reading-writing',
    moduleId: 'rw-module-2-hard',
    domain: 'Expression of Ideas',
    skill: 'Transitions',
    difficulty: 'hard',
    stimulus: `The architectural movement known as Brutalism achieved its greatest visibility in the 1960s and 1970s, when governments and universities commissioned massive concrete structures intended to project permanence, civic seriousness, and institutional confidence. Many of these buildings now face demolition, their raw facades having grown unpopular with the publics they were meant to impress. _______, a growing cohort of architects, historians, and preservation advocates argues that the most significant Brutalist structures deserve legal protection as works of artistic and historical importance.`,
    question: `Which choice completes the text with the most logical transition?`,
    choices: [
      { label: 'A', text: 'As a result' },
      { label: 'B', text: 'Likewise' },
      { label: 'C', text: 'That said' },
      { label: 'D', text: 'For instance' },
    ],
    correctAnswer: 'C',
    explanation: `Choice C is correct. The first two sentences establish that Brutalist buildings face demolition because the public has grown to dislike them. The third sentence introduces a contrasting countercurrent: preservation advocates argue the most significant ones should be protected. The relationship is concessive — acknowledging a prevailing tendency before introducing a complicating counterposition. "That said" precisely signals this kind of concessive pivot: it grants the preceding point while introducing a qualifying counter-view.`,
    wrongAnswerExplanations: {
      A: `Choice A is incorrect. "As a result" signals that the third sentence is a consequence of the demolition pressures described in the second sentence. But the emergence of a preservation movement is not a consequence of demolition pressure; it is a reaction against it, making causation the wrong logical relationship.`,
      B: `Choice B is incorrect. "Likewise" signals that the third sentence adds a parallel or similar point, but the preservation argument is opposed to the demolition trend rather than parallel to it.`,
      D: `Choice D is incorrect. "For instance" introduces a specific example illustrating the preceding claim. The third sentence is not an example of Brutalist buildings facing demolition; it is a counter-movement that complicates that trend.`,
    },
  },

  {
    id: 'rw2h-26',
    section: 'reading-writing',
    moduleId: 'rw-module-2-hard',
    domain: 'Expression of Ideas',
    skill: 'Transitions',
    difficulty: 'hard',
    stimulus: `Scholars of tragedy have long argued that the genre achieves its emotional power by making the protagonist's downfall feel both inevitable and unjust — that the audience must simultaneously accept the logic that brings the hero to ruin and resist the feeling that the punishment fits the transgression. _______, recent work in moral psychology has suggested that this tension maps onto a genuine feature of human ethical cognition: our tendency to hold people responsible for foreseeable consequences of their choices even when those consequences exceed what any reasonable agent could have anticipated.`,
    question: `Which choice completes the text with the most logical transition?`,
    choices: [
      { label: 'A', text: 'Nevertheless' },
      { label: 'B', text: 'Interestingly' },
      { label: 'C', text: 'In contrast' },
      { label: 'D', text: 'By the same token' },
    ],
    correctAnswer: 'B',
    explanation: `Choice B is correct. The first sentence presents a long-standing literary claim about tragedy. The second sentence introduces a new, surprising finding from an unrelated field — moral psychology — that happens to map onto and corroborate the literary claim. This convergence between aesthetics and cognitive science is noteworthy and somewhat unexpected, making "Interestingly" the right signal: it introduces a development the reader would find striking given what was just stated.`,
    wrongAnswerExplanations: {
      A: `Choice A is incorrect. "Nevertheless" signals a contrast or qualification of the preceding point, but the moral psychology research supports and illuminates the literary claim rather than contradicting or complicating it.`,
      C: `Choice C is incorrect. "In contrast" introduces an opposing or diverging idea, but the second sentence is consistent with and confirmatory of the first rather than opposed to it.`,
      D: `Choice D is incorrect. "By the same token" signals that the second sentence makes a parallel point using the same logic as the first, but the second sentence draws on a different field and framing — it is not simply restating the same argument in a parallel register.`,
    },
  },

  {
    id: 'rw2h-23',
    section: 'reading-writing',
    moduleId: 'rw-module-2-hard',
    domain: 'Expression of Ideas',
    skill: 'Transitions',
    difficulty: 'hard',
    stimulus: `Proponents of deliberative democracy argue that political legitimacy derives not from majority voting alone but from the quality of public reasoning that precedes it: decisions reached after inclusive, reasoned debate have a stronger claim to democratic authority than those reached by preference aggregation without deliberation. Critics concede that deliberation can refine and clarify political disagreements. _______, they contend, it rarely resolves the deep value conflicts that drive the most contentious political disputes — and may even sharpen disagreement by giving each side a more articulate vocabulary for defending its position.`,
    question: `Which choice completes the text with the most logical transition?`,
    choices: [
      { label: 'A', text: 'Consequently' },
      { label: 'B', text: 'In addition' },
      { label: 'C', text: 'For instance' },
      { label: 'D', text: 'Yet' },
    ],
    correctAnswer: 'D',
    explanation: `Choice D is correct. The sentence before the blank concedes a point in favor of deliberation (it can refine and clarify disagreements). The sentence after the blank introduces a contrasting limitation (deliberation rarely resolves deep value conflicts). The logical relationship is concession followed by counter-qualification — the critic grants a partial point and then pushes back on a stronger claim. "Yet" signals exactly this kind of concessive contrast, acknowledging what has just been granted while pivoting to the stronger objection.`,
    wrongAnswerExplanations: {
      A: `Choice A is incorrect. "Consequently" signals a causal result, implying that what follows is an outcome or logical consequence of what precedes it. But the critics are not saying that deliberation's ability to refine disagreements leads to failure to resolve them; they are making a separate, contrasting point.`,
      B: `Choice B is incorrect. "In addition" signals that the following point supplements or adds to the previous one. But the following clause is a limitation that qualifies the concession just made — it is a contrast, not an addition.`,
      C: `Choice C is incorrect. "For instance" introduces a specific example illustrating the preceding claim. The following sentence is not an example of deliberation refining disagreements; it is a contrasting objection about deliberation's limits.`,
    },
  },

  {
    id: 'rw2h-24',
    section: 'reading-writing',
    moduleId: 'rw-module-2-hard',
    domain: 'Expression of Ideas',
    skill: 'Transitions',
    difficulty: 'hard',
    stimulus: `Scholars in the tradition of cultural psychology have argued that cognitive processes previously assumed to be universal — such as analytic reasoning, categorization strategies, and attention patterns — vary systematically across cultures. _______, researchers have proposed that individuals raised in East Asian cultures tend to attend more holistically to contextual information, while those raised in Western cultures tend to focus more analytically on individual objects.`,
    question: `Which choice completes the text with the most logical transition?`,
    choices: [
      { label: 'A', text: 'Nevertheless' },
      { label: 'B', text: 'For instance' },
      { label: 'C', text: 'On the contrary' },
      { label: 'D', text: 'In conclusion' },
    ],
    correctAnswer: 'B',
    explanation: `Choice B is correct. The first sentence makes a general claim (cognitive processes vary across cultures). The second sentence provides a specific example of this variation (East Asian vs. Western attention patterns). "For instance" introduces an illustrative example of a preceding general claim.`,
    wrongAnswerExplanations: {
      A: `Choice A is incorrect. "Nevertheless" signals a contrast or qualification, but the second sentence supports and illustrates the first rather than contradicting it.`,
      C: `Choice C is incorrect. "On the contrary" introduces a direct contradiction of the previous statement, but the second sentence is consistent with and illustrative of the first.`,
      D: `Choice D is incorrect. "In conclusion" signals a summary at the end of an argument, which does not fit the mid-passage relationship between these two sentences.`,
    },
  },

  {
    id: 'rw2h-21',
    section: 'reading-writing',
    moduleId: 'rw-module-2-hard',
    domain: 'Expression of Ideas',
    skill: 'Rhetorical Synthesis',
    difficulty: 'hard',
    stimulus: `A student is writing an essay arguing that antibiotic resistance is primarily an economic problem, not merely a medical one, and has compiled the following notes:
• Antibiotics are frequently prescribed for viral infections against which they have no effect, partly because of patient pressure and partly because the time cost of testing to confirm a bacterial cause is borne by individual clinicians while the social cost of resistance is borne by the public.
• Pharmaceutical companies have little financial incentive to develop new antibiotics because antibiotics are used briefly and cured patients stop purchasing them, unlike treatments for chronic conditions.
• In livestock agriculture, antibiotics are routinely administered at sub-therapeutic doses to promote growth, accelerating the development of resistant strains in contexts where the profit motive is direct and the costs are externalized.
• Effective new antibiotic compounds do exist in laboratory settings but remain underdeveloped because the projected return on investment does not justify the cost of clinical trials.`,
    question: `The student wants to write a thesis sentence that argues resistance is primarily an economic problem by synthesizing the structural incentive failures described across the notes. Which choice most effectively accomplishes this goal?`,
    choices: [
      { label: 'A', text: 'Antibiotic resistance is worsening globally because patients pressure physicians to prescribe medications that are not medically appropriate.' },
      { label: 'B', text: 'Because the individual incentives of clinicians, pharmaceutical companies, and agricultural producers all encourage antibiotic overuse or underinvestment in new drugs while the resulting costs are borne collectively, resistance is fundamentally a problem of misaligned economic incentives rather than of medical ignorance.' },
      { label: 'C', text: 'Pharmaceutical companies should be required to invest in antibiotic research, and agricultural use of sub-therapeutic antibiotics should be regulated more strictly.' },
      { label: 'D', text: 'Laboratory compounds that could address resistance exist but remain underdeveloped, suggesting that the pipeline for new antibiotics is not as empty as critics claim.' },
    ],
    correctAnswer: 'B',
    explanation: `Choice B is correct. The student's specific goal is to synthesize the structural incentive failures across all four notes into a thesis that frames resistance as an economic problem. Choice B does exactly this: it identifies the common thread across clinicians (time cost externalized), pharmaceutical companies (low return on investment), and agricultural producers (profit motive with externalized costs), and explicitly frames the synthesis as "misaligned economic incentives" rather than medical ignorance. It is the only choice that draws on multiple notes to argue for the economic framing the student wants to establish.`,
    wrongAnswerExplanations: {
      A: `Choice A is incorrect. It draws on only the first note (patient pressure on clinicians) and identifies a single actor, missing the broader structural argument the student wants to make across all four notes. It also frames the problem as inappropriate prescribing rather than as a systemic economic incentive failure.`,
      C: `Choice C is incorrect. It proposes policy solutions (regulation and investment mandates) rather than advancing a thesis about what kind of problem resistance is. A thesis sentence should make an argument, not recommend policy actions.`,
      D: `Choice D is incorrect. It draws on only the fourth note and actually partially challenges the framing (suggesting the pipeline is not as empty as critics claim), which undermines rather than supports the student's argument.`,
    },
  },

  {
    id: 'rw2h-22',
    section: 'reading-writing',
    moduleId: 'rw-module-2-hard',
    domain: 'Expression of Ideas',
    skill: 'Rhetorical Synthesis',
    difficulty: 'hard',
    stimulus: `A student writing about the philosophy of science has taken the following notes:
• Karl Popper argued that a scientific theory is valid only if it makes predictions that could, in principle, be proven false by experiment.
• Thomas Kuhn argued that science does not progress through steady accumulation but through revolutionary "paradigm shifts" — abrupt reorganizations of the entire conceptual framework of a discipline.
• Paul Feyerabend argued that there is no single scientific method; successful science has employed a wide variety of procedures, and rigid adherence to any one method can impede discovery.
• All three thinkers wrote primarily in the mid-to-late twentieth century and responded directly to one another's work.`,
    question: `The student wants to write a sentence for a section arguing that philosophers of science in the twentieth century disagreed about what distinguishes genuine science from other forms of inquiry. Which choice most effectively uses the notes to accomplish this goal?`,
    choices: [
      { label: 'A', text: 'Popper, Kuhn, and Feyerabend all wrote in the mid-to-late twentieth century and engaged with each other\'s ideas.' },
      { label: 'B', text: 'Thomas Kuhn argued that science advances through paradigm shifts rather than steady accumulation of knowledge.' },
      { label: 'C', text: 'Twentieth-century philosophers including Popper, Kuhn, and Feyerabend offered competing accounts of what makes a discipline scientific, disagreeing on whether science requires falsifiability, proceeds by paradigm shifts, or even follows a consistent method at all.' },
      { label: 'D', text: 'Paul Feyerabend believed that any single scientific method could become an obstacle to discovery.' },
    ],
    correctAnswer: 'C',
    explanation: `Choice C is correct. The student wants to show that these thinkers disagreed about what distinguishes science. Only choice C captures all three philosophers, summarizes their distinct positions, and frames their disagreement — making it the most effective sentence for the stated purpose.`,
    wrongAnswerExplanations: {
      A: `Choice A is incorrect. It establishes historical context (they were contemporaries who engaged with each other) but does not convey any of their substantive disagreements.`,
      B: `Choice B is incorrect. It covers only Kuhn's view and does not introduce the diversity of competing positions.`,
      D: `Choice D is incorrect. It covers only Feyerabend's position and does not illustrate the broader disagreement among the three thinkers.`,
    },
  },
]
