import type { MathQuestion } from '../types'

export const f3MathModule2EasyQuestionsV2: MathQuestion[] = [
  // ── Algebra ×7 (q01–q07) ────────────────────────────────────────────────────

  {
    id: 'sat-f3-v2-math-m2e-q01',
    section: 'math',
    moduleId: 'f3v2-math-module-2-easy',
    domain: 'Algebra',
    skill: 'Linear equations in one variable',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'If 4x + 9 = 29, what is the value of x?',
    choices: [
      { label: 'A', text: '4' },
      { label: 'B', text: '5' },
      { label: 'C', text: '6' },
      { label: 'D', text: '7' },
    ],
    correctAnswer: 'B',
    explanation: 'Subtract 9 from both sides: 4x = 20. Divide by 4: x = 5.',
    wrongAnswerExplanations: {
      A: 'x = 4 gives 4(4) + 9 = 25 ≠ 29. Students who add 9 to 29 first (getting 38) and then divide by 4 (getting 9.5, which they round to an integer near the choices) may arrive near 4. Alternatively, students who set up 4x = 29 − 9 correctly but make an arithmetic error (computing 20 ÷ 4 = 4 instead of 5) arrive here.',
      C: 'x = 6 gives 4(6) + 9 = 33 ≠ 29. Students who add rather than subtract: 4x = 29 + 9 = 38 → x ≈ 9 (not 6) or who use a different equation — these paths don\'t cleanly produce 6. More likely, x = 6 is a trap for students who roughly estimate: "4 times something near 5 is close to 20, plus 9... maybe 6?"',
      D: 'x = 7 gives 4(7) + 9 = 37 ≠ 29. Students who misread 29 as 37, or who add 9 + 29 = 38 and then compute 38/4 ≈ 9, rounding down to 7 or 8, may land here. A quick check 4(7) + 9 = 37 confirms this is wrong.',
    },
  },

  {
    id: 'sat-f3-v2-math-m2e-q02',
    section: 'math',
    moduleId: 'f3v2-math-module-2-easy',
    domain: 'Algebra',
    skill: 'Linear equations in one variable',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'If 5x − 3 = 2(x + 6), what is the value of 3x?',
    choices: [
      { label: 'A', text: '5' },
      { label: 'B', text: '10' },
      { label: 'C', text: '15' },
      { label: 'D', text: '18' },
    ],
    correctAnswer: 'C',
    explanation: 'Distribute: 5x − 3 = 2x + 12 → 3x = 15.',
    wrongAnswerExplanations: {
      A: '5 is the value of x, not 3x. Students who correctly solve the equation (finding x = 5) but then answer the wrong question — reporting x instead of 3x — select this. The question asks for 3x, so the final step is 3 × 5 = 15. This error is about careful reading, not algebra.',
      B: '10 has no clean derivation. A student might compute 3x = 15 correctly but then divide by 1.5 instead of stopping: 15/1.5 = 10. Or students who forget to distribute the 2 in 2(x + 6) get 5x − 3 = 2x + 6 → 3x = 9 → x = 3 → 3x = 9 (not 10). The path to 10 requires a specific mid-process error.',
      D: '18 would require x = 6, which comes from incorrectly distributing the 2: students who write 2(x + 6) = 2x + 6 (forgetting to multiply 6 by 2) get 5x − 3 = 2x + 6 → 3x = 9 → x = 3 → 3x = 9. That\'s 9, not 18. Students who then multiply 3 × 6 = 18 (using the 6 from the equation) combine two errors.',
    },
  },

  {
    id: 'sat-f3-v2-math-m2e-q03',
    section: 'math',
    moduleId: 'f3v2-math-module-2-easy',
    domain: 'Algebra',
    skill: 'Linear functions',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'The linear function f satisfies f(2) = 7 and f(5) = 16. What is the value of f(0)?',
    choices: [
      { label: 'A', text: '0' },
      { label: 'B', text: '1' },
      { label: 'C', text: '2' },
      { label: 'D', text: '4' },
    ],
    correctAnswer: 'B',
    explanation: 'Slope = (16 − 7)/(5 − 2) = 9/3 = 3. Using f(2) = 7: 3(2) + b = 7 → b = 1. So f(0) = 1.',
    wrongAnswerExplanations: {
      A: 'f(0) = 0 would require b = 0, but 3(2) + 0 = 6 ≠ 7.',
      C: 'f(0) = 2 would require b = 2, but 3(2) + 2 = 8 ≠ 7.',
      D: 'f(0) = 4 would require b = 4, but 3(2) + 4 = 10 ≠ 7.',
    },
  },

  {
    id: 'sat-f3-v2-math-m2e-q04',
    section: 'math',
    moduleId: 'f3v2-math-module-2-easy',
    domain: 'Algebra',
    skill: 'Linear functions',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'A driver decreases speed uniformly from 60 mph to 30 mph over 15 minutes. Which equation models the speed v (in mph) after t minutes?',
    choices: [
      { label: 'A', text: 'v = 60 − t' },
      { label: 'B', text: 'v = 60 − 2t' },
      { label: 'C', text: 'v = 30 + 2t' },
      { label: 'D', text: 'v = 30t − 60' },
    ],
    correctAnswer: 'B',
    explanation: 'The rate of decrease = (60 − 30)/15 = 2 mph per minute, starting from 60. So v = 60 − 2t. Check: at t = 15, v = 60 − 30 = 30. ✓',
    wrongAnswerExplanations: {
      A: 'v = 60 − t decreases only 1 mph per minute, reaching 45 at t = 15, not 30.',
      C: 'v = 30 + 2t increases speed and starts at 30, not 60.',
      D: 'v = 30t − 60 is not a decreasing function and gives nonsensical speeds.',
    },
  },

  {
    id: 'sat-f3-v2-math-m2e-q05',
    section: 'math',
    moduleId: 'f3v2-math-module-2-easy',
    domain: 'Algebra',
    skill: 'Systems of two linear equations in two variables',
    difficulty: 'easy',
    type: 'grid_in',
    question: 'Amara has some $5 bills and some $10 bills. She has 10 bills in total and they are worth $80. How many $5 bills does she have?',
    correctAnswer: '4',
    acceptableAnswers: ['4'],
    explanation: 'Let f = number of $5 bills and t = number of $10 bills. f + t = 10 and 5f + 10t = 80. Substitute t = 10 − f: 5f + 10(10 − f) = 80 → 100 − 5f = 80 → f = 4.',
    scoringNotes: 'Only 4 is acceptable.',
  },

  {
    id: 'sat-f3-v2-math-m2e-q06',
    section: 'math',
    moduleId: 'f3v2-math-module-2-easy',
    domain: 'Algebra',
    skill: 'Linear inequalities in one or two variables',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'If −1 < 3 − 2x < 7, which of the following describes all values of x?',
    choices: [
      { label: 'A', text: '−2 < x < 2' },
      { label: 'B', text: '−2 ≤ x ≤ 2' },
      { label: 'C', text: 'x < 2' },
      { label: 'D', text: 'x > −2' },
    ],
    correctAnswer: 'A',
    explanation: 'From 3 − 2x > −1: −2x > −4 → x < 2. From 3 − 2x < 7: −2x < 4 → x > −2. Combined: −2 < x < 2.',
    wrongAnswerExplanations: {
      B: '−2 ≤ x ≤ 2 is the most tempting wrong answer because it has the correct values (−2 and 2) but the wrong type of inequality (closed instead of open). The original inequalities are strict (< not ≤), meaning −2 and 2 are not solutions: if x = −2, then 3 − 2(−2) = 7, which is not strictly less than 7. If x = 2, then 3 − 2(2) = −1, which is not strictly greater than −1. The endpoints are excluded.',
      C: 'x < 2 captures the upper bound correctly but misses the lower bound entirely. Students who perform one step — solving 3 − 2x < 7 → x > −2 — and then only record the other step (−2x > −4 → x < 2) as a combined answer make this error. A compound inequality requires both bounds simultaneously.',
      D: 'x > −2 captures the lower bound but misses the upper bound. Students who solve only 3 − 2x > −1 → −2x > −4 → x < 2 (and then mistakenly write x > −2 by forgetting to flip the sign when dividing by −2) make this error. Both bounds are needed, and the division by a negative number must flip each inequality.',
    },
  },

  {
    id: 'sat-f3-v2-math-m2e-q07',
    section: 'math',
    moduleId: 'f3v2-math-module-2-easy',
    domain: 'Algebra',
    skill: 'Linear equations in two variables',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Line m has a slope of 3/4 and passes through the point (8, 5). What is the y-intercept of line m?',
    choices: [
      { label: 'A', text: '−1' },
      { label: 'B', text: '0' },
      { label: 'C', text: '1' },
      { label: 'D', text: '3' },
    ],
    correctAnswer: 'A',
    explanation: 'Using point-slope form: y − 5 = (3/4)(x − 8) → y = (3/4)x − 6 + 5 → y = (3/4)x − 1. The y-intercept is −1.',
    wrongAnswerExplanations: {
      B: 'y-intercept 0 comes from students who compute (3/4)(8) = 6 and then set y = 6 when the actual y is 5, concluding that the y-intercept must be 0 (since y = mx would give 6). The error is computing (3/4)(8) = 6 and confusing 6 with 5, not noticing the discrepancy. Actually, y = (3/4)x at x = 8 gives 6 ≠ 5, so b = 5 − 6 = −1, not 0.',
      C: 'y-intercept 1 is the most tempting wrong answer. Students who compute y − 5 = (3/4)(x − 8) = (3/4)x − 6 but then rearrange incorrectly — writing y = (3/4)x − 6 + 5 = (3/4)x − 1 (correct) but misreading −1 as 1 due to a sign error — arrive here. A quick check: (3/4)(8) + 1 = 7 ≠ 5.',
      D: 'y-intercept 3 might come from students who skip the point-slope form entirely and guess a y-intercept from the numbers in the problem (3 from the numerator of the slope 3/4, or 3 as a "round" number close to some calculation). Verification: (3/4)(8) + 3 = 6 + 3 = 9 ≠ 5.',
    },
  },

  // ── Advanced Math ×6 (q08–q13) ──────────────────────────────────────────────

  {
    id: 'sat-f3-v2-math-m2e-q08',
    section: 'math',
    moduleId: 'f3v2-math-module-2-easy',
    domain: 'Advanced Math',
    skill: 'Equivalent expressions',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Which expression is equivalent to (x + 3)(x − 3) + 2x(x + 1)?',
    choices: [
      { label: 'A', text: '3x² + 2x − 9' },
      { label: 'B', text: 'x² + 2x − 9' },
      { label: 'C', text: '3x² + 2x + 9' },
      { label: 'D', text: '3x² − 2x − 9' },
    ],
    correctAnswer: 'A',
    explanation: '(x + 3)(x − 3) = x² − 9 and 2x(x + 1) = 2x² + 2x. Adding: (x² − 9) + (2x² + 2x) = 3x² + 2x − 9.',
    wrongAnswerExplanations: {
      B: 'x² + 2x − 9 forgets the 2x² term from 2x(x + 1).',
      C: '3x² + 2x + 9 has the wrong constant sign; (x + 3)(x − 3) = x² − 9, not x² + 9.',
      D: '3x² − 2x − 9 has the wrong sign on the linear term; 2x(x + 1) contributes +2x.',
    },
  },

  {
    id: 'sat-f3-v2-math-m2e-q09',
    section: 'math',
    moduleId: 'f3v2-math-module-2-easy',
    domain: 'Advanced Math',
    skill: 'Quadratic functions',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'The function p(x) = x² − 5x + 6. What are the zeros of p(x)?',
    choices: [
      { label: 'A', text: 'x = 1 and x = 6' },
      { label: 'B', text: 'x = 5 and x = 1' },
      { label: 'C', text: 'x = −2 and x = −3' },
      { label: 'D', text: 'x = 2 and x = 3' },
    ],
    correctAnswer: 'D',
    explanation: 'Factor: x² − 5x + 6 = (x − 2)(x − 3). Setting each factor to zero: x = 2 and x = 3.',
    wrongAnswerExplanations: {
      A: 'x = 1 and x = 6 comes from noticing that 1 × 6 = 6 (matching the constant) and then using these as roots. However, 1 + 6 = 7, not 5, so these roots give (x − 1)(x − 6) = x² − 7x + 6, which doesn\'t match. The correct pair must satisfy both r + s = 5 AND r × s = 6, giving r = 2 and s = 3.',
      C: '(x + 2)(x + 3) = x² + 5x + 6 has the correct factor magnitudes (2 and 3) but the wrong signs. A quadratic with a negative middle term (−5x) and positive constant (+6) requires both factors to be negative: (x − 2)(x − 3). Students who forget to carry the negative signs into the roots select this — they correctly identify 2 and 3 but then choose positive roots.',
      B: '(x − 5)(x − 1) = x² − 6x + 5 has neither the correct sum (5 + 1 = 6, not 5) nor the correct product (5 × 1 = 5, not 6). Students who find numbers that are close (5 appears as the middle coefficient) or who confuse which coefficient determines the sum versus the product select this answer.',
    },
  },

  {
    id: 'sat-f3-v2-math-m2e-q10',
    section: 'math',
    moduleId: 'f3v2-math-module-2-easy',
    domain: 'Advanced Math',
    skill: 'Nonlinear equations in one variable',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'Which values of x satisfy x² − x − 12 = 0?',
    choices: [
      { label: 'A', text: 'x = 3 and x = −4' },
      { label: 'B', text: 'x = 4 and x = 3' },
      { label: 'C', text: 'x = 4 and x = −3' },
      { label: 'D', text: 'x = −4 and x = −3' },
    ],
    correctAnswer: 'C',
    explanation: 'Factor: x² − x − 12 = (x − 4)(x + 3). Setting each to zero: x = 4 and x = −3.',
    wrongAnswerExplanations: {
      A: 'x = 3 and x = −4 gives (x − 3)(x + 4) = x² + x − 12. This has the right magnitudes (3 and 4) and the right constant (−12) but the wrong sign on the middle term (+x instead of −x). Students who correctly identify 4 and 3 as the magnitudes but assign the negative to the smaller factor (3) instead of the larger one (4) make this error. For x² − x − 12, the positive root must be 4 (larger) and the negative root must be −3 (smaller).',
      B: 'x = 4 and x = 3 gives (x − 4)(x − 3) = x² − 7x + 12. Both factors are negative, which requires a positive constant term. Since x² − x − 12 has a negative constant (−12), one factor must be positive and one must be negative. Students who take 4 and 3 as both positive without checking the constant sign select this.',
      D: 'x = −4 and x = −3 gives (x + 4)(x + 3) = x² + 7x + 12. Both roots negative produces both a positive middle term and a positive constant — neither matches x² − x − 12. This is the fully reversed-sign case, where students negate both roots instead of only one.',
    },
  },

  {
    id: 'sat-f3-v2-math-m2e-q11',
    section: 'math',
    moduleId: 'f3v2-math-module-2-easy',
    domain: 'Advanced Math',
    skill: 'Equivalent expressions',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'Which of the following is equivalent to (x + 4)² − 16?',
    choices: [
      { label: 'A', text: 'x² + 8x' },
      { label: 'B', text: 'x² + 8x + 32' },
      { label: 'C', text: 'x² + 16' },
      { label: 'D', text: 'x² − 16' },
    ],
    correctAnswer: 'A',
    explanation: '(x + 4)² − 16 = x² + 8x + 16 − 16 = x² + 8x.',
    wrongAnswerExplanations: {
      B: 'This is (x+4)² = x² + 8x + 16, without subtracting 16.',
      C: 'x² + 16 is not the correct expansion of this expression.',
      D: 'x² − 16 = (x−4)(x+4), which is not the same as (x+4)² − 16.',
    },
  },

  {
    id: 'sat-f3-v2-math-m2e-q12',
    section: 'math',
    moduleId: 'f3v2-math-module-2-easy',
    domain: 'Advanced Math',
    skill: 'Quadratic functions',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'The function h(x) = −2(x − 1)² + 8. What are the coordinates of the vertex?',
    choices: [
      { label: 'A', text: '(−1, 8)' },
      { label: 'B', text: '(1, 8)' },
      { label: 'C', text: '(1, −8)' },
      { label: 'D', text: '(2, 8)' },
    ],
    correctAnswer: 'B',
    explanation: 'In vertex form h(x) = a(x − h)² + k, the vertex is at (h, k). Here a = −2, h = 1, k = 8, so the vertex is at (1, 8).',
    wrongAnswerExplanations: {
      A: '(−1, 8) results from misreading (x − 1)² as indicating x = −1. Students who read the vertex form as "the number in the parentheses with its sign attached" rather than "the value of x that makes the expression zero" make this error. In (x − h)², the vertex is at x = h (not x = −h). Since (x − 1)² = 0 when x = 1, the vertex is at x = 1, not x = −1.',
      C: '(1, −8) has the correct x-coordinate but a negated y-coordinate. Students who correctly find x = 1 and then substitute into h(x), perhaps mishandling the −2 coefficient, may compute: −2(0)² + 8 = 8 correctly, but then think the vertex k-value is −k = −8 because the parabola opens downward. However, k in vertex form is already the y-value of the vertex — it does not need to be negated.',
      D: '(2, 8) comes from reading "(x − 1)" as "x minus 1, so shift by 1 from x = 1, giving x = 2" — adding 1 to the x in the expression rather than solving (x − 1) = 0. The vertex occurs where the squared term equals zero: x − 1 = 0 → x = 1, not x = 2.',
    },
  },

  {
    id: 'sat-f3-v2-math-m2e-q13',
    section: 'math',
    moduleId: 'f3v2-math-module-2-easy',
    domain: 'Advanced Math',
    skill: 'Nonlinear functions',
    difficulty: 'hard',
    type: 'grid_in',
    question: 'If f(x) = 3x² − 2x + 1, what is the value of f(−2)?',
    correctAnswer: '17',
    acceptableAnswers: ['17'],
    explanation: 'f(−2) = 3(−2)² − 2(−2) + 1 = 3(4) + 4 + 1 = 12 + 4 + 1 = 17.',
    scoringNotes: 'Only 17 is acceptable.',
  },

  // ── Problem-Solving and Data Analysis ×5 (q14–q18) ─────────────────────────

  {
    id: 'sat-f3-v2-math-m2e-q14',
    section: 'math',
    moduleId: 'f3v2-math-module-2-easy',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'Ratios, rates, proportional relationships, and units',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'A pool contains 1,800 gallons of water. It drains at 40 gallons per minute and is simultaneously filled at 25 gallons per minute. How many minutes will it take to empty the pool?',
    choices: [
      { label: 'A', text: '45' },
      { label: 'B', text: '72' },
      { label: 'C', text: '90' },
      { label: 'D', text: '120' },
    ],
    correctAnswer: 'D',
    explanation: 'The net drain rate = 40 − 25 = 15 gallons per minute. Time = 1,800 / 15 = 120 minutes.',
    wrongAnswerExplanations: {
      A: '45 = 1800/40 uses only the drain rate and ignores the fill rate entirely. Students who set up time = total volume ÷ drain rate without accounting for the simultaneous filling make this error. Since the pool is being refilled at 25 gal/min while draining, the net rate is only 40 − 25 = 15 gal/min — making the correct time much longer than 45 minutes.',
      B: '72 = 1800/25 uses only the fill rate, which makes no sense physically (dividing volume by the fill rate would give the time to fill the pool, not empty it). Students who confuse fill and drain rates, or who accidentally use the wrong number, arrive here.',
      C: '90 might come from computing 1800/(40 − 25 + 5) = 1800/20 = 90 — using a net rate of 20 instead of 15. This error could arise from adding or subtracting the rates incorrectly, or from combining 40 and 25 as 40/25 × something. The correct net drain rate is 40 − 25 = 15 gal/min.',
    },
  },

  {
    id: 'sat-f3-v2-math-m2e-q15',
    section: 'math',
    moduleId: 'f3v2-math-module-2-easy',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'Percentages',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'A store prices items at 60% above wholesale cost. During a clearance sale, the retail price is reduced by 25%. The clearance sale price is what percent of the original wholesale cost?',
    choices: [
      { label: 'A', text: '80%' },
      { label: 'B', text: '100%' },
      { label: 'C', text: '120%' },
      { label: 'D', text: '135%' },
    ],
    correctAnswer: 'C',
    explanation: 'Let wholesale = 100. Retail = 100 × 1.60 = 160. Clearance = 160 × 0.75 = 120. So the clearance price is 120% of the wholesale cost.',
    wrongAnswerExplanations: {
      A: '80% subtracts the percentages incorrectly instead of applying them multiplicatively.',
      B: '100% assumes the two changes cancel, but the discount applies to the marked-up price of 160, not 100.',
      D: '135% ignores the 25% discount.',
    },
  },

  {
    id: 'sat-f3-v2-math-m2e-q16',
    section: 'math',
    moduleId: 'f3v2-math-module-2-easy',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'One-variable data: distributions and measures of center and spread',
    difficulty: 'medium',
    type: 'grid_in',
    question: 'The ages (in years) of 6 employees at a company are: 24, 31, 37, 42, 47, and 55. What is the median age?',
    correctAnswer: '39.5',
    acceptableAnswers: ['39.5', '79/2'],
    explanation: 'With an even number of values, the median is the average of the two middle values. The data in order: 24, 31, 37, 42, 47, 55. The two middle values are 37 and 42. Median = (37 + 42)/2 = 39.5.',
    scoringNotes: 'Accept 39.5 or 79/2.',
  },

  {
    id: 'sat-f3-v2-math-m2e-q17',
    section: 'math',
    moduleId: 'f3v2-math-module-2-easy',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'Probability and conditional probability',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'In a class of 30 students, 18 passed the quiz and 12 failed. Of those who passed, 10 completed all homework; of those who failed, 2 completed all homework. What is the probability that a randomly selected student who completed all homework passed the quiz?',
    choices: [
      { label: 'A', text: '1/3' },
      { label: 'B', text: '5/9' },
      { label: 'C', text: '5/6' },
      { label: 'D', text: '9/10' },
    ],
    correctAnswer: 'C',
    explanation: 'Total students who completed all homework = 10 + 2 = 12. Of these, 10 passed. P(passed | completed HW) = 10/12 = 5/6.',
    wrongAnswerExplanations: {
      A: '1/3 does not match 10/12.',
      B: '5/9 would use a homework total of 18, not 12.',
      D: '9/10 inverts a different ratio; the correct fraction is 10/12 = 5/6.',
    },
  },

  {
    id: 'sat-f3-v2-math-m2e-q18',
    section: 'math',
    moduleId: 'f3v2-math-module-2-easy',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'Two-variable data: models and scatterplots',
    difficulty: 'hard',
    type: 'grid_in',
    question: 'A linear model for study time (hours) and exam score (points) is: Score = 12(hours) + 55. A student scored 97 on the exam. According to this model, how many hours did the student study?',
    correctAnswer: '3.5',
    acceptableAnswers: ['3.5', '7/2'],
    explanation: '97 = 12h + 55 → 12h = 42 → h = 42/12 = 3.5 hours.',
    scoringNotes: 'Accept 3.5 or 7/2.',
  },

  // ── Geometry and Trigonometry ×4 (q19–q22) ──────────────────────────────────

  {
    id: 'sat-f3-v2-math-m2e-q19',
    section: 'math',
    moduleId: 'f3v2-math-module-2-easy',
    domain: 'Geometry and Trigonometry',
    skill: 'Lines, angles, and triangles',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'In triangle ABC, angle A is twice angle B, and angle C = 60°. What is the measure of angle B in degrees?',
    choices: [
      { label: 'A', text: '30°' },
      { label: 'B', text: '40°' },
      { label: 'C', text: '45°' },
      { label: 'D', text: '60°' },
    ],
    correctAnswer: 'B',
    explanation: 'Let angle B = x, so angle A = 2x. The angles sum to 180°: 2x + x + 60 = 180 → 3x = 120 → x = 40.',
    wrongAnswerExplanations: {
      A: 'x = 30 gives angles 60 + 30 + 60 = 150°, not 180°.',
      C: 'x = 45 gives 90 + 45 + 60 = 195°, not 180°.',
      D: 'x = 60 gives 120 + 60 + 60 = 240°, not 180°.',
    },
  },

  {
    id: 'sat-f3-v2-math-m2e-q20',
    section: 'math',
    moduleId: 'f3v2-math-module-2-easy',
    domain: 'Geometry and Trigonometry',
    skill: 'Right triangles and trigonometry',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'In right triangle RST, angle T = 90°. If sin(R) = 5/13, what is cos(R)?',
    choices: [
      { label: 'A', text: '5/12' },
      { label: 'B', text: '12/13' },
      { label: 'C', text: '13/12' },
      { label: 'D', text: '5/13' },
    ],
    correctAnswer: 'B',
    explanation: 'sin(R) = 5/13 means the opposite side = 5 and hypotenuse = 13. The adjacent side = √(13² − 5²) = √144 = 12. So cos(R) = 12/13.',
    wrongAnswerExplanations: {
      A: '5/12 = tan(R), not cos(R). Students who correctly identify the adjacent leg as 12 and the hypotenuse as 13 but then form the ratio opposite/adjacent (5/12) instead of adjacent/hypotenuse (12/13) confuse cosine with tangent. A memory aid: SOH CAH TOA — cos = Adjacent/Hypotenuse, tan = Opposite/Adjacent.',
      C: '13/12 exceeds 1, which is impossible for any cosine value (cosine is always between −1 and 1 for real angles). This comes from inverting cos(R) = 12/13 to get 13/12 — perhaps confusing secant (1/cos) with cosine. Any fraction with hypotenuse in the numerator cannot be a valid sine or cosine ratio.',
      D: '5/13 = sin(R), which is the ratio given in the problem, not the one asked for. This is the most tempting wrong answer for students who misread the question — it asks for cos(R), not sin(R) — or who assume the answer must be one of the ratios already mentioned. Students should note that sin(R) and cos(R) are complementary functions: sin(R) = cos(90° − R), and they use different sides.',
    },
  },

  {
    id: 'sat-f3-v2-math-m2e-q21',
    section: 'math',
    moduleId: 'f3v2-math-module-2-easy',
    domain: 'Geometry and Trigonometry',
    skill: 'Area and volume',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'A circle has a circumference of 20π. What is the area of the circle?',
    choices: [
      { label: 'A', text: '10π' },
      { label: 'B', text: '100π' },
      { label: 'C', text: '400π' },
      { label: 'D', text: '40π' },
    ],
    correctAnswer: 'B',
    explanation: 'Circumference = 2πr = 20π → r = 10. Area = πr² = π(10)² = 100π.',
    wrongAnswerExplanations: {
      A: '10π = π × r = π × 10 uses the radius directly instead of squaring it. Students who confuse the area formula A = πr² with the circumference formula C = 2πr, or who forget to square the radius, compute A = π × 10 = 10π. The squaring step is the most commonly forgotten step in area problems.',
      C: '400π = π(20)² comes from using the full circumference value (20π → 20) as if it were the radius. Students who skip the step of dividing 20π by 2π to find r, and instead use 20 as r directly, get A = π(20)² = 400π. The correct chain: C = 2πr → r = C/(2π) = 20π/(2π) = 10.',
      D: '40π is the product π × 40 = π × (10 + 30) or some other non-standard combination of numbers from the problem. One common route: students who compute r = 20π/π = 20 (forgetting the 2) and then use A = πr = π × 20 × 2 = 40π combine two errors. Another route: 2r = 20, so r = 10, and area = 2πr × 2 = 40π — confusing area with a doubled circumference.',
    },
  },

  {
    id: 'sat-f3-v2-math-m2e-q22',
    section: 'math',
    moduleId: 'f3v2-math-module-2-easy',
    domain: 'Geometry and Trigonometry',
    skill: 'Lines, angles, and triangles',
    difficulty: 'medium',
    type: 'grid_in',
    question: 'A right triangle has one leg of length 7 and a hypotenuse of length 25. What is the length of the other leg?',
    correctAnswer: '24',
    acceptableAnswers: ['24'],
    explanation: 'The other leg = √(25² − 7²) = √(625 − 49) = √576 = 24.',
    scoringNotes: 'Only 24 is acceptable.',
  },
]
