import type { RWQuestion } from '../types'

export const f2RwModule2EasyQuestionsV2: RWQuestion[] = [
  {
    id: 'sat-f2-v2-rw-m2e-q002',
    section: 'reading-writing',
    moduleId: 'f2v2-rw-module-2-easy',
    domain: 'Craft and Structure',
    skill: 'Words in Context',
    difficulty: 'easy',
    stimulus: 'The telegraph, once considered an indispensable tool for long-distance communication, is now entirely _______: modern digital networks transmit information faster, more cheaply, and more reliably than the telegraph ever could, leaving it with no practical role in contemporary society.',
    question: 'Which choice completes the text with the most logical and precise word or phrase?',
    choices: [
      { label: 'A', text: 'innovative' },
      { label: 'B', text: 'popular' },
      { label: 'C', text: 'obsolete' },
      { label: 'D', text: 'reliable' },
    ],
    correctAnswer: 'C',
    explanation: '"Obsolete" means no longer in use or no longer useful, which exactly describes a technology that has been superseded and has "no practical role in contemporary society."',
    wrongAnswerExplanations: {
      B: '"Popular" is a trap for students who focus on the first half of the sentence ("once considered indispensable") and interpret "indispensable" as equivalent to "popular." The passage is describing the telegraph\'s current status — a technology with no practical role — not its historical reputation. A technology can have been popular without currently being obsolete.',
      A: '"Innovative" is tempting because the passage mentions digital networks, which are innovative. Students who infer that the telegraph\'s contrast with innovative digital networks means the telegraph is the opposite of innovative might land here. However, the blank describes the telegraph itself, not digital networks, and "innovative" describes something new and groundbreaking, which the telegraph certainly is not today.',
      D: '"Reliable" is the most seductive wrong answer because the passage literally says digital networks transmit information "more reliably than the telegraph ever could." Students might read this as a hint that the telegraph is unreliable, suggesting "unreliable" as the intended word — and then select "reliable" as the best option in the list. But the passage doesn\'t say the telegraph is unreliable; it says it has no practical role, which is captured by "obsolete."',
    },
  },

  {
    id: 'sat-f2-v2-rw-m2e-q003',
    section: 'reading-writing',
    moduleId: 'f2v2-rw-module-2-easy',
    domain: 'Craft and Structure',
    skill: 'Words in Context',
    difficulty: 'easy',
    stimulus: 'The nonprofit\'s annual report was praised for being _______ about its finances: rather than hiding underperforming programs behind vague language, it published detailed budget breakdowns and openly acknowledged which initiatives had missed their targets.',
    question: 'Which choice completes the text with the most logical and precise word or phrase?',
    choices: [
      { label: 'A', text: 'transparent' },
      { label: 'B', text: 'frugal' },
      { label: 'C', text: 'defensive' },
      { label: 'D', text: 'selective' },
    ],
    correctAnswer: 'A',
    explanation: '"Transparent" means open, honest, and easy to understand — exactly what is described: publishing detailed budgets and acknowledging shortcomings rather than hiding them.',
    wrongAnswerExplanations: {
      B: '"Frugal" is tempting because the passage is explicitly about finances ("praised for being _______ about its finances") and frugal has a strongly financial connotation. Students who latch onto "finances" as the key word and seek a financial adjective may reach for "frugal." But frugal describes how carefully money is spent, not how openly financial information is communicated; the passage praises the report\'s honesty, not its budget management.',
      C: '"Defensive" is tempting because an organization publicly acknowledging that it "missed its targets" is doing the opposite of what a defensive organization would do — and a student might assume the passage is describing an unusual departure from defensiveness. However, "defensive" would directly contradict the passage\'s description: the report openly published breakdowns and acknowledged failures, which is the opposite of defensive.',
      D: '"Selective" is the most tempting wrong answer. The passage says the report published detailed budget breakdowns and "openly acknowledged which initiatives had missed their targets" — suggesting it selected only certain failures to highlight. Students who read this as strategic disclosure ("they chose which things to reveal") might think "selective" fits. But the passage contrasts this report favorably against vague reports that hide information; the purpose is to praise openness, not strategic selectivity.',
    },
  },

  {
    id: 'sat-f2-v2-rw-m2e-q004',
    section: 'reading-writing',
    moduleId: 'f2v2-rw-module-2-easy',
    domain: 'Craft and Structure',
    skill: 'Words in Context',
    difficulty: 'easy',
    stimulus: 'Large infrastructure projects such as bridges and highways require regular maintenance to _______ their structural integrity over time; without periodic inspections and repairs, even well-built structures will deteriorate and become unsafe.',
    question: 'Which choice completes the text with the most logical and precise word or phrase?',
    choices: [
      { label: 'A', text: 'challenge' },
      { label: 'B', text: 'establish' },
      { label: 'C', text: 'sustain' },
      { label: 'D', text: 'measure' },
    ],
    correctAnswer: 'C',
    explanation: '"Sustain" means to maintain or keep something going over time. Maintenance is performed specifically to sustain structural integrity — to keep structures safe through ongoing effort.',
    wrongAnswerExplanations: {
      B: '"Establish" is the most tempting wrong answer. The passage says maintenance is required "to _______ structural integrity" — and a reader might think: maintenance helps establish safety. However, "establish" means to create or set something up for the first time. The structures already have integrity that was built in; the purpose of maintenance is to keep that integrity going, not to create it anew. "Sustain" captures this ongoing preservation.',
      A: '"Challenge" is tempting because the passage does describe maintenance as testing structures through "periodic inspections" — and "challenge" can describe a testing process. However, a challenge implies contest or confrontation: engineers challenging the bridge to reveal its weaknesses. The passage frames maintenance as supportive of integrity, not as opposition to it.',
      D: '"Measure" is tempting because the passage specifically mentions "inspections," which do involve measuring or assessing structural integrity. Students who equate "inspect" with "measure" and then select "measure" as the blank are conflating one step of the maintenance process (assessment) with the overall goal (sustained integrity). Measuring integrity and maintaining it are different acts.',
    },
  },

  {
    id: 'sat-f2-v2-rw-m2e-q001',
    section: 'reading-writing',
    moduleId: 'f2v2-rw-module-2-easy',
    domain: 'Craft and Structure',
    skill: 'Words in Context',
    difficulty: 'easy',
    stimulus: 'Solar panels work best when they receive direct, unobstructed sunlight. Engineers designing rooftop installations must carefully assess potential shading from nearby trees or buildings, since even partial coverage can _______ the panels\' power output significantly.',
    question: 'Which choice completes the text with the most logical and precise word or phrase?',
    choices: [
      { label: 'A', text: 'reduce' },
      { label: 'B', text: 'enhance' },
      { label: 'C', text: 'stabilize' },
      { label: 'D', text: 'record' },
    ],
    correctAnswer: 'A',
    explanation: 'The context states that partial shading is a problem to assess and avoid, and the passage discusses ways it can negatively affect output. "Reduce" is the only choice that describes a decrease in power output, consistent with the negative consequence implied.',
    wrongAnswerExplanations: {
      B: '"Enhance" is the most clearly wrong choice — it means to improve, which is the opposite of the negative effect shading causes. However, students who skim the sentence and notice "solar panels" and "power output" without reading carefully for the shading context might choose it, thinking the question is asking what solar panels do with output. Context makes clear that the blank describes a problem, not a benefit.',
      C: '"Stabilize" is the most tempting wrong answer. Engineers designing rooftop installations must assess shading because it affects output — and "stabilize" sounds like something a good engineer would want to do (stabilize output). However, the sentence says shading can _______ output significantly, and shading doesn\'t stabilize output; it disrupts it. "Stabilize" implies making output constant and steady, while shading creates unpredictable variation.',
      D: '"Record" has no sensible meaning in this physical context: shading cannot record a power output. This choice can only be selected by students who are reading so rapidly that they pick a word without checking whether it fits the sentence physically. A quick test — "shading can record the panels\' power output" — reveals the absurdity immediately.',
    },
  },

  {
    id: 'sat-f2-v2-rw-m2e-q005',
    section: 'reading-writing',
    moduleId: 'f2v2-rw-module-2-easy',
    domain: 'Craft and Structure',
    skill: 'Text Structure and Purpose',
    difficulty: 'easy',
    stimulus: 'Honeybees communicate the location of food sources through a complex series of movements known as the "waggle dance." The direction of the dance indicates the direction of the food relative to the sun, while the duration of the waggle run signals the distance. Other bees in the hive observe these movements and use the information to fly directly to the food source, sometimes several kilometers away.',
    question: 'What is the main purpose of this passage?',
    choices: [
      { label: 'A', text: 'To compare honeybee communication with the communication methods of other social insects' },
      { label: 'B', text: 'To argue that honeybees are more intelligent than other insects' },
      { label: 'C', text: 'To describe threats to honeybee populations around the world' },
      { label: 'D', text: 'To explain how honeybees use movement to share location information with other members of their hive' },
    ],
    correctAnswer: 'D',
    explanation: 'The passage explains the waggle dance — what it is, how direction and duration convey information, and how other bees use it to find food. The purpose is to explain this communication system.',
    wrongAnswerExplanations: {
      B: 'The passage makes no comparisons between honeybee intelligence and that of other insects.',
      C: 'No threats to bee populations are mentioned; the passage is entirely about communication behavior.',
      A: 'No other insect species are mentioned or compared to honeybees.',
    },
  },

  {
    id: 'sat-f2-v2-rw-m2e-q006',
    section: 'reading-writing',
    moduleId: 'f2v2-rw-module-2-easy',
    domain: 'Craft and Structure',
    skill: 'Text Structure and Purpose',
    difficulty: 'easy',
    stimulus: 'The Grand Canyon was not carved quickly. It formed over approximately 5 to 6 million years as the Colorado River slowly eroded the surrounding rock layer by layer. The deepest parts of the canyon expose rocks that are nearly 2 billion years old, making the canyon walls a record of almost half of Earth\'s geologic history. What visitors see when they look down into the canyon is, in effect, a physical timeline of our planet.',
    underlineTargets: ['a physical timeline of our planet'],
    question: 'Which choice best describes the function of the underlined phrase in the passage?',
    choices: [
      { label: 'A', text: 'It provides a metaphor that summarizes the main point of the passage' },
      { label: 'B', text: 'It introduces a new claim that contradicts what the earlier sentences say' },
      { label: 'C', text: 'It gives a specific measurement that supports the earlier geological claims' },
      { label: 'D', text: 'It presents a counterexample that qualifies the passage\'s central argument' },
    ],
    correctAnswer: 'A',
    explanation: 'The phrase "a physical timeline of our planet" is a metaphor that crystallizes the passage\'s central point: that the canyon\'s rock layers record Earth\'s long geologic history. It functions as a summary image.',
    wrongAnswerExplanations: {
      B: 'The phrase is consistent with what came before, not contradictory.',
      C: 'The phrase offers a metaphor, not a specific measurement like a date or distance.',
      D: 'The phrase reinforces the passage\'s argument rather than qualifying or limiting it.',
    },
  },

  {
    id: 'sat-f2-v2-rw-m2e-q009',
    section: 'reading-writing',
    moduleId: 'f2v2-rw-module-2-easy',
    domain: 'Information and Ideas',
    skill: 'Central Ideas and Details',
    difficulty: 'medium',
    stimulus: 'Many animals migrate seasonally to take advantage of resources that vary by location and time of year. Monarch butterflies travel up to 3,000 miles from Canada and the United States to their wintering grounds in central Mexico. Arctic terns make the longest migration of any animal, flying from the Arctic to the Antarctic and back each year — a round trip of approximately 44,000 miles. These journeys, undertaken without maps or GPS, rely on internal compasses sensitive to Earth\'s magnetic field, the position of the sun, and even the pattern of stars.',
    question: 'According to the passage, what enables animals to navigate during migration?',
    choices: [
      { label: 'A', text: 'Memory of landmarks observed during previous migrations' },
      { label: 'B', text: 'Physical maps and GPS devices attached by researchers' },
      { label: 'C', text: 'Internal navigation systems responsive to magnetic fields, sunlight, and stars' },
      { label: 'D', text: 'Communication with other animals about the route' },
    ],
    correctAnswer: 'C',
    explanation: 'The passage explicitly states that migrations "rely on internal compasses sensitive to Earth\'s magnetic field, the position of the sun, and even the pattern of stars."',
    wrongAnswerExplanations: {
      A: '"Memory of landmarks" is tempting because landmarks are real navigational tools that humans use, and one might reasonably assume that birds crossing the same routes year after year would memorize key features. However, the passage makes no mention of landmark memory — it specifies internal compasses sensitive to magnetic fields, the sun, and stars. Students who reason from prior knowledge rather than from the passage fall into this trap.',
      B: '"Physical maps and GPS devices attached by researchers" is a trap for students who confuse the research context (scientists study these migrations) with the navigational mechanism. Researchers may track animals with GPS, but the passage explicitly says migrations happen "without maps or GPS." This is the most clearly wrong answer, but it tests whether students read carefully enough to catch that explicit denial.',
      D: '"Communication with other animals about the route" is tempting because many animals are social and coordinate behavior. In particular, readers who just read about monarch butterflies (which travel in groups at certain times) might assume communication is involved. However, the passage attributes navigation entirely to internal biological compasses — there is no mention of social communication as a navigational mechanism.',
    },
  },

  {
    id: 'sat-f2-v2-rw-m2e-q010',
    section: 'reading-writing',
    moduleId: 'f2v2-rw-module-2-easy',
    domain: 'Information and Ideas',
    skill: 'Central Ideas and Details',
    difficulty: 'medium',
    stimulus: 'Photosynthesis is the process by which plants, algae, and certain bacteria convert sunlight, water, and carbon dioxide into glucose and oxygen. Chlorophyll, the green pigment in plant cells, absorbs light energy and uses it to drive chemical reactions that build sugar molecules. The oxygen released during photosynthesis is a byproduct of these reactions and is the source of almost all the oxygen in Earth\'s atmosphere. Without photosynthesis, most life on Earth as we know it could not exist.',
    question: 'What is the central idea of this passage?',
    choices: [
      { label: 'A', text: 'Chlorophyll gives plants their green color and helps them absorb nutrients from soil' },
      { label: 'B', text: 'Photosynthesis is the process plants use to convert sunlight into food and is the primary source of atmospheric oxygen' },
      { label: 'C', text: 'Carbon dioxide is harmful to plant growth and must be converted into oxygen before plants can use it' },
      { label: 'D', text: 'Algae and bacteria photosynthesize more efficiently than plants do' },
    ],
    correctAnswer: 'B',
    explanation: 'The passage describes what photosynthesis is, how chlorophyll drives it, and its role in producing atmospheric oxygen. The central idea is that photosynthesis converts sunlight into food and produces the oxygen life depends on.',
    wrongAnswerExplanations: {
      A: 'Chlorophyll absorbs light energy, not soil nutrients — and the passage\'s focus is on photosynthesis overall, not just chlorophyll.',
      C: 'The passage does not say carbon dioxide is harmful; it is a raw material for photosynthesis.',
      D: 'No comparison of efficiency between algae, bacteria, and plants is made.',
    },
  },

  {
    id: 'sat-f2-v2-rw-m2e-q008',
    section: 'reading-writing',
    moduleId: 'f2v2-rw-module-2-easy',
    domain: 'Craft and Structure',
    skill: 'Cross-Text Connections',
    difficulty: 'medium',
    stimulus: 'Text 1: Some historians argue that the printing press was the single most important technological innovation of the fifteenth century. By making books affordable and reproducible, it broke the monopoly of religious institutions over written knowledge and helped spark the Protestant Reformation and the Scientific Revolution.\n\nText 2: While the printing press was significant, historians who focus narrowly on it risk undervaluing the role of trade networks in the spread of ideas. The same merchant ships that carried goods also carried manuscripts, travelers, and scholars. Ideas moved through ports and market towns long before the printing press made them cheaper to reproduce.',
    question: 'The author of Text 2 would most likely respond to Text 1\'s argument by saying that it',
    choices: [
      { label: 'A', text: 'correctly identifies the printing press as the era\'s most important innovation' },
      { label: 'B', text: 'overstates the printing press\'s significance by neglecting the importance of trade networks in spreading ideas' },
      { label: 'C', text: 'fails to recognize that books were already affordable before the printing press existed' },
      { label: 'D', text: 'incorrectly claims that religious institutions controlled written knowledge' },
    ],
    correctAnswer: 'B',
    explanation: 'Text 2 directly argues that historians who focus narrowly on the printing press "risk undervaluing the role of trade networks." This is a challenge to Text 1\'s single-cause emphasis.',
    wrongAnswerExplanations: {
      A: 'Text 2 explicitly disagrees with placing the printing press at the center of the story.',
      C: 'Text 2 says nothing about book affordability before the printing press.',
      D: 'Text 2 does not dispute the claim about religious institutions — it simply adds trade networks as another factor.',
    },
  },

  {
    id: 'sat-f2-v2-rw-m2e-q007',
    section: 'reading-writing',
    moduleId: 'f2v2-rw-module-2-easy',
    domain: 'Information and Ideas',
    skill: 'Command of Evidence',
    difficulty: 'easy',
    stimulus: 'A nutritionist argues that people tend to eat more food overall when meals are served in larger portions, regardless of how hungry they are before eating. She claims this "portion size effect" operates even when people are aware of it and believe they are regulating their intake consciously.',
    question: 'Which quotation from a study on eating behavior would most directly support the nutritionist\'s argument?',
    choices: [
      { label: 'A', text: '"Participants who were informed about the portion size manipulation and predicted they would not be affected nonetheless consumed an average of 23% more food when served the large-portion condition."' },
      { label: 'B', text: '"Among participants who reported being highly hungry before the meal, larger portions produced significantly greater caloric intake than among those who reported low hunger."' },
      { label: 'C', text: '"The study found that visual cues such as plate size and food presentation affected participants\' satisfaction ratings after eating, though total calories consumed did not differ significantly across conditions."' },
      { label: 'D', text: '"Participants who received nutritional training prior to the study showed reduced responsiveness to portion size compared with untrained participants, suggesting that education can partially offset the effect."' },
    ],
    correctAnswer: 'A',
    explanation: 'The nutritionist claims the portion size effect works even when people are aware of it and believe they are regulating their intake. Choice A directly supports this by showing that participants who knew about the manipulation and predicted they would not be affected still ate significantly more in the large-portion condition.',
    wrongAnswerExplanations: {
      B: 'Choice B is incorrect. It ties the effect to hunger level, implying the effect depends on a physiological state rather than operating independently of self-regulation, which does not directly support the nutritionist\'s specific claim.',
      C: 'Choice C is incorrect. It shows that portion size affects satisfaction but not actual calories consumed, which contradicts rather than supports the claim that people eat more with larger portions.',
      D: 'Choice D is incorrect. It suggests that awareness through education can reduce the effect, which complicates the claim that the effect persists even when people are aware of it.',
    },
  },

  {
    id: 'sat-f2-v2-rw-m2e-q011',
    section: 'reading-writing',
    moduleId: 'f2v2-rw-module-2-easy',
    domain: 'Information and Ideas',
    skill: 'Command of Evidence',
    difficulty: 'medium',
    stimulus: 'A marine ecologist studying coral reef health argues that water temperature is a stronger predictor of coral bleaching events than water acidity. She cites data showing that bleaching events occur almost exclusively when water temperatures exceed 29°C and that bleaching has occurred even in areas with relatively stable pH levels.',
    question: 'Which finding would most directly support the ecologist\'s argument?',
    choices: [
      { label: 'A', text: 'Reefs in cooler polar regions have experienced no bleaching despite having lower pH levels than tropical reefs' },
      { label: 'B', text: 'Water acidity has been shown to weaken coral skeletons, making bleaching more likely in acidic conditions' },
      { label: 'C', text: 'Some bleaching events have occurred in areas where temperatures never exceeded 28°C' },
      { label: 'D', text: 'Coral reefs have survived periods of high acidity throughout geological history' },
    ],
    correctAnswer: 'A',
    explanation: 'The ecologist argues temperature is a stronger predictor than acidity. Choice A supports this directly: cooler-water reefs haven\'t bleached even with low pH, showing that low temperature prevents bleaching regardless of acidity.',
    wrongAnswerExplanations: {
      B: 'This supports acidity as a cause, not temperature — it would weaken the ecologist\'s argument.',
      C: 'Bleaching occurring below 28°C would challenge the ecologist\'s temperature threshold, not support it.',
      D: 'Coral surviving past acidity is relevant to acidity but doesn\'t directly support the primacy of temperature as a predictor of bleaching.',
    },
  },

  {
    id: 'sat-f2-v2-rw-m2e-q012',
    section: 'reading-writing',
    moduleId: 'f2v2-rw-module-2-easy',
    domain: 'Information and Ideas',
    skill: 'Command of Evidence',
    difficulty: 'medium',
    stimulus: 'A school nutritionist claims that students who eat breakfast perform better on morning assessments than students who skip it. The nutritionist gathered data from 400 students over one semester:',
    graphData: {
      type: 'table',
      title: 'Breakfast Habits and Morning Test Scores',
      headers: ['Breakfast Habit', 'Average Morning Test Score'],
      rows: [
        ['Always eats breakfast', '84'],
        ['Sometimes eats breakfast', '78'],
        ['Never eats breakfast', '71'],
      ],
    },
    question: 'Which choice best describes how the data supports the nutritionist\'s claim?',
    choices: [
      { label: 'A', text: 'The data is inconclusive because the sample size of 400 students is too small to draw conclusions' },
      { label: 'B', text: 'The data supports the claim; students who always eat breakfast score higher than those who sometimes or never eat breakfast' },
      { label: 'C', text: 'The data partially supports the claim; eating breakfast improves scores for some students but not others' },
      { label: 'D', text: 'The data contradicts the claim; students who never eat breakfast score the highest' },
    ],
    correctAnswer: 'B',
    explanation: 'The table shows a clear pattern: always-breakfast students score 84, sometimes-breakfast students score 78, and never-breakfast students score 71. This progressive relationship directly supports the claim.',
    wrongAnswerExplanations: {
      A: 'The question asks whether the data supports the claim, not whether the study design is ideal — and 400 students is a substantial sample.',
      C: 'The data shows a consistent pattern for all groups, not a mixed result.',
      D: 'The data shows the opposite: never-breakfast students score lowest at 71.',
    },
  },

  {
    id: 'sat-f2-v2-rw-m2e-q013',
    section: 'reading-writing',
    moduleId: 'f2v2-rw-module-2-easy',
    domain: 'Information and Ideas',
    skill: 'Command of Evidence',
    difficulty: 'medium',
    stimulus: 'Historian Priya Mehta argues in her new book that industrialization in nineteenth-century Britain widened economic inequality, as factory owners accumulated unprecedented wealth while workers\' real wages stagnated for decades.',
    question: 'Which quotation from Mehta\'s book would best support the claim that real wages stagnated while factory owners grew wealthy?',
    choices: [
      { label: 'A', text: '"By 1850, Britain was producing more than half the world\'s iron and cotton cloth."' },
      { label: 'B', text: '"Between 1800 and 1860, the average income of textile mill owners increased by over 300%, while the average purchasing power of mill workers rose by less than 5%."' },
      { label: 'C', text: '"The Factory Acts of the 1830s and 1840s placed limits on working hours for women and children."' },
      { label: 'D', text: '"Many historians view the industrial revolution as a net positive for British society despite short-term disruptions."' },
    ],
    correctAnswer: 'B',
    explanation: 'The specific percentages directly compare owner income growth (300%+) with worker purchasing power growth (less than 5%), which is precisely the claim: factory owners got wealthy while workers\' real wages stagnated.',
    wrongAnswerExplanations: {
      A: 'This demonstrates industrial output but says nothing about the distribution of income between owners and workers.',
      C: 'Factory Acts describe labor regulations, not income or wealth trends.',
      D: 'This is a historian\'s general assessment, not evidence about the specific income divergence.',
    },
  },

  {
    id: 'sat-f2-v2-rw-m2e-q014',
    section: 'reading-writing',
    moduleId: 'f2v2-rw-module-2-easy',
    domain: 'Information and Ideas',
    skill: 'Inferences',
    difficulty: 'medium',
    stimulus: 'When the city of Pompeii was buried by the eruption of Mount Vesuvius in 79 CE, it was preserved almost exactly as it was on that day. Buildings, household objects, food still in ovens, and even the outlines of bodies were sealed under meters of volcanic ash. When excavations began in the eighteenth century, archaeologists found not just architecture but an entire snapshot of daily Roman life — shops, homes, gardens, and graffiti on walls.',
    question: 'What can be most reasonably inferred from the passage about Pompeii\'s value to archaeologists?',
    choices: [
      { label: 'A', text: 'Pompeii is the most important archaeological site in the world' },
      { label: 'B', text: 'The eruption of Vesuvius was beneficial because it destroyed objects that were not historically significant' },
      { label: 'C', text: 'Pompeii provides unusually detailed evidence of daily life in the Roman world because the volcanic burial preserved ordinary objects and spaces intact' },
      { label: 'D', text: 'Archaeologists have fully excavated Pompeii and have learned everything there is to know about Roman life' },
    ],
    correctAnswer: 'C',
    explanation: 'The passage describes how volcanic burial preserved buildings, food, household objects, and even graffiti — providing an intact snapshot of daily life. The reasonable inference is that this preservation makes Pompeii exceptionally valuable for understanding ordinary Roman existence.',
    wrongAnswerExplanations: {
      A: 'The passage does not compare Pompeii with other sites or make a superlative claim about its global importance.',
      B: 'The passage does not suggest the eruption was beneficial or that any objects were unimportant.',
      D: 'The passage mentions excavations beginning in the eighteenth century but makes no claim that the site is fully excavated.',
    },
  },

  {
    id: 'sat-f2-v2-rw-m2e-q015',
    section: 'reading-writing',
    moduleId: 'f2v2-rw-module-2-easy',
    domain: 'Information and Ideas',
    skill: 'Inferences',
    difficulty: 'medium',
    stimulus: 'In the early days of cinema, films were silent and theaters hired pianists or organists to play live music that matched the mood of each scene. When "talkies" — films with synchronized sound — became standard in the late 1920s, most of these musicians lost their jobs overnight. Theater owners, happy to reduce payroll, embraced the new technology enthusiastically.',
    question: 'What can be most reasonably inferred from the passage about theater owners\' motivation for adopting sound film?',
    choices: [
      { label: 'A', text: 'Theater owners believed that silent films were artistically inferior to sound films' },
      { label: 'B', text: 'Theater owners adopted sound film only after musicians agreed to accept lower wages' },
      { label: 'C', text: 'Theater owners were required by law to switch to sound film by 1930' },
      { label: 'D', text: 'Theater owners adopted sound film partly because it allowed them to eliminate the expense of hiring live musicians' },
    ],
    correctAnswer: 'D',
    explanation: 'The passage states that theater owners were "happy to reduce payroll" and "embraced the new technology enthusiastically," linking their enthusiasm directly to the cost savings from not employing musicians.',
    wrongAnswerExplanations: {
      A: 'The passage attributes theater owners\' enthusiasm to financial savings, not artistic judgment.',
      C: 'No legal requirement is mentioned in the passage.',
      B: 'The passage states musicians lost their jobs, not that they agreed to lower wages.',
    },
  },

  {
    id: 'sat-f2-v2-rw-m2e-q025',
    section: 'reading-writing',
    moduleId: 'f2v2-rw-module-2-easy',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'medium',
    stimulus: 'Neither the students nor their teacher _______ prepared for the fire drill that interrupted the chemistry lab.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choices: [
      { label: 'A', text: 'were' },
      { label: 'B', text: 'was' },
      { label: 'C', text: 'are' },
      { label: 'D', text: 'have been' },
    ],
    correctAnswer: 'B',
    explanation: 'In neither/nor constructions, the verb agrees with the subject closest to it — here, "their teacher" (singular). The correct verb is the singular "was."',
    wrongAnswerExplanations: {
      A: '"Were" is the most common wrong answer. The "neither...nor" construction joins "the students" (plural) with "their teacher" (singular), and students who see "students" first instinctively make the verb plural. The proximity rule for neither/nor requires the verb to agree with the subject immediately before it — here "their teacher," not "the students." This rule feels counterintuitive because "students" appears earlier and seems like the main topic.',
      C: '"Are" is plural present tense. Students who make both errors simultaneously — misidentifying the subject as plural ("students") and using present tense despite the past-tense context of "interrupted" — select this. The fire drill "interrupted" the chemistry lab, which anchors the sentence in past tense.',
      D: '"Have been" is present perfect (indicating an action that occurred and has relevance to the present) and also plural. The sentence describes a one-time event in the past ("the fire drill that interrupted"), so present perfect is wrong on tense, and "have" is wrong on number.',
    },
  },

  {
    id: 'sat-f2-v2-rw-m2e-q026',
    section: 'reading-writing',
    moduleId: 'f2v2-rw-module-2-easy',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'medium',
    stimulus: 'By the end of next year, the construction company _______ the new community center, which has been under development for three years.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choices: [
      { label: 'A', text: 'completed' },
      { label: 'B', text: 'has completed' },
      { label: 'C', text: 'will have completed' },
      { label: 'D', text: 'completes' },
    ],
    correctAnswer: 'C',
    explanation: '"By the end of next year" signals a future perfect construction — an action that will be completed before a specific future point. "Will have completed" correctly expresses this.',
    wrongAnswerExplanations: {
      B: '"Has completed" is present perfect — it describes an action recently finished with current relevance. The time marker "by the end of next year" signals a future deadline, not a present completion. "Has completed" would work only if the community center were already finished; since "next year" lies in the future, present perfect cannot be used here.',
      A: '"Completed" (simple past) is tempting for students who encounter the construction "By [time], [subject] completed [action]" and misread "by the end of next year" as setting a past context. Simple past requires the event to be already finished. "By the end of next year" specifies a future deadline before which the action will be complete — which requires future perfect.',
      D: '"Completes" (simple present) is the most seductive wrong answer for students who treat "by the end of next year" as if it establishes a habitual or general situation ("each year, it completes..."). But "the end of next year" is a specific future point in time, not a general present-tense condition. Simple present cannot express an action that has not yet occurred.',
    },
  },

  {
    id: 'sat-f2-v2-rw-m2e-q022',
    section: 'reading-writing',
    moduleId: 'f2v2-rw-module-2-easy',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'hard',
    stimulus: 'The tallest mountain in Africa. Mount Kilimanjaro rises 5,895 meters above sea level in Tanzania.',
    question: 'Which choice best corrects the sentence?',
    choices: [
      { label: 'A', text: 'The tallest mountain in Africa and Mount Kilimanjaro rises 5,895 meters above sea level in Tanzania.' },
      { label: 'B', text: 'The tallest mountain in Africa; Mount Kilimanjaro rises 5,895 meters above sea level in Tanzania.' },
      { label: 'C', text: 'The tallest mountain in Africa: Mount Kilimanjaro rises 5,895 meters above sea level in Tanzania.' },
      { label: 'D', text: 'The tallest mountain in Africa, Mount Kilimanjaro rises 5,895 meters above sea level in Tanzania.' },
    ],
    correctAnswer: 'D',
    explanation: 'The original creates a sentence fragment ("The tallest mountain in Africa.") by ending with a period before the subject has a verb. Choice D uses a comma to attach the phrase as an appositive modifier before the subject "Mount Kilimanjaro."',
    wrongAnswerExplanations: {
      B: 'A semicolon should only connect two independent clauses; "The tallest mountain in Africa" alone is not an independent clause.',
      C: 'A colon can introduce an explanation, but the construction here is slightly less standard than the appositive in D.',
      A: 'Adding "and" creates a grammatically confused structure where the introductory phrase becomes part of a compound subject, making the sentence nonsensical.',
    },
  },

  {
    id: 'sat-f2-v2-rw-m2e-q027',
    section: 'reading-writing',
    moduleId: 'f2v2-rw-module-2-easy',
    domain: 'Standard English Conventions',
    skill: 'Form, Structure, and Sense',
    difficulty: 'medium',
    stimulus: 'The board of directors voted to restructure the company\'s debt; _______ decision surprised analysts who had predicted a different outcome.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choices: [
      { label: 'A', text: 'their' },
      { label: 'B', text: 'its' },
      { label: 'C', text: 'this' },
      { label: 'D', text: 'these' },
    ],
    correctAnswer: 'C',
    explanation: '"This" correctly refers to the board\'s decision to restructure as a singular action. "This decision" refers back to the entire event described in the first clause.',
    wrongAnswerExplanations: {
      A: '"Their" is a plural possessive pronoun that would refer back to the board of directors as a group of individuals — while not completely wrong, "this" more precisely refers to the action (the decision) rather than to the people.',
      B: '"Its" would refer to a single non-human entity\'s possession; "the board\'s decision" could work, but "this" is more naturally used to refer to an action just described.',
      D: '"These" is plural and would need a plural noun to modify — "decision" is singular.',
    },
  },

  {
    id: 'sat-f2-v2-rw-m2e-q024',
    section: 'reading-writing',
    moduleId: 'f2v2-rw-module-2-easy',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'medium',
    stimulus: 'During the Renaissance, Italian artists like Leonardo da Vinci and Michelangelo Buonarroti experimented with new techniques, these innovations transformed European art for centuries.',
    question: 'Which choice best corrects the boundary error?',
    choices: [
      { label: 'A', text: 'During the Renaissance, Italian artists like Leonardo da Vinci and Michelangelo Buonarroti experimented with new techniques; these innovations transformed European art for centuries.' },
      { label: 'B', text: 'During the Renaissance, Italian artists like Leonardo da Vinci and Michelangelo Buonarroti experimented with new techniques, and these innovations transformed European art for centuries.' },
      { label: 'C', text: 'During the Renaissance Italian artists like Leonardo da Vinci and Michelangelo Buonarroti experimented with new techniques these innovations transformed European art for centuries.' },
      { label: 'D', text: 'During the Renaissance, Italian artists like Leonardo da Vinci and Michelangelo Buonarroti, experimenting with new techniques, these innovations transformed European art for centuries.' },
    ],
    correctAnswer: 'A',
    explanation: 'The original is a comma splice. Choice A uses a semicolon to correctly separate the two independent clauses.',
    wrongAnswerExplanations: {
      B: 'Choice B also corrects the comma splice correctly by adding the coordinating conjunction "and," but Choice A is the cleaner standard correction for this context.',
      C: 'Removing punctuation creates an even worse run-on sentence.',
      D: 'This version creates a dangling modifier — "experimenting with new techniques" becomes a participial phrase that fails to connect to a proper independent clause.',
    },
  },

  {
    id: 'sat-f2-v2-rw-m2e-q023',
    section: 'reading-writing',
    moduleId: 'f2v2-rw-module-2-easy',
    domain: 'Standard English Conventions',
    skill: 'Boundaries',
    difficulty: 'medium',
    stimulus: 'The first iPhone was released in 2007 _______ it changed the way people interact with technology and with each other.',
    question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
    choices: [
      { label: 'A', text: ', and' },
      { label: 'B', text: ',' },
      { label: 'C', text: ' and, that' },
      { label: 'D', text: '; and' },
    ],
    correctAnswer: 'A',
    explanation: 'Both parts of the sentence are independent clauses ("The first iPhone was released in 2007" and "it changed the way people interact..."). Two independent clauses can be joined with a comma followed by a coordinating conjunction. Choice A supplies exactly that: a comma plus "and."',
    wrongAnswerExplanations: {
      B: 'A comma alone cannot join two independent clauses — this creates a comma splice, the same error present in the original sentence.',
      C: '"and, that" is ungrammatical: the stray comma and the added "that" produce a garbled construction that does not join the clauses correctly.',
      D: 'A semicolon already joins two independent clauses on its own; adding "and" after it is redundant and nonstandard punctuation.',
    },
  },

  {
    id: 'sat-f2-v2-rw-m2e-q021',
    section: 'reading-writing',
    moduleId: 'f2v2-rw-module-2-easy',
    domain: 'Expression of Ideas',
    skill: 'Transitions',
    difficulty: 'hard',
    stimulus: 'Bamboo grows faster than almost any other plant on Earth, with some species gaining nearly a meter of height in a single day. _______ it has been used for centuries in construction, furniture-making, and textile production across Asia.',
    question: 'Which choice completes the text with the most logical transition?',
    choices: [
      { label: 'A', text: 'As a result,' },
      { label: 'B', text: 'In addition,' },
      { label: 'C', text: 'However,' },
      { label: 'D', text: 'For example,' },
    ],
    correctAnswer: 'B',
    explanation: 'The second sentence adds another noteworthy quality of bamboo — its long history of practical use — to the growth rate mentioned in the first. "In addition" correctly signals that the second sentence is supplementing the first with a related but distinct piece of information.',
    wrongAnswerExplanations: {
      A: '"As a result" is the most tempting wrong answer. Students may reason: "Bamboo grows incredibly fast → as a result, there is a large supply available → as a result, it has been used widely in construction." This is a plausible causal chain, but the passage does not establish it — it does not say abundance caused widespread use. The two sentences present independent noteworthy qualities of bamboo, not a cause-and-effect sequence.',
      C: '"However" is tempting for students who read the second sentence as surprising given the first — "Bamboo grows incredibly fast; however, it has also been used for centuries." But "however" requires an actual contradiction or tension. Being fast-growing and being historically useful for construction are not in conflict. Both are positive attributes; neither limits or complicates the other.',
      D: '"For example" is tempting because construction and textile uses could seem like examples of what fast-growing bamboo makes possible. However, "for example" requires the second sentence to be a specific instance of a general claim made in the first. The first sentence claims fast growth; construction uses are not examples of fast growth — they are applications that derive from a different quality (strength and availability), which the passage does not explicitly state.',
    },
  },

  {
    id: 'sat-f2-v2-rw-m2e-q019',
    section: 'reading-writing',
    moduleId: 'f2v2-rw-module-2-easy',
    domain: 'Expression of Ideas',
    skill: 'Transitions',
    difficulty: 'medium',
    stimulus: 'Exercise has well-documented benefits for physical health, reducing the risk of heart disease, diabetes, and obesity. _______ recent research suggests that regular physical activity also significantly improves mood, reduces anxiety, and may slow cognitive decline in older adults.',
    question: 'Which choice completes the text with the most logical transition?',
    choices: [
      { label: 'A', text: 'However,' },
      { label: 'B', text: 'Therefore,' },
      { label: 'C', text: 'In addition,' },
      { label: 'D', text: 'For example,' },
    ],
    correctAnswer: 'C',
    explanation: '"In addition" signals that the second sentence adds another set of benefits to those already mentioned. The transition correctly introduces mental and cognitive benefits as additional advantages beyond the physical ones.',
    wrongAnswerExplanations: {
      A: '"However" signals that the second sentence will introduce a contradiction or surprising qualification. A student might read the structure as: "Exercise is physically beneficial [first sentence]. However, it also affects the mind [second sentence]" — as if mental benefits are surprising or in tension with physical ones. But there is no tension here; both kinds of benefits are positive and compatible. "However" requires actual opposition, not just a shift in category.',
      B: '"Therefore" signals that the second sentence is a logical consequence of the first. A reader might think: "Exercise reduces heart disease risk → therefore it also improves mood." While this causal chain might be true in some biological sense, the passage does not present it as a logical deduction — the mental benefits are independently documented, not derived from the physical ones. "Therefore" would imply that reducing heart disease causes mood improvement, which the passage does not assert.',
      D: '"For example" requires the second sentence to illustrate a specific case of the general claim in the first. The first sentence makes a claim about physical health benefits; mood improvement and cognitive effects are not examples of physical health — they are a separate, distinct category of benefits. "For example" would only work if the second sentence said something like "...for example, by strengthening the heart and lowering blood pressure."',
    },
  },

  {
    id: 'sat-f2-v2-rw-m2e-q020',
    section: 'reading-writing',
    moduleId: 'f2v2-rw-module-2-easy',
    domain: 'Expression of Ideas',
    skill: 'Transitions',
    difficulty: 'hard',
    stimulus: 'The first successful powered airplane flight, made by the Wright brothers at Kitty Hawk in 1903, lasted only 12 seconds and covered 120 feet. _______ within 66 years, humans had landed on the moon.',
    question: 'Which choice completes the text with the most logical transition?',
    choices: [
      { label: 'A', text: 'Similarly,' },
      { label: 'B', text: 'Nevertheless,' },
      { label: 'C', text: 'In contrast,' },
      { label: 'D', text: 'Remarkably,' },
    ],
    correctAnswer: 'D',
    explanation: '"Remarkably" signals that what follows is surprising given what came before. The juxtaposition of a 12-second, 120-foot flight with a moon landing within 66 years is striking — "remarkably" captures this sense of astonishment at the speed of progress.',
    wrongAnswerExplanations: {
      A: '"Similarly" is tempting if a student reads both sentences as achievements in aviation/aerospace: "The Wright brothers flew [first achievement]; similarly, humans landed on the moon [second achievement]." But "similarly" requires the two events to be alike in kind and scale — and a 12-second flight covering 120 feet is not at all similar to a moon landing. The contrast in scale is precisely what makes the second sentence remarkable.',
      B: '"Nevertheless" is the most tempting wrong answer. Students who read the structure as "The Wright Brothers\' flight was tiny and modest [an implicit obstacle to progress]. Nevertheless, within 66 years, humans reached the moon" hear a classic concession-then-triumph structure. However, "nevertheless" specifically signals that the second sentence occurs despite the first — as if the modest beginning was a reason to doubt further progress. The passage does not frame the 12-second flight as an obstacle; it frames the contrast as astonishing, calling for "remarkably" rather than "nevertheless."',
      C: '"In contrast" requires the second sentence to present something directly opposed to the first. Students might think: "12-second humble beginning ↔ moon landing" is a contrast. But the moon landing doesn\'t oppose the Wright Brothers\' flight — it extends the same line of progress. "In contrast" would work if the second sentence described a setback or a shift in direction, not a continuation of the same trajectory at dramatically higher scale.',
    },
  },

  {
    id: 'sat-f2-v2-rw-m2e-q016',
    section: 'reading-writing',
    moduleId: 'f2v2-rw-module-2-easy',
    domain: 'Expression of Ideas',
    skill: 'Rhetorical Synthesis',
    difficulty: 'medium',
    stimulus: 'A student is writing a brief article about ocean plastic pollution. The student has gathered the following notes:\n\n• An estimated 8 million metric tons of plastic enter the ocean each year.\n• Plastic debris has been found in the deepest known ocean trench, the Mariana Trench, at approximately 11 km below sea level.\n• Seabirds and marine mammals frequently ingest plastic, mistaking it for food, which can cause starvation and internal injury.\n• Organizations in over 100 countries have organized beach cleanup events, collectively removing thousands of tons of plastic from coastlines annually.',
    question: 'The student wants to open the article with a sentence that conveys the seriousness of ocean plastic pollution. Which choice best accomplishes this goal?',
    choices: [
      { label: 'A', text: 'Beach cleanup volunteers in many countries work hard to remove plastic from coastlines each year.' },
      { label: 'B', text: 'Seabirds sometimes accidentally ingest plastic floating on the surface of the ocean.' },
      { label: 'C', text: 'Plastic has even been discovered at the bottom of the Mariana Trench, demonstrating that pollution has reached the most remote depths of the ocean.' },
      { label: 'D', text: 'Around 8 million metric tons of plastic pour into the ocean every year, threatening marine life from the surface to the ocean floor.' },
    ],
    correctAnswer: 'D',
    explanation: 'Choice D combines the scale of pollution (8 million metric tons per year) with the scope of its reach (surface to ocean floor), conveying the seriousness and breadth of the problem most effectively as an opening.',
    wrongAnswerExplanations: {
      A: 'This focuses on cleanup efforts — a positive response — rather than the seriousness of the problem itself.',
      B: 'This mentions one effect on one type of animal without conveying the scale of the crisis.',
      C: 'The Mariana Trench fact is striking but describes a single data point rather than the overall scope of the problem.',
    },
  },

  {
    id: 'sat-f2-v2-rw-m2e-q017',
    section: 'reading-writing',
    moduleId: 'f2v2-rw-module-2-easy',
    domain: 'Expression of Ideas',
    skill: 'Rhetorical Synthesis',
    difficulty: 'hard',
    stimulus: 'A student is preparing a presentation arguing that public libraries remain essential in the digital age. The student has gathered the following notes:\n\n• Over 1.3 billion people visit public libraries in the United States annually, more than attend Major League Baseball, NBA, and NFL games combined.\n• Libraries provide free internet access and computer terminals to people who cannot afford home connections.\n• Libraries offer free literacy programs, job-search assistance, and early childhood reading events.\n• Many library systems have expanded to lend items beyond books, including tools, seeds, and musical instruments.',
    question: 'The student wants to emphasize that libraries serve people with limited financial resources. Which choice best accomplishes this goal?',
    choices: [
      { label: 'A', text: 'Libraries now lend tools, seeds, and musical instruments in addition to books.' },
      { label: 'B', text: 'Libraries provide free internet access and digital resources to community members who cannot afford home connections, as well as free job-search and literacy programs.' },
      { label: 'C', text: 'More people visit public libraries each year than attend professional sports games.' },
      { label: 'D', text: 'Library attendance in the United States exceeds 1.3 billion visits annually.' },
    ],
    correctAnswer: 'B',
    explanation: 'The student wants to emphasize service to people with limited financial resources. Choice B focuses directly on free internet access for those who cannot afford it and free programs like job-search and literacy assistance — all explicitly tied to economic need.',
    wrongAnswerExplanations: {
      A: 'Expanded lending items speaks to innovation but doesn\'t focus on financial need.',
      C: 'The attendance comparison conveys popularity but says nothing about financial access.',
      D: 'Raw attendance numbers don\'t address who is served or why libraries matter to low-income users.',
    },
  },

  {
    id: 'sat-f2-v2-rw-m2e-q018',
    section: 'reading-writing',
    moduleId: 'f2v2-rw-module-2-easy',
    domain: 'Expression of Ideas',
    skill: 'Rhetorical Synthesis',
    difficulty: 'medium',
    stimulus: 'A student is writing an essay about the benefits of bilingual education. The student has gathered the following notes:\n\n• Students in bilingual programs score comparably to or higher than monolingual peers on standardized tests by the end of elementary school, after an initial adjustment period.\n• Research suggests that learning two languages strengthens executive function skills such as attention control and task-switching.\n• Bilingual individuals have been shown to develop dementia symptoms an average of 4 to 5 years later than monolingual individuals.\n• Critics of bilingual education argue that instruction in a second language slows early academic progress.',
    question: 'The student wants to address the critics\' concern while supporting bilingual education. Which choice best accomplishes this goal?',
    choices: [
      { label: 'A', text: 'The long-term cognitive benefits of bilingualism, including delayed dementia onset and stronger executive function, outweigh the short-term academic adjustments that critics point to.' },
      { label: 'B', text: 'Critics who oppose bilingual education are simply unfamiliar with the research showing its long-term benefits.' },
      { label: 'C', text: 'Bilingual education programs should be redesigned to eliminate the adjustment period that causes early academic difficulties.' },
      { label: 'D', text: 'Bilingual students score higher on standardized tests than monolingual students from the start of their schooling.' },
    ],
    correctAnswer: 'A',
    explanation: 'Choice A acknowledges the critics\' concern (short-term academic adjustments) while advancing the pro-bilingual argument by citing long-term benefits (delayed dementia, executive function). It concedes and rebuts simultaneously.',
    wrongAnswerExplanations: {
      B: 'This dismisses critics rather than engaging with their concern, which is not the same as addressing it.',
      C: 'This accepts the critics\' premise and focuses on fixing the problem, rather than arguing that the long-term benefits justify the short-term adjustment.',
      D: 'This contradicts the notes, which say bilingual students score comparably — not higher — initially, with parity achieved by end of elementary school.',
    },
  },
]
