import type { MathQuestion } from '../types'

// Math Module 2 Easy — 22 questions (~12 easy, ~10 medium, 0 hard)
// 17 multiple choice (q01–q17) + 5 grid-in (q18–q22)

export const mathModule2EasyQuestionsV2: MathQuestion[] = [
  {
    id: 'sat-f1-v2-math-m2e-q14',
    section: 'math',
    moduleId: 'f1v2-math-module-2-easy',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'Ratios, rates, proportional relationships, and units',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'A car travels 240 miles in 4 hours. At the same speed, how many miles will it travel in 7 hours?',
    choices: [
      { label: 'A', text: '380' },
      { label: 'B', text: '400' },
      { label: 'C', text: '420' },
      { label: 'D', text: '480' },
    ],
    correctAnswer: 'C',
    explanation: 'Speed = 240 ÷ 4 = 60 mph. Distance in 7 hours = 60 × 7 = 420 miles.',
    wrongAnswerExplanations: {
      A: '380 is a trap for students who compute 240 + (240/4) × (7 − 4) = 240 + 60 × 3 = 240 + 180 = 420 but make an arithmetic error adding: 240 + 140 = 380 (using 140 instead of 180). The path is right — find the unit rate and scale — but arithmetic slips produce this answer.',
      B: '400 is the most tempting wrong answer. Students who round 60 mph to "about 57 mph" and multiply 57 × 7 ≈ 400, or who incorrectly compute the unit rate as 240/6 = 40 mph and multiply 40 × 10 = 400, land here. A quick check: 60 × 7 = 420, not 400.',
      D: '480 = 240 × 2, which comes from noticing that 7 is "almost double" 4 and doubling 240. This is off because 7/4 = 1.75, not 2.0 — the correct approach is to multiply by the exact ratio 7/4, giving 240 × 7/4 = 420.',
    },
  },

  {
    id: 'sat-f1-v2-math-m2e-q12',
    section: 'math',
    moduleId: 'f1v2-math-module-2-easy',
    domain: 'Advanced Math',
    skill: 'Equivalent expressions',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Which of the following is equivalent to √75?',
    choices: [
      { label: 'A', text: '5√3' },
      { label: 'B', text: '3√5' },
      { label: 'C', text: '15√3' },
      { label: 'D', text: '25√3' },
    ],
    correctAnswer: 'A',
    explanation: '√75 = √(25 · 3) = √25 · √3 = 5√3.',
    wrongAnswerExplanations: {
      B: '3√5 results from trying to factor √75 as √9 × √(75/9). But 75 ÷ 9 = 8.33, which is not a perfect square, so this factoring doesn\'t produce a clean integer coefficient. Students who try to pull out √9 = 3 because 3 is "close" to a factor of 75 make this error — the correct perfect-square factor of 75 is 25, not 9.',
      C: '15√3 would require 75 = 225 × (1/3), but 225 > 75, so this is impossible. Students who confuse √225 = 15 with √25 = 5 might write 15√3 as if they factored out 225 from 75, which is not possible since the factor must be at most 75.',
      D: '25√3 results from correctly identifying that 25 is the largest perfect-square factor of 75 but writing 25 as the coefficient instead of √25 = 5. The rule is: √(a × b) = √a × √b → √25 × √3 = 5√3, not 25√3. This is the most common error on square-root simplification problems.',
    },
  },

  {
    id: 'sat-f1-v2-math-m2e-q02',
    section: 'math',
    moduleId: 'f1v2-math-module-2-easy',
    domain: 'Algebra',
    skill: 'Linear equations in one variable',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'A car rental company charges a flat fee of $45 plus $0.20 per mile driven. A customer has a budget of $105 for the rental. What is the maximum number of miles the customer can drive?',
    choices: [
      { label: 'A', text: '300' },
      { label: 'B', text: '250' },
      { label: 'C', text: '275' },
      { label: 'D', text: '350' },
    ],
    correctAnswer: 'A',
    explanation: 'Set up: 45 + 0.20m ≤ 105. Solve: 0.20m ≤ 60, so m ≤ 300. Maximum miles = 300.',
    wrongAnswerExplanations: {
      B: '250 is the most common wrong answer. Students who subtract the flat fee correctly ($105 − $45 = $60) but then divide by $0.20 incorrectly — perhaps computing 60/0.20 = 30 and then multiplying 30 × 10 = 300 but making an off-by-one error — or who divide $60 by $0.24 (confusing the rate) get approximately 250. Verification: 45 + 0.20(250) = $95, which is $10 under budget, so the customer can drive further.',
      C: '275 results from a slightly different route error: perhaps computing ($105 − $45) / $0.20 but treating the budget as $100 instead of $105 (a reading error), giving 55/0.20 = 275. Verification: 45 + 0.20(275) = $100, still under budget.',
      D: '350 is a tempting overestimate that results from dividing the total budget by the per-mile rate without subtracting the flat fee first: $105 / $0.30 = 350, or $105 / $0.20 = 525 and then misreading the problem. Either way, 350 miles would cost $115, exceeding the $105 budget.',
    },
  },

  {
    id: 'sat-f1-v2-math-m2e-q03',
    section: 'math',
    moduleId: 'f1v2-math-module-2-easy',
    domain: 'Algebra',
    skill: 'Systems of two linear equations in two variables',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'In the system of equations below, what is the value of 2x + y?\n3x + y = 19\nx = y + 1',
    choices: [
      { label: 'A', text: '14' },
      { label: 'B', text: '9' },
      { label: 'C', text: '11' },
      { label: 'D', text: '19' },
    ],
    correctAnswer: 'A',
    explanation: 'Substitute x = y + 1 into the first equation: 3(y + 1) + y = 19 → 4y + 3 = 19 → y = 4. Then x = 5. So 2x + y = 10 + 4 = 14.',
    wrongAnswerExplanations: {
      B: '9 = x + y = 5 + 4 — the question asks for 2x + y, not x + y.',
      C: '11 = 2(4) + 3 — uses y = 4 but substitutes the wrong expression for x.',
      D: '19 is the right-hand side of the first equation, not the value of 2x + y.',
    },
  },

  {
    id: 'sat-f1-v2-math-m2e-q04',
    section: 'math',
    moduleId: 'f1v2-math-module-2-easy',
    domain: 'Algebra',
    skill: 'Linear inequalities in one or two variables',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'Which of the following is equivalent to −1 ≤ 2x + 3 ≤ 9?',
    choices: [
      { label: 'A', text: '−2 ≤ x ≤ 3' },
      { label: 'B', text: '−4 ≤ x ≤ 6' },
      { label: 'C', text: '0 ≤ x ≤ 6' },
      { label: 'D', text: '−1 ≤ x ≤ 3' },
    ],
    correctAnswer: 'A',
    explanation: 'Subtract 3 from all three parts: −1 − 3 ≤ 2x ≤ 9 − 3 → −4 ≤ 2x ≤ 6. Divide by 2: −2 ≤ x ≤ 3.',
    wrongAnswerExplanations: {
      B: '−4 ≤ x ≤ 6 is the result after subtracting 3 from all parts (correctly getting −4 ≤ 2x ≤ 6) but forgetting the final step of dividing all parts by 2. This is the most common stopping-too-early error — the algebra is right up to the last operation.',
      C: '0 ≤ x ≤ 6 comes from subtracting 3 from only the right and center parts (9 − 3 = 6, 2x − 3 → treating this as 2x; dividing to get x ≤ 3) but treating the left side as −1 + 3 = 0 (adding 3 instead of subtracting). Students who misapply the operation asymmetrically land here.',
      D: '−1 ≤ x ≤ 3 is the most tempting wrong answer. It looks like the correct answer range but has the wrong lower bound. Students who subtract 3 from the right side (9 − 3 = 6, divide by 2 → 3) and divide the right bound correctly, but carry the original left bound (−1) without subtracting 3 (−1 − 3 = −4, divide by 2 → −2), produce this answer. The lower bound should be −2, not −1.',
    },
  },

  {
    id: 'sat-f1-v2-math-m2e-q05',
    section: 'math',
    moduleId: 'f1v2-math-module-2-easy',
    domain: 'Algebra',
    skill: 'Linear functions',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'Line k has a slope of −3 and passes through the point (0, 4). What is the equation of line k?',
    choices: [
      { label: 'A', text: 'y = 3x + 4' },
      { label: 'B', text: 'y = −3x − 4' },
      { label: 'C', text: 'y = −3x + 4' },
      { label: 'D', text: 'y = 4x − 3' },
    ],
    correctAnswer: 'C',
    explanation: 'The point (0, 4) is the y-intercept, so b = 4. With slope −3: y = −3x + 4.',
    wrongAnswerExplanations: {
      A: 'y = 3x + 4 uses the wrong sign for the slope. The problem states slope = −3, so the x-coefficient must be negative. Students who drop the negative sign — perhaps because they think of "slope = 3" as the magnitude — select this answer. A quick check: at x = 1, this line gives y = 7, but the correct line gives y = 1.',
      B: 'y = −3x − 4 has the correct slope (−3) but the wrong sign for the y-intercept. The point (0, 4) is given, meaning when x = 0, y = 4, so the y-intercept is +4. Students who misread (0, 4) as (0, −4) — perhaps confusing the coordinate pair — or who automatically negate both values select this answer.',
      D: 'y = 4x − 3 swaps the roles of slope and y-intercept, using 4 as the slope and −3 as the y-intercept. Students who read the problem quickly and assign the numbers in the wrong positions make this error. The number 4 belongs in the y-intercept position (from the point (0, 4)), and −3 is the slope.',
    },
  },

  {
    id: 'sat-f1-v2-math-m2e-q06',
    section: 'math',
    moduleId: 'f1v2-math-module-2-easy',
    domain: 'Algebra',
    skill: 'Linear functions',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'The equation P = 500 + 40t represents a town\'s population P after t years. What is the population when t = 10?',
    choices: [
      { label: 'A', text: '400' },
      { label: 'B', text: '540' },
      { label: 'C', text: '900' },
      { label: 'D', text: '4,500' },
    ],
    correctAnswer: 'C',
    explanation: 'P = 500 + 40(10) = 500 + 400 = 900.',
    wrongAnswerExplanations: {
      A: '400 is just 40 × 10 — the increase — without adding the initial population of 500.',
      B: '540 results from computing 500 + 40 = 540, treating t = 1 rather than t = 10.',
      D: '4,500 results from multiplying 500 × 10 − 500 instead of using the correct formula.',
    },
  },

  {
    id: 'sat-f1-v2-math-m2e-q07',
    section: 'math',
    moduleId: 'f1v2-math-module-2-easy',
    domain: 'Algebra',
    skill: 'Linear equations in one variable',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'If 5(2 − x) = 3x − 6, what is the value of x?',
    choices: [
      { label: 'A', text: '1' },
      { label: 'B', text: '2' },
      { label: 'C', text: '3' },
      { label: 'D', text: '4' },
    ],
    correctAnswer: 'B',
    explanation: 'Expand: 10 − 5x = 3x − 6. Add 5x: 10 = 8x − 6. Add 6: 16 = 8x. Divide: x = 2.',
    wrongAnswerExplanations: {
      A: 'Substituting x = 1: 5(1) = 5 and 3(1) − 6 = −3; 5 ≠ −3.',
      C: 'Substituting x = 3: 5(−1) = −5 and 3(3) − 6 = 3; −5 ≠ 3.',
      D: 'Substituting x = 4: 5(−2) = −10 and 3(4) − 6 = 6; −10 ≠ 6.',
    },
  },

  {
    id: 'sat-f1-v2-math-m2e-q15',
    section: 'math',
    moduleId: 'f1v2-math-module-2-easy',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'Percentages',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'A jacket costs a retailer $120. The retailer marks up the price by 50% and then offers a 30% discount on the marked-up price. What is the final selling price of the jacket?',
    choices: [
      { label: 'A', text: '$126' },
      { label: 'B', text: '$144' },
      { label: 'C', text: '$108' },
      { label: 'D', text: '$132' },
    ],
    correctAnswer: 'A',
    explanation: 'Marked-up price = $120 × 1.50 = $180. Final price after 30% discount = $180 × 0.70 = $126.',
    wrongAnswerExplanations: {
      B: '$144 is the most tempting wrong answer. Students reason: "50% markup then 30% discount = net 20% increase," computing $120 × 1.20 = $144. This is wrong because the 30% discount applies to the marked-up price ($180), not the original cost. 30% of $180 = $54, and $180 − $54 = $126 — not 20% of $120. Percentages that apply to different bases cannot be combined by simple subtraction.',
      C: '$108 comes from computing a net 10% discount on the original price: 50% up, 30% down → net 10% down? This is doubly wrong: first because the operations cannot be combined this way, and second because 30% discount on $180 is $54, not $12. Students who try to "shortcut" by combining percentages arrive here.',
      D: '$132 is the hardest wrong answer to explain — it may come from computing 50% markup ($60) and subtracting 30% of the original cost (30% × $120 = $36): $120 + $60 − $36 = $144... or applying the 30% discount to the original $120 ($36 off) and then marking up: $84 × 1.5 = $126. The key error in $132 is applying the discount to a base other than the marked-up price.',
    },
  },

  {
    id: 'sat-f1-v2-math-m2e-q16',
    section: 'math',
    moduleId: 'f1v2-math-module-2-easy',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'One-variable data: distributions and measures of center and spread',
    difficulty: 'medium',
    type: 'multiple_choice',
    stimulus: 'The ages of five students in a class are: 14, 16, 15, 17, and 13.',
    question: 'What is the mean age of the five students?',
    choices: [
      { label: 'A', text: '14' },
      { label: 'B', text: '15' },
      { label: 'C', text: '16' },
      { label: 'D', text: '17' },
    ],
    correctAnswer: 'B',
    explanation: 'Sum = 14 + 16 + 15 + 17 + 13 = 75. Mean = 75 ÷ 5 = 15.',
    wrongAnswerExplanations: {
      A: '14 is the second-smallest value, not the mean.',
      C: '16 is the second-largest value.',
      D: '17 is the maximum value, not the mean.',
    },
  },

  {
    id: 'sat-f1-v2-math-m2e-q19',
    section: 'math',
    moduleId: 'f1v2-math-module-2-easy',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'Probability',
    difficulty: 'medium',
    type: 'grid_in',
    question: 'A box contains 4 red balls and 6 blue balls. Two balls are drawn one at a time without replacement. What is the probability that the first ball drawn is red and the second ball drawn is blue? Enter your answer as a fraction.',
    correctAnswer: '4/15',
    acceptableAnswers: ['4/15'],
    explanation: 'P(first red) = 4/10. After removing one red ball, 9 balls remain (3 red, 6 blue). P(second blue | first red) = 6/9 = 2/3. P(first red and second blue) = (4/10)(6/9) = 24/90 = 4/15.',
    scoringNotes: '4/15 is the only acceptable answer.',
  },

  {
    id: 'sat-f1-v2-math-m2e-q08',
    section: 'math',
    moduleId: 'f1v2-math-module-2-easy',
    domain: 'Advanced Math',
    skill: 'Nonlinear equations in one variable',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'For what positive value of b does x² + bx + 25 = 0 have exactly one real solution?',
    choices: [
      { label: 'A', text: '5' },
      { label: 'B', text: '10' },
      { label: 'C', text: '20' },
      { label: 'D', text: '25' },
    ],
    correctAnswer: 'B',
    explanation: 'For exactly one real solution, the discriminant equals zero: b² − 4(1)(25) = 0 → b² = 100 → b = 10 (taking the positive value).\n\nDesmos method: Enter y = x² + bx + 25 and add a slider for b. Increase b from 0. When b = 10 the parabola just touches the x-axis at one point (tangent); for b < 10 there are no x-intercepts, and for b > 10 there are two.',
    wrongAnswerExplanations: {
      A: 'b = 5 is tempting because 5 is the square root of the constant term (√25 = 5), and students may remember that "for a perfect square trinomial the middle coefficient relates to the square root of the constant." But b = 5 gives discriminant = 25 − 100 = −75 < 0, meaning no real solutions at all. For exactly one solution, the discriminant must be zero, requiring b² = 4(25) = 100, so b = 10, not 5.',
      C: 'b = 20 appears because students who solve b² − 4ac = 0 and compute 4ac = 4(1)(25) = 100 might then take b = 100/5 = 20 instead of √100 = 10. Dividing by 5 instead of taking the square root is the arithmetic error. Verification: b = 20 gives discriminant = 400 − 100 = 300 > 0, yielding two real solutions, not one.',
      D: 'b = 25 equals the constant term c, not the solution to b² = 100. Students who confuse "b must equal c in this type of problem" or who add the numbers in the equation (1 + 25 = 26 ≈ 25) arrive here. Verification: b = 25 gives discriminant = 625 − 100 = 525 > 0, again two real solutions.',
    },
  },

  {
    id: 'sat-f1-v2-math-m2e-q09',
    section: 'math',
    moduleId: 'f1v2-math-module-2-easy',
    domain: 'Advanced Math',
    skill: 'Equivalent expressions',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'For x ≠ 2, which expression is equivalent to (x² − 4)/(x − 2)?',
    choices: [
      { label: 'A', text: 'x + 2' },
      { label: 'B', text: 'x − 2' },
      { label: 'C', text: 'x + 4' },
      { label: 'D', text: 'x' },
    ],
    correctAnswer: 'A',
    explanation: 'Factor the numerator as a difference of squares: x² − 4 = (x + 2)(x − 2). Cancel the common factor (x − 2): (x + 2)(x − 2)/(x − 2) = x + 2, for x ≠ 2.',
    wrongAnswerExplanations: {
      B: 'x − 2 is the factor that was cancelled, not the simplified result.',
      C: 'x + 4 would require the numerator to factor as (x + 4)(x − 2) = x² + 2x − 8, which is not x² − 4.',
      D: 'x omits the constant term that remains after cancellation.',
    },
  },

  {
    id: 'sat-f1-v2-math-m2e-q10',
    section: 'math',
    moduleId: 'f1v2-math-module-2-easy',
    domain: 'Advanced Math',
    skill: 'Equivalent expressions',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'Which of the following is a factored form of 2x² + 7x + 3?',
    choices: [
      { label: 'A', text: '(2x + 1)(x + 3)' },
      { label: 'B', text: '(2x − 1)(x − 3)' },
      { label: 'C', text: '(x + 3)(x + 1)' },
      { label: 'D', text: '(2x + 3)(x + 1)' },
    ],
    correctAnswer: 'A',
    explanation: 'Check: (2x + 1)(x + 3) = 2x² + 6x + x + 3 = 2x² + 7x + 3 ✓.',
    wrongAnswerExplanations: {
      B: '(2x − 1)(x − 3) = 2x² − 7x + 3, which has a negative middle term.',
      C: '(x + 3)(x + 1) = x² + 4x + 3, which has the wrong leading coefficient.',
      D: '(2x + 3)(x + 1) = 2x² + 2x + 3x + 3 = 2x² + 5x + 3, wrong middle term.',
    },
  },

  {
    id: 'sat-f1-v2-math-m2e-q11',
    section: 'math',
    moduleId: 'f1v2-math-module-2-easy',
    domain: 'Advanced Math',
    skill: 'Nonlinear functions',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'The graph of f(x) = x² − 4x + 3 crosses the x-axis at two points. What is the sum of the x-coordinates of those points?',
    choices: [
      { label: 'A', text: '3' },
      { label: 'B', text: '4' },
      { label: 'C', text: '7' },
      { label: 'D', text: '−4' },
    ],
    correctAnswer: 'B',
    explanation: 'Factor: (x − 1)(x − 3) = 0, so x = 1 and x = 3. Sum = 1 + 3 = 4. (By Vieta\'s formulas, sum of roots = −b/a = −(−4)/1 = 4.)',
    wrongAnswerExplanations: {
      A: '3 is the product of the roots (by Vieta\'s formulas, product = c/a = 3/1 = 3), not the sum. Students who know Vieta\'s formulas but confuse which formula gives the sum versus the product select this. The sum is −b/a = −(−4)/1 = 4; the product is c/a = 3.',
      C: '7 is obtained by adding all three coefficients: 1 + (−4) + 3 = 0... or perhaps adding the constant to the sum of roots: 4 + 3 = 7. Neither is the correct procedure. The sum of the x-intercepts is the sum of the roots of the equation, found by factoring or by Vieta\'s formula (−b/a), not by adding coefficients.',
      D: '−4 comes from reading Vieta\'s formula incorrectly: sum of roots = b/a = −4/1 = −4, forgetting the negative sign. The correct formula is sum = −b/a. Since b = −4, the sum is −(−4)/1 = 4, not −4. This sign error is especially common when the b coefficient is itself negative.',
    },
  },

  {
    id: 'sat-f1-v2-math-m2e-q13',
    section: 'math',
    moduleId: 'f1v2-math-module-2-easy',
    domain: 'Advanced Math',
    skill: 'Nonlinear functions',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'If f(x) = x² and g(x) = x + 3, what is the value of f(g(2))?',
    choices: [
      { label: 'A', text: '7' },
      { label: 'B', text: '13' },
      { label: 'C', text: '25' },
      { label: 'D', text: '49' },
    ],
    correctAnswer: 'C',
    explanation: 'First evaluate g(2) = 2 + 3 = 5. Then f(g(2)) = f(5) = 5² = 25.',
    wrongAnswerExplanations: {
      A: '7 = f(2) + g(2) = 4 + 3, which applies both functions separately to x = 2 and adds them. This is the most common misreading of function composition: students see f(g(2)) and think "apply f to 2 and g to 2, then combine," rather than "apply g to 2 first, then apply f to that result."',
      B: '13 comes from reversing the order of composition: computing g(f(2)) instead of f(g(2)). First apply f: f(2) = 4. Then apply g: g(4) = 4 + 3 = 7. That gives 7, not 13. Actually 13 might come from f(g(2)) computed as g(2)² + g(2) = 25 ≠ 13, or from computing g(f(3)) = g(9) = 12 ≠ 13. The key point is that f(g(2)) ≠ g(f(2)) — composition order matters.',
      D: '49 = f(7) = 7² — students who first compute g(2) = 5 correctly but then compute g(5) = 8 (applying g twice instead of f) or who compute f(g(3)) instead of f(g(2)) by misreading the input arrive near this range. Actually 49 = f(7) = 7², which would arise from computing g(4) = 7 (an off-by-two error on the input) rather than g(2) = 5.',
    },
  },

  {
    id: 'sat-f1-v2-math-m2e-q18',
    section: 'math',
    moduleId: 'f1v2-math-module-2-easy',
    domain: 'Advanced Math',
    skill: 'Nonlinear functions',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'The function g(x) = k · 2^x passes through the point (3, 24). What is the value of k?',
    choices: [
      { label: 'A', text: '2' },
      { label: 'B', text: '3' },
      { label: 'C', text: '4' },
      { label: 'D', text: '6' },
    ],
    correctAnswer: 'B',
    explanation: 'Substitute x = 3 and g(3) = 24: k · 2³ = 24 → 8k = 24 → k = 3.\n\nDesmos method: Enter y = k · 2^x and add a slider for k. Adjust k until the graph passes through the point (3, 24). The slider confirms k = 3.',
    wrongAnswerExplanations: {
      A: 'k = 2 gives g(3) = 2 · 8 = 16, not 24.',
      C: 'k = 4 gives g(3) = 4 · 8 = 32, not 24.',
      D: 'k = 6 gives g(3) = 6 · 8 = 48, not 24.',
    },
  },

  {
    id: 'sat-f1-v2-math-m2e-q01',
    section: 'math',
    moduleId: 'f1v2-math-module-2-easy',
    domain: 'Geometry and Trigonometry',
    skill: 'Circles',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'A circle has a radius of 9. An arc of the circle subtends a central angle of 80°. What is the length of this arc, in terms of π?',
    choices: [
      { label: 'A', text: '4π' },
      { label: 'B', text: '2π' },
      { label: 'C', text: '8π' },
      { label: 'D', text: '9π/2' },
    ],
    correctAnswer: 'A',
    explanation: 'Arc length = (central angle / 360°) × 2πr = (80/360) × 2π(9) = (2/9) × 18π = 4π.',
    wrongAnswerExplanations: {
      B: '2π results from using half the radius (4.5 instead of 9): (80/360) × 2π(4.5) = (2/9) × 9π = 2π. Students who misread the radius as the diameter and halve it make this error. The problem states radius = 9, so the full radius should be used.',
      C: '8π comes from doubling the central angle before applying the formula: (160/360) × 2π(9) = (4/9) × 18π = 8π. This error might arise from confusing a central angle with an inscribed angle (an inscribed angle is half the central angle it subtends, so students might think they need to double 80° to convert). No conversion is needed when the angle is already a central angle.',
      D: '9π/2 is the most seductive wrong answer because it uses a "clean" fraction: (1/4) × 2π(9) = 9π/2, which comes from using 90° (a right angle) instead of 80°. Students who round 80° to the nearest "nice" angle or who misread 80° as 90° land here. The problem explicitly states 80°, so no rounding should occur.',
    },
  },

  {
    id: 'sat-f1-v2-math-m2e-q17',
    section: 'math',
    moduleId: 'f1v2-math-module-2-easy',
    domain: 'Geometry and Trigonometry',
    skill: 'Area and volume',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'A trapezoid has two parallel sides of lengths 8 cm and 14 cm and a height of 6 cm. What is the area of the trapezoid, in square centimeters?',
    choices: [
      { label: 'A', text: '66' },
      { label: 'B', text: '132' },
      { label: 'C', text: '84' },
      { label: 'D', text: '48' },
    ],
    correctAnswer: 'A',
    explanation: 'Area of a trapezoid = ½(b₁ + b₂) × h = ½(8 + 14) × 6 = ½ × 22 × 6 = 66 cm².',
    wrongAnswerExplanations: {
      B: '132 = (8 + 14) × 6 — omits the factor of ½ in the trapezoid area formula.',
      C: '84 = 14 × 6 — uses only the longer base, ignoring the shorter base.',
      D: '48 = 8 × 6 — uses only the shorter base, ignoring the longer base.',
    },
  },

  {
    id: 'sat-f1-v2-math-m2e-q20',
    section: 'math',
    moduleId: 'f1v2-math-module-2-easy',
    domain: 'Geometry and Trigonometry',
    skill: 'Lines, angles, and triangles',
    difficulty: 'medium',
    type: 'grid_in',
    question: 'Triangle ABC is similar to triangle DEF, with side AB corresponding to side DE. If AB = 5, DE = 8, and the perimeter of triangle ABC is 20, what is the perimeter of triangle DEF, in units?',
    correctAnswer: '32',
    acceptableAnswers: ['32'],
    explanation: 'The ratio of corresponding sides is DE/AB = 8/5. The perimeters of similar triangles scale by the same ratio: perimeter of DEF = 20 × (8/5) = 32.',
    scoringNotes: 'Answer must be 32.',
  },

  {
    id: 'sat-f1-v2-math-m2e-q21',
    section: 'math',
    moduleId: 'f1v2-math-module-2-easy',
    domain: 'Geometry and Trigonometry',
    skill: 'Lines, angles, and triangles',
    difficulty: 'medium',
    type: 'grid_in',
    question: 'Two supplementary angles are in the ratio 2:3. What is the measure, in degrees, of the larger angle?',
    correctAnswer: '108',
    acceptableAnswers: ['108'],
    explanation: 'Supplementary angles sum to 180°. Let the angles be 2x and 3x: 2x + 3x = 180 → x = 36. Larger angle = 3(36) = 108°.',
    scoringNotes: 'Answer must be 108.',
  },

  {
    id: 'sat-f1-v2-math-m2e-q22',
    section: 'math',
    moduleId: 'f1v2-math-module-2-easy',
    domain: 'Geometry and Trigonometry',
    skill: 'Lines, angles, and triangles',
    difficulty: 'medium',
    type: 'grid_in',
    question: 'Two angles of a triangle measure 48° and 75°. What is the measure, in degrees, of the third angle?',
    correctAnswer: '57',
    acceptableAnswers: ['57'],
    explanation: 'The angles of a triangle sum to 180°. Third angle = 180° − 48° − 75° = 57°.',
    scoringNotes: 'Answer must be 57.',
  },
]
