import type { MathQuestion } from '../types'

// Math Module 1 — 22 questions, mixed difficulty (routing module)
// 17 multiple choice (q01–q17) + 5 grid-in (q18–q22)

export const mathModule1QuestionsV2: MathQuestion[] = [
  {
    id: 'sat-f1-v2-math-m1-q02',
    section: 'math',
    moduleId: 'f1v2-math-module-1',
    domain: 'Algebra',
    skill: 'Linear functions',
    difficulty: 'easy',
    type: 'multiple_choice',
    stimulus: 'The graph of line f is shown in the xy-plane.',
    graphData: {
      type: 'coordinate_plane',
      xMin: -4, xMax: 4, yMin: -5, yMax: 7, gridStep: 1,
      xLabel: 'x', yLabel: 'y',
      lines: [{
        label: 'f',
        points: [[-3, -4], [-1, 0], [0, 2], [2, 6]],
        color: '#4f46e5',
      }],
    },
    question: 'What is the y-intercept of line f?',
    choices: [
      { label: 'A', text: '2' },
      { label: 'B', text: '−2' },
      { label: 'C', text: '−4' },
      { label: 'D', text: '4' },
    ],
    correctAnswer: 'A',
    explanation: 'The y-intercept is the point where the line crosses the y-axis (x = 0). From the graph, the line passes through (0, 2), so the y-intercept is 2.',
    wrongAnswerExplanations: {
      C: '−4 is the y-value when x = −3, not at x = 0.',
      B: 'The line does not cross the y-axis at −2.',
      D: '4 is close to the slope, not the y-intercept.',
    },
  },

  {
    id: 'sat-f1-v2-math-m1-q03',
    section: 'math',
    moduleId: 'f1v2-math-module-1',
    domain: 'Algebra',
    skill: 'Systems of two linear equations in two variables',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'A school store sells notebooks for $3.00 each and pens for $1.25 each. A student buys a total of 8 items and spends exactly $18.75. How many notebooks did the student buy?',
    choices: [
      { label: 'A', text: '3' },
      { label: 'B', text: '4' },
      { label: 'C', text: '5' },
      { label: 'D', text: '6' },
    ],
    correctAnswer: 'C',
    explanation: 'Let n = number of notebooks and p = number of pens. Set up the system: n + p = 8 and 3n + 1.25p = 18.75. From the first equation, p = 8 − n. Substitute into the second: 3n + 1.25(8 − n) = 18.75 → 3n + 10 − 1.25n = 18.75 → 1.75n = 8.75 → n = 5. The student bought 5 notebooks.',
    wrongAnswerExplanations: {
      A: 'If n = 3: cost = 3(3) + 1.25(5) = 9 + 6.25 = $15.25, not $18.75.',
      B: 'If n = 4: cost = 3(4) + 1.25(4) = 12 + 5 = $17.00, not $18.75.',
      D: 'If n = 6: cost = 3(6) + 1.25(2) = 18 + 2.50 = $20.50, not $18.75.',
    },
  },

  {
    id: 'sat-f1-v2-math-m1-q04',
    section: 'math',
    moduleId: 'f1v2-math-module-1',
    domain: 'Algebra',
    skill: 'Linear inequalities in one or two variables',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'A moving company charges a flat fee of $120 plus $0.40 per pound for shipments over 200 pounds. A customer\'s total bill must stay under $220. Which inequality represents the maximum weight w (in pounds) of a shipment that meets this condition?',
    choices: [
      { label: 'A', text: 'w < 450' },
      { label: 'B', text: 'w < 250' },
      { label: 'C', text: 'w < 350' },
      { label: 'D', text: 'w < 500' },
    ],
    correctAnswer: 'A',
    explanation: 'The per-pound charge applies only to weight over 200 pounds, so the charge for the excess is 0.40(w − 200). The total bill inequality is: 120 + 0.40(w − 200) < 220 → 120 + 0.40w − 80 < 220 → 0.40w + 40 < 220 → 0.40w < 180 → w < 450.',
    wrongAnswerExplanations: {
      B: 'w < 250 results from applying the $0.40 rate to the entire weight w rather than only to the excess above 200 pounds. Setting up 120 + 0.40w < 220 gives 0.40w < 100, so w < 250 — a common error when the "over 200 pounds" threshold is missed.',
      C: 'w < 350 results from correctly applying 0.40(w − 200) but then comparing it to the remaining budget after subtracting $60 instead of $100: if 0.40(w − 200) < 60 (using the wrong remainder), then w − 200 < 150, giving w < 350. The correct remaining budget is $220 − $120 = $100, not $60.',
      D: 'w < 500 results from an off-by-one error in computing the remaining budget, such as using $220 − $80 = $140 and then solving 0.40(w − 200) < 120 → w < 500, forgetting to subtract the full flat fee of $120.',
    },
  },

  {
    id: 'sat-f1-v2-math-m1-q05',
    section: 'math',
    moduleId: 'f1v2-math-module-1',
    domain: 'Algebra',
    skill: 'Linear equations in one variable',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'A store is running a promotion: customers receive a $15 discount off any purchase totaling $80 or more. Elena buys items priced at $12, $27, and $53. How much does she pay after the discount is applied?',
    choices: [
      { label: 'A', text: '$62' },
      { label: 'B', text: '$77' },
      { label: 'C', text: '$80' },
      { label: 'D', text: '$92' },
    ],
    correctAnswer: 'B',
    explanation: 'First find the total: 12 + 27 + 53 = $92. Since $92 ≥ $80, the discount applies: 92 − 15 = $77.',
    wrongAnswerExplanations: {
      A: '$62 subtracts the $15 discount from $77 instead of from the original $92 total.',
      C: '$80 is the minimum threshold for the discount, not the amount paid.',
      D: '$92 is the total before the discount is applied.',
    },
  },

  {
    id: 'sat-f1-v2-math-m1-q06',
    section: 'math',
    moduleId: 'f1v2-math-module-1',
    domain: 'Algebra',
    skill: 'Linear equations in two variables',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'A company has fixed monthly costs of $4,800 and variable production costs of $6 per widget. Each widget sells for $14. Which equation represents the company\'s monthly profit P (in dollars) when n widgets are sold?',
    choices: [
      { label: 'A', text: 'P = 8n − 4,800' },
      { label: 'B', text: 'P = 6n − 4,800' },
      { label: 'C', text: 'P = 14n − 4,800' },
      { label: 'D', text: 'P = 8n + 4,800' },
    ],
    correctAnswer: 'A',
    explanation: 'Profit = Revenue − Total Costs = 14n − (6n + 4,800) = 8n − 4,800.',
    wrongAnswerExplanations: {
      C: 'P = 14n − 4,800 uses the selling price per widget as the profit rate, ignoring that $6 of each sale goes toward variable production costs. Revenue is 14n, but each unit also costs $6 to produce, leaving only $8 per widget as contribution toward fixed costs and profit.',
      B: 'P = 6n − 4,800 uses the variable cost ($6) as the profit rate rather than the contribution margin ($14 − $6 = $8). It is easy to confuse the variable cost with profit-per-unit, but profit per widget requires subtracting cost from revenue.',
      D: 'P = 8n + 4,800 correctly identifies the $8 contribution margin per widget but adds the fixed costs instead of subtracting them. Fixed costs are an expense that must be recovered before any profit is earned, so they reduce, not increase, total profit.',
    },
  },

  {
    id: 'sat-f1-v2-math-m1-q15',
    section: 'math',
    moduleId: 'f1v2-math-module-1',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'Percentages',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'A solution is 40% alcohol by volume. If 20 mL of pure alcohol is added to 60 mL of this solution, what is the percent of alcohol in the new mixture?',
    choices: [
      { label: 'A', text: '55%' },
      { label: 'B', text: '50%' },
      { label: 'C', text: '60%' },
      { label: 'D', text: '45%' },
    ],
    correctAnswer: 'A',
    explanation: 'Original alcohol = 40% × 60 mL = 24 mL. After adding 20 mL of pure alcohol: total alcohol = 44 mL, total volume = 80 mL. Percent = 44/80 = 55%.',
    wrongAnswerExplanations: {
      B: '50% = (40% + 60%)/2 — incorrectly averages the two percent values instead of computing from volumes.',
      C: '60% omits the dilution effect of the extra 20 mL water-free alcohol being added to a larger total.',
      D: '45% results from computing 44/100 (wrong denominator) instead of 44/80.',
    },
  },

  {
    id: 'sat-f1-v2-math-m1-q16',
    section: 'math',
    moduleId: 'f1v2-math-module-1',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'Two-variable data: models and scatterplots',
    difficulty: 'medium',
    type: 'multiple_choice',
    stimulus: 'The scatter plot shows the number of hours students spent practicing a skill each week and their scores on a performance assessment.',
    graphData: {
      type: 'scatter',
      xLabel: 'Hours of practice per week',
      yLabel: 'Score',
      xMin: 0, xMax: 8, yMin: 50, yMax: 100,
      points: [[1,54],[1,60],[2,63],[3,68],[3,72],[4,70],[4,77],[5,80],[5,85],[6,83],[6,90],[7,92],[7,95]],
      trendLine: { slope: 6.5, intercept: 50 },
    },
    question: 'Based on the scatter plot, which of the following best describes the association between hours of practice and performance score?',
    choices: [
      { label: 'A', text: 'Strong negative linear association' },
      { label: 'B', text: 'No association' },
      { label: 'C', text: 'Nonlinear association' },
      { label: 'D', text: 'Strong positive linear association' },
    ],
    correctAnswer: 'D',
    explanation: 'As hours of practice increase, scores consistently increase in a roughly linear pattern. The data points cluster closely around an upward-sloping trend line, indicating a strong positive linear association.',
    wrongAnswerExplanations: {
      A: 'A negative association would show scores decreasing as hours increase — the opposite of what the scatter plot shows.',
      B: 'There is a clear pattern in the data; the points are not randomly scattered.',
      C: 'The points follow a roughly straight-line pattern, not a curved one.',
    },
  },

  {
    id: 'sat-f1-v2-math-m1-q17',
    section: 'math',
    moduleId: 'f1v2-math-module-1',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'Percentages',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'A store\'s annual sales rose from $40,000 to $52,000. By what percent did sales increase?',
    choices: [
      { label: 'A', text: '20%' },
      { label: 'B', text: '25%' },
      { label: 'C', text: '30%' },
      { label: 'D', text: '35%' },
    ],
    correctAnswer: 'C',
    explanation: 'Percent increase = (change ÷ original) × 100 = (12,000 ÷ 40,000) × 100 = 30%.',
    wrongAnswerExplanations: {
      A: '20% of $40,000 = $8,000 → total $48,000, not $52,000.',
      B: '25% of $40,000 = $10,000 → total $50,000, not $52,000.',
      D: '35% of $40,000 = $14,000 → total $54,000, not $52,000.',
    },
  },

  {
    id: 'sat-f1-v2-math-m1-q18',
    section: 'math',
    moduleId: 'f1v2-math-module-1',
    domain: 'Problem-Solving and Data Analysis',
    skill: 'Ratios, rates, proportional relationships, and units',
    difficulty: 'medium',
    type: 'grid_in',
    question: 'A worker earns $20 per hour for the first 40 hours worked in a week and $30 per hour for each additional hour worked beyond 40. Last week the worker earned a total of $950. How many overtime hours did the worker work?',
    correctAnswer: '5',
    acceptableAnswers: ['5'],
    explanation: 'Regular pay for 40 hours = 40 × $20 = $800. Overtime pay = $950 − $800 = $150. Overtime hours = $150 ÷ $30 = 5.',
  },

  {
    id: 'sat-f1-v2-math-m1-q08',
    section: 'math',
    moduleId: 'f1v2-math-module-1',
    domain: 'Advanced Math',
    skill: 'Equivalent expressions',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'The expression x² − 10x + 29 can be written as (x − a)² + b, where a and b are constants. What is the value of a + b?',
    choices: [
      { label: 'A', text: '9' },
      { label: 'B', text: '14' },
      { label: 'C', text: '29' },
      { label: 'D', text: '5' },
    ],
    correctAnswer: 'A',
    explanation: 'Complete the square: x² − 10x + 29 = (x − 5)² − 25 + 29 = (x − 5)² + 4. So a = 5 and b = 4, giving a + b = 9.',
    wrongAnswerExplanations: {
      B: '14 results from adding the linear coefficient (10) to b (4): 10 + 4 = 14. The error is confusing the original coefficient −10 with the value of a. Completing the square gives a = 10/2 = 5, not 10.',
      C: '29 is the constant term in the original expression, not the sum a + b. A student who does not complete the square and simply reads off the last number from the original polynomial will land on this answer.',
      D: '5 is the value of a alone — the half-coefficient obtained when completing the square. Forgetting to add b = 4 gives 5 instead of 5 + 4 = 9. This error comes from stopping after finding a without evaluating b.',
    },
  },

  {
    id: 'sat-f1-v2-math-m1-q09',
    section: 'math',
    moduleId: 'f1v2-math-module-1',
    domain: 'Advanced Math',
    skill: 'Nonlinear functions',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'The function f(x) = x² − 6x + k has a minimum value of 4. What is the value of k?',
    choices: [
      { label: 'A', text: '13' },
      { label: 'B', text: '10' },
      { label: 'C', text: '4' },
      { label: 'D', text: '7' },
    ],
    correctAnswer: 'A',
    explanation: 'Complete the square: f(x) = (x − 3)² + (k − 9). The minimum value occurs at the vertex: k − 9 = 4, so k = 13.\n\nDesmos method: Enter y = x² − 6x + k and add a slider for k. Drag k until the lowest point of the parabola (the vertex) sits exactly at y = 4 on the graph. The slider value reads k = 13.',
    wrongAnswerExplanations: {
      B: '10 results from adding the linear coefficient (6) to the minimum value (4): 6 + 4 = 10. The correct method is to use the vertex form, which shows the vertex y-value is k − (b/2)² = k − 9. Setting k − 9 = 4 gives k = 13, not 10.',
      C: '4 is the minimum value of the function, not k. A student who confuses "the function has a minimum value of 4" with "k = 4" will choose this. But k is the constant in the original expression, and setting k = 4 gives a vertex at (3, 4 − 9) = (3, −5), not a minimum of 4.',
      D: '7 results from computing k = 4 + 3 — adding the minimum value to the x-coordinate of the vertex (x = 3) rather than to the square of the half-coefficient (3² = 9). The vertex x-coordinate and the quantity added to find k are both derived from b/2 = 3, making the confusion understandable but incorrect.',
    },
  },

  {
    id: 'sat-f1-v2-math-m1-q10',
    section: 'math',
    moduleId: 'f1v2-math-module-1',
    domain: 'Advanced Math',
    skill: 'Nonlinear functions',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'A savings account earns 4% annual interest compounded annually. If the initial deposit is $2,000, which expression represents the account balance after n years?',
    choices: [
      { label: 'A', text: '2000 + 0.04n' },
      { label: 'B', text: '2000(1.04)ⁿ' },
      { label: 'C', text: '2000(0.04)ⁿ' },
      { label: 'D', text: '2000 × 1.04n' },
    ],
    correctAnswer: 'B',
    explanation: 'Compound interest formula: A = P(1 + r)ⁿ = 2000(1.04)ⁿ.',
    wrongAnswerExplanations: {
      A: 'This models simple interest (adding a fixed amount each year), not compounding.',
      C: '2000(0.04)ⁿ approaches 0 as n grows — it models decay.',
      D: '1.04n is linear; compound growth requires n as an exponent on the base.',
    },
  },

  {
    id: 'sat-f1-v2-math-m1-q11',
    section: 'math',
    moduleId: 'f1v2-math-module-1',
    domain: 'Advanced Math',
    skill: 'Nonlinear functions',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'If f(x) = 3x² − 5, what is the value of f(−2) + f(3)?',
    choices: [
      { label: 'A', text: '17' },
      { label: 'B', text: '25' },
      { label: 'C', text: '36' },
      { label: 'D', text: '29' },
    ],
    correctAnswer: 'D',
    explanation: 'f(−2) = 3(−2)² − 5 = 3(4) − 5 = 12 − 5 = 7; f(3) = 3(3)² − 5 = 3(9) − 5 = 27 − 5 = 22. Sum = 7 + 22 = 29.',
    wrongAnswerExplanations: {
      A: '17 = 22 − 5 results from evaluating only f(3) correctly (22) and then mistakenly subtracting 5 again from f(−2). Alternatively, it comes from computing f(−2) = 3(−2) − 5 = −6 − 5 = −11 and f(3) = 3(3) − 5 = 4 (forgetting to square), with arithmetic errors producing 17.',
      B: '25 results from computing f(−2) = 3(4) − 5 = 7 correctly but then calculating f(3) as 3(3) − 5 = 4 (using 3 instead of 3²), giving 7 + 18 = 25. The error is failing to square the input for f(3).',
      C: '36 results from omitting the −5 in both evaluations: 3(4) + 3(9) = 12 + 27 = 39, then possibly making a further arithmetic error, or from computing f(−2) = 3(4) = 12 and f(3) = 3(8) = 24 (using 2³ instead of 3²), giving 12 + 24 = 36.',
    },
  },

  {
    id: 'sat-f1-v2-math-m1-q12',
    section: 'math',
    moduleId: 'f1v2-math-module-1',
    domain: 'Advanced Math',
    skill: 'Equivalent expressions',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'Which expression is equivalent to (3a²b³)²?',
    choices: [
      { label: 'A', text: '6a⁴b⁶' },
      { label: 'B', text: '9a⁴b⁶' },
      { label: 'C', text: '6a⁴b⁵' },
      { label: 'D', text: '9a⁴b⁵' },
    ],
    correctAnswer: 'B',
    explanation: '(3a²b³)² = 3² · a^(2×2) · b^(3×2) = 9a⁴b⁶.',
    wrongAnswerExplanations: {
      A: '3² = 9, not 6; multiplying instead of squaring the coefficient.',
      C: 'Both coefficient and b-exponent are wrong (3² = 9 and 3×2 = 6).',
      D: 'b-exponent: 3 × 2 = 6, not 5.',
    },
  },

  {
    id: 'sat-f1-v2-math-m1-q01',
    section: 'math',
    moduleId: 'f1v2-math-module-1',
    domain: 'Geometry and Trigonometry',
    skill: 'Lines, angles, and triangles',
    difficulty: 'medium',
    type: 'multiple_choice',
    graphData: {
      type: 'coordinate_plane',
      xMin: -1, xMax: 9, yMin: -1, yMax: 12,
      gridStep: 2,
      points: [
        { x: 1, y: 2, label: 'P(1, 2)' },
        { x: 7, y: 10, label: 'Q(7, 10)' },
      ],
      lines: [
        { points: [[1, 2], [7, 10]] as [number, number][], color: '#4f46e5' },
      ],
    },
    question: 'In the xy-plane, point P has coordinates (1, 2) and point Q has coordinates (7, 10). What is the length of segment PQ?',
    choices: [
      { label: 'A', text: '8' },
      { label: 'B', text: '10' },
      { label: 'C', text: '√68' },
      { label: 'D', text: '14' },
    ],
    correctAnswer: 'B',
    explanation: 'Apply the distance formula: PQ = √((7 − 1)² + (10 − 2)²) = √(36 + 64) = √100 = 10.',
    wrongAnswerExplanations: {
      A: '8 is the vertical difference 10 − 2, not the distance between the two points.',
      C: '√68 would result from using (6² + 2²) or a similar arithmetic error in one of the squared differences.',
      D: '14 = 6 + 8 adds the horizontal and vertical differences directly instead of squaring and taking the square root.',
    },
  },

  {
    id: 'sat-f1-v2-math-m1-q19',
    section: 'math',
    moduleId: 'f1v2-math-module-1',
    domain: 'Geometry and Trigonometry',
    skill: 'Area and volume',
    difficulty: 'medium',
    type: 'grid_in',
    question: 'The radius of a circle is increased by 50%. By what percent does the area of the circle increase?',
    correctAnswer: '125',
    acceptableAnswers: ['125'],
    explanation: 'Let the original radius be r. New radius = 1.5r. Original area = πr². New area = π(1.5r)² = 2.25πr². Increase = (2.25 − 1) × 100% = 125%.',
  },

  {
    id: 'sat-f1-v2-math-m1-q20',
    section: 'math',
    moduleId: 'f1v2-math-module-1',
    domain: 'Geometry and Trigonometry',
    skill: 'Area and volume',
    difficulty: 'hard',
    type: 'grid_in',
    question: 'A solid metal cylinder has a radius of 3 cm and a height of 10 cm. A cylindrical hole of radius 1 cm is drilled straight through the center of the cylinder along its entire height. The remaining solid is melted down and recast into a new solid cylinder with radius 2 cm. What is the height, in centimeters, of the new cylinder? (Use π as needed; express the answer in exact form as an integer or simplified fraction.)',
    correctAnswer: '20',
    acceptableAnswers: ['20'],
    explanation: 'Volume of original cylinder: π(3²)(10) = 90π cm³. Volume removed by hole: π(1²)(10) = 10π cm³. Volume of remaining solid: 90π − 10π = 80π cm³. This is recast into a new cylinder with radius 2 cm. Volume formula: π(2²)(h) = 4πh. Set equal to remaining volume: 4πh = 80π → h = 20 cm.',
  },

  {
    id: 'sat-f1-v2-math-m1-q21',
    section: 'math',
    moduleId: 'f1v2-math-module-1',
    domain: 'Geometry and Trigonometry',
    skill: 'Lines, angles, and triangles',
    difficulty: 'hard',
    type: 'grid_in',
    question: 'In triangle ABC, angle B = 90°. The length of leg AB is (x + 5), the length of leg BC is x, and the length of hypotenuse AC is (2x − 5). What is the perimeter of triangle ABC?',
    correctAnswer: '60',
    acceptableAnswers: ['60'],
    explanation: 'Apply the Pythagorean theorem: AB² + BC² = AC². Substitute the expressions: (x + 5)² + x² = (2x − 5)². Expand each term: (x² + 10x + 25) + x² = 4x² − 20x + 25. Combine the left side: 2x² + 10x + 25 = 4x² − 20x + 25. Subtract 2x² + 10x + 25 from both sides: 0 = 2x² − 30x. Factor: 0 = 2x(x − 15). So x = 0 or x = 15. Since x must be positive, x = 15. The three sides are: AB = 15 + 5 = 20, BC = 15, AC = 2(15) − 5 = 25. Perimeter = 20 + 15 + 25 = 60.',
  },

  {
    id: 'sat-f1-v2-math-m1-q07',
    section: 'math',
    moduleId: 'f1v2-math-module-1',
    domain: 'Algebra',
    skill: 'Linear equations in one variable',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'A store offers two discount plans. Plan X gives a flat $30 discount. Plan Y gives a 20% discount off the original price. For what purchase amount (in dollars) do both plans result in the same final price?',
    choices: [
      { label: 'A', text: '$100' },
      { label: 'B', text: '$120' },
      { label: 'C', text: '$150' },
      { label: 'D', text: '$180' },
    ],
    correctAnswer: 'C',
    explanation: 'Set the final prices equal: p − 30 = 0.8p → 0.2p = 30 → p = 150. At $150: Plan X gives $120 and Plan Y gives 0.8(150) = $120 ✓.',
    wrongAnswerExplanations: {
      A: 'At $100: Plan X gives $70 and Plan Y gives $80. Plan Y is better here because a 20% discount is only $20, less than the flat $30. At prices below $150, Plan X always wins, so these plans cannot be equal at $100.',
      B: 'At $120: Plan X gives $90 and Plan Y gives $96. A 20% discount on $120 is $24, which is less than $30, so Plan X again gives the lower final price. The break-even point must be higher.',
      D: 'At $180: Plan X gives $150 and Plan Y gives $144. A 20% discount on $180 is $36, which exceeds the flat $30, so Plan Y is now cheaper. The break-even price must be between $120 and $180 — specifically $150.',
    },
  },

  {
    id: 'sat-f1-v2-math-m1-q13',
    section: 'math',
    moduleId: 'f1v2-math-module-1',
    domain: 'Advanced Math',
    skill: 'Nonlinear equations in one variable',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'The equation 3x² − 6x + k = 0 has exactly one real solution. What is the value of k?',
    choices: [
      { label: 'A', text: '1' },
      { label: 'B', text: '2' },
      { label: 'C', text: '3' },
      { label: 'D', text: '4' },
    ],
    correctAnswer: 'C',
    explanation: 'For exactly one real solution, the discriminant must equal zero: b² − 4ac = (−6)² − 4(3)(k) = 36 − 12k = 0 → k = 3.\n\nDesmos method: Enter y = 3x² − 6x + k and add a slider for k. When k < 3 the parabola crosses the x-axis at two points; when k > 3 it never touches the x-axis. At k = 3 the parabola is tangent to the x-axis — exactly one real solution.',
    wrongAnswerExplanations: {
      A: 'k = 1 gives discriminant = (−6)² − 4(3)(1) = 36 − 12 = 24 > 0. A positive discriminant means two distinct real solutions, not one. This is a plausible guess if a student incorrectly sets b² − 4ac = 1 or confuses the discriminant condition.',
      B: 'k = 2 gives discriminant = 36 − 4(3)(2) = 36 − 24 = 12 > 0. Still two real solutions. This answer is tempting because 36/12 = 3 involves the coefficient 12 from 4ac = 4(3)(k), and a student might mistakenly solve 36 − 12 = 0 (using k = 1) or miscount the factor.',
      D: 'k = 4 gives discriminant = 36 − 4(3)(4) = 36 − 48 = −12 < 0. A negative discriminant means no real solutions at all. This is particularly tempting because k = 4 is one step above the correct answer and a student who solves 36 − 12k = 0 and gets k = 3 but then rounds up or adds 1 will land here.',
    },
  },

  {
    id: 'sat-f1-v2-math-m1-q14',
    section: 'math',
    moduleId: 'f1v2-math-module-1',
    domain: 'Advanced Math',
    skill: 'Nonlinear equations in one variable and systems of equations',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'The graphs of y = x² − 2 and y = x intersect at two points. What is the x-coordinate of the intersection where x is positive?',
    choices: [
      { label: 'A', text: '−1' },
      { label: 'B', text: '0' },
      { label: 'C', text: '1' },
      { label: 'D', text: '2' },
    ],
    correctAnswer: 'D',
    explanation: 'Set x² − 2 = x → x² − x − 2 = 0 → (x − 2)(x + 1) = 0 → x = 2 or x = −1. The positive root is 2.',
    wrongAnswerExplanations: {
      A: 'x = −1 is the other (negative) intersection point. It is a valid solution to x² − x − 2 = 0, but the question asks for the positive intersection. Students who factor correctly but do not read the question carefully may select this.',
      B: 'At x = 0: y = 0² − 2 = −2 on the parabola and y = 0 on the line. These are not equal, so (0, 0) is not an intersection. Students may guess this because 0 is "between" −1 and 2 or confuse it with the line\'s y-intercept.',
      C: 'At x = 1: y = 1² − 2 = −1 on the parabola and y = 1 on the line. These are not equal. Students may select 1 because the problem mentions x is positive and 1 is the smallest positive integer answer, or because they factor x² − x − 2 incorrectly as (x − 1)(x − 2) = 0.',
    },
  },

  {
    id: 'sat-f1-v2-math-m1-q22',
    section: 'math',
    moduleId: 'f1v2-math-module-1',
    domain: 'Geometry and Trigonometry',
    skill: 'Lines, angles, and triangles',
    difficulty: 'hard',
    type: 'grid_in',
    question: 'Triangle PQR is similar to triangle XYZ, with PQ corresponding to XY. If PQ = 6, XY = 10, and the area of triangle PQR is 27 square units, what is the area of triangle XYZ, in square units?',
    correctAnswer: '75',
    acceptableAnswers: ['75'],
    explanation: 'The ratio of corresponding sides is 10/6 = 5/3. The area ratio of similar figures equals the square of the side ratio: (5/3)² = 25/9. Area of XYZ = 27 × 25/9 = 75.',
    scoringNotes: 'Answer must be 75.',
  },
]
