import type { MCATSection } from './types'

export const bioBiochemSection: MCATSection = {
  id: 'bio-biochem',
  title: 'Biological and Biochemical Foundations of Living Systems',
  abbreviation: 'Bio/Biochem',
  questionCount: 59,
  seededCount: 35,
  timeMinutes: 95,
  breakAfterMinutes: 10,
  breakType: 'short',
  passages: [
    {
      id: 'bb-p1',
      sectionId: 'bio-biochem',
      title: 'Passage 1',
      passageText: `Nucleotide excision repair (NER) is a versatile DNA repair pathway that removes bulky DNA lesions such as those caused by ultraviolet (UV) radiation. Two subpathways exist: global genome NER (GG-NER), which surveys the entire genome, and transcription-coupled NER (TC-NER), which is activated when RNA polymerase II stalls at a lesion during active transcription.

NER proceeds through six coordinated steps: (1) lesion recognition, (2) local DNA unwinding by helicases XPB and XPD, (3) dual incision by endonucleases XPF-ERCC1 (5′ side) and XPG (3′ side), (4) excision of a ~25–30 nucleotide oligomer, (5) DNA synthesis by polymerase δ or ε using the undamaged strand as template, and (6) ligation by DNA ligase I or III.

Researchers studying xeroderma pigmentosum (XP), a hereditary condition characterized by extreme UV sensitivity and dramatically elevated skin cancer risk, identified mutations affecting components of the NER pathway. Cell lines from XP patients showed reduced repair of cyclobutane pyrimidine dimers (CPDs) and 6-4 photoproducts — the two main UV-induced lesions. When XP fibroblasts were irradiated with UV and allowed to incubate, unscheduled DNA synthesis (UDS) — DNA synthesis outside of S phase, indicating repair — was markedly reduced compared to wild-type cells.

Experiment: To test the requirement for XPD helicase activity, researchers introduced either wild-type XPD or a helicase-dead mutant (K48A) into XP complementation group D cells. UDS was measured at 1, 6, and 24 hours post-UV irradiation.

Table 1: UDS (arbitrary units) in XP-D cells after transfection

| Construct     | 1 hr | 6 hr | 24 hr |
|---------------|------|------|-------|
| Vector only   | 2    | 3    | 4     |
| Wild-type XPD | 18   | 42   | 68    |
| K48A mutant   | 3    | 4    | 5     |`,
      figures: [
        {
          type: 'table',
          title: 'Table 1: UDS in XP-D cells post-UV irradiation',
          headers: ['Construct', '1 hr', '6 hr', '24 hr'],
          rows: [
            ['Vector only', '2', '3', '4'],
            ['Wild-type XPD', '18', '42', '68'],
            ['K48A mutant', '3', '4', '5'],
          ],
        },
      ],
      questions: [
        {
          id: 'mcat1-bb-001',
          sectionId: 'bio-biochem',
          passageId: 'bb-p1',
          questionType: 'passage',
          discipline: 'Biology',
          contentCategory: 'DNA replication and repair',
          foundationalConcept: 'FC 1: Biomolecules have unique properties that determine how they contribute to the structure and function of cells.',
          scientificSkill: 'Skill 4',
          difficulty: 'medium',
          question: 'Based on Table 1, what conclusion is best supported regarding the role of XPD helicase activity in NER?',
          choices: [
            { label: 'A', text: 'Helicase activity is dispensable since K48A cells show some residual UDS.' },
            { label: 'B', text: 'Helicase activity is essential for NER, since the K48A mutant fails to restore UDS above vector-only levels.' },
            { label: 'C', text: 'Wild-type XPD and K48A rescue NER equally at 24 hours.' },
            { label: 'D', text: 'NER in XP-D cells is independent of XPD when given sufficient time.' },
          ],
          correctAnswer: 'B',
          explanation: 'The K48A mutant (helicase-dead) shows UDS of 3-5 units — indistinguishable from vector-only (2-4 units). Wild-type XPD restores UDS to 18-68 units. This confirms that XPD\'s helicase activity, not merely its physical presence, is required for NER function.',
          wrongAnswerExplanations: {
            A: 'K48A shows the same minimal UDS as vector only (background repair), indicating no meaningful rescue. Small values reflect residual activity unrelated to NER.',
            C: 'At 24 hours, wild-type shows 68 units vs. K48A showing 5 units — a >13-fold difference. They are not equivalent.',
            D: 'The data shows no recovery of NER over time in K48A cells. XP-D cells require functional XPD for NER regardless of time.',
          },
          teachingPoint: 'Control comparisons: K48A ≈ vector-only (no rescue) vs. WT XPD (full rescue). Helicase-dead mutant = no catalytic function = NER requires the enzymatic activity, not just XPD presence.',
          relatedTopics: ['NER pathway', 'XPD helicase', 'xeroderma pigmentosum', 'unscheduled DNA synthesis'],
        },
        {
          id: 'mcat1-bb-002',
          sectionId: 'bio-biochem',
          passageId: 'bb-p1',
          questionType: 'passage',
          discipline: 'Biology',
          contentCategory: 'DNA replication and repair',
          foundationalConcept: 'FC 1',
          scientificSkill: 'Skill 1',
          difficulty: 'medium',
          question: 'After the ~25–30 nucleotide oligomer is excised in NER, DNA synthesis restores the sequence. This synthesis uses the undamaged strand as a template. Which property of DNA makes this restoration accurate?',
          choices: [
            { label: 'A', text: 'Antiparallel orientation of the double helix ensures replication proceeds 5′→3′' },
            { label: 'B', text: 'Complementary base pairing allows the undamaged strand to serve as an unambiguous template for accurate synthesis' },
            { label: 'C', text: 'Histone packaging protects the template strand from further UV damage during synthesis' },
            { label: 'D', text: 'DNA ligase proofreads newly synthesized bases before sealing the nick' },
          ],
          correctAnswer: 'B',
          explanation: 'Complementary base pairing (A-T, G-C) means each base on the undamaged strand specifies exactly one correct base in the new strand. This is the fundamental property that enables accurate, template-directed DNA synthesis in all repair and replication pathways.',
          wrongAnswerExplanations: {
            A: 'Antiparallel orientation explains the directionality of synthesis (5\'→3\'), not its accuracy. Accuracy comes from complementary base pairing, not the helix orientation.',
            C: 'Histones are displaced from the region being repaired during NER. Histone protection does not explain synthesis accuracy.',
            D: 'DNA ligase seals the nick between Okazaki fragments and repair patches; it does not proofread. Proofreading is a function of DNA polymerase\'s 3\'→5\' exonuclease activity.',
          },
          teachingPoint: 'Accurate DNA synthesis in NER relies on complementary base pairing — each template base specifies the correct incoming nucleotide. This is the same logic as semiconservative replication.',
          relatedTopics: ['complementary base pairing', 'template-directed synthesis', 'NER repair synthesis', 'DNA polymerase'],
        },
        {
          id: 'mcat1-bb-003',
          sectionId: 'bio-biochem',
          passageId: 'bb-p1',
          questionType: 'passage',
          discipline: 'Biology',
          contentCategory: 'DNA replication and repair',
          foundationalConcept: 'FC 1',
          scientificSkill: 'Skill 3',
          difficulty: 'hard',
          question: 'To distinguish whether reduced UDS in XP patients results from defective excision versus defective resynthesis, what experimental design would be most informative?',
          choices: [
            { label: 'A', text: 'Measure UDS at increasing UV doses to determine dose-response relationship' },
            { label: 'B', text: 'Use a radioactive nucleotide pulse to label newly synthesized DNA and compare it to direct measurement of excised oligomer fragments' },
            { label: 'C', text: 'Transfect wild-type XPD and measure whether UDS normalizes' },
            { label: 'D', text: 'Compare XP cells to normal cells using a fluorescent stain for CPD lesions' },
          ],
          correctAnswer: 'B',
          explanation: 'To separate excision from resynthesis defects: (1) measuring excised oligomer fragments directly tests the excision step; (2) a radioactive nucleotide pulse-label tests resynthesis. If excision fragments are absent but resynthesis is normal, the defect is in excision. If fragments are present but labeling is absent, the defect is downstream (resynthesis or ligation).',
          wrongAnswerExplanations: {
            A: 'Dose-response quantifies UV sensitivity but does not distinguish which NER step is defective.',
            C: 'Wild-type XPD transfection tests whether XPD specifically is the defect, not whether excision vs. resynthesis is impaired — it addresses genetic complementation, not mechanistic step.',
            D: 'Fluorescent CPD staining measures lesion persistence (repair outcome) but does not resolve whether excision or resynthesis is the deficient step.',
          },
          teachingPoint: 'To pinpoint a pathway step, directly measure the product of that step. Excision: detect oligomer fragment. Resynthesis: detect newly incorporated nucleotides via pulse-labeling.',
          relatedTopics: ['experimental design', 'NER mechanism', 'pulse-label assay', 'repair pathway dissection'],
        },
        {
          id: 'mcat1-bb-004',
          sectionId: 'bio-biochem',
          passageId: 'bb-p1',
          questionType: 'passage',
          discipline: 'Biology',
          contentCategory: 'DNA damage and cancer',
          foundationalConcept: 'FC 1',
          scientificSkill: 'Skill 2',
          difficulty: 'medium',
          question: 'XP patients develop skin cancers at dramatically elevated rates. Based on the passage, which sequence of events best explains this elevated cancer risk?',
          choices: [
            { label: 'A', text: 'Reduced NER → persistent UV lesions → misreplication → mutations in oncogenes or tumor suppressors → cancer' },
            { label: 'B', text: 'Reduced NER → immune suppression → viral infection → insertional mutagenesis → cancer' },
            { label: 'C', text: 'Increased apoptosis in XP cells → tissue regeneration → proliferative error → cancer' },
            { label: 'D', text: 'UV exposure → direct protein damage → enzyme dysfunction → metabolic crisis → cancer' },
          ],
          correctAnswer: 'A',
          explanation: 'XP cells cannot repair CPDs and 6-4 photoproducts. Persistent UV lesions cause misreplication (translesion synthesis errors), leading to C→T or CC→TT mutations — the UV signature mutations. These accumulate in key genes (e.g., TP53, RAS), driving carcinogenesis.',
          wrongAnswerExplanations: {
            B: 'Immune suppression and viral mutagenesis are not the primary mechanism described. UV-induced DNA damage is directly mutagenic without requiring viral mediation.',
            C: 'Apoptosis in XP cells could occur, but the primary cancer-driving mechanism is mutagenesis from unrepaired lesions during replication, not tissue regeneration errors.',
            D: 'UV-induced carcinogenesis is DNA-mediated (mutations), not from protein damage. Enzymatic dysfunction from protein damage is not the cancer pathway here.',
          },
          teachingPoint: 'XP cancer mechanism: NER defect → unrepaired UV lesions persist → during S phase, replication over lesions causes UV-signature mutations → accumulation in tumor suppressor/oncogene loci → cancer.',
          relatedTopics: ['XP and cancer', 'UV mutagenesis', 'tumor suppressor mutations', 'replication fidelity'],
        },
        {
          id: 'mcat1-bb-005',
          sectionId: 'bio-biochem',
          passageId: 'bb-p1',
          questionType: 'passage',
          discipline: 'Biology',
          contentCategory: 'DNA replication and repair',
          foundationalConcept: 'FC 1',
          scientificSkill: 'Skill 2',
          difficulty: 'hard',
          question: 'TC-NER is activated when RNA polymerase II stalls at a lesion. How does this mechanism benefit transcriptionally active genes compared to silent genes?',
          choices: [
            { label: 'A', text: 'TC-NER preferentially repairs the template strand of active genes, ensuring that transcription of essential proteins resumes quickly.' },
            { label: 'B', text: 'TC-NER is slower than GG-NER and therefore delays repair of active genes.' },
            { label: 'C', text: 'TC-NER only repairs the coding strand, leaving the template strand permanently damaged.' },
            { label: 'D', text: 'TC-NER operates in G1 phase only, limiting repair to pre-replication cells.' },
          ],
          correctAnswer: 'A',
          explanation: 'TC-NER uses stalled RNA Pol II as the lesion sensor, targeting damage specifically on the template strand of actively transcribed genes. This provides faster, preferential repair of the template strand relative to silent genes, which rely on slower GG-NER. This ensures rapid restoration of transcription for important actively expressed genes.',
          wrongAnswerExplanations: {
            B: 'TC-NER is generally faster than GG-NER for the template strand of active genes, not slower. The stalled polymerase rapidly recruits repair factors.',
            C: 'TC-NER repairs the template strand (the one being read by RNA Pol II), not the coding strand. The damaged template strand is what blocks transcription.',
            D: 'NER can operate throughout the cell cycle. TC-NER is not phase-restricted — transcription occurs in G1, S, and G2.',
          },
          teachingPoint: 'TC-NER targets the template strand of actively transcribed genes, providing faster repair where stalled RNA Pol II signals damage. This ensures essential transcription resumes quickly.',
          relatedTopics: ['TC-NER vs. GG-NER', 'RNA polymerase stalling', 'preferential template strand repair', 'transcription-coupled repair'],
        },
      ],
    },
    {
      id: 'bb-p2',
      sectionId: 'bio-biochem',
      title: 'Passage 2',
      passageText: `Epidermal growth factor receptor (EGFR) is a receptor tyrosine kinase (RTK) that initiates the RAS-MAPK signaling cascade upon activation by EGF. Binding of EGF induces receptor dimerization, transphosphorylation of intracellular tyrosine residues, and recruitment of adaptor proteins including Grb2 and SOS. SOS functions as a guanine nucleotide exchange factor (GEF), catalyzing exchange of GDP for GTP on RAS, converting it from inactive (RAS-GDP) to active (RAS-GTP) form.

RAS is a small GTPase with intrinsic GTPase activity that hydrolyzes RAS-GTP → RAS-GDP, terminating signaling. This hydrolysis is accelerated by GTPase-activating proteins (GAPs). Downstream, RAS-GTP activates RAF → MEK → ERK kinases, ultimately phosphorylating transcription factors that drive cell proliferation.

Oncogenic mutations in RAS (e.g., G12V, Q61L) impair intrinsic GTPase activity and block GAP-stimulated hydrolysis, locking RAS in the GTP-bound active state. Such mutations are found in approximately 30% of all human cancers. Similarly, activating mutations in EGFR (present in ~10-15% of non-small-cell lung cancers) lead to ligand-independent receptor activation.

Researchers studying a lung adenocarcinoma cell line found constitutive ERK phosphorylation despite absence of EGF. Western blot analysis showed:
- EGFR phosphorylation: absent
- RAS-GTP levels: elevated
- ERK phosphorylation: elevated
- Treatment with RAF inhibitor: blocked ERK phosphorylation`,
      questions: [
        {
          id: 'mcat1-bb-006',
          sectionId: 'bio-biochem',
          passageId: 'bb-p2',
          questionType: 'passage',
          discipline: 'Biology',
          contentCategory: 'Cell signaling',
          foundationalConcept: 'FC 2: Highly organized assemblies of molecules, cells, and organs interact to carry out the functions of living organisms.',
          scientificSkill: 'Skill 2',
          difficulty: 'hard',
          question: 'Based on the western blot data, where in the EGFR-RAS-MAPK pathway is the most likely activating mutation in this cell line?',
          choices: [
            { label: 'A', text: 'EGFR — an activating mutation causes ligand-independent phosphorylation' },
            { label: 'B', text: 'RAS — an oncogenic mutation maintains RAS in the GTP-bound active state' },
            { label: 'C', text: 'ERK — a gain-of-function ERK mutation drives constitutive transcription' },
            { label: 'D', text: 'Grb2 — overexpression of Grb2 constitutively activates SOS' },
          ],
          correctAnswer: 'B',
          explanation: 'EGFR phosphorylation is absent, ruling out an EGFR mutation. Yet RAS-GTP is elevated and ERK is phosphorylated. The pattern — normal upstream signaling absent but constitutive downstream activation — localizes the mutation to RAS itself. An oncogenic RAS mutation (like G12V) locks RAS in the GTP-bound state independent of upstream EGFR signaling.',
          wrongAnswerExplanations: {
            A: 'EGFR phosphorylation is specifically described as absent, ruling out an EGFR activating mutation.',
            C: 'ERK phosphorylation is blocked by RAF inhibitor, confirming the activation is RAF-dependent (upstream of ERK). A primary ERK mutation would not be blocked by a RAF inhibitor.',
            D: 'If Grb2 overexpression activated the pathway, it would require EGFR phosphorylation to scaffold Grb2. With EGFR phosphorylation absent, a Grb2 mechanism cannot explain the observations.',
          },
          teachingPoint: 'Pathway logic: absent EGFR-P but elevated RAS-GTP → mutation between EGFR and RAS, specifically in RAS. This is the classic oncogenic RAS pattern seen in 30% of cancers.',
          relatedTopics: ['EGFR-RAS-MAPK pathway', 'oncogenic RAS', 'pathway mutation localization', 'signal transduction'],
        },
        {
          id: 'mcat1-bb-007',
          sectionId: 'bio-biochem',
          passageId: 'bb-p2',
          questionType: 'passage',
          discipline: 'Biology',
          contentCategory: 'Cell signaling',
          foundationalConcept: 'FC 2',
          scientificSkill: 'Skill 1',
          difficulty: 'medium',
          question: 'What is the role of SOS in the EGFR signaling cascade?',
          choices: [
            { label: 'A', text: 'SOS phosphorylates RAS, activating it directly' },
            { label: 'B', text: 'SOS catalyzes exchange of GDP for GTP on RAS, converting it to the active form' },
            { label: 'C', text: 'SOS accelerates GTP hydrolysis on RAS, terminating signaling' },
            { label: 'D', text: 'SOS dimerizes EGFR, initiating receptor transphosphorylation' },
          ],
          correctAnswer: 'B',
          explanation: 'SOS is a guanine nucleotide exchange factor (GEF). It catalyzes the release of GDP from RAS and its replacement with GTP, producing active RAS-GTP. This is explicitly stated in the passage: "SOS functions as a guanine nucleotide exchange factor (GEF), catalyzing exchange of GDP for GTP on RAS."',
          wrongAnswerExplanations: {
            A: 'RAS activation is not through phosphorylation but through GTP loading. RAS is not a substrate for SOS kinase activity — SOS is a GEF, not a kinase.',
            C: 'Accelerating GTP hydrolysis describes the role of GAPs (GTPase-activating proteins), which terminate signaling. SOS activates RAS; GAPs inactivate it.',
            D: 'EGFR dimerization is induced by EGF ligand binding, not by SOS. SOS functions downstream of dimerization to activate RAS.',
          },
          teachingPoint: 'SOS = GEF: catalyzes GDP→GTP exchange on RAS, activating it. GAP = opposite: accelerates GTP hydrolysis on RAS, inactivating it. Know these two regulatory proteins and their opposing functions.',
          relatedTopics: ['GEF', 'GAP', 'RAS activation', 'guanine nucleotide exchange', 'signal transduction'],
        },
        {
          id: 'mcat1-bb-008',
          sectionId: 'bio-biochem',
          passageId: 'bb-p2',
          questionType: 'passage',
          discipline: 'Biology',
          contentCategory: 'Cell signaling',
          foundationalConcept: 'FC 2',
          scientificSkill: 'Skill 2',
          difficulty: 'medium',
          question: 'A patient\'s tumor carries an oncogenic KRAS G12V mutation. An oncologist considers treating with an EGFR inhibitor (e.g., cetuximab). Based on the passage, why would this treatment likely be ineffective?',
          choices: [
            { label: 'A', text: 'EGFR inhibitors block receptor dimerization, which the KRAS mutation prevents anyway.' },
            { label: 'B', text: 'The KRAS G12V mutation locks RAS in the active GTP-bound state independently of EGFR, so blocking EGFR does not prevent downstream ERK activation.' },
            { label: 'C', text: 'EGFR inhibitors increase RAS GTPase activity, which is incompatible with the KRAS mutation.' },
            { label: 'D', text: 'KRAS mutations prevent EGF from binding its receptor, making the inhibitor redundant.' },
          ],
          correctAnswer: 'B',
          explanation: 'Oncogenic KRAS G12V bypasses upstream signaling by constitutively activating RAS regardless of EGFR status. If RAS is always active, inhibiting EGFR does nothing to reduce RAS-GTP levels or downstream ERK phosphorylation. This is the clinical rationale for why KRAS-mutant tumors do not respond to EGFR inhibitors.',
          wrongAnswerExplanations: {
            A: 'EGFR dimerization and KRAS mutation are independent mechanisms. The KRAS mutation does not prevent EGFR dimerization; it bypasses the need for EGFR activation entirely.',
            C: 'EGFR inhibitors block receptor kinase activity or ligand binding — they do not directly affect RAS GTPase activity.',
            D: 'KRAS mutations occur downstream of EGFR and do not affect EGF binding to the receptor.',
          },
          teachingPoint: 'Clinical corollary: KRAS-mutant cancers are resistant to EGFR inhibitors because constitutively active RAS bypasses EGFR. Testing for RAS mutations before EGFR-targeted therapy is now standard practice.',
          relatedTopics: ['KRAS mutation', 'EGFR inhibitor resistance', 'cetuximab', 'targeted therapy rationale'],
        },
        {
          id: 'mcat1-bb-009',
          sectionId: 'bio-biochem',
          passageId: 'bb-p2',
          questionType: 'passage',
          discipline: 'Biology',
          contentCategory: 'Cell signaling',
          foundationalConcept: 'FC 2',
          scientificSkill: 'Skill 1',
          difficulty: 'easy',
          question: 'Which of the following best describes the intrinsic mechanism that normally terminates RAS signaling?',
          choices: [
            { label: 'A', text: 'Proteolytic degradation of RAS protein by the ubiquitin-proteasome system' },
            { label: 'B', text: 'Phosphorylation of RAS by ERK in a negative feedback loop' },
            { label: 'C', text: 'Hydrolysis of GTP to GDP by RAS\'s intrinsic GTPase activity, accelerated by GAPs' },
            { label: 'D', text: 'Dissociation of RAS from the plasma membrane upon GTP binding' },
          ],
          correctAnswer: 'C',
          explanation: 'The passage states RAS has "intrinsic GTPase activity that hydrolyzes RAS-GTP → RAS-GDP, terminating signaling. This hydrolysis is accelerated by GAPs." When RAS-GTP → RAS-GDP, RAS can no longer interact with effectors and signaling ceases.',
          wrongAnswerExplanations: {
            A: 'Ubiquitin-proteasome degradation can regulate some signaling proteins, but it is not the described mechanism for turning off RAS. The passage cites GTPase activity.',
            B: 'ERK negative feedback can regulate upstream components in some pathways, but the passage describes GTPase hydrolysis, not phosphorylation, as the primary off-switch for RAS.',
            D: 'RAS is prenylated (farnesylated) and constitutively membrane-anchored. GTP binding does not cause membrane dissociation — it changes the conformation of RAS to interact with effectors.',
          },
          teachingPoint: 'RAS is a molecular switch: GTP-bound = ON, GDP-bound = OFF. The OFF switch is intrinsic GTPase activity (hydrolysis of GTP), accelerated by GAPs. Oncogenic mutations block this hydrolysis.',
          relatedTopics: ['RAS GTPase', 'GAP', 'molecular switch', 'signal termination'],
        },
        {
          id: 'mcat1-bb-010',
          sectionId: 'bio-biochem',
          passageId: 'bb-p2',
          questionType: 'passage',
          discipline: 'Biology',
          contentCategory: 'Cell signaling',
          foundationalConcept: 'FC 2',
          scientificSkill: 'Skill 3',
          difficulty: 'hard',
          question: 'Researchers want to test whether a new small molecule (compound X) inhibits RAS-GTP loading. Which experiment would most directly test this?',
          choices: [
            { label: 'A', text: 'Measure ERK phosphorylation in EGF-stimulated cells treated with compound X' },
            { label: 'B', text: 'Measure RAS-GTP levels in EGF-stimulated cells treated with compound X using a RAS-binding domain pull-down assay' },
            { label: 'C', text: 'Measure cell proliferation in compound X-treated vs. untreated cells' },
            { label: 'D', text: 'Measure EGFR phosphorylation in compound X-treated cells' },
          ],
          correctAnswer: 'B',
          explanation: 'To directly test RAS-GTP loading, measure RAS-GTP levels directly. A RAS-binding domain (RBD) pull-down assay selectively captures only GTP-bound RAS, providing a direct readout of RAS activation status. If compound X reduces RAS-GTP in stimulated cells, it inhibits GTP loading.',
          wrongAnswerExplanations: {
            A: 'ERK phosphorylation is downstream of RAS. Reduced ERK-P would suggest pathway inhibition but would not confirm the specific step — it could reflect EGFR inhibition or RAF/MEK inhibition, not RAS-GTP loading per se.',
            C: 'Cell proliferation is a distal endpoint reflecting many processes. It lacks specificity for RAS-GTP loading.',
            D: 'EGFR phosphorylation is upstream of RAS. Measuring it tests EGFR activity, not RAS-GTP loading.',
          },
          teachingPoint: 'To test a specific pathway step, measure that step\'s direct product. RAS-GTP loading → measure RAS-GTP (RBD pull-down). Downstream measurements (ERK-P, proliferation) are indirect and less specific.',
          relatedTopics: ['RAS-GTP assay', 'RBD pull-down', 'experimental specificity', 'pathway drug target'],
        },
      ],
    },
    {
      id: 'bb-p3',
      sectionId: 'bio-biochem',
      title: 'Passage 3',
      passageText: `Antidiuretic hormone (ADH, also called vasopressin) is a peptide hormone synthesized in the hypothalamus and released from the posterior pituitary in response to increased plasma osmolarity (>295 mOsm/kg) or decreased blood volume. ADH acts on principal cells of the collecting duct by binding to V2 receptors, activating adenylyl cyclase, increasing cAMP, and activating protein kinase A (PKA), which phosphorylates aquaporin-2 (AQP2). Phosphorylated AQP2 inserts into the apical membrane, dramatically increasing water permeability and allowing water to move from the tubular lumen into the hypertonic interstitium and ultimately into the bloodstream.

Diabetes insipidus (DI) is characterized by polyuria and polydipsia and results from either insufficient ADH secretion (central DI) or renal insensitivity to ADH (nephrogenic DI). Both forms result in dilute urine despite high plasma osmolarity.

Researchers compared urine and plasma osmolarity in four subject groups:

Table 1: Osmolarity measurements (mOsm/kg)

| Group               | Plasma osmolarity | Urine osmolarity |
|---------------------|-------------------|------------------|
| Normal              | 290               | 800              |
| Central DI          | 305               | 80               |
| Nephrogenic DI      | 308               | 75               |
| SIADH (ADH excess)  | 270               | 900              |

SIADH (syndrome of inappropriate ADH secretion) results from excessive ADH release despite low plasma osmolarity.`,
      figures: [
        {
          type: 'table',
          title: 'Table 1: Osmolarity measurements across groups',
          headers: ['Group', 'Plasma osmolarity (mOsm/kg)', 'Urine osmolarity (mOsm/kg)'],
          rows: [
            ['Normal', '290', '800'],
            ['Central DI', '305', '80'],
            ['Nephrogenic DI', '308', '75'],
            ['SIADH (ADH excess)', '270', '900'],
          ],
        },
      ],
      questions: [
        {
          id: 'mcat1-bb-011',
          sectionId: 'bio-biochem',
          passageId: 'bb-p3',
          questionType: 'passage',
          discipline: 'Biology',
          contentCategory: 'Renal physiology',
          foundationalConcept: 'FC 3: Complex systems of tissues and organs sense the internal and external environments of multicellular organisms, and through integrated mechanisms, maintain a stable internal environment.',
          scientificSkill: 'Skill 1',
          difficulty: 'easy',
          question: 'A patient is given exogenous ADH. In which group from Table 1 would you expect urine osmolarity to increase most significantly in response?',
          choices: [
            { label: 'A', text: 'Normal' },
            { label: 'B', text: 'Central DI' },
            { label: 'C', text: 'Nephrogenic DI' },
            { label: 'D', text: 'SIADH' },
          ],
          correctAnswer: 'B',
          explanation: 'Central DI results from insufficient ADH secretion. The kidney has intact V2 receptors and AQP2 machinery. Exogenous ADH will bind V2 receptors, trigger AQP2 insertion, and restore water reabsorption — dramatically increasing urine osmolarity. In nephrogenic DI, the kidney is insensitive to ADH, so exogenous ADH would not help.',
          wrongAnswerExplanations: {
            A: 'Normal subjects already have adequate ADH. Adding exogenous ADH would produce only a modest incremental increase from an already-functioning system.',
            C: 'Nephrogenic DI is caused by renal insensitivity to ADH (V2 receptor or AQP2 dysfunction). Exogenous ADH cannot overcome this resistance.',
            D: 'SIADH already has excessive ADH and maximally concentrated urine (900 mOsm/kg). Adding more ADH would have minimal additional effect.',
          },
          teachingPoint: 'Central DI: kidney works, ADH is absent → responds to exogenous ADH. Nephrogenic DI: ADH present/given but kidney cannot respond. This distinction is both diagnostic and therapeutic.',
          relatedTopics: ['central DI', 'nephrogenic DI', 'ADH therapy', 'desmopressin'],
        },
        {
          id: 'mcat1-bb-012',
          sectionId: 'bio-biochem',
          passageId: 'bb-p3',
          questionType: 'passage',
          discipline: 'Biology',
          contentCategory: 'Renal physiology',
          foundationalConcept: 'FC 3',
          scientificSkill: 'Skill 4',
          difficulty: 'medium',
          question: 'Based on Table 1, which pattern is consistent with SIADH?',
          choices: [
            { label: 'A', text: 'Low plasma osmolarity and high urine osmolarity' },
            { label: 'B', text: 'High plasma osmolarity and low urine osmolarity' },
            { label: 'C', text: 'Normal plasma osmolarity and normal urine osmolarity' },
            { label: 'D', text: 'Low plasma osmolarity and low urine osmolarity' },
          ],
          correctAnswer: 'A',
          explanation: 'Table 1 shows SIADH has plasma osmolarity of 270 mOsm/kg (low — below normal 290) and urine osmolarity of 900 mOsm/kg (very high). Excess ADH drives inappropriate water retention (diluting plasma) while maximally concentrating urine.',
          wrongAnswerExplanations: {
            B: 'High plasma + low urine osmolarity is the pattern of diabetes insipidus, not SIADH. In DI, water is lost in urine (dilute urine) while plasma concentrates.',
            C: 'Normal values in both would not represent SIADH, which is defined by inappropriate ADH causing pathological water retention.',
            D: 'Low plasma + low urine would suggest dilute urine despite dilute plasma — this does not match SIADH. Excess ADH concentrates urine (high urine osmolarity).',
          },
          teachingPoint: 'SIADH: excess ADH → retain water → dilute plasma (low osmolarity) + concentrated urine. DI is the opposite: no ADH effect → lose water in urine (low urine osmolarity) + concentrated plasma.',
          relatedTopics: ['SIADH', 'diabetes insipidus', 'osmolarity patterns', 'ADH excess vs. deficiency'],
        },
        {
          id: 'mcat1-bb-013',
          sectionId: 'bio-biochem',
          passageId: 'bb-p3',
          questionType: 'passage',
          discipline: 'Biology',
          contentCategory: 'Renal physiology',
          foundationalConcept: 'FC 3',
          scientificSkill: 'Skill 1',
          difficulty: 'medium',
          question: 'Through which intracellular second messenger does ADH increase AQP2 expression on the apical membrane of collecting duct cells?',
          choices: [
            { label: 'A', text: 'IP₃ and DAG via phospholipase C' },
            { label: 'B', text: 'cAMP via adenylyl cyclase and PKA' },
            { label: 'C', text: 'cGMP via guanylyl cyclase' },
            { label: 'D', text: 'Ca²⁺ via voltage-gated calcium channels' },
          ],
          correctAnswer: 'B',
          explanation: 'The passage explicitly states: ADH binds V2 receptors → activates adenylyl cyclase → increases cAMP → activates PKA → phosphorylates AQP2. The cAMP-PKA pathway is the second messenger cascade for V2 receptor signaling.',
          wrongAnswerExplanations: {
            A: 'IP₃/DAG via phospholipase C is the Gq pathway, associated with V1 receptors (vasoconstriction) and other GPCR signaling. V2 uses Gs → adenylyl cyclase → cAMP.',
            C: 'cGMP via guanylyl cyclase is used by atrial natriuretic peptide (ANP) and nitric oxide. ADH uses cAMP, not cGMP.',
            D: 'Voltage-gated Ca²⁺ channels are involved in muscle and neuronal signaling, not the principal cell AQP2 trafficking mechanism.',
          },
          teachingPoint: 'ADH → V2 receptor (Gs-coupled) → adenylyl cyclase → ↑cAMP → PKA → AQP2 phosphorylation and apical insertion. The Gs→cAMP→PKA pathway is the canonical V2 signaling cascade.',
          relatedTopics: ['V2 receptor', 'cAMP second messenger', 'PKA', 'AQP2 trafficking', 'GPCR signaling'],
        },
        {
          id: 'mcat1-bb-014',
          sectionId: 'bio-biochem',
          passageId: 'bb-p3',
          questionType: 'passage',
          discipline: 'Biology',
          contentCategory: 'Renal physiology',
          foundationalConcept: 'FC 3',
          scientificSkill: 'Skill 2',
          difficulty: 'medium',
          question: 'Loop diuretics (e.g., furosemide) block the Na-K-2Cl cotransporter in the thick ascending limb, preventing buildup of the renal medullary osmotic gradient. How would this affect ADH-driven water reabsorption in the collecting duct?',
          choices: [
            { label: 'A', text: 'Water reabsorption would increase because tubular fluid osmolarity rises.' },
            { label: 'B', text: 'Water reabsorption would be impaired because there is no interstitial osmotic gradient to drive water movement out of the collecting duct.' },
            { label: 'C', text: 'Water reabsorption would be unaffected because AQP2 insertion is independent of the osmotic gradient.' },
            { label: 'D', text: 'Water reabsorption would increase because loop diuretics stimulate ADH release.' },
          ],
          correctAnswer: 'B',
          explanation: 'ADH increases AQP2-mediated water permeability, but water movement out of the collecting duct requires an osmotic gradient — the hypertonic medullary interstitium. Loop diuretics eliminate this gradient by blocking NaCl accumulation in the medulla. With no gradient, water cannot move out even with AQP2 present. ADH is necessary but not sufficient without the countercurrent gradient.',
          wrongAnswerExplanations: {
            A: 'Without the medullary gradient, tubular fluid osmolarity does not drive water reabsorption. The driving force for water movement is the interstitial gradient, which is destroyed by loop diuretics.',
            C: 'AQP2 insertion creates water permeability, but permeability alone does not move water — an osmotic gradient is required. Permeability is a necessary but not sufficient condition.',
            D: 'Loop diuretics may cause volume depletion, which can trigger ADH release. However, more ADH cannot rescue water reabsorption if the medullary gradient is absent.',
          },
          teachingPoint: 'Water reabsorption = AQP2 permeability × osmotic driving force. Loop diuretics destroy the countercurrent gradient → eliminate driving force → no water reabsorption even with ADH-inserted AQP2.',
          relatedTopics: ['countercurrent mechanism', 'loop diuretics', 'medullary osmotic gradient', 'ADH and water reabsorption'],
        },
        {
          id: 'mcat1-bb-015',
          sectionId: 'bio-biochem',
          passageId: 'bb-p3',
          questionType: 'passage',
          discipline: 'Biology',
          contentCategory: 'Renal physiology',
          foundationalConcept: 'FC 3',
          scientificSkill: 'Skill 2',
          difficulty: 'easy',
          question: 'A patient presents with plasma osmolarity of 305 mOsm/kg, polyuria, and very dilute urine. Exogenous ADH administration completely normalizes urine osmolarity. Which diagnosis does this best support?',
          choices: [
            { label: 'A', text: 'Nephrogenic diabetes insipidus' },
            { label: 'B', text: 'SIADH' },
            { label: 'C', text: 'Central diabetes insipidus' },
            { label: 'D', text: 'Primary polydipsia' },
          ],
          correctAnswer: 'C',
          explanation: 'High plasma osmolarity + dilute urine = DI. Response to exogenous ADH confirms the kidneys are functional (V2 receptor and AQP2 intact) — the problem is insufficient ADH secretion. This is central DI. In nephrogenic DI, exogenous ADH would not restore urine concentration because the kidneys cannot respond.',
          wrongAnswerExplanations: {
            A: 'Nephrogenic DI: kidneys do not respond to ADH. Exogenous ADH would not normalize urine osmolarity.',
            B: 'SIADH presents with low plasma osmolarity (excess water retention), not high plasma osmolarity. This patient has concentrated plasma.',
            D: 'Primary polydipsia causes low plasma osmolarity (excessive water intake), not high plasma osmolarity. Urine in primary polydipsia is dilute from high fluid intake, but plasma osmolarity is low-normal.',
          },
          teachingPoint: 'ADH water deprivation/exogenous ADH test: Central DI → responds to ADH (kidneys normal). Nephrogenic DI → does not respond (kidneys insensitive). Plasma osmolarity distinguishes DI from primary polydipsia.',
          relatedTopics: ['central DI diagnosis', 'ADH challenge test', 'DI vs. primary polydipsia', 'water deprivation test'],
        },
      ],
    },
    {
      id: 'bb-p4',
      sectionId: 'bio-biochem',
      title: 'Passage 4',
      passageText: `Hemoglobin (Hb) is a tetrameric protein (α₂β₂ in adults) responsible for O₂ transport in erythrocytes. Unlike myoglobin, which binds O₂ with hyperbolic kinetics (Hill coefficient nH = 1.0), hemoglobin exhibits a sigmoidal O₂-dissociation curve reflecting positive cooperativity (nH ≈ 2.7). This cooperativity arises from a conformational equilibrium between two quaternary states: the low-affinity T-state (tense, deoxy) and the high-affinity R-state (relaxed, oxy). Binding of O₂ to one subunit shifts the equilibrium toward the R-state, increasing affinity of the remaining subunits.

Several allosteric effectors modulate Hb's O₂ affinity. Elevated partial pressure of CO₂ (PCO₂) and H⁺ — the Bohr effect — stabilize the T-state by protonating key histidine residues in the β-chains, promoting O₂ release in metabolically active tissues. 2,3-Bisphosphoglycerate (2,3-BPG), produced by erythrocytes via the Rapoport–Luebering shunt, binds preferentially to the central cavity formed by the four T-state subunits, further lowering O₂ affinity.

Fetal hemoglobin (HbF, α₂γ₂) carries γ-chains instead of β-chains. A critical amino acid difference at position 143 (Ser-143 in γ vs. His-143 in β) reduces 2,3-BPG binding affinity in HbF, because His-143 is a primary contact residue for 2,3-BPG in HbA. As a result, HbF is less stabilized in the T-state and maintains higher O₂ affinity than HbA under identical conditions — facilitating O₂ transfer from maternal to fetal circulation at the placenta.

Researchers measured O₂ saturation of HbA and HbF at five PO₂ values under three conditions (Table 1). All measurements were at pH 7.4, 37°C, and physiological 2,3-BPG levels except where indicated.`,
      figures: [
        {
          type: 'table' as const,
          title: 'Table 1. O₂ saturation (%) at various PO₂ values',
          headers: ['PO₂ (mmHg)', 'HbA (% saturation)', 'HbA + high PCO₂ (% saturation)', 'HbF (% saturation)'],
          rows: [
            ['10', '12', '8', '22'],
            ['19', '35', '27', '51'],
            ['26', '50', '38', '68'],
            ['40', '75', '62', '87'],
            ['100', '97', '92', '98'],
          ],
        },
      ],
      questions: [
        {
          id: 'mcat1-bb-021',
          sectionId: 'bio-biochem',
          passageId: 'bb-p4',
          questionType: 'passage',
          discipline: 'Biochemistry',
          contentCategory: 'Structure and function of proteins',
          foundationalConcept: 'FC 1',
          scientificSkill: 'Skill 4',
          difficulty: 'medium',
          question: 'Based on Table 1, what is the approximate P50 (PO₂ at which Hb is 50% saturated) of fetal hemoglobin (HbF)?',
          choices: [
            { label: 'A', text: '10 mmHg' },
            { label: 'B', text: '19 mmHg' },
            { label: 'C', text: '26 mmHg' },
            { label: 'D', text: '40 mmHg' },
          ],
          correctAnswer: 'B',
          explanation: 'P50 is the PO₂ at which hemoglobin is 50% saturated. From Table 1, at PO₂ = 19 mmHg, HbF is 51% saturated — very close to 50%. Therefore the P50 of HbF is approximately 19 mmHg. For comparison, HbA reaches exactly 50% at PO₂ = 26 mmHg, confirming HbF has a lower P50 (higher O₂ affinity) and a left-shifted dissociation curve.',
          wrongAnswerExplanations: {
            A: 'At PO₂ = 10 mmHg, HbF is only 22% saturated — far below 50%. This point lies to the left of the P50.',
            C: 'PO₂ = 26 mmHg is the P50 of HbA (50% saturation), not HbF. At this PO₂, HbF is already 68% saturated, confirming HbF\'s P50 is lower than 26 mmHg.',
            D: 'At PO₂ = 40 mmHg, HbF is 87% saturated — far above 50%. This lies well to the right of the P50.',
          },
          teachingPoint: 'P50 is the PO₂ at 50% O₂ saturation. HbF has a lower P50 (~19 mmHg) than HbA (~26 mmHg), reflecting higher O₂ affinity due to reduced 2,3-BPG binding (γ-chains lack the His-143 contact residue).',
          relatedTopics: ['hemoglobin P50', 'fetal hemoglobin', 'O₂-dissociation curve', '2,3-BPG', 'hemoglobin affinity'],
        },
        {
          id: 'mcat1-bb-022',
          sectionId: 'bio-biochem',
          passageId: 'bb-p4',
          questionType: 'passage',
          discipline: 'Biochemistry',
          contentCategory: 'Structure and function of proteins',
          foundationalConcept: 'FC 1',
          scientificSkill: 'Skill 2',
          difficulty: 'medium',
          question: 'Based on the passage, which mechanism best explains the rightward shift in O₂ saturation seen in the HbA + high PCO₂ condition compared to normal HbA in Table 1?',
          choices: [
            { label: 'A', text: 'CO₂ directly competes with O₂ for the heme iron binding site on each Hb subunit' },
            { label: 'B', text: 'Elevated PCO₂ lowers pH by generating H⁺, which protonates β-chain histidine residues and stabilizes the low-affinity T-state' },
            { label: 'C', text: 'High CO₂ permanently denatures the quaternary structure of hemoglobin, reducing total O₂-carrying capacity' },
            { label: 'D', text: 'CO₂ increases 2,3-BPG synthesis, and the resulting 2,3-BPG then stabilizes the R-state to promote O₂ release' },
          ],
          correctAnswer: 'B',
          explanation: 'The Bohr effect: CO₂ + H₂O → H₂CO₃ → H⁺ + HCO₃⁻. The generated H⁺ protonates key histidine residues (notably His146 of the β-chain) and N-terminal amino groups of the α-chains. Protonation stabilizes the T-state → lower O₂ affinity → rightward shift in the dissociation curve → O₂ is released to metabolically active tissues where PCO₂ and [H⁺] are elevated.',
          wrongAnswerExplanations: {
            A: 'CO₂ and O₂ do not compete for the same binding site. CO₂ binds to N-terminal amino groups of hemoglobin chains (forming carbaminohemoglobin), not to the heme iron. O₂ binds the heme iron (Fe²⁺).',
            C: 'CO₂ at physiological levels does not denature hemoglobin. The Bohr effect is a fully reversible allosteric conformational change, not irreversible denaturation.',
            D: '2,3-BPG stabilizes the T-state (low affinity), not the R-state. Furthermore, CO₂ does not directly drive 2,3-BPG synthesis — that is regulated by the Rapoport–Luebering shunt in response to other signals.',
          },
          teachingPoint: 'Bohr effect: elevated CO₂ → low pH → H⁺ protonates Hb → T-state stabilized → rightward O₂ curve shift → enhanced O₂ delivery to active tissues. This is the physiological adaptation allowing Hb to release more O₂ precisely where it is most needed.',
          relatedTopics: ['Bohr effect', 'hemoglobin allostery', 'T-state vs R-state', 'O₂ delivery', 'carbonic anhydrase'],
        },
        {
          id: 'mcat1-bb-023',
          sectionId: 'bio-biochem',
          passageId: 'bb-p4',
          questionType: 'passage',
          discipline: 'Biochemistry',
          contentCategory: 'Structure and function of proteins',
          foundationalConcept: 'FC 1',
          scientificSkill: 'Skill 1',
          difficulty: 'medium',
          question: 'According to the passage, why does HbF (α₂γ₂) bind O₂ with greater affinity than HbA (α₂β₂) under identical conditions?',
          choices: [
            { label: 'A', text: 'HbF γ-chains carry Ser-143 instead of His-143, reducing 2,3-BPG binding affinity and thus decreasing T-state stabilization' },
            { label: 'B', text: 'HbF contains four heme groups while HbA contains only two, allowing more O₂ to be bound per molecule' },
            { label: 'C', text: 'Fetal erythrocytes have more active mitochondria that generate higher intracellular O₂ partial pressures' },
            { label: 'D', text: 'HbF subunits form a dimer rather than a tetramer, eliminating cooperativity and conferring a high baseline affinity' },
          ],
          correctAnswer: 'A',
          explanation: 'The passage states that Ser-143 in the γ-chain (vs. His-143 in the β-chain) reduces 2,3-BPG binding affinity in HbF, because His-143 is a key 2,3-BPG contact residue. Since 2,3-BPG stabilizes the low-affinity T-state, reduced 2,3-BPG binding means HbF is less locked in the T-state → higher O₂ affinity → left-shifted dissociation curve.',
          wrongAnswerExplanations: {
            B: 'Both HbA and HbF are tetramers with four subunits and four heme groups each. Neither has more heme groups than the other.',
            C: 'Mature erythrocytes lack mitochondria entirely. They generate ATP exclusively through anaerobic glycolysis. HbF\'s affinity advantage is a structural difference in subunit composition, not mitochondrial activity.',
            D: 'HbF is a tetramer (α₂γ₂), not a dimer. The key difference is the γ-chain amino acid composition affecting 2,3-BPG binding, as stated in the passage.',
          },
          teachingPoint: 'HbF has higher O₂ affinity than HbA because γ-chains (Ser-143) bind 2,3-BPG less avidly than β-chains (His-143). Less 2,3-BPG binding = less T-state stabilization = higher O₂ affinity = left-shifted curve = efficient O₂ extraction from maternal blood at the placenta.',
          relatedTopics: ['fetal hemoglobin', 'gamma chains', '2,3-BPG mechanism', 'placental gas exchange', 'T-state stabilization'],
        },
        {
          id: 'mcat1-bb-024',
          sectionId: 'bio-biochem',
          passageId: 'bb-p4',
          questionType: 'passage',
          discipline: 'Biochemistry',
          contentCategory: 'Structure and function of proteins',
          foundationalConcept: 'FC 1',
          scientificSkill: 'Skill 3',
          difficulty: 'hard',
          question: 'A researcher wants to determine whether the Bohr effect\'s rightward shift is mediated exclusively through pH change or also involves direct CO₂ binding to hemoglobin. Which experimental design would best distinguish these two mechanisms?',
          choices: [
            { label: 'A', text: 'Compare O₂-dissociation curves of purified HbA solutions at identical pH but different PCO₂ values, with pH held constant by a strong buffer' },
            { label: 'B', text: 'Compare O₂-dissociation curves of HbA and HbF at the same elevated PCO₂' },
            { label: 'C', text: 'Measure intracellular 2,3-BPG concentrations in erythrocytes exposed to high PCO₂ to assess whether CO₂ acts through 2,3-BPG' },
            { label: 'D', text: 'Perform western blots on hemoglobin from erythrocytes at high and low PCO₂ to detect post-translational modifications' },
          ],
          correctAnswer: 'A',
          explanation: 'To isolate whether CO₂ acts through pH vs. direct binding (carbamino formation), hold pH constant while varying PCO₂. If a rightward shift occurs at high PCO₂ even when pH is buffered to remain identical, the shift must arise from direct CO₂ binding. If no shift occurs at fixed pH, the Bohr effect is entirely pH-mediated. This separation-of-variables design eliminates pH as a confounding variable.',
          wrongAnswerExplanations: {
            B: 'Comparing HbA vs. HbF at high PCO₂ would reveal differences due to γ vs. β chain structure and 2,3-BPG binding, not resolve whether the Bohr effect operates through pH or direct CO₂. This tests subunit structural differences, not the CO₂ mechanism.',
            C: 'Measuring 2,3-BPG levels explores a third potential mechanism (CO₂ → 2,3-BPG) but does not resolve whether the primary Bohr effect is pH-mediated vs. direct CO₂ binding. It also does not directly measure the O₂ curve shift.',
            D: 'Western blots detect protein levels or large covalent modifications. They cannot detect the subtle conformational change underlying the Bohr effect or distinguish carbamino formation from pH effects on Hb.',
          },
          teachingPoint: 'Separation-of-variables experimental design: to distinguish mechanism A (pH change) from mechanism B (direct CO₂ binding), hold the variable that causes A constant while varying the independent variable. If the outcome still changes, mechanism B is confirmed.',
          relatedTopics: ['Bohr effect mechanism', 'carbaminohemoglobin', 'experimental controls', 'O₂-dissociation curve', 'CO₂ transport'],
        },
        {
          id: 'mcat1-bb-025',
          sectionId: 'bio-biochem',
          passageId: 'bb-p4',
          questionType: 'passage',
          discipline: 'Biochemistry',
          contentCategory: 'Structure and function of proteins',
          foundationalConcept: 'FC 1',
          scientificSkill: 'Skill 4',
          difficulty: 'medium',
          question: 'Based on Table 1, at which PO₂ range is the difference in O₂ saturation between HbA and HbF most functionally significant for fetal gas exchange at the placenta?',
          choices: [
            { label: 'A', text: '90–100 mmHg, where both HbA and HbF are nearly fully saturated' },
            { label: 'B', text: '19–40 mmHg, where HbF is substantially more saturated than HbA, creating a thermodynamic gradient for O₂ transfer from maternal to fetal blood' },
            { label: 'C', text: '0–10 mmHg, where neither HbA nor HbF shows significant O₂ binding' },
            { label: 'D', text: 'Above 100 mmHg, where hyperbaric conditions equalize O₂ delivery between the two species' },
          ],
          correctAnswer: 'B',
          explanation: 'Placental intervillous PO₂ is approximately 30–50 mmHg. At PO₂ = 40 mmHg, Table 1 shows HbA is 75% saturated while HbF is 87% saturated — a 12-percentage-point difference. This gradient drives O₂ transfer from maternal HbA (releasing O₂) to fetal HbF (loading O₂). At very high PO₂ both Hbs are nearly fully saturated (trivial difference); at very low PO₂ neither carries meaningful O₂.',
          wrongAnswerExplanations: {
            A: 'At 100 mmHg, HbA is 97% and HbF is 98% saturated — only 1 percentage point difference. No meaningful transfer gradient exists at these high PO₂ values (which occur in pulmonary capillaries, not the placenta).',
            C: 'At 10 mmHg, HbA is 12% and HbF is 22% saturated. While a 10-point difference exists, PO₂ rarely falls this low at the placenta under physiological conditions and neither Hb carries much O₂ here.',
            D: 'Above 100 mmHg is hyperoxic and not relevant to normal placental physiology. Both Hbs are already nearly maximally saturated at 100 mmHg, so higher PO₂ adds no meaningful transfer gradient.',
          },
          teachingPoint: 'Placental gas exchange occurs at PO₂ ≈ 30–50 mmHg. HbF\'s left-shifted curve produces the largest saturation difference relative to HbA in this mid-range, creating the thermodynamic gradient for O₂ transfer from maternal blood to fetal blood.',
          relatedTopics: ['placental gas exchange', 'O₂ transfer gradient', 'fetal hemoglobin function', 'P50 comparison', 'PO₂ at placenta'],
        },
      ],
    },
    {
      id: 'bb-p5',
      sectionId: 'bio-biochem',
      title: 'Passage 5',
      passageText: `The tumor suppressor p53 is a transcription factor that coordinates the cellular response to genotoxic stress. Under normal conditions, p53 protein is maintained at very low levels by MDM2, an E3 ubiquitin ligase that continuously binds p53, adds polyubiquitin chains, and targets it for proteasomal degradation. This constitutive turnover keeps p53 inactive in the absence of damage.

When DNA is damaged — by ionizing radiation, UV light, chemotherapy, or replication stress — the ATM and ATR kinases are activated. These kinases phosphorylate p53 at multiple residues; phosphorylation at serine 15 (Ser15) directly disrupts the MDM2–p53 binding interface, preventing ubiquitination. Stabilized p53 accumulates and transcriptionally activates target genes: CDKN1A (encoding p21, a broad CDK inhibitor that arrests the cell cycle at G1/S), BAX (a pro-apoptotic BCL-2 family member that promotes mitochondrial cytochrome c release), and MDM2 itself — creating a negative-feedback loop to limit the response once repair is complete.

Researchers examined p53 and p21 protein levels by western blot in four cell lines after UV irradiation: (1) wild-type (WT) cells, (2) TP53-null cells (p53 knockout), (3) cells stably overexpressing MDM2, and (4) cells in which ATM was knocked out. Protein levels were measured at 2, 4, and 6 hours post-UV and are expressed relative to WT at 6 hours (Table 1). In WT cells, p53 rose sharply by 2 hours and p21 followed by 4 hours. TP53-null cells showed no induction of either protein. MDM2-overexpressing cells showed blunted p53 stabilization and minimal p21 induction. ATM-knockout cells displayed delayed p53 stabilization with modest accumulation by 6 hours (presumably from residual ATR activity) and correspondingly delayed p21 induction.`,
      figures: [
        {
          type: 'table' as const,
          title: 'Table 1. p53 and p21 protein levels (relative to WT at 6 hr post-UV)',
          headers: ['Cell line', 'p53 (2 hr)', 'p53 (6 hr)', 'p21 (4 hr)', 'p21 (6 hr)'],
          rows: [
            ['WT', '8.2', '10.5', '4.0', '6.3'],
            ['TP53-null', '0.1', '0.1', '0.1', '0.1'],
            ['MDM2-overexpressing', '1.2', '1.0', '0.5', '0.6'],
            ['ATM-knockout', '1.4', '5.8', '0.8', '3.2'],
          ],
        },
      ],
      questions: [
        {
          id: 'mcat1-bb-026',
          sectionId: 'bio-biochem',
          passageId: 'bb-p5',
          questionType: 'passage',
          discipline: 'Biology',
          contentCategory: 'Cell cycle and apoptosis',
          foundationalConcept: 'FC 1',
          scientificSkill: 'Skill 4',
          difficulty: 'medium',
          question: 'Based on Table 1, which comparison most directly demonstrates that p21 induction following UV irradiation is p53-dependent?',
          choices: [
            { label: 'A', text: 'WT vs. MDM2-overexpressing cells — MDM2 directly inhibits p21 transcription' },
            { label: 'B', text: 'WT vs. TP53-null cells — in the absence of p53, p21 is not induced despite identical UV irradiation' },
            { label: 'C', text: 'WT vs. ATM-knockout cells — ATM directly phosphorylates and activates p21 protein' },
            { label: 'D', text: 'MDM2-overexpressing vs. TP53-null cells — MDM2 is the primary regulator of p21 levels' },
          ],
          correctAnswer: 'B',
          explanation: 'TP53-null cells receive the same UV dose but show no p21 induction (0.1 at all time points), while WT cells show robust p21 induction (4.0 at 4 hr, 6.3 at 6 hr). The only experimental difference between these two conditions is the presence of p53 — this directly demonstrates that p21 induction requires p53. The WT vs. MDM2-overexpressing comparison reflects indirect effects through p53 suppression; ATM-KO still allows some p53 and p21 at 6 hr, not a clean null phenotype.',
          wrongAnswerExplanations: {
            A: 'MDM2 does not directly inhibit p21 transcription. MDM2 ubiquitinates and degrades p53 — any effect on p21 is indirect via reduced p53 availability. This comparison cannot distinguish MDM2\'s direct vs. indirect effects on p21.',
            C: 'ATM does not directly phosphorylate or activate p21 protein. ATM activates p53 (by phosphorylating Ser15). In ATM-KO cells, p53 still accumulates by 6 hours (5.8) via residual ATR activity, and p21 follows (3.2), confirming p21 responds to p53, not ATM directly.',
            D: 'MDM2 regulates p53 stability, not p21 directly. The MDM2-overexpressing vs. TP53-null comparison cannot isolate p53 dependence of p21, because both conditions suppress p21 for different reasons (MDM2 via p53 degradation; TP53-null via absent p53 protein).',
          },
          teachingPoint: 'Genetic loss-of-function is the cleanest way to establish necessity: TP53-null cells show no p21 induction despite UV, proving p21 transcription requires p53. This null phenotype cannot be explained by other variables changed between conditions.',
          relatedTopics: ['p53 target genes', 'p21/CDKN1A', 'G1 checkpoint', 'genetic knockouts', 'p53-dependent transcription'],
        },
        {
          id: 'mcat1-bb-027',
          sectionId: 'bio-biochem',
          passageId: 'bb-p5',
          questionType: 'passage',
          discipline: 'Biology',
          contentCategory: 'Cell cycle and apoptosis',
          foundationalConcept: 'FC 1',
          scientificSkill: 'Skill 2',
          difficulty: 'medium',
          question: 'According to the passage, why does MDM2 overexpression reduce p53 and p21 levels even after UV irradiation, despite ATM phosphorylating p53 at Ser15?',
          choices: [
            { label: 'A', text: 'MDM2 competes with ATM for the Ser15 site on p53, blocking ATM-mediated phosphorylation' },
            { label: 'B', text: 'Excess MDM2 ubiquitinates and degrades p53 faster than Ser15 phosphorylation can protect it, keeping p53 levels insufficient to transcribe CDKN1A' },
            { label: 'C', text: 'Overexpressed MDM2 directly binds p21 protein and prevents it from entering the nucleus' },
            { label: 'D', text: 'Excess MDM2 degrades ATM kinase, eliminating the Ser15 phosphorylation signal' },
          ],
          correctAnswer: 'B',
          explanation: 'MDM2 is an E3 ubiquitin ligase whose rate of p53 ubiquitination is concentration-dependent. Even when ATM phosphorylates Ser15 to partially disrupt MDM2 binding, greatly elevated MDM2 levels can still ubiquitinate and degrade enough p53 to keep it below the threshold needed for CDKN1A transcription — producing the blunted p21 response seen in Table 1 (p53 at 6 hr: 1.0; p21 at 6 hr: 0.6 vs. WT 10.5 and 6.3).',
          wrongAnswerExplanations: {
            A: 'MDM2 binds p53\'s transactivation domain (N-terminus), not the Ser15 phosphorylation site. ATM phosphorylates Ser15 to disrupt MDM2 binding, not the other way around. They target different regions of p53.',
            C: 'MDM2 does not bind or regulate p21 protein. MDM2\'s relevant substrates include p53, Rb, and a few others. Effects on p21 are always indirect — through p53 degradation reducing CDKN1A transcription.',
            D: 'MDM2 does not degrade ATM. MDM2 is an E3 ubiquitin ligase whose primary target here is p53. There is no passage evidence that MDM2 controls ATM levels.',
          },
          teachingPoint: 'MDM2 overexpression (found in ~7% of human cancers as an alternative to TP53 mutation) creates a "dose vs. protection" competition: even if ATM partially protects p53 via Ser15 phosphorylation, excess MDM2 can still degrade enough p53 to prevent threshold-level accumulation required for transcriptional activation.',
          relatedTopics: ['MDM2 mechanism', 'p53 ubiquitination', 'proteasomal degradation', 'E3 ubiquitin ligase', 'MDM2 amplification in cancer'],
        },
        {
          id: 'mcat1-bb-028',
          sectionId: 'bio-biochem',
          passageId: 'bb-p5',
          questionType: 'passage',
          discipline: 'Biology',
          contentCategory: 'Cell cycle and apoptosis',
          foundationalConcept: 'FC 1',
          scientificSkill: 'Skill 1',
          difficulty: 'hard',
          question: 'The passage notes that MDM2 is itself a transcriptional target of p53, creating a negative-feedback loop. What is the most likely biological purpose of this feedback?',
          choices: [
            { label: 'A', text: 'To ensure p53 levels continue rising after DNA repair, maintaining permanent cell cycle arrest as a protective measure' },
            { label: 'B', text: 'To limit the duration and magnitude of the p53 response, allowing cell cycle resumption after successful DNA repair' },
            { label: 'C', text: 'To amplify the apoptotic signal by increasing MDM2\'s pro-apoptotic function at the mitochondrial membrane' },
            { label: 'D', text: 'To prevent MDM2 from being expressed during DNA damage so p53 can accumulate without inhibition' },
          ],
          correctAnswer: 'B',
          explanation: 'Negative-feedback loops limit and terminate responses. When p53 activates MDM2 transcription → MDM2 protein rises → MDM2 ubiquitinates p53 → p53 levels fall → p21 and BAX transcription decrease → cells can resume normal cycling once DNA is repaired. Without this feedback, p53 would remain elevated even after successful repair, causing unnecessary apoptosis or permanent senescence in cells that have fixed their damage.',
          wrongAnswerExplanations: {
            A: 'Negative feedback by definition reduces the stimulus over time. Continued p53 elevation would require positive feedback (amplification). The p53→MDM2→p53 loop is designed to restore baseline, not sustain activation after repair.',
            C: 'MDM2 has no established pro-apoptotic function at the mitochondria. It is primarily an E3 ubiquitin ligase that promotes p53 degradation. The pro-apoptotic arm of the p53 response involves BAX and PUMA transcription, not MDM2.',
            D: 'The opposite is true: MDM2 is induced by p53 as a consequence of p53 activation. p53 accumulates first (via ATM-mediated Ser15 phosphorylation), then transcribes MDM2. MDM2 expression is a delayed consequence of p53 activity, not suppressed during damage.',
          },
          teachingPoint: 'p53→MDM2 negative feedback: the same event that stabilizes p53 (DNA damage) also programs its eventual inactivation via p53-driven MDM2 transcription. This proportionate, self-limiting response ensures arrested/apoptotic decisions are time-limited and reversible after repair.',
          relatedTopics: ['p53-MDM2 feedback loop', 'negative feedback', 'cell cycle restoration after repair', 'transcriptional autoregulation', 'p53 response duration'],
        },
        {
          id: 'mcat1-bb-029',
          sectionId: 'bio-biochem',
          passageId: 'bb-p5',
          questionType: 'passage',
          discipline: 'Biology',
          contentCategory: 'Cell cycle and apoptosis',
          foundationalConcept: 'FC 1',
          scientificSkill: 'Skill 3',
          difficulty: 'hard',
          question: 'A researcher wants to confirm that p53\'s ability to induce G1 cell cycle arrest specifically requires p21, independent of p53\'s other transcriptional targets. Which experimental approach best addresses this question?',
          choices: [
            { label: 'A', text: 'Measure p21 mRNA levels after UV irradiation by RT-PCR to confirm CDKN1A is transcribed in WT cells' },
            { label: 'B', text: 'Engineer a separation-of-function p53 mutant that activates MDM2 and BAX but cannot bind the CDKN1A promoter; compare G1 arrest to cells expressing WT p53 after UV irradiation' },
            { label: 'C', text: 'Overexpress p21 in TP53-null cells and observe whether G1 arrest occurs in the absence of DNA damage' },
            { label: 'D', text: 'Compare cell cycle arrest kinetics in WT vs. MDM2-overexpressing cells after UV irradiation' },
          ],
          correctAnswer: 'B',
          explanation: 'To determine whether p21 is specifically required (necessary) for p53-driven G1 arrest, you need a p53 that retains all functions except p21 induction — a "separation-of-function" mutant. If this mutant (which still activates MDM2 and BAX, confirming it is functional) fails to induce G1 arrest while WT p53 succeeds, then p21 is specifically required. This isolates p21\'s contribution from all other p53 targets.',
          wrongAnswerExplanations: {
            A: 'Measuring p21 mRNA confirms CDKN1A is a p53 transcriptional target but does not establish whether p21 is necessary for G1 arrest. Correlation between p21 induction and arrest is not the same as causation.',
            C: 'Overexpressing p21 in TP53-null cells tests whether p21 is sufficient for G1 arrest in the absence of p53 and damage — it tests sufficiency, not necessity. The question asks whether p21 is required for p53-driven G1 arrest.',
            D: 'MDM2-overexpressing cells have globally suppressed p53, reducing all p53 target genes simultaneously. This cannot isolate the specific contribution of p21 vs. other p53 targets (BAX, MDM2) to G1 arrest.',
          },
          teachingPoint: 'Separation-of-function mutants: to test whether target gene Y is specifically required for outcome Z, create an upstream regulator that activates all targets except Y, and compare Z. Overexpression → tests sufficiency; loss-of-function (KO or separation-of-function) → tests necessity.',
          relatedTopics: ['separation-of-function mutants', 'experimental necessity vs sufficiency', 'p21 and G1 arrest', 'CDK inhibitors', 'cell cycle checkpoints'],
        },
        {
          id: 'mcat1-bb-030',
          sectionId: 'bio-biochem',
          passageId: 'bb-p5',
          questionType: 'passage',
          discipline: 'Biology',
          contentCategory: 'Cell cycle and apoptosis',
          foundationalConcept: 'FC 1',
          scientificSkill: 'Skill 2',
          difficulty: 'medium',
          question: 'Based on the passage, what would you predict for p53 and p21 protein levels after UV irradiation in a cell line in which both TP53 and MDM2 are deleted (double knockout)?',
          choices: [
            { label: 'A', text: 'p53 protein would accumulate to very high levels because MDM2-mediated degradation is eliminated' },
            { label: 'B', text: 'p21 would accumulate to higher levels than in WT cells because MDM2 can no longer indirectly suppress p21 via p53 degradation' },
            { label: 'C', text: 'Neither p53 nor p21 would be induced, because the transcription factor (p53) required to activate CDKN1A is still absent' },
            { label: 'D', text: 'MDM2 deletion compensates for TP53 loss by activating an alternative p21 induction pathway' },
          ],
          correctAnswer: 'C',
          explanation: 'In a TP53/MDM2 double knockout, p53 protein is absent because the TP53 gene is deleted — there is no p53 mRNA or protein to stabilize. Without p53 as the transcriptional activator, CDKN1A cannot be induced regardless of MDM2 status. The TP53-null phenotype is epistatic to (dominant over) MDM2 deletion, because MDM2 acts upstream to regulate p53 stability; without p53 to act on, MDM2\'s presence or absence is irrelevant to p21 induction.',
          wrongAnswerExplanations: {
            A: 'p53 cannot accumulate in a TP53-null cell — the gene is deleted, so there is no p53 protein to stabilize. MDM2 deletion has no effect when there is no p53 substrate.',
            B: 'MDM2 does not directly target p21 for degradation. MDM2\'s ubiquitin ligase activity is directed at p53 and a small set of other substrates. Removing MDM2 cannot increase p21 levels in the absence of p53.',
            D: 'The passage provides no evidence of an MDM2-independent, p53-independent pathway for CDKN1A transcription. All data consistently show p21 requires p53 as its transcriptional activator.',
          },
          teachingPoint: 'Epistasis: when gene A regulates gene B (MDM2 regulates p53 stability), deleting A has no effect on B\'s function if B is already deleted. TP53-null is epistatic over MDM2-null for p21 induction because p53 is the direct transcriptional activator of CDKN1A — upstream regulation is irrelevant if the effector is absent.',
          relatedTopics: ['epistasis', 'gene regulation hierarchy', 'p53 as transcription factor', 'double knockout interpretation', 'CDKN1A regulation'],
        },
      ],
    },
  ],
  discreteQuestions: [
    {
      id: 'mcat1-bb-016',
      sectionId: 'bio-biochem',
      passageId: null,
      questionType: 'discrete',
      discipline: 'Biology',
      contentCategory: 'Genetics',
      foundationalConcept: 'FC 2',
      scientificSkill: 'Skill 1',
      difficulty: 'medium',
      question: 'Two parents are heterozygous carriers for an autosomal recessive disorder (Aa × Aa). The mother is X^A X^a (carrier for an X-linked recessive disorder) and the father is X^a Y (affected by the same X-linked disorder). What is the probability that a child is female AND has both the autosomal recessive disorder AND the X-linked disorder?',
      choices: [
        { label: 'A', text: '1/8' },
        { label: 'B', text: '1/16' },
        { label: 'C', text: '1/32' },
        { label: 'D', text: '1/4' },
      ],
      correctAnswer: 'B',
      explanation: 'Multiply the three independent probabilities. (1) P(aa) = 1/4 from Aa × Aa cross. (2) P(female child) = 1/2. (3) P(X^a X^a | female): father (X^a Y) always passes X^a to daughters; mother (X^A X^a) passes X^a with P = 1/2. Therefore P(X^a X^a | female) = 1/2. Combined: 1/4 × 1/2 × 1/2 = 1/16. Answer B is correct.',
      wrongAnswerExplanations: {
        A: '1/8 = 1/4 × 1/2 × 1 — this treats the X-linked probability in females as 1 (certainty), but P(X^a X^a | female) = 1/2 because only the mother\'s X^a transmission is uncertain (father always passes X^a to daughters).',
        C: '1/32 = 1/4 × 1/2 × 1/4 — this incorrectly treats X-linked inheritance as autosomal (P = 1/4 for "homozygous recessive"), ignoring that daughters always inherit X^a from an X^a Y father.',
        D: '1/4 gives only the autosomal recessive probability (P(aa)), ignoring both the requirement for a female child (×1/2) and the X-linked probability (×1/2).',
      },
      teachingPoint: 'For X-linked recessive in daughters: father (X^a Y) always passes X^a, so only the mother\'s allele transmission is probabilistic. Multiply independent probabilities: P(autosomal recessive) × P(female) × P(X^a X^a | female).',
      relatedTopics: ['autosomal recessive', 'X-linked recessive', 'dihybrid cross probability', 'inheritance patterns'],
    },
    {
      id: 'mcat1-bb-017',
      sectionId: 'bio-biochem',
      passageId: null,
      questionType: 'discrete',
      discipline: 'Biochemistry',
      contentCategory: 'Cellular respiration',
      foundationalConcept: 'FC 1',
      scientificSkill: 'Skill 1',
      difficulty: 'medium',
      question: 'The TCA cycle oxidizes acetyl-CoA, producing NADH, FADH₂, GTP, and CO₂. Per complete turn of the cycle (one acetyl-CoA), how many molecules of CO₂ are produced?',
      choices: [
        { label: 'A', text: '1' },
        { label: 'B', text: '2' },
        { label: 'C', text: '3' },
        { label: 'D', text: '4' },
      ],
      correctAnswer: 'B',
      explanation: 'Per turn of the TCA cycle, 2 molecules of CO₂ are released: one at the isocitrate dehydrogenase step (isocitrate → α-ketoglutarate) and one at the α-ketoglutarate dehydrogenase step (α-ketoglutarate → succinyl-CoA). These are the two decarboxylation steps. Note that the 2 carbons entering as acetyl-CoA are not the same 2 carbons leaving as CO₂ in the first cycle (carbon accounting takes 2 turns to fully oxidize entered carbons).',
      wrongAnswerExplanations: {
        A: '1 CO₂ would represent only one decarboxylation step. There are two in each TCA cycle turn.',
        C: '3 CO₂ is the count for pyruvate decarboxylation (1 CO₂) plus one full TCA turn (2 CO₂). Per TCA turn only, the count is 2.',
        D: '4 CO₂ is produced over two turns of the TCA cycle (4 total = 2 per turn × 2 turns). Per single turn: 2 CO₂.',
      },
      teachingPoint: 'TCA cycle per turn: 3 NADH, 1 FADH₂, 1 GTP, 2 CO₂. The two decarboxylations are at isocitrate dehydrogenase and α-ketoglutarate dehydrogenase.',
      relatedTopics: ['TCA cycle', 'citric acid cycle', 'decarboxylation', 'CO₂ production', 'NADH yield'],
    },
    {
      id: 'mcat1-bb-018',
      sectionId: 'bio-biochem',
      passageId: null,
      questionType: 'discrete',
      discipline: 'Biology',
      contentCategory: 'Cell membrane and transport',
      foundationalConcept: 'FC 2',
      scientificSkill: 'Skill 1',
      difficulty: 'easy',
      question: 'A large, polar molecule (MW 500 Da) is found to cross the cell membrane down its concentration gradient without energy expenditure. Which transport mechanism is most likely responsible?',
      choices: [
        { label: 'A', text: 'Simple diffusion through the phospholipid bilayer' },
        { label: 'B', text: 'Facilitated diffusion via a protein channel or carrier' },
        { label: 'C', text: 'Primary active transport via an ATP-driven pump' },
        { label: 'D', text: 'Secondary active transport coupled to an ion gradient' },
      ],
      correctAnswer: 'B',
      explanation: 'Large, polar molecules cannot cross the hydrophobic phospholipid bilayer by simple diffusion. Movement down the concentration gradient without energy expenditure = passive transport. Passive transport of large polar molecules requires protein channels or carriers — facilitated diffusion.',
      wrongAnswerExplanations: {
        A: 'Simple diffusion works for small, nonpolar molecules (O₂, CO₂) or very small uncharged molecules (H₂O via aquaporins). Large polar molecules cannot directly cross the hydrophobic bilayer.',
        C: 'Primary active transport (e.g., Na/K-ATPase) requires ATP and moves molecules against their gradient. Movement down the gradient without energy use rules this out.',
        D: 'Secondary active transport uses ion gradients as energy source — this is still energy-dependent transport (coupled to ion gradient). Movement without energy expenditure excludes this.',
      },
      teachingPoint: 'Large polar molecule + down gradient + no energy = facilitated diffusion (channel protein or carrier). Simple diffusion = small nonpolar. Active transport = against gradient or requires energy.',
      relatedTopics: ['membrane transport', 'facilitated diffusion', 'simple diffusion', 'active vs. passive transport'],
    },
    {
      id: 'mcat1-bb-019',
      sectionId: 'bio-biochem',
      passageId: null,
      questionType: 'discrete',
      discipline: 'Biology',
      contentCategory: 'Nervous system',
      foundationalConcept: 'FC 3',
      scientificSkill: 'Skill 1',
      difficulty: 'medium',
      question: 'During the rising phase of an action potential, which ion movement is primarily responsible for membrane depolarization?',
      choices: [
        { label: 'A', text: 'K⁺ flowing out of the cell through voltage-gated channels' },
        { label: 'B', text: 'Na⁺ flowing into the cell through voltage-gated channels' },
        { label: 'C', text: 'Cl⁻ flowing into the cell through voltage-gated channels' },
        { label: 'D', text: 'Ca²⁺ flowing into the cell through ligand-gated channels' },
      ],
      correctAnswer: 'B',
      explanation: 'During the rising phase, threshold depolarization opens voltage-gated Na⁺ channels. Na⁺ rushes in (down its concentration and electrical gradient) → inside becomes more positive → rapid depolarization toward +30–40 mV (approaching E_Na ≈ +60 mV). This is the defining ionic event of the upstroke.',
      wrongAnswerExplanations: {
        A: 'K⁺ outflow causes repolarization (the falling phase), not depolarization. Voltage-gated K⁺ channels open after Na⁺ channels, restoring the negative resting potential.',
        C: 'Cl⁻ influx would hyperpolarize the cell (making inside more negative), opposing depolarization. Cl⁻ does not drive the action potential upstroke.',
        D: 'Ca²⁺ influx through voltage-gated channels occurs at synaptic terminals to trigger neurotransmitter release, not during the classical somatic action potential upstroke.',
      },
      teachingPoint: 'Action potential phases: depolarization (upstroke) = Na⁺ in via voltage-gated Na⁺ channels; repolarization (downstroke) = K⁺ out via voltage-gated K⁺ channels + Na⁺ channel inactivation.',
      relatedTopics: ['action potential', 'voltage-gated Na⁺ channels', 'depolarization', 'membrane potential'],
    },
    {
      id: 'mcat1-bb-020',
      sectionId: 'bio-biochem',
      passageId: null,
      questionType: 'discrete',
      discipline: 'Biology',
      contentCategory: 'Immune system',
      foundationalConcept: 'FC 2',
      scientificSkill: 'Skill 1',
      difficulty: 'medium',
      question: 'An IgG antibody has two identical heavy chains and two identical light chains. Which region of the antibody is responsible for binding antigen?',
      choices: [
        { label: 'A', text: 'The Fc region of the heavy chain constant domains' },
        { label: 'B', text: 'The variable regions of both heavy and light chains (Fab region)' },
        { label: 'C', text: 'The hinge region connecting the two Fab arms' },
        { label: 'D', text: 'The constant region of the light chain (CL domain)' },
      ],
      correctAnswer: 'B',
      explanation: 'Antigen binding occurs in the Fab region, formed by the variable domains (V_H and V_L) of the heavy and light chains. The hypervariable loops (CDRs — complementarity-determining regions) within the variable domains create the antigen-binding site. The Fc region mediates effector functions (complement, FcR binding), not antigen binding.',
      wrongAnswerExplanations: {
        A: 'The Fc region (constant domains of heavy chains) mediates effector functions: complement activation, binding to Fc receptors on phagocytes, neonatal FcR for half-life. It does not bind antigen.',
        C: 'The hinge region provides flexibility between the two Fab arms and the Fc region. It does not directly contact antigen.',
        D: 'The constant region of the light chain contributes to Fab structure but the antigen-binding specificity resides in the variable regions of both chains, not the constant domains.',
      },
      teachingPoint: 'Antibody structure: Fab = variable regions of heavy + light chains = antigen binding. Fc = constant regions of heavy chains = effector functions. CDRs within variable regions determine specificity.',
      relatedTopics: ['antibody structure', 'Fab region', 'Fc region', 'variable vs. constant domains', 'CDRs'],
    },
    {
      id: 'mcat1-bb-031',
      sectionId: 'bio-biochem',
      passageId: null,
      questionType: 'discrete',
      discipline: 'Biochemistry',
      contentCategory: 'Amino acid structure and biochemistry',
      foundationalConcept: 'FC 1',
      scientificSkill: 'Skill 1',
      difficulty: 'medium',
      question: 'Histidine has a side chain pKa of approximately 6.0. At physiological pH (7.4), histidine most commonly functions in enzyme active sites as:',
      choices: [
        { label: 'A', text: 'A permanently negatively charged residue that stabilizes cationic transition states' },
        { label: 'B', text: 'An electron carrier that shuttles electrons between the enzyme and NAD⁺ cofactors' },
        { label: 'C', text: 'An acid-base catalyst that can readily donate or accept protons, enabling general-base or nucleophilic catalysis' },
        { label: 'D', text: 'A disulfide bond donor that cross-links polypeptide chains to maintain enzyme quaternary structure' },
      ],
      correctAnswer: 'C',
      explanation: 'At pH 7.4 (above pKa 6.0), histidine\'s imidazole side chain is predominantly neutral (deprotonated), but within approximately one pH unit of its pKa — meaning it can readily accept or donate a proton under physiological conditions. This proximity to physiological pH makes histidine uniquely suited as a general acid-base catalyst. In serine proteases (chymotrypsin, trypsin, elastase), the catalytic triad (His-Asp-Ser) uses histidine as a proton shuttle: acting as a general base to deprotonate Ser, then donating that proton to the leaving group.',
      wrongAnswerExplanations: {
        A: 'Histidine at pH 7.4 is largely neutral (imidazole deprotonated, net charge ~0), not permanently negatively charged. Aspartate (pKa ≈ 3.65) and glutamate (pKa ≈ 4.25) are the permanently ionized negatively charged amino acids at physiological pH.',
        B: 'Electron carrier function belongs to redox cofactors (NAD⁺/NADH, FAD/FADH₂) or metal centers. Amino acid side chains participate in proton transfer (acid-base) and nucleophilic catalysis, not direct electron shuttling.',
        D: 'Disulfide bonds form exclusively between cysteine residues via oxidation of their thiol (–SH) groups. Histidine does not form disulfide bonds; its imidazole group participates in acid-base catalysis and metal coordination.',
      },
      teachingPoint: 'Histidine is the only amino acid with a pKa near physiological pH (~6.0), allowing it to exist in both protonated and neutral forms under biological conditions. This makes it an ideal proton shuttle for acid-base catalysis — the defining feature of the catalytic triad (Ser-His-Asp) in serine proteases.',
      relatedTopics: ['histidine pKa', 'acid-base catalysis', 'catalytic triad', 'serine proteases', 'amino acid ionization at pH 7.4'],
    },
    {
      id: 'mcat1-bb-032',
      sectionId: 'bio-biochem',
      passageId: null,
      questionType: 'discrete',
      discipline: 'Biochemistry',
      contentCategory: 'Enzyme kinetics and regulation',
      foundationalConcept: 'FC 1',
      scientificSkill: 'Skill 2',
      difficulty: 'medium',
      question: 'An allosteric enzyme displays a sigmoidal velocity-vs-substrate concentration curve with a Hill coefficient (nH) of 3.4. Which statement best explains the significance of nH = 3.4?',
      choices: [
        { label: 'A', text: 'The enzyme has exactly 3 active sites, each binding substrate independently according to Michaelis-Menten kinetics' },
        { label: 'B', text: 'The enzyme exhibits positive cooperativity: binding of one substrate molecule increases the affinity of remaining binding sites for additional substrate' },
        { label: 'C', text: 'nH = 3.4 indicates the presence of a non-competitive inhibitor at a concentration 3.4-fold above the inhibitor Ki' },
        { label: 'D', text: 'The sigmoidal curve results from the enzyme being saturated at all substrate concentrations, producing a plateau at very low [S]' },
      ],
      correctAnswer: 'B',
      explanation: 'A Hill coefficient nH > 1 indicates positive cooperativity: binding of the first substrate molecule induces a conformational shift (T-state → R-state) that increases the affinity of remaining subunits. nH = 1 → no cooperativity (hyperbolic Michaelis-Menten). nH < 1 → negative cooperativity. nH does not equal the number of binding sites — hemoglobin, for example, has 4 O₂-binding sites but nH ≈ 2.7. The sigmoidal shape reflects a switch-like response to small changes in substrate concentration.',
      wrongAnswerExplanations: {
        A: 'Independent binding sites would yield nH = 1 (hyperbolic, not sigmoidal, velocity curve). nH reflects the degree of cooperativity, not the number of active sites. An enzyme with 3 independent sites would show Michaelis-Menten kinetics.',
        C: 'The Hill coefficient quantifies cooperativity in ligand binding and is unrelated to inhibitor concentrations or inhibition type. Non-competitive inhibition changes Vmax and produces modified Michaelis-Menten (hyperbolic) kinetics, not a sigmoidal curve.',
        D: 'Sigmoidal curves arise from cooperative binding, not premature saturation. At low [S], cooperative enzymes are far from saturation and show an accelerating response — the S-shape reflects the cooperative transition from T to R states, not a saturation plateau.',
      },
      teachingPoint: 'Hill coefficient nH: = 1 → no cooperativity (Michaelis-Menten, hyperbolic); > 1 → positive cooperativity (sigmoidal, switch-like); < 1 → negative cooperativity. Positive cooperativity allows precise, ultrasensitive responses to small changes in substrate concentration — physiologically critical for hemoglobin and allosteric metabolic enzymes.',
      relatedTopics: ['Hill coefficient', 'positive cooperativity', 'allosteric enzymes', 'sigmoidal kinetics', 'T-state R-state transition'],
    },
    {
      id: 'mcat1-bb-033',
      sectionId: 'bio-biochem',
      passageId: null,
      questionType: 'discrete',
      discipline: 'Biology',
      contentCategory: 'DNA replication',
      foundationalConcept: 'FC 1',
      scientificSkill: 'Skill 1',
      difficulty: 'easy',
      question: 'During eukaryotic DNA replication, which statement correctly distinguishes leading strand from lagging strand synthesis?',
      choices: [
        { label: 'A', text: 'The leading strand requires a new RNA primer at regular intervals; the lagging strand requires only a single primer at the origin of replication' },
        { label: 'B', text: 'The lagging strand is synthesized continuously toward the replication fork; the leading strand is made as short discontinuous fragments' },
        { label: 'C', text: 'The leading strand is synthesized continuously in the 5′→3′ direction toward the fork; the lagging strand is synthesized as discontinuous Okazaki fragments extending away from the fork, each requiring a new RNA primer' },
        { label: 'D', text: 'Both strands are synthesized discontinuously in opposite directions, requiring an equal number of RNA primers' },
      ],
      correctAnswer: 'C',
      explanation: 'DNA polymerase synthesizes only 5′→3′. At a rightward-moving replication fork: the leading strand template runs 3′→5′ in the direction of fork movement, so DNA Pol ε synthesizes continuously toward the fork after a single initial RNA primer. The lagging strand template runs 5′→3′ relative to fork movement — polymerase must synthesize away from the fork in short Okazaki fragments (100–200 nt), each requiring its own RNA primer from primase. Primers are later removed by RNase H/FEN1, gaps filled by DNA Pol δ, and nicks sealed by DNA ligase I.',
      wrongAnswerExplanations: {
        A: 'This is reversed. The lagging strand requires multiple RNA primers (one per Okazaki fragment). The leading strand requires only a single primer at the origin of replication.',
        B: 'This is the opposite of reality. The leading strand is synthesized continuously; the lagging strand is synthesized discontinuously as Okazaki fragments that extend away from, not toward, the fork.',
        D: 'Only the lagging strand is synthesized discontinuously. The leading strand is continuous after a single initial primer. They require very different numbers of RNA primers.',
      },
      teachingPoint: 'Leading strand: one RNA primer, continuous 5′→3′ synthesis toward the fork. Lagging strand: multiple RNA primers, discontinuous Okazaki fragments extending away from the fork. After replication: primers removed (RNase H/FEN1) → gaps filled (Pol δ) → nicks sealed (DNA ligase I).',
      relatedTopics: ['DNA replication', 'leading vs lagging strand', 'Okazaki fragments', 'RNA primer and primase', 'DNA ligase'],
    },
    {
      id: 'mcat1-bb-034',
      sectionId: 'bio-biochem',
      passageId: null,
      questionType: 'discrete',
      discipline: 'Biology',
      contentCategory: 'Cell cycle and apoptosis',
      foundationalConcept: 'FC 1',
      scientificSkill: 'Skill 1',
      difficulty: 'medium',
      question: 'Which of the following correctly distinguishes the intrinsic apoptosis pathway from the extrinsic apoptosis pathway?',
      choices: [
        { label: 'A', text: 'The intrinsic pathway is triggered by death ligands (FasL, TNF-α) binding to cell surface death receptors; the extrinsic pathway involves mitochondrial cytochrome c release' },
        { label: 'B', text: 'The intrinsic pathway is initiated by internal stress signals leading to mitochondrial cytochrome c release and caspase-9 activation; the extrinsic pathway is triggered by extracellular death ligands binding to death receptors and activating caspase-8' },
        { label: 'C', text: 'Both pathways converge on caspase-8 as the shared initiator caspase before activating executioner caspases' },
        { label: 'D', text: 'The extrinsic pathway does not activate caspases; it instead directly degrades DNA via endonuclease release from the nucleus' },
      ],
      correctAnswer: 'B',
      explanation: 'Intrinsic (mitochondrial) pathway: internal stresses (DNA damage, hypoxia, oxidative stress) → pro-apoptotic BCL-2 family members (BAX, BAK) oligomerize in the outer mitochondrial membrane → cytochrome c release → apoptosome formation with APAF-1 → caspase-9 activation → executioner caspases (caspase-3, -7). Extrinsic (death receptor) pathway: FasL/TRAIL/TNF binds Fas/DR4-5/TNFR → DISC assembly → procaspase-8 cleavage → active caspase-8 → caspase-3/7 (and BID cleavage can amplify the intrinsic pathway).',
      wrongAnswerExplanations: {
        A: 'These descriptions are exactly reversed. Death ligands and surface receptors activate the EXTRINSIC pathway. Mitochondrial cytochrome c release is the defining feature of the INTRINSIC pathway.',
        C: 'Caspase-8 is the initiator caspase of the EXTRINSIC pathway (activated at the DISC). Caspase-9 is the initiator of the INTRINSIC pathway (activated in the apoptosome). Both pathways share executioner caspases (caspase-3, -7), not caspase-8.',
        D: 'Both apoptosis pathways are caspase-dependent. The extrinsic pathway activates caspase-8, which then activates executioner caspases. DNA fragmentation (by caspase-activated DNase, CAD) occurs downstream of executioner caspase-3 — a caspase-dependent step, not direct endonuclease release.',
      },
      teachingPoint: 'Two apoptosis pathways: Intrinsic (mitochondrial): internal stress → BAX/BAK → cytochrome c → apoptosome → caspase-9 → caspase-3/7. Extrinsic (death receptor): FasL/TNF → death receptor → DISC → caspase-8 → caspase-3/7. Cross-talk: caspase-8 cleaves BID → tBID → amplifies intrinsic pathway.',
      relatedTopics: ['intrinsic apoptosis', 'extrinsic apoptosis', 'cytochrome c release', 'caspase cascade', 'BCL-2 family'],
    },
    {
      id: 'mcat1-bb-035',
      sectionId: 'bio-biochem',
      passageId: null,
      questionType: 'discrete',
      discipline: 'Biology',
      contentCategory: 'Endocrine signaling',
      foundationalConcept: 'FC 3',
      scientificSkill: 'Skill 1',
      difficulty: 'medium',
      question: 'Why do steroid hormones (e.g., cortisol) generally produce longer-lasting effects than peptide hormones (e.g., glucagon) when both are present at equivalent circulating concentrations?',
      choices: [
        { label: 'A', text: 'Steroid hormones bind extracellular receptors and trigger faster second-messenger cascades than peptide hormones' },
        { label: 'B', text: 'Steroid hormones are hydrophilic and cannot be degraded by plasma proteases, giving them a longer circulating half-life' },
        { label: 'C', text: 'Steroid hormones are lipophilic, cross the plasma membrane, bind intracellular receptors, and alter gene transcription directly — effects persist as long as the newly synthesized proteins remain functional' },
        { label: 'D', text: 'Steroid hormones are stored in secretory vesicles and released continuously, unlike peptide hormones which are synthesized on demand' },
      ],
      correctAnswer: 'C',
      explanation: 'Steroid hormones (cholesterol-derived, lipophilic) diffuse through the phospholipid bilayer and bind cytoplasmic or nuclear receptors. The hormone–receptor complex acts as a transcription factor, altering gene expression to produce new proteins (enzymes, transporters, etc.). These protein-level changes persist far beyond the hormone\'s presence — effects can last hours to days. Peptide hormones (hydrophilic) bind plasma membrane receptors and act via second messengers (cAMP, IP₃/DAG, Ca²⁺), producing rapid but short-lived effects that end when the second messenger is degraded.',
      wrongAnswerExplanations: {
        A: 'Steroid hormones do NOT bind extracellular (plasma membrane) receptors — they bind intracellular receptors. It is peptide hormones that bind surface receptors and activate second-messenger cascades. Steroid hormone effects are slower in onset (require transcription/translation) but longer lasting.',
        B: 'Steroid hormones are lipophilic, not hydrophilic. They circulate bound to carrier proteins (e.g., corticosteroid-binding globulin for cortisol) and are metabolized by hepatic cytochrome P450 enzymes. They are not immune to degradation.',
        D: 'Steroid hormones are NOT stored in vesicles — their lipophilicity prevents vesicular storage; they are synthesized from cholesterol on demand and immediately diffuse out. Peptide hormones (e.g., insulin, glucagon) are stored in secretory granules. This description is exactly reversed.',
      },
      teachingPoint: 'Steroid hormones: lipophilic → cross membrane → intracellular/nuclear receptor → altered gene transcription → delayed onset, long-lasting effects (hours to days). Peptide hormones: hydrophilic → membrane receptor → second messenger → rapid onset, short-lived effects (seconds to minutes). Key distinction: steroids change which proteins are made; peptide hormones modulate what existing proteins do.',
      relatedTopics: ['steroid hormones mechanism', 'peptide hormones mechanism', 'intracellular receptors', 'nuclear receptor', 'second messenger systems'],
    },
  ],
}
