import type { MCATSection } from './types'

export const chemPhysSection: MCATSection = {
  id: 'chem-phys',
  title: 'Chemical and Physical Foundations of Biological Systems',
  abbreviation: 'Chem/Phys',
  questionCount: 59,
  seededCount: 35,
  timeMinutes: 95,
  breakAfterMinutes: 10,
  breakType: 'short',
  passages: [
    {
      id: 'cp-p1',
      sectionId: 'chem-phys',
      title: 'Passage 1',
      passageText: `The carbonate buffer system is the primary extracellular buffer in human blood, maintaining plasma pH near 7.4. This system consists of carbonic acid (H₂CO₃) and bicarbonate (HCO₃⁻), described by the equilibrium:

H₂CO₃ ⇌ H⁺ + HCO₃⁻     pKₐ = 6.1

Because dissolved CO₂ rapidly equilibrates with H₂CO₃ (via carbonic anhydrase), the effective pKₐ for the CO₂/HCO₃⁻ pair is often cited as 6.1. The Henderson-Hasselbalch equation describes the pH of this system:

pH = pKₐ + log([HCO₃⁻] / [CO₂])

Normal plasma values are [HCO₃⁻] ≈ 24 mM and [CO₂] ≈ 1.2 mM.

A researcher titrated a solution containing 0.10 M H₂CO₃ with 1.0 M NaOH. The resulting titration curve showed two distinct inflection points near pH 6.1 and pH 10.3, corresponding to the two ionization steps of carbonic acid.

At the half-equivalence points, the buffer capacity is maximal because the concentrations of acid and conjugate base are equal. The buffer capacity diminishes as the ratio of acid to base deviates from 1:1. A buffer resists pH changes most effectively within ±1 pH unit of its pKₐ.

Table 1 shows the pH measured after adding NaOH to the carbonate solution.

| Volume NaOH added (mL) | pH   |
|------------------------|------|
| 0                      | 3.7  |
| 5                      | 5.4  |
| 10                     | 6.1  |
| 15                     | 6.8  |
| 20                     | 8.4  |
| 25                     | 10.3 |
| 30                     | 11.9 |`,
      figures: [
        {
          type: 'table',
          title: 'Table 1: Titration of 0.10 M H₂CO₃ with 1.0 M NaOH',
          headers: ['Volume NaOH added (mL)', 'pH'],
          rows: [
            ['0', '3.7'], ['5', '5.4'], ['10', '6.1'],
            ['15', '6.8'], ['20', '8.4'], ['25', '10.3'], ['30', '11.9'],
          ],
        },
      ],
      questions: [
        {
          id: 'mcat1-cp-001',
          sectionId: 'chem-phys',
          passageId: 'cp-p1',
          questionType: 'passage',
          discipline: 'General Chemistry',
          contentCategory: 'Intermolecular forces and properties of solutions',
          foundationalConcept: 'FC 5: The principles that govern chemical interactions and reactions.',
          scientificSkill: 'Skill 1',
          difficulty: 'medium',
          question: 'Using the Henderson-Hasselbalch equation, what is the pH of normal blood plasma given [HCO₃⁻] = 24 mM and [CO₂] = 1.2 mM?',
          choices: [
            { label: 'A', text: '6.1' },
            { label: 'B', text: '7.1' },
            { label: 'C', text: '7.4' },
            { label: 'D', text: '8.1' },
          ],
          correctAnswer: 'C',
          explanation: 'pH = pKₐ + log([HCO₃⁻]/[CO₂]) = 6.1 + log(24/1.2) = 6.1 + log(20) = 6.1 + 1.30 = 7.4. This matches the normal blood pH.',
          wrongAnswerExplanations: {
            A: '6.1 is the pKₐ itself, not the solution pH. The pH differs from pKₐ when the ratio of base to acid is not 1:1.',
            B: '7.1 results from using log(10) = 1, which would require [HCO₃⁻]/[CO₂] = 10:1, not the 20:1 ratio given.',
            D: '8.1 would require a ratio of [HCO₃⁻]/[CO₂] ≈ 100:1, far above physiological values.',
          },
          teachingPoint: 'The Henderson-Hasselbalch equation: pH = pKₐ + log([A⁻]/[HA]). For blood: pH = 6.1 + log(24/1.2) = 6.1 + 1.3 = 7.4.',
          relatedTopics: ['buffer systems', 'Henderson-Hasselbalch', 'blood pH regulation', 'carbonate system'],
        },
        {
          id: 'mcat1-cp-002',
          sectionId: 'chem-phys',
          passageId: 'cp-p1',
          questionType: 'passage',
          discipline: 'General Chemistry',
          contentCategory: 'Acid-base equilibria',
          foundationalConcept: 'FC 5',
          scientificSkill: 'Skill 4',
          difficulty: 'medium',
          question: 'According to Table 1, at which volume of NaOH added does the first equivalence point occur?',
          choices: [
            { label: 'A', text: '5 mL' },
            { label: 'B', text: '10 mL' },
            { label: 'C', text: '20 mL' },
            { label: 'D', text: '25 mL' },
          ],
          correctAnswer: 'C',
          explanation: 'The first equivalence point occurs at pH ~8.4 (at 20 mL), midway between the two pKₐ values (6.1 and 10.3). At this point, all H₂CO₃ has been converted to HCO₃⁻. The half-equivalence point is at 10 mL (pH = pKₐ₁ = 6.1).',
          wrongAnswerExplanations: {
            A: '5 mL is before the half-equivalence point. The solution is still primarily H₂CO₃.',
            B: '10 mL is the first half-equivalence point (pH = pKₐ₁ = 6.1), where [H₂CO₃] = [HCO₃⁻], not the equivalence point.',
            D: '25 mL is the second half-equivalence point (pH = pKₐ₂ = 10.3), where [HCO₃⁻] = [CO₃²⁻].',
          },
          teachingPoint: 'In a diprotic acid titration, the first equivalence point occurs when all HA has been converted to A⁻. The half-equivalence point (pH = pKₐ) precedes it at half the equivalence volume.',
          relatedTopics: ['titration', 'equivalence point', 'diprotic acids', 'polyprotic acid titration'],
        },
        {
          id: 'mcat1-cp-003',
          sectionId: 'chem-phys',
          passageId: 'cp-p1',
          questionType: 'passage',
          discipline: 'General Chemistry',
          contentCategory: 'Acid-base equilibria',
          foundationalConcept: 'FC 5',
          scientificSkill: 'Skill 2',
          difficulty: 'medium',
          question: 'A patient with emphysema retains CO₂ due to impaired ventilation. How will this affect blood pH and [HCO₃⁻] initially?',
          choices: [
            { label: 'A', text: 'pH decreases; [HCO₃⁻] decreases' },
            { label: 'B', text: 'pH decreases; [HCO₃⁻] increases' },
            { label: 'C', text: 'pH increases; [HCO₃⁻] decreases' },
            { label: 'D', text: 'pH increases; [HCO₃⁻] increases' },
          ],
          correctAnswer: 'B',
          explanation: 'Retained CO₂ drives CO₂ + H₂O → H₂CO₃ → H⁺ + HCO₃⁻. This produces more H⁺ (lowering pH) and more HCO₃⁻ (raising [HCO₃⁻]). This is respiratory acidosis with compensatory bicarbonate rise.',
          wrongAnswerExplanations: {
            A: 'While pH does decrease, [HCO₃⁻] increases as CO₂ dissociates to form both H⁺ and HCO₃⁻.',
            C: 'Retained CO₂ increases H⁺, so pH decreases, not increases.',
            D: 'pH cannot increase when CO₂ is being retained — excess CO₂ drives the reaction toward acid production.',
          },
          teachingPoint: 'Respiratory acidosis from CO₂ retention: ↑CO₂ → ↑H₂CO₃ → ↑H⁺ + ↑HCO₃⁻. pH falls, [HCO₃⁻] rises acutely.',
          relatedTopics: ['respiratory acidosis', 'CO₂ retention', 'buffer equilibrium', 'carbonate system'],
        },
        {
          id: 'mcat1-cp-004',
          sectionId: 'chem-phys',
          passageId: 'cp-p1',
          questionType: 'passage',
          discipline: 'General Chemistry',
          contentCategory: 'Acid-base equilibria',
          foundationalConcept: 'FC 5',
          scientificSkill: 'Skill 2',
          difficulty: 'hard',
          question: 'The carbonate buffer system in blood operates at pH 7.4, which is more than 1 unit above its pKₐ of 6.1. Why is this system still physiologically effective despite being outside its ideal buffering range?',
          choices: [
            { label: 'A', text: 'The lungs can rapidly adjust [CO₂] by changing ventilation rate, making the system an open buffer.' },
            { label: 'B', text: 'At pH 7.4, [H₂CO₃] greatly exceeds [HCO₃⁻], providing a large reservoir of acid to neutralize bases.' },
            { label: 'C', text: 'The kidneys continuously produce H₂CO₃ to maintain the buffer ratio.' },
            { label: 'D', text: 'A second pKₐ at 10.3 provides additional buffering capacity near pH 7.4.' },
          ],
          correctAnswer: 'A',
          explanation: 'Although pH 7.4 is >1 unit from pKₐ 6.1, the respiratory system can rapidly adjust [CO₂] (and thus [H₂CO₃]). This makes the carbonate system an open system — unlike a closed buffer, [CO₂] is regulated, not fixed. This respiratory regulation dramatically expands effective buffering range.',
          wrongAnswerExplanations: {
            B: 'At pH 7.4, [HCO₃⁻] >> [H₂CO₃] (ratio ~20:1), so H₂CO₃ is the minor species, not the major one.',
            C: 'The kidneys regulate [HCO₃⁻], not [H₂CO₃]. H₂CO₃ arises from CO₂ hydration.',
            D: 'The second pKₐ (10.3) is even further from pH 7.4, providing no meaningful buffering at physiological pH.',
          },
          teachingPoint: 'The carbonate buffer is an open system: ventilation adjusts [CO₂] rapidly. This allows effective buffering even far from pKₐ — a key physiological feature.',
          relatedTopics: ['open buffer system', 'respiratory compensation', 'physiological buffering', 'ventilation and pH'],
        },
        {
          id: 'mcat1-cp-005',
          sectionId: 'chem-phys',
          passageId: 'cp-p1',
          questionType: 'passage',
          discipline: 'General Chemistry',
          contentCategory: 'Acid-base equilibria',
          foundationalConcept: 'FC 5',
          scientificSkill: 'Skill 2',
          difficulty: 'easy',
          question: 'At which pH from Table 1 is the buffer capacity of the carbonate system greatest for the first ionization step?',
          choices: [
            { label: 'A', text: '3.7' },
            { label: 'B', text: '6.1' },
            { label: 'C', text: '7.4' },
            { label: 'D', text: '10.3' },
          ],
          correctAnswer: 'B',
          explanation: 'Buffer capacity is maximal at pH = pKₐ, where [HA] = [A⁻]. For the first ionization of H₂CO₃, pKₐ₁ = 6.1, so maximum buffer capacity for this step occurs at pH 6.1 (10 mL NaOH added in Table 1).',
          wrongAnswerExplanations: {
            A: '3.7 is the initial pH with no buffer base present. Buffer capacity is low because [HCO₃⁻] ≈ 0.',
            C: '7.4 is physiological blood pH but is not near pKₐ₁ = 6.1, so buffer capacity for this step is reduced.',
            D: '10.3 is the pKₐ₂ — this is where the second ionization step has maximum buffer capacity.',
          },
          teachingPoint: 'Maximum buffer capacity occurs at pH = pKₐ where [acid] = [conjugate base]. For H₂CO₃, pKₐ₁ = 6.1.',
          relatedTopics: ['buffer capacity', 'pKₐ', 'half-equivalence point', 'acid-base'],
        },
      ],
    },
    {
      id: 'cp-p2',
      sectionId: 'chem-phys',
      title: 'Passage 2',
      passageText: `Enzyme kinetics can be described by the Michaelis-Menten model, where reaction velocity (v) depends on substrate concentration [S]:

v = Vmax[S] / (Km + [S])

Here Vmax is the maximum velocity and Km is the Michaelis constant — the substrate concentration at which v = Vmax/2. A low Km indicates high affinity between enzyme and substrate.

Inhibitors alter enzyme kinetics predictably. A competitive inhibitor binds the active site reversibly, competing with substrate. A noncompetitive inhibitor binds an allosteric site, reducing enzyme efficiency regardless of [S].

Researchers studied an enzyme catalyzing the first committed step of a biosynthetic pathway. They measured v at various [S] with and without two inhibitors (I₁ and I₂). They generated Lineweaver-Burk (double-reciprocal) plots: 1/v vs. 1/[S].

Results:
- No inhibitor: x-intercept = -0.5 mM⁻¹, y-intercept = 0.02 (µmol/min)⁻¹
- Inhibitor I₁: x-intercept = -0.25 mM⁻¹, y-intercept = 0.02 (µmol/min)⁻¹
- Inhibitor I₂: x-intercept = -0.5 mM⁻¹, y-intercept = 0.04 (µmol/min)⁻¹

On a Lineweaver-Burk plot, the y-intercept = 1/Vmax and the x-intercept = -1/Km. The slope = Km/Vmax.`,
      questions: [
        {
          id: 'mcat1-cp-006',
          sectionId: 'chem-phys',
          passageId: 'cp-p2',
          questionType: 'passage',
          discipline: 'Biochemistry',
          contentCategory: 'Enzyme structure and function',
          foundationalConcept: 'FC 1: Biomolecules have unique properties that determine how they contribute to the structure and function of cells.',
          scientificSkill: 'Skill 4',
          difficulty: 'medium',
          question: 'What is the Km of the uninhibited enzyme based on the Lineweaver-Burk data in the passage?',
          choices: [
            { label: 'A', text: '0.5 mM' },
            { label: 'B', text: '2 mM' },
            { label: 'C', text: '4 mM' },
            { label: 'D', text: '50 mM' },
          ],
          correctAnswer: 'B',
          explanation: 'On a Lineweaver-Burk plot, x-intercept = -1/Km. With x-intercept = -0.5 mM⁻¹, Km = 1/0.5 = 2 mM.',
          wrongAnswerExplanations: {
            A: '0.5 mM is the x-intercept value itself (in mM⁻¹), not Km. Km = 1/(|x-intercept|).',
            C: '4 mM would come from -1/Km = -0.25, which describes the inhibited enzyme I₁.',
            D: '50 mM is not derivable from the data. This appears to confuse y-intercept (0.02) with Km calculation.',
          },
          teachingPoint: 'Lineweaver-Burk: x-intercept = -1/Km, y-intercept = 1/Vmax. Km = -1/(x-intercept).',
          relatedTopics: ['Michaelis-Menten kinetics', 'Lineweaver-Burk plot', 'Km', 'enzyme affinity'],
        },
        {
          id: 'mcat1-cp-007',
          sectionId: 'chem-phys',
          passageId: 'cp-p2',
          questionType: 'passage',
          discipline: 'Biochemistry',
          contentCategory: 'Enzyme structure and function',
          foundationalConcept: 'FC 1',
          scientificSkill: 'Skill 4',
          difficulty: 'medium',
          question: 'Based on the Lineweaver-Burk data, which type of inhibition does I₁ represent?',
          choices: [
            { label: 'A', text: 'Competitive inhibition, because Km increases and Vmax is unchanged' },
            { label: 'B', text: 'Noncompetitive inhibition, because Km is unchanged and Vmax decreases' },
            { label: 'C', text: 'Competitive inhibition, because Vmax increases and Km decreases' },
            { label: 'D', text: 'Uncompetitive inhibition, because both Km and Vmax decrease proportionally' },
          ],
          correctAnswer: 'A',
          explanation: 'I₁ has the same y-intercept as the uninhibited enzyme (1/Vmax = 0.02 → Vmax unchanged), but a different x-intercept (-0.25 vs. -0.5), indicating Km increases from 2 mM to 4 mM. Unchanged Vmax + increased Km = competitive inhibition.',
          wrongAnswerExplanations: {
            B: 'This describes noncompetitive inhibition (I₂), not I₁. I₁ changes the x-intercept, not the y-intercept.',
            C: 'Competitive inhibitors always increase apparent Km (they compete with substrate). Vmax stays the same, not increases.',
            D: 'Uncompetitive inhibition decreases both Km and Vmax proportionally, shifting the LB line parallel. I₁ shows different x-intercepts, not the same slope.',
          },
          teachingPoint: 'Competitive: same y-intercept (Vmax unchanged), different x-intercept (Km increases). Noncompetitive: same x-intercept (Km unchanged), different y-intercept (Vmax decreases).',
          relatedTopics: ['competitive inhibition', 'noncompetitive inhibition', 'Lineweaver-Burk', 'enzyme kinetics'],
        },
        {
          id: 'mcat1-cp-008',
          sectionId: 'chem-phys',
          passageId: 'cp-p2',
          questionType: 'passage',
          discipline: 'Biochemistry',
          contentCategory: 'Enzyme structure and function',
          foundationalConcept: 'FC 1',
          scientificSkill: 'Skill 1',
          difficulty: 'easy',
          question: 'What effect does increasing substrate concentration to very high levels have on a competitive inhibitor\'s effect on reaction velocity?',
          choices: [
            { label: 'A', text: 'The inhibitor\'s effect is amplified because more substrate-inhibitor collisions occur' },
            { label: 'B', text: 'The inhibitor\'s effect is overcome and Vmax approaches the uninhibited value' },
            { label: 'C', text: 'Vmax is permanently reduced regardless of substrate concentration' },
            { label: 'D', text: 'The enzyme becomes permanently inactivated' },
          ],
          correctAnswer: 'B',
          explanation: 'Competitive inhibitors bind reversibly and compete with substrate for the active site. At very high [S], substrate outcompetes the inhibitor, and the reaction approaches uninhibited Vmax. This is the defining feature of competitive (reversible) inhibition.',
          wrongAnswerExplanations: {
            A: 'High [S] outcompetes the inhibitor rather than amplifying its effect. The inhibitor is displaced, not promoted.',
            C: 'Permanent Vmax reduction describes noncompetitive inhibition, not competitive. Competitive inhibition is overcome by excess substrate.',
            D: 'Permanent inactivation describes irreversible (suicide) inhibitors, not competitive inhibitors.',
          },
          teachingPoint: 'Competitive inhibition is reversible and overcome by excess substrate. Vmax is unchanged; only Km (apparent) increases.',
          relatedTopics: ['competitive inhibition', 'reversibility', 'Vmax', 'active site'],
        },
        {
          id: 'mcat1-cp-009',
          sectionId: 'chem-phys',
          passageId: 'cp-p2',
          questionType: 'passage',
          discipline: 'Biochemistry',
          contentCategory: 'Enzyme structure and function',
          foundationalConcept: 'FC 1',
          scientificSkill: 'Skill 2',
          difficulty: 'hard',
          question: 'The enzyme studied is the first committed step of a biosynthetic pathway. If the end product of this pathway acts as inhibitor I₂ (noncompetitive), what regulatory strategy does this represent?',
          choices: [
            { label: 'A', text: 'Substrate-level regulation' },
            { label: 'B', text: 'Allosteric feedback inhibition' },
            { label: 'C', text: 'Competitive product inhibition' },
            { label: 'D', text: 'Covalent enzyme modification' },
          ],
          correctAnswer: 'B',
          explanation: 'When the end product of a pathway inhibits an early (first committed) enzyme at an allosteric (non-active) site, this is feedback inhibition — a classic form of allosteric regulation. Noncompetitive inhibition fits the allosteric model (binds site other than active site).',
          wrongAnswerExplanations: {
            A: 'Substrate-level regulation involves the substrate itself altering the enzyme, not the downstream product.',
            C: 'Competitive product inhibition would involve the product binding the active site, increasing apparent Km. I₂ is noncompetitive (allosteric site).',
            D: 'Covalent modification (e.g., phosphorylation) involves chemical changes to the enzyme — not described here.',
          },
          teachingPoint: 'Allosteric feedback inhibition: pathway end product inhibits first committed enzyme at an allosteric site. Prevents overproduction of product. Often appears as noncompetitive inhibition kinetically.',
          relatedTopics: ['allosteric regulation', 'feedback inhibition', 'first committed step', 'biosynthetic pathway control'],
        },
        {
          id: 'mcat1-cp-010',
          sectionId: 'chem-phys',
          passageId: 'cp-p2',
          questionType: 'passage',
          discipline: 'Biochemistry',
          contentCategory: 'Enzyme structure and function',
          foundationalConcept: 'FC 1',
          scientificSkill: 'Skill 3',
          difficulty: 'hard',
          question: 'To confirm that I₁ is competitive rather than mixed, what experimental result would be most informative?',
          choices: [
            { label: 'A', text: 'Show that increasing [I₁] decreases Vmax' },
            { label: 'B', text: 'Show that at saturating [S], v approaches the same Vmax as the uninhibited enzyme' },
            { label: 'C', text: 'Show that I₁ does not bind the active site using X-ray crystallography' },
            { label: 'D', text: 'Show that the reaction still proceeds in the presence of I₁ at low [S]' },
          ],
          correctAnswer: 'B',
          explanation: 'The hallmark of pure competitive inhibition (vs. mixed) is that saturating [S] completely overcomes inhibition, restoring Vmax to the uninhibited value. If Vmax is unchanged at high [S], inhibition is purely competitive.',
          wrongAnswerExplanations: {
            A: 'If increasing [I₁] decreases Vmax, this would suggest mixed or noncompetitive inhibition, not pure competitive.',
            C: 'Crystallography showing non-active site binding would suggest allosteric/noncompetitive inhibition — contradicting competitive classification.',
            D: 'Activity at low [S] would occur with any reversible inhibitor. This does not distinguish competitive from mixed inhibition.',
          },
          teachingPoint: 'To confirm competitive inhibition: demonstrate that Vmax is unchanged at saturating substrate. The inhibitor is outcompeted by substrate, so v → Vmax.',
          relatedTopics: ['competitive vs. mixed inhibition', 'experimental design', 'Vmax determination', 'inhibition characterization'],
        },
      ],
    },
    {
      id: 'cp-p3',
      sectionId: 'chem-phys',
      title: 'Passage 3',
      passageText: `Blood flow through vessels follows principles of fluid dynamics. For laminar flow, the Hagen-Poiseuille equation describes volumetric flow rate (Q):

Q = (πr⁴ΔP) / (8ηL)

where r is vessel radius, ΔP is the pressure difference, η is blood viscosity, and L is vessel length. Resistance to flow (R) is therefore:

R = 8ηL / (πr⁴)

During atherosclerosis, plaques narrow the arterial lumen, reducing r. Because Q ∝ r⁴, small reductions in radius cause dramatic drops in flow. In a stenotic vessel, Bernoulli's principle governs local pressure:

P₁ + ½ρv₁² + ρgh₁ = P₂ + ½ρv₂² + ρgh₂

For horizontal vessels (h₁ = h₂): P₁ + ½ρv₁² = P₂ + ½ρv₂²

Thus, at a stenosis where cross-sectional area decreases, blood velocity increases and local pressure falls. This creates the pressure gradient that can cause plaque rupture.

Clinicians use the ankle-brachial index (ABI) to assess peripheral artery disease. A normal ABI is 1.0–1.4. An ABI < 0.9 indicates significant stenosis.

Experiment: In an in vitro model, a tube of inner radius 3 mm was reduced to 1.5 mm at a 2 cm stenosis. Pressure drop across the stenosis was 20 mmHg at baseline flow of 60 mL/min.`,
      questions: [
        {
          id: 'mcat1-cp-011',
          sectionId: 'chem-phys',
          passageId: 'cp-p3',
          questionType: 'passage',
          discipline: 'Physics',
          contentCategory: 'Fluid statics and dynamics',
          foundationalConcept: 'FC 4: Complex living organisms transport materials, sense their environment, process signals, and respond to changes using processes understood in terms of physical principles.',
          scientificSkill: 'Skill 1',
          difficulty: 'medium',
          question: 'If the radius of an artery decreases from 3 mm to 1.5 mm due to plaque, by what factor does resistance to blood flow change?',
          choices: [
            { label: 'A', text: '2-fold increase' },
            { label: 'B', text: '4-fold increase' },
            { label: 'C', text: '8-fold increase' },
            { label: 'D', text: '16-fold increase' },
          ],
          correctAnswer: 'D',
          explanation: 'Resistance R ∝ 1/r⁴. When r decreases from 3 to 1.5 mm (factor of 2), R increases by 2⁴ = 16-fold. The r⁴ dependence makes even small radius reductions catastrophic for flow.',
          wrongAnswerExplanations: {
            A: '2-fold would apply if R ∝ 1/r (linear). Poiseuille\'s law has an r⁴ dependence.',
            B: '4-fold would apply if R ∝ 1/r². The actual exponent is 4, not 2.',
            C: '8-fold is not derived from Poiseuille\'s law. R ∝ 1/r⁴, so halving r gives 2⁴ = 16-fold increase.',
          },
          teachingPoint: 'Poiseuille: R = 8ηL/πr⁴, so R ∝ r⁻⁴. Halving radius increases resistance 16-fold. This is why even 50% stenosis severely reduces blood flow.',
          relatedTopics: ['Hagen-Poiseuille equation', 'vascular resistance', 'atherosclerosis', 'r⁴ dependence'],
        },
        {
          id: 'mcat1-cp-012',
          sectionId: 'chem-phys',
          passageId: 'cp-p3',
          questionType: 'passage',
          discipline: 'Physics',
          contentCategory: 'Fluid statics and dynamics',
          foundationalConcept: 'FC 4',
          scientificSkill: 'Skill 1',
          difficulty: 'medium',
          question: 'At the stenotic narrowing in the experiment, blood velocity increases. According to Bernoulli\'s principle, what happens to local blood pressure at the stenosis?',
          choices: [
            { label: 'A', text: 'Increases, because more blood passes per unit time' },
            { label: 'B', text: 'Decreases, because kinetic energy increases at the expense of pressure energy' },
            { label: 'C', text: 'Remains unchanged, because total blood volume is conserved' },
            { label: 'D', text: 'Increases, because the vessel wall exerts inward force on the blood' },
          ],
          correctAnswer: 'B',
          explanation: 'Bernoulli\'s principle: P + ½ρv² = constant (for horizontal flow). As v increases at the stenosis, ½ρv² increases, so P must decrease to conserve the sum. Pressure drops at the narrowing.',
          wrongAnswerExplanations: {
            A: 'More flow through the stenosis does not raise pressure — it raises velocity. Bernoulli shows the inverse relationship between velocity and pressure.',
            C: 'Volume conservation (continuity) explains why velocity increases, but Bernoulli\'s principle shows that pressure is not conserved — kinetic and potential energy exchange.',
            D: 'Vessel wall forces are not part of the Bernoulli analysis of ideal fluid flow, and inward wall force would not raise luminal pressure.',
          },
          teachingPoint: 'Bernoulli\'s principle: faster flow → lower pressure. At a stenosis: velocity↑ → pressure↓. This low pressure can cause vessel collapse or plaque rupture.',
          relatedTopics: ['Bernoulli\'s principle', 'fluid dynamics', 'stenosis', 'venturi effect'],
        },
        {
          id: 'mcat1-cp-013',
          sectionId: 'chem-phys',
          passageId: 'cp-p3',
          questionType: 'passage',
          discipline: 'Physics',
          contentCategory: 'Fluid statics and dynamics',
          foundationalConcept: 'FC 4',
          scientificSkill: 'Skill 4',
          difficulty: 'hard',
          question: 'In the experiment, when the tube radius was reduced to 1.5 mm (half of 3 mm), the pressure drop across the stenosis was 20 mmHg at 60 mL/min. If the stenosis is treated and radius restored to 3 mm, what would the new pressure drop be at the same flow rate, assuming laminar flow?',
          choices: [
            { label: 'A', text: '1.25 mmHg' },
            { label: 'B', text: '5 mmHg' },
            { label: 'C', text: '10 mmHg' },
            { label: 'D', text: '40 mmHg' },
          ],
          correctAnswer: 'A',
          explanation: 'ΔP = QR and R ∝ 1/r⁴. Doubling r reduces R by 2⁴ = 16. New ΔP = 20/16 = 1.25 mmHg. Restoring radius dramatically reduces the pressure gradient needed to drive flow.',
          wrongAnswerExplanations: {
            B: '5 mmHg would be 20/4, implying R ∝ 1/r², not 1/r⁴.',
            C: '10 mmHg would be 20/2, implying R ∝ 1/r. Poiseuille gives r⁴ dependence.',
            D: '40 mmHg would be doubling — this would apply if radius halving increased ΔP proportionally, but the question asks about doubling radius (which reduces R).',
          },
          teachingPoint: 'ΔP = Q × R. With R ∝ r⁻⁴, doubling r decreases R by 16×. So ΔP decreases 16-fold: 20/16 = 1.25 mmHg.',
          relatedTopics: ['Poiseuille\'s law', 'pressure drop', 'flow resistance', 'stenosis reversal'],
        },
        {
          id: 'mcat1-cp-014',
          sectionId: 'chem-phys',
          passageId: 'cp-p3',
          questionType: 'passage',
          discipline: 'Biology',
          contentCategory: 'Circulatory system',
          foundationalConcept: 'FC 4',
          scientificSkill: 'Skill 2',
          difficulty: 'easy',
          question: 'A patient has an ABI of 0.7. Which of the following best explains this finding based on passage information?',
          choices: [
            { label: 'A', text: 'Elevated blood pressure in the arm relative to the ankle' },
            { label: 'B', text: 'Significant peripheral arterial stenosis reducing ankle blood pressure' },
            { label: 'C', text: 'Increased cardiac output leading to higher brachial pressure' },
            { label: 'D', text: 'Vasodilation of peripheral arteries increasing ankle pressure' },
          ],
          correctAnswer: 'B',
          explanation: 'ABI = ankle pressure / brachial pressure. Normal ABI is 1.0–1.4. An ABI of 0.7 (<0.9) indicates ankle pressure is significantly lower than brachial pressure, consistent with peripheral arterial stenosis reducing blood flow (and pressure) to the ankle.',
          wrongAnswerExplanations: {
            A: 'ABI < 1.0 means ankle pressure < brachial pressure, so brachial pressure is higher — but this is because ankle pressure is low due to stenosis, not because arm pressure is artificially elevated.',
            C: 'Increased cardiac output would raise pressure throughout the body, including the ankle. This would not lower ABI.',
            D: 'Vasodilation would increase ankle pressure, raising (not lowering) ABI toward or above 1.0.',
          },
          teachingPoint: 'ABI < 0.9 indicates peripheral arterial disease. Stenosis reduces blood pressure distal to the obstruction → low ankle pressure → low ABI.',
          relatedTopics: ['ankle-brachial index', 'peripheral artery disease', 'blood pressure measurement', 'stenosis'],
        },
        {
          id: 'mcat1-cp-015',
          sectionId: 'chem-phys',
          passageId: 'cp-p3',
          questionType: 'passage',
          discipline: 'Physics',
          contentCategory: 'Fluid statics and dynamics',
          foundationalConcept: 'FC 4',
          scientificSkill: 'Skill 2',
          difficulty: 'medium',
          question: 'Turbulent flow occurs when the Reynolds number exceeds ~2000 in blood vessels. Compared to laminar flow, turbulent flow would most likely produce what clinical finding?',
          choices: [
            { label: 'A', text: 'Silent, smooth blood flow with no auscultatory findings' },
            { label: 'B', text: 'An audible bruit caused by chaotic pressure fluctuations' },
            { label: 'C', text: 'Decreased resistance to flow due to turbulent mixing' },
            { label: 'D', text: 'Increased oxygen delivery due to enhanced red cell mixing' },
          ],
          correctAnswer: 'B',
          explanation: 'Turbulent flow causes chaotic, swirling fluid motion with random pressure fluctuations. This generates vibrations audible as a bruit (vascular murmur) on auscultation. Bruits over arteries indicate turbulent flow, often from stenosis or arteriovenous malformations.',
          wrongAnswerExplanations: {
            A: 'Silent flow describes laminar flow. Turbulent flow is not silent — it generates audible sounds.',
            C: 'Turbulent flow increases resistance compared to laminar flow. The Hagen-Poiseuille equation applies only to laminar flow; turbulence dissipates more energy.',
            D: 'While mixing occurs, the primary clinical effect of turbulence is increased flow resistance and audible bruits, not enhanced oxygen delivery.',
          },
          teachingPoint: 'Turbulent flow produces audible bruits (vascular murmurs). It increases resistance compared to laminar flow and occurs at high Reynolds numbers, often near stenoses.',
          relatedTopics: ['Reynolds number', 'turbulent flow', 'bruit', 'laminar vs. turbulent flow'],
        },
      ],
    },
    {
      id: 'cp-p4',
      sectionId: 'chem-phys',
      title: 'Passage 4',
      passageText: `The resting membrane potential of neurons arises from unequal ion distributions across the plasma membrane. The equilibrium potential for any individual ion is described by the Nernst equation. At physiological temperature (37°C), this simplifies to:

E_ion = (61.5 mV / z) × log([X]_out / [X]_in)

where z is the ion's charge (positive for cations), and concentrations are in mM.

Typical intracellular and extracellular ion concentrations for a mammalian neuron are given in Table 1. The measured resting membrane potential is approximately −70 mV (inside negative relative to outside).

Table 1: Ion concentrations in a resting mammalian neuron

| Ion | Intracellular (mM) | Extracellular (mM) |
|-----|-------------------|-------------------|
| K⁺  | 140               | 5                 |
| Na⁺ | 14                | 145               |
| Cl⁻ | 9                 | 110               |

The Na⁺–K⁺ ATPase (sodium-potassium pump) actively transports three Na⁺ ions out of the cell and two K⁺ ions in per ATP consumed, maintaining the concentration gradients shown in Table 1. Because it moves unequal numbers of charges, it is electrogenic and contributes a small hyperpolarizing current to the resting potential.`,
      figures: [
        {
          type: 'table',
          title: 'Table 1: Ion concentrations in a resting mammalian neuron',
          headers: ['Ion', 'Intracellular (mM)', 'Extracellular (mM)'],
          rows: [
            ['K⁺', '140', '5'],
            ['Na⁺', '14', '145'],
            ['Cl⁻', '9', '110'],
          ],
        },
      ],
      questions: [
        {
          id: 'mcat1-cp-021',
          sectionId: 'chem-phys',
          passageId: 'cp-p4',
          questionType: 'passage',
          discipline: 'Physics',
          contentCategory: 'Electrochemistry',
          foundationalConcept: 'FC 4: Complex living organisms transport materials, sense their environment, process signals, and respond to changes using processes understood in terms of physical principles.',
          scientificSkill: 'Skill 1',
          difficulty: 'medium',
          question: 'Using the Nernst equation and the data in Table 1, what is the equilibrium potential for K⁺ (E_K) at 37°C?',
          choices: [
            { label: 'A', text: '+89 mV' },
            { label: 'B', text: '−27 mV' },
            { label: 'C', text: '−55 mV' },
            { label: 'D', text: '−89 mV' },
          ],
          correctAnswer: 'D',
          explanation: 'E_K = (61.5 mV / z) × log([K⁺]_out / [K⁺]_in) = (61.5 / 1) × log(5 / 140) = 61.5 × log(0.0357) = 61.5 × (−1.447) ≈ −89 mV. The negative value reflects that K⁺ equilibrium requires a highly negative interior to counterbalance the large outward chemical gradient.',
          wrongAnswerExplanations: {
            A: '+89 mV results from inverting the ratio: log([K⁺]_in / [K⁺]_out) = log(140/5) = +1.447, then ×61.5. The Nernst equation uses [X]_out / [X]_in in the numerator.',
            B: '−27 mV is not derivable from these data. This may arise from confusing z = 1 with z = 2 or misreading the logarithm calculation.',
            C: '−55 mV would result from a calculation error on log(5/140) or from using a constant closer to 38 mV (appropriate for 25°C divided by 1.6) rather than 61.5 mV at 37°C.',
          },
          teachingPoint: 'Nernst at 37°C: E_ion = (61.5 mV / z) × log([X]_out / [X]_in). For K⁺: 61.5 × log(5/140) = 61.5 × (−1.447) ≈ −89 mV. The large outward K⁺ gradient requires a very negative interior for electrochemical equilibrium.',
          relatedTopics: ['Nernst equation', 'membrane potential', 'electrochemical gradient', 'potassium equilibrium potential'],
        },
        {
          id: 'mcat1-cp-022',
          sectionId: 'chem-phys',
          passageId: 'cp-p4',
          questionType: 'passage',
          discipline: 'Biology',
          contentCategory: 'Nervous system',
          foundationalConcept: 'FC 4',
          scientificSkill: 'Skill 2',
          difficulty: 'hard',
          question: 'At the resting membrane potential of −70 mV, E_K = −89 mV. What is the net electrochemical driving force on K⁺, and in which direction will K⁺ flow through open K⁺ channels?',
          choices: [
            { label: 'A', text: 'Driving force = −19 mV; K⁺ flows inward because the interior is too negative' },
            { label: 'B', text: 'Driving force = +19 mV; K⁺ flows outward because the electrical gradient does not fully counterbalance the chemical gradient' },
            { label: 'C', text: 'Driving force = 0 mV; no net flux because the neuron is at rest' },
            { label: 'D', text: 'Driving force = −159 mV; K⁺ flows inward because both gradients are directed inward' },
          ],
          correctAnswer: 'B',
          explanation: 'Electrochemical driving force = Vm − E_ion. For K⁺: −70 − (−89) = +19 mV. A positive driving force for a cation means the ion tends to exit the cell. At −70 mV, the interior is not negative enough (would need −89 mV) to fully oppose the outward chemical gradient, so K⁺ leaks outward through resting K⁺ channels.',
          wrongAnswerExplanations: {
            A: '−19 mV reverses the subtraction. Driving force = Vm − E_K = −70 − (−89) = +19 mV, not −19 mV. A positive result for a cation indicates net outward flow.',
            C: 'Zero driving force would occur only if Vm = E_K = −89 mV. At −70 mV, the neuron is not at K⁺ electrochemical equilibrium.',
            D: '−159 mV = −70 + (−89), which erroneously adds rather than subtracts. The formula is Vm − E_ion, not Vm + E_ion.',
          },
          teachingPoint: 'Driving force = Vm − E_ion. For K⁺ at rest: −70 − (−89) = +19 mV → net K⁺ exits. The Na-K ATPase continuously restores the gradient lost by this outward leak.',
          relatedTopics: ['electrochemical driving force', 'resting membrane potential', 'potassium flux', 'K⁺ channels'],
        },
        {
          id: 'mcat1-cp-023',
          sectionId: 'chem-phys',
          passageId: 'cp-p4',
          questionType: 'passage',
          discipline: 'Physics',
          contentCategory: 'Electrochemistry',
          foundationalConcept: 'FC 4',
          scientificSkill: 'Skill 1',
          difficulty: 'medium',
          question: 'Using the Nernst equation and Table 1, calculate the equilibrium potential for Na⁺ (E_Na) at 37°C.',
          choices: [
            { label: 'A', text: '−62 mV' },
            { label: 'B', text: '+26 mV' },
            { label: 'C', text: '+62 mV' },
            { label: 'D', text: '+89 mV' },
          ],
          correctAnswer: 'C',
          explanation: 'E_Na = (61.5 / 1) × log([Na⁺]_out / [Na⁺]_in) = 61.5 × log(145 / 14) = 61.5 × log(10.36) = 61.5 × 1.015 ≈ +62 mV. The strongly positive value reflects that Na⁺ equilibrium requires a positive interior to counterbalance the large inward chemical gradient.',
          wrongAnswerExplanations: {
            A: '−62 mV is the correct magnitude but wrong sign, resulting from inverting the ratio to [Na⁺]_in / [Na⁺]_out = 14/145. Nernst for cations uses [X]_out / [X]_in.',
            B: '+26 mV would arise from a calculation error, possibly using the 25°C constant (25.7 mV) and dividing by ln(10) twice, or applying an incorrect formula.',
            D: '+89 mV is the magnitude of E_K (not E_Na). The Na⁺ and K⁺ gradients produce different equilibrium potentials of opposite sign.',
          },
          teachingPoint: 'E_Na = 61.5 × log(145/14) ≈ +62 mV. Na⁺ has a large inward chemical gradient, so equilibrium requires a positive interior. At resting Vm = −70 mV, there is a large inward driving force on Na⁺ — the basis of the action potential upstroke.',
          relatedTopics: ['Nernst equation', 'sodium equilibrium potential', 'action potential', 'ion gradients'],
        },
        {
          id: 'mcat1-cp-024',
          sectionId: 'chem-phys',
          passageId: 'cp-p4',
          questionType: 'passage',
          discipline: 'Biology',
          contentCategory: 'Nervous system',
          foundationalConcept: 'FC 4',
          scientificSkill: 'Skill 2',
          difficulty: 'medium',
          question: 'Ouabain is a cardiac glycoside that blocks the Na⁺–K⁺ ATPase. After prolonged ouabain exposure, which change in resting membrane potential would be expected, and why?',
          choices: [
            { label: 'A', text: 'Hyperpolarization, because blocked pump reduces Na⁺ efflux, lowering intracellular positive charge' },
            { label: 'B', text: 'Depolarization, because intracellular Na⁺ rises and the K⁺ gradient dissipates over time' },
            { label: 'C', text: 'No change, because passive ion channels maintain the resting potential independently of active pumps' },
            { label: 'D', text: 'Transient hyperpolarization followed by sustained depolarization as the electrogenic pump contribution is first lost, then gradients collapse' },
          ],
          correctAnswer: 'B',
          explanation: 'The Na-K ATPase pumps Na⁺ out and K⁺ in, maintaining the gradients in Table 1. Ouabain blocks this pump, causing [Na⁺]_in to rise and [K⁺]_in to fall. As the K⁺ gradient dissipates, E_K becomes less negative, and the resting potential depolarizes progressively toward 0 mV.',
          wrongAnswerExplanations: {
            A: 'Blocking pump reduces K⁺ inside (not Na⁺ outside accumulation that lowers charge). As [K⁺]_in falls, E_K becomes less negative → depolarization, not hyperpolarization.',
            C: 'Passive channels move ions down their concentration gradients, but those gradients are actively maintained by the pump. Without the pump, gradients and the resting potential decay.',
            D: 'While the pump is slightly electrogenic (hyperpolarizing contribution), this effect is small. The dominant, sustained effect of pump blockade is depolarization from gradient dissipation, not a biphasic response.',
          },
          teachingPoint: 'Na-K ATPase maintains [K⁺]_in and [Na⁺]_out. Blocking it → [K⁺]_in falls → E_K less negative → Vm depolarizes. Clinically, cardiac glycosides raise intracellular Ca²⁺ indirectly via this Na⁺ accumulation, increasing contractility.',
          relatedTopics: ['Na-K ATPase', 'ouabain', 'cardiac glycosides', 'resting membrane potential', 'depolarization'],
        },
        {
          id: 'mcat1-cp-025',
          sectionId: 'chem-phys',
          passageId: 'cp-p4',
          questionType: 'passage',
          discipline: 'Biology',
          contentCategory: 'Nervous system',
          foundationalConcept: 'FC 4',
          scientificSkill: 'Skill 3',
          difficulty: 'hard',
          question: 'A researcher hypothesizes that the resting membrane potential is primarily determined by K⁺ permeability. Which experimental approach would most directly test this hypothesis?',
          choices: [
            { label: 'A', text: 'Block voltage-gated Na⁺ channels with tetrodotoxin (TTX) and record any change in resting potential' },
            { label: 'B', text: 'Vary extracellular [K⁺] over a 10-fold range and determine whether resting Vm shifts by ~61 mV per decade as predicted by the Nernst equation' },
            { label: 'C', text: 'Replace all extracellular Na⁺ with the impermeant cation choline⁺ and measure changes in resting potential' },
            { label: 'D', text: 'Inhibit the Na-K ATPase with ouabain and record resting potential over 30 minutes' },
          ],
          correctAnswer: 'B',
          explanation: 'If resting potential is dominated by K⁺ permeability, then Vm ≈ E_K. The Nernst equation predicts E_K shifts by 61.5 mV per 10-fold change in [K⁺]_out. Demonstrating this slope by systematically varying [K⁺]_out directly confirms K⁺ as the primary determinant. This is the classical experimental strategy used to validate the Goldman-Hodgkin-Katz model.',
          wrongAnswerExplanations: {
            A: 'TTX blocks voltage-gated Na⁺ channels (important during action potentials), not leak channels that set resting potential. Resting Vm may be largely unaffected by TTX, but this does not directly test K⁺ dominance.',
            C: 'Replacing Na⁺ with choline tests the contribution of Na⁺ gradient to resting potential — not whether K⁺ is dominant. The experiment must manipulate [K⁺]_out to test K⁺ dependence.',
            D: 'Ouabain alters all ion gradients simultaneously (Na⁺ and K⁺ both change). The resulting Vm change cannot be attributed to K⁺ alone, making this a poor test of K⁺-specific dominance.',
          },
          teachingPoint: 'To confirm K⁺ dominance: vary [K⁺]_out and verify ~61 mV/decade shift in Vm matching the Nernst prediction for K⁺. This is how physiologists established that the resting potential is primarily set by K⁺ leak conductance.',
          relatedTopics: ['experimental design', 'Nernst equation', 'K⁺ permeability', 'resting membrane potential', 'Goldman-Hodgkin-Katz'],
        },
      ],
    },
    {
      id: 'cp-p5',
      sectionId: 'chem-phys',
      title: 'Passage 5',
      passageText: `Spectrophotometry exploits the absorption of electromagnetic radiation by molecules in solution. When monochromatic light of intensity I₀ passes through a solution of path length b (cm) containing an absorbing species at molar concentration c (mol/L), the Beer-Lambert law describes the transmitted intensity I:

A = εbc = log(I₀ / I)

where A is absorbance (dimensionless), ε is the molar absorptivity (L·mol⁻¹·cm⁻¹), and transmittance T = I / I₀.

Proteins containing tryptophan (Trp) or tyrosine (Tyr) absorb UV light near 280 nm with ε₂₈₀ values ranging from 5,500 to 40,000 L·mol⁻¹·cm⁻¹ depending on amino acid composition. Nucleic acids absorb maximally at 260 nm. The A₂₈₀/A₂₆₀ ratio exceeds 1.8 for pure protein; nucleic acid contamination lowers this ratio toward 1.0.

A researcher characterizes a purified kinase enzyme (ε₂₈₀ = 40,000 L·mol⁻¹·cm⁻¹) using a 1.0 cm path length cuvette. Absorbance data are summarized in Table 1.

Table 1: Absorbance data for the kinase enzyme at 280 nm

| Sample | Concentration (µM) | A₂₈₀ |
|--------|--------------------|------|
| 1      | 2.5                | 0.10 |
| 2      | 5.0                | 0.20 |
| 3      | 10.0               | 0.40 |
| 4      | 25.0               | 0.98 |

Note: Most spectrophotometers maintain a linear absorbance response only up to A ≈ 0.8. Above this limit, stray light and detector saturation cause measured A to be lower than the true value.`,
      figures: [
        {
          type: 'table',
          title: 'Table 1: Absorbance data for the kinase enzyme at 280 nm',
          headers: ['Sample', 'Concentration (µM)', 'A₂₈₀'],
          rows: [
            ['1', '2.5', '0.10'],
            ['2', '5.0', '0.20'],
            ['3', '10.0', '0.40'],
            ['4', '25.0', '0.98'],
          ],
        },
      ],
      questions: [
        {
          id: 'mcat1-cp-026',
          sectionId: 'chem-phys',
          passageId: 'cp-p5',
          questionType: 'passage',
          discipline: 'General Chemistry',
          contentCategory: 'Spectroscopy',
          foundationalConcept: 'FC 4: Complex living organisms transport materials, sense their environment, process signals, and respond to changes using processes understood in terms of physical principles.',
          scientificSkill: 'Skill 4',
          difficulty: 'medium',
          question: 'An unknown sample of the kinase shows A₂₈₀ = 0.50 in a 1.0 cm cuvette. Using the molar absorptivity given in the passage, what is the enzyme concentration?',
          choices: [
            { label: 'A', text: '5.0 µM' },
            { label: 'B', text: '12.5 µM' },
            { label: 'C', text: '50.0 µM' },
            { label: 'D', text: '80.0 µM' },
          ],
          correctAnswer: 'B',
          explanation: 'From Beer-Lambert: c = A / (εb) = 0.50 / (40,000 L·mol⁻¹·cm⁻¹ × 1.0 cm) = 0.50 / 40,000 = 1.25 × 10⁻⁵ mol/L = 12.5 µM. This is consistent with Table 1: at 10.0 µM, A = 0.40; at 12.5 µM, A = 0.50 by linear extrapolation.',
          wrongAnswerExplanations: {
            A: '5.0 µM gives A = 40,000 × 5×10⁻⁶ × 1 = 0.20, not 0.50. This is Sample 2\'s concentration.',
            C: '50 µM gives A = 40,000 × 50×10⁻⁶ × 1 = 2.0, far above the measured 0.50 and outside the linear Beer-Lambert range.',
            D: '80 µM would correspond to A = 3.2 — far above the linear range. This likely results from dividing ε by A rather than dividing A by ε.',
          },
          teachingPoint: 'Rearrange Beer-Lambert: c = A / (εb). With A = 0.50, ε = 40,000 L·mol⁻¹·cm⁻¹, b = 1 cm: c = 1.25×10⁻⁵ M = 12.5 µM.',
          relatedTopics: ['Beer-Lambert law', 'molar absorptivity', 'protein quantification', 'spectrophotometry'],
        },
        {
          id: 'mcat1-cp-027',
          sectionId: 'chem-phys',
          passageId: 'cp-p5',
          questionType: 'passage',
          discipline: 'General Chemistry',
          contentCategory: 'Spectroscopy',
          foundationalConcept: 'FC 4',
          scientificSkill: 'Skill 1',
          difficulty: 'easy',
          question: 'A researcher switches from a 1.0 cm cuvette to a 2.0 cm cuvette to measure the same 5.0 µM enzyme solution. What absorbance reading should be expected at 280 nm?',
          choices: [
            { label: 'A', text: '0.10' },
            { label: 'B', text: '0.20' },
            { label: 'C', text: '0.28' },
            { label: 'D', text: '0.40' },
          ],
          correctAnswer: 'D',
          explanation: 'Beer-Lambert: A = εbc. All parameters are constant except b, which doubles from 1.0 to 2.0 cm. Therefore A doubles: 2 × 0.20 = 0.40. The same result is observed for 10.0 µM at 1.0 cm (Sample 3 in Table 1), confirming the linear relationship.',
          wrongAnswerExplanations: {
            A: '0.10 is the absorbance at 2.5 µM with a 1.0 cm path (Sample 1). Doubling path length increases, not decreases, absorbance.',
            B: '0.20 is the absorbance at 5.0 µM with the original 1.0 cm cuvette (Sample 2). Path length has doubled, so A must be larger.',
            C: '0.28 would imply A ∝ √b, a square-root relationship. Beer-Lambert predicts a direct linear proportionality between A and b.',
          },
          teachingPoint: 'A = εbc: absorbance is directly proportional to path length b. Doubling b doubles A. At 5.0 µM with b = 2.0 cm: A = 40,000 × 5×10⁻⁶ × 2 = 0.40.',
          relatedTopics: ['Beer-Lambert law', 'path length', 'absorbance linearity', 'cuvette'],
        },
        {
          id: 'mcat1-cp-028',
          sectionId: 'chem-phys',
          passageId: 'cp-p5',
          questionType: 'passage',
          discipline: 'Physics',
          contentCategory: 'Light and electromagnetic radiation',
          foundationalConcept: 'FC 4',
          scientificSkill: 'Skill 1',
          difficulty: 'easy',
          question: 'The kinase absorbs maximally at 280 nm (UV), while a fluorescent dye in solution absorbs at 560 nm (visible green). Which photon carries more energy, and by approximately what factor?',
          choices: [
            { label: 'A', text: '560 nm photon; approximately 2× more energy than the 280 nm photon' },
            { label: 'B', text: '280 nm photon; approximately 2× more energy than the 560 nm photon' },
            { label: 'C', text: 'Both carry equal energy because both are electromagnetic radiation traveling at speed c' },
            { label: 'D', text: '280 nm photon; approximately 4× more energy than the 560 nm photon' },
          ],
          correctAnswer: 'B',
          explanation: 'Photon energy E = hc/λ. Since h and c are constants, E ∝ 1/λ. The energy ratio E₂₈₀/E₅₆₀ = λ₅₆₀/λ₂₈₀ = 560/280 = 2. The 280 nm UV photon carries exactly twice the energy of the 560 nm visible photon. This is why UV radiation can break chemical bonds and cause DNA damage while visible light generally cannot.',
          wrongAnswerExplanations: {
            A: 'Longer wavelength (560 nm) corresponds to lower frequency and lower photon energy. E ∝ 1/λ, so 560 nm < 280 nm in energy.',
            C: 'All photons travel at c, but energy depends on frequency: E = hf = hc/λ. Different wavelengths carry different energies.',
            D: 'A factor of 4 is incorrect. Energy ratio = λ₅₆₀/λ₂₈₀ = 560/280 = 2, not 4. A 4-fold difference would require a 4-fold difference in wavelength.',
          },
          teachingPoint: 'E = hf = hc/λ. Shorter wavelength → higher frequency → higher energy. UV (280 nm) photons carry twice the energy of visible green (560 nm) photons: E ∝ 1/λ.',
          relatedTopics: ['photon energy', 'electromagnetic spectrum', 'UV vs. visible', 'wavelength-frequency-energy relationship'],
        },
        {
          id: 'mcat1-cp-029',
          sectionId: 'chem-phys',
          passageId: 'cp-p5',
          questionType: 'passage',
          discipline: 'General Chemistry',
          contentCategory: 'Spectroscopy',
          foundationalConcept: 'FC 4',
          scientificSkill: 'Skill 1',
          difficulty: 'medium',
          question: 'A concentrated protein solution transmits only 1% of incident light at 280 nm. What is the absorbance of this solution?',
          choices: [
            { label: 'A', text: '0.5' },
            { label: 'B', text: '1.0' },
            { label: 'C', text: '2.0' },
            { label: 'D', text: '99.0' },
          ],
          correctAnswer: 'C',
          explanation: 'Transmittance T = I/I₀ = 0.01 (1%). A = log(I₀/I) = log(1/0.01) = log(100) = 2.0. Alternatively, A = −log(T) = −log(0.01) = 2.0. Per the passage note, this value exceeds the 0.8 reliability limit, so the reading would underestimate the true absorbance.',
          wrongAnswerExplanations: {
            A: '0.5 corresponds to T = 0.316 (%T ≈ 32%), not 1%. A = −log(0.316) = 0.5.',
            B: '1.0 corresponds to T = 0.10 (%T = 10%), not 1%. A = −log(0.10) = 1.0.',
            D: '99 is simply 100 − %T, the percent absorbed — not absorbance. Absorbance = −log(%T/100) = −log(0.01) = 2.0, which is dimensionless and not a percentage.',
          },
          teachingPoint: '%T = 1 → T = 0.01 → A = −log(0.01) = 2.0. Key conversions: %T = 100 → A = 0; %T = 10 → A = 1; %T = 1 → A = 2.',
          relatedTopics: ['absorbance', 'percent transmittance', 'Beer-Lambert law', 'spectrophotometry calculations'],
        },
        {
          id: 'mcat1-cp-030',
          sectionId: 'chem-phys',
          passageId: 'cp-p5',
          questionType: 'passage',
          discipline: 'General Chemistry',
          contentCategory: 'Spectroscopy',
          foundationalConcept: 'FC 4',
          scientificSkill: 'Skill 4',
          difficulty: 'medium',
          question: 'According to Table 1, which sample most clearly shows deviation from the linear Beer-Lambert relationship, and what does this indicate about the measurement?',
          choices: [
            { label: 'A', text: 'Sample 1 (2.5 µM, A = 0.10), because low absorbance values are below the instrument\'s detection limit' },
            { label: 'B', text: 'Sample 3 (10.0 µM, A = 0.40), because absorbance values above 0.40 are unreliable in most instruments' },
            { label: 'C', text: 'Sample 4 (25.0 µM, A = 0.98), because the measured absorbance is lower than the Beer-Lambert prediction and exceeds the stated reliability limit' },
            { label: 'D', text: 'No sample deviates; Beer-Lambert predicts exactly the values in Table 1' },
          ],
          correctAnswer: 'C',
          explanation: 'Beer-Lambert predicts A = εbc = 40,000 × 25×10⁻⁶ × 1 = 1.00 for Sample 4. The measured value is 0.98 — slightly below 1.00 — and it exceeds the A ≈ 0.8 linearity limit stated in the passage. This is consistent with stray light and detector saturation causing underestimation at high absorbance. Samples 1–3 all lie within the linear range (A ≤ 0.40).',
          wrongAnswerExplanations: {
            A: 'A = 0.10 is within the Beer-Lambert linear range and above the noise floor of modern UV-Vis instruments. Low absorbance reduces signal-to-noise but does not indicate deviation from linearity.',
            B: 'A = 0.40 is well within the linear range. The reliability limit stated in the passage is A ≈ 0.8, not 0.40.',
            D: 'Sample 4 shows a slight deviation: predicted A = 1.00 but measured A = 0.98. Beer-Lambert is not perfectly followed at high absorbance values, as stated in the passage.',
          },
          teachingPoint: 'Beer-Lambert linearity holds up to A ≈ 0.8. Above this, stray light causes measured A to read lower than the true value. To avoid error, dilute samples to bring A into the 0.1–0.8 range before measuring.',
          relatedTopics: ['Beer-Lambert law', 'linearity limits', 'stray light', 'spectrophotometer', 'absorbance range'],
        },
      ],
    },
  ],
  discreteQuestions: [
    {
      id: 'mcat1-cp-016',
      sectionId: 'chem-phys',
      passageId: null,
      questionType: 'discrete',
      discipline: 'General Chemistry',
      contentCategory: 'Thermodynamics and thermochemistry',
      foundationalConcept: 'FC 5',
      scientificSkill: 'Skill 1',
      difficulty: 'medium',
      question: 'A biochemical reaction has ΔH = -40 kJ/mol and ΔS = -100 J/mol·K at 310 K (physiological temperature). What is ΔG, and will this reaction proceed spontaneously?',
      choices: [
        { label: 'A', text: 'ΔG = -71 kJ/mol; spontaneous' },
        { label: 'B', text: 'ΔG = -9 kJ/mol; spontaneous' },
        { label: 'C', text: 'ΔG = +9 kJ/mol; non-spontaneous' },
        { label: 'D', text: 'ΔG = +71 kJ/mol; non-spontaneous' },
      ],
      correctAnswer: 'B',
      explanation: 'ΔG = ΔH − TΔS. ΔS = −100 J/mol·K, so TΔS = (310)(−100) = −31,000 J/mol. ΔG = −40,000 − (−31,000) = −40,000 + 31,000 = −9,000 J/mol = −9 kJ/mol. Negative ΔG → spontaneous.',
      wrongAnswerExplanations: {
        A: '−71 kJ/mol comes from ΔG = ΔH + TΔS (wrong sign on TΔS). The formula is ΔH − TΔS.',
        C: '+9 kJ/mol comes from treating ΔS as positive (+100 J/mol·K) instead of negative. Sign errors in ΔS are common.',
        D: '+71 kJ/mol comes from both using the wrong formula (ΔH + TΔS) and a sign error on ΔS.',
      },
      teachingPoint: 'ΔG = ΔH − TΔS. Here: ΔG = −40 − (310)(−0.1) = −40 + 31 = −9 kJ/mol. Negative ΔG = spontaneous. When ΔH < 0 and ΔS < 0, spontaneity depends on temperature.',
      relatedTopics: ['Gibbs free energy', 'thermodynamics', 'spontaneity', 'enthalpy', 'entropy'],
    },
    {
      id: 'mcat1-cp-017',
      sectionId: 'chem-phys',
      passageId: null,
      questionType: 'discrete',
      discipline: 'General Chemistry',
      contentCategory: 'Atomic and nuclear structure',
      foundationalConcept: 'FC 4',
      scientificSkill: 'Skill 1',
      difficulty: 'easy',
      question: 'A radioactive isotope has a half-life of 6 hours. Starting with 80 mg, how much remains after 24 hours?',
      choices: [
        { label: 'A', text: '2.5 mg' },
        { label: 'B', text: '5 mg' },
        { label: 'C', text: '10 mg' },
        { label: 'D', text: '20 mg' },
      ],
      correctAnswer: 'B',
      explanation: '24 hours / 6 hours per half-life = 4 half-lives. Amount remaining = 80 × (1/2)⁴ = 80/16 = 5 mg.',
      wrongAnswerExplanations: {
        A: '2.5 mg would be 5 half-lives (80/32). 24 hours = 4 half-lives with t₁/₂ = 6 h.',
        C: '10 mg would be 3 half-lives (80/8). This assumes 24/6 = 3, but 24/6 = 4.',
        D: '20 mg would be 2 half-lives (80/4). 24 hours / 6 = 4 half-lives, not 2.',
      },
      teachingPoint: 'Number of half-lives = total time / half-life = 24/6 = 4. Amount = initial × (½)ⁿ = 80 × (½)⁴ = 80/16 = 5 mg.',
      relatedTopics: ['radioactive decay', 'half-life', 'nuclear chemistry', 'exponential decay'],
    },
    {
      id: 'mcat1-cp-018',
      sectionId: 'chem-phys',
      passageId: null,
      questionType: 'discrete',
      discipline: 'Organic Chemistry',
      contentCategory: 'Carbonyl chemistry',
      foundationalConcept: 'FC 5',
      scientificSkill: 'Skill 1',
      difficulty: 'medium',
      question: 'During fatty acid synthesis, malonyl-CoA undergoes decarboxylative condensation with acetyl-CoA to extend the chain by two carbons. The CO₂ released comes from which functional group?',
      choices: [
        { label: 'A', text: 'Thioester of acetyl-CoA' },
        { label: 'B', text: 'Carboxylate group of malonyl-CoA' },
        { label: 'C', text: 'Beta-keto group produced after condensation' },
        { label: 'D', text: 'Phosphate group of CoA' },
      ],
      correctAnswer: 'B',
      explanation: 'Malonyl-CoA (HOOC-CH₂-CO-SCoA) contains a carboxylate group that is lost as CO₂ during the decarboxylative Claisen condensation. The decarboxylation drives the thermodynamically unfavorable condensation forward. The CO₂ comes from the C1 carboxylate of malonyl-CoA.',
      wrongAnswerExplanations: {
        A: 'The thioester of acetyl-CoA is the electrophile attacked by the malonyl carbanion. It contributes carbons to the product, not the CO₂.',
        C: 'The beta-keto group forms after condensation and is reduced in subsequent steps. It does not release CO₂ during chain extension.',
        D: 'CoA contains a pantetheine-phosphate-adenosine structure. The phosphate is not involved in CO₂ release during condensation.',
      },
      teachingPoint: 'In fatty acid synthesis, malonyl-CoA\'s free carboxylate (C1) is lost as CO₂ during decarboxylative condensation. This CO₂ release provides thermodynamic driving force for chain extension.',
      relatedTopics: ['fatty acid synthesis', 'malonyl-CoA', 'decarboxylation', 'Claisen condensation', 'FAS enzyme'],
    },
    {
      id: 'mcat1-cp-019',
      sectionId: 'chem-phys',
      passageId: null,
      questionType: 'discrete',
      discipline: 'Physics',
      contentCategory: 'Atomic structure and spectra',
      foundationalConcept: 'FC 4',
      scientificSkill: 'Skill 1',
      difficulty: 'easy',
      question: 'An electron in a hydrogen atom transitions from n=3 to n=1. How does the energy and wavelength of the emitted photon compare to a transition from n=2 to n=1?',
      choices: [
        { label: 'A', text: 'Higher energy, shorter wavelength' },
        { label: 'B', text: 'Higher energy, longer wavelength' },
        { label: 'C', text: 'Lower energy, shorter wavelength' },
        { label: 'D', text: 'Lower energy, longer wavelength' },
      ],
      correctAnswer: 'A',
      explanation: 'The n=3→1 transition spans a larger energy gap than n=2→1. More energy released → higher energy photon. Since E = hc/λ, higher E corresponds to shorter λ. The n=3→1 transition emits UV light (Lyman series); n=2→1 emits lower-energy UV.',
      wrongAnswerExplanations: {
        B: 'Higher energy photons have shorter, not longer, wavelengths. E = hc/λ: E and λ are inversely proportional.',
        C: 'n=3→1 spans a larger gap than n=2→1, so more energy is released — not less.',
        D: 'Both premises are wrong: n=3→1 releases more energy (not less) with a shorter wavelength (not longer).',
      },
      teachingPoint: 'Larger energy gap → higher energy photon → shorter wavelength. E = hf = hc/λ. The n=3→1 jump is larger than n=2→1, so the emitted photon is more energetic and has a shorter wavelength.',
      relatedTopics: ['Bohr model', 'atomic emission', 'energy levels', 'photon wavelength', 'Lyman series'],
    },
    {
      id: 'mcat1-cp-020',
      sectionId: 'chem-phys',
      passageId: null,
      questionType: 'discrete',
      discipline: 'General Chemistry',
      contentCategory: 'Electrochemistry',
      foundationalConcept: 'FC 5',
      scientificSkill: 'Skill 1',
      difficulty: 'medium',
      question: 'A galvanic cell is constructed with Zn²⁺/Zn (E° = -0.76 V) and Cu²⁺/Cu (E° = +0.34 V) half-cells. What is the standard cell potential (E°cell) and which metal is oxidized?',
      choices: [
        { label: 'A', text: 'E°cell = +1.10 V; Zn is oxidized' },
        { label: 'B', text: 'E°cell = +1.10 V; Cu is oxidized' },
        { label: 'C', text: 'E°cell = -1.10 V; Zn is oxidized' },
        { label: 'D', text: 'E°cell = -0.42 V; Cu is oxidized' },
      ],
      correctAnswer: 'A',
      explanation: 'E°cell = E°cathode − E°anode. The more positive half-cell (Cu²⁺/Cu, +0.34 V) is the cathode (reduction). Zn/Zn²⁺ (−0.76 V) is the anode (oxidation). E°cell = 0.34 − (−0.76) = +1.10 V. Positive E°cell confirms spontaneous galvanic cell. Zn is oxidized.',
      wrongAnswerExplanations: {
        B: 'Cu is not oxidized — Cu²⁺ is reduced at the cathode. The stronger reducing agent (more negative E°) is oxidized: that is Zn.',
        C: 'A negative E°cell would mean a non-spontaneous reaction. Zn anode and Cu cathode gives a positive (spontaneous) cell.',
        D: '-0.42 V would come from adding E° values with wrong signs. E°cell = E°cathode − E°anode = 0.34 − (−0.76) = +1.10 V.',
      },
      teachingPoint: 'E°cell = E°cathode − E°anode. Reduction occurs at cathode (higher E°). Oxidation at anode (lower E°). Zn (-0.76 V) is oxidized; Cu²⁺ (+0.34 V) is reduced. E°cell = 0.34 - (-0.76) = +1.10 V.',
      relatedTopics: ['galvanic cell', 'standard reduction potential', 'electrochemistry', 'anode', 'cathode'],
    },
    {
      id: 'mcat1-cp-031',
      sectionId: 'chem-phys',
      passageId: null,
      questionType: 'discrete',
      discipline: 'General Chemistry',
      contentCategory: 'Solutions and colligative properties',
      foundationalConcept: 'FC 5: The principles that govern chemical interactions and reactions.',
      scientificSkill: 'Skill 2',
      difficulty: 'medium',
      question: 'A researcher immerses human erythrocytes in a 0.60 M sucrose solution (sucrose is membrane-impermeant; van\'t Hoff factor i = 1). Normal blood osmolarity is 285 mOsm/L. Which outcome is most likely?',
      choices: [
        { label: 'A', text: 'The cells lyse because the sucrose solution is hypotonic relative to blood' },
        { label: 'B', text: 'The cells undergo crenation because the sucrose solution is hypertonic and water exits by osmosis' },
        { label: 'C', text: 'No change occurs because sucrose cannot cross the membrane and therefore exerts no osmotic effect' },
        { label: 'D', text: 'The cells first swell, then shrink as sucrose gradually equilibrates across the membrane' },
      ],
      correctAnswer: 'B',
      explanation: '0.60 M sucrose with i = 1 has an osmolarity of 600 mOsm/L — more than twice normal blood osmolarity (285 mOsm/L). The sucrose solution is therefore hypertonic. Water moves by osmosis from the cells (lower osmolarity) into the surrounding solution (higher osmolarity), causing crenation (cell shrinkage).',
      wrongAnswerExplanations: {
        A: '600 mOsm/L > 285 mOsm/L, so the sucrose solution is hypertonic, not hypotonic. Hypotonic solutions cause lysis (water enters cells); hypertonic solutions cause crenation (water exits cells).',
        C: 'Membrane impermeability to sucrose is precisely what makes sucrose an effective osmotic agent. The solute establishes an osmotic gradient that drives water movement through aquaporins. Impermeable solutes cause full osmotic effect.',
        D: 'Since sucrose is membrane-impermeant (does not cross the membrane), it cannot enter the cell. The cells shrink continuously; there is no subsequent reswelling.',
      },
      teachingPoint: 'Osmolarity 0.60 M sucrose = 600 mOsm/L >> 285 mOsm/L → hypertonic → water exits → crenation. Membrane-impermeant solutes exert full osmotic effect. Isotonic NaCl ≈ 0.9% w/v ≈ 308 mOsm/L.',
      relatedTopics: ['osmolarity', 'tonicity', 'crenation', 'osmosis', 'colligative properties'],
    },
    {
      id: 'mcat1-cp-032',
      sectionId: 'chem-phys',
      passageId: null,
      questionType: 'discrete',
      discipline: 'General Chemistry',
      contentCategory: 'Atomic and nuclear structure',
      foundationalConcept: 'FC 4',
      scientificSkill: 'Skill 1',
      difficulty: 'easy',
      question: 'Radon-222 (²²²₈₆Rn) is a naturally occurring radioactive gas produced in uranium decay chains. It undergoes alpha decay. Which of the following correctly represents the products?',
      choices: [
        { label: 'A', text: '²¹⁸₈₄Po + ⁴₂He' },
        { label: 'B', text: '²²²₈₇Fr + ⁰₋₁e' },
        { label: 'C', text: '²¹⁸₈₃Bi + ⁴₂He' },
        { label: 'D', text: '²²²₈₆Rn + γ' },
      ],
      correctAnswer: 'A',
      explanation: 'In alpha decay, the parent nucleus emits an alpha particle (⁴₂He): mass number A decreases by 4 and atomic number Z decreases by 2. ²²²₈₆Rn → ²¹⁸₈₄Po + ⁴₂He. Mass check: 222 − 4 = 218 ✓. Charge check: 86 − 2 = 84 (polonium) ✓.',
      wrongAnswerExplanations: {
        B: '²²²₈₇Fr + ⁰₋₁e describes beta-minus decay (neutron → proton + electron + antineutrino), which increases Z by 1. Alpha decay decreases Z by 2.',
        C: '²¹⁸₈₃Bi would require Z to decrease by 3 (86 → 83). Alpha decay decreases Z by exactly 2: 86 − 2 = 84 (polonium, not bismuth which is Z = 83).',
        D: 'Gamma decay (γ) involves emission of a high-energy photon from a nuclear excited state with no change in A or Z. Radon-222\'s primary decay mode is alpha, which changes both A and Z.',
      },
      teachingPoint: 'Alpha decay: A − 4, Z − 2. ²²²₈₆Rn → ²¹⁸₈₄Po + ⁴₂He. Decay type summary: α (−4A, −2Z), β⁻ (+1Z, A unchanged), β⁺ (−1Z, A unchanged), γ (no A or Z change).',
      relatedTopics: ['alpha decay', 'nuclear reactions', 'conservation laws', 'radioactive series', 'decay type comparison'],
    },
    {
      id: 'mcat1-cp-033',
      sectionId: 'chem-phys',
      passageId: null,
      questionType: 'discrete',
      discipline: 'General Chemistry',
      contentCategory: 'Solutions and colligative properties',
      foundationalConcept: 'FC 5',
      scientificSkill: 'Skill 1',
      difficulty: 'medium',
      question: '5.85 g of NaCl (molar mass = 58.5 g/mol) is dissolved in 1.00 kg of water. The ebullioscopic constant for water is Kb = 0.512 °C·kg/mol. What is the expected boiling point of this solution at 1 atm?',
      choices: [
        { label: 'A', text: '100.05°C' },
        { label: 'B', text: '100.10°C' },
        { label: 'C', text: '100.20°C' },
        { label: 'D', text: '101.02°C' },
      ],
      correctAnswer: 'B',
      explanation: 'Moles NaCl = 5.85 g / 58.5 g/mol = 0.100 mol. Molality m = 0.100 mol / 1.00 kg = 0.100 m. NaCl dissociates into Na⁺ and Cl⁻, so van\'t Hoff factor i = 2. ΔTb = i × Kb × m = 2 × 0.512 × 0.100 = 0.1024°C ≈ 0.10°C. Boiling point = 100.00 + 0.10 = 100.10°C.',
      wrongAnswerExplanations: {
        A: '100.05°C results from using i = 1 (treating NaCl as a non-electrolyte): ΔTb = 1 × 0.512 × 0.100 = 0.051°C. NaCl fully dissociates into two ions, so i = 2.',
        C: '100.20°C would require ΔTb = 0.20°C, corresponding to i = 4 or m = 0.20 m — neither is correct for 0.100 mol NaCl in 1.00 kg water.',
        D: '101.02°C would require ΔTb = 1.02°C, arising from using m = 1.0 mol/kg (forgetting to divide by the 1.0 kg solvent) or a severe calculation error.',
      },
      teachingPoint: 'ΔTb = i × Kb × m. For NaCl (i = 2): ΔTb = 2 × 0.512 × 0.100 = 0.10°C → bp = 100.10°C. The van\'t Hoff factor i counts the total number of particles from one formula unit.',
      relatedTopics: ['boiling point elevation', 'colligative properties', 'van\'t Hoff factor', 'molality', 'electrolyte solutions'],
    },
    {
      id: 'mcat1-cp-034',
      sectionId: 'chem-phys',
      passageId: null,
      questionType: 'discrete',
      discipline: 'Physics',
      contentCategory: 'Gas phase and kinetic-molecular theory',
      foundationalConcept: 'FC 4',
      scientificSkill: 'Skill 1',
      difficulty: 'easy',
      question: 'A scuba diver breathes compressed air at a total pressure of 3.0 atm (equivalent to about 20 m depth). Dry air contains 21% O₂ and 79% N₂ by mole fraction. According to Dalton\'s Law of Partial Pressures, what is the partial pressure of N₂ in the diver\'s lungs?',
      choices: [
        { label: 'A', text: '0.79 atm' },
        { label: 'B', text: '1.0 atm' },
        { label: 'C', text: '2.37 atm' },
        { label: 'D', text: '3.0 atm' },
      ],
      correctAnswer: 'C',
      explanation: 'Dalton\'s Law: P_N₂ = χ_N₂ × P_total = 0.79 × 3.0 atm = 2.37 atm. At elevated depth, this high partial pressure of N₂ increases dissolved N₂ in blood and tissues (Henry\'s Law), potentially causing nitrogen narcosis at depth and decompression sickness (the bends) on rapid ascent.',
      wrongAnswerExplanations: {
        A: '0.79 atm is the partial pressure of N₂ at sea level (total P = 1 atm). At 3 atm total pressure, each component\'s partial pressure is 3× the sea-level value.',
        B: '1.0 atm does not follow from these data. This would only apply if the N₂ mole fraction were 1/3 (33%), not 79%.',
        D: '3.0 atm is the total pressure of the gas mixture, not the partial pressure of N₂. N₂ contributes 79% of the total (2.37 atm), and O₂ contributes 21% (0.63 atm).',
      },
      teachingPoint: 'Dalton\'s Law: P_partial = χ_mole × P_total. At 3 atm depth: P_N₂ = 0.79 × 3 = 2.37 atm; P_O₂ = 0.21 × 3 = 0.63 atm. Physiological applications: nitrogen narcosis (high P_N₂) and oxygen toxicity (high P_O₂).',
      relatedTopics: ['Dalton\'s Law', 'partial pressure', 'mole fraction', 'gas laws', 'Henry\'s Law', 'diving physiology'],
    },
    {
      id: 'mcat1-cp-035',
      sectionId: 'chem-phys',
      passageId: null,
      questionType: 'discrete',
      discipline: 'General Chemistry',
      contentCategory: 'Equilibrium and thermodynamics',
      foundationalConcept: 'FC 5',
      scientificSkill: 'Skill 2',
      difficulty: 'medium',
      question: 'For the equilibrium reaction N₂(g) + O₂(g) ⇌ 2NO(g), ΔH = +181 kJ/mol, the temperature is increased from 25°C to 500°C while volume is held constant. How does the equilibrium respond?',
      choices: [
        { label: 'A', text: 'Equilibrium shifts toward NO; [NO] increases and Keq increases' },
        { label: 'B', text: 'Equilibrium shifts toward N₂ and O₂; [NO] decreases because the reverse reaction is favored at higher temperature' },
        { label: 'C', text: 'No change in equilibrium position; temperature affects reaction rates but not Keq' },
        { label: 'D', text: 'Equilibrium shifts toward NO, but Keq remains constant because concentration changes are proportional' },
      ],
      correctAnswer: 'A',
      explanation: 'The reaction is endothermic (ΔH = +181 kJ/mol), so heat can be treated as a reactant: N₂ + O₂ + heat ⇌ 2NO. Increasing temperature adds more "reactant" (heat), shifting equilibrium to the right and increasing [NO]. For endothermic reactions, Keq increases with temperature (van\'t Hoff equation: d ln Keq / dT = ΔH°/RT² > 0 when ΔH° > 0).',
      wrongAnswerExplanations: {
        B: 'Equilibrium shifting toward reactants at higher temperature occurs for exothermic reactions (where heat is treated as a product). This reaction is endothermic, so the forward reaction is favored as temperature rises.',
        C: 'Temperature directly changes Keq via the van\'t Hoff relationship. Keq is not constant across temperatures for non-zero ΔH° reactions. Temperature affects both rates and equilibrium position.',
        D: 'If equilibrium shifts right (more product), Keq must increase — a larger ratio of products to reactants at equilibrium. Keq cannot remain constant if the equilibrium position changes at a given temperature.',
      },
      teachingPoint: 'Le Chatelier: treat heat as reactant (endothermic) or product (exothermic). Endothermic + ↑T → shifts right → ↑Keq. Exothermic + ↑T → shifts left → ↓Keq. Keq is only constant when temperature is constant.',
      relatedTopics: ['Le Chatelier\'s principle', 'endothermic equilibrium', 'equilibrium constant temperature dependence', 'van\'t Hoff equation'],
    },
  ],
}
