import type { MCATSection } from './types'

export const carsSection: MCATSection = {
  id: 'cars',
  title: 'Critical Analysis and Reasoning Skills',
  abbreviation: 'CARS',
  questionCount: 53,
  seededCount: 20,
  timeMinutes: 90,
  breakAfterMinutes: 30,
  breakType: 'long',
  passages: [
    {
      id: 'cars-p1',
      sectionId: 'cars',
      title: 'Passage 1',
      passageText: `The hypothesis that language shapes thought — often called the Sapir-Whorf hypothesis — has occupied linguists and philosophers since Benjamin Lee Whorf proposed, in the mid-twentieth century, that the grammar and vocabulary of one's native language determine the categories through which one perceives and reasons about the world. In its strong form, the hypothesis implies that speakers of languages without a future tense cannot conceptualize future time, and that people whose language lacks color terms for blue and green cannot perceptually distinguish those hues. These claims proved empirically untenable. Speakers of Mandarin, a language with no obligatory grammatical marking of future events, demonstrate no impairment in planning or anticipating the future. Speakers of languages with fewer basic color terms nonetheless pass visual discrimination tasks that require distinguishing wavelengths in the blue-green range.

Yet the strong formulation's failure does not discredit a subtler position. Cognitive scientists have accumulated evidence that language influences — rather than determines — certain aspects of cognition. Cross-linguistic studies of spatial reasoning find that speakers of languages that privilege absolute directions (north, south, east, west) over egocentric directions (left, right) are more reliably oriented to compass points, even when blindfolded and rotated. This is a genuine difference in habitual cognition that correlates with linguistic convention, yet it stops well short of claiming that egocentric-language speakers cannot orient themselves absolutely when required to do so. The linguistic influence is a matter of default tendency, not categorical inability.

The philosophical stakes of even the weak hypothesis are not trivial. If language shapes the grooves along which thought habitually runs, then monolingual individuals may be cognitively disadvantaged in contexts that reward alternative framings. This implication has animated debates about language policy, bilingual education, and the epistemic value of preserving endangered languages. Critics argue that such claims romanticize linguistic diversity by overstating its cognitive consequences; defenders respond that what is modest as a scientific claim may still be significant as a cultural and political one. The gap between the empirical finding and the normative conclusion is wide, and traversing it requires arguments that the scientific literature alone cannot supply.`,
      questions: [
        {
          id: 'mcat1-cars-001',
          sectionId: 'cars',
          passageId: 'cars-p1',
          questionType: 'passage',
          discipline: 'CARS',
          contentCategory: 'Foundations of Comprehension',
          foundationalConcept: 'FC 6: Biological, psychological, and socio-cultural factors influence the way we think about ourselves and others.',
          scientificSkill: 'Skill 1',
          difficulty: 'easy',
          question: 'The central argument of the passage is best described as which of the following?',
          choices: [
            { label: 'A', text: 'The strong version of the Sapir-Whorf hypothesis is empirically confirmed and has important policy implications.' },
            { label: 'B', text: 'Language influences habitual patterns of thought without determining the limits of cognition, and even modest linguistic effects carry non-trivial philosophical stakes.' },
            { label: 'C', text: 'Monolingual speakers are cognitively disadvantaged compared to bilingual speakers in all domains of reasoning.' },
            { label: 'D', text: 'Cross-linguistic differences in spatial reasoning prove that language determines how people perceive the world.' },
          ],
          correctAnswer: 'B',
          explanation: 'The passage refutes the strong Sapir-Whorf hypothesis (first paragraph) but defends a weaker version: language influences habitual cognition without setting hard limits (second paragraph). The third paragraph extends this to note philosophical and policy stakes. Choice B captures both moves.',
          wrongAnswerExplanations: {
            A: 'The passage explicitly states the strong hypothesis "proved empirically untenable." It supports only the weak version.',
            C: 'The passage does not claim monolingual speakers are disadvantaged in all domains. The potential disadvantage is described as hypothetical and debated.',
            D: 'The spatial reasoning data supports influence, not determination. The passage explicitly distinguishes "default tendency" from "categorical inability."',
          },
          teachingPoint: 'CARS central argument questions require tracking how the passage qualifies or nuances its main claim. Here: strong hypothesis → refuted; weak hypothesis → defended; policy stakes → noted.',
          relatedTopics: ['Sapir-Whorf hypothesis', 'linguistic relativity', 'cognitive linguistics'],
        },
        {
          id: 'mcat1-cars-002',
          sectionId: 'cars',
          passageId: 'cars-p1',
          questionType: 'passage',
          discipline: 'CARS',
          contentCategory: 'Reasoning Within the Text',
          foundationalConcept: 'FC 6',
          scientificSkill: 'Skill 2',
          difficulty: 'medium',
          question: 'The author mentions Mandarin speakers\' ability to plan for the future primarily in order to:',
          choices: [
            { label: 'A', text: 'illustrate the cognitive superiority of speakers whose languages mark future tense grammatically' },
            { label: 'B', text: 'demonstrate that cross-linguistic differences in grammar do not translate into categorical differences in cognition' },
            { label: 'C', text: 'support the claim that all languages are cognitively equivalent in every domain' },
            { label: 'D', text: 'provide evidence for the strong version of the Sapir-Whorf hypothesis' },
          ],
          correctAnswer: 'B',
          explanation: 'The Mandarin example appears in the refutation of the strong hypothesis. The author uses it to show that lacking obligatory future-tense marking does not impair future-oriented reasoning — countering the deterministic claim.',
          wrongAnswerExplanations: {
            A: 'The passage makes no claim about cognitive superiority of any group of speakers. The point is equivalence in this domain.',
            C: 'The author does not claim total cognitive equivalence — the spatial reasoning example later shows real differences in habits. The claim is narrower.',
            D: 'The Mandarin example refutes the strong hypothesis, not supports it.',
          },
          teachingPoint: 'When asked about the function of a specific example, locate it in the passage structure. Here it sits in the paragraph refuting the strong hypothesis → its function is refutation/counterevidence.',
          relatedTopics: ['Sapir-Whorf', 'grammar and cognition', 'counterexample function'],
        },
        {
          id: 'mcat1-cars-003',
          sectionId: 'cars',
          passageId: 'cars-p1',
          questionType: 'passage',
          discipline: 'CARS',
          contentCategory: 'Reasoning Beyond the Text',
          foundationalConcept: 'FC 6',
          scientificSkill: 'Skill 2',
          difficulty: 'hard',
          question: 'Which of the following findings, if true, would most directly challenge the weak version of the Sapir-Whorf hypothesis as described in the passage?',
          choices: [
            { label: 'A', text: 'Speakers of languages with absolute spatial terms outperform egocentric-language speakers on compass orientation tasks even after a single training session.' },
            { label: 'B', text: 'After extensive training, speakers of egocentric-direction languages perform just as well on absolute spatial orientation tasks as absolute-direction speakers.' },
            { label: 'C', text: 'Bilingual speakers show no cognitive advantages over monolingual speakers on spatial reasoning tasks.' },
            { label: 'D', text: 'Color perception differences across language groups persist even under conditions of high visual contrast.' },
          ],
          correctAnswer: 'B',
          explanation: 'The weak hypothesis holds that language shapes habitual cognitive tendencies, producing real (if overridable) differences. If egocentric-language speakers can match absolute-direction speakers after training alone — without changing their language — the linguistic influence is trivial. Choice B directly undercuts the claim of meaningful linguistic influence on spatial cognition.',
          wrongAnswerExplanations: {
            A: 'This would support, not challenge, the weak hypothesis by confirming the performance difference between language groups.',
            C: 'Bilingualism is discussed normatively in the third paragraph, not as the core empirical claim. This does not directly address the spatial-linguistic hypothesis.',
            D: 'Color perception differences are mentioned in the context of refuting the strong hypothesis. Persistent differences would support some version of linguistic influence, not challenge it.',
          },
          teachingPoint: 'Weakening questions require finding the passage\'s actual claim and identifying what evidence would undermine it. The weak hypothesis: language → habitual tendency differences. B shows differences disappear with training → no lasting linguistic influence.',
          relatedTopics: ['linguistic relativity', 'reasoning beyond the text', 'weakening arguments'],
        },
        {
          id: 'mcat1-cars-004',
          sectionId: 'cars',
          passageId: 'cars-p1',
          questionType: 'passage',
          discipline: 'CARS',
          contentCategory: 'Reasoning Within the Text',
          foundationalConcept: 'FC 6',
          scientificSkill: 'Skill 2',
          difficulty: 'medium',
          question: 'The author characterizes critics of the weak Sapir-Whorf hypothesis as arguing that linguistic diversity advocates "romanticize" their claims. The author\'s own attitude toward this criticism is best described as:',
          choices: [
            { label: 'A', text: 'Full agreement — the passage concludes the weak hypothesis has no meaningful implications' },
            { label: 'B', text: 'Full rejection — the author argues the critics are simply wrong' },
            { label: 'C', text: 'Partial acknowledgment — the author grants the empirical stakes are modest while defending the policy stakes as genuinely significant' },
            { label: 'D', text: 'Indifference — the author presents the debate without taking any position' },
          ],
          correctAnswer: 'C',
          explanation: 'The final paragraph presents both sides: critics say the cognitive effects are overstated (romanticization); defenders say the cultural/political implications remain significant even if the science is modest. The author endorses neither side completely, but frames the policy stakes as real while acknowledging the gap between scientific finding and normative conclusion.',
          wrongAnswerExplanations: {
            A: 'The author states the philosophical stakes are "not trivial" and that defenders have a legitimate point about cultural significance. This is not full agreement with critics.',
            B: 'The author does not dismiss the critics — the word "romanticize" is presented as a potentially fair characterization of overstatement.',
            D: 'The author takes a position: that the gap between scientific finding and normative conclusion "requires arguments the scientific literature alone cannot supply" — not neutral.',
          },
          teachingPoint: 'Author attitude questions require reading tone and hedging carefully. Phrases like "not trivial" and "may still be significant" signal a partial endorsement of the defenders\' position.',
          relatedTopics: ['author attitude', 'tone', 'language policy debate'],
        },
        {
          id: 'mcat1-cars-005',
          sectionId: 'cars',
          passageId: 'cars-p1',
          questionType: 'passage',
          discipline: 'CARS',
          contentCategory: 'Foundations of Comprehension',
          foundationalConcept: 'FC 6',
          scientificSkill: 'Skill 1',
          difficulty: 'easy',
          question: 'According to the passage, the spatial reasoning evidence for the weak Sapir-Whorf hypothesis differs from its strong version in that the weak version:',
          choices: [
            { label: 'A', text: 'makes no predictions about cross-linguistic cognitive differences' },
            { label: 'B', text: 'claims language shapes tendencies without making categorical differences impossible to overcome' },
            { label: 'C', text: 'applies only to spatial cognition and not to color perception or temporal reasoning' },
            { label: 'D', text: 'requires large-scale brain imaging studies rather than behavioral experiments to confirm' },
          ],
          correctAnswer: 'B',
          explanation: 'The passage explicitly describes the weak hypothesis as a matter of "default tendency, not categorical inability." Absolute-direction-language speakers are better oriented by default, but egocentric-language speakers can orient absolutely when required. This is the defining contrast with the strong version.',
          wrongAnswerExplanations: {
            A: 'The weak hypothesis does predict cross-linguistic differences — specifically in habitual tendencies. The author presents spatial data as evidence for it.',
            C: 'The passage does not limit the weak hypothesis to spatial cognition. Color and time examples appear in the strong-hypothesis refutation section, but the weak claim is broader.',
            D: 'The passage cites behavioral experiments (compass orientation while blindfolded), not brain imaging, as the relevant evidence.',
          },
          teachingPoint: '"Default tendency, not categorical inability" is the key phrase distinguishing weak from strong Sapir-Whorf. The weak version allows that linguistic habits shape, but do not imprison, thought.',
          relatedTopics: ['strong vs. weak Sapir-Whorf', 'cognitive tendency vs. cognitive limit'],
        },
      ],
    },
    {
      id: 'cars-p2',
      sectionId: 'cars',
      title: 'Passage 2',
      passageText: `Explanations of economic inequality typically divide into two camps: those that emphasize individual attributes — skill, education, work ethic — and those that emphasize structural conditions — labor market institutions, historical patterns of capital accumulation, and political power. The former approach, dominant in neoclassical economics, treats income as a return on human capital. Workers earn wages proportional to their marginal productivity, and inequality therefore reflects differences in what individuals contribute. The latter approach, more common in institutional and heterodox economics, argues that wages are set through bargaining processes shaped by power asymmetries, union density, minimum wage legislation, and the historical residue of race and gender discrimination. From this perspective, two workers with identical productivity may receive very different wages depending on the strength of their collective bargaining position and the political environment in which they operate.

The human capital framework has obvious appeal: it locates the determinants of earnings in factors that individuals can, at least in principle, change. Education and training programs become the policy instruments of choice. But critics argue this framing systematically underweights the role of initial conditions. A child born into poverty faces constraints on educational investment that are not the product of her choices or her parents' character, but of the economic position into which she was born. Returns on education, moreover, are not uniform: the credential obtained at a resource-poor school may yield substantially lower returns than the same credential from a more affluent institution — a difference that compounds rather than erodes initial disadvantage.

Structural accounts, in contrast, point to the dramatic declines in union membership in the United States since the 1970s as a proximate cause of wage stagnation for middle and lower-income workers. When workers cannot collectively bargain, the wage negotiated is the wage the employer prefers to offer. Minimum wage legislation functions similarly: where it is set influences the floor below which wages cannot fall, regardless of the productivity calculations that neoclassical models might predict. Neither of these factors appears in a model that treats wages as outputs of a competitive market clearing mechanism. The conclusion many structural economists draw is not that human capital is irrelevant, but that it operates within institutional constraints that significantly modulate its returns.`,
      questions: [
        {
          id: 'mcat1-cars-006',
          sectionId: 'cars',
          passageId: 'cars-p2',
          questionType: 'passage',
          discipline: 'CARS',
          contentCategory: 'Foundations of Comprehension',
          foundationalConcept: 'FC 6',
          scientificSkill: 'Skill 1',
          difficulty: 'easy',
          question: 'The passage\'s main argument is that:',
          choices: [
            { label: 'A', text: 'individual human capital is the most reliable predictor of wages and should be the focus of inequality policy' },
            { label: 'B', text: 'both human capital and structural factors shape wages, with institutional constraints modulating how human capital translates into earnings' },
            { label: 'C', text: 'union membership is the single most important determinant of wage levels in modern economies' },
            { label: 'D', text: 'neoclassical economic models are entirely wrong about how wages are set' },
          ],
          correctAnswer: 'B',
          explanation: 'The passage concludes: "human capital is not irrelevant, but it operates within institutional constraints that significantly modulate its returns." This integrates both frameworks rather than dismissing either. The final paragraph\'s conclusion is the key passage-level claim.',
          wrongAnswerExplanations: {
            A: 'The passage critiques the human capital framework for underweighting initial conditions and structural constraints. It does not endorse human capital as most reliable.',
            C: 'Union membership is one structural example, not the singular cause. The passage offers it as evidence alongside minimum wage legislation and historical discrimination.',
            D: 'The author does not claim neoclassical models are entirely wrong — the final sentence explicitly says "human capital is not irrelevant."',
          },
          teachingPoint: 'Look for the integrating conclusion in the final paragraph. Passages that present two competing views often end with a synthesis. Here: human capital matters but within structural constraints.',
          relatedTopics: ['human capital theory', 'structural economics', 'wage determination'],
        },
        {
          id: 'mcat1-cars-007',
          sectionId: 'cars',
          passageId: 'cars-p2',
          questionType: 'passage',
          discipline: 'CARS',
          contentCategory: 'Reasoning Within the Text',
          foundationalConcept: 'FC 6',
          scientificSkill: 'Skill 2',
          difficulty: 'medium',
          question: 'The author uses the example of a child born into poverty primarily to:',
          choices: [
            { label: 'A', text: 'argue that education policy is irrelevant to reducing inequality' },
            { label: 'B', text: 'show that the human capital framework ignores how initial conditions constrain individual choice' },
            { label: 'C', text: 'demonstrate that parental character determines children\'s economic outcomes' },
            { label: 'D', text: 'support the conclusion that structural factors alone explain inequality' },
          ],
          correctAnswer: 'B',
          explanation: 'The poverty example illustrates the critique of human capital theory: a child in poverty faces educational investment constraints "not the product of her choices," meaning the framework\'s assumption that individuals can change their human capital ignores the role of birth circumstances.',
          wrongAnswerExplanations: {
            A: 'The passage critiques how education returns are modulated by initial conditions, not that education policy is irrelevant. These are distinct claims.',
            C: 'The passage explicitly says the constraints are "not the product of her choices or her parents\' character" — the opposite of emphasizing parental character.',
            D: 'The example is part of a critique of human capital theory, but the passage does not conclude that structural factors alone explain inequality.',
          },
          teachingPoint: 'Identify what claim an example is supporting. Here: the example is in the paragraph critiquing human capital theory\'s blindness to initial conditions.',
          relatedTopics: ['initial conditions', 'human capital critique', 'inequality and opportunity'],
        },
        {
          id: 'mcat1-cars-008',
          sectionId: 'cars',
          passageId: 'cars-p2',
          questionType: 'passage',
          discipline: 'CARS',
          contentCategory: 'Reasoning Beyond the Text',
          foundationalConcept: 'FC 6',
          scientificSkill: 'Skill 2',
          difficulty: 'hard',
          question: 'A country with strong labor unions but a weakly enforced minimum wage reports rising inequality. Based on the passage\'s framework, which conclusion would structural economists most likely draw?',
          choices: [
            { label: 'A', text: 'The rising inequality is due entirely to declining worker productivity.' },
            { label: 'B', text: 'The weak minimum wage floor allows employers to drive wages below market-clearing levels for the lowest-paid workers, increasing inequality despite union protections for unionized workers.' },
            { label: 'C', text: 'The presence of unions proves structural factors have no effect on inequality in this country.' },
            { label: 'D', text: 'Rising inequality confirms the human capital framework, since workers must lack the right skills.' },
          ],
          correctAnswer: 'B',
          explanation: 'The passage identifies minimum wage legislation as setting the floor "below which wages cannot fall." A weak floor allows bottom-wage compression downward. Even with unions (protecting some workers), non-unionized low-wage workers lack both protections — consistent with structural analysis predicting increased inequality among those workers.',
          wrongAnswerExplanations: {
            A: 'Structural economists do not attribute inequality primarily to productivity differences — that is the human capital framework\'s explanation.',
            C: 'The presence of unions does not prove structural factors are irrelevant — it is one structural factor among several. Missing minimum wage protection illustrates other structural factors still matter.',
            D: 'The human capital framework predicts skill differences drive inequality. Structural economists would reject this in favor of institutional explanations.',
          },
          teachingPoint: 'Apply-the-framework questions require using the passage\'s logic on a new scenario. Structural framework: wages reflect institutional constraints (unions, minimum wage). Weak minimum wage → downward wage pressure for lowest-paid workers.',
          relatedTopics: ['minimum wage', 'union density', 'structural inequality'],
        },
        {
          id: 'mcat1-cars-009',
          sectionId: 'cars',
          passageId: 'cars-p2',
          questionType: 'passage',
          discipline: 'CARS',
          contentCategory: 'Reasoning Within the Text',
          foundationalConcept: 'FC 6',
          scientificSkill: 'Skill 2',
          difficulty: 'medium',
          question: 'The author\'s tone when describing the human capital framework is best characterized as:',
          choices: [
            { label: 'A', text: 'enthusiastically supportive' },
            { label: 'B', text: 'critically dismissive' },
            { label: 'C', text: 'acknowledging its appeal while identifying substantive limitations' },
            { label: 'D', text: 'neutral and purely descriptive without evaluation' },
          ],
          correctAnswer: 'C',
          explanation: 'The second paragraph opens "The human capital framework has obvious appeal" — acknowledging its intuitive plausibility — then pivots with "But critics argue..." to identify limitations around initial conditions and unequal educational returns. The tone is balanced critique, not dismissal or endorsement.',
          wrongAnswerExplanations: {
            A: 'The passage raises substantial criticisms of the human capital framework. "Obvious appeal" is followed immediately by "But critics argue..." — not enthusiastic endorsement.',
            B: 'The author acknowledges the framework\'s appeal and notes it "locates determinants in factors individuals can change." Dismissal would not grant these merits.',
            D: 'The passage is not neutral — it actively critiques the framework\'s blindness to initial conditions. The author has a clear perspective.',
          },
          teachingPoint: 'Tone questions often hinge on qualifiers. "Obvious appeal" + "But critics argue" = acknowledging strengths while raising criticisms. Neither pure praise nor pure dismissal.',
          relatedTopics: ['author tone', 'balanced critique', 'human capital theory'],
        },
        {
          id: 'mcat1-cars-010',
          sectionId: 'cars',
          passageId: 'cars-p2',
          questionType: 'passage',
          discipline: 'CARS',
          contentCategory: 'Foundations of Comprehension',
          foundationalConcept: 'FC 6',
          scientificSkill: 'Skill 1',
          difficulty: 'easy',
          question: 'According to the passage, what role does union density play in the structural account of wages?',
          choices: [
            { label: 'A', text: 'It determines workers\' human capital accumulation.' },
            { label: 'B', text: 'It shapes workers\' bargaining power, influencing the wages employers must offer.' },
            { label: 'C', text: 'It sets the legal minimum below which wages cannot fall.' },
            { label: 'D', text: 'It is irrelevant because wages are set by market-clearing mechanisms.' },
          ],
          correctAnswer: 'B',
          explanation: 'The passage states workers "cannot collectively bargain" without unions, so "the wage negotiated is the wage the employer prefers to offer." Union density therefore determines collective bargaining strength, which shapes wages. Minimum wage legislation is a separate mechanism (choice C).',
          wrongAnswerExplanations: {
            A: 'Human capital accumulation (education, skills) is the domain of the competing neoclassical framework, not the structural explanation involving unions.',
            C: 'The legal wage floor is the role of minimum wage legislation, described separately. Unions set bargaining power, not legal minimums.',
            D: 'This describes the neoclassical market-clearing view. The structural account is precisely that market-clearing mechanisms are inadequate explanations.',
          },
          teachingPoint: 'Distinguish between mechanisms: unions → bargaining power; minimum wage → legal floor. Both are structural factors but work differently.',
          relatedTopics: ['collective bargaining', 'union density', 'wage determination'],
        },
      ],
    },
    {
      id: 'cars-p3',
      sectionId: 'cars',
      title: 'Passage 3',
      passageText: `Virginia Woolf argued, in a series of essays written between the wars, that the novel had exhausted the conventions it inherited from the Victorian tradition — the omniscient narrator who surveys action from without, the plot organized around external events, the characters whose interiority is delivered through dialogue and behavior rather than accessed directly. These conventions, she suggested, were not neutral vehicles for representing experience but active constraints on what could be represented. The novel as she inherited it was, at its most fundamental level, shaped by the assumption that consciousness is opaque to direct presentation. A character's inner life could only be gestured at through what the character said and did; the narrator stood outside and interpreted.

Woolf's project was to dissolve this barrier. Her technique — which critics have called stream of consciousness, though she herself distrusted the phrase as too hydraulic — sought to render the texture of mental experience as it actually occurs: associative, discontinuous, emotionally inflected, layered with memory and anticipation. In Mrs. Dalloway, a walk through London becomes a vehicle for tracking a mind as it moves through time, connecting present perception to past memory and future anxiety. There is no stable narrator interpreting this movement for the reader. The reader must orient herself by following the movement of Clarissa Dalloway's consciousness directly.

What Woolf achieved, and what made her technique both celebrated and controversial, is that interiority itself becomes the primary medium of narrative. Plot is not abandoned but relocated: it moves from the external world of events to the internal world of perception and response. This relocation required new formal strategies — the free indirect style, the shifting temporal perspective, the sentence that mimics the rhythm of attention — and these strategies in turn required a reader willing to collaborate in the construction of meaning. The Victorian novel presupposed a reader who followed a story. The modernist novel presupposed a reader who participated in a consciousness.`,
      questions: [
        {
          id: 'mcat1-cars-011',
          sectionId: 'cars',
          passageId: 'cars-p3',
          questionType: 'passage',
          discipline: 'CARS',
          contentCategory: 'Foundations of Comprehension',
          foundationalConcept: 'FC 6',
          scientificSkill: 'Skill 1',
          difficulty: 'easy',
          question: 'The passage argues that Victorian novelistic conventions were:',
          choices: [
            { label: 'A', text: 'technically inferior to modernist techniques and therefore abandoned' },
            { label: 'B', text: 'not neutral vehicles but active constraints that limited what could be represented' },
            { label: 'C', text: 'incapable of depicting interiority in any form' },
            { label: 'D', text: 'preferred by readers who participated in constructing meaning' },
          ],
          correctAnswer: 'B',
          explanation: 'The first paragraph states directly: "These conventions...were not neutral vehicles for representing experience but active constraints on what could be represented." This is Woolf\'s critique as summarized by the passage.',
          wrongAnswerExplanations: {
            A: 'The passage does not evaluate Victorian conventions as "technically inferior." Woolf\'s argument is about what they can and cannot represent, not technical quality.',
            C: 'Victorian novels could gesture at interiority through dialogue and behavior — the passage says this was limited, not that it was completely absent.',
            D: 'Reader participation in constructing meaning is associated with modernist, not Victorian, novels (see the final sentence).',
          },
          teachingPoint: 'Locate direct quotations or paraphrases of the stated argument. "Not neutral vehicles but active constraints" is the passage\'s characterization of Victorian conventions.',
          relatedTopics: ['Victorian novel', 'literary convention', 'Woolf\'s critique'],
        },
        {
          id: 'mcat1-cars-012',
          sectionId: 'cars',
          passageId: 'cars-p3',
          questionType: 'passage',
          discipline: 'CARS',
          contentCategory: 'Reasoning Within the Text',
          foundationalConcept: 'FC 6',
          scientificSkill: 'Skill 2',
          difficulty: 'medium',
          question: 'The author notes that Woolf "distrusted the phrase" stream of consciousness as "too hydraulic." This most likely means Woolf believed the phrase:',
          choices: [
            { label: 'A', text: 'was too technical for general readers to understand' },
            { label: 'B', text: 'implied a continuous, flowing quality that failed to capture the discontinuous nature of mental experience' },
            { label: 'C', text: 'was inaccurate because her technique relied on external narration rather than internal experience' },
            { label: 'D', text: 'underestimated the political dimensions of her literary project' },
          ],
          correctAnswer: 'B',
          explanation: '"Hydraulic" connotes continuous, fluid flow. The passage describes mental experience as "associative, discontinuous, emotionally inflected" — not a smooth stream. The contrast between "stream" (continuous) and the actual texture of consciousness (discontinuous) is why Woolf distrusted the phrase.',
          wrongAnswerExplanations: {
            A: 'The concern is about accuracy, not accessibility. Woolf\'s objection is to what the metaphor implies about consciousness, not its difficulty for readers.',
            C: 'Woolf\'s technique does rely on internal experience — that is her entire project. The issue is with the metaphor\'s implications about that internal experience, not its interiority.',
            D: 'The passage does not associate the phrase objection with political concerns.',
          },
          teachingPoint: '"Hydraulic" describes fluid mechanics — smooth, continuous flow. Woolf\'s consciousness is discontinuous, not flowing. The metaphor misrepresents the texture of mind.',
          relatedTopics: ['stream of consciousness', 'literary metaphor', 'modernist technique'],
        },
        {
          id: 'mcat1-cars-013',
          sectionId: 'cars',
          passageId: 'cars-p3',
          questionType: 'passage',
          discipline: 'CARS',
          contentCategory: 'Reasoning Within the Text',
          foundationalConcept: 'FC 6',
          scientificSkill: 'Skill 2',
          difficulty: 'medium',
          question: 'The contrast drawn in the final paragraph between "a reader who followed a story" and "a reader who participated in a consciousness" serves primarily to:',
          choices: [
            { label: 'A', text: 'argue that modernist novels are more difficult and therefore superior' },
            { label: 'B', text: 'illustrate how the relocation of plot from external events to internal perception required a different kind of reader engagement' },
            { label: 'C', text: 'suggest that Victorian readers were passive while modernist readers are active' },
            { label: 'D', text: 'conclude that Woolf abandoned plot in favor of pure psychological description' },
          ],
          correctAnswer: 'B',
          explanation: 'The contrast appears as the culmination of the argument that Woolf relocated plot from external to internal. New formal strategies required a new reader: not a follower of events but a participant in consciousness. The contrast illustrates the shift in the nature of reader engagement that modernist technique demanded.',
          wrongAnswerExplanations: {
            A: 'The passage does not rank modernist over Victorian as superior — it describes the difference in what each presupposes.',
            C: 'While the contrast implies different kinds of engagement, the passage does not characterize Victorian reading as "passive." Following a story is a different activity, not an inferior or passive one.',
            D: 'The passage explicitly states "plot is not abandoned but relocated." This choice directly contradicts the text.',
          },
          teachingPoint: 'The "followed a story" vs. "participated in consciousness" contrast is the final distillation of the relocation-of-plot argument. Its function is to crystallize the new reader relationship that modernist technique requires.',
          relatedTopics: ['reader engagement', 'modernist novel', 'narrative technique'],
        },
        {
          id: 'mcat1-cars-014',
          sectionId: 'cars',
          passageId: 'cars-p3',
          questionType: 'passage',
          discipline: 'CARS',
          contentCategory: 'Reasoning Beyond the Text',
          foundationalConcept: 'FC 6',
          scientificSkill: 'Skill 2',
          difficulty: 'hard',
          question: 'Based on the passage\'s framework, which of the following best describes what a critic applying Woolf\'s principles would most likely say about a novel in which an omniscient narrator explains what each character is thinking and feeling throughout?',
          choices: [
            { label: 'A', text: 'It successfully renders the texture of mental experience as it actually occurs.' },
            { label: 'B', text: 'It relies on a convention that keeps the narrator outside consciousness, interpreting rather than accessing interiority directly.' },
            { label: 'C', text: 'It exemplifies the modernist technique Woolf championed.' },
            { label: 'D', text: 'It demonstrates that interiority is best represented through external action.' },
          ],
          correctAnswer: 'B',
          explanation: 'An omniscient narrator who explains character thoughts fits the Victorian model the passage describes: the narrator "stood outside and interpreted." According to Woolf\'s critique, this keeps the reader mediated from interiority. A critic applying Woolf\'s framework would identify it as the convention she was reacting against.',
          wrongAnswerExplanations: {
            A: 'Rendering "texture of mental experience as it actually occurs" describes Woolf\'s own project, not the omniscient narrator model she criticized.',
            C: 'An omniscient narrator interpreting interiority is Victorian, not modernist. Woolf\'s modernist technique aimed to dissolve the narrative barrier.',
            D: 'Woolf\'s critique is precisely that Victorian technique mediated interiority through external action (dialogue, behavior) — this choice aligns with the Victorian approach, not a Woolfian endorsement.',
          },
          teachingPoint: 'Apply-the-author\'s-framework questions: apply the passage\'s explicit criteria to a new case. Omniscient narrator interpreting interiority = Victorian convention Woolf critiqued.',
          relatedTopics: ['omniscient narrator', 'Victorian vs. modernist', 'Woolf\'s literary project'],
        },
        {
          id: 'mcat1-cars-015',
          sectionId: 'cars',
          passageId: 'cars-p3',
          questionType: 'passage',
          discipline: 'CARS',
          contentCategory: 'Foundations of Comprehension',
          foundationalConcept: 'FC 6',
          scientificSkill: 'Skill 1',
          difficulty: 'easy',
          question: 'What does the author mean by saying that plot in Woolf\'s work is "relocated" rather than abandoned?',
          choices: [
            { label: 'A', text: 'Woolf retains traditional external plot structures but adds psychological depth.' },
            { label: 'B', text: 'The organizing principle of the narrative shifts from external events to internal experience and perception.' },
            { label: 'C', text: 'Woolf moves plot elements to the end of the novel rather than distributing them throughout.' },
            { label: 'D', text: 'Plot is replaced entirely by free indirect style in modernist fiction.' },
          ],
          correctAnswer: 'B',
          explanation: '"Plot is not abandoned but relocated: it moves from the external world of events to the internal world of perception and response." The passage is explicit that the structuring principle of narrative moves from outer to inner, not that plot disappears.',
          wrongAnswerExplanations: {
            A: 'Woolf does not retain "traditional external plot structures" — the walk in Mrs. Dalloway is not a traditional plot. The external structure becomes minimal; the internal becomes primary.',
            C: 'There is no spatial or sequential relocation within the novel described. "Relocated" means moved from external to internal, not rearranged within the text.',
            D: 'The passage says plot is not abandoned — choice D contradicts this. Free indirect style is one technique, not a replacement for plot.',
          },
          teachingPoint: '"Relocated" = moved from external events to internal perception. This is a direct comprehension question — the answer paraphrases the passage\'s explicit statement.',
          relatedTopics: ['narrative structure', 'internal vs. external plot', 'modernist fiction'],
        },
      ],
    },
    {
      id: 'cars-p4',
      sectionId: 'cars',
      title: 'Passage 4',
      passageText: `Marcel Mauss's 1925 essay "The Gift" proposed that exchange in non-market societies operates according to a logic fundamentally different from the utilitarian calculus that dominates modern economic thought. Where classical economics imagines exchange as a voluntary transaction between self-interested individuals seeking to maximize utility, Mauss described gift economies as governed by an obligation structure involving three interlocking duties: the obligation to give, the obligation to receive, and the obligation to reciprocate. These duties are not legally enforceable contracts; they are moral and social imperatives whose violation carries consequences in terms of status, honor, and social position rather than legal sanction.

What is particularly counterintuitive about Mauss's analysis is that gift exchange, despite its surface appearance of generosity, is anything but free. The gift creates a debt. The recipient of a gift is placed in a state of obligation that can only be discharged through reciprocal giving — typically with interest, since failing to give more than one received signals an inability to compete in the prestige economy. Among the communities Mauss studied, excessive generosity functions as a form of domination: to give more than can be reciprocated is to humiliate the recipient and establish a hierarchy of obligation. The most extreme example he documented was the potlatch ceremony practiced by certain Pacific Northwest Indigenous peoples, in which wealth was ostentatiously given away or destroyed precisely to demonstrate the giver's superiority.

Critics of Mauss have argued that he projected Western preoccupations with reciprocity onto societies that understood exchange differently, and that his framework universalizes a particular cultural logic. More sympathetic interpreters have suggested that Mauss's analysis reveals not the exotic practices of distant cultures but a persistent dimension of social life that market economies obscure: the moral entanglement of persons through things. Whether or not the gift economy is a distinct economic type, the insight that exchange is never simply economic — that it always carries social, moral, and political valences — retains considerable analytical force.`,
      questions: [
        {
          id: 'mcat1-cars-016',
          sectionId: 'cars',
          passageId: 'cars-p4',
          questionType: 'passage',
          discipline: 'CARS',
          contentCategory: 'Foundations of Comprehension',
          foundationalConcept: 'FC 6',
          scientificSkill: 'Skill 1',
          difficulty: 'easy',
          question: 'According to the passage, what distinguishes gift exchange from market exchange?',
          choices: [
            { label: 'A', text: 'Gift exchange is governed by legally enforceable contracts, while market exchange is not.' },
            { label: 'B', text: 'Gift exchange involves moral and social obligations to give, receive, and reciprocate, rather than voluntary self-interested transactions.' },
            { label: 'C', text: 'Gift exchange maximizes individual utility more effectively than market exchange.' },
            { label: 'D', text: 'Gift exchange occurs only in non-modern societies, while market exchange is universal.' },
          ],
          correctAnswer: 'B',
          explanation: 'The passage contrasts Mauss\'s gift economy (three interlocking moral duties: give, receive, reciprocate) against classical economics\' "voluntary transaction between self-interested individuals." Gift obligations are "not legally enforceable contracts" but moral and social imperatives.',
          wrongAnswerExplanations: {
            A: 'The passage explicitly states gift obligations are not legally enforceable contracts — the opposite of choice A.',
            C: 'Gift exchange is not described as maximizing individual utility — that is the logic of market exchange. Gift exchange operates on prestige and social obligation.',
            D: 'The final paragraph suggests gift economy logic appears in all societies: "a persistent dimension of social life that market economies obscure." It is not confined to non-modern societies.',
          },
          teachingPoint: 'Direct comprehension: find the explicit contrast the passage draws. Gift = moral obligations (give/receive/reciprocate); market = voluntary self-interested transactions.',
          relatedTopics: ['gift economy', 'Mauss', 'reciprocity', 'market vs. non-market exchange'],
        },
        {
          id: 'mcat1-cars-017',
          sectionId: 'cars',
          passageId: 'cars-p4',
          questionType: 'passage',
          discipline: 'CARS',
          contentCategory: 'Reasoning Within the Text',
          foundationalConcept: 'FC 6',
          scientificSkill: 'Skill 2',
          difficulty: 'medium',
          question: 'The author describes the potlatch ceremony as "the most extreme example" of which principle?',
          choices: [
            { label: 'A', text: 'The legal enforceability of gift obligations in Pacific Northwest societies' },
            { label: 'B', text: 'Excessive generosity functioning as a form of domination within prestige economies' },
            { label: 'C', text: 'The failure of gift exchange to create social obligations' },
            { label: 'D', text: 'The superiority of non-market over market economies' },
          ],
          correctAnswer: 'B',
          explanation: 'The passage states: "excessive generosity functions as a form of domination: to give more than can be reciprocated is to humiliate the recipient." The potlatch exemplifies this extreme — wealth given away or destroyed to demonstrate superiority through unreturnable generosity.',
          wrongAnswerExplanations: {
            A: 'Gift obligations in Mauss\'s framework are explicitly not legally enforceable. The potlatch is an example of moral/social hierarchy, not legal enforcement.',
            C: 'The potlatch creates extreme obligations — the gift creates a debt that may be impossible to repay. This is the opposite of failing to create obligations.',
            D: 'The passage does not compare market and non-market economies in terms of superiority. The potlatch illustrates the prestige-domination dynamic, not economic efficiency.',
          },
          teachingPoint: 'Locate the potlatch example in context: it follows "excessive generosity functions as a form of domination." It exemplifies that giving more than can be reciprocated = humiliation = hierarchy.',
          relatedTopics: ['potlatch', 'prestige economy', 'gift as domination'],
        },
        {
          id: 'mcat1-cars-018',
          sectionId: 'cars',
          passageId: 'cars-p4',
          questionType: 'passage',
          discipline: 'CARS',
          contentCategory: 'Reasoning Beyond the Text',
          foundationalConcept: 'FC 6',
          scientificSkill: 'Skill 2',
          difficulty: 'hard',
          question: 'A sympathetic interpreter of Mauss, as described in the passage, would most likely agree with which of the following statements?',
          choices: [
            { label: 'A', text: 'Modern market economies have fully eliminated the moral entanglement of persons through exchange.' },
            { label: 'B', text: 'Gift logic is not merely a feature of exotic cultures but an enduring social dimension of exchange that markets tend to conceal.' },
            { label: 'C', text: 'Mauss\'s framework should replace economic theory as the basis for understanding modern markets.' },
            { label: 'D', text: 'The potlatch ceremony demonstrates that gift economies are economically irrational.' },
          ],
          correctAnswer: 'B',
          explanation: 'Sympathetic interpreters say Mauss reveals "not the exotic practices of distant cultures but a persistent dimension of social life that market economies obscure." Choice B paraphrases this directly: gift logic is universal, merely hidden in market economies.',
          wrongAnswerExplanations: {
            A: 'The sympathetic interpretation holds that markets obscure, not eliminate, gift logic. "Obscure" implies it persists but is hidden.',
            C: 'The passage says Mauss\'s insight "retains analytical force" — not that his framework should replace economic theory entirely.',
            D: 'Economic rationality judgments are not made in the sympathetic interpreters\' position. The sympathetic view rehabilitates Mauss\'s insight as universal, not as a rationality claim.',
          },
          teachingPoint: 'Identify the sympathetic interpreters\' position in the text: gift logic = "persistent dimension of social life that market economies obscure." Match the answer to this.',
          relatedTopics: ['Mauss interpretation', 'gift economy universality', 'market economies and social exchange'],
        },
        {
          id: 'mcat1-cars-019',
          sectionId: 'cars',
          passageId: 'cars-p4',
          questionType: 'passage',
          discipline: 'CARS',
          contentCategory: 'Reasoning Within the Text',
          foundationalConcept: 'FC 6',
          scientificSkill: 'Skill 2',
          difficulty: 'medium',
          question: 'The critics\' objection to Mauss (paragraph 3) is that he:',
          choices: [
            { label: 'A', text: 'failed to provide sufficient empirical examples to support his claims' },
            { label: 'B', text: 'imposed Western assumptions about reciprocity onto societies that operated on different terms' },
            { label: 'C', text: 'ignored the role of legal enforcement in non-market exchange systems' },
            { label: 'D', text: 'overstated the economic efficiency of gift economies relative to markets' },
          ],
          correctAnswer: 'B',
          explanation: 'The passage states critics argued "he projected Western preoccupations with reciprocity onto societies that understood exchange differently, and that his framework universalizes a particular cultural logic." This is the classic critique of Mauss: ethnocentrism or cultural projection.',
          wrongAnswerExplanations: {
            A: 'Mauss uses the potlatch and other empirical examples. Critics do not fault him for lack of evidence but for how he interpreted it.',
            C: 'Legal enforcement is the basis of market contracts, not the critics\' concern about Mauss. They critique conceptual projection, not this omission.',
            D: 'No comparison of economic efficiency is made in the critics\' position. Their critique is anthropological/interpretive, not economic.',
          },
          teachingPoint: 'Locate the critics\' exact objection: "projected Western preoccupations with reciprocity...universalizes a particular cultural logic." This is a charge of ethnocentric projection.',
          relatedTopics: ['Mauss criticism', 'ethnocentrism', 'cultural projection', 'gift economy'],
        },
        {
          id: 'mcat1-cars-020',
          sectionId: 'cars',
          passageId: 'cars-p4',
          questionType: 'passage',
          discipline: 'CARS',
          contentCategory: 'Foundations of Comprehension',
          foundationalConcept: 'FC 6',
          scientificSkill: 'Skill 1',
          difficulty: 'easy',
          question: 'The author\'s conclusion that Mauss\'s insight "retains considerable analytical force" suggests the author:',
          choices: [
            { label: 'A', text: 'fully endorses Mauss\'s framework and rejects all criticisms of it' },
            { label: 'B', text: 'agrees with the critics that Mauss projected Western values onto other cultures' },
            { label: 'C', text: 'holds that even if critics are partly right, the core insight — that exchange always carries social and moral dimensions — remains valuable' },
            { label: 'D', text: 'argues that gift economies are superior to market economies in generating social cohesion' },
          ],
          correctAnswer: 'C',
          explanation: 'The author hedges with "whether or not the gift economy is a distinct economic type" — acknowledging the critics\' possible validity — but concludes the core insight retains analytical force. This is a partial endorsement: critics may be right about universalizing, but the social/moral dimension of exchange remains a genuine insight.',
          wrongAnswerExplanations: {
            A: '"Whether or not the gift economy is a distinct economic type" concedes some uncertainty about the critics. The author does not fully reject criticism.',
            B: 'If the author agreed fully with critics, the conclusion would not affirm Mauss\'s analytical value. The hedging followed by endorsement shows a middle position.',
            D: 'The passage does not compare social cohesion across economic types. The author\'s conclusion concerns the analytical insight about exchange having social dimensions, not system performance.',
          },
          teachingPoint: 'The structure: "whether or not X is true...Y retains force" = hedging + partial endorsement. Author grants critics may be right on the universalizing charge, but defends the core insight.',
          relatedTopics: ['author conclusion', 'hedged endorsement', 'Mauss analytical value'],
        },
      ],
    },
  ],
  discreteQuestions: [],
}
