import type { MCATPassage } from '../types'

// Form 5 CARS — Passages 6–9 (IDs mcat5-cars-027 through mcat5-cars-053)

export const carsPassages5_06to09: MCATPassage[] = [
  {
    id: 'f5-cars-p6',
    sectionId: 'cars',
    passageNumber: 6,
    title: 'The Sociology of Scientific Knowledge',
    passageText: `The sociology of scientific knowledge (SSK) emerged in the 1970s as a radical challenge to the traditional view that science generates knowledge through a straightforward process of observation, hypothesis, and rational evaluation. The Edinburgh School's "strong programme," articulated by David Bloor, argued that sociological explanation should apply symmetrically to all knowledge claims — true and false, successful and failed scientific programs alike. Rather than explaining successful science by its rationality and failed science by social factors, SSK demanded that the same causal factors — interests, social organization, material practices — explain both.

This symmetry principle was deeply controversial. Critics, particularly philosophers of science, argued that it committed a category error: social conditions explain why scientists come to hold beliefs, but they cannot explain why those beliefs are true. The causes of belief-formation and the justification for belief-content are logically independent. Rationalist critics held that sound scientific method — controlled experiment, peer review, mathematical formalism — provides genuine access to how the world is, regardless of the social circumstances of its practitioners.

Harry Collins's empirical program of relativism (EPOR) extended SSK by studying ongoing scientific controversies, arguing that "interpretive flexibility" characterizes genuine scientific disputes: different experimental results can support different theoretical interpretations, and closure on a controversy is achieved through social negotiation rather than compelling evidence alone. His study of gravitational wave detection in the 1970s showed that physicists evaluated the same data differently based on their theoretical commitments and institutional affiliations.

The debate remains unresolved. A middle position, associated with laboratory studies (Latour and Woolgar's work on Salk Institute scientists), holds that scientific facts are produced through material practices and inscription devices, and that the distinction between "nature" and "social construction" is itself constructed in the course of laboratory work — without denying that the resulting knowledge is reliable and effective.`,
    questions: [
      {
        id: 'mcat5-cars-027',
        sectionId: 'cars',
        passageId: 'f5-cars-p6',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'The "symmetry principle" of the Edinburgh School requires that:',
        choices: [
          { label: 'A', text: 'Successful scientific theories must be explained by rational factors alone' },
          { label: 'B', text: 'The same sociological causes should explain both successful and failed scientific beliefs' },
          { label: 'C', text: 'Social factors explain failed science while rational factors explain successful science' },
          { label: 'D', text: 'All scientific claims are equally valid regardless of empirical support' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 1: the strong programme "demanded that the same causal factors — interests, social organization, material practices — explain both" successful and failed scientific programs. B is a direct match. C is the TRADITIONAL view that SSK is challenging (explains failure by social factors, success by rationality). A is also the traditional view. D overstates — SSK does not claim all claims are equally valid; it claims sociological explanation applies symmetrically.',
        wrongAnswerExplanations: {
          A: 'The symmetry principle REJECTS explaining successful science exclusively by rationality — it insists social factors apply to successful science too.',
          C: 'This is exactly the asymmetric view the strong programme critiques. Bloor\'s symmetry principle demands the SAME factors explain both sides.',
          D: 'SSK does not claim all scientific claims are equally valid (that would be epistemological relativism). It claims sociological explanation applies symmetrically, not that truth is irrelevant.',
        },
        teachingPoint: 'SSK symmetry principle: same causal factors for both success and failure. Traditional view (asymmetric): social factors → failure; rational factors → success. Bloor flips this: apply sociological explanation uniformly to both. B captures "same factors, both directions."',
        relatedTopics: ['SSK symmetry principle', 'Edinburgh School Bloor', 'sociology of knowledge', 'CARS social science'],
      },
      {
        id: 'mcat5-cars-028',
        sectionId: 'cars',
        passageId: 'f5-cars-p6',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'The rationalist critique of SSK (paragraph 2) argues that:',
        choices: [
          { label: 'A', text: 'Sociology has no role in studying scientific communities' },
          { label: 'B', text: 'The causes of belief-formation are logically identical to the justification for belief content' },
          { label: 'C', text: 'Social conditions explain why scientists hold beliefs, but not why those beliefs are true — justification is independent of causal origin' },
          { label: 'D', text: 'Peer review and mathematical formalism are social constructions with no epistemic value' },
        ],
        correctAnswer: 'C',
        explanation: 'Paragraph 2: "social conditions explain why scientists come to hold beliefs, but they cannot explain why those beliefs are true. The causes of belief-formation and the justification for belief-content are logically independent." C is a direct match. A overstates — rationalists do not deny sociology studies communities. B inverts the rationalist claim (they say causes and justification are INDEPENDENT, not identical). D contradicts the rationalist position (which defends peer review and mathematical formalism as giving genuine access to how the world is).',
        wrongAnswerExplanations: {
          A: 'The rationalists don\'t deny that sociology can study scientific communities — they challenge whether sociological explanation exhausts scientific knowledge claims.',
          B: 'The rationalists claim causes and justification are LOGICALLY INDEPENDENT — not identical. B reverses the argument.',
          D: 'The rationalists DEFEND peer review and formalism as genuine epistemic methods. They would not call them social constructions with no epistemic value.',
        },
        teachingPoint: 'The rationalist critique uses the distinction between "context of discovery" (how beliefs are formed, which can be sociological) and "context of justification" (why beliefs are true, which requires epistemic reasons). SSK conflates these; rationalists insist they are independent.',
        relatedTopics: ['rationalist critique SSK', 'context discovery justification', 'belief formation vs truth', 'CARS epistemology'],
      },
      {
        id: 'mcat5-cars-029',
        sectionId: 'cars',
        passageId: 'f5-cars-p6',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'hard',
        question: 'Collins\'s study of gravitational wave detection is cited to support the claim that:',
        choices: [
          { label: 'A', text: 'Gravitational waves did not actually exist during the 1970s controversy' },
          { label: 'B', text: 'Scientific controversies are closed by compelling empirical evidence alone' },
          { label: 'C', text: 'Interpretive flexibility means the same data can support different interpretations, and closure involves social negotiation' },
          { label: 'D', text: 'Physicists\' theoretical commitments are irrelevant to how they evaluate data' },
        ],
        correctAnswer: 'C',
        explanation: 'Paragraph 3: "interpretive flexibility characterizes genuine scientific disputes: different experimental results can support different theoretical interpretations, and closure on a controversy is achieved through social negotiation rather than compelling evidence alone." Collins\'s study showed "physicists evaluated the same data differently based on their theoretical commitments and institutional affiliations." C matches. A — Collins\'s study is about how physicists debated, not whether gravitational waves exist. B — Collins argues closure involves social negotiation, NOT compelling evidence alone (he challenges B). D inverts the finding: theoretical commitments are RELEVANT to data evaluation (physicists with different commitments read the same data differently).',
        wrongAnswerExplanations: {
          A: 'The study is about the sociology of the controversy, not about the physical reality of gravitational waves. SSK\'s symmetry principle explains belief formation, not the truth of beliefs.',
          B: 'Collins argues exactly the OPPOSITE: closure involves social negotiation, not compelling evidence alone. B contradicts the EPOR claim.',
          D: 'The study shows theoretical commitments and institutional affiliations ARE relevant — physicists with different theoretical commitments evaluated the same data differently. D inverts the finding.',
        },
        teachingPoint: 'Collins EPOR: (1) interpretive flexibility — same data → different interpretations; (2) closure via social negotiation, not just evidence. The gravitational wave study = paradigm case. The SAME data was read differently by physicists with different commitments. C captures both claims.',
        relatedTopics: ['Collins EPOR', 'interpretive flexibility', 'gravitational wave controversy', 'social negotiation closure'],
      },
      {
        id: 'mcat5-cars-030',
        sectionId: 'cars',
        passageId: 'f5-cars-p6',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'The "middle position" in the final paragraph differs from SSK primarily by:',
        choices: [
          { label: 'A', text: 'Denying that social processes play any role in the production of scientific facts' },
          { label: 'B', text: 'Holding that scientific facts are produced through material practices while maintaining that the resulting knowledge is reliable' },
          { label: 'C', text: 'Claiming that the distinction between nature and social construction is absolute and permanent' },
          { label: 'D', text: 'Arguing that only rationalist methods can produce genuine scientific knowledge' },
        ],
        correctAnswer: 'B',
        explanation: 'Final paragraph: the middle position (Latour, Woolgar) holds "scientific facts are produced through material practices and inscription devices" (acknowledging construction) "without denying that the resulting knowledge is reliable and effective." This differs from stronger SSK by maintaining reliability — combining social production with epistemic effectiveness. B captures this. A — the middle position does not deny social processes; it affirms them (material practices). C — the final paragraph says the distinction is "itself constructed" (not absolute). D — rationalism is not the middle position (which incorporates social/material practices).',
        wrongAnswerExplanations: {
          A: 'The middle position explicitly acknowledges social and material processes in science — it is NOT a return to naive realism that denies social roles.',
          C: 'The middle position says the nature/construction distinction is "itself constructed in the course of laboratory work" — meaning it\'s not an absolute given. C misrepresents.',
          D: 'The middle position (laboratory studies) emphasizes material practices, not pure rationalist methods. D describes the traditional rationalist view.',
        },
        teachingPoint: 'Middle position = laboratory studies approach. Key nuance: acknowledges social/material production of facts (like SSK) BUT does not deny that the knowledge is reliable and effective. SSK tends toward relativism; laboratory studies acknowledge construction while preserving reliability.',
        relatedTopics: ['laboratory studies Latour Woolgar', 'SSK middle position', 'material practices reliability', 'CARS three positions'],
      },
      {
        id: 'mcat5-cars-031',
        sectionId: 'cars',
        passageId: 'f5-cars-p6',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning beyond the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'A historian finds that a major 20th-century scientific theory was accepted partly because its key proponent held an influential institutional position, even though competing evidence was available. An SSK advocate would MOST likely argue that this finding:',
        choices: [
          { label: 'A', text: 'Proves the theory is false' },
          { label: 'B', text: 'Demonstrates that social factors causally contributed to belief acceptance, consistent with the symmetry principle' },
          { label: 'C', text: 'Is irrelevant to understanding how scientists form beliefs' },
          { label: 'D', text: 'Undermines SSK by showing that rational factors sometimes dominate' },
        ],
        correctAnswer: 'B',
        explanation: 'The finding — institutional position influenced acceptance despite competing evidence — is exactly the kind of social factor SSK points to. An SSK advocate would say this confirms the symmetry principle: social factors (institutional authority) causally contributed to belief acceptance. B is correct. A — SSK explains why beliefs are held, not whether they are true (it does not claim institutional influence proves falsity). C inverts — this IS relevant to SSK\'s analysis. D — the finding shows social factors at work, which SUPPORTS SSK, not undermines it.',
        wrongAnswerExplanations: {
          A: 'SSK explains belief formation, not truth. Institutional influence in acceptance does not establish the theory is false — that would require evidence about the theory\'s content.',
          C: 'This is exactly the kind of case SSK studies — social factors (institutional position) affecting belief acceptance. Highly relevant.',
          D: 'The finding illustrates social factors at work in belief acceptance — this SUPPORTS SSK\'s program, not undermines it.',
        },
        teachingPoint: 'SSK application: social factors (interests, institutional affiliations, authority) causally explain belief acceptance. This is the symmetry principle in action — the same kinds of social factors that explain failed science also explain accepted science. SSK would embrace this finding as confirming evidence.',
        relatedTopics: ['SSK application', 'institutional authority belief', 'symmetry principle example', 'CARS apply social science'],
      },
      {
        id: 'mcat5-cars-032',
        sectionId: 'cars',
        passageId: 'f5-cars-p6',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'easy',
        question: 'The primary purpose of the passage is to:',
        choices: [
          { label: 'A', text: 'Argue that science is entirely reducible to social interests' },
          { label: 'B', text: 'Describe the debate over whether sociological factors can explain scientific knowledge, and outline a middle position' },
          { label: 'C', text: 'Prove that scientific knowledge is unreliable because it is socially constructed' },
          { label: 'D', text: 'Defend the Edinburgh School\'s strong programme against all criticism' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage maps the SSK debate: strong programme (symmetry), rationalist critique, Collins\'s EPOR, and laboratory studies middle position. It presents positions without definitively resolving the debate ("The debate remains unresolved"). B — describe the debate and outline the middle position — matches the structure. A overstates (not the author\'s claim). C overstates (middle position maintains reliability). D overstates (the passage presents criticism fairly and ends with a middle position).',
        wrongAnswerExplanations: {
          A: 'The author presents SSK, its critics, and a middle position. "Entirely reducible" is not the author\'s conclusion.',
          C: 'The middle position (final paragraph) explicitly maintains that "the resulting knowledge is reliable and effective." The author does not argue unreliability.',
          D: 'The author presents rationalist critiques fairly (paragraph 2) and the middle position (paragraph 4), not a defense of the strong programme exclusively.',
        },
        teachingPoint: 'Primary purpose: identify what the passage as a whole is doing structurally. Here: map the SSK debate across three positions (strong programme → rationalist critique → Collins EPOR → laboratory studies middle). The final position offers a synthesis. B captures: describe debate + outline middle position.',
        relatedTopics: ['primary purpose SSK passage', 'debate structure CARS', 'middle position final paragraph', 'CARS primary purpose'],
      },
    ],
  },
  {
    id: 'f5-cars-p7',
    sectionId: 'cars',
    passageNumber: 7,
    title: 'Language, Power, and the Politics of Translation',
    passageText: `Translation is never a purely linguistic act. Every act of translation involves choices — about register, connotation, culturally embedded meaning, and the negotiation of incommensurable conceptual frameworks — and those choices are inevitably shaped by asymmetries of power between source and target cultures. The history of colonial translation makes this visible: colonial administrators and missionaries routinely translated indigenous concepts into European frameworks that fundamentally altered their meaning, imposing juridical, religious, and political structures that the original languages resisted.

Postcolonial translation theorists, building on Lawrence Venuti's concept of "domestication" and "foreignization," argue that domesticating translation — which renders the foreign text fluent and transparent in the target language — naturalizes dominant cultural values while making the act of translation itself invisible. The foreign text appears to speak in the translator's native idiom, erasing the cultural distance that separates them. Foreignizing translation, by contrast, deliberately preserves alien syntactic structures, untranslated terms, and cultural dissonances — making the reader aware that they are encountering a different world.

Neither strategy is without costs. Domestication makes texts accessible but at the price of cultural erasure. Foreignization preserves difference but risks producing texts that are difficult or alienating for target audiences — or, paradoxically, that exoticize the source culture through selective emphasis on its strangeness.

Translation theorists increasingly favor a practice of "translational ethics" — explicit acknowledgment by translators of their interpretive choices, the power relations shaping them, and the limits of equivalence. On this view, the ideal translation is not the transparent one but the one that is accompanied by a critical apparatus that makes the translator's mediating role visible and accountable.`,
    questions: [
      {
        id: 'mcat5-cars-033',
        sectionId: 'cars',
        passageId: 'f5-cars-p7',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'easy',
        question: 'According to the passage, "domesticating translation" is problematic primarily because it:',
        choices: [
          { label: 'A', text: 'Is too difficult for most readers to understand' },
          { label: 'B', text: 'Makes the act of translation invisible while naturalizing dominant cultural values' },
          { label: 'C', text: 'Preserves cultural difference in ways that alienate target audiences' },
          { label: 'D', text: 'Deliberately introduces political bias to undermine indigenous concepts' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 2: "domesticating translation...naturalizes dominant cultural values while making the act of translation itself invisible." B is a direct match. A — the problem with domesticating is invisibility/naturalization, not difficulty (that\'s the concern with foreignizing). C — preserving difference is foreignizing, not domesticating. D — intentional political bias is not stated; domestication is described as making power asymmetries invisible, not deliberately introducing bias.',
        wrongAnswerExplanations: {
          A: 'Domesticating translation is described as making texts FLUENT and accessible — the opposite of difficult to understand. Difficulty is the risk with foreignizing.',
          C: 'Alienating target audiences and preserving cultural dissonances = foreignizing (paragraph 3). Domesticating does the opposite.',
          D: 'Domestication is described as making power asymmetries invisible through apparent naturalness — not as a deliberate act of introducing political bias.',
        },
        teachingPoint: 'Domesticating vs. foreignizing: Domesticating = fluent, target-culture idiom, invisible translator = naturalizes dominant values. Foreignizing = alien structures, untranslated terms, visible difference = risks alienation or exoticization. The critique of domesticating: power asymmetries become invisible.',
        relatedTopics: ['domesticating translation', 'Venuti translation theory', 'naturalization power', 'CARS definition contrast'],
      },
      {
        id: 'mcat5-cars-034',
        sectionId: 'cars',
        passageId: 'f5-cars-p7',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'The author\'s description of foreignization as potentially "exoticizing" suggests that:',
        choices: [
          { label: 'A', text: 'Foreignization always succeeds in restoring authenticity to source-culture concepts' },
          { label: 'B', text: 'Even well-intentioned attempts to preserve cultural difference can distort by selectively emphasizing strangeness' },
          { label: 'C', text: 'Foreignization is a disguised form of domestication' },
          { label: 'D', text: 'Exoticization is preferable to naturalization in postcolonial contexts' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 3: foreignization risks "exoticizing the source culture through selective emphasis on its strangeness" — paradoxically, trying to preserve difference can highlight strangeness in a way that distorts the source culture just as domestication does, but in the opposite direction. B captures this: even the foreignizing strategy meant to preserve authenticity can distort. A overstates — "always succeeds" contradicts the "risks" and "paradoxically" language. C is not stated (foreignization and domestication are distinct strategies). D — the passage presents both as having costs, not one as preferable.',
        wrongAnswerExplanations: {
          A: '"Always succeeds" ignores the "paradoxically" qualifier in paragraph 3. Foreignization can distort through exoticization.',
          C: 'Foreignization and domestication are presented as distinct, opposite strategies. The passage does not claim foreignization is secretly domestication.',
          D: 'The author presents BOTH strategies as having costs — paragraph 3 explicitly lists risks of BOTH. Neither is endorsed as simply preferable.',
        },
        teachingPoint: 'Paradox of foreignization: preserving difference through alien structures/untranslated terms can itself distort by selectively emphasizing strangeness (exoticization). The source culture becomes "the exotic other" rather than being understood on its own terms. This is a subtle critique that neither strategy fully resolves the power problem.',
        relatedTopics: ['exoticization foreignization', 'translation paradox', 'selective emphasis strangeness', 'CARS nuanced critique'],
      },
      {
        id: 'mcat5-cars-035',
        sectionId: 'cars',
        passageId: 'f5-cars-p7',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'The author\'s concept of "translational ethics" (final paragraph) is BEST understood as:',
        choices: [
          { label: 'A', text: 'A call for translators to avoid all interpretive choices and produce neutral texts' },
          { label: 'B', text: 'The requirement that translators acknowledge their interpretive choices, power relations, and limits of equivalence' },
          { label: 'C', text: 'The view that only members of the source culture can legitimately translate its texts' },
          { label: 'D', text: 'A method for achieving perfect equivalence between source and target languages' },
        ],
        correctAnswer: 'B',
        explanation: 'Final paragraph: "translational ethics — explicit acknowledgment by translators of their interpretive choices, the power relations shaping them, and the limits of equivalence." B matches directly. A — "avoid all interpretive choices" is impossible and contradicts the passage\'s argument that all translation involves choices. C — membership in source culture is not the criterion. D — the passage explicitly states "limits of equivalence," meaning perfect equivalence is not achievable; translational ethics acknowledges this rather than seeking to achieve it.',
        wrongAnswerExplanations: {
          A: 'The passage establishes (paragraph 1) that translation necessarily involves interpretive choices — they cannot be avoided. Translational ethics acknowledges this rather than eliminating it.',
          C: 'Source-culture membership is not mentioned in the passage as a criterion for legitimate translation.',
          D: 'Translational ethics explicitly acknowledges the "limits of equivalence" — meaning perfect equivalence is NOT the goal or the claim.',
        },
        teachingPoint: 'Translational ethics: not the transparent translator (domestication ideal) or the foreignizing preservationist, but the ACCOUNTABLE translator who makes their choices visible. Key features: (1) explicit acknowledgment of choices; (2) power relations named; (3) limits of equivalence acknowledged. The ideal = critical apparatus making mediation visible.',
        relatedTopics: ['translational ethics', 'accountability translator', 'limits equivalence', 'CARS final paragraph'],
      },
      {
        id: 'mcat5-cars-036',
        sectionId: 'cars',
        passageId: 'f5-cars-p7',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning beyond the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'A translator publishes an edition of an indigenous oral narrative with extensive footnotes explaining untranslated terms, acknowledging that the written format inevitably changes the text\'s meaning, and describing the translator\'s cultural position. This approach MOST closely reflects:',
        choices: [
          { label: 'A', text: 'Pure domestication — the text is made fully transparent to target-culture readers' },
          { label: 'B', text: 'Pure foreignization — alien syntactic structures are preserved' },
          { label: 'C', text: 'Translational ethics — making the translator\'s mediating role visible and acknowledging limits of equivalence' },
          { label: 'D', text: 'Colonial translation practice — imposing European frameworks on indigenous concepts' },
        ],
        correctAnswer: 'C',
        explanation: 'Final paragraph: translational ethics involves "explicit acknowledgment by translators of their interpretive choices, the power relations shaping them, and the limits of equivalence...accompanied by a critical apparatus that makes the translator\'s mediating role visible and accountable." The translator: footnotes (critical apparatus), untranslated terms (acknowledging incommensurability), acknowledging format limits (limits of equivalence), describing cultural position (power relations). C matches precisely. A — domestication = transparent, invisible translator — opposite of this approach. B — foreignization = alien structures, but no mention of critical apparatus. D — colonial translation imposed frameworks without acknowledgment — opposite of what\'s described.',
        wrongAnswerExplanations: {
          A: 'Domestication makes translation invisible. This translator explicitly makes their role VISIBLE through footnotes and positional acknowledgment — the opposite.',
          B: 'Foreignization preserves alien structures but the passage does not describe it as including a "critical apparatus" of acknowledgments. The translator here is primarily making their mediation accountable.',
          D: 'Colonial translation is described as imposing European frameworks and altering meaning — the opposite of acknowledging limits of equivalence and one\'s cultural position.',
        },
        teachingPoint: 'Apply translational ethics to a concrete example. Key markers: (1) critical apparatus (footnotes); (2) untranslated terms with explanation; (3) acknowledging format changes (limits of equivalence); (4) translator\'s cultural position (power relations). All four features = translational ethics.',
        relatedTopics: ['translational ethics application', 'critical apparatus', 'CARS apply translation', 'footnotes untranslated'],
      },
      {
        id: 'mcat5-cars-037',
        sectionId: 'cars',
        passageId: 'f5-cars-p7',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'easy',
        question: 'The opening paragraph\'s reference to colonial translation is used to:',
        choices: [
          { label: 'A', text: 'Argue that modern translation has overcome the power asymmetries of the colonial era' },
          { label: 'B', text: 'Illustrate historically how translation has operated within power asymmetries to distort indigenous meanings' },
          { label: 'C', text: 'Provide evidence that foreignization is always preferable in postcolonial contexts' },
          { label: 'D', text: 'Show that only indigenous translators can produce accurate translations of indigenous texts' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 1 introduces the argument that translation is shaped by power asymmetries, then uses colonial translation as historical illustration: "colonial administrators and missionaries routinely translated indigenous concepts into European frameworks that fundamentally altered their meaning." B: illustrating how power asymmetries distort indigenous meanings through translation — the historical case that makes the argument visible. A — the passage does not claim modern translation has overcome these problems. C — foreignization is not addressed in paragraph 1. D — not mentioned in the passage.',
        wrongAnswerExplanations: {
          A: 'The passage does not claim these asymmetries have been overcome — it then addresses present translation theory (Venuti, Collins, translational ethics) as responses to ongoing issues.',
          C: 'The colonial translation reference is about the general problem of power + translation; foreignization is introduced in paragraph 2 as one proposed response, not as always preferable.',
          D: 'Indigenous-translator-only requirement is not mentioned; the passage focuses on translation ethics and strategies, not who can translate.',
        },
        teachingPoint: 'Opening historical example purpose: establish the general claim (translation involves power) with a concrete historical illustration (colonial translation distorted indigenous meaning). Sets up the problem that the rest of the passage addresses through Venuti\'s strategies and translational ethics.',
        relatedTopics: ['colonial translation example', 'CARS opening example purpose', 'power asymmetry translation', 'historical illustration'],
      },
      {
        id: 'mcat5-cars-038',
        sectionId: 'cars',
        passageId: 'f5-cars-p7',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'The passage suggests that both domestication and foreignization share which limitation?',
        choices: [
          { label: 'A', text: 'Both produce texts that are inaccessible to target-culture readers' },
          { label: 'B', text: 'Both can distort the source culture, though through opposite mechanisms' },
          { label: 'C', text: 'Both are forms of colonial translation that impose European frameworks' },
          { label: 'D', text: 'Both are rejected by postcolonial translation theorists as inadequate' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 3 presents the costs of BOTH: domestication = cultural erasure; foreignization = alienation or exoticization. Both distort, but through opposite mechanisms — domestication by erasing difference, foreignization by overemphasizing strangeness. B captures this shared limitation. A — inaccessibility is only foreignization\'s risk, not domestication\'s. C — foreignization is not colonial translation; it is presented as an alternative that still has problems. D — postcolonial theorists (Venuti) advocate foreignization; translational ethics is a further response, not a rejection of both.',
        wrongAnswerExplanations: {
          A: 'Domestication produces ACCESSIBLE texts (it renders them fluent). Inaccessibility is only foreignization\'s risk.',
          C: 'Colonial translation is described in paragraph 1 as imposing European frameworks (domesticating). Foreignization deliberately resists this by preserving alien elements.',
          D: 'Postcolonial theorists (Venuti) favor foreignizing over domesticating — they don\'t simply reject both. Translational ethics (final paragraph) adds to rather than rejects these strategies.',
        },
        teachingPoint: 'Shared limitation: both domestication (erases difference) and foreignization (exoticizes difference) can distort the source culture. Domestication = too smooth; foreignization = too strange. This is why translational ethics is needed — acknowledging the limitations rather than pretending either strategy is perfect.',
        relatedTopics: ['domestication foreignization shared limitation', 'distortion opposite mechanisms', 'translation theory critique', 'CARS both sides limitation'],
      },
      {
        id: 'mcat5-cars-039',
        sectionId: 'cars',
        passageId: 'f5-cars-p7',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'hard',
        question: 'The phrase "incommensurable conceptual frameworks" (paragraph 1) most likely refers to:',
        choices: [
          { label: 'A', text: 'Linguistic frameworks that are structurally similar but use different vocabulary' },
          { label: 'B', text: 'Conceptual systems so different that direct equivalence or translation may not be possible' },
          { label: 'C', text: 'Frameworks that cannot be ranked by any common standard of value' },
          { label: 'D', text: 'Translation tools that are incompatible with modern computer-assisted translation' },
        ],
        correctAnswer: 'B',
        explanation: '"Incommensurable" means having no common measure or standard — conceptual frameworks that cannot be directly mapped onto each other because they organize experience in fundamentally different ways. In context (paragraph 1): indigenous concepts that European frameworks "fundamentally altered" through translation — suggesting the original language organized reality in ways that do not map onto European juridical, religious, or political structures. B is correct: conceptual systems so different that direct equivalence may be impossible. A — "structurally similar but different vocabulary" would be easily translatable, not incommensurable. C — ranking by value is a separate philosophical concept (not the meaning here). D — irrelevant to the passage.',
        wrongAnswerExplanations: {
          A: 'Structurally similar frameworks with different vocabulary = commensurable (easily translatable). Incommensurable implies the frameworks themselves organize reality differently.',
          C: 'Value incommensurability (cannot be ranked by common standard) is a distinct philosophical concept. In this context, incommensurability refers to conceptual untranslatability, not value ranking.',
          D: 'Computer-assisted translation is not mentioned in the passage. D is clearly irrelevant.',
        },
        teachingPoint: 'Incommensurable = lacking a common measure. In philosophy of language and anthropology: conceptual incommensurability = concepts that do not have equivalents across frameworks because the frameworks organize reality differently. Example: indigenous legal concepts may have no equivalent in European legal systems — forcing translation distorts by imposing a framework the concept was not designed for.',
        relatedTopics: ['incommensurable conceptual frameworks', 'vocabulary CARS', 'translation untranslatability', 'indigenous concepts European frameworks'],
      },
    ],
  },
  {
    id: 'f5-cars-p8',
    sectionId: 'cars',
    passageNumber: 8,
    title: 'Economic Models and Human Behavior',
    passageText: `Classical economic theory rests on the assumption of rational choice: agents act to maximize their utility, defined as a consistent preference ordering over outcomes, subject to budget constraints. This model generates powerful predictions about market behavior in aggregate, and its theoretical elegance has made it central to both economic and political reasoning. Yet its empirical record is uneven: it performs well when incentives are strong and feedback loops are tight, but poorly in many everyday and institutional contexts where it assumes too much from human psychology.

Behavioral economics emerged from the anomalies that classical theory could not explain: systematic patterns of preference reversal, loss aversion, probability distortions, hyperbolic time discounting, and context-dependence of choice. Kahneman and Tversky's prospect theory replaced the utility function with a value function defined relative to a reference point, with losses looming larger than equivalent gains. This was not just a technical refinement — it reflected a different picture of human psychology: bounded rationality (Herbert Simon's concept), in which agents are not maximizers but "satisficers" who make "good enough" choices within cognitive limits.

The policy implications divide opinion. "Libertarian paternalism" or "nudge theory" (Thaler and Sunstein) argues that since choice architecture inevitably shapes decisions, governments and institutions should design default options that steer people toward choices they would endorse on reflection — while preserving freedom to opt out. Critics argue that nudging is manipulative: it bypasses rational agency rather than informing it, and the choice of what to nudge toward reflects the values of policymakers rather than of the people being nudged.

The deepest issue is whether behavioral anomalies reflect stable features of human cognition or are artifacts of laboratory conditions. If the anomalies dissolve with experience and market feedback, classical theory's predictive utility may survive. If they are robust across contexts, the normative implications of economic models must be fundamentally revised.`,
    questions: [
      {
        id: 'mcat5-cars-040',
        sectionId: 'cars',
        passageId: 'f5-cars-p8',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'easy',
        question: 'Kahneman and Tversky\'s prospect theory differs from classical utility theory primarily by:',
        choices: [
          { label: 'A', text: 'Assuming that agents are perfectly rational maximizers' },
          { label: 'B', text: 'Using a value function defined relative to a reference point, where losses loom larger than equivalent gains' },
          { label: 'C', text: 'Eliminating all psychological factors from economic modeling' },
          { label: 'D', text: 'Assuming that all agents have identical preferences' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 2: "Kahneman and Tversky\'s prospect theory replaced the utility function with a value function defined relative to a reference point, with losses looming larger than equivalent gains." B matches. A — rational maximizers = classical theory, not prospect theory. C — prospect theory incorporates psychological factors (loss aversion, reference points); it does not eliminate them. D — identical preferences is not claimed by either theory.',
        wrongAnswerExplanations: {
          A: 'Prospect theory is explicitly contrasted with classical theory. Rational maximizers = classical theory. Prospect theory incorporates bounded rationality and psychological features.',
          C: 'Prospect theory was developed precisely to incorporate psychological factors that classical theory excluded. C describes the opposite of what prospect theory does.',
          D: 'Neither theory assumes identical preferences. Prospect theory allows heterogeneous reference points and loss aversion coefficients.',
        },
        teachingPoint: 'Prospect theory key features: (1) value function, not utility function; (2) defined relative to reference point (gains/losses, not absolute wealth); (3) loss aversion (losses loom larger than equal gains); (4) probability distortions. These all differ from classical rational utility maximization.',
        relatedTopics: ['prospect theory', 'Kahneman Tversky reference point', 'loss aversion', 'utility function contrast'],
      },
      {
        id: 'mcat5-cars-041',
        sectionId: 'cars',
        passageId: 'f5-cars-p8',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'The critics of nudge theory argue that it is problematic because:',
        choices: [
          { label: 'A', text: 'It increases the cost of making choices for individuals' },
          { label: 'B', text: 'It bypasses rational agency rather than informing it, and reflects policymaker values rather than those of the people being nudged' },
          { label: 'C', text: 'It eliminates all default options from choice architecture' },
          { label: 'D', text: 'It requires individuals to choose against their stated preferences' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 3: "Critics argue that nudging is manipulative: it bypasses rational agency rather than informing it, and the choice of what to nudge toward reflects the values of policymakers rather than of the people being nudged." B is a direct match. A — nudging is about defaults, not increasing choice costs. C — nudging USES defaults; it does not eliminate them. D — nudging preserves the freedom to opt out; it does not require choosing against stated preferences.',
        wrongAnswerExplanations: {
          A: 'Nudge theory is about default options — it doesn\'t increase choice costs. The critique is about manipulation/autonomy, not cost.',
          C: 'Nudge theory is precisely about designing default options — it does not eliminate defaults. The critique is that the defaults reflect policymaker values.',
          D: 'Nudge theory preserves the right to opt out. The critique is not that it forces choices against preferences but that it steers people through defaults without engaging rational agency.',
        },
        teachingPoint: 'Nudge theory critique: two components: (1) bypasses rational agency (manipulates rather than informs — engages System 1, not System 2); (2) who decides what to nudge toward? Policymakers choose based on their values, not necessarily the population\'s authentic values. Both components together constitute the manipulation critique.',
        relatedTopics: ['nudge theory critique', 'libertarian paternalism', 'rational agency bypass', 'policymaker values'],
      },
      {
        id: 'mcat5-cars-042',
        sectionId: 'cars',
        passageId: 'f5-cars-p8',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'Herbert Simon\'s concept of "bounded rationality" and "satisficing" suggests that agents:',
        choices: [
          { label: 'A', text: 'Always find the optimal solution to any choice problem' },
          { label: 'B', text: 'Make choices randomly because they lack any consistent preferences' },
          { label: 'C', text: 'Make "good enough" decisions within cognitive limits rather than maximizing utility' },
          { label: 'D', text: 'Maximize utility but only within bounded time periods' },
        ],
        correctAnswer: 'C',
        explanation: 'Paragraph 2: bounded rationality is described as agents who "are not maximizers but \'satisficers\' who make \'good enough\' choices within cognitive limits." C matches. A — always finding the optimal solution = classical rationality, not bounded rationality. B — random choices with no consistent preferences is not described; satisficing is systematic (find a "good enough" option), not random. D — time-bounded maximization is not described; satisficing means accepting a "good enough" solution, not maximizing within time constraints.',
        wrongAnswerExplanations: {
          A: 'Optimal solution = maximizing. Bounded rationality explicitly says agents are NOT maximizers. A describes classical rationality.',
          B: 'Random choices with no preferences = neither classical nor bounded rationality. Satisficers have preferences and make systematic decisions — just stopping at "good enough" rather than optimum.',
          D: 'Simon\'s satisficing is not about time-bounded maximizing. It\'s about cognitive limitations that make maximizing impossible, so agents settle for acceptable options.',
        },
        teachingPoint: 'Bounded rationality: cognitive limits mean perfect optimization is impossible. Satisficing: find a solution that meets a threshold (good enough) rather than searching for the best possible option. Contrast: classical theory = maximizing agent; bounded rationality = satisficing agent with cognitive limits.',
        relatedTopics: ['bounded rationality Herbert Simon', 'satisficing definition', 'cognitive limits choice', 'CARS behavioral economics'],
      },
      {
        id: 'mcat5-cars-043',
        sectionId: 'cars',
        passageId: 'f5-cars-p8',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'hard',
        question: 'The "deepest issue" described in the final paragraph concerns:',
        choices: [
          { label: 'A', text: 'Whether behavioral economists have the right mathematical tools' },
          { label: 'B', text: 'Whether behavioral anomalies are stable features of human cognition or artifacts of laboratory conditions that dissolve with experience' },
          { label: 'C', text: 'Whether classical economic theory should be fully abandoned' },
          { label: 'D', text: 'Whether nudge theory is consistent with libertarian political philosophy' },
        ],
        correctAnswer: 'B',
        explanation: 'Final paragraph: "The deepest issue is whether behavioral anomalies reflect stable features of human cognition or are artifacts of laboratory conditions. If the anomalies dissolve with experience and market feedback, classical theory\'s predictive utility may survive. If they are robust across contexts, the normative implications of economic models must be fundamentally revised." B is a direct match. A — mathematical tools are not the issue. C — the passage does not call for abandoning classical theory. D — nudge/libertarian consistency is paragraph 3, not the final paragraph.',
        wrongAnswerExplanations: {
          A: 'Mathematical tools are not mentioned as the deepest issue. The concern is about the robustness and generalizability of behavioral anomalies.',
          C: 'The final paragraph raises whether classical theory\'s "predictive utility may survive" — not abandonment. The author presents both possibilities.',
          D: 'The libertarian/nudge question is in paragraph 3. The final paragraph raises a deeper methodological/empirical question about the robustness of the anomalies themselves.',
        },
        teachingPoint: 'The passage\'s deepest question: laboratory vs. real-world robustness. If behavioral anomalies (loss aversion, framing, hyperbolic discounting) are artifacts of lab conditions, classical theory survives. If they are stable and robust, economic models need normative revision. This is the fundamental empirical question underlying the entire debate.',
        relatedTopics: ['behavioral anomalies robustness', 'lab vs real-world', 'classical theory survival', 'CARS deepest issue'],
      },
      {
        id: 'mcat5-cars-044',
        sectionId: 'cars',
        passageId: 'f5-cars-p8',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning beyond the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'An employer automatically enrolls all new employees in a retirement savings plan but allows them to opt out. According to the passage, a proponent of nudge theory would argue this is justified because:',
        choices: [
          { label: 'A', text: 'The employer eliminates employees\' freedom to choose their savings rate' },
          { label: 'B', text: 'Default enrollment steers employees toward a choice they would likely endorse on reflection while preserving the right to opt out' },
          { label: 'C', text: 'Loss aversion means employees will always invest in retirement when given a choice' },
          { label: 'D', text: 'The employer maximizes utility by choosing the optimal savings rate for employees' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 3: nudge theory "argues that since choice architecture inevitably shapes decisions, governments and institutions should design default options that steer people toward choices they would endorse on reflection — while preserving freedom to opt out." Auto-enrollment in retirement = a default option (save) that people would endorse on reflection (most want retirement savings) + right to opt out preserved. B matches exactly. A — freedom is preserved (opt-out option). C — loss aversion does not make employees "always invest" — this is not a nudge theory claim. D — nudge theory does not claim to maximize utility; it designs defaults, not optimal solutions.',
        wrongAnswerExplanations: {
          A: 'The opt-out option specifically preserves freedom. A describes the opposite of what the example does.',
          C: 'Loss aversion describes how people weight losses vs. gains — it doesn\'t predict that employees will "always invest." Auto-enrollment is a nudge, not a consequence of loss aversion alone.',
          D: 'Nudge theory does not claim to optimize — it designs defaults that people would endorse on reflection. Maximizing utility = classical rationality claim, not nudge.',
        },
        teachingPoint: 'Nudge theory application: auto-enrollment retirement = paradigm case from Thaler and Sunstein. Justification: (1) choice architecture is inevitable; (2) the default reflects what people would endorse on reflection; (3) opt-out preserves freedom. This is "libertarian paternalism" — paternalistic (guides choice) but libertarian (preserves freedom to choose otherwise).',
        relatedTopics: ['nudge theory application', 'auto-enrollment retirement', 'default enrollment', 'libertarian paternalism example'],
      },
      {
        id: 'mcat5-cars-045',
        sectionId: 'cars',
        passageId: 'f5-cars-p8',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'The passage indicates that classical rational choice theory performs well when:',
        choices: [
          { label: 'A', text: 'Agents face complex decisions with many options and no prior experience' },
          { label: 'B', text: 'Incentives are strong and feedback loops are tight' },
          { label: 'C', text: 'Agents must make decisions under conditions of bounded rationality' },
          { label: 'D', text: 'Governments design default options to guide choices' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 1: classical theory "performs well when incentives are strong and feedback loops are tight, but poorly in many everyday and institutional contexts where it assumes too much from human psychology." B is a direct match. A — many options and no prior experience = conditions of complexity and bounded rationality, where classical theory performs poorly. C — bounded rationality = Herbert Simon\'s alternative to classical rationality; classical theory does NOT perform well under bounded rationality. D — government defaults = nudge theory, not classical rational choice.',
        wrongAnswerExplanations: {
          A: 'Complex decisions with no experience and many options are conditions where classical theory assumes too much — it performs poorly here according to paragraph 1.',
          C: 'Bounded rationality is the alternative model that explains why classical theory fails. Classical theory performs well where its assumption of full rationality approximates reality — strong incentives and tight feedback.',
          D: 'Government defaults = nudge theory (paragraph 3). Classical theory makes no such recommendation.',
        },
        teachingPoint: 'Classical theory conditions: strong incentives (agents are motivated to optimize) + tight feedback (agents learn quickly from mistakes). These approximate the conditions where rationality assumptions hold. In complex, low-feedback, low-incentive situations, behavioral anomalies dominate and classical theory fails.',
        relatedTopics: ['classical theory performance conditions', 'incentives feedback loops', 'rational choice theory limits', 'CARS recall'],
      },
      {
        id: 'mcat5-cars-046',
        sectionId: 'cars',
        passageId: 'f5-cars-p8',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'easy',
        question: 'According to the passage, behavioral economics emerged primarily because:',
        choices: [
          { label: 'A', text: 'Classical economists were uninterested in human psychology' },
          { label: 'B', text: 'Government regulators required a new framework for taxation policy' },
          { label: 'C', text: 'Classical theory could not explain systematic anomalies like loss aversion, preference reversal, and hyperbolic discounting' },
          { label: 'D', text: 'Prospect theory was developed to simplify the mathematics of classical utility theory' },
        ],
        correctAnswer: 'C',
        explanation: 'Paragraph 2: "Behavioral economics emerged from the anomalies that classical theory could not explain: systematic patterns of preference reversal, loss aversion, probability distortions, hyperbolic time discounting, and context-dependence of choice." C is a direct match. A — classical economists were not uninterested, but their theory assumed away psychological complexity. B — taxation policy is not mentioned. D — prospect theory is not a simplification; it is a fundamentally different model that addresses psychological realities classical theory missed.',
        wrongAnswerExplanations: {
          A: 'Classical economists were not uninterested in psychology — they made specific assumptions about it (rational maximization). Behavioral economics emerged because those assumptions were empirically wrong.',
          B: 'Government regulation and taxation are not mentioned as the origin of behavioral economics. It emerged from empirical anomalies in classic theory.',
          D: 'Prospect theory is more complex than classical utility theory in some respects (reference points, value functions). It was not developed to simplify — it was developed to account for anomalies.',
        },
        teachingPoint: 'Origin of behavioral economics: empirical anomalies that classical theory predicted would not occur systematically. Key anomalies: loss aversion, preference reversal, hyperbolic discounting, probability distortion, context-dependence. Kahneman and Tversky documented these, leading to prospect theory as an alternative model.',
        relatedTopics: ['behavioral economics origin', 'anomalies classical theory', 'loss aversion', 'hyperbolic discounting'],
      },
    ],
  },
  {
    id: 'f5-cars-p9',
    sectionId: 'cars',
    passageNumber: 9,
    title: 'Memory, Identity, and Narrative Self',
    passageText: `The relationship between memory and personal identity has been a central question in philosophy since Locke, who argued that personal identity consists in continuity of consciousness — specifically, the ability to extend memory backward in time to connect present and past selves. On Locke's view, if I can remember performing an action, I am the same person who performed it; if I cannot, I am not identical with that earlier person for purposes of moral responsibility.

This view faces a series of objections. The "transitivity problem" arises because memory chains can be non-transitive: a person A (at time 3) may remember being B (at time 2), and B may have remembered being C (at time 1), yet A cannot remember being C. If identity is constituted by memory connections, then A is identical with B, B is identical with C, but A is not identical with C — violating the transitivity of identity. Thomas Reid raised this objection in the form of the "brave officer paradox."

Derek Parfit's influential work reconceives personal identity by distinguishing identity from what he calls "psychological connectedness" — overlapping chains of memory, intention, belief, and desire that connect persons over time. For Parfit, strict numerical identity (the "one true self" through time) matters less than the degree of psychological continuity. Parfit's radical conclusion is that personal identity is not what matters: what matters is psychological continuity, which can come in degrees and can survive even without strict identity.

Paul Ricoeur takes a different approach, arguing that the self is constituted through narrative. Rather than treating the self as a metaphysical substance or a chain of psychological states, Ricoeur distinguishes idem-identity (sameness — the body, the biological substrate that persists) from ipse-identity (selfhood — the narrative capacity that integrates past, present, and anticipated future into a coherent self-understanding). Narrative identity is not found but constructed — and it is this construction that makes us capable of keeping promises and being held responsible.`,
    questions: [
      {
        id: 'mcat5-cars-047',
        sectionId: 'cars',
        passageId: 'f5-cars-p9',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'easy',
        question: 'Locke\'s theory holds that personal identity consists in:',
        choices: [
          { label: 'A', text: 'Continuity of the physical body over time' },
          { label: 'B', text: 'Continuity of consciousness, specifically the ability to extend memory backward to connect present and past selves' },
          { label: 'C', text: 'Narrative self-understanding that integrates past, present, and future' },
          { label: 'D', text: 'Psychological connectedness through overlapping chains of belief and desire' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 1: "personal identity consists in continuity of consciousness — specifically, the ability to extend memory backward in time to connect present and past selves." B is a direct match. A — physical continuity = a different theory (not Locke\'s). C = Ricoeur\'s narrative identity (paragraph 4). D = Parfit\'s psychological connectedness (paragraph 3).',
        wrongAnswerExplanations: {
          A: 'Physical/bodily continuity is a separate theory of personal identity (associated with biological views). Locke\'s theory is about consciousness/memory, not the body.',
          C: 'Narrative integration = Ricoeur\'s ipse-identity (paragraph 4). Locke\'s theory is about memory continuity, not narrative self-construction.',
          D: 'Overlapping psychological chains = Parfit\'s psychological continuity theory (paragraph 3). Locke focuses specifically on memory extension, not beliefs and desires.',
        },
        teachingPoint: 'Locke identity theory: consciousness + memory = identity. "If I remember doing X, I am the same person who did X." Simple but faces the transitivity problem. Map: Locke=memory, Parfit=psychological connectedness, Ricoeur=narrative self-construction.',
        relatedTopics: ['Locke personal identity', 'memory consciousness identity', 'CARS philosophy recall', 'personal identity theories'],
      },
      {
        id: 'mcat5-cars-048',
        sectionId: 'cars',
        passageId: 'f5-cars-p9',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'The "transitivity problem" undermines Locke\'s theory by showing that:',
        choices: [
          { label: 'A', text: 'Memory is too unreliable to serve as the basis of personal identity' },
          { label: 'B', text: 'Memory chains can be non-transitive, meaning A can be identical with B and B with C without A being identical with C — violating the transitivity of identity' },
          { label: 'C', text: 'The physical body is a more reliable criterion of personal identity than memory' },
          { label: 'D', text: 'Personal identity is impossible to determine in cases of amnesia' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 2: "The \'transitivity problem\' arises because memory chains can be non-transitive: a person A (at time 3) may remember being B (at time 2), and B may have remembered being C (at time 1), yet A cannot remember being C. If identity is constituted by memory connections, then A is identical with B, B is identical with C, but A is not identical with C — violating the transitivity of identity." B is a direct match. A — reliability of memory is a different objection. C — the physical body argument is an alternative theory, not the transitivity problem. D — amnesia is not mentioned in the passage.',
        wrongAnswerExplanations: {
          A: 'The transitivity problem is a logical objection about the structure of memory chains, not about whether memory is psychologically reliable.',
          C: 'The physical body as criterion is an alternative to Locke\'s theory, not the transitivity problem. The transitivity problem is an internal logical challenge to the memory theory.',
          D: 'Amnesia is not discussed in the passage. The transitivity problem is a general logical objection about non-transitive memory chains, not a special case of amnesia.',
        },
        teachingPoint: 'Transitivity problem: mathematical identity is transitive (if A=B and B=C, then A=C). Memory chains can be non-transitive (A remembers B, B remembered C, but A cannot remember C). If identity = memory, then A=B and B=C but A≠C — logical contradiction. Reid\'s brave officer paradox: the general (A) remembers being the young officer (B); the young officer (B) remembered being the boy who was flogged (C); but the general cannot remember being the boy flogged. → Identity cannot be transitive on memory theory.',
        relatedTopics: ['transitivity problem', 'Reid brave officer', 'Locke memory critique', 'non-transitive memory chains'],
      },
      {
        id: 'mcat5-cars-049',
        sectionId: 'cars',
        passageId: 'f5-cars-p9',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'Parfit\'s radical conclusion — that "personal identity is not what matters" — most likely means:',
        choices: [
          { label: 'A', text: 'Personal identity is trivial and unimportant for all practical purposes' },
          { label: 'B', text: 'What matters morally and practically is psychological continuity, not strict numerical identity of a persisting self' },
          { label: 'C', text: 'Persons do not persist through time at all' },
          { label: 'D', text: 'Memory is the only thing that matters in personal identity' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 3: "For Parfit, strict numerical identity (the \'one true self\' through time) matters less than the degree of psychological continuity. Parfit\'s radical conclusion is that personal identity is not what matters: what matters is psychological continuity, which can come in degrees and can survive even without strict identity." B captures the nuance: what matters morally/practically is psychological continuity — not identity per se. A overstates ("trivial and unimportant for all purposes" — Parfit argues it matters less than psychological continuity, not that it\'s trivial universally). C is not Parfit\'s claim (persons do persist — they just do so through overlapping psychological states, not strict numerical identity). D misrepresents (memory is one component of psychological continuity, not "the only thing").',
        wrongAnswerExplanations: {
          A: '"Trivial and unimportant for all purposes" goes beyond Parfit\'s claim. Parfit says identity matters LESS than psychological continuity — he shifts what we should care about, not eliminates caring about persons.',
          C: 'Persons do persist in Parfit\'s view — through psychological continuity. Parfit argues that what matters is this continuity, not that persons don\'t exist across time.',
          D: 'Parfit includes memory but also intentions, beliefs, and desires in psychological connectedness. Memory alone is Locke\'s focus.',
        },
        teachingPoint: 'Parfit: identity is real but not what matters. What matters: psychological continuity — overlapping chains of memory, belief, desire, intention. This can come in degrees and survive even without strict identity (e.g., if you split into two continuous psychological descendants — identity cannot hold for both, but both have what matters). Parfit\'s conclusion has ethical implications: if identity is not what matters, self-interest rationality and some desert-based punishment views are challenged.',
        relatedTopics: ['Parfit psychological continuity', 'identity not what matters', 'overlapping chains', 'CARS philosophy Parfit'],
      },
      {
        id: 'mcat5-cars-050',
        sectionId: 'cars',
        passageId: 'f5-cars-p9',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'hard',
        question: 'Ricoeur\'s distinction between idem-identity and ipse-identity holds that:',
        choices: [
          { label: 'A', text: 'Idem-identity is the biological substrate; ipse-identity is the narrative self that integrates past, present, and anticipated future' },
          { label: 'B', text: 'Idem-identity is the narrative self; ipse-identity is the biological substrate' },
          { label: 'C', text: 'Both refer to the same underlying substance of the self' },
          { label: 'D', text: 'Idem-identity corresponds to Parfit\'s psychological connectedness' },
        ],
        correctAnswer: 'A',
        explanation: 'Paragraph 4: "Ricoeur distinguishes idem-identity (sameness — the body, the biological substrate that persists) from ipse-identity (selfhood — the narrative capacity that integrates past, present, and anticipated future into a coherent self-understanding)." A is a direct match. B inverts the definitions. C is wrong — Ricoeur distinguishes them as different aspects of identity. D — Parfit\'s psychological connectedness focuses on memory, belief, and desire chains — not the biological substrate (idem) or narrative self (ipse).',
        wrongAnswerExplanations: {
          B: 'B inverts the definitions. Idem = sameness/body; ipse = selfhood/narrative. The passage states these clearly.',
          C: 'Ricoeur distinguishes them precisely because they are different aspects of identity — idem is the bodily substrate; ipse is the narrative construction. They are not the same underlying substance.',
          D: 'Parfit\'s psychological connectedness corresponds more closely to ipse-identity (continuous psychological states) than idem-identity. But even this mapping is imprecise — Ricoeur\'s ipse-identity specifically emphasizes narrative self-construction rather than Parfit\'s chain model.',
        },
        teachingPoint: 'Ricoeur identity: Idem (from Latin "same") = sameness = body/biological continuity. Ipse (from Latin "self") = selfhood = narrative capacity integrating temporally. Key: ipse-identity is CONSTRUCTED, not found — this is what grounds promise-keeping and moral responsibility. Compare: Locke=memory, Parfit=psychological chains, Ricoeur=narrative construction.',
        relatedTopics: ['Ricoeur idem ipse', 'narrative identity', 'biological substrate selfhood', 'CARS identity philosophy'],
      },
      {
        id: 'mcat5-cars-051',
        sectionId: 'cars',
        passageId: 'f5-cars-p9',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning beyond the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'A patient with severe anterograde amnesia can no longer form new memories but retains all memories from before the injury. According to Locke\'s theory as described, which conclusion follows?',
        choices: [
          { label: 'A', text: 'The patient is not responsible for actions taken after the injury because memory continuity is broken for those actions' },
          { label: 'B', text: 'The patient\'s identity is unaffected because the body remains the same' },
          { label: 'C', text: 'The patient\'s ipse-identity is preserved but idem-identity is lost' },
          { label: 'D', text: 'Parfit would agree with Locke that the patient is not the same person as their post-injury self' },
        ],
        correctAnswer: 'A',
        explanation: 'Locke (paragraph 1): "if I can remember performing an action, I am the same person who performed it; if I cannot, I am not identical with that earlier person for purposes of moral responsibility." Anterograde amnesia = cannot form new memories, so cannot remember actions taken after the injury. On Locke\'s view, this means the person is not identical with the agent of post-injury actions for purposes of moral responsibility. A follows logically. B — bodily continuity = a different theory (not Locke\'s). C — Ricoeur\'s concepts (idem/ipse), not Locke\'s. D — Parfit would analyze the case differently (psychological continuity, not strict memory) and might reach different conclusions.',
        wrongAnswerExplanations: {
          B: 'Bodily continuity is NOT Locke\'s criterion. Locke\'s theory is about memory-based consciousness continuity. The body\'s sameness is irrelevant to Locke\'s identity claim.',
          C: 'Idem-identity and ipse-identity are Ricoeur\'s concepts (paragraph 4), not Locke\'s. Applying Locke\'s theory requires using Locke\'s memory criterion.',
          D: 'Parfit (paragraph 3) uses psychological continuity, which includes memory but also intentions, beliefs, and desires. The patient retains pre-injury memories and psychological states. Parfit\'s analysis would be more nuanced — the degree of psychological continuity depends on other factors beyond just new memory formation.',
        },
        teachingPoint: 'Apply Locke: anterograde amnesia → cannot form new memories of post-injury actions → cannot "remember performing" those actions → on Locke\'s theory, not the same person for those actions → not responsible. This is a direct application of paragraph 1\'s logic. Note: this is controversial but follows from Locke\'s criterion.',
        relatedTopics: ['Locke apply amnesia', 'anterograde amnesia identity', 'memory responsibility', 'CARS apply philosophy'],
      },
      {
        id: 'mcat5-cars-052',
        sectionId: 'cars',
        passageId: 'f5-cars-p9',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'Ricoeur argues that narrative identity is "not found but constructed." This most likely implies:',
        choices: [
          { label: 'A', text: 'The self is an illusion with no real existence' },
          { label: 'B', text: 'The self is a fixed metaphysical substance that can be discovered through introspection' },
          { label: 'C', text: 'The self is actively created through the narratives we construct about our lives, rather than being a pre-existing thing we merely discover' },
          { label: 'D', text: 'Narrative identity is the same as idem-identity' },
        ],
        correctAnswer: 'C',
        explanation: 'Paragraph 4: "Narrative identity is not found but constructed — and it is this construction that makes us capable of keeping promises and being held responsible." "Not found" = not a pre-existing metaphysical substance waiting to be discovered. "Constructed" = actively created through narrative self-understanding. C captures this. A overstates — Ricoeur does not say the self is an illusion; he says the ipse-identity is constructed (real, but through construction). B is what "found" would imply — the opposite of Ricoeur\'s claim. D — narrative identity = ipse-identity, not idem-identity.',
        wrongAnswerExplanations: {
          A: 'Ricoeur affirms the self\'s reality — narrative construction is how the self exists, not evidence that it doesn\'t exist. Calling it an illusion is nihilistic; Ricoeur\'s view is constructivist, not illusionist.',
          B: '"Found through introspection" would mean the self is a fixed metaphysical substance to be discovered — exactly what "not found" rejects.',
          D: 'Idem-identity = the body/biological substrate (sameness). Ipse-identity = narrative selfhood. Narrative identity = ipse, not idem. Final paragraph distinguishes them clearly.',
        },
        teachingPoint: 'Ricoeur constructivism: the self is neither a fixed substance (found by introspection) nor an illusion (dismissed by Humean/Parfitian critiques) — it is actively constructed through narrative. This construction is not arbitrary (it must integrate real memories, commitments, relationships) but it is genuinely created through the act of self-narration.',
        relatedTopics: ['narrative construction self', 'Ricoeur constructivism', 'ipse-identity not found', 'CARS Ricoeur'],
      },
      {
        id: 'mcat5-cars-053',
        sectionId: 'cars',
        passageId: 'f5-cars-p9',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'The passage as a whole is BEST characterized as:',
        choices: [
          { label: 'A', text: 'An argument that Locke\'s theory is the most defensible account of personal identity' },
          { label: 'B', text: 'A survey of competing philosophical theories of personal identity, moving from Locke through Parfit to Ricoeur\'s narrative alternative' },
          { label: 'C', text: 'A defense of Parfit\'s psychological continuity theory against Locke and Ricoeur' },
          { label: 'D', text: 'A critique of philosophical accounts of personal identity in favor of neuroscientific approaches' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage maps: Locke (memory-based identity) → transitivity problem/objections → Parfit (psychological connectedness) → Ricoeur (narrative identity). It presents each view with its core claims without definitively endorsing one over the others. B captures this survey structure. A — Locke\'s theory is immediately challenged (paragraph 2). C — Parfit is presented alongside others; the passage does not defend Parfit against Ricoeur specifically. D — neuroscience is not mentioned.',
        wrongAnswerExplanations: {
          A: 'Locke\'s theory is presented and then immediately subjected to the transitivity objection. The passage does not defend Locke as most defensible.',
          C: 'The passage presents Parfit and Ricoeur as distinct approaches — it does not defend Parfit against Ricoeur. Ricoeur is introduced as taking "a different approach," not as wrong.',
          D: 'Neuroscience is entirely absent from the passage. The survey is entirely within philosophy of mind and personal identity theory.',
        },
        teachingPoint: 'Passage structure characterization: Locke (view) → objection (transitivity) → Parfit (alternative 1) → Ricoeur (alternative 2). No definitive endorsement. This is a neutral survey of competing theories. B captures: survey + three positions + progression from Locke to Parfit to Ricoeur.',
        relatedTopics: ['passage structure CARS', 'survey philosophy theories', 'Locke Parfit Ricoeur', 'CARS overall structure'],
      },
    ],
  },
]
