import type { MCATPassage } from '../types'

// Form 5 CARS — Passages 1–5 (IDs mcat5-cars-001 through mcat5-cars-026)

export const carsPassages5_01to05: MCATPassage[] = [
  {
    id: 'f5-cars-p1',
    sectionId: 'cars',
    passageNumber: 1,
    title: 'The Limits of Expertise',
    passageText: `Expertise is typically conceptualized as deep, reliable knowledge within a defined domain — the product of deliberate practice, pattern recognition, and the accumulation of case-specific experience. Yet research on expert performance reveals a paradox: experts frequently outperform novices within their domain while simultaneously making systematic errors that novices avoid, particularly when domain-irrelevant biases intrude.

Philip Tetlock's landmark study of political forecasters found that experts — economists, political scientists, foreign policy analysts — performed only marginally better than chance over a twenty-year period when their predictions were evaluated against actual outcomes. The "foxes" — generalists who drew on multiple frameworks — outperformed the "hedgehogs" — specialists committed to a single dominant idea. Tetlock's conclusion was not that expertise is worthless, but that it is domain-specific: expertise in explaining the past does not translate smoothly into predicting the future, particularly in complex, nonlinear systems.

This finding connects to a broader debate about the relationship between domain knowledge and calibration — the alignment between confidence and accuracy. Experts, paradoxically, are often less well calibrated than novices in domains adjacent to their specialty. The Dunning-Kruger effect describes a related phenomenon: less competent individuals overestimate their competence, while more competent individuals underestimate theirs — though the primary cause of expert miscalibration is distinct: it arises from the habit of extending heuristics beyond the conditions for which they were validated.

The implication is not that expertise should be distrusted but that it should be bounded. Domain-specific expertise combined with explicit uncertainty quantification and structured adversarial review processes produces significantly more accurate forecasts than unstructured expert opinion alone.`,
    questions: [
      {
        id: 'mcat5-cars-001',
        sectionId: 'cars',
        passageId: 'f5-cars-p1',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'The author\'s primary purpose in describing Tetlock\'s study is to:',
        choices: [
          { label: 'A', text: 'Argue that political expertise is entirely without merit' },
          { label: 'B', text: 'Illustrate the paradox that domain expertise does not automatically produce accurate predictions in complex systems' },
          { label: 'C', text: 'Demonstrate that generalists are superior to specialists in all contexts' },
          { label: 'D', text: 'Advocate for the elimination of expert advisory roles in policy decisions' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 2 describes Tetlock\'s study as evidence that "expertise in explaining the past does not translate smoothly into predicting the future, particularly in complex, nonlinear systems." The author uses this to illustrate the limits of expertise — specifically the paradox established in paragraph 1. B captures this precisely. A is too extreme (paragraph 2: "not that expertise is worthless"). C overstates — foxes outperformed hedgehogs in this context, not generally. D is not stated; the author advocates for bounded expertise with structured review, not elimination.',
        wrongAnswerExplanations: {
          A: 'The author explicitly states "not that expertise is worthless" — the passage does not argue expertise is without merit.',
          C: 'Foxes outperformed hedgehogs in political forecasting — but the author does not generalize this to "all contexts."',
          D: 'The author\'s recommendation is structured adversarial review, not elimination of expert roles.',
        },
        teachingPoint: 'CARS primary purpose questions: focus on what the author IS claiming, not extreme versions of the argument. Authors often set up nuance ("not X, but Y") — correct answers reflect this nuance. Tetlock study purpose: evidence for the limits (not worthlessness) of expertise in complex prediction tasks.',
        relatedTopics: ['primary purpose', 'Tetlock expertise', 'complex systems prediction', 'author intent'],
      },
      {
        id: 'mcat5-cars-002',
        sectionId: 'cars',
        passageId: 'f5-cars-p1',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'According to the passage, what distinguishes the miscalibration of experts from the Dunning-Kruger effect?',
        choices: [
          { label: 'A', text: 'Expert miscalibration involves overconfidence; Dunning-Kruger involves underconfidence' },
          { label: 'B', text: 'Expert miscalibration arises from extending heuristics beyond validated conditions; Dunning-Kruger involves overestimation by the less competent' },
          { label: 'C', text: 'They are the same phenomenon described from different perspectives' },
          { label: 'D', text: 'Dunning-Kruger affects only novices; expert miscalibration affects only specialists' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 3: "the primary cause of expert miscalibration is distinct: it arises from the habit of extending heuristics beyond the conditions for which they were validated." The Dunning-Kruger effect is described as "less competent individuals overestimate their competence, while more competent individuals underestimate theirs." These are different: Dunning-Kruger = less competent overestimate; expert miscalibration = heuristic over-extension. B captures this distinction. A misattributes underconfidence to experts (the passage says experts underestimate within DK, but expert miscalibration is about heuristic extension, not simple over/underconfidence).',
        wrongAnswerExplanations: {
          A: 'The DK effect has BOTH components: less competent overestimate, more competent underestimate. Expert miscalibration is not simply overconfidence — it is specifically about heuristic over-extension.',
          C: 'The passage explicitly distinguishes them: "the primary cause of expert miscalibration is distinct."',
          D: 'The passage does not restrict DK to "only novices" — it applies to competence levels generally. Expert miscalibration is discussed as "distinct" from DK, not as exclusive to specialists.',
        },
        teachingPoint: 'Detail distinction questions: use precise passage text. DK = competence-confidence mismatch. Expert miscalibration = heuristic extension beyond validated context. The author calls these "related" but "distinct" — pick the answer that preserves both characterizations without conflating or reversing them.',
        relatedTopics: ['Dunning-Kruger distinction', 'expert miscalibration', 'heuristic extension', 'calibration'],
      },
      {
        id: 'mcat5-cars-003',
        sectionId: 'cars',
        passageId: 'f5-cars-p1',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning beyond the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'Which finding would most strengthen the author\'s argument in the final paragraph?',
        choices: [
          { label: 'A', text: 'Experts who used a single dominant analytical framework were the most accurate forecasters' },
          { label: 'B', text: 'Structured adversarial review processes were found to improve forecast accuracy by 40% compared to unstructured expert opinion' },
          { label: 'C', text: 'Experts in one domain routinely outperformed novices in completely unrelated domains' },
          { label: 'D', text: 'Uncertainty quantification reduced the confidence of experts, making them less useful to policymakers' },
        ],
        correctAnswer: 'B',
        explanation: 'The final paragraph argues that "domain-specific expertise combined with explicit uncertainty quantification and structured adversarial review processes produces significantly more accurate forecasts than unstructured expert opinion alone." Finding B directly confirms this claim — adversarial review improves accuracy → strengthens the prescription. A contradicts it (single framework = hedgehog, which underperformed). C is about unrelated domains, not the author\'s claim. D weakens the argument (reduced utility = against the recommendation).',
        wrongAnswerExplanations: {
          A: 'Single dominant framework = hedgehog style, which Tetlock found performed worse. This would undermine the author\'s argument, not strengthen it.',
          C: 'The passage doesn\'t claim experts outperform in unrelated domains — it makes no such claim. This finding is tangential.',
          D: 'If uncertainty quantification reduced experts\' usefulness, this would undermine the final recommendation, not strengthen it.',
        },
        teachingPoint: 'Strengthen questions: find the answer that directly supports the specific claim being tested. Final paragraph claim: structured review + uncertainty quantification improves accuracy. B provides direct empirical support. Avoid answers that support tangential claims or contradict the argument.',
        relatedTopics: ['strengthen argument', 'structured review', 'uncertainty quantification', 'CARS strengthen'],
      },
      {
        id: 'mcat5-cars-004',
        sectionId: 'cars',
        passageId: 'f5-cars-p1',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'easy',
        question: 'The term "bounded" (final paragraph) most nearly means, in context:',
        choices: [
          { label: 'A', text: 'Suppressed or ignored' },
          { label: 'B', text: 'Limited in scope or application to appropriate domains' },
          { label: 'C', text: 'Amplified through deliberate practice' },
          { label: 'D', text: 'Replaced by algorithmic forecasting' },
        ],
        correctAnswer: 'B',
        explanation: '"Expertise should be bounded" in context means applying expertise within appropriate limits — recognizing where it applies and where it does not. The passage established that expertise is domain-specific and can fail when extended beyond validated conditions. "Bounded" = limited to the domain where it has been validated. B is correct. A — "suppressed" contradicts the author\'s conclusion (use expertise, but within limits). C is unrelated. D is not stated.',
        wrongAnswerExplanations: {
          A: 'The author advocates for using expertise (not ignoring it) — the recommendation is to bound it appropriately, not suppress it.',
          C: 'The passage is about limiting (not amplifying) the application of expertise beyond validated domains.',
          D: 'Algorithmic replacement is not mentioned in the passage as the meaning of "bounded."',
        },
        teachingPoint: 'Vocabulary in context: use surrounding text. "Bounded expertise" follows from the passage\'s argument: expertise is domain-specific, fails when extended beyond its domain → "bounded" means domain-limited. The recommendation: use expertise within appropriate limits + add structured review.',
        relatedTopics: ['vocabulary context', 'bounded expertise', 'scope limitation', 'CARS word meaning'],
      },
      {
        id: 'mcat5-cars-005',
        sectionId: 'cars',
        passageId: 'f5-cars-p1',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'The author would MOST likely agree with which statement?',
        choices: [
          { label: 'A', text: 'Expert opinion should be replaced with crowdsourced predictions in complex domains' },
          { label: 'B', text: 'The hedgehog\'s depth of specialization generally produces superior forecasting than the fox\'s breadth' },
          { label: 'C', text: 'Expert prediction can be improved by explicitly quantifying uncertainty and subjecting forecasts to adversarial review' },
          { label: 'D', text: 'Expertise in one domain guarantees superior performance in adjacent domains' },
        ],
        correctAnswer: 'C',
        explanation: 'Final paragraph directly states: "domain-specific expertise combined with explicit uncertainty quantification and structured adversarial review processes produces significantly more accurate forecasts than unstructured expert opinion alone." C matches this prescription exactly. A — crowdsourcing is not mentioned; the author advocates structured adversarial review, not crowdsourcing. B — paragraph 2 explicitly says foxes (breadth) outperformed hedgehogs (depth). D — paragraph 3 says experts are "less well calibrated than novices in domains adjacent to their specialty."',
        wrongAnswerExplanations: {
          A: 'The author recommends structured adversarial review and uncertainty quantification — not replacing experts with crowds.',
          B: 'Tetlock\'s finding was the opposite: foxes (generalists) outperformed hedgehogs (specialists). The author agrees with this finding.',
          D: 'The passage explicitly states expertise is domain-specific and fails in adjacent domains — the opposite of this claim.',
        },
        teachingPoint: 'Author agreement questions: synthesize the passage\'s central argument. The author\'s position: expertise is real but domain-specific; miscalibration arises from over-extension; solution = bounded expertise + structured review. Match to C.',
        relatedTopics: ['author agreement', 'structured review prescription', 'CARS inference', 'fox vs hedgehog'],
      },
      {
        id: 'mcat5-cars-006',
        sectionId: 'cars',
        passageId: 'f5-cars-p1',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'hard',
        question: 'Which of the following most accurately identifies a potential weakness in the author\'s argument?',
        choices: [
          { label: 'A', text: 'The author fails to cite any empirical evidence in support of the argument' },
          { label: 'B', text: 'Tetlock\'s study of political forecasters may not generalize to all domains of expertise' },
          { label: 'C', text: 'The author contradicts themselves by both defending and criticizing expertise' },
          { label: 'D', text: 'The concept of "bounded expertise" has never been successfully implemented in practice' },
        ],
        correctAnswer: 'B',
        explanation: 'The author builds the general argument about the limits of expertise primarily on Tetlock\'s study of political forecasters. Political forecasting is a domain with particularly high uncertainty, nonlinearity, and complexity. The study may not generalize to domains like engineering, medicine, or physics, where expert performance is more reliable. B identifies this generalizability limitation. A — the author cites Tetlock, Dunning-Kruger, and the structured review finding. C — the author makes a nuanced claim (not worthless, but bounded) — this is not a contradiction. D — no evidence is given for or against implementation; D introduces an unsupported claim.',
        wrongAnswerExplanations: {
          A: 'The author cites Tetlock\'s study, the Dunning-Kruger effect, and structured review findings — there is empirical grounding.',
          C: 'Arguing "expertise is real but has limits" is not a contradiction — it is a nuanced position. The author distinguishes between domain-specific expertise (valuable) and over-extended heuristics (problematic).',
          D: 'Whether bounded expertise has been "successfully implemented" is not addressed in the passage. Introducing an external claim unrelated to the passage\'s argument is not a legitimate weakness of the argument as stated.',
        },
        teachingPoint: 'Weakness identification: look for logical gaps, unsupported generalizations, or unstated assumptions. Key weakness here: generalizing from political forecasting (high complexity, low predictability) to "expertise" broadly. Other domains (surgery, structural engineering) have much better expert track records. The argument is strongest for complex, nonlinear systems but may not hold across all expert domains.',
        relatedTopics: ['argument weakness', 'generalizability limitation', 'single study basis', 'CARS critique'],
      },
    ],
  },
  {
    id: 'f5-cars-p2',
    sectionId: 'cars',
    passageNumber: 2,
    title: 'The Philosophy of Historical Causation',
    passageText: `Historians disagree about the nature of historical explanation. The debate is at its sharpest on the question of causation: what counts as a cause of a historical event, and how should causal claims be evaluated?

One tradition, associated with positivist historiography, holds that historical explanation is fundamentally similar to scientific explanation: to explain an event is to subsume it under a general causal law. An adequate historical explanation identifies the antecedent conditions and the covering law (a universal generalization) under which the event necessarily follows. This view demands that historical claims be empirically verifiable and that narrative accounts be translatable into law-like statements.

Critics of the covering-law model argue that history is irreducibly particular: unlike natural phenomena, historical events are unique configurations of human agency, contingency, and contextual meaning that resist subsumption under universal laws. Wilhelm Dilthey drew a sharp distinction between Erklären (causal explanation, appropriate for natural science) and Verstehen (interpretive understanding, appropriate for the human sciences). Historical understanding, on this view, involves reconstructing the intentions, meanings, and contexts of historical actors — a fundamentally interpretive enterprise that cannot be captured in causal laws.

A third position, associated with narrative causation, holds that neither the covering-law model nor pure Verstehen fully captures historical explanation. Historians explain by constructing narratives that organize events into intelligible sequences — narratives that implicitly rely on causal assumptions without requiring explicit formulation of universal laws. The narrative connects events by showing how earlier states of affairs constrained, enabled, or made probable later ones, without claiming strict necessity.

The most defensible position may be that historical explanation is genuinely pluralistic: different explanatory strategies are appropriate for different questions. Macro-historical trends (e.g., industrialization, demographic shifts) may be amenable to quasi-nomological explanation; micro-historical questions about individual decisions and motivations require interpretive approaches.`,
    questions: [
      {
        id: 'mcat5-cars-007',
        sectionId: 'cars',
        passageId: 'f5-cars-p2',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'easy',
        question: 'Dilthey\'s distinction between Erklären and Verstehen most directly challenges which approach to historical explanation?',
        choices: [
          { label: 'A', text: 'Narrative causation' },
          { label: 'B', text: 'Pluralistic historical explanation' },
          { label: 'C', text: 'The covering-law model' },
          { label: 'D', text: 'Micro-historical interpretive approaches' },
        ],
        correctAnswer: 'C',
        explanation: 'Paragraph 3 presents Dilthey\'s distinction as a critique: "Critics of the covering-law model argue that history is irreducibly particular...Dilthey drew a sharp distinction between Erklären (causal explanation) and Verstehen." The target of this critique is the covering-law model (paragraph 2), which holds that historical explanation should subsume events under universal laws (Erklären). C is correct. A — narrative causation is a third position, not Dilthey\'s target. B — pluralism is the final position, not Dilthey\'s. D — interpretive (Verstehen) approaches are what Dilthey advocates for, not what he challenges.',
        wrongAnswerExplanations: {
          A: 'Narrative causation is presented as a THIRD position beyond both covering-law and Verstehen. Dilthey\'s argument pre-dates and targets the covering-law model.',
          B: 'Pluralism is the author\'s final synthesis — not Dilthey\'s target.',
          D: 'Micro-historical interpretive approaches are aligned WITH Dilthey\'s Verstehen — they would be what Dilthey recommends, not what he challenges.',
        },
        teachingPoint: 'Identify who is critiquing whom: Dilthey = critic of positivist/covering-law model. He argues history requires Verstehen, not Erklären. This directly targets the covering-law model of paragraph 2. Map the debate structure before answering.',
        relatedTopics: ['Dilthey Erklären Verstehen', 'covering law model critique', 'historical explanation', 'CARS debate structure'],
      },
      {
        id: 'mcat5-cars-008',
        sectionId: 'cars',
        passageId: 'f5-cars-p2',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'Which of the following BEST describes the author\'s position on historical explanation?',
        choices: [
          { label: 'A', text: 'The covering-law model provides the most rigorous and defensible approach' },
          { label: 'B', text: 'Verstehen is always superior to causal explanation in historical contexts' },
          { label: 'C', text: 'Different explanatory strategies are appropriate for different historical questions — no single approach is universally adequate' },
          { label: 'D', text: 'Narrative causation has rendered both covering-law and Verstehen approaches obsolete' },
        ],
        correctAnswer: 'C',
        explanation: 'Final paragraph: "The most defensible position may be that historical explanation is genuinely pluralistic: different explanatory strategies are appropriate for different questions." C matches this directly. A and B are positions described and critiqued, not the author\'s own. D overstates — the author does not claim narrative causation has made other approaches obsolete.',
        wrongAnswerExplanations: {
          A: 'The covering-law model is presented in paragraph 2 and immediately subjected to Dilthey\'s critique in paragraph 3 — the author does not endorse it as "most defensible."',
          B: 'Verstehen is presented as one approach — appropriate for some questions (micro-history, individual motivations). The author argues for pluralism, not Verstehen universally.',
          D: 'The final paragraph includes BOTH quasi-nomological explanation AND interpretive approaches — not only narrative. Obsolescence is not claimed.',
        },
        teachingPoint: 'Author position questions: look at the final paragraph and evaluate the hedging language. "The most defensible position may be..." signals the author\'s view. Pluralism: multiple approaches, each appropriate for different questions. This is the synthetic resolution that authors often favor in CARS passages.',
        relatedTopics: ['author position pluralism', 'historical explanation synthesis', 'CARS author view', 'pluralistic approach'],
      },
      {
        id: 'mcat5-cars-009',
        sectionId: 'cars',
        passageId: 'f5-cars-p2',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'According to the passage, what makes narrative causation distinct from both the covering-law model and Verstehen?',
        choices: [
          { label: 'A', text: 'It organizes events into intelligible sequences without requiring explicit universal laws or purely interpretive reconstruction of intentions' },
          { label: 'B', text: 'It requires both universal laws AND interpretive understanding simultaneously' },
          { label: 'C', text: 'It focuses exclusively on individual decisions and motivations' },
          { label: 'D', text: 'It is the only approach that makes causal assumptions explicit' },
        ],
        correctAnswer: 'A',
        explanation: 'Paragraph 4: narrative causation "holds that neither the covering-law model nor pure Verstehen fully captures historical explanation. Historians explain by constructing narratives that organize events into intelligible sequences — narratives that implicitly rely on causal assumptions without requiring explicit formulation of universal laws." A captures this: organizes into sequences (neither explicit laws nor pure intention-reconstruction). B — narrative does not require BOTH simultaneously; it works without requiring either in their pure form. C — exclusive focus on individual decisions = Verstehen, not narrative. D — narrative makes causal assumptions IMPLICIT, not explicit.',
        wrongAnswerExplanations: {
          B: 'Narrative causation is presented as a THIRD position that does not require both covering-laws AND Verstehen simultaneously. It works differently from either.',
          C: 'Individual decisions and motivations are the domain of interpretive (Verstehen) approaches — micro-history. Narrative causation spans different scales.',
          D: 'The passage says narrative relies on causal assumptions "without requiring EXPLICIT formulation of universal laws" — the assumptions are IMPLICIT, not made explicit.',
        },
        teachingPoint: 'Identifying the middle position: narrative causation = third option that differs from BOTH extremes. Key features: (1) constructs intelligible sequences; (2) implicit causal assumptions; (3) shows constraint/enabling without strict necessity; (4) doesn\'t require universal laws OR pure intention-reconstruction. A captures all this.',
        relatedTopics: ['narrative causation', 'third position history', 'implicit causation', 'CARS three position debate'],
      },
      {
        id: 'mcat5-cars-010',
        sectionId: 'cars',
        passageId: 'f5-cars-p2',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning beyond the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'An economic historian explains industrialization by identifying structural conditions (capital availability, coal deposits, legal institutions) that made industrial development probable. This approach is BEST classified as:',
        choices: [
          { label: 'A', text: 'Pure Verstehen — reconstruction of the intentions of economic actors' },
          { label: 'B', text: 'Quasi-nomological explanation — macro-historical structural causation approaching the covering-law model' },
          { label: 'C', text: 'Narrative causation — organizing events into an intelligible sequence' },
          { label: 'D', text: 'The covering-law model — subsuming industrialization under a universal economic law' },
        ],
        correctAnswer: 'B',
        explanation: 'Final paragraph: "Macro-historical trends (e.g., industrialization, demographic shifts) may be amenable to quasi-nomological explanation." Quasi-nomological = law-like but not strictly universal; identifying structural conditions (capital, coal, institutions) that make industrialization probable (not necessary) fits this category — approaching but not fully committing to the covering-law model. B is correct. A — Verstehen = reconstruction of individual intentions — not this example. C — narrative = constructing a sequence narrative — the example focuses on structural conditions, not a narrative. D — the covering-law model requires strict universal laws; this example uses probabilistic structural conditions, which is quasi-nomological.',
        wrongAnswerExplanations: {
          A: 'Verstehen reconstructs the intentions and meanings of individual historical actors. Identifying coal deposits and legal institutions as structural conditions = structural causation, not individual intention reconstruction.',
          C: 'Narrative causation emphasizes organizing events into intelligible sequences. Identifying structural conditions (preconditions) is closer to quasi-nomological structural explanation than narrative organization.',
          D: 'The covering-law model requires strict universal laws that necessitate the outcome. Structural conditions that make industrialization "probable" (not necessary) = probabilistic, which is quasi-nomological, not fully covering-law.',
        },
        teachingPoint: 'Application questions: map the example onto the framework. Macro-historical + structural conditions + industrialization = final paragraph categorization = quasi-nomological. Key word: "probable" (not "necessary") → quasi-nomological, not covering-law.',
        relatedTopics: ['quasi-nomological explanation', 'macro-historical causation', 'structural conditions', 'CARS application'],
      },
      {
        id: 'mcat5-cars-011',
        sectionId: 'cars',
        passageId: 'f5-cars-p2',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'easy',
        question: 'The positivist covering-law model holds that a historical explanation is adequate only if it:',
        choices: [
          { label: 'A', text: 'Reconstructs the intentions and meanings of historical actors' },
          { label: 'B', text: 'Identifies antecedent conditions and a covering law under which the event necessarily follows' },
          { label: 'C', text: 'Constructs an intelligible narrative without claiming strict necessity' },
          { label: 'D', text: 'Distinguishes between macro and micro levels of historical analysis' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 2: the covering-law model holds that "to explain an event is to subsume it under a general causal law...An adequate historical explanation identifies the antecedent conditions and the covering law (a universal generalization) under which the event necessarily follows." B matches. A = Verstehen (paragraph 3). C = narrative causation (paragraph 4). D = the pluralist approach (paragraph 5).',
        wrongAnswerExplanations: {
          A: 'Reconstructing intentions = Verstehen (Dilthey). The covering-law model focuses on universal laws and antecedent conditions, not individual intentions.',
          C: 'Intelligible narrative without strict necessity = narrative causation (paragraph 4). The covering-law model claims events follow "necessarily."',
          D: 'Macro/micro distinction = pluralistic approach (paragraph 5). The covering-law model makes no such distinction.',
        },
        teachingPoint: 'Direct recall: covering-law model requirements: (1) antecedent conditions; (2) universal covering law; (3) logical necessity. The event follows necessarily from conditions + law. This is the positivist/Hempel model. Opposed by Dilthey (Verstehen) and narrative theorists.',
        relatedTopics: ['covering law model', 'antecedent conditions', 'universal law history', 'Hempel explanation'],
      },
    ],
  },
  {
    id: 'f5-cars-p3',
    sectionId: 'cars',
    passageNumber: 3,
    title: 'The Digital Attention Economy and Democratic Discourse',
    passageText: `The commercialization of online attention has produced an epistemic environment that many scholars argue is fundamentally hostile to the requirements of democratic deliberation. The attention economy — in which platforms compete for user engagement to sell advertising — creates powerful incentives to maximize outrage, novelty, and tribal affiliation rather than to promote reflection, accuracy, or cross-cutting dialogue.

The mechanism is straightforward: algorithmic recommendation systems optimize for engagement, and research consistently shows that emotionally provocative, identity-affirming content generates more engagement than nuanced, uncertain, or disconfirming content. This creates a feedback loop: users receive more content that confirms their existing views, become more confident in those views, and become less tolerant of alternative perspectives. The result — often called "filter bubbles" or "echo chambers" — is an epistemic fragmentation that many argue makes collective problem-solving more difficult.

Critics of the filter-bubble thesis argue that the evidence is more mixed than commonly assumed. Some studies find that most users' online feeds contain substantial cross-partisan content, and that exposure to opposing views sometimes increases rather than decreases polarization (the "backfire effect" — though the robustness of this effect has been questioned). The stronger claim — that social media causes democratic dysfunction — rests on weak causal evidence: correlation between social media use and polarization does not establish causation, and political polarization in many countries preceded social media.

A more defensible position may be that the attention economy creates selective conditions that amplify pre-existing human cognitive tendencies — confirmation bias, in-group favoritism, motivated reasoning — without being the root cause of polarization. On this view, interventions should target both platform design (reducing algorithmic amplification of outrage) and civic education (developing resilience to manipulation), rather than treating social media as the singular cause of democratic decline.`,
    questions: [
      {
        id: 'mcat5-cars-012',
        sectionId: 'cars',
        passageId: 'f5-cars-p3',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'easy',
        question: 'According to the passage, what is the primary mechanism by which the attention economy affects democratic deliberation?',
        choices: [
          { label: 'A', text: 'Direct censorship of opposing political views by platform administrators' },
          { label: 'B', text: 'Algorithmic amplification of emotionally engaging content creates feedback loops that reduce exposure to cross-cutting views' },
          { label: 'C', text: 'Users consciously choose to read only partisan content' },
          { label: 'D', text: 'Advertising revenue directly funds political misinformation campaigns' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 2: "algorithmic recommendation systems optimize for engagement...emotionally provocative, identity-affirming content generates more engagement...users receive more content that confirms their existing views...become less tolerant of alternative perspectives." This algorithmic feedback loop is the mechanism. B captures this precisely. A — direct censorship is not described. C — users are not described as consciously choosing; algorithmic systems shape what they see. D — advertising funding misinformation is not the mechanism described.',
        wrongAnswerExplanations: {
          A: 'The passage describes algorithmic filtering, not intentional censorship by administrators.',
          C: 'The passage emphasizes algorithmic curation — users are presented with content algorithmically, not purely by conscious choice.',
          D: 'The mechanism is engagement optimization (amplifying outrage/confirmation), not direct funding of misinformation.',
        },
        teachingPoint: 'Mechanism questions: trace the causal chain described. Here: attention economy → engagement optimization → algorithmically amplified outrage/confirmation → feedback loop → filter bubbles → epistemic fragmentation. B captures the key links.',
        relatedTopics: ['attention economy mechanism', 'algorithmic amplification', 'filter bubbles', 'CARS mechanism'],
      },
      {
        id: 'mcat5-cars-013',
        sectionId: 'cars',
        passageId: 'f5-cars-p3',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'The author mentions the "backfire effect" in paragraph 3 primarily to:',
        choices: [
          { label: 'A', text: 'Prove that cross-partisan exposure always increases polarization' },
          { label: 'B', text: 'Acknowledge counterevidence while noting its limitations, to present a nuanced view of the filter-bubble thesis' },
          { label: 'C', text: 'Support the claim that social media causes democratic dysfunction' },
          { label: 'D', text: 'Show that the attention economy has no effect on political discourse' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 3: the backfire effect is cited as a complication to the filter-bubble thesis — some exposure to opposing views increases polarization. However, the author immediately qualifies: "though the robustness of this effect has been questioned." This signals that the author is presenting a complex picture — critics of filter bubbles note the effect, but the effect itself is uncertain. B: the author uses the backfire effect to complicate the filter-bubble thesis while acknowledging the effect may be unreliable. A overstates ("always"). C contradicts — the backfire effect is cited as part of the CRITIQUE of the filter-bubble thesis. D overstates in the other direction.',
        wrongAnswerExplanations: {
          A: '"Always" is too absolute. The passage says exposure "sometimes increases" polarization — not always. And the robustness is questioned.',
          C: 'The backfire effect is cited in the paragraph CHALLENGING the filter-bubble thesis (critics of the thesis cite it). It does not support the thesis that social media causes dysfunction.',
          D: 'The backfire effect is one piece of evidence complicating the picture — not evidence that the attention economy has NO effect.',
        },
        teachingPoint: 'Citation purpose: ask WHY the author included this — what rhetorical function does it serve? Here: the backfire effect is part of the critique section (paragraph 3 = critics). It shows that exposure to opposing views can paradoxically increase polarization — complicating the filter-bubble thesis. But the author qualifies it (robustness questioned). B captures this nuanced function.',
        relatedTopics: ['backfire effect purpose', 'CARS evidence function', 'filter bubble critique', 'rhetorical purpose'],
      },
      {
        id: 'mcat5-cars-014',
        sectionId: 'cars',
        passageId: 'f5-cars-p3',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'The author\'s final position is BEST characterized as:',
        choices: [
          { label: 'A', text: 'Social media is the primary cause of political polarization and should be heavily regulated' },
          { label: 'B', text: 'The attention economy amplifies pre-existing cognitive tendencies; interventions should target both platform design and civic education' },
          { label: 'C', text: 'Filter bubbles do not exist and the evidence for epistemic fragmentation is entirely weak' },
          { label: 'D', text: 'Platform algorithms should be replaced with human editorial curation' },
        ],
        correctAnswer: 'B',
        explanation: 'Final paragraph: "the attention economy creates selective conditions that amplify pre-existing human cognitive tendencies...interventions should target both platform design...and civic education...rather than treating social media as the singular cause." B matches this nuanced position. A — the author explicitly says social media is NOT the singular cause; A overstates. C — the author does not deny filter bubbles; paragraph 1-2 grant the concern and only paragraph 3 complicates it. D — human editorial curation is not mentioned.',
        wrongAnswerExplanations: {
          A: 'The author explicitly argues AGAINST treating social media as "the singular cause." Regulation is not mentioned.',
          C: 'The author grants the concern about filter bubbles (paragraph 1-2), acknowledges mixed evidence (paragraph 3), then synthesizes. The author does not deny epistemic fragmentation.',
          D: 'Human editorial curation is not proposed in the passage. The interventions proposed are: reducing algorithmic outrage amplification AND civic education.',
        },
        teachingPoint: 'Final position synthesis: identify the nuanced conclusion. Here: (1) attention economy amplifies (does not create) cognitive tendencies; (2) dual intervention strategy. B captures both components. CARS passages often build to a nuanced conclusion in the final paragraph — read carefully for hedging language and the specific recommendation.',
        relatedTopics: ['author final position', 'dual intervention strategy', 'amplification not causation', 'CARS conclusion'],
      },
      {
        id: 'mcat5-cars-015',
        sectionId: 'cars',
        passageId: 'f5-cars-p3',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning beyond the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'A study finds that political polarization increased at similar rates in countries with low and high social media use. This finding would MOST directly:',
        choices: [
          { label: 'A', text: 'Strengthen the claim that the attention economy is the primary driver of polarization' },
          { label: 'B', text: 'Weaken the causal claim that social media causes polarization, supporting the critic\'s argument in paragraph 3' },
          { label: 'C', text: 'Confirm that filter bubbles are a universal phenomenon' },
          { label: 'D', text: 'Undermine the author\'s recommendation about platform design interventions' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 3: critics argue "political polarization in many countries preceded social media" and that correlation does not establish causation. A finding that polarization increased similarly in low and high social-media-use countries would directly challenge the causal claim — if social media caused polarization, higher social media use should correlate with more polarization. This confirms the critic\'s point. B is correct. A contradicts — this finding weakens the social media causation claim. C — filter bubbles are about epistemic fragmentation, not polarization rates across countries. D — the finding weakens the causation claim but does not necessarily undermine platform design interventions (which the author recommends as one part of a dual strategy, independent of whether social media is the singular cause).',
        wrongAnswerExplanations: {
          A: 'If polarization increased equally in low and high social-media-use countries, social media use does not predict polarization → weakens, not strengthens, the causation claim.',
          C: 'The finding is about polarization rates across countries with different social media use — not about the universality of filter bubbles.',
          D: 'The author recommends platform design interventions as part of a broader approach — even if social media is not the primary cause, reducing algorithmic outrage amplification could still be beneficial. The finding complicates causation but doesn\'t necessarily undermine targeted interventions.',
        },
        teachingPoint: 'Impact of new evidence: match the finding to the specific claim it challenges. "Polarization increased similarly regardless of social media use" → challenges the social media causation claim → supports the critics (paragraph 3). Know which paragraph/claim each piece of evidence targets.',
        relatedTopics: ['new evidence impact', 'causation correlation', 'social media polarization', 'CARS strengthen weaken'],
      },
    ],
  },
  {
    id: 'f5-cars-p4',
    sectionId: 'cars',
    passageNumber: 4,
    title: 'The Autonomy of Art',
    passageText: `The question of whether art is autonomous — whether it can be understood and evaluated independently of the social, political, and biographical circumstances of its production — has divided aestheticians since the Romantic period. The autonomy thesis holds that aesthetic value is intrinsic: the work of art contains within itself the resources for its own appreciation and evaluation. To properly understand a painting or a poem, one need only attend to the work itself — its formal properties, internal coherence, and achieved emotional effects — rather than to who painted it, when, or under what political conditions.

The autonomy thesis has intuitive appeal: great works of literature can be appreciated across centuries and cultures, suggesting that aesthetic value transcends its historical occasion. It also supports the practice of formalism — close reading of textual or visual properties without recourse to contextual information — which has been an extraordinarily productive critical methodology.

Critics of autonomy argue that the very concept of the "work itself" is an ideological construction. The formal properties of a work are not neutral facts but historically conditioned perceptions shaped by conventions, institutions, and interpretive traditions. To understand Beethoven's Ninth Symphony purely in terms of its musical structure is to suppress its complex social reception history, including its use by both revolutionary and totalitarian political movements. Art, on this view, is constitutively social — it cannot be stripped of its context without distortion.

A middle position suggests that these perspectives are not exclusive. Works of art may be understood at multiple levels simultaneously: as formal constructions amenable to immanent analysis and as social documents that bear the traces of their historical production. The art-historical method combines formal analysis with contextual research precisely because neither approach alone gives a complete picture. The question is not whether context matters but how much weight it should receive in specific interpretive decisions.`,
    questions: [
      {
        id: 'mcat5-cars-016',
        sectionId: 'cars',
        passageId: 'f5-cars-p4',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'easy',
        question: 'The passage presents Beethoven\'s Ninth Symphony primarily as:',
        choices: [
          { label: 'A', text: 'An example of a work whose musical structure alone conveys its full significance' },
          { label: 'B', text: 'An example of how a work\'s social reception history cannot be separated from understanding it' },
          { label: 'C', text: 'Evidence that the autonomy thesis is correct' },
          { label: 'D', text: 'A work whose value is diminished by its use for political purposes' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 3: "To understand Beethoven\'s Ninth Symphony purely in terms of its musical structure is to suppress its complex social reception history, including its use by both revolutionary and totalitarian political movements." The example supports the critic\'s argument — context (reception history) is essential to full understanding. B is correct. A is the autonomy thesis view being critiqued. C contradicts — the example is used against the autonomy thesis. D — the passage doesn\'t claim the value is "diminished."',
        wrongAnswerExplanations: {
          A: 'The passage argues the OPPOSITE — that musical structure alone suppresses the social reception history. The example is used to challenge the autonomy thesis.',
          C: 'The Beethoven example is used by CRITICS of autonomy — it argues that social context cannot be stripped away without distortion.',
          D: 'The passage doesn\'t say the Ninth\'s value is diminished by political use — it says that ignoring that political use means suppressing part of its history.',
        },
        teachingPoint: 'Identify the rhetorical purpose of examples. Beethoven = support for the CONTEXTUAL (anti-autonomy) argument in paragraph 3. The example shows that reception history (revolutionary and totalitarian political use) is part of understanding the work.',
        relatedTopics: ['Beethoven Ninth example', 'CARS example purpose', 'contextual history', 'autonomy critique'],
      },
      {
        id: 'mcat5-cars-017',
        sectionId: 'cars',
        passageId: 'f5-cars-p4',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'The author\'s view about autonomy and context is BEST described as:',
        choices: [
          { label: 'A', text: 'Context is irrelevant; formalism is the only valid critical methodology' },
          { label: 'B', text: 'Context determines everything; formal properties are ideological constructions with no independent validity' },
          { label: 'C', text: 'Both formal analysis and contextual research are necessary; neither alone gives a complete picture' },
          { label: 'D', text: 'The autonomy thesis should be fully abandoned in favor of social criticism' },
        ],
        correctAnswer: 'C',
        explanation: 'Final paragraph: "Works of art may be understood at multiple levels simultaneously...The art-historical method combines formal analysis with contextual research precisely because neither approach alone gives a complete picture." C matches. A = strict formalism; B = strict contextualism; D = abandoning autonomy entirely. The author advocates a pluralistic middle position.',
        wrongAnswerExplanations: {
          A: 'The author explicitly grants context a role: "The question is not whether context matters but how much weight it should receive."',
          B: 'Paragraph 3 presents this as the critics\' view. The final paragraph synthesizes — formal analysis remains valid.',
          D: 'The author defends formal analysis as productive (paragraph 2) and includes it in the final synthesis. Fully abandoning autonomy is not the position.',
        },
        teachingPoint: 'Author synthesis: always read the final paragraph carefully. Here: formal + contextual = both necessary. The synthesis acknowledges the validity of both positions while avoiding the extremes.',
        relatedTopics: ['formal contextual synthesis', 'author synthesis CARS', 'middle position art', 'neither alone sufficient'],
      },
      {
        id: 'mcat5-cars-018',
        sectionId: 'cars',
        passageId: 'f5-cars-p4',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'Which of the following is offered as evidence FOR the autonomy thesis?',
        choices: [
          { label: 'A', text: 'The social reception history of Beethoven\'s Ninth Symphony' },
          { label: 'B', text: 'The fact that great works of literature can be appreciated across centuries and cultures' },
          { label: 'C', text: 'The argument that formal properties are historically conditioned perceptions' },
          { label: 'D', text: 'The use of art by both revolutionary and totalitarian political movements' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 2: "great works of literature can be appreciated across centuries and cultures, suggesting that aesthetic value transcends its historical occasion." This is offered as evidence supporting the autonomy thesis — if a work can be appreciated without knowing its historical context, its aesthetic value must be intrinsic. B is correct. A and D = evidence used AGAINST autonomy (Beethoven reception history). C = the critics\' argument against autonomy.',
        wrongAnswerExplanations: {
          A: 'Beethoven\'s reception history is used in paragraph 3 to argue AGAINST the autonomy thesis (showing that context matters).',
          C: '"Historically conditioned perceptions" is the critics\' argument challenging the neutrality of formal properties — used AGAINST autonomy.',
          D: 'Art used by political movements = evidence that art cannot be understood outside social context — AGAINST autonomy.',
        },
        teachingPoint: 'Track which evidence belongs to which position. Pro-autonomy evidence: cross-cultural, cross-century appreciation of great works (aesthetics transcend historical occasion). Anti-autonomy evidence: Beethoven reception history, political use, formal properties as historically conditioned.',
        relatedTopics: ['autonomy evidence', 'cross-cultural appreciation', 'CARS evidence for thesis', 'aesthetic value transcends'],
      },
      {
        id: 'mcat5-cars-019',
        sectionId: 'cars',
        passageId: 'f5-cars-p4',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning beyond the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'A literary scholar argues that knowing an author\'s biographical trauma fundamentally changes the meaning of their novel. The author of the passage would MOST likely respond that:',
        choices: [
          { label: 'A', text: 'Biographical context is irrelevant; the novel must be read on its own formal terms' },
          { label: 'B', text: 'Biographical context provides one layer of understanding but does not exhaust the work\'s meaning; formal analysis remains necessary' },
          { label: 'C', text: 'Biographical information always distorts interpretation and should be excluded' },
          { label: 'D', text: 'The literary scholar\'s approach proves the autonomy thesis is correct' },
        ],
        correctAnswer: 'B',
        explanation: 'The author\'s position (final paragraph): works can be understood at multiple levels simultaneously — formal analysis AND contextual research both contribute; "neither approach alone gives a complete picture." The author would not dismiss biographical context (A) nor endorse it as the only valid approach. B: biographical context = one layer (contextual), but formal analysis remains necessary — consistent with the pluralistic synthesis. C overstates (biographical information "always distorts" — not the author\'s view). D is the opposite of the scholar\'s position (the scholar emphasizes biography, not formal autonomy).',
        wrongAnswerExplanations: {
          A: 'The author explicitly recognizes context (including presumably biographical context) as one layer of understanding. Dismissal is not the pluralistic position.',
          C: '"Always distorts" is too absolute and represents an extreme autonomy view. The author endorses using both formal and contextual approaches.',
          D: 'Arguing that biographical context "fundamentally changes meaning" supports the contextual (anti-autonomy) position, not the autonomy thesis.',
        },
        teachingPoint: 'Apply author\'s position to new scenario: the author\'s pluralism says both formal and contextual analysis are valuable. Biographical trauma = contextual layer. Author\'s response: this contributes one layer of understanding; formal analysis still needed. B fits the pluralistic synthesis without rejecting either approach.',
        relatedTopics: ['biographical context', 'author pluralism application', 'CARS apply position', 'multiple layers interpretation'],
      },
      {
        id: 'mcat5-cars-020',
        sectionId: 'cars',
        passageId: 'f5-cars-p4',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'The phrase "ideological construction" (paragraph 3) is used by critics to argue that:',
        choices: [
          { label: 'A', text: 'Works of art deliberately promote political ideologies' },
          { label: 'B', text: 'The concept of the "work itself" as a neutral formal object is not truly neutral but shaped by historical conventions and institutions' },
          { label: 'C', text: 'Formalism is a useful methodology but must be supplemented with political theory' },
          { label: 'D', text: 'All art is propaganda for the ruling class' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 3: "the very concept of the \'work itself\' is an ideological construction. The formal properties of a work are not neutral facts but historically conditioned perceptions shaped by conventions, institutions, and interpretive traditions." The critics use "ideological construction" to undermine the claim that formal analysis is neutral — what we perceive as intrinsic formal properties are actually shaped by history. B is correct. A — "deliberately promote" overstates. C — the critics go further than supplementation; they challenge the neutrality claim. D — Marxist reductionism; not what the passage states.',
        wrongAnswerExplanations: {
          A: 'The passage does not say art deliberately promotes ideology. The critics argue that our perception of formal properties is historically conditioned — a more subtle epistemological claim.',
          C: 'The critics are making a stronger claim — formal properties are not neutral at all, not just that formalism needs supplementation.',
          D: 'Ruling class propaganda is a crude Marxist reduction not supported by the passage text. The critics make a more subtle epistemological argument about historically conditioned perceptions.',
        },
        teachingPoint: 'Vocabulary in critical context: "ideological construction" = the claim that something presented as natural/neutral is actually historically produced and shaped by power. The critics use it to argue that formal analysis itself is not neutral. B captures this epistemological critique precisely.',
        relatedTopics: ['ideological construction', 'formal properties critique', 'neutral perception claim', 'CARS critical vocabulary'],
      },
    ],
  },
  {
    id: 'f5-cars-p5',
    sectionId: 'cars',
    passageNumber: 5,
    title: 'Moral Luck and Responsibility',
    passageText: `Thomas Nagel's influential essay on moral luck identifies a deep tension within ordinary moral practice. We standardly hold people responsible only for what is within their control — this is the control principle, or what Nagel calls the Kantian intuition. Yet our actual moral judgments routinely depend on factors that are entirely outside the agent's control. Nagel identifies four types of moral luck: resultant luck (e.g., whether a drunk driver hits a pedestrian); circumstantial luck (whether one is born in a time and place that makes moral transgression possible or tempting); constitutive luck (the dispositions, temperament, and character traits one is born with or develops through unchosen circumstances); and causal luck (whether one's choices are causally determined by prior causes).

The problem is that once we take the control principle seriously, the domain of moral responsibility appears to shrink dramatically. If what one does is substantially influenced by genetic endowments, early childhood experiences, and social circumstances — none of which are chosen — then it becomes unclear how much of one's character and conduct is genuinely "one's own."

Nagel does not resolve this tension but argues that it reflects a genuine antinomy in our moral thinking — the simultaneous pull of two incompatible attitudes: the objective view (from outside, which undermines responsibility) and the subjective view (from inside one's own agency, which sustains it). Compatibilists argue that the problem is avoidable: freedom and responsibility require only that behavior issue from the agent's own desires and deliberations, regardless of whether those desires were themselves caused by prior factors. If I act in accordance with my reflective values, I am responsible — even if those values were shaped by factors I did not choose.

Martha Nussbaum takes a different approach: instead of resolving the control problem, she argues for greater compassion toward wrongdoers, recognizing that their transgressions may be substantially explained by unchosen circumstances. Punishment, on this view, should acknowledge the role of luck in producing moral failure.`,
    questions: [
      {
        id: 'mcat5-cars-021',
        sectionId: 'cars',
        passageId: 'f5-cars-p5',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'The "control principle" as described in the passage holds that:',
        choices: [
          { label: 'A', text: 'Agents should be held responsible for all outcomes they cause, whether or not the outcomes were foreseeable' },
          { label: 'B', text: 'Moral responsibility extends only to what is genuinely within the agent\'s control' },
          { label: 'C', text: 'Character and moral disposition are entirely within the agent\'s control' },
          { label: 'D', text: 'Luck has no role in moral life because all outcomes can be controlled with sufficient effort' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 1: "We standardly hold people responsible only for what is within their control — this is the control principle." B matches. A says "all outcomes" regardless of control — opposite of the control principle. C is not stated — the passage raises constitutive luck (character is partly unchosen) as a PROBLEM for the control principle. D denies luck — the opposite of Nagel\'s argument.',
        wrongAnswerExplanations: {
          A: 'The control principle restricts responsibility to what is WITHIN control. "All outcomes caused" regardless of control is actually the critique that the control principle would oppose.',
          C: 'If character were entirely within control, there would be no constitutive luck problem. The control principle does not claim character is fully controllable — this is the tension Nagel identifies.',
          D: 'Nagel\'s argument shows luck IS pervasive in moral life. "No luck" would contradict the entire passage premise.',
        },
        teachingPoint: 'Direct definition recall: control principle = responsibility limited to what is within the agent\'s control. The tension: most moral judgments VIOLATE this principle by depending on luck. B is the direct statement from the passage.',
        relatedTopics: ['control principle', 'moral responsibility', 'Nagel moral luck', 'Kantian intuition'],
      },
      {
        id: 'mcat5-cars-022',
        sectionId: 'cars',
        passageId: 'f5-cars-p5',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'The compatibilist response to moral luck (paragraph 3) holds that responsibility requires:',
        choices: [
          { label: 'A', text: 'That the agent\'s choices are uncaused by prior factors (libertarian free will)' },
          { label: 'B', text: 'That behavior issue from the agent\'s own desires and deliberations, regardless of whether those desires were themselves caused' },
          { label: 'C', text: 'That agents fully control the formation of their own values' },
          { label: 'D', text: 'That luck be eliminated before assigning responsibility' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 3: "Compatibilists argue that the problem is avoidable: freedom and responsibility require only that behavior issue from the agent\'s own desires and deliberations, regardless of whether those desires were themselves caused by prior factors." B is a direct match. A — libertarian free will (uncaused causes) is what compatibilism denies needing. C — compatibilism does not require full control over value formation. D — compatibilists say luck is compatible with responsibility (hence the name).',
        wrongAnswerExplanations: {
          A: 'Libertarian free will requires uncaused choices. Compatibilism is distinguished by REJECTING this requirement — responsibility and determinism are compatible.',
          C: 'Compatibilism does not require full control over value formation — it says acting in accordance with your own values (however formed) is sufficient for responsibility.',
          D: 'Compatibilists argue that luck does NOT need to be eliminated — their position is that freedom is compatible with causal determination, so luck (causal factors) does not undermine responsibility.',
        },
        teachingPoint: 'Compatibilism: freedom = acting from your own desires and deliberations; does not require those desires to be uncaused. Key contrast: libertarianism (requires uncaused free will); compatibilism (requires only that action flows from agent\'s own reflective values, even if causally determined). "Hard incompatibilism" (opposite): determination + luck → no responsibility.',
        relatedTopics: ['compatibilism', 'freedom causal determinism', 'agent desires deliberation', 'libertarian free will contrast'],
      },
      {
        id: 'mcat5-cars-023',
        sectionId: 'cars',
        passageId: 'f5-cars-p5',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'hard',
        question: 'Nagel describes the tension between the objective and subjective views as a "genuine antinomy." In context, this most likely means:',
        choices: [
          { label: 'A', text: 'The tension can be fully resolved by adopting the objective view' },
          { label: 'B', text: 'Both views can be reconciled through a synthesis that eliminates the tension' },
          { label: 'C', text: 'The tension reflects an irresolvable contradiction within moral thinking itself — both views have force but cannot be simultaneously maintained' },
          { label: 'D', text: 'The tension is merely apparent and dissolves on closer analysis' },
        ],
        correctAnswer: 'C',
        explanation: 'Paragraph 3: "Nagel does not resolve this tension but argues that it reflects a genuine antinomy in our moral thinking — the simultaneous pull of two incompatible attitudes." "Antinomy" = an irresolvable contradiction (philosophical term: two valid arguments leading to opposite conclusions). "Genuine" = Nagel believes it is real, not merely apparent. C captures: irresolvable contradiction, both views have force, cannot be simultaneously maintained. A — Nagel does not resolve it (rejects the objective view entirely). B — Nagel does not offer a synthesis. D — Nagel insists it is "genuine" (real, not merely apparent).',
        wrongAnswerExplanations: {
          A: 'Nagel "does not resolve this tension" — he does not adopt the objective view to resolve it. The antinomy persists.',
          B: 'A synthesis that eliminates tension would mean Nagel resolved the problem. The passage states he does not resolve it.',
          D: '"Genuine antinomy" means Nagel believes the contradiction is real — not merely apparent. "Does not resolve" = the tension persists on closer analysis.',
        },
        teachingPoint: 'Vocabulary: antinomy = irresolvable contradiction between two valid propositions. Kant used it for cosmological antinomies (the world has a beginning vs. the world has no beginning — both valid arguments). Nagel borrows this framework: control principle (moral intuition) vs. luck (empirical fact) = genuine antinomy, not resolvable by better analysis.',
        relatedTopics: ['antinomy definition', 'irresolvable contradiction', 'Nagel objective subjective', 'philosophical tension'],
      },
      {
        id: 'mcat5-cars-024',
        sectionId: 'cars',
        passageId: 'f5-cars-p5',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning beyond the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'A judge says: "Even though this defendant grew up in poverty and experienced severe childhood abuse, I must hold them fully responsible for their crime." This judge is MOST closely aligned with which position?',
        choices: [
          { label: 'A', text: 'Nussbaum\'s view that compassion for unchosen circumstances should modify punishment' },
          { label: 'B', text: 'Nagel\'s antinomy — recognizing both the objective and subjective pull' },
          { label: 'C', text: 'A strict application of the control principle, holding responsibility even though constitutive and circumstantial luck shaped the defendant' },
          { label: 'D', text: 'Compatibilism — the defendant\'s desires flowed from their own deliberation' },
        ],
        correctAnswer: 'C',
        explanation: 'The judge holds the defendant "fully responsible" despite acknowledging unchosen circumstances (poverty, abuse). This treats the full weight of moral responsibility as maintained regardless of circumstantial and constitutive luck — a strong application of the control principle in one direction. However, it is inconsistent WITH the control principle strictly applied (which would reduce responsibility when control is lacking) — actually this is more like holding responsibility against the control principle. More precisely: the judge acknowledges unchosen circumstances but proceeds with full responsibility = prioritizing the subjective/practice of holding accountable over the objective view. But the closest match is C — the judge is applying a standard that ignores luck in assigning responsibility. A — Nussbaum would urge compassion; this judge does not. B — Nagel recognizes the tension but does not resolve it; the judge resolves it by assigning full responsibility. D — compatibilism would agree with responsibility if the action flowed from the defendant\'s desires, but the question does not address that; C more directly characterizes the position.',
        wrongAnswerExplanations: {
          A: 'Nussbaum argues for GREATER COMPASSION toward wrongdoers due to unchosen circumstances. This judge explicitly holds the defendant "fully responsible" despite those circumstances — the opposite of Nussbaum\'s prescription.',
          B: 'Nagel\'s antinomy acknowledges BOTH pulls simultaneously without resolving the tension. The judge resolves it by assigning full responsibility — this is one resolution, not the antinomy itself.',
          D: 'Compatibilism holds that responsibility requires actions flowing from the agent\'s own desires and deliberations. The judge\'s statement does not address the source of the defendant\'s desires — it addresses unchosen circumstances (poverty, abuse). The better match is C.',
        },
        teachingPoint: 'Apply abstract positions to concrete cases: the judge acknowledges circumstantial and constitutive luck (poverty, abuse) but assigns full responsibility anyway = ignoring luck in favor of the practice of holding accountable. This most closely resembles strict responsibility assignment despite luck — C. Nussbaum = modify punishment; Nagel = acknowledge the tension; Compatibilist = focus on whether action flowed from own deliberation.',
        relatedTopics: ['moral luck application', 'full responsibility circumstance', 'Nussbaum compassion contrast', 'CARS apply philosophy'],
      },
      {
        id: 'mcat5-cars-025',
        sectionId: 'cars',
        passageId: 'f5-cars-p5',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'easy',
        question: 'Which type of moral luck does the case of a drunk driver who does NOT hit anyone (while another drunk driver does) BEST illustrate?',
        choices: [
          { label: 'A', text: 'Constitutive luck — the driver\'s temperament disposes them toward risk-taking' },
          { label: 'B', text: 'Circumstantial luck — the driver happened to be in a situation where risk-taking was possible' },
          { label: 'C', text: 'Resultant luck — the outcome (whether anyone was hit) was outside the driver\'s control' },
          { label: 'D', text: 'Causal luck — the driver\'s choice to drink and drive was determined by prior causes' },
        ],
        correctAnswer: 'C',
        explanation: 'Paragraph 1: "resultant luck (e.g., whether a drunk driver hits a pedestrian)." The drunk driver example is the exact illustration given for resultant luck — the outcome (whether someone was hit) was not in the driver\'s control; both drivers made the same decision (drink and drive) but got different moral outcomes. C is correct. A = constitutive luck = traits/temperament. B = circumstantial luck = the situation one is in. D = causal luck = whether choices are causally determined.',
        wrongAnswerExplanations: {
          A: 'Constitutive luck = the character traits and dispositions one is born with or develops through unchosen circumstances. The drunk driver example is specifically about outcomes (resultant), not traits.',
          B: 'Circumstantial luck = being in a situation that makes transgression possible or tempting. The drunk driver case involves the same situation for both drivers — the difference is in the outcome (whether someone happened to be crossing).',
          D: 'Causal luck = whether the agent\'s choices themselves are causally determined. The drunk driver example illustrates the outcome being out of control, not the choice being causally determined.',
        },
        teachingPoint: 'Four types of moral luck: Resultant: outcome is out of control (same action → different results due to luck). Circumstantial: the situation you\'re placed in. Constitutive: the character/disposition you have. Causal: whether your choices are causally determined. The passage uses "whether a drunk driver hits a pedestrian" as the paradigm example of resultant luck.',
        relatedTopics: ['resultant luck', 'moral luck types', 'drunk driver example', 'outcome control'],
      },
      {
        id: 'mcat5-cars-026',
        sectionId: 'cars',
        passageId: 'f5-cars-p5',
        questionType: 'passage',
        discipline: 'CARS',
        contentCategory: 'Reasoning within the text',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'Nussbaum\'s approach to moral luck differs from the compatibilist approach primarily in that:',
        choices: [
          { label: 'A', text: 'Nussbaum denies that luck plays any role in moral failure' },
          { label: 'B', text: 'Nussbaum focuses on modifying punishment to reflect unchosen circumstances; compatibilists argue that acting from one\'s own values is sufficient for full responsibility' },
          { label: 'C', text: 'Nussbaum endorses the control principle while compatibilists reject it' },
          { label: 'D', text: 'Both positions are identical — both argue that luck undermines all moral responsibility' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 3: compatibilists say responsibility requires only behavior issuing from the agent\'s own desires — "even if those values were shaped by factors I did not choose" → full responsibility maintained. Paragraph 4: Nussbaum argues "greater compassion toward wrongdoers, recognizing that their transgressions may be substantially explained by unchosen circumstances. Punishment...should acknowledge the role of luck." Nussbaum modifies punishment; compatibilists argue for full responsibility given internal deliberation. B captures this distinction. A contradicts Nussbaum (she acknowledges luck extensively). C — Nussbaum does not endorse the control principle strictly; she acknowledges luck\'s role. D — they are different (compatibilists maintain full responsibility; Nussbaum modifies punishment).',
        wrongAnswerExplanations: {
          A: 'Nussbaum explicitly acknowledges luck (unchosen circumstances) and argues for compassion BECAUSE of luck\'s role. She does not deny luck.',
          C: 'Neither Nussbaum nor compatibilists strictly endorse the control principle as stated. Compatibilists sidestep it by redefining freedom; Nussbaum addresses it through compassion rather than endorsing strict control-based responsibility.',
          D: 'Compatibilists maintain that one can be responsible even when choices are causally shaped by prior factors — they do not argue luck undermines all responsibility.',
        },
        teachingPoint: 'Compare positions: Compatibilist = full responsibility if action from own desires (prior shaping doesn\'t undermine responsibility). Nussbaum = acknowledge luck → modify punishment. Key difference: compatibilists maintain responsibility; Nussbaum acknowledges luck and adjusts the RESPONSE (compassion/modified punishment) without fully resolving the metaphysical question.',
        relatedTopics: ['Nussbaum vs compatibilism', 'modified punishment luck', 'unchosen circumstances compassion', 'responsibility comparison'],
      },
    ],
  },
]
