import type { MCATPassage } from '../types'

// Form 5 P/S — Passages 6–9 (IDs mcat5-ps-027 through mcat5-ps-051)

export const psPassages5_06to09: MCATPassage[] = [
  {
    id: 'f5-ps-p6',
    sectionId: 'psych-soc',
    passageNumber: 6,
    title: 'Psychological Disorders: Mood and Anxiety',
    text: `Mood disorders are characterized by disturbances in mood as the primary feature. Major depressive disorder (MDD) requires at least two weeks of depressed mood or loss of interest, plus at least four additional symptoms (sleep disturbance, appetite change, psychomotor changes, fatigue, concentration difficulties, feelings of worthlessness or guilt, and recurrent thoughts of death or suicidality). Dysthymia (persistent depressive disorder) involves chronic low-grade depression lasting at least two years. Bipolar I disorder requires at least one manic episode (elevated or expansive mood, decreased need for sleep, grandiosity, pressured speech, flight of ideas, distractibility, increased goal-directed activity, and risky behavior for ≥7 days or any duration if hospitalized); depressive episodes commonly occur but are not required for diagnosis.

The monoamine hypothesis of depression proposes that MDD results from insufficient activity of serotonin, norepinephrine, and dopamine. This hypothesis supports the use of SSRIs (selective serotonin reuptake inhibitors), SNRIs (serotonin-norepinephrine reuptake inhibitors), and MAOIs (monoamine oxidase inhibitors) in treatment. However, the hypothesis is incomplete: antidepressants raise monoamine levels within hours but therapeutic effects take weeks, suggesting downstream neuroplasticity mechanisms (BDNF, neurogenesis) are the actual therapeutic drivers.

Anxiety disorders share excessive fear or anxiety as a central feature. Generalized anxiety disorder (GAD) involves chronic, uncontrollable worry about multiple domains. Panic disorder features recurrent unexpected panic attacks — sudden surges of intense fear peaking within minutes — with at least one attack followed by persistent concern about future attacks or avoidance behavior. Specific phobia is intense, irrational fear of a specific object or situation triggering immediate anxiety.

Cognitive-behavioral therapy (CBT) is first-line for anxiety disorders: cognitive restructuring addresses maladaptive beliefs; exposure and response prevention (ERP) involves graduated exposure to feared stimuli while preventing avoidance responses.`,
    questions: [
      {
        id: 'mcat5-ps-027',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p6',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'PSYCH: 7B',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 2',
        difficulty: 'easy',
        question: 'A patient presents with elevated mood, decreased need for sleep, grandiosity, and racing thoughts for 10 days. He has never had such an episode before and has no prior psychiatric history. The MOST likely diagnosis is:',
        choices: [
          { label: 'A', text: 'Major depressive disorder — depressed mood is present along with sleep disturbance' },
          { label: 'B', text: 'Bipolar I disorder — a manic episode lasting ≥7 days meets the diagnostic threshold' },
          { label: 'C', text: 'Generalized anxiety disorder — chronic worry is present' },
          { label: 'D', text: 'Panic disorder — recurrent unexpected panic attacks with anticipatory anxiety' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 1: "Bipolar I disorder requires at least one manic episode (elevated or expansive mood, decreased need for sleep, grandiosity, pressured speech, flight of ideas...for ≥7 days or any duration if hospitalized)." The patient has 10 days of manic symptoms — clearly meets the duration criterion. Bipolar I requires at least ONE manic episode; depressive episodes are not required for diagnosis ("depressive episodes commonly occur but are not required"). B is correct. A — MDD requires depressed mood or anhedonia as the primary feature; this patient has ELEVATED mood (mania). C — GAD = chronic uncontrollable worry; not the picture here. D — panic disorder = recurrent panic attacks; not described here.',
        wrongAnswerExplanations: {
          A: 'MDD features depressed mood, anhedonia, and associated vegetative symptoms. The patient has the opposite: ELEVATED mood, decreased sleep need (manic feature, not depressive), grandiosity. MDD does not explain this presentation.',
          C: 'GAD = excessive, uncontrollable worry about multiple domains. The patient has manic symptoms (elevated mood, grandiosity, decreased sleep need), not anxiety/worry.',
          D: 'Panic disorder = recurrent unexpected panic attacks (surges of intense fear, peaking within minutes). Manic symptoms lasting 10 days continuously is not a panic attack pattern.',
        },
        teachingPoint: 'Bipolar I vs. Bipolar II: Bipolar I requires ≥1 full manic episode (≥7 days, or any duration if hospitalized or requires antipsychotic). Bipolar II requires ≥1 hypomanic episode (≥4 days, less severe, no hospitalization/psychosis) AND ≥1 MDD episode. Manic symptoms: DIG FAST — Distractibility, Impulsivity/risky behavior, Grandiosity, Flight of ideas, Activity increase, Sleep need decreased, Talkativeness/pressured speech.',
        relatedTopics: ['bipolar I disorder manic episode', 'manic episode criteria', 'bipolar I vs II', 'mood disorder diagnosis'],
      },
      {
        id: 'mcat5-ps-028',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p6',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'PSYCH: 7B',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'Antidepressants raise monoamine levels within hours but therapeutic effects take weeks. The passage suggests this discrepancy implies:',
        choices: [
          { label: 'A', text: 'Antidepressants do not actually raise monoamine levels — the premise of the monoamine hypothesis is wrong' },
          { label: 'B', text: 'The actual therapeutic mechanism involves downstream adaptations such as increased BDNF and neurogenesis, not just immediate monoamine elevation' },
          { label: 'C', text: 'Patients with depression have normal monoamine levels and are misdiagnosed' },
          { label: 'D', text: 'SSRIs work faster than MAOIs because they are more selective' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 2: "However, the hypothesis is incomplete: antidepressants raise monoamine levels within hours but therapeutic effects take weeks, suggesting downstream neuroplasticity mechanisms (BDNF, neurogenesis) are the actual therapeutic drivers." The time lag suggests that monoamine elevation is an upstream trigger but the actual therapeutic effect requires time-dependent processes — neuroplasticity (BDNF-mediated synaptic changes, hippocampal neurogenesis). B matches. A — the passage does not say monoamines are not elevated; it says this alone doesn\'t explain the time lag. C — the passage doesn\'t say patients are misdiagnosed. D — SSRI vs. MAOI speed comparison is not in the passage.',
        wrongAnswerExplanations: {
          A: 'The passage says monoamine levels ARE elevated quickly by antidepressants. The problem is that clinical improvement takes WEEKS despite this rapid monoamine increase — suggesting the monoamine elevation is necessary but not sufficient.',
          C: 'The passage is about a mechanistic discrepancy in how antidepressants work, not a claim that depression patients have normal monoamines. The monoamine hypothesis is about insufficient monoamine activity.',
          D: 'SSRI vs. MAOI comparison is not made in the passage. The passage addresses the general time lag across antidepressant classes, not a comparison between them.',
        },
        teachingPoint: 'Monoamine hypothesis limitations: (1) Time lag (hours vs. weeks) suggests monoamines trigger but don\'t directly mediate the antidepressant effect. (2) Current evidence: BDNF (brain-derived neurotrophic factor) increases with antidepressant treatment → synaptic plasticity → hippocampal neurogenesis. (3) New mechanism: ketamine (NMDA antagonist) works within hours — supports glutamate system involvement. Depression = complex, not simply "low serotonin."',
        relatedTopics: ['monoamine hypothesis limitation', 'antidepressant time lag', 'BDNF neurogenesis depression', 'monoamine hypothesis incomplete'],
      },
      {
        id: 'mcat5-ps-029',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p6',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'PSYCH: 7B',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'A patient with panic disorder avoids crowded spaces because she fears having a panic attack there. According to the passage, CBT would address this avoidance behavior using:',
        choices: [
          { label: 'A', text: 'Cognitive restructuring alone — addressing the maladaptive belief that crowded spaces are dangerous' },
          { label: 'B', text: 'Systematic desensitization — pairing crowded spaces with deep relaxation to counteract anxiety' },
          { label: 'C', text: 'Exposure and response prevention — graduated exposure to crowded spaces while preventing the avoidance response' },
          { label: 'D', text: 'Pharmacotherapy with benzodiazepines to reduce anxiety in crowded spaces' },
        ],
        correctAnswer: 'C',
        explanation: 'Paragraph 4: "exposure and response prevention (ERP) involves graduated exposure to feared stimuli while preventing avoidance responses." Crowded spaces = feared stimulus. Avoiding them = avoidance response. ERP: gradually expose the patient to crowded spaces (graduated) while preventing the avoidance (preventing escape/avoidance behavior). C matches. A — cognitive restructuring addresses beliefs but not avoidance directly; the passage says ERP specifically addresses avoidance. B — systematic desensitization pairs the stimulus with relaxation (classic behavioral therapy); the passage specifically mentions "exposure and response prevention" as the CBT technique. D — pharmacotherapy is not CBT.',
        wrongAnswerExplanations: {
          A: 'Cognitive restructuring is the cognitive component of CBT (challenging maladaptive thoughts). ERP is the behavioral component specifically targeting avoidance. The passage pairs both techniques as components of CBT; for avoidance specifically, ERP is the targeted intervention.',
          B: 'Systematic desensitization (Wolpe): stimulus hierarchy + paired relaxation. This is a behavioral technique but the passage specifically names ERP as the CBT technique for anxiety. ERP does not require paired relaxation — exposure is done without using relaxation to prevent safety behaviors.',
          D: 'Benzodiazepines are pharmacological (not CBT). While they may be used adjunctively, the passage identifies CBT — specifically ERP — as the first-line approach for anxiety disorders.',
        },
        teachingPoint: 'CBT for anxiety: Cognitive component (restructuring maladaptive beliefs) + Behavioral component (ERP: graduated exposure + no avoidance). Exposure disrupts the avoidance cycle: anxiety → avoidance → short-term relief → reinforces avoidance. ERP breaks this: prolonged exposure → anxiety peaks then naturally habituates → avoidance response not performed → belief that anxiety is tolerable and manageable develops. Gold-standard for phobias, panic disorder, OCD.',
        relatedTopics: ['exposure response prevention CBT', 'CBT anxiety disorders', 'avoidance behavior ERP', 'graduated exposure anxiety'],
      },
      {
        id: 'mcat5-ps-030',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p6',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'PSYCH: 7B',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 2',
        difficulty: 'easy',
        question: 'SSRIs, SNRIs, and MAOIs all target the monoamine system. Which type of monoamine does an SSRI specifically prevent from being removed from the synapse?',
        choices: [
          { label: 'A', text: 'Norepinephrine — by blocking the norepinephrine transporter' },
          { label: 'B', text: 'Serotonin — by blocking the serotonin reuptake transporter (SERT)' },
          { label: 'C', text: 'Dopamine — by blocking the dopamine transporter (DAT)' },
          { label: 'D', text: 'GABA — by enhancing GABA-A receptor activity' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 2: "SSRIs (selective serotonin reuptake inhibitors)." The name specifies: selective (specific to serotonin), serotonin (the monoamine), reuptake inhibitor (blocks the transporter that removes serotonin from the synapse). SSRIs block SERT → serotonin stays in the synapse longer → more serotonergic activity. B is correct. A — norepinephrine transporter blockade = SNRIs (also block SERT) and NRIs. C — DAT blockade = cocaine and amphetamines (and some SNRIs at higher doses). D — GABA enhancement = benzodiazepines (not monoamine, not SSRI mechanism).',
        wrongAnswerExplanations: {
          A: 'Norepinephrine reuptake inhibition = SNRIs (and specifically NRIs). SSRIs are SELECTIVE for serotonin — they have minimal effect on the norepinephrine transporter at therapeutic doses.',
          C: 'Dopamine transporter blockade = cocaine (and to some extent amphetamines). SSRIs are selective for SERT (serotonin transporter). While SSRIs can have small effects on dopamine at high doses, the defining mechanism is serotonin reuptake inhibition.',
          D: 'GABA is not a monoamine — it is an amino acid neurotransmitter. GABA-A enhancement is the mechanism of benzodiazepines, not antidepressants.',
        },
        teachingPoint: 'Monoamine neurotransmitter reuptake: each monoamine has a specific transporter — SERT (serotonin), NET (norepinephrine), DAT (dopamine). SSRIs block SERT → ↑synaptic serotonin. SNRIs block SERT + NET → ↑serotonin + ↑norepinephrine. MAOIs block monoamine oxidase → ↓breakdown of all three monoamines. Cocaine blocks all three transporters (SERT, NET, DAT). SSRI selectivity: fluoxetine, sertraline, escitalopram, citalopram, paroxetine.',
        relatedTopics: ['SSRI mechanism SERT', 'serotonin reuptake inhibitor', 'antidepressant mechanism', 'monoamine transporters'],
      },
      {
        id: 'mcat5-ps-031',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p6',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'PSYCH: 7B',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'A researcher proposes that differences in rates of MDD between high-income and low-income groups reflect the psychosocial stress of poverty rather than genetic predisposition. Which study design would BEST test this hypothesis?',
        choices: [
          { label: 'A', text: 'Cross-sectional survey of MDD prevalence in low-income and high-income groups at one time point' },
          { label: 'B', text: 'Retrospective study comparing income histories of MDD patients vs. controls' },
          { label: 'C', text: 'A longitudinal study tracking MDD incidence in individuals before and after an exogenous income shock (e.g., factory closure), controlling for genetic predisposition via twin comparisons' },
          { label: 'D', text: 'A randomized controlled trial comparing SSRIs vs. placebo in low-income patients' },
        ],
        correctAnswer: 'C',
        explanation: 'The hypothesis: poverty → psychosocial stress → MDD (not genetic). To test a causal claim about income → MDD, the design needs: (1) a change in income (not just correlation between current income and MDD); (2) a way to rule out genetic confounding. A longitudinal study with exogenous income shock (factory closure is exogenous — not caused by prior mental illness) allows before/after comparison of MDD incidence. Twin comparisons control for genetics (twins share ~50% genes [fraternal] or ~100% [identical]; if one twin has a factory closure and the other doesn\'t, and the closure twin develops MDD more, it is not genetic). C meets both criteria. A — cross-sectional only shows association at one time; cannot establish temporality (did poverty cause MDD or did MDD cause poverty?). B — retrospective income histories subject to recall bias; still cannot rule out reverse causality. D — tests treatment efficacy, not etiology.',
        wrongAnswerExplanations: {
          A: 'Cross-sectional design: cannot establish temporal order (income before MDD?). People with MDD may also experience income loss — reverse causality is a major threat. Cannot rule out genetic confounders.',
          B: 'Retrospective studies are subject to recall bias. More importantly, MDD may have predated the income decline (reverse causality), and genetic predisposition is not controlled for.',
          D: 'RCT testing SSRI efficacy has nothing to do with the etiological question of whether poverty causes MDD through psychosocial stress rather than genetic predisposition.',
        },
        teachingPoint: 'Natural experiments (exogenous shocks): factory closures, lottery wins, policy changes — create quasi-random variation in income that is not caused by the individual\'s mental state. This allows causal inference stronger than observational designs. Twin studies control genetics — if identical twins diverge in income and in MDD rates, genes cannot explain the divergence. Research design for social determinants of health requires careful attention to reverse causality, confounding, and establishing temporal order.',
        relatedTopics: ['natural experiment research design', 'poverty depression causality', 'reverse causality SES mental health', 'twin study genetic control'],
      },
      {
        id: 'mcat5-ps-032',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p6',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'PSYCH: 7B',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'Dysthymia differs from major depressive disorder primarily in:',
        choices: [
          { label: 'A', text: 'Symptom severity — dysthymia involves more severe depressive symptoms than MDD' },
          { label: 'B', text: 'Duration — dysthymia is a chronic condition (≥2 years) with persistent but less intense symptoms; MDD requires ≥2 weeks of more intense symptoms' },
          { label: 'C', text: 'Etiology — MDD is genetic while dysthymia is purely psychosocial in origin' },
          { label: 'D', text: 'Treatment — dysthymia requires antipsychotics while MDD requires antidepressants' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 1: "Dysthymia (persistent depressive disorder) involves chronic low-grade depression lasting at least two years." In contrast, "Major depressive disorder requires at least two weeks of depressed mood." Key differences: MDD = more intense episodes (meeting full criteria including ≥5 symptoms) but can be episodic; dysthymia = milder but persistent (≥2 years, fewer symptoms required). B captures the duration/chronicity and severity distinction. A inverts severity — dysthymia is LESS severe. C — both have complex etiologies involving genetics and environment. D — dysthymia does not require antipsychotics; antidepressants are used for both.',
        wrongAnswerExplanations: {
          A: 'Dysthymia involves LOWER severity (chronic low-grade depression). MDD involves more severe symptoms meeting higher diagnostic thresholds. A inverts the comparison.',
          C: 'Both MDD and dysthymia have multifactorial etiologies involving genetics (heritability ~40% for MDD), neurobiology, and psychosocial factors. Neither is "purely genetic" or "purely psychosocial."',
          D: 'Antipsychotics are not the standard treatment for dysthymia. Both dysthymia and MDD are treated with antidepressants (SSRIs/SNRIs) and psychotherapy. Antipsychotics may be added in psychotic depression.',
        },
        teachingPoint: 'MDD vs. Persistent Depressive Disorder (PDD/Dysthymia): MDD — ≥5 symptoms, ≥2 weeks, meets full criteria for a major depressive episode. PDD — fewer symptoms (≥2), ≥2 years continuous (adults), never symptom-free for >2 months. Double depression: someone with chronic PDD who also experiences superimposed MDD episodes. Shared features: depressed mood is required for both; treatment includes antidepressants + psychotherapy.',
        relatedTopics: ['dysthymia vs MDD', 'persistent depressive disorder', 'mood disorder duration', 'double depression'],
      },
    ],
  },
  {
    id: 'f5-ps-p7',
    sectionId: 'psych-soc',
    passageNumber: 7,
    title: 'Neuroscience of Motivation and Emotion',
    text: `Motivation can be divided into intrinsic motivation — engaging in a behavior for its own sake, for the inherent satisfaction or interest — and extrinsic motivation — engaging in a behavior for external rewards or to avoid punishment. Self-determination theory (Deci and Ryan) proposes that intrinsic motivation is supported by three basic psychological needs: autonomy (sense of choice and ownership), competence (sense of mastery), and relatedness (sense of connection). When external rewards undermine perceived autonomy, they can reduce intrinsic motivation — a phenomenon termed the overjustification effect.

Drive reduction theory (Hull) proposes that physiological needs (hunger, thirst, temperature regulation) create internal drives that motivate behavior aimed at restoring homeostasis. Incentive theory proposes that external stimuli (incentives) pull organisms toward goal-directed behavior; the incentive value of a stimulus is influenced by past experience and current deprivation state. Maslow's hierarchy of needs proposes that lower-order needs (physiological, safety) must be satisfied before higher-order needs (belonging, esteem, self-actualization) are pursued.

Emotion involves both physiological arousal and cognitive appraisal. The James-Lange theory holds that emotional experience is the perception of physiological change ("we are afraid because we tremble"). The Cannon-Bard theory holds that physiological arousal and emotional experience occur simultaneously and independently, both triggered by the thalamus. Schachter-Singer two-factor theory holds that emotion = physiological arousal + cognitive label; the same arousal can produce different emotions depending on the situational appraisal.

The limbic system — including the amygdala, hippocampus, hypothalamus, and cingulate cortex — is central to emotional processing. The amygdala processes fear and emotional salience; stimulation produces fear responses; damage causes Klüver-Bucy syndrome (placidity, hypersexuality, hyperorality, inability to recognize emotional significance of objects).`,
    questions: [
      {
        id: 'mcat5-ps-033',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p7',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'PSYCH: 7C',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 2',
        difficulty: 'easy',
        question: 'A student who loved writing stories starts receiving a grade for each story she writes. After grading begins, she finds she enjoys writing less. This BEST illustrates:',
        choices: [
          { label: 'A', text: 'Drive reduction theory — writing fulfills a physiological drive for expression' },
          { label: 'B', text: 'The overjustification effect — external rewards can reduce intrinsic motivation when they undermine perceived autonomy' },
          { label: 'C', text: 'Incentive theory — the grade is an incentive that increases writing behavior' },
          { label: 'D', text: 'Maslow\'s hierarchy — the student\'s esteem needs are now being satisfied through grades' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 1: "When external rewards undermine perceived autonomy, they can reduce intrinsic motivation — a phenomenon termed the overjustification effect." The student initially writes for intrinsic enjoyment. When grading (external reward) begins, she perceives writing as now externally motivated ("I write for the grade") → intrinsic interest declines. B is correct. A — drive reduction involves homeostasis-restoring physiological needs; writing is not a physiological drive. C — incentive theory says external incentives INCREASE goal-directed behavior; this scenario shows DECREASED motivation with a reward — the opposite of simple incentive theory. D — Maslow is about a hierarchy of needs, not about how rewards affect motivation.',
        wrongAnswerExplanations: {
          A: 'Drive reduction theory (Hull): physiological needs → internal drives → homeostasis-restoring behavior. Writing is not a physiological need. Drive reduction does not explain decreasing enjoyment of an activity after reward introduction.',
          C: 'Incentive theory predicts external incentives increase behavior. The scenario shows DECREASED intrinsic motivation, not increased behavior — the overjustification effect contradicts simple incentive predictions.',
          D: 'Maslow\'s hierarchy predicts which needs are prioritized (lower before higher). It does not address how rewards affect intrinsic motivation. The student\'s situation is specifically about motivation undermining, not need prioritization.',
        },
        teachingPoint: 'Overjustification effect (Lepper, Greene, Nisbett 1973): children who drew for fun were given a "Good Player Award." Later, without reward, they drew less than control children who never received a reward. Interpretation: external reward → internal attribution shifts to external ("I do this for the reward") → when reward removed, no internal reason remains. Clinical/educational application: excessive external rewards for already-enjoyable tasks can backfire. Self-determination theory: rewards that support competence and autonomy preserve intrinsic motivation; controlling rewards (contingent on performance) undermine it.',
        relatedTopics: ['overjustification effect', 'intrinsic motivation external reward', 'self-determination theory', 'extrinsic undermines intrinsic'],
      },
      {
        id: 'mcat5-ps-034',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p7',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'PSYCH: 7C',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'According to the Schachter-Singer two-factor theory, which scenario BEST demonstrates how the same physiological arousal can lead to different emotional experiences?',
        choices: [
          { label: 'A', text: 'A person trembles and then concludes they are afraid — physiological state precedes emotional label' },
          { label: 'B', text: 'Two people with identical thalamic activations experience the same emotion simultaneously' },
          { label: 'C', text: 'A participant injected with epinephrine who is placed in an angry context reports anger; an identical participant placed in an euphoric context reports happiness' },
          { label: 'D', text: 'A person\'s emotion is determined solely by their physiological arousal level, regardless of situational context' },
        ],
        correctAnswer: 'C',
        explanation: 'Paragraph 3: "Schachter-Singer two-factor theory holds that emotion = physiological arousal + cognitive label; the same arousal can produce different emotions depending on the situational appraisal." C demonstrates the classic Schachter-Singer experiment: same physiological arousal (epinephrine) → different emotion based on context (angry confederate → anger label; euphoric confederate → happiness label). C is correct. A — James-Lange theory: physiological state → emotional experience. B — Cannon-Bard: thalamus triggers simultaneous arousal and emotional experience. D — describes pure arousal-only theory (no cognitive label), contradicting two-factor theory which REQUIRES the cognitive component.',
        wrongAnswerExplanations: {
          A: 'James-Lange: "We feel afraid because we tremble." Physiological state causes emotional experience. This is specifically what Schachter-Singer challenges by showing that the LABEL (cognitive appraisal) also shapes the experience.',
          B: 'Cannon-Bard: thalamus simultaneously activates cortex (emotion) and peripheral nervous system (arousal). Two people with identical thalamic activations → same emotion simultaneously. This does not distinguish the role of cognitive labeling.',
          D: 'Pure arousal theory (no cognitive label) contradicts Schachter-Singer two-factor theory. The two-factor theory explicitly requires BOTH physiological arousal AND cognitive label. Without the cognitive component, you cannot predict which emotion will result.',
        },
        teachingPoint: 'Emotion theories: James-Lange: physiological arousal → perceive the arousal → emotion. Cannon-Bard: thalamus simultaneously triggers arousal (peripheral) and emotion (cortical) — independent, simultaneous. Schachter-Singer two-factor: arousal + cognitive label = emotion (same arousal, different label → different emotion). Clinical: Schachter-Singer explains misattribution of arousal (e.g., suspension bridge study — arousal from fear attributed to attraction to researcher).',
        relatedTopics: ['Schachter Singer two factor', 'emotion theories arousal label', 'James Lange vs Cannon Bard', 'misattribution arousal emotion'],
      },
      {
        id: 'mcat5-ps-035',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p7',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'PSYCH: 7C',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'Maslow\'s hierarchy predicts that a person experiencing severe food insecurity (unmet physiological needs) would have difficulty pursing which type of need?',
        choices: [
          { label: 'A', text: 'Physiological needs — food insecurity directly impairs their ability to find food' },
          { label: 'B', text: 'Safety needs — danger and insecurity are the same level as physiological needs' },
          { label: 'C', text: 'Esteem and self-actualization — higher-order needs that require lower-order needs to be met first' },
          { label: 'D', text: 'Relatedness — the social need at the third level cannot be satisfied without food security' },
        ],
        correctAnswer: 'C',
        explanation: 'Paragraph 2: "Maslow\'s hierarchy of needs proposes that lower-order needs (physiological, safety) must be satisfied before higher-order needs (belonging, esteem, self-actualization) are pursued." Food insecurity = unmet physiological (lowest tier). If physiological needs are unmet, the person cannot effectively pursue higher-order needs (esteem, self-actualization) — these require the foundation of met physiological and safety needs. C is correct. A — the question asks which needs they have DIFFICULTY pursuing beyond physiological; it\'s already established that physiological is the problem. B — safety needs are also lower-order, not the highest impact. D — while relatedness may be impacted, esteem and self-actualization (highest levels) would be MOST impaired when the LOWEST level is unmet.',
        wrongAnswerExplanations: {
          A: 'The question is about which needs are most difficult to pursue given the unmet physiological needs. A simply restates the problem rather than identifying what is most impacted by it.',
          B: 'Safety is the second level — also a lower-order need. While it is impaired too, the hierarchy predicts the HIGHEST-order needs (esteem, self-actualization) are MOST inaccessible when even physiological needs are unmet.',
          D: 'Belonging/relatedness is the third level (above physiological and safety). While it is affected, esteem (fourth) and self-actualization (fifth) are even more inaccessible. C identifies the higher-order needs most impaired.',
        },
        teachingPoint: 'Maslow\'s hierarchy (bottom to top): Physiological (food, water, shelter, sleep) → Safety (security, stability) → Belonging/Love (relationships, social connection) → Esteem (achievement, recognition, self-respect) → Self-actualization (reaching one\'s potential, purpose). Clinical application: addressing only disease without addressing food insecurity, housing, or safety means patients cannot engage with health promotion or self-management (higher-order needs). Social determinants of health align with Maslow\'s lower tiers.',
        relatedTopics: ['Maslow hierarchy needs', 'physiological needs hierarchy', 'self-actualization lower order', 'hierarchy social determinants'],
      },
      {
        id: 'mcat5-ps-036',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p7',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'PSYCH: 7C',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'A patient with bilateral amygdala damage presents with inability to recognize fearful faces, reduced fear response to threats, and hypersexuality. This presentation is MOST consistent with:',
        choices: [
          { label: 'A', text: 'Major depressive disorder — anhedonia and loss of emotional engagement' },
          { label: 'B', text: 'Klüver-Bucy syndrome — features consistent with bilateral temporal/amygdala damage' },
          { label: 'C', text: 'Panic disorder — recurrent fear responses triggered by the amygdala' },
          { label: 'D', text: 'Generalized anxiety disorder — excessive fear and worry are hallmarks' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 4: "damage causes Klüver-Bucy syndrome (placidity, hypersexuality, hyperorality, inability to recognize emotional significance of objects)." The patient shows: inability to recognize fearful faces (= inability to recognize emotional significance) + reduced fear response (= placidity) + hypersexuality. This matches Klüver-Bucy syndrome from bilateral amygdala damage. B is correct. A — MDD involves depressed mood, anhedonia, sleep/appetite changes; not hypersexuality or inability to recognize fearful faces. C — panic disorder = EXCESSIVE fear/anxiety; this patient has REDUCED fear, the opposite. D — GAD = excessive worry; this patient has reduced fear response.',
        wrongAnswerExplanations: {
          A: 'MDD features: depressed mood, anhedonia, sleep disturbance, guilt, psychomotor changes. Hypersexuality and inability to recognize fearful faces are not features of MDD.',
          C: 'Panic disorder = recurrent unexpected surges of intense FEAR. Amygdala damage causes REDUCED fear (placidity). C would expect the amygdala to be hyperactive, not damaged.',
          D: 'GAD = excessive, chronic worry. Bilateral amygdala damage causes REDUCED anxiety and fear, not excessive worry.',
        },
        teachingPoint: 'Klüver-Bucy syndrome (H. Klüver & P. Bucy, 1937): bilateral temporal lobe/amygdala lesions → placidity (no fear/aggression), hypersexuality, hyperorality (mouth everything), visual agnosia (cannot recognize objects), and psychic blindness (see objects but cannot assign meaning/significance). Human cases: bilateral temporal lobe lesions (severe herpes encephalitis, surgical bilateral temporal lobectomy). Amygdala = fear and emotional salience. Loss → flat affect, no fear of threats.',
        relatedTopics: ['Kluver-Bucy syndrome', 'amygdala damage', 'bilateral amygdala lesion', 'amygdala fear processing'],
      },
      {
        id: 'mcat5-ps-037',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p7',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'PSYCH: 7C',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 2',
        difficulty: 'easy',
        question: 'Drive reduction theory predicts that a hungry person will seek food. After eating, the drive decreases and behavior stops. This process is BEST described as:',
        choices: [
          { label: 'A', text: 'Homeostasis — returning a physiological variable to its set point through behavior' },
          { label: 'B', text: 'The overjustification effect — hunger drives food-seeking for external reward' },
          { label: 'C', text: 'Self-actualization — fulfilling the highest tier of Maslow\'s hierarchy' },
          { label: 'D', text: 'Incentive salience — the smell of food motivates eating' },
        ],
        correctAnswer: 'A',
        explanation: 'Paragraph 2: "Drive reduction theory (Hull) proposes that physiological needs (hunger, thirst, temperature regulation) create internal drives that motivate behavior aimed at restoring homeostasis." Hunger = homeostatic signal (energy deficit). Eating = behavior restoring energy balance. After eating → drive decreases (homeostasis restored) → behavior stops. A captures the homeostatic process. B — overjustification = intrinsic motivation decreased by external rewards; not relevant. C — self-actualization = highest Maslow tier (reaching potential); eating is the LOWEST tier (physiological). D — incentive salience (Berridge) = the "wanting" component of reward, driven by dopamine; not the core mechanism of drive reduction theory.',
        wrongAnswerExplanations: {
          B: 'Overjustification: external rewards undermine intrinsic motivation. Food-seeking driven by hunger is not about external rewards undermining intrinsic behavior — it is about physiological need restoration.',
          C: 'Self-actualization is Maslow\'s highest tier (realizing full potential, purpose, creativity). Eating addresses the LOWEST physiological tier. Hunger cessation restores homeostasis, not self-actualization.',
          D: 'Incentive salience (the smell of food motivating eating) is a separate mechanism — it addresses how environmental cues trigger "wanting." Drive reduction focuses on internal homeostatic drives, not external stimulus salience.',
        },
        teachingPoint: 'Drive reduction vs. incentive theory: Drive reduction = internal homeostatic imbalance → drive → behavior → homeostasis → drive reduced. Incentive theory = external stimuli pull behavior independent of internal drive state (you eat dessert even when full because dessert is appealing). Real feeding behavior uses both: hunger (drive) + food smell (incentive). Critiques of drive reduction: doesn\'t explain why people seek stimulation (curiosity, novelty) when no homeostatic need exists.',
        relatedTopics: ['drive reduction theory homeostasis', 'Hull drive reduction', 'incentive theory vs drive', 'physiological need motivation'],
      },
      {
        id: 'mcat5-ps-038',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p7',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'PSYCH: 7C',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'Self-determination theory predicts that a medical resident will have the HIGHEST intrinsic motivation for patient care when:',
        choices: [
          { label: 'A', text: 'She is closely supervised and told exactly what procedures to perform (high structure, low autonomy)' },
          { label: 'B', text: 'She receives large financial bonuses for each patient seen (high extrinsic reward)' },
          { label: 'C', text: 'She feels ownership over her clinical decisions, has developed clinical mastery, and has meaningful relationships with patients and colleagues' },
          { label: 'D', text: 'She completes tasks to avoid punishment from attending physicians (external motivation by threat)' },
        ],
        correctAnswer: 'C',
        explanation: 'Paragraph 1: self-determination theory proposes intrinsic motivation is supported by "autonomy (sense of choice and ownership), competence (sense of mastery), and relatedness (sense of connection)." C satisfies all three needs: ownership → autonomy; clinical mastery → competence; meaningful relationships → relatedness. All three needs met = highest intrinsic motivation. A — low autonomy directly undermines intrinsic motivation. B — large financial bonuses = extrinsic reward → overjustification effect risk → may undermine intrinsic motivation. D — avoiding punishment = external regulation (most controlled, least autonomous form) → lowest intrinsic motivation.',
        wrongAnswerExplanations: {
          A: 'SDT: autonomy is a core need. Close supervision with prescribed procedures → low autonomy → undermines intrinsic motivation. High structure with no self-direction contradicts SDT conditions for intrinsic motivation.',
          B: 'Large financial bonuses = strong extrinsic reward. SDT: overjustification effect — when external rewards are salient, they can shift attribution from internal interest to external reward → intrinsic motivation may decrease.',
          D: 'Motivation by threat/punishment = external regulation (opposite end of the self-determination continuum from autonomous/intrinsic motivation). This produces compliance, not intrinsic motivation.',
        },
        teachingPoint: 'SDT motivation continuum: External regulation (rewards/punishments) → Introjection (guilt/ego) → Identification (personal importance) → Integration (aligned with values) → Intrinsic (inherent interest). All three basic needs (autonomy, competence, relatedness) must be satisfied for intrinsic motivation. Medical education application: training environments that support resident autonomy, develop competence, and foster teamwork produce more intrinsically motivated physicians → better patient care, lower burnout.',
        relatedTopics: ['self determination theory SDT', 'autonomy competence relatedness', 'intrinsic motivation SDT conditions', 'motivation continuum SDT'],
      },
    ],
  },
  {
    id: 'f5-ps-p8',
    sectionId: 'psych-soc',
    passageNumber: 8,
    title: 'Group Behavior and Social Influence',
    text: `Social psychology investigates how individuals' thoughts, feelings, and behaviors are influenced by the actual, imagined, or implied presence of others. Several classic phenomena illuminate the power of social influence.

Conformity refers to changing one's behavior or beliefs to match a group. Asch's conformity experiments demonstrated that participants would give obviously incorrect answers when confederates unanimously gave the wrong answer — even when the task (judging line lengths) was unambiguous. Conformity was driven by normative influence (desire to be accepted) and informational influence (using the group as a source of information when the situation is ambiguous).

Obedience refers to compliance with direct orders from an authority figure. Milgram's obedience studies found that 65% of participants administered what they believed were painful, potentially lethal electric shocks to a confederate when instructed by an experimenter in a white coat. Factors increasing obedience included: physical proximity to the authority, proximity of the victim being low (buffering effect), and escalating commitment.

Bystander effect: the presence of other people reduces the likelihood that any individual will help in an emergency. Latané and Darley identified two key mechanisms: (1) diffusion of responsibility — each bystander assumes someone else will help; (2) pluralistic ignorance — each bystander looks to others for cues and, seeing no one act, interprets the situation as non-emergent.

Social facilitation refers to improved performance on simple or well-learned tasks in the presence of others, and impaired performance on complex or novel tasks. Zajonc proposed the dominant response hypothesis: presence of others increases arousal → strengthens the dominant (most practiced) response → helps if dominant response is correct (simple task), hurts if dominant response is incorrect (complex task).`,
    questions: [
      {
        id: 'mcat5-ps-039',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p8',
        questionType: 'passage',
        discipline: 'Sociology',
        contentCategory: 'SOC: 8A',
        foundationalConcept: 'FC 8',
        scientificSkill: 'Skill 2',
        difficulty: 'easy',
        question: 'In Asch\'s conformity experiments, participants gave wrong answers because confederates unanimously chose incorrectly. The passage identifies which TWO mechanisms driving this conformity?',
        choices: [
          { label: 'A', text: 'Obedience to authority and diffusion of responsibility' },
          { label: 'B', text: 'Normative influence (desire to be accepted) and informational influence (using group as information source)' },
          { label: 'C', text: 'Social facilitation and pluralistic ignorance' },
          { label: 'D', text: 'Fundamental attribution error and self-serving bias' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 2: "Conformity was driven by normative influence (desire to be accepted) and informational influence (using the group as a source of information when the situation is ambiguous)." B directly quotes the passage. A — obedience and diffusion of responsibility are different phenomena (Milgram, bystander effect). C — social facilitation involves performance tasks; pluralistic ignorance is a bystander mechanism. D — FAE and self-serving bias are attribution phenomena, not conformity mechanisms.',
        wrongAnswerExplanations: {
          A: 'Obedience is compliance with direct authority orders (Milgram); diffusion of responsibility is a bystander mechanism. Neither is identified in the passage as driving Asch\'s conformity.',
          C: 'Social facilitation is about task performance in others\' presence. Pluralistic ignorance is a bystander mechanism. Neither explains Asch\'s line-judging conformity.',
          D: 'FAE and self-serving bias are attribution errors in social cognition — they explain HOW we explain behavior, not WHY we conform to group judgment.',
        },
        teachingPoint: 'Conformity mechanisms: (1) Normative influence: social pressure to be accepted; conform to avoid rejection. Strongest when: unanimity, group is important to the person, public behavior. (2) Informational influence: others as information sources; strongest when ambiguous situations, high uncertainty, crisis conditions, or when others seem more expert. Asch: even on UNAMBIGUOUS tasks, 75% conformed at least once → shows normative power even without informational ambiguity.',
        relatedTopics: ['Asch conformity', 'normative informational influence', 'conformity mechanisms', 'social pressure conformity'],
      },
      {
        id: 'mcat5-ps-040',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p8',
        questionType: 'passage',
        discipline: 'Sociology',
        contentCategory: 'SOC: 8A',
        foundationalConcept: 'FC 8',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'In Milgram\'s study, obedience was higher when the victim was physically farther from the participant. This finding is consistent with which psychological principle?',
        choices: [
          { label: 'A', text: 'Social facilitation — presence of others increases arousal and strengthens dominant responses' },
          { label: 'B', text: 'The buffering effect — physical or psychological distance from the victim reduces the moral weight of the action, facilitating obedience' },
          { label: 'C', text: 'Informational influence — participants used the victim\'s responses as information about whether to continue' },
          { label: 'D', text: 'Diffusion of responsibility — more bystanders reduced any individual\'s sense of obligation' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 3: "proximity of the victim being low (buffering effect)" increases obedience. The buffering effect: when the victim is far away (you can\'t see their distress, you hear only muffled responses or nothing), the emotional and moral salience of harming them is reduced — the harm feels less real and the distress is less visible. This makes it easier to continue despite causing harm. B matches. A — social facilitation = task performance in audience presence; not related to victim distance in obedience. C — informational influence drives conformity to group judgment; in Milgram, the participant follows the authority, not victim responses. D — Milgram\'s paradigm has a single participant; diffusion of responsibility requires multiple bystanders.',
        wrongAnswerExplanations: {
          A: 'Social facilitation: audience → arousal → dominant response. Milgram\'s obedience involves compliance with authority, not performance on a task in front of an audience.',
          C: 'Informational influence: using group as information source in ambiguous situations. In Milgram, the victim is not a peer whose judgment the participant is following — the authority (experimenter) is giving the orders.',
          D: 'Diffusion of responsibility requires multiple bystanders sharing the responsibility. Milgram\'s paradigm has one participant at a time — no other bystanders whose presence would dilute responsibility.',
        },
        teachingPoint: 'Milgram findings: 65% full compliance (450V). Factors affecting obedience: authority proximity (high → more obedient), victim proximity (low = buffered → more obedient), institutional legitimacy (Yale → more vs. run-down office → less), presence of disobedient confederate (ally → dramatically reduces obedience). Clinical: "just following orders" in institutional settings, diffusion of moral responsibility in bureaucracies — basis for studying atrocity and institutional harm.',
        relatedTopics: ['Milgram obedience', 'buffering effect victim proximity', 'obedience authority factors', 'victim distance obedience'],
      },
      {
        id: 'mcat5-ps-041',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p8',
        questionType: 'passage',
        discipline: 'Sociology',
        contentCategory: 'SOC: 8A',
        foundationalConcept: 'FC 8',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'At the scene of a car accident on a busy street, witnesses look at each other and, seeing everyone else remaining still, assume the situation is not serious and do not call for help. This BEST illustrates:',
        choices: [
          { label: 'A', text: 'Diffusion of responsibility — each person assumes someone else already called' },
          { label: 'B', text: 'Pluralistic ignorance — each bystander interprets others\' inaction as a signal that no emergency exists' },
          { label: 'C', text: 'Conformity through normative influence — witnesses follow group behavior to be accepted' },
          { label: 'D', text: 'Social facilitation — the audience effect improves bystander performance' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 4: "pluralistic ignorance — each bystander looks to others for cues and, seeing no one act, interprets the situation as non-emergent." The witnesses look at each other (look for cues) → see no one acting → interpret as "not serious" → don\'t call for help. This is pluralistic ignorance: using others\' apparent calm as informational input, leading to a shared misperception. B is correct. A — diffusion of responsibility = "someone else will help" without questioning the emergency; the scenario specifically involves interpreting the SEVERITY of the situation based on others\' inaction. C — normative conformity = conforming to be accepted; this is cognitive misinterpretation of emergency, not social acceptance motivation. D — social facilitation involves task performance in an audience; not relevant here.',
        wrongAnswerExplanations: {
          A: 'Diffusion of responsibility: each person acknowledges it is an emergency but assumes SOMEONE ELSE will handle it. Pluralistic ignorance: each person uses others\' inaction as EVIDENCE that it is not an emergency. The scenario shows the latter (witnesses conclude "not serious" from observing others\' stillness).',
          C: 'Normative influence conformity: conforming to match group behavior to be socially accepted. Pluralistic ignorance is a cognitive process (using others as information), not a social acceptance motivation.',
          D: 'Social facilitation: audience presence affects task performance. This scenario involves an emergency response situation — not a performance task requiring arousal-dominant response logic.',
        },
        teachingPoint: 'Bystander intervention (Darley & Latané): 5 steps to help: (1) Notice event. (2) Interpret as emergency. (3) Assume responsibility. (4) Know how to help. (5) Decide to help. Pluralistic ignorance fails at Step 2 (interpret as emergency). Diffusion of responsibility fails at Step 3 (assume responsibility). Both increase with crowd size. Genovese case: 38 witnesses, no one helped. Intervention: single out specific people ("YOU in the red hat, call 911") — breaks both mechanisms.',
        relatedTopics: ['pluralistic ignorance', 'bystander effect mechanisms', 'diffusion responsibility vs pluralistic ignorance', 'Darley Latane bystander'],
      },
      {
        id: 'mcat5-ps-042',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p8',
        questionType: 'passage',
        discipline: 'Sociology',
        contentCategory: 'SOC: 8A',
        foundationalConcept: 'FC 8',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'A medical student performs well on a simple physical exam maneuver (already practiced hundreds of times) when being observed by an attending. However, she performs worse than usual on a complex, rarely-practiced procedure when observed. This pattern is BEST explained by:',
        choices: [
          { label: 'A', text: 'Diffusion of responsibility — the attending is present and shares responsibility' },
          { label: 'B', text: 'The overjustification effect — being observed introduces an external reward that undermines intrinsic motivation' },
          { label: 'C', text: 'Social facilitation — observation increases arousal, strengthening the dominant response (helpful for simple/practiced tasks, harmful for complex/novel tasks)' },
          { label: 'D', text: 'Normative conformity — she conforms her behavior to match the attending\'s preferences' },
        ],
        correctAnswer: 'C',
        explanation: 'Paragraph 5: "Social facilitation refers to improved performance on simple or well-learned tasks in the presence of others, and impaired performance on complex or novel tasks. Zajonc proposed the dominant response hypothesis: presence of others increases arousal → strengthens the dominant (most practiced) response → helps if dominant response is correct (simple task), hurts if dominant response is incorrect (complex task)." Simple practiced maneuver → dominant response is correct → observation → arousal → performs better. Complex, novel procedure → dominant response may not be correct → observation → arousal → over-activates incorrect dominant response → performs worse. C is correct.',
        wrongAnswerExplanations: {
          A: 'Diffusion of responsibility = less likely to help in an emergency because others share responsibility. The attending\'s presence doesn\'t reduce the student\'s responsibility — it\'s about task performance.',
          B: 'Overjustification: external rewards undermine intrinsic motivation. Being observed is not an external reward for the task; the pattern (better simple, worse complex) specifically matches social facilitation, not motivation undermining.',
          D: 'Normative conformity = changing behavior to match group and be accepted. The scenario describes differential performance on simple vs. complex tasks — this is about arousal and task complexity, not social acceptance.',
        },
        teachingPoint: 'Social facilitation history: Triplett (1898) — cyclists faster in pairs. Zajonc (1965) — cockroaches run maze faster in audience for simple maze, slower for complex maze. Mechanism: evaluation apprehension (fear of being judged) → physiological arousal → dominant response strengthened. Clinical: medical students perform well-practiced physical exam well but fumble novel procedures under observation. Solution: practice novel procedures in low-evaluation contexts first, then introduce supervision.',
        relatedTopics: ['social facilitation Zajonc', 'dominant response hypothesis', 'observation task performance', 'simple complex task arousal'],
      },
      {
        id: 'mcat5-ps-043',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p8',
        questionType: 'passage',
        discipline: 'Sociology',
        contentCategory: 'SOC: 8A',
        foundationalConcept: 'FC 8',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'Milgram\'s study raised profound ethical concerns. Which aspect of the study most directly violated the ethical principle of protection from harm?',
        choices: [
          { label: 'A', text: 'Failure to obtain informed consent — participants were not told they would be asked to harm others' },
          { label: 'B', text: 'Use of deception — participants believed the electric shocks were real, but the confederate was not actually harmed' },
          { label: 'C', text: 'The psychological distress experienced by participants who believed they were harming another person — many showed extreme stress during the study' },
          { label: 'D', text: 'Lack of debriefing — participants were not told the study\'s true purpose after completion' },
        ],
        correctAnswer: 'C',
        explanation: 'Protection from harm: participants should not experience physical or significant psychological harm. In Milgram\'s study, participants showed visible signs of extreme stress (sweating, trembling, laughing nervously, protesting) as they believed they were harming someone. This psychological harm to participants is the most direct violation of protection from harm. A — informed consent was not fully obtained (deception involved), but the primary harm concern is to the participants themselves. B — deception is a methodological concern (related to informed consent), but the harm was the psychological distress. D — Milgram DID debrief participants; debriefing was part of his protocol. The greatest harm was the acute psychological distress during the study.',
        wrongAnswerExplanations: {
          A: 'Failure to obtain fully informed consent is an ethical violation, but the question asks about the principle most DIRECTLY violated. Protection from harm is most directly violated by the psychological distress the participants actually experienced.',
          B: 'Deception (fake shocks) relates to informed consent and truthfulness. The confederate was not harmed; the harm issue is about the REAL distress participants experienced believing they were inflicting pain.',
          D: 'Milgram actually did conduct debriefing — participants were told the truth after the study. Debriefing was part of the protocol. This was not the primary ethical violation.',
        },
        teachingPoint: 'Research ethics (Belmont Report): (1) Respect for persons (autonomy, informed consent). (2) Beneficence (maximize benefits, minimize harm). (3) Justice (equitable distribution of burdens/benefits). Milgram\'s violations: deception (incomplete informed consent), psychological harm to participants (protection from harm). IRBs now require: informed consent, right to withdraw without penalty, minimal risk, debriefing. Milgram\'s study changed how human subjects research is conducted.',
        relatedTopics: ['Milgram ethics', 'research ethics protection harm', 'informed consent research', 'Belmont Report principles'],
      },
      {
        id: 'mcat5-ps-044',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p8',
        questionType: 'passage',
        discipline: 'Sociology',
        contentCategory: 'SOC: 8A',
        foundationalConcept: 'FC 8',
        scientificSkill: 'Skill 2',
        difficulty: 'easy',
        question: 'In a group of medical students studying together, each student reduces their individual study effort because they assume the others will cover the material adequately. This illustrates which group phenomenon?',
        choices: [
          { label: 'A', text: 'Social facilitation — studying with others improves performance on well-learned material' },
          { label: 'B', text: 'Groupthink — the group suppresses dissent to reach consensus' },
          { label: 'C', text: 'Social loafing — individuals reduce effort in group settings because individual contributions are less identifiable' },
          { label: 'D', text: 'Deindividuation — anonymity reduces self-regulation and increases impulsive behavior' },
        ],
        correctAnswer: 'C',
        explanation: 'Social loafing: individuals in groups reduce their individual effort, assuming the group\'s combined effort will suffice, and individual contribution is not individually identifiable or accountable. Each student reduces effort assuming others will cover the material = social loafing. C is correct. A — social facilitation = observation affects performance on simple/complex tasks; these students are reducing effort, not performing differently based on arousal. B — groupthink = suppression of dissent for group consensus; not about effort reduction in studying. D — deindividuation = anonymity → reduced self-regulation → impulsive behavior; the scenario is about effort reduction, not impulsivity.',
        wrongAnswerExplanations: {
          A: 'Social facilitation: arousal from audience → strengthens dominant response → better simple, worse complex. Reducing study effort is not a social facilitation phenomenon.',
          B: 'Groupthink (Janis): cohesive group suppresses critical thinking → poor decisions. Examples: Bay of Pigs, Challenger explosion. The scenario is about effort reduction (loafing), not suppressed critical thinking for consensus.',
          D: 'Deindividuation: anonymous/crowd situations → loss of personal identity → reduced self-regulation → increased impulsive behavior. The scenario involves deliberate effort reduction, not impulsive behavior from anonymity.',
        },
        teachingPoint: 'Social loafing (Ringelmann effect, Latané): individual effort decreases as group size increases. Mechanisms: (1) diffusion of responsibility (someone else will do it), (2) reduced identifiability (my contribution isn\'t measured separately). Remedies: increase individual accountability (identifiable contributions), increase group cohesion, make individual effort visible. Medical team setting: social loafing in handoffs, documentation, or follow-up tasks when accountability is unclear.',
        relatedTopics: ['social loafing', 'group effort reduction', 'Ringelmann social loafing', 'group accountability effort'],
      },
      {
        id: 'mcat5-ps-045',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p8',
        questionType: 'passage',
        discipline: 'Sociology',
        contentCategory: 'SOC: 8A',
        foundationalConcept: 'FC 8',
        scientificSkill: 'Skill 2',
        difficulty: 'easy',
        question: 'Informational social influence is MOST likely to drive conformity when:',
        choices: [
          { label: 'A', text: 'The task is unambiguous and the person is highly confident in their answer' },
          { label: 'B', text: 'The situation is ambiguous and the group appears to have expertise or information the individual lacks' },
          { label: 'C', text: 'The group is unanimously wrong about an easily verified fact' },
          { label: 'D', text: 'The individual disagrees with the group but wants to be liked by group members' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 2: "informational influence (using the group as a source of information when the situation is ambiguous)." Informational influence is strongest when: (1) the situation is ambiguous (you are uncertain, so others\' behavior provides information), (2) others seem more expert or have better information. B captures both conditions. A — unambiguous task + high confidence: informational influence is minimal (you don\'t need others\' information). C — easily verified fact + unanimously wrong group: informational influence is weak (you can check yourself); any conformity here is normative. D — wanting to be liked = normative influence, not informational.',
        wrongAnswerExplanations: {
          A: 'High confidence + unambiguous task → low uncertainty → no need for others\' information → minimal informational influence. Any conformity on an unambiguous task under these conditions would be normative.',
          C: 'Unanimously wrong group on an easily verified fact: you CAN check, so you should not use the group as an information source. Conforming here is normative (social pressure), not informational.',
          D: 'Wanting to be liked = normative social influence (conform to be accepted). Not informational influence.',
        },
        teachingPoint: 'Normative vs. informational influence: Normative = conform to be liked/accepted (even if you think they are wrong). Informational = conform because you believe others have better information (especially in ambiguous/crisis situations). Both operate simultaneously. Asch study showed BOTH in action even on unambiguous tasks. Medical context: informational influence explains why trainees often defer to senior clinicians\' diagnoses, especially in ambiguous cases. The danger: uncritical deference in high-stakes situations.',
        relatedTopics: ['informational influence conditions', 'normative vs informational influence', 'conformity types', 'social influence ambiguity'],
      },
    ],
  },
  {
    id: 'f5-ps-p9',
    sectionId: 'psych-soc',
    passageNumber: 9,
    title: 'Culture, Health, and Demographic Patterns',
    text: `Culture encompasses the shared values, norms, beliefs, symbols, and practices of a group. Cultural competence in medicine requires awareness of how cultural factors influence health beliefs, illness experience, healthcare seeking, and adherence. Explanatory models (Kleinman) refer to patients' own cultural frameworks for understanding their illness — what caused it, why it started when it did, what it does, how severe it is, and what treatment it requires. When provider and patient explanatory models diverge, miscommunication and poor adherence can result.

Health disparities are differences in health outcomes between groups that are systematic, avoidable, and often the result of social and economic disadvantage. Social determinants of health — including income, education, housing, neighborhood safety, and social support — account for approximately 30-55% of health outcomes. The built environment (the physical structures and infrastructure of neighborhoods) influences health: walkability promotes physical activity; food deserts limit access to nutritious food; environmental exposures (pollution, industrial sites) cluster in low-income and minority neighborhoods.

Demographic patterns in the United States show significant variation in health outcomes by race, ethnicity, SES, and geography. Black Americans have higher rates of cardiovascular disease, hypertension, diabetes, and maternal mortality than white Americans — even after controlling for SES in many analyses. Rural communities face challenges including healthcare provider shortages, limited specialty care access, and higher rates of chronic disease and opioid use disorder. The Hispanic paradox describes the phenomenon where Hispanic Americans — despite lower average SES — have better health outcomes on several measures (especially cardiovascular mortality) compared to non-Hispanic whites; proposed explanations include cultural protective factors (familismo, social cohesion), selective migration effects, and possibly data limitations.

Medically underserved areas (MUAs) and health professional shortage areas (HPSAs) are federal designations for regions lacking adequate primary care access, often coinciding with low-income, rural, or urban minority communities.`,
    questions: [
      {
        id: 'mcat5-ps-046',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p9',
        questionType: 'passage',
        discipline: 'Sociology',
        contentCategory: 'SOC: 9B',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'easy',
        question: 'A patient tells her physician that her fatigue is caused by "an imbalance in her life force" and she plans to see a traditional healer. Her physician believes fatigue is due to her anemia. The gap between these frameworks BEST illustrates:',
        choices: [
          { label: 'A', text: 'The Hispanic paradox — cultural protective factors explain the discrepancy in explanations' },
          { label: 'B', text: 'Divergent explanatory models — provider and patient have different cultural frameworks for understanding illness' },
          { label: 'C', text: 'Informational social influence — the patient is using her cultural community as an information source' },
          { label: 'D', text: 'Structural racism — the healthcare system has failed to diagnose the patient correctly' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 1: "Explanatory models (Kleinman) refer to patients\' own cultural frameworks for understanding their illness...When provider and patient explanatory models diverge, miscommunication and poor adherence can result." The patient\'s "life force imbalance" = her explanatory model. The physician\'s "anemia" = biomedical explanatory model. These are different cultural frameworks in direct conflict — divergent explanatory models. B is correct. A — Hispanic paradox = health outcome discrepancy by ethnicity; not about explanatory models. C — informational social influence is about conformity; not about illness frameworks. D — structural racism may be present in the healthcare system, but the specific scenario illustrates divergent explanatory models.',
        wrongAnswerExplanations: {
          A: 'The Hispanic paradox is about differential health outcomes (mortality, CVD) in Hispanic Americans relative to expected outcomes given SES. It has nothing to do with patient-provider communication about illness explanations.',
          C: 'Informational social influence (conformity) = using groups as information sources when uncertain. This scenario is about cultural illness frameworks between a patient and provider, not conformity to group behavior.',
          D: 'Structural racism (inequity embedded in healthcare systems) may be relevant context, but the scenario specifically illustrates the concept of divergent explanatory models — a distinct communication concept from Kleinman.',
        },
        teachingPoint: 'Kleinman\'s explanatory model questions (LEARN model): What do you call this problem? What do you think caused it? Why do you think it started when it did? What do you think the sickness does? How severe is it? What treatment do you think you need? When providers elicit patients\' explanatory models and negotiate understanding, adherence improves. Ignoring explanatory models → poor adherence, missed diagnoses, strained therapeutic relationship.',
        relatedTopics: ['explanatory models Kleinman', 'patient provider cultural frameworks', 'divergent explanatory models', 'cultural competence illness'],
      },
      {
        id: 'mcat5-ps-047',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p9',
        questionType: 'passage',
        discipline: 'Sociology',
        contentCategory: 'SOC: 9B',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'The Hispanic paradox describes better health outcomes in Hispanic Americans despite lower average SES. The passage provides several proposed explanations. Which explanation invokes a CULTURAL protective factor?',
        choices: [
          { label: 'A', text: 'Selective migration — healthier Hispanic immigrants self-select for immigration, leaving sicker individuals behind' },
          { label: 'B', text: 'Data limitations — health outcomes may be undercounted for Hispanic Americans' },
          { label: 'C', text: 'Familismo — strong family cohesion and social support networks in Hispanic culture serve as a health-protective buffer' },
          { label: 'D', text: 'Lower SES — Hispanic Americans actually have worse outcomes once SES is fully controlled' },
        ],
        correctAnswer: 'C',
        explanation: 'Paragraph 3: "proposed explanations include cultural protective factors (familismo, social cohesion), selective migration effects, and possibly data limitations." Familismo = strong family bonds and collective support in Hispanic culture = a CULTURAL protective factor. Social support buffers stress and promotes health behaviors. C directly names a cultural factor. A — selective migration = a selection effect (who immigrates), not a cultural factor within the community. B — data limitations = methodological artifact, not a cultural explanation. D — contradicts the paradox definition (the paradox is that outcomes are BETTER despite lower SES, not worse).',
        wrongAnswerExplanations: {
          A: 'Selective migration (the "healthy immigrant effect"): immigrants are self-selected for health/motivation. This is a SELECTION effect, not a cultural protective factor operating within the immigrant community.',
          B: 'Data limitations (misclassification of race/ethnicity, underreporting of deaths in Hispanic Americans) would artificially make outcomes appear better. This is a methodological concern, not a cultural mechanism.',
          D: 'If outcomes were actually WORSE once SES is controlled, this would disprove the paradox, not explain it. The paradox IS that outcomes are better — D contradicts the phenomenon being explained.',
        },
        teachingPoint: 'Hispanic paradox (Markides & Coreil, 1986): Hispanic Americans have lower mortality from cardiovascular disease and some cancers despite lower average SES — paradoxical given SES-health gradient. Proposed mechanisms: (1) Familismo/social cohesion = cultural protective factor (social support buffers stress). (2) Healthy immigrant/salmon bias effect. (3) Cultural health behaviors (diet, alcohol use). (4) Data artifacts. The paradox challenges purely SES-deterministic models of health, suggesting cultural factors mediate the SES-health relationship.',
        relatedTopics: ['Hispanic paradox', 'familismo cultural protective factor', 'healthy immigrant effect', 'cultural factors health'],
      },
      {
        id: 'mcat5-ps-048',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p9',
        questionType: 'passage',
        discipline: 'Sociology',
        contentCategory: 'SOC: 9B',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'easy',
        question: 'A neighborhood lacks grocery stores but has many fast food restaurants. Residents have limited access to fresh fruits and vegetables. This neighborhood is BEST described as:',
        choices: [
          { label: 'A', text: 'A medically underserved area (MUA) — lacking adequate primary care access' },
          { label: 'B', text: 'A food desert — a feature of the built environment limiting access to nutritious food' },
          { label: 'C', text: 'A health professional shortage area (HPSA) — lacking primary care providers' },
          { label: 'D', text: 'A collectivistic community — group-oriented values impair individual healthcare seeking' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 2: "food deserts limit access to nutritious food" — explicitly named in the context of the built environment. A neighborhood lacking grocery stores but with only fast food = food desert = built environment feature limiting nutritious food access. B is correct. A — MUA refers to lack of primary CARE access (healthcare providers), not food access. C — HPSA = shortage of primary care health PROFESSIONALS; not about food. D — collectivism is a cultural orientation concept, not a feature of physical food access infrastructure.',
        wrongAnswerExplanations: {
          A: 'MUA (medically underserved area) = insufficient primary care relative to need — about healthcare access, not food access.',
          C: 'HPSA (health professional shortage area) = areas with an inadequate supply of primary care physicians relative to population — about physician workforce, not food infrastructure.',
          D: 'Collectivism is a cultural value orientation (group over individual). A neighborhood lacking grocery stores is a built environment issue (food desert), not a cultural orientation issue.',
        },
        teachingPoint: 'Built environment and health: walkability → physical activity → less obesity/CVD. Food deserts → poor nutrition → obesity, diabetes, CVD. Environmental pollution (toxic sites, traffic) clusters in low-income/minority neighborhoods → respiratory disease, cancer (environmental justice). Green spaces → mental health. The built environment is a structural social determinant that operates independently of individual health behaviors.',
        relatedTopics: ['food desert built environment', 'social determinants built environment', 'food access health', 'neighborhood health infrastructure'],
      },
      {
        id: 'mcat5-ps-049',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p9',
        questionType: 'passage',
        discipline: 'Sociology',
        contentCategory: 'SOC: 9B',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'A study finds that Black women have higher rates of maternal mortality than white women, even after controlling for income and education. Which explanation is MOST consistent with the passage?',
        choices: [
          { label: 'A', text: 'The SES-health gradient fully explains racial health disparities; this study must have inadequately controlled for SES' },
          { label: 'B', text: 'Racial health disparities — racism itself is a health determinant independent of SES, consistent with the weathering hypothesis' },
          { label: 'C', text: 'The Hispanic paradox — cultural protective factors are absent in Black women' },
          { label: 'D', text: 'Food deserts in Black communities are the sole explanation for maternal mortality disparities' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 3: "Black Americans have higher rates of cardiovascular disease, hypertension, diabetes, and maternal mortality than white Americans — even after controlling for SES in many analyses." The study controlling for income and education still finding Black-white disparities in maternal mortality = SES does not fully explain the gap. Paragraph from the broader passage context: racism itself is a health determinant (weathering hypothesis: cumulative race-based stressors → allostatic load → worse health outcomes). B is correct. A — the passage explicitly says disparities persist AFTER controlling for SES; calling the SES control inadequate is special pleading not supported by the passage. C — Hispanic paradox is about Hispanic Americans; not applicable here. D — food deserts contribute to some disparities but are not the "sole explanation" for maternal mortality specifically.',
        wrongAnswerExplanations: {
          A: 'The passage states disparities persist "even after controlling for SES in many analyses." The finding in the scenario is consistent with the passage; asserting the SES control was inadequate without evidence contradicts the passage.',
          C: 'The Hispanic paradox concerns Hispanic American health outcomes relative to expected SES-based outcomes. It does not address Black maternal mortality disparities.',
          D: 'Food deserts contribute to nutrition-related disparities. Maternal mortality involves obstetric care access, quality of care, implicit bias in clinical encounters, and cumulative stress from racism — not primarily food access. "Sole explanation" is never appropriate for a multifactorial disparity.',
        },
        teachingPoint: 'Black maternal mortality: Black women in the US are 2-3× more likely to die from pregnancy-related complications than white women. This disparity persists across income and education levels (even among college-educated Black women, risk remains elevated). Proposed mechanisms: implicit bias in clinical recognition of symptoms, racism-related allostatic load, disparate quality of care by facility, structural barriers. This is a leading health equity issue — not explained by individual factors alone.',
        relatedTopics: ['Black maternal mortality', 'racial health disparities SES control', 'weathering hypothesis maternal mortality', 'racism health determinant'],
      },
      {
        id: 'mcat5-ps-050',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p9',
        questionType: 'passage',
        discipline: 'Sociology',
        contentCategory: 'SOC: 9B',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'Social determinants of health account for approximately 30-55% of health outcomes. This finding has which of the following implications for medical practice?',
        choices: [
          { label: 'A', text: 'Individual clinical care (medications, procedures) is sufficient to eliminate health disparities' },
          { label: 'B', text: 'Addressing only biological disease without attending to social determinants leaves a substantial driver of health outcomes unaddressed' },
          { label: 'C', text: 'Physicians bear no responsibility for patients\' social circumstances, as these are outside the medical domain' },
          { label: 'D', text: 'Social determinants explain 100% of health disparities; genetics plays no role' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 2: "Social determinants of health — including income, education, housing, neighborhood safety, and social support — account for approximately 30-55% of health outcomes." If social factors drive 30-55% of outcomes, then addressing only biological disease (the remaining fraction) leaves a major driver unaddressed. B captures the implication: comprehensive care requires attending to social determinants alongside clinical disease management. A — clinical care alone cannot eliminate disparities because it doesn\'t address the 30-55% social determinant component. C — the medical community increasingly recognizes that physicians have a role in addressing social determinants (SDOH screening, community referrals). D — 30-55% ≠ 100%; genetics and other biological factors also matter.',
        wrongAnswerExplanations: {
          A: 'If social determinants drive 30-55% of outcomes, individual clinical care (biological model alone) cannot eliminate disparities. A contradicts the magnitude of the social determinants\'s contribution.',
          C: 'Contemporary medicine recognizes physician responsibility to screen for SDOH (food insecurity, housing) and connect patients to resources. SDOH are not "outside the medical domain" — they are core drivers of patient outcomes.',
          D: 'Social determinants account for 30-55%, not 100%. Genetics, biological factors, healthcare access, and individual behaviors all contribute. A multifactorial model is accurate.',
        },
        teachingPoint: 'SDOH and clinical medicine: WHO estimates 30-55% of health outcomes determined by social/economic factors. Remaining: healthcare access and quality (~10-20%), individual behaviors (~30%), genetics (~20%). Implication: "pill for every ill" is insufficient. Clinical best practice: screen for food insecurity (Hunger Vital Sign), housing instability, transportation barriers, interpersonal violence. Community health worker referrals, medical-legal partnerships, community benefit investments are structural responses.',
        relatedTopics: ['social determinants health outcomes', 'SDOH clinical practice', 'social factors health percentage', 'biopsychosocial model practice'],
      },
      {
        id: 'mcat5-ps-051',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p9',
        questionType: 'passage',
        discipline: 'Sociology',
        contentCategory: 'SOC: 9B',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'easy',
        question: 'Rural communities face healthcare provider shortages and limited specialty care. Federal programs designate such areas as HPSAs or MUAs. Which population health strategy would MOST directly address physician shortages in rural areas?',
        choices: [
          { label: 'A', text: 'Increasing the number of medical specialists trained in urban academic medical centers' },
          { label: 'B', text: 'Loan repayment programs and service scholarships that incentivize physicians to practice in rural and underserved areas' },
          { label: 'C', text: 'Advising rural patients to relocate to urban areas for better healthcare access' },
          { label: 'D', text: 'Expanding telemedicine for cosmetic procedures only' },
        ],
        correctAnswer: 'B',
        explanation: 'Rural physician shortages are driven by limited financial incentives and career factors that deter physicians from rural practice. Loan repayment programs (National Health Service Corps) and service scholarships reduce medical school debt in exchange for service in HPSAs/MUAs — directly incentivizing physicians to work in underserved areas. B directly addresses the workforce shortage. A — training more urban specialists does not distribute physicians to rural areas (where primary care shortages are the primary problem). C — advising patients to relocate is not a population health strategy; it is impractical and ignores structural barriers. D — cosmetic telemedicine does not address primary care access shortages in rural communities.',
        wrongAnswerExplanations: {
          A: 'Training more urban specialists would increase urban specialist supply but not distribute primary care physicians to rural areas. Rural shortages are primarily in primary care, not urban specialty training volume.',
          C: 'Advising rural patients to relocate is not a population health intervention — it places the burden on the patient, is not feasible for most, and ignores why rural communities lack healthcare rather than fixing the shortage.',
          D: 'Telemedicine for cosmetic procedures does not address access to primary care, emergency care, or chronic disease management — the core healthcare needs of rural underserved populations.',
        },
        teachingPoint: 'HPSA/MUA workforce solutions: National Health Service Corps (NHSC) — loan repayment and scholarships for primary care providers who commit to service in HPSAs (typical commitment: 2 years). J-1 visa waiver programs: international medical graduates can waive the visa requirement to return home by practicing in underserved areas. Community health centers (FQHCs): federally qualified health centers provide sliding-scale primary care in underserved areas. Telemedicine: can address SOME specialty shortages but requires broadband infrastructure.',
        relatedTopics: ['HPSA MUA rural healthcare', 'rural physician shortage', 'National Health Service Corps', 'rural health workforce strategy'],
      },
    ],
  },
]
