import type { MCATPassage } from '../types'

// Form 5 P/S — Passages 1–5 (IDs mcat5-ps-001 through mcat5-ps-026)

export const psPassages5_01to05: MCATPassage[] = [
  {
    id: 'f5-ps-p1',
    sectionId: 'psych-soc',
    passageNumber: 1,
    title: 'Social Cognition: Attribution and Perception',
    text: `Social cognition encompasses the mental processes people use to perceive, interpret, and respond to other people and social situations. A central domain of social cognition is attribution — the process of explaining the causes of behavior. Fritz Heider's foundational work distinguished internal attributions (explaining behavior by reference to personal dispositions, traits, or abilities) from external attributions (explaining behavior by reference to situational factors).

The fundamental attribution error (FAE) describes the tendency to overweight dispositional explanations and underweight situational factors when explaining others' behavior. Classic demonstrations include the quiz show study (Ross, 1977), in which observers rated questioners as more knowledgeable than contestants even though the questioner role was randomly assigned — a purely situational advantage. Actors and observers show a systematic difference: the actor-observer bias holds that we attribute our own behavior to situations (because we see our own situational context clearly) while attributing others' behavior to dispositions (because we see only others' behavior, not their context).

Self-serving bias refers to the tendency to attribute our successes to internal factors (ability, effort) and our failures to external factors (bad luck, unfair circumstances). This protects self-esteem. Cultural variation exists: collectivistic cultures show weaker FAE and self-serving bias, possibly because they prioritize social context and group interdependence over individual agency.

A researcher studies attribution patterns in medical contexts, finding that physicians systematically attribute patient non-adherence to patient character (dispositional) rather than to social determinants of health — barriers like cost, transportation, and work schedules (situational). This attribution pattern has consequences for how physicians approach the clinical encounter.`,
    questions: [
      {
        id: 'mcat5-ps-001',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p1',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'PSYCH: 7A',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 2',
        difficulty: 'easy',
        question: 'When physicians attribute patient non-adherence to patient character rather than to social barriers, this BEST illustrates:',
        choices: [
          { label: 'A', text: 'Self-serving bias — physicians protect their own self-esteem by blaming patients' },
          { label: 'B', text: 'The fundamental attribution error — overweighting dispositional factors and underweighting situational factors when explaining others\' behavior' },
          { label: 'C', text: 'Actor-observer bias — physicians see their own situational context but not patients\'' },
          { label: 'D', text: 'Collectivistic cultural attribution — emphasizing group context over individual agency' },
        ],
        correctAnswer: 'B',
        explanation: 'The physicians are explaining others\' behavior (patient non-adherence) by attributing it to character (disposition) rather than situational barriers (cost, transportation, work schedules). This is the textbook definition of FAE: overweighting dispositional explanations and underweighting situational factors for others\' behavior. B is correct. A — self-serving bias involves attributions about one\'s own successes and failures. C — actor-observer bias: physicians ARE the observers (seeing patient character), not actors. But the FAE is the broader principle. D — collectivistic cultures show WEAKER FAE; this example shows strong FAE.',
        wrongAnswerExplanations: {
          A: 'Self-serving bias: I attribute MY successes to internal factors and MY failures to external. This involves physicians attributing PATIENT behavior (others\'), not physician behavior — not self-serving bias.',
          C: 'Actor-observer bias is a form of FAE specifically contrasting first-person vs. third-person perspectives. The clinical example is specifically about dispositional vs. situational attribution for others\' behavior — FAE is the more direct answer.',
          D: 'Collectivistic attribution emphasizes situational/social context, which would REDUCE FAE. The passage says collectivistic cultures show weaker FAE. This example shows strong FAE — the opposite.',
        },
        teachingPoint: 'FAE in medicine: clinicians systematically overattribute patient behavior (non-adherence, unhealthy choices) to character while underestimating social determinants of health (poverty, lack of insurance, food deserts, transportation). Recognizing FAE is clinically important — it can lead to victim-blaming and missed opportunities for structural intervention.',
        relatedTopics: ['fundamental attribution error', 'FAE medicine', 'dispositional vs situational', 'attribution bias'],
      },
      {
        id: 'mcat5-ps-002',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p1',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'PSYCH: 7A',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'A medical student fails her first clinical exam and tells herself "the questions were unfair and poorly written." What attribution pattern does this BEST illustrate?',
        choices: [
          { label: 'A', text: 'Fundamental attribution error — she overweights situational factors for her own behavior' },
          { label: 'B', text: 'Self-serving bias — attributing failure to an external factor (poorly written questions) to protect self-esteem' },
          { label: 'C', text: 'Actor-observer bias — she attributes her own behavior to dispositional factors' },
          { label: 'D', text: 'Internal attribution — she credits her own effort as the cause of failure' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 3: "Self-serving bias refers to the tendency to attribute our successes to internal factors...and our failures to external factors (bad luck, unfair circumstances). This protects self-esteem." Attributing exam failure to "unfair, poorly written questions" = external attribution for own failure = self-serving bias. B is correct. A — FAE applies to explaining OTHERS\' behavior; this is about her own failure. C — actor-observer bias would have her attributing her OWN behavior to dispositional factors — the opposite of what she does here. D — she is making an external (not internal) attribution.',
        wrongAnswerExplanations: {
          A: 'FAE is about explaining OTHERS\' behavior. When someone explains their own behavior, the relevant bias is actor-observer or self-serving bias, not FAE.',
          C: 'Actor-observer bias predicts that actors attribute their own behavior to SITUATIONAL factors. She IS doing that (external attribution). But actor-observer bias describes a systematic contrast with how observers attribute; the specific protective function here (protecting self-esteem for failure) is self-serving bias.',
          D: 'Internal attribution = crediting personal ability or effort. "Unfair questions" = external attribution. D is incorrect.',
        },
        teachingPoint: 'Self-serving bias = asymmetric attribution for own outcomes: success → internal (ability, effort); failure → external (luck, difficulty, unfairness). Function: ego protection. Distinguished from actor-observer bias (which applies to self vs. other contrast, not success vs. failure contrast). Medical relevance: physicians may attribute their own errors to external factors and successes to their skill.',
        relatedTopics: ['self-serving bias', 'external attribution failure', 'ego protection', 'attribution own behavior'],
      },
      {
        id: 'mcat5-ps-003',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p1',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'PSYCH: 7A',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'The quiz show study (Ross, 1977) found that observers rated questioners as more knowledgeable even though questioner roles were randomly assigned. What is the KEY methodological strength of random assignment in this study?',
        choices: [
          { label: 'A', text: 'It ensures questioners are actually more knowledgeable, validating the observers\' attributions' },
          { label: 'B', text: 'It eliminates the possibility that pre-existing differences in knowledge caused the observers\' ratings, isolating the situational advantage as the only explanation for the rating difference' },
          { label: 'C', text: 'It prevents demand characteristics from influencing participants\' behavior' },
          { label: 'D', text: 'It increases ecological validity by matching real-world quiz show conditions' },
        ],
        correctAnswer: 'B',
        explanation: 'Random assignment ensures that participants\' pre-existing characteristics (intelligence, knowledge) are distributed equally across conditions. If questioner roles are randomly assigned, any knowledge difference between questioners and contestants is due to the role advantage (getting to choose questions in your own area of expertise), not pre-existing differences. This allows researchers to conclude that observers\' dispositional attributions are erroneous — the questioner advantage is purely situational. B captures this logic. A — the point is that observers rate questioners as MORE knowledgeable when they are NOT necessarily so (random assignment proves the advantage is artificial). C — demand characteristics are about participants guessing study goals; random assignment addresses confounding, not demand characteristics. D — quiz show conditions are artificial; random assignment addresses confounding, not ecological validity.',
        wrongAnswerExplanations: {
          A: 'Random assignment proves questioners are NOT necessarily more knowledgeable (roles were random). The study shows observers FALSELY attribute greater knowledge to questioners — that\'s the demonstration of FAE.',
          C: 'Demand characteristics: participants acting according to perceived study expectations. Random assignment controls for CONFOUNDING variables (pre-existing differences), not demand characteristics specifically.',
          D: 'Ecological validity = how well the lab setting reflects real-world conditions. The quiz show is artificial; random assignment addresses internal validity (causal inference), not external validity (ecological).',
        },
        teachingPoint: 'Random assignment function: eliminates systematic differences between groups from pre-existing variables (individual differences), allowing causal conclusions. In the quiz show study: without random assignment, questioners might actually be smarter (selection effect). With random assignment, any apparent "advantage" is purely situational — demonstrating that observers commit FAE by treating a situational advantage as a dispositional trait.',
        relatedTopics: ['random assignment research methods', 'confounding control', 'FAE quiz show', 'internal validity'],
      },
      {
        id: 'mcat5-ps-004',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p1',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'PSYCH: 7A',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'Collectivistic cultures show weaker FAE than individualistic cultures. Which explanation is MOST consistent with the passage?',
        choices: [
          { label: 'A', text: 'People in collectivistic cultures have lower intelligence and cannot make dispositional attributions' },
          { label: 'B', text: 'Collectivistic cultures prioritize social context and group interdependence, leading people to naturally consider situational factors when explaining behavior' },
          { label: 'C', text: 'Individualistic cultures have fewer social relationships, reducing opportunities for attribution errors' },
          { label: 'D', text: 'Collectivistic cultures show weaker FAE because they have a stronger self-serving bias' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 3: "Collectivistic cultures show weaker FAE and self-serving bias, possibly because they prioritize social context and group interdependence over individual agency." B matches: emphasis on social context → more attention to situational factors → weaker FAE. A is factually wrong and not from the passage. C inverts the logic: more social relationships → more attention to context → less FAE. D contradicts the passage (collectivistic cultures show weaker BOTH FAE and self-serving bias).',
        wrongAnswerExplanations: {
          A: 'Intelligence is not mentioned in the passage and would not explain cultural differences in attribution style. This is factually incorrect and unsupported.',
          C: 'Collectivistic cultures typically have denser social networks; individualistic cultures emphasize individual autonomy. More social relationships → more attention to relational context → less FAE. C inverses the relationship.',
          D: 'The passage states collectivistic cultures show weaker BOTH FAE AND self-serving bias — not a trade-off between them.',
        },
        teachingPoint: 'Cultural variation in attribution: Individualistic (Western) cultures → FAE stronger → dispositional explanations favored. Collectivistic (East Asian) cultures → FAE weaker → situational/contextual explanations more salient. Research (Norenzayan, Nisbett): East Asian students more likely to explain behavior with context; American students with traits. Explains cross-cultural differences in social perception.',
        relatedTopics: ['cultural variation FAE', 'collectivistic individualistic attribution', 'social context FAE', 'cross-cultural psychology'],
      },
      {
        id: 'mcat5-ps-005',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p1',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'PSYCH: 7A',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 2',
        difficulty: 'easy',
        question: 'The actor-observer bias predicts that a student who trips in the hallway will:',
        choices: [
          { label: 'A', text: 'Attribute their tripping to clumsiness (dispositional) while observers also attribute it to clumsiness' },
          { label: 'B', text: 'Attribute their tripping to the uneven floor (situational) while observers attribute it to clumsiness (dispositional)' },
          { label: 'C', text: 'Attribute their tripping to clumsiness (dispositional) while observers attribute it to the floor (situational)' },
          { label: 'D', text: 'Not make any attribution because they are too embarrassed to reflect on the cause' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 2: "actor-observer bias holds that we attribute our own behavior to situations (because we see our own situational context clearly) while attributing others\' behavior to dispositions (because we see only others\' behavior, not their context)." The student (actor) sees the floor → attributes to situational factor (uneven floor). Observers see only the behavior → attribute to disposition (clumsiness). B matches. C inverts the pattern (the actor wrongly makes dispositional self-attribution in C). A has both attributing to disposition — observers would, but the actor would not (actor-observer bias predicts situational self-attribution).',
        wrongAnswerExplanations: {
          A: 'Actor-observer bias predicts that the ACTOR makes a SITUATIONAL attribution (sees the floor), not dispositional. Only observers make dispositional attributions.',
          C: 'C inverts the pattern: actor → dispositional (clumsiness) is wrong; observers → situational is wrong. The correct pattern: actor → situational; observer → dispositional.',
          D: 'The passage discusses systematic attribution patterns, not avoidance of attribution due to embarrassment. Actor-observer bias predicts a specific asymmetry in attribution, not attribution avoidance.',
        },
        teachingPoint: 'Actor-observer bias mechanism: actors have access to their situational context (I see the floor was wet) → situational attributions. Observers have limited information (they see the behavior, not the situation) → dispositional attributions. Both actor and observer make the same perceptual error but in opposite directions. This asymmetry is reduced when observers have access to situational information.',
        relatedTopics: ['actor-observer bias', 'situational self-attribution', 'observer dispositional attribution', 'attribution asymmetry'],
      },
      {
        id: 'mcat5-ps-006',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p1',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'PSYCH: 7A',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'A study finds that showing physicians detailed information about a patient\'s social circumstances (income, housing instability, transportation barriers) REDUCES their attribution of non-adherence to character. This finding is MOST consistent with:',
        choices: [
          { label: 'A', text: 'The actor-observer bias — physicians now become "actors" in the patient\'s situation' },
          { label: 'B', text: 'The principle that FAE is reduced when situational information is made salient and available to the observer' },
          { label: 'C', text: 'Self-serving bias — physicians protect themselves by blaming the system' },
          { label: 'D', text: 'Collectivism — providing social information converts physicians to collectivistic thinkers' },
        ],
        correctAnswer: 'B',
        explanation: 'The FAE is partly caused by lack of situational information (observers only see behavior). When situational information (social circumstances) is made explicitly available, observers can correct their dispositional bias — they consider the situational explanation. B: providing situational information reduces FAE by making situational factors salient. A — physicians don\'t become actors (patients\'); they remain observers with better situational information. C — self-serving bias is about one\'s own outcomes; physicians correcting their attribution about patients is not self-serving. D — providing social information is not the same as converting to collectivism.',
        wrongAnswerExplanations: {
          A: 'Actor-observer bias involves first-person vs. third-person perspective. Physicians remain observers; gaining access to situational information doesn\'t make them "actors."',
          C: 'Self-serving bias: attributing own successes/failures protectively. Physicians revising patient non-adherence attributions is not about physician self-esteem or outcomes.',
          D: 'Collectivism is a cultural value orientation, not something induced by providing information in a study. The explanation is about information availability affecting attribution, not cultural orientation.',
        },
        teachingPoint: 'FAE reduction: the error is strongest when situational information is absent. When observers have rich situational context, they correct toward situational attributions. This is a key insight for medical education: training physicians to seek social history systematically reduces dispositional over-attribution. "What barriers does this patient face?" shifts attribution toward situational factors — more accurate and more useful clinically.',
        relatedTopics: ['FAE reduction situational information', 'attribution correction', 'physician patient attribution', 'social determinants health attribution'],
      },
    ],
  },
  {
    id: 'f5-ps-p2',
    sectionId: 'psych-soc',
    passageNumber: 2,
    title: 'Memory Systems and Encoding',
    text: `Memory is not a single system but a collection of distinct neurological processes. Atkinson and Shiffrin's modal model distinguishes sensory memory (brief, high-capacity, modality-specific), short-term memory (STM; limited capacity ~7±2 items; ~18-30 seconds without rehearsal), and long-term memory (LTM; theoretically unlimited capacity and duration). Baddeley's working memory model replaced the unitary STM with a multicomponent system: a central executive (attentional control), a phonological loop (verbal/acoustic information), a visuospatial sketchpad (visual/spatial information), and an episodic buffer (integration of information).

Long-term memory is divided into declarative (explicit) memory — accessible to conscious awareness — and non-declarative (implicit) memory — unconscious. Declarative memory includes episodic memory (autobiographical events with temporal and spatial context) and semantic memory (general knowledge, facts, and concepts independent of specific episodes). Non-declarative memory includes procedural memory (skills and habits), priming, and classical conditioning.

The hippocampus is critical for the formation of new declarative memories (anterograde amnesia follows hippocampal damage). Procedural memory and priming are largely independent of the hippocampus (spared in amnesic patients). The amygdala modulates emotional memory consolidation: emotionally arousing events are better remembered (flashbulb memories), and amygdala activation during encoding predicts later memory strength.

Levels of processing theory (Craik and Lockhart) holds that deeper encoding leads to better retention: shallow processing (structural/phonological features) yields weak traces; deep processing (semantic/meaningful elaboration) yields strong, durable traces.`,
    questions: [
      {
        id: 'mcat5-ps-007',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p2',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'PSYCH: 6A',
        foundationalConcept: 'FC 6',
        scientificSkill: 'Skill 2',
        difficulty: 'easy',
        question: 'A patient sustains damage to the hippocampus. Which type of memory would be MOST impaired?',
        choices: [
          { label: 'A', text: 'Procedural memory — skills like riding a bicycle' },
          { label: 'B', text: 'Priming — faster responses to recently encountered stimuli' },
          { label: 'C', text: 'Formation of new episodic and semantic memories (anterograde amnesia for declarative memory)' },
          { label: 'D', text: 'Sensory memory — brief iconic or echoic traces' },
        ],
        correctAnswer: 'C',
        explanation: 'Paragraph 3: "The hippocampus is critical for the formation of new declarative memories (anterograde amnesia follows hippocampal damage)." Declarative memory = episodic + semantic. Hippocampal damage → impaired formation of new declarative memories. C is correct. A — procedural memory and B — priming are "largely independent of the hippocampus (spared in amnesic patients)." D — sensory memory is a pre-hippocampal stage; iconic/echoic traces are not hippocampus-dependent.',
        wrongAnswerExplanations: {
          A: 'Procedural memory (skill learning) is hippocampus-independent. The famous case of H.M. (bilateral hippocampal removal) showed preserved procedural learning (mirror drawing improved daily despite no memory of practicing).',
          B: 'Priming is also hippocampus-independent (implicit/non-declarative). H.M. showed normal priming despite severe anterograde amnesia for declarative memories.',
          D: 'Sensory memory (iconic ~0.5 sec, echoic ~3-4 sec) is a very early pre-mnemonic stage. It does not involve the hippocampus — it is a brief perceptual trace in sensory cortex.',
        },
        teachingPoint: 'Memory system dissociation by hippocampal damage: IMPAIRED = declarative (episodic + semantic). SPARED = procedural, priming, classical conditioning (these are non-declarative/implicit). Classic case: H.M. (Henry Molaison): bilateral medial temporal lobe removal → severe anterograde amnesia for declarative memories, preserved procedural learning and priming. Confirmed hippocampus = critical for declarative memory formation.',
        relatedTopics: ['hippocampus declarative memory', 'anterograde amnesia', 'HM case study', 'memory dissociation'],
      },
      {
        id: 'mcat5-ps-008',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p2',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'PSYCH: 6A',
        foundationalConcept: 'FC 6',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'According to levels of processing theory, which study strategy would produce the BEST long-term retention of material?',
        choices: [
          { label: 'A', text: 'Repeating each word\'s spelling aloud (phonological processing)' },
          { label: 'B', text: 'Noting whether each word is printed in uppercase or lowercase (structural processing)' },
          { label: 'C', text: 'Creating a sentence using each word and relating it to a personal experience (semantic elaboration)' },
          { label: 'D', text: 'Counting the number of vowels in each word (phonological/structural processing)' },
        ],
        correctAnswer: 'C',
        explanation: 'Paragraph 4: "deeper encoding leads to better retention: shallow processing (structural/phonological features) yields weak traces; deep processing (semantic/meaningful elaboration) yields strong, durable traces." C = semantic elaboration + personal relevance = deepest processing → best retention. A and D = phonological/structural = shallow. B = structural (uppercase/lowercase) = shallowest.',
        wrongAnswerExplanations: {
          A: 'Phonological processing (sounds, spelling) = shallow level. Better than pure structural, but less durable than semantic processing.',
          B: 'Structural processing (visual features like case) = shallowest level. Poorest retention.',
          D: 'Counting vowels = structural/phonological analysis = shallow processing. Produces weaker memory traces.',
        },
        teachingPoint: 'Levels of processing (Craik & Lockhart 1972): Shallow → Structural (visual features) → Phonological (sound, rhyme) → Deep Semantic (meaning, elaboration). Deeper = more connections made in LTM = more retrieval cues = better recall. Applied: elaborative interrogation ("why does this make sense?"), self-referencing effect (relating to personal experience), semantic encoding (meaning-based study) all improve memory vs. rote repetition.',
        relatedTopics: ['levels of processing', 'semantic elaboration memory', 'deep vs shallow processing', 'Craik Lockhart'],
      },
      {
        id: 'mcat5-ps-009',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p2',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'PSYCH: 6A',
        foundationalConcept: 'FC 6',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'Emotionally arousing events are better remembered. The amygdala modulates this effect. A patient with bilateral amygdala damage but intact hippocampus would most likely show:',
        choices: [
          { label: 'A', text: 'No memory for emotional or neutral events' },
          { label: 'B', text: 'Normal memory for neutral events; reduced enhancement of memory for emotional events' },
          { label: 'C', text: 'Enhanced memory for emotional events because the hippocampus compensates for amygdala damage' },
          { label: 'D', text: 'Normal memory for emotional events because the hippocampus handles emotional memory' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 3: "The amygdala modulates emotional memory consolidation: emotionally arousing events are better remembered (flashbulb memories), and amygdala activation during encoding predicts later memory strength." With intact hippocampus and damaged amygdala: hippocampus handles formation of new declarative memories → neutral events remembered normally. Amygdala modulates the ENHANCEMENT of memory for emotional events → without amygdala, the emotional boost is absent. B: normal memory for neutral; reduced enhancement for emotional. A — neutral memory is intact (hippocampus intact). C — hippocampus does not compensate for amygdala\'s emotional modulation. D — amygdala, not hippocampus, is the emotional memory modulator.',
        wrongAnswerExplanations: {
          A: 'Intact hippocampus allows normal formation of declarative memories, including neutral events. Only the emotional enhancement is lost with amygdala damage.',
          C: 'The hippocampus and amygdala have distinct roles. Hippocampus forms declarative memories; amygdala modulates emotional salience of those memories. The hippocampus does not take over amygdala\'s emotional modulation.',
          D: 'The hippocampus is the declarative memory system. The amygdala is the emotional modulator. Without the amygdala, emotionally arousing events lose their mnemonic advantage — they are no longer better remembered than neutral events.',
        },
        teachingPoint: 'Amygdala-hippocampus interaction: hippocampus encodes episodic/semantic content; amygdala activates during emotional events → releases norepinephrine → strengthens hippocampal consolidation via basolateral amygdala projections. Without amygdala: memories still form (hippocampus intact) but emotional memories lose their enhancement (Cahill et al., 1994 — propranolol beta-blocker study). Clinical application: PTSD involves exaggerated amygdala-mediated emotional memory consolidation.',
        relatedTopics: ['amygdala emotional memory', 'emotional memory enhancement', 'amygdala hippocampus interaction', 'memory consolidation emotion'],
      },
      {
        id: 'mcat5-ps-010',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p2',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'PSYCH: 6A',
        foundationalConcept: 'FC 6',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'Baddeley\'s model replaces the unitary STM with multiple components. Which component would be MOST active when a surgeon mentally rotates a 3D anatomy image while planning a procedure?',
        choices: [
          { label: 'A', text: 'Phonological loop — for rehearsing verbal anatomy terminology' },
          { label: 'B', text: 'Visuospatial sketchpad — for mental manipulation of spatial and visual information' },
          { label: 'C', text: 'Episodic buffer — for integrating procedural memory with episodic experience' },
          { label: 'D', text: 'Central executive — for managing attention without engaging visual or verbal resources' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 1: the visuospatial sketchpad handles "visual/spatial information." Mental rotation of a 3D anatomy image = visual + spatial processing. B is correct. A — the phonological loop handles verbal/acoustic information; mental rotation is not verbal. C — the episodic buffer integrates information across subsystems and LTM; while it may be partially involved, the PRIMARY active component for 3D spatial manipulation is the visuospatial sketchpad. D — the central executive manages attentional control and coordinates the other components; it doesn\'t specialize in visual/spatial processing.',
        wrongAnswerExplanations: {
          A: 'The phonological loop handles verbal/acoustic material (inner speech, phonological rehearsal). Mental rotation of 3D images is a spatial, not verbal, task.',
          C: 'The episodic buffer integrates information from LTM and other working memory components. It may be recruited when integrating past surgical experience with current planning, but the primary processing of 3D spatial manipulation is in the visuospatial sketchpad.',
          D: 'The central executive directs attention and coordinates subsystems but does not itself perform visual-spatial processing. The surgeon would use the central executive to DIRECT the visuospatial sketchpad, but the sketchpad is the component actively processing the visual-spatial content.',
        },
        teachingPoint: 'Baddeley\'s working memory: Central executive = attentional control hub. Phonological loop = verbal/auditory (inner speech). Visuospatial sketchpad = visual/spatial (mental rotation, navigation). Episodic buffer = integrates across subsystems and LTM. Clinical relevance: dual-task studies show these are largely separate (doing spatial + verbal tasks simultaneously is easier than two verbal or two spatial tasks).',
        relatedTopics: ['Baddeley working memory', 'visuospatial sketchpad', 'phonological loop', 'working memory components'],
      },
      {
        id: 'mcat5-ps-011',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p2',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'PSYCH: 6A',
        foundationalConcept: 'FC 6',
        scientificSkill: 'Skill 2',
        difficulty: 'easy',
        question: 'Which memory type is BEST illustrated by knowing that "Paris is the capital of France" without being able to remember where or when you learned this fact?',
        choices: [
          { label: 'A', text: 'Episodic memory — autobiographical event with temporal context' },
          { label: 'B', text: 'Procedural memory — skill-based, implicit knowledge' },
          { label: 'C', text: 'Semantic memory — general knowledge independent of specific learning episodes' },
          { label: 'D', text: 'Priming — faster processing of related concepts' },
        ],
        correctAnswer: 'C',
        explanation: 'Paragraph 2: "semantic memory (general knowledge, facts, and concepts independent of specific episodes)." "Paris is the capital of France" = a factual piece of world knowledge with no memory of the specific episode when it was learned. C is correct. A — episodic memory involves specific autobiographical events with temporal and spatial context ("I learned this in 4th grade during a geography lesson"). B — procedural memory = motor/cognitive skills (implicit, unconscious). D — priming = faster processing of related stimuli after prior exposure.',
        wrongAnswerExplanations: {
          A: 'Episodic memory would be: "I remember being in 4th grade when Ms. Smith taught us that Paris is the capital of France." Knowing the fact WITHOUT the episodic context = semantic memory.',
          B: 'Procedural memory is for skills and habits (riding a bike, typing, surgical suturing). Factual knowledge about geography is declarative, not procedural.',
          D: 'Priming is an implicit phenomenon: prior exposure to a stimulus speeds processing of related stimuli. Knowing a capital city fact is not about processing speed — it is a declarative knowledge fact.',
        },
        teachingPoint: 'Episodic vs. semantic: Episodic = "what happened to me, where and when." Semantic = "what I know about the world" (decontextualized from specific learning episode). Clinical: early Alzheimer\'s disproportionately impairs episodic memory initially; semantic memory may be relatively preserved longer. Some patients can recall general facts but not when/where they learned them.',
        relatedTopics: ['semantic memory', 'episodic vs semantic', 'declarative memory types', 'general knowledge memory'],
      },
    ],
  },
  {
    id: 'f5-ps-p3',
    sectionId: 'psych-soc',
    passageNumber: 3,
    title: 'Social Stratification and Health Disparities',
    text: `Social stratification refers to the hierarchical organization of society into layers (strata) based on socioeconomic status (SES), race, gender, and other markers of social position. SES is typically operationalized through income, education, and occupational prestige. Stratification is consequential for health: lower SES is associated with higher rates of morbidity, mortality, and mental illness across virtually all health outcomes studied.

Several mechanisms link SES to health. Material deprivation (lack of access to nutritious food, safe housing, medical care) operates directly. Psychosocial pathways operate indirectly: chronic exposure to subordinate social positions activates the hypothalamic-pituitary-adrenal (HPA) axis and sympatho-adrenomedullary system, elevating cortisol and catecholamines, which over time contribute to cardiovascular disease, immune dysregulation, and accelerated cellular aging. Allostatic load — the cumulative physiological burden of chronic stress — is elevated in lower-SES populations.

Race intersects with class in complex ways. Racial health disparities persist even after controlling for SES, suggesting that racism itself is a health determinant. The weathering hypothesis (Geronimus) proposes that cumulative exposure to race-based stressors leads to accelerated biological aging in Black Americans — evidenced by higher allostatic load and earlier onset of chronic diseases relative to white Americans of comparable SES.

Sociological perspectives on stratification differ: functionalism holds that inequality is inevitable and serves social stability (differential rewards motivate people to fill important roles); conflict theory (Marx, Weber) holds that stratification reflects power asymmetries that serve elite interests; symbolic interactionism examines how daily interactions reproduce and reinforce status hierarchies.`,
    questions: [
      {
        id: 'mcat5-ps-012',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p3',
        questionType: 'passage',
        discipline: 'Sociology',
        contentCategory: 'SOC: 9A',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'easy',
        question: 'The weathering hypothesis proposes that Black Americans experience accelerated biological aging relative to white Americans of comparable SES. This finding is significant because it suggests:',
        choices: [
          { label: 'A', text: 'Racial health disparities are entirely explained by socioeconomic differences' },
          { label: 'B', text: 'Racism itself — independent of SES — contributes to health disparities through chronic stress exposure' },
          { label: 'C', text: 'Allostatic load is only elevated in low-SES populations, not in middle-class Black Americans' },
          { label: 'D', text: 'Biological differences between racial groups are the primary cause of health disparities' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 3: "Racial health disparities persist even after controlling for SES, suggesting that racism itself is a health determinant. The weathering hypothesis...proposes that cumulative exposure to race-based stressors leads to accelerated biological aging in Black Americans." Controlling for SES and still finding disparities means SES doesn\'t fully explain the gap — racism-related stress is an additional determinant. B is correct. A — the passage explicitly says disparities PERSIST after controlling for SES (= not entirely explained by SES). C — the hypothesis applies to Black Americans at comparable SES levels (contradicts C). D — the passage is about race-based SOCIAL stressors, not biological/genetic differences.',
        wrongAnswerExplanations: {
          A: 'The passage explicitly states disparities persist "even after controlling for SES" — meaning SES does NOT fully explain racial health disparities. A contradicts the passage.',
          C: 'The weathering hypothesis was developed specifically to explain disparities at comparable SES levels. Middle-class Black Americans also experience elevated allostatic load — a key finding of the hypothesis.',
          D: 'The passage discusses race-based SOCIAL stressors (racism, discrimination) as the mechanism — not biological differences. "Race" in medicine is primarily a social construct; biological explanations without social context are not supported by this passage.',
        },
        teachingPoint: 'Weathering hypothesis (Arline Geronimus): cumulative race-based stressors → chronic HPA/SAM axis activation → allostatic load → accelerated aging. Evidence: telomere shortening, higher allostatic load scores in Black Americans vs. white Americans at same SES. Clinical application: Black women face higher preterm birth rates and worse maternal outcomes across SES — the stress of racism, not SES alone, explains part of this.',
        relatedTopics: ['weathering hypothesis', 'racial health disparities SES', 'allostatic load race', 'racism health determinant'],
      },
      {
        id: 'mcat5-ps-013',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p3',
        questionType: 'passage',
        discipline: 'Sociology',
        contentCategory: 'SOC: 9A',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'Allostatic load is described as "the cumulative physiological burden of chronic stress." Which physiological mechanism MOST directly links chronic psychosocial stress to cardiovascular disease?',
        choices: [
          { label: 'A', text: 'Elevated cortisol and catecholamines from chronic HPA and SAM activation → hypertension, inflammation, and atherosclerosis' },
          { label: 'B', text: 'Reduced HPA axis activity → insufficient cortisol → immune overactivation' },
          { label: 'C', text: 'Chronic stress activates the parasympathetic nervous system → increased heart rate' },
          { label: 'D', text: 'Stress hormones inhibit the sympathetic nervous system, reducing cardiovascular strain' },
        ],
        correctAnswer: 'A',
        explanation: 'Paragraph 2: "chronic exposure to subordinate social positions activates the hypothalamic-pituitary-adrenal (HPA) axis and sympatho-adrenomedullary system, elevating cortisol and catecholamines, which over time contribute to cardiovascular disease, immune dysregulation, and accelerated cellular aging." Cortisol → hypertension, glucose dysregulation; catecholamines (epinephrine, norepinephrine) → increased heart rate, blood pressure, inflammation → endothelial damage → atherosclerosis. A captures this mechanism. B inverts — chronic stress ELEVATES HPA activity, not reduces it. C — chronic stress activates SYMPATHETIC, not parasympathetic. D inverts — stress hormones ACTIVATE sympathetic.',
        wrongAnswerExplanations: {
          B: 'Chronic psychosocial stress → ELEVATED HPA axis activity → more cortisol (not less). Reduced HPA would mean insufficient stress response, which is a different problem (Addison\'s disease pattern).',
          C: 'Chronic stress activates the SYMPATHETIC nervous system (fight/flight: increased HR, BP, vasoconstriction). The parasympathetic (rest-and-digest) is typically suppressed during stress.',
          D: 'Stress hormones (cortisol, epinephrine, norepinephrine) ACTIVATE the sympathetic nervous system and cardiovascular responses — they increase, not reduce, cardiovascular strain over time.',
        },
        teachingPoint: 'Allostatic load pathway: chronic psychosocial stress → sustained HPA (cortisol) + SAM (epinephrine, norepinephrine) activation → hypertension (increased peripheral resistance), endothelial damage, pro-inflammatory cytokines, insulin resistance, visceral adiposity → atherosclerosis → cardiovascular disease. This is the psychobiological mechanism underlying SES-CVD associations.',
        relatedTopics: ['allostatic load mechanism', 'HPA cortisol cardiovascular', 'chronic stress physiology', 'SES cardiovascular pathway'],
      },
      {
        id: 'mcat5-ps-014',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p3',
        questionType: 'passage',
        discipline: 'Sociology',
        contentCategory: 'SOC: 9A',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'A sociologist who argues that income inequality is necessary because differential pay motivates talented people to pursue demanding roles (e.g., physicians, engineers) is adopting which theoretical perspective?',
        choices: [
          { label: 'A', text: 'Conflict theory — inequality reflects power asymmetries and serves elite interests' },
          { label: 'B', text: 'Functionalism — inequality is inevitable and serves social stability by motivating people to fill important social roles' },
          { label: 'C', text: 'Symbolic interactionism — inequality is reproduced through micro-level daily interactions' },
          { label: 'D', text: 'The weathering hypothesis — differential rewards accelerate biological aging in disadvantaged groups' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 4: "functionalism holds that inequality is inevitable and serves social stability (differential rewards motivate people to fill important roles)." The example (differential pay motivates talent to pursue demanding roles) matches functionalism exactly. B is correct. A — conflict theory holds that inequality serves ELITE interests, not social stability through motivation. C — symbolic interactionism examines micro-level interactions reproducing status, not the macro-level justification for inequality. D — the weathering hypothesis is an empirical health claim about biological aging, not a sociological theory of why inequality exists.',
        wrongAnswerExplanations: {
          A: 'Conflict theory (Marx, Weber) views stratification as reflecting power asymmetries that benefit elites at the expense of others — it does not view inequality as functionally necessary for social stability.',
          C: 'Symbolic interactionism examines how daily micro-level interactions (e.g., deference to authority, honorific titles) reproduce status hierarchies. It does not make macro-level claims about why inequality is justified or necessary.',
          D: 'The weathering hypothesis is a health science empirical hypothesis about accelerated aging — not a sociological theory of stratification justification.',
        },
        teachingPoint: 'Three sociological perspectives: Functionalism (Durkheim, Parsons, Davis-Moore): society is a stable system; institutions serve functions; inequality motivates role-filling. Conflict theory (Marx, Weber): society = groups in power struggle; inequality = power/exploitation, not function. Symbolic interactionism (Goffman, Mead): society = constructed through micro-level interactions, symbols, and meanings. For MCAT: know which argument belongs to which theory.',
        relatedTopics: ['functionalism inequality', 'Davis-Moore stratification', 'conflict theory vs functionalism', 'sociological perspectives'],
      },
      {
        id: 'mcat5-ps-015',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p3',
        questionType: 'passage',
        discipline: 'Sociology',
        contentCategory: 'SOC: 9A',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'A researcher finds that even after controlling for income and education, occupational prestige independently predicts health outcomes. This finding is MOST consistent with:',
        choices: [
          { label: 'A', text: 'SES is fully captured by income and education; occupational prestige has no independent effect' },
          { label: 'B', text: 'SES is multidimensional; occupational prestige captures psychosocial aspects of status (autonomy, control, respect) that income and education do not fully measure' },
          { label: 'C', text: 'Occupational prestige predicts health only through its correlation with income' },
          { label: 'D', text: 'The weathering hypothesis — occupational prestige determines allostatic load through race-based stressors' },
        ],
        correctAnswer: 'B',
        explanation: 'SES is measured as income + education + occupational prestige. If occupational prestige independently predicts health after controlling for income and education, this means prestige captures something unique — the psychosocial aspects of one\'s social position (autonomy, respect, control, sense of status). These psychosocial dimensions affect HPA/SAM axis activation independently of material resources. B captures this multidimensional view of SES. A — the finding directly contradicts this: prestige HAS independent effect. C — the finding says independent of income (after controlling); if effect were only through income, controlling for income would eliminate it. D — weathering specifically involves race-based stressors; this finding is about SES dimensions.',
        wrongAnswerExplanations: {
          A: 'The finding shows occupational prestige HAS an independent effect after controlling for income and education — directly contradicting A.',
          C: 'If prestige acted only through income, controlling for income would eliminate its effect. The finding is that it has an INDEPENDENT effect — meaning it adds predictive power beyond income.',
          D: 'Weathering involves race-based stressors specifically. Occupational prestige as an independent SES dimension affecting health is a general SES phenomenon, not specifically race-related.',
        },
        teachingPoint: 'Multidimensional SES: income (material resources), education (cognitive resources, health literacy), occupational prestige (social position, autonomy, control, respect). Marmot\'s Whitehall studies: UK civil servants — higher grade = better health, even controlling for income. Mechanism: psychosocial (autonomy, control, job demands). Prestige captures social standing and control — independent health determinants through psychosocial pathways.',
        relatedTopics: ['SES multidimensional', 'occupational prestige health', 'Whitehall study', 'psychosocial SES pathways'],
      },
      {
        id: 'mcat5-ps-016',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p3',
        questionType: 'passage',
        discipline: 'Sociology',
        contentCategory: 'SOC: 9A',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'easy',
        question: 'SES is operationalized through income, education, and occupational prestige. Which of the following is the BEST example of upward social mobility?',
        choices: [
          { label: 'A', text: 'A factory worker whose brother is a physician' },
          { label: 'B', text: 'A restaurant server who earns a higher tip one evening' },
          { label: 'C', text: 'The child of a coal miner who earns a medical degree and becomes a physician' },
          { label: 'D', text: 'A physician who moves from one city to another for a new position at the same pay grade' },
        ],
        correctAnswer: 'C',
        explanation: 'Upward social mobility = movement from lower to higher SES stratum across generations (intergenerational) or within one\'s lifetime (intragenerational). The child of a coal miner becoming a physician = crossing from low-SES background to high-SES professional occupation — clear intergenerational upward mobility. C is correct. A — having a high-SES sibling does not change the worker\'s own SES position. B — a temporary higher tip is not a change in social stratum. D — moving cities at same pay grade = horizontal mobility (geographic) with no change in SES stratum.',
        wrongAnswerExplanations: {
          A: 'Sibling\'s occupation does not determine one\'s own social stratum. Social mobility is about the individual\'s own SES change, not relatives\'.',
          B: 'A temporary increase in earnings for one evening is not a change in social stratum — social mobility refers to sustained changes in social position, not ephemeral fluctuations.',
          D: 'Geographic relocation without SES change = horizontal geographic movement, not vertical social mobility. The physician remains in the same occupational prestige level.',
        },
        teachingPoint: 'Social mobility types: Vertical mobility (up or down the SES hierarchy). Intergenerational = parent-to-child comparison. Intragenerational = within one\'s own lifetime. Horizontal mobility = lateral movement within same stratum (e.g., career change to equivalent prestige, geographic move). Structure mobility = mobility due to changes in the occupational structure (e.g., industrial decline).',
        relatedTopics: ['social mobility types', 'intergenerational mobility', 'upward vertical mobility', 'horizontal mobility'],
      },
    ],
  },
  {
    id: 'f5-ps-p4',
    sectionId: 'psych-soc',
    passageNumber: 4,
    title: 'Learning Theory: Classical and Operant Conditioning',
    text: `Learning is defined as a relatively permanent change in behavior or knowledge as a result of experience. Two fundamental forms of associative learning are classical conditioning (Pavlov) and operant conditioning (Skinner).

In classical conditioning, a neutral stimulus (CS) is paired with an unconditioned stimulus (UCS) that naturally elicits an unconditioned response (UCR). After repeated pairings, the CS alone elicits a conditioned response (CR). Key phenomena include extinction (CS presented without UCS → CR diminishes), spontaneous recovery (CR reappears after a rest period following extinction), stimulus generalization (similar stimuli elicit the CR), and stimulus discrimination (training distinguishes the CS from similar stimuli).

Operant conditioning links behavior to consequences. Reinforcement increases behavior; punishment decreases it. Positive reinforcement adds a desirable stimulus; negative reinforcement removes an aversive stimulus (both increase behavior). Positive punishment adds an aversive stimulus; negative punishment removes a desirable stimulus (both decrease behavior). Schedules of reinforcement determine response patterns: fixed-ratio (FR) produces a high rate with a post-reinforcement pause; variable-ratio (VR) produces the highest steady rate and is most resistant to extinction; fixed-interval (FI) produces a scalloped response (slow then fast approaching the interval end); variable-interval (VI) produces a steady moderate rate.

Observational learning (Bandura) extends learning beyond direct experience: people learn by observing others\' behavior and its consequences. The Bobo doll experiment demonstrated that children imitate aggressive behavior observed in adults — even without direct reinforcement of the children\'s behavior.`,
    questions: [
      {
        id: 'mcat5-ps-017',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p4',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'PSYCH: 6B',
        foundationalConcept: 'FC 6',
        scientificSkill: 'Skill 2',
        difficulty: 'easy',
        question: 'A hospital patient begins to feel anxious whenever she hears a beeping sound, because the beep has preceded painful procedures. The beep is best classified as:',
        choices: [
          { label: 'A', text: 'An unconditioned stimulus — it naturally elicits anxiety without prior learning' },
          { label: 'B', text: 'A conditioned stimulus — it acquired the ability to elicit anxiety through pairing with a painful procedure (UCS)' },
          { label: 'C', text: 'A conditioned response — anxiety is the behavioral output' },
          { label: 'D', text: 'A negative reinforcer — removing the beep increases a desired behavior' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 2: "a neutral stimulus (CS) is paired with an unconditioned stimulus (UCS) that naturally elicits an unconditioned response (UCR). After repeated pairings, the CS alone elicits a conditioned response (CR)." The beep started as a neutral stimulus, was paired with painful procedures (UCS → UCR = pain/anxiety), and now elicits anxiety alone (CR). The beep = CS. B is correct. A — a neutral stimulus that becomes a CS is by definition NOT unconditioned (it required learning). C — anxiety is the CR (conditioned response), not the CS. D — negative reinforcement removes an aversive stimulus to increase behavior; this is a classical conditioning scenario.',
        wrongAnswerExplanations: {
          A: 'An unconditioned stimulus (UCS) naturally and automatically produces a response without prior learning (e.g., food → salivation, pain → fear). The beep was originally neutral — it required pairing with the painful procedure to acquire its anxiety-eliciting property. After conditioning, it is a CS, not a UCS.',
          C: 'The CR is the behavioral/physiological response (anxiety) elicited by the CS. The beep is the stimulus — the CS — not the response.',
          D: 'Negative reinforcement is an operant conditioning concept (removing an aversive stimulus after a behavior → behavior increases). This scenario involves stimulus-stimulus pairing (classical conditioning), not behavior-consequence pairing (operant).',
        },
        teachingPoint: 'Classical conditioning mapping: neutral stimulus (beep) + UCS (painful procedure) → UCR (anxiety). After conditioning: CS (beep) → CR (anxiety). Medical applications: conditioned nausea in chemotherapy patients (treatment context → nausea CR), white coat hypertension (clinic → elevated BP CR), conditioned anxiety in hospital. These conditioned responses are real physiological changes, not just "imagined."',
        relatedTopics: ['classical conditioning CS CR', 'conditioned stimulus hospital', 'Pavlov conditioning', 'conditioned fear'],
      },
      {
        id: 'mcat5-ps-018',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p4',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'PSYCH: 6B',
        foundationalConcept: 'FC 6',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'A physician tells a patient: "If you take your medication every day this week, I\'ll remove the daily check-in calls you find burdensome." This is an example of:',
        choices: [
          { label: 'A', text: 'Positive reinforcement — a pleasant stimulus is added to increase medication adherence' },
          { label: 'B', text: 'Negative punishment — a desired stimulus is removed' },
          { label: 'C', text: 'Negative reinforcement — an aversive stimulus (burdensome calls) is removed contingent on the target behavior (medication adherence)' },
          { label: 'D', text: 'Positive punishment — an aversive stimulus is added to decrease the undesired behavior' },
        ],
        correctAnswer: 'C',
        explanation: 'Paragraph 3: "Negative reinforcement removes an aversive stimulus (both increase behavior)." The check-in calls are aversive (burdensome). Removing them contingent on medication adherence = negative reinforcement. This INCREASES the target behavior (adherence). C is correct. A — positive reinforcement ADDS a pleasant stimulus; nothing is added here — something is removed. B — negative punishment removes a desirable stimulus (both decrease behavior); the calls are described as burdensome (aversive), not desirable — and the intent is to INCREASE adherence, not decrease a behavior. D — positive punishment adds an aversive stimulus to decrease a behavior; the physician is trying to INCREASE adherence by REMOVING an aversive stimulus.',
        wrongAnswerExplanations: {
          A: 'Positive reinforcement = adding a desirable stimulus. The physician is REMOVING an aversive stimulus (calls). "Positive" = adding, not pleasant.',
          B: 'Negative punishment = removing something desirable to decrease a behavior. The calls are BURDENSOME (aversive), not desirable. And the goal is to INCREASE medication adherence, not decrease a behavior.',
          D: 'Positive punishment = adding an aversive stimulus to decrease a behavior. Here, an aversive stimulus is being REMOVED (not added), and the goal is to INCREASE (not decrease) behavior.',
        },
        teachingPoint: 'Operant conditioning terminology: the +/- refers to adding/removing (not pleasant/unpleasant). Reinforcement = increases behavior. Punishment = decreases behavior. Negative reinforcement (common confusion): removing something bad → behavior increases. Clinical examples of negative reinforcement: taking an analgesic to remove pain (pain removal reinforces taking medication), wearing compression stockings to reduce edema (edema reduction reinforces wearing stockings).',
        relatedTopics: ['negative reinforcement', 'operant conditioning clinical', 'remove aversive increases behavior', 'negative reinforcement vs punishment'],
      },
      {
        id: 'mcat5-ps-019',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p4',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'PSYCH: 6B',
        foundationalConcept: 'FC 6',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'A slot machine pays out randomly and unpredictably. According to the passage, which reinforcement schedule is this, and why is it so resistant to extinction?',
        choices: [
          { label: 'A', text: 'Fixed-ratio — pays out after a fixed number of plays; resistant to extinction because of the post-reinforcement pause' },
          { label: 'B', text: 'Variable-ratio — pays out after an unpredictable number of responses; most resistant to extinction because the animal (or person) cannot predict when the next reinforcement will come' },
          { label: 'C', text: 'Variable-interval — reinforcement available after a variable time period; produces high rates' },
          { label: 'D', text: 'Fixed-interval — pays out after a fixed time period; produces a scalloped response pattern' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 3: "variable-ratio (VR) produces the highest steady rate and is most resistant to extinction." A slot machine pays out after an unpredictable number of plays — this is a variable-ratio schedule. The reason for extinction resistance: because reinforcement is unpredictable, the absence of reinforcement is not immediately distinguishable from a long run of unrewarded responses that might still lead to a win. The person continues responding because the next response might be the one that pays off. B is correct. A — FR has a post-reinforcement pause (not characteristic of slots) and is less resistant to extinction than VR. C — VI involves TIME intervals, not numbers of responses. D — FI produces a scalloped pattern and is based on time, not response count.',
        wrongAnswerExplanations: {
          A: 'Fixed-ratio produces a post-reinforcement pause (brief pause after each reward before resuming). Slot machines have no such pause. FR is also less resistant to extinction than VR.',
          C: 'Variable-interval is time-based (the next reinforcement is available after a variable time period, regardless of response rate). Slot machines pay based on number of responses, not elapsed time.',
          D: 'Fixed-interval produces a scalloped response (slow at the start of the interval, fast toward the end). Slot machines don\'t operate on a time schedule — they pay based on response number.',
        },
        teachingPoint: 'VR resistance to extinction: cannot detect when extinction begins because each response could be the one that wins. Applies to: gambling, social media (unpredictable "likes"), fishing. Most addictive schedule because: high steady rate + cannot distinguish extinction from long unrewarded run. Compared to FR: post-reinforcement pause → organism "learns" the schedule; extinction easier to detect. VR: no predictable pattern → maximum resistance.',
        relatedTopics: ['variable-ratio schedule', 'slot machine VR', 'extinction resistance schedule', 'reinforcement schedules comparison'],
      },
      {
        id: 'mcat5-ps-020',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p4',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'PSYCH: 6B',
        foundationalConcept: 'FC 6',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'Spontaneous recovery in classical conditioning demonstrates that:',
        choices: [
          { label: 'A', text: 'Extinction permanently destroys the CS-UCS association' },
          { label: 'B', text: 'The CR can reappear after a rest period following extinction, showing that the original association was not erased but suppressed' },
          { label: 'C', text: 'The UCS must be re-presented to restore the CR after extinction' },
          { label: 'D', text: 'Extinction and spontaneous recovery are only seen in animal but not human conditioning' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 2: "spontaneous recovery (CR reappears after a rest period following extinction)." This demonstrates that extinction does not erase the CS-UCS association — it creates an inhibitory process that suppresses the CR. After a rest period (which allows the inhibitory process to weaken), the CS can again elicit a weakened CR. B captures this: original association was suppressed (not erased), and spontaneous recovery is evidence of this. A — extinction does NOT permanently erase the association (spontaneous recovery proves this). C — spontaneous recovery occurs with CS presentation after rest, NOT re-presentation of UCS. D — spontaneous recovery is observed in humans (e.g., conditioned fear responses return after therapy-induced extinction).',
        wrongAnswerExplanations: {
          A: 'If extinction permanently erased the association, spontaneous recovery would be impossible. Spontaneous recovery proves A is wrong — the association persists in suppressed form.',
          C: 'Spontaneous recovery occurs when the CS is presented after a rest period. The UCS is NOT needed — the CS alone can again elicit a weakened CR. This is distinct from re-conditioning.',
          D: 'Spontaneous recovery occurs in humans — for example, clinically extinguished fear responses can return (spontaneous recovery) after a period of time without therapy. This is why multiple therapy sessions and booster sessions are needed.',
        },
        teachingPoint: 'Extinction is inhibitory learning (not erasure): a new association (CS → no UCS → no CR) is learned that inhibits the original (CS → CR). Evidence: (1) Spontaneous recovery after rest; (2) Renewal (return to original context restores CR); (3) Reinstatement (UCS exposure restores CR). Clinical implication: treated phobias and addictions can relapse (spontaneous recovery) — extinction therapy is not permanent erasure. Boosters and context generalization strategies are needed.',
        relatedTopics: ['spontaneous recovery', 'extinction inhibitory learning', 'CS-UCS association suppression', 'conditioning clinical relapse'],
      },
      {
        id: 'mcat5-ps-021',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p4',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'PSYCH: 6B',
        foundationalConcept: 'FC 6',
        scientificSkill: 'Skill 2',
        difficulty: 'easy',
        question: 'Bandura\'s Bobo doll experiment demonstrated that children imitated aggressive behavior without being directly reinforced for that behavior. This BEST supports which concept?',
        choices: [
          { label: 'A', text: 'Operant conditioning — aggressive behavior was reinforced by the experimenter' },
          { label: 'B', text: 'Classical conditioning — aggression became associated with a neutral stimulus' },
          { label: 'C', text: 'Observational learning (social learning theory) — learning occurs by observing others\' behavior, independent of direct reinforcement' },
          { label: 'D', text: 'The law of effect — behavior followed by positive consequences is strengthened' },
        ],
        correctAnswer: 'C',
        explanation: 'Paragraph 4: "Observational learning (Bandura) extends learning beyond direct experience: people learn by observing others\' behavior and its consequences. The Bobo doll experiment demonstrated that children imitate aggressive behavior observed in adults — even without direct reinforcement of the children\'s behavior." The key feature: learning WITHOUT direct reinforcement (challenging operant conditioning\'s assumption that reinforcement is necessary). C is correct. A — children were not directly reinforced; this contradicts operant conditioning as the mechanism. B — no CS-UCS pairing occurred. D — the law of effect requires direct consequences; this experiment explicitly showed learning WITHOUT direct consequences.',
        wrongAnswerExplanations: {
          A: 'Operant conditioning requires direct reinforcement of the behavior being learned. The Bobo doll study specifically showed learning WITHOUT direct reinforcement — the key feature that made it a challenge to pure operant conditioning.',
          B: 'Classical conditioning requires CS-UCS pairing. There was no such pairing for the children. The adults hit Bobo; the children watched — no neutral stimulus was paired with an UCS for the children.',
          D: 'The law of effect (Thorndike) = behaviors followed by satisfying consequences are strengthened. The Bobo experiment showed learning WITHOUT any direct consequences to the observing children — directly contrasting with the law of effect.',
        },
        teachingPoint: 'Observational learning (Bandura): also called vicarious learning or modeling. Processes: (1) Attention: observing the model. (2) Retention: encoding the behavior. (3) Reproduction: physically replicating the behavior. (4) Motivation: having a reason to perform it. The Bobo doll: challenged purely behavioral accounts by showing cognition and modeling are central to learning. Extended to pro-social behavior (modeling helpful behavior) and media violence research.',
        relatedTopics: ['observational learning Bandura', 'Bobo doll experiment', 'social learning theory', 'vicarious reinforcement'],
      },
    ],
  },
  {
    id: 'f5-ps-p5',
    sectionId: 'psych-soc',
    passageNumber: 5,
    title: 'Perception and Consciousness',
    text: `Perception involves the interpretation of sensory information to construct meaningful representations of the external world. While sensation refers to the raw detection of stimuli by sensory organs, perception involves active cognitive processing that is influenced by expectations, attention, prior knowledge, and context.

Signal detection theory (SDT) provides a framework for understanding how observers make decisions in the presence of sensory uncertainty. SDT distinguishes the observer's sensitivity (d') — the ability to distinguish signal from noise — from their response criterion (β) — the decision threshold that determines how much evidence is needed before reporting detection. A conservative criterion means the observer requires more evidence to report a signal (fewer hits, fewer false alarms); a liberal criterion means they report a signal on less evidence (more hits, more false alarms). Crucially, SDT shows that hits and false alarms are not independent — changing the criterion changes both.

Sleep and consciousness exist on a continuum. Sleep is divided into NREM and REM stages. NREM stage 3 (slow-wave sleep) is characterized by delta waves, and is associated with physical restoration and immune function; it predominates in the first third of the night. REM sleep is characterized by rapid eye movements, muscle atonia, vivid dreaming, and beta-like EEG activity (resembling wakefulness); it predominates in the last third of the night and is associated with memory consolidation and emotional processing.

Psychoactive substances alter consciousness. Stimulants (caffeine, amphetamines, cocaine) increase alertness and sympathetic arousal. Depressants (alcohol, benzodiazepines, barbiturates) reduce CNS activity. Hallucinogens (LSD, psilocybin) produce perceptual distortions. Opioids (morphine, heroin) activate mu-opioid receptors, producing analgesia and euphoria, and are highly addictive through dopaminergic reward system activation.`,
    questions: [
      {
        id: 'mcat5-ps-022',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p5',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'PSYCH: 6C',
        foundationalConcept: 'FC 6',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'A radiologist reviewing mammograms for cancer is trained to have a liberal detection criterion. According to SDT, this training would be expected to:',
        choices: [
          { label: 'A', text: 'Decrease both hits and false alarms' },
          { label: 'B', text: 'Increase hits (correct cancer detection) but also increase false alarms (calling normal tissue cancerous)' },
          { label: 'C', text: 'Increase hits while decreasing false alarms — improving both sensitivity and specificity' },
          { label: 'D', text: 'Have no effect on hit or false alarm rates — only true sensitivity (d\') matters' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 2: "A liberal criterion means they report a signal on less evidence (more hits, more false alarms). Crucially, SDT shows that hits and false alarms are not independent — changing the criterion changes both." A liberal criterion = report cancer whenever there is ANY suggestion of signal → more correct detections (hits: cancer present and called) AND more false alarms (cancer absent but called). B captures this trade-off. A — conservative criterion would decrease both. C — SDT shows you CANNOT simultaneously increase hits and decrease false alarms without improving actual sensitivity (d\'). D — the criterion directly determines hit/false alarm rates independent of sensitivity.',
        wrongAnswerExplanations: {
          A: 'Decreasing both hits and false alarms = conservative criterion (require more evidence before reporting). Liberal criterion does the opposite.',
          C: 'SDT shows that criterion and sensitivity are separate. You CANNOT improve both hits and false alarms simultaneously by changing the criterion alone — that would require actually better discrimination ability (higher d\'). Improving criterion gives a trade-off, not simultaneous improvement of both.',
          D: 'SDT shows that the response criterion (β) directly and independently affects hit and false alarm rates. Sensitivity (d\') and criterion (β) are separate parameters — both affect performance.',
        },
        teachingPoint: 'SDT clinical application: screening tests face the criterion problem. Liberal criterion (low threshold for "positive") → high sensitivity (few missed cancers) BUT low specificity (many false positives → unnecessary biopsies, patient anxiety). Conservative criterion → high specificity BUT low sensitivity (missed cancers). The ROC curve shows all possible criterion settings. The goal: find the criterion that optimizes the cost/benefit of hits vs. false alarms for the specific context.',
        relatedTopics: ['signal detection theory', 'liberal criterion hits false alarms', 'SDT radiologist', 'sensitivity specificity criterion'],
      },
      {
        id: 'mcat5-ps-023',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p5',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'PSYCH: 6C',
        foundationalConcept: 'FC 6',
        scientificSkill: 'Skill 2',
        difficulty: 'easy',
        question: 'During which sleep stage would a person be most difficult to wake and would likely experience slow-wave, high-amplitude EEG activity?',
        choices: [
          { label: 'A', text: 'REM sleep — vivid dreaming and beta-like EEG activity' },
          { label: 'B', text: 'NREM Stage 1 — transition between wakefulness and sleep with theta waves' },
          { label: 'C', text: 'NREM Stage 3 (slow-wave sleep) — deep sleep with delta waves; hardest to arouse' },
          { label: 'D', text: 'NREM Stage 2 — sleep spindles and K-complexes; intermediate depth' },
        ],
        correctAnswer: 'C',
        explanation: 'Paragraph 3: "NREM stage 3 (slow-wave sleep) is characterized by delta waves." Delta waves = high-amplitude, low-frequency waves indicating deepest sleep. NREM Stage 3 is the hardest stage to arouse from (deepest sleep). C is correct. A — REM has beta-like (low amplitude, high frequency) EEG, not slow-wave; and REM is actually easier to wake from than Stage 3 despite vivid dreams. B — Stage 1 has theta waves; it is the lightest sleep stage. D — Stage 2 has sleep spindles and K-complexes; intermediate depth but not the deepest.',
        wrongAnswerExplanations: {
          A: 'REM EEG resembles wakefulness (beta-like). REM is not the hardest stage to wake from — NREM Stage 3 is deepest. Interestingly, you can be harder to wake from Stage 3 than REM despite REM having more vivid experience.',
          B: 'NREM Stage 1 is the lightest sleep stage — transition from wakefulness. Theta waves, easily awakened, often not even perceived as sleeping by the person.',
          D: 'NREM Stage 2 has sleep spindles (12-15 Hz bursts) and K-complexes (large slow waves). It is deeper than Stage 1 but not as deep as Stage 3 (delta wave slow-wave sleep).',
        },
        teachingPoint: 'Sleep stages: Stage 1 (theta, lightest) → Stage 2 (spindles, K-complexes) → Stage 3 (delta, deepest, slow-wave). REM (beta-like, dreaming, muscle atonia). Night architecture: first half = more NREM Stage 3 (physical restoration); second half = more REM (memory consolidation). Sleep deprivation effects: first to recover is Stage 3 (rebound), then REM rebound.',
        relatedTopics: ['NREM stage 3 slow wave sleep', 'delta waves deepest sleep', 'sleep stages EEG', 'sleep architecture'],
      },
      {
        id: 'mcat5-ps-024',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p5',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'PSYCH: 6C',
        foundationalConcept: 'FC 6',
        scientificSkill: 'Skill 2',
        difficulty: 'easy',
        question: 'Benzodiazepines are classified as CNS depressants. Their primary mechanism of action involves:',
        choices: [
          { label: 'A', text: 'Blocking dopamine reuptake, increasing dopamine in the synapse' },
          { label: 'B', text: 'Binding to GABA-A receptors and enhancing the inhibitory effect of GABA, reducing CNS activity' },
          { label: 'C', text: 'Activating mu-opioid receptors, producing analgesia and euphoria' },
          { label: 'D', text: 'Blocking serotonin reuptake, increasing serotonin at the synapse' },
        ],
        correctAnswer: 'B',
        explanation: 'Benzodiazepines are CNS depressants that enhance the effect of GABA (the major inhibitory neurotransmitter in the CNS). They bind to the GABA-A receptor (allosteric modulator site) → increase the frequency of chloride channel opening in response to GABA → hyperpolarization → CNS inhibition. The passage identifies depressants as substances that "reduce CNS activity." B is the mechanism. A — dopamine reuptake blockade = stimulants (cocaine, amphetamines). C — mu-opioid receptor activation = opioids (morphine, heroin). D — serotonin reuptake blockade = SSRIs (antidepressants, not depressants).',
        wrongAnswerExplanations: {
          A: 'Dopamine reuptake blockade is the mechanism of cocaine and some amphetamines (stimulants). Benzodiazepines enhance GABA (inhibitory), not dopamine (which can be excitatory).',
          C: 'Mu-opioid receptor activation = opioid analgesia. Benzodiazepines act on GABA-A receptors. These are distinct receptor systems.',
          D: 'Serotonin reuptake inhibition = SSRIs (fluoxetine, sertraline). These are antidepressants — not benzodiazepines and not CNS depressants in the classical sense.',
        },
        teachingPoint: 'Benzodiazepines: GABA-A receptor positive allosteric modulators. Mechanism: ↑ GABA efficacy → ↑ Cl- channel opening frequency → hyperpolarization → CNS depression. Uses: anxiety, insomnia, seizures, alcohol withdrawal, muscle relaxation. Risks: tolerance, dependence, withdrawal (can be life-threatening — seizures). Not analgesics (don\'t activate opioid receptors). Clinical: different from barbiturates (which increase Cl- channel DURATION, not frequency — more dangerous overdose profile).',
        relatedTopics: ['benzodiazepines GABA-A', 'CNS depressants mechanism', 'GABA inhibitory', 'benzodiazepine pharmacology'],
      },
      {
        id: 'mcat5-ps-025',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p5',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'PSYCH: 6C',
        foundationalConcept: 'FC 6',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'A patient reports that the room seems to be moving and objects appear to be changing size. The patient has taken a substance that produces these perceptual distortions. According to the passage, this substance is MOST likely classified as:',
        choices: [
          { label: 'A', text: 'A stimulant — increasing alertness and sympathetic arousal' },
          { label: 'B', text: 'A depressant — reducing CNS activity and producing perceptual changes through sedation' },
          { label: 'C', text: 'A hallucinogen — producing perceptual distortions' },
          { label: 'D', text: 'An opioid — producing analgesia and euphoria through mu-opioid receptor activation' },
        ],
        correctAnswer: 'C',
        explanation: 'Paragraph 4: "Hallucinogens (LSD, psilocybin) produce perceptual distortions." Room appearing to move and objects changing size = perceptual distortions (visual illusions/hallucinations). C matches. A — stimulants increase alertness/arousal; not specifically associated with perceptual distortions. B — depressants cause sedation, impaired coordination, slurred speech; perceptual distortions are not the primary characteristic. D — opioids produce analgesia, euphoria, respiratory depression; not primarily perceptual distortions.',
        wrongAnswerExplanations: {
          A: 'Stimulants (caffeine, amphetamines, cocaine) increase heart rate, alertness, focus, sympathetic tone. While high doses of stimulants can occasionally produce psychosis-like symptoms, perceptual distortions are the defining feature of hallucinogens.',
          B: 'Depressants reduce CNS activity → sedation, anxiolysis, impaired motor coordination. Perceptual distortions (room moving, objects changing size) are not the primary feature of depressants.',
          D: 'Opioids produce analgesia, euphoria, miosis, constipation, respiratory depression (overdose). Perceptual distortions (visual hallucinations, objects changing size) are associated with hallucinogens, not opioids.',
        },
        teachingPoint: 'Psychoactive drug classes: Stimulants = ↑arousal, ↑sympathetic. Depressants = ↓CNS, sedation. Hallucinogens = perceptual distortions, altered consciousness. Opioids = analgesia, euphoria, reward. Dissociatives (ketamine, PCP) = detachment from reality (separate category). LSD mechanism: serotonin 5-HT2A receptor agonism in cortex. Psilocybin: same mechanism (converted to psilocin). Clinical: psilocybin in clinical trials for depression and PTSD.',
        relatedTopics: ['hallucinogens perceptual distortion', 'LSD psilocybin', 'drug classification', 'psychoactive substance classification'],
      },
      {
        id: 'mcat5-ps-026',
        sectionId: 'psych-soc',
        passageId: 'f5-ps-p5',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'PSYCH: 6C',
        foundationalConcept: 'FC 6',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'Opioids are addictive primarily because they activate the dopaminergic reward system. This is consistent with which broader principle of addiction neuroscience?',
        choices: [
          { label: 'A', text: 'All addictive substances act through opioid receptors' },
          { label: 'B', text: 'Addiction is driven by dopamine release in the nucleus accumbens — a common final pathway for diverse addictive substances and behaviors' },
          { label: 'C', text: 'The addiction potential of a substance is determined solely by its half-life' },
          { label: 'D', text: 'Opioid addiction is limited to mu-receptor agonists and does not involve other reward pathways' },
        ],
        correctAnswer: 'B',
        explanation: 'Paragraph 4: opioids are "highly addictive through dopaminergic reward system activation." The common feature of addictive substances (cocaine, amphetamines, opioids, nicotine, alcohol) is dopamine release in the nucleus accumbens (the brain\'s "reward center"). B captures the common final pathway principle. A — not all addictive substances act through opioid receptors (cocaine acts on dopamine transporter; alcohol on GABA/glutamate; nicotine on nicotinic acetylcholine receptors). C — half-life affects pharmacokinetics but is not the primary determinant of addiction potential (route of administration and speed to reward are more important). D — opioids do involve other reward pathways (e.g., locus coeruleus for withdrawal), but the passage specifically highlights the dopaminergic reward system.',
        wrongAnswerExplanations: {
          A: 'Different addictive substances act through different initial mechanisms. Cocaine blocks dopamine transporter. Nicotine activates nicotinic ACh receptors. Alcohol modulates GABA-A and NMDA receptors. They all ultimately affect the dopaminergic reward system, but the initial target differs.',
          C: 'Half-life is pharmacokinetically important (longer half-life → smoother, less acute peaks; shorter half-life → more abrupt peaks/troughs). Addiction potential depends more on the speed of reward (faster onset = higher addictiveness) and the magnitude of dopamine release, not simply half-life.',
          D: 'Opioids also affect the locus coeruleus (withdrawal), the limbic system, and various other circuits. The claim that opioid addiction is "limited to" mu-receptor agonists and "does not involve other reward pathways" is incorrect and overly narrow.',
        },
        teachingPoint: 'Common reward pathway: ventral tegmental area (VTA) → nucleus accumbens (dopamine release) → prefrontal cortex (subjective experience of reward). All addictive substances and many addictive behaviors (gambling, social media) converge on this pathway. Neuroadaptation: with chronic use, dopamine baseline falls → tolerance and withdrawal. DSM-5 addiction diagnosis: tolerance, withdrawal, loss of control, continued use despite consequences.',
        relatedTopics: ['dopamine reward pathway', 'nucleus accumbens addiction', 'common addiction pathway', 'opioid dopaminergic reward'],
      },
    ],
  },
]
