import type { MCATPassage } from '../types'

// Form 2 B/B — Passages 6–10
// Topics: Genetic Regulation, Membrane Transport, Cellular Respiration, Protein Folding, Cell Cycle
// Questions: 5+5+5+5+5 = 25 questions (IDs mcat2-bb-026 through mcat2-bb-050)

export const bbPassages06to10: MCATPassage[] = [
  // ─── B/B Passage 6: lac Operon and Gene Regulation ─────────────────────────
  {
    id: 'f2-bb-p6',
    sectionId: 'bio-biochem',
    title: 'Regulation of the lac Operon',
    passageText: `The lac operon of E. coli encodes enzymes for lactose utilization (β-galactosidase, permease, transacetylase) and is regulated by both negative control (repressor-mediated) and positive control (catabolite activator protein, CAP-mediated).

Negative control: The lac repressor (encoded by lacI) binds the lac operator (a specific DNA sequence) when no allolactose (a lactose metabolite) is present, blocking transcription. When lactose is present, allolactose binds the repressor, inducing a conformational change that reduces its affinity for the operator, allowing RNA polymerase to transcribe the structural genes.

Positive control: The CAP protein binds cAMP, and the CAP-cAMP complex binds a site upstream of the promoter, stimulating RNA polymerase binding. When glucose is present, adenylyl cyclase is inhibited and [cAMP] is low; thus CAP-cAMP does not form, and transcription is minimal even in the presence of lactose. When glucose is absent and lactose is present, [cAMP] rises, CAP-cAMP forms, and robust transcription of the lac operon occurs.

Figure 1 (not shown) shows β-galactosidase activity in four E. coli cultures: (A) no lactose, no glucose; (B) lactose only; (C) glucose only; (D) lactose + glucose.`,
    figures: [],
    questions: [
      {
        id: 'mcat2-bb-026',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p6',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Gene regulation',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'In condition D (lactose + glucose), what is the expected β-galactosidase activity relative to condition B (lactose only)?',
        choices: [
          { label: 'A', text: 'Higher than condition B because both inducers are present' },
          { label: 'B', text: 'Lower than condition B because glucose keeps cAMP low, preventing CAP-cAMP-mediated activation' },
          { label: 'C', text: 'Equal to condition B because lactose is sufficient to induce transcription' },
          { label: 'D', text: 'Zero, because glucose represses the operator directly' },
        ],
        correctAnswer: 'B',
        explanation: 'When glucose is present (condition D), adenylyl cyclase is inhibited → [cAMP] is low → CAP-cAMP complex does not form → no positive control activation. The repressor can be relieved by allolactose, but without CAP-cAMP, RNA polymerase does not bind the promoter efficiently. Transcription (and thus β-galactosidase activity) is significantly lower than in condition B (lactose only, no glucose), where CAP-cAMP is present and fully activates transcription. B is correct. A is wrong — glucose does not add to induction; it prevents positive control. C is wrong — lactose relieves repression, but activation still requires CAP-cAMP. D is wrong — glucose does not directly repress the operator.',
        wrongAnswerExplanations: {
          A: 'Glucose does not act as an inducer. Its presence inhibits the positive control system, so adding glucose to lactose reduces (not increases) lac operon expression.',
          C: 'Lactose removes the repressor (negative control), but RNA polymerase still needs the CAP-cAMP activator for efficient transcription. Without CAP-cAMP (because glucose is present), expression is low.',
          D: 'Glucose does not directly repress the operator. It exerts catabolite repression by lowering [cAMP], which prevents CAP from activating transcription.',
        },
        teachingPoint: 'Catabolite repression: glucose → low [cAMP] → no CAP-cAMP → minimal lac transcription even if lactose is present. The cell prioritizes glucose metabolism. Maximum lac expression requires both allolactose (remove repressor) AND high [cAMP] (CAP activation).',
        relatedTopics: ['lac operon', 'catabolite repression', 'CAP-cAMP', 'glucose repression', 'cAMP'],
      },
      {
        id: 'mcat2-bb-027',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p6',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Gene regulation',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'In condition A (no lactose, no glucose), which regulatory elements would keep lac operon transcription minimal?',
        choices: [
          { label: 'A', text: 'The repressor is bound to the operator (negative control prevents transcription); and no glucose means cAMP is high, but insufficient without lactose' },
          { label: 'B', text: 'Repressor binds operator (no allolactose to displace it); transcription is blocked regardless of cAMP/CAP status' },
          { label: 'C', text: 'CAP-cAMP inhibits transcription because no glucose is present' },
          { label: 'D', text: 'RNA polymerase is covalently modified by the repressor' },
        ],
        correctAnswer: 'B',
        explanation: 'Without lactose, no allolactose is generated. The unbound repressor has high affinity for the operator and blocks RNA polymerase. CAP-cAMP may be present (no glucose → high cAMP), but CAP-cAMP can only activate transcription — it cannot overcome the repressor physically blocking the operator. Thus transcription is minimal. B correctly identifies repressor binding as the dominant regulatory block. A is misleading in implying CAP-cAMP status is sufficient without resolving the repressor issue. C inverts CAP\'s role (activator, not inhibitor). D is incorrect — the repressor does not covalently modify polymerase.',
        wrongAnswerExplanations: {
          A: 'The framing in A is partially correct (repressor does bind) but adds confusion by suggesting cAMP status alone is sufficient. The key point is that repressor binding is the primary block, regardless of cAMP/CAP.',
          C: 'CAP-cAMP is an activator (stimulates polymerase binding), not an inhibitor. High cAMP without lactose means activation potential is present but cannot be realized because the repressor blocks the promoter.',
          D: 'The lac repressor is a sequence-specific DNA-binding protein; it does not covalently modify RNA polymerase.',
        },
        teachingPoint: 'No lactose, no glucose: repressor binds operator (no allolactose to remove it) → transcription blocked. Even though no glucose means high cAMP → CAP-cAMP forms, this activator cannot overcome the repressor physically blocking the promoter. Repressor = dominant off switch.',
        relatedTopics: ['lac repressor', 'operator', 'allolactose', 'negative control', 'gene regulation'],
      },
      {
        id: 'mcat2-bb-028',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p6',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Gene regulation',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'A lacI⁻ mutant (unable to produce functional repressor) is grown in glucose alone (no lactose). What is the expected lac operon transcription level?',
        choices: [
          { label: 'A', text: 'High transcription because the repressor cannot block the operator' },
          { label: 'B', text: 'Low transcription because glucose keeps cAMP low, preventing CAP-cAMP activation' },
          { label: 'C', text: 'No transcription because the absence of allolactose prevents transcription regardless of repressor' },
          { label: 'D', text: 'Moderate transcription because the cell partially activates the operon without inducer' },
        ],
        correctAnswer: 'B',
        explanation: 'A lacI⁻ mutant cannot make a repressor → operator is always unoccupied → negative control is constitutively OFF (no repression). However, the positive control still operates: glucose → low [cAMP] → no CAP-cAMP → no activation of RNA polymerase. Without CAP-cAMP activation, RNA polymerase cannot efficiently bind the promoter. Transcription will be low (not high) despite absent repression. B correctly identifies this. A incorrectly assumes absent repression alone is sufficient for high transcription. C is wrong — allolactose affects the repressor; with no functional repressor, allolactose status is irrelevant. D is wrong — there is no partial activation mechanism described.',
        wrongAnswerExplanations: {
          A: 'Absent repression is necessary but not sufficient for high transcription. CAP-cAMP is also required for efficient RNA polymerase binding. Without it (glucose is present), transcription is low despite no repressor.',
          C: 'Allolactose removes the repressor; if there is no repressor (lacI⁻), allolactose is irrelevant. Transcription depends on CAP-cAMP for activation.',
          D: 'There is no described partial activation mechanism. Without CAP-cAMP, the promoter is a "weak" promoter with minimal polymerase binding.',
        },
        teachingPoint: 'Dual control dissection: lacI⁻ mutant removes negative control completely, but positive control (CAP-cAMP) is still required. With glucose (low cAMP), even a constitutively de-repressed operon shows low transcription. This demonstrates that both controls operate independently.',
        relatedTopics: ['lacI mutant', 'constitutive expression', 'catabolite repression', 'dual regulation', 'CAP-cAMP'],
      },
      {
        id: 'mcat2-bb-029',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p6',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Gene regulation',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'The allolactose-repressor interaction is best described as:',
        choices: [
          { label: 'A', text: 'Allolactose covalently modifies the repressor, permanently inactivating it' },
          { label: 'B', text: 'Allolactose binds the repressor, inducing a conformational change that reduces its DNA affinity' },
          { label: 'C', text: 'Allolactose degrades the repressor via protease activation' },
          { label: 'D', text: 'Allolactose competes with the operator for binding the repressor' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage states allolactose binds the repressor, "inducing a conformational change that reduces its affinity for the operator." B reproduces this. A is wrong — the interaction is non-covalent and reversible. C is wrong — no proteolysis is described. D is wrong — allolactose binds the repressor protein, not the operator DNA; it changes the repressor\'s conformation rather than competing for the same binding site.',
        wrongAnswerExplanations: {
          A: 'The interaction is non-covalent and reversible. If allolactose is removed, the repressor can rebind the operator.',
          C: 'No protease or degradation is involved. The repressor is allosterically regulated.',
          D: 'Allolactose binds to a specific inducer-binding site on the repressor protein, causing an allosteric conformational change — it does not compete with repressor for the operator DNA.',
        },
        teachingPoint: 'Allosteric regulation of lac repressor: allolactose = inducer. Binds allosteric site on repressor → conformational change → reduced DNA-binding affinity → repressor dissociates from operator → transcription proceeds. Classic example of negative control with inducible operon.',
        relatedTopics: ['lac repressor', 'allolactose', 'allosteric regulation', 'negative control', 'inducer'],
      },
      {
        id: 'mcat2-bb-030',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p6',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Gene regulation',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'CAP-cAMP stimulates lac operon transcription by which mechanism?',
        choices: [
          { label: 'A', text: 'Displacing the repressor from the operator' },
          { label: 'B', text: 'Binding upstream of the promoter and stimulating RNA polymerase binding' },
          { label: 'C', text: 'Directly phosphorylating RNA polymerase to increase its activity' },
          { label: 'D', text: 'Inhibiting adenylyl cyclase to increase cAMP levels further' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage states: "the CAP-cAMP complex binds a site upstream of the promoter, stimulating RNA polymerase binding." B reproduces this. A is wrong — CAP-cAMP does not interact with the repressor; they are independent regulatory systems. C is wrong — no phosphorylation of RNA polymerase is described. D is wrong — inhibiting adenylyl cyclase would lower cAMP; and the passage states glucose inhibits adenylyl cyclase (a negative regulatory event).',
        wrongAnswerExplanations: {
          A: 'CAP-cAMP and the repressor act at different DNA sites and by different mechanisms. They are independent: CAP acts at the CAP binding site upstream; the repressor acts at the operator.',
          C: 'CAP-cAMP is a transcriptional activator that facilitates polymerase binding through protein-DNA and protein-protein interactions, not covalent phosphorylation.',
          D: 'Adenylyl cyclase makes cAMP. Inhibiting it would lower cAMP — which is exactly what glucose does to suppress lac transcription. CAP-cAMP uses existing cAMP; it does not regulate adenylyl cyclase.',
        },
        teachingPoint: 'CAP mechanism: CAP + cAMP → CAP-cAMP complex → binds CAP site upstream of promoter → contacts α subunit of RNA polymerase → promotes polymerase recruitment. This is the positive control arm of the lac operon.',
        relatedTopics: ['CAP protein', 'cAMP', 'positive control', 'RNA polymerase binding', 'transcription activation'],
      },
    ],
  },

  // ─── B/B Passage 7: Membrane Transport and Electrochemical Gradients ─────────
  {
    id: 'f2-bb-p7',
    sectionId: 'bio-biochem',
    title: 'Driving Forces for Membrane Transport',
    passageText: `The movement of ions and small molecules across biological membranes is governed by electrochemical gradients — the combined effect of concentration (chemical) gradient and electrical potential. For an ion of charge z, the electrochemical potential difference across a membrane is described by the Nernst equation:

E_ion = (RT/zF) × ln([ion]_out / [ion]_in)

where R is the gas constant (8.314 J/mol·K), T is temperature in Kelvin, F is Faraday's constant (96,485 C/mol), and [ion]_out and [ion]_in are extracellular and intracellular concentrations, respectively. At 37°C (310 K), RT/F ≈ 26.7 mV.

The resting membrane potential of a typical mammalian neuron is approximately −70 mV (inside negative). Extracellular [Na⁺] ≈ 145 mM; intracellular [Na⁺] ≈ 12 mM. Extracellular [K⁺] ≈ 4 mM; intracellular [K⁺] ≈ 140 mM.

The Na⁺/K⁺-ATPase pumps 3 Na⁺ out and 2 K⁺ in per ATP hydrolyzed, maintaining the concentration gradients and contributing directly to the membrane potential (net outward positive charge movement per cycle).

Secondary active transport exploits the electrochemical gradient of Na⁺ established by the Na⁺/K⁺-ATPase to drive uphill transport of other solutes. The Na⁺-glucose cotransporter (SGLT1) moves one glucose molecule into the cell along with two Na⁺ ions, harnessing the Na⁺ electrochemical gradient.`,
    figures: [],
    questions: [
      {
        id: 'mcat2-bb-031',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p7',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Membrane transport',
        foundationalConcept: 'FC 3',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'Using the Nernst equation, calculate the equilibrium potential for Na⁺ across the neuronal membrane (at 37°C, [Na⁺]_out = 145 mM, [Na⁺]_in = 12 mM). Which answer is closest?',
        choices: [
          { label: 'A', text: '+66 mV' },
          { label: 'B', text: '−70 mV' },
          { label: 'C', text: '+26 mV' },
          { label: 'D', text: '−94 mV' },
        ],
        correctAnswer: 'A',
        explanation: 'E_Na = (RT/zF) × ln([Na⁺]_out / [Na⁺]_in) = (26.7 mV / 1) × ln(145/12) = 26.7 × ln(12.08) = 26.7 × 2.49 ≈ +66.4 mV. Answer A is correct. B is the resting membrane potential, not the Na⁺ equilibrium potential. C would result from a much smaller concentration gradient. D is approximately the K⁺ equilibrium potential (E_K = 26.7 × ln(4/140) ≈ 26.7 × (−3.56) ≈ −95 mV).',
        wrongAnswerExplanations: {
          B: '−70 mV is the resting membrane potential of the neuron, not the Na⁺ Nernst equilibrium potential. At −70 mV, Na⁺ is far from equilibrium, which is why Na⁺ rushes in during an action potential.',
          C: '+26 mV would be the equilibrium potential for a concentration gradient of only about e¹ ≈ 2.7-fold, not the 145/12 ≈ 12-fold Na⁺ gradient.',
          D: '−94 to −95 mV is approximately the K⁺ equilibrium potential (ln(4/140) = −3.56; 26.7 × −3.56 = −95 mV), not the Na⁺ equilibrium potential.',
        },
        teachingPoint: 'Nernst equation at 37°C: E = (26.7/z) × ln([out]/[in]). For Na⁺ (z=+1): E_Na = 26.7 × ln(145/12) = 26.7 × 2.49 ≈ +66 mV. Since resting Vm = −70 mV ≠ E_Na = +66 mV, there is a large electrochemical driving force for Na⁺ influx (~136 mV driving force).',
        relatedTopics: ['Nernst equation', 'Na+ equilibrium potential', 'electrochemical gradient', 'membrane potential'],
      },
      {
        id: 'mcat2-bb-032',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p7',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Membrane transport',
        foundationalConcept: 'FC 3',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'The Na⁺/K⁺-ATPase is described in the passage as contributing directly to the membrane potential. Why?',
        choices: [
          { label: 'A', text: 'It pumps equal numbers of Na⁺ and K⁺, generating no net charge movement' },
          { label: 'B', text: 'It moves 3 Na⁺ out and 2 K⁺ in per cycle — net outward movement of one positive charge per cycle' },
          { label: 'C', text: 'It uses ATP hydrolysis to generate a proton gradient across the membrane' },
          { label: 'D', text: 'It opens voltage-gated Na⁺ channels that hyperpolarize the cell' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage states the pump moves "3 Na⁺ out and 2 K⁺ in per ATP hydrolyzed... (net outward positive charge movement per cycle)." 3 positive charges leave; 2 positive charges enter → net 1 positive charge leaves per cycle → the pump is electrogenic (inside becomes more negative). B reproduces this. A is wrong — 3:2 is not equal. C describes a proton pump, not Na⁺/K⁺-ATPase. D conflates pumping with gating.',
        wrongAnswerExplanations: {
          A: 'The pump is asymmetric (3 out, 2 in), not symmetric. This asymmetry is what makes it electrogenic.',
          C: 'Na⁺/K⁺-ATPase transports Na⁺ and K⁺, not protons. Proton pumps are found in mitochondria (ATP synthase/F₀F₁) and lysosomes.',
          D: 'The Na⁺/K⁺-ATPase is a pump (uses ATP to move ions against gradient), not a channel. It does not open or close voltage-gated channels.',
        },
        teachingPoint: 'Na⁺/K⁺-ATPase: electrogenic pump (3 Na⁺ out, 2 K⁺ in). Net outward movement of +1 charge per cycle → contributes ~3–5 mV to resting membrane potential. Primary function is maintaining gradients; secondary function is electrogenic contribution.',
        relatedTopics: ['Na+/K+-ATPase', 'electrogenic pump', 'membrane potential', 'primary active transport'],
      },
      {
        id: 'mcat2-bb-033',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p7',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Membrane transport',
        foundationalConcept: 'FC 3',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'SGLT1 (Na⁺-glucose cotransporter) moves glucose against its concentration gradient. This is an example of:',
        choices: [
          { label: 'A', text: 'Primary active transport — ATP is used directly to move glucose' },
          { label: 'B', text: 'Secondary active transport — the Na⁺ electrochemical gradient (maintained by Na⁺/K⁺-ATPase) provides energy for uphill glucose transport' },
          { label: 'C', text: 'Facilitated diffusion — glucose moves along its concentration gradient through a protein channel' },
          { label: 'D', text: 'Osmosis — water movement drives glucose across the membrane' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage defines secondary active transport as exploiting "the electrochemical gradient of Na⁺ established by the Na⁺/K⁺-ATPase to drive uphill transport of other solutes." SGLT1 cotransports glucose with Na⁺ — Na⁺ moves down its electrochemical gradient, releasing energy that drives glucose uphill. The Na⁺/K⁺-ATPase provides the primary energy input; SGLT1 is "secondary." A is wrong — SGLT1 does not use ATP directly. C is wrong — glucose moves against its gradient (uphill), not along it. D is wrong — osmosis involves water, not solute cotransport.',
        wrongAnswerExplanations: {
          A: 'SGLT1 does not hydrolyze ATP. The energy comes from the Na⁺ gradient established by the Na⁺/K⁺-ATPase (which does use ATP). This indirect energy coupling defines secondary active transport.',
          C: 'Facilitated diffusion is passive (down the gradient). Glucose moves against its concentration gradient here — that requires active (energy-consuming) transport.',
          D: 'Osmosis is the movement of water across a semipermeable membrane. SGLT1 moves glucose and Na⁺, not water.',
        },
        teachingPoint: 'Secondary active transport: energy stored in Na⁺ gradient (built by Na⁺/K⁺-ATPase) drives uphill transport of other solutes. Examples: SGLT1 (glucose), Na⁺/Ca²⁺ exchanger, Na⁺/amino acid cotransporters. Blocking Na⁺/K⁺-ATPase (ouabain) eventually impairs secondary transport by collapsing the Na⁺ gradient.',
        relatedTopics: ['secondary active transport', 'SGLT1', 'Na+ gradient', 'cotransport', 'glucose uptake'],
      },
      {
        id: 'mcat2-bb-034',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p7',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Membrane transport',
        foundationalConcept: 'FC 3',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'If a drug completely inhibits the Na⁺/K⁺-ATPase in intestinal epithelial cells, what would most likely happen to glucose absorption via SGLT1?',
        choices: [
          { label: 'A', text: 'Glucose absorption increases because Na⁺ accumulates intracellularly, increasing the driving force for Na⁺ influx via SGLT1' },
          { label: 'B', text: 'Glucose absorption decreases because the Na⁺ gradient collapses, removing the driving force for SGLT1' },
          { label: 'C', text: 'No change because SGLT1 uses ATP directly and is independent of Na⁺/K⁺-ATPase' },
          { label: 'D', text: 'Glucose absorption increases because the membrane potential hyperpolarizes, driving more SGLT1 activity' },
        ],
        correctAnswer: 'B',
        explanation: 'SGLT1 (secondary active transporter) relies on the inwardly directed Na⁺ electrochemical gradient established by the Na⁺/K⁺-ATPase. If Na⁺/K⁺-ATPase is blocked, Na⁺ accumulates inside the cell and K⁺ depletes → the Na⁺ gradient collapses → the driving force for Na⁺ influx via SGLT1 is eliminated → SGLT1 can no longer drive uphill glucose transport. B is correct. A describes initial Na⁺ accumulation but incorrectly predicts the consequence (more intracellular Na⁺ reduces, not increases, the inward Na⁺ gradient). C is wrong — SGLT1 depends on the Na⁺ gradient, not ATP. D is wrong — blocking Na⁺/K⁺-ATPase depolarizes (not hyperpolarizes) the membrane.',
        wrongAnswerExplanations: {
          A: 'Na⁺ accumulation inside the cell reduces the inward Na⁺ concentration gradient (and the pump\'s absence means the membrane depolarizes, reducing the electrical gradient too). Both components of the electrochemical gradient diminish, reducing SGLT1 driving force.',
          C: 'SGLT1 is a secondary active transporter that uses the Na⁺ gradient as its energy source. It does not hydrolyze ATP directly.',
          D: 'Blocking Na⁺/K⁺-ATPase causes depolarization (Na⁺ enters, K⁺ can\'t be replenished externally), not hyperpolarization.',
        },
        teachingPoint: 'Na⁺/K⁺-ATPase is the energy foundation for all secondary active transporters. Block the pump → Na⁺ gradient collapses → all Na⁺-coupled transporters (SGLT1, Na⁺/amino acid, Na⁺/Ca²⁺) fail. This is why ouabain (cardiac glycoside) eventually raises intracellular Ca²⁺ via impaired Na⁺/Ca²⁺ exchanger.',
        relatedTopics: ['Na+/K+-ATPase inhibition', 'SGLT1', 'Na+ gradient collapse', 'secondary transport failure'],
      },
      {
        id: 'mcat2-bb-035',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p7',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Membrane transport',
        foundationalConcept: 'FC 3',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'The resting membrane potential of −70 mV is much closer to E_K (approximately −95 mV) than to E_Na (+66 mV). What does this imply about the membrane\'s permeability at rest?',
        choices: [
          { label: 'A', text: 'The membrane is much more permeable to Na⁺ than to K⁺ at rest' },
          { label: 'B', text: 'The membrane is much more permeable to K⁺ than to Na⁺ at rest, because leak K⁺ channels dominate resting permeability' },
          { label: 'C', text: 'The membrane has equal permeability to Na⁺ and K⁺, and the potential reflects an average' },
          { label: 'D', text: 'The membrane is impermeable to all ions at rest' },
        ],
        correctAnswer: 'B',
        explanation: 'The Goldman equation (generalization of Nernst for multiple ions) shows that the membrane potential is closer to the Nernst potential of the most permeable ion. Since the resting potential (−70 mV) is closer to E_K (−95 mV) than to E_Na (+66 mV), the membrane at rest is dominated by K⁺ permeability — primarily through inwardly rectifying K⁺ leak channels. This is the fundamental basis of the resting potential. B is correct. A predicts the potential would be closer to +66 mV. C would give an intermediate value, but the resting potential is distinctly closer to E_K, not an average.',
        wrongAnswerExplanations: {
          A: 'If Na⁺ permeability dominated, the resting potential would approach E_Na ≈ +66 mV. The actual −70 mV is near E_K, implying K⁺ dominates.',
          C: 'If permeabilities were equal, the resting potential would be near the average of E_K and E_Na (approximately −15 mV). The −70 mV value indicates K⁺ permeability dominates.',
          D: 'If impermeable, ions couldn\'t create a membrane potential. The resting potential exists because ions CAN cross — primarily K⁺ through leak channels.',
        },
        teachingPoint: 'Goldman equation insight: resting membrane potential ≈ E_K because at rest, K⁺ permeability >> Na⁺ permeability (K⁺ leak channels are open; Na⁺ channels are mostly closed). The closer Vm is to E_X, the more dominant ion X\'s permeability is.',
        relatedTopics: ['Goldman equation', 'resting membrane potential', 'K+ permeability', 'leak channels', 'Nernst potential'],
      },
    ],
  },

  // ─── B/B Passage 8: Oxidative Phosphorylation ───────────────────────────────
  {
    id: 'f2-bb-p8',
    sectionId: 'bio-biochem',
    title: 'The Proton Motive Force and ATP Synthesis',
    passageText: `Oxidative phosphorylation couples the exergonic transfer of electrons through the electron transport chain (ETC) to the endergonic synthesis of ATP by ATP synthase (Complex V). The ETC components — NADH dehydrogenase (Complex I), succinate dehydrogenase (Complex II), cytochrome bc₁ (Complex III), and cytochrome c oxidase (Complex IV) — transfer electrons from NADH or FADH₂ to molecular oxygen, the terminal electron acceptor, generating water. The free energy released drives proton pumping from the matrix into the intermembrane space at Complexes I, III, and IV, creating the proton motive force (pmf):

pmf = ΔΨ + (2.303 RT/F) × ΔpH

where ΔΨ is the electrical potential across the inner mitochondrial membrane (inside negative) and ΔpH is the pH gradient (matrix more alkaline than IMS). At physiological conditions, pmf ≈ 200 mV, with roughly 70% from ΔΨ and 30% from ΔpH.

ATP synthase uses the pmf to synthesize ATP via the binding-change mechanism: the flow of protons through the F₀ rotor drives rotation of the γ subunit within the F₁ complex, cycling its three β subunits through loose (L), tight (T), and open (O) conformational states. In the T state, bound ADP and Pᵢ are condensed to ATP; in the O state, ATP is released. Approximately 2.5–3 protons flow through F₀ per ATP synthesized.

Uncouplers such as 2,4-dinitrophenol (DNP) dissipate the proton gradient by carrying protons across the inner membrane independent of ATP synthase — they collapse the pmf without generating ATP, releasing energy as heat.`,
    figures: [],
    questions: [
      {
        id: 'mcat2-bb-036',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p8',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'Cellular respiration',
        foundationalConcept: 'FC 2',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'Which ETC complexes directly pump protons from the mitochondrial matrix to the intermembrane space?',
        choices: [
          { label: 'A', text: 'Complexes I, II, and III' },
          { label: 'B', text: 'Complexes I, III, and IV' },
          { label: 'C', text: 'Complexes II, III, and IV' },
          { label: 'D', text: 'Complexes I, II, III, and IV' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage states: "The free energy released drives proton pumping from the matrix into the intermembrane space at Complexes I, III, and IV." B reproduces this. Complex II (succinate dehydrogenase) does not pump protons; it accepts electrons from FADH₂ and passes them to ubiquinone without contributing to the proton gradient, which is why FADH₂ yields fewer ATP per mole than NADH.',
        wrongAnswerExplanations: {
          A: 'Complex II does not pump protons. It is the only ETC complex embedded in the inner membrane that does not contribute to the proton gradient.',
          C: 'Complex I (NADH dehydrogenase) is a proton pump; it should be included. Complex II does not pump protons.',
          D: 'All four complexes do not pump protons. Complex II oxidizes FADH₂ and transfers electrons to ubiquinone but does not pump protons.',
        },
        teachingPoint: 'ETC proton pumps: I, III, IV. NOT II. This is why FADH₂ (which enters at Complex II, bypassing Complex I) yields fewer ATP than NADH (which enters at Complex I, going through all three pumping complexes). FADH₂ ≈ 1.5 ATP; NADH ≈ 2.5 ATP.',
        relatedTopics: ['electron transport chain', 'proton pumping', 'NADH vs FADH2', 'Complex II', 'oxidative phosphorylation'],
      },
      {
        id: 'mcat2-bb-037',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p8',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'Cellular respiration',
        foundationalConcept: 'FC 2',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'DNP (2,4-dinitrophenol) increases oxygen consumption while decreasing ATP production. Based on the passage, why?',
        choices: [
          { label: 'A', text: 'DNP inhibits ATP synthase, preventing F₀ rotation' },
          { label: 'B', text: 'DNP dissipates the proton gradient, so the ETC continues oxidizing NADH (consuming O₂) but ATP synthase cannot synthesize ATP without the pmf' },
          { label: 'C', text: 'DNP inhibits Complexes I and III, reducing proton pumping' },
          { label: 'D', text: 'DNP converts NADH to FADH₂, reducing the ATP yield per electron pair' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage describes DNP as an uncoupler that "dissipates the proton gradient by carrying protons across the inner membrane independent of ATP synthase — they collapse the pmf without generating ATP, releasing energy as heat." Without a proton gradient, ATP synthase cannot operate. But the ETC continues running (it responds to the availability of NADH/FADH₂ and O₂, not to the pmf per se), consuming O₂ at high rates while generating no ATP. B captures this logic. A inverts DNP\'s target. C is wrong — DNP does not inhibit Complexes I or III. D is incorrect — DNP does not interconvert electron carriers.',
        wrongAnswerExplanations: {
          A: 'DNP does not inhibit ATP synthase directly. It collapses the proton gradient (the substrate for ATP synthase), so the enzyme has no driving force to use. ATP synthase inhibitor drugs (oligomycin) work differently.',
          C: 'DNP is a proton carrier (lipophilic weak acid) that dissipates the gradient — it does not inhibit ETC complexes.',
          D: 'DNP carries protons across the membrane; it does not alter NADH/FADH₂ chemistry.',
        },
        teachingPoint: 'Uncoupler mechanism: DNP carries H⁺ through the lipid bilayer → collapses ΔΨ and ΔpH → ATP synthase has no pmf to use → no ATP made. But ETC still oxidizes NADH/FADH₂ (driven by the thermodynamically favorable e⁻ transfer to O₂) → high O₂ consumption, low ATP. Energy released as heat — used (dangerously) as a diet drug historically.',
        relatedTopics: ['DNP', 'uncoupler', 'proton gradient', 'oxygen consumption', 'ETC vs ATP synthase'],
      },
      {
        id: 'mcat2-bb-038',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p8',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'Cellular respiration',
        foundationalConcept: 'FC 2',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'According to the binding-change mechanism, in which conformational state of the β subunit does ADP + Pᵢ condense to form ATP?',
        choices: [
          { label: 'A', text: 'Open (O) state' },
          { label: 'B', text: 'Loose (L) state' },
          { label: 'C', text: 'Tight (T) state' },
          { label: 'D', text: 'Protonated (P) state' },
        ],
        correctAnswer: 'C',
        explanation: 'The passage states: "In the T state, bound ADP and Pᵢ are condensed to ATP; in the O state, ATP is released." C (Tight state) is correct for ATP synthesis. A (Open) is where ATP is released. B (Loose) binds nucleotides loosely but has not yet condensed them. D is not a described conformational state.',
        wrongAnswerExplanations: {
          A: 'The Open state releases ATP. It has low nucleotide affinity and allows the synthesized ATP to leave the β subunit.',
          B: 'The Loose state binds ADP and Pᵢ but has not yet condensed them. Condensation to ATP occurs in the Tight state.',
          D: 'There is no "Protonated" conformational state in the binding-change mechanism. The three states are L (Loose), T (Tight), and O (Open).',
        },
        teachingPoint: 'Binding-change mechanism: L → T → O cycling driven by γ subunit rotation. L: binds ADP+Pi loosely. T: ADP+Pi → ATP (condensation). O: releases ATP (low affinity). All three β subunits are in different states simultaneously and cycle together.',
        relatedTopics: ['ATP synthase', 'binding-change mechanism', 'T state', 'β subunit', 'F1 complex'],
      },
      {
        id: 'mcat2-bb-039',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p8',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'Cellular respiration',
        foundationalConcept: 'FC 2',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'The passage states that approximately 70% of the pmf comes from ΔΨ and 30% from ΔpH. If a drug selectively eliminates the pH gradient while leaving ΔΨ intact, what fraction of the driving force for ATP synthesis would remain?',
        choices: [
          { label: 'A', text: '0% — the pH gradient is essential for ATP synthesis' },
          { label: 'B', text: '30%' },
          { label: 'C', text: '70%' },
          { label: 'D', text: '100% — ΔΨ alone is sufficient' },
        ],
        correctAnswer: 'C',
        explanation: 'The passage states pmf ≈ 200 mV total, with roughly 70% from ΔΨ and 30% from ΔpH. If the pH gradient (30%) is eliminated, the remaining driving force is 70% of the original pmf (from ΔΨ). ATP synthase uses the total pmf; with 70% remaining, it can still synthesize ATP but at a reduced rate. C is correct.',
        wrongAnswerExplanations: {
          A: 'ΔΨ alone can drive proton flow through F₀ and support ATP synthesis — chloroplasts and some bacteria demonstrate this experimentally. The pH gradient is not uniquely essential.',
          B: '30% would be what remains if ΔΨ were eliminated and only ΔpH remained — B has it backwards.',
          D: 'While ΔΨ alone can drive some ATP synthesis, 70% of the normal pmf remains — not 100%. ATP synthesis rate would be proportionally reduced.',
        },
        teachingPoint: 'pmf = ΔΨ (70%) + ΔpH (30%). Both components contribute to the proton motive force that drives F₀ rotation. Eliminating one component leaves the other, which still supports partial ATP synthesis. Classic experiment (Jagendorf 1966 with chloroplasts) showed pH gradient alone can drive ATP synthesis.',
        relatedTopics: ['pmf', 'ΔΨ', 'ΔpH', 'ATP synthesis driving force', 'proton motive force components'],
      },
      {
        id: 'mcat2-bb-040',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p8',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'Cellular respiration',
        foundationalConcept: 'FC 2',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'A patient with a genetic defect affecting the F₀ subunit of ATP synthase (preventing proton flow through F₀) would most likely exhibit which metabolic phenotype?',
        choices: [
          { label: 'A', text: 'Increased cellular ATP with normal O₂ consumption' },
          { label: 'B', text: 'Elevated proton gradient, reduced O₂ consumption, and severely reduced ATP production' },
          { label: 'C', text: 'Normal ATP production via enhanced glycolysis alone' },
          { label: 'D', text: 'Increased O₂ consumption with normal ATP production' },
        ],
        correctAnswer: 'B',
        explanation: 'If F₀ is defective and protons cannot flow through ATP synthase, two consequences follow: (1) ATP synthesis via oxidative phosphorylation fails → severely reduced ATP. (2) The proton gradient cannot be discharged by ATP synthase → the gradient builds up → back-pressure on the ETC proton pumps → electron flow through the ETC slows → O₂ consumption decreases. The cell is in a state similar to being treated with an ATP synthase inhibitor (like oligomycin). B captures both elevated pmf and reduced O₂/ATP. A inverts ATP production. C is incorrect — glycolysis can partially compensate but not fully (its 2 ATP/glucose vs. 30-32 from full oxidation). D is the uncoupler pattern (DNP), not the ATP synthase defect pattern.',
        wrongAnswerExplanations: {
          A: 'F₀ defect blocks proton flow → ATP synthase cannot rotate → no ATP synthesis. ATP does not increase.',
          C: 'Glycolysis produces only 2 ATP per glucose; OxPhos normally provides 30-32. Glycolysis alone cannot fully compensate for OxPhos deficiency, especially in high-energy-demand tissues.',
          D: 'Increased O₂ consumption with normal ATP is the uncoupler (DNP) pattern: proton gradient is dissipated without going through ATP synthase, so ETC runs fast (high O₂) but makes no ATP. An F₀ defect that blocks proton flow has the opposite effect — gradient builds, ETC slows, O₂ decreases.',
        },
        teachingPoint: 'F₀/ATP synthase inhibition (oligomycin/F₀ defect) vs. uncoupler (DNP): Inhibitor blocks proton flow → pmf builds → ETC back-pressure → O₂ consumption falls, no ATP. Uncoupler dissipates pmf without ATP → ETC runs fast → high O₂ consumption, no ATP. Both produce no ATP but have opposite effects on O₂ consumption.',
        relatedTopics: ['ATP synthase defect', 'F0 subunit', 'oligomycin', 'proton back-pressure', 'O₂ consumption'],
      },
    ],
  },

  // ─── B/B Passage 9: Protein Folding and Chaperones ──────────────────────────
  {
    id: 'f2-bb-p9',
    sectionId: 'bio-biochem',
    title: 'Protein Folding, Chaperones, and Misfolding Diseases',
    passageText: `The thermodynamic hypothesis of protein folding — articulated by Anfinsen in his 1972 Nobel lecture — states that the native conformation of a protein is the one with the lowest Gibbs free energy under physiological conditions, and that this conformation is fully determined by the amino acid sequence. Anfinsen demonstrated this with ribonuclease A: complete denaturation with urea and β-mercaptoethanol followed by removal of denaturants yielded spontaneous refolding to full enzymatic activity, showing that no information beyond the primary sequence is required.

In the cellular environment, however, spontaneous folding of many proteins is complicated by the high concentration of macromolecules (molecular crowding), which promotes non-productive inter-molecular aggregation of exposed hydrophobic surfaces. Molecular chaperones — proteins that assist in folding without becoming part of the final structure — counteract aggregation by transiently shielding hydrophobic surfaces. The Hsp70 system binds extended polypeptide chains emerging from the ribosome; the GroEL/GroES (chaperonin) system provides an isolated hydrophilic cavity for folding of medium-sized proteins (20–60 kDa). Both systems use ATP hydrolysis to cycle between high-affinity (substrate-bound) and low-affinity (substrate-released) states.

Protein misfolding underlies several neurodegenerative diseases. In Alzheimer's disease, amyloid-β peptides and tau protein aggregate into amyloid fibrils — β-sheet-rich, protease-resistant structures. In Parkinson's disease, α-synuclein misfolds and aggregates into Lewy bodies. Prion diseases (e.g., CJD, scrapie) involve the conversion of normal cellular prion protein (PrPᶜ) to the misfolded, protease-resistant conformer PrPˢᶜ. Notably, PrPˢᶜ acts as a template, recruiting and converting PrPᶜ — a mechanism of infectious propagation that requires no nucleic acid.`,
    figures: [],
    questions: [
      {
        id: 'mcat2-bb-041',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p9',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'Protein structure and folding',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'What does Anfinsen\'s ribonuclease experiment demonstrate?',
        choices: [
          { label: 'A', text: 'Chaperones are required for proper folding of all proteins' },
          { label: 'B', text: 'The native protein conformation is fully encoded in the amino acid sequence and can be reached spontaneously' },
          { label: 'C', text: 'Protein folding requires RNA templates beyond the primary sequence' },
          { label: 'D', text: 'Disulfide bonds cannot re-form spontaneously after reduction' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage describes Anfinsen\'s demonstration: ribonuclease A was completely denatured (destroying secondary/tertiary structure and reducing disulfide bonds), then spontaneously refolded to "full enzymatic activity" upon removal of denaturants. This shows that all information needed for the correct conformation is in the amino acid sequence — no additional templates, chaperones, or information beyond primary sequence is required. B is correct. A is contradicted (spontaneous refolding without chaperones). C is contradicted. D is contradicted (refolding includes re-oxidation of disulfide bonds).',
        wrongAnswerExplanations: {
          A: 'Anfinsen\'s experiment shows RNase A refolds without chaperones. The passage separately notes chaperones are important in the crowded cellular environment, not as a universal requirement.',
          C: 'The experiment explicitly showed "no information beyond the primary sequence is required" — the opposite of requiring an RNA template.',
          D: 'The refolding to "full enzymatic activity" implies disulfide bonds reformed correctly upon reoxidation. Disulfide bonds can re-form spontaneously under oxidizing conditions.',
        },
        teachingPoint: 'Anfinsen\'s thermodynamic hypothesis: native state = lowest free energy state; encoded entirely by amino acid sequence. Demonstrated by denaturation and spontaneous refolding of RNase A. "Sequence → structure" is the central dogma of protein folding.',
        relatedTopics: ['Anfinsen', 'thermodynamic hypothesis', 'ribonuclease A', 'protein folding', 'amino acid sequence'],
      },
      {
        id: 'mcat2-bb-042',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p9',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'Protein structure and folding',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'Molecular chaperones assist protein folding primarily by:',
        choices: [
          { label: 'A', text: 'Providing an alternative amino acid sequence for refolding' },
          { label: 'B', text: 'Transiently shielding exposed hydrophobic surfaces to prevent non-productive aggregation' },
          { label: 'C', text: 'Covalently linking protein subunits to stabilize the native state' },
          { label: 'D', text: 'Accelerating the thermodynamic search for the lowest free energy state by lowering activation energy for every folding step' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage states chaperones "counteract aggregation by transiently shielding hydrophobic surfaces." They prevent the problem of crowded-environment aggregation, not the thermodynamic search itself. B is correct. A is wrong — chaperones do not alter primary sequence. C is wrong — chaperones do not become part of the final structure (as stated: "without becoming part of the final structure"). D overstates; chaperones prevent misfolding/aggregation, not uniformly lower all folding activation energies.',
        wrongAnswerExplanations: {
          A: 'Chaperones are proteins that assist folding; they do not provide or alter the amino acid sequence.',
          C: 'The passage explicitly states chaperones assist folding "without becoming part of the final structure." They interact transiently and then release the folded protein.',
          D: 'Chaperones prevent aggregation and allow correct folding to occur — they don\'t universally lower activation energies for all folding steps. They create a protected environment for folding.',
        },
        teachingPoint: 'Chaperone function: prevent aggregation by shielding hydrophobic patches from the crowded cellular milieu. Hsp70 binds nascent chains; GroEL/ES provides a protected cavity. Both use ATP cycling. They do not change which conformation is thermodynamically favored — Anfinsen\'s hypothesis still applies.',
        relatedTopics: ['molecular chaperones', 'Hsp70', 'GroEL', 'hydrophobic effect', 'protein aggregation'],
      },
      {
        id: 'mcat2-bb-043',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p9',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'Protein structure and folding',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 2',
        difficulty: 'hard',
        question: 'Prion propagation is described as "infectious" without nucleic acid. What molecular mechanism accounts for this, according to the passage?',
        choices: [
          { label: 'A', text: 'PrPˢᶜ acts as an enzyme that catalyzes the irreversible chemical modification of PrPᶜ' },
          { label: 'B', text: 'PrPˢᶜ acts as a conformational template, recruiting normal PrPᶜ and inducing it to adopt the misfolded PrPˢᶜ conformation' },
          { label: 'C', text: 'PrPˢᶜ contains a retroviral reverse transcriptase that synthesizes a prion RNA' },
          { label: 'D', text: 'PrPˢᶜ suppresses chaperone function, allowing all cellular proteins to misfold' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage states: "PrPˢᶜ acts as a template, recruiting and converting PrPᶜ — a mechanism of infectious propagation that requires no nucleic acid." B captures this exactly: conformational templating. PrPˢᶜ does not chemically modify PrPᶜ (ruling out A — no covalent catalysis). No reverse transcriptase is involved (ruling out C). PrPˢᶜ does not generally suppress chaperone function (ruling out D).',
        wrongAnswerExplanations: {
          A: 'Prion propagation is a conformational conversion, not a covalent enzymatic modification. PrPᶜ and PrPˢᶜ have the same primary sequence — only their conformation differs.',
          C: 'Prion propagation is defined by the absence of nucleic acid. No reverse transcriptase or RNA is involved — this was the revolutionary insight that challenged the central dogma (information can propagate as protein conformation alone).',
          D: 'PrPˢᶜ specifically converts PrPᶜ; it does not broadly suppress chaperone function or cause widespread misfolding of other proteins.',
        },
        teachingPoint: 'Prion mechanism: PrPˢᶜ (misfolded, β-sheet rich, protease-resistant) templates PrPᶜ (normal, α-helix rich) to adopt PrPˢᶜ conformation → exponential growth of misfolded aggregate. No nucleic acid needed — protein conformation itself is the "infectious" agent. This challenged central dogma assumptions about information flow.',
        relatedTopics: ['prion', 'PrPsc', 'conformational templating', 'infectious protein', 'amyloid'],
      },
      {
        id: 'mcat2-bb-044',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p9',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'Protein structure and folding',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 4',
        difficulty: 'medium',
        question: 'A protein that requires GroEL/GroES for folding would most likely have which characteristic?',
        choices: [
          { label: 'A', text: 'A molecular weight under 5 kDa' },
          { label: 'B', text: 'A molecular weight of approximately 20–60 kDa and significant risk of aggregation without a protected folding cavity' },
          { label: 'C', text: 'A primary structure entirely composed of polar residues' },
          { label: 'D', text: 'A secondary structure with exclusively α-helices, no β-sheets' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage states GroEL/GroES provides "an isolated hydrophilic cavity for folding of medium-sized proteins (20–60 kDa)." This is the defining characteristic: the protein is in the 20–60 kDa range and needs protection from aggregation. B matches directly. A (under 5 kDa) is too small — such proteins generally fold without chaperonins. C (all polar residues) is not a distinguishing feature mentioned. D (only α-helices) is not the relevant structural criterion — size and aggregation propensity are.',
        wrongAnswerExplanations: {
          A: 'Very small proteins (< 5 kDa) typically fold spontaneously without chaperonins. GroEL/GroES is for medium-sized proteins.',
          C: 'Aggregation is driven by exposed hydrophobic surfaces. A protein with only polar residues would be less prone to aggregation and likely would not need GroEL/GroES.',
          D: 'The folding substrate requirement is based on size (20–60 kDa) and aggregation propensity, not secondary structure content.',
        },
        teachingPoint: 'GroEL/GroES substrate profile: medium-sized proteins (20–60 kDa) that are aggregation-prone. GroEL barrel provides a hydrophilic, isolated cavity where one protein at a time folds protected from crowding. Classic substrates include RuBisCO and other essential cellular enzymes.',
        relatedTopics: ['GroEL', 'GroES', 'chaperonin', 'protein size', 'folding cavity'],
      },
      {
        id: 'mcat2-bb-045',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p9',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'Protein structure and folding',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'Amyloid fibrils, Lewy bodies, and PrPˢᶜ aggregates are all described as β-sheet-rich and protease-resistant. What structural property likely explains their protease resistance?',
        choices: [
          { label: 'A', text: 'The aggregates have no exposed peptide bonds for proteases to cleave' },
          { label: 'B', text: 'Tightly stacked β-sheets in amyloid structures bury the polypeptide backbone, reducing protease accessibility' },
          { label: 'C', text: 'The β-sheet conformation covalently links adjacent polypeptide chains' },
          { label: 'D', text: 'Amyloid β-sheet fibrils have a lower molecular weight than protease substrates' },
        ],
        correctAnswer: 'B',
        explanation: 'Amyloid fibrils are composed of tightly packed, hydrogen-bonded β-sheets running perpendicular to the fibril axis. This tight stacking buries much of the polypeptide backbone in the hydrophobic core and shields the substrate from proteolytic enzymes. The steric inaccessibility of the backbone — not the absence of peptide bonds — confers resistance. B captures this structural reasoning. A is incorrect — peptide bonds exist throughout but are sterically protected. C is incorrect — amyloid fibrils are held by non-covalent interactions (hydrogen bonds), not covalent links. D is wrong — amyloid aggregates are typically large, not small.',
        wrongAnswerExplanations: {
          A: 'Amyloid fibrils are polypeptides and therefore contain many peptide bonds. The resistance comes from the bonds being physically inaccessible to proteases due to tight packing.',
          C: 'Amyloid fibrils are stabilized by extensive intermolecular hydrogen bonds, not covalent cross-links (though some amyloid modifications can involve covalent bonds, the primary structural basis is non-covalent H-bonding).',
          D: 'Amyloid aggregates are large, insoluble macromolecular assemblies — not small. Their size would not confer protease resistance; if anything, larger substrates are cleaved efficiently by many proteases.',
        },
        teachingPoint: 'Amyloid β-sheet structure: cross-β structure with H-bonds parallel to fibril axis, strands perpendicular. Tight packing buries backbone, limiting protease access. This structural basis explains clinical failure to clear amyloid — normal cellular proteolysis cannot efficiently degrade fibrils.',
        relatedTopics: ['amyloid fibril', 'β-sheet', 'protease resistance', 'cross-β structure', 'neurodegenerative disease'],
      },
    ],
  },

  // ─── B/B Passage 10: Cell Cycle and Tumor Suppressor Genes ─────────────────
  {
    id: 'f2-bb-p10',
    sectionId: 'bio-biochem',
    title: 'The Retinoblastoma Protein and G1/S Checkpoint',
    passageText: `Cell cycle progression is controlled by cyclin-dependent kinases (CDKs) whose activity requires association with regulatory subunits called cyclins. At the G1/S checkpoint, Cyclin D accumulates in response to mitogenic signals and activates CDK4/6. Active CDK4/6-Cyclin D phosphorylates the retinoblastoma protein (Rb), partially inactivating it. Subsequent Cyclin E-CDK2 activity hyperphorylates Rb, completing its inactivation. Underphosphorylated (active) Rb binds the transcription factor E2F, preventing transcription of genes required for S-phase entry (DNA polymerase, thymidine kinase, etc.). Hyperphosphorylated (inactive) Rb releases E2F, allowing S-phase gene transcription and DNA replication to proceed.

The p16INK4a tumor suppressor inhibits CDK4/6, preventing Rb phosphorylation and enforcing G1 arrest. p53 is activated by DNA damage and transcriptionally induces p21CIP1, a broad CDK inhibitor that blocks multiple CDK/cyclin complexes; p53 also induces apoptosis via Bax upregulation and Bcl-2 downregulation. Loss of p53 function — through mutation, deletion, or viral oncoprotein binding (e.g., HPV E6 targets p53 for proteasomal degradation) — removes a critical brake on cell cycle progression.

In the "two-hit hypothesis" formulated by Knudson for hereditary retinoblastoma, individuals who inherit one mutant RB1 allele require only one additional somatic mutation in the second allele to develop tumor. Sporadic retinoblastoma requires two independent somatic mutations in both alleles of the same cell, which is much less likely — consistent with the earlier age of onset and bilateral presentation in hereditary cases.`,
    figures: [],
    questions: [
      {
        id: 'mcat2-bb-046',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p10',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Cell cycle',
        foundationalConcept: 'FC 2',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'When Rb is underphosphorylated (active), what effect does it have on cell cycle progression?',
        choices: [
          { label: 'A', text: 'It activates E2F, promoting transcription of S-phase genes' },
          { label: 'B', text: 'It binds and sequesters E2F, preventing S-phase gene transcription and G1/S progression' },
          { label: 'C', text: 'It activates CDK4/6 to phosphorylate itself' },
          { label: 'D', text: 'It induces apoptosis by activating Bax' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage states: "Underphosphorylated (active) Rb binds the transcription factor E2F, preventing transcription of genes required for S-phase entry." B reproduces this: active Rb sequesters E2F, blocking S-phase gene transcription and preventing G1→S transition. A inverts the relationship. C is wrong — Rb does not activate CDK4/6. D is p53\'s mechanism.',
        wrongAnswerExplanations: {
          A: 'Active Rb INHIBITS E2F by binding it. Hyperphosphorylated (inactive) Rb releases E2F, allowing E2F to activate transcription.',
          C: 'Rb does not activate CDK4/6. CDK4/6 (activated by Cyclin D) phosphorylates Rb, not vice versa.',
          D: 'Bax activation is downstream of p53, not Rb. These are separate tumor suppressor pathways.',
        },
        teachingPoint: 'Rb as gatekeeper: active (hypophosphorylated) Rb = brake. It sequesters E2F → no S-phase genes → G1 arrest. CDK4/6-CycD → partial phosphorylation; CDK2-CycE → hyperphosphorylation → Rb inactivation → E2F free → S-phase entry.',
        relatedTopics: ['Rb protein', 'E2F', 'G1/S checkpoint', 'CDK4/6', 'cell cycle'],
      },
      {
        id: 'mcat2-bb-047',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p10',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Cell cycle',
        foundationalConcept: 'FC 2',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'How does loss of p16INK4a promote uncontrolled cell proliferation?',
        choices: [
          { label: 'A', text: 'p16 loss activates p53, driving apoptosis' },
          { label: 'B', text: 'p16 loss removes inhibition of CDK4/6 → CDK4/6 hyperactivates → Rb is hyperphosphorylated → E2F released → uncontrolled S-phase entry' },
          { label: 'C', text: 'p16 loss increases Cyclin D synthesis' },
          { label: 'D', text: 'p16 loss directly activates MAPK signaling' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage states p16INK4a "inhibits CDK4/6, preventing Rb phosphorylation and enforcing G1 arrest." Loss of p16 removes CDK4/6 inhibition → CDK4/6 is constitutively active → Rb is continuously phosphorylated → E2F is continuously released → S-phase genes are always transcribed → uncontrolled proliferation. B traces this pathway. A confuses the pathway direction. C is not the mechanism — p16 inhibits CDK4/6 directly, without affecting Cyclin D levels. D is not described.',
        wrongAnswerExplanations: {
          A: 'p16 loss promotes proliferation, not p53 activation/apoptosis. p53 is activated by DNA damage through a different pathway.',
          C: 'p16 loss allows CDK4/6 to be active without also needing more Cyclin D. The brake (p16 inhibition of CDK4/6) is removed, not the gas pedal (Cyclin D) increased.',
          D: 'p16 is a CDK inhibitor in the cell cycle pathway; it does not directly regulate MAPK signaling.',
        },
        teachingPoint: 'p16 → CDK4/6 inhibitor → Rb hypophosphorylated → G1 arrest. p16 loss → CDK4/6 unrestrained → Rb hyperphosphorylated → E2F free → S-phase entry. p16 is frequently deleted in melanoma, pancreatic cancer, and other tumor types.',
        relatedTopics: ['p16INK4a', 'CDK4/6', 'Rb pathway', 'tumor suppressor', 'G1 arrest'],
      },
      {
        id: 'mcat2-bb-048',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p10',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Cell cycle',
        foundationalConcept: 'FC 2',
        scientificSkill: 'Skill 2',
        difficulty: 'hard',
        question: 'HPV E6 promotes cervical cancer development by which mechanism described in the passage?',
        choices: [
          { label: 'A', text: 'E6 activates Rb, keeping E2F sequestered' },
          { label: 'B', text: 'E6 targets p53 for proteasomal degradation, removing the DNA damage-induced growth arrest and apoptosis checkpoint' },
          { label: 'C', text: 'E6 activates p21CIP1, blocking CDK activity' },
          { label: 'D', text: 'E6 inhibits Cyclin D synthesis' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage states: "HPV E6 targets p53 for proteasomal degradation" and that "Loss of p53 function... removes a critical brake on cell cycle progression." With p53 degraded, cells with DNA damage cannot arrest in G1 (via p21) or undergo apoptosis (via Bax/Bcl-2 regulation). Unrepaired DNA damage accumulates → additional mutations → cancer progression. B correctly applies the passage. A is wrong — E6 targets p53, not Rb. C is wrong — E6 degrades p53, which normally induces p21; E6 would thereby decrease p21 activity, not increase it. D is wrong — E6 does not inhibit Cyclin D.',
        wrongAnswerExplanations: {
          A: 'E6 targets p53, not Rb. HPV E7 (another HPV oncoprotein not mentioned in the passage) targets Rb.',
          C: 'p21CIP1 is induced BY p53. Degrading p53 via E6 would REDUCE p21 activity, not increase it.',
          D: 'E6 specifically targets p53 for proteasomal degradation via E3 ubiquitin ligase recruitment. It does not inhibit Cyclin D synthesis.',
        },
        teachingPoint: 'HPV oncoproteins: E6 degrades p53 (removes DNA damage checkpoint), E7 inactivates Rb (removes G1/S brake). Together, they eliminate two critical tumor suppressors. This is why HPV is causative for cervical cancer — loss of both checkpoints allows accumulation of mutations and uncontrolled proliferation.',
        relatedTopics: ['HPV E6', 'p53 degradation', 'proteasomal degradation', 'cervical cancer', 'viral oncoproteins'],
      },
      {
        id: 'mcat2-bb-049',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p10',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Cell cycle',
        foundationalConcept: 'FC 2',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'According to Knudson\'s two-hit hypothesis, why does hereditary retinoblastoma typically present at an earlier age and in both eyes compared to sporadic retinoblastoma?',
        choices: [
          { label: 'A', text: 'Hereditary retinoblastoma involves a more aggressive viral oncogene' },
          { label: 'B', text: 'In hereditary cases, every cell already carries one mutant RB1 allele, so only one additional somatic mutation is needed per cell — making bilateral tumor development much more likely than in sporadic cases requiring two independent somatic mutations' },
          { label: 'C', text: 'Hereditary retinoblastoma arises from environmental carcinogen exposure that primarily affects young children' },
          { label: 'D', text: 'Hereditary cases have a dominant gain-of-function Rb mutation that actively promotes tumor formation' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage states: "individuals who inherit one mutant RB1 allele require only one additional somatic mutation in the second allele to develop tumor. Sporadic retinoblastoma requires two independent somatic mutations in both alleles of the same cell." In hereditary cases, every retinal cell is "one hit away" from losing all Rb function — so many cells can independently reach zero Rb function, leading to earlier onset and bilateral (both eye) presentation. Sporadic cases need two random events in the same cell — much rarer, tending to be unilateral and later in onset. B captures this logic. A, C, and D are not in the passage.',
        wrongAnswerExplanations: {
          A: 'Retinoblastoma is caused by RB1 mutations, not viral oncogenes.',
          C: 'The two-hit model explains the age and laterality difference without invoking environmental carcinogens.',
          D: 'Rb is a tumor suppressor, not an oncogene. Hereditary retinoblastoma involves loss-of-function mutations, not dominant gain-of-function.',
        },
        teachingPoint: 'Two-hit hypothesis: tumor suppressors require loss of both alleles ("two hits") for tumor development. Hereditary cases: one hit is inherited (germline) → only one somatic hit needed → multiple independent cells can reach homozygous null state → multiple, bilateral, early tumors. Sporadic: both hits must be somatic → rare → later, usually unilateral.',
        relatedTopics: ['two-hit hypothesis', 'Knudson', 'tumor suppressor', 'RB1', 'bilateral retinoblastoma'],
      },
      {
        id: 'mcat2-bb-050',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p10',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Cell cycle',
        foundationalConcept: 'FC 2',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'A cancer cell line has a mutation inactivating p21CIP1 but an intact p53 gene. Following DNA damage, what would most likely occur?',
        choices: [
          { label: 'A', text: 'Normal G1 arrest because p53 can still activate other CDK inhibitors' },
          { label: 'B', text: 'Impaired G1 arrest because p21, which normally blocks CDKs after p53 induction, is nonfunctional — but apoptosis via Bax/Bcl-2 may still occur' },
          { label: 'C', text: 'Enhanced DNA repair because p53 transcription is unimpaired' },
          { label: 'D', text: 'No consequence because p21 is redundant with CDK4/6 activity in G1 arrest' },
        ],
        correctAnswer: 'B',
        explanation: 'p53 is intact, so DNA damage → p53 activation → p53 transcribes target genes. One target is p21CIP1, which mediates G1 arrest by blocking CDK activity. If p21 is inactivated, this arm of p53\'s response fails → G1 arrest is impaired. However, p53 has other outputs: transcription of Bax (pro-apoptotic) and repression of Bcl-2 (anti-apoptotic) — these can still occur. So the cell is likely to undergo apoptosis (or proceed through the cell cycle with unrepaired DNA) rather than properly arresting. B captures both aspects: impaired arrest (p21 nonfunctional) but preserved apoptosis potential (p53-Bax/Bcl-2 intact). A assumes p53 can substitute p21 — not described. C is unrelated to arrest. D incorrectly dismisses p21\'s role.',
        wrongAnswerExplanations: {
          A: 'The passage identifies p21CIP1 as the specific CDK inhibitor induced by p53 for G1 arrest. Without p21, the G1 arrest mechanism is impaired, even with intact p53.',
          C: 'DNA repair capacity depends on repair enzymes, not on p53 transcriptional activity per se. p53 induces cell arrest to allow repair time — without arrest (no p21), cells may replicate before repair is complete.',
          D: 'p21 is not redundant with CDK4/6; it is a CDK inhibitor that blocks multiple CDK/cyclin complexes. Its loss impairs G1 arrest specifically.',
        },
        teachingPoint: 'p53 has multiple effector arms: (1) G1 arrest via p21 induction; (2) apoptosis via Bax upregulation/Bcl-2 downregulation; (3) senescence. Loss of p21 specifically impairs the arrest arm but leaves apoptosis intact. This is clinically relevant — p21 loss can allow cells to cycle with damaged DNA, increasing mutation rate.',
        relatedTopics: ['p21CIP1', 'p53 effectors', 'G1 arrest', 'Bax', 'Bcl-2', 'DNA damage response'],
      },
    ],
  },
]
