import type { MCATPassage } from '../types'

// Form 2 B/B — Passages 1–5
// Topics: DNA Replication, Enzyme Catalysis, Cell Signaling, Muscle Physiology, Immunology
// Questions: 5+5+5+5+5 = 25 questions (IDs mcat2-bb-001 through mcat2-bb-025)

export const bbPassages01to05: MCATPassage[] = [
  // ─── B/B Passage 1: DNA Replication Fidelity and Repair ─────────────────────
  {
    id: 'f2-bb-p1',
    sectionId: 'bio-biochem',
    title: 'Proofreading and Mismatch Repair in DNA Replication',
    passageText: `Accurate DNA replication requires multiple error-correction mechanisms acting in series. DNA polymerase III in E. coli achieves an intrinsic error rate of approximately 10⁻⁵ per base pair through its 3'→5' exonuclease proofreading activity, which excises incorrectly incorporated nucleotides immediately after misincorporation. After proofreading, the residual error rate is approximately 10⁻⁷ per base pair. A subsequent post-replication mismatch repair (MMR) system reduces errors by an additional factor of 10²–10³, yielding a final error rate of approximately 10⁻⁹ to 10⁻¹⁰ per base pair per replication cycle.

MMR in E. coli depends on the ability of the MutS–MutL–MutH complex to discriminate between the newly synthesized strand (containing errors) and the template strand (which is transiently hemimethylated at GATC sequences). MutH endonuclease incises the unmethylated strand at GATC sites near the mismatch; the excision repair machinery then removes a segment spanning the mismatch on the new strand and resynthesizes it.

Hereditary nonpolyposis colorectal cancer (HNPCC, also called Lynch syndrome) results from germline mutations in human MMR genes (most commonly MLH1 and MSH2). Cells with defective MMR accumulate microsatellite instability (MSI): slippage errors at short tandem repeat sequences that are normally corrected by MMR. MSI is used clinically as a biomarker for HNPCC and predicts response to immune checkpoint inhibitors, because hypermutated tumors generate abundant neoantigens recognized by T cells.`,
    figures: [],
    questions: [
      {
        id: 'mcat2-bb-001',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p1',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'DNA replication and repair',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'Based on the passage, what is the approximate overall error rate reduction achieved by combining intrinsic proofreading with mismatch repair?',
        choices: [
          { label: 'A', text: '10-fold' },
          { label: 'B', text: '1,000-fold' },
          { label: 'C', text: '100,000-fold (10⁵-fold)' },
          { label: 'D', text: '10⁷-fold' },
        ],
        correctAnswer: 'C',
        explanation: 'Proofreading reduces error rate from 10⁻⁵ to 10⁻⁷ — a 100-fold (10²) reduction. MMR then reduces the 10⁻⁷ rate by 10²–10³, yielding 10⁻⁹ to 10⁻¹⁰. Total reduction from base rate: 10⁻⁵ → 10⁻¹⁰ = 10⁵-fold reduction. Answer C (100,000-fold = 10⁵) is correct. Answer B gives 1,000-fold (10³), which is only the MMR contribution. Answer D (10⁷-fold) overstates.',
        wrongAnswerExplanations: {
          A: '10-fold would yield 10⁻⁶, which is far worse than what the passage describes.',
          B: '1,000-fold represents only the MMR contribution (10⁻⁷ × 10⁻³ = 10⁻¹⁰). The full combined reduction from the starting 10⁻⁵ to 10⁻¹⁰ is 10⁵-fold.',
          D: '10⁷-fold is not supported by the numbers in the passage. The final rate of ~10⁻¹⁰ represents a 10⁵-fold improvement over the intrinsic 10⁻⁵ rate.',
        },
        teachingPoint: 'Serial error correction: proofreading achieves 10⁻⁵ → 10⁻⁷ (10²-fold). MMR achieves another 10²–10³-fold. Combined: ~10⁵-fold total reduction from baseline intrinsic polymerase error rate.',
        relatedTopics: ['DNA polymerase proofreading', 'mismatch repair', 'error rate calculation', 'sequential correction'],
      },
      {
        id: 'mcat2-bb-002',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p1',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'DNA replication and repair',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'How does the MMR system in E. coli distinguish the newly synthesized (error-containing) strand from the template strand?',
        choices: [
          { label: 'A', text: 'The new strand is distinguished by its lower GC content' },
          { label: 'B', text: 'The new strand is transiently unmethylated at GATC sequences, whereas the template is methylated' },
          { label: 'C', text: 'The new strand contains ribonucleotides that flag it for repair' },
          { label: 'D', text: 'MutS recognizes the 5′ end of the new strand and flags it for excision' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage states that MMR discriminates "between the newly synthesized strand (containing errors) and the template strand (which is transiently hemimethylated at GATC sequences)." The new strand has not yet been methylated, creating a hemimethylated duplex that MutH uses to direct incision to the correct (unmethylated, new) strand. B is accurate. A (GC content) is not a recognition mechanism. C (ribonucleotides) is used by some eukaryotic systems (RNase H2 removes misincorporated ribonucleotides) but is not the passage\'s described mechanism. D misidentifies MutS\'s role (it recognizes mismatches, not strand ends).',
        wrongAnswerExplanations: {
          A: 'GC content is not used to identify the new strand for MMR.',
          C: 'The passage describes methylation-based discrimination, not ribonucleotide-based. Eukaryotic MMR has some strand discrimination involving RNA primers, but that is not the mechanism described here.',
          D: 'MutS recognizes mismatches and recruits MutL; MutH incises the strand at hemimethylated GATC sites. The 5′ end is not the primary recognition signal described.',
        },
        teachingPoint: 'E. coli MMR strand discrimination: newly replicated DNA is transiently hemimethylated — template is methylated at GATC, new strand is not yet. MutH incises the unmethylated (new) strand near the mismatch, ensuring repair targets the correct strand.',
        relatedTopics: ['mismatch repair', 'GATC methylation', 'hemimethylation', 'MutH', 'strand discrimination'],
      },
      {
        id: 'mcat2-bb-003',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p1',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'DNA replication and repair',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'A patient\'s tumor displays high microsatellite instability (MSI-H) and is found to have a somatic mutation inactivating MLH1. Which treatment would this finding most support, according to the passage?',
        choices: [
          { label: 'A', text: 'Platinum-based chemotherapy, because MMR-deficient cells cannot repair cross-links' },
          { label: 'B', text: 'Immune checkpoint inhibitor therapy, because hypermutated tumors generate neoantigens recognized by T cells' },
          { label: 'C', text: 'VEGF inhibitors, because microsatellite instability increases tumor angiogenesis' },
          { label: 'D', text: 'Radiation therapy alone, because MMR-deficient cells are more sensitive to double-strand breaks' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage explicitly states: "MSI is used clinically as a biomarker for HNPCC and predicts response to immune checkpoint inhibitors, because hypermutated tumors generate abundant neoantigens recognized by T cells." B directly applies this statement. A is plausible mechanistically (MMR-deficient cells are actually resistant to platinum, not sensitive) but is not what the passage supports. C (VEGF) has no support in the passage. D has no support in the passage.',
        wrongAnswerExplanations: {
          A: 'MMR-deficient tumors are actually RESISTANT to platinum-based chemotherapy because they cannot recognize platinum adducts as DNA damage that needs to trigger apoptosis. This is the opposite of the clinical situation.',
          C: 'VEGF inhibitors (anti-angiogenic therapy) have no mechanistic connection to MSI or MMR deficiency described in the passage.',
          D: 'Radiation sensitivity in MMR-deficient cells is not mentioned in the passage. The passage specifies checkpoint inhibitor response as the clinical implication of MSI.',
        },
        teachingPoint: 'MSI-H tumors → many neoantigens → recognized by T cells → respond to immune checkpoint inhibitors (e.g., pembrolizumab). This is why FDA approved pembrolizumab for MSI-H/dMMR tumors regardless of tissue of origin — a landmark biomarker-driven approval.',
        relatedTopics: ['MSI', 'Lynch syndrome', 'checkpoint inhibitors', 'neoantigens', 'immunotherapy'],
      },
      {
        id: 'mcat2-bb-004',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p1',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'DNA replication and repair',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'The 3′→5′ exonuclease activity of DNA polymerase III primarily serves which function?',
        choices: [
          { label: 'A', text: 'Removing RNA primers from Okazaki fragments' },
          { label: 'B', text: 'Excising incorrectly incorporated nucleotides immediately after misincorporation' },
          { label: 'C', text: 'Degrading the template strand to allow strand separation' },
          { label: 'D', text: 'Synthesizing new DNA in the 3′→5′ direction' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage directly states: "DNA polymerase III... achieves an intrinsic error rate of approximately 10⁻⁵ per base pair through its 3′→5′ exonuclease proofreading activity, which excises incorrectly incorporated nucleotides immediately after misincorporation." B reproduces this. A (removing RNA primers) is the function of 5′→3′ exonuclease activity (DNA Pol I in E. coli, or FEN1/RNase H in eukaryotes). C is not an exonuclease function in replication. D is incorrect — DNA synthesis proceeds 5′→3′; the exonuclease moves 3′→5′.',
        wrongAnswerExplanations: {
          A: 'RNA primer removal requires 5′→3′ exonuclease activity (DNA Pol I\'s 5′→3′ exo), not 3′→5′.',
          C: '3′→5′ exonuclease activity removes single nucleotides from the 3′ end of the growing strand; it does not degrade the template.',
          D: 'DNA synthesis itself proceeds 5′→3′ (adding nucleotides to the 3′ end). The 3′→5′ exonuclease activity runs in the opposite direction for error correction, not synthesis.',
        },
        teachingPoint: '3′→5′ exonuclease = proofreading. It removes the last-added nucleotide from the 3′ end when a mismatch is detected. Distinct from 5′→3′ exonuclease (primer removal). Both directions refer to the direction of movement along the strand being degraded.',
        relatedTopics: ['DNA polymerase proofreading', '3′→5′ exonuclease', 'DNA replication fidelity'],
      },
      {
        id: 'mcat2-bb-005',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p1',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'DNA replication and repair',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'If a strain of E. coli had its GATC methyltransferase (Dam methylase) inactivated, what would be the most likely consequence for MMR fidelity?',
        choices: [
          { label: 'A', text: 'Improved MMR fidelity because more GATC sites would be available for MutH cleavage' },
          { label: 'B', text: 'Reduced MMR fidelity because MMR could no longer reliably distinguish the new strand from the template' },
          { label: 'C', text: 'No change because MMR uses a methylation-independent mechanism' },
          { label: 'D', text: 'Cell death because methylation is required for chromosome segregation' },
        ],
        correctAnswer: 'B',
        explanation: 'MMR strand discrimination depends on hemimethylation: the template is methylated, the new strand is not yet methylated. If Dam methylase is inactivated, neither strand will be methylated at GATC sites. MutH will be unable to distinguish which strand is old (template) and which is new (newly synthesized). Without this discrimination, MMR cannot correctly direct excision to the error-containing strand, reducing fidelity (and potentially causing incorrect strand excision). B is correct. A is incorrect — more sites for MutH cleavage doesn\'t help if strand identity cannot be determined. C is contradicted by the passage. D overstates; Dam⁻ E. coli is viable, though with elevated mutation rates.',
        wrongAnswerExplanations: {
          A: 'If neither strand is methylated, MutH cannot determine which strand to incise. More GATC sites that are all unmethylated would lead to random incision, not improved fidelity.',
          C: 'The passage explicitly states that MMR discriminates using hemimethylation at GATC sequences — methylation is central to the mechanism.',
          D: 'Dam⁻ E. coli mutants are viable. Methylation is important for mismatch repair and some aspects of replication timing, but its loss is not lethal.',
        },
        teachingPoint: 'Dam methylase inactivation → no hemimethylation → MutH cannot tell old from new strand → MMR directs repair to the wrong strand as often as the right one → elevated mutation rate. This is a classic way to show that hemimethylation is essential for MMR strand discrimination.',
        relatedTopics: ['Dam methylase', 'hemimethylation', 'MutH', 'strand discrimination', 'MMR mechanism'],
      },
    ],
  },

  // ─── B/B Passage 2: Enzyme Kinetics — Allosteric Regulation ─────────────────
  {
    id: 'f2-bb-p2',
    sectionId: 'bio-biochem',
    title: 'Allosteric Regulation of ATCase',
    passageText: `Aspartate transcarbamoylase (ATCase) from E. coli catalyzes the first committed step of pyrimidine biosynthesis: the condensation of carbamoyl phosphate with aspartate to yield N-carbamoyl-L-aspartate. ATCase is a paradigmatic allosteric enzyme, exhibiting sigmoidal (cooperative) kinetics with respect to aspartate concentration rather than the hyperbolic kinetics of a Michaelis-Menten enzyme.

ATCase consists of six catalytic (c) subunits and six regulatory (r) subunits. The enzyme exists in two conformational states: the T (tense) state with low substrate affinity and the R (relaxed) state with high substrate affinity. Binding of one aspartate molecule to a catalytic subunit increases the probability of conversion of remaining subunits to the R state (positive cooperativity), producing the sigmoidal velocity-vs-[S] curve. CTP, the end product of the pyrimidine biosynthetic pathway, binds to regulatory subunits and stabilizes the T state (feedback inhibition). ATP, which competes with CTP for the regulatory site, stabilizes the R state and activates the enzyme.

Figure 1 (not shown) depicts ATCase velocity vs. aspartate concentration curves under three conditions: (A) enzyme alone, (B) enzyme + 2 mM CTP, and (C) enzyme + 2 mM ATP. The half-saturation constant [S]₀.₅ increases in condition B relative to A, and decreases in condition C relative to A. Vmax is essentially unchanged in all three conditions.`,
    figures: [],
    questions: [
      {
        id: 'mcat2-bb-006',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p2',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'Enzyme kinetics and regulation',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'Which type of kinetic behavior does ATCase exhibit, and what feature of the velocity curve reflects this?',
        choices: [
          { label: 'A', text: 'Michaelis-Menten kinetics, reflected by a hyperbolic velocity curve' },
          { label: 'B', text: 'Cooperative (allosteric) kinetics, reflected by a sigmoidal velocity curve' },
          { label: 'C', text: 'Competitive inhibition kinetics, reflected by an increased Km' },
          { label: 'D', text: 'Uncompetitive inhibition kinetics, reflected by decreased Vmax and Km' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage states ATCase exhibits "sigmoidal (cooperative) kinetics with respect to aspartate concentration rather than the hyperbolic kinetics of a Michaelis-Menten enzyme." B reproduces this. A describes Michaelis-Menten, which the passage explicitly says ATCase does NOT follow. C and D describe inhibition patterns of non-allosteric enzymes.',
        wrongAnswerExplanations: {
          A: 'The passage explicitly distinguishes ATCase\'s sigmoidal kinetics from Michaelis-Menten hyperbolic kinetics.',
          C: 'Competitive inhibition applies to Michaelis-Menten enzymes; CTP inhibition of ATCase is allosteric (changes conformation), not competitive with the substrate.',
          D: 'Uncompetitive inhibition decreases both Vmax and Km. The passage states Vmax is "essentially unchanged" under CTP conditions — ruling out uncompetitive inhibition.',
        },
        teachingPoint: 'Allosteric enzymes: sigmoidal v vs. [S] curves (Hill plot slope > 1). ATCase is the textbook allosteric enzyme — end-product (CTP) inhibition by stabilizing T-state; ATP activation by stabilizing R-state.',
        relatedTopics: ['ATCase', 'cooperative kinetics', 'sigmoidal curve', 'allosteric regulation', 'Hill coefficient'],
      },
      {
        id: 'mcat2-bb-007',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p2',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'Enzyme kinetics and regulation',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'CTP inhibition of ATCase is best characterized as which type of inhibition based on the passage data?',
        choices: [
          { label: 'A', text: 'Competitive inhibition — CTP competes with aspartate for the active site' },
          { label: 'B', text: 'Heterotropic allosteric inhibition — CTP binds a regulatory site distinct from the catalytic site and decreases apparent substrate affinity without changing Vmax' },
          { label: 'C', text: 'Irreversible inhibition — CTP covalently modifies the catalytic subunit' },
          { label: 'D', text: 'Uncompetitive inhibition — CTP binds only the enzyme-substrate complex' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage states CTP "binds to regulatory subunits" (distinct from catalytic subunits) and increases [S]₀.₅ (apparent substrate affinity decreases), while Vmax is unchanged. This pattern — binding at a different site, changing affinity but not Vmax — defines heterotropic allosteric inhibition. It is "heterotropic" because the modulator (CTP) is chemically different from the substrate (aspartate). A is wrong — CTP does not compete for the active site. C is wrong — no covalent modification is described. D is wrong — uncompetitive inhibition reduces both apparent Km and Vmax.',
        wrongAnswerExplanations: {
          A: 'Competitive inhibition involves competing for the substrate binding site. CTP binds regulatory subunits, not the active site on catalytic subunits.',
          C: 'No covalent modification is described. Allosteric regulation is non-covalent and reversible.',
          D: 'Uncompetitive inhibition decreases both Vmax and apparent Km. The passage specifies Vmax is unchanged — ruling out uncompetitive inhibition.',
        },
        teachingPoint: 'Heterotropic allosteric inhibition: modulator (CTP) differs from substrate (aspartate), binds at a regulatory site, changes conformation → decreased substrate affinity ([S]₀.₅ increases), Vmax unchanged. Contrast with competitive inhibition (binds active site, Vmax unchanged, Km increases — but for non-cooperative enzymes).',
        relatedTopics: ['heterotropic inhibition', 'allosteric regulation', 'regulatory site', 'CTP feedback inhibition'],
      },
      {
        id: 'mcat2-bb-008',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p2',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'Enzyme kinetics and regulation',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'ATP activates ATCase by stabilizing the R state. Based on the passage, what effect does 2 mM ATP have on the velocity curve relative to enzyme alone?',
        choices: [
          { label: 'A', text: 'Increases Vmax while keeping [S]₀.₅ constant' },
          { label: 'B', text: 'Decreases [S]₀.₅ (shifts curve left) while Vmax remains unchanged' },
          { label: 'C', text: 'Converts the sigmoidal curve to a hyperbolic curve' },
          { label: 'D', text: 'Increases both [S]₀.₅ and Vmax' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage states condition C (+ 2 mM ATP) shows "[S]₀.₅ decreases in condition C relative to A" and "Vmax is essentially unchanged in all three conditions." Lower [S]₀.₅ means the enzyme reaches half-maximal velocity at lower substrate concentration — the curve shifts left (higher apparent affinity). B captures this. A is wrong — Vmax unchanged. C is not stated; the curve remains sigmoidal (just shifted). D is wrong — Vmax unchanged and [S]₀.₅ decreases, not increases.',
        wrongAnswerExplanations: {
          A: 'The passage explicitly states Vmax is essentially unchanged in all conditions, including ATP.',
          C: 'The passage does not state that ATP converts the sigmoidal curve to hyperbolic. The cooperative mechanism remains intact; ATP shifts the T→R equilibrium toward R but doesn\'t eliminate cooperativity.',
          D: 'Vmax is unchanged, and [S]₀.₅ decreases (not increases) with ATP. Increasing [S]₀.₅ is the CTP effect, not the ATP effect.',
        },
        teachingPoint: 'ATP as activator: stabilizes R state → enzyme achieves half-maximal activity at lower [aspartate] → [S]₀.₅ decreases (curve shifts left). Vmax unchanged. This is homotropic cooperativity shift, not intrinsic Vmax change.',
        relatedTopics: ['ATCase activation', 'R state', 'T state', '[S]₀.₅', 'allosteric activator'],
      },
      {
        id: 'mcat2-bb-009',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p2',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'Enzyme kinetics and regulation',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'In a cell producing excess CTP and insufficient ATP, what immediate consequence for pyrimidine biosynthesis would the passage\'s model predict?',
        choices: [
          { label: 'A', text: 'Increased pyrimidine synthesis because CTP is a substrate for the pathway' },
          { label: 'B', text: 'Decreased pyrimidine synthesis because CTP feedback-inhibits ATCase while insufficient ATP cannot counteract this inhibition' },
          { label: 'C', text: 'No change because ATCase activity depends only on aspartate concentration' },
          { label: 'D', text: 'Increased pyrimidine synthesis because ATP depletion removes competitive inhibition at ATCase\'s active site' },
        ],
        correctAnswer: 'B',
        explanation: 'CTP inhibits ATCase (stabilizes T state, reduces apparent substrate affinity). ATP activates ATCase (stabilizes R state, increases apparent substrate affinity). With excess CTP and insufficient ATP, the inhibitory effect of CTP is maximized and the activating effect of ATP is minimized. ATCase will be in a largely T-state (low activity) configuration → decreased pyrimidine synthesis. This is classical feedback inhibition of the first committed step. A misidentifies CTP as a substrate. C ignores allosteric modulation. D incorrectly claims ATP is a competitive inhibitor at the active site — it is an allosteric activator at the regulatory site.',
        wrongAnswerExplanations: {
          A: 'CTP is the end product that inhibits the pathway, not a substrate for ATCase.',
          C: 'The passage explicitly shows that CTP and ATP modulate ATCase activity independent of aspartate — Vmax is unchanged but [S]₀.₅ changes, affecting activity at physiological [aspartate].',
          D: 'ATP is not a competitive inhibitor at the active site. It is an allosteric activator that competes with CTP for the regulatory site. Without ATP, CTP\'s inhibitory effect is unopposed.',
        },
        teachingPoint: 'Feedback inhibition logic: CTP (end product) inhibits ATCase → when [CTP] is high, pyrimidine synthesis slows (no overproduction). ATP competition with CTP at regulatory site ensures purine/pyrimidine balance. When ATP is low AND CTP is high → maximum inhibition of pyrimidine synthesis.',
        relatedTopics: ['feedback inhibition', 'ATCase regulation', 'pyrimidine biosynthesis', 'nucleotide balance'],
      },
      {
        id: 'mcat2-bb-010',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p2',
        questionType: 'passage',
        discipline: 'Biochemistry',
        contentCategory: 'Enzyme kinetics and regulation',
        foundationalConcept: 'FC 1',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'The positive cooperativity of ATCase means that:',
        choices: [
          { label: 'A', text: 'Each successive substrate molecule binds with lower affinity than the previous' },
          { label: 'B', text: 'Binding of one aspartate molecule to one subunit increases substrate affinity at remaining subunits' },
          { label: 'C', text: 'CTP and aspartate compete for the same binding site' },
          { label: 'D', text: 'The enzyme requires both carbamoyl phosphate and aspartate before any binding can occur' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage states: "Binding of one aspartate molecule to a catalytic subunit increases the probability of conversion of remaining subunits to the R state (positive cooperativity)." B reproduces this definition. A describes negative cooperativity (decreasing affinity with successive binding). C is wrong — CTP and aspartate bind different sites (regulatory vs. catalytic). D describes an ordered mechanism, not cooperativity.',
        wrongAnswerExplanations: {
          A: 'This describes negative cooperativity (e.g., hemoglobin in CO₂-rich tissues) — not positive cooperativity. ATCase has positive cooperativity.',
          C: 'CTP binds regulatory subunits; aspartate binds catalytic subunits. They do not compete for the same site.',
          D: 'An ordered binding mechanism is a different concept from cooperativity. The passage describes cooperative binding, not obligate ordering of substrate binding.',
        },
        teachingPoint: 'Positive cooperativity: binding of first substrate molecules promotes conformational change (T→R) that increases affinity for subsequent substrate molecules. Produces sigmoidal curve. In ATCase, aspartate binding shifts subunits to R state.',
        relatedTopics: ['positive cooperativity', 'T state', 'R state', 'concerted model', 'sigmoidal kinetics'],
      },
    ],
  },

  // ─── B/B Passage 3: Cell Signaling — Receptor Tyrosine Kinases ─────────────
  {
    id: 'f2-bb-p3',
    sectionId: 'bio-biochem',
    title: 'EGF Receptor Signaling and Oncogenic Mutations',
    passageText: `The epidermal growth factor receptor (EGFR) is a receptor tyrosine kinase (RTK) that plays critical roles in cell proliferation, survival, and differentiation. EGFR is a single-pass transmembrane protein consisting of an extracellular ligand-binding domain, a transmembrane helix, and an intracellular kinase domain. In the unstimulated state, EGFR exists largely as a monomer with low intrinsic kinase activity.

Binding of EGF to the extracellular domain induces receptor dimerization. Dimerization activates the intracellular kinase domain of each receptor monomer, leading to transphosphorylation: each kinase phosphorylates specific tyrosine residues on the cytoplasmic tail of the partnering receptor. These phosphotyrosine residues serve as docking sites for SH2 domain-containing adaptor proteins (e.g., GRB2), which recruit guanine nucleotide exchange factors (GEFs such as SOS) to the plasma membrane. SOS activates RAS by catalyzing the exchange of GDP for GTP. Activated RAS-GTP binds and activates RAF, initiating the MAPK/ERK kinase cascade (RAF→MEK→ERK), ultimately leading to transcription factor phosphorylation and altered gene expression.

Activating mutations in EGFR — particularly exon 19 deletions and the exon 21 L858R point mutation — are found in approximately 15% of non-small-cell lung cancers (NSCLC) in Western populations and in up to 50% in East Asian populations. These mutations render EGFR constitutively active (ligand-independent), driving uncontrolled proliferation. First-generation EGFR inhibitors (gefitinib, erlotinib) competitively inhibit the kinase domain. Resistance frequently develops through a secondary T790M "gatekeeper" mutation, which sterically blocks first-generation inhibitors while preserving kinase activity. Third-generation inhibitors (osimertinib) are designed to covalently inactivate EGFR bearing the T790M mutation.`,
    figures: [],
    questions: [
      {
        id: 'mcat2-bb-011',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p3',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Cell signaling',
        foundationalConcept: 'FC 2',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'What event initiates activation of the EGFR signaling cascade, according to the passage?',
        choices: [
          { label: 'A', text: 'Phosphorylation of RAS by EGFR kinase' },
          { label: 'B', text: 'EGF binding to the extracellular domain, inducing receptor dimerization' },
          { label: 'C', text: 'SOS recruitment to the nucleus' },
          { label: 'D', text: 'ERK phosphorylation of EGFR' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage states: "Binding of EGF to the extracellular domain induces receptor dimerization. Dimerization activates the intracellular kinase domain..." — B describes the initiating event. A is incorrect (RAS is activated by GEF/SOS, not directly by EGFR kinase). C is wrong — SOS is recruited to the plasma membrane, not the nucleus. D describes a feedback pathway not mentioned.',
        wrongAnswerExplanations: {
          A: 'EGFR kinase phosphorylates its own cytoplasmic tail (transphosphorylation); RAS is activated downstream by SOS-catalyzed GDP→GTP exchange, not direct phosphorylation by EGFR.',
          C: 'SOS is recruited to the plasma membrane (via GRB2 binding phosphotyrosines), not to the nucleus. SOS activates membrane-bound RAS.',
          D: 'ERK is a downstream effector. Feedback phosphorylation of EGFR by ERK is not described in the passage.',
        },
        teachingPoint: 'RTK signaling cascade order: ligand binding → receptor dimerization → transphosphorylation → adaptor (GRB2) recruitment → GEF (SOS) → RAS-GTP → RAF→MEK→ERK → transcription. Know each step and direction.',
        relatedTopics: ['EGFR', 'receptor tyrosine kinase', 'EGF', 'dimerization', 'signal transduction'],
      },
      {
        id: 'mcat2-bb-012',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p3',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Cell signaling',
        foundationalConcept: 'FC 2',
        scientificSkill: 'Skill 1',
        difficulty: 'medium',
        question: 'What is the role of SOS in the EGFR signaling pathway?',
        choices: [
          { label: 'A', text: 'SOS is a kinase that phosphorylates ERK' },
          { label: 'B', text: 'SOS is a GEF that activates RAS by catalyzing exchange of GDP for GTP' },
          { label: 'C', text: 'SOS is a GTPase-activating protein that inactivates RAS' },
          { label: 'D', text: 'SOS is a phosphatase that dephosphorylates EGFR to terminate signaling' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage states: "SOS activates RAS by catalyzing the exchange of GDP for GTP." SOS is a guanine nucleotide exchange factor (GEF). B is correct. A is wrong — SOS is not a kinase and does not phosphorylate ERK. C inverts SOS\'s role (GAPs inactivate RAS; GEFs activate it). D describes a phosphatase, which is the opposite of SOS\'s function.',
        wrongAnswerExplanations: {
          A: 'ERK is phosphorylated by MEK; SOS acts much earlier in the pathway on RAS.',
          C: 'GTPase-activating proteins (GAPs) inactivate RAS by stimulating GTP hydrolysis. SOS is a GEF, which activates RAS. These are opposite functions.',
          D: 'Phosphatases dephosphorylate proteins. SOS acts on a nucleotide exchange reaction (GDP→GTP), not a phosphorylation reaction.',
        },
        teachingPoint: 'SOS = guanine nucleotide exchange factor (GEF). Activates RAS by replacing GDP with GTP. RAS-GTP = active. RAS-GDP = inactive. GAPs (GTPase-activating proteins) inactivate RAS by stimulating intrinsic GTPase activity. Oncogenic RAS mutations (G12V, G12D) eliminate GTPase activity → constitutively active.',
        relatedTopics: ['SOS', 'RAS', 'GEF', 'GTP exchange', 'MAPK cascade'],
      },
      {
        id: 'mcat2-bb-013',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p3',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Cell signaling',
        foundationalConcept: 'FC 2',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'A NSCLC patient with an EGFR L858R mutation initially responds to gefitinib but later develops resistance. Tumor biopsy reveals acquisition of the T790M mutation. Why does osimertinib overcome this resistance?',
        choices: [
          { label: 'A', text: 'Osimertinib blocks EGF binding at the extracellular domain' },
          { label: 'B', text: 'Osimertinib is designed to covalently inactivate EGFR bearing T790M, which cannot be sterically blocked like first-generation inhibitors' },
          { label: 'C', text: 'Osimertinib activates a different receptor that bypasses EGFR' },
          { label: 'D', text: 'Osimertinib activates the immune system to kill EGFR-mutated cells' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage states: "Third-generation inhibitors (osimertinib) are designed to covalently inactivate EGFR bearing the T790M mutation." The T790M mutation sterically blocks first-generation inhibitors (competitive, reversible), but osimertinib covalently modifies a cysteine near the ATP binding site, forming an irreversible bond that T790M cannot block. B directly applies the passage. A is wrong — EGFR inhibitors target the intracellular kinase domain, not the extracellular EGF-binding domain. C and D are not described in the passage.',
        wrongAnswerExplanations: {
          A: 'EGFR kinase inhibitors (gefitinib, osimertinib) target the intracellular ATP-binding kinase domain, not the extracellular ligand-binding domain.',
          C: 'Osimertinib targets EGFR specifically; it does not activate an alternative receptor.',
          D: 'Osimertinib is a targeted kinase inhibitor, not an immunotherapy agent.',
        },
        teachingPoint: 'T790M resistance mechanism: bulky methionine at position 790 sterically clashes with first-generation inhibitors (which bind reversibly). Osimertinib forms a covalent bond with Cys797, bypassing the steric obstruction. Covalent = irreversible = cannot be displaced by T790M steric effect.',
        relatedTopics: ['EGFR T790M', 'osimertinib', 'resistance mechanism', 'covalent inhibitor', 'NSCLC'],
      },
      {
        id: 'mcat2-bb-014',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p3',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Cell signaling',
        foundationalConcept: 'FC 2',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'Activating mutations in EGFR cause constitutive receptor activity. This most directly affects which downstream component?',
        choices: [
          { label: 'A', text: 'GRB2 — it is constitutively degraded' },
          { label: 'B', text: 'RAS — it remains constitutively in the GTP-bound active state due to persistent SOS recruitment' },
          { label: 'C', text: 'EGF — it is no longer synthesized because the receptor is already active' },
          { label: 'D', text: 'MEK — it is constitutively inactive because ERK feedback is lost' },
        ],
        correctAnswer: 'B',
        explanation: 'Constitutively active EGFR continuously transphosphorylates its own cytoplasmic tail → continuous GRB2/SOS recruitment → continuous RAS activation (GDP→GTP exchange). The MAPK cascade is therefore persistently activated. RAS is constitutively GTP-bound. B captures the downstream consequence. A is wrong — GRB2 is not degraded; it is constitutively recruited. C conflates the receptor\'s activity with ligand production. D inverts — MEK would be constitutively active, not inactive.',
        wrongAnswerExplanations: {
          A: 'GRB2 is constitutively recruited (not degraded) when EGFR is constitutively phosphorylated.',
          C: 'EGFR activity is ligand-independent in the mutant, but this has no feedback on EGF ligand synthesis described in the passage.',
          D: 'Constitutively active EGFR → constitutively active RAS → RAF constitutively active → MEK constitutively phosphorylated → ERK constitutively active. MEK is more active, not inactive.',
        },
        teachingPoint: 'Oncogenic EGFR → constitutive kinase activity → persistent transphosphorylation → constitutive GRB2/SOS recruitment → constitutive RAS-GTP → constitutive MAPK cascade → uncontrolled cell proliferation. Each activating mutation in this cascade can be an oncogene.',
        relatedTopics: ['oncogenic mutation', 'constitutive activation', 'RAS', 'MAPK cascade', 'cancer biology'],
      },
      {
        id: 'mcat2-bb-015',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p3',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Cell signaling',
        foundationalConcept: 'FC 2',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'Phosphotyrosine residues on the EGFR cytoplasmic tail serve which function in the signaling cascade?',
        choices: [
          { label: 'A', text: 'They directly phosphorylate RAS' },
          { label: 'B', text: 'They serve as docking sites for SH2 domain-containing adaptor proteins such as GRB2' },
          { label: 'C', text: 'They anchor EGFR to the plasma membrane after dimerization' },
          { label: 'D', text: 'They signal to the nucleus directly without intermediate steps' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage states: "These phosphotyrosine residues serve as docking sites for SH2 domain-containing adaptor proteins (e.g., GRB2)." B reproduces this. A is wrong — RAS is activated by GDP→GTP exchange via SOS, not by direct phosphorylation. C is wrong — membrane anchoring is provided by the transmembrane helix, not phosphotyrosines. D is wrong — the cascade proceeds through multiple cytoplasmic steps before reaching the nucleus.',
        wrongAnswerExplanations: {
          A: 'RAS is a GTPase activated by guanine nucleotide exchange (GDP→GTP), not by tyrosine phosphorylation.',
          C: 'The transmembrane domain anchors EGFR in the plasma membrane. Phosphotyrosines are on the cytoplasmic tail and serve as protein-protein interaction platforms.',
          D: 'Receptor phosphotyrosines initiate a multi-step cascade (GRB2→SOS→RAS→RAF→MEK→ERK→nucleus); they do not directly signal to the nucleus.',
        },
        teachingPoint: 'Phosphotyrosines on RTK cytoplasmic tails = docking platforms for SH2 domain proteins. SH2 domains bind phosphotyrosine-containing sequences with specificity. GRB2 has two SH3 domains that recruit SOS via its proline-rich regions.',
        relatedTopics: ['phosphotyrosine', 'SH2 domain', 'GRB2', 'adaptor protein', 'RTK signaling'],
      },
    ],
  },

  // ─── B/B Passage 4: Muscle Physiology — Cross-Bridge Cycle ─────────────────
  {
    id: 'f2-bb-p4',
    sectionId: 'bio-biochem',
    title: 'Skeletal Muscle Contraction and the Sliding Filament Model',
    passageText: `The sliding filament model describes how skeletal muscle generates force: thick filaments (myosin II) slide past thin filaments (actin) through repeated cross-bridge cycles, powered by ATP hydrolysis. The cross-bridge cycle consists of four principal steps: (1) ATP binding to myosin causes release of the actin filament (dissociation); (2) ATP hydrolysis (forming ADP·Pi on myosin) cocks the myosin head into a high-energy configuration; (3) the myosin head binds actin in the "weak-binding" state, followed by Pi release and transition to the "strong-binding" state; (4) the power stroke — myosin head pivots, pulling the actin filament toward the M-line — is coupled to ADP release.

Regulation of contraction in skeletal muscle depends on the troponin-tropomyosin complex on thin filaments. At resting [Ca²⁺], tropomyosin physically blocks myosin-binding sites on actin. A rise in cytoplasmic Ca²⁺ (from sarcoplasmic reticulum release via ryanodine receptors upon action potential propagation along the T-tubule) allows Ca²⁺ to bind troponin C, inducing a conformational change that moves tropomyosin away from myosin-binding sites, permitting cross-bridge formation.

Rigor mortis — the post-mortem stiffening of muscles — occurs because ATP depletion after death traps actomyosin in the strongly bound, post-power-stroke state (step 4 above): without ATP, myosin cannot release from actin. Rigor resolves after 24–72 hours as proteolytic enzymes degrade the myofilaments.`,
    figures: [],
    questions: [
      {
        id: 'mcat2-bb-016',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p4',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Muscle physiology',
        foundationalConcept: 'FC 3',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'According to the cross-bridge cycle described in the passage, what is the direct cause of myosin dissociating from actin?',
        choices: [
          { label: 'A', text: 'ADP release during the power stroke' },
          { label: 'B', text: 'ATP binding to myosin' },
          { label: 'C', text: 'Pi release from the myosin head' },
          { label: 'D', text: 'Ca²⁺ binding to troponin C' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage states step 1: "ATP binding to myosin causes release of the actin filament (dissociation)." B is correct. A (ADP release) occurs during the power stroke (step 4), which is after the power stroke, not when dissociation occurs. C (Pi release) triggers the strong-binding transition (step 3), not dissociation. D (Ca²⁺/troponin) controls whether binding sites are accessible, not the direct cause of dissociation in the cross-bridge cycle.',
        wrongAnswerExplanations: {
          A: 'ADP release is coupled to the power stroke (step 4). This is the step preceding the next ATP binding (step 1). ADP release comes before dissociation, not as its cause.',
          C: 'Pi release occurs in step 3, triggering the transition from weak to strong binding. It does not cause dissociation.',
          D: 'Ca²⁺/troponin controls access to binding sites but does not directly cause myosin dissociation from actin in the cycle.',
        },
        teachingPoint: 'Cross-bridge cycle order: ATP binding → myosin releases actin → ATP hydrolysis → myosin re-binds actin (weak) → Pi release → strong binding → power stroke (ADP release) → ready for next ATP binding. ATP binding = dissociation step.',
        relatedTopics: ['cross-bridge cycle', 'myosin', 'ATP binding', 'muscle contraction', 'sliding filament'],
      },
      {
        id: 'mcat2-bb-017',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p4',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Muscle physiology',
        foundationalConcept: 'FC 3',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'At resting Ca²⁺ concentrations, why can\'t myosin form cross-bridges with actin?',
        choices: [
          { label: 'A', text: 'Myosin is not phosphorylated and therefore lacks ATPase activity' },
          { label: 'B', text: 'Tropomyosin physically blocks the myosin-binding sites on actin' },
          { label: 'C', text: 'The T-tubule action potential has not been triggered' },
          { label: 'D', text: 'ATP concentrations are insufficient to power the cross-bridge cycle at rest' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage states: "At resting [Ca²⁺], tropomyosin physically blocks myosin-binding sites on actin." B reproduces this directly. A is incorrect — skeletal muscle myosin II does not require phosphorylation for ATPase activity (that is smooth muscle). C describes a condition, but the direct reason cross-bridges can\'t form is the physical blockade by tropomyosin. D is wrong — ATP is available at rest; the limitation is physical steric blockade.',
        wrongAnswerExplanations: {
          A: 'Myosin phosphorylation is required for smooth muscle activation (MLCK pathway), not skeletal muscle. Skeletal muscle is regulated by troponin/tropomyosin.',
          C: 'The absence of an action potential is the upstream cause, but the proximate reason for no cross-bridge formation is tropomyosin blocking the binding sites.',
          D: 'ATP is abundant in resting muscle. The issue is not ATP availability but physical steric blockade by tropomyosin.',
        },
        teachingPoint: 'Skeletal muscle regulation: troponin-tropomyosin complex. At rest (low Ca²⁺): tropomyosin blocks actin-myosin binding sites. Upon stimulation: Ca²⁺ binds troponin C → conformational change → tropomyosin moves → binding sites exposed → cross-bridge formation.',
        relatedTopics: ['tropomyosin', 'troponin', 'Ca²⁺ regulation', 'actin binding', 'thin filament regulation'],
      },
      {
        id: 'mcat2-bb-018',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p4',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Muscle physiology',
        foundationalConcept: 'FC 3',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'Rigor mortis develops after death because ATP depletion leads to which condition?',
        choices: [
          { label: 'A', text: 'Myosin heads cannot complete the power stroke without ATP' },
          { label: 'B', text: 'Actomyosin is trapped in the strongly bound, post-power-stroke state because myosin cannot release actin without ATP binding' },
          { label: 'C', text: 'Ca²⁺ cannot be pumped back into the sarcoplasmic reticulum, causing sustained Ca²⁺ elevation' },
          { label: 'D', text: 'Tropomyosin permanently covers the actin binding sites, preventing any cross-bridge formation' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage explicitly states rigor mortis occurs because "ATP depletion after death traps actomyosin in the strongly bound, post-power-stroke state: without ATP, myosin cannot release from actin." This matches B directly. A misidentifies the problem (the power stroke has occurred; the issue is the inability to release post-stroke). C (Ca²⁺ reuptake failure) contributes to initial contraction but is not the mechanism of rigor as described. D is the opposite — in rigor, myosin is locked ONTO actin, not prevented from binding.',
        wrongAnswerExplanations: {
          A: 'The power stroke has already occurred (actomyosin is in the post-power-stroke state). The problem is that without ATP, myosin cannot dissociate from actin to begin the next cycle.',
          C: 'Ca²⁺ reuptake failure would cause persistent activation, but rigor specifically involves lock of myosin ON actin due to no ATP for step 1 (release).',
          D: 'Tropomyosin blocking (as in relaxation) would cause muscle relaxation, not stiffness. Rigor is caused by myosin firmly attached to actin, not by prevented attachment.',
        },
        teachingPoint: 'Rigor mortis mechanism: post-death ATP depletion → myosin completes power stroke but cannot rebind ATP → stuck in rigor (strongly bound) state → stiff muscles. ATP binding is the dissociation step. Without ATP, every cross-bridge is locked.',
        relatedTopics: ['rigor mortis', 'ATP depletion', 'cross-bridge cycle', 'strongly bound state'],
      },
      {
        id: 'mcat2-bb-019',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p4',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Muscle physiology',
        foundationalConcept: 'FC 3',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'Which step in the cross-bridge cycle directly provides the mechanical force of muscle contraction?',
        choices: [
          { label: 'A', text: 'ATP binding — releases myosin, allowing filament sliding' },
          { label: 'B', text: 'ATP hydrolysis — the energy released drives the power stroke' },
          { label: 'C', text: 'The power stroke — myosin head pivots and pulls actin toward the M-line, coupled to ADP release' },
          { label: 'D', text: 'Pi release — the transition from weak to strong binding produces the main force' },
        ],
        correctAnswer: 'C',
        explanation: 'The passage states step 4 is "the power stroke — myosin head pivots, pulling the actin filament toward the M-line — is coupled to ADP release." The power stroke is the mechanical event that generates force. A (ATP binding) causes dissociation, not force generation. B (ATP hydrolysis) stores energy by cocking the head, but the mechanical event is the power stroke. D (Pi release) is the trigger that initiates the strong-binding state prior to the power stroke, not the force-generating event itself.',
        wrongAnswerExplanations: {
          A: 'ATP binding causes myosin to RELEASE actin — this is the "relaxation" step of the cycle, not the force-generating step.',
          B: 'ATP hydrolysis (ADP·Pi formation) cocks the myosin head into a high-energy state. Energy is stored, but force is generated later during the power stroke when ADP is released.',
          D: 'Pi release is the trigger for transitioning from weak to strong binding, which positions myosin for the power stroke. The power stroke itself (step 4) is the force-generating event.',
        },
        teachingPoint: 'The power stroke is the mechanical force-generating event: the pre-loaded (ADP·Pi bound) myosin head swings ~70° (from ~90° to ~45°), pulling actin toward the M-line. ADP release is coupled to this motion. ATP hydrolysis stores energy; the power stroke releases it as mechanical work.',
        relatedTopics: ['power stroke', 'mechanical force', 'ADP release', 'myosin head pivot', 'cross-bridge cycle'],
      },
      {
        id: 'mcat2-bb-020',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p4',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Muscle physiology',
        foundationalConcept: 'FC 3',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'A researcher blocks ryanodine receptors in a skeletal muscle preparation with a specific inhibitor. Which of the following would be the most likely outcome upon nerve stimulation?',
        choices: [
          { label: 'A', text: 'Prolonged muscle contraction because Ca²⁺ accumulates in the cytoplasm' },
          { label: 'B', text: 'Failure of muscle contraction because Ca²⁺ cannot be released from the sarcoplasmic reticulum' },
          { label: 'C', text: 'Contraction occurs normally because ryanodine receptors regulate only smooth muscle' },
          { label: 'D', text: 'Rigor mortis develops because myosin is trapped in the strongly bound state' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage states Ca²⁺ is released from the sarcoplasmic reticulum "via ryanodine receptors upon action potential propagation along the T-tubule." If ryanodine receptors are blocked, Ca²⁺ cannot be released despite the action potential. Without cytoplasmic Ca²⁺, troponin C cannot bind Ca²⁺, tropomyosin remains blocking, and cross-bridges cannot form → no contraction. B is correct. A is the opposite. C is wrong — ryanodine receptors (RyR1) are critical for skeletal muscle excitation-contraction coupling. D is wrong — rigor requires ATP depletion, not Ca²⁺ blockade.',
        wrongAnswerExplanations: {
          A: 'Blocking RyR prevents Ca²⁺ release — cytoplasmic Ca²⁺ would remain low, not accumulate. The passage describes this as the pathway for Ca²⁺ elevation.',
          C: 'Ryanodine receptor type 1 (RyR1) is the primary Ca²⁺ release channel in skeletal muscle SR. Smooth muscle uses IP₃ receptors primarily.',
          D: 'Rigor mortis requires ATP depletion trapping actomyosin in the strongly bound state. Blocking Ca²⁺ release prevents contraction from occurring; without contraction, rigor cannot develop from this mechanism.',
        },
        teachingPoint: 'Excitation-contraction coupling pathway: action potential → T-tubule → RyR1 (skeletal) or IP₃R (smooth) → Ca²⁺ released from SR → Ca²⁺ binds TnC → tropomyosin moves → cross-bridge forms. Blocking RyR1 severs this chain after the electrical event.',
        relatedTopics: ['ryanodine receptor', 'excitation-contraction coupling', 'Ca²⁺ release', 'sarcoplasmic reticulum', 'T-tubule'],
      },
    ],
  },

  // ─── B/B Passage 5: Immunology — Adaptive Immune Response ──────────────────
  {
    id: 'f2-bb-p5',
    sectionId: 'bio-biochem',
    title: 'Clonal Selection and the Adaptive Immune Response',
    passageText: `The adaptive immune system generates antigen-specific responses through a process of clonal selection. Each lymphocyte (B or T cell) expresses a unique antigen receptor — generated by somatic recombination of V(D)J gene segments — that defines its antigen specificity before any encounter with antigen. Upon encounter with a cognate antigen, a naïve lymphocyte is activated, proliferates extensively (clonal expansion), and differentiates into effector and memory cells. This process generates a large clone of antigen-specific effectors and a long-lived memory population that enables faster, stronger responses upon secondary exposure.

T cell activation requires two signals: (1) TCR engagement with peptide-MHC complex on an antigen-presenting cell (APC); and (2) co-stimulatory signal — typically CD28 on the T cell engaging B7 (CD80/86) on the APC. Signal 1 alone induces anergy (unresponsiveness), which prevents autoimmune responses to self-peptides presented without co-stimulation. Upon activation, helper T (Th) cells secrete cytokines that promote B cell class-switching, cytotoxic T cell (CTL) activation, and macrophage activation.

The primary antibody response after first antigen encounter is characterized by a lag phase of approximately 5–10 days, production of predominantly IgM antibodies, and relatively low titer. The secondary response to the same antigen occurs more rapidly (1–3 day lag), produces predominantly IgG (or IgA, IgE depending on the site) via class-switch recombination, at higher titers with higher affinity — due to affinity maturation in germinal centers during the primary response.`,
    figures: [],
    questions: [
      {
        id: 'mcat2-bb-021',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p5',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Immunology',
        foundationalConcept: 'FC 3',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'According to the passage, what mechanism generates the diversity of antigen receptors on lymphocytes?',
        choices: [
          { label: 'A', text: 'Somatic mutation of receptor genes after antigen exposure' },
          { label: 'B', text: 'Somatic recombination of V(D)J gene segments before any antigen encounter' },
          { label: 'C', text: 'Gene duplication events during lymphocyte development' },
          { label: 'D', text: 'Horizontal gene transfer from pathogens' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage states: "Each lymphocyte expresses a unique antigen receptor — generated by somatic recombination of V(D)J gene segments — that defines its antigen specificity before any encounter with antigen." B reproduces this. A (somatic mutation after antigen exposure) describes affinity maturation in B cells during germinal center reactions, which is a separate process from the initial receptor generation. C and D are not the mechanism described.',
        wrongAnswerExplanations: {
          A: 'Somatic hypermutation occurs in germinal centers AFTER antigen exposure during affinity maturation. The initial receptor diversity is generated by V(D)J recombination BEFORE antigen exposure.',
          C: 'Gene duplication is not the mechanism of antigen receptor diversity.',
          D: 'Horizontal gene transfer does not occur in lymphocyte development.',
        },
        teachingPoint: 'Antigen receptor diversity: V(D)J recombination generates random combinations of V, D, and J gene segments before antigen encounter → primary repertoire of ~10⁷–10⁹ specificities. Affinity maturation (somatic hypermutation) refines this after antigen exposure.',
        relatedTopics: ['VDJ recombination', 'clonal selection', 'antigen receptor diversity', 'adaptive immunity'],
      },
      {
        id: 'mcat2-bb-022',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p5',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Immunology',
        foundationalConcept: 'FC 3',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'Which two signals are required for T cell activation, and what happens when only Signal 1 is provided?',
        choices: [
          { label: 'A', text: 'Signal 1 = CD28/B7; Signal 2 = TCR/pMHC; only Signal 1 causes apoptosis' },
          { label: 'B', text: 'Signal 1 = TCR/pMHC; Signal 2 = CD28/B7; only Signal 1 causes anergy (unresponsiveness)' },
          { label: 'C', text: 'Signal 1 = IL-2/IL-2R; Signal 2 = TCR/pMHC; only Signal 1 causes proliferation without differentiation' },
          { label: 'D', text: 'Signal 1 = TCR/pMHC; Signal 2 = CD28/B7; only Signal 1 causes hyperactivation' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage states: "T cell activation requires two signals: (1) TCR engagement with peptide-MHC complex on an APC; and (2) co-stimulatory signal — typically CD28 on the T cell engaging B7 (CD80/86) on the APC. Signal 1 alone induces anergy (unresponsiveness)." B reproduces this accurately. A reverses Signal 1 and 2. C substitutes IL-2 for Signal 1. D gives the correct signals but wrong outcome (hyperactivation vs. anergy).',
        wrongAnswerExplanations: {
          A: 'Signal 1 is TCR/pMHC and Signal 2 is CD28/B7 — A reverses these. Also, anergy (not apoptosis) results from Signal 1 alone.',
          C: 'IL-2/IL-2R is the T cell growth factor that promotes clonal expansion after activation — it is not Signal 1 of the activation requirement.',
          D: 'Signal 1 alone induces anergy, not hyperactivation. Hyperactivation is not the described outcome.',
        },
        teachingPoint: 'Two-signal model of T cell activation: Signal 1 = antigen-specific (TCR:pMHC). Signal 2 = co-stimulatory (CD28:B7). Signal 1 alone → anergy (prevents autoreactive T cells from attacking self). Both signals → activation. Exploited clinically: blocking CD28 (CTLA-4-Ig/abatacept) prevents T cell activation in autoimmunity.',
        relatedTopics: ['T cell activation', 'TCR', 'CD28', 'B7', 'anergy', 'two-signal model'],
      },
      {
        id: 'mcat2-bb-023',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p5',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Immunology',
        foundationalConcept: 'FC 3',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'Why is the secondary antibody response characterized by a shorter lag, higher titer, and predominantly IgG rather than IgM?',
        choices: [
          { label: 'A', text: 'IgG is synthesized faster than IgM because it is smaller' },
          { label: 'B', text: 'Memory B cells from the primary response are already class-switched, expanded, and have higher affinity receptors — enabling rapid, high-affinity IgG responses' },
          { label: 'C', text: 'The innate immune system activates more strongly on secondary exposure' },
          { label: 'D', text: 'IgM is depleted after the primary response and cannot be resynthesized' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage explains the secondary response is faster and produces higher-affinity IgG "due to affinity maturation in germinal centers during the primary response." Memory cells generated during the primary response are: (1) more numerous (clonal expansion); (2) have high-affinity BCRs (affinity maturation); (3) have undergone class-switch recombination (producing IgG/A/E, not IgM). When re-exposed, these cells respond rapidly without needing a full primary activation lag. B captures all three reasons. A is incorrect — size is not the reason. C confuses innate/adaptive memory. D is incorrect — IgM can always be resynthesized.',
        wrongAnswerExplanations: {
          A: 'The faster response is due to the existence of antigen-specific memory cells, not the molecular size of antibody isotypes.',
          C: 'Immunological memory is a property of the adaptive (B cell and T cell) compartment, not the innate immune system.',
          D: 'IgM is produced throughout life by naïve B cells encountering antigen for the first time. It is not "depleted" after a primary response.',
        },
        teachingPoint: 'Secondary response features: shorter lag (memory cells, no priming needed), higher titer (more memory cells), predominantly IgG (class switching occurred in primary GC reaction), higher affinity (affinity maturation in primary GC). These are all consequences of memory B cell generation.',
        relatedTopics: ['immunological memory', 'class switching', 'affinity maturation', 'IgM vs IgG', 'germinal center'],
      },
      {
        id: 'mcat2-bb-024',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p5',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Immunology',
        foundationalConcept: 'FC 3',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'A vaccine that contains a protein antigen but no adjuvant (co-stimulatory activator) is injected into a mouse. Based on the passage\'s two-signal model, what would most likely result?',
        choices: [
          { label: 'A', text: 'A robust primary antibody response followed by long-lasting immunity' },
          { label: 'B', text: 'Anergy in antigen-specific T cells, impairing the ability to generate an effective adaptive immune response' },
          { label: 'C', text: 'Direct B cell activation without T cell involvement' },
          { label: 'D', text: 'A stronger response than normal because antigen is presented without inflammatory distractors' },
        ],
        correctAnswer: 'B',
        explanation: 'Adjuvants in vaccines function by activating APCs to upregulate B7 (CD80/86), providing the co-stimulatory Signal 2. Without adjuvant, APCs may present antigen (providing Signal 1 via pMHC:TCR) without sufficient B7 expression (insufficient Signal 2). Per the passage: "Signal 1 alone induces anergy (unresponsiveness)." Antigen-specific T cells that receive only Signal 1 become anergic — they cannot help B cells or activate CTLs. B follows directly. A is wrong — no adjuvant impairs, not enhances, the response. C is wrong — T helper cells are required for most antibody responses (T-dependent antigens). D is wrong — the absence of inflammatory signal (adjuvant) impairs, not enhances, the response.',
        wrongAnswerExplanations: {
          A: 'Without co-stimulation (adjuvant), T cell anergy would impair the adaptive response, not produce robust immunity.',
          C: 'B cells can respond to T-independent antigens (polysaccharides, LPS) without T help, but protein antigens require T helper cells. Without functional T cells (anergized by Signal 1 alone), the B cell response to protein antigens would be impaired.',
          D: 'Adjuvants are necessary, not distracting, for vaccine immunogenicity. They provide the "danger signals" that activate APCs to express co-stimulatory molecules.',
        },
        teachingPoint: 'Adjuvants activate innate immunity → APC upregulates B7 → T cells receive Signal 2 → activation. Without adjuvant: T cells receive only Signal 1 (antigen/pMHC) → anergy. This explains why pure protein antigens injected alone are poorly immunogenic.',
        relatedTopics: ['adjuvants', 'vaccine immunogenicity', 'anergy', 'two-signal model', 'co-stimulation'],
      },
      {
        id: 'mcat2-bb-025',
        sectionId: 'bio-biochem',
        passageId: 'f2-bb-p5',
        questionType: 'passage',
        discipline: 'Biology',
        contentCategory: 'Immunology',
        foundationalConcept: 'FC 3',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'What is the function of helper T (Th) cells in the adaptive immune response, according to the passage?',
        choices: [
          { label: 'A', text: 'Directly killing virus-infected cells via perforin and granzyme' },
          { label: 'B', text: 'Secreting cytokines that promote B cell class-switching, CTL activation, and macrophage activation' },
          { label: 'C', text: 'Presenting antigens to naïve B cells on MHC class II' },
          { label: 'D', text: 'Generating antigen-specific antibodies for immediate release' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage states: "Upon activation, helper T (Th) cells secrete cytokines that promote B cell class-switching, cytotoxic T cell (CTL) activation, and macrophage activation." B reproduces this. A describes cytotoxic T cells (CTLs), not helper T cells. C describes APCs (dendritic cells, macrophages, B cells), not Th cells. D describes B cells/plasma cells.',
        wrongAnswerExplanations: {
          A: 'Killing virus-infected cells via perforin and granzyme B is the function of CD8+ cytotoxic T lymphocytes (CTLs), not CD4+ helper T cells.',
          C: 'APCs (dendritic cells, macrophages, B cells) present antigen on MHC class II to CD4+ T cells. Helper T cells receive this presentation; they do not provide it.',
          D: 'Antibody production is the function of B cells/plasma cells after activation. Helper T cells provide cytokine signals to B cells but do not produce antibodies themselves.',
        },
        teachingPoint: 'Helper T (CD4+) cell functions: cytokine secretion (IL-2, IL-4, IL-5, IFN-γ, etc.) that orchestrates B cells (class switching, activation), CTLs (activation), and macrophages (activation). Th1 cells mainly activate macrophages and CTLs; Th2 cells mainly help B cells. HIV destroys CD4+ T cells, crippling all these downstream functions.',
        relatedTopics: ['helper T cells', 'cytokines', 'class switching', 'CTL activation', 'macrophage activation'],
      },
    ],
  },
]
