import type { MCATQuestion } from '../types'

// Form 2 B/B — Discrete Questions
// 9 questions (IDs mcat2-bb-051 through mcat2-bb-059)

export const bbDiscretes: MCATQuestion[] = [
  {
    id: 'mcat2-bb-051',
    sectionId: 'bio-biochem',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Biochemistry',
    contentCategory: 'Amino acids and peptides',
    foundationalConcept: 'FC 1',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    question: 'Which amino acid is unique in having its side chain cyclized to form a ring with its own backbone amino group, restricting the φ (phi) dihedral angle and disrupting α-helices and β-sheets?',
    choices: [
      { label: 'A', text: 'Glycine' },
      { label: 'B', text: 'Cysteine' },
      { label: 'C', text: 'Proline' },
      { label: 'D', text: 'Phenylalanine' },
    ],
    correctAnswer: 'C',
    explanation: 'Proline is the only standard amino acid that is a secondary amine — its side chain forms a ring with its own backbone nitrogen, severely restricting the φ torsion angle. This ring conformation introduces a rigid kink in the polypeptide chain, which disrupts regular α-helices and β-sheets (proline is called a "helix breaker"). Glycine (A) is the opposite: lacking a side chain, it has the greatest conformational freedom. Cysteine (B) forms disulfide bonds. Phenylalanine (D) has a bulky aromatic side chain but does not cyclize with its backbone.',
    wrongAnswerExplanations: {
      A: 'Glycine lacks a side chain entirely, giving the backbone maximum conformational freedom — the opposite of proline\'s restriction.',
      B: 'Cysteine\'s unique property is the thiol (-SH) side chain capable of forming disulfide bonds, not backbone cyclization.',
      D: 'Phenylalanine is a large hydrophobic aromatic residue; it does not cyclize with its backbone nitrogen.',
    },
    teachingPoint: 'Proline = cyclic secondary amine; unique backbone restriction; "helix breaker." Found at turns and loop regions. ω bond to proline can also be cis (trans elsewhere), important for protein folding.',
    relatedTopics: ['proline', 'helix breaker', 'dihedral angles', 'secondary structure disruption'],
  },
  {
    id: 'mcat2-bb-052',
    sectionId: 'bio-biochem',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Biology',
    contentCategory: 'Eukaryotic cell',
    foundationalConcept: 'FC 2',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    question: 'A protein synthesized in the cytoplasm that is destined for the endoplasmic reticulum lumen will enter the secretory pathway through which initial mechanism?',
    choices: [
      { label: 'A', text: 'Import through nuclear pores' },
      { label: 'B', text: 'Co-translational translocation guided by a signal peptide recognized by the Signal Recognition Particle (SRP)' },
      { label: 'C', text: 'Post-translational transport through autophagosomes' },
      { label: 'D', text: 'Diffusion across the ER membrane through lipid flipping' },
    ],
    correctAnswer: 'B',
    explanation: 'Proteins destined for the ER lumen (and subsequently the secretory pathway) bear an N-terminal signal peptide. The Signal Recognition Particle (SRP) recognizes this signal peptide as the ribosome emerges, pauses translation, and docks the ribosome-mRNA complex to the SRP receptor on the ER membrane. Translation resumes co-translationally, threading the polypeptide directly into the ER lumen through the Sec61 translocon. A (nuclear pores) is for nuclear-targeted proteins. C (autophagy) is for cytoplasmic material degradation. D (lipid flipping) moves lipids, not proteins.',
    wrongAnswerExplanations: {
      A: 'Nuclear proteins contain nuclear localization signals (NLS) and are imported post-translationally through nuclear pore complexes.',
      C: 'Autophagosomes engulf cytoplasmic material (including organelles and proteins) for lysosomal degradation — this is not the secretory pathway entry mechanism.',
      D: 'Lipid flipping (by flippases) maintains lipid bilayer asymmetry. Proteins are translocated through protein channels (Sec61 translocon), not by lipid flip mechanisms.',
    },
    teachingPoint: 'Co-translational ER translocation: signal peptide → SRP recognition → ribosome docking at ER → Sec61 translocon → polypeptide enters ER lumen. Signal peptide is cleaved by signal peptidase. This is entry into the secretory pathway (ER → Golgi → secretory vesicle/plasma membrane/lysosomes).',
    relatedTopics: ['SRP', 'signal peptide', 'Sec61 translocon', 'secretory pathway', 'ER translocation'],
  },
  {
    id: 'mcat2-bb-053',
    sectionId: 'bio-biochem',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Biochemistry',
    contentCategory: 'Carbohydrates',
    foundationalConcept: 'FC 1',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    question: 'Cellulose and starch are both polymers of glucose, yet cellulose is indigestible to humans whereas starch is easily digested. What accounts for this difference?',
    choices: [
      { label: 'A', text: 'Cellulose contains fructose monomers; starch contains glucose monomers' },
      { label: 'B', text: 'Cellulose uses β-1,4-glycosidic bonds; starch uses α-1,4-glycosidic bonds — human amylases only cleave α-1,4 bonds' },
      { label: 'C', text: 'Cellulose is a branched polymer; starch is unbranched' },
      { label: 'D', text: 'Cellulose contains more hydrogen bonds than starch, making it water-soluble' },
    ],
    correctAnswer: 'B',
    explanation: 'Both cellulose and starch are composed exclusively of glucose, but they differ in glycosidic bond stereochemistry. Starch (amylose/amylopectin) uses α-1,4-glycosidic bonds, which are cleaved by human salivary and pancreatic amylase. Cellulose uses β-1,4-glycosidic bonds, adopting an extended flat ribbon conformation. Human cells lack β-1,4-glucosidase (cellulase); thus cellulose passes through the gut undigested. A is wrong — both use glucose. C is wrong — amylopectin (starch) is branched; cellulose is unbranched. D inverts — cellulose is insoluble, not water-soluble.',
    wrongAnswerExplanations: {
      A: 'Both cellulose and starch are homopolymers of glucose. Sucrose (not starch) contains fructose.',
      C: 'Amylopectin (a starch component) is branched via α-1,6 bonds; cellulose is actually the unbranched polymer. The key difference is the α vs. β linkage.',
      D: 'Cellulose is essentially insoluble in water due to extensive intermolecular hydrogen bonding between parallel cellulose chains — not water-soluble. The β-1,4 conformation allows tighter chain packing.',
    },
    teachingPoint: 'α vs. β glycosidic bonds: α = digestible (amylase substrate), β = indigestible to humans (no cellulase). Starch = α-1,4 (+ α-1,6 branches in amylopectin). Cellulose = β-1,4. Glycogen = α-1,4 + more frequent α-1,6 branches. This structural difference = functional difference.',
    relatedTopics: ['cellulose', 'starch', 'glycosidic bond', 'α vs β', 'amylase', 'digestibility'],
  },
  {
    id: 'mcat2-bb-054',
    sectionId: 'bio-biochem',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Biology',
    contentCategory: 'Genetics',
    foundationalConcept: 'FC 1',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    question: 'A man with an X-linked recessive disease mates with a carrier woman. What is the probability that their daughter will be affected?',
    choices: [
      { label: 'A', text: '0%' },
      { label: 'B', text: '25%' },
      { label: 'C', text: '50%' },
      { label: 'D', text: '100%' },
    ],
    correctAnswer: 'C',
    explanation: 'The affected father has genotype X^a Y (where X^a = disease allele). The carrier mother is X^A X^a. Daughter genotypes receive X from father (always X^a for daughters) and X from mother (X^A or X^a, 50/50): (1) X^a X^A = carrier (unaffected); (2) X^a X^a = affected. Each daughter has a 50% chance of being X^a X^a (affected). C is correct. A would apply if the father were unaffected. B would be the fraction of all children affected. D would apply only if the mother were homozygous affected.',
    wrongAnswerExplanations: {
      A: '0% would require either the father to be unaffected (not carrying X^a) or for daughters to never inherit the paternal X — but daughters always get the paternal X.',
      B: '25% is the fraction of ALL children (both sexes) that are affected: 25% affected daughters + 25% sons are unaffected → sons are 0% or 50% depending on calculation. Overall 25% affected among all children, but among daughters specifically, it is 50%.',
      D: '100% would require the mother to be homozygous affected (X^a X^a), not a carrier. A carrier provides X^A or X^a with equal probability.',
    },
    teachingPoint: 'X-linked recessive: affected father (X^a Y) × carrier mother (X^A X^a). Daughters get father\'s X^a and either mother\'s X^A or X^a → 50% daughters affected. Sons get mother\'s X^A or X^a → 50% sons affected. Affected father does NOT pass disease to sons (sons get Y from father).',
    relatedTopics: ['X-linked inheritance', 'carrier mother', 'affected father', 'sex-linked recessive'],
  },
  {
    id: 'mcat2-bb-055',
    sectionId: 'bio-biochem',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Biochemistry',
    contentCategory: 'Lipid metabolism',
    foundationalConcept: 'FC 1',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    question: 'During fasting, adipocytes release fatty acids into the circulation. These fatty acids enter the mitochondria of liver hepatocytes for β-oxidation via which transport mechanism?',
    choices: [
      { label: 'A', text: 'Free diffusion across both mitochondrial membranes' },
      { label: 'B', text: 'Conjugation to carnitine for transport across the inner mitochondrial membrane by the carnitine shuttle' },
      { label: 'C', text: 'Activation to fatty acyl-CoA in the matrix, then transfer across the outer membrane' },
      { label: 'D', text: 'Transport via GLUT transporters across the inner mitochondrial membrane' },
    ],
    correctAnswer: 'B',
    explanation: 'Fatty acids are activated to fatty acyl-CoA in the cytosol by acyl-CoA synthetase. The bulky CoA group prevents direct crossing of the inner mitochondrial membrane. The carnitine shuttle transfers the acyl group: acyl-CoA + carnitine → acylcarnitine (via carnitine acyltransferase I/CPT1 on outer face of inner membrane) → transported by carnitine-acylcarnitine translocase → regenerated as acyl-CoA in the matrix (via CPT2). B is correct. A is wrong — CoA-conjugated fatty acids cannot freely diffuse across the inner membrane. C reverses the location of activation. D is wrong — GLUT transporters move glucose, not fatty acids.',
    wrongAnswerExplanations: {
      A: 'The inner mitochondrial membrane is highly impermeable to charged/large molecules. Fatty acyl-CoA (negatively charged CoA) cannot freely diffuse.',
      C: 'Fatty acid activation to acyl-CoA occurs in the CYTOSOL (outer mitochondrial membrane), not in the matrix. The carnitine shuttle then transfers the acyl group into the matrix where it is re-conjugated to matrix CoA.',
      D: 'GLUT (glucose transporter) family members are hexose transporters on plasma membranes and endoplasmic reticulum, not on the inner mitochondrial membrane.',
    },
    teachingPoint: 'Carnitine shuttle = key regulated step of fatty acid entry into mitochondria. CPT1 (carnitine palmitoyltransferase 1) catalyzes the cytosolic step (acyl-CoA → acylcarnitine). CPT1 is inhibited by malonyl-CoA (which is high when fed/high carb) — this prevents futile cycling of β-oxidation and fatty acid synthesis.',
    relatedTopics: ['carnitine shuttle', 'β-oxidation', 'CPT1', 'fatty acid transport', 'inner mitochondrial membrane'],
  },
  {
    id: 'mcat2-bb-056',
    sectionId: 'bio-biochem',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Biology',
    contentCategory: 'Nervous system',
    foundationalConcept: 'FC 3',
    scientificSkill: 'Skill 1',
    difficulty: 'medium',
    question: 'An action potential travels along an unmyelinated axon more slowly than along a myelinated axon of similar diameter. The primary reason for faster conduction velocity in myelinated axons is:',
    choices: [
      { label: 'A', text: 'Myelinated axons have more voltage-gated Na⁺ channels throughout their length' },
      { label: 'B', text: 'Myelin increases membrane resistance and decreases capacitance, allowing current to spread passively along the axon and regenerating only at nodes of Ranvier (saltatory conduction)' },
      { label: 'C', text: 'Myelin contains ATP synthase that provides additional energy for ion pumping' },
      { label: 'D', text: 'Myelinated axons have a larger diameter, which decreases resistance per unit length' },
    ],
    correctAnswer: 'B',
    explanation: 'Myelin is a lipid-rich insulating sheath that dramatically increases membrane resistance (preventing charge leakage) and decreases membrane capacitance (less charge needed to change voltage). These electrical properties allow depolarization to spread passively and rapidly along the internode. Voltage-gated Na⁺ channels are concentrated at nodes of Ranvier (gaps in myelin); the action potential regenerates only at nodes — "jumping" from node to node (saltatory conduction). This is far faster and more energy-efficient than continuous conduction. A is wrong — myelinated segments have few Na⁺ channels; channels are at nodes. C is wrong — myelin has no ATP synthase. D is a contributing factor to conduction velocity generally, but the specific reason myelination increases speed beyond diameter effects is the saltatory mechanism.',
    wrongAnswerExplanations: {
      A: 'The internode (myelinated) segments have very few voltage-gated Na⁺ channels; they are densely clustered at nodes of Ranvier. Myelin insulates rather than adding Na⁺ channels.',
      C: 'Myelin is formed by Schwann cells (PNS) or oligodendrocytes (CNS); it is a passive insulating sheath without metabolic machinery like ATP synthase.',
      D: 'While larger diameter axons do conduct faster (more internal conductive volume, less longitudinal resistance), the question asks specifically why myelination increases speed. The electrical properties and saltatory conduction are the primary reason.',
    },
    teachingPoint: 'Saltatory conduction: myelin ↑ membrane resistance, ↓ capacitance → depolarization spreads passively fast along internode → regenerates at nodes of Ranvier. Much faster (up to 70 m/s vs. 0.5 m/s for unmyelinated) and energy-efficient (ion pumping only at nodes). Multiple sclerosis destroys myelin → slowed or blocked conduction.',
    relatedTopics: ['saltatory conduction', 'myelin', 'nodes of Ranvier', 'conduction velocity', 'multiple sclerosis'],
  },
  {
    id: 'mcat2-bb-057',
    sectionId: 'bio-biochem',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Biology',
    contentCategory: 'Reproductive biology',
    foundationalConcept: 'FC 3',
    scientificSkill: 'Skill 1',
    difficulty: 'medium',
    question: 'During spermatogenesis, spermatogonia undergo mitosis to produce primary spermatocytes, which then complete meiosis. How many functional sperm are ultimately produced from each primary spermatocyte?',
    choices: [
      { label: 'A', text: '1' },
      { label: 'B', text: '2' },
      { label: 'C', text: '4' },
      { label: 'D', text: '8' },
    ],
    correctAnswer: 'C',
    explanation: 'One primary spermatocyte undergoes meiosis I → two secondary spermatocytes → each undergoes meiosis II → two spermatids each → total four spermatids per primary spermatocyte. All four spermatids mature into functional sperm (spermiogenesis). This is in contrast to oogenesis, where unequal cytokinesis produces one egg and polar bodies. C (4) is correct.',
    wrongAnswerExplanations: {
      A: 'One sperm per primary spermatocyte would apply if only one cell survived meiosis — this describes oogenesis (one egg) due to unequal cytokinesis into polar bodies, not spermatogenesis.',
      B: 'Two would result from meiosis I only (two secondary spermatocytes), before meiosis II divides each again.',
      D: 'Eight would require an extra round of mitosis after meiosis, which does not occur during the primary spermatocyte → spermatid pathway.',
    },
    teachingPoint: 'Spermatogenesis: 1 primary spermatocyte → (meiosis I) 2 secondary spermatocytes → (meiosis II) 4 spermatids → 4 sperm. All 4 are functional. Oogenesis: unequal cytokinesis → 1 egg + 3 polar bodies (1 functional cell). Key contrast for MCAT.',
    relatedTopics: ['spermatogenesis', 'meiosis', 'spermatids', 'oogenesis comparison'],
  },
  {
    id: 'mcat2-bb-058',
    sectionId: 'bio-biochem',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Biochemistry',
    contentCategory: 'Nucleotide metabolism',
    foundationalConcept: 'FC 1',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    question: 'Allopurinol is used to treat gout by inhibiting xanthine oxidase. What is the immediate consequence of this inhibition on purine catabolism?',
    choices: [
      { label: 'A', text: 'Accumulation of uric acid in the blood' },
      { label: 'B', text: 'Accumulation of hypoxanthine and xanthine (xanthine oxidase substrates) instead of uric acid' },
      { label: 'C', text: 'Increased de novo purine synthesis to compensate' },
      { label: 'D', text: 'Decreased AMP and GMP production' },
    ],
    correctAnswer: 'B',
    explanation: 'Xanthine oxidase catalyzes two steps in purine catabolism: hypoxanthine → xanthine → uric acid. Allopurinol (a structural analog of hypoxanthine) inhibits xanthine oxidase. This blocks conversion of hypoxanthine and xanthine to uric acid → these less soluble (actually more soluble than urate at high concentrations) precursors accumulate, and uric acid production falls. Lower uric acid reduces gout symptoms (urate crystal deposition). B is correct. A is the opposite. C is not the direct consequence. D confuses purine synthesis with catabolism.',
    wrongAnswerExplanations: {
      A: 'Inhibiting xanthine oxidase DECREASES uric acid production — that\'s the therapeutic goal. Gout is caused by high uric acid.',
      C: 'Allopurinol does not directly increase de novo purine synthesis. The salvage pathway may be affected (allopurinol is itself metabolized to oxypurinol), but increased de novo synthesis is not the primary immediate consequence.',
      D: 'AMP and GMP are synthesized from IMP (de novo and salvage pathways), not by xanthine oxidase. Xanthine oxidase acts on hypoxanthine and xanthine, which are degradation products, not precursors to AMP/GMP.',
    },
    teachingPoint: 'Purine catabolism pathway: AMP/GMP → IMP → hypoxanthine → xanthine → uric acid (via xanthine oxidase). Allopurinol blocks last two steps → hypoxanthine and xanthine accumulate, uric acid drops. These precursors are more soluble than urate → less crystallization → less gout.',
    relatedTopics: ['allopurinol', 'xanthine oxidase', 'gout', 'purine catabolism', 'uric acid'],
  },
  {
    id: 'mcat2-bb-059',
    sectionId: 'bio-biochem',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Biology',
    contentCategory: 'Endocrine system',
    foundationalConcept: 'FC 3',
    scientificSkill: 'Skill 1',
    difficulty: 'medium',
    question: 'Insulin and glucagon are both secreted by the pancreas but have opposing effects on blood glucose. Which statement correctly contrasts their cellular mechanisms?',
    choices: [
      { label: 'A', text: 'Insulin activates adenylyl cyclase via Gs protein; glucagon inhibits adenylyl cyclase via Gi protein' },
      { label: 'B', text: 'Insulin signals via a receptor tyrosine kinase to promote GLUT4 translocation and glycogen synthesis; glucagon signals via cAMP/PKA to promote glycogenolysis and gluconeogenesis' },
      { label: 'C', text: 'Both insulin and glucagon use cAMP as a second messenger but activate different downstream targets' },
      { label: 'D', text: 'Insulin uses nuclear receptors; glucagon uses G-protein-coupled receptors' },
    ],
    correctAnswer: 'B',
    explanation: 'Insulin binds its receptor tyrosine kinase (IRK), initiating PI3K→Akt signaling → GLUT4 vesicle translocation to plasma membrane (glucose uptake) and activation of glycogen synthase (glycogen synthesis). Glucagon binds a Gs-coupled GPCR → adenylyl cyclase activation → ↑cAMP → PKA activation → glycogen phosphorylase activation (glycogenolysis) and gluconeogenic enzyme induction. B correctly contrasts both mechanisms and effects. A inverts the roles. C is wrong — insulin does not use cAMP as a primary second messenger. D is wrong — insulin uses a tyrosine kinase receptor, not nuclear receptors (those are for steroid/thyroid hormones).',
    wrongAnswerExplanations: {
      A: 'Glucagon uses Gs (activates adenylyl cyclase, raises cAMP). Insulin uses a receptor tyrosine kinase (not a GPCR). A inverts the roles.',
      C: 'Insulin does NOT use cAMP as its primary second messenger. Insulin signals through receptor tyrosine kinase → PI3K → PIP3 → PDK1 → Akt. Glucagon uses cAMP via Gs-coupled GPCR.',
      D: 'Nuclear receptors are for lipid-soluble hormones (steroids, thyroid hormone). Insulin is a peptide hormone that cannot cross the membrane — it uses a cell-surface receptor tyrosine kinase.',
    },
    teachingPoint: 'Insulin: RTK → PI3K→Akt → GLUT4 translocation, glycogen synthase activation, protein synthesis. Glucagon: GPCR (Gs) → cAMP → PKA → glycogen phosphorylase (glycogenolysis), PEPCK induction (gluconeogenesis). Opposing effects; different receptor types.',
    relatedTopics: ['insulin signaling', 'glucagon signaling', 'RTK', 'cAMP', 'GLUT4', 'glycogenolysis'],
  },
]
