import type { MCATQuestion } from '../types'

// Form 2 P/S — 8 Standalone Discrete Questions
// IDs: mcat2-ps-052 through mcat2-ps-059
// Topics: emotion, identity, socialization, social stratification, implicit bias,
//         social mobility, motivation, group dynamics

export const psDiscretes: MCATQuestion[] = [
  {
    id: 'mcat2-ps-052',
    sectionId: 'psych-soc',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Psychology',
    contentCategory: 'Emotion',
    foundationalConcept: 'FC 6',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    question: 'The two-factor theory of emotion (Schachter-Singer) proposes that emotional experience requires which two components?',
    choices: [
      { label: 'A', text: 'A specific brain structure activation and a conscious thought' },
      { label: 'B', text: 'Physiological arousal and a cognitive label for that arousal based on contextual cues' },
      { label: 'C', text: 'Behavioral expression and social validation of the emotion' },
      { label: 'D', text: 'Subcortical fear processing (amygdala) and cortical appraisal (prefrontal cortex)' },
    ],
    correctAnswer: 'B',
    explanation: 'The Schachter-Singer (1962) two-factor theory states emotion = physiological arousal + cognitive labeling. Arousal is general and nonspecific; the emotional label comes from interpreting the context (situational cues) in which the arousal is experienced. Classic demonstration: adrenaline-injected participants who were told about the drug\'s effects (and could attribute arousal correctly) reported less emotion than participants who were not informed — the latter labeled their unexplained arousal using social context (a stooge acting euphoric or angry). B is correct. A (brain structure + thought) describes aspects of other theories (LeDoux). C (behavior + validation) is not Schachter-Singer. D (amygdala + prefrontal) describes the dual-pathway model of fear.',
    wrongAnswerExplanations: {
      A: 'Specific brain structure activation + conscious thought is not the formulation of Schachter-Singer\'s two-factor theory. This describes aspects of neuroscientific models of emotion.',
      C: 'Behavioral expression and social validation do not constitute the two factors in Schachter-Singer\'s model.',
      D: 'The subcortical/cortical dual-pathway model describes LeDoux\'s account of fear processing, not the two-factor theory.',
    },
    teachingPoint: 'Two-factor theory: arousal (nonspecific) + cognitive label (context-dependent) = emotion. Classic experiment: epinephrine + eupho/angry stooge = labeled emotion. Implication: same arousal, different context → different emotion. Explains misattribution of arousal (bridge study: men attributed arousal from bridge crossing to attraction).',
    relatedTopics: ['Schachter-Singer', 'two-factor theory', 'physiological arousal', 'cognitive labeling', 'emotion theories'],
  },
  {
    id: 'mcat2-ps-053',
    sectionId: 'psych-soc',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Sociology',
    contentCategory: 'Social identity and group membership',
    foundationalConcept: 'FC 8',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    question: 'Tajfel and Turner\'s social identity theory predicts that individuals will tend to favor members of their in-group over out-group members even when group membership is:',
    choices: [
      { label: 'A', text: 'Based on meaningful differences in ability or status' },
      { label: 'B', text: 'Assigned randomly on trivial criteria (the minimal group paradigm)' },
      { label: 'C', text: 'Chosen voluntarily based on shared values' },
      { label: 'D', text: 'Defined by long-term shared experience' },
    ],
    correctAnswer: 'B',
    explanation: 'Social identity theory holds that individuals derive self-esteem and identity from group membership and therefore are motivated to view their in-group favorably. The minimal group paradigm (Tajfel) demonstrated this by assigning participants to arbitrary groups (e.g., preference for Klee vs. Kandinsky paintings) — even with these meaningless distinctions, participants showed in-group favoritism in resource allocation. This shows favoritism does not require meaningful, ability-based, or historically shared group differences. B is correct. A, C, and D describe conditions where favoritism might be expected for other reasons (justified differences in ability, shared values, in-group loyalty). The crucial finding is favoritism occurs even without these.',
    wrongAnswerExplanations: {
      A: 'If favoritism requires meaningful ability differences, it could be explained by actual merit rather than in-group bias. Tajfel\'s key contribution was showing favoritism occurs even without ability differences.',
      C: 'Voluntary membership based on shared values is a meaningful and consequential basis for group identity. The minimal group paradigm shows favoritism occurs even for trivial, randomly assigned categories.',
      D: 'Long-term shared experience creates strong in-group bonds with clear explanations for favoritism. The minimal group paradigm removes such history to demonstrate the mere categorization effect.',
    },
    teachingPoint: 'Minimal group paradigm: in-group favoritism emerges from mere categorization alone, even when groups are: (1) randomly assigned, (2) trivially defined, (3) anonymous, (4) without interaction history, (5) with nothing materially at stake for the self. This demonstrates that categorization itself triggers social identity processes.',
    relatedTopics: ['social identity theory', 'minimal group paradigm', 'in-group favoritism', 'Tajfel', 'intergroup bias'],
  },
  {
    id: 'mcat2-ps-054',
    sectionId: 'psych-soc',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Sociology',
    contentCategory: 'Social stratification',
    foundationalConcept: 'FC 9',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    question: 'Sociologists distinguish ascribed status from achieved status. A physician\'s professional rank in a hospital is an example of:',
    choices: [
      { label: 'A', text: 'Ascribed status — it is assigned based on birth characteristics' },
      { label: 'B', text: 'Achieved status — it is earned through effort, education, and credentialing' },
      { label: 'C', text: 'Master status — it overrides all other identities' },
      { label: 'D', text: 'Social role — it describes expected behaviors, not status' },
    ],
    correctAnswer: 'B',
    explanation: 'Achieved status is earned through individual effort, merit, or choice (education, certification, job performance). A physician\'s hospital rank (attending, fellow, resident) is earned through medical training, board certification, and career progression — not assigned at birth. B is correct. A (ascribed status) includes race, ethnicity, sex assigned at birth, family wealth — fixed or assigned, not earned. C (master status) is a separate concept — a status so dominant it overrides all others (e.g., being Black in a racist society can become a "master status" regardless of other achievements). D mislabels — professional rank is a social position (status), and roles are the behavioral expectations attached to that position.',
    wrongAnswerExplanations: {
      A: 'Ascribed status is assigned, typically at birth, based on characteristics the individual did not choose or earn — race, sex, family background. A hospital rank is earned, not ascribed.',
      C: 'Master status is a type of status (can be achieved or ascribed) that dominates others in social interactions. The question asks achieved vs. ascribed, not about dominance relative to other statuses.',
      D: 'Social role describes the expected behaviors associated with a status. Status (rank) and role (behavior expectations) are related concepts — this answer conflates them. Professional rank is a status, not a role.',
    },
    teachingPoint: 'Ascribed vs. achieved status: ascribed = assigned, fixed (race, sex, birth order); achieved = earned (degree, occupation, marriage). Master status = status that eclipses all others. Role = behavioral expectations attached to a status. Classic example: being a "doctor" (achieved status) carries the role of healer/authority.',
    relatedTopics: ['ascribed status', 'achieved status', 'master status', 'social stratification', 'social role'],
  },
  {
    id: 'mcat2-ps-055',
    sectionId: 'psych-soc',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Psychology',
    contentCategory: 'Implicit and explicit attitudes',
    foundationalConcept: 'FC 8',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    question: 'The Implicit Association Test (IAT) measures:',
    choices: [
      { label: 'A', text: 'Explicit, consciously held attitudes that participants are willing to report on surveys' },
      { label: 'B', text: 'The degree of social desirability bias in attitude surveys' },
      { label: 'C', text: 'Working memory capacity and processing speed' },
      { label: 'D', text: 'The strength of automatic associations between concepts in memory, reflecting attitudes that may be unconscious or not endorsed at the explicit level' },
    ],
    correctAnswer: 'D',
    explanation: 'The IAT (Greenwald et al., 1998) measures reaction time to sorting pairings of concepts and attributes (e.g., "Black faces + good" vs. "Black faces + bad") to reveal the strength of automatic (implicit) mental associations. Faster categorization of a pairing indicates stronger association in memory. Implicit associations often differ from explicitly stated attitudes — people may consciously endorse racial equality but have implicit racial associations that are revealed by the IAT. D is correct. A describes explicit attitude measures (surveys, Likert scales). C (working memory) is irrelevant to the IAT construct. B (social desirability) is partially the point — IAT claims to access attitudes beneath socially desirable responding, but the question asks what it measures, not why it was developed.',
    wrongAnswerExplanations: {
      A: 'Explicit attitudes are measured by direct survey methods. The IAT\'s purpose is specifically to access attitudes that may not be consciously accessible or that participants might not report accurately.',
      C: 'The IAT uses reaction times, but the construct it measures is association strength (implicit attitudes), not working memory or processing speed per se.',
          B: 'Social desirability bias is a reason for using implicit measures (to bypass motivated responding), but it is not what the IAT measures. The IAT measures automatic association strength.',
          
    },
    teachingPoint: 'IAT = implicit measure: measures automatic cognitive associations via reaction time. Implicit ≠ explicit: someone can have a pro-diversity explicit attitude (survey response) and an anti-diversity implicit association (IAT result). Clinical relevance: implicit provider bias has been associated with disparities in pain management, diagnostic accuracy, and patient-provider communication.',
    relatedTopics: ['IAT', 'implicit attitudes', 'explicit attitudes', 'automatic association', 'implicit bias'],
  },
  {
    id: 'mcat2-ps-056',
    sectionId: 'psych-soc',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Sociology',
    contentCategory: 'Social mobility',
    foundationalConcept: 'FC 9',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    question: 'A child raised in poverty who, through education and hard work, attains a high-income profession is an example of:',
    choices: [
      { label: 'A', text: 'Horizontal mobility — moving within the same social stratum' },
      { label: 'B', text: 'Downward mobility — losing social standing relative to previous position' },
      { label: 'C', text: 'Intergenerational upward mobility — attaining higher socioeconomic status than one\'s family of origin' },
      { label: 'D', text: 'Structural mobility — mobility driven by macroeconomic changes that lift an entire class' },
    ],
    correctAnswer: 'C',
    explanation: 'Intergenerational mobility refers to changes in social status across generations (parent to child). Upward intergenerational mobility = higher SES than parents. This scenario describes exactly that: a child from poverty achieving high-income professional status. C is correct. A (horizontal) is movement at the same level (e.g., changing from one manual labor job to another of equal status). B (downward) is loss of status. D (structural) is when macroeconomic changes (e.g., post-WWII economic expansion) create widespread upward mobility across an entire class — distinct from individual upward mobility through personal effort.',
    wrongAnswerExplanations: {
      A: 'Horizontal mobility = lateral movement within the same social stratum (e.g., a nurse changing hospitals without gaining prestige or income). No vertical change.',
      B: 'Downward mobility = lower SES than starting point or parents. This scenario is explicitly upward.',
      D: 'Structural mobility results from broad economic changes that move entire cohorts up regardless of individual effort (e.g., expansion of middle-class jobs in post-WWII America). The scenario describes individual upward mobility, not structural.',
    },
    teachingPoint: 'Types of social mobility: vertical (up or down); horizontal (lateral, same level); intergenerational (compared to parents); intragenerational (within own lifetime); structural (macro changes). Most MCAT questions distinguish: intergenerational upward (child > parent SES) vs. structural mobility (macro forces, not individual action).',
    relatedTopics: ['social mobility', 'intergenerational mobility', 'upward mobility', 'social stratification', 'SES'],
  },
  {
    id: 'mcat2-ps-057',
    sectionId: 'psych-soc',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Psychology',
    contentCategory: 'Motivation',
    foundationalConcept: 'FC 7',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    question: 'According to self-determination theory (SDT), intrinsic motivation is most likely to be undermined when:',
    choices: [
      { label: 'A', text: 'The task is novel and challenging' },
      { label: 'B', text: 'The person receives unexpected positive feedback on their performance' },
      { label: 'C', text: 'Controlling external rewards are introduced for activities the person already finds inherently enjoyable (overjustification effect)' },
      { label: 'D', text: 'The person sets personal goals aligned with their values' },
    ],
    correctAnswer: 'C',
    explanation: 'Self-determination theory (Deci and Ryan) identifies three basic psychological needs: autonomy, competence, and relatedness. Intrinsic motivation (engaging in an activity for its own sake) is maintained when these needs are met. The overjustification effect describes the well-documented phenomenon where introducing controlling external rewards (e.g., paying someone to do something they love) undermines intrinsic motivation — the person\'s attribution for their behavior shifts from "I do this because I enjoy it" to "I do this for the reward." C is correct. A (novel and challenging tasks) typically supports intrinsic motivation (flow, competence-building). B (unexpected positive feedback) is informationally motivating (enhances perceived competence) without being controlling — SDT distinguishes unexpected/informational feedback from expected/controlling rewards. D (personal goal alignment) supports intrinsic motivation through autonomy.',
    wrongAnswerExplanations: {
      A: 'Novel and challenging tasks that match skill level support intrinsic motivation — they engage the need for competence and can produce flow (Csikszentmihalyi). Intrinsic motivation is not undermined.',
      B: 'Unexpected positive feedback is informational (tells you that you\'re competent), not controlling. SDT predicts informational feedback enhances intrinsic motivation. Only expected, controlling, contingent rewards undermine it.',
      D: 'Setting goals aligned with personal values reflects autonomous motivation — one of the pillars of SDT. This supports, not undermines, intrinsic motivation.',
    },
    teachingPoint: 'Overjustification effect: adding controlling external rewards to intrinsically motivated behavior undermines intrinsic motivation. Classic study: children who liked drawing were paid to draw; after payment stopped, they drew less than before. SDT prediction: controlling rewards shift perceived locus of causality from internal ("I love this") to external ("I do this for money").',
    relatedTopics: ['self-determination theory', 'intrinsic motivation', 'overjustification effect', 'extrinsic reward', 'autonomy'],
  },
  {
    id: 'mcat2-ps-058',
    sectionId: 'psych-soc',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Sociology',
    contentCategory: 'Social institutions',
    foundationalConcept: 'FC 9',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    question: 'Erving Goffman\'s concept of a "total institution" is best exemplified by:',
    choices: [
      { label: 'A', text: 'A community college where students commute daily to take classes' },
      { label: 'B', text: 'A hospital where patients go for day surgery and return home the same evening' },
      { label: 'C', text: 'A residential psychiatric facility where patients live, eat, sleep, and are subject to institutional authority around the clock' },
      { label: 'D', text: 'A workplace where employees work nine-to-five shifts' },
    ],
    correctAnswer: 'C',
    explanation: 'Goffman (1961) defined a total institution as a place of residence and work where a large number of individuals, cut off from wider society for an appreciable period, together lead an enclosed, formally administered round of life — all aspects of life (sleeping, eating, working, recreation) are conducted in the same place under a single authority. Examples: prisons, military barracks, psychiatric hospitals, monasteries. C matches all features: residential, 24-hour authority, enclosed, institutional management of all life activities. A, B, and D describe partial institutions — people go in and out; total control is not exercised over all life domains.',
    wrongAnswerExplanations: {
      A: 'A commuter college is not a total institution — students come and go, live outside, and retain control over their non-class activities.',
      B: 'A day surgery hospital is not a total institution — patients return to their own lives the same day, without the "enclosed round of life" feature.',
      D: 'A 9-to-5 workplace is not a total institution — employees return to their own lives outside of work hours and are not under institutional authority for all life domains.',
    },
    teachingPoint: 'Goffman\'s total institution: (1) all life domains in one place; (2) under single authority; (3) cut off from wider society; (4) activities tightly scheduled; (5) mortification of self (identity stripped, replaced with institutional identity). Examples: prisons, psychiatric hospitals, military boot camps, convents, concentration camps.',
    relatedTopics: ['total institution', 'Goffman', 'socialization', 'social control', 'institutional authority'],
  },
  {
    id: 'mcat2-ps-059',
    sectionId: 'psych-soc',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Psychology',
    contentCategory: 'Group dynamics',
    foundationalConcept: 'FC 8',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    question: 'A team of surgeons consistently performs better when observed by attending physicians than when working alone. This phenomenon is best explained by:',
    choices: [
      { label: 'A', text: 'Social loafing — the presence of others reduces individual effort' },
      { label: 'B', text: 'Social facilitation — the presence of an audience enhances performance on well-learned or simple tasks' },
      { label: 'C', text: 'Groupthink — the group suppresses dissent to maintain harmony' },
      { label: 'D', text: 'Deindividuation — loss of identity in a group reduces accountability' },
    ],
    correctAnswer: 'B',
    explanation: 'Social facilitation (Zajonc) occurs when the presence of others (audience or co-actors) enhances performance on dominant (well-learned, simple) responses and impairs performance on non-dominant (complex, novel) responses. Experienced surgeons performing established procedures is a well-learned task for them — so audience presence enhances performance. B is correct. A (social loafing) occurs when individual effort decreases in group work where contributions are not individually identifiable — opposite of enhancement. C (groupthink) is faulty collective decision-making, not individual performance. D (deindividuation) involves loss of self-awareness in groups, often associated with reduced restraint.',
    wrongAnswerExplanations: {
      A: 'Social loafing would predict worse performance in a group/observed setting, as individuals reduce individual effort when their contribution is not individually identifiable. This scenario shows improved performance.',
      C: 'Groupthink is a phenomenon in decision-making groups under pressure for consensus — suppression of dissent. It doesn\'t explain individual task performance improvement under observation.',
      D: 'Deindividuation reduces self-monitoring and constraint (can lead to anti-normative behavior), not enhanced skilled performance. Surgeons performing better under observation is increased, not decreased, self-monitoring.',
    },
    teachingPoint: 'Social facilitation (Zajonc): audience presence → arousal → dominant response enhanced. Well-learned tasks (experienced surgeon, proficient cyclist) → better with audience. Novel/complex tasks (learning a new procedure, beginner cyclist) → worse with audience. Corollary: social inhibition occurs for non-dominant/complex tasks.',
    relatedTopics: ['social facilitation', 'social loafing', 'Zajonc', 'dominant response', 'audience effects'],
  },
]
