import type { MCATQuestion } from '../types'

// Form 3 C/P — 16 Discrete Questions
// IDs: mcat3-cp-044 through mcat3-cp-059
// Topics: kinematics, thermochemistry, organic reactions, spectroscopy, magnetism,
//         nuclear, gas laws, stoichiometry, electronegativity, periodic trends

export const chemPhysDiscretes3: MCATQuestion[] = [
  {
    id: 'mcat3-cp-044',
    sectionId: 'chem-phys',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Physics',
    contentCategory: 'Kinematics',
    foundationalConcept: 'FC 4',
    scientificSkill: 'Skill 2',
    difficulty: 'easy',
    question: 'A ball is dropped from rest off a cliff 80 m high (g = 10 m/s²). How long does it take to hit the ground?',
    choices: [
      { label: 'A', text: '4 s' },
      { label: 'B', text: '8 s' },
      { label: 'C', text: '16 s' },
      { label: 'D', text: '4√2 s' },
    ],
    correctAnswer: 'A',
    explanation: 'Free fall: h = ½gt². 80 = ½(10)t² → 80 = 5t² → t² = 16 → t = 4 s. A is correct. B would result from h = gt² (missing the ½). C would result from t² = 80 without the factor of 5. D = 4√2 ≈ 5.66 s is incorrect.',
    wrongAnswerExplanations: {
      B: 'Using h = gt² (missing the ½ factor). Free fall: h = ½gt².',
      C: 'Setting t² = 80 instead of t² = 16 (forgot to divide h by ½g = 5). 80/5 = 16, t = 4.',
      D: '4√2 ≈ 5.66 s results from a different algebra error. t = √16 = 4 s exactly.',
    },
    teachingPoint: 'Free fall from rest: d = ½gt². t = √(2d/g) = √(2×80/10) = √16 = 4 s. Final velocity: v = gt = 10 × 4 = 40 m/s = 144 km/h.',
    relatedTopics: ['free fall', 'kinematics', 'gravitational acceleration', 'projectile motion'],
  },
  {
    id: 'mcat3-cp-045',
    sectionId: 'chem-phys',
    passageId: null,
    questionType: 'discrete',
    discipline: 'General Chemistry',
    contentCategory: 'Thermochemistry',
    foundationalConcept: 'FC 5',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    question: 'Using Hess\'s law: ΔH°(combustion of carbon) = −393.5 kJ/mol; ΔH°(combustion of hydrogen) = −285.8 kJ/mol; ΔH°(combustion of ethanol, C₂H₅OH) = −1366.8 kJ/mol. What is ΔH°f of ethanol? (Reaction: 2C + 3H₂ + ½O₂ → C₂H₅OH)',
    choices: [
      { label: 'A', text: '−277.7 kJ/mol' },
      { label: 'B', text: '+277.7 kJ/mol' },
      { label: 'C', text: '−687.4 kJ/mol' },
      { label: 'D', text: '+1366.8 kJ/mol' },
    ],
    correctAnswer: 'A',
    explanation: 'Hess\'s law: ΔH°f(ethanol) = [2 × ΔH°combustion(C) + 3 × ΔH°combustion(H₂)] − ΔH°combustion(ethanol). = [2(−393.5) + 3(−285.8)] − (−1366.8) = [−787 + (−857.4)] − (−1366.8) = −1644.4 + 1366.8 = −277.6 ≈ −277.7 kJ/mol. A is correct (ethanol standard heat of formation is negative — exothermic formation from elements). Note: This uses the relation ΔH°combustion(reactant) = ΔH°f(CO₂) × n_C + ΔH°f(H₂O) × n_H₂O − ΔH°f(compound).',
    wrongAnswerExplanations: {
      B: '+277.7 kJ/mol has the correct magnitude but wrong sign. Formation of ethanol from its elements is exothermic (ΔH°f < 0).',
      C: '−687.4 kJ/mol results from adding combustion enthalpies without applying Hess\'s law correctly.',
      D: '+1366.8 kJ/mol is the reverse of the combustion enthalpy — not ΔH°f.',
    },
    teachingPoint: 'Hess\'s law allows combining known ΔH values to calculate unknown ones. ΔH°f of a compound = energies of forming it from elements. Known standard: ethanol ΔH°f ≈ −278 kJ/mol (exothermic, more stable than elements).',
    relatedTopics: ['Hess\'s law', 'standard enthalpy of formation', 'combustion enthalpy', 'thermochemistry'],
  },
  {
    id: 'mcat3-cp-046',
    sectionId: 'chem-phys',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Organic Chemistry',
    contentCategory: 'Stereochemistry',
    foundationalConcept: 'FC 5',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    question: 'Which of the following is a chiral molecule?',
    choices: [
      { label: 'A', text: 'CH₂Cl₂ (dichloromethane)' },
      { label: 'B', text: 'CHClBrF (carbon with four different substituents)' },
      { label: 'C', text: 'CCl₄ (carbon tetrachloride)' },
      { label: 'D', text: 'CH₃CH₃ (ethane)' },
    ],
    correctAnswer: 'B',
    explanation: 'A chiral molecule has at least one stereocenter — a carbon with four different substituents (no plane of symmetry). CHClBrF: the central carbon has H, Cl, Br, and F (all different) → chiral center → chiral molecule. B is correct. CH₂Cl₂: two H and two Cl → only two different substituents → not chiral. CCl₄: four identical Cl → not chiral. CH₃CH₃: no carbon with 4 different substituents.',
    wrongAnswerExplanations: {
      A: 'CH₂Cl₂ has the central carbon bearing H, H, Cl, Cl — two pairs of identical substituents. This carbon has only two different substituents → not a stereocenter → not chiral. CH₂Cl₂ has a plane of symmetry.',
      C: 'CCl₄ has four identical substituents (all Cl) → highly symmetric, not chiral.',
      D: 'CH₃CH₃ (ethane): each carbon bears 3 H + 1 C (from the other CH₃) → not four different substituents. Not chiral.',
    },
    teachingPoint: 'Chirality requires a stereocenter: carbon with four DIFFERENT groups. Mnemonic: CHFClBr (the simplest chiral molecule — four different halogens/H). Test for chirality: are there four different groups? Is there a plane/center of symmetry?',
    relatedTopics: ['chirality', 'stereocenter', 'enantiomers', 'chiral carbon', 'stereochemistry'],
  },
  {
    id: 'mcat3-cp-047',
    sectionId: 'chem-phys',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Physics',
    contentCategory: 'Circuits',
    foundationalConcept: 'FC 4',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    question: 'Three resistors (R₁ = 2Ω, R₂ = 4Ω, R₃ = 12Ω) are connected in parallel across a 12 V battery. What is the total current drawn from the battery?',
    choices: [
      { label: 'A', text: '1 A' },
      { label: 'B', text: '7 A' },
      { label: 'C', text: '10 A' },
      { label: 'D', text: '18 A' },
    ],
    correctAnswer: 'C',
    explanation: 'In parallel, total current = sum of currents in each branch. I₁ = V/R₁ = 12/2 = 6 A. I₂ = 12/4 = 3 A. I₃ = 12/12 = 1 A. I_total = 6 + 3 + 1 = 10 A. C is correct. Alternatively: 1/R_eq = 1/2 + 1/4 + 1/12 = 6/12 + 3/12 + 1/12 = 10/12 → R_eq = 12/10 = 1.2Ω. I = V/R_eq = 12/1.2 = 10 A. B (7 A) misses the first branch. D (18 A) sums voltages incorrectly.',
    wrongAnswerExplanations: {
      B: '7 A = 3 + 1 + 3 is not correct. The correct individual currents are 6 + 3 + 1 = 10 A.',
      A: '1 A would be the current through R₃ alone. Total current includes all three branches.',
      D: '18 A = 12 + 4 + 2 sums the resistance values divided into 12, in wrong order, or other arithmetic error.',
    },
    teachingPoint: 'Parallel resistors: same voltage across each. I_total = I₁ + I₂ + I₃ = V/R₁ + V/R₂ + V/R₃. 1/R_eq = Σ(1/Rᵢ). Series vs. parallel: series has same current, different voltages. Parallel has same voltage, different currents.',
    relatedTopics: ['parallel circuit', 'Ohm\'s law', 'current', 'equivalent resistance', 'resistors'],
  },
  {
    id: 'mcat3-cp-048',
    sectionId: 'chem-phys',
    passageId: null,
    questionType: 'discrete',
    discipline: 'General Chemistry',
    contentCategory: 'Gas laws',
    foundationalConcept: 'FC 4',
    scientificSkill: 'Skill 2',
    difficulty: 'easy',
    question: 'A gas occupies 4.0 L at 300 K and 2.0 atm. What is its volume at 600 K and 1.0 atm?',
    choices: [
      { label: 'A', text: '4.0 L' },
      { label: 'B', text: '8.0 L' },
      { label: 'C', text: '16.0 L' },
      { label: 'D', text: '2.0 L' },
    ],
    correctAnswer: 'C',
    explanation: 'Combined gas law: P₁V₁/T₁ = P₂V₂/T₂. V₂ = V₁ × (P₁/P₂) × (T₂/T₁) = 4.0 × (2.0/1.0) × (600/300) = 4.0 × 2 × 2 = 16.0 L. C is correct. Temperature doubles → volume doubles. Pressure halves → volume doubles. Both effects together: 4.0 × 2 × 2 = 16.0 L.',
    wrongAnswerExplanations: {
      A: '4.0 L would result from the effects exactly canceling — e.g., T × 2 and P × 2, but here P halves (doubles volume) and T doubles (also doubles volume) → both effects increase volume.',
      B: '8.0 L accounts for only one doubling factor (either pressure or temperature), not both.',
      D: '2.0 L would result from both effects decreasing volume — which is the opposite of what occurs here.',
    },
    teachingPoint: 'Combined gas law: P₁V₁/T₁ = P₂V₂/T₂ (must use K). Identify changes: T doubles (V doubles at constant P). P halves (V doubles at constant T). Both: V quadruples. 4.0 × 4 = 16 L. Quick check: always verify T in Kelvin.',
    relatedTopics: ['combined gas law', 'ideal gas', 'temperature-volume', 'pressure-volume', 'Boyle Charles Gay-Lussac'],
  },
  {
    id: 'mcat3-cp-049',
    sectionId: 'chem-phys',
    passageId: null,
    questionType: 'discrete',
    discipline: 'General Chemistry',
    contentCategory: 'Periodic trends',
    foundationalConcept: 'FC 4',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    question: 'Which element has the highest first ionization energy: Na, Mg, Al, or Cl?',
    choices: [
      { label: 'A', text: 'Na' },
      { label: 'B', text: 'Mg' },
      { label: 'C', text: 'Al' },
      { label: 'D', text: 'Cl' },
    ],
    correctAnswer: 'D',
    explanation: 'Ionization energy increases across a period (left to right) and increases up a group. All four elements are in Period 3 (Na Z=11, Mg Z=12, Al Z=13, Cl Z=17). Moving right across the period, increasing nuclear charge and decreasing atomic radius make it harder to remove the valence electron. Among these, Cl (Z=17) is rightmost and has the highest first ionization energy. D is correct. Note: small anomalies exist (Mg > Al in Period 3 due to Mg\'s full 3s²) but among these four, Cl is clearly highest.',
    wrongAnswerExplanations: {
      A: 'Na has the lowest ionization energy among Period 3 elements — it readily loses its one valence electron to form Na⁺.',
      B: 'Mg has higher IE₁ than Na and Al but lower than Cl. (Mg\'s full 3s² is slightly higher IE than Al\'s 3p¹, but Cl at 3p⁵ is highest among these four.)',
      C: 'Al (3p¹) has a lower IE₁ than Mg (3s²) — an anomaly in the trend due to the 3p electron being slightly easier to remove than a 3s electron. Cl is still highest.',
    },
    teachingPoint: 'IE₁ trend: increases left → right in a period (more nuclear charge, smaller radius, electron harder to remove). Period 3 approximate order: Na < Mg > Al < Si < P > S < Cl. Small anomalies: Mg > Al (3s² vs 3p¹); P > S (half-filled 3p³ stability). Cl is clearly > Na, Mg, Al among these four choices.',
    relatedTopics: ['ionization energy', 'periodic trends', 'Period 3', 'nuclear charge', 'valence electrons'],
  },
  {
    id: 'mcat3-cp-050',
    sectionId: 'chem-phys',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Physics',
    contentCategory: 'Work and energy',
    foundationalConcept: 'FC 4',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    question: 'A 70 kg person climbs a flight of stairs 5 m high in 10 seconds. What is their power output? (g = 10 m/s²)',
    choices: [
      { label: 'A', text: '35 W' },
      { label: 'B', text: '350 W' },
      { label: 'C', text: '3,500 W' },
      { label: 'D', text: '70 W' },
    ],
    correctAnswer: 'B',
    explanation: 'Work done against gravity: W = mgh = 70 × 10 × 5 = 3,500 J. Power = W/t = 3,500/10 = 350 W. B is correct. This is roughly 0.47 horsepower — a reasonable sustained output for a healthy adult. A (35 W) divides by 100 instead of 10. C (3,500 W) is work in J, not power. D (70 W) ignores g.',
    wrongAnswerExplanations: {
      A: '35 W = 3500/100. Should divide by time (10 s), not 100.',
      C: '3,500 W is the work done (W = mgh = 3,500 J), not power. Power = work/time = 3500/10 = 350 W.',
      D: '70 W ignores the acceleration due to gravity in the work calculation. W = m × g × h, not m × h.',
    },
    teachingPoint: 'Power = Work/time = Force × velocity. For vertical lift: W = mgh. P = mgh/t = 70 × 10 × 5/10 = 350 W. Human power: sustained ~75–350 W; peak sprint ~1,000 W. 1 horsepower = 746 W.',
    relatedTopics: ['power', 'work', 'potential energy', 'gravitational PE', 'mechanical work'],
  },
  {
    id: 'mcat3-cp-051',
    sectionId: 'chem-phys',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Organic Chemistry',
    contentCategory: 'Functional groups',
    foundationalConcept: 'FC 5',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    question: 'Which functional group is responsible for the acidic character of carboxylic acids?',
    choices: [
      { label: 'A', text: 'The carbonyl group (C=O)' },
      { label: 'B', text: 'The carboxyl group (–COOH), specifically the O–H bond that donates a proton to give the resonance-stabilized carboxylate anion (–COO⁻)' },
      { label: 'C', text: 'The alkyl chain attached to the –COOH group' },
      { label: 'D', text: 'The lone pair on the carbonyl oxygen' },
    ],
    correctAnswer: 'B',
    explanation: 'Carboxylic acids (R–COOH) are acidic because the O–H bond in the –COOH group donates a proton (H⁺). The resulting carboxylate anion (–COO⁻) is stabilized by resonance delocalization of the negative charge across both oxygens. This resonance stabilization of the conjugate base increases the acid\'s Ka (pKa ≈ 4–5). B is correct. A (carbonyl C=O alone) is not the acidic site. C (alkyl chain) can influence but is not responsible for the acidic character. D (lone pair) would make it basic, not acidic.',
    wrongAnswerExplanations: {
      A: 'The carbonyl C=O contributes to the acidity by enabling resonance stabilization of the carboxylate anion, but it is not itself the acidic site — the O–H bond is.',
      C: 'Alkyl groups can inductively affect acidity (electron-withdrawing groups increase acidity), but the alkyl chain alone is not the source of acidity.',
      D: 'Lone pairs on oxygen make it a hydrogen bond acceptor and Lewis base in some contexts, not a proton donor.',
    },
    teachingPoint: 'Carboxylic acid acidity: COOH → COO⁻ + H⁺. The carboxylate anion is resonance-stabilized (charge delocalized over both oxygens) → stable conjugate base → pKa ≈ 4–5 (stronger than alcohols, phenols weaker than H₃O⁺). Factors increasing acidity: electron-withdrawing groups on R (lower pKa), more electronegative substituents.',
    relatedTopics: ['carboxylic acid', 'acidity', 'resonance stabilization', 'carboxylate', 'pKa'],
  },
  {
    id: 'mcat3-cp-052',
    sectionId: 'chem-phys',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Physics',
    contentCategory: 'Magnetism',
    foundationalConcept: 'FC 4',
    scientificSkill: 'Skill 1',
    difficulty: 'medium',
    question: 'A proton (charge +e) moves with velocity v horizontally through a uniform magnetic field B directed vertically upward. The magnetic force on the proton is:',
    choices: [
      { label: 'A', text: 'F = qvB, directed horizontally perpendicular to both v and B' },
      { label: 'B', text: 'F = qvB, directed parallel to v (in the direction of motion)' },
      { label: 'C', text: 'F = qvB, directed parallel to B (vertically upward)' },
      { label: 'D', text: 'F = 0 because the proton is moving perpendicular to B' },
    ],
    correctAnswer: 'A',
    explanation: 'Magnetic force: F = qv × B. The magnitude is F = qvB sin θ. Since v is horizontal and B is vertical, θ = 90°, sin 90° = 1, so F = qvB. The direction is given by the right-hand rule: F = v × B → perpendicular to both v (horizontal) and B (vertical) → horizontal, perpendicular to the direction of motion. This causes circular motion (the proton curves). A is correct. B is wrong — magnetic force is never parallel to v. C is wrong — force is never parallel to B. D is wrong — sin 90° = 1, not 0; force is maximum when v ⊥ B.',
    wrongAnswerExplanations: {
      B: 'Magnetic force is always perpendicular to velocity (F = qv × B). A force parallel to velocity would do work and change kinetic energy — magnetic forces never do work.',
      C: 'Magnetic force is always perpendicular to B (from the cross product). The force cannot be in the direction of the magnetic field.',
      D: 'F = qvB sin θ. When v ⊥ B (θ = 90°), sin θ = 1 → MAXIMUM force, not zero. Zero force occurs when v is parallel to B (sin 0° = 0).',
    },
    teachingPoint: 'Magnetic force: F = qv × B. Key properties: (1) perpendicular to both v and B; (2) magnitude = qvB sin θ; (3) does no work (⊥ to displacement); (4) causes circular motion (centripetal force). Maximum force when v ⊥ B; zero force when v ∥ B.',
    relatedTopics: ['magnetic force', 'Lorentz force', 'right-hand rule', 'cross product', 'circular motion in B field'],
  },
  {
    id: 'mcat3-cp-053',
    sectionId: 'chem-phys',
    passageId: null,
    questionType: 'discrete',
    discipline: 'General Chemistry',
    contentCategory: 'Chemical bonding',
    foundationalConcept: 'FC 4',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    question: 'Which molecule has the highest boiling point due to intermolecular forces?',
    choices: [
      { label: 'A', text: 'CH₄ (methane, MW 16)' },
      { label: 'B', text: 'HF (hydrogen fluoride, MW 20)' },
      { label: 'C', text: 'F₂ (fluorine gas, MW 38)' },
      { label: 'D', text: 'CH₃F (fluoromethane, MW 34)' },
    ],
    correctAnswer: 'B',
    explanation: 'HF forms strong hydrogen bonds (N–H, O–H, F–H are the three most important H-bond donors/acceptors). Despite its small molecular weight (MW 20), HF has a disproportionately high boiling point (~19.5°C) due to hydrogen bonding. CH₃F has dipole-dipole interactions (polar C–F bond) but no H–F bond for hydrogen bonding. F₂ has only London dispersion forces (larger MW increases dispersion, but no polar bond). CH₄ has only London dispersion (smallest, least polarizable). Rank: HF (H-bond) > CH₃F (dipole-dipole, MW 34) > F₂ (London, MW 38) > CH₄ (London, MW 16).',
    wrongAnswerExplanations: {
      A: 'CH₄ has only weak London dispersion forces (small, non-polar) → boiling point = −162°C. Lowest boiling point of the four.',
      C: 'F₂ has London dispersion forces only (non-polar). Despite higher MW than HF, no dipole and no H-bonding → bp = −188°C.',
      D: 'CH₃F has dipole-dipole interactions (C–F is polar), but no H–F hydrogen bond. Bp ≈ −78°C. Higher than CH₄ and F₂ but lower than HF.',
    },
    teachingPoint: 'Intermolecular force strength: H-bonding (HF, H₂O, NH₃) >> dipole-dipole > London dispersion. H-bonding requires H bonded directly to N, O, or F, AND the H-bond acceptor (also N, O, or F). HF bp = +19.5°C (anomalously high for MW 20). H₂O bp = 100°C (anomalously high for MW 18).',
    relatedTopics: ['hydrogen bonding', 'intermolecular forces', 'boiling point', 'dipole-dipole', 'London dispersion'],
  },
  {
    id: 'mcat3-cp-054',
    sectionId: 'chem-phys',
    passageId: null,
    questionType: 'discrete',
    discipline: 'General Chemistry',
    contentCategory: 'Stoichiometry',
    foundationalConcept: 'FC 5',
    scientificSkill: 'Skill 2',
    difficulty: 'easy',
    question: 'Glucose (C₆H₁₂O₆, MW = 180 g/mol) combustion: C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O. How many grams of CO₂ (MW = 44 g/mol) are produced from 360 g of glucose?',
    choices: [
      { label: 'A', text: '264 g' },
      { label: 'B', text: '528 g' },
      { label: 'C', text: '132 g' },
      { label: 'D', text: '44 g' },
    ],
    correctAnswer: 'B',
    explanation: 'Moles of glucose = 360/180 = 2 mol. Molar ratio glucose:CO₂ = 1:6. Moles CO₂ = 2 × 6 = 12 mol. Mass CO₂ = 12 × 44 = 528 g. B is correct. A (264 g) would result from using 6 mol CO₂ (from 1 mol glucose). C (132 g) = 3 mol CO₂ (incorrect ratio). D (44 g) = 1 mol CO₂.',
    wrongAnswerExplanations: {
      A: '264 g = 6 × 44 = 6 mol CO₂, which is correct for 1 mol glucose. But we have 2 mol glucose → 12 mol CO₂ → 528 g.',
      C: '132 g = 3 mol CO₂. This uses neither the correct moles of glucose (2) nor the correct ratio (6).',
      D: '44 g = 1 mol CO₂ — only accounts for 1/12 of the product. ',
    },
    teachingPoint: 'Stoichiometry: (1) grams → moles (÷ MW); (2) apply molar ratio; (3) moles → grams (× MW). 360 g glucose ÷ 180 g/mol = 2 mol. × 6 (ratio) = 12 mol CO₂. × 44 g/mol = 528 g.',
    relatedTopics: ['stoichiometry', 'molar mass', 'combustion', 'mole ratio', 'limiting reagent'],
  },
  {
    id: 'mcat3-cp-055',
    sectionId: 'chem-phys',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Physics',
    contentCategory: 'Thermodynamics',
    foundationalConcept: 'FC 4',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    question: 'A heat engine operates between a hot reservoir at 800 K and a cold reservoir at 400 K. What is its maximum (Carnot) efficiency?',
    choices: [
      { label: 'A', text: '25%' },
      { label: 'B', text: '50%' },
      { label: 'C', text: '75%' },
      { label: 'D', text: '100%' },
    ],
    correctAnswer: 'B',
    explanation: 'Carnot efficiency: η = 1 − (T_cold/T_hot) = 1 − (400/800) = 1 − 0.5 = 0.5 = 50%. B is correct. This is the maximum theoretical efficiency for any heat engine operating between these temperatures. A (25%) would result from η = T_cold/T_hot (inverted formula). C (75%) would correspond to T_cold = 200 K. D (100%) would require T_cold = 0 K (impossible by 3rd law).',
    wrongAnswerExplanations: {
      A: '25% would result from computing T_cold/T_hot = 400/800 = 0.5, then halving (another error). Carnot efficiency = 1 − T_cold/T_hot = 50%, not 25%.',
      C: '75% would require T_cold = 0.25 × T_hot = 200 K. Here T_cold = 400 K.',
      D: '100% efficiency is impossible for a heat engine operating between two finite-temperature reservoirs (2nd law of thermodynamics). 100% would require T_cold = 0 K.',
    },
    teachingPoint: 'Carnot efficiency: η = 1 − T_C/T_H (temperatures in Kelvin). Maximum possible efficiency for any heat engine between these reservoirs. Real engines are less efficient due to irreversibilities. Doubling T_C/T_H ratio to 1:1 would give η = 0 (useless). T_C = 0 K gives η = 100% (impossible).',
    relatedTopics: ['Carnot efficiency', 'heat engine', 'thermodynamics', 'second law', 'maximum efficiency'],
  },
  {
    id: 'mcat3-cp-056',
    sectionId: 'chem-phys',
    passageId: null,
    questionType: 'discrete',
    discipline: 'General Chemistry',
    contentCategory: 'Kinetics',
    foundationalConcept: 'FC 5',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    question: 'A reaction is second-order in [A] and first-order in [B]. If [A] doubles and [B] triples, by what factor does the rate increase?',
    choices: [
      { label: 'A', text: '6-fold' },
      { label: 'B', text: '12-fold' },
      { label: 'C', text: '18-fold' },
      { label: 'D', text: '3-fold' },
    ],
    correctAnswer: 'B',
    explanation: 'Rate = k[A]²[B]. Doubling [A]: rate factor = (2)² = 4. Tripling [B]: rate factor = 3¹ = 3. Combined: 4 × 3 = 12-fold increase. B is correct. A (6-fold) would result from first-order [A] effect (2 × 3 = 6). C (18-fold) would require (3)² × 2 instead. D (3-fold) accounts for [B] effect only.',
    wrongAnswerExplanations: {
      A: '6-fold = 2 × 3 treats [A] as first-order. The reaction is SECOND-order in [A]: factor = 2² = 4, not 2.',
      C: '18-fold = 3² × 2 treats [B] as second-order and [A] as first-order. The orders are reversed.',
      D: '3-fold accounts for [B] only (tripling) and ignores the [A] effect.',
    },
    teachingPoint: 'Rate law: rate = k[A]ⁿ[B]ᵐ. Each reactant effect is calculated separately and multiplied. 2nd order in [A]: [A]→2[A] gives rate × 2² = 4. 1st order in [B]: [B]→3[B] gives rate × 3¹ = 3. Total: 4 × 3 = 12×.',
    relatedTopics: ['rate law', 'reaction kinetics', 'reaction order', 'rate constant', 'concentration effects'],
  },
  {
    id: 'mcat3-cp-057',
    sectionId: 'chem-phys',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Organic Chemistry',
    contentCategory: 'Spectroscopy',
    foundationalConcept: 'FC 5',
    scientificSkill: 'Skill 1',
    difficulty: 'medium',
    question: 'In ¹H NMR spectroscopy, a proton adjacent to an electronegative group (e.g., –COOH) appears at:',
    choices: [
      { label: 'A', text: 'Higher field (lower δ, δ ≈ 0–2 ppm) because the electronegative group shielding effect increases electron density near the proton' },
      { label: 'B', text: 'Lower field (higher δ, δ ≈ 10–12 ppm for carboxylic acid O–H) because electronegative groups withdraw electron density, deshielding the proton' },
      { label: 'C', text: 'At δ = 0 ppm (same as TMS reference) because all protons resonate at the same frequency' },
      { label: 'D', text: 'Higher field (lower δ) because COOH groups donate electrons through resonance' },
    ],
    correctAnswer: 'B',
    explanation: 'Electronegative groups (O, N, halides) withdraw electron density from adjacent C–H bonds through inductive effects. Less electron density around the proton = decreased shielding = resonates at lower field (higher δ in ppm). Carboxylic acid O–H protons appear at very low field (δ ≈ 10–12 ppm) due to both inductive withdrawal and participation in resonance. B is correct. A inverts — electronegative groups deshield (lower field), not shield. C is wrong — all protons have different chemical environments. D is wrong — COOH withdraws electrons through induction and resonance.',
    wrongAnswerExplanations: {
      A: 'Electronegative groups WITHDRAW electron density (inductive effect) → LESS shielding → lower field (higher δ). They do not donate electrons to increase shielding.',
      C: 'TMS (δ = 0 ppm) is used as a reference because it is highly shielded. Different proton environments appear at different δ values — the basis of NMR analysis.',
      D: 'COOH withdraws electrons through resonance and induction. The carbonyl and hydroxyl oxygens are electronegative → reduce electron density on adjacent C.',
    },
    teachingPoint: '¹H NMR chemical shift (δ): higher δ = lower field = less shielded = deshielded. Deshielding causes: electronegative atoms nearby (induction), aromatic ring currents, carbonyl groups. Reference points: TMS = 0; alkyl C–H = 0.5–2; vinyl C–H = 5–6; aromatic = 7–8; aldehyde H = 9–10; COOH = 10–12.',
    relatedTopics: ['¹H NMR', 'chemical shift', 'deshielding', 'electronegativity', 'inductive effect'],
  },
  {
    id: 'mcat3-cp-058',
    sectionId: 'chem-phys',
    passageId: null,
    questionType: 'discrete',
    discipline: 'Physics',
    contentCategory: 'Optics',
    foundationalConcept: 'FC 4',
    scientificSkill: 'Skill 1',
    difficulty: 'easy',
    question: 'Total internal reflection can occur when light travels from:',
    choices: [
      { label: 'A', text: 'Air into glass (less dense to more dense medium)' },
      { label: 'B', text: 'Glass into air (more dense to less dense medium), at an angle of incidence exceeding the critical angle' },
      { label: 'C', text: 'Vacuum into water (less dense to more dense)' },
      { label: 'D', text: 'Water into glass (approximately equal optical densities)' },
    ],
    correctAnswer: 'B',
    explanation: 'Total internal reflection (TIR) occurs when light travels from a medium with higher refractive index (optically denser) to lower refractive index (less dense) AND the angle of incidence exceeds the critical angle (θ_c = arcsin(n₂/n₁)). Glass → air: n_glass ≈ 1.5 > n_air ≈ 1.0. This satisfies the condition. B is correct. A (air → glass): going from less to more dense — cannot have TIR (refraction always occurs). C (vacuum → water): same direction issue. D (water → glass): n_water ≈ 1.33 < n_glass ≈ 1.5 — wrong direction for TIR.',
    wrongAnswerExplanations: {
      A: 'Going from less to more optically dense (air → glass): refraction occurs and the ray bends toward the normal. TIR cannot occur — light always enters the denser medium.',
      C: 'Vacuum → water: same issue as air → glass — going from less to more dense. TIR requires more dense → less dense medium.',
      D: 'Water (n ≈ 1.33) → glass (n ≈ 1.5): going from less dense to more dense → TIR cannot occur.',
    },
    teachingPoint: 'TIR conditions: (1) light travels from denser (higher n) to less dense (lower n) medium; (2) angle of incidence > critical angle. Critical angle: θ_c = arcsin(n₂/n₁). Applications: optical fibers (glass core surrounded by cladding with lower n → TIR keeps light in the fiber), diamonds (many TIR reflections → brilliance), endoscopes.',
    relatedTopics: ['total internal reflection', 'critical angle', 'refractive index', 'Snell\'s law', 'fiber optics'],
  },
  {
    id: 'mcat3-cp-059',
    sectionId: 'chem-phys',
    passageId: null,
    questionType: 'discrete',
    discipline: 'General Chemistry',
    contentCategory: 'Solution chemistry',
    foundationalConcept: 'FC 5',
    scientificSkill: 'Skill 2',
    difficulty: 'medium',
    question: 'A 0.10 M solution of a weak acid (pKa = 5.0) has a pH of approximately:',
    choices: [
      { label: 'A', text: 'pH = 5.0' },
      { label: 'B', text: 'pH ≈ 3.0' },
      { label: 'C', text: 'pH ≈ 1.0' },
      { label: 'D', text: 'pH = 10.0' },
    ],
    correctAnswer: 'B',
    explanation: 'For a weak acid approximation: pH = ½(pKa − log C) = ½(pKa + pC). pC = −log(0.10) = 1. pH ≈ ½(5.0 + 1.0) = ½(6.0) = 3.0. Alternatively: [H⁺] = √(Ka × C). Ka = 10⁻⁵. [H⁺] = √(10⁻⁵ × 0.10) = √(10⁻⁶) = 10⁻³. pH = 3. B is correct. A (pH 5.0) would be the pH of a buffer at pKa, not of a pure weak acid. C (1.0) would be 0.10 M strong acid. D (10.0) would be basic solution.',
    wrongAnswerExplanations: {
      A: 'pH = pKa only when the weak acid is in a buffer at half-neutralization ([A⁻] = [HA]). For a pure 0.10 M weak acid, pH is determined by the degree of ionization, giving pH ≈ 3.',
      C: 'pH = 1.0 corresponds to a 0.10 M strong acid (fully dissociated, [H⁺] = 0.10 M). A weak acid with pKa = 5 is only slightly dissociated → higher pH (less acidic).',
      D: 'pH = 10 corresponds to a basic solution. A weak acid produces an acidic (pH < 7) solution.',
    },
    teachingPoint: 'Weak acid pH shortcut: pH = ½(pKa + pC) where pC = −log[HA]₀. pKa = 5, pC = 1 → pH = ½(6) = 3. Verification: Ka = 10⁻⁵, [H⁺] = √(Ka × C) = √(10⁻⁵ × 10⁻¹) = √10⁻⁶ = 10⁻³ → pH = 3. This shortcut works when Ka << C (weak acid condition).',
    relatedTopics: ['weak acid pH', 'pKa', 'Henderson-Hasselbalch', 'acid dissociation', 'pH calculation'],
  },
]
