import type { MCATPassage } from '../types'

// Form 3 P/S — Passages 6–9
// P6: 6q (mcat3-ps-031–036), P7: 5q (037–041), P8: 5q (042–046), P9: 5q (047–051)
// Subtotal: 21 questions

export const psPassages3_06to09: MCATPassage[] = [
  // ─── P/S Passage 6: Psychological Disorders and Diagnosis ─────────────────────
  {
    id: 'f3-ps-p6',
    sectionId: 'psych-soc',
    title: 'Classifying and Explaining Psychological Disorders',
    passageText: `The Diagnostic and Statistical Manual of Mental Disorders (DSM-5) defines a mental disorder as a syndrome characterized by clinically significant disturbance in an individual\'s cognition, emotion regulation, or behavior that reflects a dysfunction in the psychological, biological, or developmental processes underlying mental functioning, and that is associated with significant distress or disability. The DSM-5 moved away from a multiaxial system to a single-axis dimensional approach that rates symptom severity rather than simply categorizing presence or absence.

The biopsychosocial model (Engel, 1977) holds that mental illness arises from the interplay of biological factors (genetics, neurobiology, neurochemistry), psychological factors (cognition, learning history, personality), and social factors (stressors, social support, cultural context). This contrasts with a purely biomedical model that treats mental illness as a brain disease with primarily neurochemical causes.

Schizophrenia is a psychotic disorder characterized by positive symptoms (hallucinations — most commonly auditory; delusions — typically persecutory or grandiose; disorganized thinking/speech; disorganized behavior) and negative symptoms (flat affect, alogia, avolition, anhedonia, asociality). The dopamine hypothesis of schizophrenia proposes that excess dopaminergic activity in the mesolimbic pathway underlies positive symptoms; this is supported by the fact that drugs blocking D2 receptors (antipsychotics) reduce positive symptoms, while drugs increasing dopamine activity (amphetamines) can induce psychosis. Negative symptoms are associated with deficits in prefrontal dopamine activity.`,
    figures: [],
    questions: [
      {
        id: 'mcat3-ps-031',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p6',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'Which of the following is a negative symptom of schizophrenia?',
        choices: [
          { label: 'A', text: 'Auditory hallucinations — hearing voices that others cannot hear' },
          { label: 'B', text: 'Persecutory delusions — believing the government is monitoring you' },
          { label: 'C', text: 'Avolition — lack of motivation to engage in goal-directed activities' },
          { label: 'D', text: 'Disorganized speech — derailment and loose associations' },
        ],
        correctAnswer: 'C',
        explanation: 'Negative symptoms = deficit or reduction in normal functioning: flat affect (reduced emotional expression), alogia (poverty of speech), avolition (lack of motivation), anhedonia (inability to feel pleasure), asociality (social withdrawal). Avolition (C) is a classic negative symptom. A (hallucinations) and B (delusions) are positive symptoms — experiences added beyond normal. D (disorganized speech) is also a positive symptom (something added/distorted). The passage explicitly lists "flat affect, alogia, avolition, anhedonia, asociality" as negative symptoms.',
        wrongAnswerExplanations: {
          A: 'Hallucinations (false perceptions) are positive symptoms — they represent an excess or distortion of normal function, not a reduction or absence.',
          B: 'Delusions (fixed false beliefs) are positive symptoms — they represent a distortion of normal thinking processes.',
          D: 'Disorganized speech/thinking (derailment, loose associations, tangentiality) is a positive symptom — it represents a distortion of normal language production.',
        },
        teachingPoint: 'Positive vs. negative symptoms mnemonic: Positive = things that are ADDED (hallucinations, delusions, disorganized thought/behavior); Negative = things that are LOST (5 As: flat Affect, Alogia, Avolition, Anhedonia, Asociality). Antipsychotics (D2 blockers) effectively treat positive symptoms; negative symptoms are harder to treat. Second-generation antipsychotics (atypicals, e.g., clozapine) have more effect on negative symptoms.',
        relatedTopics: ['negative symptoms schizophrenia', 'avolition', 'positive vs negative symptoms', 'schizophrenia', 'anhedonia alogia'],
      },
      {
        id: 'mcat3-ps-032',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p6',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'According to the dopamine hypothesis of schizophrenia, amphetamines can induce psychotic symptoms in some individuals because:',
        choices: [
          { label: 'A', text: 'Amphetamines block D2 receptors in the mesolimbic pathway, mimicking the effect of antipsychotics' },
          { label: 'B', text: 'Amphetamines block serotonin reuptake, which indirectly increases dopamine in the nigrostriatal pathway' },
          { label: 'C', text: 'Amphetamines reduce prefrontal dopamine activity, directly causing auditory hallucinations' },
          { label: 'D', text: 'Amphetamines increase dopamine activity in the mesolimbic pathway, replicating the excess dopaminergic activity proposed to underlie positive symptoms' },
        ],
        correctAnswer: 'D',
        explanation: 'The passage states: "drugs increasing dopamine activity (amphetamines) can induce psychosis." Amphetamines increase dopamine release and block reuptake, elevating dopamine in the mesolimbic pathway. If excess mesolimbic dopamine underlies positive symptoms, then amphetamines (increasing mesolimbic dopamine) should produce positive symptoms — which they do at high doses. D is correct. A inverts — amphetamines INCREASE dopamine, not block receptors. C — prefrontal dopamine DEFICIT is associated with negative symptoms (not hallucinations directly). D — amphetamines primarily affect dopamine (and norepinephrine), not serotonin reuptake (SSRIs do that).',
        wrongAnswerExplanations: {
          A: 'Amphetamines are dopamine AGONISTS (increase dopamine release and block reuptake), not D2 blockers. D2 blockers are antipsychotics that REDUCE positive symptoms.',
          C: 'Reduced prefrontal dopamine is associated with NEGATIVE symptoms (cognitive deficits, flat affect) — not the generation of positive symptoms like hallucinations. Positive symptoms arise from excess MESOLIMBIC dopamine.',
          B: 'Amphetamines primarily act on dopamine and norepinephrine transporters (increasing release and blocking reuptake). SSRIs block serotonin reuptake. The dopamine hypothesis specifically implicates mesolimbic dopamine, not serotonin or nigrostriatal pathways.',
          
        },
        teachingPoint: 'Dopamine hypothesis evidence: (1) D2 antagonists (antipsychotics) reduce positive symptoms; (2) dopamine agonists (amphetamines, L-DOPA) can induce psychosis; (3) PET imaging shows elevated D2 receptor occupancy in schizophrenia. Pathways: mesolimbic (VTA → limbic) = positive symptoms (excess); mesocortical (VTA → prefrontal cortex) = negative symptoms (deficit); nigrostriatal (substantia nigra → striatum) = motor control (affected by antipsychotic side effects — EPS); tuberoinfundibular (hypothalamus → pituitary) = prolactin regulation (antipsychotics → hyperprolactinemia).',
        relatedTopics: ['dopamine hypothesis', 'amphetamine psychosis', 'mesolimbic pathway', 'antipsychotics D2', 'schizophrenia dopamine'],
      },
      {
        id: 'mcat3-ps-033',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p6',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'The biopsychosocial model predicts that two individuals with identical genetic vulnerability to depression will experience different clinical outcomes. Which scenario best illustrates this prediction?',
        choices: [
          { label: 'A', text: 'Both develop depression at the same time because their shared genetic vulnerability determines outcomes' },
          { label: 'B', text: 'One individual develops depression after experiencing chronic work stress and social isolation, while the other maintains mental health through strong social support and effective coping' },
          { label: 'C', text: 'One individual develops depression because of a neurochemical imbalance that is independent of their social environment' },
          { label: 'D', text: 'Both individuals require the same pharmacological treatment regardless of their social circumstances' },
        ],
        correctAnswer: 'B',
        explanation: 'The biopsychosocial model: mental illness arises from INTERPLAY of biological, psychological, and social factors. Identical genetic vulnerability (same biology) → different outcomes depending on social factors (isolation vs. support) and psychological factors (coping). B captures this: same genes, different outcomes based on social and psychological factors. A — if genetics alone determined outcomes, identical vulnerability = identical outcome (pure biomedical model). C — a neurochemical imbalance independent of environment is the purely biomedical model. D — the biopsychosocial model would predict that treatment should address biological, psychological, AND social factors; identical pharmacological treatment ignores individual social context.',
        wrongAnswerExplanations: {
          A: 'If identical genetic vulnerability produced identical outcomes regardless of environment, this would support genetic determinism or the biomedical model — not the biopsychosocial model, which holds that social and psychological factors modulate biological risk.',
          C: 'A neurochemical imbalance independent of the social environment is the biomedical model (biology alone causes disease). The biopsychosocial model holds that social and psychological factors interact with biology.',
          D: 'The biopsychosocial model implies that treatment should address all three dimensions. Identical pharmacological treatment for everyone ignores the social and psychological contributors to illness.',
        },
        teachingPoint: 'Biopsychosocial model (Engel, 1977): challenge to biomedical model (disease = biological pathology only). Diathesis-stress model extension: genetic diathesis (vulnerability) + environmental stress = disorder. Same vulnerability + different environment → different outcomes. Clinical implication: treatment must address all three levels — medications (biology), psychotherapy (psychology), social support/social work (social).',
        relatedTopics: ['biopsychosocial model', 'Engel', 'diathesis-stress', 'gene-environment interaction', 'mental illness causation'],
      },
      {
        id: 'mcat3-ps-034',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p6',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'The DSM-5\'s definition requires that a mental disorder be associated with significant distress OR disability. Why is this criterion important?',
        choices: [
          { label: 'A', text: 'It ensures that any deviation from statistical norms is classified as a disorder' },
          { label: 'B', text: 'It allows mental disorders to be diagnosed without any psychological assessment' },
          { label: 'C', text: 'It limits the DSM-5 to diagnosing only disorders with biological causes' },
          { label: 'D', text: 'It prevents labeling as disorders behaviors or mental states that are unusual but do not impair functioning or cause suffering' },
        ],
        correctAnswer: 'D',
        explanation: 'The distress/disability criterion serves as a clinical significance requirement: it ensures that not every unusual mental state is pathologized. Some cognitions or behaviors may be statistically unusual but not impair the person or cause suffering (e.g., extremely high intelligence, unconventional but adaptive beliefs). The criterion prevents over-diagnosis. D is correct. A — statistical rarity alone is not sufficient for a DSM disorder (statistical deviance criterion alone would pathologize giftedness). C — the DSM is atheoretical about causes; the distress/disability criterion does not limit diagnoses to biological causes. D — the DSM requires psychological/clinical assessment; the criterion does not bypass this.',
        wrongAnswerExplanations: {
          A: 'Statistical rarity alone is not a valid criterion for disorder. Many rare traits (genius, exceptional athleticism) are statistically unusual but not disorders. DSM criteria require clinical significance (distress/disability), not mere statistical deviance.',
          C: 'The DSM-5 is explicitly atheoretical about etiology — it does not require biological causes. The distress/disability criterion is about clinical significance, not causal mechanism.',
          B: 'Diagnosing a mental disorder requires clinical assessment by a qualified professional. The distress/disability criterion is part of the diagnostic criteria, not a mechanism for bypassing assessment.',
          
        },
        teachingPoint: 'DSM diagnostic criteria: syndrome of symptoms + clinical significance (distress or functional impairment) + not better explained by another condition (differential diagnosis). The clinical significance criterion addresses the concern that medicalizing normal human variation (e.g., shyness, grief) creates unnecessary diagnoses. Controversy: where to draw the line between normal variation and disorder (e.g., bereavement exclusion for depression in DSM-IV → removed in DSM-5).',
        relatedTopics: ['DSM-5 criteria', 'clinical significance criterion', 'distress and disability', 'over-diagnosis', 'mental disorder definition'],
      },
      {
        id: 'mcat3-ps-035',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p6',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'A researcher proposes that schizophrenia is purely a "brain disease" caused by excess dopamine and should be treated exclusively with D2 antagonists. Which evidence would most challenge this claim?',
        choices: [
          { label: 'A', text: 'Studies showing D2 antagonists effectively reduce positive symptoms in most patients' },
          { label: 'B', text: 'Evidence that social stress (e.g., urban living, immigration, racial discrimination) increases schizophrenia incidence, and that social support improves outcomes beyond what medication alone achieves' },
          { label: 'C', text: 'Twin studies showing a genetic heritability of ~80% for schizophrenia' },
          { label: 'D', text: 'Neuroimaging data showing enlarged ventricles and reduced gray matter in schizophrenic patients' },
        ],
        correctAnswer: 'B',
        explanation: 'The claim is a purely biomedical model (brain disease, dopamine, drug treatment alone). The biopsychosocial model would challenge this by showing that social and psychological factors influence both incidence and outcome. B provides two lines of evidence: (1) social stress increases incidence → purely biological causation is insufficient; (2) social support improves outcomes beyond medication → treatment should address social factors. This directly challenges the "purely a brain disease, treat exclusively with medication" claim. A — D2 antagonist effectiveness supports the biological hypothesis, not challenges it. C — high heritability supports genetic/biological factors. D — neuroimaging abnormalities support a neurobiological basis. All of A, C, D are consistent with the biomedical model.',
        wrongAnswerExplanations: {
          A: 'D2 antagonist effectiveness is consistent with the dopamine hypothesis and supports the biomedical model — it would strengthen, not challenge, the researcher\'s claim.',
          C: 'High heritability (~80%) supports a strong genetic (biological) component — consistent with the biomedical model. It challenges purely environmental theories, not the biomedical model.',
          D: 'Enlarged ventricles and reduced gray matter are neurobiological findings that support the "brain disease" framing — consistent with the biomedical model.',
        },
        teachingPoint: 'Evidence for social factors in schizophrenia: (1) urban living doubles risk — social density, stress exposure; (2) immigrants (especially second-generation) have higher rates — social exclusion, discrimination; (3) expressed emotion (EE) in family environments predicts relapse; (4) psychosocial interventions (CBT, family therapy, supported employment) improve outcomes. This supports biopsychosocial over purely biomedical. Dopamine hypothesis is necessary but insufficient: D2 blockers don\'t cure schizophrenia, and many patients have residual symptoms and social disability.',
        relatedTopics: ['biopsychosocial vs biomedical', 'schizophrenia social factors', 'dopamine hypothesis limitations', 'social stress and psychosis', 'expressed emotion'],
      },
      {
        id: 'mcat3-ps-036',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p6',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'The DSM-5 transitioned from a categorical multiaxial system to a dimensional approach. What does this mean for diagnosis?',
        choices: [
          { label: 'A', text: 'Diagnoses now require laboratory blood tests to confirm the presence of a disorder' },
          { label: 'B', text: 'The DSM-5 eliminated all categorical diagnoses in favor of personality trait profiles' },
          { label: 'C', text: 'Mental disorders are now grouped by genetic cause rather than symptom clusters' },
          { label: 'D', text: 'Clinicians rate symptom severity on a continuum rather than simply categorizing disorders as present or absent' },
        ],
        correctAnswer: 'D',
        explanation: 'The passage states: DSM-5 "rates symptom severity rather than simply categorizing presence or absence." A dimensional approach treats mental disorders as existing on a continuum — from no symptoms to mild to moderate to severe — rather than as binary (either you have it or you don\'t). D is correct. A — DSM diagnoses remain clinical/behavioral; no biological tests exist for most DSM diagnoses. C — DSM-5 is descriptive and atheoretical about etiology (including genetic cause); it uses symptom clusters, not genetic groupings. D — DSM-5 did NOT eliminate categorical diagnoses; it moved toward dimensionality while retaining categorical structure for most conditions.',
        wrongAnswerExplanations: {
          A: 'No blood tests or biomarkers are used to confirm DSM-5 diagnoses. Mental disorder diagnoses are based on clinical assessment of symptoms, duration, and functional impairment.',
          C: 'DSM-5 is explicitly atheoretical — it does not organize disorders by etiology (biological, genetic, or otherwise). RDoC (Research Domain Criteria) is a separate NIMH initiative that groups disorders by biological/neural dimensions, but it is not the DSM.',
          B: 'DSM-5 retains categorical diagnoses for most conditions (e.g., major depressive disorder, schizophrenia, bipolar disorder). Section III of DSM-5 contains an "Alternative Model for Personality Disorders" with dimensional traits, but this has not replaced categorical diagnoses entirely.',
          
        },
        teachingPoint: 'DSM-5 dimensional approach: for many disorders, specifiers indicate severity (mild/moderate/severe). Example: major depressive episode severity specifiers. The dimensional approach aligns with research showing that many "disorders" are on continua with normal variation. Contrast with RDoC: NIH initiative that bypasses DSM categories and studies transdiagnostic dimensions (e.g., fear circuits, reward processing) tied to neural mechanisms. The dimensional DSM-5 approach is a step toward RDoC thinking but within a still-categorical framework.',
        relatedTopics: ['DSM-5 dimensional', 'categorical vs dimensional', 'symptom severity rating', 'mental disorder classification', 'RDoC'],
      },
    ],
  },

  // ─── P/S Passage 7: Learning — Conditioning and Observational Learning ─────────
  {
    id: 'f3-ps-p7',
    sectionId: 'psych-soc',
    title: 'Classical Conditioning, Operant Conditioning, and Observational Learning',
    passageText: `Ivan Pavlov\'s classical conditioning paradigm demonstrated that a neutral stimulus (NS) paired with an unconditioned stimulus (US) that naturally evokes an unconditioned response (UR) will come to elicit a conditioned response (CR) after sufficient pairings. The NS, once conditioned, becomes the conditioned stimulus (CS). Key phenomena include: acquisition (initial learning); extinction (CS presented without US → CR weakens); spontaneous recovery (after extinction, rest period → CR reappears at reduced strength); stimulus generalization (stimuli similar to CS also elicit CR); and stimulus discrimination (responding to CS but not to similar stimuli through differential conditioning).

B.F. Skinner\'s operant conditioning framework holds that behavior is shaped by its consequences. Reinforcers increase the probability of a behavior; punishers decrease it. Positive operations add a stimulus; negative operations remove a stimulus. Thus: positive reinforcement (add reward → behavior increases), negative reinforcement (remove aversive stimulus → behavior increases), positive punishment (add aversive → behavior decreases), and negative punishment (remove reward → behavior decreases). Schedules of reinforcement affect response patterns: continuous reinforcement produces fast acquisition but rapid extinction; intermittent schedules (fixed ratio, variable ratio, fixed interval, variable interval) are more resistant to extinction. Variable ratio schedules produce the highest, most persistent response rates.

Albert Bandura\'s social learning (observational learning, or modeling) theory demonstrated that behavior can be acquired by watching others (models) without direct reinforcement. Vicarious reinforcement (model is rewarded → observer more likely to imitate) and vicarious punishment (model is punished → observer less likely to imitate) influence learning. Bandura\'s four processes: attention, retention, reproduction, and motivation (ARRM).`,
    figures: [],
    questions: [
      {
        id: 'mcat3-ps-037',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p7',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'A child who was bitten by a black dog (US) becomes afraid (UR) of all black dogs and also of black cats. This extension of the fear response to cats represents:',
        choices: [
          { label: 'A', text: 'Extinction — the CS is repeatedly presented without the US' },
          { label: 'B', text: 'Stimulus discrimination — the child has learned to distinguish dogs from cats' },
          { label: 'C', text: 'Stimulus generalization — the conditioned response extends to stimuli similar to the original CS' },
          { label: 'D', text: 'Spontaneous recovery — the fear response reappears after a rest period' },
        ],
        correctAnswer: 'C',
        explanation: 'Stimulus generalization: after conditioning to a CS (black dog), stimuli similar to the CS (black cats) also elicit the CR (fear). The more similar the new stimulus is to the CS, the stronger the generalized CR. C is correct. A — extinction is presenting the CS (black dog) repeatedly without the US (bite) → fear decreases. B — stimulus discrimination would mean the child ONLY fears black dogs, not cats (learned to distinguish them). D — spontaneous recovery is the return of an extinguished CR after a rest period, not extension to new stimuli.',
        wrongAnswerExplanations: {
          A: 'Extinction is the gradual weakening of the CR when the CS is presented without the US. The question describes generalization to a new stimulus, not weakening of the original CR.',
          B: 'Stimulus discrimination is the opposite of generalization: the child would only fear black dogs and NOT respond to cats (differential responding based on stimulus features). Generalization is non-discriminant spreading of the CR.',
          D: 'Spontaneous recovery is the reappearance of an extinguished CR after a rest period, not the extension of a current CR to new stimuli.',
        },
        teachingPoint: 'Generalization gradient: CR strength decreases as stimulus similarity to the original CS decreases. Black cats > gray cats (more similar to original) in terms of generalization. Therapy applications: systematic desensitization uses extinction (CS without US) to reduce phobias; stimulus discrimination training helps limit fear to the specific feared object. Little Albert (Watson & Raynor, 1920): conditioned fear of white rat generalized to white rabbit, fur coat, Santa Claus beard.',
        relatedTopics: ['stimulus generalization', 'classical conditioning', 'conditioned fear', 'CS CR US UR', 'generalization gradient'],
      },
      {
        id: 'mcat3-ps-038',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p7',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'A parent removes a child\'s weekly allowance (a privilege) every time the child argues at home. The child\'s arguing behavior decreases over time. This is an example of:',
        choices: [
          { label: 'A', text: 'Positive punishment — adding an aversive stimulus to decrease arguing' },
          { label: 'B', text: 'Negative reinforcement — removing an aversive stimulus to increase a behavior' },
          { label: 'C', text: 'Negative punishment — removing a reward to decrease arguing' },
          { label: 'D', text: 'Positive reinforcement — adding a reward to increase arguing' },
        ],
        correctAnswer: 'C',
        explanation: 'Analysis: the allowance (a reward/positive stimulus) is REMOVED when the child argues. This removal decreases arguing. Negative punishment = removing a positive stimulus → behavior decreases. "Negative" = stimulus is taken away; "punishment" = behavior decreases. C is correct. A — positive punishment adds an aversive stimulus (e.g., scolding). B — negative reinforcement removes an aversive stimulus to INCREASE a behavior (e.g., taking medicine to stop headache pain → medicine use increases). D — positive reinforcement adds a reward to INCREASE a behavior.',
        wrongAnswerExplanations: {
          A: 'Positive punishment: ADD an aversive stimulus → behavior decreases (e.g., adding scolding, adding a chore as consequence for arguing). Here, a reward is being REMOVED, not an aversive stimulus added.',
          B: 'Negative reinforcement: REMOVE an aversive stimulus → behavior INCREASES (e.g., fastening seatbelt removes irritating alarm → seatbelt behavior increases). Here, behavior DECREASES, so this is punishment, not reinforcement.',
          D: 'Positive reinforcement: ADD a reward → behavior INCREASES. Arguing decreases in this scenario, so the consequence is punishment, not reinforcement.',
        },
        teachingPoint: 'Operant conditioning 2×2: add/remove × increase/decrease behavior. Positive reinforcement: add reward → behavior ↑. Negative reinforcement: remove aversive → behavior ↑. Positive punishment: add aversive → behavior ↓. Negative punishment (response cost): remove reward → behavior ↓. Common confusions: "negative reinforcement" ≠ punishment (it still increases behavior). Examples of negative reinforcement: taking ibuprofen removes pain → ibuprofen use ↑; fastening seatbelt removes alarm → seatbelt use ↑; avoiding a difficult coworker removes stress → avoidance ↑.',
        relatedTopics: ['negative punishment', 'operant conditioning', 'positive vs negative', 'reinforcement vs punishment', 'response cost'],
      },
      {
        id: 'mcat3-ps-039',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p7',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'Why do variable ratio reinforcement schedules produce the highest and most persistent response rates, while continuous reinforcement produces rapid extinction?',
        choices: [
          { label: 'A', text: 'With continuous reinforcement, the absence of a reward immediately signals non-reinforcement; with variable ratio, omission of a reward may just be the unpredictable inter-reinforcement interval — making it slow to conclude extinction' },
          { label: 'B', text: 'Variable ratio schedules reinforce every response, making each response maximally satisfying' },
          { label: 'C', text: 'Variable ratio schedules are the least cognitively demanding, so responses are easier to produce' },
          { label: 'D', text: 'Continuous reinforcement produces satiation (boredom with reward) faster, reducing motivation' },
        ],
        correctAnswer: 'A',
        explanation: 'The partial reinforcement extinction effect (PREE): with continuous reinforcement (CRF), every non-reinforced response is a clear signal that extinction has begun → organism detects extinction quickly → fast extinction. With variable ratio (VR), the organism is accustomed to going many responses without reinforcement before getting a reward → when extinction begins, the absence of reward looks just like the normal inter-reinforcement gap → organism cannot readily detect extinction → continues responding → slow extinction + high rates during extinction. A captures this discrimination argument. A — VR does NOT reinforce every response; it is the opposite of CRF. C — cognitive demand is not the mechanism for schedule effects. D — satiation may be a minor factor but is not the primary mechanism; VR produces high rates well after satiation would predict decline.',
        wrongAnswerExplanations: {
          C: 'Cognitive demand is not the theoretical account of schedule effects. The PREE is explained by discriminability of extinction (how readily the organism can detect the transition from reinforcement to extinction).',
          D: 'Satiation could reduce motivation after many rewards in quick succession (e.g., eating one hundred candies in a row). However, this is not the primary mechanism explaining rapid CRF extinction and high VR rates, especially in non-consumable reward paradigms.',
          B: 'Variable ratio does NOT reinforce every response — it reinforces after an unpredictable average number of responses (e.g., VR-10: on average, every 10 responses, but sometimes after 1, sometimes after 25). CRF reinforces every response.',
        },
        teachingPoint: 'Reinforcement schedules: Fixed Ratio (FR) = reinforce after fixed number of responses; scallop pattern (pause after reinforcement). Variable Ratio (VR) = reinforce after variable number; high, steady rate; most resistant to extinction; gambling analogy. Fixed Interval (FI) = reinforce first response after fixed time; scallop pattern. Variable Interval (VI) = first response after variable time; moderate, steady rate. PREE: partial/intermittent schedules → more resistant to extinction than CRF because organism cannot easily discriminate extinction from normal inter-reinforcement intervals.',
        relatedTopics: ['variable ratio schedule', 'partial reinforcement extinction effect', 'PREE', 'schedule of reinforcement', 'resistance to extinction'],
      },
      {
        id: 'mcat3-ps-040',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p7',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'In Bandura\'s social learning theory, what is vicarious punishment?',
        choices: [
          { label: 'A', text: 'Being directly punished for a behavior performed in public' },
          { label: 'B', text: 'A punishment that affects multiple people simultaneously' },
          { label: 'C', text: 'Punishing a model to train the observer to avoid a behavior' },
          { label: 'D', text: 'Observing a model being punished for a behavior, which reduces the observer\'s likelihood of imitating that behavior' },
        ],
        correctAnswer: 'D',
        explanation: 'The passage defines vicarious punishment: "model is punished → observer less likely to imitate." Vicarious = experienced indirectly, through observing another. The observer learns from the model\'s consequences without being directly punished. D is correct. A — direct punishment is not vicarious. C — punishing the model specifically "to train" the observer is a description of the procedure, not the definition; B better captures the definition and mechanism. D — group punishment is not what "vicarious" means in learning theory.',
        wrongAnswerExplanations: {
          A: 'Direct punishment is when the organism itself is punished for performing the behavior. Vicarious punishment is indirect — the observer sees someone ELSE punished and reduces their own behavior accordingly.',
          C: 'Although this describes a way to use vicarious punishment deliberately, it does not define vicarious punishment itself. The definition is the phenomenon that observing another\'s punishment reduces the observer\'s behavior.',
          B: '"Vicarious" in learning theory specifically means indirect — through observation of another\'s experience. It has nothing to do with the number of people affected simultaneously.',
          
        },
        teachingPoint: 'Bandura\'s Bobo doll experiment (1961): children observed adult models act aggressively toward a Bobo doll (inflatable clown). Children who observed the model being rewarded showed more aggression (vicarious reinforcement); those who observed the model punished showed less (vicarious punishment); those who saw no consequence were intermediate. Demonstrates: learning without direct reinforcement (cognition mediates). Social cognitive theory: behavior, environment, and personal/cognitive factors interact (reciprocal determinism).',
        relatedTopics: ['vicarious punishment', 'observational learning', 'Bandura', 'social learning theory', 'Bobo doll'],
      },
      {
        id: 'mcat3-ps-041',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p7',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'A clinician uses systematic desensitization to treat a patient with a spider phobia. The patient first learns relaxation techniques, then is gradually exposed to increasingly spider-related stimuli while maintaining relaxation. Which classical conditioning principle does this treatment most directly employ?',
        choices: [
          { label: 'A', text: 'Stimulus generalization — the relaxation response generalizes to all spiders' },
          { label: 'B', text: 'Spontaneous recovery — the extinguished fear response will return briefly but then remain absent' },
          { label: 'C', text: 'Counterconditioning and extinction — the CS (spider) is now paired with an incompatible response (relaxation) instead of the CR (fear), and the CS is presented without the original US' },
          { label: 'D', text: 'Shaping — the patient is reinforced for successive approximations to tolerating spiders' },
        ],
        correctAnswer: 'C',
        explanation: 'Systematic desensitization uses two classical conditioning principles: (1) extinction — the CS (spider) is presented without the US (no actual biting, no harm occurs) → fear CR extinguishes; (2) counterconditioning — the CS is now paired with a new, incompatible response (relaxation via progressive muscle relaxation or similar), establishing relaxation as a new CR. The relaxation response is incompatible with the fear CR — one cannot be simultaneously deeply relaxed and intensely fearful. C is correct. A — stimulus generalization is the unintended spread of CR to new stimuli; here, the goal is to create a new CR (relaxation) to the CS, not to generalize. C — spontaneous recovery is an issue clinicians must address (patient may show return of fear after a gap), not the treatment principle employed. D — shaping is an operant conditioning procedure (reinforcing successive approximations); systematic desensitization is a classical conditioning procedure.',
        wrongAnswerExplanations: {
          A: 'Stimulus generalization is the spread of a conditioned response to similar stimuli — an unintended classical conditioning phenomenon, not the treatment mechanism. Systematic desensitization targets specific extinction and counterconditioning.',
          D: 'Shaping is an operant conditioning technique — reinforcing successive approximations toward a target behavior (e.g., teaching a dog to roll over). Systematic desensitization uses classical conditioning (CS-US pairing), not reinforcement of approximations.',
          B: 'Spontaneous recovery is a classical conditioning phenomenon (extinguished CR returns after a rest period) that is a challenge to overcome, not a treatment principle. Clinicians may need booster sessions to prevent spontaneous recovery.',
        },
        teachingPoint: 'Systematic desensitization (Wolpe): developed from reciprocal inhibition theory — relaxation response inhibits fear response. Steps: (1) relaxation training; (2) hierarchy construction (least → most anxiety-provoking spider stimuli); (3) gradual exposure while relaxed. Extinction component: CS without US → fear extinguishes. Counterconditioning: CS paired with relaxation → relaxation becomes new CR. Evidence-based for phobias, PTSD, OCD. Contrast with flooding/implosion: immediate full exposure to feared CS (pure extinction, no counterconditioning).',
        relatedTopics: ['systematic desensitization', 'counterconditioning', 'extinction phobia', 'classical conditioning therapy', 'reciprocal inhibition'],
      },
    ],
  },

  // ─── P/S Passage 8: Theories of Motivation and Emotion ───────────────────────
  {
    id: 'f3-ps-p8',
    sectionId: 'psych-soc',
    title: 'Motivation Theories and the Relationship Between Arousal and Performance',
    passageText: `Motivation refers to internal processes that direct, energize, and sustain behavior toward goals. Several theories have been proposed to explain motivated behavior. Drive reduction theory (Hull) proposes that physiological needs create unpleasant drives, and behavior is motivated to reduce these drives and restore homeostasis. Incentive theory emphasizes external stimuli (incentives) that attract or repel behavior — the reward\'s pull, not the drive\'s push. Arousal theory holds that humans seek an optimal level of arousal; too little (boredom) and too much (anxiety) reduce performance.

The Yerkes-Dodson law captures the relationship between arousal and performance: performance on a task is best at intermediate levels of arousal (inverted U-shaped function). Critically, the optimal arousal level depends on task complexity: simple tasks are performed best at higher arousal; complex, cognitively demanding tasks are performed best at lower arousal. Easterbrook\'s cue utilization hypothesis explains this: high arousal narrows attention to a small subset of available cues. For simple tasks, this narrowing eliminates distractors and focuses on task-relevant cues (helpful). For complex tasks, the narrowing eliminates both distractor AND task-relevant cues that are needed for sophisticated performance (harmful).

Abraham Maslow\'s hierarchy of needs proposes that needs form a pyramid: physiological (food, water, shelter) → safety → love/belonging → esteem → self-actualization (realizing one\'s full potential). Lower-level deficiency needs must be met before higher-level growth needs become motivating. Self-determination theory (Deci and Ryan) distinguishes intrinsic motivation (inherent enjoyment of the activity) from extrinsic motivation (performing for external rewards or to avoid punishment) and proposes three basic psychological needs: competence, autonomy, and relatedness.`,
    figures: [],
    questions: [
      {
        id: 'mcat3-ps-042',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p8',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'According to the Yerkes-Dodson law and Easterbrook\'s cue utilization hypothesis, a surgeon performing a highly complex procedure under extreme deadline pressure (high arousal) would be expected to:',
        choices: [
          { label: 'A', text: 'Perform worse because high arousal narrows attention too much, eliminating task-relevant cues needed for complex decision-making' },
          { label: 'B', text: 'Perform better than at moderate arousal because high arousal increases available physical energy' },
          { label: 'C', text: 'Perform the same as at moderate arousal because surgical skill is automatic and not affected by arousal level' },
          { label: 'D', text: 'Perform better because high arousal specifically enhances performance on cognitively demanding tasks' },
        ],
        correctAnswer: 'A',
        explanation: 'Complex tasks (surgery) require broad attention to many task-relevant cues — subtle tissue changes, multiple anatomical relationships, team communication. High arousal → attention narrows (Easterbrook\'s cue utilization) → eliminates some task-relevant cues → performance declines. The inverted U for complex tasks has a lower optimal arousal than for simple tasks. A is correct. A — physical energy increase does not compensate for loss of task-relevant cue processing in cognitively complex tasks. C — surgical skill involves many components that are NOT fully automatic (especially novel situations, complex decisions); automatic skills are less affected by arousal, but complex surgery is not purely automatic. D — high arousal specifically HARMS performance on complex tasks (Yerkes-Dodson inverse for complex tasks).',
        wrongAnswerExplanations: {
          C: 'While some components of expert surgical technique become automatic (proceduralized), surgery remains cognitively complex, especially under novel or unexpected conditions. Automated skills are less sensitive to arousal effects, but complex intraoperative decisions are not fully automated.',
          D: 'High arousal HELPS simple tasks (by eliminating distractors while maintaining focus on the single relevant cue). It HURTS complex tasks (by eliminating cues that are needed for sophisticated multi-element performance).',
          B: 'The Yerkes-Dodson law predicts that for complex tasks, high arousal HURTS performance. Physical energy availability is not the bottleneck — attentional capacity is.',
        },
        teachingPoint: 'Yerkes-Dodson law: inverted U relationship between arousal and performance. Optimal arousal is lower for complex tasks than simple tasks. Easterbrook\'s explanation: high arousal → attentional narrowing → eliminates peripheral/extraneous cues. For simple tasks, extraneous = distractors (benefit). For complex tasks, extraneous = also task-relevant peripheral cues needed for good performance (harm). Clinical/sports application: pre-performance anxiety management — athletes/surgeons need moderate arousal, not maximal arousal.',
        relatedTopics: ['Yerkes-Dodson law', 'Easterbrook cue utilization', 'arousal and performance', 'task complexity', 'inverted U'],
      },
      {
        id: 'mcat3-ps-043',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p8',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'According to Maslow\'s hierarchy, which need would take highest priority for a person who is homeless and hungry?',
        choices: [
          { label: 'A', text: 'Esteem needs — wanting to feel respected by peers' },
          { label: 'B', text: 'Self-actualization — pursuing creative expression and personal growth' },
          { label: 'C', text: 'Love and belonging — seeking friends and intimate relationships' },
          { label: 'D', text: 'Physiological needs — seeking food and shelter' },
        ],
        correctAnswer: 'D',
        explanation: 'Maslow\'s hierarchy: lower-level deficiency needs are prepotent — they must be met before higher-level needs become motivating. Physiological needs (food, water, shelter) are at the base and are the highest priority when unmet. A homeless, hungry person\'s primary motivation is meeting these basic survival needs. D is correct. A (esteem) and B (self-actualization) are at the top of the hierarchy and would only become motivating once all lower needs are satisfied. C (love/belonging) is at level 3 — above physiological and safety, but the person whose physiological needs are unmet would prioritize those first.',
        wrongAnswerExplanations: {
          A: 'Esteem needs (self-esteem, recognition, respect) are level 4 in the hierarchy. They become motivating only after physiological, safety, and love/belonging needs are met.',
          B: 'Self-actualization is at the top of the hierarchy — the highest growth need, activated only when all deficiency needs below it are satisfied.',
          C: 'Love and belonging (social connection, friendship, intimacy) is level 3. For a person whose physiological needs (level 1) are unmet, the hierarchy predicts that physiological needs dominate motivation.',
        },
        teachingPoint: 'Maslow\'s 5 levels (bottom to top): (1) Physiological (food, water, shelter, sleep), (2) Safety (security, employment, health), (3) Love/Belonging (friendship, intimacy, family), (4) Esteem (self-esteem, achievement, recognition), (5) Self-Actualization (realizing potential, creativity, purpose). Deficiency needs (1–4): motivated by a lack. Growth needs (5): growth is always possible, never fully "satisfied." Critiques: not universal (some prioritize love over safety; creative people may self-actualize despite unmet lower needs); hierarchy is culturally influenced.',
        relatedTopics: ['Maslow hierarchy', 'physiological needs', 'deficiency vs growth needs', 'need prepotency', 'motivation hierarchy'],
      },
      {
        id: 'mcat3-ps-044',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p8',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'Self-determination theory predicts that adding external rewards (paying people for performing an activity they previously did for free) will sometimes REDUCE intrinsic motivation. This is called the overjustification effect. Which prediction does self-determination theory make about when external rewards are LEAST damaging to intrinsic motivation?',
        choices: [
          { label: 'A', text: 'When the reward is informational (provides feedback about competence) rather than controlling (implies external control over behavior)' },
          { label: 'B', text: 'When the reward is very large, providing strong external justification for the behavior' },
          { label: 'C', text: 'When the reward is given unexpectedly after a behavior has already been performed intrinsically' },
          { label: 'D', text: 'When the reward is given on a variable ratio schedule to maximize persistence' },
        ],
        correctAnswer: 'A',
        explanation: 'SDT (Deci and Ryan) distinguishes two types of external rewards: (1) controlling rewards (contingent on performing the task, with the implicit message "I am doing this for the reward") → undermine autonomy → reduce intrinsic motivation; (2) informational rewards (provide competence feedback, e.g., "You did that excellently") → enhance feelings of competence → support intrinsic motivation. The overjustification effect occurs with controlling rewards. Informational rewards are least damaging (often protective of intrinsic motivation). A is correct. A — large rewards increase external attribution, increasing overjustification. C — unexpected rewards (not made salient before task) are less damaging than expected rewards because they are less likely to shift attribution from internal to external; this is TRUE, but B more precisely captures SDT\'s theoretical prediction. D — variable ratio schedules are irrelevant to SDT\'s theory about intrinsic motivation.',
        wrongAnswerExplanations: {
          C: 'Unexpected rewards are less harmful than expected tangible rewards (because they were not anticipated before the task, the task itself was started for intrinsic reasons). However, B more precisely captures SDT\'s theoretical mechanism: the key distinction is informational vs. controlling, which applies whether the reward is expected or not.',
          D: 'Variable ratio schedules are from operant conditioning theory (about persistence and extinction) — they are not the theoretical basis for SDT\'s predictions about intrinsic vs. extrinsic motivation.',
          B: 'Large rewards increase the salience of external justification ("I\'m doing this for the money"), shifting attribution from intrinsic to extrinsic. This INCREASES the overjustification effect — it would be most damaging, not least.',
        },
        teachingPoint: 'Overjustification effect (Deci, 1971): rewarding people for intrinsically interesting activities reduces intrinsic motivation. Mechanism: external reward provides an external attribution for behavior → person infers "I must be doing this for the reward, not because I enjoy it" → intrinsic motivation declines when reward is removed. SDT: informational rewards (feedback about skill) → enhance competence → support autonomy → protect intrinsic motivation. Controlling rewards (performance-contingent payment) → undermine autonomy → damage intrinsic motivation. Application: bonus structures and performance pay can reduce intrinsic motivation for creative work.',
        relatedTopics: ['overjustification effect', 'SDT intrinsic motivation', 'informational vs controlling rewards', 'Deci Ryan', 'external reward intrinsic motivation'],
      },
      {
        id: 'mcat3-ps-045',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p8',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'Drive reduction theory predicts that organisms are motivated to:',
        choices: [
          { label: 'A', text: 'Maximize arousal by seeking exciting, novel stimuli' },
          { label: 'B', text: 'Reduce internal tensions (drives) created by physiological needs, returning to homeostasis' },
          { label: 'C', text: 'Seek external incentives regardless of internal physiological state' },
          { label: 'D', text: 'Self-actualize by pursuing growth and meaning beyond basic needs' },
        ],
        correctAnswer: 'B',
        explanation: 'Hull\'s drive reduction theory: physiological needs (food deprivation, dehydration) create unpleasant drive states → behavior is directed toward need satisfaction → drive reduces → homeostasis restored. B is correct. A — maximizing arousal is arousal theory (or sensation-seeking perspective), not drive reduction. C — seeking external incentives regardless of internal state is incentive theory (emphasizes reward pull, not drive push). D — self-actualization is Maslow\'s growth need concept, not drive reduction theory.',
        wrongAnswerExplanations: {
          A: 'Arousal theory predicts that organisms seek an optimal level of arousal. Drive reduction theory focuses on reducing biological needs back to homeostatic baseline — not maximizing arousal.',
          C: 'Incentive theory emphasizes the attractiveness of external stimuli (incentives) as the motivating force, separate from internal drive states. Drive reduction theory emphasizes internal physiological need as the primary motivator.',
          D: 'Self-actualization is Maslow\'s concept — the highest need in his hierarchy, about realizing one\'s full potential. Drive reduction theory (Hull) focuses on biological drives and homeostasis, not psychological self-fulfillment.',
        },
        teachingPoint: 'Motivation theories: Drive reduction (Hull) — internal biological need → drive → behavior to reduce drive → homeostasis. Incentive theory — external rewards/incentives pull behavior (explains non-homeostatic motivated behaviors like pursuing luxury goods). Arousal theory — optimal arousal level sought. Maslow\'s hierarchy — hierarchical needs from physiological to self-actualization. SDT — autonomy, competence, relatedness needs. Each theory captures different aspects of motivation; none fully explains all motivated behavior.',
        relatedTopics: ['drive reduction theory', 'Hull', 'homeostasis', 'biological drive', 'motivation theories'],
      },
      {
        id: 'mcat3-ps-046',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p8',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'Drive reduction theory struggles to explain why humans sometimes engage in sensation-seeking behaviors (e.g., extreme sports, eating when not hungry). Which alternative theory best addresses this limitation?',
        choices: [
          { label: 'A', text: 'Drive reduction theory — sensation-seeking increases homeostatic drive to later recover' },
          { label: 'B', text: 'Arousal theory — humans seek optimal arousal levels; sensation-seeking elevates arousal to optimize performance' },
          { label: 'C', text: 'Instinct theory — sensation-seeking is an evolved, hardwired instinct' },
          { label: 'D', text: 'Incentive theory — external stimuli (thrilling experiences, pleasurable taste) attract behavior independent of homeostatic drive' },
        ],
        correctAnswer: 'D',
        explanation: 'Drive reduction theory assumes all motivation reduces biological needs. Sensation-seeking (skydiving) does NOT reduce a homeostatic deficit — it may even increase physiological arousal. Eating tasty food when not hungry is not driven by a caloric deficit. Incentive theory explains these: the external incentive (thrill, taste) pulls behavior regardless of internal drive state. D is correct. B — arousal theory could also explain sensation-seeking (optimizing arousal), but incentive theory more specifically addresses the "pull" of external stimuli like food taste and thrilling experiences. C — instinct theory (McDougall) proposes innate drives but is largely dismissed in modern psychology for circular reasoning. D is the best supported alternative.',
        wrongAnswerExplanations: {
          A: 'Drive reduction theory cannot straightforwardly explain sensation-seeking by claiming it creates later drive recovery — this is ad hoc and not part of the original theory. The question asks which alternative theory best addresses the limitation.',
          B: 'Arousal theory (Berlyne) does explain sensation-seeking as seeking optimal arousal. However, it does not well explain eating palatable food when not hungry (excess food is not about optimizing arousal level). Incentive theory covers both cases more parsimoniously.',
          C: 'Instinct theory assigns innate labels to behaviors but does not explain the mechanism or make specific predictions. It is considered largely circular (we "seek thrills" because we have a thrill instinct). Modern psychology largely rejected pure instinct theory for humans.',
        },
        teachingPoint: 'Incentive theory: external stimuli acquire incentive salience — the ability to attract and motivate approach behavior. Berridge\'s wanting vs. liking distinction: dopamine mediates "wanting" (incentive motivation) separately from "liking" (hedonic impact). This explains why drug addicts "want" drugs even when they no longer "like" them (wanting system sensitized, liking system blunted). Incentive salience explains appetitive behaviors that violate homeostasis: craving sweets when sated, novelty-seeking, risk-taking.',
        relatedTopics: ['incentive theory', 'sensation seeking', 'drive reduction limitations', 'external stimuli motivation', 'wanting vs liking'],
      },
    ],
  },

  // ─── P/S Passage 9: Research Methods in Psychology ───────────────────────────
  {
    id: 'f3-ps-p9',
    sectionId: 'psych-soc',
    title: 'Research Design, Validity, and Statistical Inference in Psychological Research',
    passageText: `Psychological research employs several study designs, each with different strengths and limitations. The experiment is the only design that can establish causation: the researcher randomly assigns participants to conditions, manipulates the independent variable (IV), and measures the dependent variable (DV), while controlling extraneous variables. Random assignment distributes individual differences across conditions, isolating the IV\'s effect. Without random assignment, the design is quasi-experimental and cannot rule out confounds.

Correlational studies measure relationships between variables (correlation coefficient r, ranging from –1 to +1) but cannot establish causation — they may reflect a third variable (a common cause) or reverse causation. Longitudinal studies follow the same participants over time and can detect change and temporal order, but attrition (dropout of participants over time) threatens internal validity. Cross-sectional studies compare different age groups at a single time point, but cohort effects (different historical experiences) may confound apparent developmental differences.

Internal validity refers to the degree to which the study design supports causal inference (i.e., that the IV caused the DV effect). Threats to internal validity include selection bias, history effects (external events co-occurring with the intervention), maturation, testing effects, and regression to the mean. External validity (generalizability) refers to whether results apply to other populations, settings, and times.

Statistical significance (p < 0.05) indicates the probability of obtaining results at least as extreme as observed, assuming the null hypothesis is true. It does not indicate the size or practical importance of an effect. Effect size (e.g., Cohen\'s d, r) measures the magnitude of the effect. Power (1 − β) is the probability of detecting a true effect when it exists, and is increased by larger sample size, larger effect size, and higher alpha levels.`,
    figures: [],
    questions: [
      {
        id: 'mcat3-ps-047',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p9',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Research and statistics',
        foundationalConcept: 'FC 10',
        scientificSkill: 'Skill 3',
        difficulty: 'medium',
        question: 'A researcher finds a positive correlation (r = 0.65) between hours of television watched per day and childhood obesity rates. Which of the following is the most appropriate conclusion?',
        choices: [
          { label: 'A', text: 'Watching television causes childhood obesity' },
          { label: 'B', text: 'Childhood obesity causes children to watch more television' },
          { label: 'C', text: 'There is a strong positive association between TV watching and obesity, but causal direction cannot be determined from correlational data' },
          { label: 'D', text: 'r = 0.65 means that TV watching explains 65% of the variance in childhood obesity' },
        ],
        correctAnswer: 'C',
        explanation: 'Correlational studies cannot establish causation. The passage states: correlations "may reflect a third variable (a common cause) or reverse causation." Three interpretations: (1) TV watching → obesity (sedentary behavior + food advertising); (2) obesity → TV watching (less physical activity, more indoor sedentary time); (3) third variable → both (e.g., low socioeconomic status → both less healthy food and more TV access). C correctly limits the conclusion to an association with no causal inference. A and B both assert causation in one direction. D — r² = proportion of variance explained; r = 0.65 means r² ≈ 0.42 (42% of variance), not 65%.',
        wrongAnswerExplanations: {
          A: 'Correlation cannot establish causation. To conclude TV causes obesity, a randomized experiment (randomly assigning children to TV-watching conditions) would be needed.',
          B: 'Reverse causation is possible (obese children may watch more TV) but correlation alone cannot determine which direction the causation runs, or whether causation exists at all.',
          D: 'The proportion of variance explained by a correlation is r² (the coefficient of determination), not r. r = 0.65 → r² = 0.4225 → TV watching is associated with ~42% of the variance in obesity, not 65%.',
        },
        teachingPoint: 'Correlation ≠ causation. Three explanations for a correlation: A causes B, B causes A, or C causes both. r² = proportion of variance explained (0.65² ≈ 0.42 = 42%). Correlation strength: |r| < 0.3 = weak; 0.3–0.5 = moderate; > 0.5 = strong. Sign indicates direction (positive = both increase together; negative = one increases as the other decreases). To establish causation: random assignment, manipulation of IV, control of confounds — all hallmarks of the true experiment.',
        relatedTopics: ['correlation causation', 'third variable', 'reverse causation', 'r-squared', 'correlational design'],
      },
      {
        id: 'mcat3-ps-048',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p9',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Research and statistics',
        foundationalConcept: 'FC 10',
        scientificSkill: 'Skill 3',
        difficulty: 'medium',
        question: 'A study comparing math performance between 20-year-olds and 60-year-olds at a single time point finds that 20-year-olds score significantly higher. A researcher concludes that math ability declines with age. What is the main threat to this conclusion?',
        choices: [
          { label: 'A', text: 'Cohort effect — the two age groups grew up in different historical eras and may have received different quality or quantity of math education' },
          { label: 'B', text: 'Attrition — the 60-year-olds who completed the study are not representative' },
          { label: 'C', text: 'Regression to the mean — extreme scores at baseline are expected to be less extreme at follow-up' },
          { label: 'D', text: 'Selection bias — the 20-year-olds were recruited from elite universities' },
        ],
        correctAnswer: 'A',
        explanation: 'This is a cross-sectional study (comparing different age groups at one time point). The passage states: "cohort effects (different historical experiences) may confound apparent developmental differences." Today\'s 60-year-olds (born ~1966) attended school during a different era than today\'s 20-year-olds (born ~2006) — different math curricula, computer exposure, educational resources. The difference in math scores might reflect cohort differences in education, not age-related cognitive decline. A is correct. A — attrition is a threat in longitudinal studies (dropout over time), not cross-sectional studies. C — regression to the mean applies when participants are selected for extreme scores and later re-tested. D — selection bias from elite university recruiting is a different confound (and would only apply if 20-year-olds were selectively recruited, which the question does not specify).',
        wrongAnswerExplanations: {
          C: 'Regression to the mean occurs when extreme scorers are selected at one time point and then retested — their scores regress toward the group mean. This does not apply to a straightforward cross-sectional age comparison.',
          D: 'Selection bias from university recruitment is a potential external validity threat (samples not representative of the general population), but the specific internal validity threat unique to cross-sectional age comparisons is cohort effects.',
          B: 'Attrition threatens longitudinal studies, where participants drop out over time leading to a non-representative remaining sample. Cross-sectional studies do not follow the same participants over time — the 60-year-olds in the study were never the same cohort as the 20-year-olds.',
        },
        teachingPoint: 'Longitudinal vs. cross-sectional: Longitudinal (same people, different time points) — detects within-person change; threats: attrition, practice effects, history effects. Cross-sectional (different people, same time point) — faster and cheaper; threat: cohort effects confound age differences with generational differences. Cohort example: today\'s elderly scored lower on IQ tests partly because they had less education than younger cohorts (Flynn effect — IQ scores have risen over generations due to environmental changes).',
        relatedTopics: ['cohort effect', 'cross-sectional design', 'longitudinal vs cross-sectional', 'internal validity', 'developmental research designs'],
      },
      {
        id: 'mcat3-ps-049',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p9',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Research and statistics',
        foundationalConcept: 'FC 10',
        scientificSkill: 'Skill 3',
        difficulty: 'easy',
        question: 'A study finds p = 0.03. Which of the following is the most accurate interpretation?',
        choices: [
          { label: 'A', text: 'There is a 3% probability that the null hypothesis is true' },
          { label: 'B', text: 'There is a 3% probability of observing results at least as extreme as these, if the null hypothesis were true' },
          { label: 'C', text: 'The effect size is large and practically important' },
          { label: 'D', text: 'The results will replicate 97% of the time in future studies' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage defines p-value: "the probability of obtaining results at least as extreme as observed, assuming the null hypothesis is true." P = 0.03 means: if the null hypothesis (no effect) were true, there is a 3% probability of observing a result this extreme by chance. B is correct. A — the p-value does NOT indicate the probability that H₀ is true (this is a common misconception). C — statistical significance does not indicate effect size or practical importance; a tiny effect can be statistically significant with a large sample. D — p < 0.05 does not mean the result will replicate 97% of the time (the replication crisis shows many p < 0.05 findings fail to replicate).',
        wrongAnswerExplanations: {
          A: 'The p-value is NOT the probability that H₀ is true. It is the probability of the data given H₀. These are different conditional probabilities (P(data|H₀) ≠ P(H₀|data)).',
          C: 'Statistical significance (p value) is entirely separate from effect size. A p = 0.001 result in a study with n = 10,000 could have a trivially small effect size (e.g., Cohen\'s d = 0.05). Statistical significance also depends on sample size.',
          D: 'The p-value does not predict replication rate. Replication probability depends on true effect size, sample size, and research methodology. Many p < 0.05 findings fail to replicate (replication crisis in psychology).',
        },
        teachingPoint: 'P-value misconceptions (MCAT-tested): (1) P = probability H₀ is true — FALSE; (2) P = probability result was due to chance — partially correct framing but technically "the data were generated under H₀"; (3) P < 0.05 means the effect is important — FALSE (importance = effect size + real-world context); (4) P < 0.05 guarantees replication — FALSE. Effect size measures: Cohen\'s d = (M₁ − M₂) / SD pooled; r = correlation coefficient; η² = proportion variance explained. Practical vs. statistical significance distinction is critical.',
        relatedTopics: ['p-value interpretation', 'statistical significance', 'null hypothesis', 'effect size', 'p-value misconceptions'],
      },
      {
        id: 'mcat3-ps-050',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p9',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Research and statistics',
        foundationalConcept: 'FC 10',
        scientificSkill: 'Skill 3',
        difficulty: 'medium',
        question: 'Random assignment in an experiment:',
        choices: [
          { label: 'A', text: 'Ensures that the sample is representative of the general population' },
          { label: 'B', text: 'Controls for confounding variables by distributing participant characteristics equally across conditions on average' },
          { label: 'C', text: 'Increases external validity by selecting diverse participants' },
          { label: 'D', text: 'Eliminates the need for a control group' },
        ],
        correctAnswer: 'B',
        explanation: 'Random assignment (not to be confused with random selection/sampling) distributes participant characteristics (age, baseline scores, personality, health status) randomly across conditions. On average, this balances known and unknown confounds across groups, allowing the researcher to attribute any group difference to the IV manipulation. B is correct. A — random sampling ensures representative samples; random assignment does not address representativeness. C — external validity is enhanced by random sampling and diverse recruitment, not random assignment per se. D — random assignment distributes participants into groups but does not eliminate the need for a control group; without a control condition, there is no baseline to compare the experimental condition against.',
        wrongAnswerExplanations: {
          A: 'Random sampling (selecting participants from the population randomly) addresses representativeness. Random assignment is the process of distributing existing participants across conditions — it does not make the sample more representative of the general population.',
          C: 'External validity is about generalizability of findings to other populations and settings. It is enhanced by diverse, representative sampling. Random assignment improves INTERNAL validity (causal inference), not external validity.',
          D: 'Random assignment determines which participants go to which condition. The experiment still needs a control (comparison) condition to establish a baseline against which to measure the effect of the IV. Without a control group, there is no causal inference possible even with random assignment.',
        },
        teachingPoint: 'Random assignment vs. random selection: Random selection = randomly choosing who participates from the population → enhances external validity (representativeness). Random assignment = randomly distributing participants to conditions → enhances internal validity (causal inference). Both are random, but they serve different purposes. True experiment: random assignment + IV manipulation + DV measurement + control group. Quasi-experiment: lacks random assignment → cannot rule out confounds → cannot establish causation.',
        relatedTopics: ['random assignment', 'internal validity', 'confounding variables', 'random assignment vs sampling', 'experimental design'],
      },
      {
        id: 'mcat3-ps-051',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p9',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Research and statistics',
        foundationalConcept: 'FC 10',
        scientificSkill: 'Skill 3',
        difficulty: 'hard',
        question: 'A researcher conducts a study with very small sample size and finds p = 0.04. Another study with a large sample size tests the same hypothesis and finds p = 0.04 but a much smaller effect size. Which conclusion correctly interprets this pattern?',
        choices: [
          { label: 'A', text: 'The large-sample study has detected a statistically significant but possibly trivially small effect; statistical significance does not equal practical importance' },
          { label: 'B', text: 'The small-sample study has more statistical power because its p-value required a larger true effect to reach significance' },
          { label: 'C', text: 'Both studies have equal power because they have the same p-value (0.04)' },
          { label: 'D', text: 'The small-sample study has better external validity because it was more difficult to achieve significance' },
        ],
        correctAnswer: 'A',
        explanation: 'With a large sample size, statistical power is high — even tiny, practically insignificant effects can produce p < 0.05. The large-sample study found the same p-value but a much smaller effect size: this illustrates that statistical significance and practical importance are independent. A very large sample can detect a difference so small it has no real-world meaning. A is correct. A — the small-sample study having p = 0.04 means it had to have a relatively large true effect to reach significance (small samples have low power → only large effects are detectable). The large-sample study has MORE power. C — power is determined by sample size, effect size, and alpha — not by the p-value directly. Same p does not mean same power. D — external validity is about generalizability to other populations; difficulty of achieving significance does not relate to external validity.',
        wrongAnswerExplanations: {
          C: 'Power is determined by: sample size (larger = more power), effect size (larger = more power), and alpha level (higher = more power). The p-value is the outcome of a hypothesis test, not an indicator of power. Two studies can have the same p-value with vastly different power and effect sizes.',
          D: 'External validity (generalizability) is related to sample representativeness, diversity of settings, and replication — not difficulty of achieving statistical significance. Difficult-to-achieve significance does not make results more generalizable.',
          B: 'The small-sample study has LOWER statistical power — small samples are less likely to detect true effects (higher type II error rate). Achieving p = 0.04 with a small sample DOES suggest the true effect is large (only large effects can be detected). But "more power" is incorrect — it has less power. The large-sample study has more power.',
        },
        teachingPoint: 'Power and sample size: as n increases, even trivial effects become statistically significant. This is why large clinical trials (n = 50,000) often find "statistically significant" differences between treatments that are clinically meaningless. Solution: report effect sizes (Cohen\'s d, NNT) alongside p-values. MCAT: know that statistical significance ≠ practical/clinical significance. Type I error (α): rejecting a true H₀ (false positive); Type II error (β): failing to reject a false H₀ (false negative); Power = 1 − β = probability of detecting a true effect.',
        relatedTopics: ['statistical vs practical significance', 'effect size', 'statistical power', 'large sample significance', 'type I type II error'],
      },
    ],
  },
]
