import type { MCATPassage } from '../types'

// Form 3 P/S — Passages 1–5
// 5 passages × 6 questions = 30 questions (IDs mcat3-ps-001 through mcat3-ps-030)

export const psPassages3_01to05: MCATPassage[] = [
  // ─── P/S Passage 1: Sensation and Perception — Signal Detection Theory ────────
  {
    id: 'f3-ps-p1',
    sectionId: 'psych-soc',
    title: 'Signal Detection Theory and Perceptual Thresholds',
    passageText: `Sensation is the process by which sensory organs transduce physical stimuli into neural signals; perception is the brain\'s interpretation of these signals. Classical psychophysics established the concept of absolute threshold — the minimum stimulus intensity detectable 50% of the time — and the just noticeable difference (JND) — the minimum change in stimulus intensity detectable. Weber\'s Law holds that the JND is a constant fraction (Weber fraction, k) of the original stimulus: ΔI/I = k. Fechner\'s Law extends this, proposing that perceived sensation (S) is proportional to the logarithm of stimulus intensity: S = k log(I).

Signal detection theory (SDT) challenged classical approaches by demonstrating that detection is not simply a matter of sensory threshold but also of decision criteria (bias). In a detection task, an observer may respond "yes, I detect the signal" or "no" when a signal may or may not be present. Four outcomes arise: hit (signal present, response "yes"), miss (signal present, response "no"), false alarm (no signal, response "yes"), and correct rejection (no signal, response "no"). The receiver operating characteristic (ROC) curve plots hit rate against false alarm rate across varying criteria.

SDT distinguishes sensitivity (d-prime, d′) from response bias (β). D-prime reflects the true ability to discriminate signal from noise; β reflects the observer\'s criterion for responding "yes." A liberal criterion (low β) increases both hits and false alarms; a conservative criterion (high β) decreases both. SDT has applications in medical imaging, eyewitness testimony, and quality control.`,
    figures: [],
    questions: [
      {
        id: 'mcat3-ps-001',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p1',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 6',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'Weber\'s Law states that the JND (ΔI) is proportional to the original stimulus intensity (I). Which scenario best illustrates this principle?',
        choices: [
          { label: 'A', text: 'You can detect the addition of 1 gram to a 10-gram weight and also 1 gram to a 100-gram weight' },
          { label: 'B', text: 'You can detect the addition of 1 gram to a 10-gram weight, but need 10 additional grams to notice a change in a 100-gram weight' },
          { label: 'C', text: 'You can detect the addition of 10 grams to a 10-gram weight and also 10 grams to a 100-gram weight' },
          { label: 'D', text: 'You can detect any change in a 100-gram weight because heavier weights have lower absolute thresholds' },
        ],
        correctAnswer: 'B',
        explanation: 'Weber\'s Law: ΔI/I = k (constant). If k = 0.1 (10%) for weight discrimination: ΔI for a 10g weight = 0.1 × 10 = 1g; ΔI for a 100g weight = 0.1 × 100 = 10g. You need a proportionally larger difference (10g, not 1g) to notice a change in the heavier weight. B illustrates this correctly. A — constant absolute JND (1g) regardless of base weight contradicts Weber\'s Law. C — constant absolute JND (10g) also contradicts (works for 100g but not 10g). D — absolute threshold decreases with weight is false and not Weber\'s Law.',
        wrongAnswerExplanations: {
          A: 'If 1g is detectable at both 10g and 100g, the JND is constant (1g) — this contradicts Weber\'s Law, which predicts the JND increases proportionally with base intensity.',
          C: 'If 10g is detectable at both 10g and 100g base weights, this implies a 100% Weber fraction at 10g (10/10 = 1.0) but only 10% at 100g (10/100 = 0.1) — not a constant fraction.',
          D: 'Absolute threshold is the minimum detectable intensity, not a property that changes with stimulus weight in the way described. Weber\'s Law is about change detection, not absolute threshold.',
        },
        teachingPoint: 'Weber\'s Law: ΔI/I = k (constant fraction). Heavier, brighter, louder stimuli require proportionally larger changes to notice. Weber fractions vary by sense: weight ~2%, light ~8%, sound frequency ~0.3%. Fechner extended this to a logarithmic scale for perceived intensity.',
        relatedTopics: ['Weber\'s Law', 'JND', 'sensory thresholds', 'psychophysics', 'ΔI/I'],
      },
      {
        id: 'mcat3-ps-002',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p1',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 6',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'In signal detection theory, which outcome occurs when a signal is present but the observer responds "no"?',
        choices: [
          { label: 'A', text: 'Hit' },
          { label: 'B', text: 'False alarm' },
          { label: 'C', text: 'Correct rejection' },
          { label: 'D', text: 'Miss' },
        ],
        correctAnswer: 'D',
        explanation: 'Signal present + response "no" = Miss (the observer failed to detect the signal). The four SDT outcomes: Hit (signal present + "yes"), Miss (signal present + "no"), False Alarm (no signal + "yes"), Correct Rejection (no signal + "no"). D is correct.',
        wrongAnswerExplanations: {
          A: 'A hit is signal present + response "yes" — the observer correctly detected the signal.',
          B: 'A false alarm is no signal + response "yes" — the observer detected a signal that was not there.',
          C: 'A correct rejection is no signal + response "no" — the observer correctly identified the absence of a signal.',
        },
        teachingPoint: 'SDT 2×2 matrix: columns = signal present/absent; rows = response yes/no. Hits and correct rejections are accurate; misses and false alarms are errors. Medical application: mammography screening — radiologist must balance sensitivity (hit rate) against specificity (1 − false alarm rate). Liberal criterion: more hits but more false alarms. Conservative criterion: fewer false alarms but more misses.',
        relatedTopics: ['signal detection theory', 'miss', 'hit false alarm correct rejection', 'SDT outcomes'],
      },
      {
        id: 'mcat3-ps-003',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p1',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 6',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'A radiologist examining mammograms decides to flag any image that has even a slight suspicious finding (liberal criterion). How does this affect the SDT outcomes?',
        choices: [
          { label: 'A', text: 'Both hit rate and false alarm rate increase' },
          { label: 'B', text: 'Hit rate increases but false alarm rate decreases' },
          { label: 'C', text: 'Hit rate decreases and false alarm rate decreases' },
          { label: 'D', text: 'D-prime (sensitivity) increases because the radiologist is more willing to detect cancer' },
        ],
        correctAnswer: 'A',
        explanation: 'A liberal criterion (low β) means the observer is quick to respond "yes." When a signal is present, they are more likely to detect it (higher hit rate). When no signal is present, they are also more likely to say "yes" (higher false alarm rate). Both rates increase with a liberal criterion. A is correct. B inverts the false alarm effect. C — a conservative criterion decreases both rates. D — d-prime is sensitivity (ability to discriminate signal from noise), which is independent of criterion. Changing criterion does not change d-prime.',
        wrongAnswerExplanations: {
          B: 'A liberal criterion increases both hits AND false alarms — the observer is more willing to say "yes" regardless of signal presence. It does not selectively increase hits while decreasing false alarms.',
          C: 'Decreasing both rates is a conservative criterion (high β). Liberal criterion = more "yes" responses = higher rates for both hit and false alarm.',
          D: 'D-prime is a measure of perceptual sensitivity (how well the observer can separate signal from noise) — it is independent of response criterion. Changing criterion shifts β but not d-prime. Only improving the observer\'s sensory ability or increasing signal-to-noise ratio improves d-prime.',
        },
        teachingPoint: 'ROC curve: plots hit rate vs. false alarm rate as criterion varies. Liberal criterion: upper right of ROC curve (high hit rate + high false alarm rate). Conservative criterion: lower left (low hit rate + low false alarm rate). D-prime is the AUC-related measure — orthogonal to criterion. Clinical tradeoffs: missing cancer (miss, false negative) vs. unnecessary biopsy (false alarm). Context determines optimal criterion (β).',
        relatedTopics: ['liberal criterion', 'hit rate', 'false alarm rate', 'SDT criterion', 'ROC curve'],
      },
      {
        id: 'mcat3-ps-004',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p1',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 6',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'Fechner\'s Law states S = k log(I). What does the logarithmic relationship imply about how perceived sensation changes as physical intensity increases?',
        choices: [
          { label: 'A', text: 'Equal increases in physical intensity produce equal increases in perceived sensation' },
          { label: 'B', text: 'Equal increases in physical intensity produce progressively smaller increases in perceived sensation (diminishing returns)' },
          { label: 'C', text: 'Equal increases in physical intensity produce progressively larger increases in perceived sensation' },
          { label: 'D', text: 'Perceived sensation decreases as physical intensity increases beyond the absolute threshold' },
        ],
        correctAnswer: 'B',
        explanation: 'The logarithm of a number grows slowly as the number increases: log(10) = 1, log(100) = 2, log(1000) = 3. So going from intensity 10 to 100 (10-fold increase) adds 1 unit of sensation, and going from 100 to 1000 (another 10-fold increase) also adds only 1 unit of sensation. Equal log-scale increases in intensity produce equal sensation increments, but on a linear intensity scale, each additional unit of sensation requires progressively larger intensity increases. B captures this: equal linear increases in intensity produce diminishing sensation returns. A describes a linear relationship (not logarithmic). C describes an accelerating relationship. D is false — sensation increases monotonically with intensity under Fechner\'s Law.',
        wrongAnswerExplanations: {
          A: 'A linear relationship (S = kI) would produce equal sensation increments for equal intensity increments. The logarithmic function grows more slowly than linear — each additional intensity unit above a high base adds less sensation.',
          C: 'A power law with exponent > 1 (Stevens\' Power Law for some modalities) could produce accelerating sensation. Fechner\'s log function decelerates (diminishing returns).',
          D: 'Fechner\'s Law predicts sensation increases monotonically with log(I). Sensation does not decrease above absolute threshold (unless a ceiling/saturation effect occurs, which is not Fechner\'s Law).',
        },
        teachingPoint: 'Fechner\'s Law: S = k log(I). Diminishing returns: each 10-fold increase in intensity adds a fixed increment to sensation (1 log unit). This is why the decibel scale for sound and the Richter scale for earthquakes are logarithmic — they match human perceptual compression. Stevens\' Power Law (S = kIⁿ) modified this: n < 1 gives diminishing returns (cold, brightness); n > 1 gives accelerating perception (electric shock). MCAT tests Fechner\'s Law specifically.',
        relatedTopics: ['Fechner\'s Law', 'logarithmic sensation', 'diminishing returns', 'psychophysics', 'Stevens Power Law'],
      },
      {
        id: 'mcat3-ps-005',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p1',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 6',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'In eyewitness testimony research, SDT predicts that instructing witnesses to report identifications only when they are highly confident (strict instruction) versus any time a person looks familiar (lenient instruction) will produce different outcomes. Which prediction is most consistent with SDT?',
        choices: [
          { label: 'A', text: 'Strict instruction increases d-prime by improving discriminability between the perpetrator and fillers' },
          { label: 'B', text: 'Strict instruction shifts the criterion (β) to be more conservative, reducing both correct identifications and false identifications' },
          { label: 'C', text: 'Lenient instruction increases d-prime by encouraging more attempts to detect the perpetrator' },
          { label: 'D', text: 'Strict instruction selectively increases hit rate without affecting false identification rate' },
        ],
        correctAnswer: 'B',
        explanation: 'Confidence instruction affects criterion (β), not d-prime. Strict instruction ("only identify if highly confident") = conservative criterion → fewer "yes" responses → lower hit rate AND lower false identification rate. Lenient instruction = liberal criterion → more hits AND more false identifications. D-prime depends on the witness\'s actual memory quality and ability to discriminate the perpetrator from innocent fillers — not on the instruction. B correctly predicts the SDT consequence. A — criterion change does not change d-prime. C — lenient instruction shifts criterion, not d-prime. D — changing criterion always affects both hit AND false alarm rates in the same direction.',
        wrongAnswerExplanations: {
          A: 'D-prime is determined by memory quality (encoding, retention) — how well the witness can discriminate the perpetrator\'s face from distractors. Confidence instructions change the criterion, not the underlying discriminability.',
          C: 'Lenient instruction shifts criterion (liberal = lower β), increasing both correct and incorrect identifications. It does not change d-prime (the underlying discriminability). Only improving memory encoding or presenting a better lineup would improve d-prime.',
          D: 'SDT predicts that criterion changes always affect hit rate and false alarm rate in the same direction. A conservative criterion (strict instruction) decreases BOTH. You cannot selectively increase hits without also increasing false alarms by simply changing criterion.',
        },
        teachingPoint: 'SDT in eyewitness testimony: d-prime = memory quality (discriminability); β = response criterion. Strict instruction → conservative β → fewer correct identifications AND fewer false IDs. Lenient → liberal β → more correct AND false IDs. The optimal lineup procedure considers both. Lineup administrators who don\'t know who the suspect is ("double-blind") can\'t inadvertently signal liberal criteria to witnesses — reducing false identifications.',
        relatedTopics: ['SDT eyewitness', 'criterion vs sensitivity', 'd-prime', 'β criterion', 'lineup identification'],
      },
      {
        id: 'mcat3-ps-006',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p1',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 6',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'Absolute threshold is defined as the minimum stimulus intensity detectable:',
        choices: [
          { label: 'A', text: '100% of the time under ideal conditions' },
          { label: 'B', text: '50% of the time in detection experiments' },
          { label: 'C', text: '75% of the time across repeated trials' },
          { label: 'D', text: 'At least once in a lifetime of exposures' },
        ],
        correctAnswer: 'B',
        explanation: 'The absolute threshold is classically defined as the stimulus intensity detected 50% of the time. This is the psychophysical definition from classical detection experiments (method of limits, method of constant stimuli). At this intensity, the stimulus is detected on half the trials, giving a probabilistic definition rather than an all-or-nothing one. B is correct.',
        wrongAnswerExplanations: {
          A: '100% detection would be a suprathreshold stimulus. The absolute threshold is specifically defined at the 50% detection point.',
          C: '75% is sometimes used as an alternative criterion in two-alternative forced choice procedures, but the classical definition is 50%.',
          D: 'Lifetime exposure is not a psychophysical criterion. Absolute threshold is a statistical property of detection performance in controlled experiments.',
        },
        teachingPoint: 'Absolute threshold = 50% detection criterion in psychophysical measurement. Methods: method of limits (ascending/descending stimulus until response change), method of constant stimuli (many intensities presented randomly), method of adjustment (subject adjusts until just detectable). SDT challenges the idea of a fixed threshold — detection depends on both sensory sensitivity and criterion (bias).',
        relatedTopics: ['absolute threshold', 'psychophysics', '50% detection', 'method of limits', 'sensory threshold'],
      },
    ],
  },

  // ─── P/S Passage 2: Memory — Encoding, Storage, and Retrieval ────────────────
  {
    id: 'f3-ps-p2',
    sectionId: 'psych-soc',
    title: 'Levels of Processing and Memory Consolidation',
    passageText: `Craik and Lockhart\'s levels-of-processing (LOP) framework (1972) proposed that memory is not merely a function of rehearsal duration but of the depth (elaborateness) of encoding. Shallow processing — attending to surface features like letter case or rhyme — produces weaker memory traces than deep processing, which involves semantic analysis (meaning, associations, self-reference). The self-reference effect is particularly robust: information processed in relation to oneself shows exceptionally strong memory.

Memory storage is not uniform. Working memory (WM) has limited capacity (~7 ± 2 items in Miller\'s classical estimate, revised to ~4 chunks in more recent work) and short duration (~20 seconds without rehearsal). Long-term memory (LTM) includes explicit (declarative) memory — episodic (personal events, "autobiography") and semantic (general knowledge) — and implicit memory, including procedural (motor skills), priming, and classical conditioning. Declarative memories depend on the medial temporal lobe (hippocampus, entorhinal cortex); implicit memories are mediated by distinct systems (cerebellum for motor conditioning, basal ganglia for procedural skills, amygdala for emotional conditioning).

Memory consolidation occurs in two phases: synaptic consolidation (minutes to hours, involving protein synthesis and LTP) and systems consolidation (weeks to years, during which hippocampus-dependent memories are gradually transferred to neocortex). Retrograde amnesia following hippocampal damage shows a temporal gradient — recent memories are lost; remote memories are spared — consistent with systems consolidation.`,
    figures: [],
    questions: [
      {
        id: 'mcat3-ps-007',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p2',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'According to levels-of-processing theory, which encoding strategy would produce the best long-term retention of a word list?',
        choices: [
          { label: 'A', text: 'Counting the number of letters in each word' },
          { label: 'B', text: 'Identifying whether each word rhymes with "cat"' },
          { label: 'C', text: 'Generating a sentence using each word in a meaningful context' },
          { label: 'D', text: 'Repeating each word aloud five times (maintenance rehearsal)' },
        ],
        correctAnswer: 'C',
        explanation: 'LOP theory: deeper semantic processing produces stronger memory traces. Generating a meaningful sentence = semantic encoding (processing meaning and context) = deep processing → best retention. A (counting letters) = structural processing (shallow). B (rhyme) = phonological processing (slightly deeper than structural but still shallow). D (repetition) = maintenance rehearsal, which extends information in WM briefly but does not deepen encoding significantly. Elaborative rehearsal (connecting information to meaning, prior knowledge, or self) is more effective than maintenance rehearsal. C is correct.',
        wrongAnswerExplanations: {
          A: 'Counting letters is structural (physical feature) processing — the shallowest level in LOP. It produces weaker memory traces than semantic processing.',
          B: 'Rhyme detection involves phonological processing — deeper than structural but shallower than semantic. Better than A but not as effective as semantic processing (C).',
          D: 'Maintenance rehearsal (repetition without elaboration) keeps information in working memory temporarily but does not necessarily create strong long-term traces. Elaborative rehearsal (adding meaning, connections) is more effective for LTM formation.',
        },
        teachingPoint: 'LOP hierarchy (shallowest → deepest): structural (physical features) → phonological (sound) → semantic (meaning) → self-referential (relating to oneself). Clinical application: mnemonic strategies use deep encoding (mnemonics create elaborate semantic connections). Spacing effect and testing effect also improve retention by requiring retrieval, which strengthens memory traces.',
        relatedTopics: ['levels of processing', 'deep vs shallow encoding', 'semantic encoding', 'elaborative rehearsal', 'Craik and Lockhart'],
      },
      {
        id: 'mcat3-ps-008',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p2',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'A patient with hippocampal damage loses the ability to form new declarative memories but retains procedural skills learned before the injury. Which memory system is spared?',
        choices: [
          { label: 'A', text: 'Episodic memory' },
          { label: 'B', text: 'Semantic memory' },
          { label: 'C', text: 'Implicit/procedural memory (dependent on basal ganglia and cerebellum)' },
          { label: 'D', text: 'Working memory (dependent on prefrontal cortex)' },
        ],
        correctAnswer: 'C',
        explanation: 'The passage states: declarative memories depend on the medial temporal lobe (hippocampus); implicit memories (procedural skills) are mediated by basal ganglia (skills) and cerebellum (motor conditioning). A patient with hippocampal damage cannot form new declarative memories (episodic and semantic) but spares implicit memory systems. This mirrors the famous case of HM (Henry Molaison), who lost hippocampi and could not form new episodic memories but learned new motor skills normally. C is correct. A and B (episodic and semantic) are declarative — both would be impaired. D — working memory is relatively spared in hippocampal amnesia; the question asks what is specifically "spared" as an intact system.',
        wrongAnswerExplanations: {
          A: 'Episodic memory is explicitly declarative and depends on the hippocampus. It would be impaired by hippocampal damage — new episodic memories cannot form (anterograde amnesia).',
          B: 'Semantic memory (general knowledge) also depends on hippocampal-mediated consolidation. While remote semantic memories may be somewhat spared, new semantic learning is impaired.',
          D: 'Working memory (dependent on prefrontal cortex) is relatively intact in hippocampal amnesia. However, the question contrasts declarative versus procedural/implicit systems, and the most directly relevant "spared" system is procedural/implicit memory, not just WM.',
        },
        teachingPoint: 'HM (Henry Molaison): bilateral hippocampal removal → anterograde amnesia (cannot form new declarative memories) + retrograde amnesia (some past episodic memories lost) + SPARED implicit memory (learned mirror-tracing task normally, with no memory of practicing). Demonstrates the dissociation: hippocampus = declarative; basal ganglia + cerebellum = implicit/procedural.',
        relatedTopics: ['hippocampal amnesia', 'procedural memory', 'declarative vs implicit', 'HM case', 'anterograde amnesia'],
      },
      {
        id: 'mcat3-ps-009',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p2',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'A patient suffers a traumatic brain injury affecting the hippocampus. She cannot recall personal events from the past year but has intact memories from childhood. This pattern is called:',
        choices: [
          { label: 'A', text: 'Anterograde amnesia with a temporal gradient sparing remote memories' },
          { label: 'B', text: 'Retrograde amnesia with a temporal gradient sparing remote memories — consistent with systems consolidation' },
          { label: 'C', text: 'Proactive interference — old memories blocking recall of new events' },
          { label: 'D', text: 'Infantile amnesia — inability to recall memories from infancy' },
        ],
        correctAnswer: 'B',
        explanation: 'The patient cannot recall events from the PAST YEAR (recent retrograde amnesia) but has intact childhood memories (remote memories spared). This is retrograde amnesia with a temporal gradient — consistent with Ribot\'s Law. The passage explains: "systems consolidation — remote memories are gradually transferred to neocortex, sparing them from hippocampal damage." Recent memories still depend on the hippocampus (not yet fully consolidated to neocortex) and are lost; remote memories (already consolidated to neocortex) are spared. B is correct. A — anterograde amnesia is inability to form NEW memories after injury (not recalling PRE-injury events). C — proactive interference is when old learning impairs new learning, unrelated to this scenario. D — infantile amnesia is inability to recall early childhood events (before age 3-4), not relevant here.',
        wrongAnswerExplanations: {
          A: 'Anterograde amnesia is the inability to form new memories AFTER the injury. The patient\'s deficit is in recalling pre-injury events (retrograde amnesia). The temporal gradient (recent lost, remote spared) specifically describes retrograde amnesia.',
          C: 'Proactive interference: previously learned information interferes with learning NEW information. This is about new learning impairment, not loss of past memories.',
          D: 'Infantile amnesia refers to the normal inability to recall events from the first 2-3 years of life. This patient cannot recall the past year, which is a different phenomenon.',
        },
        teachingPoint: 'Ribot\'s gradient / temporal gradient in retrograde amnesia: recent memories (still hippocampus-dependent) are lost; remote memories (consolidated to neocortex) are spared. This supports the systems consolidation hypothesis. Standard consolidation: hippocampus transfers memories to cortex over weeks-years. Multiple trace theory (alternative): hippocampus always involved in episodic memory retrieval regardless of age.',
        relatedTopics: ['retrograde amnesia', 'temporal gradient', 'systems consolidation', 'Ribot\'s Law', 'hippocampal consolidation'],
      },
      {
        id: 'mcat3-ps-010',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p2',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'Which of the following is an example of implicit memory?',
        choices: [
          { label: 'A', text: 'Recalling what you ate for breakfast yesterday' },
          { label: 'B', text: 'Knowing that Paris is the capital of France' },
          { label: 'C', text: 'Riding a bicycle without thinking consciously about each movement' },
          { label: 'D', text: 'Remembering a phone number long enough to dial it' },
        ],
        correctAnswer: 'C',
        explanation: 'Implicit memory is memory expressed without conscious recollection — it influences behavior without awareness. Procedural memory (riding a bike = motor skill) is a classic implicit memory: you perform the skill without being able to consciously articulate how you do it. C is correct. A — recalling breakfast yesterday = episodic memory (explicit, declarative). B — knowing Paris is the capital of France = semantic memory (explicit, declarative). D — phone number in WM = working memory (short-term, not long-term implicit).',
        wrongAnswerExplanations: {
          A: 'Episodic memory: personal events with contextual details (when, where, what). Declarative and explicit — requires conscious recall.',
          B: 'Semantic memory: general world knowledge, facts, concepts. Declarative and explicit — requires conscious recall.',
          D: 'Holding a phone number briefly = working memory (verbal rehearsal loop). Not implicit — the person is consciously aware of the information.',
        },
        teachingPoint: 'Implicit memory types: procedural (motor skills), priming (prior exposure affects later response without conscious awareness), classical conditioning, habituation/sensitization. All are non-declarative — expressed through behavior, not conscious recall. Contrast: explicit (declarative) = episodic + semantic, requires conscious retrieval effort, hippocampus-dependent.',
        relatedTopics: ['implicit memory', 'procedural memory', 'explicit vs implicit', 'declarative memory', 'motor skills'],
      },
      {
        id: 'mcat3-ps-011',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p2',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'A researcher proposes that sleep improves memory consolidation. Which experimental finding would most strongly support this claim?',
        choices: [
          { label: 'A', text: 'Participants who study and sleep perform better on recall tests than participants who study and stay awake for an equal time interval' },
          { label: 'B', text: 'Participants recall more items immediately after studying than after a delay' },
          { label: 'C', text: 'Disrupting REM sleep has no effect on procedural memory consolidation' },
          { label: 'D', text: 'Participants who study in the morning perform as well as participants who study at night' },
        ],
        correctAnswer: 'A',
        explanation: 'To support that sleep improves consolidation, a direct comparison between sleep and equivalent wake periods is needed. A shows: sleep group outperforms wake group after the same time interval — this cannot be explained by mere passage of time (both groups had equal time) and specifically implicates sleep. A is the strongest support. B — the forgetting curve shows recall decreases with delay, regardless of sleep — this supports forgetting, not specifically sleep consolidation. C — if disrupting REM has no effect on procedural memory, this would suggest REM is NOT important for procedural consolidation (if anything, it would challenge part of the consolidation hypothesis). D — no difference between morning and night study doesn\'t specifically test sleep consolidation.',
        wrongAnswerExplanations: {
          B: 'The finding that immediate recall exceeds delayed recall is the forgetting curve — it shows forgetting occurs over time but does not specifically implicate sleep as improving consolidation.',
          C: 'If REM disruption does NOT impair procedural memory, this evidence suggests REM sleep is NOT necessary for procedural consolidation — this weakens or is irrelevant to the sleep consolidation hypothesis.',
          D: 'Morning vs. night study comparison doesn\'t isolate sleep. Multiple variables could differ (circadian rhythm, fatigue, study context). This does not directly test sleep consolidation.',
        },
        teachingPoint: 'Sleep consolidation evidence: studies show that sleep within 24 hours of learning significantly improves retention vs. equivalent wake periods. Proposed mechanisms: slow-wave sleep (SWS) reactivates hippocampal memory traces → transfers to cortex; REM sleep may stabilize emotional memories and motor learning. The "sleep after learning" design (A) controls for time elapsed and isolates sleep as the active variable.',
        relatedTopics: ['sleep consolidation', 'REM sleep', 'memory reactivation', 'experimental design', 'sleep vs wake comparison'],
      },
      {
        id: 'mcat3-ps-012',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p2',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'The self-reference effect in memory refers to:',
        choices: [
          { label: 'A', text: 'The tendency to remember information about others better than information about oneself' },
          { label: 'B', text: 'Superior memory for information encoded in relation to the self (e.g., "Does this word describe you?") compared to other encoding conditions' },
          { label: 'C', text: 'The phenomenon where people remember their own mistakes more vividly than their successes' },
          { label: 'D', text: 'Enhanced memory for events that occur in the observer\'s presence' },
        ],
        correctAnswer: 'B',
        explanation: 'The self-reference effect: encoding information by asking whether it applies to oneself ("Does this word describe you?") produces better memory than structural, phonological, or even general semantic encoding. The self acts as an especially rich associative network — self-related processing is deeply elaborative and meaningful. B is correct. A inverts (self > other, not other > self). C — recall of mistakes vs. successes is related to self-esteem effects, not the self-reference effect as defined in LOP. D — being present during an event describes the encoding context effect (mood congruence, state-dependent memory), not self-reference.',
        wrongAnswerExplanations: {
          A: 'The self-reference effect shows that self-related processing produces BETTER memory for that information — not that information about others is remembered better.',
          C: 'The relation between remembering mistakes vs. successes involves self-esteem, mood congruence, and potentially the zeigarnik effect (unfinished tasks remembered better). This is not the self-reference effect.',
          D: 'Witnessing an event enhances episodic memory for it, but this is related to encoding richness and personal relevance (flashbulb memory context), not specifically the self-reference effect as operationalized in LOP experiments.',
        },
        teachingPoint: 'Self-reference effect: LOP ranking — structural < phonological < semantic < self-referential. "Judging whether a word describes you" produces strongest recall. Mechanism: self is a rich, well-organized schema — new information connected to self has many retrieval cues. Clinical application: memory therapy for depression often connects new positive information to self-schema to improve retention.',
        relatedTopics: ['self-reference effect', 'levels of processing', 'self-schema', 'encoding strategies', 'elaborative encoding'],
      },
    ],
  },

  // ─── P/S Passage 3: Social Cognition — Attribution and Cognitive Dissonance ──
  {
    id: 'f3-ps-p3',
    sectionId: 'psych-soc',
    title: 'Attribution Errors and Cognitive Dissonance',
    passageText: `Attribution theory examines how people explain the causes of behavior. Fritz Heider\'s foundational distinction contrasts internal (dispositional) attributions — explaining behavior by referring to the actor\'s traits, attitudes, or abilities — with external (situational) attributions — explaining behavior by environmental factors. Jones and Harris (1967) demonstrated the correspondence bias (also called the fundamental attribution error, FAE): observers overattribute behavior to internal dispositions even when they know the behavior is externally constrained (e.g., attributing a pro-Castro essay to genuine pro-Castro attitudes even when students were assigned to write it).

The actor-observer bias extends this: actors tend to make more situational attributions for their own behavior ("I was late because of traffic") while observers attribute the same behavior to the actor\'s disposition ("she is chronically late"). The self-serving bias adds an asymmetry: people attribute successes to internal causes (effort, ability) and failures to external causes (bad luck, unfair circumstances).

Leon Festinger\'s cognitive dissonance theory (1957) holds that holding two simultaneously inconsistent cognitions produces an aversive motivational state. Individuals are motivated to reduce dissonance by (1) changing one of the cognitions, (2) adding consonant cognitions, or (3) reducing the importance of one cognition. Dissonance effects are strongest when behavior is freely chosen (no external justification) and is difficult to reverse.`,
    figures: [],
    questions: [
      {
        id: 'mcat3-ps-013',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p3',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 8',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'The fundamental attribution error (FAE) is the tendency to:',
        choices: [
          { label: 'A', text: 'Overestimate situational factors and underestimate dispositional factors when explaining others\' behavior' },
          { label: 'B', text: 'Overestimate dispositional factors and underestimate situational factors when explaining others\' behavior' },
          { label: 'C', text: 'Attribute successes to internal causes and failures to external causes' },
          { label: 'D', text: 'Explain one\'s own behavior using more situational factors than others use for the same behavior' },
        ],
        correctAnswer: 'B',
        explanation: 'The FAE/correspondence bias: observers overestimate dispositional (internal) factors and underestimate situational (external) factors when explaining others\' behavior. The Jones and Harris example: attributing pro-Castro essay to genuine attitudes even when the assignment was externally mandated. B is correct. A inverts (situational overestimated, dispositional underestimated). C describes the self-serving bias. D describes the actor-observer bias (actors use situational attributions for their own behavior).',
        wrongAnswerExplanations: {
          A: 'This inverts the FAE. The FAE is overweighting DISPOSITIONAL factors when explaining others\' behavior — not overweighting situational.',
          C: 'The self-serving bias: attributes successes to internal (ability, effort) and failures to external (luck, situation). A separate bias from FAE.',
          D: 'The actor-observer asymmetry: actors use more situational attributions for their own behavior, while observers use more dispositional attributions for the same behavior. Not the same as FAE.',
        },
        teachingPoint: 'FAE/correspondence bias: in Western cultures, people systematically over-use dispositional explanations for others\' behavior. Why: salience (the person is the figure, situation is ground); insufficient adjustment from initial dispositional anchor; different access to situational information. Cross-cultural note: FAE is weaker in collectivist cultures (East Asian) where situational factors are more salient.',
        relatedTopics: ['fundamental attribution error', 'correspondence bias', 'dispositional attribution', 'Jones and Harris', 'attribution errors'],
      },
      {
        id: 'mcat3-ps-014',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p3',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 8',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'In Festinger and Carlsmith\'s classic dissonance experiment, participants who were paid $1 to tell a confederate the boring task was fun reported liking the task more than those paid $20. What explains this counterintuitive finding?',
        choices: [
          { label: 'A', text: 'Participants paid $1 had more positive interactions with the confederate, creating genuine enjoyment' },
          { label: 'B', text: 'Participants paid $20 had sufficient external justification for lying; $1 participants had insufficient justification, generating dissonance between "I lied" and "I am an honest person," which they reduced by deciding the task was actually enjoyable' },
          { label: 'C', text: 'Participants paid $20 were more invested in the experiment, making them more honest in reporting their actual (positive) attitudes' },
          { label: 'D', text: 'Participants paid $1 showed demand characteristics — they guessed the experiment\'s purpose and responded accordingly' },
        ],
        correctAnswer: 'B',
        explanation: 'Classic dissonance analysis: $20 payment = sufficient external justification (told the confederate the task was fun for $20 → "well, I lied for the money — my attitude toward the task can remain negative"). $1 payment = insufficient external justification → dissonance between the lie and self-image as honest → cannot justify lying for only $1 → must change the attitude ("actually, the task wasn\'t that bad") to resolve dissonance. Less external justification = more attitude change = more dissonance. B is correct. A — the interaction content was scripted; $1 group did not have genuinely more positive interactions. C inverts — $20 participants reported LOWER task enjoyment (they maintained their true negative attitude). D — demand characteristics would predict both groups show equal response bias.',
        wrongAnswerExplanations: {
          A: 'The experimental procedure was standardized — both groups had the same scripted interaction. The difference in reported enjoyment is attributed to dissonance reduction, not genuine enjoyment from a different interaction quality.',
          C: 'The $20 participants were NOT more honest in reporting enjoyment — they actually reported LOWER task enjoyment than the $1 group. This is the counterintuitive result the dissonance theory explains.',
          D: 'Demand characteristics would predict that both groups try to please the experimenter equally. The differential pattern ($1 > $20 enjoyment) is unlikely to be explained by demand characteristics alone.',
        },
        teachingPoint: 'Festinger-Carlsmith experiment: "induced compliance paradigm." Key principle: insufficient justification → dissonance → attitude change. More pressure/payment = less attitude change (external justification reduces dissonance). Applications: "foot-in-the-door" technique (small commitment → larger compliance), low-balling, hazing (suffering for joining a group makes the group seem more valuable). Dissonance requires: personal responsibility, freely chosen behavior, aversive consequences.',
        relatedTopics: ['cognitive dissonance', 'Festinger', 'induced compliance', 'insufficient justification', 'attitude change'],
      },
      {
        id: 'mcat3-ps-015',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p3',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 8',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'The actor-observer bias predicts that:',
        choices: [
          { label: 'A', text: 'Actors and observers make the same attributions for a given behavior' },
          { label: 'B', text: 'Actors attribute their own behavior to situational factors, while observers attribute the same behavior to the actor\'s dispositions' },
          { label: 'C', text: 'Actors attribute their own behavior to internal dispositions, while observers attribute the same behavior to situational factors' },
          { label: 'D', text: 'Observers always make more accurate attributions than actors' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage states: "actors tend to make more situational attributions for their own behavior while observers attribute the same behavior to the actor\'s disposition." A person who arrives late says "I was stuck in traffic" (situational); an observer says "she\'s always late" (dispositional). B is correct. A — the bias is specifically about the asymmetry between actors and observers. C inverts. D — accuracy is not the same as attribution pattern; neither is necessarily "more accurate."',
        wrongAnswerExplanations: {
          A: 'The actor-observer bias describes a systematic divergence between actor and observer attributions — not agreement.',
          C: 'This inverts the actor-observer bias. Actors use situational (external) attributions for their own behavior; observers use dispositional (internal) attributions for the actor\'s behavior.',
          D: 'The actor-observer bias describes a difference in attribution pattern, not a claim about relative accuracy. Actors may have privileged access to situational factors; observers may have privileged access to behavioral patterns across time. Neither is consistently more accurate.',
        },
        teachingPoint: 'Actor-observer asymmetry: perspective (seeing the situation vs. seeing the person as the figure) drives attribution. Actors SEE the situation (traffic, social pressure); observers SEE the person\'s behavior. Visual perspective hypothesis: looking at self from outside (filmed behavior) shifts attributions toward dispositional. Note: actor-observer bias is weaker for explaining others\' successes (then observers make more situational attributions to avoid envy).',
        relatedTopics: ['actor-observer bias', 'situational vs dispositional', 'attribution asymmetry', 'perspective effects'],
      },
      {
        id: 'mcat3-ps-016',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p3',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 8',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'A smoker who knows smoking causes cancer but continues to smoke might reduce cognitive dissonance by which of the following strategies?',
        choices: [
          { label: 'A', text: 'Quitting smoking (changing the dissonant behavior)' },
          { label: 'B', text: 'Deciding that the evidence linking smoking to cancer is exaggerated (adding consonant cognition by downplaying the threat)' },
          { label: 'C', text: 'Telling others about the health risks of smoking' },
          { label: 'D', text: 'Seeking out information confirming that smoking causes cancer' },
        ],
        correctAnswer: 'B',
        explanation: 'Cognitions: "I smoke" + "smoking causes cancer." These are dissonant. Dissonance reduction strategies: (1) change behavior (quit smoking — but hard to do), (2) change cognition (convince oneself the cancer link is overstated, or that "I won\'t get cancer"), (3) add consonant cognitions ("smoking relaxes me, which reduces stress — stress also causes cancer"). B represents changing a cognition (downplaying the cancer risk) — a classic real-world dissonance reduction. A — quitting would eliminate the dissonance but is the hardest option; also a valid answer, but B represents the classic cognitive rationalization. C — telling others about risks would increase the salience of the dissonant cognition, worsening dissonance. D — seeking confirming evidence of the harm would increase, not decrease, dissonance.',
        wrongAnswerExplanations: {
          A: 'Quitting smoking would eliminate the dissonant behavior — this is the most thorough solution but also the hardest. It is a valid dissonance reduction method. However, B is more illustrative of the cognitive rationalization mechanism central to dissonance theory (people often AVOID the hard behavioral change and rationalize instead).',
          C: 'Telling others about smoking risks would increase awareness and salience of the dissonant cognition, potentially increasing dissonance. This is not a dissonance reduction strategy.',
          D: 'Seeking confirming evidence that smoking IS harmful would strengthen the dissonant cognition, increasing rather than reducing dissonance. Confirmation bias might lead the smoker to seek information that smoking is NOT harmful, not confirming the harm.',
        },
        teachingPoint: 'Dissonance reduction in health behaviors: smokers, unhealthy eaters, sedentary individuals commonly use rationalization (cognitive change) rather than behavioral change. Dissonance theory predicts: the easier the behavioral change is to make, the more likely it is to be chosen; when behavior is hard to change, cognitive rationalization dominates. Health communication implication: simply providing risk information may not change behavior — addresses the cognitive but not the motivational dissonance dynamics.',
        relatedTopics: ['cognitive dissonance reduction', 'smoking rationalization', 'cognition change', 'health behavior', 'dissonance strategies'],
      },
      {
        id: 'mcat3-ps-017',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p3',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 8',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'The self-serving bias is illustrated by which of the following?',
        choices: [
          { label: 'A', text: 'A student who passed an exam says, "I did well because I studied hard"; a student who failed says, "The exam was unfair"' },
          { label: 'B', text: 'A driver who gets in an accident says, "The other driver was reckless," while a witness says, "That driver must be careless in general"' },
          { label: 'C', text: 'A person attributes their anxiety to feeling overwhelmed by external demands but attributes a colleague\'s anxiety to being "an anxious type"' },
          { label: 'D', text: 'An observer attributes a stranger\'s behavior to personal traits even when the behavior is externally constrained' },
        ],
        correctAnswer: 'A',
        explanation: 'Self-serving bias: attribute successes to internal causes (effort, ability) and failures to external causes (luck, situational factors). A demonstrates this: passing = internal (I studied) → success to self; failing = external (unfair exam) → failure to situation. A is correct. B describes the FAE/actor-observer bias (attributing another driver\'s behavior to disposition). C describes the actor-observer bias (self = situational, colleague = dispositional). D describes the FAE (dispositional attribution for externally constrained behavior).',
        wrongAnswerExplanations: {
          B: 'B describes the FAE (blaming the other driver\'s disposition for the accident) combined with actor-observer bias (the accident victim might use situational attribution for themselves). Not specifically the self-serving bias.',
          C: 'This is the actor-observer bias: attributing one\'s own anxiety to the situation and a colleague\'s anxiety to their disposition. Not self-serving bias (which is specifically about success vs. failure attribution).',
          D: 'D is a straightforward description of the FAE/correspondence bias. The self-serving bias specifically involves the asymmetry between success and failure attributions.',
        },
        teachingPoint: 'Self-serving bias: protects self-esteem. Success → internal (I am capable); failure → external (circumstances, luck, others). Note: depressed individuals show a "depressive realism" — they lack the self-serving bias and make more accurate (though less self-enhancing) attributions. Self-serving bias is adaptive for motivation but can impair learning from failure and damage relationships (always blaming others for conflict).',
        relatedTopics: ['self-serving bias', 'internal attribution success', 'external attribution failure', 'self-esteem protection', 'depressive realism'],
      },
      {
        id: 'mcat3-ps-018',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p3',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 8',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'Cognitive dissonance is strongest when:',
        choices: [
          { label: 'A', text: 'Behavior is externally coerced and the person has little sense of personal responsibility' },
          { label: 'B', text: 'Behavior is freely chosen and difficult to reverse, and the person feels personally responsible' },
          { label: 'C', text: 'The two inconsistent cognitions are about trivial, unimportant matters' },
          { label: 'D', text: 'The person is unaware of the inconsistency between their two cognitions' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage states: "Dissonance effects are strongest when behavior is freely chosen (no external justification) and is difficult to reverse." Personal responsibility and freedom of choice are necessary for dissonance. If behavior is externally coerced, the person can attribute it to external pressure (no dissonance). If easily reversible, the person can just stop. If the matter is trivial, the dissonance is minimal. If the person is unaware of the inconsistency, no aversive state arises. B correctly identifies the strongest conditions. A — external coercion reduces dissonance (external justification). C — trivial matters produce minimal dissonance. D — awareness is necessary for dissonance to occur.',
        wrongAnswerExplanations: {
          A: 'External coercion provides external justification, which reduces the need for attitude change and thus reduces dissonance. Dissonance is strongest when there is NO external justification — behavior seems freely chosen.',
          C: 'Dissonance is proportional to the importance of the cognitions. If the inconsistency is trivial (you believe apples are better than oranges but occasionally eat oranges), the aversive motivational state is minimal.',
          D: 'If the person is unaware of the inconsistency, they experience no aversive motivational state. Dissonance requires awareness of the inconsistency between cognitions.',
        },
        teachingPoint: 'Dissonance conditions: (1) free choice/personal responsibility; (2) aversive consequences (the behavior causes harm); (3) inability to reverse; (4) awareness of inconsistency. All conditions amplify dissonance. The New Look in dissonance research (Joel Cooper): aversive consequences are more important than mere inconsistency. Applied: commitment and consistency techniques use free choice to lock people into commitments.',
        relatedTopics: ['cognitive dissonance conditions', 'free choice', 'personal responsibility', 'external justification', 'dissonance theory'],
      },
    ],
  },

  // ─── P/S Passage 4: Developmental Psychology ─────────────────────────────────
  {
    id: 'f3-ps-p4',
    sectionId: 'psych-soc',
    title: 'Cognitive and Moral Development Across the Lifespan',
    passageText: `Jean Piaget proposed that children progress through four stages of cognitive development, each characterized by qualitatively distinct modes of thinking. During the sensorimotor stage (0–2 years), infants learn through sensory experience and motor action; object permanence (understanding that objects exist when out of sight) emerges around 8 months. The preoperational stage (2–7 years) is characterized by symbolic thought but egocentrism — difficulty taking another\'s perspective — and lack of conservation (the ability to recognize that quantity remains the same despite changes in appearance). Concrete operational (7–12 years) brings logical reasoning about concrete objects and conservation. Formal operational (12+ years) enables abstract reasoning and hypothetical-deductive thinking.

Lawrence Kohlberg extended developmental theory to moral reasoning, proposing three levels (each with two stages). Preconventional morality focuses on self-interest and avoidance of punishment (Stages 1–2). Conventional morality involves conformity to social norms and laws (Stages 3–4). Postconventional morality (Stages 5–6) involves reasoning from abstract ethical principles — social contract theory and universal ethical principles. Kohlberg\'s methodology used moral dilemmas (notably the Heinz dilemma) to assess the reasoning process, not the conclusion.

Erik Erikson proposed eight psychosocial stages, each involving a crisis resolved in either an adaptive or maladaptive way. Key stages: Trust vs. Mistrust (infancy), Autonomy vs. Shame (toddler), Initiative vs. Guilt (preschool), Industry vs. Inferiority (school age), Identity vs. Role Confusion (adolescence), Intimacy vs. Isolation (young adult), Generativity vs. Stagnation (middle adulthood), Integrity vs. Despair (late adulthood).`,
    figures: [],
    questions: [
      {
        id: 'mcat3-ps-019',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p4',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'A 4-year-old child pours water from a tall thin glass into a short wide glass and claims the short glass has "less water." This demonstrates:',
        choices: [
          { label: 'A', text: 'Object permanence — the child understands the water still exists' },
          { label: 'B', text: 'Conservation failure — the child cannot recognize that quantity remains the same despite change in appearance' },
          { label: 'C', text: 'Egocentrism — the child believes others also think the short glass has less water' },
          { label: 'D', text: 'Formal operational thinking — the child is reasoning abstractly about volume' },
        ],
        correctAnswer: 'B',
        explanation: 'Conservation: the ability to recognize that quantity remains unchanged despite changes in perceptual appearance. A 4-year-old in the preoperational stage lacks conservation. The tall glass looks like "more" because it is taller; the child does not yet understand that the amount of water is conserved when poured. B is correct. A — object permanence is understanding that objects exist when out of sight (a sensorimotor achievement, not about conservation). C — egocentrism is difficulty taking another\'s perspective (the inability to understand that others see things differently), not specifically about volume conservation. D — formal operational thinking involves abstract hypothetical reasoning (12+); a 4-year-old is preoperational.',
        wrongAnswerExplanations: {
          A: 'Object permanence is knowing that a hidden object still exists (emerging ~8 months, sensorimotor stage). Conservation is about quantity remaining the same through perceptual transformation.',
          C: 'Egocentrism is about perspective-taking (e.g., thinking others see what you see, or that everyone shares your desires). Conservation is specifically about understanding that quantity is invariant under transformation.',
          D: 'Formal operational thinking (abstract, hypothetical-deductive) appears at 12+ years. A 4-year-old is in the preoperational stage (2–7 years), characterized by symbolic thought and conservation failures.',
        },
        teachingPoint: 'Conservation tasks: classic Piaget experiments. Volume conservation: same water, different container shape → preoperational child says quantity changed. Number conservation: same number of coins, spread out → preoperational child says "more." Concrete operational children (7+) understand conservation. Classic criticism: Piaget may have underestimated children\'s abilities due to confusing task demands.',
        relatedTopics: ['conservation', 'preoperational stage', 'Piaget', 'perceptual appearance vs quantity', 'cognitive development'],
      },
      {
        id: 'mcat3-ps-020',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p4',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'Kohlberg\'s methodology for assessing moral development focused on:',
        choices: [
          { label: 'A', text: 'The correctness of the moral conclusion (e.g., whether the person decided Heinz should steal the drug)' },
          { label: 'B', text: 'The reasoning process and justifications given for a moral decision, not the conclusion itself' },
          { label: 'C', text: 'Measuring empathy and emotional responses to moral dilemmas' },
          { label: 'D', text: 'Tracking the development of obedience to authority across age groups' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage explicitly states: "Kohlberg\'s methodology used moral dilemmas to assess the reasoning process, not the conclusion." Whether Heinz should steal or not matters less than WHY the person thinks so — the reasoning reveals the stage of moral development. B is correct. A — the specific conclusion is not the criterion for stage assignment. C — Kohlberg\'s approach is cognitive-developmental, not emotional/empathy-based (Gilligan\'s critique of Kohlberg was partly that he ignored care ethics and emotional dimensions). D — obedience to authority is Milgram\'s focus, not Kohlberg\'s.',
        wrongAnswerExplanations: {
          A: 'Kohlberg explicitly used the reasoning to assess stage, not the conclusion. Someone can say "yes, Heinz should steal" for preconventional (fear of punishment if wife dies) or postconventional reasons (life is a universal right) — the answer is the same but the stage differs.',
          C: 'Kohlberg\'s approach was cognitive-developmental — focused on reasoning structures. Gilligan and care ethics researchers emphasized empathy and relationships as a separate moral dimension Kohlberg missed.',
          D: 'Obedience to authority is the subject of Milgram\'s studies (1963) on obedience under experimenter pressure to administer electric shocks. Kohlberg\'s focus is moral reasoning stage development.',
        },
        teachingPoint: 'Kohlberg\'s Heinz dilemma: Heinz\'s wife is dying; druggist charges $2000 for a $200 drug; Heinz cannot pay; should he steal it? Preconventional: "No — he\'ll get caught and punished" or "Yes — he needs his wife." Conventional: "No — stealing is against the law" or "Yes — a good husband would do this." Postconventional: "Yes — life > property rights; the drug should be accessible." KEY: the REASONING, not the answer.',
        relatedTopics: ['Kohlberg methodology', 'moral dilemma', 'reasoning process', 'Heinz dilemma', 'moral stage assessment'],
      },
      {
        id: 'mcat3-ps-021',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p4',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'According to Erikson, what is the central developmental crisis of adolescence, and what does successful resolution look like?',
        choices: [
          { label: 'A', text: 'Industry vs. Inferiority — successfully mastering academic and social skills, feeling competent' },
          { label: 'B', text: 'Identity vs. Role Confusion — successfully developing a coherent sense of personal identity, values, and direction' },
          { label: 'C', text: 'Intimacy vs. Isolation — successfully forming close, committed relationships with peers' },
          { label: 'D', text: 'Generativity vs. Stagnation — successfully contributing to the next generation through work or parenting' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage lists: "Identity vs. Role Confusion (adolescence)." Successful resolution produces a coherent sense of identity — who one is, what one values, what direction to pursue. Role confusion is the maladaptive outcome (uncertainty about identity, difficulty committing to roles or values). B is correct. A — Industry vs. Inferiority is school-age (middle childhood). C — Intimacy vs. Isolation is young adulthood. D — Generativity vs. Stagnation is middle adulthood.',
        wrongAnswerExplanations: {
          A: 'Industry vs. Inferiority corresponds to school age (roughly 6–12 years, Piaget\'s concrete operational stage). Success = feeling competent and productive. Failure = feelings of inadequacy.',
          C: 'Intimacy vs. Isolation is young adulthood (roughly 18–40). Success = forming close, committed relationships. Failure = isolation and loneliness.',
          D: 'Generativity vs. Stagnation is middle adulthood (roughly 40–65). Success = contributing to society, raising children, or mentoring. Failure = self-absorption and stagnation.',
        },
        teachingPoint: 'Erikson\'s eight stages: (1) Trust/Mistrust (0–18mo), (2) Autonomy/Shame (18mo–3y), (3) Initiative/Guilt (3–5y), (4) Industry/Inferiority (5–12y), (5) Identity/Role Confusion (12–20y), (6) Intimacy/Isolation (20–40y), (7) Generativity/Stagnation (40–65y), (8) Integrity/Despair (65+). Adolescent identity crisis (Stage 5): Marcia extended this with identity statuses (diffusion, foreclosure, moratorium, achievement).',
        relatedTopics: ['Erikson adolescence', 'Identity vs Role Confusion', 'psychosocial stages', 'identity development', 'Marcia identity statuses'],
      },
      {
        id: 'mcat3-ps-022',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p4',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'Carol Gilligan argued that Kohlberg\'s theory was biased against women because it ranked an ethic of care (emphasizing relationships and context) lower than an ethic of justice (emphasizing abstract rules and rights). If this critique is correct, which implication for Kohlberg\'s findings follows?',
        choices: [
          { label: 'A', text: 'Women actually have higher moral development than Kohlberg\'s scoring indicates because care reasoning is common in female respondents but undervalued by the justice-centric scoring' },
          { label: 'B', text: 'Kohlberg\'s studies show no gender differences because the moral dilemmas were designed to be gender-neutral' },
          { label: 'C', text: 'Kohlberg\'s scoring is correct because justice reasoning is the highest form of moral thought cross-culturally' },
          { label: 'D', text: 'Gilligan\'s critique implies that moral development does not exist and all moral reasoning is equivalent' },
        ],
        correctAnswer: 'A',
        explanation: 'Gilligan\'s critique: Kohlberg\'s scoring system ranks abstract, principled justice reasoning (typical of male respondents) as highest (Stage 6) while scoring relational, care-based reasoning (typical of female respondents) as lower (Stage 3 = "good boy/girl" orientation). If care reasoning is morally legitimate — not lower but different — then women who use care-based reasoning are being systematically underscored. A follows directly: their moral development is more advanced than Kohlberg\'s scoring indicates. B denies gender differences Gilligan documented. C endorses Kohlberg against Gilligan\'s critique. D reduces Gilligan\'s position to a denial of moral development, which is too extreme.',
        wrongAnswerExplanations: {
          B: 'Kohlberg\'s research DID find gender differences in scoring, which is exactly what prompted Gilligan\'s critique. Gilligan argued these differences reflected bias in the scoring system, not lower female moral development.',
          C: 'Gilligan\'s critique is precisely a challenge to the claim that justice reasoning is universally the highest. She argues care reasoning is a legitimate alternative moral framework, not an inferior stage.',
          D: 'Gilligan does not deny that moral development occurs or that some forms of reasoning are more sophisticated. She argues that the DIMENSION of moral development is not singular (not just justice) but also includes care/relationship orientation.',
        },
        teachingPoint: 'Gilligan\'s ethics of care: women\'s moral development emphasizes relationships, context, and responsibilities (care ethics) vs. Kohlberg\'s abstract universal rules (justice ethics). Neither is superior — they represent different moral orientations. Gilligan\'s "In a Different Voice" (1982) argues Kohlberg\'s all-male sample and justice-centric framework systematically undervalued care reasoning. Contemporary view: both orientations exist in both sexes; Kohlberg\'s stage scoring has been modified.',
        relatedTopics: ['Gilligan', 'ethics of care', 'Kohlberg gender bias', 'justice vs care', 'moral development critique'],
      },
      {
        id: 'mcat3-ps-023',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p4',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'Object permanence, which Piaget placed at approximately 8 months, refers to the infant\'s understanding that:',
        choices: [
          { label: 'A', text: 'Objects fall when dropped due to gravity' },
          { label: 'B', text: 'Objects continue to exist even when they cannot be seen, heard, or touched' },
          { label: 'C', text: 'Objects have permanent, unchanging properties like color and shape' },
          { label: 'D', text: 'The amount of substance remains constant despite changes in form' },
        ],
        correctAnswer: 'B',
        explanation: 'Object permanence: infants understand that objects continue to exist even when out of perceptual contact (hidden behind a screen, out of sight). Before 8 months (Piaget\'s estimate), infants behave as if a hidden object no longer exists — they don\'t search for it. B is correct. A — understanding gravity is a separate physical knowledge achievement. C — perceptual constancy (color, shape remain the same under different conditions) is a different concept. D — conservation of substance is a preoperational→concrete operational achievement, not object permanence.',
        wrongAnswerExplanations: {
          A: 'Understanding gravity is a physical knowledge achievement studied separately from object permanence. Infants develop naive physics understanding over the first year, but object permanence is specifically about existence during absence.',
          C: 'Perceptual constancy (color constancy, size constancy, shape constancy) is the understanding that objects\' properties don\'t change despite different sensory conditions. It is a different concept from object permanence.',
          D: 'Conservation (substance, number, volume, mass) is a concrete operational achievement. Object permanence is a sensorimotor achievement. Both involve understanding persistence, but they are distinct concepts at different developmental stages.',
        },
        teachingPoint: 'Object permanence: emerges ~8 months in Piaget\'s account (sooner per Baillargeon\'s violation-of-expectation studies). Classic evidence: hiding task — cover toy with cloth; before object permanence, infant stops reaching; after object permanence, infant searches under cloth. A-not-B error: infant searches at location A where object was previously found, even when they watch it hidden at location B.',
        relatedTopics: ['object permanence', 'sensorimotor stage', 'Piaget', 'infant cognition', 'A-not-B error'],
      },
      {
        id: 'mcat3-ps-024',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p4',
        questionType: 'passage',
        discipline: 'Psychology',
        contentCategory: 'Psychological science',
        foundationalConcept: 'FC 7',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'A teenager reasons: "Heinz should steal the drug because society needs flexible rules that respect the overriding value of human life above property." This reflects which level of Kohlberg\'s moral development?',
        choices: [
          { label: 'A', text: 'Preconventional (Stage 2) — seeking reward for doing what benefits oneself' },
          { label: 'B', text: 'Conventional (Stage 4) — upholding the law and social order' },
          { label: 'C', text: 'Postconventional (Stage 5) — reasoning from a social contract perspective that places higher-order values (human life) above specific rules' },
          { label: 'D', text: 'Conventional (Stage 3) — acting like a "good person" to earn approval' },
        ],
        correctAnswer: 'C',
        explanation: 'Reasoning about "society needing flexible rules" and placing the "value of human life above property" reflects postconventional, Stage 5 reasoning (social contract / individual rights). Stage 5 recognizes that laws are social contracts that should protect fundamental human rights — when they don\'t, there is justification to override them. C is correct. A — preconventional focuses on self-interest/punishment avoidance ("I\'ll get caught," "I need my wife"). B — Stage 4 (law and order) would say "stealing is against the law; breaking the law undermines social order." D — Stage 3 (good boy/girl) focuses on being a good husband, earning approval of close others.',
        wrongAnswerExplanations: {
          A: 'Preconventional reasoning: Stage 1 (obedience, punishment avoidance) or Stage 2 (instrumental exchange — "you scratch my back, I\'ll scratch yours"). Neither involves abstract social contract reasoning.',
          B: 'Conventional Stage 4 (law and order): "The law exists for a reason; if everyone stole when they felt justified, there would be chaos." This reasoning upholds the existing law, not challenges it with a higher principle.',
          D: 'Conventional Stage 3 (good interpersonal relationships): "Heinz should steal because a good husband does whatever it takes for his wife; he\'d be judged as uncaring if he didn\'t." Focuses on social relationships and approval, not abstract social contract principles.',
        },
        teachingPoint: 'Kohlberg Stage 5 (Social Contract): laws are social contracts designed to protect rights; they can be evaluated critically against higher principles (human dignity, life). Stage 6 (Universal Ethical Principles): even more abstract — following one\'s own internalized ethical principles (Rawlsian justice, Kantian duty) even when they conflict with law or social consensus. Few people reach Stage 6 consistently in Kohlberg\'s framework.',
        relatedTopics: ['postconventional morality', 'Stage 5 social contract', 'Kohlberg stages', 'moral reasoning application', 'Heinz dilemma stages'],
      },
    ],
  },

  // ─── P/S Passage 5: Social Stratification and Health Disparities ──────────────
  {
    id: 'f3-ps-p5',
    sectionId: 'psych-soc',
    title: 'Social Stratification, Health Disparities, and Social Determinants',
    passageText: `Social stratification refers to the hierarchical ranking of individuals and groups in society along dimensions of wealth, power, and prestige. Sociologists distinguish class (economic position), status (social honor/prestige), and party (political power) — Weber\'s three dimensions of stratification. In the United States, socioeconomic status (SES) is typically measured using income, education, and occupational prestige. Stratification systems range from closed (caste systems, feudalism — mobility determined by birth) to open (class societies — some mobility possible through achievement).

Health disparities refer to systematic, unjust differences in health outcomes and access to healthcare across social groups. Research consistently demonstrates that lower SES is associated with higher rates of chronic disease, infant mortality, mental illness, obesity, and shorter life expectancy. The social determinants of health (SDOH) — conditions in the environments where people live, learn, work, play, worship, and age — shape health outcomes at least as strongly as individual behaviors or genetic factors. Key SDOH include food security, housing stability, educational attainment, neighborhood safety, and environmental exposures.

The fundamental cause theory (Link and Phelan) proposes that SES is a "fundamental cause" of health inequalities because it provides access to flexible resources (money, knowledge, prestige, social connections) that protect health regardless of the current disease burden. As new medical discoveries emerge (statins, cancer screenings, new medications), higher-SES individuals adopt them first, maintaining or widening health disparities even as population-level health improves.`,
    figures: [],
    questions: [
      {
        id: 'mcat3-ps-025',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p5',
        questionType: 'passage',
        discipline: 'Sociology',
        contentCategory: 'Social sciences',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'Weber\'s three dimensions of stratification are:',
        choices: [
          { label: 'A', text: 'Income, education, and occupational prestige' },
          { label: 'B', text: 'Class (wealth), status (social honor), and party (political power)' },
          { label: 'C', text: 'Open systems, closed systems, and mixed systems of stratification' },
          { label: 'D', text: 'Bourgeoisie, proletariat, and petty bourgeoisie' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage explicitly states: "Weber\'s three dimensions of stratification — class (economic position), status (social honor/prestige), and party (political power)." B reproduces this. A — income, education, and occupational prestige are measures of SES (socioeconomic status), a related but different concept. C — open/closed systems describe types of stratification systems, not Weber\'s three dimensions. D — bourgeoisie, proletariat, and petty bourgeoisie are Marxist class categories (based on relation to means of production), distinct from Weber\'s three-dimensional model.',
        wrongAnswerExplanations: {
          A: 'Income, education, and occupational prestige are the components of SES as operationalized in social research. They overlap with Weber\'s dimensions but are not his theoretical three-part framework.',
          C: 'Open vs. closed stratification systems is a typology of how stratification operates (mobile vs. fixed), not Weber\'s three-dimensional analysis.',
          D: 'Marx\'s class analysis (bourgeoisie = capitalist class owning means of production; proletariat = working class selling labor) is a one-dimensional economic analysis. Weber explicitly critiqued Marx\'s reduction of stratification to economics and added status and party.',
        },
        teachingPoint: 'Weber vs. Marx on stratification: Marx = economic class only (one dimension). Weber = class (economy) + status (prestige) + party (power) = three separate, partially overlapping dimensions. Someone can have high status but low class (a poor but respected professor) or high class but low status (a wealthy criminal). This multidimensional analysis better captures social complexity.',
        relatedTopics: ['Weber stratification', 'class status party', 'social stratification dimensions', 'SES vs Weber'],
      },
      {
        id: 'mcat3-ps-026',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p5',
        questionType: 'passage',
        discipline: 'Sociology',
        contentCategory: 'Social sciences',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'The fundamental cause theory predicts that even as new medical treatments become available and population health improves, socioeconomic health disparities will:',
        choices: [
          { label: 'A', text: 'Narrow, because medical advances benefit all social groups equally' },
          { label: 'B', text: 'Disappear, because universal healthcare eliminates access barriers' },
          { label: 'C', text: 'Persist or widen, because higher-SES individuals preferentially adopt new health technologies, maintaining their advantage' },
          { label: 'D', text: 'Reverse, because lower-SES groups eventually catch up to higher-SES groups\' earlier health gains' },
        ],
        correctAnswer: 'C',
        explanation: 'The passage states: "As new medical discoveries emerge... higher-SES individuals adopt them first, maintaining or widening health disparities even as population-level health improves." Fundamental cause theory: SES provides flexible resources (money, knowledge, connections) that protect health through whatever mechanisms are available. When old mechanisms become obsolete (a disease is cured) or new ones emerge (statins), SES advantage is redirected to exploit the new mechanisms. Disparities persist because the fundamental advantage (SES) persists. C is correct. A assumes equal adoption — contradicted by the theory. B — even universal access may not eliminate knowledge and behavioral advantage of higher SES. D — reversal is not what the theory predicts.',
        wrongAnswerExplanations: {
          A: 'New medical technologies (cancer screenings, statins) are first adopted by higher-SES individuals who have greater health literacy, access, insurance coverage, and ability to navigate medical systems. Equal benefit is not the actual pattern.',
          B: 'Even with universal healthcare access, higher-SES individuals use health knowledge, comply better with preventive care, and navigate the system more effectively. Access alone does not eliminate SES-health gradients.',
          D: 'Lower-SES groups do eventually adopt technologies after higher-SES groups, but by that time, new technologies advantaging higher-SES groups have emerged. The gradient maintains or widens rather than reverses.',
        },
        teachingPoint: 'Fundamental cause theory (Link and Phelan, 1995): SES is a "fundamental cause" because it provides flexible resources (money, knowledge, prestige, social capital) that protect health via whatever mechanisms are currently available. When AIDS emerged, higher-SES individuals had better access to antiretrovirals; when cancer screening emerged, they were screened first. The mechanism changes but the SES advantage persists. Implications: only interventions that reduce SES inequalities themselves (not just individual risk factors) can permanently reduce health disparities.',
        relatedTopics: ['fundamental cause theory', 'health disparities persistence', 'SES and health', 'Link and Phelan', 'flexible resources'],
      },
      {
        id: 'mcat3-ps-027',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p5',
        questionType: 'passage',
        discipline: 'Sociology',
        contentCategory: 'Social sciences',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'A caste system is an example of a _______ stratification system because:',
        choices: [
          { label: 'A', text: 'Open; mobility is determined by individual achievement and merit' },
          { label: 'B', text: 'Closed; social position is ascribed at birth and mobility is extremely limited' },
          { label: 'C', text: 'Mixed; caste determines birth status but education can change one\'s position' },
          { label: 'D', text: 'Class-based; economic factors determine caste membership' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage distinguishes closed systems (caste, feudalism — "mobility determined by birth") from open systems (class societies). A caste system is closed: one is born into a caste and remains in it regardless of individual achievement. B is correct. A describes open (class) systems. C — caste systems are highly resistant to education-based mobility (though modernization has somewhat modified this in some contexts). D — caste is not primarily economic class; it is based on hereditary status, ritual purity, and birth group.',
        wrongAnswerExplanations: {
          A: 'Open stratification systems (like U.S. class system) allow for some mobility based on achievement. Caste systems are specifically described as closed — birth determines position.',
          C: 'Traditional caste systems are specifically closed — education does not typically change caste membership. While modern societies with historical caste systems (India) have formal anti-discrimination laws, caste discrimination persists and the system remains primarily ascriptive.',
          D: 'Caste is based on birth, hereditary group membership, and often ritual status — not primarily economic factors. While caste and class are correlated in practice, caste is analytically distinct from economic class position.',
        },
        teachingPoint: 'Stratification types: Closed (estates/feudalism, caste): ascribed status, birth-determined, low mobility. Open (class systems): achieved status possible, some mobility through education/work, but structural barriers persist. Ascribed vs. achieved status: ascribed = assigned at birth (race, caste, sex); achieved = earned through effort (education, occupation). Both are present in all societies; the relative weight differs.',
        relatedTopics: ['caste system', 'closed stratification', 'ascribed status', 'social mobility', 'open vs closed systems'],
      },
      {
        id: 'mcat3-ps-028',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p5',
        questionType: 'passage',
        discipline: 'Sociology',
        contentCategory: 'Social sciences',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 4',
        difficulty: 'hard',
        question: 'A public health researcher finds that lower-income neighborhoods have higher rates of asthma than higher-income neighborhoods, even after controlling for individual smoking behavior. Which social determinant of health most directly explains this finding?',
        choices: [
          { label: 'A', text: 'Lower-income individuals have poorer diet, which weakens immune function and increases asthma susceptibility' },
          { label: 'B', text: 'Lower-income neighborhoods are more likely to be located near industrial facilities, highways, and pollution sources, increasing exposure to airborne irritants' },
          { label: 'C', text: 'Lower-income individuals experience more psychological stress, which directly causes asthma through cortisol dysregulation' },
          { label: 'D', text: 'Lower-income neighborhoods have fewer hospitals, reducing access to asthma treatment' },
        ],
        correctAnswer: 'B',
        explanation: 'After controlling for individual smoking, the remaining disparity reflects environmental determinants at the neighborhood level. Environmental exposures (industrial pollution, diesel exhaust from highways) are classic SDOH — and lower-income neighborhoods are disproportionately located near pollution sources (environmental justice issue). These exposures directly increase asthma rates. B correctly identifies the most direct neighborhood-level SDOH for asthma disparities. A — diet and immune function may contribute, but the question asks what most directly explains neighborhood-level asthma disparities after smoking is controlled. C — stress → asthma through cortisol dysregulation is a biopsychosocial pathway but less direct than physical exposure. D — treatment access affects asthma control/severity but less directly explains asthma prevalence rates.',
        wrongAnswerExplanations: {
          A: 'Diet and immune function is a pathway, but it is a more distal cause. The question asks for the most DIRECT social determinant — environmental pollution exposure is more immediate than diet-immune pathway for asthma specifically.',
          C: 'Psychosocial stress → HPA axis dysregulation → immune dysregulation → asthma is a documented pathway, but it is indirect. Environmental pollution is a more direct and proximate cause of asthma.',
          D: 'Reduced hospital access would explain worse outcomes (more hospitalizations, deaths) once asthma develops, but would not directly explain higher PREVALENCE (incidence) of asthma in the neighborhood.',
        },
        teachingPoint: 'Environmental justice: lower-SES neighborhoods are disproportionately located near industrial facilities, waste sites, and highways (historical redlining and discriminatory zoning). Diesel exhaust particulates, ozone, nitrogen oxides → asthma, COPD, cardiovascular disease. This is a neighborhood-level SDOH, distinct from individual behavioral factors. Controlling for individual smoking isolates the neighborhood environmental exposure effect.',
        relatedTopics: ['environmental justice', 'social determinants of health', 'asthma disparities', 'pollution exposure', 'neighborhood effects'],
      },
      {
        id: 'mcat3-ps-029',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p5',
        questionType: 'passage',
        discipline: 'Sociology',
        contentCategory: 'Social sciences',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 2',
        difficulty: 'medium',
        question: 'The social gradient in health refers to:',
        choices: [
          { label: 'A', text: 'A threshold effect — only those below the poverty line show worse health' },
          { label: 'B', text: 'A continuous stepwise relationship — each step up the socioeconomic ladder is associated with better health, even among those well above poverty' },
          { label: 'C', text: 'A ceiling effect — health disparities disappear above a moderate income level' },
          { label: 'D', text: 'The fact that income determines health only through healthcare access' },
        ],
        correctAnswer: 'B',
        explanation: 'The social gradient in health (Marmot\'s Whitehall studies of British civil servants) is a graded, continuous relationship: not a threshold at poverty, but a stepwise improvement in health at each level of the socioeconomic hierarchy. Even senior civil servants (well above poverty) had worse health than the top administrators. B describes this graded relationship. A — a threshold model suggests only the poor have worse health; the gradient shows disparities extend throughout the social hierarchy. C — a ceiling effect would mean rich people\'s health is no better than middle-class people\'s; the gradient is continuous, not capped. D — healthcare access is one pathway but not the only one (stress, autonomy, social status effects on biology are also documented).',
        wrongAnswerExplanations: {
          A: 'A threshold model suggests health disparities are limited to those below the poverty line. The social gradient (Whitehall studies) shows disparities persist at every level of the hierarchy — not just at the poverty threshold.',
          C: 'No ceiling effect is observed in the gradient — those at higher SES have better health than those immediately below them, even at upper-middle and upper class levels.',
          D: 'Healthcare access is ONE pathway between SES and health, but not the only one. The Whitehall studies showed health gradients in a country with universal healthcare (UK), implicating non-access pathways: autonomy, job control, chronic stress from lower social rank, health behaviors.',
        },
        teachingPoint: 'Marmot\'s Whitehall studies: British civil servants in a guaranteed employment setting. Health gradient found at EVERY level — even comparing adjacent job grades. Not explained by absolute poverty or healthcare access (UK has NHS). Proposed mechanisms: job control (autonomy) → stress response; social rank and status → allostatic load. The gradient is about RELATIVE position, not absolute deprivation. Policy implication: reducing health disparities requires addressing the entire social hierarchy, not just poverty relief.',
        relatedTopics: ['social gradient in health', 'Marmot Whitehall', 'continuous SES-health relationship', 'job control', 'allostatic load'],
      },
      {
        id: 'mcat3-ps-030',
        sectionId: 'psych-soc',
        passageId: 'f3-ps-p5',
        questionType: 'passage',
        discipline: 'Sociology',
        contentCategory: 'Social sciences',
        foundationalConcept: 'FC 9',
        scientificSkill: 'Skill 1',
        difficulty: 'easy',
        question: 'Socioeconomic status (SES) is typically measured using which three indicators?',
        choices: [
          { label: 'A', text: 'Age, gender, and race' },
          { label: 'B', text: 'Income, education, and occupational prestige' },
          { label: 'C', text: 'Class, status, and party (political power)' },
          { label: 'D', text: 'Body mass index, exercise frequency, and diet quality' },
        ],
        correctAnswer: 'B',
        explanation: 'The passage states: "SES is typically measured using income, education, and occupational prestige." B reproduces this. A — age, gender, and race are demographic variables that may correlate with SES but are not components of SES itself. C — class, status, and party are Weber\'s three stratification dimensions; they are theoretical constructs, not standard operational measures of SES. D — BMI, exercise, and diet are health behaviors that may be associated with SES but are not measures of SES.',
        wrongAnswerExplanations: {
          A: 'Age, gender, and race are demographic characteristics. While they correlate with SES (and moderate SES-health relationships), they are not components of SES itself.',
          C: 'Class, status, and party are Weber\'s three theoretical dimensions of stratification. SES (as an empirical measure) operationalizes class-related dimensions using income, education, and occupation — it overlaps with but is not identical to Weber\'s three-part framework.',
          D: 'Health behaviors (BMI, diet, exercise) are outcomes that may be influenced by SES, not components of SES itself. Measuring SES by these would conflate the cause with the effect.',
        },
        teachingPoint: 'SES components: income (economic resources), education (human capital and health literacy), occupational prestige (status and working conditions). These three indicators are correlated but not perfectly — each independently predicts health outcomes. Education may be most influential for health literacy and access to information; income for material resources; occupation for workplace exposures and autonomy. Composite SES measures combine all three.',
        relatedTopics: ['SES measurement', 'income education occupation', 'socioeconomic status indicators', 'health and SES'],
      },
    ],
  },
]
